// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefixes=CHECK-RV64,CHECK-RV64-OGCG %s
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-llvm -fclangir %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s %}
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-cir -fclangir %s -o - | \
// RUN:   FileCheck --check-prefix=CIR %s %}

#include <riscv_vector.h>

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8mf8(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !u64i) -> !cir.vector<[1] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vv_i8mf8
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[OP1:%.*]], <vscale x 1 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], <vscale x 1 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vmul_vv_i8mf8(vint8mf8_t op1, vint8mf8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8mf8(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !s8i, !u64i) -> !cir.vector<[1] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vx_i8mf8
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.nxv1i8.i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vmul_vx_i8mf8(vint8mf8_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8mf4(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !u64i) -> !cir.vector<[2] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vv_i8mf4
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[OP1:%.*]], <vscale x 2 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], <vscale x 2 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vmul_vv_i8mf4(vint8mf4_t op1, vint8mf4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8mf4(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !s8i, !u64i) -> !cir.vector<[2] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vx_i8mf4
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vmul_vx_i8mf4(vint8mf4_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8mf2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !u64i) -> !cir.vector<[4] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vv_i8mf2
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[OP1:%.*]], <vscale x 4 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], <vscale x 4 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vmul_vv_i8mf2(vint8mf2_t op1, vint8mf2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8mf2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !s8i, !u64i) -> !cir.vector<[4] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vx_i8mf2
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.nxv4i8.i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vmul_vx_i8mf2(vint8mf2_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m1(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vv_i8m1
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[OP1:%.*]], <vscale x 8 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], <vscale x 8 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vmul_vv_i8m1(vint8m1_t op1, vint8m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m1(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !s8i, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vx_i8m1
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.nxv8i8.i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vmul_vx_i8m1(vint8m1_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m2(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !u64i) -> !cir.vector<[16] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vv_i8m2
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[OP1:%.*]], <vscale x 16 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], <vscale x 16 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vmul_vv_i8m2(vint8m2_t op1, vint8m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m2(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !s8i, !u64i) -> !cir.vector<[16] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vx_i8m2
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.nxv16i8.i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vmul_vx_i8m2(vint8m2_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m4(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !u64i) -> !cir.vector<[32] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vv_i8m4
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[OP1:%.*]], <vscale x 32 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], <vscale x 32 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vmul_vv_i8m4(vint8m4_t op1, vint8m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m4(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !s8i, !u64i) -> !cir.vector<[32] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vx_i8m4
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.nxv32i8.i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vmul_vx_i8m4(vint8m4_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m8(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !u64i) -> !cir.vector<[64] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vv_i8m8
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[OP1:%.*]], <vscale x 64 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], <vscale x 64 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vmul_vv_i8m8(vint8m8_t op1, vint8m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m8(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !s8i, !u64i) -> !cir.vector<[64] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vx_i8m8
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.nxv64i8.i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vmul_vx_i8m8(vint8m8_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16mf4(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !u64i) -> !cir.vector<[1] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vv_i16mf4
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[OP1:%.*]], <vscale x 1 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], <vscale x 1 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vmul_vv_i16mf4(vint16mf4_t op1, vint16mf4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16mf4(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !s16i, !u64i) -> !cir.vector<[1] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vx_i16mf4
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vmul_vx_i16mf4(vint16mf4_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16mf2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !u64i) -> !cir.vector<[2] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vv_i16mf2
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[OP1:%.*]], <vscale x 2 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], <vscale x 2 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vmul_vv_i16mf2(vint16mf2_t op1, vint16mf2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16mf2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !s16i, !u64i) -> !cir.vector<[2] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vx_i16mf2
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vmul_vx_i16mf2(vint16mf2_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m1(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vv_i16m1
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[OP1:%.*]], <vscale x 4 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], <vscale x 4 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vmul_vv_i16m1(vint16m1_t op1, vint16m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m1(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !s16i, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vx_i16m1
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.nxv4i16.i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vmul_vx_i16m1(vint16m1_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m2(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !u64i) -> !cir.vector<[8] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vv_i16m2
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[OP1:%.*]], <vscale x 8 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], <vscale x 8 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vmul_vv_i16m2(vint16m2_t op1, vint16m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m2(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !s16i, !u64i) -> !cir.vector<[8] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vx_i16m2
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.nxv8i16.i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vmul_vx_i16m2(vint16m2_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m4(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !u64i) -> !cir.vector<[16] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vv_i16m4
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[OP1:%.*]], <vscale x 16 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], <vscale x 16 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vmul_vv_i16m4(vint16m4_t op1, vint16m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m4(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !s16i, !u64i) -> !cir.vector<[16] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vx_i16m4
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.nxv16i16.i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vmul_vx_i16m4(vint16m4_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m8(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !u64i) -> !cir.vector<[32] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vv_i16m8
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[OP1:%.*]], <vscale x 32 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], <vscale x 32 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vmul_vv_i16m8(vint16m8_t op1, vint16m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m8(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !s16i, !u64i) -> !cir.vector<[32] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vx_i16m8
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.nxv32i16.i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vmul_vx_i16m8(vint16m8_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32mf2(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !u64i) -> !cir.vector<[1] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vv_i32mf2
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[OP1:%.*]], <vscale x 1 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], <vscale x 1 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vmul_vv_i32mf2(vint32mf2_t op1, vint32mf2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32mf2(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !s32i, !u64i) -> !cir.vector<[1] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vx_i32mf2
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.nxv1i32.i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vmul_vx_i32mf2(vint32mf2_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m1(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vv_i32m1
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[OP1:%.*]], <vscale x 2 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], <vscale x 2 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vmul_vv_i32m1(vint32m1_t op1, vint32m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m1(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !s32i, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vx_i32m1
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.nxv2i32.i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vmul_vx_i32m1(vint32m1_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !u64i) -> !cir.vector<[4] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vv_i32m2
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], <vscale x 4 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vmul_vv_i32m2(vint32m2_t op1, vint32m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !s32i, !u64i) -> !cir.vector<[4] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vx_i32m2
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vmul_vx_i32m2(vint32m2_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m4(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !u64i) -> !cir.vector<[8] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vv_i32m4
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[OP1:%.*]], <vscale x 8 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], <vscale x 8 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vmul_vv_i32m4(vint32m4_t op1, vint32m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m4(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !s32i, !u64i) -> !cir.vector<[8] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vx_i32m4
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.nxv8i32.i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vmul_vx_i32m4(vint32m4_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m8(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !u64i) -> !cir.vector<[16] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vv_i32m8
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[OP1:%.*]], <vscale x 16 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], <vscale x 16 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vmul_vv_i32m8(vint32m8_t op1, vint32m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m8(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !s32i, !u64i) -> !cir.vector<[16] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vx_i32m8
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.nxv16i32.i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vmul_vx_i32m8(vint32m8_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m1(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vv_i64m1
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[OP1:%.*]], <vscale x 1 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], <vscale x 1 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vmul_vv_i64m1(vint64m1_t op1, vint64m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m1(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !s64i, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vx_i64m1
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.nxv1i64.i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vmul_vx_i64m1(vint64m1_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !u64i) -> !cir.vector<[2] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vv_i64m2
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[OP1:%.*]], <vscale x 2 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], <vscale x 2 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vmul_vv_i64m2(vint64m2_t op1, vint64m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !s64i, !u64i) -> !cir.vector<[2] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vx_i64m2
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.nxv2i64.i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vmul_vx_i64m2(vint64m2_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m4(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !u64i) -> !cir.vector<[4] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vv_i64m4
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[OP1:%.*]], <vscale x 4 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], <vscale x 4 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vmul_vv_i64m4(vint64m4_t op1, vint64m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m4(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !s64i, !u64i) -> !cir.vector<[4] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vx_i64m4
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.nxv4i64.i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vmul_vx_i64m4(vint64m4_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m8(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !u64i) -> !cir.vector<[8] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vv_i64m8
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[OP1:%.*]], <vscale x 8 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], <vscale x 8 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vmul_vv_i64m8(vint64m8_t op1, vint64m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m8(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !s64i, !u64i) -> !cir.vector<[8] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vx_i64m8
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.nxv8i64.i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vmul_vx_i64m8(vint64m8_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8mf8(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !u64i) -> !cir.vector<[1] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vv_u8mf8
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[OP1:%.*]], <vscale x 1 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], <vscale x 1 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vmul_vv_u8mf8(vuint8mf8_t op1, vuint8mf8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8mf8(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !u8i, !u64i) -> !cir.vector<[1] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vx_u8mf8
// CHECK-RV64-SAME: (<vscale x 1 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.nxv1i8.i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vmul_vx_u8mf8(vuint8mf8_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8mf4(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !u64i) -> !cir.vector<[2] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vv_u8mf4
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[OP1:%.*]], <vscale x 2 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], <vscale x 2 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vmul_vv_u8mf4(vuint8mf4_t op1, vuint8mf4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8mf4(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !u8i, !u64i) -> !cir.vector<[2] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vx_u8mf4
// CHECK-RV64-SAME: (<vscale x 2 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.nxv2i8.i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vmul_vx_u8mf4(vuint8mf4_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8mf2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !u64i) -> !cir.vector<[4] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vv_u8mf2
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[OP1:%.*]], <vscale x 4 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], <vscale x 4 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vmul_vv_u8mf2(vuint8mf2_t op1, vuint8mf2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8mf2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !u8i, !u64i) -> !cir.vector<[4] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vx_u8mf2
// CHECK-RV64-SAME: (<vscale x 4 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.nxv4i8.i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vmul_vx_u8mf2(vuint8mf2_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m1(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vv_u8m1
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[OP1:%.*]], <vscale x 8 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], <vscale x 8 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vmul_vv_u8m1(vuint8m1_t op1, vuint8m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m1(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !u8i, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vx_u8m1
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.nxv8i8.i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vmul_vx_u8m1(vuint8m1_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m2(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !u64i) -> !cir.vector<[16] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vv_u8m2
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[OP1:%.*]], <vscale x 16 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], <vscale x 16 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vmul_vv_u8m2(vuint8m2_t op1, vuint8m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m2(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !u8i, !u64i) -> !cir.vector<[16] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vx_u8m2
// CHECK-RV64-SAME: (<vscale x 16 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.nxv16i8.i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vmul_vx_u8m2(vuint8m2_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m4(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !u64i) -> !cir.vector<[32] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vv_u8m4
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[OP1:%.*]], <vscale x 32 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], <vscale x 32 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vmul_vv_u8m4(vuint8m4_t op1, vuint8m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m4(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !u8i, !u64i) -> !cir.vector<[32] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vx_u8m4
// CHECK-RV64-SAME: (<vscale x 32 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.nxv32i8.i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vmul_vx_u8m4(vuint8m4_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m8(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !u64i) -> !cir.vector<[64] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vv_u8m8
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[OP1:%.*]], <vscale x 64 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], <vscale x 64 x i8> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vmul_vv_u8m8(vuint8m8_t op1, vuint8m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m8(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !u8i, !u64i) -> !cir.vector<[64] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vx_u8m8
// CHECK-RV64-SAME: (<vscale x 64 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.nxv64i8.i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], i8 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vmul_vx_u8m8(vuint8m8_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16mf4(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !u64i) -> !cir.vector<[1] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vv_u16mf4
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[OP1:%.*]], <vscale x 1 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], <vscale x 1 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vmul_vv_u16mf4(vuint16mf4_t op1, vuint16mf4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16mf4(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !u16i, !u64i) -> !cir.vector<[1] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vx_u16mf4
// CHECK-RV64-SAME: (<vscale x 1 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.nxv1i16.i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vmul_vx_u16mf4(vuint16mf4_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16mf2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !u64i) -> !cir.vector<[2] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vv_u16mf2
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[OP1:%.*]], <vscale x 2 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], <vscale x 2 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vmul_vv_u16mf2(vuint16mf2_t op1, vuint16mf2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16mf2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !u16i, !u64i) -> !cir.vector<[2] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vx_u16mf2
// CHECK-RV64-SAME: (<vscale x 2 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vmul_vx_u16mf2(vuint16mf2_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m1(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vv_u16m1
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[OP1:%.*]], <vscale x 4 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], <vscale x 4 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vmul_vv_u16m1(vuint16m1_t op1, vuint16m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m1(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !u16i, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vx_u16m1
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.nxv4i16.i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vmul_vx_u16m1(vuint16m1_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m2(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !u64i) -> !cir.vector<[8] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vv_u16m2
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[OP1:%.*]], <vscale x 8 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], <vscale x 8 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vmul_vv_u16m2(vuint16m2_t op1, vuint16m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m2(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !u16i, !u64i) -> !cir.vector<[8] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vx_u16m2
// CHECK-RV64-SAME: (<vscale x 8 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.nxv8i16.i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vmul_vx_u16m2(vuint16m2_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m4(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !u64i) -> !cir.vector<[16] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vv_u16m4
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[OP1:%.*]], <vscale x 16 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], <vscale x 16 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vmul_vv_u16m4(vuint16m4_t op1, vuint16m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m4(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !u16i, !u64i) -> !cir.vector<[16] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vx_u16m4
// CHECK-RV64-SAME: (<vscale x 16 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.nxv16i16.i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vmul_vx_u16m4(vuint16m4_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m8(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !u64i) -> !cir.vector<[32] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vv_u16m8
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[OP1:%.*]], <vscale x 32 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], <vscale x 32 x i16> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vmul_vv_u16m8(vuint16m8_t op1, vuint16m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m8(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !u16i, !u64i) -> !cir.vector<[32] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vx_u16m8
// CHECK-RV64-SAME: (<vscale x 32 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.nxv32i16.i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], i16 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vmul_vx_u16m8(vuint16m8_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32mf2(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !u64i) -> !cir.vector<[1] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vv_u32mf2
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[OP1:%.*]], <vscale x 1 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], <vscale x 1 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vmul_vv_u32mf2(vuint32mf2_t op1, vuint32mf2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32mf2(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !u32i, !u64i) -> !cir.vector<[1] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vx_u32mf2
// CHECK-RV64-SAME: (<vscale x 1 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.nxv1i32.i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vmul_vx_u32mf2(vuint32mf2_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m1(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vv_u32m1
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[OP1:%.*]], <vscale x 2 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], <vscale x 2 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vmul_vv_u32m1(vuint32m1_t op1, vuint32m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m1(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !u32i, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vx_u32m1
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.nxv2i32.i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vmul_vx_u32m1(vuint32m1_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !u64i) -> !cir.vector<[4] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vv_u32m2
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], <vscale x 4 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vmul_vv_u32m2(vuint32m2_t op1, vuint32m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m2(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !u32i, !u64i) -> !cir.vector<[4] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vx_u32m2
// CHECK-RV64-SAME: (<vscale x 4 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.nxv4i32.i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vmul_vx_u32m2(vuint32m2_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m4(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !u64i) -> !cir.vector<[8] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vv_u32m4
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[OP1:%.*]], <vscale x 8 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], <vscale x 8 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vmul_vv_u32m4(vuint32m4_t op1, vuint32m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m4(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !u32i, !u64i) -> !cir.vector<[8] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vx_u32m4
// CHECK-RV64-SAME: (<vscale x 8 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.nxv8i32.i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vmul_vx_u32m4(vuint32m4_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m8(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !u64i) -> !cir.vector<[16] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vv_u32m8
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[OP1:%.*]], <vscale x 16 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], <vscale x 16 x i32> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vmul_vv_u32m8(vuint32m8_t op1, vuint32m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m8(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !u32i, !u64i) -> !cir.vector<[16] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vx_u32m8
// CHECK-RV64-SAME: (<vscale x 16 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.nxv16i32.i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], i32 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vmul_vx_u32m8(vuint32m8_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m1(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vv_u64m1
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[OP1:%.*]], <vscale x 1 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], <vscale x 1 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vmul_vv_u64m1(vuint64m1_t op1, vuint64m1_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m1(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !u64i, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vx_u64m1
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.nxv1i64.i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vmul_vx_u64m1(vuint64m1_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !u64i) -> !cir.vector<[2] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vv_u64m2
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[OP1:%.*]], <vscale x 2 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], <vscale x 2 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vmul_vv_u64m2(vuint64m2_t op1, vuint64m2_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m2(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !u64i, !u64i) -> !cir.vector<[2] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vx_u64m2
// CHECK-RV64-SAME: (<vscale x 2 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.nxv2i64.i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vmul_vx_u64m2(vuint64m2_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m4(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !u64i) -> !cir.vector<[4] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vv_u64m4
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[OP1:%.*]], <vscale x 4 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], <vscale x 4 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vmul_vv_u64m4(vuint64m4_t op1, vuint64m4_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m4(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !u64i, !u64i) -> !cir.vector<[4] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vx_u64m4
// CHECK-RV64-SAME: (<vscale x 4 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.nxv4i64.i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vmul_vx_u64m4(vuint64m4_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m8(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !u64i) -> !cir.vector<[8] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vv_u64m8
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[OP1:%.*]], <vscale x 8 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], <vscale x 8 x i64> [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vmul_vv_u64m8(vuint64m8_t op1, vuint64m8_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m8(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul" {{%.*}} : (!cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !u64i, !u64i) -> !cir.vector<[8] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vx_u64m8
// CHECK-RV64-SAME: (<vscale x 8 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.nxv8i64.i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], i64 [[OP2]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vmul_vx_u64m8(vuint64m8_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8mf8_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vv_i8mf8_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i8> [[OP1:%.*]], <vscale x 1 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.mask.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], <vscale x 1 x i8> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vmul_vv_i8mf8_m(vbool64_t mask, vint8mf8_t op1, vint8mf8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8mf8_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s8i>, !cir.vector<[1] x !s8i>, !s8i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vx_i8mf8_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.mask.nxv1i8.i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], i8 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vint8mf8_t test_vmul_vx_i8mf8_m(vbool64_t mask, vint8mf8_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8mf4_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vv_i8mf4_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i8> [[OP1:%.*]], <vscale x 2 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.mask.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], <vscale x 2 x i8> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vmul_vv_i8mf4_m(vbool32_t mask, vint8mf4_t op1, vint8mf4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8mf4_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s8i>, !cir.vector<[2] x !s8i>, !s8i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vx_i8mf4_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.mask.nxv2i8.i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], i8 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vint8mf4_t test_vmul_vx_i8mf4_m(vbool32_t mask, vint8mf4_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8mf2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vv_i8mf2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i8> [[OP1:%.*]], <vscale x 4 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.mask.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], <vscale x 4 x i8> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vmul_vv_i8mf2_m(vbool16_t mask, vint8mf2_t op1, vint8mf2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8mf2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s8i>, !cir.vector<[4] x !s8i>, !s8i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vx_i8mf2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.mask.nxv4i8.i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], i8 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vint8mf2_t test_vmul_vx_i8mf2_m(vbool16_t mask, vint8mf2_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m1_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vv_i8m1_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[OP1:%.*]], <vscale x 8 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], <vscale x 8 x i8> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vmul_vv_i8m1_m(vbool8_t mask, vint8m1_t op1, vint8m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m1_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !s8i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vx_i8m1_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.mask.nxv8i8.i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], i8 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vmul_vx_i8m1_m(vbool8_t mask, vint8m1_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m2_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vv_i8m2_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i8> [[OP1:%.*]], <vscale x 16 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.mask.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], <vscale x 16 x i8> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vmul_vv_i8m2_m(vbool4_t mask, vint8m2_t op1, vint8m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m2_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !s8i>, !cir.vector<[16] x !s8i>, !s8i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vx_i8m2_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.mask.nxv16i8.i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], i8 [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vint8m2_t test_vmul_vx_i8m2_m(vbool4_t mask, vint8m2_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m4_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vv_i8m4_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i8> [[OP1:%.*]], <vscale x 32 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.mask.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], <vscale x 32 x i8> [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vmul_vv_i8m4_m(vbool2_t mask, vint8m4_t op1, vint8m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m4_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !s8i>, !cir.vector<[32] x !s8i>, !s8i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vx_i8m4_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.mask.nxv32i8.i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], i8 [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vint8m4_t test_vmul_vx_i8m4_m(vbool2_t mask, vint8m4_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i8m8_m(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !cir.vector<[64] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[64] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vv_i8m8_m
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], <vscale x 64 x i8> [[OP1:%.*]], <vscale x 64 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.mask.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], <vscale x 64 x i8> [[OP2]], <vscale x 64 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vmul_vv_i8m8_m(vbool1_t mask, vint8m8_t op1, vint8m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i8m8_m(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[64] x !s8i>, !cir.vector<[64] x !s8i>, !s8i, !cir.vector<[64] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[64] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vx_i8m8_m
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], <vscale x 64 x i8> [[OP1:%.*]], i8 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.mask.nxv64i8.i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], i8 [[OP2]], <vscale x 64 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vint8m8_t test_vmul_vx_i8m8_m(vbool1_t mask, vint8m8_t op1, int8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16mf4_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vv_i16mf4_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i16> [[OP1:%.*]], <vscale x 1 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.mask.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], <vscale x 1 x i16> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vmul_vv_i16mf4_m(vbool64_t mask, vint16mf4_t op1, vint16mf4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16mf4_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s16i>, !cir.vector<[1] x !s16i>, !s16i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vx_i16mf4_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.mask.nxv1i16.i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], i16 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vint16mf4_t test_vmul_vx_i16mf4_m(vbool64_t mask, vint16mf4_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16mf2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vv_i16mf2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i16> [[OP1:%.*]], <vscale x 2 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.mask.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], <vscale x 2 x i16> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vmul_vv_i16mf2_m(vbool32_t mask, vint16mf2_t op1, vint16mf2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16mf2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s16i>, !cir.vector<[2] x !s16i>, !s16i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vx_i16mf2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.mask.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], i16 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vint16mf2_t test_vmul_vx_i16mf2_m(vbool32_t mask, vint16mf2_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m1_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vv_i16m1_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[OP1:%.*]], <vscale x 4 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], <vscale x 4 x i16> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vmul_vv_i16m1_m(vbool16_t mask, vint16m1_t op1, vint16m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m1_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !s16i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vx_i16m1_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.mask.nxv4i16.i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], i16 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vmul_vx_i16m1_m(vbool16_t mask, vint16m1_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m2_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vv_i16m2_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i16> [[OP1:%.*]], <vscale x 8 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.mask.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], <vscale x 8 x i16> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vmul_vv_i16m2_m(vbool8_t mask, vint16m2_t op1, vint16m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m2_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s16i>, !cir.vector<[8] x !s16i>, !s16i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vx_i16m2_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.mask.nxv8i16.i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], i16 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vint16m2_t test_vmul_vx_i16m2_m(vbool8_t mask, vint16m2_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m4_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vv_i16m4_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i16> [[OP1:%.*]], <vscale x 16 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.mask.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], <vscale x 16 x i16> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vmul_vv_i16m4_m(vbool4_t mask, vint16m4_t op1, vint16m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m4_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !s16i>, !cir.vector<[16] x !s16i>, !s16i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vx_i16m4_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.mask.nxv16i16.i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], i16 [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vint16m4_t test_vmul_vx_i16m4_m(vbool4_t mask, vint16m4_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i16m8_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vv_i16m8_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i16> [[OP1:%.*]], <vscale x 32 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.mask.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], <vscale x 32 x i16> [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vmul_vv_i16m8_m(vbool2_t mask, vint16m8_t op1, vint16m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i16m8_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !s16i>, !cir.vector<[32] x !s16i>, !s16i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vx_i16m8_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i16> [[OP1:%.*]], i16 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.mask.nxv32i16.i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], i16 [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vint16m8_t test_vmul_vx_i16m8_m(vbool2_t mask, vint16m8_t op1, int16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32mf2_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vv_i32mf2_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i32> [[OP1:%.*]], <vscale x 1 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.mask.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], <vscale x 1 x i32> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vmul_vv_i32mf2_m(vbool64_t mask, vint32mf2_t op1, vint32mf2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32mf2_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s32i>, !cir.vector<[1] x !s32i>, !s32i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vx_i32mf2_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.mask.nxv1i32.i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], i32 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vint32mf2_t test_vmul_vx_i32mf2_m(vbool64_t mask, vint32mf2_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m1_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vv_i32m1_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[OP1:%.*]], <vscale x 2 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], <vscale x 2 x i32> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vmul_vv_i32m1_m(vbool32_t mask, vint32m1_t op1, vint32m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m1_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !s32i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vx_i32m1_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.mask.nxv2i32.i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], i32 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vmul_vx_i32m1_m(vbool32_t mask, vint32m1_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vv_i32m2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.mask.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], <vscale x 4 x i32> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vmul_vv_i32m2_m(vbool16_t mask, vint32m2_t op1, vint32m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s32i>, !cir.vector<[4] x !s32i>, !s32i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vx_i32m2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.mask.nxv4i32.i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], i32 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vint32m2_t test_vmul_vx_i32m2_m(vbool16_t mask, vint32m2_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m4_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vv_i32m4_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i32> [[OP1:%.*]], <vscale x 8 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.mask.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], <vscale x 8 x i32> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vmul_vv_i32m4_m(vbool8_t mask, vint32m4_t op1, vint32m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m4_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s32i>, !cir.vector<[8] x !s32i>, !s32i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vx_i32m4_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.mask.nxv8i32.i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], i32 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vint32m4_t test_vmul_vx_i32m4_m(vbool8_t mask, vint32m4_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i32m8_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vv_i32m8_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i32> [[OP1:%.*]], <vscale x 16 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.mask.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], <vscale x 16 x i32> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vmul_vv_i32m8_m(vbool4_t mask, vint32m8_t op1, vint32m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i32m8_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !s32i>, !cir.vector<[16] x !s32i>, !s32i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vx_i32m8_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.mask.nxv16i32.i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], i32 [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vint32m8_t test_vmul_vx_i32m8_m(vbool4_t mask, vint32m8_t op1, int32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m1_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vv_i64m1_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[OP1:%.*]], <vscale x 1 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], <vscale x 1 x i64> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vmul_vv_i64m1_m(vbool64_t mask, vint64m1_t op1, vint64m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m1_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !s64i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vx_i64m1_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.mask.nxv1i64.i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], i64 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vmul_vx_i64m1_m(vbool64_t mask, vint64m1_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vv_i64m2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i64> [[OP1:%.*]], <vscale x 2 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.mask.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], <vscale x 2 x i64> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vmul_vv_i64m2_m(vbool32_t mask, vint64m2_t op1, vint64m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !s64i>, !cir.vector<[2] x !s64i>, !s64i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vx_i64m2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.mask.nxv2i64.i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], i64 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vint64m2_t test_vmul_vx_i64m2_m(vbool32_t mask, vint64m2_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m4_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vv_i64m4_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i64> [[OP1:%.*]], <vscale x 4 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.mask.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], <vscale x 4 x i64> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vmul_vv_i64m4_m(vbool16_t mask, vint64m4_t op1, vint64m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m4_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !s64i>, !cir.vector<[4] x !s64i>, !s64i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vx_i64m4_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.mask.nxv4i64.i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], i64 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vint64m4_t test_vmul_vx_i64m4_m(vbool16_t mask, vint64m4_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_i64m8_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vv_i64m8_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i64> [[OP1:%.*]], <vscale x 8 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.mask.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], <vscale x 8 x i64> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vmul_vv_i64m8_m(vbool8_t mask, vint64m8_t op1, vint64m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_i64m8_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !s64i>, !cir.vector<[8] x !s64i>, !s64i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vx_i64m8_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.mask.nxv8i64.i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], i64 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vint64m8_t test_vmul_vx_i64m8_m(vbool8_t mask, vint64m8_t op1, int64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8mf8_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vv_u8mf8_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i8> [[OP1:%.*]], <vscale x 1 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.mask.nxv1i8.nxv1i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], <vscale x 1 x i8> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vmul_vv_u8mf8_m(vbool64_t mask, vuint8mf8_t op1, vuint8mf8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8mf8_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u8i>, !cir.vector<[1] x !u8i>, !u8i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i8> @test_vmul_vx_u8mf8_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i8> @llvm.riscv.vmul.mask.nxv1i8.i8.i64(<vscale x 1 x i8> poison, <vscale x 1 x i8> [[OP1]], i8 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i8> [[TMP0]]
//
vuint8mf8_t test_vmul_vx_u8mf8_m(vbool64_t mask, vuint8mf8_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8mf4_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vv_u8mf4_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i8> [[OP1:%.*]], <vscale x 2 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.mask.nxv2i8.nxv2i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], <vscale x 2 x i8> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vmul_vv_u8mf4_m(vbool32_t mask, vuint8mf4_t op1, vuint8mf4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8mf4_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u8i>, !cir.vector<[2] x !u8i>, !u8i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i8> @test_vmul_vx_u8mf4_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i8> @llvm.riscv.vmul.mask.nxv2i8.i8.i64(<vscale x 2 x i8> poison, <vscale x 2 x i8> [[OP1]], i8 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i8> [[TMP0]]
//
vuint8mf4_t test_vmul_vx_u8mf4_m(vbool32_t mask, vuint8mf4_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8mf2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vv_u8mf2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i8> [[OP1:%.*]], <vscale x 4 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.mask.nxv4i8.nxv4i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], <vscale x 4 x i8> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vmul_vv_u8mf2_m(vbool16_t mask, vuint8mf2_t op1, vuint8mf2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8mf2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u8i>, !cir.vector<[4] x !u8i>, !u8i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i8> @test_vmul_vx_u8mf2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i8> @llvm.riscv.vmul.mask.nxv4i8.i8.i64(<vscale x 4 x i8> poison, <vscale x 4 x i8> [[OP1]], i8 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i8> [[TMP0]]
//
vuint8mf2_t test_vmul_vx_u8mf2_m(vbool16_t mask, vuint8mf2_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m1_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vv_u8m1_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[OP1:%.*]], <vscale x 8 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], <vscale x 8 x i8> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vmul_vv_u8m1_m(vbool8_t mask, vuint8m1_t op1, vuint8m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m1_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !u8i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vmul_vx_u8m1_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vmul.mask.nxv8i8.i8.i64(<vscale x 8 x i8> poison, <vscale x 8 x i8> [[OP1]], i8 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vmul_vx_u8m1_m(vbool8_t mask, vuint8m1_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m2_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vv_u8m2_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i8> [[OP1:%.*]], <vscale x 16 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.mask.nxv16i8.nxv16i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], <vscale x 16 x i8> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vmul_vv_u8m2_m(vbool4_t mask, vuint8m2_t op1, vuint8m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m2_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !u8i>, !cir.vector<[16] x !u8i>, !u8i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i8> @test_vmul_vx_u8m2_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i8> @llvm.riscv.vmul.mask.nxv16i8.i8.i64(<vscale x 16 x i8> poison, <vscale x 16 x i8> [[OP1]], i8 [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i8> [[TMP0]]
//
vuint8m2_t test_vmul_vx_u8m2_m(vbool4_t mask, vuint8m2_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m4_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vv_u8m4_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i8> [[OP1:%.*]], <vscale x 32 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.mask.nxv32i8.nxv32i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], <vscale x 32 x i8> [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vmul_vv_u8m4_m(vbool2_t mask, vuint8m4_t op1, vuint8m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m4_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !u8i>, !cir.vector<[32] x !u8i>, !u8i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i8> @test_vmul_vx_u8m4_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i8> @llvm.riscv.vmul.mask.nxv32i8.i8.i64(<vscale x 32 x i8> poison, <vscale x 32 x i8> [[OP1]], i8 [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i8> [[TMP0]]
//
vuint8m4_t test_vmul_vx_u8m4_m(vbool2_t mask, vuint8m4_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u8m8_m(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !cir.vector<[64] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[64] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vv_u8m8_m
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], <vscale x 64 x i8> [[OP1:%.*]], <vscale x 64 x i8> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.mask.nxv64i8.nxv64i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], <vscale x 64 x i8> [[OP2]], <vscale x 64 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vmul_vv_u8m8_m(vbool1_t mask, vuint8m8_t op1, vuint8m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u8m8_m(
// CIR-SAME: -> !cir.vector<[64]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[64] x !u8i>, !cir.vector<[64] x !u8i>, !u8i, !cir.vector<[64] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[64] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 64 x i8> @test_vmul_vx_u8m8_m
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], <vscale x 64 x i8> [[OP1:%.*]], i8 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 64 x i8> @llvm.riscv.vmul.mask.nxv64i8.i8.i64(<vscale x 64 x i8> poison, <vscale x 64 x i8> [[OP1]], i8 [[OP2]], <vscale x 64 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 64 x i8> [[TMP0]]
//
vuint8m8_t test_vmul_vx_u8m8_m(vbool1_t mask, vuint8m8_t op1, uint8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16mf4_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vv_u16mf4_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i16> [[OP1:%.*]], <vscale x 1 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.mask.nxv1i16.nxv1i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], <vscale x 1 x i16> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vmul_vv_u16mf4_m(vbool64_t mask, vuint16mf4_t op1, vuint16mf4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16mf4_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u16i>, !cir.vector<[1] x !u16i>, !u16i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i16> @test_vmul_vx_u16mf4_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i16> @llvm.riscv.vmul.mask.nxv1i16.i16.i64(<vscale x 1 x i16> poison, <vscale x 1 x i16> [[OP1]], i16 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i16> [[TMP0]]
//
vuint16mf4_t test_vmul_vx_u16mf4_m(vbool64_t mask, vuint16mf4_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16mf2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vv_u16mf2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i16> [[OP1:%.*]], <vscale x 2 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.mask.nxv2i16.nxv2i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], <vscale x 2 x i16> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vmul_vv_u16mf2_m(vbool32_t mask, vuint16mf2_t op1, vuint16mf2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16mf2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u16i>, !cir.vector<[2] x !u16i>, !u16i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i16> @test_vmul_vx_u16mf2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i16> @llvm.riscv.vmul.mask.nxv2i16.i16.i64(<vscale x 2 x i16> poison, <vscale x 2 x i16> [[OP1]], i16 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i16> [[TMP0]]
//
vuint16mf2_t test_vmul_vx_u16mf2_m(vbool32_t mask, vuint16mf2_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m1_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vv_u16m1_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[OP1:%.*]], <vscale x 4 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], <vscale x 4 x i16> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vmul_vv_u16m1_m(vbool16_t mask, vuint16m1_t op1, vuint16m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m1_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !u16i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vmul_vx_u16m1_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vmul.mask.nxv4i16.i16.i64(<vscale x 4 x i16> poison, <vscale x 4 x i16> [[OP1]], i16 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vmul_vx_u16m1_m(vbool16_t mask, vuint16m1_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m2_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vv_u16m2_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i16> [[OP1:%.*]], <vscale x 8 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.mask.nxv8i16.nxv8i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], <vscale x 8 x i16> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vmul_vv_u16m2_m(vbool8_t mask, vuint16m2_t op1, vuint16m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m2_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u16i>, !cir.vector<[8] x !u16i>, !u16i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i16> @test_vmul_vx_u16m2_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i16> @llvm.riscv.vmul.mask.nxv8i16.i16.i64(<vscale x 8 x i16> poison, <vscale x 8 x i16> [[OP1]], i16 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i16> [[TMP0]]
//
vuint16m2_t test_vmul_vx_u16m2_m(vbool8_t mask, vuint16m2_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m4_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vv_u16m4_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i16> [[OP1:%.*]], <vscale x 16 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.mask.nxv16i16.nxv16i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], <vscale x 16 x i16> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vmul_vv_u16m4_m(vbool4_t mask, vuint16m4_t op1, vuint16m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m4_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !u16i>, !cir.vector<[16] x !u16i>, !u16i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i16> @test_vmul_vx_u16m4_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i16> @llvm.riscv.vmul.mask.nxv16i16.i16.i64(<vscale x 16 x i16> poison, <vscale x 16 x i16> [[OP1]], i16 [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i16> [[TMP0]]
//
vuint16m4_t test_vmul_vx_u16m4_m(vbool4_t mask, vuint16m4_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u16m8_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vv_u16m8_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i16> [[OP1:%.*]], <vscale x 32 x i16> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.mask.nxv32i16.nxv32i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], <vscale x 32 x i16> [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vmul_vv_u16m8_m(vbool2_t mask, vuint16m8_t op1, vuint16m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u16m8_m(
// CIR-SAME: -> !cir.vector<[32]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[32] x !u16i>, !cir.vector<[32] x !u16i>, !u16i, !cir.vector<[32] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[32] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 32 x i16> @test_vmul_vx_u16m8_m
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 32 x i16> [[OP1:%.*]], i16 noundef{{( zeroext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 32 x i16> @llvm.riscv.vmul.mask.nxv32i16.i16.i64(<vscale x 32 x i16> poison, <vscale x 32 x i16> [[OP1]], i16 [[OP2]], <vscale x 32 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 32 x i16> [[TMP0]]
//
vuint16m8_t test_vmul_vx_u16m8_m(vbool2_t mask, vuint16m8_t op1, uint16_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32mf2_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vv_u32mf2_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i32> [[OP1:%.*]], <vscale x 1 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.mask.nxv1i32.nxv1i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], <vscale x 1 x i32> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vmul_vv_u32mf2_m(vbool64_t mask, vuint32mf2_t op1, vuint32mf2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32mf2_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u32i>, !cir.vector<[1] x !u32i>, !u32i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i32> @test_vmul_vx_u32mf2_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i32> @llvm.riscv.vmul.mask.nxv1i32.i32.i64(<vscale x 1 x i32> poison, <vscale x 1 x i32> [[OP1]], i32 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i32> [[TMP0]]
//
vuint32mf2_t test_vmul_vx_u32mf2_m(vbool64_t mask, vuint32mf2_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m1_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vv_u32m1_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[OP1:%.*]], <vscale x 2 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], <vscale x 2 x i32> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vmul_vv_u32m1_m(vbool32_t mask, vuint32m1_t op1, vuint32m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m1_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !u32i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vmul_vx_u32m1_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vmul.mask.nxv2i32.i32.i64(<vscale x 2 x i32> poison, <vscale x 2 x i32> [[OP1]], i32 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vmul_vx_u32m1_m(vbool32_t mask, vuint32m1_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vv_u32m2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i32> [[OP1:%.*]], <vscale x 4 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.mask.nxv4i32.nxv4i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], <vscale x 4 x i32> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vmul_vv_u32m2_m(vbool16_t mask, vuint32m2_t op1, vuint32m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m2_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u32i>, !cir.vector<[4] x !u32i>, !u32i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i32> @test_vmul_vx_u32m2_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i32> @llvm.riscv.vmul.mask.nxv4i32.i32.i64(<vscale x 4 x i32> poison, <vscale x 4 x i32> [[OP1]], i32 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i32> [[TMP0]]
//
vuint32m2_t test_vmul_vx_u32m2_m(vbool16_t mask, vuint32m2_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m4_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vv_u32m4_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i32> [[OP1:%.*]], <vscale x 8 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.mask.nxv8i32.nxv8i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], <vscale x 8 x i32> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vmul_vv_u32m4_m(vbool8_t mask, vuint32m4_t op1, vuint32m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m4_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u32i>, !cir.vector<[8] x !u32i>, !u32i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i32> @test_vmul_vx_u32m4_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i32> @llvm.riscv.vmul.mask.nxv8i32.i32.i64(<vscale x 8 x i32> poison, <vscale x 8 x i32> [[OP1]], i32 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i32> [[TMP0]]
//
vuint32m4_t test_vmul_vx_u32m4_m(vbool8_t mask, vuint32m4_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u32m8_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vv_u32m8_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i32> [[OP1:%.*]], <vscale x 16 x i32> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.mask.nxv16i32.nxv16i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], <vscale x 16 x i32> [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vmul_vv_u32m8_m(vbool4_t mask, vuint32m8_t op1, vuint32m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u32m8_m(
// CIR-SAME: -> !cir.vector<[16]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[16] x !u32i>, !cir.vector<[16] x !u32i>, !u32i, !cir.vector<[16] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[16] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 16 x i32> @test_vmul_vx_u32m8_m
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 16 x i32> [[OP1:%.*]], i32 noundef{{( signext)?}} [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 16 x i32> @llvm.riscv.vmul.mask.nxv16i32.i32.i64(<vscale x 16 x i32> poison, <vscale x 16 x i32> [[OP1]], i32 [[OP2]], <vscale x 16 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 16 x i32> [[TMP0]]
//
vuint32m8_t test_vmul_vx_u32m8_m(vbool4_t mask, vuint32m8_t op1, uint32_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m1_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vv_u64m1_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[OP1:%.*]], <vscale x 1 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], <vscale x 1 x i64> [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vmul_vv_u64m1_m(vbool64_t mask, vuint64m1_t op1, vuint64m1_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m1_m(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !u64i, !cir.vector<[1] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vmul_vx_u64m1_m
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vmul.mask.nxv1i64.i64.i64(<vscale x 1 x i64> poison, <vscale x 1 x i64> [[OP1]], i64 [[OP2]], <vscale x 1 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vmul_vx_u64m1_m(vbool64_t mask, vuint64m1_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vv_u64m2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i64> [[OP1:%.*]], <vscale x 2 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.mask.nxv2i64.nxv2i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], <vscale x 2 x i64> [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vmul_vv_u64m2_m(vbool32_t mask, vuint64m2_t op1, vuint64m2_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m2_m(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[2] x !u64i>, !cir.vector<[2] x !u64i>, !u64i, !cir.vector<[2] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[2] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i64> @test_vmul_vx_u64m2_m
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i64> @llvm.riscv.vmul.mask.nxv2i64.i64.i64(<vscale x 2 x i64> poison, <vscale x 2 x i64> [[OP1]], i64 [[OP2]], <vscale x 2 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 2 x i64> [[TMP0]]
//
vuint64m2_t test_vmul_vx_u64m2_m(vbool32_t mask, vuint64m2_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m4_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vv_u64m4_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i64> [[OP1:%.*]], <vscale x 4 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.mask.nxv4i64.nxv4i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], <vscale x 4 x i64> [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vmul_vv_u64m4_m(vbool16_t mask, vuint64m4_t op1, vuint64m4_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m4_m(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[4] x !u64i>, !cir.vector<[4] x !u64i>, !u64i, !cir.vector<[4] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[4] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i64> @test_vmul_vx_u64m4_m
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i64> @llvm.riscv.vmul.mask.nxv4i64.i64.i64(<vscale x 4 x i64> poison, <vscale x 4 x i64> [[OP1]], i64 [[OP2]], <vscale x 4 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 4 x i64> [[TMP0]]
//
vuint64m4_t test_vmul_vx_u64m4_m(vbool16_t mask, vuint64m4_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vv_u64m8_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vv_u64m8_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i64> [[OP1:%.*]], <vscale x 8 x i64> [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.mask.nxv8i64.nxv8i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], <vscale x 8 x i64> [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vmul_vv_u64m8_m(vbool8_t mask, vuint64m8_t op1, vuint64m8_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vmul_vx_u64m8_m(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vmul.mask" {{%.*}} : (!cir.vector<[8] x !u64i>, !cir.vector<[8] x !u64i>, !u64i, !cir.vector<[8] x !cir.int<u, 1>>, !u64i, !u64i) -> !cir.vector<[8] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i64> @test_vmul_vx_u64m8_m
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i64> [[OP1:%.*]], i64 noundef [[OP2:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i64> @llvm.riscv.vmul.mask.nxv8i64.i64.i64(<vscale x 8 x i64> poison, <vscale x 8 x i64> [[OP1]], i64 [[OP2]], <vscale x 8 x i1> [[MASK]], i64 [[VL]], i64 3)
// CHECK-RV64-NEXT:    ret <vscale x 8 x i64> [[TMP0]]
//
vuint64m8_t test_vmul_vx_u64m8_m(vbool8_t mask, vuint64m8_t op1, uint64_t op2, size_t vl) {
  return __riscv_vmul(mask, op1, op2, vl);
}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-RV64: {{.*}}
