// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6

// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O2 %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O2 %s

#include <ptrcheck.h>

// CHECK-O0-LABEL: define dso_local i32 @main(
// CHECK-O0-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-O0-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP2:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-O0-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP3]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[P]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[P]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP2]], ptr align 8 [[P]], i64 16, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP2]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR4:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR3]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP2]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB6:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR5]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR4]], ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB6]], ptr [[TMP7]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR4]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR8:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR7]], align 8
// CHECK-O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR8]], i64 10
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB10:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR9]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB12:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR11]], align 8
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP10:%.*]] = icmp ule ptr [[TMP9]], [[WIDE_PTR_UB10]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP10]], label %[[CONT14:.*]], label %[[TRAP13:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP13]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT14]]:
// CHECK-O0-NEXT:    [[TMP11:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP9]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP11]], label %[[CONT16:.*]], label %[[TRAP15:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP15]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT16]]:
// CHECK-O0-NEXT:    [[TMP12:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB12]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP12]], label %[[CONT18:.*]], label %[[TRAP17:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP17]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT18]]:
// CHECK-O0-NEXT:    [[TMP13:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-O0-NEXT:    ret i32 [[TMP13]]
//
// CHECK-O2-LABEL: define dso_local noundef i32 @main(
// CHECK-O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int main() {
    int arr[10];
    int *__indexable p = arr;
    return p[10]; // trap : overflow
}
