// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py

// XFAIL: *
// FIXME: rdar://80820825

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix CHECK-O2 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix CHECK-O2 %s

#include <ptrcheck.h>

// CHECK-O2-LABEL: @TestOK(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    ret void
//
void TestOK() {
    int len = 0;
    int *__single __counted_by(len) dcp = 0;
    int *__single tp = dcp;
}

// CHECK-O2-LABEL: @TestOK2(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    ret void
//
void TestOK2() {
  int len = 0;
  int arr[10];
  int *__single __counted_by(len) dcp = arr + 10;
}

// CHECK-O2-LABEL: @TestFail1(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], !annotation !{{[0-9]+}}
// CHECK-O2-NEXT:    unreachable
//
void TestFail1() {
  int len = 0;
  int arr[10];
  int *__single __counted_by(len) dcp = arr + 10;
  int *__single tp = dcp; // trap
}

// CHECK-O2-LABEL: @TestFail2(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-O2-NEXT:    unreachable
//
int TestFail2() {
  int len = 0;
  int *__single __counted_by(len) dcp = 0;
  int *__single tp = dcp;
  return *tp; // trap
}

// CHECK-O2-LABEL: @TestFail3(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-O2-NEXT:    unreachable
//
int TestFail3() {
  int len = 0;
  int *__single __counted_by(len) dcp = 0;
  int *__single tp = dcp;
  return tp[0]; // trap
}

struct Data {
  int *ptr;
  char *cp;
};

// CHECK-O2-LABEL: @TestFail4(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-O2-NEXT:    unreachable
//
int *TestFail4() {
  int len = 0;
  struct Data *__single __counted_by(len) dcp = 0;
  struct Data *__single tp = dcp;
  return tp->ptr; // trap
}

// CHECK-O2-LABEL: @TestFail5(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-O2-NEXT:    unreachable
//
char TestFail5() {
  int len = 0;
  struct Data *__single __counted_by(len) dcp = 0;
  struct Data *__single tp = dcp;
  return *(tp->cp); // trap
}

// CHECK-O2-LABEL: @TestFail6(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-O2-NEXT:    unreachable
//
char *TestFail6() {
  int len = 0;
  struct Data *__single __counted_by(len) dcp = 0;
  struct Data *__single tp = dcp;
  return tp->cp; // trap
}

// CHECK-O2-LABEL: @TestFail7(
// CHECK-O2-NEXT:  entry:
// CHECK-O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR3]], !annotation !{{[0-9]+}}
// CHECK-O2-NEXT:    unreachable
//
void TestFail7() {
  int len = 0;
  struct Data *__single __counted_by(len) dcp = 0;
  struct Data *__single tp = dcp;
  char **__single cp = &tp->cp; // trap
}
