// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 3
// RUN: %clang_cc1 -O2  -fbounds-safety -triple x86_64 -emit-llvm %s -o - | FileCheck %s
//
#include <ptrcheck.h>

typedef struct {
    int *__counted_by(len) buf;
    int len;
} S;

void use(int *, int);

// CHECK-LABEL: define dso_local range(i32 -1, 1) i32 @access1(
// CHECK-SAME: ptr noundef readonly captures(none) [[P:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[LEN:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 8, !tbaa [[TBAA5:![0-9]+]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP0]], 2
// CHECK-NEXT:    br i1 [[CMP]], label [[CLEANUP:%.*]], label [[BOUNDSCHECK_NULL:%.*]]
// CHECK:       boundscheck.null:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 8, !tbaa [[TBAA9:![0-9]+]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[TMP1]], i64 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4, !tbaa [[TBAA1:![0-9]+]]
// CHECK-NEXT:    tail call void @use(ptr noundef [[BOUND_PTR_ARITH]], i32 noundef [[TMP2]]) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    br label [[CLEANUP]]
// CHECK:       cleanup:
// CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[BOUNDSCHECK_NULL]] ], [ -1, [[ENTRY:%.*]] ]
// CHECK-NEXT:    ret i32 [[RETVAL_0]]
//
int access1(S *p) {
  int *Ptr = p->buf;
  int Len = p->len;

  if (Len < 2) return -1;
  int v = *Ptr++;
  use(Ptr, v);
  return 0;
}

// CHECK-LABEL: define dso_local range(i32 -1, 1) i32 @access2(
// CHECK-SAME: ptr noundef readonly captures(none) [[P:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[LEN:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN]], align 8, !tbaa [[TBAA5]]
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P]], align 8, !tbaa [[TBAA9]]
// CHECK-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP0]] to i64
// CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [4 x i8], ptr [[TMP1]], i64 [[IDX_EXT]]
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP0]], 2
// CHECK-NEXT:    br i1 [[CMP]], label [[CLEANUP:%.*]], label [[CONT25:%.*]]
// CHECK:       trap:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], !annotation [[META10:![0-9]+]]
// CHECK-NEXT:    unreachable, !annotation [[META10]]
// CHECK:       cont25:
// CHECK-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[TMP1]], i64 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[TMP1]], align 4, !tbaa [[TBAA1]]
// CHECK-NEXT:    tail call void @use(ptr noundef [[BOUND_PTR_ARITH]], i32 noundef [[TMP2]]) #[[ATTR3]]
// CHECK-NEXT:    [[BOUND_PTR_ARITH16:%.*]] = getelementptr i8, ptr [[TMP1]], i64 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[BOUND_PTR_ARITH]], align 4, !tbaa [[TBAA1]]
// CHECK-NEXT:    [[DOTNOT48:%.*]] = icmp eq ptr [[BOUND_PTR_ARITH16]], null, !annotation [[META11:![0-9]+]]
// CHECK-NEXT:    br i1 [[DOTNOT48]], label [[BOUNDSCHECK_NULL37:%.*]], label [[BOUNDSCHECK_NOTNULL33:%.*]], !annotation [[META11]]
// CHECK:       boundscheck.notnull33:
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[TMP1]], i64 12, !annotation [[META12:![0-9]+]]
// CHECK-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[TMP4]], [[ADD_PTR]], !annotation [[META12]]
// CHECK-NEXT:    [[TMP6:%.*]] = icmp ule ptr [[BOUND_PTR_ARITH16]], [[TMP4]], !annotation [[META12]]
// CHECK-NEXT:    [[OR_COND44:%.*]] = and i1 [[TMP5]], [[TMP6]], !annotation [[META12]]
// CHECK-NEXT:    br i1 [[OR_COND44]], label [[BOUNDSCHECK_NULL37]], label [[TRAP:%.*]], {{!prof ![0-9]+}}, !annotation [[META12]]
// CHECK:       boundscheck.null37:
// CHECK-NEXT:    tail call void @use(ptr noundef [[BOUND_PTR_ARITH16]], i32 noundef [[TMP3]]) #[[ATTR3]]
// CHECK-NEXT:    br label [[CLEANUP]]
// CHECK:       cleanup:
// CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ 0, [[BOUNDSCHECK_NULL37]] ], [ -1, [[ENTRY:%.*]] ]
// CHECK-NEXT:    ret i32 [[RETVAL_0]]
//
int access2(S *p) {
  int *Ptr = p->buf;
  int Len = p->len;

  if (Len < 2) return -1;
  int v = *Ptr++;
  use(Ptr, v);
  v = *Ptr++;
  use(Ptr, v);
  return 0;
}
