// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name TMP_ --version 6

// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck %s

#include <ptrcheck.h>

struct foo {
    int a, b, c;
};

// CHECK-LABEL: define dso_local i32 @sum(
// CHECK-SAME: ptr noundef readonly byval(%"__bounds_safety::wide_ptr.bidi_indexable") align 8 captures(none) [[F:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[AGG_TEMP_SROA_0_0_COPYLOAD:%.*]] = load ptr, ptr [[F]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_F_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_2_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_2_0_F_SROA_IDX]], align 8
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_F_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[F]], i64 16
// CHECK-NEXT:    [[AGG_TEMP_SROA_3_0_COPYLOAD:%.*]] = load ptr, ptr [[AGG_TEMP_SROA_3_0_F_SROA_IDX]], align 8, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 12
// CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[AGG_TEMP_SROA_2_0_COPYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[AGG_TEMP_SROA_3_0_COPYLOAD]], [[AGG_TEMP_SROA_0_0_COPYLOAD]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[TMP1]], i1 [[TMP2]], i1 false, {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-NEXT:    br i1 [[OR_COND]], label %[[CONT19:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK:       [[TRAP]]:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK:       [[CONT19]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[B:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 4
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[B]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP4]], [[TMP3]]
// CHECK-NEXT:    [[C:%.*]] = getelementptr inbounds nuw i8, ptr [[AGG_TEMP_SROA_0_0_COPYLOAD]], i64 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[C]], align 4, {{!tbaa ![0-9]+}}
// CHECK-NEXT:    [[ADD20:%.*]] = add nsw i32 [[ADD]], [[TMP5]]
// CHECK-NEXT:    ret i32 [[ADD20]]
//
int sum(struct foo *__bidi_indexable f) {
    // This should generate only one check at O2.
    return f->a + f->b + f->c;
}
