// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6

// RUN: %clang_cc1 -triple x86_64 -O2 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s
// RUN: %clang_cc1 -triple x86_64 -O0 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s
// RUN: %clang_cc1 -triple x86_64 -O2 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s
// RUN: %clang_cc1 -triple x86_64 -O0 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s

// O2-LABEL: define dso_local i32 @foo(
// O2-SAME: ptr noundef readonly captures(address) [[ARR:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// O2-NEXT:  [[ENTRY:.*:]]
// O2-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 4
// O2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[ARR]], i64 40
// O2-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr [[ARR]], i64 44, {{!annotation ![0-9]+}}
// O2-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[TMP0]], [[UPPER]], {{!annotation ![0-9]+}}
// O2-NEXT:    [[TMP2:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP0]], {{!annotation ![0-9]+}}
// O2-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP2]], {{!annotation ![0-9]+}}
// O2-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[ARRAYIDX]], [[ARR]], {{!annotation ![0-9]+}}
// O2-NEXT:    [[OR_COND3:%.*]] = and i1 [[TMP3]], [[OR_COND]], {{!annotation ![0-9]+}}
// O2-NEXT:    br i1 [[OR_COND3]], label %[[CONT2:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O2:       [[TRAP]]:
// O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O2:       [[CONT2]]:
// O2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[ARRAYIDX]], align 4, {{!tbaa ![0-9]+}}
// O2-NEXT:    ret i32 [[TMP4]]
//
// O0-LABEL: define dso_local i32 @foo(
// O0-SAME: ptr noundef [[ARR:%.*]]) #[[ATTR0:[0-9]+]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[ARR_ADDR:%.*]] = alloca ptr, align 8
// O0-NEXT:    [[BIDI_ARR:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[I:%.*]] = alloca i32, align 4
// O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    store ptr [[ARR]], ptr [[ARR_ADDR]], align 8
// O0-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[ARR_ADDR]], align 8
// O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[TMP0]], i64 1
// O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BIDI_ARR]], i32 0, i32 0
// O0-NEXT:    store ptr [[TMP0]], ptr [[TMP1]], align 8
// O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BIDI_ARR]], i32 0, i32 1
// O0-NEXT:    store ptr [[UPPER]], ptr [[TMP2]], align 8
// O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BIDI_ARR]], i32 0, i32 2
// O0-NEXT:    store ptr [[TMP0]], ptr [[TMP3]], align 8
// O0-NEXT:    br label %[[BINGO:.*]]
// O0:       [[BINGO]]:
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[BIDI_ARR]], i64 24, i1 false)
// O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 10
// O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// O0-NEXT:    [[TMP4:%.*]] = getelementptr i32, ptr [[ARRAYIDX]], i64 1, {{!annotation ![0-9]+}}
// O0-NEXT:    [[TMP5:%.*]] = icmp ule ptr [[TMP4]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP5]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT]]:
// O0-NEXT:    [[TMP6:%.*]] = icmp ule ptr [[ARRAYIDX]], [[TMP4]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP6]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP1]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT2]]:
// O0-NEXT:    [[TMP7:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP7]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP3]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT4]]:
// O0-NEXT:    [[TMP8:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// O0-NEXT:    store i32 [[TMP8]], ptr [[I]], align 4
// O0-NEXT:    [[TMP9:%.*]] = load i32, ptr [[I]], align 4
// O0-NEXT:    ret i32 [[TMP9]]
//
int foo(int * arr) {
    int * bidi_arr = arr;
bingo:;
    int i = bidi_arr[10];

    return i;
}


