// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --prefix-filecheck-ir-name tmp1 --version 6


// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s

// O0-LABEL: define dso_local i32 @main(
// O0-SAME: ) #[[ATTR0:[0-9]+]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// O0-NEXT:    [[ARR:%.*]] = alloca [4 x i32], align 16
// O0-NEXT:    [[P:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[TMP1TMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// O0-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[ARR]], i8 0, i64 16, i1 false)
// O0-NEXT:    br label %[[TEST_START:.*]]
// O0:       [[TEST_START]]:
// O0-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARR]], i64 0, i64 0
// O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 4
// O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 0
// O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 1
// O0-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 2
// O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP]], ptr align 8 [[P]], i64 24, i1 false)
// O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// O0-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP4]], i64 4
// O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 0
// O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP5]], align 8
// O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// O0-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[TMP6]], align 8
// O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 1
// O0-NEXT:    store ptr [[TMP7]], ptr [[TMP8]], align 8
// O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// O0-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 2
// O0-NEXT:    store ptr [[TMP10]], ptr [[TMP11]], align 8
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP1TMP1]], ptr align 8 [[P]], i64 24, i1 false)
// O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP1TMP1]], i32 0, i32 0
// O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
// O0-NEXT:    [[BOUND_PTR_ARITH2:%.*]] = getelementptr i32, ptr [[TMP13]], i64 -1
// O0-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 0
// O0-NEXT:    store ptr [[BOUND_PTR_ARITH2]], ptr [[TMP14]], align 8
// O0-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP1TMP1]], i32 0, i32 1
// O0-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP15]], align 8
// O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 1
// O0-NEXT:    store ptr [[TMP16]], ptr [[TMP17]], align 8
// O0-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP1TMP1]], i32 0, i32 2
// O0-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[TMP18]], align 8
// O0-NEXT:    [[TMP20:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[P]], i32 0, i32 2
// O0-NEXT:    store ptr [[TMP19]], ptr [[TMP20]], align 8
// O0-NEXT:    br label %[[TEST_END:.*]]
// O0:       [[TEST_END]]:
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[P]], i64 24, i1 false)
// O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// O0-NEXT:    [[TMP21:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 1, {{!annotation ![0-9]+}}
// O0-NEXT:    [[TMP22:%.*]] = icmp ule ptr [[TMP21]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP22]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT]]:
// O0-NEXT:    [[TMP23:%.*]] = icmp ule ptr [[WIDE_PTR_PTR]], [[TMP21]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP23]], label %[[CONT4:.*]], label %[[TRAP3:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP3]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT4]]:
// O0-NEXT:    [[TMP24:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP24]], label %[[CONT6:.*]], label %[[TRAP5:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP5]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT6]]:
// O0-NEXT:    [[TMP25:%.*]] = load i32, ptr [[WIDE_PTR_PTR]], align 4
// O0-NEXT:    ret i32 [[TMP25]]
//
// O2-LABEL: define dso_local noundef i32 @main(
// O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// O2-NEXT:  [[ENTRY:.*:]]
// O2-NEXT:    ret i32 0
//
int main() {
    int arr[4] = {0};
test_start:;
    int *p = arr;
    p += 4;
    p -= 1;
test_end:;
    return *p; // ok
}


