; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes='loop(indvars)' -verify-scev -S %s | FileCheck %s

define ptr @pointer_advance_inbounds(ptr %p, i64 %n) {
; CHECK-LABEL: define ptr @pointer_advance_inbounds(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[P]], i64 [[N]]
; CHECK-NEXT:    ret ptr [[SCEVGEP]]
;
entry:
  br label %loop

loop:
  %ptr = phi ptr [ %p, %entry ], [ %inc, %loop ]
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %inc = getelementptr inbounds nuw i8, ptr %ptr, i64 1
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %n
  br i1 %cond, label %exit, label %loop

exit:
  ret ptr %inc
}

define ptr @pointer_advance_no_inbounds(ptr %p, i64 %n) {
; CHECK-LABEL: define ptr @pointer_advance_no_inbounds(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[P]], i64 [[N]]
; CHECK-NEXT:    ret ptr [[SCEVGEP]]
;
entry:
  br label %loop

loop:
  %ptr = phi ptr [ %p, %entry ], [ %inc, %loop ]
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %inc = getelementptr i8, ptr %ptr, i64 1
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %n
  br i1 %cond, label %exit, label %loop

exit:
  ret ptr %inc
}

define ptr @two_loops_only_first_inbounds(ptr %p, i64 %n) {
; CHECK-LABEL: define ptr @two_loops_only_first_inbounds(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    br i1 true, label %[[BETWEEN:.*]], label %[[LOOP1]]
; CHECK:       [[BETWEEN]]:
; CHECK-NEXT:    [[TMP0:%.*]] = shl i64 [[N]], 1
; CHECK-NEXT:    br label %[[LOOP2:.*]]
; CHECK:       [[LOOP2]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LOOP2]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP0]]
; CHECK-NEXT:    ret ptr [[SCEVGEP1]]
;
entry:
  br label %loop1

loop1:
  %ptr1 = phi ptr [ %p, %entry ], [ %inc1, %loop1 ]
  %iv1 = phi i64 [ 0, %entry ], [ %iv1.next, %loop1 ]
  %inc1 = getelementptr inbounds nuw i8, ptr %ptr1, i64 1
  %iv1.next = add nuw nsw i64 %iv1, 1
  %cond1 = icmp eq i64 %iv1.next, %n
  br i1 %cond1, label %between, label %loop1

between:
  br label %loop2

loop2:
  %ptr2 = phi ptr [ %inc1, %between ], [ %inc2, %loop2 ]
  %iv2 = phi i64 [ 0, %between ], [ %iv2.next, %loop2 ]
  %inc2 = getelementptr i8, ptr %ptr2, i64 1
  %iv2.next = add nuw nsw i64 %iv2, 1
  %cond2 = icmp eq i64 %iv2.next, %n
  br i1 %cond2, label %exit, label %loop2

exit:
  ret ptr %inc2
}

define ptr @unknown_step_inbounds(ptr %p, i64 %n, i64 %step) {
; CHECK-LABEL: define ptr @unknown_step_inbounds(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]], i64 [[STEP:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = mul i64 [[STEP]], [[N]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP0]]
; CHECK-NEXT:    ret ptr [[SCEVGEP]]
;
entry:
  br label %loop

loop:
  %ptr = phi ptr [ %p, %entry ], [ %inc, %loop ]
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %inc = getelementptr inbounds nuw i8, ptr %ptr, i64 %step
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %n
  br i1 %cond, label %exit, label %loop

exit:
  ret ptr %inc
}

define ptr @start_below_base_inbounds(ptr %base) {
; CHECK-LABEL: define ptr @start_below_base_inbounds(
; CHECK-SAME: ptr [[BASE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[BASE]], i64 -4
; CHECK-NEXT:    ret ptr [[SCEVGEP]]
;
entry:
  %p0 = getelementptr i8, ptr %base, i64 -8
  br label %loop

loop:
  %ptr = phi ptr [ %p0, %entry ], [ %inc, %loop ]
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %inc = getelementptr inbounds nuw i8, ptr %ptr, i64 1
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, 4
  br i1 %cond, label %exit, label %loop

exit:
  ret ptr %inc
}

define ptr @symbolic_start_below_base_inbounds(ptr %base, i64 %m, i64 %n) {
; CHECK-LABEL: define ptr @symbolic_start_below_base_inbounds(
; CHECK-SAME: ptr [[BASE:%.*]], i64 [[M:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[N]], [[M]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[BASE]], i64 [[TMP0]]
; CHECK-NEXT:    ret ptr [[SCEVGEP]]
;
entry:
  %p0 = getelementptr i8, ptr %base, i64 %m
  br label %loop

loop:
  %ptr = phi ptr [ %p0, %entry ], [ %inc, %loop ]
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %inc = getelementptr inbounds nuw i8, ptr %ptr, i64 1
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %n
  br i1 %cond, label %exit, label %loop

exit:
  ret ptr %inc
}

define ptr @nonconstant_nonneg_step_inbounds(ptr %p, i64 %n, i32 %s) {
; CHECK-LABEL: define ptr @nonconstant_nonneg_step_inbounds(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]], i32 [[S:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[STEP:%.*]] = zext i32 [[S]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = mul i64 [[N]], [[STEP]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP0]]
; CHECK-NEXT:    ret ptr [[SCEVGEP]]
;
entry:
  %step = zext i32 %s to i64
  br label %loop

loop:
  %ptr = phi ptr [ %p, %entry ], [ %inc, %loop ]
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %inc = getelementptr inbounds nuw i8, ptr %ptr, i64 %step
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %n
  br i1 %cond, label %exit, label %loop

exit:
  ret ptr %inc
}

define ptr @polynomial_addrec_inbounds(ptr %p, i64 %n) {
; CHECK-LABEL: define ptr @polynomial_addrec_inbounds(
; CHECK-SAME: ptr [[P:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[EXIT:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = shl i64 [[N]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[N]], -1
; CHECK-NEXT:    [[TMP2:%.*]] = zext i64 [[TMP1]] to i65
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[N]], -2
; CHECK-NEXT:    [[TMP4:%.*]] = zext i64 [[TMP3]] to i65
; CHECK-NEXT:    [[TMP5:%.*]] = mul i65 [[TMP2]], [[TMP4]]
; CHECK-NEXT:    [[TMP6:%.*]] = lshr i65 [[TMP5]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = trunc i65 [[TMP6]] to i64
; CHECK-NEXT:    [[TMP8:%.*]] = add i64 [[TMP0]], [[TMP7]]
; CHECK-NEXT:    [[TMP9:%.*]] = add i64 [[TMP8]], -1
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br i1 true, label %[[EXIT1:.*]], label %[[LOOP]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP9]]
; CHECK-NEXT:    ret ptr [[SCEVGEP]]
;
entry:
  br label %loop

loop:
  %ptr = phi ptr [ %p, %entry ], [ %inc, %loop ]
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %step = phi i64 [ 1, %entry ], [ %step.next, %loop ]
  %inc = getelementptr inbounds nuw i8, ptr %ptr, i64 %step
  %step.next = add nuw nsw i64 %step, 1
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %n
  br i1 %cond, label %exit, label %loop

exit:
  ret ptr %inc
}
