; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=indvars -S | FileCheck %s

declare void @foo(i64 noundef)

; Function Attrs: mustprogress noreturn uwtable
define void @pr59633(ptr noundef %ptr) {
; CHECK-LABEL: @pr59633(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[WHILE_BODY:%.*]]
; CHECK:       while.body:
; CHECK-NEXT:    [[PTR_ADDR_0:%.*]] = phi ptr [ [[PTR:%.*]], [[ENTRY:%.*]] ], [ [[ADD_PTR:%.*]], [[WHILE_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[PTR_ADDR_0]] to i64
; CHECK-NEXT:    [[TMP1:%.*]] = and i64 [[TMP0]], 15
; CHECK-NEXT:    tail call void @foo(i64 noundef [[TMP1]])
; CHECK-NEXT:    [[ADD_PTR]] = getelementptr inbounds i8, ptr [[PTR_ADDR_0]], i64 16
; CHECK-NEXT:    br label [[WHILE_BODY]]
;
entry:
  br label %while.body

while.body:                                       ; preds = %entry, %while.body
  %ptr.addr.0 = phi ptr [ %ptr, %entry ], [ %add.ptr, %while.body ]
  %0 = ptrtoint ptr %ptr.addr.0 to i64
  %and = and i64 %0, 15                           ; loop invariant
  tail call void @foo(i64 noundef %and)
  %add.ptr = getelementptr inbounds i8, ptr %ptr.addr.0, i64 16
  br label %while.body
}

