; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=indvars -S %s | FileCheck %s

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128-Fn32"

define void @rewrite_preserve_add_nsw(i32 %a) {
; CHECK-LABEL: define void @rewrite_preserve_add_nsw(
; CHECK-SAME: i32 [[A:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[A]], 4
; CHECK-NEXT:    call void @use(i32 noundef [[ADD]])
; CHECK-NEXT:    [[PRE:%.*]] = icmp sgt i32 [[A]], -4
; CHECK-NEXT:    br i1 [[PRE]], label [[LOOP_PREHEADER:%.*]], label [[EXIT:%.*]]
; CHECK:       loop.preheader:
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[IV_NEXT:%.*]], [[LOOP]] ], [ 0, [[LOOP_PREHEADER]] ]
; CHECK-NEXT:    call void @clobber()
; CHECK-NEXT:    [[IV_NEXT]] = add nuw i32 [[IV]], 1
; CHECK-NEXT:    [[EC:%.*]] = icmp slt i32 [[IV]], [[ADD]]
; CHECK-NEXT:    br i1 [[EC]], label [[LOOP]], label [[EXIT_LOOPEXIT:%.*]]
; CHECK:       exit.loopexit:
; CHECK-NEXT:    br label [[EXIT]]
; CHECK:       exit:
; CHECK-NEXT:    ret void
;
entry:
  %add = add nsw i32 %a, 4
  call void @use(i32 noundef %add)
  %pre = icmp sgt i32 %a, -4
  br i1 %pre, label %loop, label %exit

loop:
  %iv = phi i32 [ 0, %entry ], [ %iv.next, %loop ]
  call void @clobber()
  %iv.next = add i32 %iv, 1
  %ec = icmp slt i32 %iv, %add
  br i1 %ec, label %loop, label %exit

exit:
  ret void
}

declare void @clobber()
declare void @use(i32)
