; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -passes=loop-vectorize -S %s | FileCheck %s

target triple = "arm64-apple-macosx"

; FIXME: should vectorize without predicates.
define void @urem_lookup(ptr noalias %src, ptr noalias %dst, ptr noalias %tbl, i64 %N) #0 {
; CHECK-LABEL: define void @urem_lookup(
; CHECK-SAME: ptr noalias [[SRC:%.*]], ptr noalias [[DST:%.*]], ptr noalias [[TBL:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP_SRC:%.*]] = getelementptr inbounds float, ptr [[SRC]], i64 [[IV]]
; CHECK-NEXT:    [[X:%.*]] = load float, ptr [[GEP_SRC]], align 4
; CHECK-NEXT:    [[CLAMPED:%.*]] = urem i64 [[IV]], 4
; CHECK-NEXT:    [[GEP_TBL:%.*]] = getelementptr inbounds float, ptr [[TBL]], i64 [[CLAMPED]]
; CHECK-NEXT:    [[T:%.*]] = load float, ptr [[GEP_TBL]], align 4
; CHECK-NEXT:    [[M1:%.*]] = fmul float [[X]], [[T]]
; CHECK-NEXT:    [[M2:%.*]] = fadd float [[M1]], [[X]]
; CHECK-NEXT:    [[M3:%.*]] = fmul float [[M2]], [[T]]
; CHECK-NEXT:    [[GEP_DST:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[IV]]
; CHECK-NEXT:    store float [[M3]], ptr [[GEP_DST]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[COND]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %gep.src = getelementptr inbounds float, ptr %src, i64 %iv
  %x = load float, ptr %gep.src
  %clamped = urem i64 %iv, 4
  %gep.tbl = getelementptr inbounds float, ptr %tbl, i64 %clamped
  %t = load float, ptr %gep.tbl
  %m1 = fmul float %x, %t
  %m2 = fadd float %m1, %x
  %m3 = fmul float %m2, %t
  %gep.dst = getelementptr inbounds float, ptr %dst, i64 %iv
  store float %m3, ptr %gep.dst
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %N
  br i1 %cond, label %exit, label %loop

exit:
  ret void
}

; The stride-2 interleave group on %B survives, no predicate should be needed.
; FIXME: only predicates required by surviving group members should be added.
define void @over_conservative_merge(ptr noalias %A, ptr noalias %B, i64 %N) #0 {
; CHECK-LABEL: define void @over_conservative_merge(
; CHECK-SAME: ptr noalias [[A:%.*]], ptr noalias [[B:%.*]], i64 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CLAMPED:%.*]] = urem i64 [[INDEX]], 4
; CHECK-NEXT:    [[GEP_A:%.*]] = getelementptr float, ptr [[A]], i64 [[CLAMPED]]
; CHECK-NEXT:    [[LA:%.*]] = load float, ptr [[GEP_A]], align 4
; CHECK-NEXT:    [[M7:%.*]] = fmul float [[LA]], [[LA]]
; CHECK-NEXT:    [[TMP12:%.*]] = shl nuw nsw i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[TMP12]]
; CHECK-NEXT:    store float [[M7]], ptr [[TMP13]], align 4
; CHECK-NEXT:    [[IDX1:%.*]] = add nuw nsw i64 [[TMP12]], 1
; CHECK-NEXT:    [[GEP_B1:%.*]] = getelementptr inbounds float, ptr [[B]], i64 [[IDX1]]
; CHECK-NEXT:    store float [[M7]], ptr [[GEP_B1]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[INDEX]], 1
; CHECK-NEXT:    [[COND:%.*]] = icmp eq i64 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[COND]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %clamped = urem i64 %iv, 4
  %gep.A = getelementptr float, ptr %A, i64 %clamped
  %la = load float, ptr %gep.A
  %m1 = fmul float %la, %la
  %idx0 = shl nuw nsw i64 %iv, 1
  %gep.B0 = getelementptr inbounds float, ptr %B, i64 %idx0
  store float %m1, ptr %gep.B0
  %idx1 = add nuw nsw i64 %idx0, 1
  %gep.B1 = getelementptr inbounds float, ptr %B, i64 %idx1
  store float %m1, ptr %gep.B1
  %iv.next = add nuw nsw i64 %iv, 1
  %cond = icmp eq i64 %iv.next, %N
  br i1 %cond, label %exit, label %loop

exit:
  ret void
}

attributes #0 = { "target-features"="+sve" optsize }
