; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S < %s -p loop-vectorize -mtriple aarch64 | FileCheck %s
; RUN: opt -S < %s -p loop-vectorize -mtriple aarch64 -mattr=+sve | FileCheck %s --check-prefix=SVE

declare void @init_mem(ptr, i64)

define i8 @predicate_exit_block_successors(ptr %p0) {
; CHECK-LABEL: define i8 @predicate_exit_block_successors(
; CHECK-SAME: ptr [[P0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[P1:%.*]] = alloca [1024 x i8], align 4
; CHECK-NEXT:    [[P2:%.*]] = alloca [1024 x i8], align 4
; CHECK-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; CHECK-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[TMP24:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[PRED_LOAD_IF7:.*]] ], [ 3, %[[ENTRY]] ]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP24]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i8, ptr [[TMP13]], align 1
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[TMP24]]
; CHECK-NEXT:    [[TMP20:%.*]] = load i8, ptr [[TMP19]], align 1
; CHECK-NEXT:    [[TMP23:%.*]] = icmp eq i8 [[TMP14]], [[TMP20]]
; CHECK-NEXT:    br i1 [[TMP23]], label %[[PRED_LOAD_IF7]], label %[[PRED_LOAD_CONTINUE8:.*]]
; CHECK:       [[PRED_LOAD_IF7]]:
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i8, ptr [[P0]], i64 [[TMP24]]
; CHECK-NEXT:    [[TMP26:%.*]] = load i8, ptr [[TMP25]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[TMP24]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[VECTOR_BODY]], label %[[PRED_LOAD_CONTINUE8]]
; CHECK:       [[PRED_LOAD_CONTINUE8]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i8 [ [[TMP14]], %[[VECTOR_BODY]] ], [ [[TMP26]], %[[PRED_LOAD_IF7]] ]
; CHECK-NEXT:    ret i8 [[RETVAL]]
;
; SVE-LABEL: define i8 @predicate_exit_block_successors(
; SVE-SAME: ptr [[P0:%.*]]) #[[ATTR0:[0-9]+]] {
; SVE-NEXT:  [[ENTRY:.*]]:
; SVE-NEXT:    [[P1:%.*]] = alloca [1024 x i8], align 4
; SVE-NEXT:    [[P2:%.*]] = alloca [1024 x i8], align 4
; SVE-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; SVE-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 4
; SVE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; SVE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; SVE:       [[VECTOR_PH]]:
; SVE-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; SVE-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 4
; SVE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP3]]
; SVE-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; SVE-NEXT:    [[TMP4:%.*]] = add i64 3, [[N_VEC]]
; SVE-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; SVE:       [[VECTOR_BODY]]:
; SVE-NEXT:    [[INDEX1:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT3:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; SVE-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX1]]
; SVE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[OFFSET_IDX]]
; SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP6]], align 1
; SVE-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[OFFSET_IDX]]
; SVE-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 16 x i8>, ptr [[TMP7]], align 1
; SVE-NEXT:    [[TMP8:%.*]] = icmp ne <vscale x 16 x i8> [[WIDE_LOAD]], [[WIDE_LOAD2]]
; SVE-NEXT:    [[TMP9:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv16i1(<vscale x 16 x i1> [[TMP8]], i1 false)
; SVE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP9]], i64 0
; SVE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; SVE-NEXT:    [[TMP10:%.*]] = icmp ult <vscale x 16 x i64> [[TMP5]], [[BROADCAST_SPLAT]]
; SVE-NEXT:    [[TMP11:%.*]] = getelementptr i8, ptr [[P0]], i64 [[OFFSET_IDX]]
; SVE-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP11]], <vscale x 16 x i1> [[TMP10]], <vscale x 16 x i8> poison)
; SVE-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX1]], [[TMP3]]
; SVE-NEXT:    [[TMP12:%.*]] = freeze <vscale x 16 x i1> [[TMP8]]
; SVE-NEXT:    [[TMP13:%.*]] = call i1 @llvm.vector.reduce.or.nxv16i1(<vscale x 16 x i1> [[TMP12]])
; SVE-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT3]], [[N_VEC]]
; SVE-NEXT:    br i1 [[TMP13]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; SVE:       [[VECTOR_BODY_INTERIM]]:
; SVE-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; SVE:       [[MIDDLE_BLOCK]]:
; SVE-NEXT:    [[TMP15:%.*]] = call i32 @llvm.vscale.i32()
; SVE-NEXT:    [[TMP16:%.*]] = mul nuw i32 [[TMP15]], 16
; SVE-NEXT:    [[TMP17:%.*]] = sub i32 [[TMP16]], 1
; SVE-NEXT:    [[TMP18:%.*]] = extractelement <vscale x 16 x i8> [[WIDE_MASKED_LOAD]], i32 [[TMP17]]
; SVE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; SVE-NEXT:    br i1 [[CMP_N]], label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; SVE:       [[VECTOR_EARLY_EXIT]]:
; SVE-NEXT:    [[TMP19:%.*]] = extractelement <vscale x 16 x i8> [[WIDE_LOAD]], i64 [[TMP9]]
; SVE-NEXT:    br label %[[LOOP_END]]
; SVE:       [[SCALAR_PH]]:
; SVE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP4]], %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ]
; SVE-NEXT:    br label %[[LOOP:.*]]
; SVE:       [[LOOP]]:
; SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; SVE-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; SVE-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; SVE-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; SVE-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; SVE-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; SVE-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; SVE:       [[LOOP_INC]]:
; SVE-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[P0]], i64 [[INDEX]]
; SVE-NEXT:    [[LD3:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; SVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; SVE-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; SVE-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP3:![0-9]+]]
; SVE:       [[LOOP_END]]:
; SVE-NEXT:    [[RETVAL:%.*]] = phi i8 [ [[LD1]], %[[LOOP]] ], [ [[LD3]], %[[LOOP_INC]] ], [ [[TMP18]], %[[MIDDLE_BLOCK]] ], [ [[TMP19]], %[[VECTOR_EARLY_EXIT]] ]
; SVE-NEXT:    ret i8 [[RETVAL]]
;
entry:
  %p1 = alloca [1024 x i8]
  %p2 = alloca [1024 x i8]
  call void @init_mem(ptr %p1, i64 1024)
  call void @init_mem(ptr %p2, i64 1024)
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %arrayidx1 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %arrayidx1, align 1
  %cmp3 = icmp eq i8 %ld1, %ld2
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %arrayidx2 = getelementptr inbounds i8, ptr %p0, i64 %index
  %ld3 = load i8, ptr %arrayidx2
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i8 [ %ld1, %loop ], [ %ld3, %loop.inc ]
  ret i8 %retval
}

define i8 @predicate_exit_block_successors_multi(ptr %p0) {
; CHECK-LABEL: define i8 @predicate_exit_block_successors_multi(
; CHECK-SAME: ptr [[P0:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[P1:%.*]] = alloca [1024 x i8], align 4
; CHECK-NEXT:    [[P2:%.*]] = alloca [1024 x i8], align 4
; CHECK-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; CHECK-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[TMP28:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[PRED_LOAD_IF9:.*]] ], [ 3, %[[ENTRY]] ]
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP28]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; CHECK-NEXT:    [[TMP21:%.*]] = icmp eq i8 [[LD2]], 1
; CHECK-NEXT:    br i1 [[TMP21]], label %[[LOOP_INC:.*]], label %[[PRED_LOAD_CONTINUE8:.*]]
; CHECK:       [[PRED_LOAD_CONTINUE8]]:
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[TMP28]]
; CHECK-NEXT:    [[LD3:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[LD3]], 1
; CHECK-NEXT:    br i1 [[CMP2]], label %[[LOOP_INC]], label %[[PRED_LOAD_IF9]]
; CHECK:       [[PRED_LOAD_IF9]]:
; CHECK-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i8, ptr [[P0]], i64 [[TMP28]]
; CHECK-NEXT:    [[TMP30:%.*]] = load i8, ptr [[TMP29]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[TMP28]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[VECTOR_BODY]], label %[[LOOP_INC]]
; CHECK:       [[LOOP_INC]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i8 [ [[LD2]], %[[VECTOR_BODY]] ], [ [[LD3]], %[[PRED_LOAD_CONTINUE8]] ], [ [[TMP30]], %[[PRED_LOAD_IF9]] ]
; CHECK-NEXT:    ret i8 [[RETVAL]]
;
; SVE-LABEL: define i8 @predicate_exit_block_successors_multi(
; SVE-SAME: ptr [[P0:%.*]]) #[[ATTR0]] {
; SVE-NEXT:  [[ENTRY:.*]]:
; SVE-NEXT:    [[P1:%.*]] = alloca [1024 x i8], align 4
; SVE-NEXT:    [[P2:%.*]] = alloca [1024 x i8], align 4
; SVE-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; SVE-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; SVE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; SVE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 4
; SVE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; SVE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; SVE:       [[VECTOR_PH]]:
; SVE-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; SVE-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 4
; SVE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP3]]
; SVE-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; SVE-NEXT:    [[TMP4:%.*]] = add i64 3, [[N_VEC]]
; SVE-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; SVE-NEXT:    br label %[[VECTOR_BODY:.*]]
; SVE:       [[VECTOR_BODY]]:
; SVE-NEXT:    [[INDEX1:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT5:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; SVE-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX1]]
; SVE-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[OFFSET_IDX]]
; SVE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP6]], align 1
; SVE-NEXT:    [[TMP7:%.*]] = icmp eq <vscale x 16 x i8> [[WIDE_LOAD]], splat (i8 1)
; SVE-NEXT:    [[TMP8:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv16i1(<vscale x 16 x i1> [[TMP7]], i1 false)
; SVE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP8]], i64 0
; SVE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; SVE-NEXT:    [[TMP9:%.*]] = icmp ult <vscale x 16 x i64> [[TMP5]], [[BROADCAST_SPLAT]]
; SVE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[OFFSET_IDX]]
; SVE-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 16 x i8>, ptr [[TMP10]], align 1
; SVE-NEXT:    [[TMP11:%.*]] = icmp eq <vscale x 16 x i8> [[WIDE_LOAD2]], splat (i8 1)
; SVE-NEXT:    [[TMP12:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv16i1(<vscale x 16 x i1> [[TMP11]], i1 false)
; SVE-NEXT:    [[BROADCAST_SPLATINSERT3:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP12]], i64 0
; SVE-NEXT:    [[BROADCAST_SPLAT4:%.*]] = shufflevector <vscale x 16 x i64> [[BROADCAST_SPLATINSERT3]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; SVE-NEXT:    [[TMP13:%.*]] = icmp ult <vscale x 16 x i64> [[TMP5]], [[BROADCAST_SPLAT4]]
; SVE-NEXT:    [[TMP14:%.*]] = select <vscale x 16 x i1> [[TMP9]], <vscale x 16 x i1> [[TMP13]], <vscale x 16 x i1> zeroinitializer
; SVE-NEXT:    [[TMP15:%.*]] = getelementptr i8, ptr [[P0]], i64 [[OFFSET_IDX]]
; SVE-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 16 x i8> @llvm.masked.load.nxv16i8.p0(ptr align 1 [[TMP15]], <vscale x 16 x i1> [[TMP14]], <vscale x 16 x i8> poison)
; SVE-NEXT:    [[INDEX_NEXT5]] = add nuw i64 [[INDEX1]], [[TMP3]]
; SVE-NEXT:    [[TMP16:%.*]] = select <vscale x 16 x i1> [[TMP7]], <vscale x 16 x i1> splat (i1 true), <vscale x 16 x i1> [[TMP11]]
; SVE-NEXT:    [[TMP17:%.*]] = freeze <vscale x 16 x i1> [[TMP16]]
; SVE-NEXT:    [[TMP18:%.*]] = call i1 @llvm.vector.reduce.or.nxv16i1(<vscale x 16 x i1> [[TMP17]])
; SVE-NEXT:    [[TMP19:%.*]] = icmp eq i64 [[INDEX_NEXT5]], [[N_VEC]]
; SVE-NEXT:    br i1 [[TMP18]], label %[[VECTOR_EARLY_EXIT_CHECK:.*]], label %[[VECTOR_BODY_INTERIM]]
; SVE:       [[VECTOR_BODY_INTERIM]]:
; SVE-NEXT:    br i1 [[TMP19]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; SVE:       [[MIDDLE_BLOCK]]:
; SVE-NEXT:    [[TMP20:%.*]] = call i32 @llvm.vscale.i32()
; SVE-NEXT:    [[TMP21:%.*]] = mul nuw i32 [[TMP20]], 16
; SVE-NEXT:    [[TMP22:%.*]] = sub i32 [[TMP21]], 1
; SVE-NEXT:    [[TMP23:%.*]] = extractelement <vscale x 16 x i8> [[WIDE_MASKED_LOAD]], i32 [[TMP22]]
; SVE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; SVE-NEXT:    br i1 [[CMP_N]], label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; SVE:       [[VECTOR_EARLY_EXIT_CHECK]]:
; SVE-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv16i1(<vscale x 16 x i1> [[TMP16]], i1 false)
; SVE-NEXT:    [[TMP24:%.*]] = extractelement <vscale x 16 x i1> [[TMP7]], i64 [[FIRST_ACTIVE_LANE]]
; SVE-NEXT:    br i1 [[TMP24]], label %[[VECTOR_EARLY_EXIT_0:.*]], label %[[VECTOR_EARLY_EXIT_1:.*]]
; SVE:       [[VECTOR_EARLY_EXIT_1]]:
; SVE-NEXT:    [[TMP25:%.*]] = extractelement <vscale x 16 x i8> [[WIDE_LOAD2]], i64 [[FIRST_ACTIVE_LANE]]
; SVE-NEXT:    br label %[[LOOP_END]]
; SVE:       [[VECTOR_EARLY_EXIT_0]]:
; SVE-NEXT:    [[TMP26:%.*]] = extractelement <vscale x 16 x i8> [[WIDE_LOAD]], i64 [[FIRST_ACTIVE_LANE]]
; SVE-NEXT:    br label %[[LOOP_END]]
; SVE:       [[SCALAR_PH]]:
; SVE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP4]], %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ]
; SVE-NEXT:    br label %[[LOOP:.*]]
; SVE:       [[LOOP]]:
; SVE-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; SVE-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; SVE-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; SVE-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], 1
; SVE-NEXT:    br i1 [[CMP3]], label %[[LOOP_END]], label %[[NEXT:.*]]
; SVE:       [[NEXT]]:
; SVE-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; SVE-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; SVE-NEXT:    [[CMP2:%.*]] = icmp eq i8 [[LD2]], 1
; SVE-NEXT:    br i1 [[CMP2]], label %[[LOOP_END]], label %[[LOOP_INC]]
; SVE:       [[LOOP_INC]]:
; SVE-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[P0]], i64 [[INDEX]]
; SVE-NEXT:    [[LD3:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; SVE-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; SVE-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; SVE-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP5:![0-9]+]]
; SVE:       [[LOOP_END]]:
; SVE-NEXT:    [[RETVAL:%.*]] = phi i8 [ [[LD1]], %[[LOOP]] ], [ [[LD2]], %[[NEXT]] ], [ [[LD3]], %[[LOOP_INC]] ], [ [[TMP23]], %[[MIDDLE_BLOCK]] ], [ [[TMP26]], %[[VECTOR_EARLY_EXIT_0]] ], [ [[TMP25]], %[[VECTOR_EARLY_EXIT_1]] ]
; SVE-NEXT:    ret i8 [[RETVAL]]
;
entry:
  %p1 = alloca [1024 x i8]
  %p2 = alloca [1024 x i8]
  call void @init_mem(ptr %p1, i64 1024)
  call void @init_mem(ptr %p2, i64 1024)
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %cmp3 = icmp eq i8 %ld1, 1
  br i1 %cmp3, label %loop.end, label %next

next:
  %arrayidx1 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %arrayidx1, align 1
  %cmp2 = icmp eq i8 %ld2, 1
  br i1 %cmp2, label %loop.end, label %loop.inc

loop.inc:
  %arrayidx2 = getelementptr inbounds i8, ptr %p0, i64 %index
  %ld3 = load i8, ptr %arrayidx2
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i8 [ %ld1, %loop ], [%ld2, %next], [ %ld3, %loop.inc ]
  ret i8 %retval
}
;.
; SVE: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; SVE: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; SVE: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; SVE: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
; SVE: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; SVE: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META1]]}
;.
