; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -p loop-vectorize < %s | FileCheck %s
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64"
; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable
define dso_local void @f64_to_q15(ptr nofree noundef readonly captures(none) %pSrc, ptr nofree noundef writeonly captures(none) %pDst, i32 noundef %blockSize) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local void @f64_to_q15(
; CHECK-SAME: ptr nofree noundef readonly captures(none) [[PSRC:%.*]], ptr nofree noundef writeonly captures(none) [[PDST:%.*]], i32 noundef [[BLOCKSIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[BLOCKSIZE]], 2
; CHECK-NEXT:    [[CMP_NOT65:%.*]] = icmp eq i32 [[SHR]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT65]], label %[[WHILE_END:.*]], label %[[WHILE_BODY_PREHEADER:.*]]
; CHECK:       [[WHILE_BODY_PREHEADER]]:
; CHECK-NEXT:    [[TMP34:%.*]] = zext i32 [[BLOCKSIZE]] to i64
; CHECK-NEXT:    [[TMP35:%.*]] = lshr i64 [[TMP34]], 2
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP35]], 8
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP35]], 2
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP35]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP36:%.*]] = shl i64 [[N_VEC]], 5
; CHECK-NEXT:    [[TMP37:%.*]] = getelementptr i8, ptr [[PSRC]], i64 [[TMP36]]
; CHECK-NEXT:    [[TMP38:%.*]] = trunc i64 [[N_VEC]] to i32
; CHECK-NEXT:    [[TMP39:%.*]] = sub i32 [[SHR]], [[TMP38]]
; CHECK-NEXT:    [[TMP40:%.*]] = shl i64 [[N_VEC]], 3
; CHECK-NEXT:    [[TMP41:%.*]] = getelementptr i8, ptr [[PDST]], i64 [[TMP40]]
; CHECK-NEXT:    br label %[[WHILE_BODY:.*]]
; CHECK:       [[WHILE_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[WHILE_BODY]] ]
; CHECK-NEXT:    [[TMP42:%.*]] = shl i64 [[INDEX]], 5
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[PSRC]], i64 [[TMP42]]
; CHECK-NEXT:    [[TMP43:%.*]] = shl i64 [[INDEX]], 3
; CHECK-NEXT:    [[NEXT_GEP1:%.*]] = getelementptr i8, ptr [[PDST]], i64 [[TMP43]]
; CHECK-NEXT:    [[STRIDED_VEC4:%.*]] = load <8 x double>, ptr [[NEXT_GEP]], align 8, !tbaa [[DOUBLE_TBAA7:![0-9]+]]
; CHECK-NEXT:    [[TMP25:%.*]] = fmul <8 x double> [[STRIDED_VEC4]], splat (double 3.276800e+04)
; CHECK-NEXT:    [[TMP26:%.*]] = fptosi <8 x double> [[TMP25]] to <8 x i32>
; CHECK-NEXT:    [[TMP27:%.*]] = call <8 x i32> @llvm.smax.v8i32(<8 x i32> [[TMP26]], <8 x i32> splat (i32 -32768))
; CHECK-NEXT:    [[TMP28:%.*]] = call <8 x i32> @llvm.smin.v8i32(<8 x i32> [[TMP27]], <8 x i32> splat (i32 32767))
; CHECK-NEXT:    [[TMP29:%.*]] = trunc nsw <8 x i32> [[TMP28]] to <8 x i16>
; CHECK-NEXT:    store <8 x i16> [[TMP29]], ptr [[NEXT_GEP1]], align 2, !tbaa [[SHORT_TBAA9:![0-9]+]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP33:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP33]], label %[[MIDDLE_BLOCK:.*]], label %[[WHILE_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP35]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[WHILE_END_LOOPEXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi ptr [ [[TMP37]], %[[MIDDLE_BLOCK]] ], [ [[PSRC]], %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL2:%.*]] = phi i32 [ [[TMP39]], %[[MIDDLE_BLOCK]] ], [ [[SHR]], %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    [[BC_RESUME_VAL3:%.*]] = phi ptr [ [[TMP41]], %[[MIDDLE_BLOCK]] ], [ [[PDST]], %[[WHILE_BODY_PREHEADER]] ]
; CHECK-NEXT:    br label %[[WHILE_BODY1:.*]]
; CHECK:       [[WHILE_BODY1]]:
; CHECK-NEXT:    [[PIN_068:%.*]] = phi ptr [ [[INCDEC_PTR15:%.*]], %[[WHILE_BODY1]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[BLKCNT_067:%.*]] = phi i32 [ [[DEC:%.*]], %[[WHILE_BODY1]] ], [ [[BC_RESUME_VAL2]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[PDST_ADDR_066:%.*]] = phi ptr [ [[INCDEC_PTR20:%.*]], %[[WHILE_BODY1]] ], [ [[BC_RESUME_VAL3]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[INCDEC_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[PIN_068]], i64 8
; CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr [[PIN_068]], align 8, !tbaa [[DOUBLE_TBAA7]]
; CHECK-NEXT:    [[MUL:%.*]] = fmul double [[TMP0]], 3.276800e+04
; CHECK-NEXT:    [[CONV:%.*]] = fptosi double [[MUL]] to i32
; CHECK-NEXT:    [[TMP1:%.*]] = tail call i32 @llvm.smax.i32(i32 [[CONV]], i32 -32768)
; CHECK-NEXT:    [[SPEC_SELECT_I64:%.*]] = tail call i32 @llvm.smin.i32(i32 [[TMP1]], i32 32767)
; CHECK-NEXT:    [[CONV1:%.*]] = trunc nsw i32 [[SPEC_SELECT_I64]] to i16
; CHECK-NEXT:    [[INCDEC_PTR2:%.*]] = getelementptr inbounds nuw i8, ptr [[PDST_ADDR_066]], i64 2
; CHECK-NEXT:    store i16 [[CONV1]], ptr [[PDST_ADDR_066]], align 2, !tbaa [[SHORT_TBAA9]]
; CHECK-NEXT:    [[INCDEC_PTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[PIN_068]], i64 16
; CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[INCDEC_PTR]], align 8, !tbaa [[DOUBLE_TBAA7]]
; CHECK-NEXT:    [[MUL4:%.*]] = fmul double [[TMP2]], 3.276800e+04
; CHECK-NEXT:    [[CONV5:%.*]] = fptosi double [[MUL4]] to i32
; CHECK-NEXT:    [[TMP3:%.*]] = tail call i32 @llvm.smax.i32(i32 [[CONV5]], i32 -32768)
; CHECK-NEXT:    [[SPEC_SELECT_I59:%.*]] = tail call i32 @llvm.smin.i32(i32 [[TMP3]], i32 32767)
; CHECK-NEXT:    [[CONV7:%.*]] = trunc nsw i32 [[SPEC_SELECT_I59]] to i16
; CHECK-NEXT:    [[INCDEC_PTR8:%.*]] = getelementptr inbounds nuw i8, ptr [[PDST_ADDR_066]], i64 4
; CHECK-NEXT:    store i16 [[CONV7]], ptr [[INCDEC_PTR2]], align 2, !tbaa [[SHORT_TBAA9]]
; CHECK-NEXT:    [[INCDEC_PTR9:%.*]] = getelementptr inbounds nuw i8, ptr [[PIN_068]], i64 24
; CHECK-NEXT:    [[TMP4:%.*]] = load double, ptr [[INCDEC_PTR3]], align 8, !tbaa [[DOUBLE_TBAA7]]
; CHECK-NEXT:    [[MUL10:%.*]] = fmul double [[TMP4]], 3.276800e+04
; CHECK-NEXT:    [[CONV11:%.*]] = fptosi double [[MUL10]] to i32
; CHECK-NEXT:    [[TMP5:%.*]] = tail call i32 @llvm.smax.i32(i32 [[CONV11]], i32 -32768)
; CHECK-NEXT:    [[SPEC_SELECT_I54:%.*]] = tail call i32 @llvm.smin.i32(i32 [[TMP5]], i32 32767)
; CHECK-NEXT:    [[CONV13:%.*]] = trunc nsw i32 [[SPEC_SELECT_I54]] to i16
; CHECK-NEXT:    [[INCDEC_PTR14:%.*]] = getelementptr inbounds nuw i8, ptr [[PDST_ADDR_066]], i64 6
; CHECK-NEXT:    store i16 [[CONV13]], ptr [[INCDEC_PTR8]], align 2, !tbaa [[SHORT_TBAA9]]
; CHECK-NEXT:    [[INCDEC_PTR15]] = getelementptr inbounds nuw i8, ptr [[PIN_068]], i64 32
; CHECK-NEXT:    [[TMP6:%.*]] = load double, ptr [[INCDEC_PTR9]], align 8, !tbaa [[DOUBLE_TBAA7]]
; CHECK-NEXT:    [[MUL16:%.*]] = fmul double [[TMP6]], 3.276800e+04
; CHECK-NEXT:    [[CONV17:%.*]] = fptosi double [[MUL16]] to i32
; CHECK-NEXT:    [[TMP7:%.*]] = tail call i32 @llvm.smax.i32(i32 [[CONV17]], i32 -32768)
; CHECK-NEXT:    [[SPEC_SELECT_I49:%.*]] = tail call i32 @llvm.smin.i32(i32 [[TMP7]], i32 32767)
; CHECK-NEXT:    [[CONV19:%.*]] = trunc nsw i32 [[SPEC_SELECT_I49]] to i16
; CHECK-NEXT:    [[INCDEC_PTR20]] = getelementptr inbounds nuw i8, ptr [[PDST_ADDR_066]], i64 8
; CHECK-NEXT:    store i16 [[CONV19]], ptr [[INCDEC_PTR14]], align 2, !tbaa [[SHORT_TBAA9]]
; CHECK-NEXT:    [[DEC]] = add nsw i32 [[BLKCNT_067]], -1
; CHECK-NEXT:    [[CMP_NOT:%.*]] = icmp eq i32 [[DEC]], 0
; CHECK-NEXT:    br i1 [[CMP_NOT]], label %[[WHILE_END_LOOPEXIT]], label %[[WHILE_BODY1]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       [[WHILE_END_LOOPEXIT]]:
; CHECK-NEXT:    [[INCDEC_PTR15_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR15]], %[[WHILE_BODY1]] ], [ [[TMP37]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[INCDEC_PTR20_LCSSA:%.*]] = phi ptr [ [[INCDEC_PTR20]], %[[WHILE_BODY1]] ], [ [[TMP41]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    br label %[[WHILE_END]]
; CHECK:       [[WHILE_END]]:
; CHECK-NEXT:    [[PDST_ADDR_0_LCSSA:%.*]] = phi ptr [ [[PDST]], %[[ENTRY]] ], [ [[INCDEC_PTR20_LCSSA]], %[[WHILE_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[PIN_0_LCSSA:%.*]] = phi ptr [ [[PSRC]], %[[ENTRY]] ], [ [[INCDEC_PTR15_LCSSA]], %[[WHILE_END_LOOPEXIT]] ]
; CHECK-NEXT:    [[REM:%.*]] = and i32 [[BLOCKSIZE]], 3
; CHECK-NEXT:    [[CMP22_NOT70:%.*]] = icmp eq i32 [[REM]], 0
; CHECK-NEXT:    br i1 [[CMP22_NOT70]], label %[[WHILE_END32:.*]], label %[[WHILE_BODY24_PREHEADER:.*]]
; CHECK:       [[WHILE_BODY24_PREHEADER]]:
; CHECK-NEXT:    br label %[[WHILE_BODY24:.*]]
; CHECK:       [[WHILE_BODY24]]:
; CHECK-NEXT:    [[PIN_173:%.*]] = phi ptr [ [[INCDEC_PTR25:%.*]], %[[WHILE_BODY24]] ], [ [[PIN_0_LCSSA]], %[[WHILE_BODY24_PREHEADER]] ]
; CHECK-NEXT:    [[BLKCNT_172:%.*]] = phi i32 [ [[DEC31:%.*]], %[[WHILE_BODY24]] ], [ [[REM]], %[[WHILE_BODY24_PREHEADER]] ]
; CHECK-NEXT:    [[PDST_ADDR_171:%.*]] = phi ptr [ [[INCDEC_PTR30:%.*]], %[[WHILE_BODY24]] ], [ [[PDST_ADDR_0_LCSSA]], %[[WHILE_BODY24_PREHEADER]] ]
; CHECK-NEXT:    [[INCDEC_PTR25]] = getelementptr inbounds nuw i8, ptr [[PIN_173]], i64 8
; CHECK-NEXT:    [[TMP8:%.*]] = load double, ptr [[PIN_173]], align 8, !tbaa [[DOUBLE_TBAA7]]
; CHECK-NEXT:    [[MUL26:%.*]] = fmul double [[TMP8]], 3.276800e+04
; CHECK-NEXT:    [[CONV27:%.*]] = fptosi double [[MUL26]] to i32
; CHECK-NEXT:    [[TMP9:%.*]] = tail call i32 @llvm.smax.i32(i32 [[CONV27]], i32 -32768)
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = tail call i32 @llvm.smin.i32(i32 [[TMP9]], i32 32767)
; CHECK-NEXT:    [[CONV29:%.*]] = trunc nsw i32 [[SPEC_SELECT_I]] to i16
; CHECK-NEXT:    [[INCDEC_PTR30]] = getelementptr inbounds nuw i8, ptr [[PDST_ADDR_171]], i64 2
; CHECK-NEXT:    store i16 [[CONV29]], ptr [[PDST_ADDR_171]], align 2, !tbaa [[SHORT_TBAA9]]
; CHECK-NEXT:    [[DEC31]] = add nsw i32 [[BLKCNT_172]], -1
; CHECK-NEXT:    [[CMP22_NOT:%.*]] = icmp eq i32 [[DEC31]], 0
; CHECK-NEXT:    br i1 [[CMP22_NOT]], label %[[WHILE_END32_LOOPEXIT:.*]], label %[[WHILE_BODY24]], !llvm.loop [[LOOP16:![0-9]+]]
; CHECK:       [[WHILE_END32_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[WHILE_END32]]
; CHECK:       [[WHILE_END32]]:
; CHECK-NEXT:    ret void
;
entry:
  %shr = lshr i32 %blockSize, 2
  %cmp.not65 = icmp eq i32 %shr, 0
  br i1 %cmp.not65, label %while.end, label %while.body.preheader

while.body.preheader:                             ; preds = %entry
  br label %while.body

while.body:                                       ; preds = %while.body.preheader, %while.body
  %pIn.068 = phi ptr [ %incdec.ptr15, %while.body ], [ %pSrc, %while.body.preheader ]
  %blkCnt.067 = phi i32 [ %dec, %while.body ], [ %shr, %while.body.preheader ]
  %pDst.addr.066 = phi ptr [ %incdec.ptr20, %while.body ], [ %pDst, %while.body.preheader ]
  %incdec.ptr = getelementptr inbounds nuw i8, ptr %pIn.068, i64 8
  %0 = load double, ptr %pIn.068, align 8, !tbaa !7
  %mul = fmul double %0, 3.276800e+04
  %conv = fptosi double %mul to i32
  %1 = tail call i32 @llvm.smax.i32(i32 %conv, i32 -32768)
  %spec.select.i64 = tail call i32 @llvm.smin.i32(i32 %1, i32 32767)
  %conv1 = trunc nsw i32 %spec.select.i64 to i16
  %incdec.ptr2 = getelementptr inbounds nuw i8, ptr %pDst.addr.066, i64 2
  store i16 %conv1, ptr %pDst.addr.066, align 2, !tbaa !9
  %incdec.ptr3 = getelementptr inbounds nuw i8, ptr %pIn.068, i64 16
  %2 = load double, ptr %incdec.ptr, align 8, !tbaa !7
  %mul4 = fmul double %2, 3.276800e+04
  %conv5 = fptosi double %mul4 to i32
  %3 = tail call i32 @llvm.smax.i32(i32 %conv5, i32 -32768)
  %spec.select.i59 = tail call i32 @llvm.smin.i32(i32 %3, i32 32767)
  %conv7 = trunc nsw i32 %spec.select.i59 to i16
  %incdec.ptr8 = getelementptr inbounds nuw i8, ptr %pDst.addr.066, i64 4
  store i16 %conv7, ptr %incdec.ptr2, align 2, !tbaa !9
  %incdec.ptr9 = getelementptr inbounds nuw i8, ptr %pIn.068, i64 24
  %4 = load double, ptr %incdec.ptr3, align 8, !tbaa !7
  %mul10 = fmul double %4, 3.276800e+04
  %conv11 = fptosi double %mul10 to i32
  %5 = tail call i32 @llvm.smax.i32(i32 %conv11, i32 -32768)
  %spec.select.i54 = tail call i32 @llvm.smin.i32(i32 %5, i32 32767)
  %conv13 = trunc nsw i32 %spec.select.i54 to i16
  %incdec.ptr14 = getelementptr inbounds nuw i8, ptr %pDst.addr.066, i64 6
  store i16 %conv13, ptr %incdec.ptr8, align 2, !tbaa !9
  %incdec.ptr15 = getelementptr inbounds nuw i8, ptr %pIn.068, i64 32
  %6 = load double, ptr %incdec.ptr9, align 8, !tbaa !7
  %mul16 = fmul double %6, 3.276800e+04
  %conv17 = fptosi double %mul16 to i32
  %7 = tail call i32 @llvm.smax.i32(i32 %conv17, i32 -32768)
  %spec.select.i49 = tail call i32 @llvm.smin.i32(i32 %7, i32 32767)
  %conv19 = trunc nsw i32 %spec.select.i49 to i16
  %incdec.ptr20 = getelementptr inbounds nuw i8, ptr %pDst.addr.066, i64 8
  store i16 %conv19, ptr %incdec.ptr14, align 2, !tbaa !9
  %dec = add nsw i32 %blkCnt.067, -1
  %cmp.not = icmp eq i32 %dec, 0
  br i1 %cmp.not, label %while.end.loopexit, label %while.body, !llvm.loop !11

while.end.loopexit:                               ; preds = %while.body
  %incdec.ptr15.lcssa = phi ptr [ %incdec.ptr15, %while.body ]
  %incdec.ptr20.lcssa = phi ptr [ %incdec.ptr20, %while.body ]
  br label %while.end

while.end:                                        ; preds = %while.end.loopexit, %entry
  %pDst.addr.0.lcssa = phi ptr [ %pDst, %entry ], [ %incdec.ptr20.lcssa, %while.end.loopexit ]
  %pIn.0.lcssa = phi ptr [ %pSrc, %entry ], [ %incdec.ptr15.lcssa, %while.end.loopexit ]
  %rem = and i32 %blockSize, 3
  %cmp22.not70 = icmp eq i32 %rem, 0
  br i1 %cmp22.not70, label %while.end32, label %while.body24.preheader

while.body24.preheader:                           ; preds = %while.end
  br label %while.body24

while.body24:                                     ; preds = %while.body24.preheader, %while.body24
  %pIn.173 = phi ptr [ %incdec.ptr25, %while.body24 ], [ %pIn.0.lcssa, %while.body24.preheader ]
  %blkCnt.172 = phi i32 [ %dec31, %while.body24 ], [ %rem, %while.body24.preheader ]
  %pDst.addr.171 = phi ptr [ %incdec.ptr30, %while.body24 ], [ %pDst.addr.0.lcssa, %while.body24.preheader ]
  %incdec.ptr25 = getelementptr inbounds nuw i8, ptr %pIn.173, i64 8
  %8 = load double, ptr %pIn.173, align 8, !tbaa !7
  %mul26 = fmul double %8, 3.276800e+04
  %conv27 = fptosi double %mul26 to i32
  %9 = tail call i32 @llvm.smax.i32(i32 %conv27, i32 -32768)
  %spec.select.i = tail call i32 @llvm.smin.i32(i32 %9, i32 32767)
  %conv29 = trunc nsw i32 %spec.select.i to i16
  %incdec.ptr30 = getelementptr inbounds nuw i8, ptr %pDst.addr.171, i64 2
  store i16 %conv29, ptr %pDst.addr.171, align 2, !tbaa !9
  %dec31 = add nsw i32 %blkCnt.172, -1
  %cmp22.not = icmp eq i32 %dec31, 0
  br i1 %cmp22.not, label %while.end32.loopexit, label %while.body24, !llvm.loop !13

while.end32.loopexit:                             ; preds = %while.body24
  br label %while.end32

while.end32:                                      ; preds = %while.end32.loopexit, %while.end
  ret void
}

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smax.i32(i32, i32) #1

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.smin.i32(i32, i32) #1

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable "frame-pointer"="non-leaf-no-reserve" "no-trapping-math"="true" "stack-protector-buffer-size"="8" }
attributes #1 = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}
!llvm.errno.tbaa = !{!3}

!0 = !{i32 7, !"uwtable", i32 2}
!1 = !{i32 7, !"frame-pointer", i32 4}
!2 = !{!"clang version 23.0.0git (git@github.com:kamleshbhalui/llvm-project.git 448b725bb78bc288c5f6e3ad27856c92902f6537)"}
!3 = !{!4, !4, i64 0}
!4 = !{!"int", !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C/C++ TBAA"}
!7 = !{!8, !8, i64 0}
!8 = !{!"double", !5, i64 0}
!9 = !{!10, !10, i64 0}
!10 = !{!"short", !5, i64 0}
!11 = distinct !{!11, !12}
!12 = !{!"llvm.loop.mustprogress"}
!13 = distinct !{!13, !12}
;.
; CHECK: [[META5:![0-9]+]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
; CHECK: [[META6]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[DOUBLE_TBAA7]] = !{[[META8:![0-9]+]], [[META8]], i64 0}
; CHECK: [[META8]] = !{!"double", [[META5]], i64 0}
; CHECK: [[SHORT_TBAA9]] = !{[[META10:![0-9]+]], [[META10]], i64 0}
; CHECK: [[META10]] = !{!"short", [[META5]], i64 0}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META12:![0-9]+]], [[META13:![0-9]+]], [[META14:![0-9]+]]}
; CHECK: [[META12]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META13]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META14]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP15]] = distinct !{[[LOOP15]], [[META12]], [[META14]], [[META13]]}
; CHECK: [[LOOP16]] = distinct !{[[LOOP16]], [[META12]]}
;.
