; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK-SVE2p1,CHECK-SVE2p1-out
; RUN: opt < %s -passes=loop-vectorize \
; RUN:     -prefer-inloop-reductions -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK-SVE2p1,CHECK-SVE2p1-inl

; Test re-vectorisation of sdot-based reductions.
; Note that inloop reductions are not support by LV for RK=TargetIntAccumulation.
; As a consequence, -prefer-inloop-reductions has no effect, but it's still tested here.

define <4 x i32> @reduction_sum_4xi32(ptr noalias nocapture %A) {
; CHECK-SVE2p1-LABEL: @reduction_sum_4xi32(
; CHECK-SVE2p1-NEXT:  entry:
; CHECK-SVE2p1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-SVE2p1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP0]]
; CHECK-SVE2p1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-SVE2p1:       vector.ph:
; CHECK-SVE2p1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP0]]
; CHECK-SVE2p1-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-SVE2p1-NEXT:    [[TMP2:%.*]] = shl i64 [[N_VEC]], 2
; CHECK-SVE2p1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i32> @llvm.vector.insert.nxv4i32.v4i32(<vscale x 4 x i32> zeroinitializer, <4 x i32> zeroinitializer, i64 0)
; CHECK-SVE2p1-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-SVE2p1:       vector.body:
; CHECK-SVE2p1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ [[TMP3]], [[VECTOR_PH]] ], [ [[TMP5:%.*]], [[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-SVE2p1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[OFFSET_IDX]]
; CHECK-SVE2p1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP4]], align 4
; CHECK-SVE2p1-NEXT:    [[TMP5]] = call <vscale x 4 x i32> @llvm.aarch64.sve.sdot.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 16 x i8> [[WIDE_LOAD]], <vscale x 16 x i8> [[WIDE_LOAD]])
; CHECK-SVE2p1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-SVE2p1-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-SVE2p1:       middle.block:
; CHECK-SVE2p1-NEXT:    [[TMP7:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.nxv4i32(<4 x i32> zeroinitializer, <vscale x 4 x i32> [[TMP5]])
; CHECK-SVE2p1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[CMP_N]], label [[LOOP_EXIT:%.*]], label [[SCALAR_PH]]
; CHECK-SVE2p1:       scalar.ph:
; CHECK-SVE2p1-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP2]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-SVE2p1-NEXT:    [[BC_MERGE_RDX:%.*]] = phi <4 x i32> [ [[TMP7]], [[MIDDLE_BLOCK]] ], [ zeroinitializer, [[ENTRY]] ]
; CHECK-SVE2p1-NEXT:    br label [[SCALAR_LOOP:%.*]]
; CHECK-SVE2p1:       scalar.loop:
; CHECK-SVE2p1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], [[SCALAR_LOOP]] ], [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ]
; CHECK-SVE2p1-NEXT:    [[SUM_02:%.*]] = phi <4 x i32> [ [[L7:%.*]], [[SCALAR_LOOP]] ], [ [[BC_MERGE_RDX]], [[SCALAR_PH]] ]
; CHECK-SVE2p1-NEXT:    [[L2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-SVE2p1-NEXT:    [[L3:%.*]] = load <16 x i8>, ptr [[L2]], align 4
; CHECK-SVE2p1-NEXT:    [[L7]] = call <4 x i32> @llvm.aarch64.neon.sdot.v4i32.v16i8(<4 x i32> [[SUM_02]], <16 x i8> [[L3]], <16 x i8> [[L3]])
; CHECK-SVE2p1-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-SVE2p1-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-SVE2p1-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-SVE2p1-NEXT:    br i1 [[EXITCOND]], label [[LOOP_EXIT]], label [[SCALAR_LOOP]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK-SVE2p1:       loop.exit:
; CHECK-SVE2p1-NEXT:    [[SUM_0_LCSSA:%.*]] = phi <4 x i32> [ [[L7]], [[SCALAR_LOOP]] ], [ [[TMP7]], [[MIDDLE_BLOCK]] ]
; CHECK-SVE2p1-NEXT:    ret <4 x i32> [[SUM_0_LCSSA]]
;
entry:
  br label %scalar.loop

scalar.loop:                                           ; preds = %entry, %scalar.loop
  %indvars.iv = phi i64 [ %indvars.iv.next, %scalar.loop ], [ 0, %entry ]
  %sum.02 = phi <4 x i32> [ %l7, %scalar.loop ], [ zeroinitializer, %entry ]
  %l2 = getelementptr inbounds i32, ptr %A, i64 %indvars.iv
  %l3 = load <16 x i8>, ptr %l2, align 4
  %l7 = call <4 x i32> @llvm.aarch64.neon.sdot.v4i32.v16i8(<4 x i32> %sum.02, <16 x i8> %l3, <16 x i8> %l3)
  %indvars.iv.next = add i64 %indvars.iv, 4
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, 256
  br i1 %exitcond, label %loop.exit, label %scalar.loop

loop.exit:                                      ; preds = %scalar.loop
  %sum.0.lcssa = phi <4 x i32> [ %l7, %scalar.loop ]
  ret <4 x i32> %sum.0.lcssa
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK-SVE2p1-inl: {{.*}}
; CHECK-SVE2p1-out: {{.*}}
