; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "^scalar.ph" --version 6
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=2 -vectorize-vector-loops \
; RUN:     -scalable-vectorization=on -force-vector-width=1 \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK,IC2,VScale1-IC2
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -scalable-vectorization=on -force-vector-width=2 \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK,VScale2-IC1
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=2 -vectorize-vector-loops \
; RUN:     -scalable-vectorization=on -force-vector-width=2 \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK,IC2,VScale2-IC2

; Test how shufflevectors are re-vectorised for combinations of VF and IC.
; In general, revec only supports VF = vscale x 1. But we want to make sure IC>1 works.
; There are more tests in revec-shufflevector.ll for the standard VF = vscale x 1 case.


define void @extract_shuffle_idx1(ptr noalias nocapture noundef writeonly %a, ptr readonly %b) {
; IC2-LABEL: define void @extract_shuffle_idx1(
; IC2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; IC2-NEXT:  [[ENTRY:.*:]]
; IC2-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; IC2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP4]], 1
; IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; IC2:       [[VECTOR_PH]]:
; IC2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP4]], 1
; IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; IC2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; IC2:       [[VECTOR_BODY]]:
; IC2-NEXT:    [[TMP0:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; IC2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[TMP0]]
; IC2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds <8 x i16>, ptr [[TMP2]], i64 [[TMP4]]
; IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP2]], align 16
; IC2-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 8 x i16>, ptr [[TMP7]], align 16
; IC2-NEXT:    [[TMP17:%.*]] = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.vector.deinterleave.segments2.nxv8i16(<vscale x 8 x i16> [[WIDE_LOAD]])
; IC2-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } [[TMP17]], 1
; IC2-NEXT:    [[TMP10:%.*]] = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.vector.deinterleave.segments2.nxv8i16(<vscale x 8 x i16> [[WIDE_LOAD1]])
; IC2-NEXT:    [[TMP11:%.*]] = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } [[TMP10]], 1
; IC2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[TMP0]]
; IC2-NEXT:    [[TMP15:%.*]] = getelementptr inbounds <4 x i16>, ptr [[TMP8]], i64 [[TMP4]]
; IC2-NEXT:    store <vscale x 4 x i16> [[TMP9]], ptr [[TMP8]], align 16
; IC2-NEXT:    store <vscale x 4 x i16> [[TMP11]], ptr [[TMP15]], align 16
; IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[TMP0]], [[TMP3]]
; IC2-NEXT:    [[TMP16:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; IC2-NEXT:    br i1 [[TMP16]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; IC2:       [[MIDDLE_BLOCK]]:
; IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; IC2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; IC2:       [[SCALAR_PH]]:
;
; VScale2-IC1-LABEL: define void @extract_shuffle_idx1(
; VScale2-IC1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; VScale2-IC1-NEXT:  [[ENTRY:.*:]]
; VScale2-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-IC1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale2-IC1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2-IC1:       [[VECTOR_PH]]:
; VScale2-IC1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale2-IC1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2-IC1:       [[VECTOR_BODY]]:
; VScale2-IC1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-IC1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; VScale2-IC1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[ARRAYIDX]], align 16
; VScale2-IC1-NEXT:    [[TMP3:%.*]] = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.vector.deinterleave.segments2.nxv8i16(<vscale x 8 x i16> [[WIDE_LOAD]])
; VScale2-IC1-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } [[TMP3]], 1
; VScale2-IC1-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; VScale2-IC1-NEXT:    store <vscale x 4 x i16> [[TMP4]], ptr [[ARRAYIDX2]], align 16
; VScale2-IC1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDVARS_IV]], [[TMP0]]
; VScale2-IC1-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-IC1-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; VScale2-IC1:       [[MIDDLE_BLOCK]]:
; VScale2-IC1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-IC1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2-IC1:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx, align 16
  %result = shufflevector <8 x i16> %0, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @extract_shuffle_from_64bits(ptr noalias nocapture noundef writeonly %a, ptr readonly %b) {
; CHECK-LABEL: define void @extract_shuffle_from_64bits(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i16>, ptr [[ARRAYIDX]], align 16
; CHECK-NEXT:    [[RESULT:%.*]] = shufflevector <4 x i16> [[TMP0]], <4 x i16> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds <2 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <2 x i16> [[RESULT]], ptr [[ARRAYIDX2]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <4 x i16>, ptr %arrayidx, align 16
  %result = shufflevector <4 x i16> %0, <4 x i16> poison, <2 x i32> <i32 0, i32 1>
  %arrayidx2 = getelementptr inbounds <2 x i16>, ptr %a, i64 %indvars.iv
  store <2 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @unzip_even_same_src(ptr noalias nocapture noundef writeonly %a, ptr readonly %b) {
; IC2-LABEL: define void @unzip_even_same_src(
; IC2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0]] {
; IC2-NEXT:  [[ENTRY:.*:]]
; IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IC2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; IC2:       [[VECTOR_PH]]:
; IC2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; IC2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; IC2:       [[VECTOR_BODY]]:
; IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; IC2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDEX]]
; IC2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds <8 x i16>, ptr [[TMP4]], i64 [[TMP0]]
; IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP4]], align 16
; IC2-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 8 x i16>, ptr [[TMP7]], align 16
; IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(<vscale x 8 x i16> [[WIDE_LOAD]], <vscale x 8 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 0, i32 2, i32 4, i32 6>)
; IC2-NEXT:    [[TMP9:%.*]] = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(<vscale x 8 x i16> [[WIDE_LOAD1]], <vscale x 8 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 0, i32 2, i32 4, i32 6>)
; IC2-NEXT:    [[TMP10:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDEX]]
; IC2-NEXT:    [[TMP13:%.*]] = getelementptr inbounds <8 x i16>, ptr [[TMP10]], i64 [[TMP0]]
; IC2-NEXT:    store <vscale x 8 x i16> [[TMP8]], ptr [[TMP10]], align 16
; IC2-NEXT:    store <vscale x 8 x i16> [[TMP9]], ptr [[TMP13]], align 16
; IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; IC2-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; IC2-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; IC2:       [[MIDDLE_BLOCK]]:
; IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; IC2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; IC2:       [[SCALAR_PH]]:
;
; VScale2-IC1-LABEL: define void @unzip_even_same_src(
; VScale2-IC1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0]] {
; VScale2-IC1-NEXT:  [[ENTRY:.*:]]
; VScale2-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-IC1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale2-IC1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2-IC1:       [[VECTOR_PH]]:
; VScale2-IC1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale2-IC1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2-IC1:       [[VECTOR_BODY]]:
; VScale2-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-IC1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale2-IC1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP2]], align 16
; VScale2-IC1-NEXT:    [[TMP3:%.*]] = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(<vscale x 8 x i16> [[WIDE_LOAD]], <vscale x 8 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 0, i32 2, i32 4, i32 6>)
; VScale2-IC1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale2-IC1-NEXT:    store <vscale x 8 x i16> [[TMP3]], ptr [[TMP4]], align 16
; VScale2-IC1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale2-IC1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-IC1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; VScale2-IC1:       [[MIDDLE_BLOCK]]:
; VScale2-IC1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-IC1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2-IC1:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx, align 16
  %result = shufflevector <8 x i16> %0, <8 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 0, i32 2, i32 4, i32 6>
  %arrayidx2 = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @unzip_even_same_src_64b(ptr noalias nocapture noundef writeonly %a, ptr readonly %b) {
; IC2-LABEL: define void @unzip_even_same_src_64b(
; IC2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0]] {
; IC2-NEXT:  [[ENTRY:.*:]]
; IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; IC2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; IC2:       [[VECTOR_PH]]:
; IC2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; IC2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; IC2:       [[VECTOR_BODY]]:
; IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; IC2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; IC2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds <4 x i16>, ptr [[TMP4]], i64 [[TMP0]]
; IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i16>, ptr [[TMP4]], align 16
; IC2-NEXT:    [[WIDE_LOAD1:%.*]] = load <vscale x 4 x i16>, ptr [[TMP7]], align 16
; IC2-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(<vscale x 4 x i16> [[WIDE_LOAD]], <vscale x 4 x i16> poison, <4 x i32> <i32 0, i32 2, i32 0, i32 2>)
; IC2-NEXT:    [[TMP9:%.*]] = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(<vscale x 4 x i16> [[WIDE_LOAD1]], <vscale x 4 x i16> poison, <4 x i32> <i32 0, i32 2, i32 0, i32 2>)
; IC2-NEXT:    [[TMP10:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; IC2-NEXT:    [[TMP13:%.*]] = getelementptr inbounds <4 x i16>, ptr [[TMP10]], i64 [[TMP0]]
; IC2-NEXT:    store <vscale x 4 x i16> [[TMP8]], ptr [[TMP10]], align 16
; IC2-NEXT:    store <vscale x 4 x i16> [[TMP9]], ptr [[TMP13]], align 16
; IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; IC2-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; IC2-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; IC2:       [[MIDDLE_BLOCK]]:
; IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; IC2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; IC2:       [[SCALAR_PH]]:
;
; VScale2-IC1-LABEL: define void @unzip_even_same_src_64b(
; VScale2-IC1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0]] {
; VScale2-IC1-NEXT:  [[ENTRY:.*:]]
; VScale2-IC1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-IC1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale2-IC1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2-IC1:       [[VECTOR_PH]]:
; VScale2-IC1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale2-IC1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-IC1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2-IC1:       [[VECTOR_BODY]]:
; VScale2-IC1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-IC1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale2-IC1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i16>, ptr [[TMP2]], align 16
; VScale2-IC1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(<vscale x 4 x i16> [[WIDE_LOAD]], <vscale x 4 x i16> poison, <4 x i32> <i32 0, i32 2, i32 0, i32 2>)
; VScale2-IC1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale2-IC1-NEXT:    store <vscale x 4 x i16> [[TMP3]], ptr [[TMP4]], align 16
; VScale2-IC1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale2-IC1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-IC1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; VScale2-IC1:       [[MIDDLE_BLOCK]]:
; VScale2-IC1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-IC1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2-IC1:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <4 x i16>, ptr %arrayidx, align 16
  %result = shufflevector <4 x i16> %0, <4 x i16> poison, <4 x i32> <i32 0, i32 2, i32 0, i32 2>
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; VScale1-IC2: {{.*}}
; VScale2-IC2: {{.*}}
