; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S < %s | FileCheck %s
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -tail-folding-policy=prefer-fold-tail \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S < %s | FileCheck %s

define void @st2q(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @st2q(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = add <vscale x 8 x i16> [[WIDE_LOAD]], splat (i16 1)
; CHECK-NEXT:    [[TMP4:%.*]] = add <vscale x 8 x i16> [[TMP3]], splat (i16 1)
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds [16 x i16], ptr [[A]], i64 [[INDEX]], i64 0
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = call <vscale x 16 x i16> @llvm.vector.interleave.segments2.nxv16i16(<vscale x 8 x i16> [[TMP3]], <vscale x 8 x i16> [[TMP4]])
; CHECK-NEXT:    store <vscale x 16 x i16> [[INTERLEAVED_VEC]], ptr [[TMP5]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX_IN:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = load <8 x i16>, ptr [[ARRAYIDX_IN]], align 16
; CHECK-NEXT:    [[V0:%.*]] = add <8 x i16> [[TMP9]], splat (i16 1)
; CHECK-NEXT:    [[V1:%.*]] = add <8 x i16> [[V0]], splat (i16 1)
; CHECK-NEXT:    [[ARRAYIDX_OUT0:%.*]] = getelementptr inbounds [16 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    store <8 x i16> [[V0]], ptr [[ARRAYIDX_OUT0]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT1:%.*]] = getelementptr inbounds [16 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    store <8 x i16> [[V1]], ptr [[ARRAYIDX_OUT1]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx.in = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx.in, align 16
  %v0 = add <8 x i16> %0, splat (i16 1)
  %v1 = add <8 x i16> %v0, splat (i16 1)

  %arrayidx.out0 = getelementptr inbounds [16 x i16], ptr %a, i64 %indvars.iv, i64 0
  store <8 x i16> %v0, ptr %arrayidx.out0, align 16
  %arrayidx.out1 = getelementptr inbounds [16 x i16], ptr %a, i64 %indvars.iv, i64 8
  store <8 x i16> %v1, ptr %arrayidx.out1, align 16

  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @st2q_reverse(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @st2q_reverse(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 1024, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX_IN:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP20:%.*]] = load <8 x i16>, ptr [[ARRAYIDX_IN]], align 16
; CHECK-NEXT:    [[V0:%.*]] = add <8 x i16> [[TMP20]], splat (i16 1)
; CHECK-NEXT:    [[V1:%.*]] = add <8 x i16> [[V0]], splat (i16 1)
; CHECK-NEXT:    [[ARRAYIDX_OUT0:%.*]] = getelementptr inbounds [16 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    store <8 x i16> [[V0]], ptr [[ARRAYIDX_OUT0]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT1:%.*]] = getelementptr inbounds [16 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    store <8 x i16> [[V1]], ptr [[ARRAYIDX_OUT1]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], -1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 1024, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx.in = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx.in, align 16
  %v0 = add <8 x i16> %0, splat (i16 1)
  %v1 = add <8 x i16> %v0, splat (i16 1)

  %arrayidx.out0 = getelementptr inbounds [16 x i16], ptr %a, i64 %indvars.iv, i64 0
  store <8 x i16> %v0, ptr %arrayidx.out0, align 16
  %arrayidx.out1 = getelementptr inbounds [16 x i16], ptr %a, i64 %indvars.iv, i64 8
  store <8 x i16> %v1, ptr %arrayidx.out1, align 16

  %indvars.iv.next = add nsw i64 %indvars.iv, -1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @st3q(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @st3q(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX_IN:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[ARRAYIDX_IN]], align 16
; CHECK-NEXT:    [[V0:%.*]] = add <8 x i16> [[TMP0]], splat (i16 1)
; CHECK-NEXT:    [[V1:%.*]] = add <8 x i16> [[V0]], splat (i16 1)
; CHECK-NEXT:    [[V2:%.*]] = add <8 x i16> [[V1]], splat (i16 1)
; CHECK-NEXT:    [[ARRAYIDX_OUT0:%.*]] = getelementptr inbounds [24 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    store <8 x i16> [[V0]], ptr [[ARRAYIDX_OUT0]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT1:%.*]] = getelementptr inbounds [24 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    store <8 x i16> [[V1]], ptr [[ARRAYIDX_OUT1]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT2:%.*]] = getelementptr inbounds [24 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 16
; CHECK-NEXT:    store <8 x i16> [[V2]], ptr [[ARRAYIDX_OUT2]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx.in = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx.in, align 16
  %v0 = add <8 x i16> %0, splat (i16 1)
  %v1 = add <8 x i16> %v0, splat (i16 1)
  %v2 = add <8 x i16> %v1, splat (i16 1)

  %arrayidx.out0 = getelementptr inbounds [24 x i16], ptr %a, i64 %indvars.iv, i64 0
  store <8 x i16> %v0, ptr %arrayidx.out0, align 16
  %arrayidx.out1 = getelementptr inbounds [24 x i16], ptr %a, i64 %indvars.iv, i64 8
  store <8 x i16> %v1, ptr %arrayidx.out1, align 16
  %arrayidx.out2 = getelementptr inbounds [24 x i16], ptr %a, i64 %indvars.iv, i64 16
  store <8 x i16> %v2, ptr %arrayidx.out2, align 16

  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @st4q(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @st4q(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = add <vscale x 8 x i16> [[WIDE_LOAD]], splat (i16 1)
; CHECK-NEXT:    [[TMP4:%.*]] = add <vscale x 8 x i16> [[TMP3]], splat (i16 1)
; CHECK-NEXT:    [[TMP5:%.*]] = add <vscale x 8 x i16> [[TMP4]], splat (i16 1)
; CHECK-NEXT:    [[TMP6:%.*]] = add <vscale x 8 x i16> [[TMP5]], splat (i16 1)
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDEX]], i64 0
; CHECK-NEXT:    [[INTERLEAVED_VEC:%.*]] = call <vscale x 32 x i16> @llvm.vector.interleave.segments4.nxv32i16(<vscale x 8 x i16> [[TMP3]], <vscale x 8 x i16> [[TMP4]], <vscale x 8 x i16> [[TMP5]], <vscale x 8 x i16> [[TMP6]])
; CHECK-NEXT:    store <vscale x 32 x i16> [[INTERLEAVED_VEC]], ptr [[TMP7]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP12]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX_IN:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP13:%.*]] = load <8 x i16>, ptr [[ARRAYIDX_IN]], align 16
; CHECK-NEXT:    [[V0:%.*]] = add <8 x i16> [[TMP13]], splat (i16 1)
; CHECK-NEXT:    [[V1:%.*]] = add <8 x i16> [[V0]], splat (i16 1)
; CHECK-NEXT:    [[V2:%.*]] = add <8 x i16> [[V1]], splat (i16 1)
; CHECK-NEXT:    [[V3:%.*]] = add <8 x i16> [[V2]], splat (i16 1)
; CHECK-NEXT:    [[ARRAYIDX_OUT0:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    store <8 x i16> [[V0]], ptr [[ARRAYIDX_OUT0]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT1:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    store <8 x i16> [[V1]], ptr [[ARRAYIDX_OUT1]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT2:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 16
; CHECK-NEXT:    store <8 x i16> [[V2]], ptr [[ARRAYIDX_OUT2]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT3:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 24
; CHECK-NEXT:    store <8 x i16> [[V3]], ptr [[ARRAYIDX_OUT3]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx.in = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx.in, align 16
  %v0 = add <8 x i16> %0, splat (i16 1)
  %v1 = add <8 x i16> %v0, splat (i16 1)
  %v2 = add <8 x i16> %v1, splat (i16 1)
  %v3 = add <8 x i16> %v2, splat (i16 1)

  %arrayidx.out0 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 0
  store <8 x i16> %v0, ptr %arrayidx.out0, align 16
  %arrayidx.out1 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 8
  store <8 x i16> %v1, ptr %arrayidx.out1, align 16
  %arrayidx.out2 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 16
  store <8 x i16> %v2, ptr %arrayidx.out2, align 16
  %arrayidx.out3 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 24
  store <8 x i16> %v3, ptr %arrayidx.out3, align 16

  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

; Store interleaving with gaps isn't supported for REVEC
define void @st4q_gap_mid(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @st4q_gap_mid(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX_IN:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[ARRAYIDX_IN]], align 16
; CHECK-NEXT:    [[V0:%.*]] = add <8 x i16> [[TMP0]], splat (i16 1)
; CHECK-NEXT:    [[V1:%.*]] = add <8 x i16> [[V0]], splat (i16 1)
; CHECK-NEXT:    [[V3:%.*]] = add <8 x i16> [[V1]], splat (i16 1)
; CHECK-NEXT:    [[ARRAYIDX_OUT0:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    store <8 x i16> [[V0]], ptr [[ARRAYIDX_OUT0]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT1:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    store <8 x i16> [[V1]], ptr [[ARRAYIDX_OUT1]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT3:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 24
; CHECK-NEXT:    store <8 x i16> [[V3]], ptr [[ARRAYIDX_OUT3]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx.in = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx.in, align 16
  %v0 = add <8 x i16> %0, splat (i16 1)
  %v1 = add <8 x i16> %v0, splat (i16 1)
  %v3 = add <8 x i16> %v1, splat (i16 1)

  %arrayidx.out0 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 0
  store <8 x i16> %v0, ptr %arrayidx.out0, align 16
  %arrayidx.out1 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 8
  store <8 x i16> %v1, ptr %arrayidx.out1, align 16
  %arrayidx.out3 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 24
  store <8 x i16> %v3, ptr %arrayidx.out3, align 16

  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

; Store interleaving with gaps isn't supported for REVEC
define void @st4q_gap_end(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @st4q_gap_end(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX_IN:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[ARRAYIDX_IN]], align 16
; CHECK-NEXT:    [[V0:%.*]] = add <8 x i16> [[TMP0]], splat (i16 1)
; CHECK-NEXT:    [[V1:%.*]] = add <8 x i16> [[V0]], splat (i16 1)
; CHECK-NEXT:    [[V2:%.*]] = add <8 x i16> [[V1]], splat (i16 1)
; CHECK-NEXT:    [[ARRAYIDX_OUT0:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    store <8 x i16> [[V0]], ptr [[ARRAYIDX_OUT0]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT1:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    store <8 x i16> [[V1]], ptr [[ARRAYIDX_OUT1]], align 16
; CHECK-NEXT:    [[ARRAYIDX_OUT2:%.*]] = getelementptr inbounds [32 x i16], ptr [[A]], i64 [[INDVARS_IV]], i64 16
; CHECK-NEXT:    store <8 x i16> [[V2]], ptr [[ARRAYIDX_OUT2]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx.in = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx.in, align 16
  %v0 = add <8 x i16> %0, splat (i16 1)
  %v1 = add <8 x i16> %v0, splat (i16 1)
  %v2 = add <8 x i16> %v1, splat (i16 1)

  %arrayidx.out0 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 0
  store <8 x i16> %v0, ptr %arrayidx.out0, align 16
  %arrayidx.out1 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 8
  store <8 x i16> %v1, ptr %arrayidx.out1, align 16
  %arrayidx.out2 = getelementptr inbounds [32 x i16], ptr %a, i64 %indvars.iv, i64 16
  store <8 x i16> %v2, ptr %arrayidx.out2, align 16

  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META1]]}
;.
