; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "^scalar.ph" --version 6
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -scalable-vectorization=on -force-vector-width=1 \
; RUN:     -mtriple=aarch64 -mattr=+sve -S | FileCheck %s --check-prefixes=CHECK,SVE1
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -scalable-vectorization=on -force-vector-width=1 \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK,SVE2p1

; Test how shufflevectors are re-vectorised depending on the SVE version.

define void @extract_shuffle_idx1(ptr noalias nocapture noundef writeonly %a, ptr readonly %b) {
; CHECK-LABEL: define void @extract_shuffle_idx1(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP2]], align 16
; CHECK-NEXT:    [[TMP3:%.*]] = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.vector.deinterleave.segments2.nxv8i16(<vscale x 8 x i16> [[WIDE_LOAD]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } [[TMP3]], 1
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 4 x i16> [[TMP4]], ptr [[TMP5]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx, align 16
  %result = shufflevector <8 x i16> %0, <8 x i16> poison, <4 x i32> <i32 4, i32 5, i32 6, i32 7>
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}


define void @unzip_even_same_src(ptr noalias nocapture noundef writeonly %a, ptr readonly %b) {
; SVE1-LABEL: define void @unzip_even_same_src(
; SVE1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0]] {
; SVE1-NEXT:  [[ENTRY:.*]]:
; SVE1-NEXT:    br label %[[FOR_BODY:.*]]
; SVE1:       [[FOR_COND_CLEANUP:.*]]:
; SVE1-NEXT:    ret void
; SVE1:       [[FOR_BODY]]:
; SVE1-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; SVE1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDVARS_IV]]
; SVE1-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[ARRAYIDX]], align 16
; SVE1-NEXT:    [[RESULT:%.*]] = shufflevector <8 x i16> [[TMP0]], <8 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 0, i32 2, i32 4, i32 6>
; SVE1-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; SVE1-NEXT:    store <8 x i16> [[RESULT]], ptr [[ARRAYIDX2]], align 16
; SVE1-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; SVE1-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; SVE1-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
; SVE2p1-LABEL: define void @unzip_even_same_src(
; SVE2p1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr readonly [[B:%.*]]) #[[ATTR0]] {
; SVE2p1-NEXT:  [[ENTRY:.*:]]
; SVE2p1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; SVE2p1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; SVE2p1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; SVE2p1:       [[VECTOR_PH]]:
; SVE2p1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; SVE2p1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; SVE2p1-NEXT:    br label %[[VECTOR_BODY:.*]]
; SVE2p1:       [[VECTOR_BODY]]:
; SVE2p1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; SVE2p1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[B]], i64 [[INDEX]]
; SVE2p1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP2]], align 16
; SVE2p1-NEXT:    [[TMP3:%.*]] = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(<vscale x 8 x i16> [[WIDE_LOAD]], <vscale x 8 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 0, i32 2, i32 4, i32 6>)
; SVE2p1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDEX]]
; SVE2p1-NEXT:    store <vscale x 8 x i16> [[TMP3]], ptr [[TMP4]], align 16
; SVE2p1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; SVE2p1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; SVE2p1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; SVE2p1:       [[MIDDLE_BLOCK]]:
; SVE2p1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; SVE2p1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; SVE2p1:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <8 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <8 x i16>, ptr %arrayidx, align 16
  %result = shufflevector <8 x i16> %0, <8 x i16> poison, <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 0, i32 2, i32 4, i32 6>
  %arrayidx2 = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

