; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=VECTORIZE

define void @pixel_ssd(ptr noundef readonly captures(none) %pixuv1, ptr noundef readonly captures(none) %pixuv2, i32 noundef %width, i32 noundef %height, ptr noundef writeonly captures(none) %ssd_u, ptr noundef writeonly captures(none) %ssd_v) {
; VECTORIZE-LABEL: define void @pixel_ssd(
; VECTORIZE-SAME: ptr noundef readonly captures(none) [[PIXUV1:%.*]], ptr noundef readonly captures(none) [[PIXUV2:%.*]], i32 noundef [[WIDTH:%.*]], i32 noundef [[HEIGHT:%.*]], ptr noundef writeonly captures(none) [[SSD_U:%.*]], ptr noundef writeonly captures(none) [[SSD_V:%.*]]) #[[ATTR0:[0-9]+]] {
; VECTORIZE-NEXT:  [[ENTRY:.*]]:
; VECTORIZE-NEXT:    [[MUL:%.*]] = shl nsw i32 [[WIDTH]], 1
; VECTORIZE-NEXT:    [[IDX_EXT14:%.*]] = sext i32 [[MUL]] to i64
; VECTORIZE-NEXT:    [[TMP0:%.*]] = sext i32 [[WIDTH]] to i64
; VECTORIZE-NEXT:    [[SMAX:%.*]] = tail call i32 @llvm.smax.i32(i32 [[HEIGHT]], i32 1)
; VECTORIZE-NEXT:    [[SMAX1:%.*]] = call i64 @llvm.smax.i64(i64 [[TMP0]], i64 8)
; VECTORIZE-NEXT:    [[TMP1:%.*]] = add nsw i64 [[SMAX1]], -1
; VECTORIZE-NEXT:    [[TMP9:%.*]] = lshr i64 [[TMP1]], 3
; VECTORIZE-NEXT:    [[TMP10:%.*]] = add nuw nsw i64 [[TMP9]], 1
; VECTORIZE-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; VECTORIZE-NEXT:    [[UMAX:%.*]] = call i64 @llvm.umax.i64(i64 [[TMP4]], i64 3)
; VECTORIZE-NEXT:    br label %[[DO_BODY:.*]]
; VECTORIZE:       [[DO_BODY]]:
; VECTORIZE-NEXT:    [[H_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[ADD18:%.*]], %[[DO_END:.*]] ]
; VECTORIZE-NEXT:    [[VSSD_V_0:%.*]] = phi <4 x i32> [ zeroinitializer, %[[ENTRY]] ], [ [[VDOT1_I_LCSSA:%.*]], %[[DO_END]] ]
; VECTORIZE-NEXT:    [[VSSD_U_0:%.*]] = phi <4 x i32> [ zeroinitializer, %[[ENTRY]] ], [ [[VDOT1_I44_LCSSA:%.*]], %[[DO_END]] ]
; VECTORIZE-NEXT:    [[PIXUV2_ADDR_0:%.*]] = phi ptr [ [[PIXUV2]], %[[ENTRY]] ], [ [[ADD_PTR17:%.*]], %[[DO_END]] ]
; VECTORIZE-NEXT:    [[PIXUV1_ADDR_0:%.*]] = phi ptr [ [[PIXUV1]], %[[ENTRY]] ], [ [[ADD_PTR15:%.*]], %[[DO_END]] ]
; VECTORIZE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP10]], [[UMAX]]
; VECTORIZE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VECTORIZE:       [[VECTOR_PH]]:
; VECTORIZE-NEXT:    [[TMP5:%.*]] = call i64 @llvm.vscale.i64()
; VECTORIZE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP10]], [[TMP5]]
; VECTORIZE-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP10]], [[N_MOD_VF]]
; VECTORIZE-NEXT:    [[TMP6:%.*]] = shl i64 [[N_VEC]], 3
; VECTORIZE-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i32> @llvm.vector.insert.nxv4i32.v4i32(<vscale x 4 x i32> zeroinitializer, <4 x i32> [[VSSD_V_0]], i64 0)
; VECTORIZE-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i32> @llvm.vector.insert.nxv4i32.v4i32(<vscale x 4 x i32> zeroinitializer, <4 x i32> [[VSSD_U_0]], i64 0)
; VECTORIZE-NEXT:    br label %[[VECTOR_BODY:.*]]
; VECTORIZE:       [[VECTOR_BODY]]:
; VECTORIZE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VECTORIZE-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ [[TMP7]], %[[VECTOR_PH]] ], [ [[TMP16:%.*]], %[[VECTOR_BODY]] ]
; VECTORIZE-NEXT:    [[VEC_PHI2:%.*]] = phi <vscale x 4 x i32> [ [[TMP8]], %[[VECTOR_PH]] ], [ [[TMP15:%.*]], %[[VECTOR_BODY]] ]
; VECTORIZE-NEXT:    [[INDVARS_IV1:%.*]] = shl i64 [[INDEX]], 3
; VECTORIZE-NEXT:    [[TMP20:%.*]] = shl nuw nsw i64 [[INDVARS_IV1]], 1
; VECTORIZE-NEXT:    [[ADD_PTR1:%.*]] = getelementptr inbounds nuw i8, ptr [[PIXUV1_ADDR_0]], i64 [[TMP20]]
; VECTORIZE-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[ADD_PTR1]], align 1
; VECTORIZE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw i8, ptr [[PIXUV2_ADDR_0]], i64 [[TMP20]]
; VECTORIZE-NEXT:    [[WIDE_LOAD3:%.*]] = load <vscale x 16 x i8>, ptr [[TMP11]], align 1
; VECTORIZE-NEXT:    [[TMP12:%.*]] = call <vscale x 16 x i8> @llvm.aarch64.sve.uabd.nxv16i8(<vscale x 16 x i1> splat (i1 true), <vscale x 16 x i8> [[WIDE_LOAD]], <vscale x 16 x i8> [[WIDE_LOAD3]])
; VECTORIZE-NEXT:    [[TMP13:%.*]] = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
; VECTORIZE-NEXT:    [[TMP14:%.*]] = call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(<vscale x 16 x i8> [[TMP12]], <vscale x 16 x i8> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
; VECTORIZE-NEXT:    [[TMP15]] = call <vscale x 4 x i32> @llvm.aarch64.sve.udot.nxv4i32(<vscale x 4 x i32> [[VEC_PHI2]], <vscale x 16 x i8> [[TMP13]], <vscale x 16 x i8> [[TMP13]])
; VECTORIZE-NEXT:    [[TMP16]] = call <vscale x 4 x i32> @llvm.aarch64.sve.udot.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 16 x i8> [[TMP14]], <vscale x 16 x i8> [[TMP14]])
; VECTORIZE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP5]]
; VECTORIZE-NEXT:    [[TMP17:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VECTORIZE-NEXT:    br i1 [[TMP17]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; VECTORIZE:       [[MIDDLE_BLOCK]]:
; VECTORIZE-NEXT:    [[TMP18:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.nxv4i32(<4 x i32> zeroinitializer, <vscale x 4 x i32> [[TMP16]])
; VECTORIZE-NEXT:    [[TMP19:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.nxv4i32(<4 x i32> zeroinitializer, <vscale x 4 x i32> [[TMP15]])
; VECTORIZE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP10]], [[N_VEC]]
; VECTORIZE-NEXT:    br i1 [[CMP_N]], label %[[DO_END]], label %[[SCALAR_PH]]
; VECTORIZE:       [[SCALAR_PH]]:
; VECTORIZE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP6]], %[[MIDDLE_BLOCK]] ], [ 0, %[[DO_BODY]] ]
; VECTORIZE-NEXT:    [[BC_MERGE_RDX:%.*]] = phi <4 x i32> [ [[TMP18]], %[[MIDDLE_BLOCK]] ], [ [[VSSD_V_0]], %[[DO_BODY]] ]
; VECTORIZE-NEXT:    [[BC_MERGE_RDX4:%.*]] = phi <4 x i32> [ [[TMP19]], %[[MIDDLE_BLOCK]] ], [ [[VSSD_U_0]], %[[DO_BODY]] ]
; VECTORIZE-NEXT:    br label %[[DO_BODY2:.*]]
; VECTORIZE:       [[DO_BODY2]]:
; VECTORIZE-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[DO_BODY2]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; VECTORIZE-NEXT:    [[VSSD_V_1:%.*]] = phi <4 x i32> [ [[VDOT1_I:%.*]], %[[DO_BODY2]] ], [ [[BC_MERGE_RDX]], %[[SCALAR_PH]] ]
; VECTORIZE-NEXT:    [[VSSD_U_1:%.*]] = phi <4 x i32> [ [[VDOT1_I44:%.*]], %[[DO_BODY2]] ], [ [[BC_MERGE_RDX4]], %[[SCALAR_PH]] ]
; VECTORIZE-NEXT:    [[TMP21:%.*]] = shl nuw nsw i64 [[INDVARS_IV]], 1
; VECTORIZE-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[PIXUV1_ADDR_0]], i64 [[TMP21]]
; VECTORIZE-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[ADD_PTR]], align 1
; VECTORIZE-NEXT:    [[ADD_PTR7:%.*]] = getelementptr inbounds nuw i8, ptr [[PIXUV2_ADDR_0]], i64 [[TMP21]]
; VECTORIZE-NEXT:    [[TMP3:%.*]] = load <16 x i8>, ptr [[ADD_PTR7]], align 1
; VECTORIZE-NEXT:    [[VABD_I:%.*]] = tail call noundef <16 x i8> @llvm.aarch64.neon.uabd.v16i8(<16 x i8> [[TMP2]], <16 x i8> [[TMP3]])
; VECTORIZE-NEXT:    [[SHUFFLE_I:%.*]] = shufflevector <16 x i8> [[VABD_I]], <16 x i8> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
; VECTORIZE-NEXT:    [[SHUFFLE_I43:%.*]] = shufflevector <16 x i8> [[VABD_I]], <16 x i8> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
; VECTORIZE-NEXT:    [[VDOT1_I44]] = tail call noundef <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> [[VSSD_U_1]], <16 x i8> [[SHUFFLE_I]], <16 x i8> [[SHUFFLE_I]])
; VECTORIZE-NEXT:    [[VDOT1_I]] = tail call noundef <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> [[VSSD_V_1]], <16 x i8> [[SHUFFLE_I43]], <16 x i8> [[SHUFFLE_I43]])
; VECTORIZE-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 8
; VECTORIZE-NEXT:    [[CMP:%.*]] = icmp slt i64 [[INDVARS_IV_NEXT]], [[TMP0]]
; VECTORIZE-NEXT:    br i1 [[CMP]], label %[[DO_BODY2]], label %[[DO_END]], !llvm.loop [[LOOP3:![0-9]+]]
; VECTORIZE:       [[DO_END]]:
; VECTORIZE-NEXT:    [[VDOT1_I44_LCSSA]] = phi <4 x i32> [ [[VDOT1_I44]], %[[DO_BODY2]] ], [ [[TMP19]], %[[MIDDLE_BLOCK]] ]
; VECTORIZE-NEXT:    [[VDOT1_I_LCSSA]] = phi <4 x i32> [ [[VDOT1_I]], %[[DO_BODY2]] ], [ [[TMP18]], %[[MIDDLE_BLOCK]] ]
; VECTORIZE-NEXT:    [[ADD_PTR15]] = getelementptr inbounds i8, ptr [[PIXUV1_ADDR_0]], i64 [[IDX_EXT14]]
; VECTORIZE-NEXT:    [[ADD_PTR17]] = getelementptr inbounds i8, ptr [[PIXUV2_ADDR_0]], i64 [[IDX_EXT14]]
; VECTORIZE-NEXT:    [[ADD18]] = add nuw nsw i32 [[H_0]], 1
; VECTORIZE-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i32 [[ADD18]], [[SMAX]]
; VECTORIZE-NEXT:    br i1 [[EXITCOND_NOT]], label %[[DO_END21:.*]], label %[[DO_BODY]]
; VECTORIZE:       [[DO_END21]]:
; VECTORIZE-NEXT:    [[VDOT1_I44_LCSSA_LCSSA:%.*]] = phi <4 x i32> [ [[VDOT1_I44_LCSSA]], %[[DO_END]] ]
; VECTORIZE-NEXT:    [[VDOT1_I_LCSSA_LCSSA:%.*]] = phi <4 x i32> [ [[VDOT1_I_LCSSA]], %[[DO_END]] ]
; VECTORIZE-NEXT:    [[VADDVQ_U32_I45:%.*]] = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> [[VDOT1_I44_LCSSA_LCSSA]])
; VECTORIZE-NEXT:    [[DIV41:%.*]] = lshr i32 [[VADDVQ_U32_I45]], 1
; VECTORIZE-NEXT:    [[CONV:%.*]] = zext nneg i32 [[DIV41]] to i64
; VECTORIZE-NEXT:    store i64 [[CONV]], ptr [[SSD_U]], align 8
; VECTORIZE-NEXT:    [[VADDVQ_U32_I:%.*]] = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> [[VDOT1_I_LCSSA_LCSSA]])
; VECTORIZE-NEXT:    [[DIV2442:%.*]] = lshr i32 [[VADDVQ_U32_I]], 1
; VECTORIZE-NEXT:    [[CONV25:%.*]] = zext nneg i32 [[DIV2442]] to i64
; VECTORIZE-NEXT:    store i64 [[CONV25]], ptr [[SSD_V]], align 8
; VECTORIZE-NEXT:    ret void
;
entry:
  %mul = shl nsw i32 %width, 1
  %idx.ext14 = sext i32 %mul to i64
  %0 = sext i32 %width to i64
  %smax = tail call i32 @llvm.smax.i32(i32 %height, i32 1)
  br label %do.body

do.body:                                          ; preds = %do.end, %entry
  %h.0 = phi i32 [ 0, %entry ], [ %add18, %do.end ]
  %vssd_v.0 = phi <4 x i32> [ zeroinitializer, %entry ], [ %vdot1.i, %do.end ]
  %vssd_u.0 = phi <4 x i32> [ zeroinitializer, %entry ], [ %vdot1.i44, %do.end ]
  %pixuv2.addr.0 = phi ptr [ %pixuv2, %entry ], [ %add.ptr17, %do.end ]
  %pixuv1.addr.0 = phi ptr [ %pixuv1, %entry ], [ %add.ptr15, %do.end ]
  br label %do.body2

do.body2:                                         ; preds = %do.body2, %do.body
  %indvars.iv = phi i64 [ %indvars.iv.next, %do.body2 ], [ 0, %do.body ]
  %vssd_v.1 = phi <4 x i32> [ %vdot1.i, %do.body2 ], [ %vssd_v.0, %do.body ]
  %vssd_u.1 = phi <4 x i32> [ %vdot1.i44, %do.body2 ], [ %vssd_u.0, %do.body ]
  %1 = shl nuw nsw i64 %indvars.iv, 1
  %add.ptr = getelementptr inbounds nuw i8, ptr %pixuv1.addr.0, i64 %1
  %2 = load <16 x i8>, ptr %add.ptr, align 1
  %add.ptr7 = getelementptr inbounds nuw i8, ptr %pixuv2.addr.0, i64 %1
  %3 = load <16 x i8>, ptr %add.ptr7, align 1
  %vabd.i = tail call noundef <16 x i8> @llvm.aarch64.neon.uabd.v16i8(<16 x i8> %2, <16 x i8> %3)
  %shuffle.i = shufflevector <16 x i8> %vabd.i, <16 x i8> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %shuffle.i43 = shufflevector <16 x i8> %vabd.i, <16 x i8> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %vdot1.i44 = tail call noundef <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> %vssd_u.1, <16 x i8> %shuffle.i, <16 x i8> %shuffle.i)
  %vdot1.i = tail call noundef <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> %vssd_v.1, <16 x i8> %shuffle.i43, <16 x i8> %shuffle.i43)
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 8
  %cmp = icmp slt i64 %indvars.iv.next, %0
  br i1 %cmp, label %do.body2, label %do.end

do.end:                                           ; preds = %do.body2
  %add.ptr15 = getelementptr inbounds i8, ptr %pixuv1.addr.0, i64 %idx.ext14
  %add.ptr17 = getelementptr inbounds i8, ptr %pixuv2.addr.0, i64 %idx.ext14
  %add18 = add nuw nsw i32 %h.0, 1
  %exitcond.not = icmp eq i32 %add18, %smax
  br i1 %exitcond.not, label %do.end21, label %do.body

do.end21:                                         ; preds = %do.end
  %vaddvq_u32.i45 = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> %vdot1.i44)
  %div41 = lshr i32 %vaddvq_u32.i45, 1
  %conv = zext nneg i32 %div41 to i64
  store i64 %conv, ptr %ssd_u, align 8
  %vaddvq_u32.i = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> %vdot1.i)
  %div2442 = lshr i32 %vaddvq_u32.i, 1
  %conv25 = zext nneg i32 %div2442 to i64
  store i64 %conv25, ptr %ssd_v, align 8
  ret void
}

;.
; VECTORIZE: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; VECTORIZE: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; VECTORIZE: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; VECTORIZE: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
