; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S < %s | FileCheck %s
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -tail-folding-policy=prefer-fold-tail \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S < %s | FileCheck %s

define void @ld2q(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @ld2q(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP10:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP10]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP10]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [16 x i16], ptr [[B]], i64 [[INDEX]], i64 0
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <vscale x 16 x i16>, ptr [[TMP2]], align 16
; CHECK-NEXT:    [[STRIDED_VEC:%.*]] = call { <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.vector.deinterleave.segments2.nxv16i16(<vscale x 16 x i16> [[WIDE_VEC]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 1
; CHECK-NEXT:    [[TMP7:%.*]] = add <vscale x 8 x i16> [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 8 x i16> [[TMP7]], ptr [[TMP8]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP10]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds [16 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[ARRAYIDX0]], align 16
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [16 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, ptr [[ARRAYIDX1]], align 16
; CHECK-NEXT:    [[RESULT:%.*]] = add <8 x i16> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <8 x i16> [[RESULT]], ptr [[ARRAYIDX2]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx0 = getelementptr inbounds [16 x i16], ptr %b, i64 %indvars.iv, i64 0
  %0 = load <8 x i16>, ptr %arrayidx0, align 16
  %arrayidx1 = getelementptr inbounds [16 x i16], ptr %b, i64 %indvars.iv, i64 8
  %1 = load <8 x i16>, ptr %arrayidx1, align 16
  %result = add <8 x i16> %0, %1
  %arrayidx2 = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

; TODO-REVEC:
; Due to how (de)interleave.segments intrinsics work, we cannot have VF = vscale x 2.
; And getSegmentInterleavedMemoryOpCost() forbids non-128bit segments.
define void @ld2q_64bits(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @ld2q_64bits(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds [8 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[TMP9:%.*]] = load <4 x i16>, ptr [[ARRAYIDX0]], align 16
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [8 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 4
; CHECK-NEXT:    [[TMP10:%.*]] = load <4 x i16>, ptr [[ARRAYIDX1]], align 16
; CHECK-NEXT:    [[RESULT:%.*]] = add <4 x i16> [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <4 x i16> [[RESULT]], ptr [[ARRAYIDX2]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx0 = getelementptr inbounds [8 x i16], ptr %b, i64 %indvars.iv, i64 0
  %0 = load <4 x i16>, ptr %arrayidx0, align 16
  %arrayidx1 = getelementptr inbounds [8 x i16], ptr %b, i64 %indvars.iv, i64 4
  %1 = load <4 x i16>, ptr %arrayidx1, align 16
  %result = add <4 x i16> %0, %1
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @ld2q_reverse(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @ld2q_reverse(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 1024, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds [16 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[TMP21:%.*]] = load <8 x i16>, ptr [[ARRAYIDX0]], align 16
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [16 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    [[TMP22:%.*]] = load <8 x i16>, ptr [[ARRAYIDX1]], align 16
; CHECK-NEXT:    [[RESULT:%.*]] = add <8 x i16> [[TMP21]], [[TMP22]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <8 x i16> [[RESULT]], ptr [[ARRAYIDX2]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], -1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 0
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 1024, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx0 = getelementptr inbounds [16 x i16], ptr %b, i64 %indvars.iv, i64 0
  %0 = load <8 x i16>, ptr %arrayidx0, align 16
  %arrayidx1 = getelementptr inbounds [16 x i16], ptr %b, i64 %indvars.iv, i64 8
  %1 = load <8 x i16>, ptr %arrayidx1, align 16
  %result = add <8 x i16> %0, %1
  %arrayidx2 = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nsw i64 %indvars.iv, -1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 0
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @ld3q(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @ld3q(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds [24 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[ARRAYIDX0]], align 16
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [24 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, ptr [[ARRAYIDX1]], align 16
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [24 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 16
; CHECK-NEXT:    [[TMP2:%.*]] = load <8 x i16>, ptr [[ARRAYIDX2]], align 16
; CHECK-NEXT:    [[TMP:%.*]] = add <8 x i16> [[TMP0]], [[TMP1]]
; CHECK-NEXT:    [[RESULT:%.*]] = add <8 x i16> [[TMP]], [[TMP2]]
; CHECK-NEXT:    [[ARRAYIDX_OUT:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <8 x i16> [[RESULT]], ptr [[ARRAYIDX_OUT]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx0 = getelementptr inbounds [24 x i16], ptr %b, i64 %indvars.iv, i64 0
  %0 = load <8 x i16>, ptr %arrayidx0, align 16
  %arrayidx1 = getelementptr inbounds [24 x i16], ptr %b, i64 %indvars.iv, i64 8
  %1 = load <8 x i16>, ptr %arrayidx1, align 16
  %arrayidx2 = getelementptr inbounds [24 x i16], ptr %b, i64 %indvars.iv, i64 16
  %2 = load <8 x i16>, ptr %arrayidx2, align 16
  %tmp = add <8 x i16> %0, %1
  %result = add <8 x i16> %tmp, %2
  %arrayidx.out = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx.out, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @ld4q(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @ld4q(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDEX]], i64 0
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <vscale x 32 x i16>, ptr [[TMP2]], align 16
; CHECK-NEXT:    [[STRIDED_VEC:%.*]] = call { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.vector.deinterleave.segments4.nxv32i16(<vscale x 32 x i16> [[WIDE_VEC]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 1
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 2
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 3
; CHECK-NEXT:    [[TMP11:%.*]] = add <vscale x 8 x i16> [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP12:%.*]] = add <vscale x 8 x i16> [[TMP11]], [[TMP8]]
; CHECK-NEXT:    [[TMP13:%.*]] = add <vscale x 8 x i16> [[TMP12]], [[TMP10]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 8 x i16> [[TMP13]], ptr [[TMP14]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP15:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP15]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[TMP16:%.*]] = load <8 x i16>, ptr [[ARRAYIDX0]], align 16
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    [[TMP17:%.*]] = load <8 x i16>, ptr [[ARRAYIDX1]], align 16
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 16
; CHECK-NEXT:    [[TMP18:%.*]] = load <8 x i16>, ptr [[ARRAYIDX2]], align 16
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 24
; CHECK-NEXT:    [[TMP19:%.*]] = load <8 x i16>, ptr [[ARRAYIDX3]], align 16
; CHECK-NEXT:    [[TMP:%.*]] = add <8 x i16> [[TMP16]], [[TMP17]]
; CHECK-NEXT:    [[TMP4:%.*]] = add <8 x i16> [[TMP]], [[TMP18]]
; CHECK-NEXT:    [[RESULT:%.*]] = add <8 x i16> [[TMP4]], [[TMP19]]
; CHECK-NEXT:    [[ARRAYIDX_OUT:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <8 x i16> [[RESULT]], ptr [[ARRAYIDX_OUT]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx0 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 0
  %0 = load <8 x i16>, ptr %arrayidx0, align 16
  %arrayidx1 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 8
  %1 = load <8 x i16>, ptr %arrayidx1, align 16
  %arrayidx2 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 16
  %2 = load <8 x i16>, ptr %arrayidx2, align 16
  %arrayidx3 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 24
  %3 = load <8 x i16>, ptr %arrayidx3, align 16
  %tmp = add <8 x i16> %0, %1
  %tmp2 = add <8 x i16> %tmp, %2
  %result = add <8 x i16> %tmp2, %3
  %arrayidx.out = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx.out, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @ld4q_gap(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @ld4q_gap(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDEX]], i64 0
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <vscale x 32 x i16>, ptr [[TMP2]], align 16
; CHECK-NEXT:    [[STRIDED_VEC:%.*]] = call { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.vector.deinterleave.segments4.nxv32i16(<vscale x 32 x i16> [[WIDE_VEC]])
; CHECK-NEXT:    [[TMP4:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 3
; CHECK-NEXT:    [[TMP12:%.*]] = add <vscale x 8 x i16> [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP13:%.*]] = add <vscale x 8 x i16> [[TMP12]], [[TMP10]]
; CHECK-NEXT:    [[TMP14:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 8 x i16> [[TMP13]], ptr [[TMP14]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP15:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP15]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[TMP16:%.*]] = load <8 x i16>, ptr [[ARRAYIDX0]], align 16
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    [[TMP17:%.*]] = load <8 x i16>, ptr [[ARRAYIDX1]], align 16
; CHECK-NEXT:    [[ARRAYIDX3:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 24
; CHECK-NEXT:    [[TMP19:%.*]] = load <8 x i16>, ptr [[ARRAYIDX3]], align 16
; CHECK-NEXT:    [[TMP:%.*]] = add <8 x i16> [[TMP16]], [[TMP17]]
; CHECK-NEXT:    [[RESULT:%.*]] = add <8 x i16> [[TMP]], [[TMP19]]
; CHECK-NEXT:    [[ARRAYIDX_OUT:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <8 x i16> [[RESULT]], ptr [[ARRAYIDX_OUT]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx0 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 0
  %0 = load <8 x i16>, ptr %arrayidx0, align 16
  %arrayidx1 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 8
  %1 = load <8 x i16>, ptr %arrayidx1, align 16
  %arrayidx3 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 24
  %3 = load <8 x i16>, ptr %arrayidx3, align 16
  %tmp = add <8 x i16> %0, %1
  %result = add <8 x i16> %tmp, %3
  %arrayidx.out = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx.out, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @ld4q_gap_end(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @ld4q_gap_end(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ule i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[N_MOD_VF]], 0
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], i64 [[TMP0]], i64 [[N_MOD_VF]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[TMP3]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDEX]], i64 0
; CHECK-NEXT:    [[WIDE_VEC:%.*]] = load <vscale x 32 x i16>, ptr [[TMP4]], align 16
; CHECK-NEXT:    [[STRIDED_VEC:%.*]] = call { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } @llvm.vector.deinterleave.segments4.nxv32i16(<vscale x 32 x i16> [[WIDE_VEC]])
; CHECK-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 1
; CHECK-NEXT:    [[TMP10:%.*]] = extractvalue { <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16>, <vscale x 8 x i16> } [[STRIDED_VEC]], 2
; CHECK-NEXT:    [[TMP11:%.*]] = add <vscale x 8 x i16> [[TMP6]], [[TMP8]]
; CHECK-NEXT:    [[TMP12:%.*]] = add <vscale x 8 x i16> [[TMP11]], [[TMP10]]
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 8 x i16> [[TMP12]], ptr [[TMP13]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[ARRAYIDX0:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 0
; CHECK-NEXT:    [[TMP15:%.*]] = load <8 x i16>, ptr [[ARRAYIDX0]], align 16
; CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 8
; CHECK-NEXT:    [[TMP16:%.*]] = load <8 x i16>, ptr [[ARRAYIDX1]], align 16
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [32 x i16], ptr [[B]], i64 [[INDVARS_IV]], i64 16
; CHECK-NEXT:    [[TMP17:%.*]] = load <8 x i16>, ptr [[ARRAYIDX2]], align 16
; CHECK-NEXT:    [[TMP:%.*]] = add <8 x i16> [[TMP15]], [[TMP16]]
; CHECK-NEXT:    [[RESULT:%.*]] = add <8 x i16> [[TMP]], [[TMP17]]
; CHECK-NEXT:    [[ARRAYIDX_OUT:%.*]] = getelementptr inbounds <8 x i16>, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store <8 x i16> [[RESULT]], ptr [[ARRAYIDX_OUT]], align 16
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 1024
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx0 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 0
  %0 = load <8 x i16>, ptr %arrayidx0, align 16
  %arrayidx1 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 8
  %1 = load <8 x i16>, ptr %arrayidx1, align 16
  %arrayidx2 = getelementptr inbounds [32 x i16], ptr %b, i64 %indvars.iv, i64 16
  %2 = load <8 x i16>, ptr %arrayidx2, align 16
  %tmp = add <8 x i16> %0, %1
  %result = add <8 x i16> %tmp, %2
  %arrayidx.out = getelementptr inbounds <8 x i16>, ptr %a, i64 %indvars.iv
  store <8 x i16> %result, ptr %arrayidx.out, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META2]], [[META1]]}
; CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
; CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META2]], [[META1]]}
; CHECK: [[LOOP8]] = distinct !{[[LOOP8]], [[META1]], [[META2]]}
; CHECK: [[LOOP9]] = distinct !{[[LOOP9]], [[META2]], [[META1]]}
;.
