; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --filter-out-after "scalar.ph:" --replace-value-regex "!llvm.loop ![0-9]+" --version 6
; RUN: opt -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops -mtriple=aarch64 -mattr=+sve2p1 -S < %s | FileCheck %s

; Ensure that vector reductions with zext/sext in their chains are not matched as
; partial reductions.

define <8 x i16> @partial_reduction_shape(i64 %0) {
; CHECK-LABEL: define <8 x i16> @partial_reduction_shape(
; CHECK-SAME: i64 [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK:       [[SCALAR_LOOP]]:
; CHECK-NEXT:    [[INDVARS_IV_I_US_I:%.*]] = phi i64 [ [[TMP0]], %[[ENTRY]] ], [ [[INDVARS_IV_NEXT_I_US_I:%.*]], %[[SCALAR_LOOP]] ]
; CHECK-NEXT:    [[SUM_1235_I_US_I:%.*]] = phi <8 x i16> [ zeroinitializer, %[[ENTRY]] ], [ [[ADD_I_I_US_I:%.*]], %[[SCALAR_LOOP]] ]
; CHECK-NEXT:    [[INDVARS_IV_NEXT_I_US_I]] = add i64 [[INDVARS_IV_I_US_I]], 1
; CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr null, align 1
; CHECK-NEXT:    [[TMP2:%.*]] = insertelement <8 x i8> zeroinitializer, i8 [[TMP1]], i64 0
; CHECK-NEXT:    [[VMOVL_I_I_US_I:%.*]] = zext <8 x i8> [[TMP2]] to <8 x i16>
; CHECK-NEXT:    [[ADD_I_I_US_I]] = add <8 x i16> [[SUM_1235_I_US_I]], [[VMOVL_I_I_US_I]]
; CHECK-NEXT:    [[CMP93_I_US_I:%.*]] = icmp ugt i64 [[INDVARS_IV_I_US_I]], 0
; CHECK-NEXT:    br i1 [[CMP93_I_US_I]], label %[[SCALAR_LOOP]], label %[[LOOP_END:.*]]
; CHECK:       [[LOOP_END]]:
; CHECK-NEXT:    [[ADD_I_I_US_I_LCSSA:%.*]] = phi <8 x i16> [ [[ADD_I_I_US_I]], %[[SCALAR_LOOP]] ]
; CHECK-NEXT:    ret <8 x i16> [[ADD_I_I_US_I_LCSSA]]
;
entry:
  br label %scalar.loop

scalar.loop:
  %indvars.iv.i.us.i = phi i64 [ %0, %entry ], [ %indvars.iv.next.i.us.i, %scalar.loop ]
  %sum.1235.i.us.i = phi <8 x i16> [ zeroinitializer, %entry ], [ %add.i.i.us.i, %scalar.loop ]
  %indvars.iv.next.i.us.i = add i64 %indvars.iv.i.us.i, 1
  %1 = load i8, ptr null, align 1
  %2 = insertelement <8 x i8> zeroinitializer, i8 %1, i64 0
  %vmovl.i.i.us.i = zext <8 x i8> %2 to <8 x i16>
  %add.i.i.us.i = add <8 x i16> %sum.1235.i.us.i, %vmovl.i.i.us.i
  %cmp93.i.us.i = icmp ugt i64 %indvars.iv.i.us.i, 0
  br i1 %cmp93.i.us.i, label %scalar.loop, label %loop.end

loop.end:
  ret <8 x i16> %add.i.i.us.i
}


define <8 x i16> @partial_reduction_vector_shape(i64 %0) {
; CHECK-LABEL: define <8 x i16> @partial_reduction_vector_shape(
; CHECK-SAME: i64 [[TMP0:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP1:%.*]] = sub i64 1, [[TMP0]]
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP1]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP5:%.*]] = add i64 [[TMP0]], [[N_VEC]]
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 8 x i16> @llvm.vector.insert.nxv8i16.v8i16(<vscale x 8 x i16> zeroinitializer, <8 x i16> zeroinitializer, i64 0)
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 8 x i16> [ [[TMP4]], %[[VECTOR_PH]] ], [ [[TMP8:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP7:%.*]] = load <8 x i8>, ptr null, align 1
; CHECK-NEXT:    [[BROADCAST:%.*]] = call <vscale x 8 x i8> @llvm.vector.broadcast.nxv8i8.v8i8(<8 x i8> [[TMP7]])
; CHECK-NEXT:    [[TMP6:%.*]] = zext <vscale x 8 x i8> [[BROADCAST]] to <vscale x 8 x i16>
; CHECK-NEXT:    [[TMP8]] = add <vscale x 8 x i16> [[VEC_PHI]], [[TMP6]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP2]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[TMP9:%.*]] = call <8 x i16> @llvm.vector.partial.reduce.add.v8i16.nxv8i16(<8 x i16> zeroinitializer, <vscale x 8 x i16> [[TMP8]])
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP1]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[LOOP_END:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
entry:
  br label %scalar.loop

scalar.loop:
  %indvars.iv.i.us.i = phi i64 [ %0, %entry ], [ %indvars.iv.next.i.us.i, %scalar.loop ]
  %sum.1235.i.us.i = phi <8 x i16> [ zeroinitializer, %entry ], [ %add.i.i.us.i, %scalar.loop ]
  %indvars.iv.next.i.us.i = add i64 %indvars.iv.i.us.i, 1
  %2 = load <8 x i8>, ptr null, align 1
  %vmovl.i.i.us.i = zext <8 x i8> %2 to <8 x i16>
  %add.i.i.us.i = add <8 x i16> %sum.1235.i.us.i, %vmovl.i.i.us.i
  %cmp93.i.us.i = icmp ugt i64 %indvars.iv.i.us.i, 0
  br i1 %cmp93.i.us.i, label %scalar.loop, label %loop.end

loop.end:
  ret <8 x i16> %add.i.i.us.i
}
