; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --filter-out-after "scalar.ph:" --replace-value-regex "!llvm.loop ![0-9]+" --version 6
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -scalable-vectorization=on -force-vector-width=1 \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK,VScale1
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -scalable-vectorization=on -force-vector-width=2 \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK,VScale2

; Test how 64-bit NEON intrinsic are re-vectorised using HVLA.

define void @uabd(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @uabd(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i16>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TO_SVE:%.*]] = call <vscale x 8 x i16> @llvm.vector.interleave2.nxv8i16(<vscale x 4 x i16> [[WIDE_LOAD]], <vscale x 4 x i16> poison)
; VScale1-NEXT:    [[TO_SVE1:%.*]] = call <vscale x 8 x i16> @llvm.vector.interleave2.nxv8i16(<vscale x 4 x i16> splat (i16 1), <vscale x 4 x i16> poison)
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.uabd.nxv8i16(<vscale x 8 x i1> splat (i1 true), <vscale x 8 x i16> [[TO_SVE]], <vscale x 8 x i16> [[TO_SVE1]])
; VScale1-NEXT:    [[TMP6:%.*]] = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.vector.deinterleave2.nxv8i16(<vscale x 8 x i16> [[TMP3]])
; VScale1-NEXT:    [[FROM_SVE:%.*]] = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } [[TMP6]], 0
; VScale1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 4 x i16> [[FROM_SVE]], ptr [[TMP4]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @uabd(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.uabd.nxv8i16(<vscale x 8 x i1> splat (i1 true), <vscale x 8 x i16> [[WIDE_LOAD]], <vscale x 8 x i16> splat (i16 1))
; VScale2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 8 x i16> [[TMP5]], ptr [[TMP6]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <4 x i16>, ptr %arrayidx, align 16
  %result = call <4 x i16> @llvm.aarch64.neon.uabd.v8i16(<4 x i16> %0, <4 x i16> splat (i16 1))
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @sabd(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @sabd(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i16>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TO_SVE:%.*]] = call <vscale x 8 x i16> @llvm.vector.interleave2.nxv8i16(<vscale x 4 x i16> [[WIDE_LOAD]], <vscale x 4 x i16> poison)
; VScale1-NEXT:    [[TO_SVE1:%.*]] = call <vscale x 8 x i16> @llvm.vector.interleave2.nxv8i16(<vscale x 4 x i16> splat (i16 1), <vscale x 4 x i16> poison)
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.sabd.nxv8i16(<vscale x 8 x i1> splat (i1 true), <vscale x 8 x i16> [[TO_SVE]], <vscale x 8 x i16> [[TO_SVE1]])
; VScale1-NEXT:    [[TMP6:%.*]] = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.vector.deinterleave2.nxv8i16(<vscale x 8 x i16> [[TMP3]])
; VScale1-NEXT:    [[FROM_SVE:%.*]] = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } [[TMP6]], 0
; VScale1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 4 x i16> [[FROM_SVE]], ptr [[TMP4]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @sabd(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.sabd.nxv8i16(<vscale x 8 x i1> splat (i1 true), <vscale x 8 x i16> [[WIDE_LOAD]], <vscale x 8 x i16> splat (i16 1))
; VScale2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 8 x i16> [[TMP5]], ptr [[TMP6]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <4 x i16>, ptr %arrayidx, align 16
  %result = call <4 x i16> @llvm.aarch64.neon.sabd.v8i16(<4 x i16> %0, <4 x i16> splat (i16 1))
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @uaddlp(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @uaddlp(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i16>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TMP3:%.*]] = zext <vscale x 4 x i16> [[WIDE_LOAD]] to <vscale x 4 x i32>
; VScale1-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.addp.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> [[TMP3]], <vscale x 4 x i32> [[TMP3]])
; VScale1-NEXT:    [[TMP5:%.*]] = call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave2.nxv4i32(<vscale x 4 x i32> [[TMP4]])
; VScale1-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32> } [[TMP5]], 0
; VScale1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 2 x i32> [[TMP6]], ptr [[TMP7]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @uaddlp(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.uadalp.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> zeroinitializer, <vscale x 8 x i16> [[WIDE_LOAD]])
; VScale2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 4 x i32> [[TMP5]], ptr [[TMP6]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <4 x i16>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <2 x i32> @llvm.aarch64.neon.uaddlp.v2i32.v4i16(<4 x i16> %0)
  %arrayidx2 = getelementptr inbounds <2 x i32>, ptr %a, i64 %indvars.iv
  store <2 x i32> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @saddlp(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @saddlp(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i16>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TMP3:%.*]] = sext <vscale x 4 x i16> [[WIDE_LOAD]] to <vscale x 4 x i32>
; VScale1-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.addp.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> [[TMP3]], <vscale x 4 x i32> [[TMP3]])
; VScale1-NEXT:    [[TMP5:%.*]] = call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave2.nxv4i32(<vscale x 4 x i32> [[TMP4]])
; VScale1-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32> } [[TMP5]], 0
; VScale1-NEXT:    [[TMP7:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 2 x i32> [[TMP6]], ptr [[TMP7]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @saddlp(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.sadalp.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> zeroinitializer, <vscale x 8 x i16> [[WIDE_LOAD]])
; VScale2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 4 x i32> [[TMP5]], ptr [[TMP6]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <4 x i16>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <2 x i32> @llvm.aarch64.neon.saddlp.v2i32.v4i16(<4 x i16> %0)
  %arrayidx2 = getelementptr inbounds <2 x i32>, ptr %a, i64 %indvars.iv
  store <2 x i32> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @addp(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @addp(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x i32>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(<vscale x 2 x i32> splat (i32 8), <vscale x 2 x i32> [[WIDE_LOAD]], <2 x i32> <i32 0, i32 2>)
; VScale1-NEXT:    [[TMP4:%.*]] = call <vscale x 2 x i32> @llvm.vector.segmented.shuffle.nxv2i32.v2i32(<vscale x 2 x i32> splat (i32 8), <vscale x 2 x i32> [[WIDE_LOAD]], <2 x i32> <i32 1, i32 3>)
; VScale1-NEXT:    [[FROM_SVE:%.*]] = add <vscale x 2 x i32> [[TMP3]], [[TMP4]]
; VScale1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 2 x i32> [[FROM_SVE]], ptr [[TMP6]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @addp(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.addp.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> splat (i32 8), <vscale x 4 x i32> [[WIDE_LOAD]])
; VScale2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 4 x i32> [[TMP5]], ptr [[TMP8]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP9]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <2 x i32>, ptr %b, i64 %indvars.iv
  %0 = load <2 x i32>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <2 x i32> @llvm.aarch64.neon.addp.v2i32(<2 x i32> splat (i32 8), <2 x i32> %0)
  %arrayidx2 = getelementptr inbounds <2 x i32>, ptr %a, i64 %indvars.iv
  store <2 x i32> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @addp_i16(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @addp_i16(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i16>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(<vscale x 4 x i16> splat (i16 8), <vscale x 4 x i16> [[WIDE_LOAD]], <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
; VScale1-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i16> @llvm.vector.segmented.shuffle.nxv4i16.v4i32(<vscale x 4 x i16> splat (i16 8), <vscale x 4 x i16> [[WIDE_LOAD]], <4 x i32> <i32 1, i32 3, i32 5, i32 7>)
; VScale1-NEXT:    [[FROM_SVE:%.*]] = add <vscale x 4 x i16> [[TMP3]], [[TMP4]]
; VScale1-NEXT:    [[TMP10:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 4 x i16> [[FROM_SVE]], ptr [[TMP10]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @addp_i16(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(<vscale x 8 x i16> splat (i16 8), <vscale x 8 x i16> [[WIDE_LOAD]], <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
; VScale2-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x i16> @llvm.vector.segmented.shuffle.nxv8i16.v8i32(<vscale x 8 x i16> splat (i16 8), <vscale x 8 x i16> [[WIDE_LOAD]], <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
; VScale2-NEXT:    [[TMP11:%.*]] = add <vscale x 8 x i16> [[TMP5]], [[TMP6]]
; VScale2-NEXT:    [[TMP8:%.*]] = bitcast <vscale x 8 x i16> [[TMP11]] to <vscale x 4 x i32>
; VScale2-NEXT:    [[TMP9:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.left.nxv4i32(<vscale x 4 x i32> [[TMP8]], <vscale x 4 x i32> poison, i32 1)
; VScale2-NEXT:    [[TMP10:%.*]] = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(<vscale x 4 x i32> [[TMP8]], <vscale x 4 x i32> [[TMP9]], <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
; VScale2-NEXT:    [[TMP14:%.*]] = bitcast <vscale x 4 x i32> [[TMP10]] to <vscale x 8 x i16>
; VScale2-NEXT:    [[TMP12:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 8 x i16> [[TMP14]], ptr [[TMP12]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x i16>, ptr %b, i64 %indvars.iv
  %0 = load <4 x i16>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <4 x i16> @llvm.aarch64.neon.addp.v4i16(<4 x i16> splat (i16 8), <4 x i16> %0)
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @addp_f16(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @addp_f16(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x half>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x half>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(<vscale x 4 x half> splat (half 8.000000e+00), <vscale x 4 x half> [[WIDE_LOAD]], <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
; VScale1-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x half> @llvm.vector.segmented.shuffle.nxv4f16.v4i32(<vscale x 4 x half> splat (half 8.000000e+00), <vscale x 4 x half> [[WIDE_LOAD]], <4 x i32> <i32 1, i32 3, i32 5, i32 7>)
; VScale1-NEXT:    [[TMP5:%.*]] = fadd <vscale x 4 x half> [[TMP3]], [[TMP4]]
; VScale1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <4 x half>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 4 x half> [[TMP5]], ptr [[TMP6]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @addp_f16(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x half>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x half>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(<vscale x 8 x half> splat (half 8.000000e+00), <vscale x 8 x half> [[WIDE_LOAD]], <8 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
; VScale2-NEXT:    [[TMP6:%.*]] = call <vscale x 8 x half> @llvm.vector.segmented.shuffle.nxv8f16.v8i32(<vscale x 8 x half> splat (half 8.000000e+00), <vscale x 8 x half> [[WIDE_LOAD]], <8 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
; VScale2-NEXT:    [[TMP7:%.*]] = fadd <vscale x 8 x half> [[TMP5]], [[TMP6]]
; VScale2-NEXT:    [[TMP8:%.*]] = bitcast <vscale x 8 x half> [[TMP7]] to <vscale x 4 x i32>
; VScale2-NEXT:    [[TMP9:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.left.nxv4i32(<vscale x 4 x i32> [[TMP8]], <vscale x 4 x i32> poison, i32 1)
; VScale2-NEXT:    [[TMP10:%.*]] = call <vscale x 4 x i32> @llvm.vector.segmented.shuffle.nxv4i32.v4i32(<vscale x 4 x i32> [[TMP8]], <vscale x 4 x i32> [[TMP9]], <4 x i32> <i32 0, i32 2, i32 4, i32 6>)
; VScale2-NEXT:    [[TMP11:%.*]] = bitcast <vscale x 4 x i32> [[TMP10]] to <vscale x 8 x half>
; VScale2-NEXT:    [[TMP12:%.*]] = getelementptr inbounds <4 x half>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 8 x half> [[TMP11]], ptr [[TMP12]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x half>, ptr %b, i64 %indvars.iv
  %0 = load <4 x half>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <4 x half> @llvm.aarch64.neon.addp.v4f16(<4 x half> splat (half 8.), <4 x half> %0)
  %arrayidx2 = getelementptr inbounds <4 x half>, ptr %a, i64 %indvars.iv
  store <4 x half> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @facge(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @facge(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <2 x float>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x float>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TO_SVE:%.*]] = call <vscale x 4 x float> @llvm.vector.interleave2.nxv4f32(<vscale x 2 x float> [[WIDE_LOAD]], <vscale x 2 x float> poison)
; VScale1-NEXT:    [[TO_SVE1:%.*]] = call <vscale x 4 x float> @llvm.vector.interleave2.nxv4f32(<vscale x 2 x float> splat (float 1.000000e+00), <vscale x 2 x float> poison)
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i1> @llvm.aarch64.sve.facge.nxv4f32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x float> [[TO_SVE]], <vscale x 4 x float> [[TO_SVE1]])
; VScale1-NEXT:    [[TMP4:%.*]] = zext <vscale x 4 x i1> [[TMP3]] to <vscale x 4 x i32>
; VScale1-NEXT:    [[TMP7:%.*]] = call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave2.nxv4i32(<vscale x 4 x i32> [[TMP4]])
; VScale1-NEXT:    [[FROM_SVE:%.*]] = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32> } [[TMP7]], 0
; VScale1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 2 x i32> [[FROM_SVE]], ptr [[TMP5]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @facge(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <2 x float>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x float>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i1> @llvm.aarch64.sve.facge.nxv4f32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x float> [[WIDE_LOAD]], <vscale x 4 x float> splat (float 1.000000e+00))
; VScale2-NEXT:    [[TMP6:%.*]] = zext <vscale x 4 x i1> [[TMP5]] to <vscale x 4 x i32>
; VScale2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 4 x i32> [[TMP6]], ptr [[TMP7]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <2 x float>, ptr %b, i64 %indvars.iv
  %0 = load <2 x float>, ptr %arrayidx, align 16
  %result = call <2 x i32> @llvm.aarch64.neon.facge.v2i32.v2f32(<2 x float> %0, <2 x float> splat (float 1.0))
  %arrayidx2 = getelementptr inbounds <2 x i32>, ptr %a, i64 %indvars.iv
  store <2 x i32> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}


define void @fcvtzs(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @fcvtzs(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <4 x half>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x half>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TO_SVE:%.*]] = call <vscale x 8 x half> @llvm.vector.interleave2.nxv8f16(<vscale x 4 x half> [[WIDE_LOAD]], <vscale x 4 x half> poison)
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.fcvtzs.nxv8i16.nxv8f16(<vscale x 8 x i16> poison, <vscale x 8 x i1> splat (i1 true), <vscale x 8 x half> [[TO_SVE]])
; VScale1-NEXT:    [[TMP6:%.*]] = call { <vscale x 4 x i16>, <vscale x 4 x i16> } @llvm.vector.deinterleave2.nxv8i16(<vscale x 8 x i16> [[TMP3]])
; VScale1-NEXT:    [[FROM_SVE:%.*]] = extractvalue { <vscale x 4 x i16>, <vscale x 4 x i16> } [[TMP6]], 0
; VScale1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 4 x i16> [[FROM_SVE]], ptr [[TMP4]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @fcvtzs(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <4 x half>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x half>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 8 x i16> @llvm.aarch64.sve.fcvtzs.nxv8i16.nxv8f16(<vscale x 8 x i16> poison, <vscale x 8 x i1> splat (i1 true), <vscale x 8 x half> [[WIDE_LOAD]])
; VScale2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <4 x i16>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 8 x i16> [[TMP5]], ptr [[TMP6]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <4 x half>, ptr %b, i64 %indvars.iv
  %0 = load <4 x half>, ptr %arrayidx, align 16
  %result = call <4 x i16> @llvm.aarch64.neon.fcvtzs.v4i16.v4f16(<4 x half> %0)
  %arrayidx2 = getelementptr inbounds <4 x i16>, ptr %a, i64 %indvars.iv
  store <4 x i16> %result, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @sshl(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @sshl(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x i32>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TO_SVE:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> splat (i32 8), <vscale x 2 x i32> poison)
; VScale1-NEXT:    [[TO_SVE1:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> [[WIDE_LOAD]], <vscale x 2 x i32> poison)
; VScale1-NEXT:    [[SHL_MASK:%.*]] = icmp sle <vscale x 4 x i32> [[TO_SVE1]], zeroinitializer
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.srshl.nxv4i32(<vscale x 4 x i1> [[SHL_MASK]], <vscale x 4 x i32> [[TO_SVE]], <vscale x 4 x i32> [[TO_SVE1]])
; VScale1-NEXT:    [[SHR_MASK:%.*]] = call <vscale x 4 x i1> @llvm.ctlz.nxv4i1(<vscale x 4 x i1> [[SHL_MASK]], i1 true)
; VScale1-NEXT:    [[WIDE_BIDIR_SHL1:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.sqshl.nxv4i32(<vscale x 4 x i1> [[SHR_MASK]], <vscale x 4 x i32> [[TMP3]], <vscale x 4 x i32> [[TO_SVE1]])
; VScale1-NEXT:    [[TMP6:%.*]] = call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave2.nxv4i32(<vscale x 4 x i32> [[WIDE_BIDIR_SHL1]])
; VScale1-NEXT:    [[WIDE_BIDIR_SHL:%.*]] = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32> } [[TMP6]], 0
; VScale1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 2 x i32> [[WIDE_BIDIR_SHL]], ptr [[TMP4]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @sshl(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[SHL_MASK:%.*]] = icmp sle <vscale x 4 x i32> [[WIDE_LOAD]], zeroinitializer
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.srshl.nxv4i32(<vscale x 4 x i1> [[SHL_MASK]], <vscale x 4 x i32> splat (i32 8), <vscale x 4 x i32> [[WIDE_LOAD]])
; VScale2-NEXT:    [[SHR_MASK:%.*]] = call <vscale x 4 x i1> @llvm.ctlz.nxv4i1(<vscale x 4 x i1> [[SHL_MASK]], i1 true)
; VScale2-NEXT:    [[WIDE_BIDIR_SHL:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.sqshl.nxv4i32(<vscale x 4 x i1> [[SHR_MASK]], <vscale x 4 x i32> [[TMP5]], <vscale x 4 x i32> [[WIDE_LOAD]])
; VScale2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 4 x i32> [[WIDE_BIDIR_SHL]], ptr [[TMP6]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <2 x i32>, ptr %b, i64 %indvars.iv
  %0 = load <2 x i32>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <2 x i32> @llvm.aarch64.neon.sshl.v4i32(<2 x i32> splat (i32 8), <2 x i32> %0)
  %arrayidx2 = getelementptr inbounds <2 x i32>, ptr %a, i64 %indvars.iv
  store <2 x i32> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @vsli(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; VScale1-LABEL: define void @vsli(
; VScale1-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale1-NEXT:  [[ENTRY:.*:]]
; VScale1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; VScale1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale1:       [[VECTOR_PH]]:
; VScale1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; VScale1-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale1-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale1:       [[VECTOR_BODY]]:
; VScale1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale1-NEXT:    [[TMP2:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; VScale1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x i32>, ptr [[TMP2]], align 16
; VScale1-NEXT:    [[TO_SVE:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> splat (i32 1), <vscale x 2 x i32> poison)
; VScale1-NEXT:    [[TO_SVE1:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> [[WIDE_LOAD]], <vscale x 2 x i32> poison)
; VScale1-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.sli.nxv4i32(<vscale x 4 x i32> [[TO_SVE]], <vscale x 4 x i32> [[TO_SVE1]], i32 2)
; VScale1-NEXT:    [[TMP6:%.*]] = call { <vscale x 2 x i32>, <vscale x 2 x i32> } @llvm.vector.deinterleave2.nxv4i32(<vscale x 4 x i32> [[TMP3]])
; VScale1-NEXT:    [[FROM_SVE:%.*]] = extractvalue { <vscale x 2 x i32>, <vscale x 2 x i32> } [[TMP6]], 0
; VScale1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale1-NEXT:    store <vscale x 2 x i32> [[FROM_SVE]], ptr [[TMP4]], align 16
; VScale1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; VScale1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale1:       [[MIDDLE_BLOCK]]:
; VScale1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale1-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale1:       [[SCALAR_PH]]:
;
; VScale2-LABEL: define void @vsli(
; VScale2-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; VScale2-NEXT:  [[ENTRY:.*:]]
; VScale2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; VScale2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP1]]
; VScale2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; VScale2:       [[VECTOR_PH]]:
; VScale2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; VScale2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP3]]
; VScale2-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; VScale2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VScale2:       [[VECTOR_BODY]]:
; VScale2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VScale2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; VScale2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 16
; VScale2-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i32> @llvm.aarch64.sve.sli.nxv4i32(<vscale x 4 x i32> splat (i32 1), <vscale x 4 x i32> [[WIDE_LOAD]], i32 2)
; VScale2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <2 x i32>, ptr [[A]], i64 [[INDEX]]
; VScale2-NEXT:    store <vscale x 4 x i32> [[TMP5]], ptr [[TMP6]], align 16
; VScale2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; VScale2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VScale2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; VScale2:       [[MIDDLE_BLOCK]]:
; VScale2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; VScale2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; VScale2:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <2 x i32>, ptr %b, i64 %indvars.iv
  %0 = load <2 x i32>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <2 x i32> @llvm.aarch64.neon.vsli.v4i32(<2 x i32> splat (i32 1), <2 x i32> %0, i32 2)
  %arrayidx2 = getelementptr inbounds <2 x i32>, ptr %a, i64 %indvars.iv
  store <2 x i32> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @smull(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @smull(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x i32>, ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> splat (i32 8), <vscale x 2 x i32> poison)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> [[WIDE_LOAD]], <vscale x 2 x i32> poison)
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 2 x i64> @llvm.aarch64.sve.smullb.nxv2i64(<vscale x 4 x i32> [[TMP2]], <vscale x 4 x i32> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <2 x i64>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 2 x i64> [[TMP4]], ptr [[TMP5]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <2 x i32>, ptr %b, i64 %indvars.iv
  %0 = load <2 x i32>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <2 x i64> @llvm.aarch64.neon.smull.v2i64(<2 x i32> splat (i32 8), <2 x i32> %0)
  %arrayidx2 = getelementptr inbounds <2 x i64>, ptr %a, i64 %indvars.iv
  store <2 x i64> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @umull(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b) {
; CHECK-LABEL: define void @umull(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <2 x i32>, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 2 x i32>, ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> splat (i32 8), <vscale x 2 x i32> poison)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i32> @llvm.vector.interleave2.nxv4i32(<vscale x 2 x i32> [[WIDE_LOAD]], <vscale x 2 x i32> poison)
; CHECK-NEXT:    [[TMP4:%.*]] = call <vscale x 2 x i64> @llvm.aarch64.sve.umullb.nxv2i64(<vscale x 4 x i32> [[TMP2]], <vscale x 4 x i32> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds <2 x i64>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 2 x i64> [[TMP4]], ptr [[TMP5]], align 16
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <2 x i32>, ptr %b, i64 %indvars.iv
  %0 = load <2 x i32>, ptr %arrayidx, align 16
  %vpaddl1.i = tail call <2 x i64> @llvm.aarch64.neon.umull.v2i64(<2 x i32> splat (i32 8), <2 x i32> %0)
  %arrayidx2 = getelementptr inbounds <2 x i64>, ptr %a, i64 %indvars.iv
  store <2 x i64> %vpaddl1.i, ptr %arrayidx2, align 16
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @tbl1(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b, <8 x i8> %mask) {
; CHECK-LABEL: define void @tbl1(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]], <8 x i8> [[MASK:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    [[BROADCAST:%.*]] = call <vscale x 8 x i8> @llvm.vector.broadcast.nxv8i8.v8i8(<8 x i8> [[MASK]])
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.vector.interleave2.nxv16i8(<vscale x 8 x i8> [[BROADCAST]], <vscale x 8 x i8> poison)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i8> @llvm.aarch64.sve.tblq.nxv16i8(<vscale x 16 x i8> [[WIDE_LOAD]], <vscale x 16 x i8> [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = call { <vscale x 8 x i8>, <vscale x 8 x i8> } @llvm.vector.deinterleave2.nxv16i8(<vscale x 16 x i8> [[TMP3]])
; CHECK-NEXT:    [[TMP5:%.*]] = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8> } [[TMP4]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <8 x i8>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 8 x i8> [[TMP5]], ptr [[TMP6]], align 8
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <16 x i8>, ptr %b, i64 %indvars.iv
  %0 = load <16 x i8>, ptr %arrayidx, align 16
  %res = tail call <8 x i8> @llvm.aarch64.neon.tbl1.v8i8(<16 x i8> %0, <8 x i8> %mask)
  %arrayidx2 = getelementptr inbounds <8 x i8>, ptr %a, i64 %indvars.iv
  store <8 x i8> %res, ptr %arrayidx2, align 8
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}

define void @tbl2(ptr noalias nocapture noundef writeonly %a, ptr nocapture noundef readonly %b, <8 x i8> %mask) {
; CHECK-LABEL: define void @tbl2(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[A:%.*]], ptr noundef readonly captures(none) [[B:%.*]], <8 x i8> [[MASK:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 1024, [[TMP0]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 1024, [[TMP0]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 1024, [[N_MOD_VF]]
; CHECK-NEXT:    [[BROADCAST:%.*]] = call <vscale x 8 x i8> @llvm.vector.broadcast.nxv8i8.v8i8(<8 x i8> [[MASK]])
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds <16 x i8>, ptr [[B]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP1]], align 16
; CHECK-NEXT:    [[TMP2:%.*]] = call <vscale x 16 x i8> @llvm.vector.interleave2.nxv16i8(<vscale x 8 x i8> [[BROADCAST]], <vscale x 8 x i8> poison)
; CHECK-NEXT:    [[TMP3:%.*]] = call <vscale x 16 x i8> @llvm.aarch64.sve.tblq.nxv16i8(<vscale x 16 x i8> [[WIDE_LOAD]], <vscale x 16 x i8> [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = sub <vscale x 16 x i8> [[TMP2]], splat (i8 16)
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 16 x i8> @llvm.aarch64.sve.tbxq.nxv16i8(<vscale x 16 x i8> [[TMP3]], <vscale x 16 x i8> splat (i8 3), <vscale x 16 x i8> [[TMP4]])
; CHECK-NEXT:    [[TMP6:%.*]] = call { <vscale x 8 x i8>, <vscale x 8 x i8> } @llvm.vector.deinterleave2.nxv16i8(<vscale x 16 x i8> [[TMP5]])
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { <vscale x 8 x i8>, <vscale x 8 x i8> } [[TMP6]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <8 x i8>, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <vscale x 8 x i8> [[TMP7]], ptr [[TMP8]], align 8
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
entry:
  br label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret void

for.body:                                         ; preds = %entry, %for.body
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %for.body ]
  %arrayidx = getelementptr inbounds <16 x i8>, ptr %b, i64 %indvars.iv
  %0 = load <16 x i8>, ptr %arrayidx, align 16
  %res = tail call <8 x i8> @llvm.aarch64.neon.tbl2.v8i8(<16 x i8> %0, <16 x i8> splat (i8 3), <8 x i8> %mask)
  %arrayidx2 = getelementptr inbounds <8 x i8>, ptr %a, i64 %indvars.iv
  store <8 x i8> %res, ptr %arrayidx2, align 8
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body
}
