; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p loop-vectorize -force-vector-width=8 -S %s | FileCheck %s

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"


define dso_local void @quux(ptr noundef readonly captures(none) %arg, ptr noundef readonly captures(none) %arg1, ptr noundef writeonly captures(none) %arg2) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local void @quux(
; CHECK-SAME: ptr noundef readonly captures(none) [[ARG:%.*]], ptr noundef readonly captures(none) [[ARG1:%.*]], ptr noundef writeonly captures(none) [[ARG2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    br label %[[BB3:.*]]
; CHECK:       [[BB3]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i32 [ 0, %[[BB]] ], [ [[ADD24:%.*]], %[[BB23:.*]] ]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_SDIV_CONTINUE31:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw i32, ptr [[ARG]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <8 x i32>, ptr [[TMP0]], align 4, !tbaa [[TBAA5:![0-9]+]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw i32, ptr [[ARG1]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD1:%.*]] = load <8 x i32>, ptr [[TMP1]], align 4, !tbaa [[TBAA5]]
; CHECK-NEXT:    [[TMP2:%.*]] = icmp slt <8 x i32> [[WIDE_LOAD1]], zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = ashr <8 x i32> [[WIDE_LOAD]], splat (i32 1)
; CHECK-NEXT:    [[TMP4:%.*]] = xor <8 x i1> [[TMP2]], splat (i1 true)
; CHECK-NEXT:    [[TMP5:%.*]] = add nsw <8 x i32> [[WIDE_LOAD1]], [[TMP3]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp sge <8 x i32> [[TMP5]], [[WIDE_LOAD]]
; CHECK-NEXT:    [[TMP7:%.*]] = select <8 x i1> [[TMP4]], <8 x i1> [[TMP6]], <8 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <8 x i1> [[TMP7]], i64 0
; CHECK-NEXT:    br i1 [[TMP8]], label %[[PRED_SDIV_IF:.*]], label %[[PRED_SDIV_CONTINUE:.*]]
; CHECK:       [[PRED_SDIV_IF]]:
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <8 x i32> [[TMP5]], i64 0
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 0
; CHECK-NEXT:    [[TMP11:%.*]] = sdiv i32 [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[TMP12:%.*]] = insertelement <8 x i32> poison, i32 [[TMP11]], i64 0
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE]]
; CHECK:       [[PRED_SDIV_CONTINUE]]:
; CHECK-NEXT:    [[TMP13:%.*]] = phi <8 x i32> [ poison, %[[VECTOR_BODY]] ], [ [[TMP12]], %[[PRED_SDIV_IF]] ]
; CHECK-NEXT:    [[TMP14:%.*]] = extractelement <8 x i1> [[TMP7]], i64 1
; CHECK-NEXT:    br i1 [[TMP14]], label %[[PRED_SDIV_IF2:.*]], label %[[PRED_SDIV_CONTINUE3:.*]]
; CHECK:       [[PRED_SDIV_IF2]]:
; CHECK-NEXT:    [[TMP15:%.*]] = extractelement <8 x i32> [[TMP5]], i64 1
; CHECK-NEXT:    [[TMP16:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 1
; CHECK-NEXT:    [[TMP17:%.*]] = sdiv i32 [[TMP15]], [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = insertelement <8 x i32> [[TMP13]], i32 [[TMP17]], i64 1
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE3]]
; CHECK:       [[PRED_SDIV_CONTINUE3]]:
; CHECK-NEXT:    [[TMP19:%.*]] = phi <8 x i32> [ [[TMP13]], %[[PRED_SDIV_CONTINUE]] ], [ [[TMP18]], %[[PRED_SDIV_IF2]] ]
; CHECK-NEXT:    [[TMP20:%.*]] = extractelement <8 x i1> [[TMP7]], i64 2
; CHECK-NEXT:    br i1 [[TMP20]], label %[[PRED_SDIV_IF4:.*]], label %[[PRED_SDIV_CONTINUE5:.*]]
; CHECK:       [[PRED_SDIV_IF4]]:
; CHECK-NEXT:    [[TMP21:%.*]] = extractelement <8 x i32> [[TMP5]], i64 2
; CHECK-NEXT:    [[TMP22:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 2
; CHECK-NEXT:    [[TMP23:%.*]] = sdiv i32 [[TMP21]], [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = insertelement <8 x i32> [[TMP19]], i32 [[TMP23]], i64 2
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE5]]
; CHECK:       [[PRED_SDIV_CONTINUE5]]:
; CHECK-NEXT:    [[TMP25:%.*]] = phi <8 x i32> [ [[TMP19]], %[[PRED_SDIV_CONTINUE3]] ], [ [[TMP24]], %[[PRED_SDIV_IF4]] ]
; CHECK-NEXT:    [[TMP26:%.*]] = extractelement <8 x i1> [[TMP7]], i64 3
; CHECK-NEXT:    br i1 [[TMP26]], label %[[PRED_SDIV_IF6:.*]], label %[[PRED_SDIV_CONTINUE7:.*]]
; CHECK:       [[PRED_SDIV_IF6]]:
; CHECK-NEXT:    [[TMP27:%.*]] = extractelement <8 x i32> [[TMP5]], i64 3
; CHECK-NEXT:    [[TMP28:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 3
; CHECK-NEXT:    [[TMP29:%.*]] = sdiv i32 [[TMP27]], [[TMP28]]
; CHECK-NEXT:    [[TMP30:%.*]] = insertelement <8 x i32> [[TMP25]], i32 [[TMP29]], i64 3
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE7]]
; CHECK:       [[PRED_SDIV_CONTINUE7]]:
; CHECK-NEXT:    [[TMP31:%.*]] = phi <8 x i32> [ [[TMP25]], %[[PRED_SDIV_CONTINUE5]] ], [ [[TMP30]], %[[PRED_SDIV_IF6]] ]
; CHECK-NEXT:    [[TMP32:%.*]] = extractelement <8 x i1> [[TMP7]], i64 4
; CHECK-NEXT:    br i1 [[TMP32]], label %[[PRED_SDIV_IF8:.*]], label %[[PRED_SDIV_CONTINUE9:.*]]
; CHECK:       [[PRED_SDIV_IF8]]:
; CHECK-NEXT:    [[TMP33:%.*]] = extractelement <8 x i32> [[TMP5]], i64 4
; CHECK-NEXT:    [[TMP34:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 4
; CHECK-NEXT:    [[TMP35:%.*]] = sdiv i32 [[TMP33]], [[TMP34]]
; CHECK-NEXT:    [[TMP36:%.*]] = insertelement <8 x i32> [[TMP31]], i32 [[TMP35]], i64 4
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE9]]
; CHECK:       [[PRED_SDIV_CONTINUE9]]:
; CHECK-NEXT:    [[TMP37:%.*]] = phi <8 x i32> [ [[TMP31]], %[[PRED_SDIV_CONTINUE7]] ], [ [[TMP36]], %[[PRED_SDIV_IF8]] ]
; CHECK-NEXT:    [[TMP38:%.*]] = extractelement <8 x i1> [[TMP7]], i64 5
; CHECK-NEXT:    br i1 [[TMP38]], label %[[PRED_SDIV_IF10:.*]], label %[[PRED_SDIV_CONTINUE11:.*]]
; CHECK:       [[PRED_SDIV_IF10]]:
; CHECK-NEXT:    [[TMP39:%.*]] = extractelement <8 x i32> [[TMP5]], i64 5
; CHECK-NEXT:    [[TMP40:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 5
; CHECK-NEXT:    [[TMP41:%.*]] = sdiv i32 [[TMP39]], [[TMP40]]
; CHECK-NEXT:    [[TMP42:%.*]] = insertelement <8 x i32> [[TMP37]], i32 [[TMP41]], i64 5
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE11]]
; CHECK:       [[PRED_SDIV_CONTINUE11]]:
; CHECK-NEXT:    [[TMP43:%.*]] = phi <8 x i32> [ [[TMP37]], %[[PRED_SDIV_CONTINUE9]] ], [ [[TMP42]], %[[PRED_SDIV_IF10]] ]
; CHECK-NEXT:    [[TMP44:%.*]] = extractelement <8 x i1> [[TMP7]], i64 6
; CHECK-NEXT:    br i1 [[TMP44]], label %[[PRED_SDIV_IF12:.*]], label %[[PRED_SDIV_CONTINUE13:.*]]
; CHECK:       [[PRED_SDIV_IF12]]:
; CHECK-NEXT:    [[TMP45:%.*]] = extractelement <8 x i32> [[TMP5]], i64 6
; CHECK-NEXT:    [[TMP46:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 6
; CHECK-NEXT:    [[TMP47:%.*]] = sdiv i32 [[TMP45]], [[TMP46]]
; CHECK-NEXT:    [[TMP48:%.*]] = insertelement <8 x i32> [[TMP43]], i32 [[TMP47]], i64 6
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE13]]
; CHECK:       [[PRED_SDIV_CONTINUE13]]:
; CHECK-NEXT:    [[TMP49:%.*]] = phi <8 x i32> [ [[TMP43]], %[[PRED_SDIV_CONTINUE11]] ], [ [[TMP48]], %[[PRED_SDIV_IF12]] ]
; CHECK-NEXT:    [[TMP50:%.*]] = extractelement <8 x i1> [[TMP7]], i64 7
; CHECK-NEXT:    br i1 [[TMP50]], label %[[PRED_SDIV_IF14:.*]], label %[[PRED_SDIV_CONTINUE15:.*]]
; CHECK:       [[PRED_SDIV_IF14]]:
; CHECK-NEXT:    [[TMP51:%.*]] = extractelement <8 x i32> [[TMP5]], i64 7
; CHECK-NEXT:    [[TMP52:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 7
; CHECK-NEXT:    [[TMP53:%.*]] = sdiv i32 [[TMP51]], [[TMP52]]
; CHECK-NEXT:    [[TMP54:%.*]] = insertelement <8 x i32> [[TMP49]], i32 [[TMP53]], i64 7
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE15]]
; CHECK:       [[PRED_SDIV_CONTINUE15]]:
; CHECK-NEXT:    [[TMP55:%.*]] = phi <8 x i32> [ [[TMP49]], %[[PRED_SDIV_CONTINUE13]] ], [ [[TMP54]], %[[PRED_SDIV_IF14]] ]
; CHECK-NEXT:    [[TMP56:%.*]] = sub nsw <8 x i32> [[TMP3]], [[WIDE_LOAD1]]
; CHECK-NEXT:    [[TMP57:%.*]] = icmp sge <8 x i32> [[TMP56]], [[WIDE_LOAD]]
; CHECK-NEXT:    [[TMP58:%.*]] = select <8 x i1> [[TMP2]], <8 x i1> [[TMP57]], <8 x i1> zeroinitializer
; CHECK-NEXT:    [[TMP59:%.*]] = extractelement <8 x i1> [[TMP58]], i64 0
; CHECK-NEXT:    br i1 [[TMP59]], label %[[PRED_SDIV_IF16:.*]], label %[[PRED_SDIV_CONTINUE17:.*]]
; CHECK:       [[PRED_SDIV_IF16]]:
; CHECK-NEXT:    [[TMP60:%.*]] = extractelement <8 x i32> [[TMP56]], i64 0
; CHECK-NEXT:    [[TMP61:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 0
; CHECK-NEXT:    [[TMP62:%.*]] = sdiv i32 [[TMP60]], [[TMP61]]
; CHECK-NEXT:    [[TMP63:%.*]] = insertelement <8 x i32> poison, i32 [[TMP62]], i64 0
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE17]]
; CHECK:       [[PRED_SDIV_CONTINUE17]]:
; CHECK-NEXT:    [[TMP64:%.*]] = phi <8 x i32> [ poison, %[[PRED_SDIV_CONTINUE15]] ], [ [[TMP63]], %[[PRED_SDIV_IF16]] ]
; CHECK-NEXT:    [[TMP65:%.*]] = extractelement <8 x i1> [[TMP58]], i64 1
; CHECK-NEXT:    br i1 [[TMP65]], label %[[PRED_SDIV_IF18:.*]], label %[[PRED_SDIV_CONTINUE19:.*]]
; CHECK:       [[PRED_SDIV_IF18]]:
; CHECK-NEXT:    [[TMP66:%.*]] = extractelement <8 x i32> [[TMP56]], i64 1
; CHECK-NEXT:    [[TMP67:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 1
; CHECK-NEXT:    [[TMP68:%.*]] = sdiv i32 [[TMP66]], [[TMP67]]
; CHECK-NEXT:    [[TMP69:%.*]] = insertelement <8 x i32> [[TMP64]], i32 [[TMP68]], i64 1
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE19]]
; CHECK:       [[PRED_SDIV_CONTINUE19]]:
; CHECK-NEXT:    [[TMP70:%.*]] = phi <8 x i32> [ [[TMP64]], %[[PRED_SDIV_CONTINUE17]] ], [ [[TMP69]], %[[PRED_SDIV_IF18]] ]
; CHECK-NEXT:    [[TMP71:%.*]] = extractelement <8 x i1> [[TMP58]], i64 2
; CHECK-NEXT:    br i1 [[TMP71]], label %[[PRED_SDIV_IF20:.*]], label %[[PRED_SDIV_CONTINUE21:.*]]
; CHECK:       [[PRED_SDIV_IF20]]:
; CHECK-NEXT:    [[TMP72:%.*]] = extractelement <8 x i32> [[TMP56]], i64 2
; CHECK-NEXT:    [[TMP73:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 2
; CHECK-NEXT:    [[TMP74:%.*]] = sdiv i32 [[TMP72]], [[TMP73]]
; CHECK-NEXT:    [[TMP75:%.*]] = insertelement <8 x i32> [[TMP70]], i32 [[TMP74]], i64 2
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE21]]
; CHECK:       [[PRED_SDIV_CONTINUE21]]:
; CHECK-NEXT:    [[TMP76:%.*]] = phi <8 x i32> [ [[TMP70]], %[[PRED_SDIV_CONTINUE19]] ], [ [[TMP75]], %[[PRED_SDIV_IF20]] ]
; CHECK-NEXT:    [[TMP77:%.*]] = extractelement <8 x i1> [[TMP58]], i64 3
; CHECK-NEXT:    br i1 [[TMP77]], label %[[PRED_SDIV_IF22:.*]], label %[[PRED_SDIV_CONTINUE23:.*]]
; CHECK:       [[PRED_SDIV_IF22]]:
; CHECK-NEXT:    [[TMP78:%.*]] = extractelement <8 x i32> [[TMP56]], i64 3
; CHECK-NEXT:    [[TMP79:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 3
; CHECK-NEXT:    [[TMP80:%.*]] = sdiv i32 [[TMP78]], [[TMP79]]
; CHECK-NEXT:    [[TMP81:%.*]] = insertelement <8 x i32> [[TMP76]], i32 [[TMP80]], i64 3
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE23]]
; CHECK:       [[PRED_SDIV_CONTINUE23]]:
; CHECK-NEXT:    [[TMP82:%.*]] = phi <8 x i32> [ [[TMP76]], %[[PRED_SDIV_CONTINUE21]] ], [ [[TMP81]], %[[PRED_SDIV_IF22]] ]
; CHECK-NEXT:    [[TMP83:%.*]] = extractelement <8 x i1> [[TMP58]], i64 4
; CHECK-NEXT:    br i1 [[TMP83]], label %[[PRED_SDIV_IF24:.*]], label %[[PRED_SDIV_CONTINUE25:.*]]
; CHECK:       [[PRED_SDIV_IF24]]:
; CHECK-NEXT:    [[TMP84:%.*]] = extractelement <8 x i32> [[TMP56]], i64 4
; CHECK-NEXT:    [[TMP85:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 4
; CHECK-NEXT:    [[TMP86:%.*]] = sdiv i32 [[TMP84]], [[TMP85]]
; CHECK-NEXT:    [[TMP87:%.*]] = insertelement <8 x i32> [[TMP82]], i32 [[TMP86]], i64 4
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE25]]
; CHECK:       [[PRED_SDIV_CONTINUE25]]:
; CHECK-NEXT:    [[TMP88:%.*]] = phi <8 x i32> [ [[TMP82]], %[[PRED_SDIV_CONTINUE23]] ], [ [[TMP87]], %[[PRED_SDIV_IF24]] ]
; CHECK-NEXT:    [[TMP89:%.*]] = extractelement <8 x i1> [[TMP58]], i64 5
; CHECK-NEXT:    br i1 [[TMP89]], label %[[PRED_SDIV_IF26:.*]], label %[[PRED_SDIV_CONTINUE27:.*]]
; CHECK:       [[PRED_SDIV_IF26]]:
; CHECK-NEXT:    [[TMP90:%.*]] = extractelement <8 x i32> [[TMP56]], i64 5
; CHECK-NEXT:    [[TMP91:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 5
; CHECK-NEXT:    [[TMP92:%.*]] = sdiv i32 [[TMP90]], [[TMP91]]
; CHECK-NEXT:    [[TMP93:%.*]] = insertelement <8 x i32> [[TMP88]], i32 [[TMP92]], i64 5
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE27]]
; CHECK:       [[PRED_SDIV_CONTINUE27]]:
; CHECK-NEXT:    [[TMP94:%.*]] = phi <8 x i32> [ [[TMP88]], %[[PRED_SDIV_CONTINUE25]] ], [ [[TMP93]], %[[PRED_SDIV_IF26]] ]
; CHECK-NEXT:    [[TMP95:%.*]] = extractelement <8 x i1> [[TMP58]], i64 6
; CHECK-NEXT:    br i1 [[TMP95]], label %[[PRED_SDIV_IF28:.*]], label %[[PRED_SDIV_CONTINUE29:.*]]
; CHECK:       [[PRED_SDIV_IF28]]:
; CHECK-NEXT:    [[TMP96:%.*]] = extractelement <8 x i32> [[TMP56]], i64 6
; CHECK-NEXT:    [[TMP97:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 6
; CHECK-NEXT:    [[TMP98:%.*]] = sdiv i32 [[TMP96]], [[TMP97]]
; CHECK-NEXT:    [[TMP99:%.*]] = insertelement <8 x i32> [[TMP94]], i32 [[TMP98]], i64 6
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE29]]
; CHECK:       [[PRED_SDIV_CONTINUE29]]:
; CHECK-NEXT:    [[TMP100:%.*]] = phi <8 x i32> [ [[TMP94]], %[[PRED_SDIV_CONTINUE27]] ], [ [[TMP99]], %[[PRED_SDIV_IF28]] ]
; CHECK-NEXT:    [[TMP101:%.*]] = extractelement <8 x i1> [[TMP58]], i64 7
; CHECK-NEXT:    br i1 [[TMP101]], label %[[PRED_SDIV_IF30:.*]], label %[[PRED_SDIV_CONTINUE31]]
; CHECK:       [[PRED_SDIV_IF30]]:
; CHECK-NEXT:    [[TMP102:%.*]] = extractelement <8 x i32> [[TMP56]], i64 7
; CHECK-NEXT:    [[TMP103:%.*]] = extractelement <8 x i32> [[WIDE_LOAD]], i64 7
; CHECK-NEXT:    [[TMP104:%.*]] = sdiv i32 [[TMP102]], [[TMP103]]
; CHECK-NEXT:    [[TMP105:%.*]] = insertelement <8 x i32> [[TMP100]], i32 [[TMP104]], i64 7
; CHECK-NEXT:    br label %[[PRED_SDIV_CONTINUE31]]
; CHECK:       [[PRED_SDIV_CONTINUE31]]:
; CHECK-NEXT:    [[TMP106:%.*]] = phi <8 x i32> [ [[TMP100]], %[[PRED_SDIV_CONTINUE29]] ], [ [[TMP105]], %[[PRED_SDIV_IF30]] ]
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <8 x i1> [[TMP57]], <8 x i32> [[TMP106]], <8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP107:%.*]] = sub nsw <8 x i32> zeroinitializer, [[PREDPHI]]
; CHECK-NEXT:    [[PREDPHI32:%.*]] = select <8 x i1> [[TMP7]], <8 x i32> [[TMP55]], <8 x i32> zeroinitializer
; CHECK-NEXT:    [[PREDPHI33:%.*]] = select <8 x i1> [[TMP2]], <8 x i32> [[TMP107]], <8 x i32> [[PREDPHI32]]
; CHECK-NEXT:    [[TMP108:%.*]] = trunc <8 x i32> [[PREDPHI33]] to <8 x i16>
; CHECK-NEXT:    [[TMP109:%.*]] = getelementptr inbounds nuw i16, ptr [[ARG2]], i64 [[INDEX]]
; CHECK-NEXT:    store <8 x i16> [[TMP108]], ptr [[TMP109]], align 2, !tbaa [[TBAA9:![0-9]+]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; CHECK-NEXT:    [[TMP110:%.*]] = icmp eq i64 [[INDEX_NEXT]], 64
; CHECK-NEXT:    br i1 [[TMP110]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[BB23]]
; CHECK:       [[BB23]]:
; CHECK-NEXT:    [[ADD24]] = add nuw nsw i32 [[PHI]], 1
; CHECK-NEXT:    [[ICMP25:%.*]] = icmp eq i32 [[ADD24]], 8
; CHECK-NEXT:    br i1 [[ICMP25]], label %[[BB26:.*]], label %[[BB3]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       [[BB26]]:
; CHECK-NEXT:    ret void
;
bb:
  br label %bb3

bb3:                                              ; preds = %bb23, %bb
  %phi = phi i32 [ 0, %bb ], [ %add24, %bb23 ]
  br label %bb4

bb4:                                              ; preds = %bb18, %bb3
  %phi5 = phi i64 [ 0, %bb3 ], [ %add21, %bb18 ]
  %getelementptr = getelementptr inbounds nuw i32, ptr %arg, i64 %phi5
  %load = load i32, ptr %getelementptr, align 4, !tbaa !5
  %getelementptr6 = getelementptr inbounds nuw i32, ptr %arg1, i64 %phi5
  %load7 = load i32, ptr %getelementptr6, align 4, !tbaa !5
  %icmp = icmp slt i32 %load7, 0
  %ashr = ashr i32 %load, 1
  br i1 %icmp, label %bb8, label %bb14

bb8:                                              ; preds = %bb4
  %sub = sub nsw i32 %ashr, %load7
  %icmp9 = icmp slt i32 %sub, %load
  br i1 %icmp9, label %bb11, label %bb10

bb10:                                             ; preds = %bb8
  %sdiv = sdiv i32 %sub, %load
  br label %bb11

bb11:                                             ; preds = %bb10, %bb8
  %phi12 = phi i32 [ %sdiv, %bb10 ], [ 0, %bb8 ]
  %sub13 = sub nsw i32 0, %phi12
  br label %bb18

bb14:                                             ; preds = %bb4
  %add = add nsw i32 %load7, %ashr
  %icmp15 = icmp slt i32 %add, %load
  br i1 %icmp15, label %bb18, label %bb16

bb16:                                             ; preds = %bb14
  %sdiv17 = sdiv i32 %add, %load
  br label %bb18

bb18:                                             ; preds = %bb16, %bb14, %bb11
  %phi19 = phi i32 [ %sub13, %bb11 ], [ %sdiv17, %bb16 ], [ 0, %bb14 ]
  %trunc = trunc i32 %phi19 to i16
  %getelementptr20 = getelementptr inbounds nuw i16, ptr %arg2, i64 %phi5
  store i16 %trunc, ptr %getelementptr20, align 2, !tbaa !9
  %add21 = add nuw nsw i64 %phi5, 1
  %icmp22 = icmp eq i64 %add21, 64
  br i1 %icmp22, label %bb23, label %bb4, !llvm.loop !11

bb23:                                             ; preds = %bb18
  %add24 = add nuw nsw i32 %phi, 1
  %icmp25 = icmp eq i32 %add24, 8
  br i1 %icmp25, label %bb26, label %bb3, !llvm.loop !13

bb26:                                             ; preds = %bb23
  ret void
}

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable "frame-pointer"="non-leaf" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "no-signed-zeros-fp-math"="true" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="oryon-1" "target-features"="+aes,+bf16,+bti,+ccidx,+complxnum,+crc,+dit,+dotprod,+flagm,+fp-armv8,+i8mm,+jsconv,+lse,+neon,+outline-atomics,+pauth,+perfmon,+predres,+rand,+ras,+rcpc,+rdm,+sb,+sha2,+sha3,+sm4,+spe,+ssbs,+v8.1a,+v8.2a,+v8.3a,+v8.4a,+v8.5a,+v8.6a,+v8a,-fmv" "unsafe-fp-math"="true" }

!llvm.module.flags = !{!0, !1, !2, !3, !4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 1}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = !{!10, !10, i64 0}
!10 = !{!"short", !7, i64 0}
!11 = distinct !{!11, !12}
!12 = !{!"llvm.loop.unroll.disable"}
!13 = distinct !{!13, !12}
;.
; CHECK: [[TBAA5]] = !{[[META6:![0-9]+]], [[META6]], i64 0}
; CHECK: [[META6]] = !{!"int", [[META7:![0-9]+]], i64 0}
; CHECK: [[META7]] = !{!"omnipotent char", [[META8:![0-9]+]], i64 0}
; CHECK: [[META8]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[TBAA9]] = !{[[META10:![0-9]+]], [[META10]], i64 0}
; CHECK: [[META10]] = !{!"short", [[META7]], i64 0}
; CHECK: [[LOOP11]] = distinct !{[[LOOP11]], [[META12:![0-9]+]], [[META13:![0-9]+]], [[META14:![0-9]+]]}
; CHECK: [[META12]] = !{!"llvm.loop.unroll.disable"}
; CHECK: [[META13]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META14]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP15]] = distinct !{[[LOOP15]], [[META12]]}
;.
