; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 5
; RUN: opt -S < %s -p loop-vectorize -enable-early-exit-vectorization -max-num-faulting-pointers=1 \
; RUN:   | FileCheck %s --check-prefixes=CHECK,MAX1
; RUN: opt -S < %s -p loop-vectorize -enable-early-exit-vectorization -max-num-faulting-pointers=2 \
; RUN:   | FileCheck %s --check-prefixes=CHECK,MAX2

target triple = "aarch64-unknown-linux-gnu"

declare void @init_mem(ptr, i64);


define i64 @same_exit_block_no_live_outs_one_faulting_ptr(ptr %p1) #0 {
; CHECK-LABEL: define i64 @same_exit_block_no_live_outs_one_faulting_ptr(
; CHECK-SAME: ptr [[P1:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[P11:%.*]] = ptrtoint ptr [[P1]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 16
; CHECK-NEXT:    [[TMP2:%.*]] = call i64 @llvm.umax.i64(i64 32, i64 [[TMP1]])
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP2]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; CHECK:       [[VECTOR_SCEVCHECK]]:
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[P11]], 3
; CHECK-NEXT:    [[TMP4:%.*]] = add nuw i64 [[P11]], 3
; CHECK-NEXT:    [[TMP5:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP6:%.*]] = shl nuw nsw i64 [[TMP5]], 4
; CHECK-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP4]], [[TMP6]]
; CHECK-NEXT:    [[TMP8:%.*]] = mul i64 [[TMP7]], [[TMP5]]
; CHECK-NEXT:    [[TMP9:%.*]] = shl i64 [[TMP8]], 4
; CHECK-NEXT:    [[TMP10:%.*]] = sub i64 [[TMP3]], [[TMP9]]
; CHECK-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP10]], 0
; CHECK-NEXT:    br i1 [[IDENT_CHECK]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP11:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP12:%.*]] = mul i64 [[TMP11]], 16
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP12]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP13:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP13]], 16
; CHECK-NEXT:    [[TMP15:%.*]] = add i64 3, [[N_VEC]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX2:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT3:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX2]]
; CHECK-NEXT:    [[TMP16:%.*]] = add i64 [[OFFSET_IDX]], 0
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i8, ptr [[TMP17]], i32 0
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP18]], align 1
; CHECK-NEXT:    [[TMP19:%.*]] = icmp eq <vscale x 16 x i8> [[WIDE_LOAD]], splat (i8 3)
; CHECK-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX2]], [[TMP14]]
; CHECK-NEXT:    [[TMP20:%.*]] = xor <vscale x 16 x i1> [[TMP19]], splat (i1 true)
; CHECK-NEXT:    [[TMP21:%.*]] = call i1 @llvm.vector.reduce.or.nxv16i1(<vscale x 16 x i1> [[TMP20]])
; CHECK-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT3]], [[N_VEC]]
; CHECK-NEXT:    [[TMP23:%.*]] = or i1 [[TMP21]], [[TMP22]]
; CHECK-NEXT:    br i1 [[TMP23]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_SPLIT]]:
; CHECK-NEXT:    br i1 [[TMP21]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[LOOP_END]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP15]], %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ], [ 3, %[[VECTOR_SCEVCHECK]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], 3
; CHECK-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; CHECK:       [[LOOP_INC]]:
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[LOOP_END]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ], [ 0, %[[MIDDLE_BLOCK]] ], [ 1, %[[VECTOR_EARLY_EXIT]] ]
; CHECK-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %cmp3 = icmp eq i8 %ld1, 3
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ 1, %loop ], [ 0, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_pre_inc_use1_too_small_allocas() #0 {
; MAX1-LABEL: define i64 @same_exit_block_pre_inc_use1_too_small_allocas(
; MAX1-SAME: ) #[[ATTR0]] {
; MAX1-NEXT:  [[ENTRY:.*]]:
; MAX1-NEXT:    [[P1:%.*]] = alloca [42 x i8], align 4
; MAX1-NEXT:    [[P2:%.*]] = alloca [42 x i8], align 4
; MAX1-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; MAX1-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; MAX1-NEXT:    br label %[[LOOP:.*]]
; MAX1:       [[LOOP]]:
; MAX1-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; MAX1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX1-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; MAX1-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX1-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; MAX1:       [[LOOP_INC]]:
; MAX1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX1-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX1-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; MAX1:       [[LOOP_END]]:
; MAX1-NEXT:    [[RETVAL:%.*]] = phi i64 [ [[INDEX]], %[[LOOP]] ], [ 67, %[[LOOP_INC]] ]
; MAX1-NEXT:    ret i64 [[RETVAL]]
;
; MAX2-LABEL: define i64 @same_exit_block_pre_inc_use1_too_small_allocas(
; MAX2-SAME: ) #[[ATTR0]] {
; MAX2-NEXT:  [[ENTRY:.*]]:
; MAX2-NEXT:    [[P1:%.*]] = alloca [42 x i8], align 4
; MAX2-NEXT:    [[P11:%.*]] = ptrtoint ptr [[P1]] to i64
; MAX2-NEXT:    [[P2:%.*]] = alloca [42 x i8], align 4
; MAX2-NEXT:    [[P22:%.*]] = ptrtoint ptr [[P2]] to i64
; MAX2-NEXT:    call void @init_mem(ptr [[P1]], i64 1024)
; MAX2-NEXT:    call void @init_mem(ptr [[P2]], i64 1024)
; MAX2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 16
; MAX2-NEXT:    [[TMP2:%.*]] = call i64 @llvm.umax.i64(i64 32, i64 [[TMP1]])
; MAX2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP2]]
; MAX2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; MAX2:       [[VECTOR_SCEVCHECK]]:
; MAX2-NEXT:    [[TMP3:%.*]] = add i64 [[P11]], 3
; MAX2-NEXT:    [[TMP4:%.*]] = add nuw nsw i64 [[P11]], 3
; MAX2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP6:%.*]] = shl nuw nsw i64 [[TMP5]], 4
; MAX2-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP4]], [[TMP6]]
; MAX2-NEXT:    [[TMP8:%.*]] = mul i64 [[TMP7]], [[TMP5]]
; MAX2-NEXT:    [[TMP9:%.*]] = shl i64 [[TMP8]], 4
; MAX2-NEXT:    [[TMP10:%.*]] = sub i64 [[TMP3]], [[TMP9]]
; MAX2-NEXT:    [[TMP11:%.*]] = add i64 [[P22]], 3
; MAX2-NEXT:    [[TMP12:%.*]] = add nuw nsw i64 [[P22]], 3
; MAX2-NEXT:    [[TMP13:%.*]] = udiv i64 [[TMP12]], [[TMP6]]
; MAX2-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP13]], [[TMP5]]
; MAX2-NEXT:    [[TMP15:%.*]] = shl i64 [[TMP14]], 4
; MAX2-NEXT:    [[TMP16:%.*]] = sub i64 [[TMP11]], [[TMP15]]
; MAX2-NEXT:    br i1 true, label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; MAX2:       [[VECTOR_PH]]:
; MAX2-NEXT:    [[TMP17:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP18:%.*]] = mul i64 [[TMP17]], 16
; MAX2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP18]]
; MAX2-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; MAX2-NEXT:    [[TMP19:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP20:%.*]] = mul i64 [[TMP19]], 16
; MAX2-NEXT:    [[TMP21:%.*]] = add i64 3, [[N_VEC]]
; MAX2-NEXT:    [[TMP22:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; MAX2-NEXT:    [[TMP23:%.*]] = mul <vscale x 16 x i64> [[TMP22]], splat (i64 1)
; MAX2-NEXT:    [[INDUCTION:%.*]] = add <vscale x 16 x i64> splat (i64 3), [[TMP23]]
; MAX2-NEXT:    [[TMP24:%.*]] = mul i64 1, [[TMP20]]
; MAX2-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP24]], i64 0
; MAX2-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; MAX2-NEXT:    br label %[[VECTOR_BODY:.*]]
; MAX2:       [[VECTOR_BODY]]:
; MAX2-NEXT:    [[INDEX3:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT5:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 16 x i64> [ [[INDUCTION]], %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX3]]
; MAX2-NEXT:    [[TMP25:%.*]] = add i64 [[OFFSET_IDX]], 0
; MAX2-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP25]]
; MAX2-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i8, ptr [[TMP26]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP27]], align 1
; MAX2-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[TMP25]]
; MAX2-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i8, ptr [[TMP28]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD4:%.*]] = load <vscale x 16 x i8>, ptr [[TMP29]], align 1
; MAX2-NEXT:    [[TMP30:%.*]] = icmp eq <vscale x 16 x i8> [[WIDE_LOAD]], [[WIDE_LOAD4]]
; MAX2-NEXT:    [[INDEX_NEXT5]] = add nuw i64 [[INDEX3]], [[TMP20]]
; MAX2-NEXT:    [[TMP31:%.*]] = xor <vscale x 16 x i1> [[TMP30]], splat (i1 true)
; MAX2-NEXT:    [[TMP32:%.*]] = call i1 @llvm.vector.reduce.or.nxv16i1(<vscale x 16 x i1> [[TMP31]])
; MAX2-NEXT:    [[TMP33:%.*]] = icmp eq i64 [[INDEX_NEXT5]], [[N_VEC]]
; MAX2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 16 x i64> [[VEC_IND]], [[DOTSPLAT]]
; MAX2-NEXT:    [[TMP34:%.*]] = or i1 [[TMP32]], [[TMP33]]
; MAX2-NEXT:    br i1 [[TMP34]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; MAX2:       [[MIDDLE_SPLIT]]:
; MAX2-NEXT:    br i1 [[TMP32]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; MAX2:       [[MIDDLE_BLOCK]]:
; MAX2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; MAX2-NEXT:    br i1 [[CMP_N]], label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; MAX2:       [[VECTOR_EARLY_EXIT]]:
; MAX2-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv16i1(<vscale x 16 x i1> [[TMP31]], i1 true)
; MAX2-NEXT:    [[EARLY_EXIT_VALUE:%.*]] = extractelement <vscale x 16 x i64> [[VEC_IND]], i64 [[FIRST_ACTIVE_LANE]]
; MAX2-NEXT:    br label %[[LOOP_END]]
; MAX2:       [[SCALAR_PH]]:
; MAX2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP21]], %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ], [ 3, %[[VECTOR_SCEVCHECK]] ]
; MAX2-NEXT:    br label %[[LOOP:.*]]
; MAX2:       [[LOOP]]:
; MAX2-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; MAX2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX2-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; MAX2-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX2-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; MAX2:       [[LOOP_INC]]:
; MAX2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX2-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP5:![0-9]+]]
; MAX2:       [[LOOP_END]]:
; MAX2-NEXT:    [[RETVAL:%.*]] = phi i64 [ [[INDEX]], %[[LOOP]] ], [ 67, %[[LOOP_INC]] ], [ 67, %[[MIDDLE_BLOCK]] ], [ [[EARLY_EXIT_VALUE]], %[[VECTOR_EARLY_EXIT]] ]
; MAX2-NEXT:    ret i64 [[RETVAL]]
;
entry:
  %p1 = alloca [42 x i8]
  %p2 = alloca [42 x i8]
  call void @init_mem(ptr %p1, i64 1024)
  call void @init_mem(ptr %p2, i64 1024)
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %arrayidx1 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %arrayidx1, align 1
  %cmp3 = icmp eq i8 %ld1, %ld2
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ %index, %loop ], [ 67, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_pre_inc_use1_too_small_deref_ptrs(ptr dereferenceable(42) %p1, ptr dereferenceable(42) %p2) #0 {
; MAX1-LABEL: define i64 @same_exit_block_pre_inc_use1_too_small_deref_ptrs(
; MAX1-SAME: ptr dereferenceable(42) [[P1:%.*]], ptr dereferenceable(42) [[P2:%.*]]) #[[ATTR0]] {
; MAX1-NEXT:  [[ENTRY:.*]]:
; MAX1-NEXT:    br label %[[LOOP:.*]]
; MAX1:       [[LOOP]]:
; MAX1-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; MAX1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX1-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; MAX1-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX1-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; MAX1:       [[LOOP_INC]]:
; MAX1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX1-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX1-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; MAX1:       [[LOOP_END]]:
; MAX1-NEXT:    [[RETVAL:%.*]] = phi i64 [ [[INDEX]], %[[LOOP]] ], [ 67, %[[LOOP_INC]] ]
; MAX1-NEXT:    ret i64 [[RETVAL]]
;
; MAX2-LABEL: define i64 @same_exit_block_pre_inc_use1_too_small_deref_ptrs(
; MAX2-SAME: ptr dereferenceable(42) [[P1:%.*]], ptr dereferenceable(42) [[P2:%.*]]) #[[ATTR0]] {
; MAX2-NEXT:  [[ENTRY:.*]]:
; MAX2-NEXT:    [[P22:%.*]] = ptrtoint ptr [[P2]] to i64
; MAX2-NEXT:    [[P11:%.*]] = ptrtoint ptr [[P1]] to i64
; MAX2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 16
; MAX2-NEXT:    [[TMP2:%.*]] = call i64 @llvm.umax.i64(i64 32, i64 [[TMP1]])
; MAX2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP2]]
; MAX2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; MAX2:       [[VECTOR_SCEVCHECK]]:
; MAX2-NEXT:    [[TMP3:%.*]] = add i64 [[P11]], 3
; MAX2-NEXT:    [[TMP4:%.*]] = add nuw i64 [[P11]], 3
; MAX2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP6:%.*]] = shl nuw nsw i64 [[TMP5]], 4
; MAX2-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP4]], [[TMP6]]
; MAX2-NEXT:    [[TMP8:%.*]] = mul i64 [[TMP7]], [[TMP5]]
; MAX2-NEXT:    [[TMP9:%.*]] = shl i64 [[TMP8]], 4
; MAX2-NEXT:    [[TMP10:%.*]] = sub i64 [[TMP3]], [[TMP9]]
; MAX2-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP10]], 0
; MAX2-NEXT:    [[TMP11:%.*]] = add i64 [[P22]], 3
; MAX2-NEXT:    [[TMP12:%.*]] = add nuw i64 [[P22]], 3
; MAX2-NEXT:    [[TMP13:%.*]] = udiv i64 [[TMP12]], [[TMP6]]
; MAX2-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP13]], [[TMP5]]
; MAX2-NEXT:    [[TMP15:%.*]] = shl i64 [[TMP14]], 4
; MAX2-NEXT:    [[TMP16:%.*]] = sub i64 [[TMP11]], [[TMP15]]
; MAX2-NEXT:    [[IDENT_CHECK3:%.*]] = icmp ne i64 [[TMP16]], 0
; MAX2-NEXT:    [[TMP17:%.*]] = or i1 [[IDENT_CHECK]], [[IDENT_CHECK3]]
; MAX2-NEXT:    br i1 [[TMP17]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; MAX2:       [[VECTOR_PH]]:
; MAX2-NEXT:    [[TMP18:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP19:%.*]] = mul i64 [[TMP18]], 16
; MAX2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP19]]
; MAX2-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; MAX2-NEXT:    [[TMP20:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 16
; MAX2-NEXT:    [[TMP22:%.*]] = add i64 3, [[N_VEC]]
; MAX2-NEXT:    [[TMP23:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; MAX2-NEXT:    [[TMP24:%.*]] = mul <vscale x 16 x i64> [[TMP23]], splat (i64 1)
; MAX2-NEXT:    [[INDUCTION:%.*]] = add <vscale x 16 x i64> splat (i64 3), [[TMP24]]
; MAX2-NEXT:    [[TMP25:%.*]] = mul i64 1, [[TMP21]]
; MAX2-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP25]], i64 0
; MAX2-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; MAX2-NEXT:    br label %[[VECTOR_BODY:.*]]
; MAX2:       [[VECTOR_BODY]]:
; MAX2-NEXT:    [[INDEX4:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT6:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 16 x i64> [ [[INDUCTION]], %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX4]]
; MAX2-NEXT:    [[TMP26:%.*]] = add i64 [[OFFSET_IDX]], 0
; MAX2-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP26]]
; MAX2-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i8, ptr [[TMP27]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP28]], align 1
; MAX2-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[TMP26]]
; MAX2-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i8, ptr [[TMP29]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD5:%.*]] = load <vscale x 16 x i8>, ptr [[TMP30]], align 1
; MAX2-NEXT:    [[TMP31:%.*]] = icmp eq <vscale x 16 x i8> [[WIDE_LOAD]], [[WIDE_LOAD5]]
; MAX2-NEXT:    [[INDEX_NEXT6]] = add nuw i64 [[INDEX4]], [[TMP21]]
; MAX2-NEXT:    [[TMP32:%.*]] = xor <vscale x 16 x i1> [[TMP31]], splat (i1 true)
; MAX2-NEXT:    [[TMP33:%.*]] = call i1 @llvm.vector.reduce.or.nxv16i1(<vscale x 16 x i1> [[TMP32]])
; MAX2-NEXT:    [[TMP34:%.*]] = icmp eq i64 [[INDEX_NEXT6]], [[N_VEC]]
; MAX2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 16 x i64> [[VEC_IND]], [[DOTSPLAT]]
; MAX2-NEXT:    [[TMP35:%.*]] = or i1 [[TMP33]], [[TMP34]]
; MAX2-NEXT:    br i1 [[TMP35]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; MAX2:       [[MIDDLE_SPLIT]]:
; MAX2-NEXT:    br i1 [[TMP33]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; MAX2:       [[MIDDLE_BLOCK]]:
; MAX2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; MAX2-NEXT:    br i1 [[CMP_N]], label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; MAX2:       [[VECTOR_EARLY_EXIT]]:
; MAX2-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv16i1(<vscale x 16 x i1> [[TMP32]], i1 true)
; MAX2-NEXT:    [[EARLY_EXIT_VALUE:%.*]] = extractelement <vscale x 16 x i64> [[VEC_IND]], i64 [[FIRST_ACTIVE_LANE]]
; MAX2-NEXT:    br label %[[LOOP_END]]
; MAX2:       [[SCALAR_PH]]:
; MAX2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP22]], %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ], [ 3, %[[VECTOR_SCEVCHECK]] ]
; MAX2-NEXT:    br label %[[LOOP:.*]]
; MAX2:       [[LOOP]]:
; MAX2-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; MAX2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX2-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; MAX2-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX2-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; MAX2:       [[LOOP_INC]]:
; MAX2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX2-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP7:![0-9]+]]
; MAX2:       [[LOOP_END]]:
; MAX2-NEXT:    [[RETVAL:%.*]] = phi i64 [ [[INDEX]], %[[LOOP]] ], [ 67, %[[LOOP_INC]] ], [ 67, %[[MIDDLE_BLOCK]] ], [ [[EARLY_EXIT_VALUE]], %[[VECTOR_EARLY_EXIT]] ]
; MAX2-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %arrayidx1 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %arrayidx1, align 1
  %cmp3 = icmp eq i8 %ld1, %ld2
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ %index, %loop ], [ 67, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_pre_inc_use1_unknown_ptrs(ptr %p1, ptr %p2) #0 {
; MAX1-LABEL: define i64 @same_exit_block_pre_inc_use1_unknown_ptrs(
; MAX1-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]]) #[[ATTR0]] {
; MAX1-NEXT:  [[ENTRY:.*]]:
; MAX1-NEXT:    br label %[[LOOP:.*]]
; MAX1:       [[LOOP]]:
; MAX1-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; MAX1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX1-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; MAX1-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX1-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; MAX1:       [[LOOP_INC]]:
; MAX1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX1-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX1-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; MAX1:       [[LOOP_END]]:
; MAX1-NEXT:    [[RETVAL:%.*]] = phi i64 [ [[INDEX]], %[[LOOP]] ], [ 67, %[[LOOP_INC]] ]
; MAX1-NEXT:    ret i64 [[RETVAL]]
;
; MAX2-LABEL: define i64 @same_exit_block_pre_inc_use1_unknown_ptrs(
; MAX2-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]]) #[[ATTR0]] {
; MAX2-NEXT:  [[ENTRY:.*]]:
; MAX2-NEXT:    [[P22:%.*]] = ptrtoint ptr [[P2]] to i64
; MAX2-NEXT:    [[P11:%.*]] = ptrtoint ptr [[P1]] to i64
; MAX2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 16
; MAX2-NEXT:    [[TMP2:%.*]] = call i64 @llvm.umax.i64(i64 32, i64 [[TMP1]])
; MAX2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP2]]
; MAX2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; MAX2:       [[VECTOR_SCEVCHECK]]:
; MAX2-NEXT:    [[TMP3:%.*]] = add i64 [[P11]], 3
; MAX2-NEXT:    [[TMP4:%.*]] = add nuw i64 [[P11]], 3
; MAX2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP6:%.*]] = shl nuw nsw i64 [[TMP5]], 4
; MAX2-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP4]], [[TMP6]]
; MAX2-NEXT:    [[TMP8:%.*]] = mul i64 [[TMP7]], [[TMP5]]
; MAX2-NEXT:    [[TMP9:%.*]] = shl i64 [[TMP8]], 4
; MAX2-NEXT:    [[TMP10:%.*]] = sub i64 [[TMP3]], [[TMP9]]
; MAX2-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP10]], 0
; MAX2-NEXT:    [[TMP11:%.*]] = add i64 [[P22]], 3
; MAX2-NEXT:    [[TMP12:%.*]] = add nuw i64 [[P22]], 3
; MAX2-NEXT:    [[TMP13:%.*]] = udiv i64 [[TMP12]], [[TMP6]]
; MAX2-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP13]], [[TMP5]]
; MAX2-NEXT:    [[TMP15:%.*]] = shl i64 [[TMP14]], 4
; MAX2-NEXT:    [[TMP16:%.*]] = sub i64 [[TMP11]], [[TMP15]]
; MAX2-NEXT:    [[IDENT_CHECK3:%.*]] = icmp ne i64 [[TMP16]], 0
; MAX2-NEXT:    [[TMP17:%.*]] = or i1 [[IDENT_CHECK]], [[IDENT_CHECK3]]
; MAX2-NEXT:    br i1 [[TMP17]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; MAX2:       [[VECTOR_PH]]:
; MAX2-NEXT:    [[TMP18:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP19:%.*]] = mul i64 [[TMP18]], 16
; MAX2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP19]]
; MAX2-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; MAX2-NEXT:    [[TMP20:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 16
; MAX2-NEXT:    [[TMP22:%.*]] = add i64 3, [[N_VEC]]
; MAX2-NEXT:    [[TMP23:%.*]] = call <vscale x 16 x i64> @llvm.stepvector.nxv16i64()
; MAX2-NEXT:    [[TMP24:%.*]] = mul <vscale x 16 x i64> [[TMP23]], splat (i64 1)
; MAX2-NEXT:    [[INDUCTION:%.*]] = add <vscale x 16 x i64> splat (i64 3), [[TMP24]]
; MAX2-NEXT:    [[TMP25:%.*]] = mul i64 1, [[TMP21]]
; MAX2-NEXT:    [[DOTSPLATINSERT:%.*]] = insertelement <vscale x 16 x i64> poison, i64 [[TMP25]], i64 0
; MAX2-NEXT:    [[DOTSPLAT:%.*]] = shufflevector <vscale x 16 x i64> [[DOTSPLATINSERT]], <vscale x 16 x i64> poison, <vscale x 16 x i32> zeroinitializer
; MAX2-NEXT:    br label %[[VECTOR_BODY:.*]]
; MAX2:       [[VECTOR_BODY]]:
; MAX2-NEXT:    [[INDEX4:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT6:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[VEC_IND:%.*]] = phi <vscale x 16 x i64> [ [[INDUCTION]], %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX4]]
; MAX2-NEXT:    [[TMP26:%.*]] = add i64 [[OFFSET_IDX]], 0
; MAX2-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP26]]
; MAX2-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i8, ptr [[TMP27]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP28]], align 1
; MAX2-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[TMP26]]
; MAX2-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i8, ptr [[TMP29]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD5:%.*]] = load <vscale x 16 x i8>, ptr [[TMP30]], align 1
; MAX2-NEXT:    [[TMP31:%.*]] = icmp eq <vscale x 16 x i8> [[WIDE_LOAD]], [[WIDE_LOAD5]]
; MAX2-NEXT:    [[INDEX_NEXT6]] = add nuw i64 [[INDEX4]], [[TMP21]]
; MAX2-NEXT:    [[TMP32:%.*]] = xor <vscale x 16 x i1> [[TMP31]], splat (i1 true)
; MAX2-NEXT:    [[TMP33:%.*]] = call i1 @llvm.vector.reduce.or.nxv16i1(<vscale x 16 x i1> [[TMP32]])
; MAX2-NEXT:    [[TMP34:%.*]] = icmp eq i64 [[INDEX_NEXT6]], [[N_VEC]]
; MAX2-NEXT:    [[VEC_IND_NEXT]] = add <vscale x 16 x i64> [[VEC_IND]], [[DOTSPLAT]]
; MAX2-NEXT:    [[TMP35:%.*]] = or i1 [[TMP33]], [[TMP34]]
; MAX2-NEXT:    br i1 [[TMP35]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; MAX2:       [[MIDDLE_SPLIT]]:
; MAX2-NEXT:    br i1 [[TMP33]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; MAX2:       [[MIDDLE_BLOCK]]:
; MAX2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; MAX2-NEXT:    br i1 [[CMP_N]], label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; MAX2:       [[VECTOR_EARLY_EXIT]]:
; MAX2-NEXT:    [[FIRST_ACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.nxv16i1(<vscale x 16 x i1> [[TMP32]], i1 true)
; MAX2-NEXT:    [[EARLY_EXIT_VALUE:%.*]] = extractelement <vscale x 16 x i64> [[VEC_IND]], i64 [[FIRST_ACTIVE_LANE]]
; MAX2-NEXT:    br label %[[LOOP_END]]
; MAX2:       [[SCALAR_PH]]:
; MAX2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP22]], %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ], [ 3, %[[VECTOR_SCEVCHECK]] ]
; MAX2-NEXT:    br label %[[LOOP:.*]]
; MAX2:       [[LOOP]]:
; MAX2-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; MAX2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX2-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
; MAX2-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX2-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; MAX2:       [[LOOP_INC]]:
; MAX2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX2-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP9:![0-9]+]]
; MAX2:       [[LOOP_END]]:
; MAX2-NEXT:    [[RETVAL:%.*]] = phi i64 [ [[INDEX]], %[[LOOP]] ], [ 67, %[[LOOP_INC]] ], [ 67, %[[MIDDLE_BLOCK]] ], [ [[EARLY_EXIT_VALUE]], %[[VECTOR_EARLY_EXIT]] ]
; MAX2-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %arrayidx1 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %arrayidx1, align 1
  %cmp3 = icmp eq i8 %ld1, %ld2
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ %index, %loop ], [ 67, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_no_live_outs_one_faulting_ptr_stride2(ptr %p1) #0 {
; CHECK-LABEL: define i64 @same_exit_block_no_live_outs_one_faulting_ptr_stride2(
; CHECK-SAME: ptr [[P1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; CHECK-NEXT:    [[STRIDE2:%.*]] = mul i64 [[INDEX]], 2
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[STRIDE2]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], 3
; CHECK-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; CHECK:       [[LOOP_INC]]:
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; CHECK:       [[LOOP_END]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ]
; CHECK-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %stride2 = mul i64 %index, 2
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %stride2
  %ld1 = load i8, ptr %arrayidx, align 1
  %cmp3 = icmp eq i8 %ld1, 3
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ 1, %loop ], [ 0, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_no_live_outs_one_faulting_ptr_stride_unknown(ptr %p1, i64 %stride) #0 {
; CHECK-LABEL: define i64 @same_exit_block_no_live_outs_one_faulting_ptr_stride_unknown(
; CHECK-SAME: ptr [[P1:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; CHECK-NEXT:    [[MUL:%.*]] = mul i64 [[INDEX]], [[STRIDE]]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[MUL]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], 3
; CHECK-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; CHECK:       [[LOOP_INC]]:
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; CHECK:       [[LOOP_END]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ]
; CHECK-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %mul = mul i64 %index, %stride
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %mul
  %ld1 = load i8, ptr %arrayidx, align 1
  %cmp3 = icmp eq i8 %ld1, 3
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ 1, %loop ], [ 0, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_no_live_outs_one_faulting_ptr_no_vscale_range(ptr %p1, i64 %stride) #1 {
; MAX1-LABEL: define i64 @same_exit_block_no_live_outs_one_faulting_ptr_no_vscale_range(
; MAX1-SAME: ptr [[P1:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR1:[0-9]+]] {
; MAX1-NEXT:  [[ENTRY:.*]]:
; MAX1-NEXT:    [[P11:%.*]] = ptrtoint ptr [[P1]] to i64
; MAX1-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; MAX1:       [[VECTOR_SCEVCHECK]]:
; MAX1-NEXT:    [[TMP0:%.*]] = trunc i64 [[P11]] to i4
; MAX1-NEXT:    [[TMP1:%.*]] = add i4 [[TMP0]], 3
; MAX1-NEXT:    [[TMP2:%.*]] = zext i4 [[TMP1]] to i64
; MAX1-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP2]], 0
; MAX1-NEXT:    br i1 [[IDENT_CHECK]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; MAX1:       [[VECTOR_PH]]:
; MAX1-NEXT:    br label %[[VECTOR_BODY:.*]]
; MAX1:       [[VECTOR_BODY]]:
; MAX1-NEXT:    [[INDEX2:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT3:%.*]], %[[VECTOR_BODY]] ]
; MAX1-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX2]]
; MAX1-NEXT:    [[TMP3:%.*]] = add i64 [[OFFSET_IDX]], 0
; MAX1-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP3]]
; MAX1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i8, ptr [[TMP4]], i32 0
; MAX1-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[TMP5]], align 1
; MAX1-NEXT:    [[TMP6:%.*]] = icmp eq <16 x i8> [[WIDE_LOAD]], splat (i8 3)
; MAX1-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX2]], 16
; MAX1-NEXT:    [[TMP7:%.*]] = xor <16 x i1> [[TMP6]], splat (i1 true)
; MAX1-NEXT:    [[TMP8:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP7]])
; MAX1-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT3]], 64
; MAX1-NEXT:    [[TMP10:%.*]] = or i1 [[TMP8]], [[TMP9]]
; MAX1-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; MAX1:       [[MIDDLE_SPLIT]]:
; MAX1-NEXT:    br i1 [[TMP8]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; MAX1:       [[MIDDLE_BLOCK]]:
; MAX1-NEXT:    br i1 true, label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; MAX1:       [[VECTOR_EARLY_EXIT]]:
; MAX1-NEXT:    br label %[[LOOP_END]]
; MAX1:       [[SCALAR_PH]]:
; MAX1-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 67, %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ], [ 3, %[[VECTOR_SCEVCHECK]] ]
; MAX1-NEXT:    br label %[[LOOP:.*]]
; MAX1:       [[LOOP]]:
; MAX1-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; MAX1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX1-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], 3
; MAX1-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; MAX1:       [[LOOP_INC]]:
; MAX1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX1-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX1-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP5:![0-9]+]]
; MAX1:       [[LOOP_END]]:
; MAX1-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ], [ 0, %[[MIDDLE_BLOCK]] ], [ 1, %[[VECTOR_EARLY_EXIT]] ]
; MAX1-NEXT:    ret i64 [[RETVAL]]
;
; MAX2-LABEL: define i64 @same_exit_block_no_live_outs_one_faulting_ptr_no_vscale_range(
; MAX2-SAME: ptr [[P1:%.*]], i64 [[STRIDE:%.*]]) #[[ATTR1:[0-9]+]] {
; MAX2-NEXT:  [[ENTRY:.*]]:
; MAX2-NEXT:    [[P11:%.*]] = ptrtoint ptr [[P1]] to i64
; MAX2-NEXT:    br i1 false, label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; MAX2:       [[VECTOR_SCEVCHECK]]:
; MAX2-NEXT:    [[TMP0:%.*]] = trunc i64 [[P11]] to i4
; MAX2-NEXT:    [[TMP1:%.*]] = add i4 [[TMP0]], 3
; MAX2-NEXT:    [[TMP2:%.*]] = zext i4 [[TMP1]] to i64
; MAX2-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP2]], 0
; MAX2-NEXT:    br i1 [[IDENT_CHECK]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; MAX2:       [[VECTOR_PH]]:
; MAX2-NEXT:    br label %[[VECTOR_BODY:.*]]
; MAX2:       [[VECTOR_BODY]]:
; MAX2-NEXT:    [[INDEX2:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT3:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX2]]
; MAX2-NEXT:    [[TMP3:%.*]] = add i64 [[OFFSET_IDX]], 0
; MAX2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP3]]
; MAX2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i8, ptr [[TMP4]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[TMP5]], align 1
; MAX2-NEXT:    [[TMP6:%.*]] = icmp eq <16 x i8> [[WIDE_LOAD]], splat (i8 3)
; MAX2-NEXT:    [[INDEX_NEXT3]] = add nuw i64 [[INDEX2]], 16
; MAX2-NEXT:    [[TMP7:%.*]] = xor <16 x i1> [[TMP6]], splat (i1 true)
; MAX2-NEXT:    [[TMP8:%.*]] = call i1 @llvm.vector.reduce.or.v16i1(<16 x i1> [[TMP7]])
; MAX2-NEXT:    [[TMP9:%.*]] = icmp eq i64 [[INDEX_NEXT3]], 64
; MAX2-NEXT:    [[TMP10:%.*]] = or i1 [[TMP8]], [[TMP9]]
; MAX2-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; MAX2:       [[MIDDLE_SPLIT]]:
; MAX2-NEXT:    br i1 [[TMP8]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; MAX2:       [[MIDDLE_BLOCK]]:
; MAX2-NEXT:    br i1 true, label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; MAX2:       [[VECTOR_EARLY_EXIT]]:
; MAX2-NEXT:    br label %[[LOOP_END]]
; MAX2:       [[SCALAR_PH]]:
; MAX2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ 67, %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ], [ 3, %[[VECTOR_SCEVCHECK]] ]
; MAX2-NEXT:    br label %[[LOOP:.*]]
; MAX2:       [[LOOP]]:
; MAX2-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; MAX2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX2-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], 3
; MAX2-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; MAX2:       [[LOOP_INC]]:
; MAX2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX2-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP11:![0-9]+]]
; MAX2:       [[LOOP_END]]:
; MAX2-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ], [ 0, %[[MIDDLE_BLOCK]] ], [ 1, %[[VECTOR_EARLY_EXIT]] ]
; MAX2-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %cmp3 = icmp eq i8 %ld1, 3
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ 1, %loop ], [ 0, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_no_live_outs_one_faulting_ptr_stride_too_low(ptr %p1) #0 {
; CHECK-LABEL: define i64 @same_exit_block_no_live_outs_one_faulting_ptr_stride_too_low(
; CHECK-SAME: ptr [[P1:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; CHECK-NEXT:    [[LD1:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i32 [[LD1]], 3
; CHECK-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; CHECK:       [[LOOP_INC]]:
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; CHECK:       [[LOOP_END]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ]
; CHECK-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i32, ptr %arrayidx, align 4
  %cmp3 = icmp eq i32 %ld1, 3
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ 1, %loop ], [ 0, %loop.inc ]
  ret i64 %retval
}


define i64 @same_exit_block_no_live_outs_two_faulting_ptrs(ptr %p1, ptr %p2) #0 {
; MAX1-LABEL: define i64 @same_exit_block_no_live_outs_two_faulting_ptrs(
; MAX1-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]]) #[[ATTR0]] {
; MAX1-NEXT:  [[ENTRY:.*]]:
; MAX1-NEXT:    br label %[[LOOP:.*]]
; MAX1:       [[LOOP]]:
; MAX1-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; MAX1-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX1-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX1-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; MAX1-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX1-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; MAX1:       [[LOOP_INC]]:
; MAX1-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX1-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX1-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; MAX1:       [[LOOP_END]]:
; MAX1-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ]
; MAX1-NEXT:    ret i64 [[RETVAL]]
;
; MAX2-LABEL: define i64 @same_exit_block_no_live_outs_two_faulting_ptrs(
; MAX2-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]]) #[[ATTR0]] {
; MAX2-NEXT:  [[ENTRY:.*]]:
; MAX2-NEXT:    [[P22:%.*]] = ptrtoint ptr [[P2]] to i64
; MAX2-NEXT:    [[P11:%.*]] = ptrtoint ptr [[P1]] to i64
; MAX2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP1:%.*]] = mul i64 [[TMP0]], 16
; MAX2-NEXT:    [[TMP2:%.*]] = call i64 @llvm.umax.i64(i64 32, i64 [[TMP1]])
; MAX2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP2]]
; MAX2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; MAX2:       [[VECTOR_SCEVCHECK]]:
; MAX2-NEXT:    [[TMP3:%.*]] = add i64 [[P11]], 3
; MAX2-NEXT:    [[TMP4:%.*]] = add nuw i64 [[P11]], 3
; MAX2-NEXT:    [[TMP5:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP6:%.*]] = shl nuw nsw i64 [[TMP5]], 4
; MAX2-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP4]], [[TMP6]]
; MAX2-NEXT:    [[TMP8:%.*]] = mul i64 [[TMP7]], [[TMP5]]
; MAX2-NEXT:    [[TMP9:%.*]] = shl i64 [[TMP8]], 4
; MAX2-NEXT:    [[TMP10:%.*]] = sub i64 [[TMP3]], [[TMP9]]
; MAX2-NEXT:    [[IDENT_CHECK:%.*]] = icmp ne i64 [[TMP10]], 0
; MAX2-NEXT:    [[TMP11:%.*]] = add i64 [[P22]], 3
; MAX2-NEXT:    [[TMP12:%.*]] = add nuw i64 [[P22]], 3
; MAX2-NEXT:    [[TMP13:%.*]] = udiv i64 [[TMP12]], [[TMP6]]
; MAX2-NEXT:    [[TMP14:%.*]] = mul i64 [[TMP13]], [[TMP5]]
; MAX2-NEXT:    [[TMP15:%.*]] = shl i64 [[TMP14]], 4
; MAX2-NEXT:    [[TMP16:%.*]] = sub i64 [[TMP11]], [[TMP15]]
; MAX2-NEXT:    [[IDENT_CHECK3:%.*]] = icmp ne i64 [[TMP16]], 0
; MAX2-NEXT:    [[TMP17:%.*]] = or i1 [[IDENT_CHECK]], [[IDENT_CHECK3]]
; MAX2-NEXT:    br i1 [[TMP17]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; MAX2:       [[VECTOR_PH]]:
; MAX2-NEXT:    [[TMP18:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP19:%.*]] = mul i64 [[TMP18]], 16
; MAX2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP19]]
; MAX2-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; MAX2-NEXT:    [[TMP20:%.*]] = call i64 @llvm.vscale.i64()
; MAX2-NEXT:    [[TMP21:%.*]] = mul i64 [[TMP20]], 16
; MAX2-NEXT:    [[TMP22:%.*]] = add i64 3, [[N_VEC]]
; MAX2-NEXT:    br label %[[VECTOR_BODY:.*]]
; MAX2:       [[VECTOR_BODY]]:
; MAX2-NEXT:    [[INDEX4:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT6:%.*]], %[[VECTOR_BODY]] ]
; MAX2-NEXT:    [[OFFSET_IDX:%.*]] = add i64 3, [[INDEX4]]
; MAX2-NEXT:    [[TMP23:%.*]] = add i64 [[OFFSET_IDX]], 0
; MAX2-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[TMP23]]
; MAX2-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i8, ptr [[TMP24]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[TMP25]], align 1
; MAX2-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[TMP23]]
; MAX2-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i8, ptr [[TMP26]], i32 0
; MAX2-NEXT:    [[WIDE_LOAD5:%.*]] = load <vscale x 16 x i8>, ptr [[TMP27]], align 1
; MAX2-NEXT:    [[TMP28:%.*]] = icmp eq <vscale x 16 x i8> [[WIDE_LOAD]], [[WIDE_LOAD5]]
; MAX2-NEXT:    [[INDEX_NEXT6]] = add nuw i64 [[INDEX4]], [[TMP21]]
; MAX2-NEXT:    [[TMP29:%.*]] = xor <vscale x 16 x i1> [[TMP28]], splat (i1 true)
; MAX2-NEXT:    [[TMP30:%.*]] = call i1 @llvm.vector.reduce.or.nxv16i1(<vscale x 16 x i1> [[TMP29]])
; MAX2-NEXT:    [[TMP31:%.*]] = icmp eq i64 [[INDEX_NEXT6]], [[N_VEC]]
; MAX2-NEXT:    [[TMP32:%.*]] = or i1 [[TMP30]], [[TMP31]]
; MAX2-NEXT:    br i1 [[TMP32]], label %[[MIDDLE_SPLIT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; MAX2:       [[MIDDLE_SPLIT]]:
; MAX2-NEXT:    br i1 [[TMP30]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[MIDDLE_BLOCK:.*]]
; MAX2:       [[MIDDLE_BLOCK]]:
; MAX2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; MAX2-NEXT:    br i1 [[CMP_N]], label %[[LOOP_END:.*]], label %[[SCALAR_PH]]
; MAX2:       [[VECTOR_EARLY_EXIT]]:
; MAX2-NEXT:    br label %[[LOOP_END]]
; MAX2:       [[SCALAR_PH]]:
; MAX2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP22]], %[[MIDDLE_BLOCK]] ], [ 3, %[[ENTRY]] ], [ 3, %[[VECTOR_SCEVCHECK]] ]
; MAX2-NEXT:    br label %[[LOOP:.*]]
; MAX2:       [[LOOP]]:
; MAX2-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ]
; MAX2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; MAX2-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; MAX2-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; MAX2-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], [[LD2]]
; MAX2-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END]]
; MAX2:       [[LOOP_INC]]:
; MAX2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; MAX2-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; MAX2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]], !llvm.loop [[LOOP13:![0-9]+]]
; MAX2:       [[LOOP_END]]:
; MAX2-NEXT:    [[RETVAL:%.*]] = phi i64 [ 1, %[[LOOP]] ], [ 0, %[[LOOP_INC]] ], [ 0, %[[MIDDLE_BLOCK]] ], [ 1, %[[VECTOR_EARLY_EXIT]] ]
; MAX2-NEXT:    ret i64 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %arrayidx2 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %arrayidx2, align 1
  %cmp3 = icmp eq i8 %ld1, %ld2
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i64 [ 1, %loop ], [ 0, %loop.inc ]
  ret i64 %retval
}


define i8 @same_exit_block_no_live_outs_faulting_load_after_early_exit(ptr %p1, ptr %p2) #0 {
; CHECK-LABEL: define i8 @same_exit_block_no_live_outs_faulting_load_after_early_exit(
; CHECK-SAME: ptr [[P1:%.*]], ptr [[P2:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[INDEX_NEXT:%.*]], %[[LOOP_INC:.*]] ], [ 3, %[[ENTRY]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[P1]], i64 [[INDEX]]
; CHECK-NEXT:    [[LD1:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
; CHECK-NEXT:    [[CMP3:%.*]] = icmp eq i8 [[LD1]], 3
; CHECK-NEXT:    br i1 [[CMP3]], label %[[LOOP_INC]], label %[[LOOP_END:.*]]
; CHECK:       [[LOOP_INC]]:
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[P2]], i64 [[INDEX]]
; CHECK-NEXT:    [[LD2:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp ne i64 [[INDEX_NEXT]], 67
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP]], label %[[LOOP_END]]
; CHECK:       [[LOOP_END]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = phi i8 [ 1, %[[LOOP]] ], [ [[LD2]], %[[LOOP_INC]] ]
; CHECK-NEXT:    ret i8 [[RETVAL]]
;
entry:
  br label %loop

loop:
  %index = phi i64 [ %index.next, %loop.inc ], [ 3, %entry ]
  %arrayidx = getelementptr inbounds i8, ptr %p1, i64 %index
  %ld1 = load i8, ptr %arrayidx, align 1
  %cmp3 = icmp eq i8 %ld1, 3
  br i1 %cmp3, label %loop.inc, label %loop.end

loop.inc:
  %arrayidx2 = getelementptr inbounds i8, ptr %p2, i64 %index
  %ld2 = load i8, ptr %arrayidx2, align 1
  %index.next = add i64 %index, 1
  %exitcond = icmp ne i64 %index.next, 67
  br i1 %exitcond, label %loop, label %loop.end

loop.end:
  %retval = phi i8 [ 1, %loop ], [ %ld2, %loop.inc ]
  ret i8 %retval
}


attributes #0 = { "target-features"="+sve" vscale_range(1,16) }
attributes #1 = { "target-features"="+sve" }
;.
; MAX1: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; MAX1: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; MAX1: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; MAX1: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]]}
; MAX1: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; MAX1: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]]}
;.
; MAX2: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; MAX2: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; MAX2: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; MAX2: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]]}
; MAX2: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
; MAX2: [[LOOP5]] = distinct !{[[LOOP5]], [[META1]]}
; MAX2: [[LOOP6]] = distinct !{[[LOOP6]], [[META1]], [[META2]]}
; MAX2: [[LOOP7]] = distinct !{[[LOOP7]], [[META1]]}
; MAX2: [[LOOP8]] = distinct !{[[LOOP8]], [[META1]], [[META2]]}
; MAX2: [[LOOP9]] = distinct !{[[LOOP9]], [[META1]]}
; MAX2: [[LOOP10]] = distinct !{[[LOOP10]], [[META1]], [[META2]]}
; MAX2: [[LOOP11]] = distinct !{[[LOOP11]], [[META1]]}
; MAX2: [[LOOP12]] = distinct !{[[LOOP12]], [[META1]], [[META2]]}
; MAX2: [[LOOP13]] = distinct !{[[LOOP13]], [[META1]]}
;.
