; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mattr=+sve2   -passes=loop-vectorize -vectorize-vector-loops -force-vector-width=1 -S < %s | FileCheck %s -check-prefixes=CHECK,CHECK_SVE2
; RUN: opt -mattr=+sve2p2 -passes=loop-vectorize -vectorize-vector-loops -force-vector-width=1 -S < %s | FileCheck %s -check-prefixes=CHECK,CHECK_SVE2p2
; RUN: opt -mattr=+sve2   -passes=loop-vectorize -vectorize-vector-loops -S < %s | FileCheck %s -check-prefixes=VECTORIZE,VECTORIZE_SVE2
; RUN: opt -mattr=+sve2p2 -passes=loop-vectorize -vectorize-vector-loops -S < %s | FileCheck %s -check-prefixes=VECTORIZE,VECTORIZE_SVE2p2

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable
define dso_local void @loop(ptr noalias nocapture noundef writeonly %dst, ptr nocapture noundef readonly %src1, ptr nocapture noundef readonly %src2, i32 noundef %count) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local void @loop(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[DST:%.*]], ptr noundef readonly captures(none) [[SRC1:%.*]], ptr noundef readonly captures(none) [[SRC2:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[COUNT]], 0
; CHECK-NEXT:    br i1 [[CMP9]], label %[[FOR_BODY_PREHEADER:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[COUNT]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[COUNT]], 8
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[FOR_BODY_PREHEADER15:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[FOR_BODY_PREHEADER15]]:
; CHECK-NEXT:    [[INDVARS_IV_PH:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[N_VEC:%.*]], %[[MIDDLE_BLOCK:.*]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_VEC]] = and i64 [[WIDE_TRIP_COUNT]], 2147483640
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 16
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x float>, ptr [[TMP0]], align 4, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[WIDE_LOAD12:%.*]] = load <4 x float>, ptr [[TMP1]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i8, ptr [[TMP2]], i64 16
; CHECK-NEXT:    [[WIDE_LOAD13:%.*]] = load <4 x float>, ptr [[TMP2]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[WIDE_LOAD14:%.*]] = load <4 x float>, ptr [[TMP3]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP4:%.*]] = fadd <4 x float> [[WIDE_LOAD]], [[WIDE_LOAD13]]
; CHECK-NEXT:    [[TMP5:%.*]] = fadd <4 x float> [[WIDE_LOAD12]], [[WIDE_LOAD14]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i8, ptr [[TMP6]], i64 16
; CHECK-NEXT:    store <4 x float> [[TMP4]], ptr [[TMP6]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    store <4 x float> [[TMP5]], ptr [[TMP7]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N_VEC]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY_PREHEADER15]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ [[INDVARS_IV_PH]], %[[FOR_BODY_PREHEADER15]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP9:%.*]] = load float, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP10:%.*]] = load float, ptr [[ARRAYIDX2]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[TMP9]], [[TMP10]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store float [[ADD]], ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
;
; VECTORIZE_SVE2-LABEL: define dso_local void @loop(
; VECTORIZE_SVE2-SAME: ptr noalias noundef writeonly captures(none) [[DST:%.*]], ptr noundef readonly captures(none) [[SRC1:%.*]], ptr noundef readonly captures(none) [[SRC2:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; VECTORIZE_SVE2-NEXT:  [[ENTRY:.*:]]
; VECTORIZE_SVE2-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[COUNT]], 0
; VECTORIZE_SVE2-NEXT:    br i1 [[CMP9]], label %[[FOR_BODY_PREHEADER:.*]], label %[[FOR_COND_CLEANUP:.*]]
; VECTORIZE_SVE2:       [[FOR_BODY_PREHEADER]]:
; VECTORIZE_SVE2-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[COUNT]] to i64
; VECTORIZE_SVE2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[COUNT]], 8
; VECTORIZE_SVE2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[FOR_BODY_PREHEADER15:.*]], label %[[VECTOR_PH:.*]]
; VECTORIZE_SVE2:       [[FOR_BODY_PREHEADER15]]:
; VECTORIZE_SVE2-NEXT:    [[INDVARS_IV_PH:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[N_VEC:%.*]], %[[MIDDLE_BLOCK:.*]] ]
; VECTORIZE_SVE2-NEXT:    br label %[[FOR_BODY:.*]]
; VECTORIZE_SVE2:       [[VECTOR_PH]]:
; VECTORIZE_SVE2-NEXT:    [[N_VEC]] = and i64 [[WIDE_TRIP_COUNT]], 2147483640
; VECTORIZE_SVE2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VECTORIZE_SVE2:       [[VECTOR_BODY]]:
; VECTORIZE_SVE2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VECTORIZE_SVE2-NEXT:    [[TMP0:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDEX]]
; VECTORIZE_SVE2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 16
; VECTORIZE_SVE2-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x float>, ptr [[TMP0]], align 4, !tbaa [[TBAA6:![0-9]+]]
; VECTORIZE_SVE2-NEXT:    [[WIDE_LOAD12:%.*]] = load <4 x float>, ptr [[TMP1]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDEX]]
; VECTORIZE_SVE2-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i8, ptr [[TMP2]], i64 16
; VECTORIZE_SVE2-NEXT:    [[WIDE_LOAD13:%.*]] = load <4 x float>, ptr [[TMP2]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    [[WIDE_LOAD14:%.*]] = load <4 x float>, ptr [[TMP3]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    [[TMP4:%.*]] = fadd <4 x float> [[WIDE_LOAD]], [[WIDE_LOAD13]]
; VECTORIZE_SVE2-NEXT:    [[TMP5:%.*]] = fadd <4 x float> [[WIDE_LOAD12]], [[WIDE_LOAD14]]
; VECTORIZE_SVE2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDEX]]
; VECTORIZE_SVE2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i8, ptr [[TMP6]], i64 16
; VECTORIZE_SVE2-NEXT:    store <4 x float> [[TMP4]], ptr [[TMP6]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    store <4 x float> [[TMP5]], ptr [[TMP7]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; VECTORIZE_SVE2-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VECTORIZE_SVE2-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; VECTORIZE_SVE2:       [[MIDDLE_BLOCK]]:
; VECTORIZE_SVE2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N_VEC]], [[WIDE_TRIP_COUNT]]
; VECTORIZE_SVE2-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY_PREHEADER15]]
; VECTORIZE_SVE2:       [[FOR_COND_CLEANUP_LOOPEXIT:.*]]:
; VECTORIZE_SVE2-NEXT:    br label %[[FOR_COND_CLEANUP]]
; VECTORIZE_SVE2:       [[FOR_COND_CLEANUP]]:
; VECTORIZE_SVE2-NEXT:    ret void
; VECTORIZE_SVE2:       [[FOR_BODY]]:
; VECTORIZE_SVE2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ [[INDVARS_IV_PH]], %[[FOR_BODY_PREHEADER15]] ]
; VECTORIZE_SVE2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDVARS_IV]]
; VECTORIZE_SVE2-NEXT:    [[TMP9:%.*]] = load float, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDVARS_IV]]
; VECTORIZE_SVE2-NEXT:    [[TMP10:%.*]] = load float, ptr [[ARRAYIDX2]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    [[ADD:%.*]] = fadd float [[TMP9]], [[TMP10]]
; VECTORIZE_SVE2-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDVARS_IV]]
; VECTORIZE_SVE2-NEXT:    store float [[ADD]], ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; VECTORIZE_SVE2-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; VECTORIZE_SVE2-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
;
; VECTORIZE_SVE2p2-LABEL: define dso_local void @loop(
; VECTORIZE_SVE2p2-SAME: ptr noalias noundef writeonly captures(none) [[DST:%.*]], ptr noundef readonly captures(none) [[SRC1:%.*]], ptr noundef readonly captures(none) [[SRC2:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; VECTORIZE_SVE2p2-NEXT:  [[ENTRY:.*:]]
; VECTORIZE_SVE2p2-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[COUNT]], 0
; VECTORIZE_SVE2p2-NEXT:    br i1 [[CMP9]], label %[[FOR_BODY_PREHEADER:.*]], label %[[FOR_COND_CLEANUP:.*]]
; VECTORIZE_SVE2p2:       [[FOR_BODY_PREHEADER]]:
; VECTORIZE_SVE2p2-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[COUNT]] to i64
; VECTORIZE_SVE2p2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[COUNT]], 8
; VECTORIZE_SVE2p2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[FOR_BODY_PREHEADER15:.*]], label %[[VECTOR_PH:.*]]
; VECTORIZE_SVE2p2:       [[FOR_BODY_PREHEADER15]]:
; VECTORIZE_SVE2p2-NEXT:    [[INDVARS_IV_PH:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[N_VEC:%.*]], %[[MIDDLE_BLOCK:.*]] ]
; VECTORIZE_SVE2p2-NEXT:    br label %[[FOR_BODY:.*]]
; VECTORIZE_SVE2p2:       [[VECTOR_PH]]:
; VECTORIZE_SVE2p2-NEXT:    [[N_VEC]] = and i64 [[WIDE_TRIP_COUNT]], 2147483640
; VECTORIZE_SVE2p2-NEXT:    [[TMP0:%.*]] = add nsw i64 [[N_VEC]], -8
; VECTORIZE_SVE2p2-NEXT:    [[TMP1:%.*]] = lshr i64 [[TMP0]], 3
; VECTORIZE_SVE2p2-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 1
; VECTORIZE_SVE2p2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; VECTORIZE_SVE2p2-NEXT:    [[MIN_ITERS_CHECK1:%.*]] = icmp ult i64 [[TMP2]], [[TMP3]]
; VECTORIZE_SVE2p2-NEXT:    br i1 [[MIN_ITERS_CHECK1]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH2:.*]]
; VECTORIZE_SVE2p2:       [[VECTOR_PH2]]:
; VECTORIZE_SVE2p2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], [[TMP3]]
; VECTORIZE_SVE2p2-NEXT:    [[N_VEC3:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP4:%.*]] = shl i64 [[N_VEC3]], 3
; VECTORIZE_SVE2p2-NEXT:    br label %[[VECTOR_BODY4:.*]]
; VECTORIZE_SVE2p2:       [[VECTOR_BODY4]]:
; VECTORIZE_SVE2p2-NEXT:    [[INDEX5:%.*]] = phi i64 [ 0, %[[VECTOR_PH2]] ], [ [[INDEX_NEXT13:%.*]], %[[VECTOR_BODY4]] ]
; VECTORIZE_SVE2p2-NEXT:    [[TMP10:%.*]] = shl i64 [[INDEX5]], 3
; VECTORIZE_SVE2p2-NEXT:    [[TMP12:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[TMP10]]
; VECTORIZE_SVE2p2-NEXT:    [[WIDE_VEC6:%.*]] = load <vscale x 8 x float>, ptr [[TMP12]], align 4, !tbaa [[TBAA6:![0-9]+]]
; VECTORIZE_SVE2p2-NEXT:    [[STRIDED_VEC7:%.*]] = call { <vscale x 4 x float>, <vscale x 4 x float> } @llvm.vector.deinterleave.segments2.nxv8f32(<vscale x 8 x float> [[WIDE_VEC6]])
; VECTORIZE_SVE2p2-NEXT:    [[TMP15:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[STRIDED_VEC7]], 0
; VECTORIZE_SVE2p2-NEXT:    [[TMP16:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[STRIDED_VEC7]], 1
; VECTORIZE_SVE2p2-NEXT:    [[TMP18:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[TMP10]]
; VECTORIZE_SVE2p2-NEXT:    [[WIDE_VEC10:%.*]] = load <vscale x 8 x float>, ptr [[TMP18]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[STRIDED_VEC11:%.*]] = call { <vscale x 4 x float>, <vscale x 4 x float> } @llvm.vector.deinterleave.segments2.nxv8f32(<vscale x 8 x float> [[WIDE_VEC10]])
; VECTORIZE_SVE2p2-NEXT:    [[TMP21:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[STRIDED_VEC11]], 0
; VECTORIZE_SVE2p2-NEXT:    [[TMP22:%.*]] = extractvalue { <vscale x 4 x float>, <vscale x 4 x float> } [[STRIDED_VEC11]], 1
; VECTORIZE_SVE2p2-NEXT:    [[TMP24:%.*]] = fadd <vscale x 4 x float> [[TMP15]], [[TMP21]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP26:%.*]] = fadd <vscale x 4 x float> [[TMP16]], [[TMP22]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP28:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[TMP10]]
; VECTORIZE_SVE2p2-NEXT:    [[INTERLEAVED_VEC12:%.*]] = call <vscale x 8 x float> @llvm.vector.interleave.segments2.nxv8f32(<vscale x 4 x float> [[TMP24]], <vscale x 4 x float> [[TMP26]])
; VECTORIZE_SVE2p2-NEXT:    store <vscale x 8 x float> [[INTERLEAVED_VEC12]], ptr [[TMP28]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[INDEX_NEXT13]] = add nuw i64 [[INDEX5]], [[TMP3]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP29:%.*]] = icmp eq i64 [[INDEX_NEXT13]], [[N_VEC3]]
; VECTORIZE_SVE2p2-NEXT:    br i1 [[TMP29]], label %[[MIDDLE_BLOCK14:.*]], label %[[VECTOR_BODY4]], !llvm.loop [[LOOP10:![0-9]+]]
; VECTORIZE_SVE2p2:       [[MIDDLE_BLOCK14]]:
; VECTORIZE_SVE2p2-NEXT:    [[CMP_N15:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC3]]
; VECTORIZE_SVE2p2-NEXT:    br i1 [[CMP_N15]], label %[[MIDDLE_BLOCK]], label %[[SCALAR_PH]]
; VECTORIZE_SVE2p2:       [[SCALAR_PH]]:
; VECTORIZE_SVE2p2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP4]], %[[MIDDLE_BLOCK14]] ], [ 0, %[[VECTOR_PH]] ]
; VECTORIZE_SVE2p2-NEXT:    br label %[[VECTOR_BODY:.*]]
; VECTORIZE_SVE2p2:       [[VECTOR_BODY]]:
; VECTORIZE_SVE2p2-NEXT:    [[INDEX:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VECTORIZE_SVE2p2-NEXT:    [[TMP30:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDEX]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP31:%.*]] = getelementptr inbounds i8, ptr [[TMP30]], i64 16
; VECTORIZE_SVE2p2-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x float>, ptr [[TMP30]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[WIDE_LOAD12:%.*]] = load <4 x float>, ptr [[TMP31]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP32:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDEX]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i8, ptr [[TMP32]], i64 16
; VECTORIZE_SVE2p2-NEXT:    [[WIDE_LOAD13:%.*]] = load <4 x float>, ptr [[TMP32]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[WIDE_LOAD14:%.*]] = load <4 x float>, ptr [[TMP33]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP34:%.*]] = fadd <4 x float> [[WIDE_LOAD]], [[WIDE_LOAD13]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP35:%.*]] = fadd <4 x float> [[WIDE_LOAD12]], [[WIDE_LOAD14]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP36:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDEX]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i8, ptr [[TMP36]], i64 16
; VECTORIZE_SVE2p2-NEXT:    store <4 x float> [[TMP34]], ptr [[TMP36]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    store <4 x float> [[TMP35]], ptr [[TMP37]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; VECTORIZE_SVE2p2-NEXT:    [[TMP38:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VECTORIZE_SVE2p2-NEXT:    br i1 [[TMP38]], label %[[MIDDLE_BLOCK]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP14:![0-9]+]]
; VECTORIZE_SVE2p2:       [[MIDDLE_BLOCK]]:
; VECTORIZE_SVE2p2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N_VEC]], [[WIDE_TRIP_COUNT]]
; VECTORIZE_SVE2p2-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY_PREHEADER15]]
; VECTORIZE_SVE2p2:       [[FOR_COND_CLEANUP_LOOPEXIT:.*]]:
; VECTORIZE_SVE2p2-NEXT:    br label %[[FOR_COND_CLEANUP]]
; VECTORIZE_SVE2p2:       [[FOR_COND_CLEANUP]]:
; VECTORIZE_SVE2p2-NEXT:    ret void
; VECTORIZE_SVE2p2:       [[FOR_BODY]]:
; VECTORIZE_SVE2p2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ [[INDVARS_IV_PH]], %[[FOR_BODY_PREHEADER15]] ]
; VECTORIZE_SVE2p2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDVARS_IV]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP39:%.*]] = load float, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDVARS_IV]]
; VECTORIZE_SVE2p2-NEXT:    [[TMP40:%.*]] = load float, ptr [[ARRAYIDX2]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[ADD:%.*]] = fadd float [[TMP39]], [[TMP40]]
; VECTORIZE_SVE2p2-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDVARS_IV]]
; VECTORIZE_SVE2p2-NEXT:    store float [[ADD]], ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA6]]
; VECTORIZE_SVE2p2-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; VECTORIZE_SVE2p2-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; VECTORIZE_SVE2p2-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
;
entry:
  %cmp9 = icmp sgt i32 %count, 0
  br i1 %cmp9, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:                               ; preds = %entry
  %wide.trip.count = zext nneg i32 %count to i64
  %min.iters.check = icmp ult i32 %count, 8
  br i1 %min.iters.check, label %for.body.preheader15, label %vector.ph

for.body.preheader15:                             ; preds = %middle.block, %for.body.preheader
  %indvars.iv.ph = phi i64 [ 0, %for.body.preheader ], [ %n.vec, %middle.block ]
  br label %for.body

vector.ph:                                        ; preds = %for.body.preheader
  %n.vec = and i64 %wide.trip.count, 2147483640
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %0 = getelementptr inbounds float, ptr %src1, i64 %index
  %1 = getelementptr inbounds i8, ptr %0, i64 16
  %wide.load = load <4 x float>, ptr %0, align 4, !tbaa !6
  %wide.load12 = load <4 x float>, ptr %1, align 4, !tbaa !6
  %2 = getelementptr inbounds float, ptr %src2, i64 %index
  %3 = getelementptr inbounds i8, ptr %2, i64 16
  %wide.load13 = load <4 x float>, ptr %2, align 4, !tbaa !6
  %wide.load14 = load <4 x float>, ptr %3, align 4, !tbaa !6
  %4 = fadd <4 x float> %wide.load, %wide.load13
  %5 = fadd <4 x float> %wide.load12, %wide.load14
  %6 = getelementptr inbounds float, ptr %dst, i64 %index
  %7 = getelementptr inbounds i8, ptr %6, i64 16
  store <4 x float> %4, ptr %6, align 4, !tbaa !6
  store <4 x float> %5, ptr %7, align 4, !tbaa !6
  %index.next = add nuw i64 %index, 8
  %8 = icmp eq i64 %index.next, %n.vec
  br i1 %8, label %middle.block, label %vector.body, !llvm.loop !10

middle.block:                                     ; preds = %vector.body
  %cmp.n = icmp eq i64 %n.vec, %wide.trip.count
  br i1 %cmp.n, label %for.cond.cleanup, label %for.body.preheader15

for.cond.cleanup:                                 ; preds = %for.body, %middle.block, %entry
  ret void

for.body:                                         ; preds = %for.body.preheader15, %for.body
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.body ], [ %indvars.iv.ph, %for.body.preheader15 ]
  %arrayidx = getelementptr inbounds float, ptr %src1, i64 %indvars.iv
  %9 = load float, ptr %arrayidx, align 4, !tbaa !6
  %arrayidx2 = getelementptr inbounds float, ptr %src2, i64 %indvars.iv
  %10 = load float, ptr %arrayidx2, align 4, !tbaa !6
  %add = fadd float %9, %10
  %arrayidx4 = getelementptr inbounds float, ptr %dst, i64 %indvars.iv
  store float %add, ptr %arrayidx4, align 4, !tbaa !6
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !14
}

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+outline-atomics,+v8a" }

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 1}
!5 = !{!"clang version 20.0.0git"}
!6 = !{!7, !7, i64 0}
!7 = !{!"float", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C/C++ TBAA"}
!10 = distinct !{!10, !11}
!11 = !{!"llvm.loop.mustprogress"}
!12 = !{!"llvm.loop.unroll.runtime.disable"}
!13 = !{!"llvm.loop.isvectorized", i32 1}
!14 = distinct !{!14, !11, !12, !13}
;.
; CHECK_SVE2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK_SVE2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; CHECK_SVE2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; CHECK_SVE2: [[META9]] = !{!"Simple C/C++ TBAA"}
; CHECK_SVE2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]]}
; CHECK_SVE2: [[META11]] = !{!"llvm.loop.mustprogress"}
; CHECK_SVE2: [[LOOP12]] = distinct !{[[LOOP12]], [[META11]], [[META13:![0-9]+]], [[META14:![0-9]+]]}
; CHECK_SVE2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK_SVE2: [[META14]] = !{!"llvm.loop.isvectorized", i32 1}
;.
; CHECK_SVE2p2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK_SVE2p2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; CHECK_SVE2p2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; CHECK_SVE2p2: [[META9]] = !{!"Simple C/C++ TBAA"}
; CHECK_SVE2p2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]]}
; CHECK_SVE2p2: [[META11]] = !{!"llvm.loop.mustprogress"}
; CHECK_SVE2p2: [[LOOP12]] = distinct !{[[LOOP12]], [[META11]], [[META13:![0-9]+]], [[META14:![0-9]+]]}
; CHECK_SVE2p2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK_SVE2p2: [[META14]] = !{!"llvm.loop.isvectorized", i32 1}
;.
; VECTORIZE_SVE2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; VECTORIZE_SVE2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; VECTORIZE_SVE2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; VECTORIZE_SVE2: [[META9]] = !{!"Simple C/C++ TBAA"}
; VECTORIZE_SVE2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]]}
; VECTORIZE_SVE2: [[META11]] = !{!"llvm.loop.mustprogress"}
; VECTORIZE_SVE2: [[LOOP12]] = distinct !{[[LOOP12]], [[META11]], [[META13:![0-9]+]], [[META14:![0-9]+]]}
; VECTORIZE_SVE2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; VECTORIZE_SVE2: [[META14]] = !{!"llvm.loop.isvectorized", i32 1}
;.
; VECTORIZE_SVE2p2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; VECTORIZE_SVE2p2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; VECTORIZE_SVE2p2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; VECTORIZE_SVE2p2: [[META9]] = !{!"Simple C/C++ TBAA"}
; VECTORIZE_SVE2p2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]], [[META12:![0-9]+]], [[META13:![0-9]+]]}
; VECTORIZE_SVE2p2: [[META11]] = !{!"llvm.loop.mustprogress"}
; VECTORIZE_SVE2p2: [[META12]] = !{!"llvm.loop.isvectorized", i32 1}
; VECTORIZE_SVE2p2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; VECTORIZE_SVE2p2: [[LOOP14]] = distinct !{[[LOOP14]], [[META11]], [[META13]], [[META12]]}
; VECTORIZE_SVE2p2: [[LOOP15]] = distinct !{[[LOOP15]], [[META11]], [[META13]], [[META12]]}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK_SVE2: {{.*}}
; CHECK_SVE2p2: {{.*}}
; VECTORIZE: {{.*}}
