; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mattr=+sve2   -passes=loop-vectorize -vectorize-vector-loops -S < %s | FileCheck %s -check-prefixes=VECTORIZE,VECTORIZE_SVE2
; RUN: opt -mattr=+sve2p2 -passes=loop-vectorize -vectorize-vector-loops -S < %s | FileCheck %s -check-prefixes=VECTORIZE,VECTORIZE_SVE2p2

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

; A simple loop with 64-bit vectors.

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable
define dso_local void @loop(ptr noalias nocapture noundef writeonly %dst, ptr nocapture noundef readonly %src1, ptr nocapture noundef readonly %src2, i32 noundef %count) local_unnamed_addr #0 {
; VECTORIZE-LABEL: define dso_local void @loop(
; VECTORIZE-SAME: ptr noalias noundef writeonly captures(none) [[DST:%.*]], ptr noundef readonly captures(none) [[SRC1:%.*]], ptr noundef readonly captures(none) [[SRC2:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; VECTORIZE-NEXT:  [[ENTRY:.*:]]
; VECTORIZE-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[COUNT]], 0
; VECTORIZE-NEXT:    br i1 [[CMP9]], label %[[VECTOR_PH:.*]], label %[[FOR_COND_CLEANUP:.*]]
; VECTORIZE:       [[VECTOR_PH]]:
; VECTORIZE-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[COUNT]] to i64
; VECTORIZE-NEXT:    [[N_VEC:%.*]] = and i64 [[WIDE_TRIP_COUNT]], 2147483644
; VECTORIZE-NEXT:    [[TMP0:%.*]] = add nsw i64 [[N_VEC]], -2
; VECTORIZE-NEXT:    [[TMP1:%.*]] = lshr i64 [[TMP0]], 1
; VECTORIZE-NEXT:    [[TMP2:%.*]] = add nuw i64 [[TMP1]], 1
; VECTORIZE-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; VECTORIZE-NEXT:    [[TMP4:%.*]] = shl nuw i64 [[TMP3]], 2
; VECTORIZE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP2]], [[TMP4]]
; VECTORIZE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH1:.*]]
; VECTORIZE:       [[VECTOR_PH1]]:
; VECTORIZE-NEXT:    [[TMP10:%.*]] = shl nuw i64 [[TMP3]], 1
; VECTORIZE-NEXT:    [[TMP6:%.*]] = shl nuw i64 [[TMP10]], 1
; VECTORIZE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], [[TMP6]]
; VECTORIZE-NEXT:    [[N_VEC2:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; VECTORIZE-NEXT:    [[TMP7:%.*]] = shl i64 [[N_VEC2]], 1
; VECTORIZE-NEXT:    br label %[[VECTOR_BODY3:.*]]
; VECTORIZE:       [[VECTOR_BODY3]]:
; VECTORIZE-NEXT:    [[INDEX4:%.*]] = phi i64 [ 0, %[[VECTOR_PH1]] ], [ [[INDEX_NEXT9:%.*]], %[[VECTOR_BODY3]] ]
; VECTORIZE-NEXT:    [[INDEX:%.*]] = shl i64 [[INDEX4]], 1
; VECTORIZE-NEXT:    [[TMP28:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDEX]]
; VECTORIZE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds <2 x float>, ptr [[TMP28]], i64 [[TMP10]]
; VECTORIZE-NEXT:    [[WIDE_LOAD5:%.*]] = load <vscale x 4 x float>, ptr [[TMP28]], align 4, !tbaa [[TBAA0:![0-9]+]]
; VECTORIZE-NEXT:    [[WIDE_LOAD6:%.*]] = load <vscale x 4 x float>, ptr [[TMP11]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    [[TMP29:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDEX]]
; VECTORIZE-NEXT:    [[TMP12:%.*]] = getelementptr inbounds <2 x float>, ptr [[TMP29]], i64 [[TMP10]]
; VECTORIZE-NEXT:    [[WIDE_LOAD7:%.*]] = load <vscale x 4 x float>, ptr [[TMP29]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    [[WIDE_LOAD8:%.*]] = load <vscale x 4 x float>, ptr [[TMP12]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    [[TMP16:%.*]] = fadd <vscale x 4 x float> [[WIDE_LOAD5]], [[WIDE_LOAD7]]
; VECTORIZE-NEXT:    [[TMP17:%.*]] = fadd <vscale x 4 x float> [[WIDE_LOAD6]], [[WIDE_LOAD8]]
; VECTORIZE-NEXT:    [[TMP18:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDEX]]
; VECTORIZE-NEXT:    [[TMP19:%.*]] = getelementptr inbounds <2 x float>, ptr [[TMP18]], i64 [[TMP10]]
; VECTORIZE-NEXT:    store <vscale x 4 x float> [[TMP16]], ptr [[TMP18]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    store <vscale x 4 x float> [[TMP17]], ptr [[TMP19]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    [[INDEX_NEXT9]] = add nuw i64 [[INDEX4]], [[TMP6]]
; VECTORIZE-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT9]], [[N_VEC2]]
; VECTORIZE-NEXT:    br i1 [[TMP22]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY3]], !llvm.loop [[LOOP4:![0-9]+]]
; VECTORIZE:       [[MIDDLE_BLOCK]]:
; VECTORIZE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC2]]
; VECTORIZE-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP_LOOPEXIT:.*]], label %[[SCALAR_PH]]
; VECTORIZE:       [[SCALAR_PH]]:
; VECTORIZE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP7]], %[[MIDDLE_BLOCK]] ], [ 0, %[[VECTOR_PH]] ]
; VECTORIZE-NEXT:    br label %[[VECTOR_BODY:.*]]
; VECTORIZE:       [[VECTOR_BODY]]:
; VECTORIZE-NEXT:    [[INDEX1:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VECTORIZE-NEXT:    [[TMP23:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDEX1]]
; VECTORIZE-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x float>, ptr [[TMP23]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    [[TMP24:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDEX1]]
; VECTORIZE-NEXT:    [[WIDE_LOAD12:%.*]] = load <2 x float>, ptr [[TMP24]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    [[TMP20:%.*]] = fadd <2 x float> [[WIDE_LOAD]], [[WIDE_LOAD12]]
; VECTORIZE-NEXT:    [[TMP26:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDEX1]]
; VECTORIZE-NEXT:    store <2 x float> [[TMP20]], ptr [[TMP26]], align 4, !tbaa [[TBAA0]]
; VECTORIZE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX1]], 2
; VECTORIZE-NEXT:    [[TMP32:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VECTORIZE-NEXT:    br i1 [[TMP32]], label %[[FOR_COND_CLEANUP_LOOPEXIT]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; VECTORIZE:       [[FOR_COND_CLEANUP_LOOPEXIT]]:
; VECTORIZE-NEXT:    br label %[[FOR_COND_CLEANUP]]
; VECTORIZE:       [[FOR_COND_CLEANUP]]:
; VECTORIZE-NEXT:    ret void
;
entry:
  %cmp9 = icmp sgt i32 %count, 0
  br i1 %cmp9, label %vector.ph, label %for.cond.cleanup

vector.ph:                                        ; preds = %entry
  %wide.trip.count = zext nneg i32 %count to i64
  %n.vec = and i64 %wide.trip.count, 2147483644
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %0 = getelementptr inbounds float, ptr %src1, i64 %index
  %wide.load = load <2 x float>, ptr %0, align 4, !tbaa !6
  %1 = getelementptr inbounds float, ptr %src2, i64 %index
  %wide.load12 = load <2 x float>, ptr %1, align 4, !tbaa !6
  %2 = fadd <2 x float> %wide.load, %wide.load12
  %3 = getelementptr inbounds float, ptr %dst, i64 %index
  store <2 x float> %2, ptr %3, align 4, !tbaa !6
  %index.next = add nuw i64 %index, 2
  %4 = icmp eq i64 %index.next, %n.vec
  br i1 %4, label %for.cond.cleanup, label %vector.body, !llvm.loop !10

for.cond.cleanup:
  ret void
}

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+outline-atomics,+v8a" }

!6 = !{!7, !7, i64 0}
!7 = !{!"float", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C/C++ TBAA"}
!10 = distinct !{!10, !11}
!11 = !{!"llvm.loop.mustprogress"}
;.
; VECTORIZE_SVE2: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; VECTORIZE_SVE2: [[META1]] = !{!"float", [[META2:![0-9]+]], i64 0}
; VECTORIZE_SVE2: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; VECTORIZE_SVE2: [[META3]] = !{!"Simple C/C++ TBAA"}
; VECTORIZE_SVE2: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]], [[META6:![0-9]+]], [[META7:![0-9]+]]}
; VECTORIZE_SVE2: [[META5]] = !{!"llvm.loop.mustprogress"}
; VECTORIZE_SVE2: [[META6]] = !{!"llvm.loop.isvectorized", i32 1}
; VECTORIZE_SVE2: [[META7]] = !{!"llvm.loop.unroll.runtime.disable"}
; VECTORIZE_SVE2: [[LOOP8]] = distinct !{[[LOOP8]], [[META5]], [[META7]], [[META6]]}
;.
; VECTORIZE_SVE2p2: [[TBAA0]] = !{[[META1:![0-9]+]], [[META1]], i64 0}
; VECTORIZE_SVE2p2: [[META1]] = !{!"float", [[META2:![0-9]+]], i64 0}
; VECTORIZE_SVE2p2: [[META2]] = !{!"omnipotent char", [[META3:![0-9]+]], i64 0}
; VECTORIZE_SVE2p2: [[META3]] = !{!"Simple C/C++ TBAA"}
; VECTORIZE_SVE2p2: [[LOOP4]] = distinct !{[[LOOP4]], [[META5:![0-9]+]], [[META6:![0-9]+]], [[META7:![0-9]+]]}
; VECTORIZE_SVE2p2: [[META5]] = !{!"llvm.loop.mustprogress"}
; VECTORIZE_SVE2p2: [[META6]] = !{!"llvm.loop.isvectorized", i32 1}
; VECTORIZE_SVE2p2: [[META7]] = !{!"llvm.loop.unroll.runtime.disable"}
; VECTORIZE_SVE2p2: [[LOOP8]] = distinct !{[[LOOP8]], [[META5]], [[META7]], [[META6]]}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; VECTORIZE_SVE2: {{.*}}
; VECTORIZE_SVE2p2: {{.*}}
