; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -mattr=+sve2   -passes=loop-vectorize -vectorize-vector-loops -force-vector-width=1 -S < %s | FileCheck %s -check-prefixes=CHECK,CHECK_SVE2
; RUN: opt -mattr=+sve2p2 -passes=loop-vectorize -vectorize-vector-loops -force-vector-width=1 -S < %s | FileCheck %s -check-prefixes=CHECK,CHECK_SVE2p2
; RUN: opt -mattr=+sve2   -passes=loop-vectorize -vectorize-vector-loops -S < %s | FileCheck %s -check-prefixes=VECTORIZE,VECTORIZE_SVE2
; RUN: opt -mattr=+sve2p2 -passes=loop-vectorize -vectorize-vector-loops -S < %s | FileCheck %s -check-prefixes=VECTORIZE,VECTORIZE_SVE2p2

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

; Function Attrs: nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable
define dso_local void @loop(ptr noalias nocapture noundef writeonly %dst, ptr nocapture noundef readonly %src1, ptr nocapture noundef readonly %src2, i32 noundef %count) local_unnamed_addr #0 {
; CHECK-LABEL: define dso_local void @loop(
; CHECK-SAME: ptr noalias noundef writeonly captures(none) [[DST:%.*]], ptr noundef readonly captures(none) [[SRC1:%.*]], ptr noundef readonly captures(none) [[SRC2:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[COUNT]], 0
; CHECK-NEXT:    br i1 [[CMP9]], label %[[FOR_BODY_PREHEADER:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_BODY_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[COUNT]] to i64
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[COUNT]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[FOR_BODY_PREHEADER13:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[FOR_BODY_PREHEADER13]]:
; CHECK-NEXT:    [[INDVARS_IV_PH:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[N_VEC:%.*]], %[[MIDDLE_BLOCK:.*]] ]
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_VEC]] = and i64 [[WIDE_TRIP_COUNT]], 2147483644
; CHECK-NEXT:    [[TMP0:%.*]] = add nsw i64 [[N_VEC]], -4
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i64 [[TMP0]], 2
; CHECK-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 1
; CHECK-NEXT:    [[MIN_ITERS_CHECK2:%.*]] = icmp ult i64 [[TMP2]], 2
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK2]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH2:.*]]
; CHECK:       [[VECTOR_PH2]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], 2
; CHECK-NEXT:    [[N_VEC4:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; CHECK-NEXT:    [[TMP3:%.*]] = shl i64 [[N_VEC4]], 2
; CHECK-NEXT:    br label %[[VECTOR_BODY4:.*]]
; CHECK:       [[VECTOR_BODY4]]:
; CHECK-NEXT:    [[INDEX6:%.*]] = phi i64 [ 0, %[[VECTOR_PH2]] ], [ [[INDEX_NEXT7:%.*]], %[[VECTOR_BODY4]] ]
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX6]], 2
; CHECK-NEXT:    [[TMP4:%.*]] = add i64 [[OFFSET_IDX]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP7:%.*]] = load <4 x float>, ptr [[TMP5]], align 4, !tbaa [[TBAA6:![0-9]+]]
; CHECK-NEXT:    [[TMP8:%.*]] = load <4 x float>, ptr [[TMP6]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP9:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP10:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[TMP4]]
; CHECK-NEXT:    [[TMP11:%.*]] = load <4 x float>, ptr [[TMP9]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP12:%.*]] = load <4 x float>, ptr [[TMP10]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP13:%.*]] = fadd <4 x float> [[TMP7]], [[TMP11]]
; CHECK-NEXT:    [[TMP14:%.*]] = fadd <4 x float> [[TMP8]], [[TMP12]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[TMP16:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[TMP4]]
; CHECK-NEXT:    store <4 x float> [[TMP13]], ptr [[TMP15]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    store <4 x float> [[TMP14]], ptr [[TMP16]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INDEX_NEXT7]] = add nuw i64 [[INDEX6]], 2
; CHECK-NEXT:    [[TMP17:%.*]] = icmp eq i64 [[INDEX_NEXT7]], [[N_VEC4]]
; CHECK-NEXT:    br i1 [[TMP17]], label %[[MIDDLE_BLOCK7:.*]], label %[[VECTOR_BODY4]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK7]]:
; CHECK-NEXT:    [[CMP_N8:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC4]]
; CHECK-NEXT:    br i1 [[CMP_N8]], label %[[MIDDLE_BLOCK]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP3]], %[[MIDDLE_BLOCK7]] ], [ 0, %[[VECTOR_PH]] ]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x float>, ptr [[TMP18]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP19:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD12:%.*]] = load <4 x float>, ptr [[TMP19]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[TMP20:%.*]] = fadd <4 x float> [[WIDE_LOAD]], [[WIDE_LOAD12]]
; CHECK-NEXT:    [[TMP21:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x float> [[TMP20]], ptr [[TMP21]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP22]], label %[[MIDDLE_BLOCK]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N_VEC]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY_PREHEADER13]]
; CHECK:       [[FOR_COND_CLEANUP_LOOPEXIT:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ [[INDVARS_IV_PH]], %[[FOR_BODY_PREHEADER13]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP23:%.*]] = load float, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP24:%.*]] = load float, ptr [[ARRAYIDX2]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[ADD:%.*]] = fadd float [[TMP23]], [[TMP24]]
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store float [[ADD]], ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA6]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
;
; VECTORIZE-LABEL: define dso_local void @loop(
; VECTORIZE-SAME: ptr noalias noundef writeonly captures(none) [[DST:%.*]], ptr noundef readonly captures(none) [[SRC1:%.*]], ptr noundef readonly captures(none) [[SRC2:%.*]], i32 noundef [[COUNT:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; VECTORIZE-NEXT:  [[ENTRY:.*:]]
; VECTORIZE-NEXT:    [[CMP9:%.*]] = icmp sgt i32 [[COUNT]], 0
; VECTORIZE-NEXT:    br i1 [[CMP9]], label %[[FOR_BODY_PREHEADER:.*]], label %[[FOR_COND_CLEANUP:.*]]
; VECTORIZE:       [[FOR_BODY_PREHEADER]]:
; VECTORIZE-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext nneg i32 [[COUNT]] to i64
; VECTORIZE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[COUNT]], 4
; VECTORIZE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[FOR_BODY_PREHEADER13:.*]], label %[[VECTOR_PH:.*]]
; VECTORIZE:       [[FOR_BODY_PREHEADER13]]:
; VECTORIZE-NEXT:    [[INDVARS_IV_PH:%.*]] = phi i64 [ 0, %[[FOR_BODY_PREHEADER]] ], [ [[N_VEC:%.*]], %[[MIDDLE_BLOCK:.*]] ]
; VECTORIZE-NEXT:    br label %[[FOR_BODY:.*]]
; VECTORIZE:       [[VECTOR_PH]]:
; VECTORIZE-NEXT:    [[N_VEC]] = and i64 [[WIDE_TRIP_COUNT]], 2147483644
; VECTORIZE-NEXT:    [[TMP0:%.*]] = add nsw i64 [[N_VEC]], -4
; VECTORIZE-NEXT:    [[TMP1:%.*]] = lshr i64 [[TMP0]], 2
; VECTORIZE-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 1
; VECTORIZE-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; VECTORIZE-NEXT:    [[TMP4:%.*]] = shl nuw i64 [[TMP3]], 1
; VECTORIZE-NEXT:    [[MIN_ITERS_CHECK2:%.*]] = icmp ult i64 [[TMP2]], [[TMP4]]
; VECTORIZE-NEXT:    br i1 [[MIN_ITERS_CHECK2]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH2:.*]]
; VECTORIZE:       [[VECTOR_PH2]]:
; VECTORIZE-NEXT:    [[TMP6:%.*]] = shl nuw i64 [[TMP3]], 1
; VECTORIZE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], [[TMP6]]
; VECTORIZE-NEXT:    [[N_VEC4:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; VECTORIZE-NEXT:    [[TMP7:%.*]] = shl i64 [[N_VEC4]], 2
; VECTORIZE-NEXT:    br label %[[VECTOR_BODY4:.*]]
; VECTORIZE:       [[VECTOR_BODY4]]:
; VECTORIZE-NEXT:    [[INDEX6:%.*]] = phi i64 [ 0, %[[VECTOR_PH2]] ], [ [[INDEX_NEXT11:%.*]], %[[VECTOR_BODY4]] ]
; VECTORIZE-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX6]], 2
; VECTORIZE-NEXT:    [[TMP10:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[OFFSET_IDX]]
; VECTORIZE-NEXT:    [[TMP9:%.*]] = getelementptr inbounds <4 x float>, ptr [[TMP10]], i64 [[TMP3]]
; VECTORIZE-NEXT:    [[WIDE_LOAD6:%.*]] = load <vscale x 4 x float>, ptr [[TMP10]], align 4, !tbaa [[TBAA6:![0-9]+]]
; VECTORIZE-NEXT:    [[WIDE_LOAD7:%.*]] = load <vscale x 4 x float>, ptr [[TMP9]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[TMP15:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[OFFSET_IDX]]
; VECTORIZE-NEXT:    [[TMP11:%.*]] = getelementptr inbounds <4 x float>, ptr [[TMP15]], i64 [[TMP3]]
; VECTORIZE-NEXT:    [[WIDE_LOAD8:%.*]] = load <vscale x 4 x float>, ptr [[TMP15]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[WIDE_LOAD9:%.*]] = load <vscale x 4 x float>, ptr [[TMP11]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[TMP16:%.*]] = fadd <vscale x 4 x float> [[WIDE_LOAD6]], [[WIDE_LOAD8]]
; VECTORIZE-NEXT:    [[TMP20:%.*]] = fadd <vscale x 4 x float> [[WIDE_LOAD7]], [[WIDE_LOAD9]]
; VECTORIZE-NEXT:    [[TMP22:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[OFFSET_IDX]]
; VECTORIZE-NEXT:    [[TMP17:%.*]] = getelementptr inbounds <4 x float>, ptr [[TMP22]], i64 [[TMP3]]
; VECTORIZE-NEXT:    store <vscale x 4 x float> [[TMP16]], ptr [[TMP22]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    store <vscale x 4 x float> [[TMP20]], ptr [[TMP17]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[INDEX_NEXT11]] = add nuw i64 [[INDEX6]], [[TMP6]]
; VECTORIZE-NEXT:    [[TMP27:%.*]] = icmp eq i64 [[INDEX_NEXT11]], [[N_VEC4]]
; VECTORIZE-NEXT:    br i1 [[TMP27]], label %[[MIDDLE_BLOCK11:.*]], label %[[VECTOR_BODY4]], !llvm.loop [[LOOP10:![0-9]+]]
; VECTORIZE:       [[MIDDLE_BLOCK11]]:
; VECTORIZE-NEXT:    [[CMP_N12:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC4]]
; VECTORIZE-NEXT:    br i1 [[CMP_N12]], label %[[MIDDLE_BLOCK]], label %[[SCALAR_PH]]
; VECTORIZE:       [[SCALAR_PH]]:
; VECTORIZE-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[TMP7]], %[[MIDDLE_BLOCK11]] ], [ 0, %[[VECTOR_PH]] ]
; VECTORIZE-NEXT:    br label %[[VECTOR_BODY:.*]]
; VECTORIZE:       [[VECTOR_BODY]]:
; VECTORIZE-NEXT:    [[INDEX:%.*]] = phi i64 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; VECTORIZE-NEXT:    [[TMP28:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDEX]]
; VECTORIZE-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x float>, ptr [[TMP28]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[TMP29:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDEX]]
; VECTORIZE-NEXT:    [[WIDE_LOAD12:%.*]] = load <4 x float>, ptr [[TMP29]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[TMP30:%.*]] = fadd <4 x float> [[WIDE_LOAD]], [[WIDE_LOAD12]]
; VECTORIZE-NEXT:    [[TMP31:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDEX]]
; VECTORIZE-NEXT:    store <4 x float> [[TMP30]], ptr [[TMP31]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; VECTORIZE-NEXT:    [[TMP32:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; VECTORIZE-NEXT:    br i1 [[TMP32]], label %[[MIDDLE_BLOCK]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP14:![0-9]+]]
; VECTORIZE:       [[MIDDLE_BLOCK]]:
; VECTORIZE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N_VEC]], [[WIDE_TRIP_COUNT]]
; VECTORIZE-NEXT:    br i1 [[CMP_N]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY_PREHEADER13]]
; VECTORIZE:       [[FOR_COND_CLEANUP_LOOPEXIT:.*]]:
; VECTORIZE-NEXT:    br label %[[FOR_COND_CLEANUP]]
; VECTORIZE:       [[FOR_COND_CLEANUP]]:
; VECTORIZE-NEXT:    ret void
; VECTORIZE:       [[FOR_BODY]]:
; VECTORIZE-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ], [ [[INDVARS_IV_PH]], %[[FOR_BODY_PREHEADER13]] ]
; VECTORIZE-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds float, ptr [[SRC1]], i64 [[INDVARS_IV]]
; VECTORIZE-NEXT:    [[TMP33:%.*]] = load float, ptr [[ARRAYIDX]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds float, ptr [[SRC2]], i64 [[INDVARS_IV]]
; VECTORIZE-NEXT:    [[TMP34:%.*]] = load float, ptr [[ARRAYIDX2]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[ADD:%.*]] = fadd float [[TMP33]], [[TMP34]]
; VECTORIZE-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds float, ptr [[DST]], i64 [[INDVARS_IV]]
; VECTORIZE-NEXT:    store float [[ADD]], ptr [[ARRAYIDX4]], align 4, !tbaa [[TBAA6]]
; VECTORIZE-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; VECTORIZE-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], [[WIDE_TRIP_COUNT]]
; VECTORIZE-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP_LOOPEXIT]], label %[[FOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
;
entry:
  %cmp9 = icmp sgt i32 %count, 0
  br i1 %cmp9, label %for.body.preheader, label %for.cond.cleanup

for.body.preheader:                               ; preds = %entry
  %wide.trip.count = zext nneg i32 %count to i64
  %min.iters.check = icmp ult i32 %count, 4
  br i1 %min.iters.check, label %for.body.preheader13, label %vector.ph

for.body.preheader13:                             ; preds = %middle.block, %for.body.preheader
  %indvars.iv.ph = phi i64 [ 0, %for.body.preheader ], [ %n.vec, %middle.block ]
  br label %for.body

vector.ph:                                        ; preds = %for.body.preheader
  %n.vec = and i64 %wide.trip.count, 2147483644
  br label %vector.body

vector.body:                                      ; preds = %vector.body, %vector.ph
  %index = phi i64 [ 0, %vector.ph ], [ %index.next, %vector.body ]
  %0 = getelementptr inbounds float, ptr %src1, i64 %index
  %wide.load = load <4 x float>, ptr %0, align 4, !tbaa !6
  %1 = getelementptr inbounds float, ptr %src2, i64 %index
  %wide.load12 = load <4 x float>, ptr %1, align 4, !tbaa !6
  %2 = fadd <4 x float> %wide.load, %wide.load12
  %3 = getelementptr inbounds float, ptr %dst, i64 %index
  store <4 x float> %2, ptr %3, align 4, !tbaa !6
  %index.next = add nuw i64 %index, 4
  %4 = icmp eq i64 %index.next, %n.vec
  br i1 %4, label %middle.block, label %vector.body, !llvm.loop !10

middle.block:                                     ; preds = %vector.body
  %cmp.n = icmp eq i64 %n.vec, %wide.trip.count
  br i1 %cmp.n, label %for.cond.cleanup, label %for.body.preheader13

for.cond.cleanup:                                 ; preds = %for.body, %middle.block, %entry
  ret void

for.body:                                         ; preds = %for.body.preheader13, %for.body
  %indvars.iv = phi i64 [ %indvars.iv.next, %for.body ], [ %indvars.iv.ph, %for.body.preheader13 ]
  %arrayidx = getelementptr inbounds float, ptr %src1, i64 %indvars.iv
  %5 = load float, ptr %arrayidx, align 4, !tbaa !6
  %arrayidx2 = getelementptr inbounds float, ptr %src2, i64 %indvars.iv
  %6 = load float, ptr %arrayidx2, align 4, !tbaa !6
  %add = fadd float %5, %6
  %arrayidx4 = getelementptr inbounds float, ptr %dst, i64 %indvars.iv
  store float %add, ptr %arrayidx4, align 4, !tbaa !6
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !14
}

attributes #0 = { nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable "frame-pointer"="non-leaf" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+outline-atomics,+v8a" }

!llvm.module.flags = !{!0, !1, !2, !3, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 1}
!5 = !{!"clang version 20.0.0git"}
!6 = !{!7, !7, i64 0}
!7 = !{!"float", !8, i64 0}
!8 = !{!"omnipotent char", !9, i64 0}
!9 = !{!"Simple C/C++ TBAA"}
!10 = distinct !{!10, !11}
!11 = !{!"llvm.loop.mustprogress"}
!12 = !{!"llvm.loop.unroll.runtime.disable"}
!13 = !{!"llvm.loop.isvectorized", i32 1}
!14 = distinct !{!14, !11, !12, !13}
;.
; CHECK_SVE2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK_SVE2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; CHECK_SVE2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; CHECK_SVE2: [[META9]] = !{!"Simple C/C++ TBAA"}
; CHECK_SVE2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]], [[META12:![0-9]+]], [[META13:![0-9]+]]}
; CHECK_SVE2: [[META11]] = !{!"llvm.loop.mustprogress"}
; CHECK_SVE2: [[META12]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK_SVE2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK_SVE2: [[LOOP14]] = distinct !{[[LOOP14]], [[META11]], [[META12]]}
; CHECK_SVE2: [[LOOP15]] = distinct !{[[LOOP15]], [[META11]], [[META13]], [[META12]]}
;.
; CHECK_SVE2p2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; CHECK_SVE2p2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; CHECK_SVE2p2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; CHECK_SVE2p2: [[META9]] = !{!"Simple C/C++ TBAA"}
; CHECK_SVE2p2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]], [[META12:![0-9]+]], [[META13:![0-9]+]]}
; CHECK_SVE2p2: [[META11]] = !{!"llvm.loop.mustprogress"}
; CHECK_SVE2p2: [[META12]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK_SVE2p2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK_SVE2p2: [[LOOP14]] = distinct !{[[LOOP14]], [[META11]], [[META12]]}
; CHECK_SVE2p2: [[LOOP15]] = distinct !{[[LOOP15]], [[META11]], [[META13]], [[META12]]}
;.
; VECTORIZE_SVE2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; VECTORIZE_SVE2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; VECTORIZE_SVE2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; VECTORIZE_SVE2: [[META9]] = !{!"Simple C/C++ TBAA"}
; VECTORIZE_SVE2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]], [[META12:![0-9]+]], [[META13:![0-9]+]]}
; VECTORIZE_SVE2: [[META11]] = !{!"llvm.loop.mustprogress"}
; VECTORIZE_SVE2: [[META12]] = !{!"llvm.loop.isvectorized", i32 1}
; VECTORIZE_SVE2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; VECTORIZE_SVE2: [[LOOP14]] = distinct !{[[LOOP14]], [[META11]], [[META13]], [[META12]]}
; VECTORIZE_SVE2: [[LOOP15]] = distinct !{[[LOOP15]], [[META11]], [[META13]], [[META12]]}
;.
; VECTORIZE_SVE2p2: [[TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
; VECTORIZE_SVE2p2: [[META7]] = !{!"float", [[META8:![0-9]+]], i64 0}
; VECTORIZE_SVE2p2: [[META8]] = !{!"omnipotent char", [[META9:![0-9]+]], i64 0}
; VECTORIZE_SVE2p2: [[META9]] = !{!"Simple C/C++ TBAA"}
; VECTORIZE_SVE2p2: [[LOOP10]] = distinct !{[[LOOP10]], [[META11:![0-9]+]], [[META12:![0-9]+]], [[META13:![0-9]+]]}
; VECTORIZE_SVE2p2: [[META11]] = !{!"llvm.loop.mustprogress"}
; VECTORIZE_SVE2p2: [[META12]] = !{!"llvm.loop.isvectorized", i32 1}
; VECTORIZE_SVE2p2: [[META13]] = !{!"llvm.loop.unroll.runtime.disable"}
; VECTORIZE_SVE2p2: [[LOOP14]] = distinct !{[[LOOP14]], [[META11]], [[META13]], [[META12]]}
; VECTORIZE_SVE2p2: [[LOOP15]] = distinct !{[[LOOP15]], [[META11]], [[META13]], [[META12]]}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK_SVE2: {{.*}}
; CHECK_SVE2p2: {{.*}}
; VECTORIZE_SVE2: {{.*}}
; VECTORIZE_SVE2p2: {{.*}}
