; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instsimplify -S | FileCheck %s

; Verify that llvm.fadd / llvm.fsub / etc. participate in the same
; simplifications as their instruction counterparts.

; llvm.fadd(x, 0.0) => x  (with nnan/nsz)
define float @fadd_x_zero(float %x) {
; CHECK-LABEL: @fadd_x_zero(
; CHECK-NEXT:    ret float [[X:%.*]]
;
  %r = call nsz nnan float @llvm.fadd.f32(float %x, float 0.0)
  ret float %r
}

; llvm.fadd(0.0, x) => x  (with nnan/nsz)
define float @fadd_zero_x(float %x) {
; CHECK-LABEL: @fadd_zero_x(
; CHECK-NEXT:    ret float [[X:%.*]]
;
  %r = call nsz nnan float @llvm.fadd.f32(float 0.0, float %x)
  ret float %r
}

; llvm.fsub(x, 0.0) => x  (with nnan/nsz)
define float @fsub_x_zero(float %x) {
; CHECK-LABEL: @fsub_x_zero(
; CHECK-NEXT:    ret float [[X:%.*]]
;
  %r = call nsz nnan float @llvm.fsub.f32(float %x, float 0.0)
  ret float %r
}

; llvm.fmul(x, 1.0) => x  (with nnan/nsz)
define float @fmul_x_one(float %x) {
; CHECK-LABEL: @fmul_x_one(
; CHECK-NEXT:    ret float [[X:%.*]]
;
  %r = call nsz nnan float @llvm.fmul.f32(float %x, float 1.0)
  ret float %r
}

; llvm.fdiv(x, 1.0) => x  (with nnan/nsz)
define float @fdiv_x_one(float %x) {
; CHECK-LABEL: @fdiv_x_one(
; CHECK-NEXT:    ret float [[X:%.*]]
;
  %r = call nsz nnan float @llvm.fdiv.f32(float %x, float 1.0)
  ret float %r
}

; llvm.fcmp with "true" predicate always returns true
define i1 @fcmp_true(float %x, float %y) {
; CHECK-LABEL: @fcmp_true(
; CHECK-NEXT:    ret i1 true
;
  %r = call i1 @llvm.fcmp.f32(float %x, float %y, metadata !"true")
  ret i1 %r
}

; llvm.fcmp with "false" predicate always returns false
define i1 @fcmp_false(float %x, float %y) {
; CHECK-LABEL: @fcmp_false(
; CHECK-NEXT:    ret i1 false
;
  %r = call i1 @llvm.fcmp.f32(float %x, float %y, metadata !"false")
  ret i1 %r
}

; Constant folding: llvm.fadd(1.0, 2.0) => 3.0
define float @fadd_const() {
; CHECK-LABEL: @fadd_const(
; CHECK-NEXT:    ret float 3.000000e+00
;
  %r = call float @llvm.fadd.f32(float 1.0, float 2.0)
  ret float %r
}

; Constant folding: llvm.fsub(5.0, 2.0) => 3.0
define float @fsub_const() {
; CHECK-LABEL: @fsub_const(
; CHECK-NEXT:    ret float 3.000000e+00
;
  %r = call float @llvm.fsub.f32(float 5.0, float 2.0)
  ret float %r
}

; Constant folding: llvm.fmul(2.0, 3.0) => 6.0
define float @fmul_const() {
; CHECK-LABEL: @fmul_const(
; CHECK-NEXT:    ret float 6.000000e+00
;
  %r = call float @llvm.fmul.f32(float 2.0, float 3.0)
  ret float %r
}

; Constant folding: llvm.fdiv(6.0, 2.0) => 3.0
define float @fdiv_const() {
; CHECK-LABEL: @fdiv_const(
; CHECK-NEXT:    ret float 3.000000e+00
;
  %r = call float @llvm.fdiv.f32(float 6.0, float 2.0)
  ret float %r
}

declare float @llvm.fadd.f32(float, float)
declare float @llvm.fsub.f32(float, float)
declare float @llvm.fmul.f32(float, float)
declare float @llvm.fdiv.f32(float, float)
declare float @llvm.frem.f32(float, float)
declare i1 @llvm.fcmp.f32(float, float, metadata)
