; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instsimplify -S | FileCheck %s

; FAILS! Because of poison.
define i32 @selectSelectAndICmpFirstSelectParam(i32 %6, i32 %44, i1 %cond) {
; CHECK-LABEL: @selectSelectAndICmpFirstSelectParam(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP4]], [[TMP3]]
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[COND:%.*]], i32 [[TMP0]], i32 [[TMP1]]
; CHECK-NEXT:    [[DOT0_I8:%.*]] = select i1 [[OR_COND_I]], i32 4, i32 [[SPEC_SELECT_I]]
; CHECK-NEXT:    ret i32 [[DOT0_I8]]
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %or.cond.i = and i1 %47, %46 ; Check if both values are 4.
  %spec.select.i = select i1 %cond, i32 %6, i32 %44
  %.0.i8 = select i1 %or.cond.i, i32 4, i32 %spec.select.i
  ret i32 %.0.i8
}


define i32 @selectSelectAndICmp(i32 %6, i32 %44) {
; CHECK-LABEL: @selectSelectAndICmp(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    [[TMP6:%.*]] = or i1 [[TMP3]], [[TMP5]]
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[TMP6]], i32 [[TMP0]], i32 [[TMP1]]
; CHECK-NEXT:    ret i32 [[SPEC_SELECT_I]]
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %or.cond.i = and i1 %47, %46 ; Check if both values are 4.
  %48 = xor i1 %47, true
  %49 = or i1 %46, %48
  %spec.select.i = select i1 %49, i32 %6, i32 %44
  %.0.i8 = select i1 %or.cond.i, i32 4, i32 %spec.select.i
  ret i32 %.0.i8
}

define i32 @selectSelectAndICmpRemovedNonConst(i32 %6, i32 %44, i32 %val) {
; CHECK-LABEL: @selectSelectAndICmpRemovedNonConst(
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], [[VAL:%.*]]
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    [[DOT0_I8:%.*]] = select i1 [[TMP5]], i32 [[TMP0]], i32 [[TMP1:%.*]]
; CHECK-NEXT:    ret i32 [[DOT0_I8]]
;
  %46 = icmp eq i32 %44, %val
  %47 = icmp eq i32 %6, %val
  %or.cond.i = and i1 %47, %46 ; Check if both values are 4.
  %48 = xor i1 %47, true
  %spec.select.i = select i1 %48, i32 %6, i32 %44
  %.0.i8 = select i1 %or.cond.i, i32 %val, i32 %spec.select.i
  ret i32 %.0.i8
}

define i32 @selectSelectAndICmpRemoved(i32 %6, i32 %44) {
; CHECK-LABEL: @selectSelectAndICmpRemoved(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = xor i1 [[TMP3]], true
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[TMP4]], i32 [[TMP0]], i32 [[TMP1:%.*]]
; CHECK-NEXT:    ret i32 [[SPEC_SELECT_I]]
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %or.cond.i = and i1 %47, %46 ; Check if both values are 4.
  %48 = xor i1 %47, true
  %spec.select.i = select i1 %48, i32 %6, i32 %44
  %.0.i8 = select i1 %or.cond.i, i32 4, i32 %spec.select.i
  ret i32 %.0.i8
}

define i32 @selectSelectAndICmpAnd(i32 %6, i32 %44) {
; CHECK-LABEL: @selectSelectAndICmpAnd(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    [[TMP6:%.*]] = and i1 [[TMP3]], [[TMP5]]
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[TMP6]], i32 [[TMP0]], i32 [[TMP1]]
; CHECK-NEXT:    ret i32 [[SPEC_SELECT_I]]
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %or.cond.i = and i1 %47, %46 ; Check if both values are 4.
  %48 = xor i1 %47, true
  %49 = and i1 %46, %48
  %spec.select.i = select i1 %49, i32 %6, i32 %44
  %.0.i8 = select i1 %or.cond.i, i32 4, i32 %spec.select.i
  ret i32 %.0.i8
}


define i32 @selectSelectAndICmpAnd2(i32 %6, i32 %44) {
; CHECK-LABEL: @selectSelectAndICmpAnd2(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = or i1 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[TMP5]], i32 [[TMP0]], i32 [[TMP1]]
; CHECK-NEXT:    ret i32 [[SPEC_SELECT_I]]
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %or.cond.i = and i1 %47, %46 ; Check if both values are 4.
  %48 = and i1 %47, true
  %49 = or i1 %46, %48
  %spec.select.i = select i1 %49, i32 %6, i32 %44
  %.0.i8 = select i1 %or.cond.i, i32 4, i32 %spec.select.i
  ret i32 %.0.i8
}

define i32 @selectSelectAndICmpUsed(i32 %6, i32 %44) {
; CHECK-LABEL: @selectSelectAndICmpUsed(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP4]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = xor i1 [[TMP4]], true
; CHECK-NEXT:    [[TMP6:%.*]] = or i1 [[TMP3]], [[TMP5]]
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[TMP6]], i32 [[TMP0]], i32 [[TMP1]]
; CHECK-NEXT:    call void @use32(i1 [[OR_COND_I]])
; CHECK-NEXT:    ret i32 [[SPEC_SELECT_I]]
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %or.cond.i = and i1 %47, %46 ; Check if both values are 4.
  %48 = xor i1 %47, true
  %49 = or i1 %46, %48
  %spec.select.i = select i1 %49, i32 %6, i32 %44
  %.0.i8 = select i1 %or.cond.i, i32 4, i32 %spec.select.i
  call void @use32(i1 %or.cond.i)
  ret i32 %.0.i8
}

define i32 @selectSelectAndICmpDisjointOr(i32 %0, i32 %1) {
; CHECK-LABEL: @selectSelectAndICmpDisjointOr(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[OR_COND_I:%.*]] = and i1 [[TMP4]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = or disjoint i1 [[TMP3]], [[TMP4]]
; CHECK-NEXT:    [[SPEC_SELECT_I:%.*]] = select i1 [[TMP5]], i32 [[TMP0]], i32 [[TMP1]]
; CHECK-NEXT:    [[DOT0_I8:%.*]] = select i1 [[OR_COND_I]], i32 4, i32 [[SPEC_SELECT_I]]
; CHECK-NEXT:    ret i32 [[DOT0_I8]]
;
  %3 = icmp eq i32 %1, 4
  %4 = icmp eq i32 %0, 4
  %or.cond.i = and i1 %4, %3
  %5 = and i1 %4, true
  %6 = or disjoint i1 %3, %5
  %spec.select.i = select i1 %6, i32 %0, i32 %1
  %.0.i8 = select i1 %or.cond.i, i32 4, i32 %spec.select.i
  ret i32 %.0.i8
}

define i32 @negSelectSelectICmpICmp(i32 %6, i32 %44) {
; CHECK-LABEL: @negSelectSelectICmpICmp(
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0:%.*]], 4
; CHECK-NEXT:    [[DOT_I:%.*]] = select i1 [[TMP4]], i32 [[TMP1]], i32 [[TMP0]]
; CHECK-NEXT:    [[DOT0_I8:%.*]] = select i1 [[TMP3]], i32 [[TMP0]], i32 [[DOT_I]]
; CHECK-NEXT:    ret i32 [[DOT0_I8]]
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %..i = select i1 %47, i32 %44, i32 %6
  %.0.i8 = select i1 %46, i32 %6, i32 %..i
  ret i32 %.0.i8
}

define void @negRealExampleBefore(ptr %0, i32 %6, i32 %44) {
; CHECK-LABEL: @negRealExampleBefore(
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP2:%.*]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i32 [[TMP1:%.*]], 4
; CHECK-NEXT:    [[DOT_I:%.*]] = select i1 [[TMP5]], i32 [[TMP2]], i32 [[TMP1]]
; CHECK-NEXT:    [[DOT0_I8:%.*]] = select i1 [[TMP4]], i32 [[TMP1]], i32 [[DOT_I]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw i8, ptr [[TMP0:%.*]], i64 12
; CHECK-NEXT:    store i32 [[DOT0_I8]], ptr [[TMP6]], align 4
; CHECK-NEXT:    ret void
;
  %46 = icmp eq i32 %44, 4
  %47 = icmp eq i32 %6, 4
  %..i = select i1 %47, i32 %44, i32 %6
  %.0.i8 = select i1 %46, i32 %6, i32 %..i
  %50 = getelementptr inbounds nuw i8, ptr %0, i64 12
  store i32 %.0.i8, ptr %50
  ret void
}

declare void @use32(i1)
