; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=aarch64 -passes=load-store-vectorizer -S %s | FileCheck %s

; Cycle fallback.
define i32 @load_cycle(ptr noundef dereferenceable(8) align 4 %x) {
; CHECK-LABEL: define i32 @load_cycle(
; CHECK-SAME: ptr noundef align 4 dereferenceable(8) [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[GEP_X_1:%.*]] = getelementptr inbounds [2 x i32], ptr [[X]], i32 0, i32 1
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr i8, ptr [[GEP_X_1]], i64 -4
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i32>, ptr [[BASE]], align 4
; CHECK-NEXT:    [[LOAD_X_21:%.*]] = extractelement <2 x i32> [[VEC]], i32 0
; CHECK-NEXT:    [[LOAD_X_12:%.*]] = extractelement <2 x i32> [[VEC]], i32 1
; CHECK-NEXT:    [[LOAD_X_1_FR:%.*]] = freeze i32 [[LOAD_X_12]]
; CHECK-NEXT:    [[LOAD_X_2_FR:%.*]] = freeze i32 [[LOAD_X_21]]
; CHECK-NEXT:    [[RET:%.*]] = add i32 [[LOAD_X_2_FR]], [[LOAD_X_1_FR]]
; CHECK-NEXT:    ret i32 [[RET]]
;
entry:
  %gep.x.1 = getelementptr inbounds [2 x i32], ptr %x, i32 0, i32 1
  %load.x.1 = load i32, ptr %gep.x.1, align 4
  %load.x.1.fr = freeze i32 %load.x.1
  %rem = urem i32 %load.x.1.fr, 1
  %gep.x.2 = getelementptr inbounds [2 x i32], ptr %x, i32 %rem, i32 0
  %load.x.2 = load i32, ptr %gep.x.2, align 4
  %load.x.2.fr = freeze i32 %load.x.2
  %ret = add i32 %load.x.2.fr, %load.x.1.fr
  ret i32 %ret
}

; Returned pointer fallback.
define i16 @load_cycle_returned_call(
; CHECK-LABEL: define i16 @load_cycle_returned_call(
; CHECK-SAME: ptr noundef align 2 dereferenceable(4) [[BASE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i16, ptr [[BASE]], i64 1
; CHECK-NEXT:    [[VEC_BASE:%.*]] = getelementptr i8, ptr [[P1]], i64 -2
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i16>, ptr [[VEC_BASE]], align 2
; CHECK-NEXT:    [[B1:%.*]] = extractelement <2 x i16> [[VEC]], i32 0
; CHECK-NEXT:    [[B_FR:%.*]] = freeze i16 [[B1]]
; CHECK-NEXT:    ret i16 [[B_FR]]
;
  ptr noundef dereferenceable(4) align 2 %base) {
entry:
  %p1 = getelementptr i16, ptr %base, i64 1
  %a = load i16, ptr %p1, align 1
  %a.fr = freeze i16 %a
  %p0 = call ptr @func_25(ptr null, ptr %base, i16 %a.fr)
  %b = load i16, ptr %p0, align 1
  %b.fr = freeze i16 %b
  ret i16 %b.fr
}

; No partial reorder.
define i16 @load_cycle_no_partial_reorder(
; CHECK-LABEL: define i16 @load_cycle_no_partial_reorder(
; CHECK-SAME: ptr noundef align 2 dereferenceable(4) [[BASE:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[P1:%.*]] = getelementptr i16, ptr [[BASE]], i64 1
; CHECK-NEXT:    [[VEC_BASE:%.*]] = getelementptr i8, ptr [[P1]], i64 -2
; CHECK-NEXT:    [[VEC:%.*]] = load <2 x i16>, ptr [[VEC_BASE]], align 2
; CHECK-NEXT:    [[B1:%.*]] = extractelement <2 x i16> [[VEC]], i32 0
; CHECK-NEXT:    [[A2:%.*]] = extractelement <2 x i16> [[VEC]], i32 1
; CHECK-NEXT:    [[A_FR:%.*]] = freeze i16 [[A2]]
; CHECK-NEXT:    [[P0_BASE:%.*]] = call ptr @func_25(ptr null, ptr [[BASE]], i16 [[A_FR]])
; CHECK-NEXT:    [[P0:%.*]] = getelementptr i16, ptr [[P0_BASE]], i64 0
; CHECK-NEXT:    [[B_FR:%.*]] = freeze i16 [[B1]]
; CHECK-NEXT:    [[KEEP:%.*]] = ptrtoint ptr [[P0]] to i16
; CHECK-NEXT:    [[RET:%.*]] = add i16 [[B_FR]], [[KEEP]]
; CHECK-NEXT:    ret i16 [[RET]]
;
  ptr noundef dereferenceable(4) align 2 %base) {
entry:
  %p1 = getelementptr i16, ptr %base, i64 1
  %a = load i16, ptr %p1, align 1
  %a.fr = freeze i16 %a
  %p0.base = call ptr @func_25(ptr null, ptr %base, i16 %a.fr)
  %p0 = getelementptr i16, ptr %p0.base, i64 0
  %b = load i16, ptr %p0, align 1
  %b.fr = freeze i16 %b
  %keep = ptrtoint ptr %p0 to i16
  %ret = add i16 %b.fr, %keep
  ret i16 %ret
}

; Function Attrs: nounwind willreturn memory(none)
declare ptr @func_25(ptr noundef, ptr noundef returned, i16 noundef) #0

attributes #0 = { nounwind willreturn memory(none) }
