; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-apple-darwin8 -mcpu=yonah | FileCheck %s

define void @test(<1 x i64> %c64, <1 x i64> %mask1, ptr %P) {
; CHECK-LABEL: test:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    pushl %edi
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    .cfi_offset %edi, -8
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %edi
; CHECK-NEXT:    movq {{[0-9]+}}(%esp), %mm0
; CHECK-NEXT:    movq {{[0-9]+}}(%esp), %mm1
; CHECK-NEXT:    maskmovq %mm0, %mm1
; CHECK-NEXT:    popl %edi
; CHECK-NEXT:    retl
entry:
	tail call void @llvm.x86.mmx.maskmovq( <1 x i64> %mask1, <1 x i64> %c64, ptr %P )
	ret void
}

declare void @llvm.x86.mmx.maskmovq(<1 x i64>, <1 x i64>, ptr)
