; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mtriple=i686-- -mattr=+sse2 | FileCheck %s

define void @f(float %wt) {
; CHECK-LABEL: f:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl $44
; CHECK-NEXT:    .cfi_adjust_cfa_offset 4
; CHECK-NEXT:    calll g@PLT
; CHECK-NEXT:    addl $4, %esp
; CHECK-NEXT:    .cfi_adjust_cfa_offset -4
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    retl
entry:
	%0 = fcmp ogt float %wt, 0.000000e+00		; <i1> [#uses=1]
	%1 = tail call i32 @g(i32 44)		; <i32> [#uses=3]
	%2 = inttoptr i32 %1 to ptr		; <ptr> [#uses=2]
	br i1 %0, label %bb, label %bb1

bb:		; preds = %entry
	ret void

bb1:		; preds = %entry
	ret void
}

declare i32 @g(i32)
