; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=x86_64-apple-darwin < %s | FileCheck %s

define i32 @add_shl_add_constant_1_i32(i32 %x, i32 %y) nounwind {
; CHECK-LABEL: add_shl_add_constant_1_i32:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    ## kill: def $esi killed $esi def $rsi
; CHECK-NEXT:    ## kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    leal (%rsi,%rdi,8), %eax
; CHECK-NEXT:    addl $984, %eax ## imm = 0x3D8
; CHECK-NEXT:    retq
  %add.0 = add i32 %x, 123
  %shl = shl i32 %add.0, 3
  %add.1 = add i32 %shl, %y
  ret i32 %add.1
}

define i32 @add_shl_add_constant_2_i32(i32 %x, i32 %y) nounwind {
; CHECK-LABEL: add_shl_add_constant_2_i32:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    ## kill: def $esi killed $esi def $rsi
; CHECK-NEXT:    ## kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    leal (%rsi,%rdi,8), %eax
; CHECK-NEXT:    addl $984, %eax ## imm = 0x3D8
; CHECK-NEXT:    retq
  %add.0 = add i32 %x, 123
  %shl = shl i32 %add.0, 3
  %add.1 = add i32 %y, %shl
  ret i32 %add.1
}

define <4 x i32> @add_shl_add_constant_1_v4i32(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-LABEL: add_shl_add_constant_1_v4i32:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    pslld $3, %xmm0
; CHECK-NEXT:    paddd %xmm1, %xmm0
; CHECK-NEXT:    paddd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %add.0 = add <4 x i32> %x, <i32 123, i32 123, i32 123, i32 123>
  %shl = shl <4 x i32> %add.0, <i32 3, i32 3, i32 3, i32 3>
  %add.1 = add <4 x i32> %shl, %y
  ret <4 x i32> %add.1
}

define <4 x i32> @add_shl_add_constant_2_v4i32(<4 x i32> %x, <4 x i32> %y) nounwind {
; CHECK-LABEL: add_shl_add_constant_2_v4i32:
; CHECK:       ## %bb.0:
; CHECK-NEXT:    pslld $3, %xmm0
; CHECK-NEXT:    paddd %xmm1, %xmm0
; CHECK-NEXT:    paddd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %add.0 = add <4 x i32> %x, <i32 123, i32 123, i32 123, i32 123>
  %shl = shl <4 x i32> %add.0, <i32 3, i32 3, i32 3, i32 3>
  %add.1 = add <4 x i32> %y, %shl
  ret <4 x i32> %add.1
}
