; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

define i32 @and_zext_sgt_zero_sign_bit_clear(i32 %x) {
; CHECK-LABEL: and_zext_sgt_zero_sign_bit_clear:
; CHECK:       # %bb.0:
; CHECK-NEXT:    andl $2147483647, %edi # imm = 0x7FFFFFFF
; CHECK-NEXT:    movl $7, %ecx
; CHECK-NEXT:    movl $42, %eax
; CHECK-NEXT:    cmovgl %ecx, %eax
; CHECK-NEXT:    retq
  %and = and i32 %x, 2147483647
  %z = zext i32 %and to i64
  %cmp = icmp sgt i64 %z, 0
  %sel = select i1 %cmp, i32 7, i32 42
  ret i32 %sel
}

define i32 @and_zext_slt_zero_sign_bit_set(i32 %x) {
; CHECK-LABEL: and_zext_slt_zero_sign_bit_set:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    andl $-2147483648, %edi # imm = 0x80000000
; CHECK-NEXT:    testq %rdi, %rdi
; CHECK-NEXT:    movl $7, %ecx
; CHECK-NEXT:    movl $42, %eax
; CHECK-NEXT:    cmovsl %ecx, %eax
; CHECK-NEXT:    retq
  %and = and i32 %x, 2147483648
  %z = zext i32 %and to i64
  %cmp = icmp slt i64 %z, 0
  %sel = select i1 %cmp, i32 7, i32 42
  ret i32 %sel
}
