; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

; range: 0..2^61
; mask: 2^61 - 8
define i64 @arg_range_top3(i64 range(i64 0, 2305843009213693952) %n) {
; CHECK-LABEL: arg_range_top3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $2305843009213693944, %rax # imm = 0x1FFFFFFFFFFFFFF8
; CHECK-NEXT:    andq %rdi, %rax
; CHECK-NEXT:    retq
  %r = and i64 %n, 2305843009213693944
  ret i64 %r
}

; range: 0..256
; mask: 0xF8 = 248
define i64 @arg_range_byte(i64 range(i64 0, 256) %n) {
; CHECK-LABEL: arg_range_byte:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    andl $248, %eax
; CHECK-NEXT:    retq
  %r = and i64 %n, 248
  ret i64 %r
}

define i64 @arg_range_nonzero_lo(i64 range(i64 1, 2305843009213693952) %n) {
; CHECK-LABEL: arg_range_nonzero_lo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $2305843009213693944, %rax # imm = 0x1FFFFFFFFFFFFFF8
; CHECK-NEXT:    andq %rdi, %rax
; CHECK-NEXT:    retq
  %r = and i64 %n, 2305843009213693944
  ret i64 %r
}

define i64 @arg_range_byte_nonzero_lo(i64 range(i64 1, 256) %n) {
; CHECK-LABEL: arg_range_byte_nonzero_lo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    andl $248, %eax
; CHECK-NEXT:    retq
  %r = and i64 %n, 248
  ret i64 %r
}

define i32 @arg_range_i32_byte(i32 range(i32 0, 256) %n) {
; CHECK-LABEL: arg_range_i32_byte:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    andl $248, %eax
; CHECK-NEXT:    retq
  %r = and i32 %n, 248
  ret i32 %r
}

define i64 @arg_range_top1(i64 range(i64 0, 9223372036854775808) %n) {
; CHECK-LABEL: arg_range_top1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    shrq $63, %rax
; CHECK-NEXT:    retq
  %r = lshr i64 %n, 63
  ret i64 %r
}

define i64 @arg_range_two_args(i64 range(i64 0, 256) %a, i64 range(i64 0, 65536) %b) {
; CHECK-LABEL: arg_range_two_args:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rsi, %rax
; CHECK-NEXT:    andl $248, %edi
; CHECK-NEXT:    andl $65528, %eax # imm = 0xFFF8
; CHECK-NEXT:    orq %rdi, %rax
; CHECK-NEXT:    retq
  %ra = and i64 %a, 248
  %rb = and i64 %b, 65528
  %r = or i64 %ra, %rb
  ret i64 %r
}

define i32 @arg_range_zeroext(i8 zeroext range(i8 0, 16) %n) {
; CHECK-LABEL: arg_range_zeroext:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    andl $14, %eax
; CHECK-NEXT:    retq
  %z = zext i8 %n to i32
  %r = and i32 %z, 14
  ret i32 %r
}

; Negative tests

define i64 @neg_no_range(i64 %n) {
; CHECK-LABEL: neg_no_range:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $2305843009213693944, %rax # imm = 0x1FFFFFFFFFFFFFF8
; CHECK-NEXT:    andq %rdi, %rax
; CHECK-NEXT:    retq
  %r = and i64 %n, 2305843009213693944
  ret i64 %r
}

define i64 @neg_wrapped_range(i64 range(i64 -100, 100) %n) {
; CHECK-LABEL: neg_wrapped_range:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $2305843009213693944, %rax # imm = 0x1FFFFFFFFFFFFFF8
; CHECK-NEXT:    andq %rdi, %rax
; CHECK-NEXT:    retq
  %r = and i64 %n, 2305843009213693944
  ret i64 %r
}

define i32 @neg_near_full_range(i32 range(i32 0, -1) %n) {
; CHECK-LABEL: neg_near_full_range:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    andl $248, %eax
; CHECK-NEXT:    retq
  %r = and i32 %n, 248
  ret i32 %r
}
