; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=FAST_ISEL_GREEDY_RA %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=GREEDY_RA %s

; RUN: not llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=fast < %s 2> %t1
; RUN: FileCheck --check-prefix=EXHAUSTED %s < %t1
; RUN: not llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=fast < %s 2> %t2
; RUN: FileCheck --check-prefix=EXHAUSTED %s < %t2

; EXHAUSTED: inline assembly requires more registers than available

; Exhaust all 14 usable x86 GPRs: 6 inputs consume rdi/rsi/rdx/rcx/r8/r9, and
; the asm clobbers rax/rbx/rbp/r10-r15. The early-clobber output (=&rm) has
; no register left, so the greedy RA must fold it to a stack slot at O2. At O0,
; InlineAsmPrepare routes directly to the memory path.
define i64 @test_rm_output_pressure(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f) {
; FAST_ISEL_GREEDY_RA-LABEL: test_rm_output_pressure:
; FAST_ISEL_GREEDY_RA:       # %bb.0: # %entry
; FAST_ISEL_GREEDY_RA-NEXT:    pushq %rbp
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_ISEL_GREEDY_RA-NEXT:    pushq %r15
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 24
; FAST_ISEL_GREEDY_RA-NEXT:    pushq %r14
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 32
; FAST_ISEL_GREEDY_RA-NEXT:    pushq %r13
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 40
; FAST_ISEL_GREEDY_RA-NEXT:    pushq %r12
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 48
; FAST_ISEL_GREEDY_RA-NEXT:    pushq %rbx
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 56
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_offset %rbx, -56
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_offset %r12, -48
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_offset %r13, -40
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_offset %r14, -32
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_offset %r15, -24
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_offset %rbp, -16
; FAST_ISEL_GREEDY_RA-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; FAST_ISEL_GREEDY_RA-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; FAST_ISEL_GREEDY_RA-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; FAST_ISEL_GREEDY_RA-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; FAST_ISEL_GREEDY_RA-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; FAST_ISEL_GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; FAST_ISEL_GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; FAST_ISEL_GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; FAST_ISEL_GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; FAST_ISEL_GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; FAST_ISEL_GREEDY_RA-NEXT:    #APP # 8-byte Folded Spill
; FAST_ISEL_GREEDY_RA-NEXT:    # -{{[0-9]+}}(%rsp) %rdi %rsi %rdx %rcx %r8 %r9
; FAST_ISEL_GREEDY_RA-NEXT:    #NO_APP
; FAST_ISEL_GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; FAST_ISEL_GREEDY_RA-NEXT:    movq %rax, -{{[0-9]+}}(%rsp)
; FAST_ISEL_GREEDY_RA-NEXT:    movq -{{[0-9]+}}(%rsp), %rax
; FAST_ISEL_GREEDY_RA-NEXT:    popq %rbx
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 48
; FAST_ISEL_GREEDY_RA-NEXT:    popq %r12
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 40
; FAST_ISEL_GREEDY_RA-NEXT:    popq %r13
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 32
; FAST_ISEL_GREEDY_RA-NEXT:    popq %r14
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 24
; FAST_ISEL_GREEDY_RA-NEXT:    popq %r15
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_ISEL_GREEDY_RA-NEXT:    popq %rbp
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 8
; FAST_ISEL_GREEDY_RA-NEXT:    retq
;
; GREEDY_RA-LABEL: test_rm_output_pressure:
; GREEDY_RA:       # %bb.0: # %entry
; GREEDY_RA-NEXT:    pushq %rbp
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; GREEDY_RA-NEXT:    pushq %r15
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 24
; GREEDY_RA-NEXT:    pushq %r14
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 32
; GREEDY_RA-NEXT:    pushq %r13
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 40
; GREEDY_RA-NEXT:    pushq %r12
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 48
; GREEDY_RA-NEXT:    pushq %rbx
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 56
; GREEDY_RA-NEXT:    .cfi_offset %rbx, -56
; GREEDY_RA-NEXT:    .cfi_offset %r12, -48
; GREEDY_RA-NEXT:    .cfi_offset %r13, -40
; GREEDY_RA-NEXT:    .cfi_offset %r14, -32
; GREEDY_RA-NEXT:    .cfi_offset %r15, -24
; GREEDY_RA-NEXT:    .cfi_offset %rbp, -16
; GREEDY_RA-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; GREEDY_RA-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; GREEDY_RA-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; GREEDY_RA-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; GREEDY_RA-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; GREEDY_RA-NEXT:    #APP # 8-byte Folded Spill
; GREEDY_RA-NEXT:    # -{{[0-9]+}}(%rsp) %rdi %rsi %rdx %rcx %r8 %r9
; GREEDY_RA-NEXT:    #NO_APP
; GREEDY_RA-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; GREEDY_RA-NEXT:    popq %rbx
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 48
; GREEDY_RA-NEXT:    popq %r12
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 40
; GREEDY_RA-NEXT:    popq %r13
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 32
; GREEDY_RA-NEXT:    popq %r14
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 24
; GREEDY_RA-NEXT:    popq %r15
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; GREEDY_RA-NEXT:    popq %rbp
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 8
; GREEDY_RA-NEXT:    retq
entry:
  %out = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  %0 = call i64 asm sideeffect "# $0 $1 $2 $3 $4 $5 $6",
      "=&rm,r,r,r,r,r,r,~{rax},~{rbx},~{rbp},~{r10},~{r11},~{r12},~{r13},~{r14},~{r15}"
      (i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f)
  br label %asm.merge

asm.pref.mem:
  call void asm sideeffect "# $0 $1 $2 $3 $4 $5 $6",
      "=*&rm,r,r,r,r,r,r,~{rax},~{rbx},~{rbp},~{r10},~{r11},~{r12},~{r13},~{r14},~{r15}"
      (ptr elementtype(i64) %out, i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f)
  %1 = load i64, ptr %out, align 8
  br label %asm.merge

asm.merge:
  %2 = phi i64 [ %0, %asm.pref.reg ], [ %1, %asm.pref.mem ]
  ret i64 %2
}
