; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --filter "^\t#" --version 4
; RUN: llc -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

; The non-fast register allocators should use registers when there isn't
; register pressure.

define dso_local i32 @test1(ptr noundef readonly captures(none) %foo) local_unnamed_addr {
; CHECK-LABEL: test1:
; CHECK:    #APP
; CHECK:    # rm input: no pressure
; CHECK:    # %eax, %ecx, %edx, %esi, %r8d
; CHECK:    #NO_APP
entry:
  %0 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %2 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %3 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %4 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# rm input: no pressure\0A\09# $0, $1, $2, $3, $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %0, i32 %1, i32 %2, i32 %3, i32 %4)
  %5 = load i32, ptr %foo, align 4
  ret i32 %5
}

define dso_local i32 @test2(ptr noundef readonly captures(none) %foo) local_unnamed_addr {
; CHECK-LABEL: test2:
; CHECK:    #APP
; CHECK:    # %rax, %rcx, %rdx, %rsi, %rdi, %rbx, %rbp, %r8, %r9, %r10, %r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm input: pressure
; CHECK:    # %esi %edi %r8d %r9d %eax
; CHECK:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %1 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %2 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %3 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %4 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %5 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# rm input: pressure\0A\09# $0 $1 $2 $3 $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %1, i32 %2, i32 %3, i32 %4, i32 %5)
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %6 = load i32, ptr %foo, align 4
  ret i32 %6
}

define dso_local i32 @test3(ptr noundef writeonly captures(none) initializes((0, 20)) %foo) local_unnamed_addr {
; CHECK-LABEL: test3:
; CHECK:    #APP
; CHECK:    # rm output: no pressure
; CHECK:    # %eax, %ecx, %edx, %esi, %r8d
; CHECK:    #NO_APP
entry:
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %0 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm output: no pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i32, i32, i32, i32, i32 } %0, 0
  %asmresult1 = extractvalue { i32, i32, i32, i32, i32 } %0, 1
  %asmresult2 = extractvalue { i32, i32, i32, i32, i32 } %0, 2
  %asmresult3 = extractvalue { i32, i32, i32, i32, i32 } %0, 3
  %asmresult4 = extractvalue { i32, i32, i32, i32, i32 } %0, 4
  store i32 %asmresult, ptr %foo, align 4
  store i32 %asmresult1, ptr %b, align 4
  store i32 %asmresult2, ptr %c, align 4
  store i32 %asmresult3, ptr %d, align 4
  store i32 %asmresult4, ptr %e, align 4
  ret i32 %asmresult
}

define dso_local i32 @test4(ptr noundef writeonly captures(none) initializes((0, 20)) %foo) local_unnamed_addr {
; CHECK-LABEL: test4:
; CHECK:    #APP
; CHECK:    # %rax, %rcx, %rdx, %rsi, %rdi, %rbx, %rbp, %r8, %r9, %r10, %r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm output: pressure
; CHECK:    # %esi, %edi, %r8d, %r9d, %eax
; CHECK:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %1 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm output: pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,~{dirflag},~{fpsr},~{flags}"()
  %asmresult15 = extractvalue { i32, i32, i32, i32, i32 } %1, 0
  %asmresult16 = extractvalue { i32, i32, i32, i32, i32 } %1, 1
  %asmresult17 = extractvalue { i32, i32, i32, i32, i32 } %1, 2
  %asmresult18 = extractvalue { i32, i32, i32, i32, i32 } %1, 3
  %asmresult19 = extractvalue { i32, i32, i32, i32, i32 } %1, 4
  store i32 %asmresult15, ptr %foo, align 4
  store i32 %asmresult16, ptr %b, align 4
  store i32 %asmresult17, ptr %c, align 4
  store i32 %asmresult18, ptr %d, align 4
  store i32 %asmresult19, ptr %e, align 4
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %2 = load i32, ptr %foo, align 4
  ret i32 %2
}

define dso_local i32 @test5(ptr noundef captures(none) %foo) local_unnamed_addr {
; CHECK-LABEL: test5:
; CHECK:    #APP
; CHECK:    # rm tied output: no pressure
; CHECK:    # %eax, %ecx, %edx, %esi, %r8d
; CHECK:    #NO_APP
entry:
  %0 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %2 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %3 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %4 = load i32, ptr %e, align 4
  %5 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm tied output: no pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(i32 %0, i32 %1, i32 %2, i32 %3, i32 %4)
  %asmresult = extractvalue { i32, i32, i32, i32, i32 } %5, 0
  %asmresult1 = extractvalue { i32, i32, i32, i32, i32 } %5, 1
  %asmresult2 = extractvalue { i32, i32, i32, i32, i32 } %5, 2
  %asmresult3 = extractvalue { i32, i32, i32, i32, i32 } %5, 3
  %asmresult4 = extractvalue { i32, i32, i32, i32, i32 } %5, 4
  store i32 %asmresult, ptr %foo, align 4
  store i32 %asmresult1, ptr %b, align 4
  store i32 %asmresult2, ptr %c, align 4
  store i32 %asmresult3, ptr %d, align 4
  store i32 %asmresult4, ptr %e, align 4
  ret i32 %asmresult
}

define dso_local i32 @test6(ptr noundef captures(none) %foo) local_unnamed_addr {
; CHECK-LABEL: test6:
; CHECK:    #APP
; CHECK:    # %rax, %rcx, %rdx, %rsi, %rdi, %rbx, %rbp, %r8, %r9, %r10, %r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm tied output: pressure
; CHECK:    # %esi, %edi, %r8d, %r9d, %eax
; CHECK:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %1 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %2 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %3 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %4 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %5 = load i32, ptr %e, align 4
  %6 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm tied output: pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(i32 %1, i32 %2, i32 %3, i32 %4, i32 %5)
  %asmresult15 = extractvalue { i32, i32, i32, i32, i32 } %6, 0
  %asmresult16 = extractvalue { i32, i32, i32, i32, i32 } %6, 1
  %asmresult17 = extractvalue { i32, i32, i32, i32, i32 } %6, 2
  %asmresult18 = extractvalue { i32, i32, i32, i32, i32 } %6, 3
  %asmresult19 = extractvalue { i32, i32, i32, i32, i32 } %6, 4
  store i32 %asmresult15, ptr %foo, align 4
  store i32 %asmresult16, ptr %b, align 4
  store i32 %asmresult17, ptr %c, align 4
  store i32 %asmresult18, ptr %d, align 4
  store i32 %asmresult19, ptr %e, align 4
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %7 = load i32, ptr %foo, align 4
  ret i32 %7
}

define dso_local i32 @test7(ptr noundef captures(none) initializes((0, 4)) %foo) local_unnamed_addr {
; CHECK-LABEL: test7:
; CHECK:    #APP
; CHECK:    # rm output, r input: no pressure
; CHECK:    # %eax, %eax
; CHECK:    #NO_APP
entry:
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %0 = load i32, ptr %b, align 4
  %1 = tail call i32 asm sideeffect "# rm output, r input: no pressure\0A\09# $0, $1", "=rm,r,~{dirflag},~{fpsr},~{flags}"(i32 %0)
  store i32 %1, ptr %foo, align 4
  ret i32 %1
}

define dso_local i32 @test8(ptr noundef captures(none) initializes((0, 4)) %foo) local_unnamed_addr {
; CHECK-LABEL: test8:
; CHECK:    #APP
; CHECK:    # %rax, %rcx, %rdx, %rsi, %rdi, %rbx, %rbp, %r8, %r9, %r10, %r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm output, r input: pressure
; CHECK:    # %esi, %esi
; CHECK:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b, align 4
  %2 = tail call i32 asm sideeffect "# rm output, r input: pressure\0A\09# $0, $1", "=rm,r,~{dirflag},~{fpsr},~{flags}"(i32 %1)
  store i32 %2, ptr %foo, align 4
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %3 = load i32, ptr %foo, align 4
  ret i32 %3
}

define dso_local i32 @test9(ptr noundef %foo) local_unnamed_addr {
; CHECK-LABEL: test9:
; CHECK:    #APP
; CHECK:    # m output, rm input: no pressure
; CHECK:    # (%rdi), %eax
; CHECK:    #NO_APP
entry:
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %0 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# m output, rm input: no pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %0)
  %1 = load i32, ptr %foo, align 4
  ret i32 %1
}

define dso_local i32 @test10(ptr noundef %foo) local_unnamed_addr {
; CHECK-LABEL: test10:
; CHECK:    #APP
; CHECK:    # %rax, %rcx, %rdx, %rsi, %rdi, %rbx, %rbp, %r8, %r9, %r10, %r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # m output, rm input: pressure
; CHECK:    # (%rbp), %esi
; CHECK:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# m output, rm input: pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %1)
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %2 = load i32, ptr %foo, align 4
  ret i32 %2
}

define dso_local i32 @test11(ptr noundef %foo) local_unnamed_addr {
; CHECK-LABEL: test11:
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: no pressure
; CHECK:    # (%rdi), 4(%rdi), 8(%rdi), 12(%rdi), 16(%rdi), %eax, %ecx
; CHECK:    #NO_APP
entry:
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %0 = load i32, ptr %foo, align 4
  %1 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %0, i32 %1)
  %2 = load i32, ptr %foo, align 4
  ret i32 %2
}

define dso_local i32 @test12(ptr noundef %foo) local_unnamed_addr {
; CHECK-LABEL: test12:
; CHECK:    #APP
; CHECK:    # %rax, %rcx, %rdx, %rsi, %rdi, %rbx, %rbp, %r8, %r9, %r10, %r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: pressure
; CHECK:    # (%rbp), 4(%rbp), 8(%rbp), 12(%rbp), 16(%rbp), %esi, %edi
; CHECK:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %1 = load i32, ptr %foo, align 4
  %2 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %1, i32 %2)
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %3 = load i32, ptr %foo, align 4
  ret i32 %3
}

define dso_local i32 @test13(ptr noundef %foo) local_unnamed_addr {
; CHECK-LABEL: test13:
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: no pressure
; CHECK:    # %eax, %esi, %r8d, %r9d, %r10d, %ecx, %edx
; CHECK:    #NO_APP
entry:
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %0 = load i32, ptr %foo, align 4
  %1 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*&rm,=*&rm,=*&rm,=*&rm,=*&rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %0, i32 %1)
  %2 = load i32, ptr %foo, align 4
  ret i32 %2
}

define dso_local i32 @test14(ptr noundef %foo) local_unnamed_addr {
; CHECK-LABEL: test14:
; CHECK:    #APP
; CHECK:    # %rax, %rcx, %rdx, %rsi, %rdi, %rbx, %rbp, %r8, %r9, %r10, %r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: pressure
; CHECK:    # (%rbp), 4(%rbp), 8(%rbp), 12(%rbp), 16(%rbp), %esi, %edi
; CHECK:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0, $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %1 = load i32, ptr %foo, align 4
  %2 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %1, i32 %2)
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %3 = load i32, ptr %foo, align 4
  ret i32 %3
}

declare void @g(i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef)
