; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --filter "^\t#" --version 4
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -O0 < %s | FileCheck %s

%struct.foo = type { i32, i32, i32, i32, i32 }

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test1(ptr noundef %foo) {
; CHECK-LABEL: test1:
; CHECK:    #APP
; CHECK:    # rm input: no pressure
; CHECK:    # -{{[0-9]+}}(%rsp), -{{[0-9]+}}(%rsp), -{{[0-9]+}}(%rsp), -{{[0-9]+}}(%rsp), -{{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %0, i32 0, i32 0
  %1 = load i32, ptr %a, align 4
  %2 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 1
  %3 = load i32, ptr %b, align 4
  %4 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %4, i32 0, i32 2
  %5 = load i32, ptr %c, align 4
  %6 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %6, i32 0, i32 3
  %7 = load i32, ptr %d, align 4
  %8 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %8, i32 0, i32 4
  %9 = load i32, ptr %e, align 4
  call void asm sideeffect "# rm input: no pressure\0A\09# $0, $1, $2, $3, $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %1, i32 %3, i32 %5, i32 %7, i32 %9)
  %10 = load ptr, ptr %foo.addr, align 8
  %a1 = getelementptr inbounds nuw %struct.foo, ptr %10, i32 0, i32 0
  %11 = load i32, ptr %a1, align 4
  ret i32 %11
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test2(ptr noundef %foo) {
; CHECK-LABEL: test2:
; CHECK:    #APP
; CHECK:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm input: pressure
; CHECK:    # {{[0-9]+}}(%rsp), {{[0-9]+}}(%rsp), {{[0-9]+}}(%rsp), {{[0-9]+}}(%rsp), {{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  %rax = alloca i64, align 8
  %rcx = alloca i64, align 8
  %rdx = alloca i64, align 8
  %rsi = alloca i64, align 8
  %rdi = alloca i64, align 8
  %rbx = alloca i64, align 8
  %rbp = alloca i64, align 8
  %r8 = alloca i64, align 8
  %r9 = alloca i64, align 8
  %r10 = alloca i64, align 8
  %r11 = alloca i64, align 8
  %r12 = alloca i64, align 8
  %r13 = alloca i64, align 8
  %r14 = alloca i64, align 8
  %r15 = alloca i64, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  store i64 %asmresult, ptr %rax, align 8
  store i64 %asmresult1, ptr %rcx, align 8
  store i64 %asmresult2, ptr %rdx, align 8
  store i64 %asmresult3, ptr %rsi, align 8
  store i64 %asmresult4, ptr %rdi, align 8
  store i64 %asmresult5, ptr %rbx, align 8
  store i64 %asmresult6, ptr %rbp, align 8
  store i64 %asmresult7, ptr %r8, align 8
  store i64 %asmresult8, ptr %r9, align 8
  store i64 %asmresult9, ptr %r10, align 8
  store i64 %asmresult10, ptr %r11, align 8
  store i64 %asmresult11, ptr %r12, align 8
  store i64 %asmresult12, ptr %r13, align 8
  store i64 %asmresult13, ptr %r14, align 8
  store i64 %asmresult14, ptr %r15, align 8
  %1 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 0
  %2 = load i32, ptr %a, align 4
  %3 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 1
  %4 = load i32, ptr %b, align 4
  %5 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %5, i32 0, i32 2
  %6 = load i32, ptr %c, align 4
  %7 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %7, i32 0, i32 3
  %8 = load i32, ptr %d, align 4
  %9 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %9, i32 0, i32 4
  %10 = load i32, ptr %e, align 4
  call void asm sideeffect "# rm input: pressure\0A\09# $0, $1, $2, $3, $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %2, i32 %4, i32 %6, i32 %8, i32 %10)
  %11 = load i64, ptr %rax, align 8
  %12 = load i64, ptr %rcx, align 8
  %13 = load i64, ptr %rdx, align 8
  %14 = load i64, ptr %rsi, align 8
  %15 = load i64, ptr %rdi, align 8
  %16 = load i64, ptr %rbx, align 8
  %17 = load i64, ptr %rbp, align 8
  %18 = load i64, ptr %r8, align 8
  %19 = load i64, ptr %r9, align 8
  %20 = load i64, ptr %r10, align 8
  %21 = load i64, ptr %r11, align 8
  %22 = load i64, ptr %r12, align 8
  %23 = load i64, ptr %r13, align 8
  %24 = load i64, ptr %r14, align 8
  %25 = load i64, ptr %r15, align 8
  call void @g(i64 noundef %11, i64 noundef %12, i64 noundef %13, i64 noundef %14, i64 noundef %15, i64 noundef %16, i64 noundef %17, i64 noundef %18, i64 noundef %19, i64 noundef %20, i64 noundef %21, i64 noundef %22, i64 noundef %23, i64 noundef %24, i64 noundef %25)
  %26 = load ptr, ptr %foo.addr, align 8
  %a15 = getelementptr inbounds nuw %struct.foo, ptr %26, i32 0, i32 0
  %27 = load i32, ptr %a15, align 4
  ret i32 %27
}

declare void @g(i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef)

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test3(ptr noundef %foo) {
; CHECK-LABEL: test3:
; CHECK:    #APP
; CHECK:    # rm output: no pressure
; CHECK:    # (%rax), (%rcx), (%rdx), (%rsi), (%rdi)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %0, i32 0, i32 0
  %1 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 1
  %2 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 2
  %3 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 3
  %4 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %4, i32 0, i32 4
  call void asm sideeffect "# rm output: no pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, ptr elementtype(i32) %d, ptr elementtype(i32) %e)
  %5 = load ptr, ptr %foo.addr, align 8
  %a1 = getelementptr inbounds nuw %struct.foo, ptr %5, i32 0, i32 0
  %6 = load i32, ptr %a1, align 4
  ret i32 %6
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test4(ptr noundef %foo) {
; CHECK-LABEL: test4:
; CHECK:    #APP
; CHECK:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm output: pressure
; CHECK:    # (%rax), (%rcx), (%rdx), (%rsi), (%rdi)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  %rax = alloca i64, align 8
  %rcx = alloca i64, align 8
  %rdx = alloca i64, align 8
  %rsi = alloca i64, align 8
  %rdi = alloca i64, align 8
  %rbx = alloca i64, align 8
  %rbp = alloca i64, align 8
  %r8 = alloca i64, align 8
  %r9 = alloca i64, align 8
  %r10 = alloca i64, align 8
  %r11 = alloca i64, align 8
  %r12 = alloca i64, align 8
  %r13 = alloca i64, align 8
  %r14 = alloca i64, align 8
  %r15 = alloca i64, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  store i64 %asmresult, ptr %rax, align 8
  store i64 %asmresult1, ptr %rcx, align 8
  store i64 %asmresult2, ptr %rdx, align 8
  store i64 %asmresult3, ptr %rsi, align 8
  store i64 %asmresult4, ptr %rdi, align 8
  store i64 %asmresult5, ptr %rbx, align 8
  store i64 %asmresult6, ptr %rbp, align 8
  store i64 %asmresult7, ptr %r8, align 8
  store i64 %asmresult8, ptr %r9, align 8
  store i64 %asmresult9, ptr %r10, align 8
  store i64 %asmresult10, ptr %r11, align 8
  store i64 %asmresult11, ptr %r12, align 8
  store i64 %asmresult12, ptr %r13, align 8
  store i64 %asmresult13, ptr %r14, align 8
  store i64 %asmresult14, ptr %r15, align 8
  %1 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 0
  %2 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 1
  %3 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 2
  %4 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %4, i32 0, i32 3
  %5 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %5, i32 0, i32 4
  call void asm sideeffect "# rm output: pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, ptr elementtype(i32) %d, ptr elementtype(i32) %e)
  %6 = load i64, ptr %rax, align 8
  %7 = load i64, ptr %rcx, align 8
  %8 = load i64, ptr %rdx, align 8
  %9 = load i64, ptr %rsi, align 8
  %10 = load i64, ptr %rdi, align 8
  %11 = load i64, ptr %rbx, align 8
  %12 = load i64, ptr %rbp, align 8
  %13 = load i64, ptr %r8, align 8
  %14 = load i64, ptr %r9, align 8
  %15 = load i64, ptr %r10, align 8
  %16 = load i64, ptr %r11, align 8
  %17 = load i64, ptr %r12, align 8
  %18 = load i64, ptr %r13, align 8
  %19 = load i64, ptr %r14, align 8
  %20 = load i64, ptr %r15, align 8
  call void @g(i64 noundef %6, i64 noundef %7, i64 noundef %8, i64 noundef %9, i64 noundef %10, i64 noundef %11, i64 noundef %12, i64 noundef %13, i64 noundef %14, i64 noundef %15, i64 noundef %16, i64 noundef %17, i64 noundef %18, i64 noundef %19, i64 noundef %20)
  %21 = load ptr, ptr %foo.addr, align 8
  %a15 = getelementptr inbounds nuw %struct.foo, ptr %21, i32 0, i32 0
  %22 = load i32, ptr %a15, align 4
  ret i32 %22
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test5(ptr noundef %foo) {
; CHECK-LABEL: test5:
; CHECK:    #APP
; CHECK:    # rm tied output: no pressure
; CHECK:    # %ecx, %esi, %r8d, %r10d, %ebx
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %0, i32 0, i32 0
  %1 = load i32, ptr %a, align 4
  %2 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 1
  %3 = load i32, ptr %b, align 4
  %4 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %4, i32 0, i32 2
  %5 = load i32, ptr %c, align 4
  %6 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %6, i32 0, i32 3
  %7 = load i32, ptr %d, align 4
  %8 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %8, i32 0, i32 4
  %9 = load i32, ptr %e, align 4
  call void asm sideeffect "# rm tied output: no pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, ptr elementtype(i32) %d, ptr elementtype(i32) %e, i32 %1, i32 %3, i32 %5, i32 %7, i32 %9)
  %10 = load ptr, ptr %foo.addr, align 8
  %a1 = getelementptr inbounds nuw %struct.foo, ptr %10, i32 0, i32 0
  %11 = load i32, ptr %a1, align 4
  ret i32 %11
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test6(ptr noundef %foo) {
; CHECK-LABEL: test6:
; CHECK:    #APP
; CHECK:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm tied output: pressure
; CHECK:    # %ecx, %esi, %r8d, %r10d, %ebx
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  %rax = alloca i64, align 8
  %rcx = alloca i64, align 8
  %rdx = alloca i64, align 8
  %rsi = alloca i64, align 8
  %rdi = alloca i64, align 8
  %rbx = alloca i64, align 8
  %rbp = alloca i64, align 8
  %r8 = alloca i64, align 8
  %r9 = alloca i64, align 8
  %r10 = alloca i64, align 8
  %r11 = alloca i64, align 8
  %r12 = alloca i64, align 8
  %r13 = alloca i64, align 8
  %r14 = alloca i64, align 8
  %r15 = alloca i64, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  store i64 %asmresult, ptr %rax, align 8
  store i64 %asmresult1, ptr %rcx, align 8
  store i64 %asmresult2, ptr %rdx, align 8
  store i64 %asmresult3, ptr %rsi, align 8
  store i64 %asmresult4, ptr %rdi, align 8
  store i64 %asmresult5, ptr %rbx, align 8
  store i64 %asmresult6, ptr %rbp, align 8
  store i64 %asmresult7, ptr %r8, align 8
  store i64 %asmresult8, ptr %r9, align 8
  store i64 %asmresult9, ptr %r10, align 8
  store i64 %asmresult10, ptr %r11, align 8
  store i64 %asmresult11, ptr %r12, align 8
  store i64 %asmresult12, ptr %r13, align 8
  store i64 %asmresult13, ptr %r14, align 8
  store i64 %asmresult14, ptr %r15, align 8
  %1 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 0
  %2 = load i32, ptr %a, align 4
  %3 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 1
  %4 = load i32, ptr %b, align 4
  %5 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %5, i32 0, i32 2
  %6 = load i32, ptr %c, align 4
  %7 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %7, i32 0, i32 3
  %8 = load i32, ptr %d, align 4
  %9 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %9, i32 0, i32 4
  %10 = load i32, ptr %e, align 4
  call void asm sideeffect "# rm tied output: pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, ptr elementtype(i32) %d, ptr elementtype(i32) %e, i32 %2, i32 %4, i32 %6, i32 %8, i32 %10)
  %11 = load i64, ptr %rax, align 8
  %12 = load i64, ptr %rcx, align 8
  %13 = load i64, ptr %rdx, align 8
  %14 = load i64, ptr %rsi, align 8
  %15 = load i64, ptr %rdi, align 8
  %16 = load i64, ptr %rbx, align 8
  %17 = load i64, ptr %rbp, align 8
  %18 = load i64, ptr %r8, align 8
  %19 = load i64, ptr %r9, align 8
  %20 = load i64, ptr %r10, align 8
  %21 = load i64, ptr %r11, align 8
  %22 = load i64, ptr %r12, align 8
  %23 = load i64, ptr %r13, align 8
  %24 = load i64, ptr %r14, align 8
  %25 = load i64, ptr %r15, align 8
  call void @g(i64 noundef %11, i64 noundef %12, i64 noundef %13, i64 noundef %14, i64 noundef %15, i64 noundef %16, i64 noundef %17, i64 noundef %18, i64 noundef %19, i64 noundef %20, i64 noundef %21, i64 noundef %22, i64 noundef %23, i64 noundef %24, i64 noundef %25)
  %26 = load ptr, ptr %foo.addr, align 8
  %a15 = getelementptr inbounds nuw %struct.foo, ptr %26, i32 0, i32 0
  %27 = load i32, ptr %a15, align 4
  ret i32 %27
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test7(ptr noundef %foo) {
; CHECK-LABEL: test7:
; CHECK:    #APP
; CHECK:    # rm output, r input: no pressure
; CHECK:    # (%rax), %ecx
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %0, i32 0, i32 0
  %1 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 1
  %2 = load i32, ptr %b, align 4
  call void asm sideeffect "# rm output, r input: no pressure\0A\09# $0, $1", "=*rm,r,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, i32 %2)
  %3 = load ptr, ptr %foo.addr, align 8
  %a1 = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 0
  %4 = load i32, ptr %a1, align 4
  ret i32 %4
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test8(ptr noundef %foo) {
; CHECK-LABEL: test8:
; CHECK:    #APP
; CHECK:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # rm output, r input: pressure
; CHECK:    # (%rax), %ecx
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  %rax = alloca i64, align 8
  %rcx = alloca i64, align 8
  %rdx = alloca i64, align 8
  %rsi = alloca i64, align 8
  %rdi = alloca i64, align 8
  %rbx = alloca i64, align 8
  %rbp = alloca i64, align 8
  %r8 = alloca i64, align 8
  %r9 = alloca i64, align 8
  %r10 = alloca i64, align 8
  %r11 = alloca i64, align 8
  %r12 = alloca i64, align 8
  %r13 = alloca i64, align 8
  %r14 = alloca i64, align 8
  %r15 = alloca i64, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  store i64 %asmresult, ptr %rax, align 8
  store i64 %asmresult1, ptr %rcx, align 8
  store i64 %asmresult2, ptr %rdx, align 8
  store i64 %asmresult3, ptr %rsi, align 8
  store i64 %asmresult4, ptr %rdi, align 8
  store i64 %asmresult5, ptr %rbx, align 8
  store i64 %asmresult6, ptr %rbp, align 8
  store i64 %asmresult7, ptr %r8, align 8
  store i64 %asmresult8, ptr %r9, align 8
  store i64 %asmresult9, ptr %r10, align 8
  store i64 %asmresult10, ptr %r11, align 8
  store i64 %asmresult11, ptr %r12, align 8
  store i64 %asmresult12, ptr %r13, align 8
  store i64 %asmresult13, ptr %r14, align 8
  store i64 %asmresult14, ptr %r15, align 8
  %1 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 0
  %2 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 1
  %3 = load i32, ptr %b, align 4
  call void asm sideeffect "# rm output, r input: pressure\0A\09# $0, $1", "=*rm,r,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, i32 %3)
  %4 = load i64, ptr %rax, align 8
  %5 = load i64, ptr %rcx, align 8
  %6 = load i64, ptr %rdx, align 8
  %7 = load i64, ptr %rsi, align 8
  %8 = load i64, ptr %rdi, align 8
  %9 = load i64, ptr %rbx, align 8
  %10 = load i64, ptr %rbp, align 8
  %11 = load i64, ptr %r8, align 8
  %12 = load i64, ptr %r9, align 8
  %13 = load i64, ptr %r10, align 8
  %14 = load i64, ptr %r11, align 8
  %15 = load i64, ptr %r12, align 8
  %16 = load i64, ptr %r13, align 8
  %17 = load i64, ptr %r14, align 8
  %18 = load i64, ptr %r15, align 8
  call void @g(i64 noundef %4, i64 noundef %5, i64 noundef %6, i64 noundef %7, i64 noundef %8, i64 noundef %9, i64 noundef %10, i64 noundef %11, i64 noundef %12, i64 noundef %13, i64 noundef %14, i64 noundef %15, i64 noundef %16, i64 noundef %17, i64 noundef %18)
  %19 = load ptr, ptr %foo.addr, align 8
  %a15 = getelementptr inbounds nuw %struct.foo, ptr %19, i32 0, i32 0
  %20 = load i32, ptr %a15, align 4
  ret i32 %20
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test9(ptr noundef %foo) {
; CHECK-LABEL: test9:
; CHECK:    #APP
; CHECK:    # m output, rm input: no pressure
; CHECK:    # (%rax), -{{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %0, i32 0, i32 0
  %1 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 1
  %2 = load i32, ptr %b, align 4
  call void asm sideeffect "# m output, rm input: no pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, i32 %2)
  %3 = load ptr, ptr %foo.addr, align 8
  %a1 = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 0
  %4 = load i32, ptr %a1, align 4
  ret i32 %4
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test10(ptr noundef %foo) {
; CHECK-LABEL: test10:
; CHECK:    #APP
; CHECK:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # m output, rm input: pressure
; CHECK:    # (%rax), {{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  %rax = alloca i64, align 8
  %rcx = alloca i64, align 8
  %rdx = alloca i64, align 8
  %rsi = alloca i64, align 8
  %rdi = alloca i64, align 8
  %rbx = alloca i64, align 8
  %rbp = alloca i64, align 8
  %r8 = alloca i64, align 8
  %r9 = alloca i64, align 8
  %r10 = alloca i64, align 8
  %r11 = alloca i64, align 8
  %r12 = alloca i64, align 8
  %r13 = alloca i64, align 8
  %r14 = alloca i64, align 8
  %r15 = alloca i64, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  store i64 %asmresult, ptr %rax, align 8
  store i64 %asmresult1, ptr %rcx, align 8
  store i64 %asmresult2, ptr %rdx, align 8
  store i64 %asmresult3, ptr %rsi, align 8
  store i64 %asmresult4, ptr %rdi, align 8
  store i64 %asmresult5, ptr %rbx, align 8
  store i64 %asmresult6, ptr %rbp, align 8
  store i64 %asmresult7, ptr %r8, align 8
  store i64 %asmresult8, ptr %r9, align 8
  store i64 %asmresult9, ptr %r10, align 8
  store i64 %asmresult10, ptr %r11, align 8
  store i64 %asmresult11, ptr %r12, align 8
  store i64 %asmresult12, ptr %r13, align 8
  store i64 %asmresult13, ptr %r14, align 8
  store i64 %asmresult14, ptr %r15, align 8
  %1 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 0
  %2 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 1
  %3 = load i32, ptr %b, align 4
  call void asm sideeffect "# m output, rm input: pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, i32 %3)
  %4 = load i64, ptr %rax, align 8
  %5 = load i64, ptr %rcx, align 8
  %6 = load i64, ptr %rdx, align 8
  %7 = load i64, ptr %rsi, align 8
  %8 = load i64, ptr %rdi, align 8
  %9 = load i64, ptr %rbx, align 8
  %10 = load i64, ptr %rbp, align 8
  %11 = load i64, ptr %r8, align 8
  %12 = load i64, ptr %r9, align 8
  %13 = load i64, ptr %r10, align 8
  %14 = load i64, ptr %r11, align 8
  %15 = load i64, ptr %r12, align 8
  %16 = load i64, ptr %r13, align 8
  %17 = load i64, ptr %r14, align 8
  %18 = load i64, ptr %r15, align 8
  call void @g(i64 noundef %4, i64 noundef %5, i64 noundef %6, i64 noundef %7, i64 noundef %8, i64 noundef %9, i64 noundef %10, i64 noundef %11, i64 noundef %12, i64 noundef %13, i64 noundef %14, i64 noundef %15, i64 noundef %16, i64 noundef %17, i64 noundef %18)
  %19 = load ptr, ptr %foo.addr, align 8
  %a15 = getelementptr inbounds nuw %struct.foo, ptr %19, i32 0, i32 0
  %20 = load i32, ptr %a15, align 4
  ret i32 %20
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test11(ptr noundef %foo) {
; CHECK-LABEL: test11:
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: no pressure
; CHECK:    # (%rax), (%rcx), (%rdx), (%rsi), (%rdi), -{{[0-9]+}}(%rsp), -{{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %0, i32 0, i32 0
  %1 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 1
  %2 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 2
  %3 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 3
  %4 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %4, i32 0, i32 4
  %5 = load ptr, ptr %foo.addr, align 8
  %a1 = getelementptr inbounds nuw %struct.foo, ptr %5, i32 0, i32 0
  %6 = load i32, ptr %a1, align 4
  %7 = load ptr, ptr %foo.addr, align 8
  %b2 = getelementptr inbounds nuw %struct.foo, ptr %7, i32 0, i32 1
  %8 = load i32, ptr %b2, align 4
  call void asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, ptr elementtype(i32) %d, ptr elementtype(i32) %e, i32 %6, i32 %8)
  %9 = load ptr, ptr %foo.addr, align 8
  %a3 = getelementptr inbounds nuw %struct.foo, ptr %9, i32 0, i32 0
  %10 = load i32, ptr %a3, align 4
  ret i32 %10
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test12(ptr noundef %foo) {
; CHECK-LABEL: test12:
; CHECK:    #APP
; CHECK:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: pressure
; CHECK:    # (%rax), (%rcx), (%rdx), (%rsi), (%rdi), {{[0-9]+}}(%rsp), {{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  %rax = alloca i64, align 8
  %rcx = alloca i64, align 8
  %rdx = alloca i64, align 8
  %rsi = alloca i64, align 8
  %rdi = alloca i64, align 8
  %rbx = alloca i64, align 8
  %rbp = alloca i64, align 8
  %r8 = alloca i64, align 8
  %r9 = alloca i64, align 8
  %r10 = alloca i64, align 8
  %r11 = alloca i64, align 8
  %r12 = alloca i64, align 8
  %r13 = alloca i64, align 8
  %r14 = alloca i64, align 8
  %r15 = alloca i64, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  store i64 %asmresult, ptr %rax, align 8
  store i64 %asmresult1, ptr %rcx, align 8
  store i64 %asmresult2, ptr %rdx, align 8
  store i64 %asmresult3, ptr %rsi, align 8
  store i64 %asmresult4, ptr %rdi, align 8
  store i64 %asmresult5, ptr %rbx, align 8
  store i64 %asmresult6, ptr %rbp, align 8
  store i64 %asmresult7, ptr %r8, align 8
  store i64 %asmresult8, ptr %r9, align 8
  store i64 %asmresult9, ptr %r10, align 8
  store i64 %asmresult10, ptr %r11, align 8
  store i64 %asmresult11, ptr %r12, align 8
  store i64 %asmresult12, ptr %r13, align 8
  store i64 %asmresult13, ptr %r14, align 8
  store i64 %asmresult14, ptr %r15, align 8
  %1 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 0
  %2 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 1
  %3 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 2
  %4 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %4, i32 0, i32 3
  %5 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %5, i32 0, i32 4
  %6 = load ptr, ptr %foo.addr, align 8
  %a15 = getelementptr inbounds nuw %struct.foo, ptr %6, i32 0, i32 0
  %7 = load i32, ptr %a15, align 4
  %8 = load ptr, ptr %foo.addr, align 8
  %b16 = getelementptr inbounds nuw %struct.foo, ptr %8, i32 0, i32 1
  %9 = load i32, ptr %b16, align 4
  call void asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, ptr elementtype(i32) %d, ptr elementtype(i32) %e, i32 %7, i32 %9)
  %10 = load i64, ptr %rax, align 8
  %11 = load i64, ptr %rcx, align 8
  %12 = load i64, ptr %rdx, align 8
  %13 = load i64, ptr %rsi, align 8
  %14 = load i64, ptr %rdi, align 8
  %15 = load i64, ptr %rbx, align 8
  %16 = load i64, ptr %rbp, align 8
  %17 = load i64, ptr %r8, align 8
  %18 = load i64, ptr %r9, align 8
  %19 = load i64, ptr %r10, align 8
  %20 = load i64, ptr %r11, align 8
  %21 = load i64, ptr %r12, align 8
  %22 = load i64, ptr %r13, align 8
  %23 = load i64, ptr %r14, align 8
  %24 = load i64, ptr %r15, align 8
  call void @g(i64 noundef %10, i64 noundef %11, i64 noundef %12, i64 noundef %13, i64 noundef %14, i64 noundef %15, i64 noundef %16, i64 noundef %17, i64 noundef %18, i64 noundef %19, i64 noundef %20, i64 noundef %21, i64 noundef %22, i64 noundef %23, i64 noundef %24)
  %25 = load ptr, ptr %foo.addr, align 8
  %a17 = getelementptr inbounds nuw %struct.foo, ptr %25, i32 0, i32 0
  %26 = load i32, ptr %a17, align 4
  ret i32 %26
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test13(ptr noundef %foo) {
; CHECK-LABEL: test13:
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: no pressure
; CHECK:    # (%rax), (%rcx), (%rdx), -{{[0-9]+}}(%rsp), -{{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %0, i32 0, i32 0
  %1 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 1
  %2 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 2
  %3 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 3
  %4 = load i32, ptr %d, align 4
  %5 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %5, i32 0, i32 4
  %6 = load i32, ptr %e, align 4
  call void asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4", "=*&rm,=*&rm,=*&rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, i32 %4, i32 %6)
  %7 = load ptr, ptr %foo.addr, align 8
  %a1 = getelementptr inbounds nuw %struct.foo, ptr %7, i32 0, i32 0
  %8 = load i32, ptr %a1, align 4
  ret i32 %8
}

; Function Attrs: noinline nounwind optnone uwtable
define dso_local i32 @test14(ptr noundef %foo) {
; CHECK-LABEL: test14:
; CHECK:    #APP
; CHECK:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; CHECK:    #NO_APP
; CHECK:    #APP
; CHECK:    # multiple m output, rm input: pressure
; CHECK:    # (%rax), (%rcx), (%rdx), {{[0-9]+}}(%rsp), {{[0-9]+}}(%rsp)
; CHECK:    #NO_APP
entry:
  %foo.addr = alloca ptr, align 8
  %rax = alloca i64, align 8
  %rcx = alloca i64, align 8
  %rdx = alloca i64, align 8
  %rsi = alloca i64, align 8
  %rdi = alloca i64, align 8
  %rbx = alloca i64, align 8
  %rbp = alloca i64, align 8
  %r8 = alloca i64, align 8
  %r9 = alloca i64, align 8
  %r10 = alloca i64, align 8
  %r11 = alloca i64, align 8
  %r12 = alloca i64, align 8
  %r13 = alloca i64, align 8
  %r14 = alloca i64, align 8
  %r15 = alloca i64, align 8
  store ptr %foo, ptr %foo.addr, align 8
  %0 = call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  store i64 %asmresult, ptr %rax, align 8
  store i64 %asmresult1, ptr %rcx, align 8
  store i64 %asmresult2, ptr %rdx, align 8
  store i64 %asmresult3, ptr %rsi, align 8
  store i64 %asmresult4, ptr %rdi, align 8
  store i64 %asmresult5, ptr %rbx, align 8
  store i64 %asmresult6, ptr %rbp, align 8
  store i64 %asmresult7, ptr %r8, align 8
  store i64 %asmresult8, ptr %r9, align 8
  store i64 %asmresult9, ptr %r10, align 8
  store i64 %asmresult10, ptr %r11, align 8
  store i64 %asmresult11, ptr %r12, align 8
  store i64 %asmresult12, ptr %r13, align 8
  store i64 %asmresult13, ptr %r14, align 8
  store i64 %asmresult14, ptr %r15, align 8
  %1 = load ptr, ptr %foo.addr, align 8
  %a = getelementptr inbounds nuw %struct.foo, ptr %1, i32 0, i32 0
  %2 = load ptr, ptr %foo.addr, align 8
  %b = getelementptr inbounds nuw %struct.foo, ptr %2, i32 0, i32 1
  %3 = load ptr, ptr %foo.addr, align 8
  %c = getelementptr inbounds nuw %struct.foo, ptr %3, i32 0, i32 2
  %4 = load ptr, ptr %foo.addr, align 8
  %d = getelementptr inbounds nuw %struct.foo, ptr %4, i32 0, i32 3
  %5 = load i32, ptr %d, align 4
  %6 = load ptr, ptr %foo.addr, align 8
  %e = getelementptr inbounds nuw %struct.foo, ptr %6, i32 0, i32 4
  %7 = load i32, ptr %e, align 4
  call void asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4", "=*&rm,=*&rm,=*&rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %a, ptr elementtype(i32) %b, ptr elementtype(i32) %c, i32 %5, i32 %7)
  %8 = load i64, ptr %rax, align 8
  %9 = load i64, ptr %rcx, align 8
  %10 = load i64, ptr %rdx, align 8
  %11 = load i64, ptr %rsi, align 8
  %12 = load i64, ptr %rdi, align 8
  %13 = load i64, ptr %rbx, align 8
  %14 = load i64, ptr %rbp, align 8
  %15 = load i64, ptr %r8, align 8
  %16 = load i64, ptr %r9, align 8
  %17 = load i64, ptr %r10, align 8
  %18 = load i64, ptr %r11, align 8
  %19 = load i64, ptr %r12, align 8
  %20 = load i64, ptr %r13, align 8
  %21 = load i64, ptr %r14, align 8
  %22 = load i64, ptr %r15, align 8
  call void @g(i64 noundef %8, i64 noundef %9, i64 noundef %10, i64 noundef %11, i64 noundef %12, i64 noundef %13, i64 noundef %14, i64 noundef %15, i64 noundef %16, i64 noundef %17, i64 noundef %18, i64 noundef %19, i64 noundef %20, i64 noundef %21, i64 noundef %22)
  %23 = load ptr, ptr %foo.addr, align 8
  %a15 = getelementptr inbounds nuw %struct.foo, ptr %23, i32 0, i32 0
  %24 = load i32, ptr %a15, align 4
  ret i32 %24
}
