; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --filter "^\t#" --version 4
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=FAST_ISEL_GREEDY_RA %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=fast < %s \
; RUN:     | FileCheck --check-prefix=FAST_ISEL_FAST_RA %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=GREEDY_RA %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=fast < %s \
; RUN:     | FileCheck --check-prefix=FAST_RA %s

; The non-fast register allocators should use registers when there isn't
; register pressure.

define dso_local i32 @test_rm_input_no_pressure(ptr noundef readonly captures(none) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_rm_input_no_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm input: no pressure
; FAST_ISEL_GREEDY_RA:    # %eax, %ecx, %edx, %esi, %r8d
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_rm_input_no_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm input: no pressure
; FAST_ISEL_FAST_RA:    # %eax, %ecx, %edx, %esi, %r8d
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_rm_input_no_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm input: no pressure
; GREEDY_RA:    # %eax, %ecx, %edx, %esi, %r8d
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_rm_input_no_pressure:
; FAST_RA:    #APP
; FAST_RA:    # rm input: no pressure
; FAST_RA:    # %eax, %ecx, %edx, %esi, %r8d
; FAST_RA:    #NO_APP
entry:
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %0 = load i32, ptr %foo, align 4
  %b2 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b2, align 4
  %c3 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %2 = load i32, ptr %c3, align 4
  %d4 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %3 = load i32, ptr %d4, align 4
  %e5 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %4 = load i32, ptr %e5, align 4
  tail call void asm sideeffect "# rm input: no pressure\0A\09# $0, $1, $2, $3, $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %0, i32 %1, i32 %2, i32 %3, i32 %4)
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %5 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %6 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %7 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %8 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %9 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# rm input: no pressure\0A\09# $0, $1, $2, $3, $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %5, i32 %6, i32 %7, i32 %8, i32 %9)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %10 = load i32, ptr %foo, align 4
  ret i32 %10
}

define dso_local i32 @test_rm_pressure(ptr noundef readonly captures(none) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_rm_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_GREEDY_RA:    #NO_APP
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm input: pressure
; FAST_ISEL_GREEDY_RA:    # %esi, %edi, %r8d, %r9d, %eax
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_rm_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_FAST_RA:    #NO_APP
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm input: pressure
; FAST_ISEL_FAST_RA:    # %eax, %ecx, %edx, %esi, %edi
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_rm_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; GREEDY_RA:    #NO_APP
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm input: pressure
; GREEDY_RA:    # %esi, %edi, %r8d, %r9d, %eax
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_rm_pressure:
; FAST_RA:    #APP
; FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_RA:    #NO_APP
; FAST_RA:    #APP
; FAST_RA:    # rm input: pressure
; FAST_RA:    # %eax, %ecx, %edx, %esi, %edi
; FAST_RA:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %1 = load i32, ptr %foo, align 4
  %b16 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %2 = load i32, ptr %b16, align 4
  %c17 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %3 = load i32, ptr %c17, align 4
  %d18 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %4 = load i32, ptr %d18, align 4
  %e19 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %5 = load i32, ptr %e19, align 4
  tail call void asm sideeffect "# rm input: pressure\0A\09# $0, $1, $2, $3, $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %1, i32 %2, i32 %3, i32 %4, i32 %5)
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %6 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %7 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %8 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %9 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %10 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# rm input: pressure\0A\09# $0, $1, $2, $3, $4", "rm,rm,rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %6, i32 %7, i32 %8, i32 %9, i32 %10)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %11 = load i32, ptr %foo, align 4
  ret i32 %11
}

define dso_local i32 @test_output_no_pressure(ptr noundef writeonly captures(none) initializes((0, 20)) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_output_no_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm output: no pressure
; FAST_ISEL_GREEDY_RA:    # %r8d, %r9d, %r10d, %r11d, %ebx
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_output_no_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm output: no pressure
; FAST_ISEL_FAST_RA:    # %ebx, %r11d, %r9d, %esi, %ecx
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_output_no_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm output: no pressure
; GREEDY_RA:    # %eax, %ecx, %edx, %esi, %r8d
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_output_no_pressure:
; FAST_RA:    #APP
; FAST_RA:    # rm output: no pressure
; FAST_RA:    # %eax, %r8d, %esi, %edx, %ecx
; FAST_RA:    #NO_APP
entry:
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b2 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c3 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d4 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e5 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %0 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm output: no pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,~{dirflag},~{fpsr},~{flags}"()
  %asmresult = extractvalue { i32, i32, i32, i32, i32 } %0, 0
  %asmresult6 = extractvalue { i32, i32, i32, i32, i32 } %0, 1
  %asmresult7 = extractvalue { i32, i32, i32, i32, i32 } %0, 2
  %asmresult8 = extractvalue { i32, i32, i32, i32, i32 } %0, 3
  %asmresult9 = extractvalue { i32, i32, i32, i32, i32 } %0, 4
  store i32 %asmresult, ptr %foo, align 4
  store i32 %asmresult6, ptr %b2, align 4
  store i32 %asmresult7, ptr %c3, align 4
  store i32 %asmresult8, ptr %d4, align 4
  store i32 %asmresult9, ptr %e5, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  tail call void asm sideeffect "# rm output: no pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e)
  %.pre = load i32, ptr %foo, align 4
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %1 = phi i32 [ %asmresult, %asm.pref.reg ], [ %.pre, %asm.pref.mem ]
  ret i32 %1
}

define dso_local i32 @test_output_pressure(ptr noundef writeonly captures(none) initializes((0, 20)) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_output_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_GREEDY_RA:    #NO_APP
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm output: pressure
; FAST_ISEL_GREEDY_RA:    # %esi, %edi, %r8d, %r9d, %ecx
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_output_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_FAST_RA:    #NO_APP
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm output: pressure
; FAST_ISEL_FAST_RA:    # %eax, %edi, %ecx, %edx, %esi
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_output_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; GREEDY_RA:    #NO_APP
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm output: pressure
; GREEDY_RA:    # %esi, %edi, %r8d, %r9d, %eax
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_output_pressure:
; FAST_RA:    #APP
; FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_RA:    #NO_APP
; FAST_RA:    #APP
; FAST_RA:    # rm output: pressure
; FAST_RA:    # %eax, %edi, %ecx, %edx, %esi
; FAST_RA:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b16 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c17 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d18 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e19 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %1 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm output: pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,~{dirflag},~{fpsr},~{flags}"()
  %asmresult20 = extractvalue { i32, i32, i32, i32, i32 } %1, 0
  %asmresult21 = extractvalue { i32, i32, i32, i32, i32 } %1, 1
  %asmresult22 = extractvalue { i32, i32, i32, i32, i32 } %1, 2
  %asmresult23 = extractvalue { i32, i32, i32, i32, i32 } %1, 3
  %asmresult24 = extractvalue { i32, i32, i32, i32, i32 } %1, 4
  store i32 %asmresult20, ptr %foo, align 4
  store i32 %asmresult21, ptr %b16, align 4
  store i32 %asmresult22, ptr %c17, align 4
  store i32 %asmresult23, ptr %d18, align 4
  store i32 %asmresult24, ptr %e19, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  tail call void asm sideeffect "# rm output: pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %2 = load i32, ptr %foo, align 4
  ret i32 %2
}

define dso_local i32 @test_tied_output_no_pressure(ptr noundef captures(none) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_tied_output_no_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm tied output: no pressure
; FAST_ISEL_GREEDY_RA:    # %eax, %edx, %r8d, %r10d, %ebx
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_tied_output_no_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm tied output: no pressure
; FAST_ISEL_FAST_RA:    # %ebx, %r11d, %r9d, %esi, %ecx
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_tied_output_no_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm tied output: no pressure
; GREEDY_RA:    # %eax, %ecx, %edx, %esi, %r8d
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_tied_output_no_pressure:
; FAST_RA:    #APP
; FAST_RA:    # rm tied output: no pressure
; FAST_RA:    # %eax, %r8d, %esi, %edx, %ecx
; FAST_RA:    #NO_APP
entry:
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %0 = load i32, ptr %foo, align 4
  %b2 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b2, align 4
  %c3 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %2 = load i32, ptr %c3, align 4
  %d4 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %3 = load i32, ptr %d4, align 4
  %e5 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %4 = load i32, ptr %e5, align 4
  %5 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm tied output: no pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(i32 %0, i32 %1, i32 %2, i32 %3, i32 %4)
  %asmresult = extractvalue { i32, i32, i32, i32, i32 } %5, 0
  %asmresult6 = extractvalue { i32, i32, i32, i32, i32 } %5, 1
  %asmresult7 = extractvalue { i32, i32, i32, i32, i32 } %5, 2
  %asmresult8 = extractvalue { i32, i32, i32, i32, i32 } %5, 3
  %asmresult9 = extractvalue { i32, i32, i32, i32, i32 } %5, 4
  store i32 %asmresult, ptr %foo, align 4
  store i32 %asmresult6, ptr %b2, align 4
  store i32 %asmresult7, ptr %c3, align 4
  store i32 %asmresult8, ptr %d4, align 4
  store i32 %asmresult9, ptr %e5, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %6 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %7 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %8 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %9 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %10 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# rm tied output: no pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %6, i32 %7, i32 %8, i32 %9, i32 %10)
  %.pre = load i32, ptr %foo, align 4
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %11 = phi i32 [ %asmresult, %asm.pref.reg ], [ %.pre, %asm.pref.mem ]
  ret i32 %11
}

define dso_local i32 @test_tied_output_pressure(ptr noundef captures(none) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_tied_output_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_GREEDY_RA:    #NO_APP
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm tied output: pressure
; FAST_ISEL_GREEDY_RA:    # %esi, %edi, %r8d, %r9d, %ecx
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_tied_output_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_FAST_RA:    #NO_APP
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm tied output: pressure
; FAST_ISEL_FAST_RA:    # %eax, %edi, %ecx, %edx, %esi
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_tied_output_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; GREEDY_RA:    #NO_APP
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm tied output: pressure
; GREEDY_RA:    # %esi, %edi, %r8d, %r9d, %eax
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_tied_output_pressure:
; FAST_RA:    #APP
; FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_RA:    #NO_APP
; FAST_RA:    #APP
; FAST_RA:    # rm tied output: pressure
; FAST_RA:    # %eax, %edi, %ecx, %edx, %esi
; FAST_RA:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %1 = load i32, ptr %foo, align 4
  %b16 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %2 = load i32, ptr %b16, align 4
  %c17 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %3 = load i32, ptr %c17, align 4
  %d18 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %4 = load i32, ptr %d18, align 4
  %e19 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %5 = load i32, ptr %e19, align 4
  %6 = tail call { i32, i32, i32, i32, i32 } asm sideeffect "# rm tied output: pressure\0A\09# $0, $1, $2, $3, $4", "=rm,=rm,=rm,=rm,=rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(i32 %1, i32 %2, i32 %3, i32 %4, i32 %5)
  %asmresult20 = extractvalue { i32, i32, i32, i32, i32 } %6, 0
  %asmresult21 = extractvalue { i32, i32, i32, i32, i32 } %6, 1
  %asmresult22 = extractvalue { i32, i32, i32, i32, i32 } %6, 2
  %asmresult23 = extractvalue { i32, i32, i32, i32, i32 } %6, 3
  %asmresult24 = extractvalue { i32, i32, i32, i32, i32 } %6, 4
  store i32 %asmresult20, ptr %foo, align 4
  store i32 %asmresult21, ptr %b16, align 4
  store i32 %asmresult22, ptr %c17, align 4
  store i32 %asmresult23, ptr %d18, align 4
  store i32 %asmresult24, ptr %e19, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %7 = load i32, ptr %foo, align 4
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %8 = load i32, ptr %b, align 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %9 = load i32, ptr %c, align 4
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %10 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %11 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# rm tied output: pressure\0A\09# $0, $1, $2, $3, $4", "=*rm,=*rm,=*rm,=*rm,=*rm,0,1,2,3,4,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %7, i32 %8, i32 %9, i32 %10, i32 %11)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %12 = load i32, ptr %foo, align 4
  ret i32 %12
}

define dso_local i32 @test_rm_output_r_input_no_pressure(ptr noundef captures(none) initializes((0, 4)) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_rm_output_r_input_no_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm output, r input: no pressure
; FAST_ISEL_GREEDY_RA:    # %eax, %eax
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_rm_output_r_input_no_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm output, r input: no pressure
; FAST_ISEL_FAST_RA:    # %eax, %eax
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_rm_output_r_input_no_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm output, r input: no pressure
; GREEDY_RA:    # %eax, %eax
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_rm_output_r_input_no_pressure:
; FAST_RA:    #APP
; FAST_RA:    # rm output, r input: no pressure
; FAST_RA:    # %eax, %eax
; FAST_RA:    #NO_APP
entry:
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b2 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %0 = load i32, ptr %b2, align 4
  %1 = tail call i32 asm sideeffect "# rm output, r input: no pressure\0A\09# $0, $1", "=rm,r,~{dirflag},~{fpsr},~{flags}"(i32 %0)
  store i32 %1, ptr %foo, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %2 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# rm output, r input: no pressure\0A\09# $0, $1", "=*rm,r,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %2)
  %.pre = load i32, ptr %foo, align 4
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %3 = phi i32 [ %1, %asm.pref.reg ], [ %.pre, %asm.pref.mem ]
  ret i32 %3
}

define dso_local i32 @test_rm_output_r_input_pressure(ptr noundef captures(none) initializes((0, 4)) %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_rm_output_r_input_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_GREEDY_RA:    #NO_APP
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # rm output, r input: pressure
; FAST_ISEL_GREEDY_RA:    # %esi, %esi
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_rm_output_r_input_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_FAST_RA:    #NO_APP
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # rm output, r input: pressure
; FAST_ISEL_FAST_RA:    # %eax, %eax
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_rm_output_r_input_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; GREEDY_RA:    #NO_APP
; GREEDY_RA:    #APP
; GREEDY_RA:    # rm output, r input: pressure
; GREEDY_RA:    # %esi, %esi
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_rm_output_r_input_pressure:
; FAST_RA:    #APP
; FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_RA:    #NO_APP
; FAST_RA:    #APP
; FAST_RA:    # rm output, r input: pressure
; FAST_RA:    # %eax, %eax
; FAST_RA:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b16 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b16, align 4
  %2 = tail call i32 asm sideeffect "# rm output, r input: pressure\0A\09# $0, $1", "=rm,r,~{dirflag},~{fpsr},~{flags}"(i32 %1)
  store i32 %2, ptr %foo, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %3 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# rm output, r input: pressure\0A\09# $0, $1", "=*rm,r,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %3)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %4 = load i32, ptr %foo, align 4
  ret i32 %4
}

define dso_local i32 @test_m_output_rm_input_no_pressure(ptr noundef %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_m_output_rm_input_no_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # m output, rm input: no pressure
; FAST_ISEL_GREEDY_RA:    # (%rdi), %eax
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_m_output_rm_input_no_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # m output, rm input: no pressure
; FAST_ISEL_FAST_RA:    # (%rdi), %eax
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_m_output_rm_input_no_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # m output, rm input: no pressure
; GREEDY_RA:    # (%rdi), %eax
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_m_output_rm_input_no_pressure:
; FAST_RA:    #APP
; FAST_RA:    # m output, rm input: no pressure
; FAST_RA:    # (%rdi), %eax
; FAST_RA:    #NO_APP
entry:
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b2 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %0 = load i32, ptr %b2, align 4
  tail call void asm sideeffect "# m output, rm input: no pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %0)
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# m output, rm input: no pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %1)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %2 = load i32, ptr %foo, align 4
  ret i32 %2
}

define dso_local i32 @test_m_output_rm_input_pressure(ptr noundef %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_m_output_rm_input_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_GREEDY_RA:    #NO_APP
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # m output, rm input: pressure
; FAST_ISEL_GREEDY_RA:    # (%rbp), %esi
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_m_output_rm_input_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_FAST_RA:    #NO_APP
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # m output, rm input: pressure
; FAST_ISEL_FAST_RA:    # (%rdi), %eax
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_m_output_rm_input_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; GREEDY_RA:    #NO_APP
; GREEDY_RA:    #APP
; GREEDY_RA:    # m output, rm input: pressure
; GREEDY_RA:    # (%rbp), %esi
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_m_output_rm_input_pressure:
; FAST_RA:    #APP
; FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_RA:    #NO_APP
; FAST_RA:    #APP
; FAST_RA:    # m output, rm input: pressure
; FAST_RA:    # (%rdi), %eax
; FAST_RA:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b16 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %1 = load i32, ptr %b16, align 4
  tail call void asm sideeffect "# m output, rm input: pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %1)
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %2 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# m output, rm input: pressure\0A\09# $0, $1", "=*m,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, i32 %2)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %3 = load i32, ptr %foo, align 4
  ret i32 %3
}

define dso_local i32 @test_mult_m_output_rm_input_no_pressure(ptr noundef %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_mult_m_output_rm_input_no_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # multiple m output, rm input: no pressure
; FAST_ISEL_GREEDY_RA:    # (%rdi), (%rax), (%rcx), (%rdx), (%rsi), %r8d, %r9d
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_mult_m_output_rm_input_no_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # multiple m output, rm input: no pressure
; FAST_ISEL_FAST_RA:    # (%rdi), (%rax), (%rcx), (%rdx), (%rsi), %r8d, %r9d
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_mult_m_output_rm_input_no_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # multiple m output, rm input: no pressure
; GREEDY_RA:    # (%rdi), 4(%rdi), 8(%rdi), 12(%rdi), 16(%rdi), %eax, %ecx
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_mult_m_output_rm_input_no_pressure:
; FAST_RA:    #APP
; FAST_RA:    # multiple m output, rm input: no pressure
; FAST_RA:    # (%rdi), 4(%rdi), 8(%rdi), 12(%rdi), 16(%rdi), %eax, %ecx
; FAST_RA:    #NO_APP
entry:
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b4 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c5 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d6 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e7 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %0 = load i32, ptr %foo, align 4
  %1 = load i32, ptr %b4, align 4
  tail call void asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b4, ptr nonnull elementtype(i32) %c5, ptr nonnull elementtype(i32) %d6, ptr nonnull elementtype(i32) %e7, i32 %0, i32 %1)
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %2 = load i32, ptr %foo, align 4
  %3 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %2, i32 %3)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %4 = load i32, ptr %foo, align 4
  ret i32 %4
}

define dso_local i32 @test_mult_m_output_rm_input_pressure(ptr noundef %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_mult_m_output_rm_input_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_GREEDY_RA:    #NO_APP
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # multiple m output, rm input: pressure
; FAST_ISEL_GREEDY_RA:    # (%rbp), (%r8), (%r9), (%rbx), (%rsi), %eax, %edi
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_mult_m_output_rm_input_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_FAST_RA:    #NO_APP
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # multiple m output, rm input: pressure
; FAST_ISEL_FAST_RA:    # (%rdi), (%rax), (%rcx), (%rdx), (%rsi), %r8d, %r9d
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_mult_m_output_rm_input_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; GREEDY_RA:    #NO_APP
; GREEDY_RA:    #APP
; GREEDY_RA:    # multiple m output, rm input: pressure
; GREEDY_RA:    # (%rbp), 4(%rbp), 8(%rbp), 12(%rbp), 16(%rbp), %esi, %edi
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_mult_m_output_rm_input_pressure:
; FAST_RA:    #APP
; FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_RA:    #NO_APP
; FAST_RA:    #APP
; FAST_RA:    # multiple m output, rm input: pressure
; FAST_RA:    # (%rdi), 4(%rdi), 8(%rdi), 12(%rdi), 16(%rdi), %eax, %ecx
; FAST_RA:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b18 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c19 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d20 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e21 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %1 = load i32, ptr %foo, align 4
  %2 = load i32, ptr %b18, align 4
  tail call void asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b18, ptr nonnull elementtype(i32) %c19, ptr nonnull elementtype(i32) %d20, ptr nonnull elementtype(i32) %e21, i32 %1, i32 %2)
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %3 = load i32, ptr %foo, align 4
  %4 = load i32, ptr %b, align 4
  tail call void asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4, $5, $6", "=*m,=*m,=*m,=*m,=*m,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, ptr nonnull elementtype(i32) %d, ptr nonnull elementtype(i32) %e, i32 %3, i32 %4)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %5 = load i32, ptr %foo, align 4
  ret i32 %5
}

define dso_local i32 @test_mult_m_early_clobber_output_rm_input_no_pressure(ptr noundef %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_mult_m_early_clobber_output_rm_input_no_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # multiple m output, rm input: no pressure
; FAST_ISEL_GREEDY_RA:    # %r8d, %r9d, %r10d, %edx, %esi
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_mult_m_early_clobber_output_rm_input_no_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # multiple m output, rm input: no pressure
; FAST_ISEL_FAST_RA:    # %r8d, %esi, %ecx, %r9d, %r10d
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_mult_m_early_clobber_output_rm_input_no_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # multiple m output, rm input: no pressure
; GREEDY_RA:    # %eax, %esi, %r8d, %ecx, %edx
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_mult_m_early_clobber_output_rm_input_no_pressure:
; FAST_RA:    #APP
; FAST_RA:    # multiple m output, rm input: no pressure
; FAST_RA:    # %eax, %edx, %ecx, %esi, %r8d
; FAST_RA:    #NO_APP
entry:
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b2 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c3 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d4 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %0 = load i32, ptr %d4, align 4
  %e5 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %1 = load i32, ptr %e5, align 4
  %2 = tail call { i32, i32, i32 } asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4", "=&rm,=&rm,=&rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %0, i32 %1)
  %asmresult = extractvalue { i32, i32, i32 } %2, 0
  %asmresult6 = extractvalue { i32, i32, i32 } %2, 1
  %asmresult7 = extractvalue { i32, i32, i32 } %2, 2
  store i32 %asmresult, ptr %foo, align 4
  store i32 %asmresult6, ptr %b2, align 4
  store i32 %asmresult7, ptr %c3, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %3 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %4 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# multiple m output, rm input: no pressure\0A\09# $0, $1, $2, $3, $4", "=*&rm,=*&rm,=*&rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, i32 %3, i32 %4)
  %.pre = load i32, ptr %foo, align 4
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %5 = phi i32 [ %asmresult, %asm.pref.reg ], [ %.pre, %asm.pref.mem ]
  ret i32 %5
}

define dso_local i32 @test_mult_m_early_clobber_output_rm_input_pressure(ptr noundef %foo) local_unnamed_addr {
; FAST_ISEL_GREEDY_RA-LABEL: test_mult_m_early_clobber_output_rm_input_pressure:
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_GREEDY_RA:    #NO_APP
; FAST_ISEL_GREEDY_RA:    #APP
; FAST_ISEL_GREEDY_RA:    # multiple m output, rm input: pressure
; FAST_ISEL_GREEDY_RA:    # %r8d, %r9d, %ecx, %esi, %edi
; FAST_ISEL_GREEDY_RA:    #NO_APP
;
; FAST_ISEL_FAST_RA-LABEL: test_mult_m_early_clobber_output_rm_input_pressure:
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_ISEL_FAST_RA:    #NO_APP
; FAST_ISEL_FAST_RA:    #APP
; FAST_ISEL_FAST_RA:    # multiple m output, rm input: pressure
; FAST_ISEL_FAST_RA:    # %eax, %edi, %ecx, %edx, %esi
; FAST_ISEL_FAST_RA:    #NO_APP
;
; GREEDY_RA-LABEL: test_mult_m_early_clobber_output_rm_input_pressure:
; GREEDY_RA:    #APP
; GREEDY_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; GREEDY_RA:    #NO_APP
; GREEDY_RA:    #APP
; GREEDY_RA:    # multiple m output, rm input: pressure
; GREEDY_RA:    # %r8d, %r9d, %eax, %esi, %edi
; GREEDY_RA:    #NO_APP
;
; FAST_RA-LABEL: test_mult_m_early_clobber_output_rm_input_pressure:
; FAST_RA:    #APP
; FAST_RA:    # %rax,%rcx,%rdx,%rsi,%rdi,%rbx,%rbp,%r8,%r9,%r10,%r11, %r12, %r13, %r14, %r15
; FAST_RA:    #NO_APP
; FAST_RA:    #APP
; FAST_RA:    # multiple m output, rm input: pressure
; FAST_RA:    # %eax, %edi, %ecx, %edx, %esi
; FAST_RA:    #NO_APP
entry:
  %0 = tail call { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } asm sideeffect "# $0,$1,$2,$3,$4,$5,$6,$7,$8,$9,$10, $11, $12, $13, $14", "={rax},={rcx},={rdx},={rsi},={rdi},={rbx},={rbp},={r8},={r9},={r10},={r11},={r12},={r13},={r14},={r15},~{dirflag},~{fpsr},~{flags}"()
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %b16 = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c17 = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d18 = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %1 = load i32, ptr %d18, align 4
  %e19 = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %2 = load i32, ptr %e19, align 4
  %3 = tail call { i32, i32, i32 } asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4", "=&rm,=&rm,=&rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(i32 %1, i32 %2)
  %asmresult20 = extractvalue { i32, i32, i32 } %3, 0
  %asmresult21 = extractvalue { i32, i32, i32 } %3, 1
  %asmresult22 = extractvalue { i32, i32, i32 } %3, 2
  store i32 %asmresult20, ptr %foo, align 4
  store i32 %asmresult21, ptr %b16, align 4
  store i32 %asmresult22, ptr %c17, align 4
  br label %asm.merge

asm.pref.mem:                                     ; preds = %entry
  %b = getelementptr inbounds nuw i8, ptr %foo, i64 4
  %c = getelementptr inbounds nuw i8, ptr %foo, i64 8
  %d = getelementptr inbounds nuw i8, ptr %foo, i64 12
  %4 = load i32, ptr %d, align 4
  %e = getelementptr inbounds nuw i8, ptr %foo, i64 16
  %5 = load i32, ptr %e, align 4
  tail call void asm sideeffect "# multiple m output, rm input: pressure\0A\09# $0, $1, $2, $3, $4", "=*&rm,=*&rm,=*&rm,rm,rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i32) %foo, ptr nonnull elementtype(i32) %b, ptr nonnull elementtype(i32) %c, i32 %4, i32 %5)
  br label %asm.merge

asm.merge:                                        ; preds = %asm.pref.reg, %asm.pref.mem
  %asmresult14 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 14
  %asmresult13 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 13
  %asmresult12 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 12
  %asmresult11 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 11
  %asmresult10 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 10
  %asmresult9 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 9
  %asmresult8 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 8
  %asmresult7 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 7
  %asmresult6 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 6
  %asmresult5 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 5
  %asmresult4 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 4
  %asmresult3 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 3
  %asmresult2 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 2
  %asmresult1 = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 1
  %asmresult = extractvalue { i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64, i64 } %0, 0
  tail call void @g(i64 noundef %asmresult, i64 noundef %asmresult1, i64 noundef %asmresult2, i64 noundef %asmresult3, i64 noundef %asmresult4, i64 noundef %asmresult5, i64 noundef %asmresult6, i64 noundef %asmresult7, i64 noundef %asmresult8, i64 noundef %asmresult9, i64 noundef %asmresult10, i64 noundef %asmresult11, i64 noundef %asmresult12, i64 noundef %asmresult13, i64 noundef %asmresult14)
  %6 = load i32, ptr %foo, align 4
  ret i32 %6
}

declare void @llvm.asm.constraint.br()

declare void @g(i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef, i64 noundef)
