; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; InstCombine folds icmp(binop(atomicrmw, C), 0) into a direct icmp on the
; old value, removing the intermediate arithmetic instruction.  The X86
; backend must recognise these folded forms in shouldExpandAtomicRMWInIR and
; emit a lock instruction + setcc rather than a cmpxchg loop.

; icmp eq (old & -2), 0  ->  icmp ult old, 2
define i1 @lock_and_sete_folded(ptr %0) nounwind {
; CHECK-LABEL: lock_and_sete_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock andq $-2, (%rdi)
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %2 = atomicrmw and ptr %0, i64 -2 seq_cst, align 8
  %3 = icmp ult i64 %2, 2
  ret i1 %3
}

; icmp ne (old & -2), 0  ->  icmp ugt old, 1
define i1 @lock_and_setne_folded(ptr %0) nounwind {
; CHECK-LABEL: lock_and_setne_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock andq $-2, (%rdi)
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    retq
  %2 = atomicrmw and ptr %0, i64 -2 seq_cst, align 8
  %3 = icmp ugt i64 %2, 1
  ret i1 %3
}

; icmp slt (old & -2), 0  ->  icmp slt old, 0  (C has sign bit; AND preserves it)
define i1 @lock_and_sets_folded(ptr %0) nounwind {
; CHECK-LABEL: lock_and_sets_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock andq $-2, (%rdi)
; CHECK-NEXT:    sets %al
; CHECK-NEXT:    retq
  %2 = atomicrmw and ptr %0, i64 -2 seq_cst, align 8
  %3 = icmp slt i64 %2, 0
  ret i1 %3
}

; icmp sgt (old & -2), -1  ->  icmp sgt old, -1  (C has sign bit; AND preserves it)
define i1 @lock_and_setns_folded(ptr %0) nounwind {
; CHECK-LABEL: lock_and_setns_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock andq $-2, (%rdi)
; CHECK-NEXT:    setns %al
; CHECK-NEXT:    retq
  %2 = atomicrmw and ptr %0, i64 -2 seq_cst, align 8
  %3 = icmp sgt i64 %2, -1
  ret i1 %3
}

; icmp slt (old ^ -2), 0  ->  icmp sgt old, -1  (XOR with -2 flips sign bit)
define i1 @lock_xor_sets_folded(ptr %0) nounwind {
; CHECK-LABEL: lock_xor_sets_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock xorq $-2, (%rdi)
; CHECK-NEXT:    sets %al
; CHECK-NEXT:    retq
  %2 = atomicrmw xor ptr %0, i64 -2 seq_cst, align 8
  %3 = icmp sgt i64 %2, -1
  ret i1 %3
}

; icmp sgt (old ^ -2), -1  ->  icmp slt old, 0  (XOR with -2 flips sign bit)
define i1 @lock_xor_setns_folded(ptr %0) nounwind {
; CHECK-LABEL: lock_xor_setns_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock xorq $-2, (%rdi)
; CHECK-NEXT:    setns %al
; CHECK-NEXT:    retq
  %2 = atomicrmw xor ptr %0, i64 -2 seq_cst, align 8
  %3 = icmp slt i64 %2, 0
  ret i1 %3
}

; Negative test: C = -3, so -C = 3 which is not a power of two.  The folded
; icmp ult old, 3 does not satisfy the power-of-two guard and must not be
; matched; a cmpxchg loop is emitted instead.
define i1 @lock_and_not_pow2(ptr %0) nounwind {
; CHECK-LABEL: lock_and_not_pow2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq (%rdi), %rax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB6_1: # %atomicrmw.start
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movq %rax, %rcx
; CHECK-NEXT:    andq $-3, %rcx
; CHECK-NEXT:    lock cmpxchgq %rcx, (%rdi)
; CHECK-NEXT:    jne .LBB6_1
; CHECK-NEXT:  # %bb.2: # %atomicrmw.end
; CHECK-NEXT:    cmpq $3, %rax
; CHECK-NEXT:    setb %al
; CHECK-NEXT:    retq
  %2 = atomicrmw and ptr %0, i64 -3 seq_cst, align 8
  %3 = icmp ult i64 %2, 3
  ret i1 %3
}
