; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; When InstCombine sees (atomicrmw and ptr, C) followed by a comparison of the
; result against zero, it can fold the intermediate 'and' away when -C is a
; power of two.  The algebraic equivalence:
;
;   (old & C) == 0  <=>  old ult -C  ->  ZF=1
;   (old & C) != 0  <=>  old ugt ~C  ->  ZF=0
;
; holds because C = ~(2^k - 1) means AND clears the bottom k bits, so the
; result is zero iff old < 2^k = -C.  The lock and instruction still sets ZF
; on (old & C), so no CAS loop is needed.

; (old & -2) != 0 -> icmp ugt old, 1 should fold
define i1 @lock_and_setne_folded(ptr %p) nounwind {
; CHECK-LABEL: lock_and_setne_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock andq $-2, (%rdi)
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    retq
  %old = atomicrmw and ptr %p, i64 -2 seq_cst
  %r = icmp ugt i64 %old, 1
  ret i1 %r
}

; (old & -2) == 0 -> icmp ult old, 2 should fold
define i1 @lock_and_sete_folded(ptr %p) nounwind {
; CHECK-LABEL: lock_and_sete_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock andq $-2, (%rdi)
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %old = atomicrmw and ptr %p, i64 -2 seq_cst
  %r = icmp ult i64 %old, 2
  ret i1 %r
}

; Different C: C=-4, -C=4=2^2. Fold holds for any k, not just k=1.
define i1 @lock_and_setne_folded_c4(ptr %p) nounwind {
; CHECK-LABEL: lock_and_setne_folded_c4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock andq $-4, (%rdi)
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    retq
  %old = atomicrmw and ptr %p, i64 -4 seq_cst
  %r = icmp ugt i64 %old, 3
  ret i1 %r
}

; Negative test: -C=3 is not a power of 2, lower to CAS loop.
define i1 @lock_and_setne_not_folded(ptr %p) nounwind {
; CHECK-LABEL: lock_and_setne_not_folded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq (%rdi), %rax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB3_1: # %atomicrmw.start
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movq %rax, %rcx
; CHECK-NEXT:    andq $-3, %rcx
; CHECK-NEXT:    lock cmpxchgq %rcx, (%rdi)
; CHECK-NEXT:    jne .LBB3_1
; CHECK-NEXT:  # %bb.2: # %atomicrmw.end
; CHECK-NEXT:    cmpq $3, %rax
; CHECK-NEXT:    setae %al
; CHECK-NEXT:    retq
  %old = atomicrmw and ptr %p, i64 -3 seq_cst
  %r = icmp ugt i64 %old, 2
  ret i1 %r
}
