; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mcpu=generic -mtriple=i686-- -mattr=+cmov,cx16 -verify-machineinstrs | FileCheck %s

target datalayout = "e-p:32:32:32-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:32:64-v64:64:64-v128:128:128-a0:0:64-f80:128:128"

define void @func(i32 %argc, ptr %argv) nounwind {
; CHECK-LABEL: func:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    pushl %ebx
; CHECK-NEXT:    andl $-8, %esp
; CHECK-NEXT:    subl $48, %esp
; CHECK-NEXT:    movl $0, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $31, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $3855, {{[0-9]+}}(%esp) # imm = 0xF0F
; CHECK-NEXT:    movl $3855, {{[0-9]+}}(%esp) # imm = 0xF0F
; CHECK-NEXT:    movl $3855, {{[0-9]+}}(%esp) # imm = 0xF0F
; CHECK-NEXT:    movl $4, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $4, %eax
; CHECK-NEXT:    lock xaddl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $-30, %eax
; CHECK-NEXT:    lock xaddl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    lock xaddl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $-1, %eax
; CHECK-NEXT:    lock xaddl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_1: # %atomicrmw.start68
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $4080, %ecx # imm = 0xFF0
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_1
; CHECK-NEXT:  # %bb.2: # %atomicrmw.end67
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_3: # %atomicrmw.start62
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    orl $4080, %ecx # imm = 0xFF0
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_3
; CHECK-NEXT:  # %bb.4: # %atomicrmw.end61
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_5: # %atomicrmw.start56
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    xorl $4080, %ecx # imm = 0xFF0
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_5
; CHECK-NEXT:  # %bb.6: # %atomicrmw.end55
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_7: # %atomicrmw.start50
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmpl $17, %eax
; CHECK-NEXT:    movl $16, %ecx
; CHECK-NEXT:    cmovll %eax, %ecx
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_7
; CHECK-NEXT:  # %bb.8: # %atomicrmw.end49
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    movl $-1, %ecx
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_9: # %atomicrmw.start44
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmpl %ecx, %eax
; CHECK-NEXT:    movl $-1, %edx
; CHECK-NEXT:    cmovlel %eax, %edx
; CHECK-NEXT:    lock cmpxchgl %edx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_9
; CHECK-NEXT:  # %bb.10: # %atomicrmw.end43
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_11: # %atomicrmw.start38
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    movl $1, %ecx
; CHECK-NEXT:    cmovgl %eax, %ecx
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_11
; CHECK-NEXT:  # %bb.12: # %atomicrmw.end37
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_13: # %atomicrmw.start32
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    movl $0, %ecx
; CHECK-NEXT:    cmovnsl %eax, %ecx
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_13
; CHECK-NEXT:  # %bb.14: # %atomicrmw.end31
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_15: # %atomicrmw.start26
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmpl $65536, %eax # imm = 0x10000
; CHECK-NEXT:    movl $65535, %ecx # imm = 0xFFFF
; CHECK-NEXT:    cmovael %eax, %ecx
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_15
; CHECK-NEXT:  # %bb.16: # %atomicrmw.end25
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_17: # %atomicrmw.start20
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmpl $11, %eax
; CHECK-NEXT:    movl $10, %ecx
; CHECK-NEXT:    cmovael %eax, %ecx
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_17
; CHECK-NEXT:  # %bb.18: # %atomicrmw.end19
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_19: # %atomicrmw.start14
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmpl $2, %eax
; CHECK-NEXT:    movl $1, %ecx
; CHECK-NEXT:    cmovbl %eax, %ecx
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_19
; CHECK-NEXT:  # %bb.20: # %atomicrmw.end13
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_21: # %atomicrmw.start8
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    cmpl $11, %eax
; CHECK-NEXT:    movl $10, %ecx
; CHECK-NEXT:    cmovbl %eax, %ecx
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_21
; CHECK-NEXT:  # %bb.22: # %atomicrmw.end7
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $1976, %eax # imm = 0x7B8
; CHECK-NEXT:    xchgl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $1, %ecx
; CHECK-NEXT:    movl $-10, %eax
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl $1976, %eax # imm = 0x7B8
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_23: # %atomicrmw.start2
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    notl %ecx
; CHECK-NEXT:    orl $-1402, %ecx # imm = 0xFA86
; CHECK-NEXT:    lock cmpxchgl %ecx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_23
; CHECK-NEXT:  # %bb.24: # %atomicrmw.end1
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %edx
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_25: # %atomicrmw.start
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movl %eax, %ebx
; CHECK-NEXT:    notl %ebx
; CHECK-NEXT:    orl $252645135, %ebx # imm = 0xF0F0F0F
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    notl %ecx
; CHECK-NEXT:    orl $252645135, %ecx # imm = 0xF0F0F0F
; CHECK-NEXT:    lock cmpxchg8b {{[0-9]+}}(%esp)
; CHECK-NEXT:    jne .LBB0_25
; CHECK-NEXT:  # %bb.26: # %atomicrmw.end
; CHECK-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; CHECK-NEXT:    leal -4(%ebp), %esp
; CHECK-NEXT:    popl %ebx
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    retl
entry:
	%argc.addr = alloca i32		; <ptr> [#uses=1]
	%argv.addr = alloca ptr		; <ptr> [#uses=1]
	%val1 = alloca i32		; <ptr> [#uses=2]
	%val2 = alloca i32		; <ptr> [#uses=15]
	%andt = alloca i32		; <ptr> [#uses=2]
	%ort = alloca i32		; <ptr> [#uses=2]
	%xort = alloca i32		; <ptr> [#uses=2]
	%old = alloca i32		; <ptr> [#uses=18]
	%temp = alloca i32		; <ptr> [#uses=2]
	%temp64 = alloca i64
	store i32 %argc, ptr %argc.addr
	store ptr %argv, ptr %argv.addr
	store i32 0, ptr %val1
	store i32 31, ptr %val2
	store i32 3855, ptr %andt
	store i32 3855, ptr %ort
	store i32 3855, ptr %xort
	store i32 4, ptr %temp
	%tmp = load i32, ptr %temp
  %0 = atomicrmw add ptr %val1, i32 %tmp monotonic
	store i32 %0, ptr %old
  %1 = atomicrmw sub ptr %val2, i32 30 monotonic
	store i32 %1, ptr %old
  %2 = atomicrmw add ptr %val2, i32 1 monotonic
	store i32 %2, ptr %old
  %3 = atomicrmw sub ptr %val2, i32 1 monotonic
	store i32 %3, ptr %old
  %4 = atomicrmw and ptr %andt, i32 4080 monotonic
	store i32 %4, ptr %old
  %5 = atomicrmw or ptr %ort, i32 4080 monotonic
	store i32 %5, ptr %old
  %6 = atomicrmw xor ptr %xort, i32 4080 monotonic
	store i32 %6, ptr %old
  %7 = atomicrmw min ptr %val2, i32 16 monotonic
	store i32 %7, ptr %old
	%neg = sub i32 0, 1		; <i32> [#uses=1]
  %8 = atomicrmw min ptr %val2, i32 %neg monotonic
	store i32 %8, ptr %old
  %9 = atomicrmw max ptr %val2, i32 1 monotonic
	store i32 %9, ptr %old
  %10 = atomicrmw max ptr %val2, i32 0 monotonic
	store i32 %10, ptr %old
  %11 = atomicrmw umax ptr %val2, i32 65535 monotonic
	store i32 %11, ptr %old
  %12 = atomicrmw umax ptr %val2, i32 10 monotonic
	store i32 %12, ptr %old
  %13 = atomicrmw umin ptr %val2, i32 1 monotonic
	store i32 %13, ptr %old
  %14 = atomicrmw umin ptr %val2, i32 10 monotonic
	store i32 %14, ptr %old
  %15 = atomicrmw xchg ptr %val2, i32 1976 monotonic
	store i32 %15, ptr %old
	%neg1 = sub i32 0, 10		; <i32> [#uses=1]
  %pair16 = cmpxchg ptr %val2, i32 %neg1, i32 1 monotonic monotonic
  %16 = extractvalue { i32, i1 } %pair16, 0
	store i32 %16, ptr %old
  %pair17 = cmpxchg ptr %val2, i32 1976, i32 1 monotonic monotonic
  %17 = extractvalue { i32, i1 } %pair17, 0
	store i32 %17, ptr %old
  %18 = atomicrmw nand ptr %val2, i32 1401 monotonic
  store i32 %18, ptr %old
  %19 = atomicrmw nand ptr %temp64, i64 17361641481138401520 monotonic
  store i64 %19, ptr %temp64
	ret void
}

define void @test2(ptr addrspace(256) nocapture %P) nounwind {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl $1, %ecx
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %edx
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    lock cmpxchgl %ecx, %gs:(%edx)
; CHECK-NEXT:    retl
entry:

  %pair0 = cmpxchg ptr addrspace(256) %P, i32 0, i32 1 monotonic monotonic
  %0 = extractvalue { i32, i1 } %pair0, 0
  ret void
}
