; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: opt < %s -O2 | llc -mtriple=x86_64-unknown-linux-gnu | FileCheck %s --check-prefixes=CHECK,X64
; RUN: opt < %s -O2 | llc -mtriple=i686-unknown-linux-gnu | FileCheck %s --check-prefixes=CHECK,X86

; Regression tests for single bit atomics instruction codegen
define i1 @or_check_bit0(ptr %v) nounwind {
; X64-LABEL: or_check_bit0:
; X64:       # %bb.0: # %entry
; X64-NEXT:    lock btsl $0, (%rdi)
; X64-NEXT:    setb %al
; X64-NEXT:    retq
;
; X86-LABEL: or_check_bit0:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    lock btsl $0, (%eax)
; X86-NEXT:    setb %al
; X86-NEXT:    retl
entry:
  %call = atomicrmw or ptr %v, i32 1 seq_cst, align 4
  %and = and i32 %call, 1
  %cmp = icmp eq i32 %and, 1
  ret i1 %cmp
}

define i1 @xor_check_bit0(ptr %v) nounwind {
; X64-LABEL: xor_check_bit0:
; X64:       # %bb.0: # %entry
; X64-NEXT:    lock btcl $0, (%rdi)
; X64-NEXT:    setb %al
; X64-NEXT:    retq
;
; X86-LABEL: xor_check_bit0:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    lock btcl $0, (%eax)
; X86-NEXT:    setb %al
; X86-NEXT:    retl
entry:
  %call = atomicrmw xor ptr %v, i32 1 seq_cst, align 4
  %and = and i32 %call, 1
  %cmp = icmp eq i32 %and, 1
  ret i1 %cmp
}

define i1 @and_check_bit0(ptr %v) nounwind {
; X64-LABEL: and_check_bit0:
; X64:       # %bb.0: # %entry
; X64-NEXT:    lock btrl $0, (%rdi)
; X64-NEXT:    setb %al
; X64-NEXT:    retq
;
; X86-LABEL: and_check_bit0:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    lock btrl $0, (%eax)
; X86-NEXT:    setb %al
; X86-NEXT:    retl
entry:
  %call = atomicrmw and ptr %v, i32 -2 seq_cst, align 4
  %and = and i32 %call, 1
  %cmp = icmp eq i32 %and, 1
  ret i1 %cmp
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
