; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mcpu=atom -mtriple=i686-linux | FileCheck %s
; CHECK: addl ({{%[a-z]+}},[[reg:%[a-z]+]],4)
; CHECK-NEXT: movl
; CHECK-NEXT: addl 4({{%[a-z]+}},[[reg:%[a-z]+]],4)
; CHECK-NEXT: incl

; Test for the FixupLEAs pre-emit pass.
; An LEA should NOT be substituted for the ADD instruction
; that increments the array pointer if it is greater than 5 instructions
; away from the memory reference that uses it.

; Original C code: clang -m32 -S -O2
;int test(int n, int * array, int * m, int * array2)
;{
;  int i, j = 0;
;  int sum = 0;
;  for (i = 0, j = 0; i < n;) {
;    ++i;
;    *m += array2[j++];
;    sum += array[i];
;  }
;  return sum;
;}

define i32 @test(i32 %n, ptr nocapture %array, ptr nocapture %k, ptr nocapture %l, ptr nocapture %m, ptr nocapture %array2) #0 {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    pushl %ebx
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    pushl %edi
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    .cfi_def_cfa_offset 20
; CHECK-NEXT:    .cfi_offset %esi, -20
; CHECK-NEXT:    .cfi_offset %edi, -16
; CHECK-NEXT:    .cfi_offset %ebx, -12
; CHECK-NEXT:    .cfi_offset %ebp, -8
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; CHECK-NEXT:    testl %ecx, %ecx
; CHECK-NEXT:    jle .LBB0_1
; CHECK-NEXT:  # %bb.2: # %for.body.lr.ph
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %esi
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %edx
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %edi
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    xorl %ebp, %ebp
; CHECK-NEXT:    movl (%esi), %ebx
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_3: # %for.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movl %ebx, (%esi)
; CHECK-NEXT:    addl (%edx,%ebp,4), %ebx
; CHECK-NEXT:    movl %ebx, (%esi)
; CHECK-NEXT:    addl 4(%edi,%ebp,4), %eax
; CHECK-NEXT:    leal 1(%ebp), %ebp
; CHECK-NEXT:    cmpl %ebp, %ecx
; CHECK-NEXT:    jne .LBB0_3
; CHECK-NEXT:    jmp .LBB0_4
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:  .LBB0_4: # %for.end
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popl %edi
; CHECK-NEXT:    .cfi_def_cfa_offset 12
; CHECK-NEXT:    popl %ebx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    .cfi_def_cfa_offset 4
; CHECK-NEXT:    retl
entry:
  %cmp7 = icmp sgt i32 %n, 0
  br i1 %cmp7, label %for.body.lr.ph, label %for.end

for.body.lr.ph:                                   ; preds = %entry
  %.pre = load i32, ptr %m, align 4
  br label %for.body

for.body:                                         ; preds = %for.body, %for.body.lr.ph
  %0 = phi i32 [ %.pre, %for.body.lr.ph ], [ %add, %for.body ]
  %sum.010 = phi i32 [ 0, %for.body.lr.ph ], [ %add3, %for.body ]
  %j.09 = phi i32 [ 0, %for.body.lr.ph ], [ %inc1, %for.body ]
  %inc1 = add nsw i32 %j.09, 1
  %arrayidx = getelementptr inbounds i32, ptr %array2, i32 %j.09
  store i32 %0, ptr %m, align 4
  store i32 %sum.010, ptr %m, align 4
  store i32 %0, ptr %m, align 4
  %1 = load i32, ptr %arrayidx, align 4
  %add = add nsw i32 %0, %1
  store i32 %add, ptr %m, align 4
  %arrayidx2 = getelementptr inbounds i32, ptr %array, i32 %inc1
  %2 = load i32, ptr %arrayidx2, align 4
  %add3 = add nsw i32 %2, %sum.010
  %exitcond = icmp eq i32 %inc1, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:                                          ; preds = %for.body, %entry
  %sum.0.lcssa = phi i32 [ 0, %entry ], [ %add3, %for.body ]
  ret i32 %sum.0.lcssa
}

