; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mtriple=i686-none-linux -verify-machineinstrs | FileCheck %s

define ptr @test_atomic_ptr_load(ptr %a0) {
; CHECK-LABEL: test_atomic_ptr_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    movl (%eax), %eax
; CHECK-NEXT:    retl
entry:
  %0 = load atomic ptr, ptr %a0 seq_cst, align 4
  ret ptr %0
}

define void @test_atomic_ptr_store(ptr %a0, ptr %a1) {
; CHECK-LABEL: test_atomic_ptr_store:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; CHECK-NEXT:    xchgl %ecx, (%eax)
; CHECK-NEXT:    retl
entry:
store atomic ptr %a0, ptr %a1 seq_cst, align 4
  ret void
}
