; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=instcombine -S %s | llc -mtriple=x86_64-unknown-linux-gnu | FileCheck %s

; fetch_add(-n) == n, unsigned: canonicalized to atomicrmw sub, enabling lock sub; sete
define i1 @fn_add(ptr %a, i64 %n) {
; CHECK-LABEL: fn_add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock subq %rsi, (%rdi)
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %neg = sub i64 0, %n
  %old = atomicrmw add ptr %a, i64 %neg monotonic, align 8
  %cmp = icmp eq i64 %old, %n
  ret i1 %cmp
}

; fetch_add(-n) == n, signed nsw: same win as unsigned
define i1 @fn_adds(ptr %a, i64 %n) {
; CHECK-LABEL: fn_adds:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock subq %rsi, (%rdi)
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %neg = sub nsw i64 0, %n
  %old = atomicrmw add ptr %a, i64 %neg monotonic, align 8
  %cmp = icmp eq i64 %old, %n
  ret i1 %cmp
}

; fetch_sub(-n), result discarded: canonicalized to atomicrmw add, enabling lock add
define void @fn_sub_neg(ptr %a, i64 %n) {
; CHECK-LABEL: fn_sub_neg:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock addq %rsi, (%rdi)
; CHECK-NEXT:    retq
  %neg = sub i64 0, %n
  atomicrmw sub ptr %a, i64 %neg monotonic, align 8
  ret void
}

; fetch_add(-10), with discarded result: canonicalized to atomicrmw sub with positive constant
define void @fn_add_neg_const(ptr %a) {
; CHECK-LABEL: fn_add_neg_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock subq $10, (%rdi)
; CHECK-NEXT:    retq
  atomicrmw add ptr %a, i64 -10 monotonic, align 8
  ret void
}

; fetch_sub(-10), with discarded result: canonicalized to atomicrmw add with positive constant
define void @fn_sub_neg_const(ptr %a) {
; CHECK-LABEL: fn_sub_neg_const:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lock addq $10, (%rdi)
; CHECK-NEXT:    retq
  atomicrmw sub ptr %a, i64 -10 monotonic, align 8
  ret void
}
