; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=x86_64-- -mattr=-fma < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK
; RUN: llc -mtriple=x86_64-- -mattr=+fma < %s \
; RUN:   | FileCheck %s --check-prefixes=CHECK-FMA

define dso_local double @x1(double noundef %a, double noundef %b, double noundef %c) local_unnamed_addr #0 {
; CHECK-LABEL: x1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mulsd %xmm1, %xmm0
; CHECK-NEXT:    subsd %xmm2, %xmm0
; CHECK-NEXT:    retq
;
; CHECK-FMA-LABEL: x1:
; CHECK-FMA:       # %bb.0: # %entry
; CHECK-FMA-NEXT:    vfnmadd213sd {{.*#+}} xmm0 = -(xmm1 * xmm0) + xmm2
; CHECK-FMA-NEXT:    retq
entry:
  %neg = fneg double %a
  %0 = tail call double @llvm.experimental.constrained.fmuladd.f64(double negated %neg, double %b, double %c, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret double %0
}
define dso_local double @x2(double noundef %a, double noundef %b, double noundef %c) local_unnamed_addr #0 {
; CHECK-LABEL: x2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    mulsd %xmm1, %xmm0
; CHECK-NEXT:    subsd %xmm2, %xmm0
; CHECK-NEXT:    retq
;
; CHECK-FMA-LABEL: x2:
; CHECK-FMA:       # %bb.0: # %entry
; CHECK-FMA-NEXT:    vfnmadd213sd {{.*#+}} xmm0 = -(xmm1 * xmm0) + xmm2
; CHECK-FMA-NEXT:    retq
entry:
  %neg = fneg double %b
  %0 = tail call double @llvm.experimental.constrained.fmuladd.f64(double %a, double negated %neg, double %c, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret double %0
}
define dso_local double @x3(double noundef %a, double noundef %b, double noundef %c) local_unnamed_addr #0 {
; CHECK-LABEL: x3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorpd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    mulsd %xmm1, %xmm0
; CHECK-NEXT:    addsd %xmm2, %xmm0
; CHECK-NEXT:    retq
;
; CHECK-FMA-LABEL: x3:
; CHECK-FMA:       # %bb.0: # %entry
; CHECK-FMA-NEXT:    vfnmadd213sd {{.*#+}} xmm0 = -(xmm1 * xmm0) + xmm2
; CHECK-FMA-NEXT:    retq
entry:
  %neg = fneg double %a
  %0 = tail call double @llvm.experimental.constrained.fmuladd.f64(double %neg, double %b, double %c, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret double %0
}
define dso_local double @x4(double noundef %a, double noundef %b, double noundef %c) local_unnamed_addr #0 {
; CHECK-LABEL: x4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorpd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    mulsd %xmm1, %xmm0
; CHECK-NEXT:    addsd %xmm2, %xmm0
; CHECK-NEXT:    retq
;
; CHECK-FMA-LABEL: x4:
; CHECK-FMA:       # %bb.0: # %entry
; CHECK-FMA-NEXT:    vfnmadd213sd {{.*#+}} xmm0 = -(xmm1 * xmm0) + xmm2
; CHECK-FMA-NEXT:    retq
entry:
  %neg = fneg double %b
  %0 = tail call double @llvm.experimental.constrained.fmuladd.f64(double %a, double %neg, double %c, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret double %0
}
