; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx512f | FileCheck %s

; Backend behavior for the AVX-512 packed add/sub/mul/div "_round" intrinsics
; with rounding-mode operand == 4 (_MM_FROUND_CUR_DIRECTION, "use current
; MXCSR").
;
; - With symbolic operands the intrinsic lowers to a plain vaddps that reads the
;   live MXCSR rounding mode at run time (correct), including under strictfp.
; - With constant operands in a non-strictfp function the SelectionDAG
;   constant-folds the result using round-to-nearest-even (0x3F800001 ==
;   1.00000012f). This is allowed under the default-FP-environment contract.
; - With constant operands in a strictfp function the lowering emits a strict
;   node, which is NOT constant-folded, so a real runtime vaddps is produced
;   that honors the live MXCSR rounding mode (no round-to-nearest value is
;   baked in).

declare <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float>, <16 x float>, i32)

define <16 x float> @add_ps_512_symbolic(<16 x float> %a, <16 x float> %b) {
; CHECK-LABEL: add_ps_512_symbolic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddps %zmm1, %zmm0, %zmm0
; CHECK-NEXT:    retq
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> %a, <16 x float> %b, i32 4)
  ret <16 x float> %r
}

define <16 x float> @add_ps_512_symbolic_strictfp(<16 x float> %a, <16 x float> %b) strictfp {
; CHECK-LABEL: add_ps_512_symbolic_strictfp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vaddps %zmm1, %zmm0, %zmm0
; CHECK-NEXT:    retq
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(<16 x float> %a, <16 x float> %b, i32 4) strictfp
  ret <16 x float> %r
}

define <16 x float> @add_ps_512_constant() {
; CHECK-LABEL: add_ps_512_constant:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vbroadcastss {{.*#+}} zmm0 = [1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0,1.00000012E+0]
; CHECK-NEXT:    retq
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(
        <16 x float> splat (float 1.0),
        <16 x float> splat (float 0x3E78000000000000),
        i32 4)
  ret <16 x float> %r
}

define <16 x float> @add_ps_512_constant_strictfp() strictfp {
; CHECK-LABEL: add_ps_512_constant_strictfp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vbroadcastss {{.*#+}} zmm0 = [1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0,1.0E+0]
; CHECK-NEXT:    vaddps {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm0, %zmm0
; CHECK-NEXT:    retq
  %r = call <16 x float> @llvm.x86.avx512.add.ps.512(
        <16 x float> splat (float 1.0),
        <16 x float> splat (float 0x3E78000000000000),
        i32 4) strictfp
  ret <16 x float> %r
}
