; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx512bmm,+avx512vl,+avx512bw --show-mc-encoding | FileCheck %s

; Test vbitrevb instruction generation from bitreverse intrinsic
; This test verifies that the bitreverse intrinsic generates vbitrevb instructions
; when AVX512BMM is available. This tests code converted from C (bitrev3.c).

; Test 512-bit vector bit reversal with aligned memory load
define <64 x i8> @bitrev_zmm_aligned_load(ptr %ptr) {
; CHECK-LABEL: bitrev_zmm_aligned_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb (%rdi), %zmm0 # encoding: [0x62,0xf6,0x7c,0x48,0x81,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = load <64 x i8>, ptr %ptr, align 64
  %1 = tail call <64 x i8> @llvm.bitreverse.v64i8(<64 x i8> %0)
  ret <64 x i8> %1
}

; Test 256-bit with aligned memory load (AVX512VL)
define <32 x i8> @bitrev_ymm_aligned_load(ptr %ptr) {
; CHECK-LABEL: bitrev_ymm_aligned_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb (%rdi), %ymm0 # encoding: [0x62,0xf6,0x7c,0x28,0x81,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = load <32 x i8>, ptr %ptr, align 32
  %1 = tail call <32 x i8> @llvm.bitreverse.v32i8(<32 x i8> %0)
  ret <32 x i8> %1
}

; Test 128-bit with aligned memory load (AVX512VL + AVX512BW)
define <16 x i8> @bitrev_xmm_aligned_load(ptr %ptr) {
; CHECK-LABEL: bitrev_xmm_aligned_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb (%rdi), %xmm0 # encoding: [0x62,0xf6,0x7c,0x08,0x81,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = load <16 x i8>, ptr %ptr, align 16
  %1 = tail call <16 x i8> @llvm.bitreverse.v16i8(<16 x i8> %0)
  ret <16 x i8> %1
}

; Test 512-bit with unaligned memory load
; Memory operand can be folded directly into vbitrevb (no alignment required)
define <64 x i8> @bitrev_zmm_unaligned_load(ptr %ptr) {
; CHECK-LABEL: bitrev_zmm_unaligned_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb (%rdi), %zmm0 # encoding: [0x62,0xf6,0x7c,0x48,0x81,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = load <64 x i8>, ptr %ptr, align 1
  %1 = tail call <64 x i8> @llvm.bitreverse.v64i8(<64 x i8> %0)
  ret <64 x i8> %1
}

; Test 256-bit with unaligned memory load
; Memory operand can be folded directly into vbitrevb (no alignment required)
define <32 x i8> @bitrev_ymm_unaligned_load(ptr %ptr) {
; CHECK-LABEL: bitrev_ymm_unaligned_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb (%rdi), %ymm0 # encoding: [0x62,0xf6,0x7c,0x28,0x81,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = load <32 x i8>, ptr %ptr, align 1
  %1 = tail call <32 x i8> @llvm.bitreverse.v32i8(<32 x i8> %0)
  ret <32 x i8> %1
}

; Test 128-bit with unaligned memory load
; Memory operand can be folded directly into vbitrevb (no alignment required)
define <16 x i8> @bitrev_xmm_unaligned_load(ptr %ptr) {
; CHECK-LABEL: bitrev_xmm_unaligned_load:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb (%rdi), %xmm0 # encoding: [0x62,0xf6,0x7c,0x08,0x81,0x07]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = load <16 x i8>, ptr %ptr, align 1
  %1 = tail call <16 x i8> @llvm.bitreverse.v16i8(<16 x i8> %0)
  ret <16 x i8> %1
}

declare <64 x i8> @llvm.bitreverse.v64i8(<64 x i8>)
declare <32 x i8> @llvm.bitreverse.v32i8(<32 x i8>)
declare <16 x i8> @llvm.bitreverse.v16i8(<16 x i8>)
