; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -O3 -mtriple=x86_64-linux-gnu -mcpu=c86-4g-m7 | FileCheck %s --check-prefixes=C864GM7-DEFAULT
; RUN: llc < %s -O3 -mtriple=x86_64-linux-gnu -mcpu=c86-4g-m7 -x86-split-gather-intrinsics | FileCheck %s --check-prefixes=C864GM7-DEFAULT-OPT

declare <16 x float>  @llvm.x86.avx512.mask.gather.dps.512(<16 x float>,  ptr, <16 x i32>, <16 x i1>, i32)
declare <8 x double>  @llvm.x86.avx512.mask.gather.dpd.512(<8 x double>,  ptr, <8 x i32>,  <8 x i1>,  i32)
declare <8 x float>   @llvm.x86.avx512.mask.gather.qps.512(<8 x float>,   ptr, <8 x i64>,  <8 x i1>,  i32)
declare <8 x double>  @llvm.x86.avx512.mask.gather.qpd.512(<8 x double>,  ptr, <8 x i64>,  <8 x i1>,  i32)
declare <16 x i32>    @llvm.x86.avx512.mask.gather.dpi.512(<16 x i32>,    ptr, <16 x i32>, <16 x i1>, i32)
declare <8 x i64>     @llvm.x86.avx512.mask.gather.dpq.512(<8 x i64>,     ptr, <8 x i32>,  <8 x i1>,  i32)
declare <8 x i32>     @llvm.x86.avx512.mask.gather.qpi.512(<8 x i32>,     ptr, <8 x i64>,  <8 x i1>,  i32)
declare <8 x i64>     @llvm.x86.avx512.mask.gather.qpq.512(<8 x i64>,     ptr, <8 x i64>,  <8 x i1>,  i32)

; Case 1: v16f32 (dps) all-ones-mask
define void @opt_v16f32_dps(ptr %base, <16 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: opt_v16f32_dps:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorw %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vgatherdps (%rdi,%zmm0,4), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovaps %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: opt_v16f32_dps:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    vextracti32x4 $3, %zmm0, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vmovd %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovss {{.*#+}} xmm2 = mem[0],zero,zero,zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $1, %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0],mem[0],xmm2[2,3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $2, %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm2 = xmm2[0,1],mem[0],xmm2[3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $3, %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm1 = xmm2[0,1,2],mem[0]
; C864GM7-DEFAULT-OPT-NEXT:    vextracti32x4 $2, %zmm0, %xmm2
; C864GM7-DEFAULT-OPT-NEXT:    vmovd %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovss {{.*#+}} xmm3 = mem[0],zero,zero,zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $1, %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm3 = xmm3[0],mem[0],xmm3[2,3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $2, %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm3 = xmm3[0,1],mem[0],xmm3[3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $3, %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm2 = xmm3[0,1,2],mem[0]
; C864GM7-DEFAULT-OPT-NEXT:    vinsertf128 $1, %xmm1, %ymm2, %ymm1
; C864GM7-DEFAULT-OPT-NEXT:    vextracti128 $1, %ymm0, %xmm2
; C864GM7-DEFAULT-OPT-NEXT:    vmovd %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovss {{.*#+}} xmm3 = mem[0],zero,zero,zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $1, %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm3 = xmm3[0],mem[0],xmm3[2,3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $2, %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm3 = xmm3[0,1],mem[0],xmm3[3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $3, %xmm2, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm2 = xmm3[0,1,2],mem[0]
; C864GM7-DEFAULT-OPT-NEXT:    vmovd %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovss {{.*#+}} xmm3 = mem[0],zero,zero,zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $1, %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm3 = xmm3[0],mem[0],xmm3[2,3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $2, %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm3 = xmm3[0,1],mem[0],xmm3[3]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $3, %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertps {{.*#+}} xmm0 = xmm3[0,1,2],mem[0]
; C864GM7-DEFAULT-OPT-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; C864GM7-DEFAULT-OPT-NEXT:    vinsertf64x4 $1, %ymm1, %zmm0, %zmm0
; C864GM7-DEFAULT-OPT-NEXT:    vmovaps %zmm0, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <16 x float> @llvm.x86.avx512.mask.gather.dps.512(
            <16 x float> undef,
            ptr %base,
            <16 x i32> %idx,
            <16 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1,
                       i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 4)
  store <16 x float> %res, ptr %out
  ret void
}

; Case 2: v8f64 (dpd) all-ones-mask
define void @opt_v8f64_dpd(ptr %base, <8 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: opt_v8f64_dpd:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vgatherdpd (%rdi,%ymm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovapd %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: opt_v8f64_dpd:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    vextracti128 $1, %ymm0, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $2, %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovsd {{.*#+}} xmm2 = mem[0],zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $3, %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovhps {{.*#+}} xmm2 = xmm2[0,1],mem[0,1]
; C864GM7-DEFAULT-OPT-NEXT:    vmovd %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovsd {{.*#+}} xmm3 = mem[0],zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $1, %xmm1, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovhps {{.*#+}} xmm1 = xmm3[0,1],mem[0,1]
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $2, %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vinsertf128 $1, %xmm2, %ymm1, %ymm1
; C864GM7-DEFAULT-OPT-NEXT:    vmovsd {{.*#+}} xmm2 = mem[0],zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $3, %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovhps {{.*#+}} xmm2 = xmm2[0,1],mem[0,1]
; C864GM7-DEFAULT-OPT-NEXT:    vmovd %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovsd {{.*#+}} xmm3 = mem[0],zero
; C864GM7-DEFAULT-OPT-NEXT:    vpextrd $1, %xmm0, %eax
; C864GM7-DEFAULT-OPT-NEXT:    vmovhps {{.*#+}} xmm0 = xmm3[0,1],mem[0,1]
; C864GM7-DEFAULT-OPT-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; C864GM7-DEFAULT-OPT-NEXT:    vinsertf64x4 $1, %ymm1, %zmm0, %zmm0
; C864GM7-DEFAULT-OPT-NEXT:    vmovaps %zmm0, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x double> @llvm.x86.avx512.mask.gather.dpd.512(
            <8 x double> undef,
            ptr %base,
            <8 x i32> %idx,
            <8 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 8)
  store <8 x double> %res, ptr %out
  ret void
}

; Case 3: v8f32 (qps) all-ones-mask
define void @opt_v8f32_qps(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: opt_v8f32_qps:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vgatherqps (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovaps %ymm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: opt_v8f32_qps:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vgatherqps (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovaps %ymm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x float> @llvm.x86.avx512.mask.gather.qps.512(
            <8 x float> undef,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 4)
  store <8 x float> %res, ptr %out
  ret void
}

; Case 4: v8f64 (qpd) all-ones-mask
define void @opt_v8f64_qpd(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: opt_v8f64_qpd:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vgatherqpd (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovapd %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: opt_v8f64_qpd:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vgatherqpd (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovapd %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x double> @llvm.x86.avx512.mask.gather.qpd.512(
            <8 x double> undef,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 8)
  store <8 x double> %res, ptr %out
  ret void
}

; Case 5: v16f32 (dps) zero-mask
define void @fallback_v16f32_dps_masked(ptr %base, <16 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v16f32_dps_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movw $21845, %ax # imm = 0x5555
; C864GM7-DEFAULT-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vgatherdps (%rdi,%zmm0,4), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovaps %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v16f32_dps_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movw $21845, %ax # imm = 0x5555
; C864GM7-DEFAULT-OPT-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vgatherdps (%rdi,%zmm0,4), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovaps %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <16 x float> @llvm.x86.avx512.mask.gather.dps.512(
            <16 x float> zeroinitializer,
            ptr %base,
            <16 x i32> %idx,
            <16 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0,
                       i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 4)
  store <16 x float> %res, ptr %out
  ret void
}

; Case 6: v8f64 (dpd) zero-mask
define void @fallback_v8f64_dpd_masked(ptr %base, <8 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8f64_dpd_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vgatherdpd (%rdi,%ymm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovapd %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8f64_dpd_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-OPT-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vgatherdpd (%rdi,%ymm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovapd %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x double> @llvm.x86.avx512.mask.gather.dpd.512(
            <8 x double> zeroinitializer,
            ptr %base,
            <8 x i32> %idx,
            <8 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 8)
  store <8 x double> %res, ptr %out
  ret void
}

; Case 7: v8f32 (qps) zero-mask
define void @fallback_v8f32_qps_masked(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8f32_qps_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vgatherqps (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovaps %ymm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8f32_qps_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-OPT-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vgatherqps (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovaps %ymm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x float> @llvm.x86.avx512.mask.gather.qps.512(
            <8 x float> zeroinitializer,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 4)
  store <8 x float> %res, ptr %out
  ret void
}

; Case 8: v8f64 (qpd) zero-mask
define void @fallback_v8f64_qpd_masked(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8f64_qpd_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vgatherqpd (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovapd %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8f64_qpd_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-OPT-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vgatherqpd (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovapd %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x double> @llvm.x86.avx512.mask.gather.qpd.512(
            <8 x double> zeroinitializer,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 8)
  store <8 x double> %res, ptr %out
  ret void
}

; Case 9: v16i32 (dpi) all-ones-mask
define void @fallback_v16i32_dpi(ptr %base, <16 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v16i32_dpi:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorw %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vpgatherdd (%rdi,%zmm0,4), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v16i32_dpi:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    kxnorw %k0, %k0, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherdd (%rdi,%zmm0,4), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <16 x i32> @llvm.x86.avx512.mask.gather.dpi.512(
            <16 x i32> undef,
            ptr %base,
            <16 x i32> %idx,
            <16 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1,
                       i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 4)
  store <16 x i32> %res, ptr %out
  ret void
}

; Case 10: v16i32 (dpi) zero-mask
define void @fallback_v16i32_dpi_masked(ptr %base, <16 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v16i32_dpi_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movw $21845, %ax # imm = 0x5555
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vpgatherdd (%rdi,%zmm0,4), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v16i32_dpi_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movw $21845, %ax # imm = 0x5555
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherdd (%rdi,%zmm0,4), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <16 x i32> @llvm.x86.avx512.mask.gather.dpi.512(
            <16 x i32> zeroinitializer,
            ptr %base,
            <16 x i32> %idx,
            <16 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0,
                       i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 4)
  store <16 x i32> %res, ptr %out
  ret void
}

; Case 11: v8i64 (dpq) all-ones-mask
define void @fallback_v8i64_dpq(ptr %base, <8 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8i64_dpq:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vpgatherdq (%rdi,%ymm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8i64_dpq:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherdq (%rdi,%ymm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x i64> @llvm.x86.avx512.mask.gather.dpq.512(
            <8 x i64> undef,
            ptr %base,
            <8 x i32> %idx,
            <8 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 8)
  store <8 x i64> %res, ptr %out
  ret void
}

; Case 12: v8i64 (dpq) zero-mask
define void @fallback_v8i64_dpq_masked(ptr %base, <8 x i32> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8i64_dpq_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vpgatherdq (%rdi,%ymm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8i64_dpq_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherdq (%rdi,%ymm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x i64> @llvm.x86.avx512.mask.gather.dpq.512(
            <8 x i64> zeroinitializer,
            ptr %base,
            <8 x i32> %idx,
            <8 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 8)
  store <8 x i64> %res, ptr %out
  ret void
}

; Case 13: v8i32 (qpi) all-ones-mask
define void @fallback_v8i32_qpi(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8i32_qpi:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vpgatherqd (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa %ymm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8i32_qpi:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherqd (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa %ymm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x i32> @llvm.x86.avx512.mask.gather.qpi.512(
            <8 x i32> undef,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 4)
  store <8 x i32> %res, ptr %out
  ret void
}

; Case 14: v8i32 (qpi) zero-mask
define void @fallback_v8i32_qpi_masked(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8i32_qpi_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vpgatherqd (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa %ymm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8i32_qpi_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherqd (%rdi,%zmm0,4), %ymm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa %ymm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x i32> @llvm.x86.avx512.mask.gather.qpi.512(
            <8 x i32> zeroinitializer,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 4)
  store <8 x i32> %res, ptr %out
  ret void
}

; Case 15: v8i64 (qpq) all-ones-mask
define void @fallback_v8i64_qpq(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8i64_qpq:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    vpgatherqq (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8i64_qpq:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    kxnorb %k0, %k0, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherqq (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x i64> @llvm.x86.avx512.mask.gather.qpq.512(
            <8 x i64> undef,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1, i1 1>,
            i32 8)
  store <8 x i64> %res, ptr %out
  ret void
}

; Case 16: v8i64 (qpq) zero-mask
define void @fallback_v8i64_qpq_masked(ptr %base, <8 x i64> %idx, ptr %out) {
; C864GM7-DEFAULT-LABEL: fallback_v8i64_qpq_masked:
; C864GM7-DEFAULT:       # %bb.0:
; C864GM7-DEFAULT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-NEXT:    vpgatherqq (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-NEXT:    vzeroupper
; C864GM7-DEFAULT-NEXT:    retq
;
; C864GM7-DEFAULT-OPT-LABEL: fallback_v8i64_qpq_masked:
; C864GM7-DEFAULT-OPT:       # %bb.0:
; C864GM7-DEFAULT-OPT-NEXT:    movb $85, %al
; C864GM7-DEFAULT-OPT-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; C864GM7-DEFAULT-OPT-NEXT:    kmovd %eax, %k1
; C864GM7-DEFAULT-OPT-NEXT:    vpgatherqq (%rdi,%zmm0,8), %zmm1 {%k1}
; C864GM7-DEFAULT-OPT-NEXT:    vmovdqa64 %zmm1, (%rsi)
; C864GM7-DEFAULT-OPT-NEXT:    vzeroupper
; C864GM7-DEFAULT-OPT-NEXT:    retq
  %res = call <8 x i64> @llvm.x86.avx512.mask.gather.qpq.512(
            <8 x i64> zeroinitializer,
            ptr %base,
            <8 x i64> %idx,
            <8 x i1> <i1 1, i1 0, i1 1, i1 0, i1 1, i1 0, i1 1, i1 0>,
            i32 8)
  store <8 x i64> %res, ptr %out
  ret void
}
