; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512bmm,+avx512vl --show-mc-encoding | FileCheck %s

define <2 x i64> @test_mm128_vbitrev_epi8(<2 x i64> %a) {
; CHECK-LABEL: test_mm128_vbitrev_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb %xmm0, %xmm0 # encoding: [0x62,0xf6,0x7c,0x08,0x81,0xc0]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = bitcast <2 x i64> %a to <16 x i8>
  %1 = tail call <16 x i8> @llvm.bitreverse.v16i8(<16 x i8> %0)
  %2 = bitcast <16 x i8> %1 to <2 x i64>
  ret <2 x i64> %2
}

define <4 x i64> @test_mm256_vbitrev_epi8(<4 x i64> %a) {
; CHECK-LABEL: test_mm256_vbitrev_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb %ymm0, %ymm0 # encoding: [0x62,0xf6,0x7c,0x28,0x81,0xc0]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = bitcast <4 x i64> %a to <32 x i8>
  %1 = tail call <32 x i8> @llvm.bitreverse.v32i8(<32 x i8> %0)
  %2 = bitcast <32 x i8> %1 to <4 x i64>
  ret <4 x i64> %2
}

define <8 x i64> @test_mm512_vbitrev_epi8(<8 x i64> %a) {
; CHECK-LABEL: test_mm512_vbitrev_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vbitrevb %zmm0, %zmm0 # encoding: [0x62,0xf6,0x7c,0x48,0x81,0xc0]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = bitcast <8 x i64> %a to <64 x i8>
  %1 = tail call <64 x i8> @llvm.bitreverse.v64i8(<64 x i8> %0)
  %2 = bitcast <64 x i8> %1 to <8 x i64>
  ret <8 x i64> %2
}

define <4 x float> @test_mm128_mask_vbitrevb_epi8(<2 x i64> %a, i64 %mask, <2 x i64> %b) {
; CHECK-LABEL: test_mm128_mask_vbitrevb_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmovd %edi, %k1 # encoding: [0xc5,0xfb,0x92,0xcf]
; CHECK-NEXT:    vbitrevb %xmm1, %xmm0 {%k1} # encoding: [0x62,0xf6,0x7c,0x09,0x81,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %conv = trunc i64 %mask to i16
  %0 = bitcast <2 x i64> %b to <16 x i8>
  %1 = tail call <16 x i8> @llvm.bitreverse.v16i8(<16 x i8> %0)
  %2 = bitcast <2 x i64> %a to <16 x i8>
  %3 = bitcast i16 %conv to <16 x i1>
  %4 = select <16 x i1> %3, <16 x i8> %1, <16 x i8> %2
  %5 = bitcast <16 x i8> %4 to <4 x float>
  ret <4 x float> %5
}

define <8 x float> @test_mm256_mask_vbitrevb_epi8(<4 x i64> %a, i64 %mask, <4 x i64> %b) {
; CHECK-LABEL: test_mm256_mask_vbitrevb_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmovd %edi, %k1 # encoding: [0xc5,0xfb,0x92,0xcf]
; CHECK-NEXT:    vbitrevb %ymm1, %ymm0 {%k1} # encoding: [0x62,0xf6,0x7c,0x29,0x81,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %conv = trunc i64 %mask to i32
  %0 = bitcast <4 x i64> %b to <32 x i8>
  %1 = tail call <32 x i8> @llvm.bitreverse.v32i8(<32 x i8> %0)
  %2 = bitcast <4 x i64> %a to <32 x i8>
  %3 = bitcast i32 %conv to <32 x i1>
  %4 = select <32 x i1> %3, <32 x i8> %1, <32 x i8> %2
  %5 = bitcast <32 x i8> %4 to <8 x float>
  ret <8 x float> %5
}

define <8 x i64> @test_mm512_mask_vbitrevb_epi8(<8 x i64> %a, i64 %mask, <8 x i64> %b) {
; CHECK-LABEL: test_mm512_mask_vbitrevb_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmovq %rdi, %k1 # encoding: [0xc4,0xe1,0xfb,0x92,0xcf]
; CHECK-NEXT:    vbitrevb %zmm1, %zmm0 {%k1} # encoding: [0x62,0xf6,0x7c,0x49,0x81,0xc1]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = bitcast <8 x i64> %b to <64 x i8>
  %1 = tail call <64 x i8> @llvm.bitreverse.v64i8(<64 x i8> %0)
  %2 = bitcast <8 x i64> %a to <64 x i8>
  %3 = bitcast i64 %mask to <64 x i1>
  %4 = select <64 x i1> %3, <64 x i8> %1, <64 x i8> %2
  %5 = bitcast <64 x i8> %4 to <8 x i64>
  ret <8 x i64> %5
}

define <4 x float> @test_mm128_maskz_vbitrevb_epi8(i64 %mask, <2 x i64> %b) {
; CHECK-LABEL: test_mm128_maskz_vbitrevb_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmovd %edi, %k1 # encoding: [0xc5,0xfb,0x92,0xcf]
; CHECK-NEXT:    vbitrevb %xmm0, %xmm0 {%k1} {z} # encoding: [0x62,0xf6,0x7c,0x89,0x81,0xc0]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %conv = trunc i64 %mask to i16
  %0 = bitcast <2 x i64> %b to <16 x i8>
  %1 = tail call <16 x i8> @llvm.bitreverse.v16i8(<16 x i8> %0)
  %2 = bitcast i16 %conv to <16 x i1>
  %3 = select <16 x i1> %2, <16 x i8> %1, <16 x i8> zeroinitializer
  %4 = bitcast <16 x i8> %3 to <4 x float>
  ret <4 x float> %4
}

define <8 x float> @test_mm256_maskz_vbitrevb_epi8(i64 %mask, <4 x i64> %b) {
; CHECK-LABEL: test_mm256_maskz_vbitrevb_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmovd %edi, %k1 # encoding: [0xc5,0xfb,0x92,0xcf]
; CHECK-NEXT:    vbitrevb %ymm0, %ymm0 {%k1} {z} # encoding: [0x62,0xf6,0x7c,0xa9,0x81,0xc0]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %conv = trunc i64 %mask to i32
  %0 = bitcast <4 x i64> %b to <32 x i8>
  %1 = tail call <32 x i8> @llvm.bitreverse.v32i8(<32 x i8> %0)
  %2 = bitcast i32 %conv to <32 x i1>
  %3 = select <32 x i1> %2, <32 x i8> %1, <32 x i8> zeroinitializer
  %4 = bitcast <32 x i8> %3 to <8 x float>
  ret <8 x float> %4
}

define <8 x i64> @test_mm512_maskz_vbitrevb_epi8(i64 %mask, <8 x i64> %b) {
; CHECK-LABEL: test_mm512_maskz_vbitrevb_epi8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    kmovq %rdi, %k1 # encoding: [0xc4,0xe1,0xfb,0x92,0xcf]
; CHECK-NEXT:    vbitrevb %zmm0, %zmm0 {%k1} {z} # encoding: [0x62,0xf6,0x7c,0xc9,0x81,0xc0]
; CHECK-NEXT:    retq # encoding: [0xc3]
entry:
  %0 = bitcast <8 x i64> %b to <64 x i8>
  %1 = tail call <64 x i8> @llvm.bitreverse.v64i8(<64 x i8> %0)
  %2 = bitcast i64 %mask to <64 x i1>
  %3 = select <64 x i1> %2, <64 x i8> %1, <64 x i8> zeroinitializer
  %4 = bitcast <64 x i8> %3 to <8 x i64>
  ret <8 x i64> %4
}

declare <16 x i8> @llvm.bitreverse.v16i8(<16 x i8>)
declare <32 x i8> @llvm.bitreverse.v32i8(<32 x i8>)
declare <64 x i8> @llvm.bitreverse.v64i8(<64 x i8>)
