; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-- -mattr=+bmi2 | FileCheck %s --check-prefix=BMI2
; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s --check-prefix=NOBMI2

define i8 @bext_i8(i8 %val, i8 %mask) nounwind {
; BMI2-LABEL: bext_i8:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movzbl %sil, %eax
; BMI2-NEXT:    movzbl %dil, %ecx
; BMI2-NEXT:    pextl %eax, %ecx, %eax
; BMI2-NEXT:    # kill: def $al killed $al killed $eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i8:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl %esi, %ecx
; NOBMI2-NEXT:    notb %cl
; NOBMI2-NEXT:    leal (,%rcx,4), %edx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorb %al, %dl
; NOBMI2-NEXT:    leal (,%rcx,8), %r8d
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shlb $4, %r9b
; NOBMI2-NEXT:    xorb %r8b, %r9b
; NOBMI2-NEXT:    xorb %dl, %r9b
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shlb $5, %dl
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shlb $6, %r8b
; NOBMI2-NEXT:    xorb %dl, %r8b
; NOBMI2-NEXT:    shlb $7, %cl
; NOBMI2-NEXT:    xorb %r8b, %cl
; NOBMI2-NEXT:    xorb %r9b, %cl
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    andb %sil, %dl
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %edi, %r8d
; NOBMI2-NEXT:    andb %dl, %r8b
; NOBMI2-NEXT:    xorb %r8b, %dil
; NOBMI2-NEXT:    shrb %r8b
; NOBMI2-NEXT:    orb %dil, %r8b
; NOBMI2-NEXT:    xorb %dl, %sil
; NOBMI2-NEXT:    shrb %dl
; NOBMI2-NEXT:    orb %sil, %dl
; NOBMI2-NEXT:    notb %cl
; NOBMI2-NEXT:    andb %al, %cl
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorb %cl, %al
; NOBMI2-NEXT:    leal (,%rcx,4), %esi
; NOBMI2-NEXT:    leal (,%rcx,8), %edi
; NOBMI2-NEXT:    xorb %sil, %dil
; NOBMI2-NEXT:    xorb %al, %dil
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shlb $4, %al
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shlb $5, %r9b
; NOBMI2-NEXT:    xorb %al, %r9b
; NOBMI2-NEXT:    movl %ecx, %esi
; NOBMI2-NEXT:    shlb $6, %sil
; NOBMI2-NEXT:    xorb %r9b, %sil
; NOBMI2-NEXT:    xorb %dil, %sil
; NOBMI2-NEXT:    movl %esi, %eax
; NOBMI2-NEXT:    andb %dl, %al
; NOBMI2-NEXT:    movl %r8d, %edi
; NOBMI2-NEXT:    andb %al, %dil
; NOBMI2-NEXT:    xorb %dil, %r8b
; NOBMI2-NEXT:    shrb $2, %dil
; NOBMI2-NEXT:    orb %r8b, %dil
; NOBMI2-NEXT:    xorb %al, %dl
; NOBMI2-NEXT:    shrb $2, %al
; NOBMI2-NEXT:    orb %dl, %al
; NOBMI2-NEXT:    notb %sil
; NOBMI2-NEXT:    andb %cl, %sil
; NOBMI2-NEXT:    leal (%rsi,%rsi), %ecx
; NOBMI2-NEXT:    xorb %sil, %cl
; NOBMI2-NEXT:    leal (,%rsi,4), %edx
; NOBMI2-NEXT:    leal (,%rsi,8), %r8d
; NOBMI2-NEXT:    xorb %dl, %r8b
; NOBMI2-NEXT:    xorb %cl, %r8b
; NOBMI2-NEXT:    movl %esi, %ecx
; NOBMI2-NEXT:    shlb $4, %cl
; NOBMI2-NEXT:    movl %esi, %edx
; NOBMI2-NEXT:    shlb $5, %dl
; NOBMI2-NEXT:    xorb %cl, %dl
; NOBMI2-NEXT:    shlb $6, %sil
; NOBMI2-NEXT:    xorb %dl, %sil
; NOBMI2-NEXT:    xorb %r8b, %sil
; NOBMI2-NEXT:    andb %dil, %al
; NOBMI2-NEXT:    andb %sil, %al
; NOBMI2-NEXT:    xorb %al, %dil
; NOBMI2-NEXT:    shrb $4, %al
; NOBMI2-NEXT:    orb %dil, %al
; NOBMI2-NEXT:    retq
  %res = call i8 @llvm.bext.i8(i8 %val, i8 %mask)
  ret i8 %res
}

define i16 @bext_i16(i16 %val, i16 %mask) nounwind {
; BMI2-LABEL: bext_i16:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movzwl %si, %eax
; BMI2-NEXT:    movzwl %di, %ecx
; BMI2-NEXT:    pextl %eax, %ecx, %eax
; BMI2-NEXT:    # kill: def $ax killed $ax killed $eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i16:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    pushq %rbx
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %esi, %eax
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    leal (,%rax,4), %edx
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    leal (,%rax,8), %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $4, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $11, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $14, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    shll $15, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    xorl %r9d, %eax
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    andl %esi, %r8d
; NOBMI2-NEXT:    movl %edi, %edx
; NOBMI2-NEXT:    andl %r8d, %edx
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movzwl %dx, %edx
; NOBMI2-NEXT:    shrl %edx
; NOBMI2-NEXT:    orl %edi, %edx
; NOBMI2-NEXT:    xorl %r8d, %esi
; NOBMI2-NEXT:    movzwl %r8w, %edi
; NOBMI2-NEXT:    shrl %edi
; NOBMI2-NEXT:    orl %esi, %edi
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rax,4), %esi
; NOBMI2-NEXT:    leal (,%rax,8), %r8d
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $4, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $5, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $6, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $7, %esi
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $9, %esi
; NOBMI2-NEXT:    xorl %r8d, %esi
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $11, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $12, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $13, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $14, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    andl %edi, %r8d
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    andl %r8d, %esi
; NOBMI2-NEXT:    xorl %esi, %edx
; NOBMI2-NEXT:    movzwl %si, %esi
; NOBMI2-NEXT:    shrl $2, %esi
; NOBMI2-NEXT:    orl %edx, %esi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movzwl %r8w, %edx
; NOBMI2-NEXT:    shrl $2, %edx
; NOBMI2-NEXT:    orl %edi, %edx
; NOBMI2-NEXT:    notl %ecx
; NOBMI2-NEXT:    andl %eax, %ecx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    leal (,%rcx,4), %edi
; NOBMI2-NEXT:    leal (,%rcx,8), %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $5, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %edi, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $7, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $9, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $12, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shll $13, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $14, %eax
; NOBMI2-NEXT:    xorl %r9d, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    andl %edx, %r8d
; NOBMI2-NEXT:    movl %esi, %edi
; NOBMI2-NEXT:    andl %r8d, %edi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movzwl %di, %edi
; NOBMI2-NEXT:    shrl $4, %edi
; NOBMI2-NEXT:    orl %esi, %edi
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movzwl %r8w, %ebx
; NOBMI2-NEXT:    shrl $4, %ebx
; NOBMI2-NEXT:    orl %edx, %ebx
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rax,4), %edx
; NOBMI2-NEXT:    leal (,%rax,8), %esi
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $4, %ecx
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $6, %ecx
; NOBMI2-NEXT:    xorl %edx, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $8, %esi
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $9, %edx
; NOBMI2-NEXT:    xorl %esi, %edx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $10, %esi
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $11, %ecx
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $13, %ecx
; NOBMI2-NEXT:    xorl %edx, %ecx
; NOBMI2-NEXT:    shll $14, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    xorl %esi, %eax
; NOBMI2-NEXT:    andl %edi, %ebx
; NOBMI2-NEXT:    andl %eax, %ebx
; NOBMI2-NEXT:    xorl %ebx, %edi
; NOBMI2-NEXT:    movzbl %bh, %eax
; NOBMI2-NEXT:    orl %edi, %eax
; NOBMI2-NEXT:    # kill: def $ax killed $ax killed $eax
; NOBMI2-NEXT:    popq %rbx
; NOBMI2-NEXT:    retq
  %res = call i16 @llvm.bext.i16(i16 %val, i16 %mask)
  ret i16 %res
}

define i32 @bext_i32(i32 %val, i32 %mask) nounwind {
; BMI2-LABEL: bext_i32:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pextl %esi, %edi, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i32:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %esi, %eax
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    leal (,%rax,4), %edx
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    leal (,%rax,8), %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $4, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $11, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $14, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $15, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %r10d
; NOBMI2-NEXT:    shll $16, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %r9d, %r10d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $17, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $18, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $19, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $20, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $21, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $22, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    xorl %r10d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $23, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $24, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $25, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $26, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $27, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $28, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $29, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $30, %edx
; NOBMI2-NEXT:    shll $31, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    andl %esi, %edx
; NOBMI2-NEXT:    movl %edi, %r8d
; NOBMI2-NEXT:    andl %edx, %r8d
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    shrl %r8d
; NOBMI2-NEXT:    orl %edi, %r8d
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    shrl %edx
; NOBMI2-NEXT:    orl %esi, %edx
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rax,4), %esi
; NOBMI2-NEXT:    leal (,%rax,8), %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    xorl %ecx, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $4, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $5, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $6, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $7, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $8, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $9, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $10, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    xorl %ecx, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $11, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $12, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $13, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $14, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $15, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $16, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $17, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $18, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $19, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $20, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $21, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $22, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $23, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $24, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $25, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $26, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $27, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $28, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $29, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $30, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %ecx, %esi
; NOBMI2-NEXT:    andl %edx, %esi
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    andl %esi, %r9d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    shrl $2, %r9d
; NOBMI2-NEXT:    orl %r8d, %r9d
; NOBMI2-NEXT:    xorl %esi, %edx
; NOBMI2-NEXT:    shrl $2, %esi
; NOBMI2-NEXT:    orl %edx, %esi
; NOBMI2-NEXT:    notl %ecx
; NOBMI2-NEXT:    andl %eax, %ecx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    leal (,%rcx,4), %edx
; NOBMI2-NEXT:    leal (,%rcx,8), %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    xorl %edi, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $8, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $9, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $10, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $13, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $14, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $15, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $16, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $17, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $18, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $19, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $20, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $21, %eax
; NOBMI2-NEXT:    xorl %edi, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $22, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $23, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $24, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $25, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $26, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $27, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $28, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $29, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $30, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %edx, %edi
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    andl %edi, %r8d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    shrl $4, %r8d
; NOBMI2-NEXT:    orl %r9d, %r8d
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    shrl $4, %edi
; NOBMI2-NEXT:    orl %esi, %edi
; NOBMI2-NEXT:    notl %edx
; NOBMI2-NEXT:    andl %ecx, %edx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    leal (,%rdx,4), %ecx
; NOBMI2-NEXT:    leal (,%rdx,8), %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    xorl %eax, %esi
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $5, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    xorl %esi, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $7, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $8, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $9, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $10, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    xorl %eax, %esi
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $12, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $13, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $14, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $15, %r9d
; NOBMI2-NEXT:    xorl %ecx, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $16, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $17, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $18, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $19, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $20, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $21, %eax
; NOBMI2-NEXT:    xorl %esi, %eax
; NOBMI2-NEXT:    xorl %r9d, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $22, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $23, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $24, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $25, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $26, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $27, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $28, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    xorl %eax, %r9d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $29, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $30, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    andl %edi, %eax
; NOBMI2-NEXT:    movl %r8d, %esi
; NOBMI2-NEXT:    andl %eax, %esi
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    shrl $8, %esi
; NOBMI2-NEXT:    orl %r8d, %esi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    shrl $8, %eax
; NOBMI2-NEXT:    orl %edi, %eax
; NOBMI2-NEXT:    notl %ecx
; NOBMI2-NEXT:    andl %edx, %ecx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    leal (,%rcx,4), %edi
; NOBMI2-NEXT:    leal (,%rcx,8), %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $4, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $5, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $6, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $7, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $9, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $11, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $12, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $13, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $14, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shll $15, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $16, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $17, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $18, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $19, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $20, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $21, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $22, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $23, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $24, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $25, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $26, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $27, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $28, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $29, %edx
; NOBMI2-NEXT:    shll $30, %ecx
; NOBMI2-NEXT:    xorl %edx, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    andl %esi, %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    xorl %eax, %esi
; NOBMI2-NEXT:    shrl $16, %eax
; NOBMI2-NEXT:    orl %esi, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 %val, i32 %mask)
  ret i32 %res
}

define i64 @bext_i64(i64 %val, i64 %mask) nounwind {
; BMI2-LABEL: bext_i64:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pextq %rsi, %rdi, %rax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i64:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    andq %rsi, %rdi
; NOBMI2-NEXT:    movq %rsi, %rax
; NOBMI2-NEXT:    notq %rax
; NOBMI2-NEXT:    leaq (,%rax,4), %rdx
; NOBMI2-NEXT:    leaq (%rax,%rax), %rcx
; NOBMI2-NEXT:    xorq %rcx, %rdx
; NOBMI2-NEXT:    leaq (,%rax,8), %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $4, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $5, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $6, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $7, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $8, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $9, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $10, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $11, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $12, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $13, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $14, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $15, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $16, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $17, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $18, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $19, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r10
; NOBMI2-NEXT:    shlq $21, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $22, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $23, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $24, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $25, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $26, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $27, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $28, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $29, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $30, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $31, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $32, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $33, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $34, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r10
; NOBMI2-NEXT:    shlq $36, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $37, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $38, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $39, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $40, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $41, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $42, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $43, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $44, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $45, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $46, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $47, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $48, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $49, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $50, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $51, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $52, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $53, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r10
; NOBMI2-NEXT:    shlq $55, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $56, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $57, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $58, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $59, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $60, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $61, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $62, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    shlq $63, %rax
; NOBMI2-NEXT:    xorq %r9, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    andq %rsi, %rdx
; NOBMI2-NEXT:    movq %rdi, %r8
; NOBMI2-NEXT:    andq %rdx, %r8
; NOBMI2-NEXT:    xorq %r8, %rdi
; NOBMI2-NEXT:    shrq %r8
; NOBMI2-NEXT:    orq %rdi, %r8
; NOBMI2-NEXT:    xorq %rdx, %rsi
; NOBMI2-NEXT:    shrq %rdx
; NOBMI2-NEXT:    orq %rsi, %rdx
; NOBMI2-NEXT:    notq %rax
; NOBMI2-NEXT:    andq %rcx, %rax
; NOBMI2-NEXT:    leaq (%rax,%rax), %rcx
; NOBMI2-NEXT:    xorq %rax, %rcx
; NOBMI2-NEXT:    leaq (,%rax,4), %rsi
; NOBMI2-NEXT:    leaq (,%rax,8), %rdi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $4, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $5, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $6, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $7, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $8, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $9, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $10, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $11, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $12, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $13, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $14, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $15, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $16, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $17, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $18, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $19, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $21, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $22, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $23, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $24, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $25, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $26, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $27, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $28, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $29, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $30, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $31, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $32, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $33, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $34, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $36, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $37, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $38, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $39, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $40, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $41, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $42, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $43, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $44, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $45, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $46, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $47, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $48, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $49, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $50, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $51, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $52, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $53, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $55, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $56, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $57, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $58, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $59, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $60, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $61, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $62, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rcx, %rsi
; NOBMI2-NEXT:    andq %rdx, %rsi
; NOBMI2-NEXT:    movq %r8, %rdi
; NOBMI2-NEXT:    andq %rsi, %rdi
; NOBMI2-NEXT:    xorq %rdi, %r8
; NOBMI2-NEXT:    shrq $2, %rdi
; NOBMI2-NEXT:    orq %r8, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdx
; NOBMI2-NEXT:    shrq $2, %rsi
; NOBMI2-NEXT:    orq %rdx, %rsi
; NOBMI2-NEXT:    notq %rcx
; NOBMI2-NEXT:    andq %rax, %rcx
; NOBMI2-NEXT:    leaq (%rcx,%rcx), %rax
; NOBMI2-NEXT:    xorq %rcx, %rax
; NOBMI2-NEXT:    leaq (,%rcx,4), %rdx
; NOBMI2-NEXT:    leaq (,%rcx,8), %r8
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $4, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $5, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $6, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $7, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $8, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $9, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $11, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $12, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $13, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $14, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $15, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $16, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $17, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $18, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $19, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $21, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $22, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $23, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $24, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $25, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $26, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $27, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $28, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $29, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $30, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $31, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $32, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $33, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $34, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $36, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $37, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $38, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $39, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $40, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $41, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $42, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $43, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $44, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $45, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $46, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $47, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $48, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $49, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $50, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $51, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $52, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $53, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $55, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $56, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $57, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $58, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $59, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $60, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $61, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $62, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    andq %rsi, %rdx
; NOBMI2-NEXT:    movq %rdi, %r8
; NOBMI2-NEXT:    andq %rdx, %r8
; NOBMI2-NEXT:    xorq %r8, %rdi
; NOBMI2-NEXT:    shrq $4, %r8
; NOBMI2-NEXT:    orq %rdi, %r8
; NOBMI2-NEXT:    xorq %rdx, %rsi
; NOBMI2-NEXT:    shrq $4, %rdx
; NOBMI2-NEXT:    orq %rsi, %rdx
; NOBMI2-NEXT:    notq %rax
; NOBMI2-NEXT:    andq %rcx, %rax
; NOBMI2-NEXT:    leaq (%rax,%rax), %rcx
; NOBMI2-NEXT:    xorq %rax, %rcx
; NOBMI2-NEXT:    leaq (,%rax,4), %rsi
; NOBMI2-NEXT:    leaq (,%rax,8), %rdi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $4, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $5, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $6, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $7, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $8, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $9, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $10, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $11, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $12, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $13, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $14, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $15, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $16, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $17, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $18, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $19, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $21, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $22, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $23, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $24, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $25, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $26, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $27, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $28, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $29, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $30, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $31, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $32, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $33, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $34, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $36, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $37, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $38, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $39, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $40, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $41, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $42, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $43, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $44, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $45, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $46, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $47, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $48, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $49, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $50, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $51, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $52, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $53, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $55, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $56, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $57, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $58, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $59, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $60, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $61, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $62, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rcx, %rsi
; NOBMI2-NEXT:    andq %rdx, %rsi
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    andq %rsi, %r9
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    shrq $8, %r9
; NOBMI2-NEXT:    orq %r8, %r9
; NOBMI2-NEXT:    xorq %rsi, %rdx
; NOBMI2-NEXT:    shrq $8, %rsi
; NOBMI2-NEXT:    orq %rdx, %rsi
; NOBMI2-NEXT:    notq %rcx
; NOBMI2-NEXT:    andq %rax, %rcx
; NOBMI2-NEXT:    leaq (%rcx,%rcx), %rax
; NOBMI2-NEXT:    xorq %rcx, %rax
; NOBMI2-NEXT:    leaq (,%rcx,4), %rdx
; NOBMI2-NEXT:    leaq (,%rcx,8), %rdi
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $4, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $5, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $6, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $7, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $8, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $9, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $10, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $11, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $12, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $13, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $14, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $15, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $16, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $17, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $18, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $19, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $20, %r8
; NOBMI2-NEXT:    xorq %rdi, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $21, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $22, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $23, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $24, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $25, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $26, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $27, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $28, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $29, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $30, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $31, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $32, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $33, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $34, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $35, %r8
; NOBMI2-NEXT:    xorq %rdi, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $36, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $37, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $38, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $39, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $40, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $41, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $42, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $43, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $44, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $45, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $46, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $47, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $48, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $49, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $50, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $51, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $52, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $53, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $54, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $55, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $56, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $57, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $58, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $59, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $60, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $61, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $62, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    andq %rsi, %rax
; NOBMI2-NEXT:    movq %r9, %rdi
; NOBMI2-NEXT:    andq %rax, %rdi
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    shrq $16, %rdi
; NOBMI2-NEXT:    orq %r9, %rdi
; NOBMI2-NEXT:    xorq %rax, %rsi
; NOBMI2-NEXT:    shrq $16, %rax
; NOBMI2-NEXT:    orq %rsi, %rax
; NOBMI2-NEXT:    notq %rdx
; NOBMI2-NEXT:    andq %rcx, %rdx
; NOBMI2-NEXT:    leaq (%rdx,%rdx), %rcx
; NOBMI2-NEXT:    xorq %rdx, %rcx
; NOBMI2-NEXT:    leaq (,%rdx,4), %rsi
; NOBMI2-NEXT:    leaq (,%rdx,8), %r8
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $4, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $5, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $6, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $7, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $8, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $9, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $10, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $11, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $12, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $13, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $14, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $15, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $16, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $17, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $18, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $19, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $21, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $22, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $23, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $24, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $25, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $26, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $27, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $28, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $29, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $30, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $31, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $32, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $33, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $34, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $36, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $37, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $38, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $39, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $40, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $41, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $42, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $43, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $44, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $45, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $46, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $47, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $48, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $49, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $50, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $51, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $52, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $53, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $55, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $56, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $57, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $58, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $59, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $60, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $61, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $62, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    shlq $63, %rdx
; NOBMI2-NEXT:    xorq %rcx, %rdx
; NOBMI2-NEXT:    xorq %rsi, %rdx
; NOBMI2-NEXT:    andq %rdi, %rax
; NOBMI2-NEXT:    andq %rdx, %rax
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    shrq $32, %rax
; NOBMI2-NEXT:    orq %rdi, %rax
; NOBMI2-NEXT:    retq
  %res = call i64 @llvm.bext.i64(i64 %val, i64 %mask)
  ret i64 %res
}

define i32 @bext_mask_zero(i32 %val) nounwind {
; BMI2-LABEL: bext_mask_zero:
; BMI2:       # %bb.0:
; BMI2-NEXT:    xorl %eax, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_mask_zero:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    xorl %eax, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 %val, i32 0)
  ret i32 %res
}

define i32 @bext_mask_allones(i32 %val) nounwind {
; BMI2-LABEL: bext_mask_allones:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movl %edi, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_mask_allones:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl %edi, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 %val, i32 -1)
  ret i32 %res
}

define i32 @bext_const_fold() nounwind {
; BMI2-LABEL: bext_const_fold:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movl $10, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_const_fold:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl $10, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 170, i32 204)
  ret i32 %res
}

