; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-- -mattr=+bmi2 | FileCheck %s --check-prefix=BMI2
; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s --check-prefix=NOBMI2

define i8 @bext_i8(i8 %val, i8 %mask) nounwind {
; BMI2-LABEL: bext_i8:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movzbl %sil, %eax
; BMI2-NEXT:    movzbl %dil, %ecx
; BMI2-NEXT:    pextl %eax, %ecx, %eax
; BMI2-NEXT:    # kill: def $al killed $al killed $eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i8:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl %esi, %ecx
; NOBMI2-NEXT:    notb %cl
; NOBMI2-NEXT:    leal (,%rcx,4), %edx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorb %al, %dl
; NOBMI2-NEXT:    leal (,%rcx,8), %r8d
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shlb $4, %r9b
; NOBMI2-NEXT:    xorb %r8b, %r9b
; NOBMI2-NEXT:    xorb %dl, %r9b
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shlb $5, %dl
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shlb $6, %r8b
; NOBMI2-NEXT:    xorb %dl, %r8b
; NOBMI2-NEXT:    shlb $7, %cl
; NOBMI2-NEXT:    xorb %r8b, %cl
; NOBMI2-NEXT:    xorb %r9b, %cl
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    andb %sil, %dl
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %edi, %r8d
; NOBMI2-NEXT:    andb %dl, %r8b
; NOBMI2-NEXT:    xorb %r8b, %dil
; NOBMI2-NEXT:    shrb %r8b
; NOBMI2-NEXT:    orb %dil, %r8b
; NOBMI2-NEXT:    xorb %dl, %sil
; NOBMI2-NEXT:    shrb %dl
; NOBMI2-NEXT:    orb %sil, %dl
; NOBMI2-NEXT:    notb %cl
; NOBMI2-NEXT:    andb %al, %cl
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorb %cl, %al
; NOBMI2-NEXT:    leal (,%rcx,4), %esi
; NOBMI2-NEXT:    leal (,%rcx,8), %edi
; NOBMI2-NEXT:    xorb %sil, %dil
; NOBMI2-NEXT:    xorb %al, %dil
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shlb $4, %al
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shlb $5, %r9b
; NOBMI2-NEXT:    xorb %al, %r9b
; NOBMI2-NEXT:    movl %ecx, %esi
; NOBMI2-NEXT:    shlb $6, %sil
; NOBMI2-NEXT:    xorb %r9b, %sil
; NOBMI2-NEXT:    xorb %dil, %sil
; NOBMI2-NEXT:    movl %esi, %eax
; NOBMI2-NEXT:    andb %dl, %al
; NOBMI2-NEXT:    movl %r8d, %edi
; NOBMI2-NEXT:    andb %al, %dil
; NOBMI2-NEXT:    xorb %dil, %r8b
; NOBMI2-NEXT:    shrb $2, %dil
; NOBMI2-NEXT:    orb %r8b, %dil
; NOBMI2-NEXT:    xorb %al, %dl
; NOBMI2-NEXT:    shrb $2, %al
; NOBMI2-NEXT:    orb %dl, %al
; NOBMI2-NEXT:    notb %sil
; NOBMI2-NEXT:    andb %cl, %sil
; NOBMI2-NEXT:    leal (%rsi,%rsi), %ecx
; NOBMI2-NEXT:    xorb %sil, %cl
; NOBMI2-NEXT:    leal (,%rsi,4), %edx
; NOBMI2-NEXT:    leal (,%rsi,8), %r8d
; NOBMI2-NEXT:    xorb %dl, %r8b
; NOBMI2-NEXT:    xorb %cl, %r8b
; NOBMI2-NEXT:    movl %esi, %ecx
; NOBMI2-NEXT:    shlb $4, %cl
; NOBMI2-NEXT:    movl %esi, %edx
; NOBMI2-NEXT:    shlb $5, %dl
; NOBMI2-NEXT:    xorb %cl, %dl
; NOBMI2-NEXT:    shlb $6, %sil
; NOBMI2-NEXT:    xorb %dl, %sil
; NOBMI2-NEXT:    xorb %r8b, %sil
; NOBMI2-NEXT:    andb %dil, %al
; NOBMI2-NEXT:    andb %sil, %al
; NOBMI2-NEXT:    xorb %al, %dil
; NOBMI2-NEXT:    shrb $4, %al
; NOBMI2-NEXT:    orb %dil, %al
; NOBMI2-NEXT:    retq
  %res = call i8 @llvm.bext.i8(i8 %val, i8 %mask)
  ret i8 %res
}

define i8 @bdep_i8(i8 %val, i8 %mask) nounwind {
; BMI2-LABEL: bdep_i8:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pdepl %esi, %edi, %eax
; BMI2-NEXT:    # kill: def $al killed $al killed $eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bdep_i8:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl %esi, %eax
; NOBMI2-NEXT:    notb %al
; NOBMI2-NEXT:    leal (,%rax,4), %ecx
; NOBMI2-NEXT:    leal (%rax,%rax), %edx
; NOBMI2-NEXT:    xorb %dl, %cl
; NOBMI2-NEXT:    leal (,%rax,8), %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shlb $4, %r9b
; NOBMI2-NEXT:    xorb %r8b, %r9b
; NOBMI2-NEXT:    xorb %cl, %r9b
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shlb $5, %cl
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shlb $6, %r8b
; NOBMI2-NEXT:    xorb %cl, %r8b
; NOBMI2-NEXT:    shlb $7, %al
; NOBMI2-NEXT:    xorb %r8b, %al
; NOBMI2-NEXT:    xorb %r9b, %al
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    andb %sil, %cl
; NOBMI2-NEXT:    movl %esi, %r8d
; NOBMI2-NEXT:    xorb %cl, %r8b
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shrb %r9b
; NOBMI2-NEXT:    orb %r8b, %r9b
; NOBMI2-NEXT:    notb %al
; NOBMI2-NEXT:    andb %dl, %al
; NOBMI2-NEXT:    leal (%rax,%rax), %edx
; NOBMI2-NEXT:    xorb %al, %dl
; NOBMI2-NEXT:    leal (,%rax,4), %r8d
; NOBMI2-NEXT:    leal (,%rax,8), %r10d
; NOBMI2-NEXT:    xorb %r8b, %r10b
; NOBMI2-NEXT:    xorb %dl, %r10b
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shlb $4, %dl
; NOBMI2-NEXT:    movl %eax, %r11d
; NOBMI2-NEXT:    shlb $5, %r11b
; NOBMI2-NEXT:    xorb %dl, %r11b
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shlb $6, %r8b
; NOBMI2-NEXT:    xorb %r11b, %r8b
; NOBMI2-NEXT:    xorb %r10b, %r8b
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    andb %r9b, %dl
; NOBMI2-NEXT:    xorb %dl, %r9b
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shrb $2, %r10b
; NOBMI2-NEXT:    orb %r9b, %r10b
; NOBMI2-NEXT:    notb %r8b
; NOBMI2-NEXT:    andb %al, %r8b
; NOBMI2-NEXT:    leal (%r8,%r8), %eax
; NOBMI2-NEXT:    xorb %r8b, %al
; NOBMI2-NEXT:    leal (,%r8,4), %r9d
; NOBMI2-NEXT:    leal (,%r8,8), %r11d
; NOBMI2-NEXT:    xorb %r9b, %r11b
; NOBMI2-NEXT:    xorb %al, %r11b
; NOBMI2-NEXT:    movl %r8d, %eax
; NOBMI2-NEXT:    shlb $4, %al
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shlb $5, %r9b
; NOBMI2-NEXT:    xorb %al, %r9b
; NOBMI2-NEXT:    shlb $6, %r8b
; NOBMI2-NEXT:    xorb %r9b, %r8b
; NOBMI2-NEXT:    xorb %r11b, %r8b
; NOBMI2-NEXT:    movl %edi, %eax
; NOBMI2-NEXT:    shlb $4, %al
; NOBMI2-NEXT:    xorb %dil, %al
; NOBMI2-NEXT:    andb %r10b, %al
; NOBMI2-NEXT:    andb %r8b, %al
; NOBMI2-NEXT:    xorb %dil, %al
; NOBMI2-NEXT:    leal (,%rax,4), %edi
; NOBMI2-NEXT:    xorb %al, %dil
; NOBMI2-NEXT:    andb %dl, %dil
; NOBMI2-NEXT:    xorb %al, %dil
; NOBMI2-NEXT:    leal (%rdi,%rdi), %eax
; NOBMI2-NEXT:    xorb %dil, %al
; NOBMI2-NEXT:    andb %cl, %al
; NOBMI2-NEXT:    xorb %dil, %al
; NOBMI2-NEXT:    andb %sil, %al
; NOBMI2-NEXT:    # kill: def $al killed $al killed $eax
; NOBMI2-NEXT:    retq
  %res = call i8 @llvm.bdep.i8(i8 %val, i8 %mask)
  ret i8 %res
}

define i16 @bext_i16(i16 %val, i16 %mask) nounwind {
; BMI2-LABEL: bext_i16:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movzwl %si, %eax
; BMI2-NEXT:    movzwl %di, %ecx
; BMI2-NEXT:    pextl %eax, %ecx, %eax
; BMI2-NEXT:    # kill: def $ax killed $ax killed $eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i16:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    pushq %rbx
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %esi, %eax
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    leal (,%rax,4), %edx
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    leal (,%rax,8), %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $4, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $11, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $14, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    shll $15, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    xorl %r9d, %eax
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    andl %esi, %r8d
; NOBMI2-NEXT:    movl %edi, %edx
; NOBMI2-NEXT:    andl %r8d, %edx
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movzwl %dx, %edx
; NOBMI2-NEXT:    shrl %edx
; NOBMI2-NEXT:    orl %edi, %edx
; NOBMI2-NEXT:    xorl %r8d, %esi
; NOBMI2-NEXT:    movzwl %r8w, %edi
; NOBMI2-NEXT:    shrl %edi
; NOBMI2-NEXT:    orl %esi, %edi
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rax,4), %esi
; NOBMI2-NEXT:    leal (,%rax,8), %r8d
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $4, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $5, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $6, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $7, %esi
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $9, %esi
; NOBMI2-NEXT:    xorl %r8d, %esi
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $11, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $12, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $13, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $14, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    andl %edi, %r8d
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    andl %r8d, %esi
; NOBMI2-NEXT:    xorl %esi, %edx
; NOBMI2-NEXT:    movzwl %si, %esi
; NOBMI2-NEXT:    shrl $2, %esi
; NOBMI2-NEXT:    orl %edx, %esi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movzwl %r8w, %edx
; NOBMI2-NEXT:    shrl $2, %edx
; NOBMI2-NEXT:    orl %edi, %edx
; NOBMI2-NEXT:    notl %ecx
; NOBMI2-NEXT:    andl %eax, %ecx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    leal (,%rcx,4), %edi
; NOBMI2-NEXT:    leal (,%rcx,8), %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $5, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %edi, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $7, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $9, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $12, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shll $13, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $14, %eax
; NOBMI2-NEXT:    xorl %r9d, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    andl %edx, %r8d
; NOBMI2-NEXT:    movl %esi, %edi
; NOBMI2-NEXT:    andl %r8d, %edi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movzwl %di, %edi
; NOBMI2-NEXT:    shrl $4, %edi
; NOBMI2-NEXT:    orl %esi, %edi
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movzwl %r8w, %ebx
; NOBMI2-NEXT:    shrl $4, %ebx
; NOBMI2-NEXT:    orl %edx, %ebx
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rax,4), %edx
; NOBMI2-NEXT:    leal (,%rax,8), %esi
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $4, %ecx
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $6, %ecx
; NOBMI2-NEXT:    xorl %edx, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $8, %esi
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $9, %edx
; NOBMI2-NEXT:    xorl %esi, %edx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $10, %esi
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $11, %ecx
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $13, %ecx
; NOBMI2-NEXT:    xorl %edx, %ecx
; NOBMI2-NEXT:    shll $14, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    xorl %esi, %eax
; NOBMI2-NEXT:    andl %edi, %ebx
; NOBMI2-NEXT:    andl %eax, %ebx
; NOBMI2-NEXT:    xorl %ebx, %edi
; NOBMI2-NEXT:    movzbl %bh, %eax
; NOBMI2-NEXT:    orl %edi, %eax
; NOBMI2-NEXT:    # kill: def $ax killed $ax killed $eax
; NOBMI2-NEXT:    popq %rbx
; NOBMI2-NEXT:    retq
  %res = call i16 @llvm.bext.i16(i16 %val, i16 %mask)
  ret i16 %res
}

define i16 @bdep_i16(i16 %val, i16 %mask) nounwind {
; BMI2-LABEL: bdep_i16:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pdepl %esi, %edi, %eax
; BMI2-NEXT:    # kill: def $ax killed $ax killed $eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bdep_i16:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    pushq %rbx
; NOBMI2-NEXT:    movl %esi, %edx
; NOBMI2-NEXT:    notl %edx
; NOBMI2-NEXT:    leal (,%rdx,4), %ecx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rdx,8), %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $4, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %ecx, %r9d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $5, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $7, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $11, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %ecx, %r9d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $12, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $14, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    shll $15, %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    andl %esi, %ecx
; NOBMI2-NEXT:    movl %esi, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movzwl %cx, %r9d
; NOBMI2-NEXT:    shrl %r9d
; NOBMI2-NEXT:    orl %r8d, %r9d
; NOBMI2-NEXT:    notl %edx
; NOBMI2-NEXT:    andl %eax, %edx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    leal (,%rdx,4), %r8d
; NOBMI2-NEXT:    leal (,%rdx,8), %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %eax, %r10d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $5, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    xorl %r10d, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $7, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $8, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $9, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $10, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %eax, %r10d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $12, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $13, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $14, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    movl %r8d, %eax
; NOBMI2-NEXT:    andl %r9d, %eax
; NOBMI2-NEXT:    xorl %eax, %r9d
; NOBMI2-NEXT:    movzwl %ax, %r10d
; NOBMI2-NEXT:    shrl $2, %r10d
; NOBMI2-NEXT:    orl %r9d, %r10d
; NOBMI2-NEXT:    notl %r8d
; NOBMI2-NEXT:    andl %edx, %r8d
; NOBMI2-NEXT:    leal (%r8,%r8), %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    leal (,%r8,4), %r9d
; NOBMI2-NEXT:    leal (,%r8,8), %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    xorl %edx, %r11d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $4, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $5, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $6, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    xorl %r11d, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $7, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $8, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $10, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    xorl %edx, %r11d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $11, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $12, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $13, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $14, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    movl %r9d, %edx
; NOBMI2-NEXT:    andl %r10d, %edx
; NOBMI2-NEXT:    xorl %edx, %r10d
; NOBMI2-NEXT:    movzwl %dx, %r11d
; NOBMI2-NEXT:    shrl $4, %r11d
; NOBMI2-NEXT:    orl %r10d, %r11d
; NOBMI2-NEXT:    notl %r9d
; NOBMI2-NEXT:    andl %r8d, %r9d
; NOBMI2-NEXT:    leal (%r9,%r9), %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    leal (,%r9,4), %r10d
; NOBMI2-NEXT:    leal (,%r9,8), %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    xorl %r8d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $4, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $5, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    xorl %ebx, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $7, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $8, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $9, %r10d
; NOBMI2-NEXT:    xorl %ebx, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $10, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    xorl %r8d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $11, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $12, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    shll $14, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %ebx, %r9d
; NOBMI2-NEXT:    movl %edi, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    andl %r11d, %r8d
; NOBMI2-NEXT:    andl %r9d, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %r8d, %edi
; NOBMI2-NEXT:    shll $4, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    andl %edx, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    leal (,%rdi,4), %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    andl %eax, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    andl %esi, %eax
; NOBMI2-NEXT:    # kill: def $ax killed $ax killed $eax
; NOBMI2-NEXT:    popq %rbx
; NOBMI2-NEXT:    retq
  %res = call i16 @llvm.bdep.i16(i16 %val, i16 %mask)
  ret i16 %res
}

define i32 @bext_i32(i32 %val, i32 %mask) nounwind {
; BMI2-LABEL: bext_i32:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pextl %esi, %edi, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i32:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %esi, %eax
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    leal (,%rax,4), %edx
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    leal (,%rax,8), %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $4, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $11, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $14, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $15, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %r10d
; NOBMI2-NEXT:    shll $16, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %r9d, %r10d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $17, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $18, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $19, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $20, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $21, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $22, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    xorl %r10d, %edx
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $23, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $24, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $25, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $26, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $27, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $28, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %eax, %r8d
; NOBMI2-NEXT:    shll $29, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    shll $30, %edx
; NOBMI2-NEXT:    shll $31, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %eax, %edx
; NOBMI2-NEXT:    andl %esi, %edx
; NOBMI2-NEXT:    movl %edi, %r8d
; NOBMI2-NEXT:    andl %edx, %r8d
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    shrl %r8d
; NOBMI2-NEXT:    orl %edi, %r8d
; NOBMI2-NEXT:    xorl %edx, %esi
; NOBMI2-NEXT:    shrl %edx
; NOBMI2-NEXT:    orl %esi, %edx
; NOBMI2-NEXT:    notl %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    leal (%rax,%rax), %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rax,4), %esi
; NOBMI2-NEXT:    leal (,%rax,8), %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    xorl %ecx, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $4, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $5, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $6, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $7, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $8, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $9, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $10, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    xorl %ecx, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $11, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $12, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $13, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $14, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %r9d
; NOBMI2-NEXT:    shll $15, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $16, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $17, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $18, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $19, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $20, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $21, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $22, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $23, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $24, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $25, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $26, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $27, %edi
; NOBMI2-NEXT:    xorl %esi, %edi
; NOBMI2-NEXT:    movl %eax, %esi
; NOBMI2-NEXT:    shll $28, %esi
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %eax, %edi
; NOBMI2-NEXT:    shll $29, %edi
; NOBMI2-NEXT:    movl %eax, %ecx
; NOBMI2-NEXT:    shll $30, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %ecx, %esi
; NOBMI2-NEXT:    andl %edx, %esi
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    andl %esi, %r9d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    shrl $2, %r9d
; NOBMI2-NEXT:    orl %r8d, %r9d
; NOBMI2-NEXT:    xorl %esi, %edx
; NOBMI2-NEXT:    shrl $2, %esi
; NOBMI2-NEXT:    orl %edx, %esi
; NOBMI2-NEXT:    notl %ecx
; NOBMI2-NEXT:    andl %eax, %ecx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    leal (,%rcx,4), %edx
; NOBMI2-NEXT:    leal (,%rcx,8), %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $5, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    xorl %edi, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $7, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $8, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $9, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $10, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $12, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $13, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $14, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $15, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $16, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $17, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $18, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $19, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $20, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $21, %eax
; NOBMI2-NEXT:    xorl %edi, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $22, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $23, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $24, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $25, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $26, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $27, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $28, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    shll $29, %eax
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $30, %edx
; NOBMI2-NEXT:    xorl %eax, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %edx, %edi
; NOBMI2-NEXT:    andl %esi, %edi
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    andl %edi, %r8d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    shrl $4, %r8d
; NOBMI2-NEXT:    orl %r9d, %r8d
; NOBMI2-NEXT:    xorl %edi, %esi
; NOBMI2-NEXT:    shrl $4, %edi
; NOBMI2-NEXT:    orl %esi, %edi
; NOBMI2-NEXT:    notl %edx
; NOBMI2-NEXT:    andl %ecx, %edx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    leal (,%rdx,4), %ecx
; NOBMI2-NEXT:    leal (,%rdx,8), %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    xorl %eax, %esi
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $5, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    xorl %esi, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $7, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $8, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $9, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $10, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    xorl %eax, %esi
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $12, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $13, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $14, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $15, %r9d
; NOBMI2-NEXT:    xorl %ecx, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $16, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $17, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $18, %eax
; NOBMI2-NEXT:    xorl %ecx, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $19, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $20, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $21, %eax
; NOBMI2-NEXT:    xorl %esi, %eax
; NOBMI2-NEXT:    xorl %r9d, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $22, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $23, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $24, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $25, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $26, %ecx
; NOBMI2-NEXT:    xorl %esi, %ecx
; NOBMI2-NEXT:    movl %edx, %esi
; NOBMI2-NEXT:    shll $27, %esi
; NOBMI2-NEXT:    xorl %ecx, %esi
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $28, %r9d
; NOBMI2-NEXT:    xorl %esi, %r9d
; NOBMI2-NEXT:    xorl %eax, %r9d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $29, %eax
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $30, %ecx
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    movl %ecx, %eax
; NOBMI2-NEXT:    andl %edi, %eax
; NOBMI2-NEXT:    movl %r8d, %esi
; NOBMI2-NEXT:    andl %eax, %esi
; NOBMI2-NEXT:    xorl %esi, %r8d
; NOBMI2-NEXT:    shrl $8, %esi
; NOBMI2-NEXT:    orl %r8d, %esi
; NOBMI2-NEXT:    xorl %eax, %edi
; NOBMI2-NEXT:    shrl $8, %eax
; NOBMI2-NEXT:    orl %edi, %eax
; NOBMI2-NEXT:    notl %ecx
; NOBMI2-NEXT:    andl %edx, %ecx
; NOBMI2-NEXT:    leal (%rcx,%rcx), %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    leal (,%rcx,4), %edi
; NOBMI2-NEXT:    leal (,%rcx,8), %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $4, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $5, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $6, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $7, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $9, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    xorl %edx, %r8d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $11, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $12, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $13, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $14, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shll $15, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $16, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $17, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $18, %edx
; NOBMI2-NEXT:    xorl %edi, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $19, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $20, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $21, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $22, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $23, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $24, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $25, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $26, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    movl %ecx, %r8d
; NOBMI2-NEXT:    shll $27, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    movl %ecx, %edi
; NOBMI2-NEXT:    shll $28, %edi
; NOBMI2-NEXT:    xorl %r8d, %edi
; NOBMI2-NEXT:    xorl %edx, %edi
; NOBMI2-NEXT:    movl %ecx, %edx
; NOBMI2-NEXT:    shll $29, %edx
; NOBMI2-NEXT:    shll $30, %ecx
; NOBMI2-NEXT:    xorl %edx, %ecx
; NOBMI2-NEXT:    xorl %edi, %ecx
; NOBMI2-NEXT:    andl %esi, %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    xorl %eax, %esi
; NOBMI2-NEXT:    shrl $16, %eax
; NOBMI2-NEXT:    orl %esi, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 %val, i32 %mask)
  ret i32 %res
}

define i32 @bdep_i32(i32 %val, i32 %mask) nounwind {
; BMI2-LABEL: bdep_i32:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pdepl %esi, %edi, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bdep_i32:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    pushq %rbp
; NOBMI2-NEXT:    pushq %r14
; NOBMI2-NEXT:    pushq %rbx
; NOBMI2-NEXT:    movl %esi, %edx
; NOBMI2-NEXT:    notl %edx
; NOBMI2-NEXT:    leal (,%rdx,4), %ecx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %eax, %ecx
; NOBMI2-NEXT:    leal (,%rdx,8), %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $4, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %ecx, %r9d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $5, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $7, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $8, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $10, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $11, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    xorl %ecx, %r9d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $12, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $14, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $15, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $16, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %r9d, %r10d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $17, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $18, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $19, %ecx
; NOBMI2-NEXT:    xorl %r8d, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $20, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $21, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $22, %ecx
; NOBMI2-NEXT:    xorl %r9d, %ecx
; NOBMI2-NEXT:    xorl %r10d, %ecx
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $23, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $24, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $25, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $26, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $27, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    movl %edx, %r9d
; NOBMI2-NEXT:    shll $28, %r9d
; NOBMI2-NEXT:    xorl %r8d, %r9d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $29, %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    shll $30, %ecx
; NOBMI2-NEXT:    shll $31, %edx
; NOBMI2-NEXT:    xorl %ecx, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    movl %edx, %ecx
; NOBMI2-NEXT:    andl %esi, %ecx
; NOBMI2-NEXT:    movl %esi, %r8d
; NOBMI2-NEXT:    xorl %ecx, %r8d
; NOBMI2-NEXT:    movl %ecx, %r9d
; NOBMI2-NEXT:    shrl %r9d
; NOBMI2-NEXT:    orl %r8d, %r9d
; NOBMI2-NEXT:    notl %edx
; NOBMI2-NEXT:    andl %eax, %edx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    leal (,%rdx,4), %r8d
; NOBMI2-NEXT:    leal (,%rdx,8), %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %eax, %r10d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $4, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $5, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $6, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    xorl %r10d, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $7, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $8, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $9, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $10, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %eax, %r10d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $11, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $12, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $13, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $14, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %edx, %r11d
; NOBMI2-NEXT:    shll $15, %r11d
; NOBMI2-NEXT:    xorl %r8d, %r11d
; NOBMI2-NEXT:    xorl %r10d, %r11d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $16, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $17, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $18, %eax
; NOBMI2-NEXT:    xorl %r8d, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $19, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $20, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $21, %eax
; NOBMI2-NEXT:    xorl %r10d, %eax
; NOBMI2-NEXT:    xorl %r11d, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $22, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $23, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $24, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $25, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $26, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    movl %edx, %r10d
; NOBMI2-NEXT:    shll $27, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %edx, %r11d
; NOBMI2-NEXT:    shll $28, %r11d
; NOBMI2-NEXT:    xorl %r10d, %r11d
; NOBMI2-NEXT:    xorl %eax, %r11d
; NOBMI2-NEXT:    movl %edx, %eax
; NOBMI2-NEXT:    shll $29, %eax
; NOBMI2-NEXT:    movl %edx, %r8d
; NOBMI2-NEXT:    shll $30, %r8d
; NOBMI2-NEXT:    xorl %eax, %r8d
; NOBMI2-NEXT:    xorl %r11d, %r8d
; NOBMI2-NEXT:    movl %r8d, %eax
; NOBMI2-NEXT:    andl %r9d, %eax
; NOBMI2-NEXT:    xorl %eax, %r9d
; NOBMI2-NEXT:    movl %eax, %r10d
; NOBMI2-NEXT:    shrl $2, %r10d
; NOBMI2-NEXT:    orl %r9d, %r10d
; NOBMI2-NEXT:    notl %r8d
; NOBMI2-NEXT:    andl %edx, %r8d
; NOBMI2-NEXT:    leal (%r8,%r8), %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    leal (,%r8,4), %r9d
; NOBMI2-NEXT:    leal (,%r8,8), %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    xorl %edx, %r11d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $4, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $5, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $6, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    xorl %r11d, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $7, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $8, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $9, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $10, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    xorl %edx, %r11d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $11, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $12, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $13, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $14, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %r8d, %ebx
; NOBMI2-NEXT:    shll $15, %ebx
; NOBMI2-NEXT:    xorl %r9d, %ebx
; NOBMI2-NEXT:    xorl %r11d, %ebx
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $16, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $17, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $18, %edx
; NOBMI2-NEXT:    xorl %r9d, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $19, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $20, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $21, %edx
; NOBMI2-NEXT:    xorl %r11d, %edx
; NOBMI2-NEXT:    xorl %ebx, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $22, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $23, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $24, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $25, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $26, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    movl %r8d, %r11d
; NOBMI2-NEXT:    shll $27, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r8d, %ebx
; NOBMI2-NEXT:    shll $28, %ebx
; NOBMI2-NEXT:    xorl %r11d, %ebx
; NOBMI2-NEXT:    xorl %edx, %ebx
; NOBMI2-NEXT:    movl %r8d, %edx
; NOBMI2-NEXT:    shll $29, %edx
; NOBMI2-NEXT:    movl %r8d, %r9d
; NOBMI2-NEXT:    shll $30, %r9d
; NOBMI2-NEXT:    xorl %edx, %r9d
; NOBMI2-NEXT:    xorl %ebx, %r9d
; NOBMI2-NEXT:    movl %r9d, %edx
; NOBMI2-NEXT:    andl %r10d, %edx
; NOBMI2-NEXT:    xorl %edx, %r10d
; NOBMI2-NEXT:    movl %edx, %r11d
; NOBMI2-NEXT:    shrl $4, %r11d
; NOBMI2-NEXT:    orl %r10d, %r11d
; NOBMI2-NEXT:    notl %r9d
; NOBMI2-NEXT:    andl %r8d, %r9d
; NOBMI2-NEXT:    leal (%r9,%r9), %r8d
; NOBMI2-NEXT:    xorl %r9d, %r8d
; NOBMI2-NEXT:    leal (,%r9,4), %r10d
; NOBMI2-NEXT:    leal (,%r9,8), %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    xorl %r8d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $4, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $5, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $6, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    xorl %ebx, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $7, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $8, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $9, %r10d
; NOBMI2-NEXT:    xorl %ebx, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $10, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    xorl %r8d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $11, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $12, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $13, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $14, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebp
; NOBMI2-NEXT:    shll $15, %ebp
; NOBMI2-NEXT:    xorl %r10d, %ebp
; NOBMI2-NEXT:    xorl %ebx, %ebp
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $16, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $17, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $18, %r8d
; NOBMI2-NEXT:    xorl %r10d, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $19, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $20, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $21, %r8d
; NOBMI2-NEXT:    xorl %ebx, %r8d
; NOBMI2-NEXT:    xorl %ebp, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $22, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $23, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $24, %r10d
; NOBMI2-NEXT:    xorl %ebx, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $25, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $26, %r10d
; NOBMI2-NEXT:    xorl %ebx, %r10d
; NOBMI2-NEXT:    movl %r9d, %ebx
; NOBMI2-NEXT:    shll $27, %ebx
; NOBMI2-NEXT:    xorl %r10d, %ebx
; NOBMI2-NEXT:    movl %r9d, %ebp
; NOBMI2-NEXT:    shll $28, %ebp
; NOBMI2-NEXT:    xorl %ebx, %ebp
; NOBMI2-NEXT:    xorl %r8d, %ebp
; NOBMI2-NEXT:    movl %r9d, %r8d
; NOBMI2-NEXT:    shll $29, %r8d
; NOBMI2-NEXT:    movl %r9d, %r10d
; NOBMI2-NEXT:    shll $30, %r10d
; NOBMI2-NEXT:    xorl %r8d, %r10d
; NOBMI2-NEXT:    xorl %ebp, %r10d
; NOBMI2-NEXT:    movl %r10d, %r8d
; NOBMI2-NEXT:    andl %r11d, %r8d
; NOBMI2-NEXT:    xorl %r8d, %r11d
; NOBMI2-NEXT:    movl %r8d, %ebx
; NOBMI2-NEXT:    shrl $8, %ebx
; NOBMI2-NEXT:    orl %r11d, %ebx
; NOBMI2-NEXT:    notl %r10d
; NOBMI2-NEXT:    andl %r9d, %r10d
; NOBMI2-NEXT:    leal (%r10,%r10), %r9d
; NOBMI2-NEXT:    xorl %r10d, %r9d
; NOBMI2-NEXT:    leal (,%r10,4), %r11d
; NOBMI2-NEXT:    leal (,%r10,8), %ebp
; NOBMI2-NEXT:    xorl %r11d, %ebp
; NOBMI2-NEXT:    xorl %r9d, %ebp
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $4, %r9d
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $5, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $6, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    xorl %ebp, %r9d
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $7, %r11d
; NOBMI2-NEXT:    movl %r10d, %ebp
; NOBMI2-NEXT:    shll $8, %ebp
; NOBMI2-NEXT:    xorl %r11d, %ebp
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $9, %r11d
; NOBMI2-NEXT:    xorl %ebp, %r11d
; NOBMI2-NEXT:    movl %r10d, %ebp
; NOBMI2-NEXT:    shll $10, %ebp
; NOBMI2-NEXT:    xorl %r11d, %ebp
; NOBMI2-NEXT:    xorl %r9d, %ebp
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $11, %r9d
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $12, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $13, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $14, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r10d, %r14d
; NOBMI2-NEXT:    shll $15, %r14d
; NOBMI2-NEXT:    xorl %r11d, %r14d
; NOBMI2-NEXT:    xorl %ebp, %r14d
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $16, %r9d
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $17, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $18, %r9d
; NOBMI2-NEXT:    xorl %r11d, %r9d
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $19, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r10d, %ebp
; NOBMI2-NEXT:    shll $20, %ebp
; NOBMI2-NEXT:    xorl %r11d, %ebp
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $21, %r9d
; NOBMI2-NEXT:    xorl %ebp, %r9d
; NOBMI2-NEXT:    xorl %r14d, %r9d
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $22, %r11d
; NOBMI2-NEXT:    movl %r10d, %ebp
; NOBMI2-NEXT:    shll $23, %ebp
; NOBMI2-NEXT:    xorl %r11d, %ebp
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $24, %r11d
; NOBMI2-NEXT:    xorl %ebp, %r11d
; NOBMI2-NEXT:    movl %r10d, %ebp
; NOBMI2-NEXT:    shll $25, %ebp
; NOBMI2-NEXT:    xorl %r11d, %ebp
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $26, %r11d
; NOBMI2-NEXT:    xorl %ebp, %r11d
; NOBMI2-NEXT:    movl %r10d, %ebp
; NOBMI2-NEXT:    shll $27, %ebp
; NOBMI2-NEXT:    xorl %r11d, %ebp
; NOBMI2-NEXT:    movl %r10d, %r11d
; NOBMI2-NEXT:    shll $28, %r11d
; NOBMI2-NEXT:    xorl %ebp, %r11d
; NOBMI2-NEXT:    xorl %r9d, %r11d
; NOBMI2-NEXT:    movl %r10d, %r9d
; NOBMI2-NEXT:    shll $29, %r9d
; NOBMI2-NEXT:    shll $30, %r10d
; NOBMI2-NEXT:    xorl %r9d, %r10d
; NOBMI2-NEXT:    xorl %r11d, %r10d
; NOBMI2-NEXT:    movl %edi, %r9d
; NOBMI2-NEXT:    shll $16, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    andl %ebx, %r9d
; NOBMI2-NEXT:    andl %r10d, %r9d
; NOBMI2-NEXT:    xorl %edi, %r9d
; NOBMI2-NEXT:    movl %r9d, %edi
; NOBMI2-NEXT:    shll $8, %edi
; NOBMI2-NEXT:    xorl %r9d, %edi
; NOBMI2-NEXT:    andl %r8d, %edi
; NOBMI2-NEXT:    xorl %r9d, %edi
; NOBMI2-NEXT:    movl %edi, %r8d
; NOBMI2-NEXT:    shll $4, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    andl %edx, %r8d
; NOBMI2-NEXT:    xorl %edi, %r8d
; NOBMI2-NEXT:    leal (,%r8,4), %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    andl %eax, %edx
; NOBMI2-NEXT:    xorl %r8d, %edx
; NOBMI2-NEXT:    leal (%rdx,%rdx), %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    andl %ecx, %eax
; NOBMI2-NEXT:    xorl %edx, %eax
; NOBMI2-NEXT:    andl %esi, %eax
; NOBMI2-NEXT:    popq %rbx
; NOBMI2-NEXT:    popq %r14
; NOBMI2-NEXT:    popq %rbp
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bdep.i32(i32 %val, i32 %mask)
  ret i32 %res
}

define i64 @bext_i64(i64 %val, i64 %mask) nounwind {
; BMI2-LABEL: bext_i64:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pextq %rsi, %rdi, %rax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_i64:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    andq %rsi, %rdi
; NOBMI2-NEXT:    movq %rsi, %rax
; NOBMI2-NEXT:    notq %rax
; NOBMI2-NEXT:    leaq (,%rax,4), %rdx
; NOBMI2-NEXT:    leaq (%rax,%rax), %rcx
; NOBMI2-NEXT:    xorq %rcx, %rdx
; NOBMI2-NEXT:    leaq (,%rax,8), %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $4, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $5, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $6, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $7, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $8, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $9, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $10, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $11, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $12, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $13, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $14, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $15, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $16, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $17, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $18, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $19, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r10
; NOBMI2-NEXT:    shlq $21, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $22, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $23, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $24, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $25, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $26, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $27, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $28, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $29, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $30, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $31, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $32, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $33, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $34, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r10
; NOBMI2-NEXT:    shlq $36, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $37, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $38, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $39, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $40, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $41, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $42, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $43, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $44, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $45, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $46, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $47, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $48, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $49, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $50, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $51, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $52, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $53, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rax, %r10
; NOBMI2-NEXT:    shlq $55, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rax, %r8
; NOBMI2-NEXT:    shlq $56, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $57, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $58, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $59, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $60, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    shlq $61, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $62, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    shlq $63, %rax
; NOBMI2-NEXT:    xorq %r9, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    andq %rsi, %rdx
; NOBMI2-NEXT:    movq %rdi, %r8
; NOBMI2-NEXT:    andq %rdx, %r8
; NOBMI2-NEXT:    xorq %r8, %rdi
; NOBMI2-NEXT:    shrq %r8
; NOBMI2-NEXT:    orq %rdi, %r8
; NOBMI2-NEXT:    xorq %rdx, %rsi
; NOBMI2-NEXT:    shrq %rdx
; NOBMI2-NEXT:    orq %rsi, %rdx
; NOBMI2-NEXT:    notq %rax
; NOBMI2-NEXT:    andq %rcx, %rax
; NOBMI2-NEXT:    leaq (%rax,%rax), %rcx
; NOBMI2-NEXT:    xorq %rax, %rcx
; NOBMI2-NEXT:    leaq (,%rax,4), %rsi
; NOBMI2-NEXT:    leaq (,%rax,8), %rdi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $4, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $5, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $6, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $7, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $8, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $9, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $10, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $11, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $12, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $13, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $14, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $15, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $16, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $17, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $18, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $19, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $21, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $22, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $23, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $24, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $25, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $26, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $27, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $28, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $29, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $30, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $31, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $32, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $33, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $34, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $36, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $37, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $38, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $39, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $40, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $41, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $42, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $43, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $44, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $45, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $46, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $47, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $48, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $49, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $50, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $51, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $52, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $53, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $55, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $56, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $57, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $58, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $59, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $60, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $61, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $62, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rcx, %rsi
; NOBMI2-NEXT:    andq %rdx, %rsi
; NOBMI2-NEXT:    movq %r8, %rdi
; NOBMI2-NEXT:    andq %rsi, %rdi
; NOBMI2-NEXT:    xorq %rdi, %r8
; NOBMI2-NEXT:    shrq $2, %rdi
; NOBMI2-NEXT:    orq %r8, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdx
; NOBMI2-NEXT:    shrq $2, %rsi
; NOBMI2-NEXT:    orq %rdx, %rsi
; NOBMI2-NEXT:    notq %rcx
; NOBMI2-NEXT:    andq %rax, %rcx
; NOBMI2-NEXT:    leaq (%rcx,%rcx), %rax
; NOBMI2-NEXT:    xorq %rcx, %rax
; NOBMI2-NEXT:    leaq (,%rcx,4), %rdx
; NOBMI2-NEXT:    leaq (,%rcx,8), %r8
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $4, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $5, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $6, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $7, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $8, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $9, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $10, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $11, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $12, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $13, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $14, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $15, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $16, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $17, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $18, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $19, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $21, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $22, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $23, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $24, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $25, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $26, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $27, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $28, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $29, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $30, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $31, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $32, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $33, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $34, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $36, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $37, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $38, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $39, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $40, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $41, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $42, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $43, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $44, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $45, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $46, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $47, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $48, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $49, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $50, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $51, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $52, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $53, %r8
; NOBMI2-NEXT:    xorq %rdx, %r8
; NOBMI2-NEXT:    movq %rcx, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $55, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $56, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $57, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $58, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $59, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $60, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $61, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $62, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rax, %rdx
; NOBMI2-NEXT:    andq %rsi, %rdx
; NOBMI2-NEXT:    movq %rdi, %r8
; NOBMI2-NEXT:    andq %rdx, %r8
; NOBMI2-NEXT:    xorq %r8, %rdi
; NOBMI2-NEXT:    shrq $4, %r8
; NOBMI2-NEXT:    orq %rdi, %r8
; NOBMI2-NEXT:    xorq %rdx, %rsi
; NOBMI2-NEXT:    shrq $4, %rdx
; NOBMI2-NEXT:    orq %rsi, %rdx
; NOBMI2-NEXT:    notq %rax
; NOBMI2-NEXT:    andq %rcx, %rax
; NOBMI2-NEXT:    leaq (%rax,%rax), %rcx
; NOBMI2-NEXT:    xorq %rax, %rcx
; NOBMI2-NEXT:    leaq (,%rax,4), %rsi
; NOBMI2-NEXT:    leaq (,%rax,8), %rdi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $4, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $5, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $6, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $7, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $8, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $9, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $10, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $11, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $12, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $13, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $14, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $15, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $16, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $17, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $18, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $19, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $21, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $22, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $23, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $24, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $25, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $26, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $27, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $28, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $29, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $30, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $31, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $32, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $33, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $34, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $36, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $37, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $38, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $39, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $40, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $41, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $42, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $43, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $44, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $45, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $46, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $47, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $48, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $49, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $50, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $51, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $52, %rsi
; NOBMI2-NEXT:    xorq %rdi, %rsi
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $53, %rdi
; NOBMI2-NEXT:    xorq %rsi, %rdi
; NOBMI2-NEXT:    movq %rax, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %rax, %rsi
; NOBMI2-NEXT:    shlq $55, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $56, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $57, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $58, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $59, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $60, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    movq %rax, %rdi
; NOBMI2-NEXT:    shlq $61, %rdi
; NOBMI2-NEXT:    xorq %rcx, %rdi
; NOBMI2-NEXT:    movq %rax, %rcx
; NOBMI2-NEXT:    shlq $62, %rcx
; NOBMI2-NEXT:    xorq %rdi, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rcx, %rsi
; NOBMI2-NEXT:    andq %rdx, %rsi
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    andq %rsi, %r9
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    shrq $8, %r9
; NOBMI2-NEXT:    orq %r8, %r9
; NOBMI2-NEXT:    xorq %rsi, %rdx
; NOBMI2-NEXT:    shrq $8, %rsi
; NOBMI2-NEXT:    orq %rdx, %rsi
; NOBMI2-NEXT:    notq %rcx
; NOBMI2-NEXT:    andq %rax, %rcx
; NOBMI2-NEXT:    leaq (%rcx,%rcx), %rax
; NOBMI2-NEXT:    xorq %rcx, %rax
; NOBMI2-NEXT:    leaq (,%rcx,4), %rdx
; NOBMI2-NEXT:    leaq (,%rcx,8), %rdi
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $4, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $5, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $6, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $7, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $8, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $9, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $10, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $11, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $12, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $13, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $14, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $15, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $16, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $17, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $18, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $19, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $20, %r8
; NOBMI2-NEXT:    xorq %rdi, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $21, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $22, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $23, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $24, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $25, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $26, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $27, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $28, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $29, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $30, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $31, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $32, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $33, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $34, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $35, %r8
; NOBMI2-NEXT:    xorq %rdi, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $36, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $37, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $38, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $39, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $40, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $41, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $42, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $43, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $44, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $45, %rax
; NOBMI2-NEXT:    xorq %rdi, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $46, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $47, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $48, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $49, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $50, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $51, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $52, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $53, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $54, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rcx, %rdi
; NOBMI2-NEXT:    shlq $55, %rdi
; NOBMI2-NEXT:    xorq %rdx, %rdi
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $56, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $57, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $58, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $59, %rdx
; NOBMI2-NEXT:    xorq %rax, %rdx
; NOBMI2-NEXT:    movq %rcx, %rax
; NOBMI2-NEXT:    shlq $60, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    movq %rcx, %r8
; NOBMI2-NEXT:    shlq $61, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rcx, %rdx
; NOBMI2-NEXT:    shlq $62, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    andq %rsi, %rax
; NOBMI2-NEXT:    movq %r9, %rdi
; NOBMI2-NEXT:    andq %rax, %rdi
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    shrq $16, %rdi
; NOBMI2-NEXT:    orq %r9, %rdi
; NOBMI2-NEXT:    xorq %rax, %rsi
; NOBMI2-NEXT:    shrq $16, %rax
; NOBMI2-NEXT:    orq %rsi, %rax
; NOBMI2-NEXT:    notq %rdx
; NOBMI2-NEXT:    andq %rcx, %rdx
; NOBMI2-NEXT:    leaq (%rdx,%rdx), %rcx
; NOBMI2-NEXT:    xorq %rdx, %rcx
; NOBMI2-NEXT:    leaq (,%rdx,4), %rsi
; NOBMI2-NEXT:    leaq (,%rdx,8), %r8
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $4, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $5, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $6, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $7, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $8, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $9, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $10, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $11, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $12, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $13, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $14, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $15, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $16, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $17, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $18, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $19, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $21, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $22, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $23, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $24, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $25, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $26, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $27, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $28, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $29, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $30, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $31, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $32, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $33, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $34, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $36, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $37, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $38, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $39, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $40, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $41, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $42, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $43, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $44, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $45, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %rsi, %rcx
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $46, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $47, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $48, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $49, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $50, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $51, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $52, %rsi
; NOBMI2-NEXT:    xorq %r8, %rsi
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $53, %r8
; NOBMI2-NEXT:    xorq %rsi, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %rsi
; NOBMI2-NEXT:    shlq $55, %rsi
; NOBMI2-NEXT:    xorq %r9, %rsi
; NOBMI2-NEXT:    xorq %rcx, %rsi
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $56, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $57, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $58, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $59, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $60, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $61, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $62, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    shlq $63, %rdx
; NOBMI2-NEXT:    xorq %rcx, %rdx
; NOBMI2-NEXT:    xorq %rsi, %rdx
; NOBMI2-NEXT:    andq %rdi, %rax
; NOBMI2-NEXT:    andq %rdx, %rax
; NOBMI2-NEXT:    xorq %rax, %rdi
; NOBMI2-NEXT:    shrq $32, %rax
; NOBMI2-NEXT:    orq %rdi, %rax
; NOBMI2-NEXT:    retq
  %res = call i64 @llvm.bext.i64(i64 %val, i64 %mask)
  ret i64 %res
}

define i64 @bdep_i64(i64 %val, i64 %mask) nounwind {
; BMI2-LABEL: bdep_i64:
; BMI2:       # %bb.0:
; BMI2-NEXT:    pdepq %rsi, %rdi, %rax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bdep_i64:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    pushq %r15
; NOBMI2-NEXT:    pushq %r14
; NOBMI2-NEXT:    pushq %r12
; NOBMI2-NEXT:    pushq %rbx
; NOBMI2-NEXT:    movq %rsi, %rdx
; NOBMI2-NEXT:    notq %rdx
; NOBMI2-NEXT:    leaq (,%rdx,4), %rcx
; NOBMI2-NEXT:    leaq (%rdx,%rdx), %rax
; NOBMI2-NEXT:    xorq %rax, %rcx
; NOBMI2-NEXT:    leaq (,%rdx,8), %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $4, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $5, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $6, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $7, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $8, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $9, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $10, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $11, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $12, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $13, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $14, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $15, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $16, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $17, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $18, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $19, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $20, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $21, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $22, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $23, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $24, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $25, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $26, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $27, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $28, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $29, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $30, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $31, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $32, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $33, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $34, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $35, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $36, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $37, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $38, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $39, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $40, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $41, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $42, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $43, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $44, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $45, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $46, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    xorq %r8, %rcx
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $47, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $48, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $49, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $50, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $51, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $52, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $53, %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r8, %r9
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $55, %r10
; NOBMI2-NEXT:    xorq %r9, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $56, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $57, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $58, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $59, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $60, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    shlq $61, %rcx
; NOBMI2-NEXT:    xorq %r9, %rcx
; NOBMI2-NEXT:    movq %rdx, %r9
; NOBMI2-NEXT:    shlq $62, %r9
; NOBMI2-NEXT:    xorq %rcx, %r9
; NOBMI2-NEXT:    shlq $63, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    movq %rdx, %rcx
; NOBMI2-NEXT:    andq %rsi, %rcx
; NOBMI2-NEXT:    movq %rsi, %r8
; NOBMI2-NEXT:    xorq %rcx, %r8
; NOBMI2-NEXT:    movq %rcx, %r9
; NOBMI2-NEXT:    shrq %r9
; NOBMI2-NEXT:    orq %r8, %r9
; NOBMI2-NEXT:    notq %rdx
; NOBMI2-NEXT:    andq %rax, %rdx
; NOBMI2-NEXT:    leaq (%rdx,%rdx), %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    leaq (,%rdx,4), %r8
; NOBMI2-NEXT:    leaq (,%rdx,8), %r10
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $4, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $5, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $6, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $7, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $8, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $9, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $10, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $11, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $12, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $13, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $14, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $15, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $16, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $17, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $18, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $19, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r11
; NOBMI2-NEXT:    shlq $20, %r11
; NOBMI2-NEXT:    xorq %r10, %r11
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $21, %r8
; NOBMI2-NEXT:    xorq %r11, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $22, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $23, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $24, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $25, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $26, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $27, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $28, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $29, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $30, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $31, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $32, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $33, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $34, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r11
; NOBMI2-NEXT:    shlq $35, %r11
; NOBMI2-NEXT:    xorq %r10, %r11
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $36, %r8
; NOBMI2-NEXT:    xorq %r11, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $37, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $38, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $39, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $40, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $41, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $42, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $43, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $44, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $45, %rax
; NOBMI2-NEXT:    xorq %r10, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $46, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $47, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $48, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $49, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $50, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $51, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $52, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $53, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $54, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %rdx, %r10
; NOBMI2-NEXT:    shlq $55, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    xorq %rax, %r10
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $56, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $57, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $58, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $59, %r8
; NOBMI2-NEXT:    xorq %rax, %r8
; NOBMI2-NEXT:    movq %rdx, %rax
; NOBMI2-NEXT:    shlq $60, %rax
; NOBMI2-NEXT:    xorq %r8, %rax
; NOBMI2-NEXT:    movq %rdx, %r11
; NOBMI2-NEXT:    shlq $61, %r11
; NOBMI2-NEXT:    xorq %rax, %r11
; NOBMI2-NEXT:    movq %rdx, %r8
; NOBMI2-NEXT:    shlq $62, %r8
; NOBMI2-NEXT:    xorq %r11, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %r8, %rax
; NOBMI2-NEXT:    andq %r9, %rax
; NOBMI2-NEXT:    xorq %rax, %r9
; NOBMI2-NEXT:    movq %rax, %r10
; NOBMI2-NEXT:    shrq $2, %r10
; NOBMI2-NEXT:    orq %r9, %r10
; NOBMI2-NEXT:    notq %r8
; NOBMI2-NEXT:    andq %rdx, %r8
; NOBMI2-NEXT:    leaq (%r8,%r8), %rdx
; NOBMI2-NEXT:    xorq %r8, %rdx
; NOBMI2-NEXT:    leaq (,%r8,4), %r9
; NOBMI2-NEXT:    leaq (,%r8,8), %r11
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $4, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $5, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $6, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $7, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $8, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $9, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $10, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $11, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $12, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $13, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $14, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $15, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $16, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $17, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $18, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $19, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %rbx
; NOBMI2-NEXT:    shlq $20, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $21, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $22, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $23, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $24, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $25, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $26, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $27, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $28, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $29, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $30, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $31, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $32, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $33, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $34, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %rbx
; NOBMI2-NEXT:    shlq $35, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $36, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $37, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $38, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $39, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $40, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $41, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $42, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $43, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $44, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $45, %rdx
; NOBMI2-NEXT:    xorq %r11, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $46, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $47, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $48, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $49, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $50, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $51, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $52, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $53, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $54, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r8, %r11
; NOBMI2-NEXT:    shlq $55, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    xorq %rdx, %r11
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $56, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $57, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $58, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $59, %r9
; NOBMI2-NEXT:    xorq %rdx, %r9
; NOBMI2-NEXT:    movq %r8, %rdx
; NOBMI2-NEXT:    shlq $60, %rdx
; NOBMI2-NEXT:    xorq %r9, %rdx
; NOBMI2-NEXT:    movq %r8, %rbx
; NOBMI2-NEXT:    shlq $61, %rbx
; NOBMI2-NEXT:    xorq %rdx, %rbx
; NOBMI2-NEXT:    movq %r8, %r9
; NOBMI2-NEXT:    shlq $62, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r9, %rdx
; NOBMI2-NEXT:    andq %r10, %rdx
; NOBMI2-NEXT:    xorq %rdx, %r10
; NOBMI2-NEXT:    movq %rdx, %r11
; NOBMI2-NEXT:    shrq $4, %r11
; NOBMI2-NEXT:    orq %r10, %r11
; NOBMI2-NEXT:    notq %r9
; NOBMI2-NEXT:    andq %r8, %r9
; NOBMI2-NEXT:    leaq (%r9,%r9), %r8
; NOBMI2-NEXT:    xorq %r9, %r8
; NOBMI2-NEXT:    leaq (,%r9,4), %r10
; NOBMI2-NEXT:    leaq (,%r9,8), %rbx
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $4, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $5, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $6, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $7, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $8, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $9, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $10, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $11, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $12, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $13, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $14, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $15, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $16, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $17, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $18, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $19, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r14
; NOBMI2-NEXT:    shlq $20, %r14
; NOBMI2-NEXT:    xorq %rbx, %r14
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $21, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $22, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $23, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $24, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $25, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $26, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $27, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $28, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $29, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $30, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $31, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $32, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $33, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $34, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r14
; NOBMI2-NEXT:    shlq $35, %r14
; NOBMI2-NEXT:    xorq %rbx, %r14
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $36, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $37, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $38, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $39, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $40, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $41, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $42, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $43, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $44, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $45, %r8
; NOBMI2-NEXT:    xorq %rbx, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $46, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $47, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $48, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $49, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $50, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $51, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $52, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $53, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $54, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shlq $55, %rbx
; NOBMI2-NEXT:    xorq %r10, %rbx
; NOBMI2-NEXT:    xorq %r8, %rbx
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $56, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $57, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $58, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $59, %r10
; NOBMI2-NEXT:    xorq %r8, %r10
; NOBMI2-NEXT:    movq %r9, %r8
; NOBMI2-NEXT:    shlq $60, %r8
; NOBMI2-NEXT:    xorq %r10, %r8
; NOBMI2-NEXT:    movq %r9, %r14
; NOBMI2-NEXT:    shlq $61, %r14
; NOBMI2-NEXT:    xorq %r8, %r14
; NOBMI2-NEXT:    movq %r9, %r10
; NOBMI2-NEXT:    shlq $62, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    xorq %rbx, %r10
; NOBMI2-NEXT:    movq %r10, %r8
; NOBMI2-NEXT:    andq %r11, %r8
; NOBMI2-NEXT:    xorq %r8, %r11
; NOBMI2-NEXT:    movq %r8, %r14
; NOBMI2-NEXT:    shrq $8, %r14
; NOBMI2-NEXT:    orq %r11, %r14
; NOBMI2-NEXT:    notq %r10
; NOBMI2-NEXT:    andq %r9, %r10
; NOBMI2-NEXT:    leaq (%r10,%r10), %r9
; NOBMI2-NEXT:    xorq %r10, %r9
; NOBMI2-NEXT:    leaq (,%r10,4), %r11
; NOBMI2-NEXT:    leaq (,%r10,8), %rbx
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $4, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $5, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $6, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $7, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $8, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $9, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $10, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $11, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $12, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $13, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $14, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $15, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $16, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $17, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $18, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $19, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r15
; NOBMI2-NEXT:    shlq $20, %r15
; NOBMI2-NEXT:    xorq %rbx, %r15
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $21, %r11
; NOBMI2-NEXT:    xorq %r15, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $22, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $23, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $24, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $25, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $26, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $27, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $28, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $29, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $30, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $31, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $32, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $33, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $34, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r15
; NOBMI2-NEXT:    shlq $35, %r15
; NOBMI2-NEXT:    xorq %rbx, %r15
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $36, %r11
; NOBMI2-NEXT:    xorq %r15, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $37, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $38, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $39, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $40, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $41, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $42, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $43, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $44, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $45, %r9
; NOBMI2-NEXT:    xorq %rbx, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $46, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $47, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $48, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $49, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $50, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $51, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $52, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $53, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $54, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r10, %rbx
; NOBMI2-NEXT:    shlq $55, %rbx
; NOBMI2-NEXT:    xorq %r11, %rbx
; NOBMI2-NEXT:    xorq %r9, %rbx
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $56, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $57, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $58, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $59, %r11
; NOBMI2-NEXT:    xorq %r9, %r11
; NOBMI2-NEXT:    movq %r10, %r9
; NOBMI2-NEXT:    shlq $60, %r9
; NOBMI2-NEXT:    xorq %r11, %r9
; NOBMI2-NEXT:    movq %r10, %r15
; NOBMI2-NEXT:    shlq $61, %r15
; NOBMI2-NEXT:    xorq %r9, %r15
; NOBMI2-NEXT:    movq %r10, %r11
; NOBMI2-NEXT:    shlq $62, %r11
; NOBMI2-NEXT:    xorq %r15, %r11
; NOBMI2-NEXT:    xorq %rbx, %r11
; NOBMI2-NEXT:    movq %r11, %r9
; NOBMI2-NEXT:    andq %r14, %r9
; NOBMI2-NEXT:    xorq %r9, %r14
; NOBMI2-NEXT:    movq %r9, %rbx
; NOBMI2-NEXT:    shrq $16, %rbx
; NOBMI2-NEXT:    orq %r14, %rbx
; NOBMI2-NEXT:    notq %r11
; NOBMI2-NEXT:    andq %r10, %r11
; NOBMI2-NEXT:    leaq (%r11,%r11), %r10
; NOBMI2-NEXT:    xorq %r11, %r10
; NOBMI2-NEXT:    leaq (,%r11,4), %r14
; NOBMI2-NEXT:    leaq (,%r11,8), %r15
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    xorq %r10, %r14
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $4, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $5, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $6, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $7, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $8, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $9, %r14
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $10, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $11, %r10
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $12, %r14
; NOBMI2-NEXT:    xorq %r10, %r14
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $13, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $14, %r14
; NOBMI2-NEXT:    xorq %r10, %r14
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $15, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $16, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $17, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $18, %r14
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $19, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r12
; NOBMI2-NEXT:    shlq $20, %r12
; NOBMI2-NEXT:    xorq %r15, %r12
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $21, %r14
; NOBMI2-NEXT:    xorq %r12, %r14
; NOBMI2-NEXT:    xorq %r10, %r14
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $22, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $23, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $24, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $25, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $26, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $27, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $28, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $29, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $30, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $31, %r14
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $32, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $33, %r14
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $34, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r12
; NOBMI2-NEXT:    shlq $35, %r12
; NOBMI2-NEXT:    xorq %r15, %r12
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $36, %r14
; NOBMI2-NEXT:    xorq %r12, %r14
; NOBMI2-NEXT:    xorq %r10, %r14
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $37, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $38, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $39, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $40, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $41, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $42, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $43, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $44, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $45, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    xorq %r14, %r10
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $46, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $47, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $48, %r14
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $49, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $50, %r14
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $51, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $52, %r14
; NOBMI2-NEXT:    xorq %r15, %r14
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $53, %r15
; NOBMI2-NEXT:    xorq %r14, %r15
; NOBMI2-NEXT:    movq %r11, %r12
; NOBMI2-NEXT:    shlq $54, %r12
; NOBMI2-NEXT:    xorq %r15, %r12
; NOBMI2-NEXT:    movq %r11, %r14
; NOBMI2-NEXT:    shlq $55, %r14
; NOBMI2-NEXT:    xorq %r12, %r14
; NOBMI2-NEXT:    xorq %r10, %r14
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $56, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $57, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $58, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $59, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $60, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    movq %r11, %r15
; NOBMI2-NEXT:    shlq $61, %r15
; NOBMI2-NEXT:    xorq %r10, %r15
; NOBMI2-NEXT:    movq %r11, %r10
; NOBMI2-NEXT:    shlq $62, %r10
; NOBMI2-NEXT:    xorq %r15, %r10
; NOBMI2-NEXT:    shlq $63, %r11
; NOBMI2-NEXT:    xorq %r10, %r11
; NOBMI2-NEXT:    xorq %r14, %r11
; NOBMI2-NEXT:    movq %rdi, %r10
; NOBMI2-NEXT:    shlq $32, %r10
; NOBMI2-NEXT:    xorq %rdi, %r10
; NOBMI2-NEXT:    andq %rbx, %r10
; NOBMI2-NEXT:    andq %r11, %r10
; NOBMI2-NEXT:    xorq %rdi, %r10
; NOBMI2-NEXT:    movq %r10, %rdi
; NOBMI2-NEXT:    shlq $16, %rdi
; NOBMI2-NEXT:    xorq %r10, %rdi
; NOBMI2-NEXT:    andq %r9, %rdi
; NOBMI2-NEXT:    xorq %r10, %rdi
; NOBMI2-NEXT:    movq %rdi, %r9
; NOBMI2-NEXT:    shlq $8, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    andq %r8, %r9
; NOBMI2-NEXT:    xorq %rdi, %r9
; NOBMI2-NEXT:    movq %r9, %rdi
; NOBMI2-NEXT:    shlq $4, %rdi
; NOBMI2-NEXT:    xorq %r9, %rdi
; NOBMI2-NEXT:    andq %rdx, %rdi
; NOBMI2-NEXT:    xorq %r9, %rdi
; NOBMI2-NEXT:    leaq (,%rdi,4), %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    andq %rax, %rdx
; NOBMI2-NEXT:    xorq %rdi, %rdx
; NOBMI2-NEXT:    leaq (%rdx,%rdx), %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    andq %rcx, %rax
; NOBMI2-NEXT:    xorq %rdx, %rax
; NOBMI2-NEXT:    andq %rsi, %rax
; NOBMI2-NEXT:    popq %rbx
; NOBMI2-NEXT:    popq %r12
; NOBMI2-NEXT:    popq %r14
; NOBMI2-NEXT:    popq %r15
; NOBMI2-NEXT:    retq
  %res = call i64 @llvm.bdep.i64(i64 %val, i64 %mask)
  ret i64 %res
}

define i32 @bext_mask_zero(i32 %val) nounwind {
; BMI2-LABEL: bext_mask_zero:
; BMI2:       # %bb.0:
; BMI2-NEXT:    xorl %eax, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_mask_zero:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    xorl %eax, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 %val, i32 0)
  ret i32 %res
}

define i32 @bext_mask_allones(i32 %val) nounwind {
; BMI2-LABEL: bext_mask_allones:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movl %edi, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_mask_allones:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl %edi, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 %val, i32 -1)
  ret i32 %res
}

define i32 @bdep_mask_zero(i32 %val) nounwind {
; BMI2-LABEL: bdep_mask_zero:
; BMI2:       # %bb.0:
; BMI2-NEXT:    xorl %eax, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bdep_mask_zero:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    xorl %eax, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bdep.i32(i32 %val, i32 0)
  ret i32 %res
}

define i32 @bdep_mask_allones(i32 %val) nounwind {
; BMI2-LABEL: bdep_mask_allones:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movl %edi, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bdep_mask_allones:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl %edi, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bdep.i32(i32 %val, i32 -1)
  ret i32 %res
}

define i32 @bext_const_fold() nounwind {
; BMI2-LABEL: bext_const_fold:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movl $10, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bext_const_fold:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl $10, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bext.i32(i32 170, i32 204)
  ret i32 %res
}

define i32 @bdep_const_fold() nounwind {
; BMI2-LABEL: bdep_const_fold:
; BMI2:       # %bb.0:
; BMI2-NEXT:    movl $136, %eax
; BMI2-NEXT:    retq
;
; NOBMI2-LABEL: bdep_const_fold:
; NOBMI2:       # %bb.0:
; NOBMI2-NEXT:    movl $136, %eax
; NOBMI2-NEXT:    retq
  %res = call i32 @llvm.bdep.i32(i32 10, i32 204)
  ret i32 %res
}

declare i8 @llvm.bext.i8(i8, i8)
declare i16 @llvm.bext.i16(i16, i16)
declare i32 @llvm.bext.i32(i32, i32)
declare i64 @llvm.bext.i64(i64, i64)
declare i8 @llvm.bdep.i8(i8, i8)
declare i16 @llvm.bdep.i16(i16, i16)
declare i32 @llvm.bdep.i32(i32, i32)
declare i64 @llvm.bdep.i64(i64, i64)
