; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=x86_64 -O2 < %s | FileCheck %s

; Returning a boolean that is also the branch condition currently produces a
; redundant test/cmp instruction: the generated assembly contains a duplicate
; "testb $3, %dil; sete %al" sequence in the shared return block, in addition
; to the "testb $3, %dil; jne" used for the branch.

define i1 @bool_ret(i64 %x, ptr %y) {
; CHECK-LABEL: bool_ret:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    testb $3, %dil
; CHECK-NEXT:    jne .LBB0_2
; CHECK-NEXT:  # %bb.1: # %if.then
; CHECK-NEXT:    movl $0, (%rsi)
; CHECK-NEXT:  .LBB0_2: # %return
; CHECK-NEXT:    testb $3, %dil
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
entry:
  %rem = and i64 %x, 3
  %cmp = icmp eq i64 %rem, 0
  br i1 %cmp, label %if.then, label %return

if.then:
  store i32 0, ptr %y, align 4
  br label %return

return:
  ret i1 %cmp
}
