; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-- -O1 < %s | FileCheck %s

define void @test_drop_undef_when_hoisting(<4 x i8> %v0, i1 %c) {
; CHECK-LABEL: test_drop_undef_when_hoisting:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movdqa {{.*#+}} xmm1 = [1,1,1,1,u,u,u,u,u,u,u,u,u,u,u,u]
; CHECK-NEXT:    pcmpgtb %xmm0, %xmm1
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    movdqa {{.*#+}} xmm2 = [255,255,255,255,255,255,255,255]
; CHECK-NEXT:    jmp .LBB0_1
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_3: # %if.then
; CHECK-NEXT:    # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    pmullw %xmm1, %xmm1
; CHECK-NEXT:    pand %xmm2, %xmm1
; CHECK-NEXT:    packuswb %xmm1, %xmm1
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    jne .LBB0_5
; CHECK-NEXT:  .LBB0_1: # %loop
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    punpcklbw {{.*#+}} xmm1 = xmm1[0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7]
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    jne .LBB0_3
; CHECK-NEXT:  # %bb.2: # in Loop: Header=BB0_1 Depth=1
; CHECK-NEXT:    pshuflw {{.*#+}} xmm1 = xmm1[1,0,0,0,4,5,6,7]
; CHECK-NEXT:    packuswb %xmm1, %xmm1
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    je .LBB0_1
; CHECK-NEXT:  .LBB0_5: # %exit
; CHECK-NEXT:    retq
  entry:
    %cmp = icmp slt <4 x i8> %v0, splat (i8 1)
    %sext = sext <4 x i1> %cmp to <4 x i8>
    br label %loop

  loop:                                             ; preds = %if.end, %entry
    %val = phi <4 x i8> [ %sext, %entry ], [ %val.next, %if.end ]
    %shuffle = shufflevector <4 x i8> %val, <4 x i8> poison, <4 x i32> <i32 1, i32 0, i32 0, i32 0>
    br i1 %c, label %if.then, label %if.end

  if.then:                                          ; preds = %loop
    %mul = mul <4 x i8> %val, %val
    br label %if.end

  if.end:                                           ; preds = %if.then, %loop
    %val.next = phi <4 x i8> [ %mul, %if.then ], [ %shuffle, %loop ]
    br i1 %c, label %exit, label %loop

  exit:                                             ; preds = %if.end
    ret void
}
