# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=x86_64-pc-windows-msvc -run-pass=branch-folder -o - %s | FileCheck %s
---
name:            main
body:             |
  ; CHECK-LABEL: name: main
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x7ffff800), %bb.3(0x00000800)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x00000800)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2 (machine-block-address-taken, landing-pad, ehfunclet-entry):
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   CLEANUPRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3 (landing-pad, ehfunclet-entry):
  ; CHECK-NEXT:   CLEANUPRET
  bb.0:
    successors: %bb.1(0x7ffff800), %bb.5(0x00000800)
    JMP_1 %bb.1

  bb.1:
    successors: %bb.2(0x7ffff800), %bb.4(0x00000800)

    JMP_1 %bb.2

  bb.2:
    successors: %bb.3(0x7ffff800), %bb.4(0x00000800)

    JMP_1 %bb.3

  bb.3:
    successors: %bb.6(0x7ffff800)

    JMP_1 %bb.6

  bb.4 (machine-block-address-taken, landing-pad, ehfunclet-entry):
    successors: %bb.5(0x80000000)
    CLEANUPRET

  bb.5 (landing-pad, ehfunclet-entry):
    CLEANUPRET

  bb.6:
    RET 0
...
