; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

declare void @notify()

; using nuw lowers to cmp reg, 1
define void @br_trunc_nuw(ptr %p) {
; CHECK-LABEL: br_trunc_nuw:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmpb $1, (%rdi)
; CHECK-NEXT:    je notify@PLT # TAILCALL
; CHECK-NEXT:  # %bb.1: # %ret
; CHECK-NEXT:    retq
  %v = load i8, ptr %p, align 1
  %b = trunc nuw i8 %v to i1
  br i1 %b, label %taken, label %ret
taken:
  tail call void @notify()
  br label %ret
ret:
  ret void
}

; using range lowers to cmp reg, 1
define void @br_trunc_range(ptr %p) {
; CHECK-LABEL: br_trunc_range:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmpb $1, (%rdi)
; CHECK-NEXT:    je notify@PLT # TAILCALL
; CHECK-NEXT:  # %bb.1: # %ret
; CHECK-NEXT:    retq
  %v = load i8, ptr %p, align 1, !range !0
  %b = trunc i8 %v to i1
  br i1 %b, label %taken, label %ret
taken:
  tail call void @notify()
  br label %ret
ret:
  ret void
}

; using nuw and range lowers to cmp reg, 1
define void @br_trunc_nuw_and_range(ptr %p) {
; CHECK-LABEL: br_trunc_nuw_and_range:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmpb $1, (%rdi)
; CHECK-NEXT:    je notify@PLT # TAILCALL
; CHECK-NEXT:  # %bb.1: # %ret
; CHECK-NEXT:    retq
  %v = load i8, ptr %p, align 1, !range !0
  %b = trunc nuw i8 %v to i1
  br i1 %b, label %taken, label %ret
taken:
  tail call void @notify()
  br label %ret
ret:
  ret void
}

; atomic load currently uses cmp reg, 1
define void @br_atomic_trunc_range(ptr %p) {
; CHECK-LABEL: br_atomic_trunc_range:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl (%rdi), %eax
; CHECK-NEXT:    cmpb $1, %al
; CHECK-NEXT:    je notify@PLT # TAILCALL
; CHECK-NEXT:  # %bb.1: # %ret
; CHECK-NEXT:    retq
  %v = load atomic i8, ptr %p monotonic, align 1, !range !0
  %b = trunc i8 %v to i1
  br i1 %b, label %taken, label %ret
taken:
  tail call void @notify()
  br label %ret
ret:
  ret void
}

; plain trunc with no range info correctly emits test reg, 1
define void @br_trunc(ptr %p) {
; CHECK-LABEL: br_trunc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testb $1, (%rdi)
; CHECK-NEXT:    jne notify@PLT # TAILCALL
; CHECK-NEXT:  # %bb.1: # %ret
; CHECK-NEXT:    retq
  %v = load i8, ptr %p, align 1
  %b = trunc i8 %v to i1
  br i1 %b, label %taken, label %ret
taken:
  tail call void @notify()
  br label %ret
ret:
  ret void
}

!0 = !{i8 0, i8 2}
