; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=i686-- -verify-machineinstrs < %s | FileCheck %s

@var = global i32 0, align 4

define i32 @test1() {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    #APP
; CHECK-NEXT:    jmp .Ltmp0
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    retl
; CHECK-NEXT:  .Ltmp0: # Block address taken
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    retl
  callbr void asm sideeffect "jmp ${1:l}", "*m,X,~{dirflag},~{fpsr},~{flags}"(i32* nonnull @var, i8* blockaddress(@test1, %1))
          to label %2 [label %1]

1:                                                ; preds = %0
  br label %2

2:                                                ; preds = %0, %1
  %3 = phi i32 [ 1, %1 ], [ 0, %0 ]
  ret i32 %3
}
