; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --default-march x86_64-unknown-linux-gnu --version 5
; RUN: llc -mattr=sse2 -mtriple=x86_64 -denormal-fp-math=preserve-sign < %s | FileCheck -check-prefix=PRE-SIGN-SSE2 %s
; RUN: llc -mattr=sse2 -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=IEEE-DENORMAL-SSE2 %s
; RUN: llc -mattr=sse2 -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=DYN-DENORMAL-SSE2 %s
; RUN: llc -mattr=+avx -mtriple=x86_64 -denormal-fp-math=preserve-sign < %s | FileCheck -check-prefix=PRE-SIGN-AVX %s
; RUN: llc -mattr=+avx -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=IEEE-DENORMAL-AVX %s
; RUN: llc -mattr=+avx -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=DYN-DENORMAL-AVX %s
; RUN: llc -mattr=+avx2 -mtriple=x86_64 -denormal-fp-math=preserve-sign < %s | FileCheck -check-prefix=PRE-SIGN-AVX2 %s
; RUN: llc -mattr=+avx2 -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=IEEE-DENORMAL-AVX2 %s
; RUN: llc -mattr=+avx2 -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=DYN-DENORMAL-AVX2 %s
; RUN: llc -mattr=+avx512f -mtriple=x86_64 -denormal-fp-math=preserve-sign < %s | FileCheck -check-prefix=PRE-SIGN-AVX512F %s
; RUN: llc -mattr=+avx512f -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=IEEE-DENORMAL-AVX512F %s
; RUN: llc -mattr=+avx512f -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=DYN-DENORMAL-AVX512F %s
; RUN: llc -mattr=+avx512bw -mtriple=x86_64 -denormal-fp-math=preserve-sign < %s | FileCheck -check-prefix=PRE-SIGN-AVX512BW %s
; RUN: llc -mattr=+avx512bw -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=IEEE-DENORMAL-AVX512BW %s
; RUN: llc -mattr=+avx512bw -mtriple=x86_64 -denormal-fp-math=ieee < %s | FileCheck -check-prefix=DYN-DENORMAL-AVX512BW %s

define double @test_bad_subnormal() {
; PRE-SIGN-SSE2-LABEL: test_bad_subnormal:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: test_bad_subnormal:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: test_bad_subnormal:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: test_bad_subnormal:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: test_bad_subnormal:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: test_bad_subnormal:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: test_bad_subnormal:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: test_bad_subnormal:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: test_bad_subnormal:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: test_bad_subnormal:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: test_bad_subnormal:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: test_bad_subnormal:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: test_bad_subnormal:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: test_bad_subnormal:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: test_bad_subnormal:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    vmovsd {{.*#+}} xmm0 = [NaN,0.0E+0]
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canon = call double @llvm.canonicalize(double 0x7ff8000000000001) ; Nan
  ret double %canon
}

define void @canonicalize_denormal1_f32_pre_sign(float addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_f32_pre_sign:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f32_pre_sign:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f32_pre_sign:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_f32_pre_sign:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_f32_pre_sign:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_f32_pre_sign:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_f32_pre_sign:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f32_pre_sign:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f32_pre_sign:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_f32_pre_sign:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f32_pre_sign:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f32_pre_sign:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_f32_pre_sign:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f32_pre_sign:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f32_pre_sign:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call float @llvm.canonicalize.f32(float bitcast (i32 2155872255 to float))
  store float %canonicalized, float addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_f64_pre_sign(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_f64_pre_sign:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-SSE2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f64_pre_sign:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f64_pre_sign:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_f64_pre_sign:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_f64_pre_sign:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_f64_pre_sign:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_f64_pre_sign:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f64_pre_sign:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f64_pre_sign:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_f64_pre_sign:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX512F-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f64_pre_sign:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f64_pre_sign:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_f64_pre_sign:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX512BW-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f64_pre_sign:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f64_pre_sign:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double bitcast (i64 9227875636482146303 to double))
  store double %canonicalized, double addrspace(1)* %out
  ret void
}


define void @canonicalize_qnan_f64(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_qnan_f64:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-SSE2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_qnan_f64:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_qnan_f64:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_qnan_f64:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_qnan_f64:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_qnan_f64:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_qnan_f64:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_qnan_f64:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_qnan_f64:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_qnan_f64:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX512F-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_qnan_f64:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_qnan_f64:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_qnan_f64:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX512BW-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_qnan_f64:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_qnan_f64:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double 0x7FF8000000000000)
  store double %canonicalized, double addrspace(1)* %out
  ret void
}

define void @canonicalize_qnan_value_neg1_f64(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_qnan_value_neg1_f64:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movq $-1, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_qnan_value_neg1_f64:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movq $-1, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_qnan_value_neg1_f64:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movq $-1, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_qnan_value_neg1_f64:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movq $-1, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_qnan_value_neg1_f64:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movq $-1, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_qnan_value_neg1_f64:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movq $-1, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_qnan_value_neg1_f64:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movq $-1, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_qnan_value_neg1_f64:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movq $-1, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_qnan_value_neg1_f64:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movq $-1, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_qnan_value_neg1_f64:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movq $-1, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_qnan_value_neg1_f64:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movq $-1, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_qnan_value_neg1_f64:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movq $-1, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_qnan_value_neg1_f64:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movq $-1, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_qnan_value_neg1_f64:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movq $-1, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_qnan_value_neg1_f64:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movq $-1, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double bitcast (i64 -1 to double))
  store double %canonicalized, double addrspace(1)* %out
  ret void
}

define void @canonicalize_qnan_value_neg2_f64(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_qnan_value_neg2_f64:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movq $-2, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_qnan_value_neg2_f64:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movq $-2, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_qnan_value_neg2_f64:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movq $-2, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_qnan_value_neg2_f64:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movq $-2, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_qnan_value_neg2_f64:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movq $-2, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_qnan_value_neg2_f64:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movq $-2, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_qnan_value_neg2_f64:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movq $-2, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_qnan_value_neg2_f64:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movq $-2, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_qnan_value_neg2_f64:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movq $-2, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_qnan_value_neg2_f64:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movq $-2, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_qnan_value_neg2_f64:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movq $-2, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_qnan_value_neg2_f64:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movq $-2, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_qnan_value_neg2_f64:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movq $-2, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_qnan_value_neg2_f64:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movq $-2, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_qnan_value_neg2_f64:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movq $-2, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double bitcast (i64 -2 to double))
  store double %canonicalized, double addrspace(1)* %out
  ret void
}

define void @canonicalize_snan0_value_f64(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_snan0_value_f64:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-SSE2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_snan0_value_f64:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_snan0_value_f64:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_snan0_value_f64:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_snan0_value_f64:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_snan0_value_f64:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_snan0_value_f64:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_snan0_value_f64:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_snan0_value_f64:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_snan0_value_f64:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX512F-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_snan0_value_f64:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_snan0_value_f64:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_snan0_value_f64:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX512BW-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_snan0_value_f64:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_snan0_value_f64:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double bitcast (i64 9218868437227405313 to double))
  store double %canonicalized, double addrspace(1)* %out
  ret void
}

define void @canonicalize_undef(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_undef:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-SSE2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_undef:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_undef:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_undef:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_undef:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_undef:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_undef:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_undef:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_undef:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_undef:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX512F-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_undef:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_undef:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_undef:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; PRE-SIGN-AVX512BW-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_undef:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; IEEE-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_undef:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; DYN-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double undef)
  store double %canonicalized, double addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_f32_ieee(float addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_f32_ieee:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f32_ieee:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f32_ieee:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_f32_ieee:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_f32_ieee:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_f32_ieee:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_f32_ieee:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f32_ieee:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f32_ieee:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_f32_ieee:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f32_ieee:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f32_ieee:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_f32_ieee:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f32_ieee:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f32_ieee:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call float @llvm.canonicalize.f32(float bitcast (i32 2155872255 to float))
  store float %canonicalized, float addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_f64_ieee(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_f64_ieee:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-SSE2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f64_ieee:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f64_ieee:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_f64_ieee:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_f64_ieee:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_f64_ieee:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_f64_ieee:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f64_ieee:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f64_ieee:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_f64_ieee:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX512F-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f64_ieee:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f64_ieee:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_f64_ieee:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX512BW-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f64_ieee:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f64_ieee:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double bitcast (i64 9227875636482146303 to double))
  store double %canonicalized, double addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_f32_dynamic(float addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_f32_dynamic:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f32_dynamic:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f32_dynamic:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_f32_dynamic:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_f32_dynamic:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_f32_dynamic:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_f32_dynamic:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f32_dynamic:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f32_dynamic:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_f32_dynamic:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f32_dynamic:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f32_dynamic:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_f32_dynamic:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movl $-2147483648, (%rdi) # imm = 0x80000000
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f32_dynamic:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f32_dynamic:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movl $-2139095041, (%rdi) # imm = 0x807FFFFF
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call float @llvm.canonicalize.f32(float bitcast (i32 2155872255 to float))
  store float %canonicalized, float addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_f64_dynamic(double addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_f64_dynamic:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-SSE2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f64_dynamic:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_f64_dynamic:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-SSE2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_f64_dynamic:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_f64_dynamic:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_f64_dynamic:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_f64_dynamic:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX2-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f64_dynamic:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_f64_dynamic:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX2-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_f64_dynamic:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX512F-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f64_dynamic:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_f64_dynamic:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX512F-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_f64_dynamic:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; PRE-SIGN-AVX512BW-NEXT:    movq %rax, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f64_dynamic:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; IEEE-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_f64_dynamic:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movabsq $-9218868437227405313, %rax # imm = 0x800FFFFFFFFFFFFF
; DYN-DENORMAL-AVX512BW-NEXT:    movq %rax, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call double @llvm.canonicalize.f64(double bitcast (i64 9227875636482146303 to double))
  store double %canonicalized, double addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_bfloat_pre_sign(bfloat addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_bfloat_pre_sign:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call bfloat @llvm.canonicalize.bf16(bfloat bitcast (i16 32768 to bfloat))
  store bfloat %canonicalized, bfloat addrspace(1)* %out
  ret void
}


define void @canonicalize_denormal1_bfloat_ieee(bfloat addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_bfloat_ieee:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_bfloat_ieee:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_bfloat_ieee:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_bfloat_ieee:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_bfloat_ieee:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_bfloat_ieee:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_bfloat_ieee:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_bfloat_ieee:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_bfloat_ieee:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_bfloat_ieee:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_bfloat_ieee:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_bfloat_ieee:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_bfloat_ieee:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_bfloat_ieee:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_bfloat_ieee:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call bfloat @llvm.canonicalize.bf16(bfloat bitcast (i16 32768 to bfloat))
  store bfloat %canonicalized, bfloat addrspace(1)* %out
  ret void
}


define void @canonicalize_denormal1_bfloat_dynamic(bfloat addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_bfloat_dynamic:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_bfloat_dynamic:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_bfloat_dynamic:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_bfloat_dynamic:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_bfloat_dynamic:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_bfloat_dynamic:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_bfloat_dynamic:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_bfloat_dynamic:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_bfloat_dynamic:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_bfloat_dynamic:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_bfloat_dynamic:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_bfloat_dynamic:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_bfloat_dynamic:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_bfloat_dynamic:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_bfloat_dynamic:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    movw $-32768, (%rdi) # imm = 0x8000
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call bfloat @llvm.canonicalize.bf16(bfloat bitcast (i16 32768 to bfloat))
  store bfloat %canonicalized, bfloat addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_half_pre_sign(half addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_half_pre_sign:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; PRE-SIGN-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; PRE-SIGN-SSE2-NEXT:    movw %ax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_half_pre_sign:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; IEEE-DENORMAL-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; IEEE-DENORMAL-SSE2-NEXT:    movw %ax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_half_pre_sign:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; DYN-DENORMAL-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; DYN-DENORMAL-SSE2-NEXT:    movw %ax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_half_pre_sign:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_half_pre_sign:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_half_pre_sign:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_half_pre_sign:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_half_pre_sign:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_half_pre_sign:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_half_pre_sign:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_half_pre_sign:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_half_pre_sign:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_half_pre_sign:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_half_pre_sign:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_half_pre_sign:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call half @llvm.canonicalize.f16(half bitcast (i16 32768 to half))
  store half %canonicalized, half addrspace(1)* %out
  ret void
}


define void @canonicalize_denormal1_half_ieee(half addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_half_ieee:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; PRE-SIGN-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; PRE-SIGN-SSE2-NEXT:    movw %ax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_half_ieee:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; IEEE-DENORMAL-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; IEEE-DENORMAL-SSE2-NEXT:    movw %ax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_half_ieee:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; DYN-DENORMAL-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; DYN-DENORMAL-SSE2-NEXT:    movw %ax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_half_ieee:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_half_ieee:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_half_ieee:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_half_ieee:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_half_ieee:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_half_ieee:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_half_ieee:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_half_ieee:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_half_ieee:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_half_ieee:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_half_ieee:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_half_ieee:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call half @llvm.canonicalize.f16(half bitcast (i16 32768 to half))
  store half %canonicalized, half addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_half_dynamic(half addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_half_dynamic:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; PRE-SIGN-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; PRE-SIGN-SSE2-NEXT:    movw %ax, (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_half_dynamic:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; IEEE-DENORMAL-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; IEEE-DENORMAL-SSE2-NEXT:    movw %ax, (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_half_dynamic:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    pinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; DYN-DENORMAL-SSE2-NEXT:    pextrw $0, %xmm0, %eax
; DYN-DENORMAL-SSE2-NEXT:    movw %ax, (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_half_dynamic:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_half_dynamic:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_half_dynamic:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_half_dynamic:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_half_dynamic:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_half_dynamic:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX2-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_half_dynamic:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_half_dynamic:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_half_dynamic:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX512F-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_half_dynamic:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; PRE-SIGN-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_half_dynamic:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; IEEE-DENORMAL-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_half_dynamic:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    vpinsrw $0, {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; DYN-DENORMAL-AVX512BW-NEXT:    vpextrw $0, %xmm0, (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call half @llvm.canonicalize.f16(half bitcast (i16 32768 to half))
  store half %canonicalized, half addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_x86_fp80_pre_sign(x86_fp80 addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    fldz
; PRE-SIGN-SSE2-NEXT:    fstpt (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-SSE2-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-SSE2-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    fldz
; PRE-SIGN-AVX-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    fldz
; PRE-SIGN-AVX2-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX2-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX2-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    fldz
; PRE-SIGN-AVX512F-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX512F-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX512F-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    fldz
; PRE-SIGN-AVX512BW-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX512BW-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_pre_sign:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX512BW-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
    %canonicalized = call x86_fp80 @llvm.canonicalize.f80(x86_fp80 0xK00000000000000000001)
    store x86_fp80 %canonicalized, x86_fp80 addrspace(1)* %out
    ret void
}

define void @canonicalize_denormal1_x86_fp80_dynamic(x86_fp80 addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    fldz
; PRE-SIGN-SSE2-NEXT:    fstpt (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-SSE2-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-SSE2-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    fldz
; PRE-SIGN-AVX-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    fldz
; PRE-SIGN-AVX2-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX2-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX2-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    fldz
; PRE-SIGN-AVX512F-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX512F-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX512F-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    fldz
; PRE-SIGN-AVX512BW-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX512BW-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_dynamic:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX512BW-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call x86_fp80 @llvm.canonicalize.f80(x86_fp80 0xK00000000000000000001)
  store x86_fp80 %canonicalized, x86_fp80 addrspace(1)* %out
  ret void
}

define void @canonicalize_denormal1_x86_fp80_ieee(x86_fp80 addrspace(1)* %out) {
; PRE-SIGN-SSE2-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; PRE-SIGN-SSE2:       # %bb.0:
; PRE-SIGN-SSE2-NEXT:    fldz
; PRE-SIGN-SSE2-NEXT:    fstpt (%rdi)
; PRE-SIGN-SSE2-NEXT:    retq
;
; IEEE-DENORMAL-SSE2-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; IEEE-DENORMAL-SSE2:       # %bb.0:
; IEEE-DENORMAL-SSE2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-SSE2-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-SSE2-NEXT:    retq
;
; DYN-DENORMAL-SSE2-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; DYN-DENORMAL-SSE2:       # %bb.0:
; DYN-DENORMAL-SSE2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-SSE2-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-SSE2-NEXT:    retq
;
; PRE-SIGN-AVX-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; PRE-SIGN-AVX:       # %bb.0:
; PRE-SIGN-AVX-NEXT:    fldz
; PRE-SIGN-AVX-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX-NEXT:    retq
;
; IEEE-DENORMAL-AVX-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; IEEE-DENORMAL-AVX:       # %bb.0:
; IEEE-DENORMAL-AVX-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX-NEXT:    retq
;
; DYN-DENORMAL-AVX-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; DYN-DENORMAL-AVX:       # %bb.0:
; DYN-DENORMAL-AVX-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX-NEXT:    retq
;
; PRE-SIGN-AVX2-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; PRE-SIGN-AVX2:       # %bb.0:
; PRE-SIGN-AVX2-NEXT:    fldz
; PRE-SIGN-AVX2-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX2-NEXT:    retq
;
; IEEE-DENORMAL-AVX2-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; IEEE-DENORMAL-AVX2:       # %bb.0:
; IEEE-DENORMAL-AVX2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX2-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX2-NEXT:    retq
;
; DYN-DENORMAL-AVX2-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; DYN-DENORMAL-AVX2:       # %bb.0:
; DYN-DENORMAL-AVX2-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX2-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX2-NEXT:    retq
;
; PRE-SIGN-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; PRE-SIGN-AVX512F:       # %bb.0:
; PRE-SIGN-AVX512F-NEXT:    fldz
; PRE-SIGN-AVX512F-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX512F-NEXT:    retq
;
; IEEE-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; IEEE-DENORMAL-AVX512F:       # %bb.0:
; IEEE-DENORMAL-AVX512F-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX512F-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX512F-NEXT:    retq
;
; DYN-DENORMAL-AVX512F-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; DYN-DENORMAL-AVX512F:       # %bb.0:
; DYN-DENORMAL-AVX512F-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX512F-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX512F-NEXT:    retq
;
; PRE-SIGN-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; PRE-SIGN-AVX512BW:       # %bb.0:
; PRE-SIGN-AVX512BW-NEXT:    fldz
; PRE-SIGN-AVX512BW-NEXT:    fstpt (%rdi)
; PRE-SIGN-AVX512BW-NEXT:    retq
;
; IEEE-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; IEEE-DENORMAL-AVX512BW:       # %bb.0:
; IEEE-DENORMAL-AVX512BW-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; IEEE-DENORMAL-AVX512BW-NEXT:    fstpt (%rdi)
; IEEE-DENORMAL-AVX512BW-NEXT:    retq
;
; DYN-DENORMAL-AVX512BW-LABEL: canonicalize_denormal1_x86_fp80_ieee:
; DYN-DENORMAL-AVX512BW:       # %bb.0:
; DYN-DENORMAL-AVX512BW-NEXT:    fldt {{\.?LCPI[0-9]+_[0-9]+}}(%rip)
; DYN-DENORMAL-AVX512BW-NEXT:    fstpt (%rdi)
; DYN-DENORMAL-AVX512BW-NEXT:    retq
  %canonicalized = call x86_fp80 @llvm.canonicalize.f80(x86_fp80 0xK00000000000000000001)
  store x86_fp80 %canonicalized, x86_fp80 addrspace(1)* %out
  ret void
}
