; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64 | FileCheck %s

define float @cbrt_f32_fmf_ieee(float %x) nounwind {
; CHECK-LABEL: cbrt_f32_fmf_ieee:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jmp cbrtf@PLT # TAILCALL
  %r = call nsz ninf afn float @llvm.cbrt.f32(float %x)
  ret float %r
}

define float @cbrt_f32_fmf_daz(float %x) #0 {
; CHECK-LABEL: cbrt_f32_fmf_daz:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jmp cbrtf@PLT # TAILCALL
  %r = call nsz ninf afn float @llvm.cbrt.f32(float %x)
  ret float %r
}

define double @cbrt_f64_fmf(double %x) nounwind {
; CHECK-LABEL: cbrt_f64_fmf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    jmp cbrt@PLT # TAILCALL
  %r = call nsz ninf afn double @llvm.cbrt.f64(double %x)
  ret double %r
}

define <4 x float> @cbrt_v4f32_fmf(<4 x float> %x) nounwind {
; CHECK-LABEL: cbrt_v4f32_fmf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $56, %rsp
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; CHECK-NEXT:    callq cbrtf@PLT
; CHECK-NEXT:    movaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; CHECK-NEXT:    callq cbrtf@PLT
; CHECK-NEXT:    unpcklps (%rsp), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = xmm0[0],mem[0],xmm0[1],mem[1]
; CHECK-NEXT:    movaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    callq cbrtf@PLT
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    callq cbrtf@PLT
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    unpcklps {{.*#+}} xmm1 = xmm1[0],xmm0[0],xmm1[1],xmm0[1]
; CHECK-NEXT:    unpcklpd (%rsp), %xmm1 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm1 = xmm1[0],mem[0]
; CHECK-NEXT:    movaps %xmm1, %xmm0
; CHECK-NEXT:    addq $56, %rsp
; CHECK-NEXT:    retq
  %r = call fast <4 x float> @llvm.cbrt.v4f32(<4 x float> %x)
  ret <4 x float> %r
}

define <2 x double> @cbrt_v2f64_fmf(<2 x double> %x) nounwind {
; CHECK-LABEL: cbrt_v2f64_fmf:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    movaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    callq cbrt@PLT
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    movaps (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; CHECK-NEXT:    callq cbrt@PLT
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movlhps {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; CHECK-NEXT:    movaps %xmm1, %xmm0
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    retq
  %r = call fast <2 x double> @llvm.cbrt.v2f64(<2 x double> %x)
  ret <2 x double> %r
}

attributes #0 = { nounwind "denormal-fp-math"="ieee,preserve-sign" }
