; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -print-schedule -mcpu=x86-64 -mattr=+clflushopt | FileCheck %s --check-prefix=CHECK --check-prefix=GENERIC
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -print-schedule -mcpu=goldmont | FileCheck %s --check-prefix=CHECK --check-prefix=GLM
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -print-schedule -mcpu=skylake | FileCheck %s --check-prefix=CHECK --check-prefix=SKYLAKE
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -print-schedule -mcpu=skx | FileCheck %s --check-prefix=CHECK --check-prefix=SKX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -print-schedule -mcpu=znver1 | FileCheck %s --check-prefix=CHECK --check-prefix=ZNVER1

define void @clflushopt(i8* %p) nounwind {
; GENERIC-LABEL: clflushopt:
; GENERIC:       # %bb.0:
; GENERIC-NEXT:    clflushopt (%rdi) # sched: [5:1.00]
; GENERIC-NEXT:    retq # sched: [1:1.00]
;
; GLM-LABEL: clflushopt:
; GLM:       # %bb.0:
; GLM-NEXT:    clflushopt (%rdi) # sched: [3:1.00]
; GLM-NEXT:    retq # sched: [4:1.00]
;
; SKYLAKE-LABEL: clflushopt:
; SKYLAKE:       # %bb.0:
; SKYLAKE-NEXT:    clflushopt (%rdi) # sched: [2:1.00]
; SKYLAKE-NEXT:    retq # sched: [7:1.00]
;
; SKX-LABEL: clflushopt:
; SKX:       # %bb.0:
; SKX-NEXT:    clflushopt (%rdi) # sched: [2:1.00]
; SKX-NEXT:    retq # sched: [7:1.00]
;
; ZNVER1-LABEL: clflushopt:
; ZNVER1:       # %bb.0:
; ZNVER1-NEXT:    clflushopt (%rdi) # sched: [8:0.50]
; ZNVER1-NEXT:    retq # sched: [1:0.50]
  tail call void @llvm.x86.clflushopt(i8* %p)
  ret void
}
declare void @llvm.x86.clflushopt(i8*) nounwind
