; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx,+pclmul | FileCheck %s --check-prefixes=AVX1
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx2,+pclmul | FileCheck %s --check-prefixes=AVX2,AVX2-PCLMUL
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx2,+vpclmulqdq | FileCheck %s --check-prefixes=AVX2,AVX2-VPCLMULQDQ
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx512vl,+vpclmulqdq | FileCheck %s --check-prefixes=AVX512

define <32 x i8> @clmul_v32i8(<32 x i8> %a, <32 x i8> %b) nounwind {
; AVX1-LABEL: clmul_v32i8:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vandps %ymm2, %ymm1, %ymm3
; AVX1-NEXT:    vextractf128 $1, %ymm3, %xmm4
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm10 = [170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170]
; AVX1-NEXT:    vandps %ymm0, %ymm10, %ymm9
; AVX1-NEXT:    vextractf128 $1, %ymm9, %xmm7
; AVX1-NEXT:    vpmullw %xmm4, %xmm7, %xmm5
; AVX1-NEXT:    vpmullw %xmm3, %xmm9, %xmm6
; AVX1-NEXT:    vinsertf128 $1, %xmm5, %ymm6, %ymm6
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm5 = [255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0]
; AVX1-NEXT:    vandps %ymm5, %ymm6, %ymm11
; AVX1-NEXT:    vandnps %xmm3, %xmm5, %xmm6
; AVX1-NEXT:    vmovaps %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vpmaddubsw %xmm6, %xmm9, %xmm8
; AVX1-NEXT:    vpsllw $8, %xmm8, %xmm12
; AVX1-NEXT:    vandnps %xmm4, %xmm5, %xmm8
; AVX1-NEXT:    vpmaddubsw %xmm8, %xmm7, %xmm13
; AVX1-NEXT:    vpsllw $8, %xmm13, %xmm13
; AVX1-NEXT:    vinsertf128 $1, %xmm13, %ymm12, %ymm12
; AVX1-NEXT:    vorps %ymm12, %ymm11, %ymm11
; AVX1-NEXT:    vandps %ymm1, %ymm10, %ymm10
; AVX1-NEXT:    vextractf128 $1, %ymm10, %xmm12
; AVX1-NEXT:    vandps %ymm2, %ymm0, %ymm1
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm0
; AVX1-NEXT:    vpmullw %xmm0, %xmm12, %xmm13
; AVX1-NEXT:    vpmullw %xmm1, %xmm10, %xmm14
; AVX1-NEXT:    vinsertf128 $1, %xmm13, %ymm14, %ymm13
; AVX1-NEXT:    vandnps %xmm10, %xmm5, %xmm14
; AVX1-NEXT:    vpmaddubsw %xmm14, %xmm1, %xmm15
; AVX1-NEXT:    vpsllw $8, %xmm15, %xmm15
; AVX1-NEXT:    vandnps %xmm12, %xmm5, %xmm2
; AVX1-NEXT:    vpmaddubsw %xmm2, %xmm0, %xmm6
; AVX1-NEXT:    vpsllw $8, %xmm6, %xmm6
; AVX1-NEXT:    vinsertf128 $1, %xmm6, %ymm15, %ymm6
; AVX1-NEXT:    vandps %ymm5, %ymm13, %ymm13
; AVX1-NEXT:    vorps %ymm6, %ymm13, %ymm6
; AVX1-NEXT:    vxorps %ymm6, %ymm11, %ymm6
; AVX1-NEXT:    vpmullw %xmm7, %xmm12, %xmm11
; AVX1-NEXT:    vpmullw %xmm10, %xmm9, %xmm10
; AVX1-NEXT:    vinsertf128 $1, %xmm11, %ymm10, %ymm10
; AVX1-NEXT:    vpmaddubsw %xmm14, %xmm9, %xmm9
; AVX1-NEXT:    vpmaddubsw %xmm2, %xmm7, %xmm2
; AVX1-NEXT:    vpsllw $8, %xmm9, %xmm7
; AVX1-NEXT:    vpsllw $8, %xmm2, %xmm2
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm7, %ymm2
; AVX1-NEXT:    vandps %ymm5, %ymm10, %ymm7
; AVX1-NEXT:    vorps %ymm2, %ymm7, %ymm2
; AVX1-NEXT:    vpmullw %xmm4, %xmm0, %xmm4
; AVX1-NEXT:    vpmullw %xmm3, %xmm1, %xmm3
; AVX1-NEXT:    vinsertf128 $1, %xmm4, %ymm3, %ymm3
; AVX1-NEXT:    vandps %ymm5, %ymm3, %ymm3
; AVX1-NEXT:    vpmaddubsw {{[-0-9]+}}(%r{{[sb]}}p), %xmm1, %xmm1 # 16-byte Folded Reload
; AVX1-NEXT:    vpmaddubsw %xmm8, %xmm0, %xmm0
; AVX1-NEXT:    vpsllw $8, %xmm1, %xmm1
; AVX1-NEXT:    vpsllw $8, %xmm0, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm1, %ymm0
; AVX1-NEXT:    vorps %ymm0, %ymm3, %ymm0
; AVX1-NEXT:    vxorps %ymm2, %ymm0, %ymm0
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vandnps %ymm6, %ymm2, %ymm1
; AVX1-NEXT:    vandps %ymm2, %ymm0, %ymm0
; AVX1-NEXT:    vorps %ymm1, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmul_v32i8:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm2 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX2-NEXT:    vpand %ymm2, %ymm1, %ymm3
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm4 = [170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170]
; AVX2-NEXT:    vpand %ymm4, %ymm0, %ymm5
; AVX2-NEXT:    vpmullw %ymm3, %ymm5, %ymm6
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm7 = [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]
; AVX2-NEXT:    vpand %ymm7, %ymm6, %ymm6
; AVX2-NEXT:    vpandn %ymm3, %ymm7, %ymm8
; AVX2-NEXT:    vpmaddubsw %ymm8, %ymm5, %ymm9
; AVX2-NEXT:    vpsllw $8, %ymm9, %ymm9
; AVX2-NEXT:    vpor %ymm6, %ymm9, %ymm6
; AVX2-NEXT:    vpand %ymm4, %ymm1, %ymm1
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpmullw %ymm1, %ymm0, %ymm4
; AVX2-NEXT:    vpand %ymm7, %ymm4, %ymm4
; AVX2-NEXT:    vpandn %ymm1, %ymm7, %ymm9
; AVX2-NEXT:    vpmaddubsw %ymm9, %ymm0, %ymm10
; AVX2-NEXT:    vpsllw $8, %ymm10, %ymm10
; AVX2-NEXT:    vpor %ymm4, %ymm10, %ymm4
; AVX2-NEXT:    vpxor %ymm6, %ymm4, %ymm4
; AVX2-NEXT:    vpandn %ymm4, %ymm2, %ymm4
; AVX2-NEXT:    vpmullw %ymm1, %ymm5, %ymm1
; AVX2-NEXT:    vpand %ymm7, %ymm1, %ymm1
; AVX2-NEXT:    vpmaddubsw %ymm9, %ymm5, %ymm5
; AVX2-NEXT:    vpsllw $8, %ymm5, %ymm5
; AVX2-NEXT:    vpor %ymm5, %ymm1, %ymm1
; AVX2-NEXT:    vpmullw %ymm3, %ymm0, %ymm3
; AVX2-NEXT:    vpand %ymm7, %ymm3, %ymm3
; AVX2-NEXT:    vpmaddubsw %ymm8, %ymm0, %ymm0
; AVX2-NEXT:    vpsllw $8, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm3, %ymm0
; AVX2-NEXT:    vpxor %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmul_v32i8:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpbroadcastd {{.*#+}} ymm2 = [1431655765,1431655765,1431655765,1431655765,1431655765,1431655765,1431655765,1431655765]
; AVX512-NEXT:    vpand %ymm2, %ymm1, %ymm3
; AVX512-NEXT:    vpand %ymm2, %ymm0, %ymm2
; AVX512-NEXT:    vpmullw %ymm3, %ymm2, %ymm4
; AVX512-NEXT:    vpbroadcastd {{.*#+}} ymm5 = [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]
; AVX512-NEXT:    vpandn %ymm3, %ymm5, %ymm6
; AVX512-NEXT:    vpmaddubsw %ymm6, %ymm2, %ymm7
; AVX512-NEXT:    vpsllw $8, %ymm7, %ymm7
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm7 = ymm7 | (ymm4 & ymm5)
; AVX512-NEXT:    vpbroadcastd {{.*#+}} ymm4 = [170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170]
; AVX512-NEXT:    vpand %ymm4, %ymm1, %ymm1
; AVX512-NEXT:    vpand %ymm4, %ymm0, %ymm0
; AVX512-NEXT:    vpmullw %ymm1, %ymm0, %ymm4
; AVX512-NEXT:    vpand %ymm5, %ymm4, %ymm4
; AVX512-NEXT:    vpandn %ymm1, %ymm5, %ymm8
; AVX512-NEXT:    vpmaddubsw %ymm8, %ymm0, %ymm9
; AVX512-NEXT:    vpsllw $8, %ymm9, %ymm9
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm9 = ymm7 ^ (ymm9 | ymm4)
; AVX512-NEXT:    vpmullw %ymm1, %ymm2, %ymm1
; AVX512-NEXT:    vpmaddubsw %ymm8, %ymm2, %ymm2
; AVX512-NEXT:    vpsllw $8, %ymm2, %ymm2
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm2 = ymm2 | (ymm1 & ymm5)
; AVX512-NEXT:    vpmullw %ymm3, %ymm0, %ymm1
; AVX512-NEXT:    vpand %ymm5, %ymm1, %ymm1
; AVX512-NEXT:    vpmaddubsw %ymm6, %ymm0, %ymm0
; AVX512-NEXT:    vpsllw $8, %ymm0, %ymm0
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm0 = ymm2 ^ (ymm0 | ymm1)
; AVX512-NEXT:    vpternlogd {{.*#+}} ymm0 = ymm0 ^ (m32bcst & (ymm0 ^ ymm9))
; AVX512-NEXT:    retq
  %res = call <32 x i8> @llvm.clmul.v32i8(<32 x i8> %a, <32 x i8> %b)
  ret <32 x i8> %res
}

define <16 x i16> @clmul_v16i16(<16 x i16> %a, <16 x i16> %b) nounwind {
; AVX1-LABEL: clmul_v16i16:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX1-NEXT:    vandps %ymm2, %ymm1, %ymm3
; AVX1-NEXT:    vextractf128 $1, %ymm3, %xmm4
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm13 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX1-NEXT:    vandps %ymm0, %ymm13, %ymm5
; AVX1-NEXT:    vextractf128 $1, %ymm5, %xmm6
; AVX1-NEXT:    vpmullw %xmm4, %xmm6, %xmm7
; AVX1-NEXT:    vpmullw %xmm3, %xmm5, %xmm8
; AVX1-NEXT:    vinsertf128 $1, %xmm7, %ymm8, %ymm8
; AVX1-NEXT:    vandps %ymm1, %ymm13, %ymm9
; AVX1-NEXT:    vextractf128 $1, %ymm9, %xmm11
; AVX1-NEXT:    vandps %ymm2, %ymm0, %ymm7
; AVX1-NEXT:    vextractf128 $1, %ymm7, %xmm10
; AVX1-NEXT:    vpmullw %xmm11, %xmm10, %xmm12
; AVX1-NEXT:    vpmullw %xmm7, %xmm9, %xmm14
; AVX1-NEXT:    vinsertf128 $1, %xmm12, %ymm14, %ymm12
; AVX1-NEXT:    vxorps %ymm8, %ymm12, %ymm14
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX1-NEXT:    vandps %ymm2, %ymm1, %ymm12
; AVX1-NEXT:    vextractf128 $1, %ymm12, %xmm15
; AVX1-NEXT:    vandps %ymm2, %ymm0, %ymm0
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX1-NEXT:    vpmullw %xmm1, %xmm15, %xmm2
; AVX1-NEXT:    vpmullw %xmm0, %xmm12, %xmm8
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm8, %ymm2
; AVX1-NEXT:    vxorps %ymm2, %ymm14, %ymm2
; AVX1-NEXT:    vandps %ymm2, %ymm13, %ymm2
; AVX1-NEXT:    vpmullw %xmm6, %xmm15, %xmm8
; AVX1-NEXT:    vpmullw %xmm5, %xmm12, %xmm13
; AVX1-NEXT:    vinsertf128 $1, %xmm8, %ymm13, %ymm8
; AVX1-NEXT:    vpmullw %xmm4, %xmm10, %xmm13
; AVX1-NEXT:    vpmullw %xmm3, %xmm7, %xmm14
; AVX1-NEXT:    vinsertf128 $1, %xmm13, %ymm14, %ymm13
; AVX1-NEXT:    vxorps %ymm8, %ymm13, %ymm8
; AVX1-NEXT:    vpmullw %xmm1, %xmm11, %xmm13
; AVX1-NEXT:    vpmullw %xmm0, %xmm9, %xmm14
; AVX1-NEXT:    vinsertf128 $1, %xmm13, %ymm14, %ymm13
; AVX1-NEXT:    vxorps %ymm13, %ymm8, %ymm8
; AVX1-NEXT:    vandps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm8, %ymm8
; AVX1-NEXT:    vorps %ymm2, %ymm8, %ymm2
; AVX1-NEXT:    vpmullw %xmm6, %xmm11, %xmm6
; AVX1-NEXT:    vpmullw %xmm5, %xmm9, %xmm5
; AVX1-NEXT:    vinsertf128 $1, %xmm6, %ymm5, %ymm5
; AVX1-NEXT:    vpmullw %xmm15, %xmm10, %xmm6
; AVX1-NEXT:    vpmullw %xmm7, %xmm12, %xmm7
; AVX1-NEXT:    vinsertf128 $1, %xmm6, %ymm7, %ymm6
; AVX1-NEXT:    vxorps %ymm5, %ymm6, %ymm5
; AVX1-NEXT:    vpmullw %xmm4, %xmm1, %xmm1
; AVX1-NEXT:    vpmullw %xmm3, %xmm0, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX1-NEXT:    vxorps %ymm0, %ymm5, %ymm0
; AVX1-NEXT:    vandps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm0, %ymm0
; AVX1-NEXT:    vorps %ymm0, %ymm2, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmul_v16i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm2 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX2-NEXT:    vpand %ymm2, %ymm1, %ymm3
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm4 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX2-NEXT:    vpand %ymm4, %ymm0, %ymm5
; AVX2-NEXT:    vpmullw %ymm3, %ymm5, %ymm6
; AVX2-NEXT:    vpand %ymm4, %ymm1, %ymm7
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm8
; AVX2-NEXT:    vpmullw %ymm7, %ymm8, %ymm9
; AVX2-NEXT:    vpxor %ymm6, %ymm9, %ymm6
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm9 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX2-NEXT:    vpand %ymm1, %ymm9, %ymm1
; AVX2-NEXT:    vpand %ymm0, %ymm9, %ymm0
; AVX2-NEXT:    vpmullw %ymm1, %ymm0, %ymm10
; AVX2-NEXT:    vpxor %ymm6, %ymm10, %ymm6
; AVX2-NEXT:    vpand %ymm4, %ymm6, %ymm4
; AVX2-NEXT:    vpmullw %ymm1, %ymm5, %ymm6
; AVX2-NEXT:    vpmullw %ymm3, %ymm8, %ymm10
; AVX2-NEXT:    vpxor %ymm6, %ymm10, %ymm6
; AVX2-NEXT:    vpmullw %ymm7, %ymm0, %ymm10
; AVX2-NEXT:    vpxor %ymm6, %ymm10, %ymm6
; AVX2-NEXT:    vpand %ymm2, %ymm6, %ymm2
; AVX2-NEXT:    vpor %ymm4, %ymm2, %ymm2
; AVX2-NEXT:    vpmullw %ymm7, %ymm5, %ymm4
; AVX2-NEXT:    vpmullw %ymm1, %ymm8, %ymm1
; AVX2-NEXT:    vpxor %ymm4, %ymm1, %ymm1
; AVX2-NEXT:    vpmullw %ymm3, %ymm0, %ymm0
; AVX2-NEXT:    vpxor %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vpand %ymm0, %ymm9, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm2, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmul_v16i16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpbroadcastd {{.*#+}} ymm2 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX512-NEXT:    vpand %ymm2, %ymm1, %ymm3
; AVX512-NEXT:    vpand %ymm2, %ymm0, %ymm4
; AVX512-NEXT:    vpmullw %ymm3, %ymm4, %ymm5
; AVX512-NEXT:    vpbroadcastd {{.*#+}} ymm6 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX512-NEXT:    vpand %ymm6, %ymm1, %ymm7
; AVX512-NEXT:    vpbroadcastd {{.*#+}} ymm8 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX512-NEXT:    vpand %ymm0, %ymm8, %ymm9
; AVX512-NEXT:    vpmullw %ymm7, %ymm9, %ymm10
; AVX512-NEXT:    vpand %ymm1, %ymm8, %ymm1
; AVX512-NEXT:    vpand %ymm6, %ymm0, %ymm0
; AVX512-NEXT:    vpmullw %ymm1, %ymm0, %ymm11
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm11 = ymm11 ^ ymm10 ^ ymm5
; AVX512-NEXT:    vpmullw %ymm1, %ymm4, %ymm5
; AVX512-NEXT:    vpmullw %ymm3, %ymm9, %ymm10
; AVX512-NEXT:    vpmullw %ymm7, %ymm0, %ymm12
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm12 = ymm12 ^ ymm10 ^ ymm5
; AVX512-NEXT:    vpmullw %ymm7, %ymm4, %ymm4
; AVX512-NEXT:    vpmullw %ymm1, %ymm9, %ymm1
; AVX512-NEXT:    vpxor %ymm4, %ymm1, %ymm1
; AVX512-NEXT:    vpmullw %ymm3, %ymm0, %ymm0
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm0 = ymm8 & (ymm0 ^ ymm1)
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm0 = ymm0 | (ymm12 & ymm2)
; AVX512-NEXT:    vpternlogq {{.*#+}} ymm0 = ymm0 | (ymm11 & ymm6)
; AVX512-NEXT:    retq
  %res = call <16 x i16> @llvm.clmul.v16i16(<16 x i16> %a, <16 x i16> %b)
  ret <16 x i16> %res
}

define <8 x i32> @clmul_v8i32(<8 x i32> %a, <8 x i32> %b) nounwind {
; AVX1-LABEL: clmul_v8i32:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm4
; AVX1-NEXT:    vpshufd {{.*#+}} xmm5 = xmm2[1,1,1,1]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX1-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX1-NEXT:    vpunpckldq {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[1],xmm5[1]
; AVX1-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm5
; AVX1-NEXT:    vmovq %xmm5, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX1-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vmovq %xmm2, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm2
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm3
; AVX1-NEXT:    vpshufd {{.*#+}} xmm4 = xmm1[1,1,1,1]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm5 = xmm0[1,1,1,1]
; AVX1-NEXT:    vpclmulqdq $0, %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vpunpckldq {{.*#+}} xmm3 = xmm3[0],xmm4[0],xmm3[1],xmm4[1]
; AVX1-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm4
; AVX1-NEXT:    vmovq %xmm4, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm3, %xmm3
; AVX1-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vmovq %xmm0, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm3, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmul_v8i32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextracti128 $1, %ymm1, %xmm2
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm3
; AVX2-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm4
; AVX2-NEXT:    vpshufd {{.*#+}} xmm5 = xmm2[1,1,1,1]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX2-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX2-NEXT:    vpunpckldq {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[1],xmm5[1]
; AVX2-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm5
; AVX2-NEXT:    vmovq %xmm5, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX2-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX2-NEXT:    vmovq %xmm2, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm2
; AVX2-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm3
; AVX2-NEXT:    vpshufd {{.*#+}} xmm4 = xmm1[1,1,1,1]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm5 = xmm0[1,1,1,1]
; AVX2-NEXT:    vpclmulqdq $0, %xmm4, %xmm5, %xmm4
; AVX2-NEXT:    vpunpckldq {{.*#+}} xmm3 = xmm3[0],xmm4[0],xmm3[1],xmm4[1]
; AVX2-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm4
; AVX2-NEXT:    vmovq %xmm4, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vmovq %xmm0, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vinserti128 $1, %xmm2, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmul_v8i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextracti128 $1, %ymm1, %xmm2
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm3
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm5 = xmm2[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[1],xmm5[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm5
; AVX512-NEXT:    vmovq %xmm5, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX512-NEXT:    vmovq %xmm2, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm2
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm3
; AVX512-NEXT:    vpshufd {{.*#+}} xmm4 = xmm1[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm5 = xmm0[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm4, %xmm5, %xmm4
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm3 = xmm3[0],xmm4[0],xmm3[1],xmm4[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm4
; AVX512-NEXT:    vmovq %xmm4, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vmovq %xmm0, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm3, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm2, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %res = call <8 x i32> @llvm.clmul.v8i32(<8 x i32> %a, <8 x i32> %b)
  ret <8 x i32> %res
}

define <4 x i64> @clmul_v4i64(<4 x i64> %a, <4 x i64> %b) nounwind {
; AVX1-LABEL: clmul_v4i64:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm4
; AVX1-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm2[0],xmm4[0]
; AVX1-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm3
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm3[0]
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-PCLMUL-LABEL: clmul_v4i64:
; AVX2-PCLMUL:       # %bb.0:
; AVX2-PCLMUL-NEXT:    vextracti128 $1, %ymm1, %xmm2
; AVX2-PCLMUL-NEXT:    vextracti128 $1, %ymm0, %xmm3
; AVX2-PCLMUL-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm4
; AVX2-PCLMUL-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX2-PCLMUL-NEXT:    vinserti128 $1, %xmm4, %ymm5, %ymm4
; AVX2-PCLMUL-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX2-PCLMUL-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX2-PCLMUL-NEXT:    vinserti128 $1, %xmm2, %ymm0, %ymm0
; AVX2-PCLMUL-NEXT:    vpunpcklqdq {{.*#+}} ymm0 = ymm0[0],ymm4[0],ymm0[2],ymm4[2]
; AVX2-PCLMUL-NEXT:    retq
;
; AVX2-VPCLMULQDQ-LABEL: clmul_v4i64:
; AVX2-VPCLMULQDQ:       # %bb.0:
; AVX2-VPCLMULQDQ-NEXT:    vpclmulqdq $17, %ymm1, %ymm0, %ymm2
; AVX2-VPCLMULQDQ-NEXT:    vpclmulqdq $0, %ymm1, %ymm0, %ymm0
; AVX2-VPCLMULQDQ-NEXT:    vpunpcklqdq {{.*#+}} ymm0 = ymm0[0],ymm2[0],ymm0[2],ymm2[2]
; AVX2-VPCLMULQDQ-NEXT:    retq
;
; AVX512-LABEL: clmul_v4i64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpclmulqdq $17, %ymm1, %ymm0, %ymm2
; AVX512-NEXT:    vpclmulqdq $0, %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} ymm0 = ymm0[0],ymm2[0],ymm0[2],ymm2[2]
; AVX512-NEXT:    retq
  %res = call <4 x i64> @llvm.clmul.v4i64(<4 x i64> %a, <4 x i64> %b)
  ret <4 x i64> %res
}

define <32 x i8> @clmulr_v32i8(<32 x i8> %a, <32 x i8> %b) nounwind {
; AVX1-LABEL: clmulr_v32i8:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm4
; AVX1-NEXT:    vbroadcastss {{.*#+}} xmm13 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX1-NEXT:    vpand %xmm4, %xmm13, %xmm5
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm5, %xmm3, %xmm5
; AVX1-NEXT:    vpsrlw $4, %xmm4, %xmm4
; AVX1-NEXT:    vpand %xmm4, %xmm13, %xmm6
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm6, %xmm4, %xmm6
; AVX1-NEXT:    vpor %xmm6, %xmm5, %xmm10
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vpand %xmm2, %xmm10, %xmm6
; AVX1-NEXT:    vmovdqa %ymm2, %ymm11
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm7
; AVX1-NEXT:    vpand %xmm7, %xmm13, %xmm8
; AVX1-NEXT:    vmovdqa %xmm3, %xmm2
; AVX1-NEXT:    vpshufb %xmm8, %xmm3, %xmm8
; AVX1-NEXT:    vpsrlw $4, %xmm7, %xmm7
; AVX1-NEXT:    vpand %xmm7, %xmm13, %xmm7
; AVX1-NEXT:    vmovdqa %xmm4, %xmm5
; AVX1-NEXT:    vpshufb %xmm7, %xmm4, %xmm7
; AVX1-NEXT:    vpor %xmm7, %xmm8, %xmm12
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm4 = [170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170]
; AVX1-NEXT:    vpand %xmm4, %xmm12, %xmm7
; AVX1-NEXT:    vpmullw %xmm6, %xmm7, %xmm8
; AVX1-NEXT:    vmovdqa %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vpand %xmm1, %xmm13, %xmm9
; AVX1-NEXT:    vpshufb %xmm9, %xmm3, %xmm9
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm1, %xmm13, %xmm1
; AVX1-NEXT:    vpshufb %xmm1, %xmm5, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm9, %xmm14
; AVX1-NEXT:    vpand %xmm11, %xmm14, %xmm3
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm9
; AVX1-NEXT:    vpshufb %xmm9, %xmm2, %xmm9
; AVX1-NEXT:    vpsrlw $4, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm0
; AVX1-NEXT:    vpshufb %xmm0, %xmm5, %xmm0
; AVX1-NEXT:    vpor %xmm0, %xmm9, %xmm15
; AVX1-NEXT:    vpand %xmm4, %xmm15, %xmm11
; AVX1-NEXT:    vpmullw %xmm3, %xmm11, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm8, %ymm0, %ymm2
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm1 = [255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0]
; AVX1-NEXT:    vpandn %xmm3, %xmm1, %xmm0
; AVX1-NEXT:    vmovdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vpmaddubsw %xmm0, %xmm11, %xmm9
; AVX1-NEXT:    vpsllw $8, %xmm9, %xmm0
; AVX1-NEXT:    vpandn %xmm6, %xmm1, %xmm9
; AVX1-NEXT:    vpmaddubsw %xmm9, %xmm7, %xmm5
; AVX1-NEXT:    vpsllw $8, %xmm5, %xmm5
; AVX1-NEXT:    vinsertf128 $1, %xmm5, %ymm0, %ymm0
; AVX1-NEXT:    vandps %ymm1, %ymm2, %ymm2
; AVX1-NEXT:    vorps %ymm0, %ymm2, %ymm6
; AVX1-NEXT:    vpand %xmm4, %xmm10, %xmm2
; AVX1-NEXT:    vpand %xmm4, %xmm14, %xmm4
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm0 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vpand %xmm0, %xmm12, %xmm10
; AVX1-NEXT:    vpand %xmm0, %xmm15, %xmm12
; AVX1-NEXT:    vpmullw %xmm2, %xmm10, %xmm5
; AVX1-NEXT:    vpmullw %xmm4, %xmm12, %xmm14
; AVX1-NEXT:    vinsertf128 $1, %xmm5, %ymm14, %ymm5
; AVX1-NEXT:    vpandn %xmm4, %xmm1, %xmm14
; AVX1-NEXT:    vpmaddubsw %xmm14, %xmm12, %xmm15
; AVX1-NEXT:    vpsllw $8, %xmm15, %xmm15
; AVX1-NEXT:    vpandn %xmm2, %xmm1, %xmm0
; AVX1-NEXT:    vpmaddubsw %xmm0, %xmm10, %xmm8
; AVX1-NEXT:    vpsllw $8, %xmm8, %xmm8
; AVX1-NEXT:    vinsertf128 $1, %xmm8, %ymm15, %ymm8
; AVX1-NEXT:    vandps %ymm1, %ymm5, %ymm5
; AVX1-NEXT:    vorps %ymm5, %ymm8, %ymm5
; AVX1-NEXT:    vxorps %ymm6, %ymm5, %ymm5
; AVX1-NEXT:    vpmullw %xmm2, %xmm7, %xmm2
; AVX1-NEXT:    vpmullw %xmm4, %xmm11, %xmm4
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm4, %ymm2
; AVX1-NEXT:    vpmaddubsw %xmm14, %xmm11, %xmm4
; AVX1-NEXT:    vpmaddubsw %xmm0, %xmm7, %xmm0
; AVX1-NEXT:    vpsllw $8, %xmm4, %xmm4
; AVX1-NEXT:    vpsllw $8, %xmm0, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm4, %ymm0
; AVX1-NEXT:    vandps %ymm1, %ymm2, %ymm2
; AVX1-NEXT:    vorps %ymm0, %ymm2, %ymm0
; AVX1-NEXT:    vpmullw {{[-0-9]+}}(%r{{[sb]}}p), %xmm10, %xmm2 # 16-byte Folded Reload
; AVX1-NEXT:    vpmullw %xmm3, %xmm12, %xmm3
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm3, %ymm2
; AVX1-NEXT:    vandps %ymm1, %ymm2, %ymm1
; AVX1-NEXT:    vpmaddubsw {{[-0-9]+}}(%r{{[sb]}}p), %xmm12, %xmm2 # 16-byte Folded Reload
; AVX1-NEXT:    vpmaddubsw %xmm9, %xmm10, %xmm3
; AVX1-NEXT:    vpsllw $8, %xmm2, %xmm2
; AVX1-NEXT:    vpsllw $8, %xmm3, %xmm3
; AVX1-NEXT:    vinsertf128 $1, %xmm3, %ymm2, %ymm2
; AVX1-NEXT:    vorps %ymm2, %ymm1, %ymm1
; AVX1-NEXT:    vxorps %ymm0, %ymm1, %ymm0
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vandnps %ymm5, %ymm2, %ymm1
; AVX1-NEXT:    vandps %ymm2, %ymm0, %ymm0
; AVX1-NEXT:    vorps %ymm1, %ymm0, %ymm0
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX1-NEXT:    vpand %xmm1, %xmm13, %xmm2
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm1, %xmm13, %xmm1
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm1, %xmm4, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm2, %xmm1
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm2
; AVX1-NEXT:    vpshufb %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm0
; AVX1-NEXT:    vpshufb %xmm0, %xmm4, %xmm0
; AVX1-NEXT:    vpor %xmm0, %xmm2, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmulr_v32i8:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm2 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX2-NEXT:    vpand %ymm2, %ymm1, %ymm4
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240,0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX2-NEXT:    # ymm3 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm4, %ymm3, %ymm4
; AVX2-NEXT:    vpsrlw $4, %ymm1, %ymm1
; AVX2-NEXT:    vpand %ymm2, %ymm1, %ymm5
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm1 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15,0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX2-NEXT:    # ymm1 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm5, %ymm1, %ymm5
; AVX2-NEXT:    vpor %ymm5, %ymm4, %ymm5
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm4 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX2-NEXT:    vpand %ymm4, %ymm5, %ymm6
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm7
; AVX2-NEXT:    vpshufb %ymm7, %ymm3, %ymm7
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm7, %ymm0
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm7 = [170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170]
; AVX2-NEXT:    vpand %ymm7, %ymm0, %ymm8
; AVX2-NEXT:    vpmullw %ymm6, %ymm8, %ymm9
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm10 = [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]
; AVX2-NEXT:    vpand %ymm10, %ymm9, %ymm9
; AVX2-NEXT:    vpandn %ymm6, %ymm10, %ymm11
; AVX2-NEXT:    vpmaddubsw %ymm11, %ymm8, %ymm12
; AVX2-NEXT:    vpsllw $8, %ymm12, %ymm12
; AVX2-NEXT:    vpor %ymm12, %ymm9, %ymm9
; AVX2-NEXT:    vpand %ymm7, %ymm5, %ymm5
; AVX2-NEXT:    vpand %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    vpmullw %ymm5, %ymm0, %ymm7
; AVX2-NEXT:    vpand %ymm7, %ymm10, %ymm7
; AVX2-NEXT:    vpandn %ymm5, %ymm10, %ymm12
; AVX2-NEXT:    vpmaddubsw %ymm12, %ymm0, %ymm13
; AVX2-NEXT:    vpsllw $8, %ymm13, %ymm13
; AVX2-NEXT:    vpor %ymm7, %ymm13, %ymm7
; AVX2-NEXT:    vpxor %ymm7, %ymm9, %ymm7
; AVX2-NEXT:    vpandn %ymm7, %ymm4, %ymm7
; AVX2-NEXT:    vpmullw %ymm5, %ymm8, %ymm5
; AVX2-NEXT:    vpand %ymm5, %ymm10, %ymm5
; AVX2-NEXT:    vpmaddubsw %ymm12, %ymm8, %ymm8
; AVX2-NEXT:    vpsllw $8, %ymm8, %ymm8
; AVX2-NEXT:    vpor %ymm5, %ymm8, %ymm5
; AVX2-NEXT:    vpmullw %ymm6, %ymm0, %ymm6
; AVX2-NEXT:    vpand %ymm6, %ymm10, %ymm6
; AVX2-NEXT:    vpmaddubsw %ymm11, %ymm0, %ymm0
; AVX2-NEXT:    vpsllw $8, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm6, %ymm0
; AVX2-NEXT:    vpxor %ymm5, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm7, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm4
; AVX2-NEXT:    vpshufb %ymm4, %ymm3, %ymm3
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm3, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmulr_v32i8:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpbroadcastd {{.*#+}} zmm16 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX512-NEXT:    vextracti128 $1, %ymm1, %xmm3
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm8 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero,xmm3[8],zero,xmm3[9],zero,xmm3[10],zero,xmm3[11],zero,xmm3[12],zero,xmm3[13],zero,xmm3[14],zero,xmm3[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm8, %ymm3
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm4
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm9 = xmm4[0],zero,xmm4[1],zero,xmm4[2],zero,xmm4[3],zero,xmm4[4],zero,xmm4[5],zero,xmm4[6],zero,xmm4[7],zero,xmm4[8],zero,xmm4[9],zero,xmm4[10],zero,xmm4[11],zero,xmm4[12],zero,xmm4[13],zero,xmm4[14],zero,xmm4[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm9, %ymm4
; AVX512-NEXT:    vpmullw %ymm3, %ymm4, %ymm5
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm10 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero,xmm1[8],zero,xmm1[9],zero,xmm1[10],zero,xmm1[11],zero,xmm1[12],zero,xmm1[13],zero,xmm1[14],zero,xmm1[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm10, %ymm1
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm11 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero,xmm0[8],zero,xmm0[9],zero,xmm0[10],zero,xmm0[11],zero,xmm0[12],zero,xmm0[13],zero,xmm0[14],zero,xmm0[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm11, %ymm0
; AVX512-NEXT:    vpmullw %ymm1, %ymm0, %ymm6
; AVX512-NEXT:    vinserti64x4 $1, %ymm5, %zmm6, %zmm12
; AVX512-NEXT:    vpbroadcastd {{.*#+}} zmm17 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX512-NEXT:    vpandq %ymm17, %ymm8, %ymm6
; AVX512-NEXT:    vpbroadcastd {{.*#+}} zmm18 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX512-NEXT:    vpandq %ymm18, %ymm9, %ymm5
; AVX512-NEXT:    vpmullw %ymm6, %ymm5, %ymm15
; AVX512-NEXT:    vpandq %ymm17, %ymm10, %ymm2
; AVX512-NEXT:    vpandq %ymm18, %ymm11, %ymm7
; AVX512-NEXT:    vpmullw %ymm2, %ymm7, %ymm13
; AVX512-NEXT:    vinserti64x4 $1, %ymm15, %zmm13, %zmm13
; AVX512-NEXT:    vpandq %ymm18, %ymm8, %ymm8
; AVX512-NEXT:    vpandq %ymm17, %ymm9, %ymm9
; AVX512-NEXT:    vpmullw %ymm8, %ymm9, %ymm15
; AVX512-NEXT:    vpandq %ymm18, %ymm10, %ymm10
; AVX512-NEXT:    vpandq %ymm17, %ymm11, %ymm11
; AVX512-NEXT:    vpmullw %ymm10, %ymm11, %ymm14
; AVX512-NEXT:    vinserti64x4 $1, %ymm15, %zmm14, %zmm14
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm14 = zmm14 ^ zmm13 ^ zmm12
; AVX512-NEXT:    vpmullw %ymm4, %ymm8, %ymm12
; AVX512-NEXT:    vpmullw %ymm0, %ymm10, %ymm13
; AVX512-NEXT:    vinserti64x4 $1, %ymm12, %zmm13, %zmm12
; AVX512-NEXT:    vpmullw %ymm3, %ymm5, %ymm13
; AVX512-NEXT:    vmovdqa64 %ymm3, %ymm19
; AVX512-NEXT:    vpmullw %ymm1, %ymm7, %ymm15
; AVX512-NEXT:    vinserti64x4 $1, %ymm13, %zmm15, %zmm13
; AVX512-NEXT:    vpmullw %ymm6, %ymm9, %ymm15
; AVX512-NEXT:    vpmullw %ymm2, %ymm11, %ymm3
; AVX512-NEXT:    vinserti64x4 $1, %ymm15, %zmm3, %zmm3
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm3 = zmm3 ^ zmm13 ^ zmm12
; AVX512-NEXT:    vpmullw %ymm6, %ymm4, %ymm4
; AVX512-NEXT:    vpmullw %ymm2, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm4, %zmm0, %zmm0
; AVX512-NEXT:    vpmullw %ymm5, %ymm8, %ymm2
; AVX512-NEXT:    vpmullw %ymm7, %ymm10, %ymm4
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm4, %zmm2
; AVX512-NEXT:    vpxorq %zmm0, %zmm2, %zmm0
; AVX512-NEXT:    vmovdqa64 %ymm19, %ymm2
; AVX512-NEXT:    vpmullw %ymm2, %ymm9, %ymm2
; AVX512-NEXT:    vpmullw %ymm1, %ymm11, %ymm1
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm1, %zmm1
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm1 = zmm18 & (zmm1 ^ zmm0)
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm1 = zmm1 | (zmm3 & zmm16)
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm1 = zmm1 | (zmm14 & zmm17)
; AVX512-NEXT:    vpsrlw $7, %ymm1, %ymm0
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm0 = ymm0[0],zero,ymm0[1],zero,ymm0[2],zero,ymm0[3],zero,ymm0[4],zero,ymm0[5],zero,ymm0[6],zero,ymm0[7],zero,ymm0[8],zero,ymm0[9],zero,ymm0[10],zero,ymm0[11],zero,ymm0[12],zero,ymm0[13],zero,ymm0[14],zero,ymm0[15],zero
; AVX512-NEXT:    vpmovdb %zmm0, %xmm0
; AVX512-NEXT:    vextracti64x4 $1, %zmm1, %ymm1
; AVX512-NEXT:    vpsrlw $7, %ymm1, %ymm1
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm1 = ymm1[0],zero,ymm1[1],zero,ymm1[2],zero,ymm1[3],zero,ymm1[4],zero,ymm1[5],zero,ymm1[6],zero,ymm1[7],zero,ymm1[8],zero,ymm1[9],zero,ymm1[10],zero,ymm1[11],zero,ymm1[12],zero,ymm1[13],zero,ymm1[14],zero,ymm1[15],zero
; AVX512-NEXT:    vpmovdb %zmm1, %xmm1
; AVX512-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %a.ext = zext <32 x i8> %a to <32 x i16>
  %b.ext = zext <32 x i8> %b to <32 x i16>
  %clmul = call <32 x i16> @llvm.clmul.v32i16(<32 x i16> %a.ext, <32 x i16> %b.ext)
  %res.ext = lshr <32 x i16> %clmul, splat (i16 7)
  %res = trunc <32 x i16> %res.ext to <32 x i8>
  ret <32 x i8> %res
}

define <16 x i16> @clmulr_v16i16(<16 x i16> %a, <16 x i16> %b) nounwind {
; AVX1-LABEL: clmulr_v16i16:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vmovdqa %ymm0, %ymm12
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm0 = [1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14]
; AVX1-NEXT:    vpshufb %xmm0, %xmm2, %xmm3
; AVX1-NEXT:    vmovdqa %xmm0, %xmm2
; AVX1-NEXT:    vbroadcastss {{.*#+}} xmm7 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm5
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm5, %xmm4, %xmm6
; AVX1-NEXT:    vpsrlw $4, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm3
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm0 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm3, %xmm0, %xmm3
; AVX1-NEXT:    vpor %xmm3, %xmm6, %xmm9
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm3 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX1-NEXT:    vpand %xmm3, %xmm9, %xmm5
; AVX1-NEXT:    vmovdqa %xmm5, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vmovdqa %ymm3, %ymm6
; AVX1-NEXT:    vextractf128 $1, %ymm12, %xmm3
; AVX1-NEXT:    vpshufb %xmm2, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm8
; AVX1-NEXT:    vpshufb %xmm8, %xmm4, %xmm8
; AVX1-NEXT:    vpsrlw $4, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm3
; AVX1-NEXT:    vpshufb %xmm3, %xmm0, %xmm3
; AVX1-NEXT:    vpor %xmm3, %xmm8, %xmm14
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm10 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX1-NEXT:    vpand %xmm10, %xmm14, %xmm8
; AVX1-NEXT:    vpmullw %xmm5, %xmm8, %xmm11
; AVX1-NEXT:    vpshufb %xmm2, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm3
; AVX1-NEXT:    vpshufb %xmm3, %xmm4, %xmm3
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm1
; AVX1-NEXT:    vpshufb %xmm1, %xmm0, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm6, %xmm3, %xmm5
; AVX1-NEXT:    vpshufb %xmm2, %xmm12, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm2
; AVX1-NEXT:    vpshufb %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm1
; AVX1-NEXT:    vpshufb %xmm1, %xmm0, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm2, %xmm0
; AVX1-NEXT:    vpand %xmm0, %xmm10, %xmm4
; AVX1-NEXT:    vpmullw %xmm5, %xmm4, %xmm1
; AVX1-NEXT:    vmovdqa %xmm5, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vinsertf128 $1, %xmm11, %ymm1, %ymm11
; AVX1-NEXT:    vpand %xmm10, %xmm9, %xmm15
; AVX1-NEXT:    vmovdqa %ymm10, %ymm7
; AVX1-NEXT:    vpand %xmm6, %xmm14, %xmm12
; AVX1-NEXT:    vpmullw %xmm15, %xmm12, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm2
; AVX1-NEXT:    vpand %xmm6, %xmm0, %xmm13
; AVX1-NEXT:    vpmullw %xmm2, %xmm13, %xmm6
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm6, %ymm1
; AVX1-NEXT:    vxorps %ymm1, %ymm11, %ymm1
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm10 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX1-NEXT:    vpand %xmm10, %xmm9, %xmm6
; AVX1-NEXT:    vpand %xmm10, %xmm14, %xmm9
; AVX1-NEXT:    vpand %xmm3, %xmm10, %xmm3
; AVX1-NEXT:    vpand %xmm0, %xmm10, %xmm14
; AVX1-NEXT:    vpmullw %xmm6, %xmm9, %xmm0
; AVX1-NEXT:    vpmullw %xmm3, %xmm14, %xmm10
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm10, %ymm0
; AVX1-NEXT:    vxorps %ymm0, %ymm1, %ymm0
; AVX1-NEXT:    vandps %ymm7, %ymm0, %ymm7
; AVX1-NEXT:    vpmullw %xmm6, %xmm8, %xmm1
; AVX1-NEXT:    vpmullw %xmm3, %xmm4, %xmm10
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm10, %ymm1
; AVX1-NEXT:    vmovdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX1-NEXT:    vpmullw %xmm0, %xmm12, %xmm10
; AVX1-NEXT:    vpmullw %xmm5, %xmm13, %xmm11
; AVX1-NEXT:    vinsertf128 $1, %xmm10, %ymm11, %ymm10
; AVX1-NEXT:    vxorps %ymm1, %ymm10, %ymm1
; AVX1-NEXT:    vpmullw %xmm15, %xmm9, %xmm10
; AVX1-NEXT:    vpmullw %xmm2, %xmm14, %xmm11
; AVX1-NEXT:    vinsertf128 $1, %xmm10, %ymm11, %ymm10
; AVX1-NEXT:    vxorps %ymm1, %ymm10, %ymm1
; AVX1-NEXT:    vandps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm1, %ymm1
; AVX1-NEXT:    vorps %ymm7, %ymm1, %ymm5
; AVX1-NEXT:    vpmullw %xmm15, %xmm8, %xmm1
; AVX1-NEXT:    vpmullw %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm2, %ymm1
; AVX1-NEXT:    vpmullw %xmm6, %xmm12, %xmm2
; AVX1-NEXT:    vpmullw %xmm3, %xmm13, %xmm3
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm3, %ymm2
; AVX1-NEXT:    vxorps %ymm1, %ymm2, %ymm1
; AVX1-NEXT:    vpmullw %xmm0, %xmm9, %xmm2
; AVX1-NEXT:    vpmullw {{[-0-9]+}}(%r{{[sb]}}p), %xmm14, %xmm3 # 16-byte Folded Reload
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm3, %ymm2
; AVX1-NEXT:    vxorps %ymm2, %ymm1, %ymm1
; AVX1-NEXT:    vandps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm1, %ymm1
; AVX1-NEXT:    vorps %ymm1, %ymm5, %ymm0
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm3 = [1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14]
; AVX1-NEXT:    vpshufb %xmm3, %xmm1, %xmm1
; AVX1-NEXT:    vbroadcastss {{.*#+}} xmm6 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX1-NEXT:    vpand %xmm6, %xmm1, %xmm2
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm6, %xmm1, %xmm1
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm5 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm1, %xmm5, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm2, %xmm1
; AVX1-NEXT:    vpshufb %xmm3, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm6, %xmm0, %xmm2
; AVX1-NEXT:    vpshufb %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm6, %xmm0, %xmm0
; AVX1-NEXT:    vpshufb %xmm0, %xmm5, %xmm0
; AVX1-NEXT:    vpor %xmm0, %xmm2, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmulr_v16i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm2 = [1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14,1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14]
; AVX2-NEXT:    # ymm2 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm2, %ymm1, %ymm4
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm1 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX2-NEXT:    vpand %ymm1, %ymm4, %ymm5
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240,0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX2-NEXT:    # ymm3 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm5, %ymm3, %ymm5
; AVX2-NEXT:    vpsrlw $4, %ymm4, %ymm4
; AVX2-NEXT:    vpand %ymm1, %ymm4, %ymm6
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm4 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15,0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX2-NEXT:    # ymm4 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm6, %ymm4, %ymm6
; AVX2-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm6 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX2-NEXT:    vpand %ymm6, %ymm5, %ymm7
; AVX2-NEXT:    vpshufb %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm8
; AVX2-NEXT:    vpshufb %ymm8, %ymm3, %ymm8
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm4, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm8, %ymm0
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm8 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX2-NEXT:    vpand %ymm0, %ymm8, %ymm9
; AVX2-NEXT:    vpmullw %ymm7, %ymm9, %ymm10
; AVX2-NEXT:    vpand %ymm5, %ymm8, %ymm11
; AVX2-NEXT:    vpand %ymm6, %ymm0, %ymm12
; AVX2-NEXT:    vpmullw %ymm11, %ymm12, %ymm13
; AVX2-NEXT:    vpxor %ymm10, %ymm13, %ymm10
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm13 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX2-NEXT:    vpand %ymm5, %ymm13, %ymm5
; AVX2-NEXT:    vpand %ymm0, %ymm13, %ymm0
; AVX2-NEXT:    vpmullw %ymm5, %ymm0, %ymm14
; AVX2-NEXT:    vpxor %ymm14, %ymm10, %ymm10
; AVX2-NEXT:    vpand %ymm8, %ymm10, %ymm8
; AVX2-NEXT:    vpmullw %ymm5, %ymm9, %ymm10
; AVX2-NEXT:    vpmullw %ymm7, %ymm12, %ymm14
; AVX2-NEXT:    vpxor %ymm10, %ymm14, %ymm10
; AVX2-NEXT:    vpmullw %ymm0, %ymm11, %ymm14
; AVX2-NEXT:    vpxor %ymm14, %ymm10, %ymm10
; AVX2-NEXT:    vpand %ymm6, %ymm10, %ymm6
; AVX2-NEXT:    vpor %ymm6, %ymm8, %ymm6
; AVX2-NEXT:    vpmullw %ymm11, %ymm9, %ymm8
; AVX2-NEXT:    vpmullw %ymm5, %ymm12, %ymm5
; AVX2-NEXT:    vpxor %ymm5, %ymm8, %ymm5
; AVX2-NEXT:    vpmullw %ymm7, %ymm0, %ymm0
; AVX2-NEXT:    vpxor %ymm0, %ymm5, %ymm0
; AVX2-NEXT:    vpand %ymm0, %ymm13, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm6, %ymm0
; AVX2-NEXT:    vpshufb %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm2
; AVX2-NEXT:    vpshufb %ymm2, %ymm3, %ymm2
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm4, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm2, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmulr_v16i16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm1 = ymm1[0],zero,ymm1[1],zero,ymm1[2],zero,ymm1[3],zero,ymm1[4],zero,ymm1[5],zero,ymm1[6],zero,ymm1[7],zero,ymm1[8],zero,ymm1[9],zero,ymm1[10],zero,ymm1[11],zero,ymm1[12],zero,ymm1[13],zero,ymm1[14],zero,ymm1[15],zero
; AVX512-NEXT:    vextracti32x4 $3, %zmm1, %xmm2
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm0 = ymm0[0],zero,ymm0[1],zero,ymm0[2],zero,ymm0[3],zero,ymm0[4],zero,ymm0[5],zero,ymm0[6],zero,ymm0[7],zero,ymm0[8],zero,ymm0[9],zero,ymm0[10],zero,ymm0[11],zero,ymm0[12],zero,ymm0[13],zero,ymm0[14],zero,ymm0[15],zero
; AVX512-NEXT:    vextracti32x4 $3, %zmm0, %xmm3
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm5 = xmm2[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[1],xmm5[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm5
; AVX512-NEXT:    vmovq %xmm5, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX512-NEXT:    vmovq %xmm2, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm2
; AVX512-NEXT:    vextracti32x4 $2, %zmm1, %xmm3
; AVX512-NEXT:    vextracti32x4 $2, %zmm0, %xmm4
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm7 = xmm4[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm5 = xmm5[0],xmm6[0],xmm5[1],xmm6[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm3, %xmm4, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm4 = xmm4[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm3
; AVX512-NEXT:    vmovq %xmm3, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm3
; AVX512-NEXT:    vinserti128 $1, %xmm2, %ymm3, %ymm2
; AVX512-NEXT:    vextracti128 $1, %ymm1, %xmm3
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm4
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm7 = xmm4[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm5 = xmm5[0],xmm6[0],xmm5[1],xmm6[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm3, %xmm4, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm4 = xmm4[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm3
; AVX512-NEXT:    vmovq %xmm3, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm3
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm5 = xmm1[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm0[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[1],xmm5[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX512-NEXT:    vmovq %xmm5, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vmovq %xmm0, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm0, %zmm0
; AVX512-NEXT:    vpsrld $15, %zmm0, %zmm0
; AVX512-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512-NEXT:    retq
  %a.ext = zext <16 x i16> %a to <16 x i32>
  %b.ext = zext <16 x i16> %b to <16 x i32>
  %clmul = call <16 x i32> @llvm.clmul.v16i32(<16 x i32> %a.ext, <16 x i32> %b.ext)
  %res.ext = lshr <16 x i32> %clmul, splat (i32 15)
  %res = trunc <16 x i32> %res.ext to <16 x i16>
  ret <16 x i16> %res
}

define <8 x i32> @clmulr_v8i32(<8 x i32> %a, <8 x i32> %b) nounwind {
; AVX1-LABEL: clmulr_v8i32:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vpxor %xmm4, %xmm4, %xmm4
; AVX1-NEXT:    vpblendw {{.*#+}} xmm2 = xmm1[0,1],xmm4[2,3,4,5,6,7]
; AVX1-NEXT:    vpblendw {{.*#+}} xmm3 = xmm0[0,1],xmm4[2,3,4,5,6,7]
; AVX1-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vmovq %xmm2, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vmovd %eax, %xmm2
; AVX1-NEXT:    vpsrlq $32, %xmm1, %xmm3
; AVX1-NEXT:    vpsrlq $32, %xmm0, %xmm5
; AVX1-NEXT:    vpclmulqdq $0, %xmm3, %xmm5, %xmm3
; AVX1-NEXT:    vmovq %xmm3, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $1, %eax, %xmm2, %xmm2
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm3 = xmm1[2],xmm4[2],xmm1[3],xmm4[3]
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm5 = xmm0[2],xmm4[2],xmm0[3],xmm4[3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm3, %xmm5, %xmm3
; AVX1-NEXT:    vmovq %xmm3, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm2, %xmm2
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm3 = xmm1[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm0[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpclmulqdq $0, %xmm3, %xmm5, %xmm3
; AVX1-NEXT:    vmovq %xmm3, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm2, %xmm2
; AVX1-NEXT:    vpaddd %xmm2, %xmm2, %xmm5
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vpblendw {{.*#+}} xmm6 = xmm2[0,1],xmm4[2,3,4,5,6,7]
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vpblendw {{.*#+}} xmm7 = xmm3[0,1],xmm4[2,3,4,5,6,7]
; AVX1-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX1-NEXT:    vmovq %xmm6, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vmovd %eax, %xmm6
; AVX1-NEXT:    vpsrlq $32, %xmm2, %xmm7
; AVX1-NEXT:    vpsrlq $32, %xmm3, %xmm8
; AVX1-NEXT:    vpclmulqdq $0, %xmm7, %xmm8, %xmm7
; AVX1-NEXT:    vmovq %xmm7, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $1, %eax, %xmm6, %xmm6
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm2[2],xmm4[2],xmm2[3],xmm4[3]
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm4 = xmm3[2],xmm4[2],xmm3[3],xmm4[3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm7, %xmm4, %xmm4
; AVX1-NEXT:    vmovq %xmm4, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm6, %xmm4
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm2[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm7 = xmm3[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX1-NEXT:    vmovq %xmm6, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm4
; AVX1-NEXT:    vpaddd %xmm4, %xmm4, %xmm4
; AVX1-NEXT:    vinsertf128 $1, %xmm4, %ymm5, %ymm4
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm5
; AVX1-NEXT:    vpshufd {{.*#+}} xmm6 = xmm1[1,1,1,1]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm7 = xmm0[1,1,1,1]
; AVX1-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX1-NEXT:    vpunpckldq {{.*#+}} xmm5 = xmm5[0],xmm6[0],xmm5[1],xmm6[1]
; AVX1-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm6
; AVX1-NEXT:    vmovq %xmm6, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX1-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vmovq %xmm0, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm0
; AVX1-NEXT:    vpsrld $31, %xmm0, %xmm0
; AVX1-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm1
; AVX1-NEXT:    vpshufd {{.*#+}} xmm5 = xmm2[1,1,1,1]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX1-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX1-NEXT:    vpunpckldq {{.*#+}} xmm1 = xmm1[0],xmm5[0],xmm1[1],xmm5[1]
; AVX1-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm5
; AVX1-NEXT:    vmovq %xmm5, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm1, %xmm1
; AVX1-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX1-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vmovq %xmm2, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm1, %xmm1
; AVX1-NEXT:    vpsrld $31, %xmm1, %xmm1
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX1-NEXT:    vorps %ymm4, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmulr_v8i32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextracti128 $1, %ymm1, %xmm2
; AVX2-NEXT:    vpxor %xmm4, %xmm4, %xmm4
; AVX2-NEXT:    vpblendd {{.*#+}} xmm5 = xmm2[0],xmm4[1,2,3]
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm3
; AVX2-NEXT:    vpblendd {{.*#+}} xmm6 = xmm3[0],xmm4[1,2,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX2-NEXT:    vmovq %xmm5, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vmovd %eax, %xmm5
; AVX2-NEXT:    vpsrlq $32, %xmm2, %xmm6
; AVX2-NEXT:    vpsrlq $32, %xmm3, %xmm7
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $1, %eax, %xmm5, %xmm5
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm6 = xmm2[2],xmm4[2],xmm2[3],xmm4[3]
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm3[2],xmm4[2],xmm3[3],xmm4[3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm2[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm7 = xmm3[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm5
; AVX2-NEXT:    vpblendd {{.*#+}} xmm6 = xmm1[0],xmm4[1,2,3]
; AVX2-NEXT:    vpblendd {{.*#+}} xmm7 = xmm0[0],xmm4[1,2,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vmovd %eax, %xmm6
; AVX2-NEXT:    vpsrlq $32, %xmm1, %xmm7
; AVX2-NEXT:    vpsrlq $32, %xmm0, %xmm8
; AVX2-NEXT:    vpclmulqdq $0, %xmm7, %xmm8, %xmm7
; AVX2-NEXT:    vmovq %xmm7, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $1, %eax, %xmm6, %xmm6
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm1[2],xmm4[2],xmm1[3],xmm4[3]
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm4 = xmm0[2],xmm4[2],xmm0[3],xmm4[3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm7, %xmm4, %xmm4
; AVX2-NEXT:    vmovq %xmm4, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm6, %xmm4
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm1[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm7 = xmm0[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm4
; AVX2-NEXT:    vinserti128 $1, %xmm5, %ymm4, %ymm4
; AVX2-NEXT:    vpaddd %ymm4, %ymm4, %ymm4
; AVX2-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm5
; AVX2-NEXT:    vpshufd {{.*#+}} xmm6 = xmm2[1,1,1,1]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm7 = xmm3[1,1,1,1]
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vpunpckldq {{.*#+}} xmm5 = xmm5[0],xmm6[0],xmm5[1],xmm6[1]
; AVX2-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX2-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX2-NEXT:    vmovq %xmm2, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm2
; AVX2-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm3
; AVX2-NEXT:    vpshufd {{.*#+}} xmm5 = xmm1[1,1,1,1]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm6 = xmm0[1,1,1,1]
; AVX2-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX2-NEXT:    vpunpckldq {{.*#+}} xmm3 = xmm3[0],xmm5[0],xmm3[1],xmm5[1]
; AVX2-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX2-NEXT:    vmovq %xmm5, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX2-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vmovq %xmm0, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vinserti128 $1, %xmm2, %ymm0, %ymm0
; AVX2-NEXT:    vpsrld $31, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmulr_v8i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextracti128 $1, %ymm1, %xmm2
; AVX512-NEXT:    vpxor %xmm4, %xmm4, %xmm4
; AVX512-NEXT:    vpblendd {{.*#+}} xmm5 = xmm2[0],xmm4[1,2,3]
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm3
; AVX512-NEXT:    vpblendd {{.*#+}} xmm6 = xmm3[0],xmm4[1,2,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX512-NEXT:    vmovq %xmm5, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vmovd %eax, %xmm5
; AVX512-NEXT:    vpsrlq $32, %xmm2, %xmm6
; AVX512-NEXT:    vpsrlq $32, %xmm3, %xmm7
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $1, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpxor %xmm6, %xmm6, %xmm6
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm2[2],xmm6[2],xmm2[3],xmm6[3]
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm8 = xmm3[2],xmm6[2],xmm3[3],xmm6[3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm7, %xmm8, %xmm7
; AVX512-NEXT:    vmovq %xmm7, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm7 = xmm2[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm8 = xmm3[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpclmulqdq $0, %xmm7, %xmm8, %xmm7
; AVX512-NEXT:    vmovq %xmm7, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpblendd {{.*#+}} xmm7 = xmm1[0],xmm4[1,2,3]
; AVX512-NEXT:    vpblendd {{.*#+}} xmm4 = xmm0[0],xmm4[1,2,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm7, %xmm4, %xmm4
; AVX512-NEXT:    vmovq %xmm4, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vmovd %eax, %xmm4
; AVX512-NEXT:    vpsrlq $32, %xmm1, %xmm7
; AVX512-NEXT:    vpsrlq $32, %xmm0, %xmm8
; AVX512-NEXT:    vpclmulqdq $0, %xmm7, %xmm8, %xmm7
; AVX512-NEXT:    vmovq %xmm7, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $1, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm1[2],xmm6[2],xmm1[3],xmm6[3]
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm6 = xmm0[2],xmm6[2],xmm0[3],xmm6[3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm7, %xmm6, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm1[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm7 = xmm0[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vinserti128 $1, %xmm5, %ymm4, %ymm4
; AVX512-NEXT:    vpaddd %ymm4, %ymm4, %ymm4
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm2[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm7 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm5 = xmm5[0],xmm6[0],xmm5[1],xmm6[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX512-NEXT:    vmovq %xmm2, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm2
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm3
; AVX512-NEXT:    vpshufd {{.*#+}} xmm5 = xmm1[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm0[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm3 = xmm3[0],xmm5[0],xmm3[1],xmm5[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX512-NEXT:    vmovq %xmm5, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vmovq %xmm0, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm3, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm2, %ymm0, %ymm0
; AVX512-NEXT:    vpsrld $31, %ymm0, %ymm0
; AVX512-NEXT:    vpor %ymm4, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %a.ext = zext <8 x i32> %a to <8 x i64>
  %b.ext = zext <8 x i32> %b to <8 x i64>
  %clmul = call <8 x i64> @llvm.clmul.v8i64(<8 x i64> %a.ext, <8 x i64> %b.ext)
  %res.ext = lshr <8 x i64> %clmul, splat (i64 31)
  %res = trunc <8 x i64> %res.ext to <8 x i32>
  ret <8 x i32> %res
}

define <4 x i64> @clmulr_v4i64(<4 x i64> %a, <4 x i64> %b) nounwind {
; AVX1-LABEL: clmulr_v4i64:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm2
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm3
; AVX1-NEXT:    vpunpckhqdq {{.*#+}} xmm4 = xmm3[1],xmm2[1]
; AVX1-NEXT:    vpaddq %xmm4, %xmm4, %xmm4
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm1
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX1-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpunpckhqdq {{.*#+}} xmm1 = xmm0[1],xmm5[1]
; AVX1-NEXT:    vpaddq %xmm1, %xmm1, %xmm1
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm4, %ymm1
; AVX1-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm3[0],xmm2[0]
; AVX1-NEXT:    vpsrlq $63, %xmm2, %xmm2
; AVX1-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm5[0]
; AVX1-NEXT:    vpsrlq $63, %xmm0, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm2, %ymm0
; AVX1-NEXT:    vorps %ymm1, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-PCLMUL-LABEL: clmulr_v4i64:
; AVX2-PCLMUL:       # %bb.0:
; AVX2-PCLMUL-NEXT:    vextracti128 $1, %ymm1, %xmm2
; AVX2-PCLMUL-NEXT:    vextracti128 $1, %ymm0, %xmm3
; AVX2-PCLMUL-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm4
; AVX2-PCLMUL-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX2-PCLMUL-NEXT:    vinserti128 $1, %xmm4, %ymm5, %ymm4
; AVX2-PCLMUL-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX2-PCLMUL-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX2-PCLMUL-NEXT:    vinserti128 $1, %xmm2, %ymm0, %ymm0
; AVX2-PCLMUL-NEXT:    vpunpckhqdq {{.*#+}} ymm1 = ymm0[1],ymm4[1],ymm0[3],ymm4[3]
; AVX2-PCLMUL-NEXT:    vpaddq %ymm1, %ymm1, %ymm1
; AVX2-PCLMUL-NEXT:    vpunpcklqdq {{.*#+}} ymm0 = ymm0[0],ymm4[0],ymm0[2],ymm4[2]
; AVX2-PCLMUL-NEXT:    vpsrlq $63, %ymm0, %ymm0
; AVX2-PCLMUL-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-PCLMUL-NEXT:    retq
;
; AVX2-VPCLMULQDQ-LABEL: clmulr_v4i64:
; AVX2-VPCLMULQDQ:       # %bb.0:
; AVX2-VPCLMULQDQ-NEXT:    vpclmulqdq $17, %ymm1, %ymm0, %ymm2
; AVX2-VPCLMULQDQ-NEXT:    vpclmulqdq $0, %ymm1, %ymm0, %ymm0
; AVX2-VPCLMULQDQ-NEXT:    vpunpckhqdq {{.*#+}} ymm1 = ymm0[1],ymm2[1],ymm0[3],ymm2[3]
; AVX2-VPCLMULQDQ-NEXT:    vpaddq %ymm1, %ymm1, %ymm1
; AVX2-VPCLMULQDQ-NEXT:    vpunpcklqdq {{.*#+}} ymm0 = ymm0[0],ymm2[0],ymm0[2],ymm2[2]
; AVX2-VPCLMULQDQ-NEXT:    vpsrlq $63, %ymm0, %ymm0
; AVX2-VPCLMULQDQ-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX2-VPCLMULQDQ-NEXT:    retq
;
; AVX512-LABEL: clmulr_v4i64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpclmulqdq $17, %ymm1, %ymm0, %ymm2
; AVX512-NEXT:    vpclmulqdq $0, %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    vpunpckhqdq {{.*#+}} ymm1 = ymm0[1],ymm2[1],ymm0[3],ymm2[3]
; AVX512-NEXT:    vpaddq %ymm1, %ymm1, %ymm1
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} ymm0 = ymm0[0],ymm2[0],ymm0[2],ymm2[2]
; AVX512-NEXT:    vpsrlq $63, %ymm0, %ymm0
; AVX512-NEXT:    vpor %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %a.ext = zext <4 x i64> %a to <4 x i128>
  %b.ext = zext <4 x i64> %b to <4 x i128>
  %clmul = call <4 x i128> @llvm.clmul.v4i128(<4 x i128> %a.ext, <4 x i128> %b.ext)
  %res.ext = lshr <4 x i128> %clmul, splat (i128 63)
  %res = trunc <4 x i128> %res.ext to <4 x i64>
  ret <4 x i64> %res
}

define <32 x i8> @clmulh_v32i8(<32 x i8> %a, <32 x i8> %b) nounwind {
; AVX1-LABEL: clmulh_v32i8:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm4
; AVX1-NEXT:    vbroadcastss {{.*#+}} xmm13 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX1-NEXT:    vpand %xmm4, %xmm13, %xmm5
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm5, %xmm3, %xmm5
; AVX1-NEXT:    vpsrlw $4, %xmm4, %xmm4
; AVX1-NEXT:    vpand %xmm4, %xmm13, %xmm6
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm6, %xmm4, %xmm6
; AVX1-NEXT:    vpor %xmm6, %xmm5, %xmm10
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vpand %xmm2, %xmm10, %xmm6
; AVX1-NEXT:    vmovdqa %ymm2, %ymm11
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm7
; AVX1-NEXT:    vpand %xmm7, %xmm13, %xmm8
; AVX1-NEXT:    vmovdqa %xmm3, %xmm2
; AVX1-NEXT:    vpshufb %xmm8, %xmm3, %xmm8
; AVX1-NEXT:    vpsrlw $4, %xmm7, %xmm7
; AVX1-NEXT:    vpand %xmm7, %xmm13, %xmm7
; AVX1-NEXT:    vmovdqa %xmm4, %xmm5
; AVX1-NEXT:    vpshufb %xmm7, %xmm4, %xmm7
; AVX1-NEXT:    vpor %xmm7, %xmm8, %xmm12
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm4 = [170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170]
; AVX1-NEXT:    vpand %xmm4, %xmm12, %xmm7
; AVX1-NEXT:    vpmullw %xmm6, %xmm7, %xmm8
; AVX1-NEXT:    vmovdqa %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vpand %xmm1, %xmm13, %xmm9
; AVX1-NEXT:    vpshufb %xmm9, %xmm3, %xmm9
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm1, %xmm13, %xmm1
; AVX1-NEXT:    vpshufb %xmm1, %xmm5, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm9, %xmm14
; AVX1-NEXT:    vpand %xmm11, %xmm14, %xmm3
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm9
; AVX1-NEXT:    vpshufb %xmm9, %xmm2, %xmm9
; AVX1-NEXT:    vpsrlw $4, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm0
; AVX1-NEXT:    vpshufb %xmm0, %xmm5, %xmm0
; AVX1-NEXT:    vpor %xmm0, %xmm9, %xmm15
; AVX1-NEXT:    vpand %xmm4, %xmm15, %xmm11
; AVX1-NEXT:    vpmullw %xmm3, %xmm11, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm8, %ymm0, %ymm2
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm1 = [255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0,255,0]
; AVX1-NEXT:    vpandn %xmm3, %xmm1, %xmm0
; AVX1-NEXT:    vmovdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vpmaddubsw %xmm0, %xmm11, %xmm9
; AVX1-NEXT:    vpsllw $8, %xmm9, %xmm0
; AVX1-NEXT:    vpandn %xmm6, %xmm1, %xmm9
; AVX1-NEXT:    vpmaddubsw %xmm9, %xmm7, %xmm5
; AVX1-NEXT:    vpsllw $8, %xmm5, %xmm5
; AVX1-NEXT:    vinsertf128 $1, %xmm5, %ymm0, %ymm0
; AVX1-NEXT:    vandps %ymm1, %ymm2, %ymm2
; AVX1-NEXT:    vorps %ymm0, %ymm2, %ymm6
; AVX1-NEXT:    vpand %xmm4, %xmm10, %xmm2
; AVX1-NEXT:    vpand %xmm4, %xmm14, %xmm4
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm0 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vpand %xmm0, %xmm12, %xmm10
; AVX1-NEXT:    vpand %xmm0, %xmm15, %xmm12
; AVX1-NEXT:    vpmullw %xmm2, %xmm10, %xmm5
; AVX1-NEXT:    vpmullw %xmm4, %xmm12, %xmm14
; AVX1-NEXT:    vinsertf128 $1, %xmm5, %ymm14, %ymm5
; AVX1-NEXT:    vpandn %xmm4, %xmm1, %xmm14
; AVX1-NEXT:    vpmaddubsw %xmm14, %xmm12, %xmm15
; AVX1-NEXT:    vpsllw $8, %xmm15, %xmm15
; AVX1-NEXT:    vpandn %xmm2, %xmm1, %xmm0
; AVX1-NEXT:    vpmaddubsw %xmm0, %xmm10, %xmm8
; AVX1-NEXT:    vpsllw $8, %xmm8, %xmm8
; AVX1-NEXT:    vinsertf128 $1, %xmm8, %ymm15, %ymm8
; AVX1-NEXT:    vandps %ymm1, %ymm5, %ymm5
; AVX1-NEXT:    vorps %ymm5, %ymm8, %ymm5
; AVX1-NEXT:    vxorps %ymm6, %ymm5, %ymm5
; AVX1-NEXT:    vpmullw %xmm2, %xmm7, %xmm2
; AVX1-NEXT:    vpmullw %xmm4, %xmm11, %xmm4
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm4, %ymm2
; AVX1-NEXT:    vpmaddubsw %xmm14, %xmm11, %xmm4
; AVX1-NEXT:    vpmaddubsw %xmm0, %xmm7, %xmm0
; AVX1-NEXT:    vpsllw $8, %xmm4, %xmm4
; AVX1-NEXT:    vpsllw $8, %xmm0, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm4, %ymm0
; AVX1-NEXT:    vandps %ymm1, %ymm2, %ymm2
; AVX1-NEXT:    vorps %ymm0, %ymm2, %ymm0
; AVX1-NEXT:    vpmullw {{[-0-9]+}}(%r{{[sb]}}p), %xmm10, %xmm2 # 16-byte Folded Reload
; AVX1-NEXT:    vpmullw %xmm3, %xmm12, %xmm3
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm3, %ymm2
; AVX1-NEXT:    vandps %ymm1, %ymm2, %ymm1
; AVX1-NEXT:    vpmaddubsw {{[-0-9]+}}(%r{{[sb]}}p), %xmm12, %xmm2 # 16-byte Folded Reload
; AVX1-NEXT:    vpmaddubsw %xmm9, %xmm10, %xmm3
; AVX1-NEXT:    vpsllw $8, %xmm2, %xmm2
; AVX1-NEXT:    vpsllw $8, %xmm3, %xmm3
; AVX1-NEXT:    vinsertf128 $1, %xmm3, %ymm2, %ymm2
; AVX1-NEXT:    vorps %ymm2, %ymm1, %ymm1
; AVX1-NEXT:    vxorps %ymm0, %ymm1, %ymm0
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm2 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX1-NEXT:    vandnps %ymm5, %ymm2, %ymm1
; AVX1-NEXT:    vandps %ymm2, %ymm0, %ymm0
; AVX1-NEXT:    vorps %ymm1, %ymm0, %ymm0
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm1
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm1, %xmm3, %xmm1
; AVX1-NEXT:    vpsrlw $4, %xmm0, %xmm2
; AVX1-NEXT:    vpand %xmm2, %xmm13, %xmm2
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vpor %xmm2, %xmm1, %xmm1
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm2
; AVX1-NEXT:    vpshufb %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm0, %xmm13, %xmm0
; AVX1-NEXT:    vpshufb %xmm0, %xmm4, %xmm0
; AVX1-NEXT:    vpor %xmm0, %xmm2, %xmm0
; AVX1-NEXT:    vpsrlw $1, %xmm1, %xmm1
; AVX1-NEXT:    vpsrlw $1, %xmm0, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm1, %ymm0
; AVX1-NEXT:    vandps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmulh_v32i8:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm2 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX2-NEXT:    vpand %ymm2, %ymm1, %ymm4
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240,0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX2-NEXT:    # ymm3 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm4, %ymm3, %ymm4
; AVX2-NEXT:    vpsrlw $4, %ymm1, %ymm1
; AVX2-NEXT:    vpand %ymm2, %ymm1, %ymm5
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm1 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15,0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX2-NEXT:    # ymm1 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm5, %ymm1, %ymm5
; AVX2-NEXT:    vpor %ymm5, %ymm4, %ymm5
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm4 = [85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85,85]
; AVX2-NEXT:    vpand %ymm4, %ymm5, %ymm6
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm7
; AVX2-NEXT:    vpshufb %ymm7, %ymm3, %ymm7
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm7, %ymm0
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm7 = [170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170,170]
; AVX2-NEXT:    vpand %ymm7, %ymm0, %ymm8
; AVX2-NEXT:    vpmullw %ymm6, %ymm8, %ymm9
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm10 = [255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255]
; AVX2-NEXT:    vpand %ymm10, %ymm9, %ymm9
; AVX2-NEXT:    vpandn %ymm6, %ymm10, %ymm11
; AVX2-NEXT:    vpmaddubsw %ymm11, %ymm8, %ymm12
; AVX2-NEXT:    vpsllw $8, %ymm12, %ymm12
; AVX2-NEXT:    vpor %ymm12, %ymm9, %ymm9
; AVX2-NEXT:    vpand %ymm7, %ymm5, %ymm5
; AVX2-NEXT:    vpand %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    vpmullw %ymm5, %ymm0, %ymm7
; AVX2-NEXT:    vpand %ymm7, %ymm10, %ymm7
; AVX2-NEXT:    vpandn %ymm5, %ymm10, %ymm12
; AVX2-NEXT:    vpmaddubsw %ymm12, %ymm0, %ymm13
; AVX2-NEXT:    vpsllw $8, %ymm13, %ymm13
; AVX2-NEXT:    vpor %ymm7, %ymm13, %ymm7
; AVX2-NEXT:    vpxor %ymm7, %ymm9, %ymm7
; AVX2-NEXT:    vpandn %ymm7, %ymm4, %ymm7
; AVX2-NEXT:    vpmullw %ymm5, %ymm8, %ymm5
; AVX2-NEXT:    vpand %ymm5, %ymm10, %ymm5
; AVX2-NEXT:    vpmaddubsw %ymm12, %ymm8, %ymm8
; AVX2-NEXT:    vpsllw $8, %ymm8, %ymm8
; AVX2-NEXT:    vpor %ymm5, %ymm8, %ymm5
; AVX2-NEXT:    vpmullw %ymm6, %ymm0, %ymm6
; AVX2-NEXT:    vpand %ymm6, %ymm10, %ymm6
; AVX2-NEXT:    vpmaddubsw %ymm11, %ymm0, %ymm0
; AVX2-NEXT:    vpsllw $8, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm6, %ymm0
; AVX2-NEXT:    vpxor %ymm5, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    vpor %ymm7, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm4
; AVX2-NEXT:    vpshufb %ymm4, %ymm3, %ymm3
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm1, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm3, %ymm0
; AVX2-NEXT:    vpsrlw $1, %ymm0, %ymm0
; AVX2-NEXT:    vpand {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmulh_v32i8:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpbroadcastd {{.*#+}} zmm16 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX512-NEXT:    vextracti128 $1, %ymm1, %xmm3
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm8 = xmm3[0],zero,xmm3[1],zero,xmm3[2],zero,xmm3[3],zero,xmm3[4],zero,xmm3[5],zero,xmm3[6],zero,xmm3[7],zero,xmm3[8],zero,xmm3[9],zero,xmm3[10],zero,xmm3[11],zero,xmm3[12],zero,xmm3[13],zero,xmm3[14],zero,xmm3[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm8, %ymm3
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm4
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm9 = xmm4[0],zero,xmm4[1],zero,xmm4[2],zero,xmm4[3],zero,xmm4[4],zero,xmm4[5],zero,xmm4[6],zero,xmm4[7],zero,xmm4[8],zero,xmm4[9],zero,xmm4[10],zero,xmm4[11],zero,xmm4[12],zero,xmm4[13],zero,xmm4[14],zero,xmm4[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm9, %ymm4
; AVX512-NEXT:    vpmullw %ymm3, %ymm4, %ymm5
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm10 = xmm1[0],zero,xmm1[1],zero,xmm1[2],zero,xmm1[3],zero,xmm1[4],zero,xmm1[5],zero,xmm1[6],zero,xmm1[7],zero,xmm1[8],zero,xmm1[9],zero,xmm1[10],zero,xmm1[11],zero,xmm1[12],zero,xmm1[13],zero,xmm1[14],zero,xmm1[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm10, %ymm1
; AVX512-NEXT:    vpmovzxbw {{.*#+}} ymm11 = xmm0[0],zero,xmm0[1],zero,xmm0[2],zero,xmm0[3],zero,xmm0[4],zero,xmm0[5],zero,xmm0[6],zero,xmm0[7],zero,xmm0[8],zero,xmm0[9],zero,xmm0[10],zero,xmm0[11],zero,xmm0[12],zero,xmm0[13],zero,xmm0[14],zero,xmm0[15],zero
; AVX512-NEXT:    vpandq %ymm16, %ymm11, %ymm0
; AVX512-NEXT:    vpmullw %ymm1, %ymm0, %ymm6
; AVX512-NEXT:    vinserti64x4 $1, %ymm5, %zmm6, %zmm12
; AVX512-NEXT:    vpbroadcastd {{.*#+}} zmm17 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX512-NEXT:    vpandq %ymm17, %ymm8, %ymm6
; AVX512-NEXT:    vpbroadcastd {{.*#+}} zmm18 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX512-NEXT:    vpandq %ymm18, %ymm9, %ymm5
; AVX512-NEXT:    vpmullw %ymm6, %ymm5, %ymm15
; AVX512-NEXT:    vpandq %ymm17, %ymm10, %ymm2
; AVX512-NEXT:    vpandq %ymm18, %ymm11, %ymm7
; AVX512-NEXT:    vpmullw %ymm2, %ymm7, %ymm13
; AVX512-NEXT:    vinserti64x4 $1, %ymm15, %zmm13, %zmm13
; AVX512-NEXT:    vpandq %ymm18, %ymm8, %ymm8
; AVX512-NEXT:    vpandq %ymm17, %ymm9, %ymm9
; AVX512-NEXT:    vpmullw %ymm8, %ymm9, %ymm15
; AVX512-NEXT:    vpandq %ymm18, %ymm10, %ymm10
; AVX512-NEXT:    vpandq %ymm17, %ymm11, %ymm11
; AVX512-NEXT:    vpmullw %ymm10, %ymm11, %ymm14
; AVX512-NEXT:    vinserti64x4 $1, %ymm15, %zmm14, %zmm14
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm14 = zmm14 ^ zmm13 ^ zmm12
; AVX512-NEXT:    vpmullw %ymm4, %ymm8, %ymm12
; AVX512-NEXT:    vpmullw %ymm0, %ymm10, %ymm13
; AVX512-NEXT:    vinserti64x4 $1, %ymm12, %zmm13, %zmm12
; AVX512-NEXT:    vpmullw %ymm3, %ymm5, %ymm13
; AVX512-NEXT:    vmovdqa64 %ymm3, %ymm19
; AVX512-NEXT:    vpmullw %ymm1, %ymm7, %ymm15
; AVX512-NEXT:    vinserti64x4 $1, %ymm13, %zmm15, %zmm13
; AVX512-NEXT:    vpmullw %ymm6, %ymm9, %ymm15
; AVX512-NEXT:    vpmullw %ymm2, %ymm11, %ymm3
; AVX512-NEXT:    vinserti64x4 $1, %ymm15, %zmm3, %zmm3
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm3 = zmm3 ^ zmm13 ^ zmm12
; AVX512-NEXT:    vpmullw %ymm6, %ymm4, %ymm4
; AVX512-NEXT:    vpmullw %ymm2, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm4, %zmm0, %zmm0
; AVX512-NEXT:    vpmullw %ymm5, %ymm8, %ymm2
; AVX512-NEXT:    vpmullw %ymm7, %ymm10, %ymm4
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm4, %zmm2
; AVX512-NEXT:    vpxorq %zmm0, %zmm2, %zmm0
; AVX512-NEXT:    vmovdqa64 %ymm19, %ymm2
; AVX512-NEXT:    vpmullw %ymm2, %ymm9, %ymm2
; AVX512-NEXT:    vpmullw %ymm1, %ymm11, %ymm1
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm1, %zmm1
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm1 = zmm18 & (zmm1 ^ zmm0)
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm1 = zmm1 | (zmm3 & zmm16)
; AVX512-NEXT:    vpternlogq {{.*#+}} zmm1 = zmm1 | (zmm14 & zmm17)
; AVX512-NEXT:    vextracti64x4 $1, %zmm1, %ymm0
; AVX512-NEXT:    vpsrlw $8, %ymm0, %ymm0
; AVX512-NEXT:    vpsrlw $8, %ymm1, %ymm1
; AVX512-NEXT:    vpackuswb %ymm0, %ymm1, %ymm0
; AVX512-NEXT:    vpermq {{.*#+}} ymm0 = ymm0[0,2,1,3]
; AVX512-NEXT:    retq
  %a.ext = zext <32 x i8> %a to <32 x i16>
  %b.ext = zext <32 x i8> %b to <32 x i16>
  %clmul = call <32 x i16> @llvm.clmul.v32i16(<32 x i16> %a.ext, <32 x i16> %b.ext)
  %res.ext = lshr <32 x i16> %clmul, splat (i16 8)
  %res = trunc <32 x i16> %res.ext to <32 x i8>
  ret <32 x i8> %res
}

define <16 x i16> @clmulh_v16i16(<16 x i16> %a, <16 x i16> %b) nounwind {
; AVX1-LABEL: clmulh_v16i16:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vmovdqa %ymm0, %ymm12
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm0 = [1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14]
; AVX1-NEXT:    vpshufb %xmm0, %xmm2, %xmm3
; AVX1-NEXT:    vmovdqa %xmm0, %xmm2
; AVX1-NEXT:    vbroadcastss {{.*#+}} xmm7 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm5
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm5, %xmm4, %xmm6
; AVX1-NEXT:    vpsrlw $4, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm3
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm0 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm3, %xmm0, %xmm3
; AVX1-NEXT:    vpor %xmm3, %xmm6, %xmm9
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm3 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX1-NEXT:    vpand %xmm3, %xmm9, %xmm5
; AVX1-NEXT:    vmovdqa %xmm5, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vmovdqa %ymm3, %ymm6
; AVX1-NEXT:    vextractf128 $1, %ymm12, %xmm3
; AVX1-NEXT:    vpshufb %xmm2, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm8
; AVX1-NEXT:    vpshufb %xmm8, %xmm4, %xmm8
; AVX1-NEXT:    vpsrlw $4, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm3
; AVX1-NEXT:    vpshufb %xmm3, %xmm0, %xmm3
; AVX1-NEXT:    vpor %xmm3, %xmm8, %xmm14
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm10 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX1-NEXT:    vpand %xmm10, %xmm14, %xmm8
; AVX1-NEXT:    vpmullw %xmm5, %xmm8, %xmm11
; AVX1-NEXT:    vpshufb %xmm2, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm3
; AVX1-NEXT:    vpshufb %xmm3, %xmm4, %xmm3
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm1
; AVX1-NEXT:    vpshufb %xmm1, %xmm0, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm3, %xmm3
; AVX1-NEXT:    vpand %xmm6, %xmm3, %xmm5
; AVX1-NEXT:    vpshufb %xmm2, %xmm12, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm2
; AVX1-NEXT:    vpshufb %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm1, %xmm1
; AVX1-NEXT:    vpshufb %xmm1, %xmm0, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm2, %xmm0
; AVX1-NEXT:    vpand %xmm0, %xmm10, %xmm4
; AVX1-NEXT:    vpmullw %xmm5, %xmm4, %xmm1
; AVX1-NEXT:    vmovdqa %xmm5, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX1-NEXT:    vinsertf128 $1, %xmm11, %ymm1, %ymm11
; AVX1-NEXT:    vpand %xmm10, %xmm9, %xmm15
; AVX1-NEXT:    vmovdqa %ymm10, %ymm7
; AVX1-NEXT:    vpand %xmm6, %xmm14, %xmm12
; AVX1-NEXT:    vpmullw %xmm15, %xmm12, %xmm1
; AVX1-NEXT:    vpand %xmm7, %xmm3, %xmm2
; AVX1-NEXT:    vpand %xmm6, %xmm0, %xmm13
; AVX1-NEXT:    vpmullw %xmm2, %xmm13, %xmm6
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm6, %ymm1
; AVX1-NEXT:    vxorps %ymm1, %ymm11, %ymm1
; AVX1-NEXT:    vbroadcastss {{.*#+}} ymm10 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX1-NEXT:    vpand %xmm10, %xmm9, %xmm6
; AVX1-NEXT:    vpand %xmm10, %xmm14, %xmm9
; AVX1-NEXT:    vpand %xmm3, %xmm10, %xmm3
; AVX1-NEXT:    vpand %xmm0, %xmm10, %xmm14
; AVX1-NEXT:    vpmullw %xmm6, %xmm9, %xmm0
; AVX1-NEXT:    vpmullw %xmm3, %xmm14, %xmm10
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm10, %ymm0
; AVX1-NEXT:    vxorps %ymm0, %ymm1, %ymm0
; AVX1-NEXT:    vandps %ymm7, %ymm0, %ymm7
; AVX1-NEXT:    vpmullw %xmm6, %xmm8, %xmm1
; AVX1-NEXT:    vpmullw %xmm3, %xmm4, %xmm10
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm10, %ymm1
; AVX1-NEXT:    vmovdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX1-NEXT:    vpmullw %xmm0, %xmm12, %xmm10
; AVX1-NEXT:    vpmullw %xmm5, %xmm13, %xmm11
; AVX1-NEXT:    vinsertf128 $1, %xmm10, %ymm11, %ymm10
; AVX1-NEXT:    vxorps %ymm1, %ymm10, %ymm1
; AVX1-NEXT:    vpmullw %xmm15, %xmm9, %xmm10
; AVX1-NEXT:    vpmullw %xmm2, %xmm14, %xmm11
; AVX1-NEXT:    vinsertf128 $1, %xmm10, %ymm11, %ymm10
; AVX1-NEXT:    vxorps %ymm1, %ymm10, %ymm1
; AVX1-NEXT:    vandps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm1, %ymm1
; AVX1-NEXT:    vorps %ymm7, %ymm1, %ymm5
; AVX1-NEXT:    vpmullw %xmm15, %xmm8, %xmm1
; AVX1-NEXT:    vpmullw %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vinsertf128 $1, %xmm1, %ymm2, %ymm1
; AVX1-NEXT:    vpmullw %xmm6, %xmm12, %xmm2
; AVX1-NEXT:    vpmullw %xmm3, %xmm13, %xmm3
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm3, %ymm2
; AVX1-NEXT:    vxorps %ymm1, %ymm2, %ymm1
; AVX1-NEXT:    vpmullw %xmm0, %xmm9, %xmm2
; AVX1-NEXT:    vpmullw {{[-0-9]+}}(%r{{[sb]}}p), %xmm14, %xmm3 # 16-byte Folded Reload
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm3, %ymm2
; AVX1-NEXT:    vxorps %ymm2, %ymm1, %ymm1
; AVX1-NEXT:    vandps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %ymm1, %ymm1
; AVX1-NEXT:    vorps %ymm1, %ymm5, %ymm0
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm3 = [1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14]
; AVX1-NEXT:    vpshufb %xmm3, %xmm0, %xmm1
; AVX1-NEXT:    vbroadcastss {{.*#+}} xmm6 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX1-NEXT:    vpand %xmm6, %xmm1, %xmm2
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm4 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX1-NEXT:    vpshufb %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm1, %xmm1
; AVX1-NEXT:    vpand %xmm6, %xmm1, %xmm1
; AVX1-NEXT:    vmovdqa {{.*#+}} xmm5 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX1-NEXT:    vpshufb %xmm1, %xmm5, %xmm1
; AVX1-NEXT:    vpor %xmm1, %xmm2, %xmm1
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX1-NEXT:    vpshufb %xmm3, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm6, %xmm0, %xmm2
; AVX1-NEXT:    vpshufb %xmm2, %xmm4, %xmm2
; AVX1-NEXT:    vpsrlw $4, %xmm0, %xmm0
; AVX1-NEXT:    vpand %xmm6, %xmm0, %xmm0
; AVX1-NEXT:    vpshufb %xmm0, %xmm5, %xmm0
; AVX1-NEXT:    vpor %xmm0, %xmm2, %xmm0
; AVX1-NEXT:    vpsrlw $1, %xmm1, %xmm1
; AVX1-NEXT:    vpsrlw $1, %xmm0, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm0, %ymm1, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmulh_v16i16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm2 = [1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14,1,0,3,2,5,4,7,6,9,8,11,10,13,12,15,14]
; AVX2-NEXT:    # ymm2 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm2, %ymm1, %ymm4
; AVX2-NEXT:    vpbroadcastb {{.*#+}} ymm1 = [15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15]
; AVX2-NEXT:    vpand %ymm1, %ymm4, %ymm5
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm3 = [0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240,0,128,64,192,32,160,96,224,16,144,80,208,48,176,112,240]
; AVX2-NEXT:    # ymm3 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm5, %ymm3, %ymm5
; AVX2-NEXT:    vpsrlw $4, %ymm4, %ymm4
; AVX2-NEXT:    vpand %ymm1, %ymm4, %ymm6
; AVX2-NEXT:    vbroadcasti128 {{.*#+}} ymm4 = [0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15,0,8,4,12,2,10,6,14,1,9,5,13,3,11,7,15]
; AVX2-NEXT:    # ymm4 = mem[0,1,0,1]
; AVX2-NEXT:    vpshufb %ymm6, %ymm4, %ymm6
; AVX2-NEXT:    vpor %ymm6, %ymm5, %ymm5
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm6 = [37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449,37449]
; AVX2-NEXT:    vpand %ymm6, %ymm5, %ymm7
; AVX2-NEXT:    vpshufb %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm8
; AVX2-NEXT:    vpshufb %ymm8, %ymm3, %ymm8
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm4, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm8, %ymm0
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm8 = [9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362,9362]
; AVX2-NEXT:    vpand %ymm0, %ymm8, %ymm9
; AVX2-NEXT:    vpmullw %ymm7, %ymm9, %ymm10
; AVX2-NEXT:    vpand %ymm5, %ymm8, %ymm11
; AVX2-NEXT:    vpand %ymm6, %ymm0, %ymm12
; AVX2-NEXT:    vpmullw %ymm11, %ymm12, %ymm13
; AVX2-NEXT:    vpxor %ymm10, %ymm13, %ymm10
; AVX2-NEXT:    vpbroadcastw {{.*#+}} ymm13 = [18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724,18724]
; AVX2-NEXT:    vpand %ymm5, %ymm13, %ymm5
; AVX2-NEXT:    vpand %ymm0, %ymm13, %ymm0
; AVX2-NEXT:    vpmullw %ymm5, %ymm0, %ymm14
; AVX2-NEXT:    vpxor %ymm14, %ymm10, %ymm10
; AVX2-NEXT:    vpand %ymm8, %ymm10, %ymm8
; AVX2-NEXT:    vpmullw %ymm5, %ymm9, %ymm10
; AVX2-NEXT:    vpmullw %ymm7, %ymm12, %ymm14
; AVX2-NEXT:    vpxor %ymm10, %ymm14, %ymm10
; AVX2-NEXT:    vpmullw %ymm0, %ymm11, %ymm14
; AVX2-NEXT:    vpxor %ymm14, %ymm10, %ymm10
; AVX2-NEXT:    vpand %ymm6, %ymm10, %ymm6
; AVX2-NEXT:    vpor %ymm6, %ymm8, %ymm6
; AVX2-NEXT:    vpmullw %ymm11, %ymm9, %ymm8
; AVX2-NEXT:    vpmullw %ymm5, %ymm12, %ymm5
; AVX2-NEXT:    vpxor %ymm5, %ymm8, %ymm5
; AVX2-NEXT:    vpmullw %ymm7, %ymm0, %ymm0
; AVX2-NEXT:    vpxor %ymm0, %ymm5, %ymm0
; AVX2-NEXT:    vpand %ymm0, %ymm13, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm6, %ymm0
; AVX2-NEXT:    vpshufb %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm2
; AVX2-NEXT:    vpshufb %ymm2, %ymm3, %ymm2
; AVX2-NEXT:    vpsrlw $4, %ymm0, %ymm0
; AVX2-NEXT:    vpand %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vpshufb %ymm0, %ymm4, %ymm0
; AVX2-NEXT:    vpor %ymm0, %ymm2, %ymm0
; AVX2-NEXT:    vpsrlw $1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmulh_v16i16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm1 = ymm1[0],zero,ymm1[1],zero,ymm1[2],zero,ymm1[3],zero,ymm1[4],zero,ymm1[5],zero,ymm1[6],zero,ymm1[7],zero,ymm1[8],zero,ymm1[9],zero,ymm1[10],zero,ymm1[11],zero,ymm1[12],zero,ymm1[13],zero,ymm1[14],zero,ymm1[15],zero
; AVX512-NEXT:    vextracti32x4 $3, %zmm1, %xmm2
; AVX512-NEXT:    vpmovzxwd {{.*#+}} zmm0 = ymm0[0],zero,ymm0[1],zero,ymm0[2],zero,ymm0[3],zero,ymm0[4],zero,ymm0[5],zero,ymm0[6],zero,ymm0[7],zero,ymm0[8],zero,ymm0[9],zero,ymm0[10],zero,ymm0[11],zero,ymm0[12],zero,ymm0[13],zero,ymm0[14],zero,ymm0[15],zero
; AVX512-NEXT:    vextracti32x4 $3, %zmm0, %xmm3
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm5 = xmm2[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[1],xmm5[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm5
; AVX512-NEXT:    vmovq %xmm5, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX512-NEXT:    vmovq %xmm2, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm2
; AVX512-NEXT:    vextracti32x4 $2, %zmm1, %xmm3
; AVX512-NEXT:    vextracti32x4 $2, %zmm0, %xmm4
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm7 = xmm4[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm5 = xmm5[0],xmm6[0],xmm5[1],xmm6[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm3, %xmm4, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm4 = xmm4[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm3
; AVX512-NEXT:    vmovq %xmm3, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm3
; AVX512-NEXT:    vinserti128 $1, %xmm2, %ymm3, %ymm2
; AVX512-NEXT:    vextracti128 $1, %ymm1, %xmm3
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm4
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm3[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm7 = xmm4[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm5 = xmm5[0],xmm6[0],xmm5[1],xmm6[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm3, %xmm4, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm5, %xmm5
; AVX512-NEXT:    vpshufd {{.*#+}} xmm3 = xmm3[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm4 = xmm4[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm4, %xmm3
; AVX512-NEXT:    vmovq %xmm3, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm5, %xmm3
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm5 = xmm1[1,1,1,1]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm6 = xmm0[1,1,1,1]
; AVX512-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX512-NEXT:    vpunpckldq {{.*#+}} xmm4 = xmm4[0],xmm5[0],xmm4[1],xmm5[1]
; AVX512-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX512-NEXT:    vmovq %xmm5, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpshufd {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX512-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vmovq %xmm0, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm0, %zmm0
; AVX512-NEXT:    vpsrld $16, %zmm0, %zmm0
; AVX512-NEXT:    vpmovdw %zmm0, %ymm0
; AVX512-NEXT:    retq
  %a.ext = zext <16 x i16> %a to <16 x i32>
  %b.ext = zext <16 x i16> %b to <16 x i32>
  %clmul = call <16 x i32> @llvm.clmul.v16i32(<16 x i32> %a.ext, <16 x i32> %b.ext)
  %res.ext = lshr <16 x i32> %clmul, splat (i32 16)
  %res = trunc <16 x i32> %res.ext to <16 x i16>
  ret <16 x i16> %res
}

define <8 x i32> @clmulh_v8i32(<8 x i32> %a, <8 x i32> %b) nounwind {
; AVX1-LABEL: clmulh_v8i32:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm3
; AVX1-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; AVX1-NEXT:    vpblendw {{.*#+}} xmm4 = xmm3[0,1],xmm2[2,3,4,5,6,7]
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm5
; AVX1-NEXT:    vpblendw {{.*#+}} xmm6 = xmm5[0,1],xmm2[2,3,4,5,6,7]
; AVX1-NEXT:    vpclmulqdq $0, %xmm4, %xmm6, %xmm4
; AVX1-NEXT:    vmovq %xmm4, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vmovd %eax, %xmm4
; AVX1-NEXT:    vpsrlq $32, %xmm3, %xmm6
; AVX1-NEXT:    vpsrlq $32, %xmm5, %xmm7
; AVX1-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX1-NEXT:    vmovq %xmm6, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $1, %eax, %xmm4, %xmm4
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm6 = xmm3[2],xmm2[2],xmm3[3],xmm2[3]
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm5[2],xmm2[2],xmm5[3],xmm2[3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX1-NEXT:    vmovq %xmm6, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm3 = xmm3[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm5[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpclmulqdq $0, %xmm3, %xmm5, %xmm3
; AVX1-NEXT:    vmovq %xmm3, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm3
; AVX1-NEXT:    vpblendw {{.*#+}} xmm4 = xmm1[0,1],xmm2[2,3,4,5,6,7]
; AVX1-NEXT:    vpblendw {{.*#+}} xmm5 = xmm0[0,1],xmm2[2,3,4,5,6,7]
; AVX1-NEXT:    vpclmulqdq $0, %xmm4, %xmm5, %xmm4
; AVX1-NEXT:    vmovq %xmm4, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vmovd %eax, %xmm4
; AVX1-NEXT:    vpsrlq $32, %xmm1, %xmm5
; AVX1-NEXT:    vpsrlq $32, %xmm0, %xmm6
; AVX1-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX1-NEXT:    vmovq %xmm5, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $1, %eax, %xmm4, %xmm4
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm5 = xmm1[2],xmm2[2],xmm1[3],xmm2[3]
; AVX1-NEXT:    vpunpckhdq {{.*#+}} xmm2 = xmm0[2],xmm2[2],xmm0[3],xmm2[3]
; AVX1-NEXT:    vpclmulqdq $0, %xmm5, %xmm2, %xmm2
; AVX1-NEXT:    vmovq %xmm2, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm2
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm1[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vmovq %xmm0, %rax
; AVX1-NEXT:    shrq $32, %rax
; AVX1-NEXT:    vpinsrd $3, %eax, %xmm2, %xmm0
; AVX1-NEXT:    vinsertf128 $1, %xmm3, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-LABEL: clmulh_v8i32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextracti128 $1, %ymm1, %xmm3
; AVX2-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vpblendd {{.*#+}} xmm4 = xmm3[0],xmm2[1,2,3]
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm5
; AVX2-NEXT:    vpblendd {{.*#+}} xmm6 = xmm5[0],xmm2[1,2,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm4, %xmm6, %xmm4
; AVX2-NEXT:    vmovq %xmm4, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vmovd %eax, %xmm4
; AVX2-NEXT:    vpsrlq $32, %xmm3, %xmm6
; AVX2-NEXT:    vpsrlq $32, %xmm5, %xmm7
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $1, %eax, %xmm4, %xmm4
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm6 = xmm3[2],xmm2[2],xmm3[3],xmm2[3]
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm5[2],xmm2[2],xmm5[3],xmm2[3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX2-NEXT:    vmovq %xmm6, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm3 = xmm3[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm5[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpclmulqdq $0, %xmm3, %xmm5, %xmm3
; AVX2-NEXT:    vmovq %xmm3, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm3
; AVX2-NEXT:    vpblendd {{.*#+}} xmm4 = xmm1[0],xmm2[1,2,3]
; AVX2-NEXT:    vpblendd {{.*#+}} xmm5 = xmm0[0],xmm2[1,2,3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm4, %xmm5, %xmm4
; AVX2-NEXT:    vmovq %xmm4, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vmovd %eax, %xmm4
; AVX2-NEXT:    vpsrlq $32, %xmm1, %xmm5
; AVX2-NEXT:    vpsrlq $32, %xmm0, %xmm6
; AVX2-NEXT:    vpclmulqdq $0, %xmm5, %xmm6, %xmm5
; AVX2-NEXT:    vmovq %xmm5, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $1, %eax, %xmm4, %xmm4
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm5 = xmm1[2],xmm2[2],xmm1[3],xmm2[3]
; AVX2-NEXT:    vpunpckhdq {{.*#+}} xmm2 = xmm0[2],xmm2[2],xmm0[3],xmm2[3]
; AVX2-NEXT:    vpclmulqdq $0, %xmm5, %xmm2, %xmm2
; AVX2-NEXT:    vmovq %xmm2, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm2
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm1[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vmovq %xmm0, %rax
; AVX2-NEXT:    shrq $32, %rax
; AVX2-NEXT:    vpinsrd $3, %eax, %xmm2, %xmm0
; AVX2-NEXT:    vinserti128 $1, %xmm3, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: clmulh_v8i32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextracti128 $1, %ymm1, %xmm3
; AVX512-NEXT:    vpxor %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vpblendd {{.*#+}} xmm4 = xmm3[0],xmm2[1,2,3]
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm5
; AVX512-NEXT:    vpblendd {{.*#+}} xmm6 = xmm5[0],xmm2[1,2,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm4, %xmm6, %xmm4
; AVX512-NEXT:    vmovq %xmm4, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vmovd %eax, %xmm4
; AVX512-NEXT:    vpsrlq $32, %xmm3, %xmm6
; AVX512-NEXT:    vpsrlq $32, %xmm5, %xmm7
; AVX512-NEXT:    vpclmulqdq $0, %xmm6, %xmm7, %xmm6
; AVX512-NEXT:    vmovq %xmm6, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $1, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpxor %xmm6, %xmm6, %xmm6
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm7 = xmm3[2],xmm6[2],xmm3[3],xmm6[3]
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm8 = xmm5[2],xmm6[2],xmm5[3],xmm6[3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm7, %xmm8, %xmm7
; AVX512-NEXT:    vmovq %xmm7, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm4, %xmm4
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm3 = xmm3[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm5[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpclmulqdq $0, %xmm3, %xmm5, %xmm3
; AVX512-NEXT:    vmovq %xmm3, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm4, %xmm3
; AVX512-NEXT:    vpblendd {{.*#+}} xmm4 = xmm1[0],xmm2[1,2,3]
; AVX512-NEXT:    vpblendd {{.*#+}} xmm2 = xmm0[0],xmm2[1,2,3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm4, %xmm2, %xmm2
; AVX512-NEXT:    vmovq %xmm2, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vmovd %eax, %xmm2
; AVX512-NEXT:    vpsrlq $32, %xmm1, %xmm4
; AVX512-NEXT:    vpsrlq $32, %xmm0, %xmm5
; AVX512-NEXT:    vpclmulqdq $0, %xmm4, %xmm5, %xmm4
; AVX512-NEXT:    vmovq %xmm4, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $1, %eax, %xmm2, %xmm2
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm4 = xmm1[2],xmm6[2],xmm1[3],xmm6[3]
; AVX512-NEXT:    vpunpckhdq {{.*#+}} xmm5 = xmm0[2],xmm6[2],xmm0[3],xmm6[3]
; AVX512-NEXT:    vpclmulqdq $0, %xmm4, %xmm5, %xmm4
; AVX512-NEXT:    vmovq %xmm4, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $2, %eax, %xmm2, %xmm2
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm1[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vmovq %xmm0, %rax
; AVX512-NEXT:    shrq $32, %rax
; AVX512-NEXT:    vpinsrd $3, %eax, %xmm2, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %a.ext = zext <8 x i32> %a to <8 x i64>
  %b.ext = zext <8 x i32> %b to <8 x i64>
  %clmul = call <8 x i64> @llvm.clmul.v8i64(<8 x i64> %a.ext, <8 x i64> %b.ext)
  %res.ext = lshr <8 x i64> %clmul, splat (i64 32)
  %res = trunc <8 x i64> %res.ext to <8 x i32>
  ret <8 x i32> %res
}

define <4 x i64> @clmulh_v4i64(<4 x i64> %a, <4 x i64> %b) nounwind {
; AVX1-LABEL: clmulh_v4i64:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm4
; AVX1-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX1-NEXT:    vpunpckhqdq {{.*#+}} xmm2 = xmm2[1],xmm4[1]
; AVX1-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm3
; AVX1-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpunpckhqdq {{.*#+}} xmm0 = xmm0[1],xmm3[1]
; AVX1-NEXT:    vinsertf128 $1, %xmm2, %ymm0, %ymm0
; AVX1-NEXT:    retq
;
; AVX2-PCLMUL-LABEL: clmulh_v4i64:
; AVX2-PCLMUL:       # %bb.0:
; AVX2-PCLMUL-NEXT:    vextracti128 $1, %ymm1, %xmm2
; AVX2-PCLMUL-NEXT:    vextracti128 $1, %ymm0, %xmm3
; AVX2-PCLMUL-NEXT:    vpclmulqdq $17, %xmm2, %xmm3, %xmm4
; AVX2-PCLMUL-NEXT:    vpclmulqdq $17, %xmm1, %xmm0, %xmm5
; AVX2-PCLMUL-NEXT:    vinserti128 $1, %xmm4, %ymm5, %ymm4
; AVX2-PCLMUL-NEXT:    vpclmulqdq $0, %xmm2, %xmm3, %xmm2
; AVX2-PCLMUL-NEXT:    vpclmulqdq $0, %xmm1, %xmm0, %xmm0
; AVX2-PCLMUL-NEXT:    vinserti128 $1, %xmm2, %ymm0, %ymm0
; AVX2-PCLMUL-NEXT:    vpunpckhqdq {{.*#+}} ymm0 = ymm0[1],ymm4[1],ymm0[3],ymm4[3]
; AVX2-PCLMUL-NEXT:    retq
;
; AVX2-VPCLMULQDQ-LABEL: clmulh_v4i64:
; AVX2-VPCLMULQDQ:       # %bb.0:
; AVX2-VPCLMULQDQ-NEXT:    vpclmulqdq $17, %ymm1, %ymm0, %ymm2
; AVX2-VPCLMULQDQ-NEXT:    vpclmulqdq $0, %ymm1, %ymm0, %ymm0
; AVX2-VPCLMULQDQ-NEXT:    vpunpckhqdq {{.*#+}} ymm0 = ymm0[1],ymm2[1],ymm0[3],ymm2[3]
; AVX2-VPCLMULQDQ-NEXT:    retq
;
; AVX512-LABEL: clmulh_v4i64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpclmulqdq $17, %ymm1, %ymm0, %ymm2
; AVX512-NEXT:    vpclmulqdq $0, %ymm1, %ymm0, %ymm0
; AVX512-NEXT:    vpunpckhqdq {{.*#+}} ymm0 = ymm0[1],ymm2[1],ymm0[3],ymm2[3]
; AVX512-NEXT:    retq
  %a.ext = zext <4 x i64> %a to <4 x i128>
  %b.ext = zext <4 x i64> %b to <4 x i128>
  %clmul = call <4 x i128> @llvm.clmul.v4i128(<4 x i128> %a.ext, <4 x i128> %b.ext)
  %res.ext = lshr <4 x i128> %clmul, splat (i128 64)
  %res = trunc <4 x i128> %res.ext to <4 x i64>
  ret <4 x i64> %res
}
