; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-- -mattr=+sse2,+pclmul | FileCheck %s

; Minimal test for i686 PCLMULQDQ lowering

define i32 @clmul_i32(i32 %a, i32 %b) nounwind {
; CHECK-LABEL: clmul_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movd {{.*#+}} xmm0 = mem[0],zero,zero,zero
; CHECK-NEXT:    movd {{.*#+}} xmm1 = mem[0],zero,zero,zero
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    retl
  %res = call i32 @llvm.clmul.i32(i32 %a, i32 %b)
  ret i32 %res
}

define i64 @clmul_i64(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: clmul_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq {{.*#+}} xmm0 = mem[0],zero
; CHECK-NEXT:    movq {{.*#+}} xmm1 = mem[0],zero
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[1,1,1,1]
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    retl
  %res = call i64 @llvm.clmul.i64(i64 %a, i64 %b)
  ret i64 %res
}

define i64 @clmulr_i64(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: clmulr_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    bswapl %ecx
; CHECK-NEXT:    movl %ecx, %edx
; CHECK-NEXT:    andl $252645135, %edx # imm = 0xF0F0F0F
; CHECK-NEXT:    shll $4, %edx
; CHECK-NEXT:    shrl $4, %ecx
; CHECK-NEXT:    andl $252645135, %ecx # imm = 0xF0F0F0F
; CHECK-NEXT:    orl %edx, %ecx
; CHECK-NEXT:    movl %ecx, %edx
; CHECK-NEXT:    andl $858993459, %edx # imm = 0x33333333
; CHECK-NEXT:    shrl $2, %ecx
; CHECK-NEXT:    andl $858993459, %ecx # imm = 0x33333333
; CHECK-NEXT:    leal (%ecx,%edx,4), %ecx
; CHECK-NEXT:    movl %ecx, %edx
; CHECK-NEXT:    andl $1431655765, %edx # imm = 0x55555555
; CHECK-NEXT:    shrl %ecx
; CHECK-NEXT:    andl $1431655765, %ecx # imm = 0x55555555
; CHECK-NEXT:    leal (%ecx,%edx,2), %ecx
; CHECK-NEXT:    movd %ecx, %xmm1
; CHECK-NEXT:    bswapl %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $252645135, %ecx # imm = 0xF0F0F0F
; CHECK-NEXT:    shll $4, %ecx
; CHECK-NEXT:    shrl $4, %eax
; CHECK-NEXT:    andl $252645135, %eax # imm = 0xF0F0F0F
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $858993459, %ecx # imm = 0x33333333
; CHECK-NEXT:    shrl $2, %eax
; CHECK-NEXT:    andl $858993459, %eax # imm = 0x33333333
; CHECK-NEXT:    leal (%eax,%ecx,4), %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $1431655765, %ecx # imm = 0x55555555
; CHECK-NEXT:    shrl %eax
; CHECK-NEXT:    andl $1431655765, %eax # imm = 0x55555555
; CHECK-NEXT:    leal (%eax,%ecx,2), %eax
; CHECK-NEXT:    movd %eax, %xmm0
; CHECK-NEXT:    punpckldq {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[1],xmm1[1]
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    bswapl %ecx
; CHECK-NEXT:    movl %ecx, %edx
; CHECK-NEXT:    andl $252645135, %edx # imm = 0xF0F0F0F
; CHECK-NEXT:    shll $4, %edx
; CHECK-NEXT:    shrl $4, %ecx
; CHECK-NEXT:    andl $252645135, %ecx # imm = 0xF0F0F0F
; CHECK-NEXT:    orl %edx, %ecx
; CHECK-NEXT:    movl %ecx, %edx
; CHECK-NEXT:    andl $858993459, %edx # imm = 0x33333333
; CHECK-NEXT:    shrl $2, %ecx
; CHECK-NEXT:    andl $858993459, %ecx # imm = 0x33333333
; CHECK-NEXT:    leal (%ecx,%edx,4), %ecx
; CHECK-NEXT:    movl %ecx, %edx
; CHECK-NEXT:    andl $1431655765, %edx # imm = 0x55555555
; CHECK-NEXT:    shrl %ecx
; CHECK-NEXT:    andl $1431655765, %ecx # imm = 0x55555555
; CHECK-NEXT:    leal (%ecx,%edx,2), %ecx
; CHECK-NEXT:    movd %ecx, %xmm2
; CHECK-NEXT:    bswapl %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $252645135, %ecx # imm = 0xF0F0F0F
; CHECK-NEXT:    shll $4, %ecx
; CHECK-NEXT:    shrl $4, %eax
; CHECK-NEXT:    andl $252645135, %eax # imm = 0xF0F0F0F
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $858993459, %ecx # imm = 0x33333333
; CHECK-NEXT:    shrl $2, %eax
; CHECK-NEXT:    andl $858993459, %eax # imm = 0x33333333
; CHECK-NEXT:    leal (%eax,%ecx,4), %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $1431655765, %ecx # imm = 0x55555555
; CHECK-NEXT:    shrl %eax
; CHECK-NEXT:    andl $1431655765, %eax # imm = 0x55555555
; CHECK-NEXT:    leal (%eax,%ecx,2), %eax
; CHECK-NEXT:    movd %eax, %xmm1
; CHECK-NEXT:    punpckldq {{.*#+}} xmm1 = xmm1[0],xmm2[0],xmm1[1],xmm2[1]
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    bswapl %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $252645135, %ecx # imm = 0xF0F0F0F
; CHECK-NEXT:    shll $4, %ecx
; CHECK-NEXT:    shrl $4, %eax
; CHECK-NEXT:    andl $252645135, %eax # imm = 0xF0F0F0F
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $858993459, %ecx # imm = 0x33333333
; CHECK-NEXT:    shrl $2, %eax
; CHECK-NEXT:    andl $858993459, %eax # imm = 0x33333333
; CHECK-NEXT:    leal (%eax,%ecx,4), %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $1431655765, %ecx # imm = 0x55555555
; CHECK-NEXT:    shrl %eax
; CHECK-NEXT:    andl $1431655765, %eax # imm = 0x55555555
; CHECK-NEXT:    leal (%eax,%ecx,2), %edx
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[1,1,1,1]
; CHECK-NEXT:    movd %xmm0, %eax
; CHECK-NEXT:    bswapl %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $252645135, %ecx # imm = 0xF0F0F0F
; CHECK-NEXT:    shll $4, %ecx
; CHECK-NEXT:    shrl $4, %eax
; CHECK-NEXT:    andl $252645135, %eax # imm = 0xF0F0F0F
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $858993459, %ecx # imm = 0x33333333
; CHECK-NEXT:    shrl $2, %eax
; CHECK-NEXT:    andl $858993459, %eax # imm = 0x33333333
; CHECK-NEXT:    leal (%eax,%ecx,4), %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    andl $1431655765, %ecx # imm = 0x55555555
; CHECK-NEXT:    shrl %eax
; CHECK-NEXT:    andl $1431655765, %eax # imm = 0x55555555
; CHECK-NEXT:    leal (%eax,%ecx,2), %eax
; CHECK-NEXT:    retl
  %a.ext = zext i64 %a to i128
  %b.ext = zext i64 %b to i128
  %clmul = call i128 @llvm.clmul.i128(i128 %a.ext, i128 %b.ext)
  %res.ext = lshr i128 %clmul, 63
  %res = trunc i128 %res.ext to i64
  ret i64 %res
}

define i64 @clmulh_i64(i64 %a, i64 %b) nounwind {
; CHECK-LABEL: clmulh_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq {{.*#+}} xmm0 = mem[0],zero
; CHECK-NEXT:    movq {{.*#+}} xmm1 = mem[0],zero
; CHECK-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[2,3,2,3]
; CHECK-NEXT:    movd %xmm0, %eax
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm1[3,3,3,3]
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    retl
  %a.ext = zext i64 %a to i128
  %b.ext = zext i64 %b to i128
  %clmul = call i128 @llvm.clmul.i128(i128 %a.ext, i128 %b.ext)
  %res.ext = lshr i128 %clmul, 64
  %res = trunc i128 %res.ext to i64
  ret i64 %res
}
