; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-- | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s --check-prefix=X64

define i32 @icmp_slt_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_slt_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setl %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_slt_i256:
; X64:       # %bb.0:
; X64-NEXT:    cmpq %r8, %rdi
; X64-NEXT:    sbbq %r9, %rsi
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rdx
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    setl %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp slt i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @icmp_sgt_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_sgt_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setl %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_sgt_i256:
; X64:       # %bb.0:
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; X64-NEXT:    cmpq %rdi, %r8
; X64-NEXT:    sbbq %rsi, %r9
; X64-NEXT:    sbbq %rdx, %r10
; X64-NEXT:    sbbq %rcx, %rax
; X64-NEXT:    setl %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp sgt i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @icmp_sle_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_sle_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setge %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_sle_i256:
; X64:       # %bb.0:
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; X64-NEXT:    cmpq %rdi, %r8
; X64-NEXT:    sbbq %rsi, %r9
; X64-NEXT:    sbbq %rdx, %r10
; X64-NEXT:    sbbq %rcx, %rax
; X64-NEXT:    setge %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp sle i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @icmp_sge_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_sge_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setge %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_sge_i256:
; X64:       # %bb.0:
; X64-NEXT:    cmpq %r8, %rdi
; X64-NEXT:    sbbq %r9, %rsi
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rdx
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    setge %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp sge i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @icmp_ult_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_ult_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setb %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_ult_i256:
; X64:       # %bb.0:
; X64-NEXT:    cmpq %r8, %rdi
; X64-NEXT:    sbbq %r9, %rsi
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rdx
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    setb %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp ult i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @icmp_ugt_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_ugt_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setb %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_ugt_i256:
; X64:       # %bb.0:
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; X64-NEXT:    cmpq %rdi, %r8
; X64-NEXT:    sbbq %rsi, %r9
; X64-NEXT:    sbbq %rdx, %r10
; X64-NEXT:    sbbq %rcx, %rax
; X64-NEXT:    setb %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp ugt i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @icmp_ule_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_ule_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setae %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_ule_i256:
; X64:       # %bb.0:
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; X64-NEXT:    cmpq %rdi, %r8
; X64-NEXT:    sbbq %rsi, %r9
; X64-NEXT:    sbbq %rdx, %r10
; X64-NEXT:    sbbq %rcx, %rax
; X64-NEXT:    setae %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp ule i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

define i32 @icmp_uge_i256(i256 %a, i256 %b) nounwind {
; X86-LABEL: icmp_uge_i256:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    setae %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    retl
;
; X64-LABEL: icmp_uge_i256:
; X64:       # %bb.0:
; X64-NEXT:    cmpq %r8, %rdi
; X64-NEXT:    sbbq %r9, %rsi
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rdx
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    setae %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    retq
  %c = icmp uge i256 %a, %b
  %r = zext i1 %c to i32
  ret i32 %r
}

; Select based on i256 comparison
define i256 @select_slt_i256(i256 %a, i256 %b, i256 %x, i256 %y) nounwind {
; X86-LABEL: select_slt_i256:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    subl $8, %esp
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    sbbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    jl .LBB8_1
; X86-NEXT:  # %bb.2:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jge .LBB8_5
; X86-NEXT:  .LBB8_4:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-NEXT:    jge .LBB8_8
; X86-NEXT:  .LBB8_7:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %esi
; X86-NEXT:    jge .LBB8_11
; X86-NEXT:  .LBB8_10:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %edi
; X86-NEXT:    jge .LBB8_14
; X86-NEXT:  .LBB8_13:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %ebx
; X86-NEXT:    jge .LBB8_17
; X86-NEXT:  .LBB8_16:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %ebp
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    jge .LBB8_20
; X86-NEXT:  .LBB8_19:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    jmp .LBB8_21
; X86-NEXT:  .LBB8_1:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jl .LBB8_4
; X86-NEXT:  .LBB8_5:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-NEXT:    jl .LBB8_7
; X86-NEXT:  .LBB8_8:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %esi
; X86-NEXT:    jl .LBB8_10
; X86-NEXT:  .LBB8_11:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %edi
; X86-NEXT:    jl .LBB8_13
; X86-NEXT:  .LBB8_14:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %ebx
; X86-NEXT:    jl .LBB8_16
; X86-NEXT:  .LBB8_17:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %ebp
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    jl .LBB8_19
; X86-NEXT:  .LBB8_20:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %ecx
; X86-NEXT:  .LBB8_21:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl (%edx), %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl (%esp), %edx # 4-byte Reload
; X86-NEXT:    movl (%edx), %edx
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    movl (%esi), %esi
; X86-NEXT:    movl (%edi), %edi
; X86-NEXT:    movl (%ebx), %ebx
; X86-NEXT:    movl (%ebp), %ebp
; X86-NEXT:    movl (%ecx), %ecx
; X86-NEXT:    jl .LBB8_22
; X86-NEXT:  # %bb.23:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %edx
; X86-NEXT:    jmp .LBB8_24
; X86-NEXT:  .LBB8_22:
; X86-NEXT:    leal {{[0-9]+}}(%esp), %edx
; X86-NEXT:  .LBB8_24:
; X86-NEXT:    movl (%edx), %edx
; X86-NEXT:    movl %edx, 28(%eax)
; X86-NEXT:    movl %ecx, 24(%eax)
; X86-NEXT:    movl %ebp, 20(%eax)
; X86-NEXT:    movl %ebx, 16(%eax)
; X86-NEXT:    movl %edi, 12(%eax)
; X86-NEXT:    movl %esi, 8(%eax)
; X86-NEXT:    movl (%esp), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 4(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, (%eax)
; X86-NEXT:    addl $8, %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
;
; X64-LABEL: select_slt_i256:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    cmpq %r9, %rsi
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rdx
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    sbbq {{[0-9]+}}(%rsp), %r8
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; X64-NEXT:    cmovlq %rcx, %rdx
; X64-NEXT:    movq (%rdx), %rcx
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %rdx
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; X64-NEXT:    cmovlq %rdx, %rsi
; X64-NEXT:    movq (%rsi), %rdx
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %rsi
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; X64-NEXT:    cmovlq %rsi, %rdi
; X64-NEXT:    movq (%rdi), %rsi
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; X64-NEXT:    leaq {{[0-9]+}}(%rsp), %r8
; X64-NEXT:    cmovlq %rdi, %r8
; X64-NEXT:    movq (%r8), %rdi
; X64-NEXT:    movq %rdi, 24(%rax)
; X64-NEXT:    movq %rsi, 16(%rax)
; X64-NEXT:    movq %rdx, 8(%rax)
; X64-NEXT:    movq %rcx, (%rax)
; X64-NEXT:    retq
  %c = icmp slt i256 %a, %b
  %r = select i1 %c, i256 %x, i256 %y
  ret i256 %r
}
