; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; Multi-word unsigned subtract with a short-circuit AND of the final borrow
; (`extra && bo ? fb : d`) where the 24-byte struct return goes via sret,
; so the select becomes a pointer select + memcpy. Clang's
; `select cond, freeze(bo), false` lowering hides the final SETCC under a
; FREEZE. DAGCombiner::visitFREEZE folds that freeze away (X86ISD::SETCC
; is marked unconditionally non-poison), but until the worklist was fixed
; the consuming BRCOND/CMOV was not re-added — so
; checkBoolTestSetCCCombine never fired and the asm retained a redundant
; setb/testb pair after the final SBB.
;
; After the fix the final borrow is consumed directly via the CF produced
; by the last SBB.

%U = type { [3 x i64] }

define void @sel(ptr sret(%U) align 8 %r, i64 %x0, i64 %x1, i64 %x2, i64 %m0, i64 %m1, i64 %m2, ptr %fb, i1 %extra) {
; CHECK-LABEL: sel:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    subq %r8, %rsi
; CHECK-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    sbbq %r9, %rdx
; CHECK-NEXT:    movq %rdx, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    sbbq {{[0-9]+}}(%rsp), %rcx
; CHECK-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; CHECK-NEXT:    leaq -{{[0-9]+}}(%rsp), %rcx
; CHECK-NEXT:    movq %rcx, %rdx
; CHECK-NEXT:    jae .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    movq {{[0-9]+}}(%rsp), %rdx
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    testb $1, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    cmovneq %rdx, %rcx
; CHECK-NEXT:    movq 16(%rcx), %rdx
; CHECK-NEXT:    movq %rdx, 16(%rax)
; CHECK-NEXT:    movq (%rcx), %rdx
; CHECK-NEXT:    movq 8(%rcx), %rcx
; CHECK-NEXT:    movq %rcx, 8(%rax)
; CHECK-NEXT:    movq %rdx, (%rax)
; CHECK-NEXT:    retq
  %d = alloca %U, align 8
  %s0 = call { i64, i1 } @llvm.usub.with.overflow.i64(i64 %x0, i64 %m0)
  %v0 = extractvalue { i64, i1 } %s0, 0
  %b0 = extractvalue { i64, i1 } %s0, 1
  %z0 = zext i1 %b0 to i64
  store i64 %v0, ptr %d
  %s1 = call { i64, i1 } @llvm.usub.with.overflow.i64(i64 %x1, i64 %m1)
  %v1a = extractvalue { i64, i1 } %s1, 0
  %b1a = extractvalue { i64, i1 } %s1, 1
  %s1b = call { i64, i1 } @llvm.usub.with.overflow.i64(i64 %v1a, i64 %z0)
  %v1 = extractvalue { i64, i1 } %s1b, 0
  %b1b = extractvalue { i64, i1 } %s1b, 1
  %b1 = or i1 %b1a, %b1b
  %z1 = zext i1 %b1 to i64
  %p1 = getelementptr i8, ptr %d, i64 8
  store i64 %v1, ptr %p1
  %s2 = call { i64, i1 } @llvm.usub.with.overflow.i64(i64 %x2, i64 %m2)
  %v2a = extractvalue { i64, i1 } %s2, 0
  %b2a = extractvalue { i64, i1 } %s2, 1
  %s2b = call { i64, i1 } @llvm.usub.with.overflow.i64(i64 %v2a, i64 %z1)
  %v2 = extractvalue { i64, i1 } %s2b, 0
  %b2b = extractvalue { i64, i1 } %s2b, 1
  %b2 = or i1 %b2a, %b2b
  %p2 = getelementptr i8, ptr %d, i64 16
  store i64 %v2, ptr %p2
  %gate = select i1 %extra, i1 %b2, i1 false
  %sel = select i1 %gate, ptr %fb, ptr %d
  call void @llvm.memcpy.p0.p0.i64(ptr %r, ptr %sel, i64 24, i1 false)
  ret void
}

declare { i64, i1 } @llvm.usub.with.overflow.i64(i64, i64)
declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)
