# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=x86_64 -run-pass=register-coalescer -enable-subreg-liveness -o - %s | FileCheck %s

# After coalescing %0, we shouldn't add an implicit-def for 'OR32ri' because the result is dead.
---
name: dead_def
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: dead_def
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[DEF:%[0-9]+]].sub_32bit:gr64_with_sub_8bit = IMPLICIT_DEF implicit-def [[DEF]]
  ; CHECK-NEXT:   JCC_1 %bb.2, 5, implicit $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   RET 0, implicit [[DEF]]
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.3(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[V_SET0_:%[0-9]+]]:vr128 = V_SET0
  ; CHECK-NEXT:   MOVAPSmr $noreg, 1, $noreg, 64, $noreg, [[V_SET0_]]
  ; CHECK-NEXT:   MOVAPSmr $noreg, 1, $noreg, 48, $noreg, [[V_SET0_]]
  ; CHECK-NEXT:   MOVAPSmr $noreg, 1, $noreg, 32, $noreg, [[V_SET0_]]
  ; CHECK-NEXT:   MOVAPSmr $noreg, 1, $noreg, 16, $noreg, [[V_SET0_]]
  ; CHECK-NEXT:   MOVAPSmr $noreg, 1, $noreg, 0, $noreg, [[V_SET0_]]
  ; CHECK-NEXT:   dead [[DEF1:%[0-9]+]]:gr32 = IMPLICIT_DEF
  ; CHECK-NEXT:   dead [[DEF:%[0-9]+]].sub_32bit:gr64_with_sub_8bit = OR32ri [[DEF]].sub_32bit, 1, implicit-def $eflags
  ; CHECK-NEXT:   JMP_1 %bb.3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[DEF:%[0-9]+]].sub_32bit:gr64_with_sub_8bit = MOV32ri 1, implicit-def [[DEF]]
  ; CHECK-NEXT:   JMP_1 %bb.2
  bb.0:
    liveins: $eflags

    %0:gr32 = IMPLICIT_DEF
    JCC_1 %bb.3, 5, implicit killed $eflags

  bb.2:
    %1:gr64 = SUBREG_TO_REG 0, %0, %subreg.sub_32bit
    RET 0, implicit %1

  bb.3:
    %2:vr128 = V_SET0
    MOVAPSmr $noreg, 1, $noreg, 64, $noreg, %2
    MOVAPSmr $noreg, 1, $noreg, 48, $noreg, %2
    MOVAPSmr $noreg, 1, $noreg, 32, $noreg, %2
    MOVAPSmr $noreg, 1, $noreg, 16, $noreg, %2
    MOVAPSmr $noreg, 1, $noreg, 0, $noreg, killed %2
    dead %10:gr32 = IMPLICIT_DEF
    dead %0:gr32 = OR32ri %0, 1, implicit-def $eflags
    JMP_1 %bb.5

  bb.5:
    %0:gr32 = MOV32ri 1
    JMP_1 %bb.3
...
