# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=x86_64 -run-pass=register-coalescer -o - %s | FileCheck %s

# The COPY can't be removed by commuting the AND since the instruction only partially defines the register
---
name: commute_tied_subreg_def_part
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: commute_tied_subreg_def_part
    ; CHECK: %A:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (volatile load (s64))
    ; CHECK-NEXT: %B:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (load (s64))
    ; CHECK-NEXT: %A.sub_32bit:gr64_with_sub_8bit = AND32rr %A.sub_32bit, %B.sub_32bit, implicit-def dead $eflags
    ; CHECK-NEXT: MOV64mr $noreg, 1, $noreg, 0, $noreg, %A :: (store (s64))
    ; CHECK-NEXT: %B:gr64_with_sub_8bit = COPY %A
    ; CHECK-NEXT: RET 0, implicit %B
    %A:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (volatile load (s64))
    %B:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (load (s64))
    %A.sub_32bit:gr64_with_sub_8bit = AND32rr %A.sub_32bit, %B.sub_32bit, implicit-def dead $eflags
    MOV64mr $noreg, 1, $noreg, 0, $noreg, %A :: (store (s64))
    %B:gr64_with_sub_8bit = COPY %A
    RET 0, implicit %B
...

# The COPY can be removed by commuting the AND since the instruction defines the entire register
---
name: commute_tied_subreg_def_full
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: commute_tied_subreg_def_full
    ; CHECK: %A:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (volatile load (s64))
    ; CHECK-NEXT: %B:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (load (s64))
    ; CHECK-NEXT: %B.sub_32bit:gr64_with_sub_8bit = AND32rr %B.sub_32bit, %A.sub_32bit, implicit-def dead $eflags, implicit-def %B
    ; CHECK-NEXT: MOV64mr $noreg, 1, $noreg, 0, $noreg, %B :: (store (s64))
    ; CHECK-NEXT: RET 0, implicit %B
    %A:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (volatile load (s64))
    %B:gr64_with_sub_8bit = MOV64rm $noreg, 1, $noreg, 0, $noreg :: (load (s64))
    %A.sub_32bit:gr64_with_sub_8bit = AND32rr %A.sub_32bit, %B.sub_32bit, implicit-def dead $eflags, implicit-def %A
    MOV64mr $noreg, 1, $noreg, 0, $noreg, %A :: (store (s64))
    %B:gr64_with_sub_8bit = COPY %A
    RET 0, implicit %B
...
