; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=x86_64 -enable-ext-tsp-block-placement=1 < %s | FileCheck %s

; Test that dominator tree is invalidated after block removals.

define fastcc i1 @fn(i1 %0) {
; CHECK-LABEL: fn:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    je .LBB0_3
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    jne .LBB0_2
; CHECK-NEXT:  .LBB0_3:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_2:
; CHECK-NEXT:    movb $1, %al
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  br i1 %0, label %2, label %4

2:                                                ; preds = %1
  br i1 %0, label %3, label %4

3:                                                ; preds = %2
  br label %4

4:                                                ; preds = %3, %2, %1
  %5 = phi i1 [ true, %3 ], [ false, %1 ], [ false, %2 ]
  ret i1 %5
}

!llvm.module.flags = !{!0}

!0 = !{i32 1, !"ProfileSummary", !1}
!1 = !{!2, !3, !4, !5, !6, !7, !8, !9, !10, !11}
!2 = !{!"ProfileFormat", !"InstrProf"}
!3 = !{!"TotalCount", i64 87557062425}
!4 = !{!"MaxCount", i64 626551227}
!5 = !{!"MaxInternalCount", i64 626551227}
!6 = !{!"MaxFunctionCount", i64 510580166}
!7 = !{!"NumCounts", i64 5667726}
!8 = !{!"NumFunctions", i64 963638}
!9 = !{!"IsPartialProfile", i64 0}
!10 = !{!"PartialProfileRatio", double 0.000000e+00}
!11 = !{!"DetailedSummary", !12}
!12 = !{!13, !14, !15, !16, !17, !18, !19, !20, !21, !22, !23, !24, !25, !26, !27, !28}
!13 = !{i32 10000, i64 510580166, i32 2}
!14 = !{i32 100000, i64 101501872, i32 50}
!15 = !{i32 200000, i64 33917881, i32 208}
!16 = !{i32 300000, i64 19300443, i32 554}
!17 = !{i32 400000, i64 10742891, i32 1176}
!18 = !{i32 500000, i64 6614715, i32 2229}
!19 = !{i32 600000, i64 4208085, i32 3894}
!20 = !{i32 700000, i64 2318291, i32 6730}
!21 = !{i32 800000, i64 1208084, i32 11969}
!22 = !{i32 900000, i64 444413, i32 23829}
!23 = !{i32 950000, i64 174449, i32 39277}
!24 = !{i32 990000, i64 20453, i32 93641}
!25 = !{i32 999000, i64 1534, i32 213507}
!26 = !{i32 999900, i64 120, i32 367707}
!27 = !{i32 999990, i64 18, i32 565769}
!28 = !{i32 999999, i64 4, i32 632473}
