; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -o - %s | FileCheck %s --check-prefix=NOPIC
; RUN: llc -o - %s -relocation-model=pic | FileCheck %s --check-prefix=PIC
; RUN: llc -o - %s -relocation-model=pic -enable-tlsdesc | FileCheck %s --check-prefix=TLSDESC

target triple = "x86_64--linux-gnu"

declare void @effect()
declare nonnull ptr @llvm.threadlocal.address.p0(ptr nonnull)

@foo_local = dso_local thread_local(localexec) global i32 0, align 4

define i32 @func_local_tls(i32 %arg0, i64 %arg1) nounwind {
; NOPIC-LABEL: func_local_tls:
; NOPIC:       # %bb.0: # %entry
; NOPIC-NEXT:    movl %fs:foo_local@TPOFF, %ecx
; NOPIC-NEXT:    testl %edi, %edi
; NOPIC-NEXT:    movl %ecx, %eax
; NOPIC-NEXT:    je .LBB0_1
; NOPIC-NEXT:  # %bb.2: # %if.end
; NOPIC-NEXT:    addl %ecx, %eax
; NOPIC-NEXT:    retq
; NOPIC-NEXT:  .LBB0_1: # %if.then
; NOPIC-NEXT:    pushq %rbx
; NOPIC-NEXT:    subq $16, %rsp
; NOPIC-NEXT:    movq %rsi, %rbx
; NOPIC-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; NOPIC-NEXT:    callq effect@PLT
; NOPIC-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Reload
; NOPIC-NEXT:    movl %fs:foo_local@TPOFF+168(,%rbx,4), %eax
; NOPIC-NEXT:    addq $16, %rsp
; NOPIC-NEXT:    popq %rbx
; NOPIC-NEXT:    addl %ecx, %eax
; NOPIC-NEXT:    retq
;
; PIC-LABEL: func_local_tls:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:    movl %fs:.Lfoo_local$local@TPOFF, %ecx
; PIC-NEXT:    testl %edi, %edi
; PIC-NEXT:    movl %ecx, %eax
; PIC-NEXT:    je .LBB0_1
; PIC-NEXT:  # %bb.2: # %if.end
; PIC-NEXT:    addl %ecx, %eax
; PIC-NEXT:    retq
; PIC-NEXT:  .LBB0_1: # %if.then
; PIC-NEXT:    pushq %r14
; PIC-NEXT:    pushq %rbx
; PIC-NEXT:    pushq %rax
; PIC-NEXT:    movq %fs:0, %rax
; PIC-NEXT:    leaq .Lfoo_local$local@TPOFF(%rax), %rbx
; PIC-NEXT:    movq %rsi, %r14
; PIC-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; PIC-NEXT:    callq effect@PLT
; PIC-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Reload
; PIC-NEXT:    movl 168(%rbx,%r14,4), %eax
; PIC-NEXT:    addq $8, %rsp
; PIC-NEXT:    popq %rbx
; PIC-NEXT:    popq %r14
; PIC-NEXT:    addl %ecx, %eax
; PIC-NEXT:    retq
;
; TLSDESC-LABEL: func_local_tls:
; TLSDESC:       # %bb.0: # %entry
; TLSDESC-NEXT:    movl %fs:.Lfoo_local$local@TPOFF, %ecx
; TLSDESC-NEXT:    testl %edi, %edi
; TLSDESC-NEXT:    movl %ecx, %eax
; TLSDESC-NEXT:    je .LBB0_1
; TLSDESC-NEXT:  # %bb.2: # %if.end
; TLSDESC-NEXT:    addl %ecx, %eax
; TLSDESC-NEXT:    retq
; TLSDESC-NEXT:  .LBB0_1: # %if.then
; TLSDESC-NEXT:    pushq %r14
; TLSDESC-NEXT:    pushq %rbx
; TLSDESC-NEXT:    pushq %rax
; TLSDESC-NEXT:    movq %fs:0, %rax
; TLSDESC-NEXT:    leaq .Lfoo_local$local@TPOFF(%rax), %rbx
; TLSDESC-NEXT:    movq %rsi, %r14
; TLSDESC-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; TLSDESC-NEXT:    callq effect@PLT
; TLSDESC-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Reload
; TLSDESC-NEXT:    movl 168(%rbx,%r14,4), %eax
; TLSDESC-NEXT:    addq $8, %rsp
; TLSDESC-NEXT:    popq %rbx
; TLSDESC-NEXT:    popq %r14
; TLSDESC-NEXT:    addl %ecx, %eax
; TLSDESC-NEXT:    retq
entry:
  %addr = tail call ptr @llvm.threadlocal.address.p0(ptr @foo_local)
  %load0 = load i32, ptr %addr, align 4
  %cond = icmp eq i32 %arg0, 0
  br i1 %cond, label %if.then, label %if.end

if.then:
  tail call void @effect()
  %x = add i64 %arg1, 42
  %addr1 = getelementptr inbounds i32, ptr %addr, i64 %x
  %load1 = load i32, ptr %addr1, align 4
  br label %if.end

if.end:
  %phi = phi i32 [ %load1, %if.then ], [ %load0, %entry ]
  %ret = add i32 %phi, %load0
  ret i32 %ret
}

@foo_nonlocal = thread_local global i32 0, align 4

define i32 @func_nonlocal_tls(i32 %arg0, i64 %arg1) nounwind {
; NOPIC-LABEL: func_nonlocal_tls:
; NOPIC:       # %bb.0: # %entry
; NOPIC-NEXT:    movq foo_nonlocal@GOTTPOFF(%rip), %rdx
; NOPIC-NEXT:    movl %fs:(%rdx), %ecx
; NOPIC-NEXT:    testl %edi, %edi
; NOPIC-NEXT:    movl %ecx, %eax
; NOPIC-NEXT:    je .LBB1_1
; NOPIC-NEXT:  # %bb.2: # %if.end
; NOPIC-NEXT:    addl %ecx, %eax
; NOPIC-NEXT:    retq
; NOPIC-NEXT:  .LBB1_1: # %if.then
; NOPIC-NEXT:    pushq %r14
; NOPIC-NEXT:    pushq %rbx
; NOPIC-NEXT:    pushq %rax
; NOPIC-NEXT:    movq %rsi, %rbx
; NOPIC-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; NOPIC-NEXT:    movq %rdx, %r14
; NOPIC-NEXT:    callq effect@PLT
; NOPIC-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Reload
; NOPIC-NEXT:    movl %fs:168(%r14,%rbx,4), %eax
; NOPIC-NEXT:    addq $8, %rsp
; NOPIC-NEXT:    popq %rbx
; NOPIC-NEXT:    popq %r14
; NOPIC-NEXT:    addl %ecx, %eax
; NOPIC-NEXT:    retq
;
; PIC-LABEL: func_nonlocal_tls:
; PIC:       # %bb.0: # %entry
; PIC-NEXT:    pushq %rbp
; PIC-NEXT:    pushq %r14
; PIC-NEXT:    pushq %rbx
; PIC-NEXT:    movq %rsi, %rbx
; PIC-NEXT:    movl %edi, %ebp
; PIC-NEXT:    data16
; PIC-NEXT:    leaq foo_nonlocal@TLSGD(%rip), %rdi
; PIC-NEXT:    data16
; PIC-NEXT:    data16
; PIC-NEXT:    rex64
; PIC-NEXT:    callq __tls_get_addr@PLT
; PIC-NEXT:    movq %rax, %rcx
; PIC-NEXT:    movl (%rax), %edx
; PIC-NEXT:    testl %ebp, %ebp
; PIC-NEXT:    movl %edx, %eax
; PIC-NEXT:    jne .LBB1_2
; PIC-NEXT:  # %bb.1: # %if.then
; PIC-NEXT:    movq %rcx, %r14
; PIC-NEXT:    movl %edx, %ebp
; PIC-NEXT:    callq effect@PLT
; PIC-NEXT:    movl %ebp, %edx
; PIC-NEXT:    movl 168(%r14,%rbx,4), %eax
; PIC-NEXT:  .LBB1_2: # %if.end
; PIC-NEXT:    addl %edx, %eax
; PIC-NEXT:    popq %rbx
; PIC-NEXT:    popq %r14
; PIC-NEXT:    popq %rbp
; PIC-NEXT:    retq
;
; TLSDESC-LABEL: func_nonlocal_tls:
; TLSDESC:       # %bb.0: # %entry
; TLSDESC-NEXT:    pushq %r14
; TLSDESC-NEXT:    pushq %rbx
; TLSDESC-NEXT:    pushq %rax
; TLSDESC-NEXT:    leaq foo_nonlocal@tlsdesc(%rip), %rax
; TLSDESC-NEXT:    callq *foo_nonlocal@tlscall(%rax)
; TLSDESC-NEXT:    movl %fs:(%rax), %edx
; TLSDESC-NEXT:    testl %edi, %edi
; TLSDESC-NEXT:    movl %edx, %ecx
; TLSDESC-NEXT:    jne .LBB1_2
; TLSDESC-NEXT:  # %bb.1: # %if.then
; TLSDESC-NEXT:    addq %fs:0, %rax
; TLSDESC-NEXT:    movq %rsi, %rbx
; TLSDESC-NEXT:    movq %rax, %r14
; TLSDESC-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; TLSDESC-NEXT:    callq effect@PLT
; TLSDESC-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edx # 4-byte Reload
; TLSDESC-NEXT:    movl 168(%r14,%rbx,4), %ecx
; TLSDESC-NEXT:  .LBB1_2: # %if.end
; TLSDESC-NEXT:    addl %edx, %ecx
; TLSDESC-NEXT:    movl %ecx, %eax
; TLSDESC-NEXT:    addq $8, %rsp
; TLSDESC-NEXT:    popq %rbx
; TLSDESC-NEXT:    popq %r14
; TLSDESC-NEXT:    retq
entry:
  %addr = tail call ptr @llvm.threadlocal.address.p0(ptr @foo_nonlocal)
  %load0 = load i32, ptr %addr, align 4
  %cond = icmp eq i32 %arg0, 0
  br i1 %cond, label %if.then, label %if.end

if.then:
  tail call void @effect()
  %x = add i64 %arg1, 42
  %addr1 = getelementptr inbounds i32, ptr %addr, i64 %x
  %load1 = load i32, ptr %addr1, align 4
  br label %if.end

if.end:
  %phi = phi i32 [ %load1, %if.then ], [ %load0, %entry ]
  %ret = add i32 %phi, %load0
  ret i32 %ret
}
