; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64    | FileCheck %s --check-prefixes=SSE
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v2 | FileCheck %s --check-prefixes=SSE
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=sandybridge | FileCheck %s --check-prefixes=AVX1OR2,AVX1
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v3 | FileCheck %s --check-prefixes=AVX1OR2,AVX2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v4 | FileCheck %s --check-prefixes=AVX512

define i4 @concat_fcmp_v4f64_v2f64(<2 x double> %a0, <2 x double> %a1) {
; SSE-LABEL: concat_fcmp_v4f64_v2f64:
; SSE:       # %bb.0:
; SSE-NEXT:    xorpd %xmm2, %xmm2
; SSE-NEXT:    xorpd %xmm3, %xmm3
; SSE-NEXT:    cmpltpd %xmm0, %xmm3
; SSE-NEXT:    cmpltpd %xmm1, %xmm2
; SSE-NEXT:    shufps {{.*#+}} xmm3 = xmm3[0,2],xmm2[0,2]
; SSE-NEXT:    movmskps %xmm3, %eax
; SSE-NEXT:    # kill: def $al killed $al killed $eax
; SSE-NEXT:    retq
;
; AVX1OR2-LABEL: concat_fcmp_v4f64_v2f64:
; AVX1OR2:       # %bb.0:
; AVX1OR2-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX1OR2-NEXT:    vcmpltpd %xmm0, %xmm2, %xmm0
; AVX1OR2-NEXT:    vcmpltpd %xmm1, %xmm2, %xmm1
; AVX1OR2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[0,2],xmm1[0,2]
; AVX1OR2-NEXT:    vmovmskps %xmm0, %eax
; AVX1OR2-NEXT:    # kill: def $al killed $al killed $eax
; AVX1OR2-NEXT:    retq
;
; AVX512-LABEL: concat_fcmp_v4f64_v2f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vcmpltpd %xmm0, %xmm2, %k0
; AVX512-NEXT:    vcmpltpd %xmm1, %xmm2, %k1
; AVX512-NEXT:    kshiftlb $2, %k1, %k1
; AVX512-NEXT:    korw %k1, %k0, %k0
; AVX512-NEXT:    kmovd %k0, %eax
; AVX512-NEXT:    # kill: def $al killed $al killed $eax
; AVX512-NEXT:    retq
  %v0 = fcmp ogt <2 x double> %a0, zeroinitializer
  %v1 = fcmp ogt <2 x double> %a1, zeroinitializer
  %v = shufflevector <2 x i1> %v0, <2 x i1> %v1, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %r = bitcast <4 x i1> %v to i4
  ret i4 %r
}

define i8 @concat_fcmp_v8f32_v4f32(<4 x float> %a0, <4 x float> %a1) {
; SSE-LABEL: concat_fcmp_v8f32_v4f32:
; SSE:       # %bb.0:
; SSE-NEXT:    xorps %xmm2, %xmm2
; SSE-NEXT:    cmpeqps %xmm2, %xmm0
; SSE-NEXT:    cmpeqps %xmm2, %xmm1
; SSE-NEXT:    packssdw %xmm1, %xmm0
; SSE-NEXT:    packsswb %xmm0, %xmm0
; SSE-NEXT:    pmovmskb %xmm0, %eax
; SSE-NEXT:    # kill: def $al killed $al killed $eax
; SSE-NEXT:    retq
;
; AVX1OR2-LABEL: concat_fcmp_v8f32_v4f32:
; AVX1OR2:       # %bb.0:
; AVX1OR2-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX1OR2-NEXT:    vcmpeqps %xmm2, %xmm0, %xmm0
; AVX1OR2-NEXT:    vcmpeqps %xmm2, %xmm1, %xmm1
; AVX1OR2-NEXT:    vpackssdw %xmm1, %xmm0, %xmm0
; AVX1OR2-NEXT:    vpacksswb %xmm0, %xmm0, %xmm0
; AVX1OR2-NEXT:    vpmovmskb %xmm0, %eax
; AVX1OR2-NEXT:    # kill: def $al killed $al killed $eax
; AVX1OR2-NEXT:    retq
;
; AVX512-LABEL: concat_fcmp_v8f32_v4f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    # kill: def $xmm0 killed $xmm0 def $ymm0
; AVX512-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX512-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vcmpeqps %ymm1, %ymm0, %k0
; AVX512-NEXT:    kmovd %k0, %eax
; AVX512-NEXT:    # kill: def $al killed $al killed $eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %v0 = fcmp oeq <4 x float> %a0, zeroinitializer
  %v1 = fcmp oeq <4 x float> %a1, zeroinitializer
  %v = shufflevector <4 x i1> %v0, <4 x i1> %v1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %r = bitcast <8 x i1> %v to i8
  ret i8 %r
}

define i8 @concat_fcmp_v8f64_v2f64(<2 x double> %a0, <2 x double> %a1, <2 x double> %a2, <2 x double> %a3) {
; SSE-LABEL: concat_fcmp_v8f64_v2f64:
; SSE:       # %bb.0:
; SSE-NEXT:    xorpd %xmm4, %xmm4
; SSE-NEXT:    cmpltpd %xmm4, %xmm0
; SSE-NEXT:    cmpltpd %xmm4, %xmm1
; SSE-NEXT:    packssdw %xmm1, %xmm0
; SSE-NEXT:    cmpltpd %xmm4, %xmm2
; SSE-NEXT:    cmpltpd %xmm4, %xmm3
; SSE-NEXT:    packssdw %xmm3, %xmm2
; SSE-NEXT:    packssdw %xmm0, %xmm0
; SSE-NEXT:    packssdw %xmm2, %xmm2
; SSE-NEXT:    packsswb %xmm2, %xmm0
; SSE-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[0,3,2,3]
; SSE-NEXT:    pmovmskb %xmm0, %eax
; SSE-NEXT:    # kill: def $al killed $al killed $eax
; SSE-NEXT:    retq
;
; AVX1OR2-LABEL: concat_fcmp_v8f64_v2f64:
; AVX1OR2:       # %bb.0:
; AVX1OR2-NEXT:    vxorpd %xmm4, %xmm4, %xmm4
; AVX1OR2-NEXT:    vcmpltpd %xmm4, %xmm0, %xmm0
; AVX1OR2-NEXT:    vcmpltpd %xmm4, %xmm1, %xmm1
; AVX1OR2-NEXT:    vpackssdw %xmm1, %xmm0, %xmm0
; AVX1OR2-NEXT:    vcmpltpd %xmm4, %xmm2, %xmm1
; AVX1OR2-NEXT:    vcmpltpd %xmm4, %xmm3, %xmm2
; AVX1OR2-NEXT:    vpackssdw %xmm2, %xmm1, %xmm1
; AVX1OR2-NEXT:    vpackssdw %xmm1, %xmm1, %xmm1
; AVX1OR2-NEXT:    vpackssdw %xmm0, %xmm0, %xmm0
; AVX1OR2-NEXT:    vpacksswb %xmm1, %xmm0, %xmm0
; AVX1OR2-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[0,3,0,3]
; AVX1OR2-NEXT:    vpmovmskb %xmm0, %eax
; AVX1OR2-NEXT:    # kill: def $al killed $al killed $eax
; AVX1OR2-NEXT:    retq
;
; AVX512-LABEL: concat_fcmp_v8f64_v2f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    # kill: def $xmm2 killed $xmm2 def $ymm2
; AVX512-NEXT:    # kill: def $xmm0 killed $xmm0 def $ymm0
; AVX512-NEXT:    vinsertf128 $1, %xmm3, %ymm2, %ymm2
; AVX512-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX512-NEXT:    vinsertf64x4 $1, %ymm2, %zmm0, %zmm0
; AVX512-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vcmpltpd %zmm1, %zmm0, %k0
; AVX512-NEXT:    kmovd %k0, %eax
; AVX512-NEXT:    # kill: def $al killed $al killed $eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %v0 = fcmp olt <2 x double> %a0, zeroinitializer
  %v1 = fcmp olt <2 x double> %a1, zeroinitializer
  %v2 = fcmp olt <2 x double> %a2, zeroinitializer
  %v3 = fcmp olt <2 x double> %a3, zeroinitializer
  %v01 = shufflevector <2 x i1> %v0, <2 x i1> %v1, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %v23 = shufflevector <2 x i1> %v2, <2 x i1> %v3, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %v = shufflevector <4 x i1> %v01, <4 x i1> %v23, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %r = bitcast <8 x i1> %v to i8
  ret i8 %r
}

define i16 @concat_fcmp_v16f32_v4f32(<4 x float> %a0, <4 x float> %a1, <4 x float> %a2, <4 x float> %a3) {
; SSE-LABEL: concat_fcmp_v16f32_v4f32:
; SSE:       # %bb.0:
; SSE-NEXT:    xorps %xmm4, %xmm4
; SSE-NEXT:    xorps %xmm5, %xmm5
; SSE-NEXT:    cmpleps %xmm0, %xmm5
; SSE-NEXT:    xorps %xmm0, %xmm0
; SSE-NEXT:    cmpleps %xmm1, %xmm0
; SSE-NEXT:    packssdw %xmm0, %xmm5
; SSE-NEXT:    xorps %xmm0, %xmm0
; SSE-NEXT:    cmpleps %xmm2, %xmm0
; SSE-NEXT:    cmpleps %xmm3, %xmm4
; SSE-NEXT:    packssdw %xmm4, %xmm0
; SSE-NEXT:    packsswb %xmm0, %xmm5
; SSE-NEXT:    pmovmskb %xmm5, %eax
; SSE-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE-NEXT:    retq
;
; AVX1OR2-LABEL: concat_fcmp_v16f32_v4f32:
; AVX1OR2:       # %bb.0:
; AVX1OR2-NEXT:    vxorps %xmm4, %xmm4, %xmm4
; AVX1OR2-NEXT:    vcmpleps %xmm0, %xmm4, %xmm0
; AVX1OR2-NEXT:    vcmpleps %xmm1, %xmm4, %xmm1
; AVX1OR2-NEXT:    vpackssdw %xmm1, %xmm0, %xmm0
; AVX1OR2-NEXT:    vcmpleps %xmm2, %xmm4, %xmm1
; AVX1OR2-NEXT:    vcmpleps %xmm3, %xmm4, %xmm2
; AVX1OR2-NEXT:    vpackssdw %xmm2, %xmm1, %xmm1
; AVX1OR2-NEXT:    vpacksswb %xmm1, %xmm0, %xmm0
; AVX1OR2-NEXT:    vpmovmskb %xmm0, %eax
; AVX1OR2-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX1OR2-NEXT:    retq
;
; AVX512-LABEL: concat_fcmp_v16f32_v4f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    # kill: def $xmm2 killed $xmm2 def $ymm2
; AVX512-NEXT:    # kill: def $xmm0 killed $xmm0 def $ymm0
; AVX512-NEXT:    vinsertf128 $1, %xmm3, %ymm2, %ymm2
; AVX512-NEXT:    vinsertf128 $1, %xmm1, %ymm0, %ymm0
; AVX512-NEXT:    vinsertf64x4 $1, %ymm2, %zmm0, %zmm0
; AVX512-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vcmpleps %zmm0, %zmm1, %k0
; AVX512-NEXT:    kmovd %k0, %eax
; AVX512-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %v0 = fcmp oge <4 x float> %a0, zeroinitializer
  %v1 = fcmp oge <4 x float> %a1, zeroinitializer
  %v2 = fcmp oge <4 x float> %a2, zeroinitializer
  %v3 = fcmp oge <4 x float> %a3, zeroinitializer
  %v01 = shufflevector <4 x i1> %v0, <4 x i1> %v1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %v23 = shufflevector <4 x i1> %v2, <4 x i1> %v3, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %v = shufflevector <8 x i1> %v01, <8 x i1> %v23, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %r = bitcast <16 x i1> %v to i16
  ret i16 %r
}

define i8 @concat_fcmp_v8f64_v4f64(<4 x double> %a0, <4 x double> %a1) {
; SSE-LABEL: concat_fcmp_v8f64_v4f64:
; SSE:       # %bb.0:
; SSE-NEXT:    xorpd %xmm4, %xmm4
; SSE-NEXT:    movapd %xmm1, %xmm5
; SSE-NEXT:    cmpneqpd %xmm4, %xmm5
; SSE-NEXT:    cmpordpd %xmm4, %xmm1
; SSE-NEXT:    andpd %xmm5, %xmm1
; SSE-NEXT:    pshufd {{.*#+}} xmm1 = xmm1[0,2,2,3]
; SSE-NEXT:    movapd %xmm0, %xmm5
; SSE-NEXT:    cmpneqpd %xmm4, %xmm5
; SSE-NEXT:    cmpordpd %xmm4, %xmm0
; SSE-NEXT:    andpd %xmm5, %xmm0
; SSE-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[0,2,2,3]
; SSE-NEXT:    punpcklwd {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[1],xmm1[1],xmm0[2],xmm1[2],xmm0[3],xmm1[3]
; SSE-NEXT:    movapd %xmm3, %xmm1
; SSE-NEXT:    cmpneqpd %xmm4, %xmm1
; SSE-NEXT:    cmpordpd %xmm4, %xmm3
; SSE-NEXT:    andpd %xmm1, %xmm3
; SSE-NEXT:    movapd %xmm2, %xmm1
; SSE-NEXT:    cmpneqpd %xmm4, %xmm1
; SSE-NEXT:    cmpordpd %xmm4, %xmm2
; SSE-NEXT:    andpd %xmm1, %xmm2
; SSE-NEXT:    packssdw %xmm3, %xmm2
; SSE-NEXT:    packssdw %xmm2, %xmm2
; SSE-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[0,2,2,3]
; SSE-NEXT:    pshuflw {{.*#+}} xmm0 = xmm0[0,2,1,3,4,5,6,7]
; SSE-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm2[0]
; SSE-NEXT:    packsswb %xmm0, %xmm0
; SSE-NEXT:    pmovmskb %xmm0, %eax
; SSE-NEXT:    # kill: def $al killed $al killed $eax
; SSE-NEXT:    retq
;
; AVX1-LABEL: concat_fcmp_v8f64_v4f64:
; AVX1:       # %bb.0:
; AVX1-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX1-NEXT:    vcmpneq_oqpd %ymm2, %ymm0, %ymm0
; AVX1-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[0,2],xmm3[0,2]
; AVX1-NEXT:    vcmpneq_oqpd %ymm2, %ymm1, %ymm1
; AVX1-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1-NEXT:    vshufps {{.*#+}} xmm1 = xmm1[0,2],xmm2[0,2]
; AVX1-NEXT:    vpackssdw %xmm1, %xmm0, %xmm0
; AVX1-NEXT:    vpsrlw $8, %xmm0, %xmm0
; AVX1-NEXT:    vpackuswb %xmm0, %xmm0, %xmm0
; AVX1-NEXT:    vpmovmskb %xmm0, %eax
; AVX1-NEXT:    # kill: def $al killed $al killed $eax
; AVX1-NEXT:    vzeroupper
; AVX1-NEXT:    retq
;
; AVX2-LABEL: concat_fcmp_v8f64_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vcmpneq_oqpd %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vmovapd {{.*#+}} xmm3 = [0,2,4,6]
; AVX2-NEXT:    vpermps %ymm0, %ymm3, %ymm0
; AVX2-NEXT:    vcmpneq_oqpd %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vpermps %ymm1, %ymm3, %ymm1
; AVX2-NEXT:    vpackssdw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vpacksswb %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vpmovmskb %xmm0, %eax
; AVX2-NEXT:    # kill: def $al killed $al killed $eax
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: concat_fcmp_v8f64_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    # kill: def $ymm0 killed $ymm0 def $zmm0
; AVX512-NEXT:    vinsertf64x4 $1, %ymm1, %zmm0, %zmm0
; AVX512-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vcmpneq_oqpd %zmm1, %zmm0, %k0
; AVX512-NEXT:    kmovd %k0, %eax
; AVX512-NEXT:    # kill: def $al killed $al killed $eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %v0 = fcmp one <4 x double> %a0, zeroinitializer
  %v1 = fcmp one <4 x double> %a1, zeroinitializer
  %v = shufflevector <4 x i1> %v0, <4 x i1> %v1, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7>
  %r = bitcast <8 x i1> %v to i8
  ret i8 %r
}

define i16 @concat_fcmp_v16f32_v8f32(<8 x float> %a0, <8 x float> %a1) {
; SSE-LABEL: concat_fcmp_v16f32_v8f32:
; SSE:       # %bb.0:
; SSE-NEXT:    xorps %xmm4, %xmm4
; SSE-NEXT:    cmpleps %xmm4, %xmm1
; SSE-NEXT:    cmpleps %xmm4, %xmm0
; SSE-NEXT:    packssdw %xmm1, %xmm0
; SSE-NEXT:    cmpleps %xmm4, %xmm3
; SSE-NEXT:    cmpleps %xmm4, %xmm2
; SSE-NEXT:    packssdw %xmm3, %xmm2
; SSE-NEXT:    packsswb %xmm2, %xmm0
; SSE-NEXT:    pmovmskb %xmm0, %eax
; SSE-NEXT:    # kill: def $ax killed $ax killed $eax
; SSE-NEXT:    retq
;
; AVX1OR2-LABEL: concat_fcmp_v16f32_v8f32:
; AVX1OR2:       # %bb.0:
; AVX1OR2-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX1OR2-NEXT:    vcmpleps %ymm2, %ymm0, %ymm0
; AVX1OR2-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX1OR2-NEXT:    vpackssdw %xmm3, %xmm0, %xmm0
; AVX1OR2-NEXT:    vcmpleps %ymm2, %ymm1, %ymm1
; AVX1OR2-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX1OR2-NEXT:    vpackssdw %xmm2, %xmm1, %xmm1
; AVX1OR2-NEXT:    vpacksswb %xmm1, %xmm0, %xmm0
; AVX1OR2-NEXT:    vpmovmskb %xmm0, %eax
; AVX1OR2-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX1OR2-NEXT:    vzeroupper
; AVX1OR2-NEXT:    retq
;
; AVX512-LABEL: concat_fcmp_v16f32_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    # kill: def $ymm0 killed $ymm0 def $zmm0
; AVX512-NEXT:    vinsertf64x4 $1, %ymm1, %zmm0, %zmm0
; AVX512-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vcmpleps %zmm1, %zmm0, %k0
; AVX512-NEXT:    kmovd %k0, %eax
; AVX512-NEXT:    # kill: def $ax killed $ax killed $eax
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %v0 = fcmp ole <8 x float> %a0, zeroinitializer
  %v1 = fcmp ole <8 x float> %a1, zeroinitializer
  %v = shufflevector <8 x i1> %v0, <8 x i1> %v1, <16 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %r = bitcast <16 x i1> %v to i16
  ret i16 %r
}
