; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mattr=+sse2    | FileCheck %s --check-prefixes=CHECK,SCALAR
; RUN: llc < %s -mtriple=x86_64-- -mattr=+sse2,+pclmul | FileCheck %s --check-prefixes=CHECK,SSE-PCLMUL
; RUN: llc < %s -mtriple=x86_64-- -mattr=+sse4.2,+pclmul | FileCheck %s --check-prefixes=CHECK,SSE-PCLMUL
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx2,+pclmul | FileCheck %s --check-prefixes=CHECK,AVX
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx2,+vpclmulqdq  | FileCheck %s --check-prefixes=CHECK,AVX
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx512vl,+vpclmulqdq | FileCheck %s --check-prefixes=CHECK,AVX

; Test with constant 0 - should optimize to just returning 0
define i32 @clmul_i32_zero(i32 %a) {
; CHECK-LABEL: clmul_i32_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.clmul.i32(i32 %a, i32 0)
  ret i32 %res
}

; Test with constant 1 - should optimize to just returning %a
define i32 @clmul_i32_one(i32 %a) {
; CHECK-LABEL: clmul_i32_one:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.clmul.i32(i32 %a, i32 1)
  ret i32 %res
}

; Test with power of 2 - should become a shift
define i32 @clmul_i32_pow2(i32 %a) {
; CHECK-LABEL: clmul_i32_pow2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    shll $4, %eax
; CHECK-NEXT:    retq
  %res = call i32 @llvm.clmul.i32(i32 %a, i32 16)  ; 0x10 = 1 << 4
  ret i32 %res
}

; Chained i32 clmul should feed the intermediate result straight into the next
; multiply in vector form instead of round-tripping it through a scalar.
define i32 @clmul_i32_chain(i32 %m) nounwind {
; SCALAR-LABEL: clmul_i32_chain:
; SCALAR:       # %bb.0:
; SCALAR-NEXT:    pushq %rbp
; SCALAR-NEXT:    pushq %r15
; SCALAR-NEXT:    pushq %r14
; SCALAR-NEXT:    pushq %r13
; SCALAR-NEXT:    pushq %r12
; SCALAR-NEXT:    pushq %rbx
; SCALAR-NEXT:    movl %edi, %esi
; SCALAR-NEXT:    leal (%rsi,%rsi), %edx
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $2, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %edx
; SCALAR-NEXT:    movl %edi, %ecx
; SCALAR-NEXT:    andl $1, %ecx
; SCALAR-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    cmovel %ecx, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %eax, %edx
; SCALAR-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    leal (,%rsi,4), %ecx
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $4, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %ecx
; SCALAR-NEXT:    xorl %edx, %ecx
; SCALAR-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    leal (,%rsi,8), %edx
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $8, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %edx
; SCALAR-NEXT:    xorl %ecx, %edx
; SCALAR-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %edi, %ecx
; SCALAR-NEXT:    shll $4, %ecx
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $16, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %ecx
; SCALAR-NEXT:    xorl %edx, %ecx
; SCALAR-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %edi, %edx
; SCALAR-NEXT:    shll $5, %edx
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $32, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %edx
; SCALAR-NEXT:    xorl %ecx, %edx
; SCALAR-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %edi, %ecx
; SCALAR-NEXT:    shll $6, %ecx
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $64, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %ecx
; SCALAR-NEXT:    xorl %edx, %ecx
; SCALAR-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %edi, %edx
; SCALAR-NEXT:    shll $7, %edx
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $128, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %edx
; SCALAR-NEXT:    xorl %ecx, %edx
; SCALAR-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %edi, %r13d
; SCALAR-NEXT:    shll $8, %r13d
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $256, %eax # imm = 0x100
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %r13d
; SCALAR-NEXT:    xorl %edx, %r13d
; SCALAR-NEXT:    movl %edi, %r12d
; SCALAR-NEXT:    shll $9, %r12d
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $512, %eax # imm = 0x200
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %r12d
; SCALAR-NEXT:    xorl %r13d, %r12d
; SCALAR-NEXT:    movl %edi, %ebp
; SCALAR-NEXT:    shll $10, %ebp
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $1024, %eax # imm = 0x400
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %ebp
; SCALAR-NEXT:    xorl %r12d, %ebp
; SCALAR-NEXT:    movl %edi, %r15d
; SCALAR-NEXT:    shll $11, %r15d
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $2048, %eax # imm = 0x800
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %r15d
; SCALAR-NEXT:    xorl %ebp, %r15d
; SCALAR-NEXT:    movl %edi, %r11d
; SCALAR-NEXT:    shll $12, %r11d
; SCALAR-NEXT:    movl %edi, %eax
; SCALAR-NEXT:    andl $4096, %eax # imm = 0x1000
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    cmovel %eax, %r11d
; SCALAR-NEXT:    xorl %r15d, %r11d
; SCALAR-NEXT:    movl %edi, %r10d
; SCALAR-NEXT:    shll $13, %r10d
; SCALAR-NEXT:    movl %edi, %r14d
; SCALAR-NEXT:    andl $8192, %r14d # imm = 0x2000
; SCALAR-NEXT:    cmovel %r14d, %r10d
; SCALAR-NEXT:    xorl %r11d, %r10d
; SCALAR-NEXT:    movl %edi, %edx
; SCALAR-NEXT:    shll $14, %edx
; SCALAR-NEXT:    movl %edi, %ebx
; SCALAR-NEXT:    andl $16384, %ebx # imm = 0x4000
; SCALAR-NEXT:    cmovel %ebx, %edx
; SCALAR-NEXT:    xorl %r10d, %edx
; SCALAR-NEXT:    movl %edi, %r8d
; SCALAR-NEXT:    shll $15, %r8d
; SCALAR-NEXT:    andl $32768, %edi # imm = 0x8000
; SCALAR-NEXT:    cmovel %edi, %r8d
; SCALAR-NEXT:    xorl %edx, %r8d
; SCALAR-NEXT:    movl %esi, %ecx
; SCALAR-NEXT:    shll $16, %ecx
; SCALAR-NEXT:    movl %r8d, %r9d
; SCALAR-NEXT:    shll $16, %r9d
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    andl $65536, %eax # imm = 0x10000
; SCALAR-NEXT:    cmovel %eax, %ecx
; SCALAR-NEXT:    cmovnel %r9d, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %r8d, %ecx
; SCALAR-NEXT:    movl %ecx, %eax
; SCALAR-NEXT:    shll $15, %eax
; SCALAR-NEXT:    testl %edi, %edi
; SCALAR-NEXT:    cmovel %edi, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    shll $17, %eax
; SCALAR-NEXT:    shll $17, %edx
; SCALAR-NEXT:    movl %esi, %edi
; SCALAR-NEXT:    andl $131072, %edi # imm = 0x20000
; SCALAR-NEXT:    cmovel %edi, %eax
; SCALAR-NEXT:    cmovnel %edx, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %ecx, %eax
; SCALAR-NEXT:    movl %eax, %ecx
; SCALAR-NEXT:    shll $14, %ecx
; SCALAR-NEXT:    testl %ebx, %ebx
; SCALAR-NEXT:    cmovel %ebx, %ecx
; SCALAR-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %ecx
; SCALAR-NEXT:    shll $18, %ecx
; SCALAR-NEXT:    shll $18, %r10d
; SCALAR-NEXT:    movl %esi, %edx
; SCALAR-NEXT:    andl $262144, %edx # imm = 0x40000
; SCALAR-NEXT:    cmovel %edx, %ecx
; SCALAR-NEXT:    cmovnel %r10d, %edx
; SCALAR-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %eax, %ecx
; SCALAR-NEXT:    movl %ecx, %eax
; SCALAR-NEXT:    shll $13, %eax
; SCALAR-NEXT:    testl %r14d, %r14d
; SCALAR-NEXT:    cmovel %r14d, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    shll $19, %eax
; SCALAR-NEXT:    shll $19, %r11d
; SCALAR-NEXT:    movl %esi, %edx
; SCALAR-NEXT:    andl $524288, %edx # imm = 0x80000
; SCALAR-NEXT:    cmovel %edx, %eax
; SCALAR-NEXT:    cmovnel %r11d, %edx
; SCALAR-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %ecx, %eax
; SCALAR-NEXT:    movl %eax, %ecx
; SCALAR-NEXT:    shll $12, %ecx
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edx # 4-byte Reload
; SCALAR-NEXT:    testl %edx, %edx
; SCALAR-NEXT:    cmovel %edx, %ecx
; SCALAR-NEXT:    movl %esi, %edx
; SCALAR-NEXT:    shll $20, %edx
; SCALAR-NEXT:    shll $20, %r15d
; SCALAR-NEXT:    movl %esi, %edi
; SCALAR-NEXT:    andl $1048576, %edi # imm = 0x100000
; SCALAR-NEXT:    cmovel %edi, %edx
; SCALAR-NEXT:    cmovnel %r15d, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %eax, %edx
; SCALAR-NEXT:    movl %edx, %eax
; SCALAR-NEXT:    shll $11, %eax
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    testl %edi, %edi
; SCALAR-NEXT:    cmovel %edi, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    shll $21, %eax
; SCALAR-NEXT:    shll $21, %ebp
; SCALAR-NEXT:    movl %esi, %edi
; SCALAR-NEXT:    andl $2097152, %edi # imm = 0x200000
; SCALAR-NEXT:    cmovel %edi, %eax
; SCALAR-NEXT:    cmovnel %ebp, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %edx, %eax
; SCALAR-NEXT:    movl %eax, %edx
; SCALAR-NEXT:    shll $10, %edx
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    testl %edi, %edi
; SCALAR-NEXT:    cmovel %edi, %edx
; SCALAR-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %edx
; SCALAR-NEXT:    shll $22, %edx
; SCALAR-NEXT:    shll $22, %r12d
; SCALAR-NEXT:    movl %esi, %edi
; SCALAR-NEXT:    andl $4194304, %edi # imm = 0x400000
; SCALAR-NEXT:    cmovel %edi, %edx
; SCALAR-NEXT:    cmovnel %r12d, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %eax, %edx
; SCALAR-NEXT:    movl %edx, %eax
; SCALAR-NEXT:    shll $9, %eax
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    testl %edi, %edi
; SCALAR-NEXT:    cmovel %edi, %eax
; SCALAR-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    shll $23, %eax
; SCALAR-NEXT:    shll $23, %r13d
; SCALAR-NEXT:    movl %esi, %edi
; SCALAR-NEXT:    andl $8388608, %edi # imm = 0x800000
; SCALAR-NEXT:    cmovel %edi, %eax
; SCALAR-NEXT:    cmovnel %r13d, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %edx, %eax
; SCALAR-NEXT:    movl %eax, %edi
; SCALAR-NEXT:    shll $8, %edi
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edx # 4-byte Reload
; SCALAR-NEXT:    testl %edx, %edx
; SCALAR-NEXT:    cmovel %edx, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %edx
; SCALAR-NEXT:    shll $24, %edx
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    shll $24, %edi
; SCALAR-NEXT:    movl %esi, %r8d
; SCALAR-NEXT:    andl $16777216, %r8d # imm = 0x1000000
; SCALAR-NEXT:    cmovel %r8d, %edx
; SCALAR-NEXT:    cmovnel %edi, %r8d
; SCALAR-NEXT:    movl %r8d, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %eax, %edx
; SCALAR-NEXT:    movl %edx, %edi
; SCALAR-NEXT:    shll $7, %edi
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; SCALAR-NEXT:    testl %eax, %eax
; SCALAR-NEXT:    cmovel %eax, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    shll $25, %eax
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    shll $25, %edi
; SCALAR-NEXT:    movl %esi, %r8d
; SCALAR-NEXT:    andl $33554432, %r8d # imm = 0x2000000
; SCALAR-NEXT:    cmovel %r8d, %eax
; SCALAR-NEXT:    cmovnel %edi, %r8d
; SCALAR-NEXT:    movl %r8d, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %edx, %eax
; SCALAR-NEXT:    movl %eax, %edi
; SCALAR-NEXT:    shll $6, %edi
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edx # 4-byte Reload
; SCALAR-NEXT:    testl %edx, %edx
; SCALAR-NEXT:    cmovel %edx, %edi
; SCALAR-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %edx
; SCALAR-NEXT:    shll $26, %edx
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    shll $26, %edi
; SCALAR-NEXT:    movl %esi, %r8d
; SCALAR-NEXT:    andl $67108864, %r8d # imm = 0x4000000
; SCALAR-NEXT:    cmovel %r8d, %edx
; SCALAR-NEXT:    cmovnel %edi, %r8d
; SCALAR-NEXT:    movl %r8d, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    xorl %eax, %edx
; SCALAR-NEXT:    movl %edx, %r8d
; SCALAR-NEXT:    shll $5, %r8d
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; SCALAR-NEXT:    testl %eax, %eax
; SCALAR-NEXT:    cmovel %eax, %r8d
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    shll $27, %eax
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    shll $27, %edi
; SCALAR-NEXT:    movl %esi, %r13d
; SCALAR-NEXT:    andl $134217728, %r13d # imm = 0x8000000
; SCALAR-NEXT:    cmovel %r13d, %eax
; SCALAR-NEXT:    cmovnel %edi, %r13d
; SCALAR-NEXT:    xorl %edx, %eax
; SCALAR-NEXT:    movl %eax, %ebx
; SCALAR-NEXT:    shll $4, %ebx
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edx # 4-byte Reload
; SCALAR-NEXT:    testl %edx, %edx
; SCALAR-NEXT:    cmovel %edx, %ebx
; SCALAR-NEXT:    movl %esi, %edx
; SCALAR-NEXT:    shll $28, %edx
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    shll $28, %edi
; SCALAR-NEXT:    movl %esi, %r14d
; SCALAR-NEXT:    andl $268435456, %r14d # imm = 0x10000000
; SCALAR-NEXT:    cmovel %r14d, %edx
; SCALAR-NEXT:    cmovnel %edi, %r14d
; SCALAR-NEXT:    xorl %eax, %edx
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; SCALAR-NEXT:    testl %eax, %eax
; SCALAR-NEXT:    leal (,%rdx,8), %r15d
; SCALAR-NEXT:    cmovel %eax, %r15d
; SCALAR-NEXT:    movl %esi, %eax
; SCALAR-NEXT:    shll $29, %eax
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    shll $29, %edi
; SCALAR-NEXT:    movl %esi, %ebp
; SCALAR-NEXT:    andl $536870912, %ebp # imm = 0x20000000
; SCALAR-NEXT:    cmovel %ebp, %eax
; SCALAR-NEXT:    cmovnel %edi, %ebp
; SCALAR-NEXT:    xorl %edx, %eax
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %edi # 4-byte Reload
; SCALAR-NEXT:    testl %edi, %edi
; SCALAR-NEXT:    leal (,%rax,4), %edx
; SCALAR-NEXT:    cmovel %edi, %edx
; SCALAR-NEXT:    movl %esi, %edi
; SCALAR-NEXT:    shll $30, %edi
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %r10d # 4-byte Reload
; SCALAR-NEXT:    shll $30, %r10d
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %r9d # 4-byte Reload
; SCALAR-NEXT:    shll $31, %r9d
; SCALAR-NEXT:    movl %esi, %r12d
; SCALAR-NEXT:    andl $-2147483648, %r12d # imm = 0x80000000
; SCALAR-NEXT:    cmovel %r12d, %r9d
; SCALAR-NEXT:    movl %r9d, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; SCALAR-NEXT:    movl %esi, %r11d
; SCALAR-NEXT:    andl $1073741824, %r11d # imm = 0x40000000
; SCALAR-NEXT:    cmovel %r11d, %edi
; SCALAR-NEXT:    cmovnel %r10d, %r11d
; SCALAR-NEXT:    xorl %eax, %edi
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; SCALAR-NEXT:    testl %eax, %eax
; SCALAR-NEXT:    leal (%rdi,%rdi), %r9d
; SCALAR-NEXT:    cmovel %eax, %r9d
; SCALAR-NEXT:    shll $31, %esi
; SCALAR-NEXT:    testl %r12d, %r12d
; SCALAR-NEXT:    cmovnel %esi, %r12d
; SCALAR-NEXT:    xorl %edi, %r12d
; SCALAR-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %esi # 4-byte Reload
; SCALAR-NEXT:    testl %esi, %esi
; SCALAR-NEXT:    cmovel %esi, %r12d
; SCALAR-NEXT:    xorl %r9d, %r12d
; SCALAR-NEXT:    xorl %r15d, %edx
; SCALAR-NEXT:    xorl %ebx, %edx
; SCALAR-NEXT:    xorl %r12d, %edx
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %r8d # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %r8d # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %r8d # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %r8d # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %r8d # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %r8d # 4-byte Folded Reload
; SCALAR-NEXT:    xorl %edx, %r8d
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Folded Reload
; SCALAR-NEXT:    xorl %r8d, %ecx
; SCALAR-NEXT:    xorl %r13d, %r14d
; SCALAR-NEXT:    xorl %ebp, %r14d
; SCALAR-NEXT:    xorl %r11d, %r14d
; SCALAR-NEXT:    xorl {{[-0-9]+}}(%r{{[sb]}}p), %r14d # 4-byte Folded Reload
; SCALAR-NEXT:    xorl %ecx, %r14d
; SCALAR-NEXT:    movl %r14d, %eax
; SCALAR-NEXT:    popq %rbx
; SCALAR-NEXT:    popq %r12
; SCALAR-NEXT:    popq %r13
; SCALAR-NEXT:    popq %r14
; SCALAR-NEXT:    popq %r15
; SCALAR-NEXT:    popq %rbp
; SCALAR-NEXT:    retq
;
; SSE-PCLMUL-LABEL: clmul_i32_chain:
; SSE-PCLMUL:       # %bb.0:
; SSE-PCLMUL-NEXT:    movd %edi, %xmm0
; SSE-PCLMUL-NEXT:    movdqa %xmm0, %xmm1
; SSE-PCLMUL-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; SSE-PCLMUL-NEXT:    pclmulqdq $0, %xmm0, %xmm1
; SSE-PCLMUL-NEXT:    movq %xmm1, %rax
; SSE-PCLMUL-NEXT:    # kill: def $eax killed $eax killed $rax
; SSE-PCLMUL-NEXT:    retq
;
; AVX-LABEL: clmul_i32_chain:
; AVX:       # %bb.0:
; AVX-NEXT:    vmovd %edi, %xmm0
; AVX-NEXT:    vpclmulqdq $0, %xmm0, %xmm0, %xmm1
; AVX-NEXT:    vpclmulqdq $0, %xmm0, %xmm1, %xmm0
; AVX-NEXT:    vmovq %xmm0, %rax
; AVX-NEXT:    # kill: def $eax killed $eax killed $rax
; AVX-NEXT:    retq
  %c0 = tail call i32 @llvm.clmul.i32(i32 %m, i32 %m)
  %c1 = tail call i32 @llvm.clmul.i32(i32 %c0, i32 %m)
  ret i32 %c1
}
