; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple i686-unknown-linux -mattr=+sse2 < %s | FileCheck --check-prefixes=CHECK,SSE2 %s
; RUN: llc -mtriple i686-unknown-linux -mattr=-sse2  < %s | FileCheck --check-prefixes=CHECK,SSE %s

define float @maxf(float %a, float %b) nounwind {
; SSE2-LABEL: maxf:
; SSE2:       # %bb.0: # %entry
; SSE2-NEXT:    pushl %eax
; SSE2-NEXT:    movss {{.*#+}} xmm0 = mem[0],zero,zero,zero
; SSE2-NEXT:    maxss {{[0-9]+}}(%esp), %xmm0
; SSE2-NEXT:    movss %xmm0, (%esp)
; SSE2-NEXT:    flds (%esp)
; SSE2-NEXT:    popl %eax
; SSE2-NEXT:    retl
;
; SSE-LABEL: maxf:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    flds {{[0-9]+}}(%esp)
; SSE-NEXT:    flds {{[0-9]+}}(%esp)
; SSE-NEXT:    fucom %st(1)
; SSE-NEXT:    fnstsw %ax
; SSE-NEXT:    # kill: def $ah killed $ah killed $ax
; SSE-NEXT:    sahf
; SSE-NEXT:    jae .LBB0_2
; SSE-NEXT:  # %bb.1: # %entry
; SSE-NEXT:    fstp %st(0)
; SSE-NEXT:    fldz
; SSE-NEXT:    fxch %st(1)
; SSE-NEXT:  .LBB0_2: # %entry
; SSE-NEXT:    fstp %st(1)
; SSE-NEXT:    retl
entry:
  %cmp = fcmp nnan nsz oge float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define float @minf(float %a, float %b) nounwind {
; SSE2-LABEL: minf:
; SSE2:       # %bb.0: # %entry
; SSE2-NEXT:    pushl %eax
; SSE2-NEXT:    movss {{.*#+}} xmm0 = mem[0],zero,zero,zero
; SSE2-NEXT:    minss {{[0-9]+}}(%esp), %xmm0
; SSE2-NEXT:    movss %xmm0, (%esp)
; SSE2-NEXT:    flds (%esp)
; SSE2-NEXT:    popl %eax
; SSE2-NEXT:    retl
;
; SSE-LABEL: minf:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    flds {{[0-9]+}}(%esp)
; SSE-NEXT:    flds {{[0-9]+}}(%esp)
; SSE-NEXT:    fucom %st(1)
; SSE-NEXT:    fnstsw %ax
; SSE-NEXT:    # kill: def $ah killed $ah killed $ax
; SSE-NEXT:    sahf
; SSE-NEXT:    jb .LBB1_2
; SSE-NEXT:  # %bb.1: # %entry
; SSE-NEXT:    fstp %st(0)
; SSE-NEXT:    fldz
; SSE-NEXT:    fxch %st(1)
; SSE-NEXT:  .LBB1_2: # %entry
; SSE-NEXT:    fstp %st(1)
; SSE-NEXT:    retl
entry:
  %cmp = fcmp nnan nsz olt float %a, %b
  %cond = select nnan nsz i1 %cmp, float %a, float %b
  ret float %cond
}

define double @maxd(double %a, double %b) nounwind {
; SSE2-LABEL: maxd:
; SSE2:       # %bb.0: # %entry
; SSE2-NEXT:    subl $12, %esp
; SSE2-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; SSE2-NEXT:    maxsd {{[0-9]+}}(%esp), %xmm0
; SSE2-NEXT:    movsd %xmm0, (%esp)
; SSE2-NEXT:    fldl (%esp)
; SSE2-NEXT:    addl $12, %esp
; SSE2-NEXT:    retl
;
; SSE-LABEL: maxd:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    fldl {{[0-9]+}}(%esp)
; SSE-NEXT:    fldl {{[0-9]+}}(%esp)
; SSE-NEXT:    fucom %st(1)
; SSE-NEXT:    fnstsw %ax
; SSE-NEXT:    # kill: def $ah killed $ah killed $ax
; SSE-NEXT:    sahf
; SSE-NEXT:    jae .LBB2_2
; SSE-NEXT:  # %bb.1: # %entry
; SSE-NEXT:    fstp %st(0)
; SSE-NEXT:    fldz
; SSE-NEXT:    fxch %st(1)
; SSE-NEXT:  .LBB2_2: # %entry
; SSE-NEXT:    fstp %st(1)
; SSE-NEXT:    retl
entry:
  %cmp = fcmp nnan nsz oge double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}

define double @mind(double %a, double %b) nounwind {
; SSE2-LABEL: mind:
; SSE2:       # %bb.0: # %entry
; SSE2-NEXT:    subl $12, %esp
; SSE2-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; SSE2-NEXT:    minsd {{[0-9]+}}(%esp), %xmm0
; SSE2-NEXT:    movsd %xmm0, (%esp)
; SSE2-NEXT:    fldl (%esp)
; SSE2-NEXT:    addl $12, %esp
; SSE2-NEXT:    retl
;
; SSE-LABEL: mind:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    fldl {{[0-9]+}}(%esp)
; SSE-NEXT:    fldl {{[0-9]+}}(%esp)
; SSE-NEXT:    fucom %st(1)
; SSE-NEXT:    fnstsw %ax
; SSE-NEXT:    # kill: def $ah killed $ah killed $ax
; SSE-NEXT:    sahf
; SSE-NEXT:    jb .LBB3_2
; SSE-NEXT:  # %bb.1: # %entry
; SSE-NEXT:    fstp %st(0)
; SSE-NEXT:    fldz
; SSE-NEXT:    fxch %st(1)
; SSE-NEXT:  .LBB3_2: # %entry
; SSE-NEXT:    fstp %st(1)
; SSE-NEXT:    retl
entry:
  %cmp = fcmp nnan nsz olt double %a, %b
  %cond = select nnan nsz i1 %cmp, double %a, double %b
  ret double %cond
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
