; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+cmov | FileCheck %s --check-prefix=X64
; RUN: llc < %s -mtriple=i386-unknown-linux-gnu -mattr=+cmov | FileCheck %s --check-prefix=X32
; RUN: llc < %s -mtriple=i386-unknown-linux-gnu -mattr=-cmov | FileCheck %s --check-prefix=X32-NOCMOV

; Test basic ct.select functionality for scalar types

define i8 @test_ctselect_i8(i1 %cond, i8 %a, i8 %b) #0 {
; X64-LABEL: test_ctselect_i8:
; X64:       # %bb.0:
; X64-NEXT:    movl %edx, %eax
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel %esi, %eax
; X64-NEXT:    # kill: def $al killed $al killed $eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_i8:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    # kill: def $al killed $al killed $eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_i8:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    retl
  %result = call i8 @llvm.ct.select.i8(i1 %cond, i8 %a, i8 %b)
  ret i8 %result
}

define i32 @test_ctselect_i32(i1 %cond, i32 %a, i32 %b) #0 {
; X64-LABEL: test_ctselect_i32:
; X64:       # %bb.0:
; X64-NEXT:    movl %edx, %eax
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel %esi, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_i32:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_i32:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %result = call i32 @llvm.ct.select.i32(i1 %cond, i32 %a, i32 %b)
  ret i32 %result
}

define i64 @test_ctselect_i64(i1 %cond, i64 %a, i64 %b) #0 {
; X64-LABEL: test_ctselect_i64:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdx, %rax
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovneq %rsi, %rax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_i64:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %edx
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_i64:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebp
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    sete %bh
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    popl %ebp
; X32-NOCMOV-NEXT:    retl
  %result = call i64 @llvm.ct.select.i64(i1 %cond, i64 %a, i64 %b)
  ret i64 %result
}

define float @test_ctselect_f32(i1 %cond, float %a, float %b) #0 {
; X64-LABEL: test_ctselect_f32:
; X64:       # %bb.0:
; X64-NEXT:    movd %xmm0, %eax
; X64-NEXT:    movd %xmm1, %ecx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel %eax, %ecx
; X64-NEXT:    movd %ecx, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_f32:
; X32:       # %bb.0:
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    pushl %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    sete %al
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %esi, (%esp)
; X32-NEXT:    flds (%esp)
; X32-NEXT:    addl $4, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_f32:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    pushl %eax
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, (%esp)
; X32-NOCMOV-NEXT:    flds (%esp)
; X32-NOCMOV-NEXT:    addl $4, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    retl
  %result = call float @llvm.ct.select.f32(i1 %cond, float %a, float %b)
  ret float %result
}

define double @test_ctselect_f64(i1 %cond, double %a, double %b) #0 {
; X64-LABEL: test_ctselect_f64:
; X64:       # %bb.0:
; X64-NEXT:    movq %xmm0, %rax
; X64-NEXT:    movq %xmm1, %rcx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovneq %rax, %rcx
; X64-NEXT:    movq %rcx, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_f64:
; X32:       # %bb.0:
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    subl $8, %esp
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    sete %al
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %esi, (%esp)
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X32-NEXT:    fldl (%esp)
; X32-NEXT:    addl $8, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_f64:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $8, %esp
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, (%esp)
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fldl (%esp)
; X32-NOCMOV-NEXT:    addl $8, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    retl
  %result = call double @llvm.ct.select.f64(i1 %cond, double %a, double %b)
  ret double %result
}

define half @test_ctselect_f16(i1 %cond, half %a, half %b) #0 {
; X64-LABEL: test_ctselect_f16:
; X64:       # %bb.0:
; X64-NEXT:    pextrw $0, %xmm0, %eax
; X64-NEXT:    pextrw $0, %xmm1, %ecx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel %ecx, %eax
; X64-NEXT:    pinsrw $0, %eax, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_f16:
; X32:       # %bb.0:
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %ax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_f16:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %result = call half @llvm.ct.select.f16(i1 %cond, half %a, half %b)
  ret half %result
}

define bfloat @test_ctselect_bf16(i1 %cond, bfloat %a, bfloat %b) #0 {
; X64-LABEL: test_ctselect_bf16:
; X64:       # %bb.0:
; X64-NEXT:    pextrw $0, %xmm1, %eax
; X64-NEXT:    pextrw $0, %xmm0, %ecx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel %ecx, %eax
; X64-NEXT:    pinsrw $0, %eax, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_bf16:
; X32:       # %bb.0:
; X32-NEXT:    pushl %esi
; X32-NEXT:    subl $8, %esp
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    movl %eax, %esi
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel %eax, %esi
; X32-NEXT:    shll $16, %esi
; X32-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    addl $8, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_bf16:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $20, %esp
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    movl %eax, %esi
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    shll $16, %edx
; X32-NOCMOV-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    addl $20, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    retl
  %result = call bfloat @llvm.ct.select.bf16(i1 %cond, bfloat %a, bfloat %b)
  ret bfloat %result
}

define fp128 @test_ctselect_f128(i1 %cond, fp128 %a, fp128 %b) #0 {
; X64-LABEL: test_ctselect_f128:
; X64:       # %bb.0:
; X64-NEXT:    movaps %xmm1, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq -{{[0-9]+}}(%rsp), %rax
; X64-NEXT:    movq -{{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovneq -{{[0-9]+}}(%rsp), %rax
; X64-NEXT:    movq %rax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    cmovneq -{{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movaps -{{[0-9]+}}(%rsp), %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_f128:
; X32:       # %bb.0:
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    pushl %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %esi
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %edi
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %edx
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl %ecx, 12(%eax)
; X32-NEXT:    movl %edx, 8(%eax)
; X32-NEXT:    movl %edi, 4(%eax)
; X32-NEXT:    movl %esi, (%eax)
; X32-NEXT:    addl $4, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    retl $4
;
; X32-NOCMOV-LABEL: test_ctselect_f128:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebp
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $12, %esp
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    sete %bh
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    sete %bh
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, 12(%eax)
; X32-NOCMOV-NEXT:    movl %edi, 8(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, 4(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, (%eax)
; X32-NOCMOV-NEXT:    addl $12, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    popl %ebp
; X32-NOCMOV-NEXT:    retl $4
  %result = call fp128 @llvm.ct.select.f128(i1 %cond, fp128 %a, fp128 %b)
  ret fp128 %result
}

define x86_fp80 @test_ctselect_f80(i1 %cond, x86_fp80 %a, x86_fp80 %b) #0 {
; X64-LABEL: test_ctselect_f80:
; X64:       # %bb.0:
; X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; X64-NEXT:    fstpt -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstpt -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    movl %eax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    movl -{{[0-9]+}}(%rsp), %ecx
; X64-NEXT:    cmovnel -{{[0-9]+}}(%rsp), %ecx
; X64-NEXT:    movl %ecx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    cmovnel -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    movl %eax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fldt -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_f80:
; X32:       # %bb.0:
; X32-NEXT:    subl $36, %esp
; X32-NEXT:    fldt {{[0-9]+}}(%esp)
; X32-NEXT:    fldt {{[0-9]+}}(%esp)
; X32-NEXT:    fstpt {{[0-9]+}}(%esp)
; X32-NEXT:    fstpt {{[0-9]+}}(%esp)
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl %eax, (%esp)
; X32-NEXT:    fldt (%esp)
; X32-NEXT:    addl $36, %esp
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_f80:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebp
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $40, %esp
; X32-NOCMOV-NEXT:    fldt {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fldt {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstpt {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstpt {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    sete %ch
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    sete %ch
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    movl %ebx, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl (%esp), %ebx # 4-byte Reload
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fldt {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    addl $40, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    popl %ebp
; X32-NOCMOV-NEXT:    retl
  %result = call x86_fp80 @llvm.ct.select.f80(i1 %cond, x86_fp80 %a, x86_fp80 %b)
  ret x86_fp80 %result
}

define ptr @test_ctselect_ptr(i1 %cond, ptr %a, ptr %b) #0 {
; X64-LABEL: test_ctselect_ptr:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdx, %rax
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovneq %rsi, %rax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_ptr:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_ptr:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %result = call ptr @llvm.ct.select.p0(i1 %cond, ptr %a, ptr %b)
  ret ptr %result
}

; Test with constant conditions
define i32 @test_ctselect_const_true(i32 %a, i32 %b) #0 {
; X64-LABEL: test_ctselect_const_true:
; X64:       # %bb.0:
; X64-NEXT:    movl %esi, %eax
; X64-NEXT:    movb $1, %cl
; X64-NEXT:    testb %cl, %cl
; X64-NEXT:    cmovnel %edi, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_const_true:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movb $1, %cl
; X32-NEXT:    testb %cl, %cl
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_const_true:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movb $1, %al
; X32-NOCMOV-NEXT:    testb %al, %al
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %result = call i32 @llvm.ct.select.i32(i1 true, i32 %a, i32 %b)
  ret i32 %result
}

define i32 @test_ctselect_const_false(i32 %a, i32 %b) #0 {
; X64-LABEL: test_ctselect_const_false:
; X64:       # %bb.0:
; X64-NEXT:    movl %esi, %eax
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    testb %cl, %cl
; X64-NEXT:    cmovnel %edi, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_const_false:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    xorl %ecx, %ecx
; X32-NEXT:    testb %cl, %cl
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_const_false:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    xorl %eax, %eax
; X32-NOCMOV-NEXT:    testb %al, %al
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %result = call i32 @llvm.ct.select.i32(i1 false, i32 %a, i32 %b)
  ret i32 %result
}

; Test with comparison conditions
define i32 @test_ctselect_icmp_eq(i32 %x, i32 %y, i32 %a, i32 %b) #0 {
; X64-LABEL: test_ctselect_icmp_eq:
; X64:       # %bb.0:
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    cmpl %esi, %edi
; X64-NEXT:    sete %cl
; X64-NEXT:    testb %cl, %cl
; X64-NEXT:    cmovnel %edx, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_icmp_eq:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    cmpl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    sete %cl
; X32-NEXT:    testb %cl, %cl
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_icmp_eq:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    testb %al, %al
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %cond = icmp eq i32 %x, %y
  %result = call i32 @llvm.ct.select.i32(i1 %cond, i32 %a, i32 %b)
  ret i32 %result
}

define i32 @test_ctselect_icmp_ult(i32 %x, i32 %y, i32 %a, i32 %b) #0 {
; X64-LABEL: test_ctselect_icmp_ult:
; X64:       # %bb.0:
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    cmpl %esi, %edi
; X64-NEXT:    setb %cl
; X64-NEXT:    testb %cl, %cl
; X64-NEXT:    cmovnel %edx, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_icmp_ult:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    cmpl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    setb %cl
; X32-NEXT:    testb %cl, %cl
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_icmp_ult:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    cmpl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    setb %al
; X32-NOCMOV-NEXT:    testb %al, %al
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %cond = icmp ult i32 %x, %y
  %result = call i32 @llvm.ct.select.i32(i1 %cond, i32 %a, i32 %b)
  ret i32 %result
}

define float @test_ctselect_fcmp_oeq(float %x, float %y, float %a, float %b) #0 {
; X64-LABEL: test_ctselect_fcmp_oeq:
; X64:       # %bb.0:
; X64-NEXT:    movd %xmm2, %eax
; X64-NEXT:    movd %xmm3, %ecx
; X64-NEXT:    ucomiss %xmm1, %xmm0
; X64-NEXT:    setnp %dl
; X64-NEXT:    sete %sil
; X64-NEXT:    testb %dl, %sil
; X64-NEXT:    cmovnel %eax, %ecx
; X64-NEXT:    movd %ecx, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_fcmp_oeq:
; X32:       # %bb.0:
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    pushl %eax
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fucompi %st(1), %st
; X32-NEXT:    fstp %st(0)
; X32-NEXT:    setnp %al
; X32-NEXT:    sete %cl
; X32-NEXT:    testb %al, %cl
; X32-NEXT:    sete %al
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %esi, (%esp)
; X32-NEXT:    flds (%esp)
; X32-NEXT:    addl $4, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_fcmp_oeq:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    pushl %eax
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fucompp
; X32-NOCMOV-NEXT:    fnstsw %ax
; X32-NOCMOV-NEXT:    # kill: def $ah killed $ah killed $ax
; X32-NOCMOV-NEXT:    sahf
; X32-NOCMOV-NEXT:    setnp %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    testb %al, %cl
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, (%esp)
; X32-NOCMOV-NEXT:    flds (%esp)
; X32-NOCMOV-NEXT:    addl $4, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    retl
  %cond = fcmp oeq float %x, %y
  %result = call float @llvm.ct.select.f32(i1 %cond, float %a, float %b)
  ret float %result
}

; Test with memory operands
define i32 @test_ctselect_load(i1 %cond, ptr %p1, ptr %p2) #0 {
; X64-LABEL: test_ctselect_load:
; X64:       # %bb.0:
; X64-NEXT:    movl (%rdx), %eax
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel (%rsi), %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_load:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl (%eax), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel (%ecx), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_load:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl (%ecx), %ecx
; X32-NOCMOV-NEXT:    movl (%eax), %edx
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %a = load i32, ptr %p1
  %b = load i32, ptr %p2
  %result = call i32 @llvm.ct.select.i32(i1 %cond, i32 %a, i32 %b)
  ret i32 %result
}

; Test nested ct_select calls
define i32 @test_ctselect_nested(i1 %cond1, i1 %cond2, i32 %a, i32 %b, i32 %c) #0 {
; X64-LABEL: test_ctselect_nested:
; X64:       # %bb.0:
; X64-NEXT:    movl %r8d, %eax
; X64-NEXT:    testb $1, %sil
; X64-NEXT:    cmovnel %edx, %ecx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    cmovnel %ecx, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_nested:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel %ecx, %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_nested:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %dl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %inner = call i32 @llvm.ct.select.i32(i1 %cond2, i32 %a, i32 %b)
  %result = call i32 @llvm.ct.select.i32(i1 %cond1, i32 %inner, i32 %c)
  ret i32 %result
}

; Test nested CT_SELECT pattern with AND merging on i1 values
; Pattern: ct_select C0, (ct_select C1, X, Y), Y -> ct_select (C0 & C1), X, Y
; This optimization only applies when selecting between i1 values (boolean logic)
define i32 @test_ctselect_nested_and_i1_to_i32(i1 %c0, i1 %c1, i32 %x, i32 %y) #0 {
; X64-LABEL: test_ctselect_nested_and_i1_to_i32:
; X64:       # %bb.0:
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    andl %esi, %edi
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    movl $1, %esi
; X64-NEXT:    cmovnel %esi, %ecx
; X64-NEXT:    testb $1, %cl
; X64-NEXT:    cmovnel %edx, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_nested_and_i1_to_i32:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    andb {{[0-9]+}}(%esp), %cl
; X32-NEXT:    xorl %edx, %edx
; X32-NEXT:    testb $1, %cl
; X32-NEXT:    movl $1, %ecx
; X32-NEXT:    cmovnel %ecx, %edx
; X32-NEXT:    testb $1, %dl
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_nested_and_i1_to_i32:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    andb {{[0-9]+}}(%esp), %al
; X32-NOCMOV-NEXT:    xorl %ebx, %ebx
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movb $1, %al
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %inner = call i1 @llvm.ct.select.i1(i1 %c1, i1 true, i1 false)
  %cond = call i1 @llvm.ct.select.i1(i1 %c0, i1 %inner, i1 false)
  %result = call i32 @llvm.ct.select.i32(i1 %cond, i32 %x, i32 %y)
  ret i32 %result
}

; Test nested CT_SELECT pattern with OR merging on i1 values
; Pattern: ct_select C0, X, (ct_select C1, X, Y) -> ct_select (C0 | C1), X, Y
; This optimization only applies when selecting between i1 values (boolean logic)
define i32 @test_ctselect_nested_or_i1_to_i32(i1 %c0, i1 %c1, i32 %x, i32 %y) #0 {
; X64-LABEL: test_ctselect_nested_or_i1_to_i32:
; X64:       # %bb.0:
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    orl %esi, %edi
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    movl $1, %esi
; X64-NEXT:    cmovnel %esi, %ecx
; X64-NEXT:    testb $1, %cl
; X64-NEXT:    cmovnel %edx, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_nested_or_i1_to_i32:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    orb {{[0-9]+}}(%esp), %cl
; X32-NEXT:    xorl %edx, %edx
; X32-NEXT:    testb $1, %cl
; X32-NEXT:    movl $1, %ecx
; X32-NEXT:    cmovnel %ecx, %edx
; X32-NEXT:    testb $1, %dl
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_nested_or_i1_to_i32:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    orb {{[0-9]+}}(%esp), %al
; X32-NOCMOV-NEXT:    xorl %ebx, %ebx
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movb $1, %al
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %inner = call i1 @llvm.ct.select.i1(i1 %c1, i1 true, i1 false)
  %cond = call i1 @llvm.ct.select.i1(i1 %c0, i1 true, i1 %inner)
  %result = call i32 @llvm.ct.select.i32(i1 %cond, i32 %x, i32 %y)
  ret i32 %result
}

; Test double nested CT_SELECT with recursive AND merging
; Pattern: ct_select C0, (ct_select C1, (ct_select C2, X, Y), Y), Y
;   -> ct_select C0, (ct_select (C1 & C2), X, Y), Y
;   -> ct_select (C0 & (C1 & C2)), X, Y
; This tests that the optimization can be applied recursively
define i32 @test_ctselect_double_nested_and_i1(i1 %c0, i1 %c1, i1 %c2, i32 %x, i32 %y) #0 {
; X64-LABEL: test_ctselect_double_nested_and_i1:
; X64:       # %bb.0:
; X64-NEXT:    movl %r8d, %eax
; X64-NEXT:    andl %esi, %edi
; X64-NEXT:    andl %edx, %edi
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    movl $1, %esi
; X64-NEXT:    cmovnel %esi, %edx
; X64-NEXT:    testb $1, %dl
; X64-NEXT:    cmovnel %ecx, %eax
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_double_nested_and_i1:
; X32:       # %bb.0:
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    andb {{[0-9]+}}(%esp), %cl
; X32-NEXT:    andb {{[0-9]+}}(%esp), %cl
; X32-NEXT:    xorl %edx, %edx
; X32-NEXT:    testb $1, %cl
; X32-NEXT:    movl $1, %ecx
; X32-NEXT:    cmovnel %ecx, %edx
; X32-NEXT:    testb $1, %dl
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_double_nested_and_i1:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    andb {{[0-9]+}}(%esp), %al
; X32-NOCMOV-NEXT:    andb {{[0-9]+}}(%esp), %al
; X32-NOCMOV-NEXT:    xorl %ebx, %ebx
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movb $1, %al
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl
  %inner2 = call i1 @llvm.ct.select.i1(i1 %c2, i1 true, i1 false)
  %inner1 = call i1 @llvm.ct.select.i1(i1 %c1, i1 %inner2, i1 false)
  %cond = call i1 @llvm.ct.select.i1(i1 %c0, i1 %inner1, i1 false)
  %result = call i32 @llvm.ct.select.i32(i1 %cond, i32 %x, i32 %y)
  ret i32 %result
}

; Vector CT_SELECT Tests
; ============================================================================

; Test vector CT_SELECT with v4i32 (128-bit vector with single i1 mask)
; NOW CONSTANT-TIME: Uses bitwise XOR/AND operations instead of branches!
define <4 x i32> @test_ctselect_v4i32(i1 %cond, <4 x i32> %a, <4 x i32> %b) #0 {
; X64-LABEL: test_ctselect_v4i32:
; X64:       # %bb.0:
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    BUNDLE
; X64-NEXT:    movaps %xmm2, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_v4i32:
; X32:       # %bb.0:
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %edi
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %esi
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %edx
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl %ecx, 12(%eax)
; X32-NEXT:    movl %edx, 8(%eax)
; X32-NEXT:    movl %esi, 4(%eax)
; X32-NEXT:    movl %edi, (%eax)
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    retl $4
;
; X32-NOCMOV-LABEL: test_ctselect_v4i32:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebp
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $8, %esp
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    sete %bh
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    sete %bh
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ecx, (%esp) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    sete %bh
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %bl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    sete %bl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, 12(%eax)
; X32-NOCMOV-NEXT:    movl %edi, 8(%eax)
; X32-NOCMOV-NEXT:    movl (%esp), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, 4(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, (%eax)
; X32-NOCMOV-NEXT:    addl $8, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    popl %ebp
; X32-NOCMOV-NEXT:    retl $4
  %result = call <4 x i32> @llvm.ct.select.v4i32(i1 %cond, <4 x i32> %a, <4 x i32> %b)
  ret <4 x i32> %result
}
define <4 x float> @test_ctselect_v4f32(i1 %cond, <4 x float> %a, <4 x float> %b) #0 {
; X64-LABEL: test_ctselect_v4f32:
; X64:       # %bb.0:
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    BUNDLE
; X64-NEXT:    movaps %xmm2, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_v4f32:
; X32:       # %bb.0:
; X32-NEXT:    pushl %ebx
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    subl $16, %esp
; X32-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, (%esp)
; X32-NEXT:    flds (%esp)
; X32-NEXT:    fstps 12(%eax)
; X32-NEXT:    fstps 8(%eax)
; X32-NEXT:    fstps 4(%eax)
; X32-NEXT:    fstps (%eax)
; X32-NEXT:    addl $16, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    popl %ebx
; X32-NEXT:    retl $4
;
; X32-NOCMOV-LABEL: test_ctselect_v4f32:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $16, %esp
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, (%esp)
; X32-NOCMOV-NEXT:    flds (%esp)
; X32-NOCMOV-NEXT:    fstps 12(%eax)
; X32-NOCMOV-NEXT:    fstps 8(%eax)
; X32-NOCMOV-NEXT:    fstps 4(%eax)
; X32-NOCMOV-NEXT:    fstps (%eax)
; X32-NOCMOV-NEXT:    addl $16, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl $4
  %result = call <4 x float> @llvm.ct.select.v4f32(i1 %cond, <4 x float> %a, <4 x float> %b)
  ret <4 x float> %result
}

define <8 x i32> @test_ctselect_v8i32_avx(i1 %cond, <8 x i32> %a, <8 x i32> %b) #0 {
; X64-LABEL: test_ctselect_v8i32_avx:
; X64:       # %bb.0:
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    BUNDLE
; X64-NEXT:    BUNDLE
; X64-NEXT:    movaps %xmm4, %xmm0
; X64-NEXT:    movaps %xmm2, %xmm1
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_v8i32_avx:
; X32:       # %bb.0:
; X32-NEXT:    pushl %ebp
; X32-NEXT:    pushl %ebx
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    subl $8, %esp
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %edx
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %esi
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %edi
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ebx
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ebp
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl %ecx, (%esp) # 4-byte Spill
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    cmovnel {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movl %ecx, 28(%eax)
; X32-NEXT:    movl (%esp), %ecx # 4-byte Reload
; X32-NEXT:    movl %ecx, 24(%eax)
; X32-NEXT:    movl %ebp, 20(%eax)
; X32-NEXT:    movl %ebx, 16(%eax)
; X32-NEXT:    movl %edi, 12(%eax)
; X32-NEXT:    movl %esi, 8(%eax)
; X32-NEXT:    movl %edx, 4(%eax)
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NEXT:    movl %ecx, (%eax)
; X32-NEXT:    addl $8, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    popl %ebx
; X32-NEXT:    popl %ebp
; X32-NEXT:    retl $4
;
; X32-NOCMOV-LABEL: test_ctselect_v8i32_avx:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebp
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $20, %esp
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, (%esp) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    sete %dl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    movl %esi, 28(%eax)
; X32-NOCMOV-NEXT:    movl %edi, 24(%eax)
; X32-NOCMOV-NEXT:    movl %ebp, 20(%eax)
; X32-NOCMOV-NEXT:    movl (%esp), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, 16(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, 12(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, 8(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, 4(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl %ecx, (%eax)
; X32-NOCMOV-NEXT:    addl $20, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    popl %ebp
; X32-NOCMOV-NEXT:    retl $4
  %result = call <8 x i32> @llvm.ct.select.v8i32(i1 %cond, <8 x i32> %a, <8 x i32> %b)
  ret <8 x i32> %result
}

define <8 x float> @test_ctselect_v8f32(i1 %cond, <8 x float> %a, <8 x float> %b) #0 {
; X64-LABEL: test_ctselect_v8f32:
; X64:       # %bb.0:
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    BUNDLE
; X64-NEXT:    BUNDLE
; X64-NEXT:    movaps %xmm4, %xmm0
; X64-NEXT:    movaps %xmm2, %xmm1
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_v8f32:
; X32:       # %bb.0:
; X32-NEXT:    pushl %ebx
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    subl $36, %esp
; X32-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp) # 4-byte Folded Spill
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    testb $1, %al
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    sete %cl
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps 28(%eax)
; X32-NEXT:    fstps 24(%eax)
; X32-NEXT:    fstps 20(%eax)
; X32-NEXT:    fstps 16(%eax)
; X32-NEXT:    fstps 12(%eax)
; X32-NEXT:    fstps 8(%eax)
; X32-NEXT:    fstps 4(%eax)
; X32-NEXT:    flds (%esp) # 4-byte Folded Reload
; X32-NEXT:    fstps (%eax)
; X32-NEXT:    addl $36, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    popl %ebx
; X32-NEXT:    retl $4
;
; X32-NOCMOV-LABEL: test_ctselect_v8f32:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $36, %esp
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp) # 4-byte Folded Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps 28(%eax)
; X32-NOCMOV-NEXT:    fstps 24(%eax)
; X32-NOCMOV-NEXT:    fstps 20(%eax)
; X32-NOCMOV-NEXT:    fstps 16(%eax)
; X32-NOCMOV-NEXT:    fstps 12(%eax)
; X32-NOCMOV-NEXT:    fstps 8(%eax)
; X32-NOCMOV-NEXT:    fstps 4(%eax)
; X32-NOCMOV-NEXT:    flds (%esp) # 4-byte Folded Reload
; X32-NOCMOV-NEXT:    fstps (%eax)
; X32-NOCMOV-NEXT:    addl $36, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    retl $4
  %result = call <8 x float> @llvm.ct.select.v8f32(i1 %cond, <8 x float> %a, <8 x float> %b)
  ret <8 x float> %result
}

define <8 x half> @test_ctselect_v8f16(i1 %cond, <8 x half> %a, <8 x half> %b) #0 {
; X64-LABEL: test_ctselect_v8f16:
; X64:       # %bb.0:
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    BUNDLE
; X64-NEXT:    movaps %xmm2, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_v8f16:
; X32:       # %bb.0:
; X32-NEXT:    pushl %ebp
; X32-NEXT:    pushl %ebx
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    pushl %eax
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %ebp
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %ebx
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %edi
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %esi
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %ax
; X32-NEXT:    movw %ax, {{[-0-9]+}}(%e{{[sb]}}p) # 2-byte Spill
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %dx
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %si
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %di
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %bx
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %bp
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %cx
; X32-NEXT:    movw %cx, (%esp) # 2-byte Spill
; X32-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    cmovnew {{[0-9]+}}(%esp), %cx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NEXT:    movw %cx, 14(%eax)
; X32-NEXT:    movzwl (%esp), %ecx # 2-byte Folded Reload
; X32-NEXT:    movw %cx, 12(%eax)
; X32-NEXT:    movw %bp, 10(%eax)
; X32-NEXT:    movw %bx, 8(%eax)
; X32-NEXT:    movw %di, 6(%eax)
; X32-NEXT:    movw %si, 4(%eax)
; X32-NEXT:    movw %dx, 2(%eax)
; X32-NEXT:    movzwl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 2-byte Folded Reload
; X32-NEXT:    movw %cx, (%eax)
; X32-NEXT:    addl $4, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    popl %ebx
; X32-NEXT:    popl %ebp
; X32-NEXT:    retl $4
;
; X32-NOCMOV-LABEL: test_ctselect_v8f16:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebp
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $12, %esp
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movw %cx, {{[-0-9]+}}(%e{{[sb]}}p) # 2-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movw %cx, {{[-0-9]+}}(%e{{[sb]}}p) # 2-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %edi
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movw %dx, {{[-0-9]+}}(%e{{[sb]}}p) # 2-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movw %si, {{[-0-9]+}}(%e{{[sb]}}p) # 2-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ebp
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    sete %ah
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movw %di, {{[-0-9]+}}(%e{{[sb]}}p) # 2-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    sete %dl
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %esi
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %al
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %ebx
; X32-NOCMOV-NEXT:    movzwl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    movw %si, 14(%eax)
; X32-NOCMOV-NEXT:    movw %di, 12(%eax)
; X32-NOCMOV-NEXT:    movw %bp, 10(%eax)
; X32-NOCMOV-NEXT:    movzwl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 2-byte Folded Reload
; X32-NOCMOV-NEXT:    movw %cx, 8(%eax)
; X32-NOCMOV-NEXT:    movzwl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 2-byte Folded Reload
; X32-NOCMOV-NEXT:    movw %cx, 6(%eax)
; X32-NOCMOV-NEXT:    movzwl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 2-byte Folded Reload
; X32-NOCMOV-NEXT:    movw %cx, 4(%eax)
; X32-NOCMOV-NEXT:    movzwl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 2-byte Folded Reload
; X32-NOCMOV-NEXT:    movw %cx, 2(%eax)
; X32-NOCMOV-NEXT:    movzwl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 2-byte Folded Reload
; X32-NOCMOV-NEXT:    movw %cx, (%eax)
; X32-NOCMOV-NEXT:    addl $12, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    popl %ebp
; X32-NOCMOV-NEXT:    retl $4
  %result = call <8 x half> @llvm.ct.select.v8f16(i1 %cond, <8 x half> %a, <8 x half> %b)
  ret <8 x half> %result
}

define <8 x bfloat> @test_ctselect_v8bf16(i1 %cond, <8 x bfloat> %a, <8 x bfloat> %b) #0 {
; X64-LABEL: test_ctselect_v8bf16:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbp
; X64-NEXT:    pushq %r15
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %r13
; X64-NEXT:    pushq %r12
; X64-NEXT:    pushq %rbx
; X64-NEXT:    movl %edi, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; X64-NEXT:    movq %xmm0, %rdi
; X64-NEXT:    punpckhqdq {{.*#+}} xmm0 = xmm0[1,1]
; X64-NEXT:    movq %xmm0, %r14
; X64-NEXT:    movl %r14d, %eax
; X64-NEXT:    shrl $16, %eax
; X64-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; X64-NEXT:    movq %xmm1, %r10
; X64-NEXT:    punpckhqdq {{.*#+}} xmm1 = xmm1[1,1]
; X64-NEXT:    movq %xmm1, %r11
; X64-NEXT:    movl %r11d, %r9d
; X64-NEXT:    shrl $16, %r9d
; X64-NEXT:    movq %r11, %rdx
; X64-NEXT:    shrq $48, %rdx
; X64-NEXT:    movq %r14, %r12
; X64-NEXT:    shrq $48, %r12
; X64-NEXT:    movq %r11, %rbx
; X64-NEXT:    shrq $32, %rbx
; X64-NEXT:    movq %r14, %r13
; X64-NEXT:    shrq $32, %r13
; X64-NEXT:    movl %edi, %ebp
; X64-NEXT:    shrl $16, %ebp
; X64-NEXT:    movl %r10d, %esi
; X64-NEXT:    shrl $16, %esi
; X64-NEXT:    movq %r10, %rcx
; X64-NEXT:    shrq $48, %rcx
; X64-NEXT:    movq %rdi, %r15
; X64-NEXT:    shrq $48, %r15
; X64-NEXT:    movq %r10, %r8
; X64-NEXT:    shrq $32, %r8
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    shrq $32, %rax
; X64-NEXT:    testb $1, {{[-0-9]+}}(%r{{[sb]}}p) # 1-byte Folded Reload
; X64-NEXT:    cmovnel %eax, %r8d
; X64-NEXT:    cmovnel %r15d, %ecx
; X64-NEXT:    cmovnel %edi, %r10d
; X64-NEXT:    cmovnel %ebp, %esi
; X64-NEXT:    cmovnel %r13d, %ebx
; X64-NEXT:    cmovnel %r12d, %edx
; X64-NEXT:    cmovnel %r14d, %r11d
; X64-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; X64-NEXT:    cmovnel %eax, %r9d
; X64-NEXT:    shll $16, %r9d
; X64-NEXT:    movzwl %r11w, %eax
; X64-NEXT:    orl %r9d, %eax
; X64-NEXT:    shll $16, %edx
; X64-NEXT:    movzwl %bx, %edi
; X64-NEXT:    orl %edx, %edi
; X64-NEXT:    shlq $32, %rdi
; X64-NEXT:    orq %rax, %rdi
; X64-NEXT:    shll $16, %esi
; X64-NEXT:    movzwl %r10w, %eax
; X64-NEXT:    orl %esi, %eax
; X64-NEXT:    shll $16, %ecx
; X64-NEXT:    movzwl %r8w, %edx
; X64-NEXT:    orl %ecx, %edx
; X64-NEXT:    shlq $32, %rdx
; X64-NEXT:    orq %rax, %rdx
; X64-NEXT:    movq %rdx, %xmm0
; X64-NEXT:    movq %rdi, %xmm1
; X64-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r12
; X64-NEXT:    popq %r13
; X64-NEXT:    popq %r14
; X64-NEXT:    popq %r15
; X64-NEXT:    popq %rbp
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_v8bf16:
; X32:       # %bb.0:
; X32-NEXT:    pushl %ebp
; X32-NEXT:    pushl %ebx
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    subl $60, %esp
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    movl %eax, %esi
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    movl %eax, %edi
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    movl %eax, %ebx
; X32-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NEXT:    fstps (%esp)
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X32-NEXT:    calll __truncsfbf2
; X32-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    cmovnel %eax, %ebx
; X32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    cmovnel %eax, %edi
; X32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    cmovnel %eax, %edi
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    cmovnel %eax, %esi
; X32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    cmovnel %eax, %esi
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    cmovnel %eax, %ebx
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    cmovnel %eax, %edx
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NEXT:    cmovnel %ecx, %eax
; X32-NEXT:    movw %ax, 14(%ebp)
; X32-NEXT:    movw %dx, 12(%ebp)
; X32-NEXT:    movw %bx, 10(%ebp)
; X32-NEXT:    movw %si, 8(%ebp)
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    movw %ax, 6(%ebp)
; X32-NEXT:    movw %di, 4(%ebp)
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    movw %ax, 2(%ebp)
; X32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X32-NEXT:    movw %ax, (%ebp)
; X32-NEXT:    movl %ebp, %eax
; X32-NEXT:    addl $60, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    popl %ebx
; X32-NEXT:    popl %ebp
; X32-NEXT:    retl $4
;
; X32-NOCMOV-LABEL: test_ctselect_v8bf16:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %ebp
; X32-NOCMOV-NEXT:    pushl %ebx
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $60, %esp
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    movl %eax, %edi
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    movl %eax, %ebx
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movb {{[0-9]+}}(%esp), %ch
; X32-NOCMOV-NEXT:    testb $1, %ch
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %ch
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    movl %eax, %esi
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    movl %eax, %esi
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %cl
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    movl %eax, %ebx
; X32-NOCMOV-NEXT:    flds {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstps (%esp)
; X32-NOCMOV-NEXT:    calll __truncsfbf2
; X32-NOCMOV-NEXT:    # kill: def $ax killed $ax def $eax
; X32-NOCMOV-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    sete %dl
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    testb $1, %cl
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X32-NOCMOV-NEXT:    movw %si, 14(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X32-NOCMOV-NEXT:    movw %si, 12(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movw %cx, 10(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movw %cx, 8(%eax)
; X32-NOCMOV-NEXT:    movw %dx, 6(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movw %cx, 4(%eax)
; X32-NOCMOV-NEXT:    movw %bx, 2(%eax)
; X32-NOCMOV-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X32-NOCMOV-NEXT:    movw %cx, (%eax)
; X32-NOCMOV-NEXT:    addl $60, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    popl %ebx
; X32-NOCMOV-NEXT:    popl %ebp
; X32-NOCMOV-NEXT:    retl $4
  %result = call <8 x bfloat> @llvm.ct.select.v8bf16(i1 %cond, <8 x bfloat> %a, <8 x bfloat> %b)
  ret <8 x bfloat> %result
}

define float @test_ctselect_f32_nan_inf(i1 %cond) #0 {
; X64-LABEL: test_ctselect_f32_nan_inf:
; X64:       # %bb.0:
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    movl $2143289344, %eax # imm = 0x7FC00000
; X64-NEXT:    movl $2139095040, %ecx # imm = 0x7F800000
; X64-NEXT:    cmovnel %eax, %ecx
; X64-NEXT:    movd %ecx, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_f32_nan_inf:
; X32:       # %bb.0:
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    pushl %eax
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    sete %al
; X32-NEXT:    movl {{\.?LCPI[0-9]+_[0-9]+}}, %ecx
; X32-NEXT:    movl {{\.?LCPI[0-9]+_[0-9]+}}, %edx
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %esi, (%esp)
; X32-NEXT:    flds (%esp)
; X32-NEXT:    addl $4, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_f32_nan_inf:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    pushl %eax
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    movl {{\.?LCPI[0-9]+_[0-9]+}}, %ecx
; X32-NOCMOV-NEXT:    movl {{\.?LCPI[0-9]+_[0-9]+}}, %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, (%esp)
; X32-NOCMOV-NEXT:    flds (%esp)
; X32-NOCMOV-NEXT:    addl $4, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    retl
  %result = call float @llvm.ct.select.f32(i1 %cond, float 0x7FF8000000000000, float 0x7FF0000000000000)
  ret float %result
}

define double @test_ctselect_f64_nan_inf(i1 %cond) #0 {
; X64-LABEL: test_ctselect_f64_nan_inf:
; X64:       # %bb.0:
; X64-NEXT:    testb $1, %dil
; X64-NEXT:    movabsq $9221120237041090560, %rax # imm = 0x7FF8000000000000
; X64-NEXT:    movabsq $9218868437227405312, %rcx # imm = 0x7FF0000000000000
; X64-NEXT:    cmovneq %rax, %rcx
; X64-NEXT:    movq %rcx, %xmm0
; X64-NEXT:    retq
;
; X32-LABEL: test_ctselect_f64_nan_inf:
; X32:       # %bb.0:
; X32-NEXT:    pushl %edi
; X32-NEXT:    pushl %esi
; X32-NEXT:    subl $24, %esp
; X32-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NEXT:    flds {{\.?LCPI[0-9]+_[0-9]+}}
; X32-NEXT:    flds {{\.?LCPI[0-9]+_[0-9]+}}
; X32-NEXT:    sete %al
; X32-NEXT:    fxch %st(1)
; X32-NEXT:    fstpl {{[0-9]+}}(%esp)
; X32-NEXT:    fstpl (%esp)
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl (%esp), %edx
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X32-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NEXT:    BUNDLE
; X32-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X32-NEXT:    fldl {{[0-9]+}}(%esp)
; X32-NEXT:    addl $24, %esp
; X32-NEXT:    popl %esi
; X32-NEXT:    popl %edi
; X32-NEXT:    retl
;
; X32-NOCMOV-LABEL: test_ctselect_f64_nan_inf:
; X32-NOCMOV:       # %bb.0:
; X32-NOCMOV-NEXT:    pushl %edi
; X32-NOCMOV-NEXT:    pushl %esi
; X32-NOCMOV-NEXT:    subl $24, %esp
; X32-NOCMOV-NEXT:    testb $1, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    flds {{\.?LCPI[0-9]+_[0-9]+}}
; X32-NOCMOV-NEXT:    flds {{\.?LCPI[0-9]+_[0-9]+}}
; X32-NOCMOV-NEXT:    sete %al
; X32-NOCMOV-NEXT:    fxch %st(1)
; X32-NOCMOV-NEXT:    fstpl {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fstpl (%esp)
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl (%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X32-NOCMOV-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X32-NOCMOV-NEXT:    BUNDLE
; X32-NOCMOV-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    fldl {{[0-9]+}}(%esp)
; X32-NOCMOV-NEXT:    addl $24, %esp
; X32-NOCMOV-NEXT:    popl %esi
; X32-NOCMOV-NEXT:    popl %edi
; X32-NOCMOV-NEXT:    retl
  %result = call double @llvm.ct.select.f64(i1 %cond, double 0x7FF8000000000000, double 0x7FF0000000000000)
  ret double %result
}

; Declare the intrinsics
declare i1 @llvm.ct.select.i1(i1, i1, i1)
declare i8 @llvm.ct.select.i8(i1, i8, i8)
declare i16 @llvm.ct.select.i16(i1, i16, i16)
declare i32 @llvm.ct.select.i32(i1, i32, i32)
declare i64 @llvm.ct.select.i64(i1, i64, i64)
declare float @llvm.ct.select.f32(i1, float, float)
declare double @llvm.ct.select.f64(i1, double, double)
declare half @llvm.ct.select.f16(i1, half, half)
declare bfloat @llvm.ct.select.bf16(i1, bfloat, bfloat)
declare fp128 @llvm.ct.select.f128(i1, fp128, fp128)
declare x86_fp80 @llvm.ct.select.f80(i1, x86_fp80, x86_fp80)
declare ptr @llvm.ct.select.p0(i1, ptr, ptr)

; Vector intrinsics
declare <4 x i32> @llvm.ct.select.v4i32(i1, <4 x i32>, <4 x i32>)
declare <2 x i64> @llvm.ct.select.v2i64(i1, <2 x i64>, <2 x i64>)
declare <8 x i16> @llvm.ct.select.v8i16(i1, <8 x i16>, <8 x i16>)
declare <16 x i8> @llvm.ct.select.v16i8(i1, <16 x i8>, <16 x i8>)
declare <4 x float> @llvm.ct.select.v4f32(i1, <4 x float>, <4 x float>)
declare <2 x double> @llvm.ct.select.v2f64(i1, <2 x double>, <2 x double>)
declare <8 x i32> @llvm.ct.select.v8i32(i1, <8 x i32>, <8 x i32>)
declare <8 x float> @llvm.ct.select.v8f32(i1, <8 x float>, <8 x float>)
declare <8 x half> @llvm.ct.select.v8f16(i1, <8 x half>, <8 x half>)
declare <8 x bfloat> @llvm.ct.select.v8bf16(i1, <8 x bfloat>, <8 x bfloat>)

attributes #0 = { nounwind }
