; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -combiner-topological-sorting=false | FileCheck %s --check-prefixes=CHECK,DEFAULT
; RUN: llc < %s -mtriple=x86_64-- -combiner-topological-sorting | FileCheck %s --check-prefixes=CHECK,TOPOLOGICAL
; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s --check-prefixes=CHECK,DEFAULT

; Example tests demonstrating current effect of topological sorting on DAG combines.

define i32 @Test_use_divrem_reg_imm(i32 %a) nounwind {
; DEFAULT-LABEL: Test_use_divrem_reg_imm:
; DEFAULT:       # %bb.0:
; DEFAULT-NEXT:    movslq %edi, %rax
; DEFAULT-NEXT:    sarl $31, %edi
; DEFAULT-NEXT:    imulq $1041204193, %rax, %rcx # imm = 0x3E0F83E1
; DEFAULT-NEXT:    sarq $35, %rcx
; DEFAULT-NEXT:    subl %edi, %ecx
; DEFAULT-NEXT:    movl %ecx, %edx
; DEFAULT-NEXT:    shll $5, %edx
; DEFAULT-NEXT:    addl %ecx, %edx
; DEFAULT-NEXT:    subl %edx, %eax
; DEFAULT-NEXT:    addl %ecx, %eax
; DEFAULT-NEXT:    # kill: def $eax killed $eax killed $rax
; DEFAULT-NEXT:    retq
;
; TOPOLOGICAL-LABEL: Test_use_divrem_reg_imm:
; TOPOLOGICAL:       # %bb.0:
; TOPOLOGICAL-NEXT:    movslq %edi, %rax
; TOPOLOGICAL-NEXT:    sarl $31, %edi
; TOPOLOGICAL-NEXT:    imulq $1041204193, %rax, %rcx # imm = 0x3E0F83E1
; TOPOLOGICAL-NEXT:    shrq $35, %rcx
; TOPOLOGICAL-NEXT:    subl %edi, %ecx
; TOPOLOGICAL-NEXT:    shll $5, %ecx
; TOPOLOGICAL-NEXT:    subl %ecx, %eax
; TOPOLOGICAL-NEXT:    # kill: def $eax killed $eax killed $rax
; TOPOLOGICAL-NEXT:    retq
  %resultdiv = sdiv i32 %a, 33
  %resultrem = srem i32 %a, 33
  %result = add i32 %resultdiv, %resultrem
  ret i32 %result
}

define <4 x float> @load_float4_float3_as_float2_float(ptr nocapture readonly dereferenceable(16)) nofree nosync {
; DEFAULT-LABEL: load_float4_float3_as_float2_float:
; DEFAULT:       # %bb.0:
; DEFAULT-NEXT:    movups (%rdi), %xmm0
; DEFAULT-NEXT:    retq
;
; TOPOLOGICAL-LABEL: load_float4_float3_as_float2_float:
; TOPOLOGICAL:       # %bb.0:
; TOPOLOGICAL-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; TOPOLOGICAL-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; TOPOLOGICAL-NEXT:    shufps {{.*#+}} xmm1 = xmm1[0,0],xmm0[3,0]
; TOPOLOGICAL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[0,1],xmm1[0,2]
; TOPOLOGICAL-NEXT:    retq
  %2 = load <2 x float>, ptr %0, align 4
  %3 = extractelement <2 x float> %2, i32 0
  %4 = insertelement <4 x float> undef, float %3, i32 0
  %5 = extractelement <2 x float> %2, i32 1
  %6 = insertelement <4 x float> %4, float %5, i32 1
  %7 = getelementptr inbounds <4 x float>, ptr %0, i64 0, i64 2
  %8 = load float, ptr %7, align 4
  %9 = insertelement <4 x float> %6, float %8, i32 2
  ret <4 x float> %9
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
