; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-unknown -mattr=+avx512bw < %s | FileCheck %s

declare <32 x i16> @llvm.vector.insert.v32i16.v4i16(<32 x i16>, <4 x i16>, i64 immarg)

define <32 x i16> @insert_concat_select(i1 %cond, <16 x i16> %a, <16 x i16> %b, <4 x i16> %sub, <32 x i16> %alt) {
; CHECK-LABEL: insert_concat_select:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    # kill: def $ymm0 killed $ymm0 def $zmm0
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    je .LBB0_2
; CHECK-NEXT:  # %bb.1:
; CHECK-NEXT:    vinserti64x4 $1, %ymm1, %zmm0, %zmm3
; CHECK-NEXT:    vmovd %xmm2, %eax
; CHECK-NEXT:    movl $65536, %ecx # imm = 0x10000
; CHECK-NEXT:    kmovd %ecx, %k1
; CHECK-NEXT:    vpbroadcastw %eax, %zmm3 {%k1}
; CHECK-NEXT:    vpextrw $1, %xmm2, %eax
; CHECK-NEXT:    movl $131072, %ecx # imm = 0x20000
; CHECK-NEXT:    kmovd %ecx, %k1
; CHECK-NEXT:    vpbroadcastw %eax, %zmm3 {%k1}
; CHECK-NEXT:    vpextrw $2, %xmm2, %eax
; CHECK-NEXT:    movl $262144, %ecx # imm = 0x40000
; CHECK-NEXT:    kmovd %ecx, %k1
; CHECK-NEXT:    vpbroadcastw %eax, %zmm3 {%k1}
; CHECK-NEXT:    vpextrw $3, %xmm2, %eax
; CHECK-NEXT:    movl $524288, %ecx # imm = 0x80000
; CHECK-NEXT:    kmovd %ecx, %k1
; CHECK-NEXT:    vpbroadcastw %eax, %zmm3 {%k1}
; CHECK-NEXT:  .LBB0_2: # %entry
; CHECK-NEXT:    vmovdqa64 %zmm3, %zmm0
; CHECK-NEXT:    retq
entry:
  %wide = shufflevector <16 x i16> %a, <16 x i16> %b, <32 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22, i32 23, i32 24, i32 25, i32 26, i32 27, i32 28, i32 29, i32 30, i32 31>
  %ins = call <32 x i16> @llvm.vector.insert.v32i16.v4i16(<32 x i16> %wide, <4 x i16> %sub, i64 16)
  %sel = select i1 %cond, <32 x i16> %ins, <32 x i16> %alt
  ret <32 x i16> %sel
}
