; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-unknown-unknown -mattr=+sse2 < %s | FileCheck %s

declare <2 x i32> @llvm.vector.extract.v2i32.v4i32(<4 x i32>, i64 immarg)

define i32 @freeze_select_scalar_demanded(i1 %c, <2 x i32> %a, <2 x i32> %b, <2 x i32> %d) {
; CHECK-LABEL: freeze_select_scalar_demanded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testb $1, %dil
; CHECK-NEXT:    jne .LBB0_1
; CHECK-NEXT:  # %bb.2:
; CHECK-NEXT:    psubd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm2
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm2[0]
; CHECK-NEXT:    movd %xmm0, %eax
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_1:
; CHECK-NEXT:    paddd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1 # [2147483647,2147483647,u,u]
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; CHECK-NEXT:    movd %xmm0, %eax
; CHECK-NEXT:    retq
  %poisonable.b = add nsw <2 x i32> %b, <i32 2147483647, i32 2147483647>
  %poisonable.d = sub nsw <2 x i32> %d, <i32 -2147483648, i32 -2147483648>
  %lhs = shufflevector <2 x i32> %a, <2 x i32> %poisonable.b, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %rhs = shufflevector <2 x i32> %a, <2 x i32> %poisonable.d, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %sel = select i1 %c, <4 x i32> %lhs, <4 x i32> %rhs
  %fr = freeze <4 x i32> %sel
  %ext = extractelement <4 x i32> %fr, i64 0
  ret i32 %ext
}

define <2 x i32> @freeze_vselect_high_demanded(<4 x i32> %csrc, <2 x i32> %a, <2 x i32> %b, <2 x i32> %e, <2 x i32> %d) {
; CHECK-LABEL: freeze_vselect_high_demanded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movdqa {{.*#+}} xmm5 = [2147483647,2147483647,2147483647,2147483647]
; CHECK-NEXT:    paddd %xmm0, %xmm5
; CHECK-NEXT:    shufps {{.*#+}} xmm5 = xmm5[0,1],xmm0[2,3]
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    pcmpgtd %xmm0, %xmm5
; CHECK-NEXT:    paddd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm2 # [2147483647,2147483647,u,u]
; CHECK-NEXT:    psubd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm4
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm2 = xmm2[0],xmm1[0]
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm4 = xmm4[0],xmm3[0]
; CHECK-NEXT:    pand %xmm5, %xmm2
; CHECK-NEXT:    pandn %xmm4, %xmm5
; CHECK-NEXT:    por %xmm2, %xmm5
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm5[2,3,2,3]
; CHECK-NEXT:    retq
  %poisonable.c.val = add nsw <4 x i32> %csrc, <i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647>
  %poisonable.c = icmp sgt <4 x i32> %poisonable.c.val, zeroinitializer
  %safe.c = icmp sgt <4 x i32> %csrc, zeroinitializer
  %cond = shufflevector <4 x i1> %poisonable.c, <4 x i1> %safe.c, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
  %poisonable.b = add nsw <2 x i32> %b, <i32 2147483647, i32 2147483647>
  %poisonable.d = sub nsw <2 x i32> %d, <i32 -2147483648, i32 -2147483648>
  %lhs = shufflevector <2 x i32> %poisonable.b, <2 x i32> %a, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %rhs = shufflevector <2 x i32> %poisonable.d, <2 x i32> %e, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %sel = select <4 x i1> %cond, <4 x i32> %lhs, <4 x i32> %rhs
  %fr = freeze <4 x i32> %sel
  %ext = call <2 x i32> @llvm.vector.extract.v2i32.v4i32(<4 x i32> %fr, i64 2)
  ret <2 x i32> %ext
}

define i32 @freeze_vselect_demanded(<4 x i32> %csrc, <2 x i32> %a, <2 x i32> %b, <2 x i32> %e, <2 x i32> %d) {
; CHECK-LABEL: freeze_vselect_demanded:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pxor %xmm2, %xmm2
; CHECK-NEXT:    pcmpgtd %xmm2, %xmm0
; CHECK-NEXT:    pand %xmm0, %xmm1
; CHECK-NEXT:    pandn %xmm3, %xmm0
; CHECK-NEXT:    por %xmm1, %xmm0
; CHECK-NEXT:    movd %xmm0, %eax
; CHECK-NEXT:    retq
  %safe.c = icmp sgt <4 x i32> %csrc, zeroinitializer
  %poisonable.c.val = add nsw <4 x i32> %csrc, <i32 2147483647, i32 2147483647, i32 2147483647, i32 2147483647>
  %poisonable.c = icmp sgt <4 x i32> %poisonable.c.val, zeroinitializer
  %cond = shufflevector <4 x i1> %safe.c, <4 x i1> %poisonable.c, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  %poisonable.b = add nsw <2 x i32> %b, <i32 2147483647, i32 2147483647>
  %poisonable.d = sub nsw <2 x i32> %d, <i32 -2147483648, i32 -2147483648>
  %lhs = shufflevector <2 x i32> %a, <2 x i32> %poisonable.b, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %rhs = shufflevector <2 x i32> %e, <2 x i32> %poisonable.d, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %sel = select <4 x i1> %cond, <4 x i32> %lhs, <4 x i32> %rhs
  %fr = freeze <4 x i32> %sel
  %ext = extractelement <4 x i32> %fr, i64 0
  ret i32 %ext
}
