# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=x86_64-unknown-unknown -run-pass=machine-scheduler -verify-misched -o - %s | FileCheck %s

---
name:            vga_load_state
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rdi

    ; CHECK-LABEL: name: vga_load_state
    ; CHECK: liveins: $rdi
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:gr64 = COPY $rdi
    ; CHECK-NEXT: dead undef [[MOV32r0_:%[0-9]+]].sub_32bit:gr64_nosp = MOV32r0 implicit-def dead $eflags
    ; CHECK-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */
    ; CHECK-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */
    ; CHECK-NEXT: dead $eax = MOV32r0 implicit-def dead $eflags, implicit-def $rax
    ; CHECK-NEXT: dead $eax = MOV32r0 implicit-def dead $eflags
    ; CHECK-NEXT: dead $eax = MOV32r0 implicit-def dead $eflags
    ; CHECK-NEXT: dead $eax = MOV32r0 implicit-def dead $eflags, implicit-def $rax
    %0:gr64 = COPY $rdi
    undef %1.sub_32bit:gr64_nosp = MOV32r0 implicit-def dead $eflags
    dead $eax = MOV32r0 implicit-def dead $eflags, implicit-def $rax
    INLINEASM &"", 1 /* sideeffect attdialect */
    dead $eax = MOV32r0 implicit-def dead $eflags
    INLINEASM &"", 1 /* sideeffect attdialect */
    dead $eax = MOV32r0 implicit-def dead $eflags
    dead $eax = MOV32r0 implicit-def dead $eflags, implicit-def $rax

...

