; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-- | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s --check-prefix=X64

define i256 @udiv256(i256 %a, i256 %b) nounwind {
; X86-LABEL: udiv256:
; X86:       # %bb.0: # %_udiv-special-cases
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $288, %esp # imm = 0x120
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    movl 72(%ebp), %ebx
; X86-NEXT:    movl 56(%ebp), %ecx
; X86-NEXT:    orl %ebx, %ecx
; X86-NEXT:    orl 64(%ebp), %eax
; X86-NEXT:    orl %ecx, %eax
; X86-NEXT:    movl 68(%ebp), %edi
; X86-NEXT:    movl 52(%ebp), %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl 44(%ebp), %edx
; X86-NEXT:    orl 60(%ebp), %edx
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    orl %eax, %edx
; X86-NEXT:    sete %al
; X86-NEXT:    movl 24(%ebp), %edx
; X86-NEXT:    orl 40(%ebp), %edx
; X86-NEXT:    movl 16(%ebp), %ecx
; X86-NEXT:    orl 32(%ebp), %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl 20(%ebp), %edx
; X86-NEXT:    orl 36(%ebp), %edx
; X86-NEXT:    movl 12(%ebp), %esi
; X86-NEXT:    orl 28(%ebp), %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    sete %ah
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    jne .LBB0_1
; X86-NEXT:  # %bb.2: # %_udiv-special-cases
; X86-NEXT:    bsrl %edi, %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:    orl $32, %edx
; X86-NEXT:    jmp .LBB0_3
; X86-NEXT:  .LBB0_1:
; X86-NEXT:    bsrl %ebx, %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:  .LBB0_3: # %_udiv-special-cases
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 64(%ebp), %edx
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    movl 56(%ebp), %ebx
; X86-NEXT:    jne .LBB0_4
; X86-NEXT:  # %bb.5: # %_udiv-special-cases
; X86-NEXT:    bsrl 60(%ebp), %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:    orl $32, %edx
; X86-NEXT:    orl 72(%ebp), %edi
; X86-NEXT:    je .LBB0_7
; X86-NEXT:    jmp .LBB0_8
; X86-NEXT:  .LBB0_4:
; X86-NEXT:    bsrl %edx, %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:    orl 72(%ebp), %edi
; X86-NEXT:    jne .LBB0_8
; X86-NEXT:  .LBB0_7: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB0_8: # %_udiv-special-cases
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    movl 52(%ebp), %edi
; X86-NEXT:    movl 44(%ebp), %esi
; X86-NEXT:    jne .LBB0_9
; X86-NEXT:  # %bb.10: # %_udiv-special-cases
; X86-NEXT:    bsrl %edi, %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:    orl $32, %edx
; X86-NEXT:    jmp .LBB0_11
; X86-NEXT:  .LBB0_9:
; X86-NEXT:    bsrl %ebx, %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:  .LBB0_11: # %_udiv-special-cases
; X86-NEXT:    movl 48(%ebp), %ecx
; X86-NEXT:    testl %ecx, %ecx
; X86-NEXT:    jne .LBB0_12
; X86-NEXT:  # %bb.13: # %_udiv-special-cases
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    orl %ebx, %edi
; X86-NEXT:    je .LBB0_15
; X86-NEXT:    jmp .LBB0_16
; X86-NEXT:  .LBB0_12:
; X86-NEXT:    bsrl %ecx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl %ebx, %edi
; X86-NEXT:    jne .LBB0_16
; X86-NEXT:  .LBB0_15: # %_udiv-special-cases
; X86-NEXT:    orl $64, %esi
; X86-NEXT:    movl %esi, %edx
; X86-NEXT:  .LBB0_16: # %_udiv-special-cases
; X86-NEXT:    movl 64(%ebp), %esi
; X86-NEXT:    orl 72(%ebp), %esi
; X86-NEXT:    movl 60(%ebp), %edi
; X86-NEXT:    orl 68(%ebp), %edi
; X86-NEXT:    orl %esi, %edi
; X86-NEXT:    movl 40(%ebp), %ebx
; X86-NEXT:    jne .LBB0_18
; X86-NEXT:  # %bb.17: # %_udiv-special-cases
; X86-NEXT:    orl $128, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB0_18: # %_udiv-special-cases
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    movl 32(%ebp), %esi
; X86-NEXT:    movl 36(%ebp), %edi
; X86-NEXT:    jne .LBB0_19
; X86-NEXT:  # %bb.20: # %_udiv-special-cases
; X86-NEXT:    bsrl %edi, %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:    orl $32, %edx
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    je .LBB0_23
; X86-NEXT:  .LBB0_22:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl %ebx, %edi
; X86-NEXT:    je .LBB0_25
; X86-NEXT:    jmp .LBB0_26
; X86-NEXT:  .LBB0_19:
; X86-NEXT:    bsrl %ebx, %edx
; X86-NEXT:    xorl $31, %edx
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    jne .LBB0_22
; X86-NEXT:  .LBB0_23: # %_udiv-special-cases
; X86-NEXT:    bsrl 28(%ebp), %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    orl %ebx, %edi
; X86-NEXT:    jne .LBB0_26
; X86-NEXT:  .LBB0_25: # %_udiv-special-cases
; X86-NEXT:    orl $64, %esi
; X86-NEXT:    movl %esi, %edx
; X86-NEXT:  .LBB0_26: # %_udiv-special-cases
; X86-NEXT:    movl 24(%ebp), %esi
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    movl 16(%ebp), %edi
; X86-NEXT:    movl 20(%ebp), %ebx
; X86-NEXT:    jne .LBB0_27
; X86-NEXT:  # %bb.28: # %_udiv-special-cases
; X86-NEXT:    bsrl %ebx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    je .LBB0_31
; X86-NEXT:  .LBB0_30:
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl 24(%ebp), %ebx
; X86-NEXT:    je .LBB0_33
; X86-NEXT:    jmp .LBB0_34
; X86-NEXT:  .LBB0_27:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB0_30
; X86-NEXT:  .LBB0_31: # %_udiv-special-cases
; X86-NEXT:    bsrl 12(%ebp), %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    orl 24(%ebp), %ebx
; X86-NEXT:    jne .LBB0_34
; X86-NEXT:  .LBB0_33: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB0_34: # %_udiv-special-cases
; X86-NEXT:    orb %ah, %al
; X86-NEXT:    movb %al, (%esp) # 1-byte Spill
; X86-NEXT:    movl 32(%ebp), %ecx
; X86-NEXT:    orl 40(%ebp), %ecx
; X86-NEXT:    movl 28(%ebp), %edi
; X86-NEXT:    orl 36(%ebp), %edi
; X86-NEXT:    orl %ecx, %edi
; X86-NEXT:    jne .LBB0_36
; X86-NEXT:  # %bb.35: # %_udiv-special-cases
; X86-NEXT:    orl $128, %esi
; X86-NEXT:    movl %esi, %edx
; X86-NEXT:  .LBB0_36: # %_udiv-special-cases
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    subl %edx, %esi
; X86-NEXT:    movl $0, %edi
; X86-NEXT:    sbbl %edi, %edi
; X86-NEXT:    movl $0, %ebx
; X86-NEXT:    sbbl %ebx, %ebx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ecx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edx, %edx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ecx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ecx, %ecx
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    cmpb $0, (%esp) # 1-byte Folded Reload
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB0_37
; X86-NEXT:  # %bb.38: # %select.false.sink
; X86-NEXT:    movl $255, %eax
; X86-NEXT:    cmpl %esi, %eax
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %edi, %eax
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %ebx, %eax
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    sbbl %ebx, %eax
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %ecx, %eax
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl %ecx, %eax
; X86-NEXT:    setb %al
; X86-NEXT:  .LBB0_39: # %select.end
; X86-NEXT:    testb %al, %al
; X86-NEXT:    movl $0, (%esp) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, %edi
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    movl $0, %esi
; X86-NEXT:    jne .LBB0_41
; X86-NEXT:  # %bb.40: # %select.end
; X86-NEXT:    movl 16(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 12(%ebp), %eax
; X86-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-NEXT:    movl 20(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 24(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 28(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 32(%ebp), %edi
; X86-NEXT:    movl 36(%ebp), %eax
; X86-NEXT:    movl 40(%ebp), %esi
; X86-NEXT:  .LBB0_41: # %select.end
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB0_42
; X86-NEXT:  # %bb.48: # %select.end
; X86-NEXT:    movl %ecx, %edi
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    xorl $255, %ecx
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    orl %esi, %ecx
; X86-NEXT:    movl %ebx, %esi
; X86-NEXT:    movl %edi, %ebx
; X86-NEXT:    orl %edi, %esi
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl (%esp), %edi # 4-byte Reload
; X86-NEXT:    je .LBB0_49
; X86-NEXT:  # %bb.46: # %udiv-bb1
; X86-NEXT:    movl 12(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 16(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 20(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 24(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 28(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 32(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 36(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 40(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    notb %cl
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $3, %al
; X86-NEXT:    andb $28, %al
; X86-NEXT:    negb %al
; X86-NEXT:    movsbl %al, %edx
; X86-NEXT:    movl 264(%esp,%edx), %esi
; X86-NEXT:    movl 268(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 260(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 256(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 252(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 248(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 240(%esp,%edx), %eax
; X86-NEXT:    movl 244(%esp,%edx), %edx
; X86-NEXT:    shldl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl %cl, %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shll %cl, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    addl $1, %ecx
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jb .LBB0_47
; X86-NEXT:  # %bb.43: # %udiv-preheader
; X86-NEXT:    movl 12(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 16(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 20(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 24(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 28(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 32(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 36(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 40(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $5, %al
; X86-NEXT:    movzbl %al, %edx
; X86-NEXT:    movl 172(%esp,%edx,4), %edi
; X86-NEXT:    movl 168(%esp,%edx,4), %ebx
; X86-NEXT:    movl %ebx, %esi
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %edi, %esi
; X86-NEXT:    movl %esi, (%esp) # 4-byte Spill
; X86-NEXT:    movl 164(%esp,%edx,4), %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    shrdl %cl, %ebx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 160(%esp,%edx,4), %eax
; X86-NEXT:    movl %eax, %ebx
; X86-NEXT:    shrdl %cl, %esi, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 156(%esp,%edx,4), %esi
; X86-NEXT:    movl %esi, %ebx
; X86-NEXT:    shrdl %cl, %eax, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 152(%esp,%edx,4), %eax
; X86-NEXT:    movl %eax, %ebx
; X86-NEXT:    shrdl %cl, %esi, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 144(%esp,%edx,4), %esi
; X86-NEXT:    movl 148(%esp,%edx,4), %edx
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    shrdl %cl, %eax, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrl %cl, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    # kill: def $cl killed $cl killed $ecx
; X86-NEXT:    shrdl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 44(%ebp), %eax
; X86-NEXT:    addl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 52(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 56(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 60(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 64(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 68(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 72(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    .p2align 4
; X86-NEXT:  .LBB0_44: # %udiv-do-while
; X86-NEXT:    # =>This Inner Loop Header: Depth=1
; X86-NEXT:    movl (%esp), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, (%esp) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %ecx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    orl %edi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    orl %edi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    orl %edi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %eax, %eax
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    cmpl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %esi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl (%esp), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    sarl $31, %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl $1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 72(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 68(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 64(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %ebx
; X86-NEXT:    andl 60(%ebp), %ebx
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:    andl 56(%ebp), %esi
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    andl 52(%ebp), %edx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 48(%ebp), %eax
; X86-NEXT:    andl 44(%ebp), %ecx
; X86-NEXT:    subl %ecx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %ebx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl (%esp), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    adcl $-1, %esi
; X86-NEXT:    adcl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    adcl $-1, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    adcl $-1, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %eax, %ecx
; X86-NEXT:    orl %esi, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edi, %edx
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    orl %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    jne .LBB0_44
; X86-NEXT:  .LBB0_45: # %udiv-loop-exit
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    leal (%esi,%edx,2), %edi
; X86-NEXT:    movl %eax, %edx
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:  .LBB0_49: # %udiv-end
; X86-NEXT:    movl 8(%ebp), %eax
; X86-NEXT:    movl %edi, (%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 4(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 8(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 12(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 16(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 20(%eax)
; X86-NEXT:    movl %edx, 24(%eax)
; X86-NEXT:    movl %esi, 28(%eax)
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
; X86-NEXT:  .LBB0_37:
; X86-NEXT:    movb $1, %al
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    jmp .LBB0_39
; X86-NEXT:  .LBB0_47:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jmp .LBB0_45
; X86-NEXT:  .LBB0_42:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl (%esp), %edi # 4-byte Reload
; X86-NEXT:    jmp .LBB0_49
;
; X64-LABEL: udiv256:
; X64:       # %bb.0: # %_udiv-special-cases
; X64-NEXT:    pushq %rbp
; X64-NEXT:    pushq %r15
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %r13
; X64-NEXT:    pushq %r12
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $88, %rsp
; X64-NEXT:    movq %rdx, %r13
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r15
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r11
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rbx
; X64-NEXT:    movq %rbx, %r10
; X64-NEXT:    orq %r11, %r10
; X64-NEXT:    movq %r9, %rdi
; X64-NEXT:    orq %r15, %rdi
; X64-NEXT:    orq %r10, %rdi
; X64-NEXT:    sete %bpl
; X64-NEXT:    movq %rdx, %rdi
; X64-NEXT:    orq %r8, %rdi
; X64-NEXT:    movq %rsi, %r10
; X64-NEXT:    orq %rcx, %r10
; X64-NEXT:    orq %rdi, %r10
; X64-NEXT:    sete %r10b
; X64-NEXT:    orb %bpl, %r10b
; X64-NEXT:    bsrq %r11, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    bsrq %r15, %r12
; X64-NEXT:    xorq $63, %r12
; X64-NEXT:    orq $64, %r12
; X64-NEXT:    testq %r11, %r11
; X64-NEXT:    cmovneq %rdi, %r12
; X64-NEXT:    bsrq %rbx, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    bsrq %r9, %r14
; X64-NEXT:    xorq $63, %r14
; X64-NEXT:    orq $64, %r14
; X64-NEXT:    testq %rbx, %rbx
; X64-NEXT:    cmovneq %rdi, %r14
; X64-NEXT:    orq $128, %r14
; X64-NEXT:    movq %r15, %rdi
; X64-NEXT:    orq %r11, %rdi
; X64-NEXT:    cmovneq %r12, %r14
; X64-NEXT:    bsrq %r8, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    bsrq %rcx, %r9
; X64-NEXT:    xorq $63, %r9
; X64-NEXT:    orq $64, %r9
; X64-NEXT:    testq %r8, %r8
; X64-NEXT:    cmovneq %rdi, %r9
; X64-NEXT:    bsrq %rdx, %r11
; X64-NEXT:    xorq $63, %r11
; X64-NEXT:    bsrq %rsi, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    orq $64, %rdi
; X64-NEXT:    testq %rdx, %rdx
; X64-NEXT:    cmovneq %r11, %rdi
; X64-NEXT:    orq $128, %rdi
; X64-NEXT:    movq %rcx, %r11
; X64-NEXT:    orq %r8, %r11
; X64-NEXT:    cmovneq %r9, %rdi
; X64-NEXT:    xorl %ebx, %ebx
; X64-NEXT:    subq %rdi, %r14
; X64-NEXT:    movl $0, %r12d
; X64-NEXT:    sbbq %r12, %r12
; X64-NEXT:    movl $0, %ebp
; X64-NEXT:    sbbq %rbp, %rbp
; X64-NEXT:    sbbq %rbx, %rbx
; X64-NEXT:    movq %rcx, %r15
; X64-NEXT:    testb %r10b, %r10b
; X64-NEXT:    jne .LBB0_1
; X64-NEXT:  # %bb.2: # %select.false.sink
; X64-NEXT:    xorl %edi, %edi
; X64-NEXT:    movl $255, %ecx
; X64-NEXT:    cmpq %r14, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    sbbq %r12, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    sbbq %rbp, %rcx
; X64-NEXT:    sbbq %rbx, %rdi
; X64-NEXT:    setb %cl
; X64-NEXT:  .LBB0_3: # %select.end
; X64-NEXT:    xorl %r10d, %r10d
; X64-NEXT:    testb %cl, %cl
; X64-NEXT:    movq %r13, %r9
; X64-NEXT:    cmovneq %r10, %r13
; X64-NEXT:    movq %rsi, %r11
; X64-NEXT:    cmovneq %r10, %r11
; X64-NEXT:    movq %r15, %rdx
; X64-NEXT:    cmovneq %r10, %rdx
; X64-NEXT:    cmoveq %r8, %r10
; X64-NEXT:    jne .LBB0_9
; X64-NEXT:  # %bb.4: # %select.end
; X64-NEXT:    movq %r14, %rcx
; X64-NEXT:    xorq $255, %rcx
; X64-NEXT:    orq %rbp, %rcx
; X64-NEXT:    movq %r12, %rdi
; X64-NEXT:    orq %rbx, %rdi
; X64-NEXT:    orq %rcx, %rdi
; X64-NEXT:    je .LBB0_9
; X64-NEXT:  # %bb.5: # %udiv-bb1
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rsi, {{[0-9]+}}(%rsp)
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r9, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r15, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r14d, %ecx
; X64-NEXT:    notb %cl
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    shrb $3, %al
; X64-NEXT:    andb $24, %al
; X64-NEXT:    negb %al
; X64-NEXT:    movsbq %al, %rdx
; X64-NEXT:    movq 64(%rsp,%rdx), %rdi
; X64-NEXT:    movq 72(%rsp,%rdx), %rax
; X64-NEXT:    shldq %cl, %rdi, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq 48(%rsp,%rdx), %rax
; X64-NEXT:    movq 56(%rsp,%rdx), %r11
; X64-NEXT:    shldq %cl, %r11, %rdi
; X64-NEXT:    movq %rdi, %rdx
; X64-NEXT:    shldq %cl, %rax, %r11
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shlq %cl, %rax
; X64-NEXT:    addq $1, %r14
; X64-NEXT:    adcq $0, %r12
; X64-NEXT:    adcq $0, %rbp
; X64-NEXT:    adcq $0, %rbx
; X64-NEXT:    jb .LBB0_10
; X64-NEXT:  # %bb.6: # %udiv-preheader
; X64-NEXT:    movq %r12, %r10
; X64-NEXT:    movq %rbx, %r12
; X64-NEXT:    movaps %xmm0, (%rsp)
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r9, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r15, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r14d, %ecx
; X64-NEXT:    shrb $6, %cl
; X64-NEXT:    movzbl %cl, %edi
; X64-NEXT:    movq -24(%rsp,%rdi,8), %rsi
; X64-NEXT:    movq %r14, %rcx
; X64-NEXT:    movq -32(%rsp,%rdi,8), %r14
; X64-NEXT:    movq %r14, %r8
; X64-NEXT:    shrdq %cl, %rsi, %r8
; X64-NEXT:    movq -48(%rsp,%rdi,8), %r11
; X64-NEXT:    movq -40(%rsp,%rdi,8), %rdi
; X64-NEXT:    movq %rdi, %rbx
; X64-NEXT:    shrdq %cl, %r14, %rbx
; X64-NEXT:    shrq %cl, %rsi
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    # kill: def $cl killed $cl killed $rcx
; X64-NEXT:    shrdq %cl, %rdi, %r11
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    addq $-1, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    adcq $-1, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    adcq $-1, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    adcq $-1, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    xorl %r15d, %r15d
; X64-NEXT:    xorl %r14d, %r14d
; X64-NEXT:    xorl %edi, %edi
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r10, %r12
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    .p2align 4
; X64-NEXT:  .LBB0_7: # %udiv-do-while
; X64-NEXT:    # =>This Inner Loop Header: Depth=1
; X64-NEXT:    shldq $1, %r8, %rsi
; X64-NEXT:    shldq $1, %rbx, %r8
; X64-NEXT:    shldq $1, %r11, %rbx
; X64-NEXT:    shldq $1, %r10, %r11
; X64-NEXT:    shldq $1, %rdx, %r10
; X64-NEXT:    orq %rdi, %r10
; X64-NEXT:    shldq $1, %r13, %rdx
; X64-NEXT:    orq %r14, %rdx
; X64-NEXT:    shldq $1, %rax, %r13
; X64-NEXT:    orq %r15, %r13
; X64-NEXT:    addq %rax, %rax
; X64-NEXT:    orq %rcx, %rax
; X64-NEXT:    cmpq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Folded Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    sbbq %rbx, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    sbbq %r8, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; X64-NEXT:    sbbq %rsi, %rdi
; X64-NEXT:    sarq $63, %rdi
; X64-NEXT:    movl %edi, %ecx
; X64-NEXT:    andl $1, %ecx
; X64-NEXT:    movq %rdi, %r9
; X64-NEXT:    andq {{[0-9]+}}(%rsp), %r9
; X64-NEXT:    movq %rdi, %r14
; X64-NEXT:    andq {{[0-9]+}}(%rsp), %r14
; X64-NEXT:    movq %rdi, %r15
; X64-NEXT:    andq {{[0-9]+}}(%rsp), %r15
; X64-NEXT:    andq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Folded Reload
; X64-NEXT:    subq %rdi, %r11
; X64-NEXT:    sbbq %r15, %rbx
; X64-NEXT:    sbbq %r14, %r8
; X64-NEXT:    sbbq %r9, %rsi
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; X64-NEXT:    addq $-1, %r9
; X64-NEXT:    adcq $-1, %r12
; X64-NEXT:    adcq $-1, %rbp
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; X64-NEXT:    adcq $-1, %r14
; X64-NEXT:    movq %r12, %rdi
; X64-NEXT:    movq %r14, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r14, %rdi
; X64-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %rbp, %r9
; X64-NEXT:    orq %rdi, %r9
; X64-NEXT:    movl $0, %r15d
; X64-NEXT:    movl $0, %r14d
; X64-NEXT:    movl $0, %edi
; X64-NEXT:    jne .LBB0_7
; X64-NEXT:  .LBB0_8: # %udiv-loop-exit
; X64-NEXT:    shldq $1, %rdx, %r10
; X64-NEXT:    shldq $1, %r13, %rdx
; X64-NEXT:    shldq $1, %rax, %r13
; X64-NEXT:    leaq (%rcx,%rax,2), %r11
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:  .LBB0_9: # %udiv-end
; X64-NEXT:    movq %r11, (%rax)
; X64-NEXT:    movq %r13, 8(%rax)
; X64-NEXT:    movq %rdx, 16(%rax)
; X64-NEXT:    movq %r10, 24(%rax)
; X64-NEXT:    addq $88, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r12
; X64-NEXT:    popq %r13
; X64-NEXT:    popq %r14
; X64-NEXT:    popq %r15
; X64-NEXT:    popq %rbp
; X64-NEXT:    retq
; X64-NEXT:  .LBB0_1:
; X64-NEXT:    movb $1, %cl
; X64-NEXT:    jmp .LBB0_3
; X64-NEXT:  .LBB0_10:
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    jmp .LBB0_8
  %r = udiv i256 %a, %b
  ret i256 %r
}

define i256 @sdiv256(i256 %a, i256 %b) nounwind {
; X86-LABEL: sdiv256:
; X86:       # %bb.0: # %_udiv-special-cases
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $320, %esp # imm = 0x140
; X86-NEXT:    movl 40(%ebp), %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    sarl $31, %eax
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 36(%ebp), %edx
; X86-NEXT:    xorl %eax, %edx
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    movl 32(%ebp), %edx
; X86-NEXT:    xorl %eax, %edx
; X86-NEXT:    movl 28(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 24(%ebp), %esi
; X86-NEXT:    xorl %eax, %esi
; X86-NEXT:    movl %esi, %ebx
; X86-NEXT:    movl 20(%ebp), %esi
; X86-NEXT:    xorl %eax, %esi
; X86-NEXT:    movl 16(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl 12(%ebp), %edi
; X86-NEXT:    xorl %eax, %edi
; X86-NEXT:    subl %eax, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, (%esp) # 4-byte Folded Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl 72(%ebp), %eax
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    sarl $31, %ecx
; X86-NEXT:    xorl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 68(%ebp), %eax
; X86-NEXT:    xorl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 64(%ebp), %ebx
; X86-NEXT:    xorl %ecx, %ebx
; X86-NEXT:    movl 60(%ebp), %eax
; X86-NEXT:    xorl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 56(%ebp), %edx
; X86-NEXT:    xorl %ecx, %edx
; X86-NEXT:    movl 52(%ebp), %edi
; X86-NEXT:    xorl %ecx, %edi
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    xorl %ecx, %eax
; X86-NEXT:    movl 44(%ebp), %esi
; X86-NEXT:    xorl %ecx, %esi
; X86-NEXT:    subl %ecx, %esi
; X86-NEXT:    sbbl %ecx, %eax
; X86-NEXT:    sbbl %ecx, %edi
; X86-NEXT:    sbbl %ecx, %edx
; X86-NEXT:    sbbl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %ecx, %ebx
; X86-NEXT:    sbbl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ebx, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    orl %ebx, %edx
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    orl %edi, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    sete %cl
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    orl %edi, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl (%esp), %edx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    orl %eax, %edi
; X86-NEXT:    orl %edx, %edi
; X86-NEXT:    movl %ebx, %edx
; X86-NEXT:    orl %esi, %edi
; X86-NEXT:    sete %ch
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    jne .LBB1_1
; X86-NEXT:  # %bb.2: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    bsrl %esi, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    orl $32, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    jmp .LBB1_3
; X86-NEXT:  .LBB1_1:
; X86-NEXT:    bsrl %edx, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:  .LBB1_3: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    jne .LBB1_4
; X86-NEXT:  # %bb.5: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    jmp .LBB1_6
; X86-NEXT:  .LBB1_4:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:  .LBB1_6: # %_udiv-special-cases
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    orl %edx, %edi
; X86-NEXT:    jne .LBB1_8
; X86-NEXT:  # %bb.7: # %_udiv-special-cases
; X86-NEXT:    orl $64, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB1_8: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    jne .LBB1_9
; X86-NEXT:  # %bb.10: # %_udiv-special-cases
; X86-NEXT:    bsrl %ebx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    je .LBB1_13
; X86-NEXT:  .LBB1_12:
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    je .LBB1_15
; X86-NEXT:    jmp .LBB1_16
; X86-NEXT:  .LBB1_9:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB1_12
; X86-NEXT:  .LBB1_13: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    jne .LBB1_16
; X86-NEXT:  .LBB1_15: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB1_16: # %_udiv-special-cases
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    orl %edi, %ebx
; X86-NEXT:    jne .LBB1_18
; X86-NEXT:  # %bb.17: # %_udiv-special-cases
; X86-NEXT:    orl $128, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB1_18: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    testl %eax, %eax
; X86-NEXT:    movl (%esp), %ebx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    jne .LBB1_19
; X86-NEXT:  # %bb.20: # %_udiv-special-cases
; X86-NEXT:    bsrl %ebx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    je .LBB1_23
; X86-NEXT:  .LBB1_22:
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl %eax, %ebx
; X86-NEXT:    je .LBB1_25
; X86-NEXT:    jmp .LBB1_26
; X86-NEXT:  .LBB1_19:
; X86-NEXT:    bsrl %eax, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB1_22
; X86-NEXT:  .LBB1_23: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    orl %eax, %ebx
; X86-NEXT:    jne .LBB1_26
; X86-NEXT:  .LBB1_25: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB1_26: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    jne .LBB1_27
; X86-NEXT:  # %bb.28: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    je .LBB1_31
; X86-NEXT:  .LBB1_30:
; X86-NEXT:    bsrl %ebx, %ebx
; X86-NEXT:    xorl $31, %ebx
; X86-NEXT:    jmp .LBB1_32
; X86-NEXT:  .LBB1_27:
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    jne .LBB1_30
; X86-NEXT:  .LBB1_31: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %ebx
; X86-NEXT:    orl $32, %ebx
; X86-NEXT:  .LBB1_32: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    jne .LBB1_34
; X86-NEXT:  # %bb.33: # %_udiv-special-cases
; X86-NEXT:    orl $64, %ebx
; X86-NEXT:    movl %ebx, %edi
; X86-NEXT:  .LBB1_34: # %_udiv-special-cases
; X86-NEXT:    orb %ch, %cl
; X86-NEXT:    movb %cl, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl (%esp), %edx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    orl %eax, %ebx
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    jne .LBB1_36
; X86-NEXT:  # %bb.35: # %_udiv-special-cases
; X86-NEXT:    orl $128, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB1_36: # %_udiv-special-cases
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    subl %esi, %edx
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %esi
; X86-NEXT:    sbbl %esi, %esi
; X86-NEXT:    movl $0, %edi
; X86-NEXT:    sbbl %edi, %edi
; X86-NEXT:    movl $0, %ebx
; X86-NEXT:    sbbl %ebx, %ebx
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ecx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    cmpb $0, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB1_37
; X86-NEXT:  # %bb.38: # %select.false.sink
; X86-NEXT:    movl $255, %ecx
; X86-NEXT:    cmpl %edx, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %esi, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %edi, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ebx, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    setb %cl
; X86-NEXT:  .LBB1_39: # %select.end
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl (%esp), %ebx # 4-byte Reload
; X86-NEXT:    xorl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    testb %cl, %cl
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, %esi
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    jne .LBB1_41
; X86-NEXT:  # %bb.40: # %select.end
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:  .LBB1_41: # %select.end
; X86-NEXT:    movl %ebx, (%esp) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    jne .LBB1_42
; X86-NEXT:  # %bb.48: # %select.end
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %ecx
; X86-NEXT:    xorl $255, %ecx
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl %eax, %edx
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    je .LBB1_49
; X86-NEXT:  # %bb.46: # %udiv-bb1
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl (%esp), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ebx, %ecx
; X86-NEXT:    notb %cl
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $3, %al
; X86-NEXT:    andb $28, %al
; X86-NEXT:    negb %al
; X86-NEXT:    movsbl %al, %edx
; X86-NEXT:    movl 296(%esp,%edx), %esi
; X86-NEXT:    movl 300(%esp,%edx), %edi
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 292(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 288(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 284(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 280(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 272(%esp,%edx), %edi
; X86-NEXT:    movl (%esp), %ebx # 4-byte Reload
; X86-NEXT:    movl 276(%esp,%edx), %edx
; X86-NEXT:    shldl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl %cl, %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shll %cl, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl $1, %ecx
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jb .LBB1_47
; X86-NEXT:  # %bb.43: # %udiv-preheader
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ebx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $5, %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    movl 204(%esp,%eax,4), %edi
; X86-NEXT:    movl 200(%esp,%eax,4), %edx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %edi, %esi
; X86-NEXT:    movl %esi, (%esp) # 4-byte Spill
; X86-NEXT:    movl 196(%esp,%eax,4), %ebx
; X86-NEXT:    movl %ebx, %esi
; X86-NEXT:    shrdl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 192(%esp,%eax,4), %esi
; X86-NEXT:    movl %esi, %edx
; X86-NEXT:    shrdl %cl, %ebx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 188(%esp,%eax,4), %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 184(%esp,%eax,4), %esi
; X86-NEXT:    movl %esi, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shrdl %cl, %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 176(%esp,%eax,4), %edx
; X86-NEXT:    movl 180(%esp,%eax,4), %eax
; X86-NEXT:    movl %eax, %ebx
; X86-NEXT:    shrdl %cl, %esi, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrl %cl, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    # kill: def $cl killed $cl killed $ecx
; X86-NEXT:    shrdl %cl, %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    addl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    .p2align 4
; X86-NEXT:  .LBB1_44: # %udiv-do-while
; X86-NEXT:    # =>This Inner Loop Header: Depth=1
; X86-NEXT:    movl (%esp), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %ecx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    orl %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %esi
; X86-NEXT:    orl %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %esi
; X86-NEXT:    orl %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    orl %edi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %ecx, %ecx
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    cmpl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl (%esp), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    sarl $31, %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl $1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %ebx
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, %edi
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    subl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %esi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %edi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %ebx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl (%esp), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    adcl $-1, %edx
; X86-NEXT:    adcl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    adcl $-1, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    adcl $-1, %esi
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edi, %edx
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %esi, %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %eax, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ebx, %edx
; X86-NEXT:    orl %esi, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    jne .LBB1_44
; X86-NEXT:  .LBB1_45: # %udiv-loop-exit
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %eax, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    leal (%ebx,%edi,2), %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl %ecx, %ebx
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    movl %ebx, %edx
; X86-NEXT:  .LBB1_49: # %udiv-end
; X86-NEXT:    xorl %edi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    xorl %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    xorl %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    xorl %edi, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    xorl %edi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    xorl %edi, %edx
; X86-NEXT:    xorl %edi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    xorl %edi, %ecx
; X86-NEXT:    subl %edi, %ecx
; X86-NEXT:    sbbl %edi, %eax
; X86-NEXT:    sbbl %edi, %edx
; X86-NEXT:    sbbl %edi, %esi
; X86-NEXT:    sbbl %edi, %ebx
; X86-NEXT:    sbbl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    movl 8(%ebp), %eax
; X86-NEXT:    movl %ecx, (%eax)
; X86-NEXT:    movl %edi, 4(%eax)
; X86-NEXT:    movl %edx, 8(%eax)
; X86-NEXT:    movl %esi, 12(%eax)
; X86-NEXT:    movl %ebx, 16(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 20(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 24(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, 28(%eax)
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
; X86-NEXT:  .LBB1_37:
; X86-NEXT:    movb $1, %cl
; X86-NEXT:    jmp .LBB1_39
; X86-NEXT:  .LBB1_47:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jmp .LBB1_45
; X86-NEXT:  .LBB1_42:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    jmp .LBB1_49
;
; X64-LABEL: sdiv256:
; X64:       # %bb.0: # %_udiv-special-cases
; X64-NEXT:    pushq %rbp
; X64-NEXT:    pushq %r15
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %r13
; X64-NEXT:    pushq %r12
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $120, %rsp
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r12
; X64-NEXT:    movq %r8, %r15
; X64-NEXT:    sarq $63, %r15
; X64-NEXT:    xorq %r15, %r8
; X64-NEXT:    xorq %r15, %rcx
; X64-NEXT:    xorq %r15, %rdx
; X64-NEXT:    xorq %r15, %rsi
; X64-NEXT:    subq %r15, %rsi
; X64-NEXT:    sbbq %r15, %rdx
; X64-NEXT:    sbbq %r15, %rcx
; X64-NEXT:    sbbq %r15, %r8
; X64-NEXT:    movq %r12, %r11
; X64-NEXT:    sarq $63, %r11
; X64-NEXT:    xorq %r11, %r12
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rax
; X64-NEXT:    xorq %r11, %rax
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rbx
; X64-NEXT:    xorq %r11, %rbx
; X64-NEXT:    xorq %r11, %r9
; X64-NEXT:    subq %r11, %r9
; X64-NEXT:    sbbq %r11, %rbx
; X64-NEXT:    sbbq %r11, %rax
; X64-NEXT:    sbbq %r11, %r12
; X64-NEXT:    movq %rbx, %r10
; X64-NEXT:    orq %r12, %r10
; X64-NEXT:    movq %r9, %rdi
; X64-NEXT:    orq %rax, %rdi
; X64-NEXT:    orq %r10, %rdi
; X64-NEXT:    sete %dil
; X64-NEXT:    movq %rdx, %r10
; X64-NEXT:    orq %r8, %r10
; X64-NEXT:    movq %rsi, %r14
; X64-NEXT:    orq %rcx, %r14
; X64-NEXT:    orq %r10, %r14
; X64-NEXT:    sete %bpl
; X64-NEXT:    orb %dil, %bpl
; X64-NEXT:    bsrq %r12, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    bsrq %rax, %r10
; X64-NEXT:    xorq $63, %r10
; X64-NEXT:    orq $64, %r10
; X64-NEXT:    testq %r12, %r12
; X64-NEXT:    cmovneq %rdi, %r10
; X64-NEXT:    bsrq %rbx, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    bsrq %r9, %r14
; X64-NEXT:    xorq $63, %r14
; X64-NEXT:    orq $64, %r14
; X64-NEXT:    movq %rbx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    testq %rbx, %rbx
; X64-NEXT:    cmovneq %rdi, %r14
; X64-NEXT:    orq $128, %r14
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rax, %rdi
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r12, %rdi
; X64-NEXT:    cmovneq %r10, %r14
; X64-NEXT:    bsrq %r8, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    bsrq %rcx, %r9
; X64-NEXT:    xorq $63, %r9
; X64-NEXT:    orq $64, %r9
; X64-NEXT:    testq %r8, %r8
; X64-NEXT:    cmovneq %rdi, %r9
; X64-NEXT:    bsrq %rdx, %rax
; X64-NEXT:    xorq $63, %rax
; X64-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    bsrq %rsi, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    orq $64, %rdi
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    testq %rdx, %rdx
; X64-NEXT:    cmovneq %rax, %rdi
; X64-NEXT:    orq $128, %rdi
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rcx, %rax
; X64-NEXT:    orq %r8, %rax
; X64-NEXT:    cmovneq %r9, %rdi
; X64-NEXT:    xorl %ebx, %ebx
; X64-NEXT:    subq %rdi, %r14
; X64-NEXT:    movl $0, %r12d
; X64-NEXT:    sbbq %r12, %r12
; X64-NEXT:    movl $0, %r10d
; X64-NEXT:    sbbq %r10, %r10
; X64-NEXT:    sbbq %rbx, %rbx
; X64-NEXT:    testb %bpl, %bpl
; X64-NEXT:    jne .LBB1_1
; X64-NEXT:  # %bb.2: # %select.false.sink
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    movl $255, %esi
; X64-NEXT:    cmpq %r14, %rsi
; X64-NEXT:    movl $0, %esi
; X64-NEXT:    sbbq %r12, %rsi
; X64-NEXT:    movl $0, %esi
; X64-NEXT:    sbbq %r10, %rsi
; X64-NEXT:    sbbq %rbx, %rdx
; X64-NEXT:    setb %dl
; X64-NEXT:  .LBB1_3: # %select.end
; X64-NEXT:    xorq %r15, %r11
; X64-NEXT:    xorl %ebp, %ebp
; X64-NEXT:    testb %dl, %dl
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Reload
; X64-NEXT:    cmovneq %rbp, %r15
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    cmovneq %rbp, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    cmovneq %rbp, %rdx
; X64-NEXT:    cmoveq %r8, %rbp
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    jne .LBB1_4
; X64-NEXT:  # %bb.10: # %select.end
; X64-NEXT:    movq %r14, %rsi
; X64-NEXT:    xorq $255, %rsi
; X64-NEXT:    orq %r10, %rsi
; X64-NEXT:    movq %r12, %rdi
; X64-NEXT:    orq %rbx, %rdi
; X64-NEXT:    orq %rsi, %rdi
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    je .LBB1_11
; X64-NEXT:  # %bb.8: # %udiv-bb1
; X64-NEXT:    movq %r8, %r9
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    movq %rcx, %rax
; X64-NEXT:    movq %rcx, {{[0-9]+}}(%rsp)
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Reload
; X64-NEXT:    movq %r15, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; X64-NEXT:    movq %r8, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r9, %r11
; X64-NEXT:    movq %r9, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r14d, %ecx
; X64-NEXT:    notb %cl
; X64-NEXT:    movl %ecx, %edx
; X64-NEXT:    shrb $3, %dl
; X64-NEXT:    andb $24, %dl
; X64-NEXT:    negb %dl
; X64-NEXT:    movsbq %dl, %rdx
; X64-NEXT:    movq 96(%rsp,%rdx), %rsi
; X64-NEXT:    movq 104(%rsp,%rdx), %rdi
; X64-NEXT:    shldq %cl, %rsi, %rdi
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq 80(%rsp,%rdx), %r9
; X64-NEXT:    movq 88(%rsp,%rdx), %rdi
; X64-NEXT:    shldq %cl, %rdi, %rsi
; X64-NEXT:    movq %rsi, %rdx
; X64-NEXT:    shldq %cl, %r9, %rdi
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shlq %cl, %r9
; X64-NEXT:    addq $1, %r14
; X64-NEXT:    adcq $0, %r12
; X64-NEXT:    adcq $0, %r10
; X64-NEXT:    movq %r10, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    adcq $0, %rbx
; X64-NEXT:    jb .LBB1_9
; X64-NEXT:  # %bb.5: # %udiv-preheader
; X64-NEXT:    movq %rbx, %rbp
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r15, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, (%rsp)
; X64-NEXT:    movq %r11, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r14d, %ecx
; X64-NEXT:    shrb $6, %cl
; X64-NEXT:    movzbl %cl, %edi
; X64-NEXT:    movq 8(%rsp,%rdi,8), %r8
; X64-NEXT:    movq %r14, %rcx
; X64-NEXT:    movq (%rsp,%rdi,8), %r14
; X64-NEXT:    movq %r14, %rsi
; X64-NEXT:    shrdq %cl, %r8, %rsi
; X64-NEXT:    movq -16(%rsp,%rdi,8), %rbx
; X64-NEXT:    movq -8(%rsp,%rdi,8), %rdi
; X64-NEXT:    movq %rdi, %r10
; X64-NEXT:    shrdq %cl, %r14, %r10
; X64-NEXT:    shrq %cl, %r8
; X64-NEXT:    shrdq %cl, %rdi, %rbx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; X64-NEXT:    addq $-1, %r11
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; X64-NEXT:    adcq $-1, %r11
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r13, %r11
; X64-NEXT:    adcq $-1, %r11
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; X64-NEXT:    adcq $-1, %r11
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    xorl %r11d, %r11d
; X64-NEXT:    xorl %r14d, %r14d
; X64-NEXT:    xorl %r15d, %r15d
; X64-NEXT:    xorl %edi, %edi
; X64-NEXT:    movq %rbp, %rax
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; X64-NEXT:    .p2align 4
; X64-NEXT:  .LBB1_6: # %udiv-do-while
; X64-NEXT:    # =>This Inner Loop Header: Depth=1
; X64-NEXT:    shldq $1, %rsi, %r8
; X64-NEXT:    shldq $1, %r10, %rsi
; X64-NEXT:    shldq $1, %rbx, %r10
; X64-NEXT:    shldq $1, %rbp, %rbx
; X64-NEXT:    shldq $1, %rdx, %rbp
; X64-NEXT:    orq %rdi, %rbp
; X64-NEXT:    shldq $1, %r12, %rdx
; X64-NEXT:    orq %r15, %rdx
; X64-NEXT:    shldq $1, %r9, %r12
; X64-NEXT:    orq %r14, %r12
; X64-NEXT:    addq %r9, %r9
; X64-NEXT:    orq %r11, %r9
; X64-NEXT:    cmpq %rbx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Folded Reload
; X64-NEXT:    movq %rax, %r15
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    sbbq %r10, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    sbbq %rsi, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; X64-NEXT:    sbbq %r8, %rdi
; X64-NEXT:    sarq $63, %rdi
; X64-NEXT:    movl %edi, %r11d
; X64-NEXT:    andl $1, %r11d
; X64-NEXT:    movq %rdi, %r14
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    andq %rax, %r14
; X64-NEXT:    movq %r15, %rax
; X64-NEXT:    movq %rdi, %r15
; X64-NEXT:    andq %r13, %r15
; X64-NEXT:    movq %rdi, %r13
; X64-NEXT:    andq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Folded Reload
; X64-NEXT:    andq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Folded Reload
; X64-NEXT:    subq %rdi, %rbx
; X64-NEXT:    sbbq %r13, %r10
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    sbbq %r15, %rsi
; X64-NEXT:    sbbq %r14, %r8
; X64-NEXT:    addq $-1, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; X64-NEXT:    adcq $-1, %rdi
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Reload
; X64-NEXT:    adcq $-1, %r15
; X64-NEXT:    adcq $-1, %rax
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %rax, %rdi
; X64-NEXT:    movq %rcx, %r14
; X64-NEXT:    movq %r15, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r15, %r14
; X64-NEXT:    orq %rdi, %r14
; X64-NEXT:    movl $0, %r14d
; X64-NEXT:    movl $0, %r15d
; X64-NEXT:    movl $0, %edi
; X64-NEXT:    jne .LBB1_6
; X64-NEXT:  .LBB1_7: # %udiv-loop-exit
; X64-NEXT:    shldq $1, %rdx, %rbp
; X64-NEXT:    shldq $1, %r12, %rdx
; X64-NEXT:    shldq $1, %r9, %r12
; X64-NEXT:    leaq (%r11,%r9,2), %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; X64-NEXT:    movq %r12, %r15
; X64-NEXT:  .LBB1_11: # %udiv-end
; X64-NEXT:    xorq %r11, %rbp
; X64-NEXT:    xorq %r11, %rdx
; X64-NEXT:    xorq %r11, %r15
; X64-NEXT:    xorq %r11, %rcx
; X64-NEXT:    subq %r11, %rcx
; X64-NEXT:    sbbq %r11, %r15
; X64-NEXT:    sbbq %r11, %rdx
; X64-NEXT:    sbbq %r11, %rbp
; X64-NEXT:    movq %rcx, (%rax)
; X64-NEXT:    movq %r15, 8(%rax)
; X64-NEXT:    movq %rdx, 16(%rax)
; X64-NEXT:    movq %rbp, 24(%rax)
; X64-NEXT:    addq $120, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r12
; X64-NEXT:    popq %r13
; X64-NEXT:    popq %r14
; X64-NEXT:    popq %r15
; X64-NEXT:    popq %rbp
; X64-NEXT:    retq
; X64-NEXT:  .LBB1_1:
; X64-NEXT:    movb $1, %dl
; X64-NEXT:    jmp .LBB1_3
; X64-NEXT:  .LBB1_9:
; X64-NEXT:    xorl %r11d, %r11d
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; X64-NEXT:    jmp .LBB1_7
; X64-NEXT:  .LBB1_4:
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    jmp .LBB1_11
  %r = sdiv i256 %a, %b
  ret i256 %r
}

define i256 @urem256(i256 %a, i256 %b) nounwind {
; X86-LABEL: urem256:
; X86:       # %bb.0: # %_udiv-special-cases
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $288, %esp # imm = 0x120
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    movl 72(%ebp), %edi
; X86-NEXT:    movl 56(%ebp), %ecx
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    orl 64(%ebp), %eax
; X86-NEXT:    orl %ecx, %eax
; X86-NEXT:    movl 68(%ebp), %ebx
; X86-NEXT:    movl 52(%ebp), %ecx
; X86-NEXT:    orl %ebx, %ecx
; X86-NEXT:    movl 44(%ebp), %edx
; X86-NEXT:    orl 60(%ebp), %edx
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    orl %eax, %edx
; X86-NEXT:    sete %cl
; X86-NEXT:    movl 24(%ebp), %edx
; X86-NEXT:    orl 40(%ebp), %edx
; X86-NEXT:    movl 16(%ebp), %eax
; X86-NEXT:    orl 32(%ebp), %eax
; X86-NEXT:    orl %edx, %eax
; X86-NEXT:    movl 20(%ebp), %edx
; X86-NEXT:    orl 36(%ebp), %edx
; X86-NEXT:    movl 12(%ebp), %esi
; X86-NEXT:    orl 28(%ebp), %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    orl %eax, %esi
; X86-NEXT:    sete %ch
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB2_1
; X86-NEXT:  # %bb.2: # %_udiv-special-cases
; X86-NEXT:    bsrl %ebx, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    orl $32, %eax
; X86-NEXT:    jmp .LBB2_3
; X86-NEXT:  .LBB2_1:
; X86-NEXT:    bsrl %edi, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:  .LBB2_3: # %_udiv-special-cases
; X86-NEXT:    movl 64(%ebp), %esi
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    movl 40(%ebp), %edx
; X86-NEXT:    jne .LBB2_4
; X86-NEXT:  # %bb.5: # %_udiv-special-cases
; X86-NEXT:    bsrl 60(%ebp), %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    orl 72(%ebp), %ebx
; X86-NEXT:    je .LBB2_7
; X86-NEXT:    jmp .LBB2_8
; X86-NEXT:  .LBB2_4:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl 72(%ebp), %ebx
; X86-NEXT:    jne .LBB2_8
; X86-NEXT:  .LBB2_7: # %_udiv-special-cases
; X86-NEXT:    orl $64, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB2_8: # %_udiv-special-cases
; X86-NEXT:    movl 56(%ebp), %esi
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    movl 44(%ebp), %edi
; X86-NEXT:    movl 48(%ebp), %ebx
; X86-NEXT:    jne .LBB2_9
; X86-NEXT:  # %bb.10: # %_udiv-special-cases
; X86-NEXT:    bsrl 52(%ebp), %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    je .LBB2_13
; X86-NEXT:  .LBB2_12:
; X86-NEXT:    bsrl %ebx, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    jmp .LBB2_14
; X86-NEXT:  .LBB2_9:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    jne .LBB2_12
; X86-NEXT:  .LBB2_13: # %_udiv-special-cases
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:  .LBB2_14: # %_udiv-special-cases
; X86-NEXT:    movl 52(%ebp), %ebx
; X86-NEXT:    orl 56(%ebp), %ebx
; X86-NEXT:    jne .LBB2_16
; X86-NEXT:  # %bb.15: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB2_16: # %_udiv-special-cases
; X86-NEXT:    movl 64(%ebp), %edi
; X86-NEXT:    orl 72(%ebp), %edi
; X86-NEXT:    movl 60(%ebp), %ebx
; X86-NEXT:    orl 68(%ebp), %ebx
; X86-NEXT:    orl %edi, %ebx
; X86-NEXT:    jne .LBB2_18
; X86-NEXT:  # %bb.17: # %_udiv-special-cases
; X86-NEXT:    orl $128, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB2_18: # %_udiv-special-cases
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    movl 32(%ebp), %edi
; X86-NEXT:    movl 36(%ebp), %ebx
; X86-NEXT:    jne .LBB2_19
; X86-NEXT:  # %bb.20: # %_udiv-special-cases
; X86-NEXT:    bsrl %ebx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    je .LBB2_23
; X86-NEXT:  .LBB2_22:
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    je .LBB2_25
; X86-NEXT:    jmp .LBB2_26
; X86-NEXT:  .LBB2_19:
; X86-NEXT:    bsrl %edx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB2_22
; X86-NEXT:  .LBB2_23: # %_udiv-special-cases
; X86-NEXT:    bsrl 28(%ebp), %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    jne .LBB2_26
; X86-NEXT:  .LBB2_25: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB2_26: # %_udiv-special-cases
; X86-NEXT:    movl 24(%ebp), %edx
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    jne .LBB2_27
; X86-NEXT:  # %bb.28: # %_udiv-special-cases
; X86-NEXT:    bsrl 20(%ebp), %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    jmp .LBB2_29
; X86-NEXT:  .LBB2_27:
; X86-NEXT:    bsrl %edx, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:  .LBB2_29: # %_udiv-special-cases
; X86-NEXT:    movl 16(%ebp), %edx
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    jne .LBB2_30
; X86-NEXT:  # %bb.31: # %_udiv-special-cases
; X86-NEXT:    bsrl 12(%ebp), %ebx
; X86-NEXT:    xorl $31, %ebx
; X86-NEXT:    orl $32, %ebx
; X86-NEXT:    jmp .LBB2_32
; X86-NEXT:  .LBB2_30:
; X86-NEXT:    bsrl %edx, %ebx
; X86-NEXT:    xorl $31, %ebx
; X86-NEXT:  .LBB2_32: # %_udiv-special-cases
; X86-NEXT:    movl 20(%ebp), %edx
; X86-NEXT:    orl 24(%ebp), %edx
; X86-NEXT:    jne .LBB2_34
; X86-NEXT:  # %bb.33: # %_udiv-special-cases
; X86-NEXT:    orl $64, %ebx
; X86-NEXT:    movl %ebx, %edi
; X86-NEXT:  .LBB2_34: # %_udiv-special-cases
; X86-NEXT:    orb %ch, %cl
; X86-NEXT:    movl 32(%ebp), %edx
; X86-NEXT:    orl 40(%ebp), %edx
; X86-NEXT:    movl 28(%ebp), %ebx
; X86-NEXT:    orl 36(%ebp), %ebx
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    jne .LBB2_36
; X86-NEXT:  # %bb.35: # %_udiv-special-cases
; X86-NEXT:    orl $128, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB2_36: # %_udiv-special-cases
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    subl %esi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edx, %edx
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    movl $0, %esi
; X86-NEXT:    sbbl %esi, %esi
; X86-NEXT:    movl $0, %edi
; X86-NEXT:    sbbl %edi, %edi
; X86-NEXT:    movl $0, %ebx
; X86-NEXT:    sbbl %ebx, %ebx
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edx, %edx
; X86-NEXT:    testb %cl, %cl
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB2_37
; X86-NEXT:  # %bb.38: # %select.false.sink
; X86-NEXT:    movl $255, %ecx
; X86-NEXT:    cmpl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl (%esp), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %esi, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %edi, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ebx, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    sbbl %edi, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %edx, %ecx
; X86-NEXT:    setb %cl
; X86-NEXT:    movl 24(%ebp), %esi
; X86-NEXT:    movl 32(%ebp), %edx
; X86-NEXT:    movl 36(%ebp), %ebx
; X86-NEXT:  .LBB2_39: # %select.end
; X86-NEXT:    testb %cl, %cl
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jne .LBB2_41
; X86-NEXT:  # %bb.40: # %select.end
; X86-NEXT:    movl 16(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 12(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 20(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 28(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, %ecx
; X86-NEXT:    movl 40(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB2_41: # %select.end
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB2_42
; X86-NEXT:  # %bb.48: # %select.end
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    xorl $255, %ecx
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl %edi, %edx
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl (%esp), %ecx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    je .LBB2_49
; X86-NEXT:  # %bb.46: # %udiv-bb1
; X86-NEXT:    movl 12(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 16(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 20(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 24(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 28(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 32(%ebp), %ebx
; X86-NEXT:    movl %ebx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 36(%ebp), %ecx
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 40(%ebp), %esi
; X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    notb %cl
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    shrb $3, %dl
; X86-NEXT:    andb $28, %dl
; X86-NEXT:    negb %dl
; X86-NEXT:    movsbl %dl, %edx
; X86-NEXT:    movl 264(%esp,%edx), %esi
; X86-NEXT:    movl 268(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 260(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 256(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 252(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 248(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 240(%esp,%edx), %edi
; X86-NEXT:    movl 244(%esp,%edx), %edx
; X86-NEXT:    shldl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl %cl, %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shll %cl, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl $1, %ecx
; X86-NEXT:    adcl $0, (%esp) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    adcl $0, %ebx
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jb .LBB2_47
; X86-NEXT:  # %bb.43: # %udiv-preheader
; X86-NEXT:    movl 12(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 16(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 20(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 24(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 28(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 32(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 36(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 40(%ebp), %eax
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $5, %al
; X86-NEXT:    movzbl %al, %esi
; X86-NEXT:    movl 172(%esp,%esi,4), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 168(%esp,%esi,4), %edi
; X86-NEXT:    movl %edi, %edx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 164(%esp,%esi,4), %edx
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    shrdl %cl, %edi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 160(%esp,%esi,4), %eax
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    shrdl %cl, %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 156(%esp,%esi,4), %edx
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    shrdl %cl, %eax, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 152(%esp,%esi,4), %eax
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    shrdl %cl, %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 144(%esp,%esi,4), %edi
; X86-NEXT:    movl 148(%esp,%esi,4), %edx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    shrdl %cl, %eax, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrl %cl, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    # kill: def $cl killed $cl killed $ecx
; X86-NEXT:    shrdl %cl, %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 44(%ebp), %eax
; X86-NEXT:    addl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 52(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 56(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 60(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 64(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 68(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 72(%ebp), %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    xorl %edx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    .p2align 4
; X86-NEXT:  .LBB2_44: # %udiv-do-while
; X86-NEXT:    # =>This Inner Loop Header: Depth=1
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ebx
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %ebx
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %edi
; X86-NEXT:    orl %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %ecx, %ebx
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %eax, %eax
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    cmpl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    sarl $31, %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl $1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 72(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 68(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 64(%ebp), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %edi
; X86-NEXT:    andl 60(%ebp), %edi
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:    andl 56(%ebp), %esi
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    andl 52(%ebp), %edx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl 48(%ebp), %eax
; X86-NEXT:    andl 44(%ebp), %ecx
; X86-NEXT:    subl %ecx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    addl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl (%esp), %edx # 4-byte Reload
; X86-NEXT:    adcl $-1, %edx
; X86-NEXT:    adcl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    adcl $-1, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    adcl $-1, %edi
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ebx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl %ebx, %edi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %eax, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %esi, %edx
; X86-NEXT:    orl %edi, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    jne .LBB2_44
; X86-NEXT:  .LBB2_45: # %udiv-loop-exit
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %ecx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    leal (%edx,%eax,2), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %edi
; X86-NEXT:  .LBB2_49: # %udiv-end
; X86-NEXT:    movl 52(%ebp), %ebx
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 56(%ebp), %eax
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl $0, %esi
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl %esi, %ebx
; X86-NEXT:    setb %cl
; X86-NEXT:    movl 56(%ebp), %eax
; X86-NEXT:    mull %edi
; X86-NEXT:    addl %ebx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movzbl %cl, %eax
; X86-NEXT:    adcl %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %ebx
; X86-NEXT:    movl 44(%ebp), %edi
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl %esi, %ecx
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    mull %ebx
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl %esi, %edx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    setb %cl
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    mull %ebx
; X86-NEXT:    addl %esi, %eax
; X86-NEXT:    movzbl %cl, %ecx
; X86-NEXT:    adcl %ecx, %edx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl %esi, %ecx
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %eax, %esi
; X86-NEXT:    addl %ecx, %esi
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl 48(%ebp), %eax
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl (%esp), %ecx # 4-byte Folded Reload
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 1-byte Folded Reload
; X86-NEXT:    adcl %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    addl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl $0, %ecx
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl 52(%ebp), %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 56(%ebp), %eax
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl (%esp), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    mull %edi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, %esi
; X86-NEXT:    adcl (%esp), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    setb (%esp) # 1-byte Folded Spill
; X86-NEXT:    movl 56(%ebp), %eax
; X86-NEXT:    mull %edi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    movzbl (%esp), %eax # 1-byte Folded Reload
; X86-NEXT:    adcl %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    addl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 1-byte Folded Reload
; X86-NEXT:    adcl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 60(%ebp), %eax
; X86-NEXT:    imull %eax, %edi
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %edi, %edx
; X86-NEXT:    movl 64(%ebp), %edi
; X86-NEXT:    imull %edi, %ebx
; X86-NEXT:    addl %edx, %ebx
; X86-NEXT:    movl 68(%ebp), %eax
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    imull %edi, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ecx, %edx
; X86-NEXT:    movl 72(%ebp), %ecx
; X86-NEXT:    imull %esi, %ecx
; X86-NEXT:    addl %edx, %ecx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-NEXT:    adcl %ebx, %ecx
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    movl %esi, %ebx
; X86-NEXT:    movl 60(%ebp), %esi
; X86-NEXT:    mull %esi
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    mull %esi
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    movl %eax, %esi
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    adcl $0, %edi
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    mull 64(%ebp)
; X86-NEXT:    addl %esi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl %edi, %edx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    setb %bl
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    mull 64(%ebp)
; X86-NEXT:    addl %esi, %eax
; X86-NEXT:    movzbl %bl, %esi
; X86-NEXT:    adcl %esi, %edx
; X86-NEXT:    addl (%esp), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-NEXT:    adcl %ecx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 52(%ebp), %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    imull {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    addl %edx, %esi
; X86-NEXT:    movl 56(%ebp), %ecx
; X86-NEXT:    imull %edi, %ecx
; X86-NEXT:    addl %esi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 44(%ebp), %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    imull %ecx, %esi
; X86-NEXT:    addl %edx, %esi
; X86-NEXT:    movl 48(%ebp), %ecx
; X86-NEXT:    imull %ecx, %ebx
; X86-NEXT:    addl %esi, %ebx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl 44(%ebp), %esi
; X86-NEXT:    mull %esi
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    mull %esi
; X86-NEXT:    movl %eax, %esi
; X86-NEXT:    addl %ecx, %esi
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl 48(%ebp), %ecx
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl %esi, %ecx
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    mull 48(%ebp)
; X86-NEXT:    addl %edi, %eax
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 1-byte Folded Reload
; X86-NEXT:    adcl %esi, %edx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    adcl %ebx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl (%esp), %eax # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl 12(%ebp), %esi
; X86-NEXT:    subl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 16(%ebp), %ebx
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 20(%ebp), %ebx
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 24(%ebp), %esi
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 28(%ebp), %esi
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl 32(%ebp), %edi
; X86-NEXT:    sbbl %ecx, %edi
; X86-NEXT:    movl 36(%ebp), %ecx
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl 40(%ebp), %eax
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl 8(%ebp), %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, (%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, 4(%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, 8(%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, 12(%edx)
; X86-NEXT:    movl %esi, 16(%edx)
; X86-NEXT:    movl %edi, 20(%edx)
; X86-NEXT:    movl %ecx, 24(%edx)
; X86-NEXT:    movl %eax, 28(%edx)
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
; X86-NEXT:  .LBB2_37:
; X86-NEXT:    movb $1, %cl
; X86-NEXT:    movl 24(%ebp), %esi
; X86-NEXT:    movl 32(%ebp), %edx
; X86-NEXT:    movl 36(%ebp), %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    jmp .LBB2_39
; X86-NEXT:  .LBB2_47:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jmp .LBB2_45
; X86-NEXT:  .LBB2_42:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    jmp .LBB2_49
;
; X64-LABEL: urem256:
; X64:       # %bb.0: # %_udiv-special-cases
; X64-NEXT:    pushq %rbp
; X64-NEXT:    pushq %r15
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %r13
; X64-NEXT:    pushq %r12
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $136, %rsp
; X64-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rcx, %r11
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r14
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r12
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; X64-NEXT:    movq %r10, %rax
; X64-NEXT:    orq %r12, %rax
; X64-NEXT:    movq %r9, %rcx
; X64-NEXT:    orq %r14, %rcx
; X64-NEXT:    orq %rax, %rcx
; X64-NEXT:    sete %cl
; X64-NEXT:    movq %rdx, %rax
; X64-NEXT:    orq %r8, %rax
; X64-NEXT:    movq %rsi, %rbx
; X64-NEXT:    orq %r11, %rbx
; X64-NEXT:    orq %rax, %rbx
; X64-NEXT:    sete %al
; X64-NEXT:    orb %cl, %al
; X64-NEXT:    bsrq %r12, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    bsrq %r14, %r15
; X64-NEXT:    xorq $63, %r15
; X64-NEXT:    orq $64, %r15
; X64-NEXT:    testq %r12, %r12
; X64-NEXT:    cmovneq %rcx, %r15
; X64-NEXT:    bsrq %r10, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    bsrq %r9, %rbx
; X64-NEXT:    xorq $63, %rbx
; X64-NEXT:    orq $64, %rbx
; X64-NEXT:    testq %r10, %r10
; X64-NEXT:    cmovneq %rcx, %rbx
; X64-NEXT:    orq $128, %rbx
; X64-NEXT:    movq %r14, %rcx
; X64-NEXT:    orq %r12, %rcx
; X64-NEXT:    cmovneq %r15, %rbx
; X64-NEXT:    bsrq %r8, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    bsrq %r11, %r9
; X64-NEXT:    xorq $63, %r9
; X64-NEXT:    orq $64, %r9
; X64-NEXT:    testq %r8, %r8
; X64-NEXT:    cmovneq %rcx, %r9
; X64-NEXT:    bsrq %rdx, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    bsrq %rsi, %r15
; X64-NEXT:    xorq $63, %r15
; X64-NEXT:    orq $64, %r15
; X64-NEXT:    testq %rdx, %rdx
; X64-NEXT:    cmovneq %rcx, %r15
; X64-NEXT:    orq $128, %r15
; X64-NEXT:    movq %r11, %rcx
; X64-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r8, %rcx
; X64-NEXT:    cmovneq %r9, %r15
; X64-NEXT:    xorl %r10d, %r10d
; X64-NEXT:    subq %r15, %rbx
; X64-NEXT:    movl $0, %r9d
; X64-NEXT:    sbbq %r9, %r9
; X64-NEXT:    movl $0, %r13d
; X64-NEXT:    sbbq %r13, %r13
; X64-NEXT:    sbbq %r10, %r10
; X64-NEXT:    testb %al, %al
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    jne .LBB2_1
; X64-NEXT:  # %bb.2: # %select.false.sink
; X64-NEXT:    xorl %eax, %eax
; X64-NEXT:    movl $255, %ecx
; X64-NEXT:    cmpq %rbx, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    sbbq %r9, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    sbbq %r13, %rcx
; X64-NEXT:    sbbq %r10, %rax
; X64-NEXT:    setb %al
; X64-NEXT:  .LBB2_3: # %select.end
; X64-NEXT:    xorl %r12d, %r12d
; X64-NEXT:    testb %al, %al
; X64-NEXT:    movq %rdx, %r8
; X64-NEXT:    movq %rdx, %r15
; X64-NEXT:    cmovneq %r12, %r15
; X64-NEXT:    movq %rsi, %rcx
; X64-NEXT:    cmovneq %r12, %rcx
; X64-NEXT:    movq %r11, %rbp
; X64-NEXT:    movq %r11, %rax
; X64-NEXT:    cmovneq %r12, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; X64-NEXT:    cmoveq %r11, %r12
; X64-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; X64-NEXT:    movq %rbp, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    jne .LBB2_4
; X64-NEXT:  # %bb.10: # %select.end
; X64-NEXT:    movq %rbx, %rdx
; X64-NEXT:    xorq $255, %rdx
; X64-NEXT:    orq %r13, %rdx
; X64-NEXT:    movq %r9, %rsi
; X64-NEXT:    orq %r10, %rsi
; X64-NEXT:    orq %rdx, %rsi
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; X64-NEXT:    je .LBB2_11
; X64-NEXT:  # %bb.8: # %udiv-bb1
; X64-NEXT:    movq %r13, %rsi
; X64-NEXT:    movq %r9, %r13
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; X64-NEXT:    movq %r14, {{[0-9]+}}(%rsp)
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; X64-NEXT:    movq %rbp, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r11, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %ebx, %ecx
; X64-NEXT:    notb %cl
; X64-NEXT:    movq %r11, %r12
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    shrb $3, %al
; X64-NEXT:    andb $24, %al
; X64-NEXT:    negb %al
; X64-NEXT:    movsbq %al, %rdx
; X64-NEXT:    movq 112(%rsp,%rdx), %r11
; X64-NEXT:    movq 120(%rsp,%rdx), %rax
; X64-NEXT:    shldq %cl, %r11, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq 96(%rsp,%rdx), %r9
; X64-NEXT:    movq 104(%rsp,%rdx), %r15
; X64-NEXT:    shldq %cl, %r15, %r11
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq %cl, %r9, %r15
; X64-NEXT:    shlq %cl, %r9
; X64-NEXT:    addq $1, %rbx
; X64-NEXT:    adcq $0, %r13
; X64-NEXT:    adcq $0, %rsi
; X64-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    adcq $0, %r10
; X64-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    jb .LBB2_9
; X64-NEXT:  # %bb.5: # %udiv-preheader
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r14, (%rsp)
; X64-NEXT:    movq %r8, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rbp, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r12, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %ebx, %ecx
; X64-NEXT:    shrb $6, %cl
; X64-NEXT:    movzbl %cl, %edx
; X64-NEXT:    movq 24(%rsp,%rdx,8), %r11
; X64-NEXT:    movq %rbx, %rcx
; X64-NEXT:    movq 16(%rsp,%rdx,8), %rbx
; X64-NEXT:    movq %rbx, %rsi
; X64-NEXT:    shrdq %cl, %r11, %rsi
; X64-NEXT:    movq (%rsp,%rdx,8), %r8
; X64-NEXT:    movq 8(%rsp,%rdx,8), %rdx
; X64-NEXT:    movq %rdx, %rbp
; X64-NEXT:    shrdq %cl, %rbx, %rbp
; X64-NEXT:    shrq %cl, %r11
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    # kill: def $cl killed $cl killed $rcx
; X64-NEXT:    shrdq %cl, %rdx, %r8
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    addq $-1, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    adcq $-1, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rcx
; X64-NEXT:    adcq $-1, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rdi, %rcx
; X64-NEXT:    adcq $-1, %rcx
; X64-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    xorl %ebx, %ebx
; X64-NEXT:    xorl %r12d, %r12d
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    movq %r10, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r13, %r10
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    .p2align 4
; X64-NEXT:  .LBB2_6: # %udiv-do-while
; X64-NEXT:    # =>This Inner Loop Header: Depth=1
; X64-NEXT:    shldq $1, %rsi, %r11
; X64-NEXT:    shldq $1, %rbp, %rsi
; X64-NEXT:    shldq $1, %r8, %rbp
; X64-NEXT:    shldq $1, %r13, %r8
; X64-NEXT:    shldq $1, %rax, %r13
; X64-NEXT:    orq %rdx, %r13
; X64-NEXT:    shldq $1, %r15, %rax
; X64-NEXT:    orq %r12, %rax
; X64-NEXT:    shldq $1, %r9, %r15
; X64-NEXT:    orq %rbx, %r15
; X64-NEXT:    addq %r9, %r9
; X64-NEXT:    orq %rcx, %r9
; X64-NEXT:    cmpq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Folded Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    sbbq %rbp, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    sbbq %rsi, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    sbbq %r11, %rdx
; X64-NEXT:    sarq $63, %rdx
; X64-NEXT:    movl %edx, %ecx
; X64-NEXT:    andl $1, %ecx
; X64-NEXT:    movq %rdx, %rbx
; X64-NEXT:    andq %rdi, %rbx
; X64-NEXT:    movq %rdx, %r12
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; X64-NEXT:    andq %rdi, %r12
; X64-NEXT:    movq %rdx, %r14
; X64-NEXT:    andq {{[0-9]+}}(%rsp), %r14
; X64-NEXT:    andq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Folded Reload
; X64-NEXT:    subq %rdx, %r8
; X64-NEXT:    sbbq %r14, %rbp
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; X64-NEXT:    sbbq %r12, %rsi
; X64-NEXT:    sbbq %rbx, %r11
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Reload
; X64-NEXT:    addq $-1, %rbx
; X64-NEXT:    adcq $-1, %r10
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; X64-NEXT:    adcq $-1, %r14
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; X64-NEXT:    adcq $-1, %r12
; X64-NEXT:    movq %r10, %rdx
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r12, %rdx
; X64-NEXT:    movq %rbx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r14, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r14, %rbx
; X64-NEXT:    orq %rdx, %rbx
; X64-NEXT:    movl $0, %ebx
; X64-NEXT:    movl $0, %r12d
; X64-NEXT:    movl $0, %edx
; X64-NEXT:    jne .LBB2_6
; X64-NEXT:  .LBB2_7: # %udiv-loop-exit
; X64-NEXT:    shldq $1, %rax, %r13
; X64-NEXT:    movq %r13, %r12
; X64-NEXT:    shldq $1, %r15, %rax
; X64-NEXT:    shldq $1, %r9, %r15
; X64-NEXT:    leaq (%rcx,%r9,2), %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; X64-NEXT:  .LBB2_11: # %udiv-end
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rbx
; X64-NEXT:    movq %rbx, %rsi
; X64-NEXT:    imulq %rax, %rsi
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; X64-NEXT:    mulq %r9
; X64-NEXT:    movq %r15, %r10
; X64-NEXT:    movq %rax, %r15
; X64-NEXT:    addq %rsi, %rdx
; X64-NEXT:    imulq %r9, %r12
; X64-NEXT:    addq %rdx, %r12
; X64-NEXT:    movq %rcx, %rax
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %rsi
; X64-NEXT:    mulq %rsi
; X64-NEXT:    movq %rax, %r14
; X64-NEXT:    imulq %rcx, %rdi
; X64-NEXT:    addq %rdx, %rdi
; X64-NEXT:    imulq %r10, %rsi
; X64-NEXT:    addq %rdi, %rsi
; X64-NEXT:    addq %r15, %r14
; X64-NEXT:    adcq %r12, %rsi
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %rcx
; X64-NEXT:    movq %rbx, %rdi
; X64-NEXT:    movq %rdx, %r12
; X64-NEXT:    movq %rax, %r15
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    mulq %rcx
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, %r13
; X64-NEXT:    addq %r12, %r13
; X64-NEXT:    adcq $0, %rcx
; X64-NEXT:    movq %r9, %rax
; X64-NEXT:    mulq %r10
; X64-NEXT:    movq %rdx, %rbx
; X64-NEXT:    movq %rax, %r12
; X64-NEXT:    addq %r13, %r12
; X64-NEXT:    adcq %rcx, %rbx
; X64-NEXT:    setb %al
; X64-NEXT:    movzbl %al, %ecx
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    mulq %r10
; X64-NEXT:    addq %rbx, %rax
; X64-NEXT:    adcq %rcx, %rdx
; X64-NEXT:    addq %r14, %rax
; X64-NEXT:    adcq %rsi, %rdx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    subq %r15, %rcx
; X64-NEXT:    sbbq %r12, %r8
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; X64-NEXT:    sbbq %rax, %rsi
; X64-NEXT:    sbbq %rdx, %r11
; X64-NEXT:    movq %rcx, (%rbp)
; X64-NEXT:    movq %r8, 8(%rbp)
; X64-NEXT:    movq %rsi, 16(%rbp)
; X64-NEXT:    movq %r11, 24(%rbp)
; X64-NEXT:    movq %rbp, %rax
; X64-NEXT:    addq $136, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r12
; X64-NEXT:    popq %r13
; X64-NEXT:    popq %r14
; X64-NEXT:    popq %r15
; X64-NEXT:    popq %rbp
; X64-NEXT:    retq
; X64-NEXT:  .LBB2_1:
; X64-NEXT:    movb $1, %al
; X64-NEXT:    jmp .LBB2_3
; X64-NEXT:  .LBB2_9:
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    jmp .LBB2_7
; X64-NEXT:  .LBB2_4:
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; X64-NEXT:    jmp .LBB2_11
  %r = urem i256 %a, %b
  ret i256 %r
}

define i256 @srem256(i256 %a, i256 %b) nounwind {
; X86-LABEL: srem256:
; X86:       # %bb.0: # %_udiv-special-cases
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $368, %esp # imm = 0x170
; X86-NEXT:    movl 40(%ebp), %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    sarl $31, %eax
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 36(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 32(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 28(%ebp), %esi
; X86-NEXT:    xorl %eax, %esi
; X86-NEXT:    movl %esi, %ebx
; X86-NEXT:    movl 24(%ebp), %edi
; X86-NEXT:    xorl %eax, %edi
; X86-NEXT:    movl 20(%ebp), %esi
; X86-NEXT:    xorl %eax, %esi
; X86-NEXT:    movl 16(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl 12(%ebp), %edx
; X86-NEXT:    xorl %eax, %edx
; X86-NEXT:    subl %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl 72(%ebp), %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    sarl $31, %eax
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 68(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 64(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 60(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    movl 56(%ebp), %edi
; X86-NEXT:    xorl %eax, %edi
; X86-NEXT:    movl 52(%ebp), %ebx
; X86-NEXT:    xorl %eax, %ebx
; X86-NEXT:    movl 48(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl 44(%ebp), %esi
; X86-NEXT:    xorl %eax, %esi
; X86-NEXT:    subl %eax, %esi
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    sbbl %eax, %ebx
; X86-NEXT:    sbbl %eax, %edi
; X86-NEXT:    sbbl %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    sbbl %eax, %edx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    orl %eax, %ecx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    orl %edx, %eax
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    orl %eax, %esi
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    sete {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    orl %ecx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    orl %esi, %edx
; X86-NEXT:    orl %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    orl %esi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    orl %eax, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    sete {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB3_1
; X86-NEXT:  # %bb.2: # %_udiv-special-cases
; X86-NEXT:    movl %ebx, %edi
; X86-NEXT:    bsrl %ebx, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    orl $32, %eax
; X86-NEXT:    jmp .LBB3_3
; X86-NEXT:  .LBB3_1:
; X86-NEXT:    bsrl %edi, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    movl %ebx, %edi
; X86-NEXT:  .LBB3_3: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    jne .LBB3_4
; X86-NEXT:  # %bb.5: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    jmp .LBB3_6
; X86-NEXT:  .LBB3_4:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:  .LBB3_6: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    jne .LBB3_8
; X86-NEXT:  # %bb.7: # %_udiv-special-cases
; X86-NEXT:    orl $64, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB3_8: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    testl %esi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    jne .LBB3_9
; X86-NEXT:  # %bb.10: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    je .LBB3_13
; X86-NEXT:  .LBB3_12:
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    jmp .LBB3_14
; X86-NEXT:  .LBB3_9:
; X86-NEXT:    bsrl %esi, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB3_12
; X86-NEXT:  .LBB3_13: # %_udiv-special-cases
; X86-NEXT:    bsrl %ebx, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:  .LBB3_14: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    jne .LBB3_16
; X86-NEXT:  # %bb.15: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB3_16: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    orl %edi, %ebx
; X86-NEXT:    jne .LBB3_18
; X86-NEXT:  # %bb.17: # %_udiv-special-cases
; X86-NEXT:    orl $128, %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:  .LBB3_18: # %_udiv-special-cases
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    jne .LBB3_19
; X86-NEXT:  # %bb.20: # %_udiv-special-cases
; X86-NEXT:    bsrl %ebx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    jmp .LBB3_21
; X86-NEXT:  .LBB3_19:
; X86-NEXT:    bsrl %edx, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:  .LBB3_21: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    testl %edi, %edi
; X86-NEXT:    jne .LBB3_22
; X86-NEXT:  # %bb.23: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    je .LBB3_25
; X86-NEXT:    jmp .LBB3_26
; X86-NEXT:  .LBB3_22:
; X86-NEXT:    bsrl %edi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    jne .LBB3_26
; X86-NEXT:  .LBB3_25: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB3_26: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    jne .LBB3_27
; X86-NEXT:  # %bb.28: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    bsrl %edx, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    testl %ecx, %ecx
; X86-NEXT:    je .LBB3_31
; X86-NEXT:  .LBB3_30:
; X86-NEXT:    bsrl %ecx, %ebx
; X86-NEXT:    xorl $31, %ebx
; X86-NEXT:    jmp .LBB3_32
; X86-NEXT:  .LBB3_27:
; X86-NEXT:    bsrl %edx, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    testl %ecx, %ecx
; X86-NEXT:    jne .LBB3_30
; X86-NEXT:  .LBB3_31: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %ebx
; X86-NEXT:    orl $32, %ebx
; X86-NEXT:  .LBB3_32: # %_udiv-special-cases
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 1-byte Folded Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    jne .LBB3_34
; X86-NEXT:  # %bb.33: # %_udiv-special-cases
; X86-NEXT:    orl $64, %ebx
; X86-NEXT:    movl %ebx, %edi
; X86-NEXT:  .LBB3_34: # %_udiv-special-cases
; X86-NEXT:    orb {{[-0-9]+}}(%e{{[sb]}}p), %cl # 1-byte Folded Reload
; X86-NEXT:    movb %cl, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    jne .LBB3_36
; X86-NEXT:  # %bb.35: # %_udiv-special-cases
; X86-NEXT:    orl $128, %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:  .LBB3_36: # %_udiv-special-cases
; X86-NEXT:    subl %esi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edx, %edx
; X86-NEXT:    movl $0, %esi
; X86-NEXT:    sbbl %esi, %esi
; X86-NEXT:    movl $0, %edi
; X86-NEXT:    sbbl %edi, %edi
; X86-NEXT:    movl $0, %ebx
; X86-NEXT:    sbbl %ebx, %ebx
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    cmpb $0, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB3_37
; X86-NEXT:  # %bb.38: # %select.false.sink
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $255, %ecx
; X86-NEXT:    cmpl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %edx, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %esi, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %edi, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ebx, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    sbbl %edx, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    sbbl %ebx, %ecx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    setb %cl
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:  .LBB3_39: # %select.end
; X86-NEXT:    testb %cl, %cl
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jne .LBB3_41
; X86-NEXT:  # %bb.40: # %select.end
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %ecx
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB3_41: # %select.end
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    jne .LBB3_42
; X86-NEXT:  # %bb.48: # %select.end
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    xorl $255, %ecx
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl %ebx, %edx
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %ecx
; X86-NEXT:    orl %esi, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    je .LBB3_49
; X86-NEXT:  # %bb.46: # %udiv-bb1
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    notb %cl
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    shrb $3, %dl
; X86-NEXT:    andb $28, %dl
; X86-NEXT:    negb %dl
; X86-NEXT:    movsbl %dl, %edx
; X86-NEXT:    movl 344(%esp,%edx), %esi
; X86-NEXT:    movl 348(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 340(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 336(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 332(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 328(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 320(%esp,%edx), %edi
; X86-NEXT:    movl 324(%esp,%edx), %edx
; X86-NEXT:    shldl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl %cl, %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shll %cl, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    addl $1, %ecx
; X86-NEXT:    adcl $0, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jb .LBB3_47
; X86-NEXT:  # %bb.43: # %udiv-preheader
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $5, %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    movl 252(%esp,%eax,4), %esi
; X86-NEXT:    movl 248(%esp,%eax,4), %edi
; X86-NEXT:    movl %edi, %edx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 244(%esp,%eax,4), %ebx
; X86-NEXT:    movl %ebx, %edx
; X86-NEXT:    shrdl %cl, %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 240(%esp,%eax,4), %edi
; X86-NEXT:    movl %edi, %edx
; X86-NEXT:    shrdl %cl, %ebx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 236(%esp,%eax,4), %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 232(%esp,%eax,4), %ebx
; X86-NEXT:    movl %ebx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shrdl %cl, %edi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 224(%esp,%eax,4), %edi
; X86-NEXT:    movl 228(%esp,%eax,4), %eax
; X86-NEXT:    movl %eax, %edx
; X86-NEXT:    shrdl %cl, %ebx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrl %cl, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    # kill: def $cl killed $cl killed $ecx
; X86-NEXT:    shrdl %cl, %eax, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    addl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    xorl %ebx, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    .p2align 4
; X86-NEXT:  .LBB3_44: # %udiv-do-while
; X86-NEXT:    # =>This Inner Loop Header: Depth=1
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %esi
; X86-NEXT:    movl %esi, %edx
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edi
; X86-NEXT:    shldl $1, %ecx, %esi
; X86-NEXT:    orl %ebx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ecx
; X86-NEXT:    orl %ebx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %esi
; X86-NEXT:    orl %ebx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    orl %ebx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    orl %ebx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ecx
; X86-NEXT:    orl %ebx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %esi
; X86-NEXT:    orl %ebx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %eax, %eax
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    cmpl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    movl %edi, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    sarl $31, %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl $1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %edi
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    subl %ecx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %esi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %edi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    adcl $-1, %esi
; X86-NEXT:    adcl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    adcl $-1, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    adcl $-1, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ecx, %esi
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %eax, %ecx
; X86-NEXT:    orl %esi, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edi, %edx
; X86-NEXT:    xorl %ebx, %ebx
; X86-NEXT:    orl %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    jne .LBB3_44
; X86-NEXT:  .LBB3_45: # %udiv-loop-exit
; X86-NEXT:    shldl $1, %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $1, %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    leal (%edi,%esi,2), %edi
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:  .LBB3_49: # %udiv-end
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl %esi, %ecx
; X86-NEXT:    adcl $0, %edi
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    mull %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl %edi, %ebx
; X86-NEXT:    setb %cl
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ebx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movzbl %cl, %eax
; X86-NEXT:    adcl %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl %ebx, %ecx
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl %ebx, %edx
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl %edi, %ecx
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ebx, %eax
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 1-byte Folded Reload
; X86-NEXT:    adcl %esi, %edx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    mull %edi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, %ebx
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 1-byte Folded Reload
; X86-NEXT:    adcl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    addl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl $0, %eax
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, %ebx
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl %esi, %edi
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 1-byte Folded Reload
; X86-NEXT:    adcl %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    addl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 1-byte Folded Reload
; X86-NEXT:    adcl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl %edi, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    imull %eax, %ecx
; X86-NEXT:    mull %esi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %ecx, %edx
; X86-NEXT:    imull {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    addl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    imull {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    mull %edi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    imull %edi, %ebx
; X86-NEXT:    addl %edx, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    addl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl %esi, %ebx
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    movl %edi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    setb {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    mull %esi
; X86-NEXT:    addl %ecx, %eax
; X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 1-byte Folded Reload
; X86-NEXT:    adcl %ecx, %edx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl %ebx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    imull {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    addl %edx, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    imull %ecx, %edx
; X86-NEXT:    addl %ebx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    mull %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    imull %ebx, %esi
; X86-NEXT:    addl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    imull %ecx, %edi
; X86-NEXT:    addl %esi, %edi
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    mull %ebx
; X86-NEXT:    movl %eax, %ebx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    mull %ecx
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    addl %ebx, %ecx
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    setb %bl
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    mull {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    addl %edi, %eax
; X86-NEXT:    movzbl %bl, %esi
; X86-NEXT:    adcl %esi, %edx
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    subl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %edi, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    sbbl %esi, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    sbbl %ecx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    xorl %edx, %eax
; X86-NEXT:    xorl %edx, %ecx
; X86-NEXT:    xorl %edx, %esi
; X86-NEXT:    xorl %edx, %edi
; X86-NEXT:    xorl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    xorl %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    xorl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    xorl %edx, %ebx
; X86-NEXT:    subl %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edx, %edi
; X86-NEXT:    sbbl %edx, %esi
; X86-NEXT:    sbbl %edx, %ecx
; X86-NEXT:    sbbl %edx, %eax
; X86-NEXT:    movl 8(%ebp), %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, (%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, 4(%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, 8(%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, 12(%edx)
; X86-NEXT:    movl %edi, 16(%edx)
; X86-NEXT:    movl %esi, 20(%edx)
; X86-NEXT:    movl %ecx, 24(%edx)
; X86-NEXT:    movl %eax, 28(%edx)
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
; X86-NEXT:  .LBB3_37:
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movb $1, %cl
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    jmp .LBB3_39
; X86-NEXT:  .LBB3_47:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jmp .LBB3_45
; X86-NEXT:  .LBB3_42:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    jmp .LBB3_49
;
; X64-LABEL: srem256:
; X64:       # %bb.0: # %_udiv-special-cases
; X64-NEXT:    pushq %rbp
; X64-NEXT:    pushq %r15
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %r13
; X64-NEXT:    pushq %r12
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $152, %rsp
; X64-NEXT:    movq %rcx, %rbx
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r13
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    sarq $63, %rax
; X64-NEXT:    xorq %rax, %r8
; X64-NEXT:    xorq %rax, %rbx
; X64-NEXT:    xorq %rax, %rdx
; X64-NEXT:    xorq %rax, %rsi
; X64-NEXT:    subq %rax, %rsi
; X64-NEXT:    sbbq %rax, %rdx
; X64-NEXT:    sbbq %rax, %rbx
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    sbbq %rax, %r8
; X64-NEXT:    movq %r13, %rax
; X64-NEXT:    sarq $63, %rax
; X64-NEXT:    xorq %rax, %r13
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r14
; X64-NEXT:    xorq %rax, %r14
; X64-NEXT:    movq {{[0-9]+}}(%rsp), %r12
; X64-NEXT:    xorq %rax, %r12
; X64-NEXT:    xorq %rax, %r9
; X64-NEXT:    subq %rax, %r9
; X64-NEXT:    sbbq %rax, %r12
; X64-NEXT:    sbbq %rax, %r14
; X64-NEXT:    sbbq %rax, %r13
; X64-NEXT:    movq %r12, %rax
; X64-NEXT:    orq %r13, %rax
; X64-NEXT:    movq %r9, %rcx
; X64-NEXT:    orq %r14, %rcx
; X64-NEXT:    orq %rax, %rcx
; X64-NEXT:    sete %cl
; X64-NEXT:    movq %rdx, %rax
; X64-NEXT:    orq %r8, %rax
; X64-NEXT:    movq %rsi, %rdi
; X64-NEXT:    orq %rbx, %rdi
; X64-NEXT:    orq %rax, %rdi
; X64-NEXT:    sete %al
; X64-NEXT:    orb %cl, %al
; X64-NEXT:    bsrq %r13, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    bsrq %r14, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    orq $64, %rdi
; X64-NEXT:    testq %r13, %r13
; X64-NEXT:    cmovneq %rcx, %rdi
; X64-NEXT:    bsrq %r12, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    bsrq %r9, %r11
; X64-NEXT:    xorq $63, %r11
; X64-NEXT:    orq $64, %r11
; X64-NEXT:    testq %r12, %r12
; X64-NEXT:    cmovneq %rcx, %r11
; X64-NEXT:    orq $128, %r11
; X64-NEXT:    movq %r14, %rcx
; X64-NEXT:    orq %r13, %rcx
; X64-NEXT:    cmovneq %rdi, %r11
; X64-NEXT:    bsrq %r8, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    bsrq %rbx, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    orq $64, %rdi
; X64-NEXT:    testq %r8, %r8
; X64-NEXT:    cmovneq %rcx, %rdi
; X64-NEXT:    bsrq %rdx, %rcx
; X64-NEXT:    xorq $63, %rcx
; X64-NEXT:    bsrq %rsi, %r10
; X64-NEXT:    xorq $63, %r10
; X64-NEXT:    orq $64, %r10
; X64-NEXT:    testq %rdx, %rdx
; X64-NEXT:    cmovneq %rcx, %r10
; X64-NEXT:    orq $128, %r10
; X64-NEXT:    movq %rbx, %rcx
; X64-NEXT:    orq %r8, %rcx
; X64-NEXT:    cmovneq %rdi, %r10
; X64-NEXT:    xorl %ebp, %ebp
; X64-NEXT:    subq %r10, %r11
; X64-NEXT:    movl $0, %edi
; X64-NEXT:    sbbq %rdi, %rdi
; X64-NEXT:    movl $0, %r10d
; X64-NEXT:    sbbq %r10, %r10
; X64-NEXT:    sbbq %rbp, %rbp
; X64-NEXT:    testb %al, %al
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    jne .LBB3_1
; X64-NEXT:  # %bb.2: # %select.false.sink
; X64-NEXT:    xorl %eax, %eax
; X64-NEXT:    movl $255, %ecx
; X64-NEXT:    cmpq %r11, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    sbbq %rdi, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    movq %r10, %r15
; X64-NEXT:    sbbq %r10, %rcx
; X64-NEXT:    movq %rbp, %r10
; X64-NEXT:    sbbq %rbp, %rax
; X64-NEXT:    setb %al
; X64-NEXT:  .LBB3_3: # %select.end
; X64-NEXT:    xorl %edi, %edi
; X64-NEXT:    testb %al, %al
; X64-NEXT:    movq %rdx, %r9
; X64-NEXT:    movq %rdx, %rax
; X64-NEXT:    cmovneq %rdi, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rsi, %rcx
; X64-NEXT:    cmovneq %rdi, %rcx
; X64-NEXT:    movq %rbx, %rbp
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    cmovneq %rdi, %rax
; X64-NEXT:    cmoveq %r8, %rdi
; X64-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r13, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    jne .LBB3_9
; X64-NEXT:  # %bb.4: # %select.end
; X64-NEXT:    movq %r11, %rdx
; X64-NEXT:    xorq $255, %rdx
; X64-NEXT:    orq %r15, %rdx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    movq %r13, %rsi
; X64-NEXT:    orq %r10, %rsi
; X64-NEXT:    orq %rdx, %rsi
; X64-NEXT:    je .LBB3_9
; X64-NEXT:  # %bb.5: # %udiv-bb1
; X64-NEXT:    movq %r10, %rbx
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdi # 8-byte Reload
; X64-NEXT:    movq %rdi, {{[0-9]+}}(%rsp)
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r9, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rbp, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r11d, %ecx
; X64-NEXT:    notb %cl
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    shrb $3, %al
; X64-NEXT:    andb $24, %al
; X64-NEXT:    negb %al
; X64-NEXT:    movsbq %al, %rdx
; X64-NEXT:    movq 128(%rsp,%rdx), %r12
; X64-NEXT:    movq 136(%rsp,%rdx), %rax
; X64-NEXT:    shldq %cl, %r12, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r9, %rsi
; X64-NEXT:    movq 112(%rsp,%rdx), %r10
; X64-NEXT:    movq 120(%rsp,%rdx), %r9
; X64-NEXT:    shldq %cl, %r9, %r12
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    shldq %cl, %r10, %r9
; X64-NEXT:    shlq %cl, %r10
; X64-NEXT:    addq $1, %r11
; X64-NEXT:    adcq $0, %r13
; X64-NEXT:    adcq $0, %r15
; X64-NEXT:    movq %r15, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    adcq $0, %rbx
; X64-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rbp, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    jb .LBB3_10
; X64-NEXT:  # %bb.6: # %udiv-preheader
; X64-NEXT:    movq %rbx, %r15
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdi, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rsi, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rbp, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r11d, %ecx
; X64-NEXT:    shrb $6, %cl
; X64-NEXT:    movzbl %cl, %edx
; X64-NEXT:    movq 40(%rsp,%rdx,8), %rsi
; X64-NEXT:    movq 32(%rsp,%rdx,8), %rbx
; X64-NEXT:    movq %r11, %rcx
; X64-NEXT:    movq %rbx, %r11
; X64-NEXT:    shrdq %cl, %rsi, %r11
; X64-NEXT:    movq 16(%rsp,%rdx,8), %rdi
; X64-NEXT:    movq 24(%rsp,%rdx,8), %rdx
; X64-NEXT:    movq %rdx, %r8
; X64-NEXT:    shrdq %cl, %rbx, %r8
; X64-NEXT:    shrq %cl, %rsi
; X64-NEXT:    shrdq %cl, %rdx, %rdi
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    addq $-1, %rdx
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    adcq $-1, %rdx
; X64-NEXT:    movq %rdx, (%rsp) # 8-byte Spill
; X64-NEXT:    movq %r14, %rdx
; X64-NEXT:    adcq $-1, %rdx
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    adcq $-1, %rdx
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    xorl %ebp, %ebp
; X64-NEXT:    xorl %ebx, %ebx
; X64-NEXT:    xorl %r12d, %r12d
; X64-NEXT:    xorl %edx, %edx
; X64-NEXT:    movq %r13, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    .p2align 4
; X64-NEXT:  .LBB3_7: # %udiv-do-while
; X64-NEXT:    # =>This Inner Loop Header: Depth=1
; X64-NEXT:    shldq $1, %r11, %rsi
; X64-NEXT:    shldq $1, %r8, %r11
; X64-NEXT:    shldq $1, %rdi, %r8
; X64-NEXT:    shldq $1, %r13, %rdi
; X64-NEXT:    shldq $1, %rax, %r13
; X64-NEXT:    orq %rdx, %r13
; X64-NEXT:    shldq $1, %r9, %rax
; X64-NEXT:    orq %r12, %rax
; X64-NEXT:    shldq $1, %r10, %r9
; X64-NEXT:    orq %rbx, %r9
; X64-NEXT:    addq %r10, %r10
; X64-NEXT:    orq %rbp, %r10
; X64-NEXT:    movq %r10, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    cmpq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Folded Reload
; X64-NEXT:    movq (%rsp), %rdx # 8-byte Reload
; X64-NEXT:    sbbq %r8, %rdx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    sbbq %r11, %rdx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    sbbq %rsi, %rdx
; X64-NEXT:    sarq $63, %rdx
; X64-NEXT:    movl %edx, %ebp
; X64-NEXT:    andl $1, %ebp
; X64-NEXT:    movq %rdx, %rbx
; X64-NEXT:    andq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Folded Reload
; X64-NEXT:    movq %rdx, %r12
; X64-NEXT:    andq %r14, %r12
; X64-NEXT:    movq %r15, %r10
; X64-NEXT:    movq %r14, %r15
; X64-NEXT:    movq %rdx, %r14
; X64-NEXT:    andq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Folded Reload
; X64-NEXT:    andq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Folded Reload
; X64-NEXT:    subq %rdx, %rdi
; X64-NEXT:    sbbq %r14, %r8
; X64-NEXT:    movq %r15, %r14
; X64-NEXT:    movq %r10, %r15
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; X64-NEXT:    sbbq %r12, %r11
; X64-NEXT:    sbbq %rbx, %rsi
; X64-NEXT:    addq $-1, %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; X64-NEXT:    adcq $-1, %rdx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; X64-NEXT:    adcq $-1, %r12
; X64-NEXT:    adcq $-1, %r15
; X64-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r15, %rdx
; X64-NEXT:    movq %rcx, %rbx
; X64-NEXT:    movq %r12, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r12, %rbx
; X64-NEXT:    orq %rdx, %rbx
; X64-NEXT:    movl $0, %ebx
; X64-NEXT:    movl $0, %r12d
; X64-NEXT:    movl $0, %edx
; X64-NEXT:    jne .LBB3_7
; X64-NEXT:  .LBB3_8: # %udiv-loop-exit
; X64-NEXT:    shldq $1, %rax, %r13
; X64-NEXT:    movq %r13, %rdi
; X64-NEXT:    shldq $1, %r9, %rax
; X64-NEXT:    shldq $1, %r10, %r9
; X64-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    leaq (%rbp,%r10,2), %rcx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbp # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; X64-NEXT:  .LBB3_9: # %udiv-end
; X64-NEXT:    movq %rax, %rsi
; X64-NEXT:    imulq %r12, %rsi
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Reload
; X64-NEXT:    mulq %r15
; X64-NEXT:    movq %rax, %r11
; X64-NEXT:    addq %rsi, %rdx
; X64-NEXT:    imulq %r15, %rdi
; X64-NEXT:    addq %rdx, %rdi
; X64-NEXT:    movq %rcx, %rax
; X64-NEXT:    mulq %r14
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Reload
; X64-NEXT:    movq %r14, %rsi
; X64-NEXT:    movq %rax, %r14
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    imulq %rcx, %rax
; X64-NEXT:    addq %rdx, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; X64-NEXT:    imulq %r10, %rsi
; X64-NEXT:    addq %rax, %rsi
; X64-NEXT:    addq %r11, %r14
; X64-NEXT:    adcq %rdi, %rsi
; X64-NEXT:    movq %r15, %rax
; X64-NEXT:    mulq %rcx
; X64-NEXT:    movq %r12, %rdi
; X64-NEXT:    movq %rdx, %r12
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    mulq %rcx
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rax, %r13
; X64-NEXT:    addq %r12, %r13
; X64-NEXT:    adcq $0, %rcx
; X64-NEXT:    movq %r15, %rax
; X64-NEXT:    mulq %r10
; X64-NEXT:    movq %rdx, %r11
; X64-NEXT:    movq %rax, %r12
; X64-NEXT:    addq %r13, %r12
; X64-NEXT:    adcq %rcx, %r11
; X64-NEXT:    setb %cl
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    mulq %r10
; X64-NEXT:    addq %r11, %rax
; X64-NEXT:    movzbl %cl, %ecx
; X64-NEXT:    adcq %rcx, %rdx
; X64-NEXT:    addq %r14, %rax
; X64-NEXT:    adcq %rsi, %rdx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    subq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Folded Reload
; X64-NEXT:    sbbq %r12, %r9
; X64-NEXT:    sbbq %rax, %rbp
; X64-NEXT:    sbbq %rdx, %r8
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    xorq %rax, %r8
; X64-NEXT:    xorq %rax, %rbp
; X64-NEXT:    xorq %rax, %r9
; X64-NEXT:    xorq %rax, %rcx
; X64-NEXT:    subq %rax, %rcx
; X64-NEXT:    sbbq %rax, %r9
; X64-NEXT:    sbbq %rax, %rbp
; X64-NEXT:    sbbq %rax, %r8
; X64-NEXT:    movq %rcx, (%rbx)
; X64-NEXT:    movq %r9, 8(%rbx)
; X64-NEXT:    movq %rbp, 16(%rbx)
; X64-NEXT:    movq %r8, 24(%rbx)
; X64-NEXT:    movq %rbx, %rax
; X64-NEXT:    addq $152, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r12
; X64-NEXT:    popq %r13
; X64-NEXT:    popq %r14
; X64-NEXT:    popq %r15
; X64-NEXT:    popq %rbp
; X64-NEXT:    retq
; X64-NEXT:  .LBB3_1:
; X64-NEXT:    movq %r10, %r15
; X64-NEXT:    movq %rbp, %r10
; X64-NEXT:    movb $1, %al
; X64-NEXT:    jmp .LBB3_3
; X64-NEXT:  .LBB3_10:
; X64-NEXT:    xorl %ebp, %ebp
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    jmp .LBB3_8
  %r = srem i256 %a, %b
  ret i256 %r
}

; Division by power of 2 should optimize to shift
define i256 @udiv256_pow2(i256 %a) nounwind {
; X86-LABEL: udiv256_pow2:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    subl $8, %esp
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X86-NEXT:    movl %ebp, %esi
; X86-NEXT:    shldl $28, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl $28, %ebx, %edx
; X86-NEXT:    movl %edx, (%esp) # 4-byte Spill
; X86-NEXT:    shldl $28, %ecx, %ebx
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:    shldl $28, %edi, %esi
; X86-NEXT:    shldl $28, %eax, %edi
; X86-NEXT:    movl %eax, %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shldl $28, %eax, %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    shrdl $4, %eax, %ecx
; X86-NEXT:    shrl $4, %ebp
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl %ebp, 28(%eax)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; X86-NEXT:    movl %ebp, 24(%eax)
; X86-NEXT:    movl (%esp), %ebp # 4-byte Reload
; X86-NEXT:    movl %ebp, 20(%eax)
; X86-NEXT:    movl %ebx, 16(%eax)
; X86-NEXT:    movl %esi, 12(%eax)
; X86-NEXT:    movl %edi, 8(%eax)
; X86-NEXT:    movl %edx, 4(%eax)
; X86-NEXT:    movl %ecx, (%eax)
; X86-NEXT:    addl $8, %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
;
; X64-LABEL: udiv256_pow2:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    shrdq $4, %rdx, %rsi
; X64-NEXT:    shrdq $4, %rcx, %rdx
; X64-NEXT:    shrdq $4, %r8, %rcx
; X64-NEXT:    shrq $4, %r8
; X64-NEXT:    movq %r8, 24(%rdi)
; X64-NEXT:    movq %rcx, 16(%rdi)
; X64-NEXT:    movq %rdx, 8(%rdi)
; X64-NEXT:    movq %rsi, (%rdi)
; X64-NEXT:    retq
  %r = udiv i256 %a, 16
  ret i256 %r
}

; Division by constant
define i256 @sdiv256_const(i256 %a) nounwind {
; X86-LABEL: sdiv256_const:
; X86:       # %bb.0: # %_udiv-special-cases
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $288, %esp # imm = 0x120
; X86-NEXT:    movl 40(%ebp), %edi
; X86-NEXT:    movl %edi, %eax
; X86-NEXT:    sarl $31, %eax
; X86-NEXT:    xorl %eax, %edi
; X86-NEXT:    movl 36(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 32(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 28(%ebp), %ecx
; X86-NEXT:    xorl %eax, %ecx
; X86-NEXT:    movl 24(%ebp), %edx
; X86-NEXT:    xorl %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 20(%ebp), %edx
; X86-NEXT:    xorl %eax, %edx
; X86-NEXT:    movl 16(%ebp), %ebx
; X86-NEXT:    xorl %eax, %ebx
; X86-NEXT:    movl 12(%ebp), %esi
; X86-NEXT:    xorl %eax, %esi
; X86-NEXT:    subl %eax, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    sbbl %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    sbbl %eax, %edx
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl %eax, %ebx
; X86-NEXT:    sbbl %eax, %ecx
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl %eax, %edi
; X86-NEXT:    jne .LBB5_1
; X86-NEXT:  # %bb.2: # %_udiv-special-cases
; X86-NEXT:    bsrl %ecx, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    orl $32, %eax
; X86-NEXT:    jmp .LBB5_3
; X86-NEXT:  .LBB5_1:
; X86-NEXT:    bsrl %edi, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:  .LBB5_3: # %_udiv-special-cases
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    testl %ebx, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    jne .LBB5_4
; X86-NEXT:  # %bb.5: # %_udiv-special-cases
; X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    orl $32, %eax
; X86-NEXT:    jmp .LBB5_6
; X86-NEXT:  .LBB5_4:
; X86-NEXT:    bsrl %ebx, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:  .LBB5_6: # %_udiv-special-cases
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edi, %ecx
; X86-NEXT:    jne .LBB5_8
; X86-NEXT:  # %bb.7: # %_udiv-special-cases
; X86-NEXT:    orl $64, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB5_8: # %_udiv-special-cases
; X86-NEXT:    testl %edx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    jne .LBB5_9
; X86-NEXT:  # %bb.10: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    bsrl %eax, %esi
; X86-NEXT:    xorl $31, %esi
; X86-NEXT:    orl $32, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    jmp .LBB5_11
; X86-NEXT:  .LBB5_9:
; X86-NEXT:    bsrl %edx, %eax
; X86-NEXT:    xorl $31, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:  .LBB5_11: # %_udiv-special-cases
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, %edx
; X86-NEXT:    testl %ecx, %ecx
; X86-NEXT:    jne .LBB5_12
; X86-NEXT:  # %bb.13: # %_udiv-special-cases
; X86-NEXT:    bsrl %esi, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:    orl $32, %edi
; X86-NEXT:    jmp .LBB5_14
; X86-NEXT:  .LBB5_12:
; X86-NEXT:    bsrl %ecx, %edi
; X86-NEXT:    xorl $31, %edi
; X86-NEXT:  .LBB5_14: # %_udiv-special-cases
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ebx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl %esi, %ebx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edx, %ebx
; X86-NEXT:    movl %eax, %ecx
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    orl %esi, %eax
; X86-NEXT:    jne .LBB5_16
; X86-NEXT:  # %bb.15: # %_udiv-special-cases
; X86-NEXT:    orl $64, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB5_16: # %_udiv-special-cases
; X86-NEXT:    orl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    orl %ecx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    orl %eax, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    jne .LBB5_18
; X86-NEXT:  # %bb.17: # %_udiv-special-cases
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    orl $128, %eax
; X86-NEXT:  .LBB5_18: # %_udiv-special-cases
; X86-NEXT:    movl $253, %esi
; X86-NEXT:    subl %eax, %esi
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    sbbl %eax, %eax
; X86-NEXT:    movl $0, %ebx
; X86-NEXT:    sbbl %ebx, %ebx
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ecx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    sbbl %ecx, %ecx
; X86-NEXT:    movl $0, %edi
; X86-NEXT:    sbbl %edi, %edi
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edx, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    je .LBB5_19
; X86-NEXT:  # %bb.20: # %select.false.sink
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $255, %edx
; X86-NEXT:    cmpl %esi, %edx
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %eax, %edx
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %ebx, %edx
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %ecx, %edx
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    sbbl %edi, %edx
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    sbbl %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    sbbl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    setb %cl
; X86-NEXT:  .LBB5_21: # %select.end
; X86-NEXT:    xorl %eax, %eax
; X86-NEXT:    testb %cl, %cl
; X86-NEXT:    movl $0, %ebx
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, %ecx
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $0, %esi
; X86-NEXT:    movl $0, %edx
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jne .LBB5_23
; X86-NEXT:  # %bb.22: # %select.end
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:  .LBB5_23: # %select.end
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    jne .LBB5_24
; X86-NEXT:  # %bb.30: # %select.end
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    movl %ebx, %edx
; X86-NEXT:    xorl $255, %edx
; X86-NEXT:    orl %edi, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    orl %edx, %edi
; X86-NEXT:    orl %esi, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    je .LBB5_31
; X86-NEXT:  # %bb.28: # %udiv-bb1
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ebx, %ecx
; X86-NEXT:    notb %cl
; X86-NEXT:    movl %ecx, %edx
; X86-NEXT:    shrb $3, %dl
; X86-NEXT:    andb $28, %dl
; X86-NEXT:    negb %dl
; X86-NEXT:    movsbl %dl, %edx
; X86-NEXT:    movl 264(%esp,%edx), %esi
; X86-NEXT:    movl 268(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %esi, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 260(%esp,%edx), %ebx
; X86-NEXT:    shldl %cl, %ebx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 256(%esp,%edx), %esi
; X86-NEXT:    shldl %cl, %esi, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 252(%esp,%edx), %edi
; X86-NEXT:    shldl %cl, %edi, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 248(%esp,%edx), %ebx
; X86-NEXT:    shldl %cl, %ebx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %eax, %esi
; X86-NEXT:    movl 240(%esp,%edx), %eax
; X86-NEXT:    movl 244(%esp,%edx), %edx
; X86-NEXT:    shldl %cl, %edx, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shldl %cl, %eax, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shll %cl, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    addl $1, %ecx
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jb .LBB5_29
; X86-NEXT:  # %bb.25: # %udiv-preheader
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $5, %al
; X86-NEXT:    movzbl %al, %ebx
; X86-NEXT:    movl 172(%esp,%ebx,4), %esi
; X86-NEXT:    movl 168(%esp,%ebx,4), %eax
; X86-NEXT:    movl %eax, %edx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 164(%esp,%ebx,4), %edx
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    shrdl %cl, %eax, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 160(%esp,%ebx,4), %eax
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    shrdl %cl, %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 156(%esp,%ebx,4), %edx
; X86-NEXT:    movl %edx, %edi
; X86-NEXT:    shrdl %cl, %eax, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 152(%esp,%ebx,4), %eax
; X86-NEXT:    movl %eax, %edi
; X86-NEXT:    shrdl %cl, %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 144(%esp,%ebx,4), %edi
; X86-NEXT:    movl 148(%esp,%ebx,4), %edx
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    shrdl %cl, %eax, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrl %cl, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    # kill: def $cl killed $cl killed $ecx
; X86-NEXT:    shrdl %cl, %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $7, %eax
; X86-NEXT:    addl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, %eax
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    .p2align 4
; X86-NEXT:  .LBB5_26: # %udiv-do-while
; X86-NEXT:    # =>This Inner Loop Header: Depth=1
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    shldl $1, %ebx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %ebx
; X86-NEXT:    shldl $1, %edi, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    orl %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %eax
; X86-NEXT:    orl %edx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %edi
; X86-NEXT:    orl %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %edi
; X86-NEXT:    orl %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shldl $1, %edi, %ecx
; X86-NEXT:    orl %edx, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl %edi, %edi
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    cmpl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl %ebx, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    sbbl %edx, %ecx
; X86-NEXT:    sarl $31, %ecx
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    andl $1, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl $7, %edi
; X86-NEXT:    andl %edi, %ecx
; X86-NEXT:    subl %ecx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl $0, %ebx
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    sbbl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    sbbl $0, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    addl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    adcl $-1, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    adcl $-1, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    adcl $-1, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    adcl $-1, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    adcl $-1, %ecx
; X86-NEXT:    adcl $-1, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edx, %esi
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; X86-NEXT:    orl %esi, %eax
; X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %ecx, %ebx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    orl %edi, %edx
; X86-NEXT:    orl %ebx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    orl %eax, %edx
; X86-NEXT:    jne .LBB5_26
; X86-NEXT:  .LBB5_27: # %udiv-loop-exit
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl $1, %edx, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    shldl $1, %ecx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    shldl $1, %esi, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    shldl $1, %eax, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    leal (%esi,%eax,2), %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:  .LBB5_31: # %udiv-end
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    xorl %edx, %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    xorl %edx, %eax
; X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    xorl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl %ecx, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; X86-NEXT:    xorl %edx, %ebx
; X86-NEXT:    xorl %edx, %edi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    xorl %edx, %esi
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; X86-NEXT:    xorl %edx, %ecx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    xorl %edx, %eax
; X86-NEXT:    subl %edx, %eax
; X86-NEXT:    sbbl %edx, %ecx
; X86-NEXT:    sbbl %edx, %esi
; X86-NEXT:    sbbl %edx, %edi
; X86-NEXT:    sbbl %edx, %ebx
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sbbl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    movl 8(%ebp), %edx
; X86-NEXT:    movl %eax, (%edx)
; X86-NEXT:    movl %ecx, 4(%edx)
; X86-NEXT:    movl %esi, 8(%edx)
; X86-NEXT:    movl %edi, 12(%edx)
; X86-NEXT:    movl %ebx, 16(%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 20(%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 24(%edx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 28(%edx)
; X86-NEXT:    movl %edx, %eax
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
; X86-NEXT:  .LBB5_19:
; X86-NEXT:    movb $1, %cl
; X86-NEXT:    jmp .LBB5_21
; X86-NEXT:  .LBB5_29:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    jmp .LBB5_27
; X86-NEXT:  .LBB5_24:
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    jmp .LBB5_31
;
; X64-LABEL: sdiv256_const:
; X64:       # %bb.0: # %_udiv-special-cases
; X64-NEXT:    pushq %rbp
; X64-NEXT:    pushq %r15
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %r13
; X64-NEXT:    pushq %r12
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $72, %rsp
; X64-NEXT:    movq %rcx, %r9
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    sarq $63, %rax
; X64-NEXT:    xorq %rax, %r8
; X64-NEXT:    xorq %rax, %r9
; X64-NEXT:    xorq %rax, %rdx
; X64-NEXT:    xorq %rax, %rsi
; X64-NEXT:    subq %rax, %rsi
; X64-NEXT:    sbbq %rax, %rdx
; X64-NEXT:    sbbq %rax, %r9
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    sbbq %rax, %r8
; X64-NEXT:    xorl %ebp, %ebp
; X64-NEXT:    movq %rdx, %rax
; X64-NEXT:    orq %r8, %rax
; X64-NEXT:    movq %rsi, %rcx
; X64-NEXT:    orq %r9, %rcx
; X64-NEXT:    bsrq %r8, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    bsrq %r9, %r10
; X64-NEXT:    xorq $63, %r10
; X64-NEXT:    orq $64, %r10
; X64-NEXT:    testq %r8, %r8
; X64-NEXT:    cmovneq %rdi, %r10
; X64-NEXT:    bsrq %rdx, %rdi
; X64-NEXT:    xorq $63, %rdi
; X64-NEXT:    bsrq %rsi, %r11
; X64-NEXT:    xorq $63, %r11
; X64-NEXT:    orq $64, %r11
; X64-NEXT:    testq %rdx, %rdx
; X64-NEXT:    cmovneq %rdi, %r11
; X64-NEXT:    orq $128, %r11
; X64-NEXT:    movq %r9, %rdi
; X64-NEXT:    orq %r8, %rdi
; X64-NEXT:    cmovneq %r10, %r11
; X64-NEXT:    movl $253, %edi
; X64-NEXT:    subq %r11, %rdi
; X64-NEXT:    movl $0, %r10d
; X64-NEXT:    sbbq %r10, %r10
; X64-NEXT:    movl $0, %r15d
; X64-NEXT:    sbbq %r15, %r15
; X64-NEXT:    sbbq %rbp, %rbp
; X64-NEXT:    orq %rax, %rcx
; X64-NEXT:    je .LBB5_1
; X64-NEXT:  # %bb.2: # %select.false.sink
; X64-NEXT:    xorl %eax, %eax
; X64-NEXT:    movl $255, %ecx
; X64-NEXT:    cmpq %rdi, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    sbbq %r10, %rcx
; X64-NEXT:    movl $0, %ecx
; X64-NEXT:    sbbq %r15, %rcx
; X64-NEXT:    sbbq %rbp, %rax
; X64-NEXT:    setb %al
; X64-NEXT:  .LBB5_3: # %select.end
; X64-NEXT:    xorl %ebx, %ebx
; X64-NEXT:    testb %al, %al
; X64-NEXT:    movq %rdx, %r12
; X64-NEXT:    cmovneq %rbx, %r12
; X64-NEXT:    movq %rsi, %r11
; X64-NEXT:    cmovneq %rbx, %r11
; X64-NEXT:    movq %r9, %r14
; X64-NEXT:    cmovneq %rbx, %r14
; X64-NEXT:    cmoveq %r8, %rbx
; X64-NEXT:    jne .LBB5_9
; X64-NEXT:  # %bb.4: # %select.end
; X64-NEXT:    movq %rdi, %rcx
; X64-NEXT:    xorq $255, %rcx
; X64-NEXT:    orq %r15, %rcx
; X64-NEXT:    movq %rdi, %r13
; X64-NEXT:    movq %r10, %rdi
; X64-NEXT:    orq %rbp, %r10
; X64-NEXT:    orq %rcx, %r10
; X64-NEXT:    je .LBB5_9
; X64-NEXT:  # %bb.5: # %udiv-bb1
; X64-NEXT:    movq %rbp, %r10
; X64-NEXT:    movq %rsi, {{[0-9]+}}(%rsp)
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, {{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, (%rsp)
; X64-NEXT:    movq %rdx, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r9, {{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, {{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r13d, %ecx
; X64-NEXT:    notb %cl
; X64-NEXT:    movl %ecx, %eax
; X64-NEXT:    shrb $3, %al
; X64-NEXT:    andb $24, %al
; X64-NEXT:    negb %al
; X64-NEXT:    movsbq %al, %rax
; X64-NEXT:    movq 48(%rsp,%rax), %r14
; X64-NEXT:    movq 56(%rsp,%rax), %rbx
; X64-NEXT:    shldq %cl, %r14, %rbx
; X64-NEXT:    movq 32(%rsp,%rax), %rbp
; X64-NEXT:    movq 40(%rsp,%rax), %r12
; X64-NEXT:    shldq %cl, %r12, %r14
; X64-NEXT:    shldq %cl, %rbp, %r12
; X64-NEXT:    shlq %cl, %rbp
; X64-NEXT:    addq $1, %r13
; X64-NEXT:    adcq $0, %rdi
; X64-NEXT:    movq %rdi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    adcq $0, %r15
; X64-NEXT:    adcq $0, %r10
; X64-NEXT:    jb .LBB5_10
; X64-NEXT:  # %bb.6: # %udiv-preheader
; X64-NEXT:    movq %r10, %rdi
; X64-NEXT:    movl $7, %r11d
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r9, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %r8, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r13d, %eax
; X64-NEXT:    shrb $6, %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    movq -40(%rsp,%rax,8), %rdx
; X64-NEXT:    movq %r13, %rcx
; X64-NEXT:    movq -48(%rsp,%rax,8), %r10
; X64-NEXT:    movq %r10, %rsi
; X64-NEXT:    shrdq %cl, %rdx, %rsi
; X64-NEXT:    movq -64(%rsp,%rax,8), %r8
; X64-NEXT:    movq -56(%rsp,%rax,8), %rax
; X64-NEXT:    movq %rax, %r9
; X64-NEXT:    shrdq %cl, %r10, %r9
; X64-NEXT:    shrq %cl, %rdx
; X64-NEXT:    movq %r13, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    # kill: def $cl killed $cl killed $rcx
; X64-NEXT:    shrdq %cl, %rax, %r8
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    addq $-1, %r11
; X64-NEXT:    movq %r11, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movl $0, %eax
; X64-NEXT:    adcq $-1, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movl $0, %eax
; X64-NEXT:    adcq $-1, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    movl $0, %eax
; X64-NEXT:    adcq $-1, %rax
; X64-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    xorl %r10d, %r10d
; X64-NEXT:    xorl %eax, %eax
; X64-NEXT:    xorl %r11d, %r11d
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; X64-NEXT:    .p2align 4
; X64-NEXT:  .LBB5_7: # %udiv-do-while
; X64-NEXT:    # =>This Inner Loop Header: Depth=1
; X64-NEXT:    shldq $1, %rsi, %rdx
; X64-NEXT:    shldq $1, %r9, %rsi
; X64-NEXT:    shldq $1, %r8, %r9
; X64-NEXT:    shldq $1, %rbx, %r8
; X64-NEXT:    shldq $1, %r14, %rbx
; X64-NEXT:    orq %r11, %rbx
; X64-NEXT:    shldq $1, %r12, %r14
; X64-NEXT:    orq %rax, %r14
; X64-NEXT:    shldq $1, %rbp, %r12
; X64-NEXT:    orq %r10, %r12
; X64-NEXT:    addq %rbp, %rbp
; X64-NEXT:    orq %rcx, %rbp
; X64-NEXT:    cmpq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Folded Reload
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    sbbq %r9, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    sbbq %rsi, %rax
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; X64-NEXT:    sbbq %rdx, %rcx
; X64-NEXT:    sarq $63, %rcx
; X64-NEXT:    movl $7, %eax
; X64-NEXT:    andl %ecx, %eax
; X64-NEXT:    # kill: def $ecx killed $ecx killed $rcx def $rcx
; X64-NEXT:    andl $1, %ecx
; X64-NEXT:    subq %rax, %r8
; X64-NEXT:    sbbq $0, %r9
; X64-NEXT:    sbbq $0, %rsi
; X64-NEXT:    sbbq $0, %rdx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r10 # 8-byte Reload
; X64-NEXT:    addq $-1, %r10
; X64-NEXT:    adcq $-1, %r13
; X64-NEXT:    adcq $-1, %r15
; X64-NEXT:    adcq $-1, %rdi
; X64-NEXT:    movq %r13, %rax
; X64-NEXT:    orq %rdi, %rax
; X64-NEXT:    movq %r10, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; X64-NEXT:    orq %r15, %r10
; X64-NEXT:    orq %rax, %r10
; X64-NEXT:    movl $0, %r10d
; X64-NEXT:    movl $0, %eax
; X64-NEXT:    movl $0, %r11d
; X64-NEXT:    jne .LBB5_7
; X64-NEXT:  .LBB5_8: # %udiv-loop-exit
; X64-NEXT:    shldq $1, %r14, %rbx
; X64-NEXT:    shldq $1, %r12, %r14
; X64-NEXT:    shldq $1, %rbp, %r12
; X64-NEXT:    leaq (%rcx,%rbp,2), %r11
; X64-NEXT:  .LBB5_9: # %udiv-end
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    xorq %rax, %rbx
; X64-NEXT:    xorq %rax, %r14
; X64-NEXT:    xorq %rax, %r12
; X64-NEXT:    xorq %rax, %r11
; X64-NEXT:    subq %rax, %r11
; X64-NEXT:    sbbq %rax, %r12
; X64-NEXT:    sbbq %rax, %r14
; X64-NEXT:    sbbq %rax, %rbx
; X64-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; X64-NEXT:    movq %r11, (%rax)
; X64-NEXT:    movq %r12, 8(%rax)
; X64-NEXT:    movq %r14, 16(%rax)
; X64-NEXT:    movq %rbx, 24(%rax)
; X64-NEXT:    addq $72, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r12
; X64-NEXT:    popq %r13
; X64-NEXT:    popq %r14
; X64-NEXT:    popq %r15
; X64-NEXT:    popq %rbp
; X64-NEXT:    retq
; X64-NEXT:  .LBB5_1:
; X64-NEXT:    movb $1, %al
; X64-NEXT:    jmp .LBB5_3
; X64-NEXT:  .LBB5_10:
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    jmp .LBB5_8
  %r = sdiv i256 %a, 7
  ret i256 %r
}
