; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64--     | FileCheck %s --check-prefix=X64
; RUN: llc < %s -mtriple=x86_64-- -O0 | FileCheck %s --check-prefix=X64-O0
; RUN: llc < %s -mtriple=i686--       | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=i686-- -O0   | FileCheck %s --check-prefix=X86-O0

define i129 @v_sdiv_i129_v_pow2k(i129 %lhs) nounwind {
; X64-LABEL: v_sdiv_i129_v_pow2k:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    andl $1, %edx
; X64-NEXT:    negq %rdx
; X64-NEXT:    movl %edx, %eax
; X64-NEXT:    andl $1, %eax
; X64-NEXT:    shldq $32, %rdx, %rax
; X64-NEXT:    addq %rdi, %rax
; X64-NEXT:    adcq $0, %rsi
; X64-NEXT:    adcq $0, %rcx
; X64-NEXT:    andl $1, %ecx
; X64-NEXT:    movq %rcx, %rdx
; X64-NEXT:    negq %rdx
; X64-NEXT:    shrdq $33, %rsi, %rax
; X64-NEXT:    shldq $31, %rsi, %rdx
; X64-NEXT:    retq
;
; X64-O0-LABEL: v_sdiv_i129_v_pow2k:
; X64-O0:       # %bb.0:
; X64-O0-NEXT:    movl %edx, %eax
; X64-O0-NEXT:    andl $1, %eax
; X64-O0-NEXT:    movl %eax, %ecx
; X64-O0-NEXT:    negq %rcx
; X64-O0-NEXT:    movl %ecx, %r8d
; X64-O0-NEXT:    andl $1, %r8d
; X64-O0-NEXT:    # implicit-def: $rax
; X64-O0-NEXT:    movl %r8d, %eax
; X64-O0-NEXT:    shldq $32, %rcx, %rax
; X64-O0-NEXT:    addq %rax, %rdi
; X64-O0-NEXT:    adcq $0, %rsi
; X64-O0-NEXT:    adcq $0, %rdx
; X64-O0-NEXT:    movl %edx, %eax
; X64-O0-NEXT:    andl $1, %eax
; X64-O0-NEXT:    movl %eax, %ecx
; X64-O0-NEXT:    movq %rcx, %rdx
; X64-O0-NEXT:    negq %rdx
; X64-O0-NEXT:    movq %rsi, %rax
; X64-O0-NEXT:    shldq $31, %rdi, %rax
; X64-O0-NEXT:    shldq $31, %rsi, %rdx
; X64-O0-NEXT:    retq
;
; X86-LABEL: v_sdiv_i129_v_pow2k:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl %ecx, %ebx
; X86-NEXT:    andl $1, %ebx
; X86-NEXT:    negl %ebx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl %ebx, %edi
; X86-NEXT:    andl $1, %edi
; X86-NEXT:    addl {{[0-9]+}}(%esp), %ebx
; X86-NEXT:    adcl {{[0-9]+}}(%esp), %edi
; X86-NEXT:    adcl $0, %esi
; X86-NEXT:    adcl $0, %edx
; X86-NEXT:    adcl $0, %ecx
; X86-NEXT:    movl %ecx, %ebx
; X86-NEXT:    andl $1, %ebx
; X86-NEXT:    movl %ebx, %ebp
; X86-NEXT:    negl %ebp
; X86-NEXT:    shldl $31, %edx, %ecx
; X86-NEXT:    shldl $31, %esi, %edx
; X86-NEXT:    shldl $31, %edi, %esi
; X86-NEXT:    movl %esi, (%eax)
; X86-NEXT:    movl %edx, 4(%eax)
; X86-NEXT:    movl %ecx, 8(%eax)
; X86-NEXT:    movl %ebp, 12(%eax)
; X86-NEXT:    movb %bl, 16(%eax)
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
;
; X86-O0-LABEL: v_sdiv_i129_v_pow2k:
; X86-O0:       # %bb.0:
; X86-O0-NEXT:    pushl %ebp
; X86-O0-NEXT:    pushl %ebx
; X86-O0-NEXT:    pushl %edi
; X86-O0-NEXT:    pushl %esi
; X86-O0-NEXT:    subl $8, %esp
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-O0-NEXT:    movl %ecx, %eax
; X86-O0-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-O0-NEXT:    movl %eax, (%esp) # 4-byte Spill
; X86-O0-NEXT:    movl %edi, %eax
; X86-O0-NEXT:    andl $1, %eax
; X86-O0-NEXT:    negl %eax
; X86-O0-NEXT:    movl %eax, %edx
; X86-O0-NEXT:    andl $1, %edx
; X86-O0-NEXT:    addl %eax, %esi
; X86-O0-NEXT:    movl (%esp), %eax # 4-byte Reload
; X86-O0-NEXT:    adcl %edx, %eax
; X86-O0-NEXT:    adcl $0, %ebp
; X86-O0-NEXT:    adcl $0, %ebx
; X86-O0-NEXT:    adcl $0, %edi
; X86-O0-NEXT:    movl %edi, %edx
; X86-O0-NEXT:    andl $1, %edx
; X86-O0-NEXT:    movl %edx, %esi
; X86-O0-NEXT:    negl %esi
; X86-O0-NEXT:    shldl $31, %ebx, %edi
; X86-O0-NEXT:    shldl $31, %ebp, %ebx
; X86-O0-NEXT:    shldl $31, %eax, %ebp
; X86-O0-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-O0-NEXT:    movl %ebp, (%ecx)
; X86-O0-NEXT:    movl %ebx, 4(%ecx)
; X86-O0-NEXT:    movl %edi, 8(%ecx)
; X86-O0-NEXT:    movl %esi, 12(%ecx)
; X86-O0-NEXT:    # kill: def $dl killed $dl killed $edx
; X86-O0-NEXT:    movb %dl, 16(%ecx)
; X86-O0-NEXT:    addl $8, %esp
; X86-O0-NEXT:    popl %esi
; X86-O0-NEXT:    popl %edi
; X86-O0-NEXT:    popl %ebx
; X86-O0-NEXT:    popl %ebp
; X86-O0-NEXT:    retl $4
  %div = sdiv i129 %lhs, 8589934592
  ret i129 %div
}

define i129 @v_sdiv_exact_i129_v_pow2k(i129 %lhs) nounwind {
; X64-LABEL: v_sdiv_exact_i129_v_pow2k:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdx, %rcx
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    andl $1, %ecx
; X64-NEXT:    movq %rcx, %rdx
; X64-NEXT:    negq %rdx
; X64-NEXT:    shrdq $33, %rsi, %rax
; X64-NEXT:    shldq $31, %rsi, %rdx
; X64-NEXT:    retq
;
; X64-O0-LABEL: v_sdiv_exact_i129_v_pow2k:
; X64-O0:       # %bb.0:
; X64-O0-NEXT:    movq %rsi, %rax
; X64-O0-NEXT:    shldq $31, %rdi, %rax
; X64-O0-NEXT:    movl %edx, %ecx
; X64-O0-NEXT:    andl $1, %ecx
; X64-O0-NEXT:    # kill: def $rcx killed $ecx
; X64-O0-NEXT:    movq %rcx, %rdx
; X64-O0-NEXT:    negq %rdx
; X64-O0-NEXT:    shldq $31, %rsi, %rdx
; X64-O0-NEXT:    retq
;
; X86-LABEL: v_sdiv_exact_i129_v_pow2k:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl %edx, %ecx
; X86-NEXT:    andl $1, %ecx
; X86-NEXT:    movl %ecx, %esi
; X86-NEXT:    negl %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X86-NEXT:    shrdl $1, %ebx, %edi
; X86-NEXT:    shldl $31, %ebp, %edx
; X86-NEXT:    shldl $31, %ebx, %ebp
; X86-NEXT:    movl %esi, 12(%eax)
; X86-NEXT:    movl %edx, 8(%eax)
; X86-NEXT:    movl %ebp, 4(%eax)
; X86-NEXT:    movl %edi, (%eax)
; X86-NEXT:    movb %cl, 16(%eax)
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl $4
;
; X86-O0-LABEL: v_sdiv_exact_i129_v_pow2k:
; X86-O0:       # %bb.0:
; X86-O0-NEXT:    pushl %ebp
; X86-O0-NEXT:    pushl %ebx
; X86-O0-NEXT:    pushl %edi
; X86-O0-NEXT:    pushl %esi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-O0-NEXT:    movl %ecx, %eax
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-O0-NEXT:    movl %edx, %edi
; X86-O0-NEXT:    shldl $31, %ebx, %edi
; X86-O0-NEXT:    shldl $31, %ebp, %ebx
; X86-O0-NEXT:    shldl $31, %esi, %ebp
; X86-O0-NEXT:    andl $1, %edx
; X86-O0-NEXT:    movl %edx, %esi
; X86-O0-NEXT:    negl %esi
; X86-O0-NEXT:    movl %ebp, (%ecx)
; X86-O0-NEXT:    movl %ebx, 4(%ecx)
; X86-O0-NEXT:    movl %edi, 8(%ecx)
; X86-O0-NEXT:    movl %esi, 12(%ecx)
; X86-O0-NEXT:    # kill: def $dl killed $dl killed $edx
; X86-O0-NEXT:    movb %dl, 16(%ecx)
; X86-O0-NEXT:    popl %esi
; X86-O0-NEXT:    popl %edi
; X86-O0-NEXT:    popl %ebx
; X86-O0-NEXT:    popl %ebp
; X86-O0-NEXT:    retl $4
  %div = sdiv exact i129 %lhs, 8589934592
  ret i129 %div
}

define i129 @v_udiv_i129_v_pow2k(i129 %lhs) nounwind {
; X64-LABEL: v_udiv_i129_v_pow2k:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    andl $1, %edx
; X64-NEXT:    shrdq $33, %rsi, %rax
; X64-NEXT:    shldq $31, %rsi, %rdx
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    retq
;
; X64-O0-LABEL: v_udiv_i129_v_pow2k:
; X64-O0:       # %bb.0:
; X64-O0-NEXT:    movq %rsi, %rax
; X64-O0-NEXT:    shldq $31, %rdi, %rax
; X64-O0-NEXT:    movl %edx, %ecx
; X64-O0-NEXT:    andl $1, %ecx
; X64-O0-NEXT:    movl %ecx, %edx
; X64-O0-NEXT:    shldq $31, %rsi, %rdx
; X64-O0-NEXT:    xorl %ecx, %ecx
; X64-O0-NEXT:    # kill: def $rcx killed $ecx
; X64-O0-NEXT:    retq
;
; X86-LABEL: v_udiv_i129_v_pow2k:
; X86:       # %bb.0:
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X86-NEXT:    shrdl $1, %esi, %edx
; X86-NEXT:    shldl $31, %edi, %ecx
; X86-NEXT:    shldl $31, %esi, %edi
; X86-NEXT:    movl %ecx, 8(%eax)
; X86-NEXT:    movl %edi, 4(%eax)
; X86-NEXT:    movl %edx, (%eax)
; X86-NEXT:    movl $0, 12(%eax)
; X86-NEXT:    movb $0, 16(%eax)
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    retl $4
;
; X86-O0-LABEL: v_udiv_i129_v_pow2k:
; X86-O0:       # %bb.0:
; X86-O0-NEXT:    pushl %ebx
; X86-O0-NEXT:    pushl %edi
; X86-O0-NEXT:    pushl %esi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-O0-NEXT:    movl %ecx, %eax
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-O0-NEXT:    shldl $31, %esi, %edx
; X86-O0-NEXT:    shldl $31, %edi, %esi
; X86-O0-NEXT:    shldl $31, %ebx, %edi
; X86-O0-NEXT:    movl %edi, (%ecx)
; X86-O0-NEXT:    movl %esi, 4(%ecx)
; X86-O0-NEXT:    movl %edx, 8(%ecx)
; X86-O0-NEXT:    movl $0, 12(%ecx)
; X86-O0-NEXT:    movb $0, 16(%ecx)
; X86-O0-NEXT:    popl %esi
; X86-O0-NEXT:    popl %edi
; X86-O0-NEXT:    popl %ebx
; X86-O0-NEXT:    retl $4
  %div = udiv i129 %lhs, 8589934592
  ret i129 %div
}

define i129 @v_udiv_exact_i129_v_pow2k(i129 %lhs) nounwind {
; X64-LABEL: v_udiv_exact_i129_v_pow2k:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdi, %rax
; X64-NEXT:    andl $1, %edx
; X64-NEXT:    shrdq $33, %rsi, %rax
; X64-NEXT:    shldq $31, %rsi, %rdx
; X64-NEXT:    xorl %ecx, %ecx
; X64-NEXT:    retq
;
; X64-O0-LABEL: v_udiv_exact_i129_v_pow2k:
; X64-O0:       # %bb.0:
; X64-O0-NEXT:    movq %rsi, %rax
; X64-O0-NEXT:    shldq $31, %rdi, %rax
; X64-O0-NEXT:    movl %edx, %ecx
; X64-O0-NEXT:    andl $1, %ecx
; X64-O0-NEXT:    movl %ecx, %edx
; X64-O0-NEXT:    shldq $31, %rsi, %rdx
; X64-O0-NEXT:    xorl %ecx, %ecx
; X64-O0-NEXT:    # kill: def $rcx killed $ecx
; X64-O0-NEXT:    retq
;
; X86-LABEL: v_udiv_exact_i129_v_pow2k:
; X86:       # %bb.0:
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X86-NEXT:    shrdl $1, %esi, %edx
; X86-NEXT:    shldl $31, %edi, %ecx
; X86-NEXT:    shldl $31, %esi, %edi
; X86-NEXT:    movl %ecx, 8(%eax)
; X86-NEXT:    movl %edi, 4(%eax)
; X86-NEXT:    movl %edx, (%eax)
; X86-NEXT:    movl $0, 12(%eax)
; X86-NEXT:    movb $0, 16(%eax)
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    retl $4
;
; X86-O0-LABEL: v_udiv_exact_i129_v_pow2k:
; X86-O0:       # %bb.0:
; X86-O0-NEXT:    pushl %ebx
; X86-O0-NEXT:    pushl %edi
; X86-O0-NEXT:    pushl %esi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-O0-NEXT:    movl %ecx, %eax
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %edx
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %edi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %esi
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-O0-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; X86-O0-NEXT:    shldl $31, %esi, %edx
; X86-O0-NEXT:    shldl $31, %edi, %esi
; X86-O0-NEXT:    shldl $31, %ebx, %edi
; X86-O0-NEXT:    movl %edi, (%ecx)
; X86-O0-NEXT:    movl %esi, 4(%ecx)
; X86-O0-NEXT:    movl %edx, 8(%ecx)
; X86-O0-NEXT:    movl $0, 12(%ecx)
; X86-O0-NEXT:    movb $0, 16(%ecx)
; X86-O0-NEXT:    popl %esi
; X86-O0-NEXT:    popl %edi
; X86-O0-NEXT:    popl %ebx
; X86-O0-NEXT:    retl $4
  %div = udiv exact i129 %lhs, 8589934592
  ret i129 %div
}
