# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=x86_64-- -run-pass x86-fixup-inst-tuning -mcpu=znver1 -o - %s | FileCheck %s
# RUN: llc -mtriple=x86_64-- -run-pass x86-fixup-inst-tuning -mcpu=znver3 -o - %s | FileCheck %s
# RUN: llc -mtriple=x86_64-- -run-pass x86-fixup-inst-tuning -mcpu=haswell -o - %s | FileCheck %s
# RUN: llc -mtriple=x86_64-- -run-pass x86-fixup-inst-tuning -mcpu=alderlake -o - %s | FileCheck %s

--- |
  define void @test_vpermq_0x44() { ret void }
  define void @test_vpermpd_0x44() { ret void }
  define void @test_vpermq_other_imm() { ret void }
...
---
name:            test_vpermq_0x44
body:             |
  bb.0:
    liveins: $ymm0
    ; CHECK-LABEL: name: test_vpermq_0x44
    ; CHECK: liveins: $ymm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $ymm0 = VINSERTI128rri $ymm0, $xmm0, 1
    ; CHECK-NEXT: RET64 $ymm0
    $ymm0 = VPERMQYri $ymm0, 68
    RET64 $ymm0
...
---
name:            test_vpermpd_0x44
body:             |
  bb.0:
    liveins: $ymm0
    ; CHECK-LABEL: name: test_vpermpd_0x44
    ; CHECK: liveins: $ymm0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $ymm0 = VINSERTF128rri $ymm0, $xmm0, 1
    ; CHECK-NEXT: RET64 $ymm0
    $ymm0 = VPERMPDYri $ymm0, 68
    RET64 $ymm0
...
---
name:            test_vpermq_other_imm
body:             |
  bb.0:
    liveins: $ymm0, $ymm1
    ; CHECK-LABEL: name: test_vpermq_other_imm
    ; CHECK: liveins: $ymm0, $ymm1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $ymm0 = VPERMQYri $ymm0, 228
    ; CHECK-NEXT: $ymm1 = VPERMQYri $ymm1, 0
    ; CHECK-NEXT: RET64 $ymm0, $ymm1
    $ymm0 = VPERMQYri $ymm0, 228
    $ymm1 = VPERMQYri $ymm1, 0
    RET64 $ymm0, $ymm1
...
