; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

; Test llvm.convert.to.arbitrary.fp intrinsic expansion.

declare i8 @llvm.convert.to.arbitrary.fp.i8.f32(float, metadata, metadata, i1)
declare i6 @llvm.convert.to.arbitrary.fp.i6.f32(float, metadata, metadata, i1)
declare i4 @llvm.convert.to.arbitrary.fp.i4.f32(float, metadata, metadata, i1)
declare <4 x i4> @llvm.convert.to.arbitrary.fp.v4i4.v4f32(<4 x float>, metadata, metadata, i1)
declare <2 x i8> @llvm.convert.to.arbitrary.fp.v2i8.v2f32(<2 x float>, metadata, metadata, i1)
declare <3 x i8> @llvm.convert.to.arbitrary.fp.v3i8.v3f32(<3 x float>, metadata, metadata, i1)
declare <4 x i8> @llvm.convert.to.arbitrary.fp.v4i8.v4f32(<4 x float>, metadata, metadata, i1)
declare <2 x i8> @llvm.convert.to.arbitrary.fp.v2i8.v2f16(<2 x half>, metadata, metadata, i1)

declare i8 @llvm.convert.to.arbitrary.fp.i8.f16(half, metadata, metadata, i1)
declare i8 @llvm.convert.to.arbitrary.fp.i8.bf16(bfloat, metadata, metadata, i1)
declare i8 @llvm.convert.to.arbitrary.fp.i8.f64(double, metadata, metadata, i1)

; Float8E5M2
; Layout: sign(1) exp(5) mant(2), bias=15
; Supports: Inf, NaN, signed zero, denormals

; Float8E5M2 dynamic input
define i8 @to_f8e5m2_dynamic(float %x) {
; CHECK-LABEL: to_f8e5m2_dynamic:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    movl $8, %ecx
; CHECK-NEXT:    subl %edx, %ecx
; CHECK-NEXT:    cmpl $31, %ecx
; CHECK-NEXT:    movl $31, %eax
; CHECK-NEXT:    cmovbl %ecx, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %esi
; CHECK-NEXT:    movl %esi, %edi
; CHECK-NEXT:    andl $8388607, %edi # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%rdi), %r8d
; CHECK-NEXT:    movl %r8d, %r9d
; CHECK-NEXT:    shrl %cl, %r9d
; CHECK-NEXT:    movl $1, %r10d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r10d
; CHECK-NEXT:    decl %r10d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl %r10d, %r8d
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r8d
; CHECK-NEXT:    movl %r8d, %r10d
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    orl %r11d, %r10d
; CHECK-NEXT:    andl %r9d, %r10d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ecx, %r10d
; CHECK-NEXT:    addl %r8d, %r10d
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpl $4, %r10d
; CHECK-NEXT:    cmovgel %ecx, %r10d
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 # 16-byte Reload
; CHECK-NEXT:    movd %xmm2, %eax
; CHECK-NEXT:    shrl $24, %eax
; CHECK-NEXT:    andl $-128, %eax
; CHECK-NEXT:    leal (%rax,%r8,4), %r8d
; CHECK-NEXT:    orl %r10d, %r8d
; CHECK-NEXT:    shrl $21, %edi
; CHECK-NEXT:    movl %edi, %r9d
; CHECK-NEXT:    andl $1, %r9d
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    testl $1048575, %esi # imm = 0xFFFFF
; CHECK-NEXT:    setne %r10b
; CHECK-NEXT:    orl %r9d, %r10d
; CHECK-NEXT:    shrl $20, %esi
; CHECK-NEXT:    andl %r10d, %esi
; CHECK-NEXT:    addl %edi, %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    cmpl $4, %esi
; CHECK-NEXT:    cmovgel %ecx, %esi
; CHECK-NEXT:    setge %dil
; CHECK-NEXT:    leal (%rdx,%rdi), %ecx
; CHECK-NEXT:    leal 56(,%rcx,4), %ecx
; CHECK-NEXT:    movl %eax, %r9d
; CHECK-NEXT:    orl %esi, %r9d
; CHECK-NEXT:    orl %ecx, %r9d
; CHECK-NEXT:    leal 14(%rdx,%rdi), %ecx
; CHECK-NEXT:    testl %ecx, %ecx
; CHECK-NEXT:    cmovlel %r8d, %r9d
; CHECK-NEXT:    cmpl $4, %esi
; CHECK-NEXT:    setge %dl
; CHECK-NEXT:    cmpl $30, %ecx
; CHECK-NEXT:    sete %sil
; CHECK-NEXT:    andb %dl, %sil
; CHECK-NEXT:    cmpl $31, %ecx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    orb %sil, %cl
; CHECK-NEXT:    leal 124(%rax), %edx
; CHECK-NEXT:    testb %cl, %cl
; CHECK-NEXT:    cmovnel %edx, %r9d
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    cmovnel %r9d, %eax
; CHECK-NEXT:    cmovpl %r9d, %eax
; CHECK-NEXT:    movaps {{.*#+}} xmm1 = [NaN,NaN,NaN,NaN]
; CHECK-NEXT:    andps %xmm2, %xmm1
; CHECK-NEXT:    ucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovnel %eax, %edx
; CHECK-NEXT:    cmovpl %eax, %edx
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    movl $126, %eax
; CHECK-NEXT:    cmovnpl %edx, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float %x, metadata !"Float8E5M2", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; Rounding tests

; Round toward zero
define i8 @to_f8e5m2_round_towardzero(float %x) {
; CHECK-LABEL: to_f8e5m2_round_towardzero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    movl $8, %eax
; CHECK-NEXT:    subl %edx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovbl %eax, %ecx
; CHECK-NEXT:    movd %xmm0, %esi
; CHECK-NEXT:    andl $8388607, %esi # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%rsi), %edi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpl $4, %edi
; CHECK-NEXT:    cmovgel %ecx, %edi
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 # 16-byte Reload
; CHECK-NEXT:    movd %xmm2, %eax
; CHECK-NEXT:    shrl $24, %eax
; CHECK-NEXT:    andl $-128, %eax
; CHECK-NEXT:    leal (%rax,%r8,4), %r8d
; CHECK-NEXT:    orl %edi, %r8d
; CHECK-NEXT:    shrl $21, %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    cmpl $4, %esi
; CHECK-NEXT:    cmovgel %ecx, %esi
; CHECK-NEXT:    setge %dil
; CHECK-NEXT:    leal (%rdx,%rdi), %ecx
; CHECK-NEXT:    leal 56(,%rcx,4), %ecx
; CHECK-NEXT:    orl %eax, %ecx
; CHECK-NEXT:    orl %esi, %ecx
; CHECK-NEXT:    leal 14(%rdx,%rdi), %edx
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    cmovlel %r8d, %ecx
; CHECK-NEXT:    cmpl $4, %esi
; CHECK-NEXT:    setge %sil
; CHECK-NEXT:    cmpl $30, %edx
; CHECK-NEXT:    sete %dil
; CHECK-NEXT:    andb %sil, %dil
; CHECK-NEXT:    cmpl $31, %edx
; CHECK-NEXT:    setge %dl
; CHECK-NEXT:    orb %dil, %dl
; CHECK-NEXT:    leal 124(%rax), %esi
; CHECK-NEXT:    testb %dl, %dl
; CHECK-NEXT:    cmovnel %esi, %ecx
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    cmovnel %ecx, %eax
; CHECK-NEXT:    cmovpl %ecx, %eax
; CHECK-NEXT:    movaps {{.*#+}} xmm1 = [NaN,NaN,NaN,NaN]
; CHECK-NEXT:    andps %xmm2, %xmm1
; CHECK-NEXT:    ucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovnel %eax, %esi
; CHECK-NEXT:    cmovpl %eax, %esi
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    movl $126, %eax
; CHECK-NEXT:    cmovnpl %esi, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f32(float %x, metadata !"Float8E5M2", metadata !"round.towardzero", i1 false)
  ret i8 %r
}

; <4 x float> to <4 x i4> (Float4E2M1FN)
define <4 x i4> @to_f4e2m1fn_v4f32(<4 x float> %x) {
; CHECK-LABEL: to_f4e2m1fn_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $88, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 96
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; CHECK-NEXT:    movq %rsp, %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movd {{.*#+}} xmm1 = mem[0],zero,zero,zero
; CHECK-NEXT:    movd {{.*#+}} xmm2 = mem[0],zero,zero,zero
; CHECK-NEXT:    punpckldq {{.*#+}} xmm2 = xmm2[0],xmm1[0],xmm2[1],xmm1[1]
; CHECK-NEXT:    movd {{.*#+}} xmm1 = mem[0],zero,zero,zero
; CHECK-NEXT:    movd {{.*#+}} xmm3 = mem[0],zero,zero,zero
; CHECK-NEXT:    punpckldq {{.*#+}} xmm1 = xmm1[0],xmm3[0],xmm1[1],xmm3[1]
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm2[0]
; CHECK-NEXT:    movdqa {{.*#+}} xmm2 = [23,23,23,23]
; CHECK-NEXT:    psubd %xmm1, %xmm2
; CHECK-NEXT:    movdqa {{.*#+}} xmm4 = [2147483648,2147483648,2147483648,2147483648]
; CHECK-NEXT:    movdqa %xmm2, %xmm5
; CHECK-NEXT:    pxor %xmm4, %xmm5
; CHECK-NEXT:    movdqa {{.*#+}} xmm3 = [2147483679,2147483679,2147483679,2147483679]
; CHECK-NEXT:    pcmpgtd %xmm5, %xmm3
; CHECK-NEXT:    movdqa %xmm5, %xmm6
; CHECK-NEXT:    pcmpgtd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm6
; CHECK-NEXT:    pandn %xmm2, %xmm6
; CHECK-NEXT:    pcmpeqd %xmm5, %xmm5
; CHECK-NEXT:    pxor %xmm5, %xmm3
; CHECK-NEXT:    psrld $27, %xmm3
; CHECK-NEXT:    por %xmm6, %xmm3
; CHECK-NEXT:    pxor %xmm2, %xmm2
; CHECK-NEXT:    movdqa %xmm3, %xmm7
; CHECK-NEXT:    pcmpeqd %xmm2, %xmm7
; CHECK-NEXT:    pxor %xmm5, %xmm7
; CHECK-NEXT:    paddd %xmm3, %xmm7
; CHECK-NEXT:    pshuflw {{.*#+}} xmm9 = xmm7[2,3,3,3,4,5,6,7]
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm6 # 16-byte Reload
; CHECK-NEXT:    unpcklps {{.*#+}} xmm6 = xmm6[0],xmm0[0],xmm6[1],xmm0[1]
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm14 # 16-byte Reload
; CHECK-NEXT:    unpcklps {{[-0-9]+}}(%r{{[sb]}}p), %xmm14 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm14 = xmm14[0],mem[0],xmm14[1],mem[1]
; CHECK-NEXT:    movlhps {{.*#+}} xmm14 = xmm14[0],xmm6[0]
; CHECK-NEXT:    movaps {{.*#+}} xmm0 = [8388607,8388607,8388607,8388607]
; CHECK-NEXT:    andps %xmm14, %xmm0
; CHECK-NEXT:    movaps {{.*#+}} xmm8 = [8388608,8388608,8388608,8388608]
; CHECK-NEXT:    orps %xmm0, %xmm8
; CHECK-NEXT:    movaps %xmm8, %xmm6
; CHECK-NEXT:    movaps %xmm8, %xmm10
; CHECK-NEXT:    movaps %xmm8, %xmm11
; CHECK-NEXT:    movaps %xmm8, %xmm12
; CHECK-NEXT:    movaps %xmm8, %xmm13
; CHECK-NEXT:    psrld %xmm9, %xmm13
; CHECK-NEXT:    pshuflw {{.*#+}} xmm9 = xmm7[0,1,1,1,4,5,6,7]
; CHECK-NEXT:    psrld %xmm9, %xmm6
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm6 = xmm6[0],xmm13[0]
; CHECK-NEXT:    pshufd {{.*#+}} xmm13 = xmm7[2,3,2,3]
; CHECK-NEXT:    pshuflw {{.*#+}} xmm9 = xmm13[2,3,3,3,4,5,6,7]
; CHECK-NEXT:    psrld %xmm9, %xmm10
; CHECK-NEXT:    movaps %xmm8, %xmm9
; CHECK-NEXT:    pslld $23, %xmm7
; CHECK-NEXT:    paddd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm7 # [1065353216,1065353216,1065353216,1065353216]
; CHECK-NEXT:    cvttps2dq %xmm7, %xmm7
; CHECK-NEXT:    paddd %xmm5, %xmm7
; CHECK-NEXT:    movaps %xmm8, %xmm5
; CHECK-NEXT:    pand %xmm8, %xmm7
; CHECK-NEXT:    pshuflw {{.*#+}} xmm13 = xmm13[0,1,1,1,4,5,6,7]
; CHECK-NEXT:    psrld %xmm13, %xmm11
; CHECK-NEXT:    punpckhqdq {{.*#+}} xmm11 = xmm11[1],xmm10[1]
; CHECK-NEXT:    shufps {{.*#+}} xmm6 = xmm6[0,3],xmm11[0,3]
; CHECK-NEXT:    pshuflw {{.*#+}} xmm10 = xmm3[2,3,3,3,4,5,6,7]
; CHECK-NEXT:    psrld %xmm10, %xmm12
; CHECK-NEXT:    pshuflw {{.*#+}} xmm10 = xmm3[0,1,1,1,4,5,6,7]
; CHECK-NEXT:    psrld %xmm10, %xmm9
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm9 = xmm9[0],xmm12[0]
; CHECK-NEXT:    pshufd {{.*#+}} xmm10 = xmm3[2,3,2,3]
; CHECK-NEXT:    pshuflw {{.*#+}} xmm11 = xmm10[2,3,3,3,4,5,6,7]
; CHECK-NEXT:    psrld %xmm11, %xmm5
; CHECK-NEXT:    pshuflw {{.*#+}} xmm10 = xmm10[0,1,1,1,4,5,6,7]
; CHECK-NEXT:    psrld %xmm10, %xmm8
; CHECK-NEXT:    punpckhqdq {{.*#+}} xmm8 = xmm8[1],xmm5[1]
; CHECK-NEXT:    shufps {{.*#+}} xmm9 = xmm9[0,3],xmm8[0,3]
; CHECK-NEXT:    pcmpgtd %xmm2, %xmm7
; CHECK-NEXT:    por %xmm9, %xmm7
; CHECK-NEXT:    pxor %xmm4, %xmm3
; CHECK-NEXT:    pcmpgtd %xmm4, %xmm3
; CHECK-NEXT:    pand %xmm6, %xmm3
; CHECK-NEXT:    movdqa {{.*#+}} xmm4 = [1,1,1,1]
; CHECK-NEXT:    pand %xmm4, %xmm3
; CHECK-NEXT:    pand %xmm7, %xmm3
; CHECK-NEXT:    paddd %xmm9, %xmm3
; CHECK-NEXT:    movdqa %xmm3, %xmm6
; CHECK-NEXT:    pcmpgtd %xmm4, %xmm6
; CHECK-NEXT:    movdqa %xmm6, %xmm5
; CHECK-NEXT:    pandn %xmm3, %xmm5
; CHECK-NEXT:    psrld $31, %xmm6
; CHECK-NEXT:    paddd %xmm6, %xmm6
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm7 # 16-byte Reload
; CHECK-NEXT:    movdqa %xmm7, %xmm3
; CHECK-NEXT:    psrld $31, %xmm3
; CHECK-NEXT:    pslld $3, %xmm3
; CHECK-NEXT:    por %xmm3, %xmm5
; CHECK-NEXT:    por %xmm6, %xmm5
; CHECK-NEXT:    movaps {{.*#+}} xmm6 = [2097151,2097151,2097151,2097151]
; CHECK-NEXT:    movaps %xmm14, %xmm8
; CHECK-NEXT:    andps %xmm14, %xmm6
; CHECK-NEXT:    pcmpgtd %xmm2, %xmm6
; CHECK-NEXT:    psrld $22, %xmm0
; CHECK-NEXT:    por %xmm0, %xmm6
; CHECK-NEXT:    psrld $21, %xmm8
; CHECK-NEXT:    pand %xmm4, %xmm8
; CHECK-NEXT:    pand %xmm6, %xmm8
; CHECK-NEXT:    paddd %xmm0, %xmm8
; CHECK-NEXT:    movdqa %xmm8, %xmm0
; CHECK-NEXT:    pcmpgtd %xmm4, %xmm0
; CHECK-NEXT:    paddd %xmm0, %xmm1
; CHECK-NEXT:    pcmpgtd %xmm1, %xmm4
; CHECK-NEXT:    pand %xmm4, %xmm5
; CHECK-NEXT:    pandn %xmm8, %xmm0
; CHECK-NEXT:    paddd %xmm1, %xmm1
; CHECK-NEXT:    por %xmm3, %xmm0
; CHECK-NEXT:    por %xmm1, %xmm0
; CHECK-NEXT:    pandn %xmm0, %xmm4
; CHECK-NEXT:    por %xmm5, %xmm4
; CHECK-NEXT:    movdqa %xmm7, %xmm0
; CHECK-NEXT:    cmpeqps %xmm2, %xmm0
; CHECK-NEXT:    pand %xmm0, %xmm3
; CHECK-NEXT:    pandn %xmm4, %xmm0
; CHECK-NEXT:    por %xmm3, %xmm0
; CHECK-NEXT:    addq $88, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <4 x i4> @llvm.convert.to.arbitrary.fp.v4i4.v4f32(<4 x float> %x, metadata !"Float4E2M1FN", metadata !"round.tonearest", i1 false)
  ret <4 x i4> %r
}

; f32 <2 x float> -> <2 x i8> Float8E5M2
define <2 x i8> @to_f8e5m2_v2f32(<2 x float> %x) {
; CHECK-LABEL: to_f8e5m2_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    subq $56, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 112
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $8, %ebx
; CHECK-NEXT:    movl $8, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r15d
; CHECK-NEXT:    movl %r15d, %r12d
; CHECK-NEXT:    andl $8388607, %r12d # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%r12), %ebp
; CHECK-NEXT:    movl %ebp, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %r14d
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %ebp
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %ebp
; CHECK-NEXT:    movl %ebp, %r13d
; CHECK-NEXT:    andl $1, %r13d
; CHECK-NEXT:    orl %edi, %r13d
; CHECK-NEXT:    andl %edx, %r13d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ecx, %r13d
; CHECK-NEXT:    movq %rsp, %rdi
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl (%rsp), %eax
; CHECK-NEXT:    subl %eax, %ebx
; CHECK-NEXT:    cmpl $31, %ebx
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %ebx
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    movl %edx, %esi
; CHECK-NEXT:    andl $8388607, %esi # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%rsi), %edi
; CHECK-NEXT:    movl %edi, %r8d
; CHECK-NEXT:    shrl %cl, %r8d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r14d
; CHECK-NEXT:    decl %r14d
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    testl %r14d, %edi
; CHECK-NEXT:    setne %r9b
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    movl %edi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    orl %r9d, %ecx
; CHECK-NEXT:    andl %r8d, %ecx
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl $0, %r9d
; CHECK-NEXT:    cmovbl %r9d, %ecx
; CHECK-NEXT:    addl %ebp, %r13d
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpl $4, %r13d
; CHECK-NEXT:    cmovgel %r9d, %r13d
; CHECK-NEXT:    movl $0, %ebp
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 # 16-byte Reload
; CHECK-NEXT:    movd %xmm2, %r9d
; CHECK-NEXT:    shrl $24, %r9d
; CHECK-NEXT:    andl $-128, %r9d
; CHECK-NEXT:    leal (%r9,%r8,4), %r8d
; CHECK-NEXT:    orl %r13d, %r8d
; CHECK-NEXT:    shrl $21, %r12d
; CHECK-NEXT:    movl %r12d, %r10d
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $1048575, %r15d # imm = 0xFFFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %r10d, %r11d
; CHECK-NEXT:    shrl $20, %r15d
; CHECK-NEXT:    andl %r11d, %r15d
; CHECK-NEXT:    addl %r12d, %r15d
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    cmpl $4, %r15d
; CHECK-NEXT:    cmovgel %ebp, %r15d
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; CHECK-NEXT:    leal (%r14,%r10), %r11d
; CHECK-NEXT:    leal 56(,%r11,4), %r11d
; CHECK-NEXT:    movl %r9d, %ebx
; CHECK-NEXT:    orl %r15d, %ebx
; CHECK-NEXT:    orl %r11d, %ebx
; CHECK-NEXT:    leal 14(%r14,%r10), %r10d
; CHECK-NEXT:    testl %r10d, %r10d
; CHECK-NEXT:    cmovlel %r8d, %ebx
; CHECK-NEXT:    cmpl $4, %r15d
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    cmpl $30, %r10d
; CHECK-NEXT:    sete %r11b
; CHECK-NEXT:    andb %r8b, %r11b
; CHECK-NEXT:    cmpl $31, %r10d
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    orb %r11b, %r10b
; CHECK-NEXT:    leal 124(%r9), %r8d
; CHECK-NEXT:    testb %r10b, %r10b
; CHECK-NEXT:    cmovnel %r8d, %ebx
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    cmovnel %ebx, %r9d
; CHECK-NEXT:    cmovpl %ebx, %r9d
; CHECK-NEXT:    movaps {{.*#+}} xmm1 = [NaN,NaN,NaN,NaN]
; CHECK-NEXT:    movaps %xmm2, %xmm3
; CHECK-NEXT:    movaps %xmm2, %xmm4
; CHECK-NEXT:    andps %xmm1, %xmm3
; CHECK-NEXT:    movss {{.*#+}} xmm2 = [+Inf,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    ucomiss %xmm2, %xmm3
; CHECK-NEXT:    cmovnel %r9d, %r8d
; CHECK-NEXT:    cmovpl %r9d, %r8d
; CHECK-NEXT:    ucomiss %xmm0, %xmm4
; CHECK-NEXT:    movl $126, %r9d
; CHECK-NEXT:    cmovpl %r9d, %r8d
; CHECK-NEXT:    addl %edi, %ecx
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    cmpl $4, %ecx
; CHECK-NEXT:    cmovgel %ebp, %ecx
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm3 # 16-byte Reload
; CHECK-NEXT:    movd %xmm3, %edi
; CHECK-NEXT:    shrl $24, %edi
; CHECK-NEXT:    andl $-128, %edi
; CHECK-NEXT:    leal (%rdi,%r10,4), %r10d
; CHECK-NEXT:    orl %ecx, %r10d
; CHECK-NEXT:    shrl $21, %esi
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $1048575, %edx # imm = 0xFFFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %ecx, %r11d
; CHECK-NEXT:    shrl $20, %edx
; CHECK-NEXT:    andl %r11d, %edx
; CHECK-NEXT:    addl %esi, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $4, %edx
; CHECK-NEXT:    cmovgel %ebp, %edx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    leal (%rax,%rcx), %esi
; CHECK-NEXT:    leal 56(,%rsi,4), %esi
; CHECK-NEXT:    movl %edi, %r11d
; CHECK-NEXT:    orl %edx, %r11d
; CHECK-NEXT:    orl %esi, %r11d
; CHECK-NEXT:    leal 14(%rax,%rcx), %eax
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    cmovlel %r10d, %r11d
; CHECK-NEXT:    cmpl $4, %edx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    cmpl $30, %eax
; CHECK-NEXT:    sete %dl
; CHECK-NEXT:    andb %cl, %dl
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    leal 124(%rdi), %ecx
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    cmovnel %ecx, %r11d
; CHECK-NEXT:    ucomiss %xmm0, %xmm3
; CHECK-NEXT:    cmovnel %r11d, %edi
; CHECK-NEXT:    cmovpl %r11d, %edi
; CHECK-NEXT:    andps %xmm3, %xmm1
; CHECK-NEXT:    ucomiss %xmm2, %xmm1
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    cmovpl %edi, %ecx
; CHECK-NEXT:    ucomiss %xmm0, %xmm3
; CHECK-NEXT:    cmovpl %r9d, %ecx
; CHECK-NEXT:    movzbl %cl, %eax
; CHECK-NEXT:    shll $8, %r8d
; CHECK-NEXT:    orl %eax, %r8d
; CHECK-NEXT:    movd %r8d, %xmm0
; CHECK-NEXT:    addq $56, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <2 x i8> @llvm.convert.to.arbitrary.fp.v2i8.v2f32(<2 x float> %x, metadata !"Float8E5M2", metadata !"round.tonearest", i1 false)
  ret <2 x i8> %r
}

; <2 x float> -> <2 x i8> Float8E4M3FN
define <2 x i8> @to_f8e4m3fn_v2f32(<2 x float> %x) {
; CHECK-LABEL: to_f8e4m3fn_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    subq $56, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 112
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    movq %rsp, %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl (%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $15, %ebx
; CHECK-NEXT:    movl $15, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r15d
; CHECK-NEXT:    movl %r15d, %r12d
; CHECK-NEXT:    andl $8388607, %r12d # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%r12), %ebp
; CHECK-NEXT:    movl %ebp, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %r14d
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %ebp
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %ebp
; CHECK-NEXT:    movl %ebp, %r13d
; CHECK-NEXT:    andl $1, %r13d
; CHECK-NEXT:    orl %edi, %r13d
; CHECK-NEXT:    andl %edx, %r13d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ecx, %r13d
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    subl %eax, %ebx
; CHECK-NEXT:    cmpl $31, %ebx
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %ebx
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    movl %edx, %esi
; CHECK-NEXT:    andl $8388607, %esi # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%rsi), %edi
; CHECK-NEXT:    movl %edi, %r8d
; CHECK-NEXT:    shrl %cl, %r8d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r14d
; CHECK-NEXT:    decl %r14d
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    testl %r14d, %edi
; CHECK-NEXT:    setne %r9b
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    movl %edi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    orl %r9d, %ecx
; CHECK-NEXT:    andl %r8d, %ecx
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl $0, %r9d
; CHECK-NEXT:    cmovbl %r9d, %ecx
; CHECK-NEXT:    addl %ebp, %r13d
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpl $8, %r13d
; CHECK-NEXT:    cmovgel %r9d, %r13d
; CHECK-NEXT:    movl $0, %ebx
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %r9d
; CHECK-NEXT:    shrl $24, %r9d
; CHECK-NEXT:    andl $-128, %r9d
; CHECK-NEXT:    leal (%r9,%r8,8), %r8d
; CHECK-NEXT:    orl %r13d, %r8d
; CHECK-NEXT:    shrl $20, %r12d
; CHECK-NEXT:    movl %r12d, %r10d
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $524287, %r15d # imm = 0x7FFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %r10d, %r11d
; CHECK-NEXT:    shrl $19, %r15d
; CHECK-NEXT:    andl %r11d, %r15d
; CHECK-NEXT:    addl %r12d, %r15d
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    cmpl $8, %r15d
; CHECK-NEXT:    cmovgel %ebx, %r15d
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; CHECK-NEXT:    leal (%r14,%r10), %r11d
; CHECK-NEXT:    leal 48(,%r11,8), %r11d
; CHECK-NEXT:    orl %r9d, %r15d
; CHECK-NEXT:    orl %r11d, %r15d
; CHECK-NEXT:    leal 6(%r14,%r10), %r10d
; CHECK-NEXT:    testl %r10d, %r10d
; CHECK-NEXT:    cmovlel %r8d, %r15d
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %r15d, %r9d
; CHECK-NEXT:    cmovpl %r15d, %r9d
; CHECK-NEXT:    movl $127, %r8d
; CHECK-NEXT:    cmovpl %r8d, %r9d
; CHECK-NEXT:    movzbl %r9b, %r9d
; CHECK-NEXT:    addl %edi, %ecx
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    cmpl $8, %ecx
; CHECK-NEXT:    cmovgel %ebx, %ecx
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %edi
; CHECK-NEXT:    shrl $24, %edi
; CHECK-NEXT:    andl $-128, %edi
; CHECK-NEXT:    leal (%rdi,%r10,8), %r10d
; CHECK-NEXT:    orl %ecx, %r10d
; CHECK-NEXT:    shrl $20, %esi
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $524287, %edx # imm = 0x7FFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %ecx, %r11d
; CHECK-NEXT:    shrl $19, %edx
; CHECK-NEXT:    andl %r11d, %edx
; CHECK-NEXT:    addl %esi, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $8, %edx
; CHECK-NEXT:    cmovgel %ebx, %edx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    leal (%rax,%rcx), %esi
; CHECK-NEXT:    leal 48(,%rsi,8), %esi
; CHECK-NEXT:    orl %edi, %edx
; CHECK-NEXT:    orl %esi, %edx
; CHECK-NEXT:    leal 6(%rax,%rcx), %eax
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    cmovlel %r10d, %edx
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %edx, %edi
; CHECK-NEXT:    cmovpl %edx, %edi
; CHECK-NEXT:    cmovpl %r8d, %edi
; CHECK-NEXT:    shll $8, %edi
; CHECK-NEXT:    orl %r9d, %edi
; CHECK-NEXT:    movd %edi, %xmm0
; CHECK-NEXT:    addq $56, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <2 x i8> @llvm.convert.to.arbitrary.fp.v2i8.v2f32(<2 x float> %x, metadata !"Float8E4M3FN", metadata !"round.tonearest", i1 false)
  ret <2 x i8> %r
}

; <3 x float> -> <3 x i8> Float8E4M3FN
define <3 x i8> @to_f8e4m3fn_v3f32(<3 x float> %x) {
; CHECK-LABEL: to_f8e4m3fn_v3f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    subq $104, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 160
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $15, %ebx
; CHECK-NEXT:    movl $15, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    movl $31, %r15d
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r13d
; CHECK-NEXT:    movl %r13d, %edx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %ebp
; CHECK-NEXT:    movl %ebp, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %ebp
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %ebp
; CHECK-NEXT:    movl %ebp, %r14d
; CHECK-NEXT:    andl $1, %r14d
; CHECK-NEXT:    orl %edi, %r14d
; CHECK-NEXT:    andl %edx, %r14d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ecx, %r14d
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $15, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    cmovael %r15d, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r15d
; CHECK-NEXT:    movl %r15d, %edx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %r12d
; CHECK-NEXT:    movl %r12d, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %r12d
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r12d
; CHECK-NEXT:    movl %r12d, (%rsp) # 4-byte Spill
; CHECK-NEXT:    andl $1, %r12d
; CHECK-NEXT:    orl %edi, %r12d
; CHECK-NEXT:    andl %edx, %r12d
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbl %eax, %r12d
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    punpckhqdq {{.*#+}} xmm0 = xmm0[1,1]
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %esi
; CHECK-NEXT:    subl %esi, %ebx
; CHECK-NEXT:    cmpl $31, %ebx
; CHECK-NEXT:    movl $31, %eax
; CHECK-NEXT:    cmovael %eax, %ebx
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %edi
; CHECK-NEXT:    movl %edi, %r8d
; CHECK-NEXT:    andl $8388607, %r8d # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%r8), %r9d
; CHECK-NEXT:    movl %r9d, %eax
; CHECK-NEXT:    shrl %cl, %eax
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    movl $1, %edx
; CHECK-NEXT:    shll %cl, %edx
; CHECK-NEXT:    decl %edx
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    testl %ecx, %r9d
; CHECK-NEXT:    setne %dl
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    shrl %cl, %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    orl %edx, %r10d
; CHECK-NEXT:    andl %eax, %r10d
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbl %eax, %r10d
; CHECK-NEXT:    addl %ebp, %r14d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $8, %r14d
; CHECK-NEXT:    cmovgel %eax, %r14d
; CHECK-NEXT:    movl $0, %ebp
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    shrl $24, %eax
; CHECK-NEXT:    andl $-128, %eax
; CHECK-NEXT:    leal (%rax,%rcx,8), %ecx
; CHECK-NEXT:    orl %r14d, %ecx
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; CHECK-NEXT:    shrl $20, %r11d
; CHECK-NEXT:    movl %r11d, %edx
; CHECK-NEXT:    movq %r11, %rbx
; CHECK-NEXT:    andl $1, %edx
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $524287, %r13d # imm = 0x7FFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %edx, %r11d
; CHECK-NEXT:    shrl $19, %r13d
; CHECK-NEXT:    andl %r11d, %r13d
; CHECK-NEXT:    addl %ebx, %r13d
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    cmpl $8, %r13d
; CHECK-NEXT:    cmovgel %ebp, %r13d
; CHECK-NEXT:    setge %dl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Reload
; CHECK-NEXT:    leal (%rbx,%rdx), %r11d
; CHECK-NEXT:    leal 48(,%r11,8), %r11d
; CHECK-NEXT:    orl %eax, %r13d
; CHECK-NEXT:    orl %r11d, %r13d
; CHECK-NEXT:    leal 6(%rbx,%rdx), %edx
; CHECK-NEXT:    testl %edx, %edx
; CHECK-NEXT:    cmovlel %ecx, %r13d
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %r13d, %eax
; CHECK-NEXT:    cmovpl %r13d, %eax
; CHECK-NEXT:    movl $127, %r11d
; CHECK-NEXT:    cmovpl %r11d, %eax
; CHECK-NEXT:    addl (%rsp), %r12d # 4-byte Folded Reload
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $8, %r12d
; CHECK-NEXT:    movl $0, %r13d
; CHECK-NEXT:    cmovgel %r13d, %r12d
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %edx
; CHECK-NEXT:    shrl $24, %edx
; CHECK-NEXT:    andl $-128, %edx
; CHECK-NEXT:    leal (%rdx,%rcx,8), %ecx
; CHECK-NEXT:    orl %r12d, %ecx
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; CHECK-NEXT:    shrl $20, %r14d
; CHECK-NEXT:    movl %r14d, %ebx
; CHECK-NEXT:    andl $1, %ebx
; CHECK-NEXT:    xorl %ebp, %ebp
; CHECK-NEXT:    testl $524287, %r15d # imm = 0x7FFFF
; CHECK-NEXT:    setne %bpl
; CHECK-NEXT:    orl %ebx, %ebp
; CHECK-NEXT:    shrl $19, %r15d
; CHECK-NEXT:    andl %ebp, %r15d
; CHECK-NEXT:    addl %r14d, %r15d
; CHECK-NEXT:    xorl %ebx, %ebx
; CHECK-NEXT:    cmpl $8, %r15d
; CHECK-NEXT:    cmovgel %r13d, %r15d
; CHECK-NEXT:    setge %bl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; CHECK-NEXT:    leal (%r12,%rbx), %r14d
; CHECK-NEXT:    leal 48(,%r14,8), %ebp
; CHECK-NEXT:    orl %edx, %r15d
; CHECK-NEXT:    orl %ebp, %r15d
; CHECK-NEXT:    leal 6(%r12,%rbx), %ebx
; CHECK-NEXT:    testl %ebx, %ebx
; CHECK-NEXT:    cmovlel %ecx, %r15d
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %r15d, %edx
; CHECK-NEXT:    cmovpl %r15d, %edx
; CHECK-NEXT:    cmovpl %r11d, %edx
; CHECK-NEXT:    addl %r9d, %r10d
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    cmpl $8, %r10d
; CHECK-NEXT:    cmovgel %r13d, %r10d
; CHECK-NEXT:    setge %r9b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %ecx
; CHECK-NEXT:    shrl $24, %ecx
; CHECK-NEXT:    andl $-128, %ecx
; CHECK-NEXT:    leal (%rcx,%r9,8), %r9d
; CHECK-NEXT:    orl %r10d, %r9d
; CHECK-NEXT:    shrl $20, %r8d
; CHECK-NEXT:    movl %r8d, %r10d
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    xorl %ebx, %ebx
; CHECK-NEXT:    testl $524287, %edi # imm = 0x7FFFF
; CHECK-NEXT:    setne %bl
; CHECK-NEXT:    orl %r10d, %ebx
; CHECK-NEXT:    shrl $19, %edi
; CHECK-NEXT:    andl %ebx, %edi
; CHECK-NEXT:    addl %r8d, %edi
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpl $8, %edi
; CHECK-NEXT:    cmovgel %r13d, %edi
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    leal (%rsi,%r8), %r10d
; CHECK-NEXT:    leal 48(,%r10,8), %r10d
; CHECK-NEXT:    orl %ecx, %edi
; CHECK-NEXT:    orl %r10d, %edi
; CHECK-NEXT:    leal 6(%rsi,%r8), %esi
; CHECK-NEXT:    testl %esi, %esi
; CHECK-NEXT:    cmovlel %r9d, %edi
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %edi, %ecx
; CHECK-NEXT:    cmovpl %edi, %ecx
; CHECK-NEXT:    cmovpl %r11d, %ecx
; CHECK-NEXT:    # kill: def $al killed $al killed $rax
; CHECK-NEXT:    # kill: def $dl killed $dl killed $rdx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $rcx
; CHECK-NEXT:    addq $104, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <3 x i8> @llvm.convert.to.arbitrary.fp.v3i8.v3f32(<3 x float> %x, metadata !"Float8E4M3FN", metadata !"round.tonearest", i1 false)
  ret <3 x i8> %r
}

; <4 x float> -> <4 x i8> Float8E4M3FN
define <4 x i8> @to_f8e4m3fn_v4f32(<4 x float> %x) {
; CHECK-LABEL: to_f8e4m3fn_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    subq $168, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 224
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $15, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    movl $31, %ebp
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r12d
; CHECK-NEXT:    movl %r12d, %edx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %ebx
; CHECK-NEXT:    movl %ebx, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %ebx
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %ebx
; CHECK-NEXT:    movl %ebx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    andl $1, %ebx
; CHECK-NEXT:    orl %edi, %ebx
; CHECK-NEXT:    andl %edx, %ebx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ecx, %ebx
; CHECK-NEXT:    xorl %r15d, %r15d
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $15, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    cmovael %ebp, %eax
; CHECK-NEXT:    movl $31, %ebp
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r13d
; CHECK-NEXT:    movl %r13d, %edx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %r14d
; CHECK-NEXT:    movl %r14d, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %r14d
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r14d
; CHECK-NEXT:    movl %r14d, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    andl $1, %r14d
; CHECK-NEXT:    orl %edi, %r14d
; CHECK-NEXT:    andl %edx, %r14d
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %r15d, %r14d
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    punpckhqdq {{.*#+}} xmm0 = xmm0[1,1]
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $15, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    cmovael %ebp, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r15d
; CHECK-NEXT:    movl %r15d, %edx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %ebp
; CHECK-NEXT:    movl %ebp, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %ebp
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %ebp
; CHECK-NEXT:    movl %ebp, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    andl $1, %ebp
; CHECK-NEXT:    orl %edi, %ebp
; CHECK-NEXT:    andl %edx, %ebp
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbl %eax, %ebp
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $15, %edx
; CHECK-NEXT:    subl %eax, %edx
; CHECK-NEXT:    cmpl $31, %edx
; CHECK-NEXT:    movl $31, %eax
; CHECK-NEXT:    cmovael %eax, %edx
; CHECK-NEXT:    cmpl $1, %edx
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    movl %edx, %eax
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    movl %edx, %esi
; CHECK-NEXT:    andl $8388607, %esi # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%rsi), %edi
; CHECK-NEXT:    movl %edi, %r8d
; CHECK-NEXT:    shrl %cl, %r8d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    movl $1, %r9d
; CHECK-NEXT:    shll %cl, %r9d
; CHECK-NEXT:    decl %r9d
; CHECK-NEXT:    movl %r9d, %ecx
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    testl %ecx, %edi
; CHECK-NEXT:    setne %r9b
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    movl %edi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    orl %r9d, %ecx
; CHECK-NEXT:    andl %r8d, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbl %eax, %ecx
; CHECK-NEXT:    addl {{[-0-9]+}}(%r{{[sb]}}p), %ebx # 4-byte Folded Reload
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpl $8, %ebx
; CHECK-NEXT:    cmovgel %eax, %ebx
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %r9d
; CHECK-NEXT:    shrl $24, %r9d
; CHECK-NEXT:    andl $-128, %r9d
; CHECK-NEXT:    leal (%r9,%r8,8), %r8d
; CHECK-NEXT:    orl %ebx, %r8d
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; CHECK-NEXT:    shrl $20, %r11d
; CHECK-NEXT:    movl %r11d, %r10d
; CHECK-NEXT:    movq %r11, %rbx
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $524287, %r12d # imm = 0x7FFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %r10d, %r11d
; CHECK-NEXT:    shrl $19, %r12d
; CHECK-NEXT:    andl %r11d, %r12d
; CHECK-NEXT:    addl %ebx, %r12d
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    cmpl $8, %r12d
; CHECK-NEXT:    cmovgel %eax, %r12d
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rbx # 8-byte Reload
; CHECK-NEXT:    leal (%rbx,%r10), %r11d
; CHECK-NEXT:    leal 48(,%r11,8), %r11d
; CHECK-NEXT:    orl %r9d, %r12d
; CHECK-NEXT:    orl %r11d, %r12d
; CHECK-NEXT:    leal 6(%rbx,%r10), %r10d
; CHECK-NEXT:    testl %r10d, %r10d
; CHECK-NEXT:    cmovlel %r8d, %r12d
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %r12d, %r9d
; CHECK-NEXT:    cmovpl %r12d, %r9d
; CHECK-NEXT:    movl $127, %r8d
; CHECK-NEXT:    cmovpl %r8d, %r9d
; CHECK-NEXT:    addl {{[-0-9]+}}(%r{{[sb]}}p), %r14d # 4-byte Folded Reload
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    cmpl $8, %r14d
; CHECK-NEXT:    cmovgel %eax, %r14d
; CHECK-NEXT:    setge %r11b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %r10d
; CHECK-NEXT:    shrl $24, %r10d
; CHECK-NEXT:    andl $-128, %r10d
; CHECK-NEXT:    leal (%r10,%r11,8), %r11d
; CHECK-NEXT:    orl %r14d, %r11d
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; CHECK-NEXT:    shrl $20, %r14d
; CHECK-NEXT:    movl %r14d, %ebx
; CHECK-NEXT:    movq %r14, %r12
; CHECK-NEXT:    andl $1, %ebx
; CHECK-NEXT:    xorl %r14d, %r14d
; CHECK-NEXT:    testl $524287, %r13d # imm = 0x7FFFF
; CHECK-NEXT:    setne %r14b
; CHECK-NEXT:    orl %ebx, %r14d
; CHECK-NEXT:    shrl $19, %r13d
; CHECK-NEXT:    andl %r14d, %r13d
; CHECK-NEXT:    addl %r12d, %r13d
; CHECK-NEXT:    xorl %ebx, %ebx
; CHECK-NEXT:    cmpl $8, %r13d
; CHECK-NEXT:    cmovgel %eax, %r13d
; CHECK-NEXT:    setge %bl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; CHECK-NEXT:    leal (%r12,%rbx), %r14d
; CHECK-NEXT:    leal 48(,%r14,8), %r14d
; CHECK-NEXT:    orl %r10d, %r13d
; CHECK-NEXT:    orl %r14d, %r13d
; CHECK-NEXT:    leal 6(%r12,%rbx), %ebx
; CHECK-NEXT:    testl %ebx, %ebx
; CHECK-NEXT:    cmovlel %r11d, %r13d
; CHECK-NEXT:    movzbl %r9b, %r11d
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %r13d, %r10d
; CHECK-NEXT:    cmovpl %r13d, %r10d
; CHECK-NEXT:    cmovpl %r8d, %r10d
; CHECK-NEXT:    movzbl %r10b, %r9d
; CHECK-NEXT:    shll $8, %r9d
; CHECK-NEXT:    orl %r11d, %r9d
; CHECK-NEXT:    addl {{[-0-9]+}}(%r{{[sb]}}p), %ebp # 4-byte Folded Reload
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    cmpl $8, %ebp
; CHECK-NEXT:    cmovgel %eax, %ebp
; CHECK-NEXT:    setge %r11b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %r10d
; CHECK-NEXT:    shrl $24, %r10d
; CHECK-NEXT:    andl $-128, %r10d
; CHECK-NEXT:    leal (%r10,%r11,8), %r11d
; CHECK-NEXT:    orl %ebp, %r11d
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; CHECK-NEXT:    shrl $20, %r14d
; CHECK-NEXT:    movl %r14d, %ebx
; CHECK-NEXT:    andl $1, %ebx
; CHECK-NEXT:    xorl %ebp, %ebp
; CHECK-NEXT:    testl $524287, %r15d # imm = 0x7FFFF
; CHECK-NEXT:    setne %bpl
; CHECK-NEXT:    orl %ebx, %ebp
; CHECK-NEXT:    shrl $19, %r15d
; CHECK-NEXT:    andl %ebp, %r15d
; CHECK-NEXT:    addl %r14d, %r15d
; CHECK-NEXT:    xorl %ebx, %ebx
; CHECK-NEXT:    cmpl $8, %r15d
; CHECK-NEXT:    cmovgel %eax, %r15d
; CHECK-NEXT:    setge %bl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; CHECK-NEXT:    leal (%r12,%rbx), %r14d
; CHECK-NEXT:    leal 48(,%r14,8), %ebp
; CHECK-NEXT:    orl %r10d, %r15d
; CHECK-NEXT:    orl %ebp, %r15d
; CHECK-NEXT:    leal 6(%r12,%rbx), %ebx
; CHECK-NEXT:    testl %ebx, %ebx
; CHECK-NEXT:    cmovlel %r11d, %r15d
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %r15d, %r10d
; CHECK-NEXT:    cmovpl %r15d, %r10d
; CHECK-NEXT:    cmovpl %r8d, %r10d
; CHECK-NEXT:    movzbl %r10b, %r10d
; CHECK-NEXT:    shll $16, %r10d
; CHECK-NEXT:    orl %r9d, %r10d
; CHECK-NEXT:    addl %edi, %ecx
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    cmpl $8, %ecx
; CHECK-NEXT:    cmovgel %eax, %ecx
; CHECK-NEXT:    setge %r9b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    movd %xmm1, %edi
; CHECK-NEXT:    shrl $24, %edi
; CHECK-NEXT:    andl $-128, %edi
; CHECK-NEXT:    leal (%rdi,%r9,8), %r9d
; CHECK-NEXT:    orl %ecx, %r9d
; CHECK-NEXT:    shrl $20, %esi
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $524287, %edx # imm = 0x7FFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %ecx, %r11d
; CHECK-NEXT:    shrl $19, %edx
; CHECK-NEXT:    andl %r11d, %edx
; CHECK-NEXT:    addl %esi, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $8, %edx
; CHECK-NEXT:    cmovgel %eax, %edx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    leal (%rax,%rcx), %esi
; CHECK-NEXT:    leal 48(,%rsi,8), %esi
; CHECK-NEXT:    orl %edi, %edx
; CHECK-NEXT:    orl %esi, %edx
; CHECK-NEXT:    leal 6(%rax,%rcx), %eax
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    cmovlel %r9d, %edx
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovnel %edx, %edi
; CHECK-NEXT:    cmovpl %edx, %edi
; CHECK-NEXT:    cmovpl %r8d, %edi
; CHECK-NEXT:    shll $24, %edi
; CHECK-NEXT:    orl %r10d, %edi
; CHECK-NEXT:    movd %edi, %xmm0
; CHECK-NEXT:    addq $168, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <4 x i8> @llvm.convert.to.arbitrary.fp.v4i8.v4f32(<4 x float> %x, metadata !"Float8E4M3FN", metadata !"round.tonearest", i1 false)
  ret <4 x i8> %r
}

; <4 x float> -> <4 x i8> Float8E5M2
define <4 x i8> @to_f8e5m2_v4f32(<4 x float> %x) {
; CHECK-LABEL: to_f8e5m2_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    subq $168, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 224
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $8, %ebx
; CHECK-NEXT:    movl $8, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    movl $31, %r14d
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r12d
; CHECK-NEXT:    movl %r12d, %edx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %r15d
; CHECK-NEXT:    movl %r15d, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %r15d
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r15d
; CHECK-NEXT:    movl %r15d, (%rsp) # 4-byte Spill
; CHECK-NEXT:    andl $1, %r15d
; CHECK-NEXT:    orl %edi, %r15d
; CHECK-NEXT:    andl %edx, %r15d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ecx, %r15d
; CHECK-NEXT:    xorl %ebp, %ebp
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $8, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    cmovael %r14d, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %r14d
; CHECK-NEXT:    movl %r14d, %edx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %r13d
; CHECK-NEXT:    movl %r13d, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %r13d
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r13d
; CHECK-NEXT:    movl %r13d, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    andl $1, %r13d
; CHECK-NEXT:    orl %edi, %r13d
; CHECK-NEXT:    andl %edx, %r13d
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ebp, %r13d
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    punpckhqdq {{.*#+}} xmm0 = xmm0[1,1]
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; CHECK-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movl $8, %eax
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    movl $31, %ecx
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    movl %edx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    # kill: def $edx killed $edx def $rdx
; CHECK-NEXT:    andl $8388607, %edx # imm = 0x7FFFFF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 8388608(%rdx), %ebp
; CHECK-NEXT:    movl %ebp, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    movl $1, %esi
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %esi
; CHECK-NEXT:    decl %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    testl %esi, %ebp
; CHECK-NEXT:    setne %dil
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %ebp
; CHECK-NEXT:    movl %ebp, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    andl $1, %ebp
; CHECK-NEXT:    orl %edi, %ebp
; CHECK-NEXT:    andl %edx, %ebp
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbl %eax, %ebp
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %eax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    subl %eax, %ebx
; CHECK-NEXT:    cmpl $31, %ebx
; CHECK-NEXT:    movl $31, %eax
; CHECK-NEXT:    cmovael %eax, %ebx
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %edx
; CHECK-NEXT:    movl %edx, %esi
; CHECK-NEXT:    andl $8388607, %esi # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%rsi), %edi
; CHECK-NEXT:    movl %edi, %r8d
; CHECK-NEXT:    shrl %cl, %r8d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    shll %cl, %eax
; CHECK-NEXT:    decl %eax
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    testl %eax, %edi
; CHECK-NEXT:    setne %r9b
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    movl %edi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    orl %r9d, %ecx
; CHECK-NEXT:    andl %r8d, %ecx
; CHECK-NEXT:    cmpl $1, %ebx
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbl %eax, %ecx
; CHECK-NEXT:    addl (%rsp), %r15d # 4-byte Folded Reload
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpl $4, %r15d
; CHECK-NEXT:    cmovgel %eax, %r15d
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 # 16-byte Reload
; CHECK-NEXT:    movd %xmm2, %r9d
; CHECK-NEXT:    shrl $24, %r9d
; CHECK-NEXT:    andl $-128, %r9d
; CHECK-NEXT:    leal (%r9,%r8,4), %r8d
; CHECK-NEXT:    orl %r15d, %r8d
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r11 # 8-byte Reload
; CHECK-NEXT:    shrl $21, %r11d
; CHECK-NEXT:    movl %r11d, %r10d
; CHECK-NEXT:    movq %r11, %rbx
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl $1048575, %r12d # imm = 0xFFFFF
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    orl %r10d, %r11d
; CHECK-NEXT:    shrl $20, %r12d
; CHECK-NEXT:    andl %r11d, %r12d
; CHECK-NEXT:    addl %ebx, %r12d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    cmpl $4, %r12d
; CHECK-NEXT:    cmovgel %eax, %r12d
; CHECK-NEXT:    setge %r11b
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Reload
; CHECK-NEXT:    leal (%r15,%r11), %r10d
; CHECK-NEXT:    leal 56(,%r10,4), %ebx
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    orl %r12d, %r10d
; CHECK-NEXT:    orl %ebx, %r10d
; CHECK-NEXT:    leal 14(%r15,%r11), %r11d
; CHECK-NEXT:    testl %r11d, %r11d
; CHECK-NEXT:    cmovlel %r8d, %r10d
; CHECK-NEXT:    cmpl $4, %r12d
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    cmpl $30, %r11d
; CHECK-NEXT:    sete %bl
; CHECK-NEXT:    andb %r8b, %bl
; CHECK-NEXT:    cmpl $31, %r11d
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    orb %bl, %r8b
; CHECK-NEXT:    testb %r8b, %r8b
; CHECK-NEXT:    leal 124(%r9), %r8d
; CHECK-NEXT:    cmovnel %r8d, %r10d
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    cmovnel %r10d, %r9d
; CHECK-NEXT:    cmovpl %r10d, %r9d
; CHECK-NEXT:    movaps {{.*#+}} xmm1 = [NaN,NaN,NaN,NaN]
; CHECK-NEXT:    movaps %xmm2, %xmm3
; CHECK-NEXT:    movaps %xmm2, %xmm4
; CHECK-NEXT:    andps %xmm1, %xmm3
; CHECK-NEXT:    movss {{.*#+}} xmm2 = [+Inf,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    ucomiss %xmm2, %xmm3
; CHECK-NEXT:    cmovnel %r9d, %r8d
; CHECK-NEXT:    cmovpl %r9d, %r8d
; CHECK-NEXT:    ucomiss %xmm0, %xmm4
; CHECK-NEXT:    movl $126, %r9d
; CHECK-NEXT:    cmovpl %r9d, %r8d
; CHECK-NEXT:    addl {{[-0-9]+}}(%r{{[sb]}}p), %r13d # 4-byte Folded Reload
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    cmpl $4, %r13d
; CHECK-NEXT:    cmovgel %eax, %r13d
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm4 # 16-byte Reload
; CHECK-NEXT:    movd %xmm4, %r11d
; CHECK-NEXT:    shrl $24, %r11d
; CHECK-NEXT:    andl $-128, %r11d
; CHECK-NEXT:    leal (%r11,%r10,4), %r10d
; CHECK-NEXT:    orl %r13d, %r10d
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r15 # 8-byte Reload
; CHECK-NEXT:    shrl $21, %r15d
; CHECK-NEXT:    movl %r15d, %ebx
; CHECK-NEXT:    movq %r15, %r12
; CHECK-NEXT:    andl $1, %ebx
; CHECK-NEXT:    xorl %r15d, %r15d
; CHECK-NEXT:    testl $1048575, %r14d # imm = 0xFFFFF
; CHECK-NEXT:    setne %r15b
; CHECK-NEXT:    orl %ebx, %r15d
; CHECK-NEXT:    shrl $20, %r14d
; CHECK-NEXT:    andl %r15d, %r14d
; CHECK-NEXT:    addl %r12d, %r14d
; CHECK-NEXT:    xorl %ebx, %ebx
; CHECK-NEXT:    cmpl $4, %r14d
; CHECK-NEXT:    cmovgel %eax, %r14d
; CHECK-NEXT:    setge %bl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r13 # 8-byte Reload
; CHECK-NEXT:    leal (%r13,%rbx), %r15d
; CHECK-NEXT:    leal 56(,%r15,4), %r15d
; CHECK-NEXT:    movl %r11d, %r12d
; CHECK-NEXT:    orl %r14d, %r12d
; CHECK-NEXT:    orl %r15d, %r12d
; CHECK-NEXT:    leal 14(%r13,%rbx), %ebx
; CHECK-NEXT:    testl %ebx, %ebx
; CHECK-NEXT:    cmovlel %r10d, %r12d
; CHECK-NEXT:    cmpl $4, %r14d
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    cmpl $30, %ebx
; CHECK-NEXT:    sete %r14b
; CHECK-NEXT:    andb %r10b, %r14b
; CHECK-NEXT:    cmpl $31, %ebx
; CHECK-NEXT:    setge %r10b
; CHECK-NEXT:    orb %r14b, %r10b
; CHECK-NEXT:    testb %r10b, %r10b
; CHECK-NEXT:    leal 124(%r11), %r10d
; CHECK-NEXT:    cmovnel %r10d, %r12d
; CHECK-NEXT:    ucomiss %xmm0, %xmm4
; CHECK-NEXT:    cmovnel %r12d, %r11d
; CHECK-NEXT:    cmovpl %r12d, %r11d
; CHECK-NEXT:    movaps %xmm4, %xmm3
; CHECK-NEXT:    andps %xmm1, %xmm3
; CHECK-NEXT:    ucomiss %xmm2, %xmm3
; CHECK-NEXT:    cmovnel %r11d, %r10d
; CHECK-NEXT:    cmovpl %r11d, %r10d
; CHECK-NEXT:    ucomiss %xmm0, %xmm4
; CHECK-NEXT:    cmovpl %r9d, %r10d
; CHECK-NEXT:    addl {{[-0-9]+}}(%r{{[sb]}}p), %ebp # 4-byte Folded Reload
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    cmpl $4, %ebp
; CHECK-NEXT:    cmovgel %eax, %ebp
; CHECK-NEXT:    setge %r11b
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm4 # 16-byte Reload
; CHECK-NEXT:    movd %xmm4, %ebx
; CHECK-NEXT:    shrl $24, %ebx
; CHECK-NEXT:    andl $-128, %ebx
; CHECK-NEXT:    leal (%rbx,%r11,4), %r11d
; CHECK-NEXT:    orl %ebp, %r11d
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r14 # 8-byte Reload
; CHECK-NEXT:    shrl $21, %r14d
; CHECK-NEXT:    movl %r14d, %ebp
; CHECK-NEXT:    movq %r14, %r15
; CHECK-NEXT:    andl $1, %ebp
; CHECK-NEXT:    xorl %r14d, %r14d
; CHECK-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %r12d # 4-byte Reload
; CHECK-NEXT:    testl $1048575, %r12d # imm = 0xFFFFF
; CHECK-NEXT:    setne %r14b
; CHECK-NEXT:    orl %ebp, %r14d
; CHECK-NEXT:    movl %r12d, %ebp
; CHECK-NEXT:    shrl $20, %ebp
; CHECK-NEXT:    andl %r14d, %ebp
; CHECK-NEXT:    addl %r15d, %ebp
; CHECK-NEXT:    xorl %r14d, %r14d
; CHECK-NEXT:    cmpl $4, %ebp
; CHECK-NEXT:    cmovgel %eax, %ebp
; CHECK-NEXT:    movl %ebp, %r13d
; CHECK-NEXT:    setge %r14b
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r12 # 8-byte Reload
; CHECK-NEXT:    leal (%r12,%r14), %r15d
; CHECK-NEXT:    leal 56(,%r15,4), %ebp
; CHECK-NEXT:    movl %ebx, %r15d
; CHECK-NEXT:    orl %r13d, %r15d
; CHECK-NEXT:    orl %ebp, %r15d
; CHECK-NEXT:    leal 14(%r12,%r14), %ebp
; CHECK-NEXT:    testl %ebp, %ebp
; CHECK-NEXT:    cmovlel %r11d, %r15d
; CHECK-NEXT:    cmpl $4, %r13d
; CHECK-NEXT:    setge %r11b
; CHECK-NEXT:    cmpl $30, %ebp
; CHECK-NEXT:    sete %r14b
; CHECK-NEXT:    andb %r11b, %r14b
; CHECK-NEXT:    cmpl $31, %ebp
; CHECK-NEXT:    setge %r11b
; CHECK-NEXT:    orb %r14b, %r11b
; CHECK-NEXT:    testb %r11b, %r11b
; CHECK-NEXT:    leal 124(%rbx), %r11d
; CHECK-NEXT:    cmovnel %r11d, %r15d
; CHECK-NEXT:    ucomiss %xmm0, %xmm4
; CHECK-NEXT:    cmovnel %r15d, %ebx
; CHECK-NEXT:    cmovpl %r15d, %ebx
; CHECK-NEXT:    movaps %xmm4, %xmm3
; CHECK-NEXT:    andps %xmm1, %xmm3
; CHECK-NEXT:    ucomiss %xmm2, %xmm3
; CHECK-NEXT:    cmovnel %ebx, %r11d
; CHECK-NEXT:    cmovpl %ebx, %r11d
; CHECK-NEXT:    ucomiss %xmm0, %xmm4
; CHECK-NEXT:    cmovpl %r9d, %r11d
; CHECK-NEXT:    addl %edi, %ecx
; CHECK-NEXT:    xorl %ebx, %ebx
; CHECK-NEXT:    cmpl $4, %ecx
; CHECK-NEXT:    cmovgel %eax, %ecx
; CHECK-NEXT:    setge %bl
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm3 # 16-byte Reload
; CHECK-NEXT:    movd %xmm3, %edi
; CHECK-NEXT:    shrl $24, %edi
; CHECK-NEXT:    andl $-128, %edi
; CHECK-NEXT:    leal (%rdi,%rbx,4), %ebx
; CHECK-NEXT:    orl %ecx, %ebx
; CHECK-NEXT:    shrl $21, %esi
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    xorl %ebp, %ebp
; CHECK-NEXT:    testl $1048575, %edx # imm = 0xFFFFF
; CHECK-NEXT:    setne %bpl
; CHECK-NEXT:    orl %ecx, %ebp
; CHECK-NEXT:    shrl $20, %edx
; CHECK-NEXT:    andl %ebp, %edx
; CHECK-NEXT:    addl %esi, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $4, %edx
; CHECK-NEXT:    cmovgel %eax, %edx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    leal (%rax,%rcx), %esi
; CHECK-NEXT:    leal 56(,%rsi,4), %esi
; CHECK-NEXT:    movl %edi, %ebp
; CHECK-NEXT:    orl %edx, %ebp
; CHECK-NEXT:    orl %esi, %ebp
; CHECK-NEXT:    leal 14(%rax,%rcx), %eax
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    cmovlel %ebx, %ebp
; CHECK-NEXT:    cmpl $4, %edx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    cmpl $30, %eax
; CHECK-NEXT:    sete %dl
; CHECK-NEXT:    andb %cl, %dl
; CHECK-NEXT:    cmpl $31, %eax
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    leal 124(%rdi), %eax
; CHECK-NEXT:    cmovnel %eax, %ebp
; CHECK-NEXT:    ucomiss %xmm0, %xmm3
; CHECK-NEXT:    cmovnel %ebp, %edi
; CHECK-NEXT:    cmovpl %ebp, %edi
; CHECK-NEXT:    andps %xmm3, %xmm1
; CHECK-NEXT:    ucomiss %xmm2, %xmm1
; CHECK-NEXT:    cmovnel %edi, %eax
; CHECK-NEXT:    cmovpl %edi, %eax
; CHECK-NEXT:    ucomiss %xmm0, %xmm3
; CHECK-NEXT:    cmovpl %r9d, %eax
; CHECK-NEXT:    movzbl %r10b, %ecx
; CHECK-NEXT:    movzbl %r8b, %edx
; CHECK-NEXT:    shll $8, %edx
; CHECK-NEXT:    orl %ecx, %edx
; CHECK-NEXT:    movzbl %r11b, %ecx
; CHECK-NEXT:    shll $16, %ecx
; CHECK-NEXT:    orl %edx, %ecx
; CHECK-NEXT:    shll $24, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    movd %eax, %xmm0
; CHECK-NEXT:    addq $168, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <4 x i8> @llvm.convert.to.arbitrary.fp.v4i8.v4f32(<4 x float> %x, metadata !"Float8E5M2", metadata !"round.tonearest", i1 false)
  ret <4 x i8> %r
}

; <2 x half> -> <2 x i8> Float8E4M3FN
define <2 x i8> @to_f8e4m3fn_v2f16(<2 x half> %x) {
; CHECK-LABEL: to_f8e4m3fn_v2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    subq $72, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 128
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    callq __extendhfsf2@PLT
; CHECK-NEXT:    mulss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    callq __truncsfhf2@PLT
; CHECK-NEXT:    pextrw $0, %xmm0, %r12d
; CHECK-NEXT:    movl %r12d, %eax
; CHECK-NEXT:    andl $31744, %eax # imm = 0x7C00
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    pextrw $0, %xmm0, %r15d
; CHECK-NEXT:    movl %r15d, %ecx
; CHECK-NEXT:    andl $32767, %ecx # imm = 0x7FFF
; CHECK-NEXT:    cmpl $1024, %ecx # imm = 0x400
; CHECK-NEXT:    cmovael %r15d, %r12d
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    shrl $10, %eax
; CHECK-NEXT:    leal -12(%rax), %edx
; CHECK-NEXT:    cmpl $1024, %ecx # imm = 0x400
; CHECK-NEXT:    psrld $16, %xmm0
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    cmovael %eax, %edx
; CHECK-NEXT:    addl $-14, %edx
; CHECK-NEXT:    andl $33791, %r12d # imm = 0x83FF
; CHECK-NEXT:    orl $14336, %r12d # imm = 0x3800
; CHECK-NEXT:    addl $-31744, %ecx # imm = 0x8400
; CHECK-NEXT:    movzwl %cx, %eax
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $33792, %eax # imm = 0x8400
; CHECK-NEXT:    cmovbel %ecx, %edx
; CHECK-NEXT:    movq %rdx, %r14
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovbel %r15d, %r12d
; CHECK-NEXT:    callq __extendhfsf2@PLT
; CHECK-NEXT:    mulss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    callq __truncsfhf2@PLT
; CHECK-NEXT:    pextrw $0, %xmm0, %ebp
; CHECK-NEXT:    movl %ebp, %eax
; CHECK-NEXT:    andl $31744, %eax # imm = 0x7C00
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    pextrw $0, %xmm0, %ebx
; CHECK-NEXT:    movl %ebx, %r9d
; CHECK-NEXT:    andl $32767, %r9d # imm = 0x7FFF
; CHECK-NEXT:    cmpl $1024, %r9d # imm = 0x400
; CHECK-NEXT:    cmovael %ebx, %ebp
; CHECK-NEXT:    cmovael %r9d, %eax
; CHECK-NEXT:    shrl $10, %eax
; CHECK-NEXT:    leal -12(%rax), %esi
; CHECK-NEXT:    cmpl $1024, %r9d # imm = 0x400
; CHECK-NEXT:    cmovael %eax, %esi
; CHECK-NEXT:    movl $2, %eax
; CHECK-NEXT:    movl $2, %edx
; CHECK-NEXT:    subl %r14d, %edx
; CHECK-NEXT:    cmpw $15, %dx
; CHECK-NEXT:    movl $15, %r13d
; CHECK-NEXT:    cmovael %r13d, %edx
; CHECK-NEXT:    cmpw $1, %dx
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movl %r12d, %r10d
; CHECK-NEXT:    andl $1023, %r10d # imm = 0x3FF
; CHECK-NEXT:    leal 1024(%r10), %edi
; CHECK-NEXT:    movl %edi, %r14d
; CHECK-NEXT:    shrl %cl, %r14d
; CHECK-NEXT:    movl $1, %r8d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r8d
; CHECK-NEXT:    decl %r8d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testw %r8w, %di
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    shrl %cl, %edi
; CHECK-NEXT:    movl %edi, %r8d
; CHECK-NEXT:    andl $1, %r8d
; CHECK-NEXT:    orl %r11d, %r8d
; CHECK-NEXT:    movl $1, %r11d
; CHECK-NEXT:    andl %r14d, %r8d
; CHECK-NEXT:    cmpw $1, %dx
; CHECK-NEXT:    movl $0, %edx
; CHECK-NEXT:    cmovbl %edx, %r8d
; CHECK-NEXT:    addl $-14, %esi
; CHECK-NEXT:    andl $33791, %ebp # imm = 0x83FF
; CHECK-NEXT:    orl $14336, %ebp # imm = 0x3800
; CHECK-NEXT:    addl $-31744, %r9d # imm = 0x8400
; CHECK-NEXT:    movzwl %r9w, %ecx
; CHECK-NEXT:    cmpl $33792, %ecx # imm = 0x8400
; CHECK-NEXT:    cmovbel %edx, %esi
; CHECK-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovbel %ebx, %ebp
; CHECK-NEXT:    subl %esi, %eax
; CHECK-NEXT:    cmpw $15, %ax
; CHECK-NEXT:    cmovael %r13d, %eax
; CHECK-NEXT:    cmpw $1, %ax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movl %ebp, %edx
; CHECK-NEXT:    andl $1023, %edx # imm = 0x3FF
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    leal 1024(%rdx), %r13d
; CHECK-NEXT:    movl %r13d, %edx
; CHECK-NEXT:    shrl %cl, %edx
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r11d
; CHECK-NEXT:    decl %r11d
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    testw %r11w, %r13w
; CHECK-NEXT:    setne %r9b
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r13d
; CHECK-NEXT:    movl %r13d, %r14d
; CHECK-NEXT:    andl $1, %r14d
; CHECK-NEXT:    orl %r9d, %r14d
; CHECK-NEXT:    andl %edx, %r14d
; CHECK-NEXT:    cmpw $1, %ax
; CHECK-NEXT:    movl $0, %ecx
; CHECK-NEXT:    cmovbl %ecx, %r14d
; CHECK-NEXT:    addl %edi, %r8d
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    cmpw $8, %r8w
; CHECK-NEXT:    cmovgel %ecx, %r8d
; CHECK-NEXT:    movl $0, %esi
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    shrl $8, %r15d
; CHECK-NEXT:    andl $128, %r15d
; CHECK-NEXT:    leal (%r15,%rax,8), %eax
; CHECK-NEXT:    orl %r8d, %eax
; CHECK-NEXT:    shrl $7, %r10d
; CHECK-NEXT:    movl %r10d, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    testb $63, %r12b
; CHECK-NEXT:    setne %dl
; CHECK-NEXT:    orl %ecx, %edx
; CHECK-NEXT:    shrl $6, %r12d
; CHECK-NEXT:    andl %edx, %r12d
; CHECK-NEXT:    addl %r10d, %r12d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpw $8, %r12w
; CHECK-NEXT:    cmovgel %esi, %r12d
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; CHECK-NEXT:    leal (%rsi,%rcx), %edx
; CHECK-NEXT:    leal 48(,%rdx,8), %edx
; CHECK-NEXT:    orl %r15d, %r12d
; CHECK-NEXT:    orl %edx, %r12d
; CHECK-NEXT:    leal 6(%rsi,%rcx), %ecx
; CHECK-NEXT:    testw %cx, %cx
; CHECK-NEXT:    cmovlel %eax, %r12d
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    callq __extendhfsf2@PLT
; CHECK-NEXT:    xorps %xmm1, %xmm1
; CHECK-NEXT:    ucomiss %xmm1, %xmm0
; CHECK-NEXT:    cmovnel %r12d, %r15d
; CHECK-NEXT:    cmovpl %r12d, %r15d
; CHECK-NEXT:    movl $127, %r12d
; CHECK-NEXT:    cmovpl %r12d, %r15d
; CHECK-NEXT:    movzbl %r15b, %r15d
; CHECK-NEXT:    addl %r13d, %r14d
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    cmpw $8, %r14w
; CHECK-NEXT:    movl $0, %edi
; CHECK-NEXT:    cmovgel %edi, %r14d
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    shrl $8, %ebx
; CHECK-NEXT:    andl $128, %ebx
; CHECK-NEXT:    leal (%rbx,%rax,8), %eax
; CHECK-NEXT:    orl %r14d, %eax
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; CHECK-NEXT:    shrl $7, %edx
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    movq %rdx, %rsi
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    testb $63, %bpl
; CHECK-NEXT:    setne %dl
; CHECK-NEXT:    orl %ecx, %edx
; CHECK-NEXT:    shrl $6, %ebp
; CHECK-NEXT:    andl %edx, %ebp
; CHECK-NEXT:    addl %esi, %ebp
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpw $8, %bp
; CHECK-NEXT:    cmovgel %edi, %ebp
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; CHECK-NEXT:    leal (%rsi,%rcx), %edx
; CHECK-NEXT:    leal 48(,%rdx,8), %edx
; CHECK-NEXT:    orl %ebx, %ebp
; CHECK-NEXT:    orl %edx, %ebp
; CHECK-NEXT:    leal 6(%rsi,%rcx), %ecx
; CHECK-NEXT:    testw %cx, %cx
; CHECK-NEXT:    cmovlel %eax, %ebp
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    callq __extendhfsf2@PLT
; CHECK-NEXT:    xorps %xmm1, %xmm1
; CHECK-NEXT:    ucomiss %xmm1, %xmm0
; CHECK-NEXT:    cmovnel %ebp, %ebx
; CHECK-NEXT:    cmovpl %ebp, %ebx
; CHECK-NEXT:    cmovpl %r12d, %ebx
; CHECK-NEXT:    shll $8, %ebx
; CHECK-NEXT:    orl %r15d, %ebx
; CHECK-NEXT:    movd %ebx, %xmm0
; CHECK-NEXT:    addq $72, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call <2 x i8> @llvm.convert.to.arbitrary.fp.v2i8.v2f16(<2 x half> %x, metadata !"Float8E4M3FN", metadata !"round.tonearest", i1 false)
  ret <2 x i8> %r
}

; Different source types

; f16 -> i8 (Float8E5M2)
define i8 @to_f8e5m2_from_f16(half %x) {
; CHECK-LABEL: to_f8e5m2_from_f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 64
; CHECK-NEXT:    .cfi_offset %rbx, -32
; CHECK-NEXT:    .cfi_offset %r14, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    callq __extendhfsf2@PLT
; CHECK-NEXT:    mulss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    callq __truncsfhf2@PLT
; CHECK-NEXT:    pextrw $0, %xmm0, %edx
; CHECK-NEXT:    movl %edx, %eax
; CHECK-NEXT:    andl $31744, %eax # imm = 0x7C00
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    pextrw $0, %xmm0, %ebx
; CHECK-NEXT:    movl %ebx, %ecx
; CHECK-NEXT:    andl $32767, %ecx # imm = 0x7FFF
; CHECK-NEXT:    cmpl $1024, %ecx # imm = 0x400
; CHECK-NEXT:    cmovael %ebx, %edx
; CHECK-NEXT:    cmovael %ecx, %eax
; CHECK-NEXT:    shrl $10, %eax
; CHECK-NEXT:    leal -12(%rax), %esi
; CHECK-NEXT:    cmpl $1024, %ecx # imm = 0x400
; CHECK-NEXT:    cmovael %eax, %esi
; CHECK-NEXT:    addl $-14, %esi
; CHECK-NEXT:    andl $33791, %edx # imm = 0x83FF
; CHECK-NEXT:    orl $14336, %edx # imm = 0x3800
; CHECK-NEXT:    addl $-31744, %ecx # imm = 0x8400
; CHECK-NEXT:    movzwl %cx, %eax
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    cmpl $33792, %eax # imm = 0x8400
; CHECK-NEXT:    cmovbel %edi, %esi
; CHECK-NEXT:    cmovbel %ebx, %edx
; CHECK-NEXT:    movl $-5, %ecx
; CHECK-NEXT:    subl %esi, %ecx
; CHECK-NEXT:    cmpw $15, %cx
; CHECK-NEXT:    movl $15, %eax
; CHECK-NEXT:    cmovbl %ecx, %eax
; CHECK-NEXT:    cmpw $1, %ax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movl %edx, %r8d
; CHECK-NEXT:    andl $1023, %r8d # imm = 0x3FF
; CHECK-NEXT:    leal 1024(%r8), %r9d
; CHECK-NEXT:    movl %r9d, %r10d
; CHECK-NEXT:    shrl %cl, %r10d
; CHECK-NEXT:    movl $1, %r11d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r11d
; CHECK-NEXT:    decl %r11d
; CHECK-NEXT:    xorl %ebp, %ebp
; CHECK-NEXT:    testw %r11w, %r9w
; CHECK-NEXT:    setne %bpl
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r9d
; CHECK-NEXT:    movl %r9d, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    orl %ebp, %ecx
; CHECK-NEXT:    andl %r10d, %ecx
; CHECK-NEXT:    cmpw $1, %ax
; CHECK-NEXT:    cmovbl %edi, %ecx
; CHECK-NEXT:    addl %r9d, %ecx
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    cmpw $4, %cx
; CHECK-NEXT:    cmovgel %edi, %ecx
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    shrl $8, %ebx
; CHECK-NEXT:    andl $128, %ebx
; CHECK-NEXT:    leal (%rbx,%rax,4), %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    shrl $8, %r8d
; CHECK-NEXT:    movl %r8d, %ecx
; CHECK-NEXT:    andl $1, %ecx
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    testb $127, %dl
; CHECK-NEXT:    setne %r9b
; CHECK-NEXT:    orl %ecx, %r9d
; CHECK-NEXT:    shrl $7, %edx
; CHECK-NEXT:    andl %r9d, %edx
; CHECK-NEXT:    addl %r8d, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpw $4, %dx
; CHECK-NEXT:    cmovgel %edi, %edx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    leal (%rsi,%rcx), %edi
; CHECK-NEXT:    leal 56(,%rdi,4), %edi
; CHECK-NEXT:    movl %ebx, %ebp
; CHECK-NEXT:    orl %edx, %ebp
; CHECK-NEXT:    orl %edi, %ebp
; CHECK-NEXT:    leal 14(%rsi,%rcx), %ecx
; CHECK-NEXT:    testw %cx, %cx
; CHECK-NEXT:    cmovlel %eax, %ebp
; CHECK-NEXT:    cmpw $4, %dx
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    cmpw $30, %cx
; CHECK-NEXT:    sete %dl
; CHECK-NEXT:    andb %al, %dl
; CHECK-NEXT:    cmpw $31, %cx
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    leal 124(%rbx), %r14d
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    cmovnel %r14d, %ebp
; CHECK-NEXT:    callq __extendhfsf2@PLT
; CHECK-NEXT:    movd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Folded Spill
; CHECK-NEXT:    xorps %xmm1, %xmm1
; CHECK-NEXT:    ucomiss %xmm1, %xmm0
; CHECK-NEXT:    cmovnel %ebp, %ebx
; CHECK-NEXT:    cmovpl %ebp, %ebx
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    andps {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    callq __extendhfsf2@PLT
; CHECK-NEXT:    ucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovnel %ebx, %r14d
; CHECK-NEXT:    cmovpl %ebx, %r14d
; CHECK-NEXT:    xorps %xmm0, %xmm0
; CHECK-NEXT:    movss {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 4-byte Reload
; CHECK-NEXT:    # xmm1 = mem[0],zero,zero,zero
; CHECK-NEXT:    ucomiss %xmm0, %xmm1
; CHECK-NEXT:    movl $126, %eax
; CHECK-NEXT:    cmovnpl %r14d, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f16(half %x, metadata !"Float8E5M2", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; bf16 -> i8 (Float8E5M2)
define i8 @to_f8e5m2_from_bf16(bfloat %x) {
; CHECK-LABEL: to_f8e5m2_from_bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    .cfi_offset %rbx, -16
; CHECK-NEXT:    pextrw $0, %xmm0, %ebx
; CHECK-NEXT:    movl %ebx, %eax
; CHECK-NEXT:    shll $16, %eax
; CHECK-NEXT:    movd %eax, %xmm0
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexpf@PLT
; CHECK-NEXT:    movl {{[0-9]+}}(%rsp), %edx
; CHECK-NEXT:    movl $8, %ecx
; CHECK-NEXT:    subl %edx, %ecx
; CHECK-NEXT:    cmpl $31, %ecx
; CHECK-NEXT:    movl $31, %eax
; CHECK-NEXT:    cmovbl %ecx, %eax
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    adcl $-1, %ecx
; CHECK-NEXT:    movd %xmm0, %esi
; CHECK-NEXT:    movl %esi, %edi
; CHECK-NEXT:    andl $8388607, %edi # imm = 0x7FFFFF
; CHECK-NEXT:    leal 8388608(%rdi), %r8d
; CHECK-NEXT:    movl %r8d, %r9d
; CHECK-NEXT:    shrl %cl, %r9d
; CHECK-NEXT:    movl $1, %r10d
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %r10d
; CHECK-NEXT:    decl %r10d
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testl %r10d, %r8d
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl %cl, %r8d
; CHECK-NEXT:    movl %r8d, %r10d
; CHECK-NEXT:    andl $1, %r10d
; CHECK-NEXT:    orl %r11d, %r10d
; CHECK-NEXT:    andl %r9d, %r10d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpl $1, %eax
; CHECK-NEXT:    cmovbl %ecx, %r10d
; CHECK-NEXT:    addl %r8d, %r10d
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    cmpl $4, %r10d
; CHECK-NEXT:    cmovgel %ecx, %r10d
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    shrl $8, %ebx
; CHECK-NEXT:    andl $128, %ebx
; CHECK-NEXT:    leal (%rbx,%rax,4), %eax
; CHECK-NEXT:    orl %r10d, %eax
; CHECK-NEXT:    shrl $21, %edi
; CHECK-NEXT:    movl %edi, %r8d
; CHECK-NEXT:    andl $1, %r8d
; CHECK-NEXT:    xorl %r9d, %r9d
; CHECK-NEXT:    testl $1048575, %esi # imm = 0xFFFFF
; CHECK-NEXT:    setne %r9b
; CHECK-NEXT:    orl %r8d, %r9d
; CHECK-NEXT:    shrl $20, %esi
; CHECK-NEXT:    andl %r9d, %esi
; CHECK-NEXT:    addl %edi, %esi
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    cmpl $4, %esi
; CHECK-NEXT:    cmovgel %ecx, %esi
; CHECK-NEXT:    setge %dil
; CHECK-NEXT:    leal (%rdx,%rdi), %ecx
; CHECK-NEXT:    leal 56(,%rcx,4), %ecx
; CHECK-NEXT:    movl %ebx, %r8d
; CHECK-NEXT:    orl %esi, %r8d
; CHECK-NEXT:    orl %ecx, %r8d
; CHECK-NEXT:    leal 14(%rdx,%rdi), %ecx
; CHECK-NEXT:    testl %ecx, %ecx
; CHECK-NEXT:    cmovlel %eax, %r8d
; CHECK-NEXT:    cmpl $4, %esi
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    cmpl $30, %ecx
; CHECK-NEXT:    sete %dl
; CHECK-NEXT:    andb %al, %dl
; CHECK-NEXT:    cmpl $31, %ecx
; CHECK-NEXT:    setge %al
; CHECK-NEXT:    orb %dl, %al
; CHECK-NEXT:    leal 124(%rbx), %ecx
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    cmovnel %ecx, %r8d
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 # 16-byte Reload
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    cmovnel %r8d, %ebx
; CHECK-NEXT:    cmovpl %r8d, %ebx
; CHECK-NEXT:    movaps {{.*#+}} xmm1 = [NaN,NaN,NaN,NaN]
; CHECK-NEXT:    andps %xmm2, %xmm1
; CHECK-NEXT:    ucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovnel %ebx, %ecx
; CHECK-NEXT:    cmovpl %ebx, %ecx
; CHECK-NEXT:    ucomiss %xmm0, %xmm2
; CHECK-NEXT:    movl $126, %eax
; CHECK-NEXT:    cmovnpl %ecx, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.bf16(bfloat %x, metadata !"Float8E5M2", metadata !"round.tonearest", i1 false)
  ret i8 %r
}

; f64 -> i8 (Float8E5M2)
define i8 @to_f8e5m2_from_f64(double %x) {
; CHECK-LABEL: to_f8e5m2_from_f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    .cfi_offset %rbx, -16
; CHECK-NEXT:    movdqa %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rdi
; CHECK-NEXT:    callq frexp@PLT
; CHECK-NEXT:    movslq {{[0-9]+}}(%rsp), %rsi
; CHECK-NEXT:    movl $37, %ecx
; CHECK-NEXT:    subq %rsi, %rcx
; CHECK-NEXT:    cmpq $63, %rcx
; CHECK-NEXT:    movl $63, %eax
; CHECK-NEXT:    cmovbq %rcx, %rax
; CHECK-NEXT:    cmpq $1, %rax
; CHECK-NEXT:    movq %rax, %rdx
; CHECK-NEXT:    adcq $0, %rdx
; CHECK-NEXT:    decl %edx
; CHECK-NEXT:    movl $1, %r10d
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    shlq %cl, %r10
; CHECK-NEXT:    decq %r10
; CHECK-NEXT:    movq %xmm0, %rdi
; CHECK-NEXT:    movabsq $4503599627370495, %r8 # imm = 0xFFFFFFFFFFFFF
; CHECK-NEXT:    andq %rdi, %r8
; CHECK-NEXT:    movabsq $4503599627370496, %r9 # imm = 0x10000000000000
; CHECK-NEXT:    orq %r8, %r9
; CHECK-NEXT:    xorl %r11d, %r11d
; CHECK-NEXT:    testq %r10, %r9
; CHECK-NEXT:    setne %r11b
; CHECK-NEXT:    movq %r9, %r10
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrq %cl, %r10
; CHECK-NEXT:    movl %r10d, %ebx
; CHECK-NEXT:    andl $1, %ebx
; CHECK-NEXT:    orl %r11d, %ebx
; CHECK-NEXT:    movl %edx, %ecx
; CHECK-NEXT:    shrq %cl, %r9
; CHECK-NEXT:    andl %ebx, %r9d
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    cmpq $1, %rax
; CHECK-NEXT:    cmovbq %rcx, %r9
; CHECK-NEXT:    addq %r10, %r9
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    cmpq $4, %r9
; CHECK-NEXT:    cmovgeq %rcx, %r9
; CHECK-NEXT:    setge %dl
; CHECK-NEXT:    movdqa {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 # 16-byte Reload
; CHECK-NEXT:    movq %xmm2, %rax
; CHECK-NEXT:    shrq $63, %rax
; CHECK-NEXT:    shll $7, %eax
; CHECK-NEXT:    leal (%rax,%rdx,4), %edx
; CHECK-NEXT:    orq %r9, %rdx
; CHECK-NEXT:    shrq $50, %r8
; CHECK-NEXT:    movl %r8d, %r9d
; CHECK-NEXT:    andl $1, %r9d
; CHECK-NEXT:    xorl %r10d, %r10d
; CHECK-NEXT:    movq %rdi, %r11
; CHECK-NEXT:    shlq $15, %r11
; CHECK-NEXT:    setne %r10b
; CHECK-NEXT:    orl %r9d, %r10d
; CHECK-NEXT:    shrq $49, %rdi
; CHECK-NEXT:    andl %r10d, %edi
; CHECK-NEXT:    addq %r8, %rdi
; CHECK-NEXT:    xorl %r8d, %r8d
; CHECK-NEXT:    cmpq $4, %rdi
; CHECK-NEXT:    cmovgeq %rcx, %rdi
; CHECK-NEXT:    setge %r8b
; CHECK-NEXT:    leaq (%rsi,%r8), %rcx
; CHECK-NEXT:    leaq 56(,%rcx,4), %rcx
; CHECK-NEXT:    movq %rax, %r9
; CHECK-NEXT:    orq %rdi, %r9
; CHECK-NEXT:    orq %rcx, %r9
; CHECK-NEXT:    leaq 14(%rsi,%r8), %rcx
; CHECK-NEXT:    testq %rcx, %rcx
; CHECK-NEXT:    cmovleq %rdx, %r9
; CHECK-NEXT:    cmpq $4, %rdi
; CHECK-NEXT:    setge %dl
; CHECK-NEXT:    cmpq $30, %rcx
; CHECK-NEXT:    sete %sil
; CHECK-NEXT:    andb %dl, %sil
; CHECK-NEXT:    cmpq $31, %rcx
; CHECK-NEXT:    setge %cl
; CHECK-NEXT:    orb %sil, %cl
; CHECK-NEXT:    leaq 124(%rax), %rdx
; CHECK-NEXT:    testb %cl, %cl
; CHECK-NEXT:    cmovneq %rdx, %r9
; CHECK-NEXT:    pxor %xmm0, %xmm0
; CHECK-NEXT:    ucomisd %xmm0, %xmm2
; CHECK-NEXT:    cmovneq %r9, %rax
; CHECK-NEXT:    cmovpq %r9, %rax
; CHECK-NEXT:    movapd {{.*#+}} xmm1 = [NaN,NaN]
; CHECK-NEXT:    andpd %xmm2, %xmm1
; CHECK-NEXT:    ucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovneq %rax, %rdx
; CHECK-NEXT:    cmovpq %rax, %rdx
; CHECK-NEXT:    ucomisd %xmm0, %xmm2
; CHECK-NEXT:    movl $126, %eax
; CHECK-NEXT:    cmovnpq %rdx, %rax
; CHECK-NEXT:    # kill: def $al killed $al killed $rax
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = call i8 @llvm.convert.to.arbitrary.fp.i8.f64(double %x, metadata !"Float8E5M2", metadata !"round.tonearest", i1 false)
  ret i8 %r
}
