; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting -mtriple=x86_64-pc-windows-msvc %s -o - | FileCheck %s -check-prefix=WIN
; RUN: llc -combiner-topological-sorting -mtriple=x86_64-pc-linux %s -o -| FileCheck %s -check-prefix=UNIX

declare float @llvm.experimental.constrained.powi.f32(float, i32, metadata, metadata)

define float @powi_f64(float %a, i32 %b) nounwind strictfp {
; WIN-LABEL: powi_f64:
; WIN:       # %bb.0:
; WIN-NEXT:    subq $40, %rsp
; WIN-NEXT:    cvtsi2ss %edx, %xmm1
; WIN-NEXT:    callq powf
; WIN-NEXT:    addq $40, %rsp
; WIN-NEXT:    retq
;
; UNIX-LABEL: powi_f64:
; UNIX:       # %bb.0:
; UNIX-NEXT:    pushq %rax
; UNIX-NEXT:    callq __powisf2@PLT
; UNIX-NEXT:    popq %rax
; UNIX-NEXT:    retq
  %1 = call float @llvm.experimental.constrained.powi.f32(float %a, i32 %b, metadata !"round.tonearest", metadata !"fpexcept.ignore") strictfp
  ret float %1
}
