; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
; RUN: llc -O3 -mtriple=i686-pc-linux -mattr=sse2 -stop-after=finalize-isel < %s | FileCheck %s

define double @sifdb(i8 %x) #0 {
  ; CHECK-LABEL: name: sifdb
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[MOVSX32rm8_:%[0-9]+]]:gr32 = MOVSX32rm8 %fixed-stack.0, 1, $noreg, 0, $noreg :: (load (s8) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   [[CVTSI2SDrr:%[0-9]+]]:fr64 = CVTSI2SDrr killed [[MOVSX32rm8_]]
  ; CHECK-NEXT:   MOVSDmr %stack.0, 1, $noreg, 0, $noreg, killed [[CVTSI2SDrr]] :: (store (s64) into %stack.0, align 4)
  ; CHECK-NEXT:   [[LD_Fp64m80_:%[0-9]+]]:rfp80 = nofpexcept LD_Fp64m80 %stack.0, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw :: (load (s64) from %stack.0, align 4)
  ; CHECK-NEXT:   RET 0, killed [[LD_Fp64m80_]]
entry:
  %result = call double @llvm.experimental.constrained.sitofp.f64.i8(i8 %x, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  ret double %result
}

define double @sifdw(i16 %x) #0 {
  ; CHECK-LABEL: name: sifdw
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[MOVSX32rm16_:%[0-9]+]]:gr32 = MOVSX32rm16 %fixed-stack.0, 1, $noreg, 0, $noreg :: (load (s16) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   [[CVTSI2SDrr:%[0-9]+]]:fr64 = CVTSI2SDrr killed [[MOVSX32rm16_]]
  ; CHECK-NEXT:   MOVSDmr %stack.0, 1, $noreg, 0, $noreg, killed [[CVTSI2SDrr]] :: (store (s64) into %stack.0, align 4)
  ; CHECK-NEXT:   [[LD_Fp64m80_:%[0-9]+]]:rfp80 = nofpexcept LD_Fp64m80 %stack.0, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw :: (load (s64) from %stack.0, align 4)
  ; CHECK-NEXT:   RET 0, killed [[LD_Fp64m80_]]
entry:
  %result = call double @llvm.experimental.constrained.sitofp.f64.i16(i16 %x, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  ret double %result
}

define i64 @f20u64(double %x) #0 {
  ; CHECK-LABEL: name: f20u64
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOVSDrm_alt:%[0-9]+]]:fr64 = MOVSDrm_alt %fixed-stack.0, 1, $noreg, 0, $noreg :: (load (s64) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   [[MOVSDrm_alt1:%[0-9]+]]:fr64 = MOVSDrm_alt $noreg, 1, $noreg, %const.0, $noreg :: (load (s64) from constant-pool)
  ; CHECK-NEXT:   nofpexcept UCOMISDrr [[MOVSDrm_alt1]], [[MOVSDrm_alt]], implicit-def $eflags, implicit $mxcsr
  ; CHECK-NEXT:   [[FsFLD0SD:%[0-9]+]]:fr64 = FsFLD0SD
  ; CHECK-NEXT:   JCC_1 %bb.2, 6, implicit $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.entry:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.entry:
  ; CHECK-NEXT:   liveins: $eflags
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[PHI:%[0-9]+]]:fr64 = PHI [[FsFLD0SD]], %bb.1, [[MOVSDrm_alt1]], %bb.0
  ; CHECK-NEXT:   [[SUBSDrr:%[0-9]+]]:fr64 = nofpexcept SUBSDrr [[MOVSDrm_alt]], killed [[PHI]], implicit $mxcsr
  ; CHECK-NEXT:   MOVSDmr %stack.0, 1, $noreg, 0, $noreg, killed [[SUBSDrr]] :: (store (s64) into %stack.0)
  ; CHECK-NEXT:   [[SETCCr:%[0-9]+]]:gr8 = SETCCr 6, implicit $eflags
  ; CHECK-NEXT:   [[LD_Fp64m80_:%[0-9]+]]:rfp80 = LD_Fp64m80 %stack.0, 1, $noreg, 0, $noreg, implicit-def dead $fpsw, implicit $fpcw :: (load (s64) from %stack.0)
  ; CHECK-NEXT:   FNSTCW16m %stack.1, 1, $noreg, 0, $noreg, implicit-def $fpsw, implicit $fpcw :: (store (s16) into %stack.1)
  ; CHECK-NEXT:   [[MOVZX32rm16_:%[0-9]+]]:gr32 = MOVZX32rm16 %stack.1, 1, $noreg, 0, $noreg :: (load (s16) from %stack.1)
  ; CHECK-NEXT:   [[OR32ri:%[0-9]+]]:gr32 = OR32ri killed [[MOVZX32rm16_]], 3072, implicit-def $eflags
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr16 = COPY killed [[OR32ri]].sub_16bit
  ; CHECK-NEXT:   MOV16mr %stack.2, 1, $noreg, 0, $noreg, killed [[COPY]] :: (store (s16) into %stack.2)
  ; CHECK-NEXT:   FLDCW16m %stack.2, 1, $noreg, 0, $noreg, implicit-def $fpsw, implicit-def $fpcw :: (load (s16) from %stack.2)
  ; CHECK-NEXT:   IST_Fp64m80 %stack.0, 1, $noreg, 0, $noreg, [[LD_Fp64m80_]], implicit-def $fpsw, implicit $fpcw
  ; CHECK-NEXT:   FLDCW16m %stack.1, 1, $noreg, 0, $noreg, implicit-def $fpsw, implicit-def $fpcw :: (load (s16) from %stack.1)
  ; CHECK-NEXT:   [[MOVZX32rr8_:%[0-9]+]]:gr32 = MOVZX32rr8 killed [[SETCCr]]
  ; CHECK-NEXT:   [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[MOVZX32rr8_]], 31, implicit-def dead $eflags
  ; CHECK-NEXT:   [[XOR32rm:%[0-9]+]]:gr32 = XOR32rm [[SHL32ri]], %stack.0, 1, $noreg, 4, $noreg, implicit-def dead $eflags :: (load (s32) from %stack.0 + 4)
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm %stack.0, 1, $noreg, 0, $noreg :: (load (s32) from %stack.0, align 8)
  ; CHECK-NEXT:   $eax = COPY [[MOV32rm]]
  ; CHECK-NEXT:   $edx = COPY [[XOR32rm]]
  ; CHECK-NEXT:   RET 0, $eax, $edx
entry:
  %result = call i64 @llvm.experimental.constrained.fptoui.i64.f64(double %x, metadata !"fpexcept.strict") #0
  ret i64 %result
}

define i8 @f20s8(double %x) #0 {
  ; CHECK-LABEL: name: f20s8
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[CVTTSD2SIrm:%[0-9]+]]:gr32 = nofpexcept CVTTSD2SIrm %fixed-stack.0, 1, $noreg, 0, $noreg, implicit $mxcsr :: (load (s64) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32_abcd = COPY killed [[CVTTSD2SIrm]]
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr8 = COPY [[COPY]].sub_8bit
  ; CHECK-NEXT:   $al = COPY [[COPY1]]
  ; CHECK-NEXT:   RET 0, $al
entry:
  %result = call i8 @llvm.experimental.constrained.fptosi.i8.f64(double %x, metadata !"fpexcept.strict") #0
  ret i8 %result
}

define i16 @f20s16(double %x) #0 {
  ; CHECK-LABEL: name: f20s16
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[CVTTSD2SIrm:%[0-9]+]]:gr32 = nofpexcept CVTTSD2SIrm %fixed-stack.0, 1, $noreg, 0, $noreg, implicit $mxcsr :: (load (s64) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr16 = COPY [[CVTTSD2SIrm]].sub_16bit
  ; CHECK-NEXT:   $ax = COPY [[COPY]]
  ; CHECK-NEXT:   RET 0, $ax
entry:
  %result = call i16 @llvm.experimental.constrained.fptosi.i16.f64(double %x, metadata !"fpexcept.strict") #0
  ret i16 %result
}

define i32 @f20u(double %x) #0 {
  ; CHECK-LABEL: name: f20u
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[MOVSDrm_alt:%[0-9]+]]:fr64 = MOVSDrm_alt %fixed-stack.0, 1, $noreg, 0, $noreg :: (load (s64) from %fixed-stack.0, align 16)
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vr128 = COPY [[MOVSDrm_alt]]
  ; CHECK-NEXT:   [[CVTTSD2SIrr_Int:%[0-9]+]]:gr32 = nofpexcept CVTTSD2SIrr_Int killed [[COPY]], implicit $mxcsr
  ; CHECK-NEXT:   [[SAR32ri:%[0-9]+]]:gr32 = SAR32ri [[CVTTSD2SIrr_Int]], 31, implicit-def dead $eflags
  ; CHECK-NEXT:   [[SUBSDrm:%[0-9]+]]:fr64 = nofpexcept SUBSDrm [[MOVSDrm_alt]], $noreg, 1, $noreg, %const.0, $noreg, implicit $mxcsr :: (load (s64) from constant-pool)
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vr128 = COPY killed [[SUBSDrm]]
  ; CHECK-NEXT:   [[CVTTSD2SIrr_Int1:%[0-9]+]]:gr32 = nofpexcept CVTTSD2SIrr_Int killed [[COPY1]], implicit $mxcsr
  ; CHECK-NEXT:   [[AND32rr:%[0-9]+]]:gr32 = AND32rr [[CVTTSD2SIrr_Int1]], killed [[SAR32ri]], implicit-def dead $eflags
  ; CHECK-NEXT:   [[OR32rr:%[0-9]+]]:gr32 = OR32rr [[CVTTSD2SIrr_Int]], killed [[AND32rr]], implicit-def dead $eflags
  ; CHECK-NEXT:   $eax = COPY [[OR32rr]]
  ; CHECK-NEXT:   RET 0, $eax
entry:
  %result = call i32 @llvm.experimental.constrained.fptoui.i32.f64(double %x, metadata !"fpexcept.strict") #0
  ret i32 %result
}

; These 4 divs only differ in their exception behavior. They form two groups,
; whithin each the constrained functions have the same exception hehavior and
; may be CSE'd. Instructions with different exception behavior belong to
; different groups, they have different chain argument and cannot be CSE'd.
define void @binop_cse(double %a, double %b, ptr %x, ptr %y) #0 {
  ; CHECK-LABEL: name: binop_cse
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm %fixed-stack.0, 1, $noreg, 0, $noreg :: (load (s32) from %fixed-stack.0)
  ; CHECK-NEXT:   [[MOV32rm1:%[0-9]+]]:gr32 = MOV32rm %fixed-stack.1, 1, $noreg, 0, $noreg :: (load (s32) from %fixed-stack.1, align 16)
  ; CHECK-NEXT:   [[MOVSDrm_alt:%[0-9]+]]:fr64 = MOVSDrm_alt %fixed-stack.3, 1, $noreg, 0, $noreg :: (load (s64) from %fixed-stack.3, align 16)
  ; CHECK-NEXT:   [[DIVSDrm:%[0-9]+]]:fr64 = nofpexcept DIVSDrm [[MOVSDrm_alt]], %fixed-stack.2, 1, $noreg, 0, $noreg, implicit $mxcsr :: (load (s64) from %fixed-stack.2)
  ; CHECK-NEXT:   MOVSDmr killed [[MOV32rm1]], 1, $noreg, 0, $noreg, [[DIVSDrm]] :: (store (s64) into %ir.x, align 4)
  ; CHECK-NEXT:   MOVSDmr killed [[MOV32rm]], 1, $noreg, 0, $noreg, [[DIVSDrm]] :: (store (s64) into %ir.y, align 4)
  ; CHECK-NEXT:   RET 0
entry:
  %div = call double @llvm.experimental.constrained.fdiv.f64(double %a, double %b, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  %div1 = call double @llvm.experimental.constrained.fdiv.f64(double %a, double %b, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  %div2 = call double @llvm.experimental.constrained.fdiv.f64(double %a, double %b, metadata !"round.dynamic", metadata !"fpexcept.ignore") #0
  %div3 = call double @llvm.experimental.constrained.fdiv.f64(double %a, double %b, metadata !"round.dynamic", metadata !"fpexcept.ignore") #0
  store double %div2, ptr %x
  store double %div3, ptr %y
  ret void
}

; These 4 divs only differ in their exception behavior. They form two groups,
; whithin each the constrained functions have the same exception hehavior and
; may be CSE'd. Instructions with different exception behavior belong to
; different groups, they have different chain argument and cannot be CSE'd.
define void @sitofp_cse(i32 %a, ptr %x, ptr %y) #0 {
  ; CHECK-LABEL: name: sitofp_cse
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   [[MOV32rm:%[0-9]+]]:gr32 = MOV32rm %fixed-stack.0, 1, $noreg, 0, $noreg :: (load (s32) from %fixed-stack.0, align 8)
  ; CHECK-NEXT:   [[MOV32rm1:%[0-9]+]]:gr32 = MOV32rm %fixed-stack.1, 1, $noreg, 0, $noreg :: (load (s32) from %fixed-stack.1)
  ; CHECK-NEXT:   [[CVTSI2SDrm:%[0-9]+]]:fr64 = nofpexcept CVTSI2SDrm %fixed-stack.2, 1, $noreg, 0, $noreg :: (load (s32) from %fixed-stack.2, align 16)
  ; CHECK-NEXT:   MOVSDmr killed [[MOV32rm1]], 1, $noreg, 0, $noreg, [[CVTSI2SDrm]] :: (store (s64) into %ir.x, align 4)
  ; CHECK-NEXT:   MOVSDmr killed [[MOV32rm]], 1, $noreg, 0, $noreg, [[CVTSI2SDrm]] :: (store (s64) into %ir.y, align 4)
  ; CHECK-NEXT:   RET 0
entry:
  %result = call double @llvm.experimental.constrained.sitofp.f64.i32(i32 %a, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  %result1 = call double @llvm.experimental.constrained.sitofp.f64.i32(i32 %a, metadata !"round.dynamic", metadata !"fpexcept.strict") #0
  %result2 = call double @llvm.experimental.constrained.sitofp.f64.i32(i32 %a, metadata !"round.dynamic", metadata !"fpexcept.ignore") #0
  %result3 = call double @llvm.experimental.constrained.sitofp.f64.i32(i32 %a, metadata !"round.dynamic", metadata !"fpexcept.ignore") #0
  store double %result2, ptr %x
  store double %result3, ptr %y
  ret void
}

attributes #0 = { strictfp }

declare double @llvm.experimental.constrained.sitofp.f64.i8(i8, metadata, metadata)
declare double @llvm.experimental.constrained.sitofp.f64.i16(i16, metadata, metadata)
declare double @llvm.experimental.constrained.sitofp.f64.i32(i32, metadata, metadata)
declare i32 @llvm.experimental.constrained.fptoui.i32.f64(double, metadata)
declare i64 @llvm.experimental.constrained.fptoui.i64.f64(double, metadata)
declare i8 @llvm.experimental.constrained.fptosi.i8.f64(double, metadata)
declare i16 @llvm.experimental.constrained.fptosi.i16.f64(double, metadata)
declare double @llvm.experimental.constrained.fdiv.f64(double, double, metadata, metadata)
