; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-- | FileCheck %s

define i32 @main() nounwind {
; CHECK-LABEL: main:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    fldl {{\.LCPI[0-9]+_[0-9]+}}
; CHECK-NEXT:    fldl {{\.LCPI[0-9]+_[0-9]+}}
; CHECK-NEXT:    fxch %st(1)
; CHECK-NEXT:    #APP
; CHECK-NEXT:    fmul %st(1), %st
; CHECK-NEXT:    fst %st(1)
; CHECK-NEXT:    frndint
; CHECK-NEXT:    fxch %st(1)
; CHECK-NEXT:    fsub %st(1), %st
; CHECK-NEXT:    f2xm1
; CHECK-EMPTY:
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    fstp %st(0)
; CHECK-NEXT:    fstp %st(0)
entry:
	%asmtmp = tail call { double, double } asm sideeffect "fmul\09%st(1),%st\0A\09fst\09%st(1)\0A\09frndint\0A\09fxch  %st(1)\0A\09fsub\09%st(1),%st\0A\09f2xm1\0A\09", "={st},={st(1)},0,1,~{dirflag},~{fpsr},~{flags}"(double 0x4030FEFBD582097D, double 4.620000e+01) nounwind		; <{ double, double }> [#uses=0]
	unreachable
}
