; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-pc-windows-gnu  | FileCheck %s --check-prefix=WIN
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s --check-prefix=LINUX

; On Windows, for calling conventions that have GCC compatibibility requirements,
; follow the GCC convention of passing via the stack (an sret). Elsewhere we use
; the more efficient approach of returning via XMM0.
;
; NOTE: f128 arguments are passed indirectly on Windows, but in XMM registers elsewhere.

define fp128 @ret_ccc(fp128 %a) {
; WIN-LABEL: ret_ccc:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %rcx, %rax
; WIN-NEXT:    movaps (%rdx), %xmm0
; WIN-NEXT:    movaps %xmm0, (%rcx)
; WIN-NEXT:    retq
;
; LINUX-LABEL: ret_ccc:
; LINUX:       # %bb.0:
; LINUX-NEXT:    retq
  ret fp128 %a
}

define win64cc fp128 @ret_win64(fp128 %a) {
; WIN-LABEL: ret_win64:
; WIN:       # %bb.0:
; WIN-NEXT:    movq %rcx, %rax
; WIN-NEXT:    movaps (%rdx), %xmm0
; WIN-NEXT:    movaps %xmm0, (%rcx)
; WIN-NEXT:    retq
;
; LINUX-LABEL: ret_win64:
; LINUX:       # %bb.0:
; LINUX-NEXT:    movq %rcx, %rax
; LINUX-NEXT:    movaps (%rdx), %xmm0
; LINUX-NEXT:    movaps %xmm0, (%rcx)
; LINUX-NEXT:    retq
  ret fp128 %a
}

; vectorcallcc symbol mangling confuses the test generation script.
; The \01 ensures re-running the script does not remove the checks.
define x86_vectorcallcc fp128 @"\01ret_vectorcall"(fp128 %a) {
; WIN-LABEL: ret_vectorcall:
; WIN:       # %bb.0:
; WIN-NEXT:    retq
;
; LINUX-LABEL: ret_vectorcall:
; LINUX:       # %bb.0:
; LINUX-NEXT:    retq
  ret fp128 %a
}

define swiftcc fp128 @ret_swift(fp128 %a) {
; WIN-LABEL: ret_swift:
; WIN:       # %bb.0:
; WIN-NEXT:    movaps (%rcx), %xmm0
; WIN-NEXT:    retq
;
; LINUX-LABEL: ret_swift:
; LINUX:       # %bb.0:
; LINUX-NEXT:    retq
  ret fp128 %a
}

define tailcc fp128 @ret_tail(fp128 %a) {
; WIN-LABEL: ret_tail:
; WIN:       # %bb.0:
; WIN-NEXT:    movaps (%rcx), %xmm0
; WIN-NEXT:    retq $40
;
; LINUX-LABEL: ret_tail:
; LINUX:       # %bb.0:
; LINUX-NEXT:    retq $8
  ret fp128 %a
}

define preserve_mostcc fp128 @ret_preserve_most(fp128 %a) {
; WIN-LABEL: ret_preserve_most:
; WIN:       # %bb.0:
; WIN-NEXT:    movaps (%rcx), %xmm0
; WIN-NEXT:    retq
;
; LINUX-LABEL: ret_preserve_most:
; LINUX:       # %bb.0:
; LINUX-NEXT:    retq
  ret fp128 %a
}

define x86_regcallcc fp128 @ret_regcall(fp128 %a) {
; WIN-LABEL: ret_regcall:
; WIN:       # %bb.0:
; WIN-NEXT:    retq
;
; LINUX-LABEL: ret_regcall:
; LINUX:       # %bb.0:
; LINUX-NEXT:    retq
  ret fp128 %a
}
