; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v3 | FileCheck %s --check-prefixes=CHECK,AVX2
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v4 | FileCheck %s --check-prefixes=CHECK,AVX512

;
; 32-bit float to unsigned integer
;

define <8 x i1> @test_unsigned_v8i1_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_unsigned_v8i1_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrw $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrw $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v8i1_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vmovss {{.*#+}} xmm3 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vpmovzxbq {{.*#+}} zmm0 = xmm0[0],zero,zero,zero,zero,zero,zero,zero,xmm0[1],zero,zero,zero,zero,zero,zero,zero,xmm0[2],zero,zero,zero,zero,zero,zero,zero,xmm0[3],zero,zero,zero,zero,zero,zero,zero,xmm0[4],zero,zero,zero,zero,zero,zero,zero,xmm0[5],zero,zero,zero,zero,zero,zero,zero,xmm0[6],zero,zero,zero,zero,zero,zero,zero,xmm0[7],zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vptestmq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %zmm0, %k0
; AVX512-NEXT:    vpmovm2w %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i1> @llvm.fptoui.sat.v8i1.v8f32(<8 x float> %f)
  ret <8 x i1> %x
}

define <8 x i1> @test_freeze_unsigned_v8i1_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_freeze_unsigned_v8i1_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrw $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrw $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_freeze_unsigned_v8i1_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vmovss {{.*#+}} xmm3 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vpmovzxbq {{.*#+}} zmm0 = xmm0[0],zero,zero,zero,zero,zero,zero,zero,xmm0[1],zero,zero,zero,zero,zero,zero,zero,xmm0[2],zero,zero,zero,zero,zero,zero,zero,xmm0[3],zero,zero,zero,zero,zero,zero,zero,xmm0[4],zero,zero,zero,zero,zero,zero,zero,xmm0[5],zero,zero,zero,zero,zero,zero,zero,xmm0[6],zero,zero,zero,zero,zero,zero,zero,xmm0[7],zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vptestmq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %zmm0, %k0
; AVX512-NEXT:    vpmovm2w %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i1> @llvm.fptoui.sat.v8i1.v8f32(<8 x float> %f)
  %y = freeze <8 x i1> %x
  ret <8 x i1> %y
}

define <8 x i8> @test_unsigned_v8i8_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_unsigned_v8i8_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [2.55E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrb $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrb $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v8i8_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vmovss {{.*#+}} xmm3 = [2.55E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i8> @llvm.fptoui.sat.v8i8.v8f32(<8 x float> %f)
  ret <8 x i8> %x
}

define <8 x i16> @test_unsigned_v8i16_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_unsigned_v8i16_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [6.5535E+4,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrw $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrw $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v8i16_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vmovss {{.*#+}} xmm3 = [6.5535E+4,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrw $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrw $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i16> @llvm.fptoui.sat.v8i16.v8f32(<8 x float> %f)
  ret <8 x i16> %x
}

define <8 x i32> @test_unsigned_v8i32_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_unsigned_v8i32_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxps %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vcvttps2dq %ymm0, %ymm1
; AVX2-NEXT:    vpsrad $31, %ymm1, %ymm2
; AVX2-NEXT:    vbroadcastss {{.*#+}} ymm3 = [2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9]
; AVX2-NEXT:    vsubps %ymm3, %ymm0, %ymm3
; AVX2-NEXT:    vcvttps2dq %ymm3, %ymm3
; AVX2-NEXT:    vpand %ymm2, %ymm3, %ymm2
; AVX2-NEXT:    vpor %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vbroadcastss {{.*#+}} ymm2 = [4.2949673E+9,4.2949673E+9,4.2949673E+9,4.2949673E+9,4.2949673E+9,4.2949673E+9,4.2949673E+9,4.2949673E+9]
; AVX2-NEXT:    vcmpleps %ymm0, %ymm2, %ymm0
; AVX2-NEXT:    vorps %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v8i32_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vmaxps %ymm1, %ymm0, %ymm1
; AVX512-NEXT:    vcvttps2dq %ymm1, %ymm2
; AVX512-NEXT:    vpsrad $31, %ymm2, %ymm3
; AVX512-NEXT:    vsubps {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %ymm1, %ymm0
; AVX512-NEXT:    vcvttps2dq %ymm0, %ymm0
; AVX512-NEXT:    vpternlogd {{.*#+}} ymm0 = (ymm0 & ymm3) | ymm2
; AVX512-NEXT:    vcmpgeps {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %ymm1, %k1
; AVX512-NEXT:    vpcmpeqd %ymm1, %ymm1, %ymm1
; AVX512-NEXT:    vmovdqa32 %ymm1, %ymm0 {%k1}
; AVX512-NEXT:    retq
  %x = call <8 x i32> @llvm.fptoui.sat.v8i32.v8f32(<8 x float> %f)
  ret <8 x i32> %x
}

define <8 x i64> @test_unsigned_v8i64_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_unsigned_v8i64_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [9.22337203E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vsubss %xmm2, %xmm4, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %rax
; AVX2-NEXT:    vcvttss2si %xmm4, %rcx
; AVX2-NEXT:    movq %rcx, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %rax, %rdx
; AVX2-NEXT:    orq %rcx, %rdx
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vmovss {{.*#+}} xmm3 = [1.8446743E+19,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm3, %xmm4
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vmovq %rdx, %xmm4
; AVX2-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; AVX2-NEXT:    vsubss %xmm2, %xmm5, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rdx
; AVX2-NEXT:    vcvttss2si %xmm5, %rsi
; AVX2-NEXT:    movq %rsi, %rdi
; AVX2-NEXT:    sarq $63, %rdi
; AVX2-NEXT:    andq %rdx, %rdi
; AVX2-NEXT:    orq %rsi, %rdi
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomiss %xmm3, %xmm5
; AVX2-NEXT:    cmovaq %rcx, %rdi
; AVX2-NEXT:    vmovq %rdi, %xmm5
; AVX2-NEXT:    vsubss %xmm2, %xmm0, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rsi
; AVX2-NEXT:    vcvttss2si %xmm0, %rdi
; AVX2-NEXT:    movq %rdi, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %rsi, %rdx
; AVX2-NEXT:    orq %rdi, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm0
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vucomiss %xmm3, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm0[1,1,3,3]
; AVX2-NEXT:    vsubss %xmm2, %xmm6, %xmm7
; AVX2-NEXT:    vcvttss2si %xmm7, %rdi
; AVX2-NEXT:    vcvttss2si %xmm6, %r8
; AVX2-NEXT:    movq %r8, %rsi
; AVX2-NEXT:    sarq $63, %rsi
; AVX2-NEXT:    andq %rdi, %rsi
; AVX2-NEXT:    orq %r8, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm6
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm5[0],xmm4[0]
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm5
; AVX2-NEXT:    vshufps {{.*#+}} xmm6 = xmm5[3,3,3,3]
; AVX2-NEXT:    vsubss %xmm2, %xmm6, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %rdi
; AVX2-NEXT:    vcvttss2si %xmm6, %r8
; AVX2-NEXT:    vmovq %rdx, %xmm0
; AVX2-NEXT:    movq %r8, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %rdi, %rdx
; AVX2-NEXT:    orq %r8, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vucomiss %xmm3, %xmm6
; AVX2-NEXT:    vshufpd {{.*#+}} xmm7 = xmm5[1,0]
; AVX2-NEXT:    vsubss %xmm2, %xmm7, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rdi
; AVX2-NEXT:    vmovq %rsi, %xmm6
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vcvttss2si %xmm7, %r8
; AVX2-NEXT:    movq %r8, %rsi
; AVX2-NEXT:    sarq $63, %rsi
; AVX2-NEXT:    andq %rdi, %rsi
; AVX2-NEXT:    orq %r8, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm7
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm7
; AVX2-NEXT:    vsubss %xmm2, %xmm5, %xmm7
; AVX2-NEXT:    vcvttss2si %xmm7, %rdi
; AVX2-NEXT:    vmovq %rdx, %xmm7
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vcvttss2si %xmm5, %r8
; AVX2-NEXT:    movq %r8, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %rdi, %rdx
; AVX2-NEXT:    orq %r8, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vucomiss %xmm3, %xmm5
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm5[1,1,3,3]
; AVX2-NEXT:    vsubss %xmm2, %xmm5, %xmm2
; AVX2-NEXT:    vcvttss2si %xmm2, %rdi
; AVX2-NEXT:    vmovq %rsi, %xmm2
; AVX2-NEXT:    vcvttss2si %xmm5, %rsi
; AVX2-NEXT:    movq %rsi, %r8
; AVX2-NEXT:    sarq $63, %r8
; AVX2-NEXT:    andq %rdi, %r8
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm6[0]
; AVX2-NEXT:    vinserti128 $1, %xmm4, %ymm0, %ymm0
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm2[0],xmm7[0]
; AVX2-NEXT:    orq %rsi, %r8
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbq %rax, %r8
; AVX2-NEXT:    vucomiss %xmm3, %xmm5
; AVX2-NEXT:    cmovaq %rcx, %r8
; AVX2-NEXT:    vmovq %rdx, %xmm1
; AVX2-NEXT:    vmovq %r8, %xmm3
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm3[0]
; AVX2-NEXT:    vinserti128 $1, %xmm2, %ymm1, %ymm1
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v8i64_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm3[3,3,3,3]
; AVX512-NEXT:    vcvttss2usi %xmm4, %rdx
; AVX512-NEXT:    xorl %eax, %eax
; AVX512-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [1.8446743E+19,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm3[1,0]
; AVX512-NEXT:    vcvttss2usi %xmm4, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm4
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm4[0],xmm5[0]
; AVX512-NEXT:    vcvttss2usi %xmm3, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm3 = xmm3[1,1,3,3]
; AVX512-NEXT:    vcvttss2usi %xmm3, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm3
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm3 = xmm5[0],xmm3[0]
; AVX512-NEXT:    vinserti128 $1, %xmm4, %ymm3, %ymm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvttss2usi %xmm4, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvttss2usi %xmm4, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm4
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm4[0],xmm5[0]
; AVX512-NEXT:    vcvttss2usi %xmm0, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm0
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm2, %xmm0
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvttss2usi %xmm0, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm0
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm2, %xmm0
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm0
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm5[0],xmm0[0]
; AVX512-NEXT:    vinserti128 $1, %xmm4, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm3, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %x = call <8 x i64> @llvm.fptoui.sat.v8i64.v8f32(<8 x float> %f)
  ret <8 x i64> %x
}

define <8 x i128> @test_unsigned_v8i128_v8f32(<8 x float> %f) nounwind {
; CHECK-LABEL: test_unsigned_v8i128_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    subq $168, %rsp
; CHECK-NEXT:    vmovups %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; CHECK-NEXT:    movq %rdi, %rbx
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm0[1,1,3,3]
; CHECK-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    xorl %r12d, %r12d
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r12, %rdx
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    movq $-1, %r13
; CHECK-NEXT:    cmovaq %r13, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovaq %r13, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vpermilpd $1, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[1,0]
; CHECK-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    vxorpd %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r12, %rdx
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovaq %r13, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovaq %r13, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vpermilps $255, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[3,3,3,3]
; CHECK-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r12, %rdx
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovaq %r13, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovaq %r13, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm0[1,1,3,3]
; CHECK-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r12, %rdx
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovaq %r13, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovaq %r13, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vpermilpd $1, (%rsp), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[1,0]
; CHECK-NEXT:    vmovapd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    movq %rdx, %rbp
; CHECK-NEXT:    vxorpd %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r12, %rbp
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovaq %r13, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovaq %r13, %rbp
; CHECK-NEXT:    vpermilps $255, (%rsp), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[3,3,3,3]
; CHECK-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    movq %rdx, %r15
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r12, %r15
; CHECK-NEXT:    cmovbq %r12, %r14
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovaq %r13, %r14
; CHECK-NEXT:    cmovaq %r13, %r15
; CHECK-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    movq %rax, %r12
; CHECK-NEXT:    movq %rdx, %r13
; CHECK-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    vxorps %xmm1, %xmm1, %xmm1
; CHECK-NEXT:    vucomiss %xmm1, %xmm0
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbq %rax, %r13
; CHECK-NEXT:    cmovbq %rax, %r12
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    movq $-1, %rax
; CHECK-NEXT:    cmovaq %rax, %r12
; CHECK-NEXT:    cmovaq %rax, %r13
; CHECK-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunssfti@PLT
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomiss %xmm0, %xmm1
; CHECK-NEXT:    movl $0, %ecx
; CHECK-NEXT:    cmovbq %rcx, %rdx
; CHECK-NEXT:    cmovbq %rcx, %rax
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    movq $-1, %rcx
; CHECK-NEXT:    cmovaq %rcx, %rax
; CHECK-NEXT:    cmovaq %rcx, %rdx
; CHECK-NEXT:    movq %rdx, 72(%rbx)
; CHECK-NEXT:    movq %rax, 64(%rbx)
; CHECK-NEXT:    movq %r13, 8(%rbx)
; CHECK-NEXT:    movq %r12, (%rbx)
; CHECK-NEXT:    movq %r15, 120(%rbx)
; CHECK-NEXT:    movq %r14, 112(%rbx)
; CHECK-NEXT:    movq %rbp, 104(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 96(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 88(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 80(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 56(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 48(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 40(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 32(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 24(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 16(%rbx)
; CHECK-NEXT:    movq %rbx, %rax
; CHECK-NEXT:    addq $168, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    retq
  %x = call <8 x i128> @llvm.fptoui.sat.v8i128.v8f32(<8 x float> %f)
  ret <8 x i128> %x
}

;
; 64-bit float to unsigned integer
;

define <4 x i1> @test_unsigned_v4i1_v4f64(<4 x double> %f) nounwind {
; AVX2-LABEL: test_unsigned_v4i1_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxpd %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vbroadcastsd {{.*#+}} ymm1 = [1.0E+0,1.0E+0,1.0E+0,1.0E+0]
; AVX2-NEXT:    vminpd %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vcvttpd2dq %ymm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v4i1_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vshufpd {{.*#+}} xmm1 = xmm0[1,0]
; AVX512-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vmovsd {{.*#+}} xmm3 = [1.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxsd %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttsd2si %xmm1, %eax
; AVX512-NEXT:    vmaxsd %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttsd2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxsd %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminsd %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttsd2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX512-NEXT:    vmaxsd %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminsd %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttsd2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vpmovzxbd {{.*#+}} xmm0 = xmm0[0],zero,zero,zero,xmm0[1],zero,zero,zero,xmm0[2],zero,zero,zero,xmm0[3],zero,zero,zero
; AVX512-NEXT:    vptestmd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %k0
; AVX512-NEXT:    vpmovm2d %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <4 x i1> @llvm.fptoui.sat.v4i1.v4f64(<4 x double> %f)
  ret <4 x i1> %x
}

define <4 x i8> @test_unsigned_v4i8_v4f64(<4 x double> %f) nounwind {
; CHECK-LABEL: test_unsigned_v4i8_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vshufpd {{.*#+}} xmm1 = xmm0[1,0]
; CHECK-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; CHECK-NEXT:    vmaxsd %xmm1, %xmm2, %xmm1
; CHECK-NEXT:    vmovsd {{.*#+}} xmm3 = [2.55E+2,0.0E+0]
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %eax
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm1
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %ecx
; CHECK-NEXT:    vmovd %ecx, %xmm1
; CHECK-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm4
; CHECK-NEXT:    vminsd %xmm4, %xmm3, %xmm4
; CHECK-NEXT:    vcvttsd2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm0
; CHECK-NEXT:    vminsd %xmm0, %xmm3, %xmm0
; CHECK-NEXT:    vcvttsd2si %xmm0, %eax
; CHECK-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %x = call <4 x i8> @llvm.fptoui.sat.v4i8.v4f64(<4 x double> %f)
  ret <4 x i8> %x
}

define <4 x i16> @test_unsigned_v4i16_v4f64(<4 x double> %f) nounwind {
; CHECK-LABEL: test_unsigned_v4i16_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vshufpd {{.*#+}} xmm1 = xmm0[1,0]
; CHECK-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; CHECK-NEXT:    vmaxsd %xmm1, %xmm2, %xmm1
; CHECK-NEXT:    vmovsd {{.*#+}} xmm3 = [6.5535E+4,0.0E+0]
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %eax
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm1
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %ecx
; CHECK-NEXT:    vmovd %ecx, %xmm1
; CHECK-NEXT:    vpinsrw $1, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm4
; CHECK-NEXT:    vminsd %xmm4, %xmm3, %xmm4
; CHECK-NEXT:    vcvttsd2si %xmm4, %eax
; CHECK-NEXT:    vpinsrw $2, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm0
; CHECK-NEXT:    vminsd %xmm0, %xmm3, %xmm0
; CHECK-NEXT:    vcvttsd2si %xmm0, %eax
; CHECK-NEXT:    vpinsrw $3, %eax, %xmm1, %xmm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %x = call <4 x i16> @llvm.fptoui.sat.v4i16.v4f64(<4 x double> %f)
  ret <4 x i16> %x
}

define <4 x i32> @test_unsigned_v4i32_v4f64(<4 x double> %f) nounwind {
; AVX2-LABEL: test_unsigned_v4i32_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxpd %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    vbroadcastsd {{.*#+}} ymm1 = [4.294967296E+9,4.294967296E+9,4.294967296E+9,4.294967296E+9]
; AVX2-NEXT:    vcmplepd %ymm0, %ymm1, %ymm1
; AVX2-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX2-NEXT:    vpackssdw %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vcvttpd2dq %ymm0, %xmm2
; AVX2-NEXT:    vpsrad $31, %xmm2, %xmm3
; AVX2-NEXT:    vbroadcastsd {{.*#+}} ymm4 = [2.147483648E+9,2.147483648E+9,2.147483648E+9,2.147483648E+9]
; AVX2-NEXT:    vsubpd %ymm4, %ymm0, %ymm0
; AVX2-NEXT:    vcvttpd2dq %ymm0, %xmm0
; AVX2-NEXT:    vandpd %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vorpd %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vpcmpeqd %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vblendvps %xmm1, %xmm2, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v4i32_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vmaxpd %ymm1, %ymm0, %ymm1
; AVX512-NEXT:    vcvttpd2dq %ymm1, %xmm2
; AVX512-NEXT:    vsubpd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %ymm1, %ymm0
; AVX512-NEXT:    vcvttpd2dq %ymm0, %xmm0
; AVX512-NEXT:    vpsrad $31, %xmm2, %xmm3
; AVX512-NEXT:    vpternlogd {{.*#+}} xmm0 = (xmm0 & xmm3) | xmm2
; AVX512-NEXT:    vcmpgepd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %ymm1, %k1
; AVX512-NEXT:    vpcmpeqd %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vmovdqa32 %xmm1, %xmm0 {%k1}
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <4 x i32> @llvm.fptoui.sat.v4i32.v4f64(<4 x double> %f)
  ret <4 x i32> %x
}

define <4 x i64> @test_unsigned_v4i64_v4f64(<4 x double> %f) nounwind {
; AVX2-LABEL: test_unsigned_v4i64_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm4
; AVX2-NEXT:    vmovsd {{.*#+}} xmm1 = [9.2233720368547758E+18,0.0E+0]
; AVX2-NEXT:    vsubsd %xmm1, %xmm4, %xmm2
; AVX2-NEXT:    vcvttsd2si %xmm2, %rax
; AVX2-NEXT:    vcvttsd2si %xmm4, %rcx
; AVX2-NEXT:    movq %rcx, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %rax, %rdx
; AVX2-NEXT:    orq %rcx, %rdx
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vucomisd %xmm2, %xmm4
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vmovsd {{.*#+}} xmm3 = [1.844674407370955E+19,0.0E+0]
; AVX2-NEXT:    vucomisd %xmm3, %xmm4
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm4[1,0]
; AVX2-NEXT:    vsubsd %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vcvttsd2si %xmm5, %rdi
; AVX2-NEXT:    vcvttsd2si %xmm4, %r8
; AVX2-NEXT:    movq %r8, %rsi
; AVX2-NEXT:    sarq $63, %rsi
; AVX2-NEXT:    andq %rdi, %rsi
; AVX2-NEXT:    orq %r8, %rsi
; AVX2-NEXT:    vucomisd %xmm2, %xmm4
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomisd %xmm3, %xmm4
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vsubsd %xmm1, %xmm0, %xmm4
; AVX2-NEXT:    vcvttsd2si %xmm4, %r8
; AVX2-NEXT:    vcvttsd2si %xmm0, %r9
; AVX2-NEXT:    movq %r9, %rdi
; AVX2-NEXT:    sarq $63, %rdi
; AVX2-NEXT:    andq %r8, %rdi
; AVX2-NEXT:    orq %r9, %rdi
; AVX2-NEXT:    vucomisd %xmm2, %xmm0
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomisd %xmm3, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %rdi
; AVX2-NEXT:    vmovq %rdx, %xmm4
; AVX2-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX2-NEXT:    vsubsd %xmm1, %xmm0, %xmm1
; AVX2-NEXT:    vcvttsd2si %xmm1, %rdx
; AVX2-NEXT:    vcvttsd2si %xmm0, %r8
; AVX2-NEXT:    vmovq %rsi, %xmm1
; AVX2-NEXT:    movq %r8, %rsi
; AVX2-NEXT:    sarq $63, %rsi
; AVX2-NEXT:    andq %rdx, %rsi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm4[0],xmm1[0]
; AVX2-NEXT:    orq %r8, %rsi
; AVX2-NEXT:    vucomisd %xmm2, %xmm0
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomisd %xmm3, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vmovq %rdi, %xmm0
; AVX2-NEXT:    vmovq %rsi, %xmm2
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm2[0]
; AVX2-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v4i64_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX512-NEXT:    vcvttsd2usi %xmm1, %rdx
; AVX512-NEXT:    xorl %eax, %eax
; AVX512-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vucomisd %xmm2, %xmm1
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vmovsd {{.*#+}} xmm3 = [1.844674407370955E+19,0.0E+0]
; AVX512-NEXT:    vucomisd %xmm3, %xmm1
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vshufpd {{.*#+}} xmm1 = xmm1[1,0]
; AVX512-NEXT:    vcvttsd2usi %xmm1, %rdx
; AVX512-NEXT:    vucomisd %xmm2, %xmm1
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomisd %xmm3, %xmm1
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm1
; AVX512-NEXT:    vcvttsd2usi %xmm0, %rdx
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm4[0],xmm1[0]
; AVX512-NEXT:    vucomisd %xmm2, %xmm0
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomisd %xmm3, %xmm0
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX512-NEXT:    vcvttsd2usi %xmm0, %rdx
; AVX512-NEXT:    vucomisd %xmm2, %xmm0
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomisd %xmm3, %xmm0
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm0
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm4[0],xmm0[0]
; AVX512-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %x = call <4 x i64> @llvm.fptoui.sat.v4i64.v4f64(<4 x double> %f)
  ret <4 x i64> %x
}

define <4 x i128> @test_unsigned_v4i128_v4f64(<4 x double> %f) nounwind {
; CHECK-LABEL: test_unsigned_v4i128_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    subq $88, %rsp
; CHECK-NEXT:    vmovupd %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; CHECK-NEXT:    movq %rdi, %rbx
; CHECK-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; CHECK-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunsdfti@PLT
; CHECK-NEXT:    movq %rdx, %r15
; CHECK-NEXT:    xorl %r14d, %r14d
; CHECK-NEXT:    vxorpd %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovapd (%rsp), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomisd %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r14, %r15
; CHECK-NEXT:    cmovbq %r14, %rax
; CHECK-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    movq $-1, %rbp
; CHECK-NEXT:    cmovaq %rbp, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovaq %rbp, %r15
; CHECK-NEXT:    vmovupd {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; CHECK-NEXT:    vmovapd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunsdfti@PLT
; CHECK-NEXT:    movq %rax, %r12
; CHECK-NEXT:    movq %rdx, %r13
; CHECK-NEXT:    vxorpd %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovapd {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomisd %xmm0, %xmm1
; CHECK-NEXT:    cmovbq %r14, %r13
; CHECK-NEXT:    cmovbq %r14, %r12
; CHECK-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    cmovaq %rbp, %r12
; CHECK-NEXT:    cmovaq %rbp, %r13
; CHECK-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunsdfti@PLT
; CHECK-NEXT:    movq %rax, %rbp
; CHECK-NEXT:    movq %rdx, %r14
; CHECK-NEXT:    vmovupd {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; CHECK-NEXT:    vucomisd %xmm1, %xmm0
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbq %rax, %r14
; CHECK-NEXT:    cmovbq %rax, %rbp
; CHECK-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    movq $-1, %rax
; CHECK-NEXT:    cmovaq %rax, %rbp
; CHECK-NEXT:    cmovaq %rax, %r14
; CHECK-NEXT:    vmovapd (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixunsdfti@PLT
; CHECK-NEXT:    vxorpd %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovapd (%rsp), %xmm1 # 16-byte Reload
; CHECK-NEXT:    vucomisd %xmm0, %xmm1
; CHECK-NEXT:    movl $0, %ecx
; CHECK-NEXT:    cmovbq %rcx, %rdx
; CHECK-NEXT:    cmovbq %rcx, %rax
; CHECK-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    movq $-1, %rcx
; CHECK-NEXT:    cmovaq %rcx, %rax
; CHECK-NEXT:    cmovaq %rcx, %rdx
; CHECK-NEXT:    movq %rdx, 40(%rbx)
; CHECK-NEXT:    movq %rax, 32(%rbx)
; CHECK-NEXT:    movq %r14, 8(%rbx)
; CHECK-NEXT:    movq %rbp, (%rbx)
; CHECK-NEXT:    movq %r13, 56(%rbx)
; CHECK-NEXT:    movq %r12, 48(%rbx)
; CHECK-NEXT:    movq %r15, 24(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 16(%rbx)
; CHECK-NEXT:    movq %rbx, %rax
; CHECK-NEXT:    addq $88, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    retq
  %x = call <4 x i128> @llvm.fptoui.sat.v4i128.v4f64(<4 x double> %f)
  ret <4 x i128> %x
}

;
; 16-bit float to unsigned integer
;

define <16 x i1> @test_unsigned_v16i1_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_unsigned_v16i1_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm2
; AVX2-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmaxss %xmm1, %xmm2, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm2, %xmm3, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm3
; AVX2-NEXT:    vmaxss %xmm1, %xmm3, %xmm3
; AVX2-NEXT:    vminss %xmm2, %xmm3, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrb $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $7, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $8, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $9, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $10, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $11, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $12, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $13, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $14, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vminss %xmm2, %xmm0, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrb $15, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v16i1_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX512-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm3, %xmm3
; AVX512-NEXT:    vminss %xmm2, %xmm3, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %eax
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm3
; AVX512-NEXT:    vmaxss %xmm1, %xmm3, %xmm3
; AVX512-NEXT:    vminss %xmm2, %xmm3, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm3
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $4, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $5, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $6, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $7, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $8, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $9, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $10, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $11, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $12, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $13, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $14, %eax, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vminss %xmm2, %xmm0, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $15, %eax, %xmm3, %xmm0
; AVX512-NEXT:    vptestmb {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %k0
; AVX512-NEXT:    vpmovm2b %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <16 x i1> @llvm.fptoui.sat.v16i1.v16f16(<16 x half> %f)
  ret <16 x i1> %x
}

define <16 x i8> @test_unsigned_v16i8_v16f16(<16 x half> %f) nounwind {
; CHECK-LABEL: test_unsigned_v16i8_v16f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpsrld $16, %xmm0, %xmm1
; CHECK-NEXT:    vcvtph2ps %xmm1, %xmm2
; CHECK-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; CHECK-NEXT:    vmaxss %xmm1, %xmm2, %xmm3
; CHECK-NEXT:    vmovss {{.*#+}} xmm2 = [2.55E+2,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    vminss %xmm2, %xmm3, %xmm3
; CHECK-NEXT:    vcvttss2si %xmm3, %eax
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm3
; CHECK-NEXT:    vmaxss %xmm1, %xmm3, %xmm3
; CHECK-NEXT:    vminss %xmm2, %xmm3, %xmm3
; CHECK-NEXT:    vcvttss2si %xmm3, %ecx
; CHECK-NEXT:    vmovd %ecx, %xmm3
; CHECK-NEXT:    vpinsrb $1, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $2, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vpsrlq $48, %xmm0, %xmm4
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $3, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $4, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $5, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $6, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $7, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vextracti128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $8, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vpsrld $16, %xmm0, %xmm4
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $9, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $10, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vpsrlq $48, %xmm0, %xmm4
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $11, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $12, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $13, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $14, %eax, %xmm3, %xmm3
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm0
; CHECK-NEXT:    vmaxss %xmm1, %xmm0, %xmm0
; CHECK-NEXT:    vminss %xmm2, %xmm0, %xmm0
; CHECK-NEXT:    vcvttss2si %xmm0, %eax
; CHECK-NEXT:    vpinsrb $15, %eax, %xmm3, %xmm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %x = call <16 x i8> @llvm.fptoui.sat.v16i8.v16f16(<16 x half> %f)
  ret <16 x i8> %x
}

define <16 x i16> @test_unsigned_v16i16_v16f16(<16 x half> %f) nounwind {
; CHECK-LABEL: test_unsigned_v16i16_v16f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vextracti128 $1, %ymm0, %xmm3
; CHECK-NEXT:    vpsrld $16, %xmm3, %xmm1
; CHECK-NEXT:    vcvtph2ps %xmm1, %xmm2
; CHECK-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; CHECK-NEXT:    vmaxss %xmm1, %xmm2, %xmm4
; CHECK-NEXT:    vmovss {{.*#+}} xmm2 = [6.5535E+4,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vcvtph2ps %xmm3, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %ecx
; CHECK-NEXT:    vmovd %ecx, %xmm4
; CHECK-NEXT:    vpinsrw $1, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm3[1,1,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $2, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vpsrlq $48, %xmm3, %xmm5
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $3, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vshufpd {{.*#+}} xmm5 = xmm3[1,0]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $4, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm3[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $5, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vshufps {{.*#+}} xmm5 = xmm3[3,3,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $6, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm3 = xmm3[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm3, %xmm3
; CHECK-NEXT:    vmaxss %xmm1, %xmm3, %xmm3
; CHECK-NEXT:    vminss %xmm2, %xmm3, %xmm3
; CHECK-NEXT:    vcvttss2si %xmm3, %eax
; CHECK-NEXT:    vpinsrw $7, %eax, %xmm4, %xmm3
; CHECK-NEXT:    vpsrld $16, %xmm0, %xmm4
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %eax
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm4
; CHECK-NEXT:    vminss %xmm2, %xmm4, %xmm4
; CHECK-NEXT:    vcvttss2si %xmm4, %ecx
; CHECK-NEXT:    vmovd %ecx, %xmm4
; CHECK-NEXT:    vpinsrw $1, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm0[1,1,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $2, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vpsrlq $48, %xmm0, %xmm5
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $3, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $4, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $5, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vshufps {{.*#+}} xmm5 = xmm0[3,3,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %eax
; CHECK-NEXT:    vpinsrw $6, %eax, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm0
; CHECK-NEXT:    vmaxss %xmm1, %xmm0, %xmm0
; CHECK-NEXT:    vminss %xmm2, %xmm0, %xmm0
; CHECK-NEXT:    vcvttss2si %xmm0, %eax
; CHECK-NEXT:    vpinsrw $7, %eax, %xmm4, %xmm0
; CHECK-NEXT:    vinserti128 $1, %xmm3, %ymm0, %ymm0
; CHECK-NEXT:    retq
  %x = call <16 x i16> @llvm.fptoui.sat.v16i16.v16f16(<16 x half> %f)
  ret <16 x i16> %x
}

define <16 x i32> @test_unsigned_v16i32_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_unsigned_v16i32_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %rdx
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vucomiss %xmm1, %xmm3
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [4.29496704E+9,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm2, %xmm3
; AVX2-NEXT:    movl $-1, %ecx
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vshufpd {{.*#+}} xmm3 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm3, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm3
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm3
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vmovd %esi, %xmm3
; AVX2-NEXT:    vpinsrd $1, %edx, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vpinsrd $2, %edx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vpinsrd $3, %edx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vmovd %esi, %xmm4
; AVX2-NEXT:    vpinsrd $1, %edx, %xmm4, %xmm4
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vpinsrd $2, %edx, %xmm4, %xmm4
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm5
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vpinsrd $3, %edx, %xmm4, %xmm4
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vmovd %esi, %xmm5
; AVX2-NEXT:    vpinsrd $1, %edx, %xmm5, %xmm5
; AVX2-NEXT:    vshufps {{.*#+}} xmm6 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vpinsrd $2, %edx, %xmm5, %xmm5
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vpinsrd $3, %edx, %xmm5, %xmm5
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm6
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vmovd %esi, %xmm6
; AVX2-NEXT:    vpinsrd $1, %edx, %xmm6, %xmm6
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm7 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm7, %xmm7
; AVX2-NEXT:    vcvttss2si %xmm7, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm7
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm7
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vpinsrd $2, %edx, %xmm6, %xmm6
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm0
; AVX2-NEXT:    cmovbl %eax, %edx
; AVX2-NEXT:    vucomiss %xmm2, %xmm0
; AVX2-NEXT:    cmoval %ecx, %edx
; AVX2-NEXT:    vinserti128 $1, %xmm3, %ymm4, %ymm0
; AVX2-NEXT:    vpinsrd $3, %edx, %xmm6, %xmm1
; AVX2-NEXT:    vinserti128 $1, %xmm5, %ymm1, %ymm1
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v16i32_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm4
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm4[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX512-NEXT:    vcvttss2usi %xmm3, %edx
; AVX512-NEXT:    xorl %eax, %eax
; AVX512-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [4.29496704E+9,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    movl $-1, %ecx
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm3 = xmm4[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm3, %xmm3
; AVX512-NEXT:    vcvttss2usi %xmm3, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vmovd %esi, %xmm3
; AVX512-NEXT:    vpinsrd $1, %edx, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm5 = xmm4[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vpinsrd $2, %edx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm4[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vpinsrd $3, %edx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrld $16, %xmm4, %xmm5
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vmovd %esi, %xmm5
; AVX512-NEXT:    vpinsrd $1, %edx, %xmm5, %xmm5
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm4[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vpinsrd $2, %edx, %xmm5, %xmm5
; AVX512-NEXT:    vpsrlq $48, %xmm4, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2usi %xmm4, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vpinsrd $3, %edx, %xmm5, %xmm4
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vmovd %esi, %xmm5
; AVX512-NEXT:    vpinsrd $1, %edx, %xmm5, %xmm5
; AVX512-NEXT:    vshufps {{.*#+}} xmm6 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vpinsrd $2, %edx, %xmm5, %xmm5
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vpinsrd $3, %edx, %xmm5, %xmm5
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm6
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %edi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %edi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    vmovd %esi, %xmm6
; AVX512-NEXT:    vpinsrd $1, %edx, %xmm6, %xmm6
; AVX512-NEXT:    cmoval %ecx, %edi
; AVX512-NEXT:    vpinsrd $2, %edi, %xmm6, %xmm6
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm4, %ymm3
; AVX512-NEXT:    vcvttss2usi %xmm0, %edx
; AVX512-NEXT:    vucomiss %xmm1, %xmm0
; AVX512-NEXT:    cmovbl %eax, %edx
; AVX512-NEXT:    vucomiss %xmm2, %xmm0
; AVX512-NEXT:    cmoval %ecx, %edx
; AVX512-NEXT:    vpinsrd $3, %edx, %xmm6, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm5, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm3, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %x = call <16 x i32> @llvm.fptoui.sat.v16i32.v16f16(<16 x half> %f)
  ret <16 x i32> %x
}

define <16 x i64> @test_unsigned_v16i64_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_unsigned_v16i64_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    pushq %r15
; AVX2-NEXT:    pushq %r14
; AVX2-NEXT:    pushq %r13
; AVX2-NEXT:    pushq %r12
; AVX2-NEXT:    pushq %rbx
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [9.22337203E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %rax
; AVX2-NEXT:    vcvttss2si %xmm1, %rcx
; AVX2-NEXT:    movq %rcx, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %rax, %rdx
; AVX2-NEXT:    orq %rcx, %rdx
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vxorps %xmm3, %xmm3, %xmm3
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vmovss {{.*#+}} xmm4 = [1.8446743E+19,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rdi
; AVX2-NEXT:    vcvttss2si %xmm1, %r8
; AVX2-NEXT:    movq %r8, %rsi
; AVX2-NEXT:    sarq $63, %rsi
; AVX2-NEXT:    andq %rdi, %rsi
; AVX2-NEXT:    orq %r8, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm1
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %r8
; AVX2-NEXT:    vcvttss2si %xmm1, %r9
; AVX2-NEXT:    movq %r9, %rdi
; AVX2-NEXT:    sarq $63, %rdi
; AVX2-NEXT:    andq %r8, %rdi
; AVX2-NEXT:    orq %r9, %rdi
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %rdi
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %r9
; AVX2-NEXT:    vcvttss2si %xmm1, %r10
; AVX2-NEXT:    movq %r10, %r8
; AVX2-NEXT:    sarq $63, %r8
; AVX2-NEXT:    andq %r9, %r8
; AVX2-NEXT:    orq %r10, %r8
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %r8
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %r8
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %r10
; AVX2-NEXT:    vcvttss2si %xmm1, %r11
; AVX2-NEXT:    movq %r11, %r9
; AVX2-NEXT:    sarq $63, %r9
; AVX2-NEXT:    andq %r10, %r9
; AVX2-NEXT:    orq %r11, %r9
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %r9
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %r9
; AVX2-NEXT:    vshufps {{.*#+}} xmm1 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %r11
; AVX2-NEXT:    vcvttss2si %xmm1, %rbx
; AVX2-NEXT:    movq %rbx, %r10
; AVX2-NEXT:    sarq $63, %r10
; AVX2-NEXT:    andq %r11, %r10
; AVX2-NEXT:    orq %rbx, %r10
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %r10
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %r10
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rbx
; AVX2-NEXT:    vcvttss2si %xmm1, %r14
; AVX2-NEXT:    movq %r14, %r11
; AVX2-NEXT:    sarq $63, %r11
; AVX2-NEXT:    andq %rbx, %r11
; AVX2-NEXT:    orq %r14, %r11
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %r11
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %r11
; AVX2-NEXT:    vshufpd {{.*#+}} xmm1 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %r14
; AVX2-NEXT:    vcvttss2si %xmm1, %r15
; AVX2-NEXT:    movq %r15, %rbx
; AVX2-NEXT:    sarq $63, %rbx
; AVX2-NEXT:    andq %r14, %rbx
; AVX2-NEXT:    orq %r15, %rbx
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %rbx
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %rbx
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm5
; AVX2-NEXT:    vpsrlq $48, %xmm5, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vsubss %xmm2, %xmm0, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %r15
; AVX2-NEXT:    vcvttss2si %xmm0, %r12
; AVX2-NEXT:    movq %r12, %r14
; AVX2-NEXT:    sarq $63, %r14
; AVX2-NEXT:    andq %r15, %r14
; AVX2-NEXT:    orq %r12, %r14
; AVX2-NEXT:    vucomiss %xmm3, %xmm0
; AVX2-NEXT:    cmovbq %rax, %r14
; AVX2-NEXT:    vucomiss %xmm4, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %r14
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm5[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vsubss %xmm2, %xmm0, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %r12
; AVX2-NEXT:    vcvttss2si %xmm0, %r13
; AVX2-NEXT:    movq %r13, %r15
; AVX2-NEXT:    sarq $63, %r15
; AVX2-NEXT:    andq %r12, %r15
; AVX2-NEXT:    orq %r13, %r15
; AVX2-NEXT:    vucomiss %xmm3, %xmm0
; AVX2-NEXT:    cmovbq %rax, %r15
; AVX2-NEXT:    vucomiss %xmm4, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %r15
; AVX2-NEXT:    vmovq %rdx, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm1
; AVX2-NEXT:    vmovq %rsi, %xmm6
; AVX2-NEXT:    vsubss %xmm2, %xmm1, %xmm7
; AVX2-NEXT:    vcvttss2si %xmm7, %rsi
; AVX2-NEXT:    vcvttss2si %xmm1, %r12
; AVX2-NEXT:    movq %r12, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %rsi, %rdx
; AVX2-NEXT:    orq %r12, %rdx
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vucomiss %xmm4, %xmm1
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vmovq %rdi, %xmm7
; AVX2-NEXT:    vpsrld $16, %xmm5, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm8
; AVX2-NEXT:    vmovq %r8, %xmm9
; AVX2-NEXT:    vsubss %xmm2, %xmm8, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %rdi
; AVX2-NEXT:    vmovq %r9, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm8, %r8
; AVX2-NEXT:    movq %r8, %rsi
; AVX2-NEXT:    sarq $63, %rsi
; AVX2-NEXT:    andq %rdi, %rsi
; AVX2-NEXT:    orq %r8, %rsi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm6[0],xmm0[0]
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm6 = xmm7[0],xmm9[0]
; AVX2-NEXT:    vinserti128 $1, %xmm0, %ymm6, %ymm0
; AVX2-NEXT:    vucomiss %xmm3, %xmm8
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm4, %xmm8
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vmovq %r10, %xmm6
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm7 = xmm5[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm7, %xmm7
; AVX2-NEXT:    vmovq %r11, %xmm8
; AVX2-NEXT:    vsubss %xmm2, %xmm7, %xmm9
; AVX2-NEXT:    vcvttss2si %xmm9, %r8
; AVX2-NEXT:    vmovq %rbx, %xmm9
; AVX2-NEXT:    vcvttss2si %xmm7, %r9
; AVX2-NEXT:    movq %r9, %rdi
; AVX2-NEXT:    sarq $63, %rdi
; AVX2-NEXT:    andq %r8, %rdi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm6[0],xmm1[0]
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm6 = xmm9[0],xmm8[0]
; AVX2-NEXT:    vinserti128 $1, %xmm1, %ymm6, %ymm1
; AVX2-NEXT:    orq %r9, %rdi
; AVX2-NEXT:    vucomiss %xmm3, %xmm7
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomiss %xmm4, %xmm7
; AVX2-NEXT:    cmovaq %rcx, %rdi
; AVX2-NEXT:    vmovq %r14, %xmm6
; AVX2-NEXT:    vshufps {{.*#+}} xmm7 = xmm5[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm7, %xmm7
; AVX2-NEXT:    vmovq %r15, %xmm8
; AVX2-NEXT:    vsubss %xmm2, %xmm7, %xmm9
; AVX2-NEXT:    vcvttss2si %xmm9, %r9
; AVX2-NEXT:    vcvttss2si %xmm7, %r10
; AVX2-NEXT:    movq %r10, %r8
; AVX2-NEXT:    sarq $63, %r8
; AVX2-NEXT:    andq %r9, %r8
; AVX2-NEXT:    orq %r10, %r8
; AVX2-NEXT:    vucomiss %xmm3, %xmm7
; AVX2-NEXT:    cmovbq %rax, %r8
; AVX2-NEXT:    vucomiss %xmm4, %xmm7
; AVX2-NEXT:    cmovaq %rcx, %r8
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm7 = xmm5[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm7, %xmm7
; AVX2-NEXT:    vsubss %xmm2, %xmm7, %xmm9
; AVX2-NEXT:    vcvttss2si %xmm9, %r9
; AVX2-NEXT:    vcvttss2si %xmm7, %r10
; AVX2-NEXT:    vmovq %rdx, %xmm9
; AVX2-NEXT:    movq %r10, %rdx
; AVX2-NEXT:    sarq $63, %rdx
; AVX2-NEXT:    andq %r9, %rdx
; AVX2-NEXT:    orq %r10, %rdx
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm6 = xmm8[0],xmm6[0]
; AVX2-NEXT:    vucomiss %xmm3, %xmm7
; AVX2-NEXT:    cmovbq %rax, %rdx
; AVX2-NEXT:    vucomiss %xmm4, %xmm7
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vmovq %rsi, %xmm7
; AVX2-NEXT:    vshufpd {{.*#+}} xmm5 = xmm5[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vmovq %rdi, %xmm8
; AVX2-NEXT:    vsubss %xmm2, %xmm5, %xmm2
; AVX2-NEXT:    vcvttss2si %xmm2, %rsi
; AVX2-NEXT:    vmovq %r8, %xmm10
; AVX2-NEXT:    vcvttss2si %xmm5, %rdi
; AVX2-NEXT:    movq %rdi, %r8
; AVX2-NEXT:    sarq $63, %r8
; AVX2-NEXT:    andq %rsi, %r8
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm9[0],xmm7[0]
; AVX2-NEXT:    vinserti128 $1, %xmm6, %ymm2, %ymm2
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm6 = xmm10[0],xmm8[0]
; AVX2-NEXT:    orq %rdi, %r8
; AVX2-NEXT:    vucomiss %xmm3, %xmm5
; AVX2-NEXT:    cmovbq %rax, %r8
; AVX2-NEXT:    vucomiss %xmm4, %xmm5
; AVX2-NEXT:    cmovaq %rcx, %r8
; AVX2-NEXT:    vmovq %rdx, %xmm3
; AVX2-NEXT:    vmovq %r8, %xmm4
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm3 = xmm4[0],xmm3[0]
; AVX2-NEXT:    vinserti128 $1, %xmm6, %ymm3, %ymm3
; AVX2-NEXT:    popq %rbx
; AVX2-NEXT:    popq %r12
; AVX2-NEXT:    popq %r13
; AVX2-NEXT:    popq %r14
; AVX2-NEXT:    popq %r15
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v16i64_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm2
; AVX512-NEXT:    vcvttss2usi %xmm2, %rdx
; AVX512-NEXT:    xorl %eax, %eax
; AVX512-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vucomiss %xmm1, %xmm2
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vmovss {{.*#+}} xmm3 = [1.8446743E+19,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vucomiss %xmm3, %xmm2
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm2
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2usi %xmm4, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm4[0],xmm2[0]
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2usi %xmm4, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm5
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm6
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %rdx
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm5[0],xmm4[0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %rsi
; AVX512-NEXT:    vinserti128 $1, %xmm2, %ymm4, %ymm2
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm3, %xmm5
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %rdx
; AVX512-NEXT:    vmovq %rsi, %xmm6
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm5
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm5
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %rsi
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm6[0],xmm4[0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm3, %xmm5
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vmovq %rsi, %xmm6
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm5[0],xmm6[0]
; AVX512-NEXT:    vinserti128 $1, %xmm4, %ymm5, %ymm4
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm4, %zmm2
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2usi %xmm4, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vshufps {{.*#+}} xmm5 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm5
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %rdx
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm5[0],xmm4[0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm6
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm3, %xmm5
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm5
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm5[0],xmm6[0]
; AVX512-NEXT:    vinserti128 $1, %xmm4, %ymm5, %ymm4
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm5
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2usi %xmm5, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm5
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm5
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm6
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm6[0],xmm5[0]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm6
; AVX512-NEXT:    vcvttss2usi %xmm6, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm6
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vcvttss2usi %xmm0, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm0
; AVX512-NEXT:    cmovbq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm0
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm0
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm6[0],xmm0[0]
; AVX512-NEXT:    vinserti128 $1, %xmm5, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm4, %zmm0, %zmm1
; AVX512-NEXT:    vmovdqa64 %zmm2, %zmm0
; AVX512-NEXT:    retq
  %x = call <16 x i64> @llvm.fptoui.sat.v16i64.v16f16(<16 x half> %f)
  ret <16 x i64> %x
}

define <16 x i128> @test_unsigned_v16i128_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_unsigned_v16i128_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    pushq %rbp
; AVX2-NEXT:    pushq %r15
; AVX2-NEXT:    pushq %r14
; AVX2-NEXT:    pushq %r13
; AVX2-NEXT:    pushq %r12
; AVX2-NEXT:    pushq %rbx
; AVX2-NEXT:    subq $328, %rsp # imm = 0x148
; AVX2-NEXT:    vmovdqu %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; AVX2-NEXT:    movq %rdi, %rbx
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    xorl %r13d, %r13d
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    movq $-1, %rbp
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovshdup {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilpd $1, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilps $255, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmovdqa %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovshdup (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqa (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilpd $1, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqa (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %rdx
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilps $255, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    movq %rdx, %r14
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %r14
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovaq %rbp, %r14
; AVX2-NEXT:    vmovdqa (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    movq %rax, %r15
; AVX2-NEXT:    movq %rdx, %r12
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    cmovbq %r13, %r12
; AVX2-NEXT:    cmovbq %r13, %r15
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    cmovaq %rbp, %r15
; AVX2-NEXT:    cmovaq %rbp, %r12
; AVX2-NEXT:    vcvtph2ps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    movq %rax, %r13
; AVX2-NEXT:    movq %rdx, %rbp
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    movl $0, %eax
; AVX2-NEXT:    cmovbq %rax, %rbp
; AVX2-NEXT:    cmovbq %rax, %r13
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    movq $-1, %rax
; AVX2-NEXT:    cmovaq %rax, %r13
; AVX2-NEXT:    cmovaq %rax, %rbp
; AVX2-NEXT:    vcvtph2ps (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixunssfti@PLT
; AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX2-NEXT:    vucomiss %xmm0, %xmm1
; AVX2-NEXT:    movl $0, %ecx
; AVX2-NEXT:    cmovbq %rcx, %rdx
; AVX2-NEXT:    cmovbq %rcx, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rax
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    movq %rdx, 136(%rbx)
; AVX2-NEXT:    movq %rax, 128(%rbx)
; AVX2-NEXT:    movq %rbp, 8(%rbx)
; AVX2-NEXT:    movq %r13, (%rbx)
; AVX2-NEXT:    movq %r12, 248(%rbx)
; AVX2-NEXT:    movq %r15, 240(%rbx)
; AVX2-NEXT:    movq %r14, 232(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 224(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 216(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 208(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 200(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 192(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 184(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 176(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 168(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 160(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 152(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 144(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 120(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 112(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 104(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 96(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 88(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 80(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 72(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 64(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 56(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 48(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 40(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 32(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 24(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 16(%rbx)
; AVX2-NEXT:    movq %rbx, %rax
; AVX2-NEXT:    addq $328, %rsp # imm = 0x148
; AVX2-NEXT:    popq %rbx
; AVX2-NEXT:    popq %r12
; AVX2-NEXT:    popq %r13
; AVX2-NEXT:    popq %r14
; AVX2-NEXT:    popq %r15
; AVX2-NEXT:    popq %rbp
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_unsigned_v16i128_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    pushq %rbp
; AVX512-NEXT:    pushq %r15
; AVX512-NEXT:    pushq %r14
; AVX512-NEXT:    pushq %r13
; AVX512-NEXT:    pushq %r12
; AVX512-NEXT:    pushq %rbx
; AVX512-NEXT:    subq $328, %rsp # imm = 0x148
; AVX512-NEXT:    vmovdqu %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; AVX512-NEXT:    movq %rdi, %rbx
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    xorl %r13d, %r13d
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    movq $-1, %rbp
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vmovshdup {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrlq $48, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilpd $1, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrldq $10, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilps $255, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrldq $14, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps (%rsp), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmovdqa %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vmovshdup (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrlq $48, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilpd $1, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrldq $10, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %rdx
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilps $255, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    movq %rdx, %r14
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %r14
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovaq %rbp, %r14
; AVX512-NEXT:    vpsrldq $14, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    movq %rax, %r15
; AVX512-NEXT:    movq %rdx, %r12
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    cmovbq %r13, %r12
; AVX512-NEXT:    cmovbq %r13, %r15
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    cmovaq %rbp, %r15
; AVX512-NEXT:    cmovaq %rbp, %r12
; AVX512-NEXT:    vcvtph2ps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    movq %rax, %r13
; AVX512-NEXT:    movq %rdx, %rbp
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    movl $0, %eax
; AVX512-NEXT:    cmovbq %rax, %rbp
; AVX512-NEXT:    cmovbq %rax, %r13
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    movq $-1, %rax
; AVX512-NEXT:    cmovaq %rax, %r13
; AVX512-NEXT:    cmovaq %rax, %rbp
; AVX512-NEXT:    vcvtph2ps (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixunssfti@PLT
; AVX512-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 # 16-byte Reload
; AVX512-NEXT:    vucomiss %xmm0, %xmm1
; AVX512-NEXT:    movl $0, %ecx
; AVX512-NEXT:    cmovbq %rcx, %rdx
; AVX512-NEXT:    cmovbq %rcx, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rax
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    movq %rdx, 136(%rbx)
; AVX512-NEXT:    movq %rax, 128(%rbx)
; AVX512-NEXT:    movq %rbp, 8(%rbx)
; AVX512-NEXT:    movq %r13, (%rbx)
; AVX512-NEXT:    movq %r12, 248(%rbx)
; AVX512-NEXT:    movq %r15, 240(%rbx)
; AVX512-NEXT:    movq %r14, 232(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 224(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 216(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 208(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 200(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 192(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 184(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 176(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 168(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 160(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 152(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 144(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 120(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 112(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 104(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 96(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 88(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 80(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 72(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 64(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 56(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 48(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 40(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 32(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 24(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 16(%rbx)
; AVX512-NEXT:    movq %rbx, %rax
; AVX512-NEXT:    addq $328, %rsp # imm = 0x148
; AVX512-NEXT:    popq %rbx
; AVX512-NEXT:    popq %r12
; AVX512-NEXT:    popq %r13
; AVX512-NEXT:    popq %r14
; AVX512-NEXT:    popq %r15
; AVX512-NEXT:    popq %rbp
; AVX512-NEXT:    retq
  %x = call <16 x i128> @llvm.fptoui.sat.v16i128.v16f16(<16 x half> %f)
  ret <16 x i128> %x
}
