; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v3 | FileCheck %s --check-prefixes=CHECK,AVX2
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v4 | FileCheck %s --check-prefixes=CHECK,AVX512

;
; 32-bit float to signed integer
;

define <8 x i1> @test_signed_v8i1_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_signed_v8i1_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrw $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrw $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v8i1_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vxorps %xmm3, %xmm3, %xmm3
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vpmovzxbq {{.*#+}} zmm0 = xmm0[0],zero,zero,zero,zero,zero,zero,zero,xmm0[1],zero,zero,zero,zero,zero,zero,zero,xmm0[2],zero,zero,zero,zero,zero,zero,zero,xmm0[3],zero,zero,zero,zero,zero,zero,zero,xmm0[4],zero,zero,zero,zero,zero,zero,zero,xmm0[5],zero,zero,zero,zero,zero,zero,zero,xmm0[6],zero,zero,zero,zero,zero,zero,zero,xmm0[7],zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vptestmq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %zmm0, %k0
; AVX512-NEXT:    vpmovm2w %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i1> @llvm.fptosi.sat.v8i1.v8f32(<8 x float> %f)
  ret <8 x i1> %x
}

define <8 x i1> @test_freeze_signed_v8i1_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_freeze_signed_v8i1_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrw $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrw $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_freeze_signed_v8i1_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vxorps %xmm3, %xmm3, %xmm3
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vpmovzxbq {{.*#+}} zmm0 = xmm0[0],zero,zero,zero,zero,zero,zero,zero,xmm0[1],zero,zero,zero,zero,zero,zero,zero,xmm0[2],zero,zero,zero,zero,zero,zero,zero,xmm0[3],zero,zero,zero,zero,zero,zero,zero,xmm0[4],zero,zero,zero,zero,zero,zero,zero,xmm0[5],zero,zero,zero,zero,zero,zero,zero,xmm0[6],zero,zero,zero,zero,zero,zero,zero,xmm0[7],zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vptestmq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %zmm0, %k0
; AVX512-NEXT:    vpmovm2w %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i1> @llvm.fptosi.sat.v8i1.v8f32(<8 x float> %f)
  %y = freeze <8 x i1> %x
  ret <8 x i1> %y
}

define <8 x i8> @test_signed_v8i8_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_signed_v8i8_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [-1.28E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [1.27E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrb $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrb $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrb $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v8i8_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [-1.28E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vmovss {{.*#+}} xmm3 = [1.27E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i8> @llvm.fptosi.sat.v8i8.v8f32(<8 x float> %f)
  ret <8 x i8> %x
}

define <8 x i16> @test_signed_v8i16_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_signed_v8i16_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [-3.2768E+4,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vmaxss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [3.2767E+4,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %eax
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm3
; AVX2-NEXT:    vminss %xmm3, %xmm2, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %ecx
; AVX2-NEXT:    vmovd %ecx, %xmm3
; AVX2-NEXT:    vpinsrw $1, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $2, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $3, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $4, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $5, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vmaxss %xmm4, %xmm1, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %eax
; AVX2-NEXT:    vpinsrw $6, %eax, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX2-NEXT:    vmaxss %xmm0, %xmm1, %xmm0
; AVX2-NEXT:    vminss %xmm0, %xmm2, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %eax
; AVX2-NEXT:    vpinsrw $7, %eax, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v8i16_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [-3.2768E+4,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vmovss {{.*#+}} xmm3 = [3.2767E+4,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %eax
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrw $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $3, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $4, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $5, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vmaxss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %eax
; AVX512-NEXT:    vpinsrw $6, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; AVX512-NEXT:    vmaxss %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminss %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %eax
; AVX512-NEXT:    vpinsrw $7, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <8 x i16> @llvm.fptosi.sat.v8i16.v8f32(<8 x float> %f)
  ret <8 x i16> %x
}

define <8 x i32> @test_signed_v8i32_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_signed_v8i32_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vbroadcastss {{.*#+}} ymm1 = [2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9,2.14748365E+9]
; AVX2-NEXT:    vcmpleps %ymm0, %ymm1, %ymm1
; AVX2-NEXT:    vcvttps2dq %ymm0, %ymm2
; AVX2-NEXT:    vbroadcastss {{.*#+}} ymm3 = [2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647]
; AVX2-NEXT:    vblendvps %ymm1, %ymm3, %ymm2, %ymm1
; AVX2-NEXT:    vcmpunordps %ymm0, %ymm0, %ymm0
; AVX2-NEXT:    vandnps %ymm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v8i32_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vcmpgeps {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to8}, %ymm0, %k1
; AVX512-NEXT:    vcvttps2dq %ymm0, %ymm1
; AVX512-NEXT:    vpbroadcastd {{.*#+}} ymm1 {%k1} = [2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647,2147483647]
; AVX512-NEXT:    vcmpunordps %ymm0, %ymm0, %k0
; AVX512-NEXT:    knotb %k0, %k1
; AVX512-NEXT:    vmovdqa32 %ymm1, %ymm0 {%k1} {z}
; AVX512-NEXT:    retq
  %x = call <8 x i32> @llvm.fptosi.sat.v8i32.v8f32(<8 x float> %f)
  ret <8 x i32> %x
}

define <8 x i64> @test_signed_v8i64_v8f32(<8 x float> %f) nounwind {
; AVX2-LABEL: test_signed_v8i64_v8f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vshufps {{.*#+}} xmm2 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvttss2si %xmm2, %rsi
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [9.22337149E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm1, %xmm2
; AVX2-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vucomiss %xmm2, %xmm2
; AVX2-NEXT:    cmovpq %rax, %rsi
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm0[1,0]
; AVX2-NEXT:    vcvttss2si %xmm2, %rdi
; AVX2-NEXT:    vucomiss %xmm1, %xmm2
; AVX2-NEXT:    cmovaq %rcx, %rdi
; AVX2-NEXT:    vucomiss %xmm2, %xmm2
; AVX2-NEXT:    cmovpq %rax, %rdi
; AVX2-NEXT:    vcvttss2si %xmm0, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rax, %rdx
; AVX2-NEXT:    vmovq %rsi, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvttss2si %xmm2, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm2
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vmovq %rdi, %xmm4
; AVX2-NEXT:    vucomiss %xmm2, %xmm2
; AVX2-NEXT:    cmovpq %rax, %rsi
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm2
; AVX2-NEXT:    vshufps {{.*#+}} xmm5 = xmm2[3,3,3,3]
; AVX2-NEXT:    vcvttss2si %xmm5, %rdi
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovaq %rcx, %rdi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm4[0],xmm3[0]
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpq %rax, %rdi
; AVX2-NEXT:    vmovq %rdx, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; AVX2-NEXT:    vcvttss2si %xmm4, %rdx
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vmovq %rsi, %xmm5
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm3 = xmm3[0],xmm5[0]
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    vmovq %rdi, %xmm4
; AVX2-NEXT:    cmovpq %rax, %rdx
; AVX2-NEXT:    vcvttss2si %xmm2, %rsi
; AVX2-NEXT:    vucomiss %xmm1, %xmm2
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vucomiss %xmm2, %xmm2
; AVX2-NEXT:    cmovpq %rax, %rsi
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm2[1,1,3,3]
; AVX2-NEXT:    vucomiss %xmm1, %xmm2
; AVX2-NEXT:    vmovq %rdx, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm2, %rdx
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vinserti128 $1, %xmm0, %ymm3, %ymm0
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm4[0]
; AVX2-NEXT:    vucomiss %xmm2, %xmm2
; AVX2-NEXT:    cmovpq %rax, %rdx
; AVX2-NEXT:    vmovq %rsi, %xmm2
; AVX2-NEXT:    vmovq %rdx, %xmm3
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm2[0],xmm3[0]
; AVX2-NEXT:    vinserti128 $1, %xmm1, %ymm2, %ymm1
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v8i64_v8f32:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm2
; AVX512-NEXT:    vshufps {{.*#+}} xmm3 = xmm2[3,3,3,3]
; AVX512-NEXT:    vcvttss2si %xmm3, %rdx
; AVX512-NEXT:    vmovss {{.*#+}} xmm1 = [9.22337149E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    movabsq $9223372036854775807, %rax # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rax, %rdx
; AVX512-NEXT:    xorl %ecx, %ecx
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm3 = xmm2[1,0]
; AVX512-NEXT:    vcvttss2si %xmm3, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovaq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rcx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm3
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm3 = xmm3[0],xmm4[0]
; AVX512-NEXT:    vcvttss2si %xmm2, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm2
; AVX512-NEXT:    cmovaq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm2, %xmm2
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm2[1,1,3,3]
; AVX512-NEXT:    vcvttss2si %xmm2, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm2
; AVX512-NEXT:    cmovaq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm2, %xmm2
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm2
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm2 = xmm4[0],xmm2[0]
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm2, %ymm2
; AVX512-NEXT:    vshufps {{.*#+}} xmm3 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvttss2si %xmm3, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovaq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm3 = xmm0[1,0]
; AVX512-NEXT:    vcvttss2si %xmm3, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovaq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rcx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm3
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm3 = xmm3[0],xmm4[0]
; AVX512-NEXT:    vcvttss2si %xmm0, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm0
; AVX512-NEXT:    cmovaq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm4
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvttss2si %xmm0, %rdx
; AVX512-NEXT:    vucomiss %xmm1, %xmm0
; AVX512-NEXT:    cmovaq %rax, %rdx
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    vmovq %rdx, %xmm0
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm4[0],xmm0[0]
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm2, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %x = call <8 x i64> @llvm.fptosi.sat.v8i64.v8f32(<8 x float> %f)
  ret <8 x i64> %x
}

define <8 x i128> @test_signed_v8i128_v8f32(<8 x float> %f) nounwind {
; CHECK-LABEL: test_signed_v8i128_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    subq $168, %rsp
; CHECK-NEXT:    vmovups %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; CHECK-NEXT:    movq %rdi, %rbx
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm0[1,1,3,3]
; CHECK-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    xorl %r12d, %r12d
; CHECK-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    movabsq $-9223372036854775808, %rbp # imm = 0x8000000000000000
; CHECK-NEXT:    cmovbq %rbp, %rdx
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    movabsq $9223372036854775807, %r15 # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    cmovaq %r15, %rdx
; CHECK-NEXT:    movq $-1, %rcx
; CHECK-NEXT:    cmovaq %rcx, %rax
; CHECK-NEXT:    movq $-1, %r13
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %r12, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovpq %r12, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vpermilpd $1, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[1,0]
; CHECK-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    cmovbq %rbp, %rdx
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovaq %r15, %rdx
; CHECK-NEXT:    cmovaq %r13, %rax
; CHECK-NEXT:    movq $-1, %r14
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %r12, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovpq %r12, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vpermilps $255, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[3,3,3,3]
; CHECK-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    cmovbq %rbp, %rdx
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovaq %r15, %rdx
; CHECK-NEXT:    cmovaq %r14, %rax
; CHECK-NEXT:    movq $-1, %r14
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %r12, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovpq %r12, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm0[1,1,3,3]
; CHECK-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    cmovbq %rbp, %rdx
; CHECK-NEXT:    movq %rbp, %r13
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovaq %r15, %rdx
; CHECK-NEXT:    cmovaq %r14, %rax
; CHECK-NEXT:    movq $-1, %r14
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %r12, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovpq %r12, %rdx
; CHECK-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    vpermilpd $1, (%rsp), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[1,0]
; CHECK-NEXT:    vmovapd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    movq %rdx, %rbp
; CHECK-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovbq %r12, %rax
; CHECK-NEXT:    cmovbq %r13, %rbp
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovaq %r15, %rbp
; CHECK-NEXT:    movq %r15, %r13
; CHECK-NEXT:    cmovaq %r14, %rax
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %r12, %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    cmovpq %r12, %rbp
; CHECK-NEXT:    vpermilps $255, (%rsp), %xmm0 # 16-byte Folded Reload
; CHECK-NEXT:    # xmm0 = mem[3,3,3,3]
; CHECK-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    movq %rax, %r14
; CHECK-NEXT:    movq %rdx, %r15
; CHECK-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovbq %r12, %r14
; CHECK-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; CHECK-NEXT:    cmovbq %rax, %r15
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    cmovaq %r13, %r15
; CHECK-NEXT:    movq $-1, %rax
; CHECK-NEXT:    cmovaq %rax, %r14
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %r12, %r14
; CHECK-NEXT:    cmovpq %r12, %r15
; CHECK-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    movq %rax, %r12
; CHECK-NEXT:    movq %rdx, %r13
; CHECK-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    movl $0, %eax
; CHECK-NEXT:    cmovbq %rax, %r12
; CHECK-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; CHECK-NEXT:    cmovbq %rcx, %r13
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    cmovaq %rcx, %r13
; CHECK-NEXT:    movq $-1, %rcx
; CHECK-NEXT:    cmovaq %rcx, %r12
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %rax, %r12
; CHECK-NEXT:    cmovpq %rax, %r13
; CHECK-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    callq __fixsfti@PLT
; CHECK-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; CHECK-NEXT:    cmovbq %rcx, %rdx
; CHECK-NEXT:    movl $0, %esi
; CHECK-NEXT:    cmovbq %rsi, %rax
; CHECK-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    cmovaq %rcx, %rdx
; CHECK-NEXT:    movq $-1, %rcx
; CHECK-NEXT:    cmovaq %rcx, %rax
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpq %rsi, %rax
; CHECK-NEXT:    movl $0, %ecx
; CHECK-NEXT:    cmovpq %rcx, %rdx
; CHECK-NEXT:    movq %rdx, 72(%rbx)
; CHECK-NEXT:    movq %rax, 64(%rbx)
; CHECK-NEXT:    movq %r13, 8(%rbx)
; CHECK-NEXT:    movq %r12, (%rbx)
; CHECK-NEXT:    movq %r15, 120(%rbx)
; CHECK-NEXT:    movq %r14, 112(%rbx)
; CHECK-NEXT:    movq %rbp, 104(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 96(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 88(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 80(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 56(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 48(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 40(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 32(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 24(%rbx)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, 16(%rbx)
; CHECK-NEXT:    movq %rbx, %rax
; CHECK-NEXT:    addq $168, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    retq
  %x = call <8 x i128> @llvm.fptosi.sat.v8i128.v8f32(<8 x float> %f)
  ret <8 x i128> %x
}

;
; 64-bit float to signed integer
;

define <4 x i1> @test_signed_v4i1_v4f64(<4 x double> %f) nounwind {
; AVX2-LABEL: test_signed_v4i1_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vcmpunordpd %ymm0, %ymm0, %ymm1
; AVX2-NEXT:    vbroadcastsd {{.*#+}} ymm2 = [-1.0E+0,-1.0E+0,-1.0E+0,-1.0E+0]
; AVX2-NEXT:    vmaxpd %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vminpd %ymm2, %ymm0, %ymm0
; AVX2-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX2-NEXT:    vcvttpd2dq %ymm0, %xmm0
; AVX2-NEXT:    vpackssdw %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vblendvps %xmm1, %xmm2, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v4i1_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vshufpd {{.*#+}} xmm1 = xmm0[1,0]
; AVX512-NEXT:    vmovsd {{.*#+}} xmm2 = [-1.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxsd %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vxorpd %xmm3, %xmm3, %xmm3
; AVX512-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttsd2si %xmm1, %eax
; AVX512-NEXT:    vmaxsd %xmm0, %xmm2, %xmm1
; AVX512-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; AVX512-NEXT:    vcvttsd2si %xmm1, %ecx
; AVX512-NEXT:    vmovd %ecx, %xmm1
; AVX512-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmaxsd %xmm0, %xmm2, %xmm4
; AVX512-NEXT:    vminsd %xmm4, %xmm3, %xmm4
; AVX512-NEXT:    vcvttsd2si %xmm4, %eax
; AVX512-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; AVX512-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX512-NEXT:    vmaxsd %xmm0, %xmm2, %xmm0
; AVX512-NEXT:    vminsd %xmm0, %xmm3, %xmm0
; AVX512-NEXT:    vcvttsd2si %xmm0, %eax
; AVX512-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm0
; AVX512-NEXT:    vpmovzxbd {{.*#+}} xmm0 = xmm0[0],zero,zero,zero,xmm0[1],zero,zero,zero,xmm0[2],zero,zero,zero,xmm0[3],zero,zero,zero
; AVX512-NEXT:    vptestmd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %xmm0, %k0
; AVX512-NEXT:    vpmovm2d %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <4 x i1> @llvm.fptosi.sat.v4i1.v4f64(<4 x double> %f)
  ret <4 x i1> %x
}

define <4 x i8> @test_signed_v4i8_v4f64(<4 x double> %f) nounwind {
; CHECK-LABEL: test_signed_v4i8_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vshufpd {{.*#+}} xmm1 = xmm0[1,0]
; CHECK-NEXT:    vmovsd {{.*#+}} xmm2 = [-1.28E+2,0.0E+0]
; CHECK-NEXT:    vmaxsd %xmm1, %xmm2, %xmm1
; CHECK-NEXT:    vmovsd {{.*#+}} xmm3 = [1.27E+2,0.0E+0]
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %eax
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm1
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %ecx
; CHECK-NEXT:    vmovd %ecx, %xmm1
; CHECK-NEXT:    vpinsrb $1, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm4
; CHECK-NEXT:    vminsd %xmm4, %xmm3, %xmm4
; CHECK-NEXT:    vcvttsd2si %xmm4, %eax
; CHECK-NEXT:    vpinsrb $2, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm0
; CHECK-NEXT:    vminsd %xmm0, %xmm3, %xmm0
; CHECK-NEXT:    vcvttsd2si %xmm0, %eax
; CHECK-NEXT:    vpinsrb $3, %eax, %xmm1, %xmm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %x = call <4 x i8> @llvm.fptosi.sat.v4i8.v4f64(<4 x double> %f)
  ret <4 x i8> %x
}

define <4 x i16> @test_signed_v4i16_v4f64(<4 x double> %f) nounwind {
; CHECK-LABEL: test_signed_v4i16_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vshufpd {{.*#+}} xmm1 = xmm0[1,0]
; CHECK-NEXT:    vmovsd {{.*#+}} xmm2 = [-3.2768E+4,0.0E+0]
; CHECK-NEXT:    vmaxsd %xmm1, %xmm2, %xmm1
; CHECK-NEXT:    vmovsd {{.*#+}} xmm3 = [3.2767E+4,0.0E+0]
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %eax
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm1
; CHECK-NEXT:    vminsd %xmm1, %xmm3, %xmm1
; CHECK-NEXT:    vcvttsd2si %xmm1, %ecx
; CHECK-NEXT:    vmovd %ecx, %xmm1
; CHECK-NEXT:    vpinsrw $1, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm0
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm4
; CHECK-NEXT:    vminsd %xmm4, %xmm3, %xmm4
; CHECK-NEXT:    vcvttsd2si %xmm4, %eax
; CHECK-NEXT:    vpinsrw $2, %eax, %xmm1, %xmm1
; CHECK-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; CHECK-NEXT:    vmaxsd %xmm0, %xmm2, %xmm0
; CHECK-NEXT:    vminsd %xmm0, %xmm3, %xmm0
; CHECK-NEXT:    vcvttsd2si %xmm0, %eax
; CHECK-NEXT:    vpinsrw $3, %eax, %xmm1, %xmm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %x = call <4 x i16> @llvm.fptosi.sat.v4i16.v4f64(<4 x double> %f)
  ret <4 x i16> %x
}

define <4 x i32> @test_signed_v4i32_v4f64(<4 x double> %f) nounwind {
; AVX2-LABEL: test_signed_v4i32_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vbroadcastsd {{.*#+}} ymm1 = [2.147483648E+9,2.147483648E+9,2.147483648E+9,2.147483648E+9]
; AVX2-NEXT:    vcmplepd %ymm0, %ymm1, %ymm1
; AVX2-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX2-NEXT:    vpackssdw %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vcvttpd2dq %ymm0, %xmm2
; AVX2-NEXT:    vbroadcastss {{.*#+}} xmm3 = [2147483647,2147483647,2147483647,2147483647]
; AVX2-NEXT:    vblendvps %xmm1, %xmm3, %xmm2, %xmm1
; AVX2-NEXT:    vcmpunordpd %ymm0, %ymm0, %ymm0
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm2
; AVX2-NEXT:    vpackssdw %xmm2, %xmm0, %xmm0
; AVX2-NEXT:    vxorpd %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vblendvps %xmm0, %xmm2, %xmm1, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v4i32_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vcmpgepd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %ymm0, %k1
; AVX512-NEXT:    vcvttpd2dq %ymm0, %xmm1
; AVX512-NEXT:    vpbroadcastd {{.*#+}} xmm1 {%k1} = [2147483647,2147483647,2147483647,2147483647]
; AVX512-NEXT:    vcmpunordpd %ymm0, %ymm0, %k0
; AVX512-NEXT:    knotw %k0, %k1
; AVX512-NEXT:    vmovdqa32 %xmm1, %xmm0 {%k1} {z}
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <4 x i32> @llvm.fptosi.sat.v4i32.v4f64(<4 x double> %f)
  ret <4 x i32> %x
}

define <4 x i64> @test_signed_v4i64_v4f64(<4 x double> %f) nounwind {
; AVX2-LABEL: test_signed_v4i64_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm2
; AVX2-NEXT:    vcvttsd2si %xmm2, %rdx
; AVX2-NEXT:    vmovsd {{.*#+}} xmm1 = [9.2233720368547748E+18,0.0E+0]
; AVX2-NEXT:    vucomisd %xmm1, %xmm2
; AVX2-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vucomisd %xmm2, %xmm2
; AVX2-NEXT:    cmovpq %rax, %rdx
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm2[1,0]
; AVX2-NEXT:    vcvttsd2si %xmm2, %rsi
; AVX2-NEXT:    vucomisd %xmm1, %xmm2
; AVX2-NEXT:    cmovaq %rcx, %rsi
; AVX2-NEXT:    vucomisd %xmm2, %xmm2
; AVX2-NEXT:    cmovpq %rax, %rsi
; AVX2-NEXT:    vcvttsd2si %xmm0, %rdi
; AVX2-NEXT:    vucomisd %xmm1, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %rdi
; AVX2-NEXT:    vmovq %rdx, %xmm2
; AVX2-NEXT:    vucomisd %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rax, %rdi
; AVX2-NEXT:    vmovq %rsi, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX2-NEXT:    vcvttsd2si %xmm0, %rdx
; AVX2-NEXT:    vucomisd %xmm1, %xmm0
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm2[0],xmm3[0]
; AVX2-NEXT:    vucomisd %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rax, %rdx
; AVX2-NEXT:    vmovq %rdi, %xmm0
; AVX2-NEXT:    vmovq %rdx, %xmm2
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm0[0],xmm2[0]
; AVX2-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v4i64_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX512-NEXT:    vcvttsd2si %xmm1, %rdx
; AVX512-NEXT:    vmovsd {{.*#+}} xmm2 = [9.2233720368547748E+18,0.0E+0]
; AVX512-NEXT:    vucomisd %xmm2, %xmm1
; AVX512-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    xorl %eax, %eax
; AVX512-NEXT:    vucomisd %xmm1, %xmm1
; AVX512-NEXT:    cmovpq %rax, %rdx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm1 = xmm1[1,0]
; AVX512-NEXT:    vcvttsd2si %xmm1, %rsi
; AVX512-NEXT:    vucomisd %xmm2, %xmm1
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vmovq %rdx, %xmm3
; AVX512-NEXT:    vucomisd %xmm1, %xmm1
; AVX512-NEXT:    cmovpq %rax, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm1
; AVX512-NEXT:    vcvttsd2si %xmm0, %rdx
; AVX512-NEXT:    vucomisd %xmm2, %xmm0
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    vucomisd %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rax, %rdx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX512-NEXT:    vcvttsd2si %xmm0, %rsi
; AVX512-NEXT:    vucomisd %xmm2, %xmm0
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm3[0],xmm1[0]
; AVX512-NEXT:    vmovq %rdx, %xmm2
; AVX512-NEXT:    vucomisd %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rax, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm0
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm2[0],xmm0[0]
; AVX512-NEXT:    vinserti128 $1, %xmm1, %ymm0, %ymm0
; AVX512-NEXT:    retq
  %x = call <4 x i64> @llvm.fptosi.sat.v4i64.v4f64(<4 x double> %f)
  ret <4 x i64> %x
}

define <4 x i128> @test_signed_v4i128_v4f64(<4 x double> %f) nounwind {
; AVX2-LABEL: test_signed_v4i128_v4f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    pushq %rbp
; AVX2-NEXT:    pushq %r15
; AVX2-NEXT:    pushq %r14
; AVX2-NEXT:    pushq %r13
; AVX2-NEXT:    pushq %r12
; AVX2-NEXT:    pushq %rbx
; AVX2-NEXT:    subq $88, %rsp
; AVX2-NEXT:    vmovupd %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; AVX2-NEXT:    movq %rdi, %rbx
; AVX2-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX2-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixdfti@PLT
; AVX2-NEXT:    xorl %ecx, %ecx
; AVX2-NEXT:    vmovapd (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %rcx, %rax
; AVX2-NEXT:    movq %rdx, %r15
; AVX2-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rcx, %r15
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movabsq $9223372036854775807, %rbp # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rbp, %r15
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rax
; AVX2-NEXT:    vucomisd %xmm0, %xmm0
; AVX2-NEXT:    movl $0, %ecx
; AVX2-NEXT:    cmovpq %rcx, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %rcx, %r15
; AVX2-NEXT:    xorl %r14d, %r14d
; AVX2-NEXT:    vmovupd {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX2-NEXT:    vmovapd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixdfti@PLT
; AVX2-NEXT:    movq %rax, %r12
; AVX2-NEXT:    movq %rdx, %r13
; AVX2-NEXT:    vmovapd {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r14, %r12
; AVX2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rax, %r13
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %rbp, %r13
; AVX2-NEXT:    movq $-1, %rax
; AVX2-NEXT:    cmovaq %rax, %r12
; AVX2-NEXT:    vucomisd %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r14, %r12
; AVX2-NEXT:    cmovpq %r14, %r13
; AVX2-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixdfti@PLT
; AVX2-NEXT:    movq %rax, %rbp
; AVX2-NEXT:    movq %rdx, %r14
; AVX2-NEXT:    vmovupd {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movl $0, %eax
; AVX2-NEXT:    cmovbq %rax, %rbp
; AVX2-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rcx, %r14
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rcx, %r14
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rbp
; AVX2-NEXT:    vucomisd %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rax, %rbp
; AVX2-NEXT:    cmovpq %rax, %r14
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixdfti@PLT
; AVX2-NEXT:    vmovapd (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movl $0, %esi
; AVX2-NEXT:    cmovbq %rsi, %rax
; AVX2-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rcx, %rdx
; AVX2-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rax
; AVX2-NEXT:    vucomisd %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rsi, %rax
; AVX2-NEXT:    movl $0, %ecx
; AVX2-NEXT:    cmovpq %rcx, %rdx
; AVX2-NEXT:    movq %rdx, 40(%rbx)
; AVX2-NEXT:    movq %rax, 32(%rbx)
; AVX2-NEXT:    movq %r14, 8(%rbx)
; AVX2-NEXT:    movq %rbp, (%rbx)
; AVX2-NEXT:    movq %r13, 56(%rbx)
; AVX2-NEXT:    movq %r12, 48(%rbx)
; AVX2-NEXT:    movq %r15, 24(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 16(%rbx)
; AVX2-NEXT:    movq %rbx, %rax
; AVX2-NEXT:    addq $88, %rsp
; AVX2-NEXT:    popq %rbx
; AVX2-NEXT:    popq %r12
; AVX2-NEXT:    popq %r13
; AVX2-NEXT:    popq %r14
; AVX2-NEXT:    popq %r15
; AVX2-NEXT:    popq %rbp
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v4i128_v4f64:
; AVX512:       # %bb.0:
; AVX512-NEXT:    pushq %rbp
; AVX512-NEXT:    pushq %r15
; AVX512-NEXT:    pushq %r14
; AVX512-NEXT:    pushq %r13
; AVX512-NEXT:    pushq %r12
; AVX512-NEXT:    pushq %rbx
; AVX512-NEXT:    subq $88, %rsp
; AVX512-NEXT:    vmovupd %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; AVX512-NEXT:    movq %rdi, %rbx
; AVX512-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX512-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixdfti@PLT
; AVX512-NEXT:    movq %rdx, %r15
; AVX512-NEXT:    xorl %r14d, %r14d
; AVX512-NEXT:    vmovapd (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r14, %rax
; AVX512-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rcx, %r15
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movabsq $9223372036854775807, %rbp # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rbp, %r15
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rax
; AVX512-NEXT:    vucomisd %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r14, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r14, %r15
; AVX512-NEXT:    vmovupd {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmovapd %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; AVX512-NEXT:    vmovapd %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixdfti@PLT
; AVX512-NEXT:    movq %rax, %r12
; AVX512-NEXT:    movq %rdx, %r13
; AVX512-NEXT:    vmovapd {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r14, %r12
; AVX512-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rax, %r13
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %rbp, %r13
; AVX512-NEXT:    movq $-1, %rax
; AVX512-NEXT:    cmovaq %rax, %r12
; AVX512-NEXT:    vucomisd %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r14, %r12
; AVX512-NEXT:    cmovpq %r14, %r13
; AVX512-NEXT:    vmovups {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX512-NEXT:    # kill: def $xmm0 killed $xmm0 killed $ymm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixdfti@PLT
; AVX512-NEXT:    movq %rax, %rbp
; AVX512-NEXT:    movq %rdx, %r14
; AVX512-NEXT:    vmovupd {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movl $0, %eax
; AVX512-NEXT:    cmovbq %rax, %rbp
; AVX512-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rcx, %r14
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rcx, %r14
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rbp
; AVX512-NEXT:    vucomisd %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rax, %rbp
; AVX512-NEXT:    cmovpq %rax, %r14
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixdfti@PLT
; AVX512-NEXT:    vmovapd (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movl $0, %esi
; AVX512-NEXT:    cmovbq %rsi, %rax
; AVX512-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rcx, %rdx
; AVX512-NEXT:    vucomisd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rax
; AVX512-NEXT:    vucomisd %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rsi, %rax
; AVX512-NEXT:    movl $0, %ecx
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    movq %rdx, 40(%rbx)
; AVX512-NEXT:    movq %rax, 32(%rbx)
; AVX512-NEXT:    movq %r14, 8(%rbx)
; AVX512-NEXT:    movq %rbp, (%rbx)
; AVX512-NEXT:    movq %r13, 56(%rbx)
; AVX512-NEXT:    movq %r12, 48(%rbx)
; AVX512-NEXT:    movq %r15, 24(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 16(%rbx)
; AVX512-NEXT:    movq %rbx, %rax
; AVX512-NEXT:    addq $88, %rsp
; AVX512-NEXT:    popq %rbx
; AVX512-NEXT:    popq %r12
; AVX512-NEXT:    popq %r13
; AVX512-NEXT:    popq %r14
; AVX512-NEXT:    popq %r15
; AVX512-NEXT:    popq %rbp
; AVX512-NEXT:    retq
  %x = call <4 x i128> @llvm.fptosi.sat.v4i128.v4f64(<4 x double> %f)
  ret <4 x i128> %x
}

;
; 16-bit float to signed integer
;

define <16 x i1> @test_signed_v16i1_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_signed_v16i1_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX2-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %ecx
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vucomiss %xmm3, %xmm3
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm3
; AVX2-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX2-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %edx
; AVX2-NEXT:    vucomiss %xmm3, %xmm3
; AVX2-NEXT:    cmovpl %eax, %edx
; AVX2-NEXT:    vmovd %edx, %xmm3
; AVX2-NEXT:    vpinsrb $1, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $2, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $3, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $4, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $5, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $6, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $7, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $8, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $9, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $10, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $11, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $12, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $13, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $14, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm1, %xmm0, %xmm1
; AVX2-NEXT:    vminss %xmm1, %xmm2, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %ecx
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $15, %ecx, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v16i1_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX512-NEXT:    vmovss {{.*#+}} xmm1 = [-1.0E+0,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX512-NEXT:    vxorps %xmm2, %xmm2, %xmm2
; AVX512-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %ecx
; AVX512-NEXT:    xorl %eax, %eax
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm3
; AVX512-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX512-NEXT:    vminss %xmm4, %xmm2, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %edx
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpl %eax, %edx
; AVX512-NEXT:    vmovd %edx, %xmm3
; AVX512-NEXT:    vpinsrb $1, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $2, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $3, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $4, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $5, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $6, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $7, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $8, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $9, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $10, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $11, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $12, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $13, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm5, %xmm2, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $14, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm1, %xmm0, %xmm1
; AVX512-NEXT:    vminss %xmm1, %xmm2, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $15, %ecx, %xmm3, %xmm0
; AVX512-NEXT:    vptestmb {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %k0
; AVX512-NEXT:    vpmovm2b %k0, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <16 x i1> @llvm.fptosi.sat.v16i1.v16f16(<16 x half> %f)
  ret <16 x i1> %x
}

define <16 x i8> @test_signed_v16i8_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_signed_v16i8_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [-1.28E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [1.27E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %ecx
; AVX2-NEXT:    xorl %eax, %eax
; AVX2-NEXT:    vucomiss %xmm3, %xmm3
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm3
; AVX2-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX2-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %edx
; AVX2-NEXT:    vucomiss %xmm3, %xmm3
; AVX2-NEXT:    cmovpl %eax, %edx
; AVX2-NEXT:    vmovd %edx, %xmm3
; AVX2-NEXT:    vpinsrb $1, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $2, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $3, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $4, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $5, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $6, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $7, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $8, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $9, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $10, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $11, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $12, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $13, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX2-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %ecx
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $14, %ecx, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmaxss %xmm1, %xmm0, %xmm1
; AVX2-NEXT:    vminss %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %ecx
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpl %eax, %ecx
; AVX2-NEXT:    vpinsrb $15, %ecx, %xmm3, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v16i8_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX512-NEXT:    vmovss {{.*#+}} xmm1 = [-1.28E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [1.27E+2,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %ecx
; AVX512-NEXT:    xorl %eax, %eax
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm3
; AVX512-NEXT:    vmaxss %xmm1, %xmm3, %xmm4
; AVX512-NEXT:    vminss %xmm2, %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %edx
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpl %eax, %edx
; AVX512-NEXT:    vmovd %edx, %xmm3
; AVX512-NEXT:    vpinsrb $1, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $2, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $3, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $4, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $5, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $6, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $7, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $8, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $9, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $10, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $11, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $12, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $13, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; AVX512-NEXT:    vminss %xmm2, %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %ecx
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $14, %ecx, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmaxss %xmm1, %xmm0, %xmm1
; AVX512-NEXT:    vminss %xmm2, %xmm1, %xmm1
; AVX512-NEXT:    vcvttss2si %xmm1, %ecx
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpl %eax, %ecx
; AVX512-NEXT:    vpinsrb $15, %ecx, %xmm3, %xmm0
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    retq
  %x = call <16 x i8> @llvm.fptosi.sat.v16i8.v16f16(<16 x half> %f)
  ret <16 x i8> %x
}

define <16 x i16> @test_signed_v16i16_v16f16(<16 x half> %f) nounwind {
; CHECK-LABEL: test_signed_v16i16_v16f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vextracti128 $1, %ymm0, %xmm3
; CHECK-NEXT:    vpsrld $16, %xmm3, %xmm1
; CHECK-NEXT:    vcvtph2ps %xmm1, %xmm4
; CHECK-NEXT:    vmovss {{.*#+}} xmm1 = [-3.2768E+4,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; CHECK-NEXT:    vmovss {{.*#+}} xmm2 = [3.2767E+4,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %ecx
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    vucomiss %xmm4, %xmm4
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vcvtph2ps %xmm3, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %edx
; CHECK-NEXT:    vucomiss %xmm4, %xmm4
; CHECK-NEXT:    cmovpl %eax, %edx
; CHECK-NEXT:    vmovd %edx, %xmm4
; CHECK-NEXT:    vpinsrw $1, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm3[1,1,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $2, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vpsrlq $48, %xmm3, %xmm5
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $3, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vshufpd {{.*#+}} xmm5 = xmm3[1,0]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $4, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm3[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $5, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vshufps {{.*#+}} xmm5 = xmm3[3,3,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $6, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm3 = xmm3[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm3, %xmm3
; CHECK-NEXT:    vmaxss %xmm1, %xmm3, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %ecx
; CHECK-NEXT:    vucomiss %xmm3, %xmm3
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $7, %ecx, %xmm4, %xmm3
; CHECK-NEXT:    vpsrld $16, %xmm0, %xmm4
; CHECK-NEXT:    vcvtph2ps %xmm4, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %ecx
; CHECK-NEXT:    vucomiss %xmm4, %xmm4
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm4
; CHECK-NEXT:    vmaxss %xmm1, %xmm4, %xmm5
; CHECK-NEXT:    vminss %xmm2, %xmm5, %xmm5
; CHECK-NEXT:    vcvttss2si %xmm5, %edx
; CHECK-NEXT:    vucomiss %xmm4, %xmm4
; CHECK-NEXT:    cmovpl %eax, %edx
; CHECK-NEXT:    vmovd %edx, %xmm4
; CHECK-NEXT:    vpinsrw $1, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm0[1,1,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $2, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vpsrlq $48, %xmm0, %xmm5
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $3, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $4, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $5, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vshufps {{.*#+}} xmm5 = xmm0[3,3,3,3]
; CHECK-NEXT:    vcvtph2ps %xmm5, %xmm5
; CHECK-NEXT:    vmaxss %xmm1, %xmm5, %xmm6
; CHECK-NEXT:    vminss %xmm2, %xmm6, %xmm6
; CHECK-NEXT:    vcvttss2si %xmm6, %ecx
; CHECK-NEXT:    vucomiss %xmm5, %xmm5
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $6, %ecx, %xmm4, %xmm4
; CHECK-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm0
; CHECK-NEXT:    vmaxss %xmm1, %xmm0, %xmm1
; CHECK-NEXT:    vminss %xmm2, %xmm1, %xmm1
; CHECK-NEXT:    vcvttss2si %xmm1, %ecx
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    cmovpl %eax, %ecx
; CHECK-NEXT:    vpinsrw $7, %ecx, %xmm4, %xmm0
; CHECK-NEXT:    vinserti128 $1, %xmm3, %ymm0, %ymm0
; CHECK-NEXT:    retq
  %x = call <16 x i16> @llvm.fptosi.sat.v16i16.v16f16(<16 x half> %f)
  ret <16 x i16> %x
}

define <16 x i32> @test_signed_v16i32_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_signed_v16i32_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %esi
; AVX2-NEXT:    vmovss {{.*#+}} xmm1 = [-2.14748365E+9,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm1, %xmm3
; AVX2-NEXT:    movl $-2147483648, %eax # imm = 0x80000000
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [2.14748352E+9,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm2, %xmm3
; AVX2-NEXT:    movl $2147483647, %ecx # imm = 0x7FFFFFFF
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    xorl %edx, %edx
; AVX2-NEXT:    vucomiss %xmm3, %xmm3
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vshufpd {{.*#+}} xmm3 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm3, %xmm3
; AVX2-NEXT:    vcvttss2si %xmm3, %edi
; AVX2-NEXT:    vucomiss %xmm1, %xmm3
; AVX2-NEXT:    cmovbl %eax, %edi
; AVX2-NEXT:    vucomiss %xmm2, %xmm3
; AVX2-NEXT:    cmoval %ecx, %edi
; AVX2-NEXT:    vucomiss %xmm3, %xmm3
; AVX2-NEXT:    cmovpl %edx, %edi
; AVX2-NEXT:    vmovd %edi, %xmm3
; AVX2-NEXT:    vpinsrd $1, %esi, %xmm3, %xmm3
; AVX2-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vpinsrd $2, %esi, %xmm3, %xmm3
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vpinsrd $3, %esi, %xmm3, %xmm3
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm4
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %edi
; AVX2-NEXT:    vucomiss %xmm1, %xmm4
; AVX2-NEXT:    cmovbl %eax, %edi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmoval %ecx, %edi
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpl %edx, %edi
; AVX2-NEXT:    vmovd %edi, %xmm4
; AVX2-NEXT:    vpinsrd $1, %esi, %xmm4, %xmm4
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm5 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vpinsrd $2, %esi, %xmm4, %xmm4
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm5
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vpinsrd $3, %esi, %xmm4, %xmm4
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %edi
; AVX2-NEXT:    vucomiss %xmm1, %xmm5
; AVX2-NEXT:    cmovbl %eax, %edi
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmoval %ecx, %edi
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpl %edx, %edi
; AVX2-NEXT:    vmovd %edi, %xmm5
; AVX2-NEXT:    vpinsrd $1, %esi, %xmm5, %xmm5
; AVX2-NEXT:    vshufps {{.*#+}} xmm6 = xmm0[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm6, %xmm6
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vpinsrd $2, %esi, %xmm5, %xmm5
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm6, %xmm6
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm6
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %edi
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %edi
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %edi
; AVX2-NEXT:    vucomiss %xmm6, %xmm6
; AVX2-NEXT:    cmovpl %edx, %edi
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %r8d
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %r8d
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %r8d
; AVX2-NEXT:    vucomiss %xmm6, %xmm6
; AVX2-NEXT:    cmovpl %edx, %r8d
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm0[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %r9d
; AVX2-NEXT:    vucomiss %xmm1, %xmm6
; AVX2-NEXT:    cmovbl %eax, %r9d
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmoval %ecx, %r9d
; AVX2-NEXT:    vpinsrd $3, %esi, %xmm5, %xmm5
; AVX2-NEXT:    vucomiss %xmm6, %xmm6
; AVX2-NEXT:    vmovd %r8d, %xmm6
; AVX2-NEXT:    vpinsrd $1, %edi, %xmm6, %xmm6
; AVX2-NEXT:    cmovpl %edx, %r9d
; AVX2-NEXT:    vpinsrd $2, %r9d, %xmm6, %xmm6
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %esi
; AVX2-NEXT:    vucomiss %xmm1, %xmm0
; AVX2-NEXT:    cmovbl %eax, %esi
; AVX2-NEXT:    vucomiss %xmm2, %xmm0
; AVX2-NEXT:    cmoval %ecx, %esi
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpl %edx, %esi
; AVX2-NEXT:    vinserti128 $1, %xmm3, %ymm4, %ymm0
; AVX2-NEXT:    vpinsrd $3, %esi, %xmm6, %xmm1
; AVX2-NEXT:    vinserti128 $1, %xmm5, %ymm1, %ymm1
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v16i32_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm4
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm4[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %esi
; AVX512-NEXT:    vmovss {{.*#+}} xmm1 = [-2.14748365E+9,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    movl $-2147483648, %eax # imm = 0x80000000
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [2.14748352E+9,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    movl $2147483647, %ecx # imm = 0x7FFFFFFF
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    xorl %edx, %edx
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    vshufpd {{.*#+}} xmm3 = xmm4[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm3, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %edi
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbl %eax, %edi
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmoval %ecx, %edi
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpl %edx, %edi
; AVX512-NEXT:    vmovd %edi, %xmm3
; AVX512-NEXT:    vpinsrd $1, %esi, %xmm3, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm5 = xmm4[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm5, %xmm5
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vpinsrd $2, %esi, %xmm3, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm4[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm5, %xmm5
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vpinsrd $3, %esi, %xmm3, %xmm3
; AVX512-NEXT:    vpsrld $16, %xmm4, %xmm5
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm5, %xmm5
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %edi
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %edi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %edi
; AVX512-NEXT:    vucomiss %xmm5, %xmm5
; AVX512-NEXT:    cmovpl %edx, %edi
; AVX512-NEXT:    vmovd %edi, %xmm5
; AVX512-NEXT:    vpinsrd $1, %esi, %xmm5, %xmm5
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm4[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vpinsrd $2, %esi, %xmm5, %xmm5
; AVX512-NEXT:    vpsrlq $48, %xmm4, %xmm4
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vpinsrd $3, %esi, %xmm5, %xmm4
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm5, %xmm5
; AVX512-NEXT:    vshufpd {{.*#+}} xmm5 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm5, %edi
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm5
; AVX512-NEXT:    cmovbl %eax, %edi
; AVX512-NEXT:    vucomiss %xmm2, %xmm5
; AVX512-NEXT:    cmoval %ecx, %edi
; AVX512-NEXT:    vucomiss %xmm5, %xmm5
; AVX512-NEXT:    cmovpl %edx, %edi
; AVX512-NEXT:    vmovd %edi, %xmm5
; AVX512-NEXT:    vpinsrd $1, %esi, %xmm5, %xmm5
; AVX512-NEXT:    vshufps {{.*#+}} xmm6 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vpinsrd $2, %esi, %xmm5, %xmm5
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vpinsrd $3, %esi, %xmm5, %xmm5
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm6
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %esi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %edi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %edi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %edi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpl %edx, %edi
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %r8d
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbl %eax, %r8d
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmoval %ecx, %r8d
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    vmovd %edi, %xmm6
; AVX512-NEXT:    vpinsrd $1, %esi, %xmm6, %xmm6
; AVX512-NEXT:    cmovpl %edx, %r8d
; AVX512-NEXT:    vpinsrd $2, %r8d, %xmm6, %xmm6
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vcvttss2si %xmm0, %esi
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm4, %ymm3
; AVX512-NEXT:    vucomiss %xmm1, %xmm0
; AVX512-NEXT:    cmovbl %eax, %esi
; AVX512-NEXT:    vucomiss %xmm2, %xmm0
; AVX512-NEXT:    cmoval %ecx, %esi
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpl %edx, %esi
; AVX512-NEXT:    vpinsrd $3, %esi, %xmm6, %xmm0
; AVX512-NEXT:    vinserti128 $1, %xmm5, %ymm0, %ymm0
; AVX512-NEXT:    vinserti64x4 $1, %ymm3, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %x = call <16 x i32> @llvm.fptosi.sat.v16i32.v16f16(<16 x half> %f)
  ret <16 x i32> %x
}

define <16 x i64> @test_signed_v16i64_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_signed_v16i64_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmovdqa %ymm0, %ymm1
; AVX2-NEXT:    vpsrlq $48, %xmm1, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %rsi
; AVX2-NEXT:    vmovss {{.*#+}} xmm2 = [-9.22337203E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm2, %xmm0
; AVX2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vmovss {{.*#+}} xmm3 = [9.22337149E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX2-NEXT:    vucomiss %xmm3, %xmm0
; AVX2-NEXT:    movabsq $9223372036854775807, %rdx # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rdx, %rsi
; AVX2-NEXT:    xorl %ecx, %ecx
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rcx, %rsi
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm0 = xmm1[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %rdi
; AVX2-NEXT:    vucomiss %xmm2, %xmm0
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomiss %xmm3, %xmm0
; AVX2-NEXT:    cmovaq %rdx, %rdi
; AVX2-NEXT:    vmovq %rsi, %xmm4
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rcx, %rdi
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %rsi
; AVX2-NEXT:    vmovq %rdi, %xmm5
; AVX2-NEXT:    vucomiss %xmm2, %xmm0
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm0
; AVX2-NEXT:    cmovaq %rdx, %rsi
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rcx, %rsi
; AVX2-NEXT:    vpsrld $16, %xmm1, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vcvttss2si %xmm0, %rdi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm5[0],xmm4[0]
; AVX2-NEXT:    vucomiss %xmm2, %xmm0
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomiss %xmm3, %xmm0
; AVX2-NEXT:    cmovaq %rdx, %rdi
; AVX2-NEXT:    vmovq %rsi, %xmm5
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rcx, %rdi
; AVX2-NEXT:    vmovq %rdi, %xmm0
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm5[0],xmm0[0]
; AVX2-NEXT:    vinserti128 $1, %xmm4, %ymm0, %ymm0
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm1[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %rsi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm4
; AVX2-NEXT:    cmovaq %rdx, %rsi
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpq %rcx, %rsi
; AVX2-NEXT:    vmovq %rsi, %xmm4
; AVX2-NEXT:    vshufps {{.*#+}} xmm5 = xmm1[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rsi
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm5
; AVX2-NEXT:    cmovaq %rdx, %rsi
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpq %rcx, %rsi
; AVX2-NEXT:    vmovq %rsi, %xmm5
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm1[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %rsi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm5[0],xmm4[0]
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm6
; AVX2-NEXT:    cmovaq %rdx, %rsi
; AVX2-NEXT:    vucomiss %xmm6, %xmm6
; AVX2-NEXT:    cmovpq %rcx, %rsi
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm1[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vcvttss2si %xmm4, %rdi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomiss %xmm3, %xmm4
; AVX2-NEXT:    cmovaq %rdx, %rdi
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpq %rcx, %rdi
; AVX2-NEXT:    vextracti128 $1, %ymm1, %xmm4
; AVX2-NEXT:    vpsrlq $48, %xmm4, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %r9
; AVX2-NEXT:    vmovq %rsi, %xmm6
; AVX2-NEXT:    vucomiss %xmm2, %xmm1
; AVX2-NEXT:    cmovbq %rax, %r9
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovaq %rdx, %r9
; AVX2-NEXT:    vucomiss %xmm1, %xmm1
; AVX2-NEXT:    cmovpq %rcx, %r9
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm1 = xmm4[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm1
; AVX2-NEXT:    vcvttss2si %xmm1, %r8
; AVX2-NEXT:    vmovq %rdi, %xmm7
; AVX2-NEXT:    vucomiss %xmm2, %xmm1
; AVX2-NEXT:    cmovbq %rax, %r8
; AVX2-NEXT:    vucomiss %xmm3, %xmm1
; AVX2-NEXT:    cmovaq %rdx, %r8
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm6 = xmm7[0],xmm6[0]
; AVX2-NEXT:    vucomiss %xmm1, %xmm1
; AVX2-NEXT:    cmovpq %rcx, %r8
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm7
; AVX2-NEXT:    vcvttss2si %xmm7, %rsi
; AVX2-NEXT:    vinserti128 $1, %xmm5, %ymm6, %ymm1
; AVX2-NEXT:    vucomiss %xmm2, %xmm7
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vucomiss %xmm3, %xmm7
; AVX2-NEXT:    cmovaq %rdx, %rsi
; AVX2-NEXT:    vucomiss %xmm7, %xmm7
; AVX2-NEXT:    cmovpq %rcx, %rsi
; AVX2-NEXT:    vpsrld $16, %xmm4, %xmm5
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %rdi
; AVX2-NEXT:    vmovq %r9, %xmm6
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmovbq %rax, %rdi
; AVX2-NEXT:    vucomiss %xmm3, %xmm5
; AVX2-NEXT:    cmovaq %rdx, %rdi
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpq %rcx, %rdi
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm5 = xmm4[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm5
; AVX2-NEXT:    vcvttss2si %xmm5, %r9
; AVX2-NEXT:    vmovq %r8, %xmm7
; AVX2-NEXT:    vucomiss %xmm2, %xmm5
; AVX2-NEXT:    cmovbq %rax, %r9
; AVX2-NEXT:    vucomiss %xmm3, %xmm5
; AVX2-NEXT:    cmovaq %rdx, %r9
; AVX2-NEXT:    vucomiss %xmm5, %xmm5
; AVX2-NEXT:    cmovpq %rcx, %r9
; AVX2-NEXT:    vshufps {{.*#+}} xmm5 = xmm4[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm5, %xmm8
; AVX2-NEXT:    vcvttss2si %xmm8, %r8
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm7[0],xmm6[0]
; AVX2-NEXT:    vucomiss %xmm2, %xmm8
; AVX2-NEXT:    cmovbq %rax, %r8
; AVX2-NEXT:    vucomiss %xmm3, %xmm8
; AVX2-NEXT:    cmovaq %rdx, %r8
; AVX2-NEXT:    vucomiss %xmm8, %xmm8
; AVX2-NEXT:    cmovpq %rcx, %r8
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm4[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX2-NEXT:    vcvttss2si %xmm6, %r10
; AVX2-NEXT:    vmovq %rsi, %xmm7
; AVX2-NEXT:    vucomiss %xmm2, %xmm6
; AVX2-NEXT:    cmovbq %rax, %r10
; AVX2-NEXT:    vucomiss %xmm3, %xmm6
; AVX2-NEXT:    cmovaq %rdx, %r10
; AVX2-NEXT:    vucomiss %xmm6, %xmm6
; AVX2-NEXT:    vmovq %rdi, %xmm6
; AVX2-NEXT:    cmovpq %rcx, %r10
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm6 = xmm7[0],xmm6[0]
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm4[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX2-NEXT:    vmovq %r9, %xmm7
; AVX2-NEXT:    vcvttss2si %xmm4, %rsi
; AVX2-NEXT:    vucomiss %xmm2, %xmm4
; AVX2-NEXT:    vmovq %r8, %xmm8
; AVX2-NEXT:    cmovbq %rax, %rsi
; AVX2-NEXT:    vinserti128 $1, %xmm5, %ymm6, %ymm2
; AVX2-NEXT:    vucomiss %xmm3, %xmm4
; AVX2-NEXT:    cmovaq %rdx, %rsi
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm3 = xmm8[0],xmm7[0]
; AVX2-NEXT:    vucomiss %xmm4, %xmm4
; AVX2-NEXT:    cmovpq %rcx, %rsi
; AVX2-NEXT:    vmovq %r10, %xmm4
; AVX2-NEXT:    vmovq %rsi, %xmm5
; AVX2-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm5[0],xmm4[0]
; AVX2-NEXT:    vinserti128 $1, %xmm3, %ymm4, %ymm3
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v16i64_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm1 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %rsi
; AVX512-NEXT:    vmovss {{.*#+}} xmm1 = [-9.22337203E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vmovss {{.*#+}} xmm2 = [9.22337149E+18,0.0E+0,0.0E+0,0.0E+0]
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    xorl %edx, %edx
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm3
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm0[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm4 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vcvttss2si %xmm4, %rdi
; AVX512-NEXT:    vmovq %rsi, %xmm5
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rdi
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rdi
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm3 = xmm5[0],xmm3[0]
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpq %rdx, %rdi
; AVX512-NEXT:    vshufpd {{.*#+}} xmm4 = xmm0[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmovq %rdi, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm4, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm4
; AVX512-NEXT:    vpsrlq $48, %xmm0, %xmm6
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %rsi
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm4[0],xmm5[0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vinserti128 $1, %xmm3, %ymm4, %ymm4
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm3 = xmm0[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm3, %xmm3
; AVX512-NEXT:    vmovq %rsi, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm3, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm3
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm3[0],xmm5[0]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm3
; AVX512-NEXT:    vcvtph2ps %xmm3, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %rdi
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbq %rax, %rdi
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmovaq %rcx, %rdi
; AVX512-NEXT:    vmovq %rsi, %xmm6
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rdx, %rdi
; AVX512-NEXT:    vmovq %rdi, %xmm3
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm6 = xmm6[0],xmm3[0]
; AVX512-NEXT:    vextractf128 $1, %ymm0, %xmm3
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm3[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm7
; AVX512-NEXT:    vcvttss2si %xmm7, %rsi
; AVX512-NEXT:    vinserti128 $1, %xmm5, %ymm6, %ymm0
; AVX512-NEXT:    vucomiss %xmm1, %xmm7
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm7
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vinserti64x4 $1, %ymm4, %zmm0, %zmm0
; AVX512-NEXT:    vucomiss %xmm7, %xmm7
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vshufps {{.*#+}} xmm4 = xmm3[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm4, %xmm4
; AVX512-NEXT:    vmovq %rsi, %xmm5
; AVX512-NEXT:    vcvttss2si %xmm4, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm4
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm4
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm4, %xmm4
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm4
; AVX512-NEXT:    vpsrldq {{.*#+}} xmm6 = xmm3[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %rsi
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm4 = xmm4[0],xmm5[0]
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm5
; AVX512-NEXT:    vshufpd {{.*#+}} xmm6 = xmm3[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm6
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm6[0],xmm5[0]
; AVX512-NEXT:    vpsrlq $48, %xmm3, %xmm6
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %rsi
; AVX512-NEXT:    vinserti128 $1, %xmm4, %ymm5, %ymm4
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm5
; AVX512-NEXT:    vmovshdup {{.*#+}} xmm6 = xmm3[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm6, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vmovq %rsi, %xmm6
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm5 = xmm6[0],xmm5[0]
; AVX512-NEXT:    vcvtph2ps %xmm3, %xmm6
; AVX512-NEXT:    vcvttss2si %xmm6, %rsi
; AVX512-NEXT:    vucomiss %xmm1, %xmm6
; AVX512-NEXT:    cmovbq %rax, %rsi
; AVX512-NEXT:    vucomiss %xmm2, %xmm6
; AVX512-NEXT:    cmovaq %rcx, %rsi
; AVX512-NEXT:    vucomiss %xmm6, %xmm6
; AVX512-NEXT:    cmovpq %rdx, %rsi
; AVX512-NEXT:    vpsrld $16, %xmm3, %xmm3
; AVX512-NEXT:    vcvtph2ps %xmm3, %xmm3
; AVX512-NEXT:    vcvttss2si %xmm3, %rdi
; AVX512-NEXT:    vmovq %rsi, %xmm6
; AVX512-NEXT:    vucomiss %xmm1, %xmm3
; AVX512-NEXT:    cmovbq %rax, %rdi
; AVX512-NEXT:    vucomiss %xmm2, %xmm3
; AVX512-NEXT:    cmovaq %rcx, %rdi
; AVX512-NEXT:    vucomiss %xmm3, %xmm3
; AVX512-NEXT:    cmovpq %rdx, %rdi
; AVX512-NEXT:    vmovq %rdi, %xmm1
; AVX512-NEXT:    vpunpcklqdq {{.*#+}} xmm1 = xmm6[0],xmm1[0]
; AVX512-NEXT:    vinserti128 $1, %xmm5, %ymm1, %ymm1
; AVX512-NEXT:    vinserti64x4 $1, %ymm4, %zmm1, %zmm1
; AVX512-NEXT:    retq
  %x = call <16 x i64> @llvm.fptosi.sat.v16i64.v16f16(<16 x half> %f)
  ret <16 x i64> %x
}

define <16 x i128> @test_signed_v16i128_v16f16(<16 x half> %f) nounwind {
; AVX2-LABEL: test_signed_v16i128_v16f16:
; AVX2:       # %bb.0:
; AVX2-NEXT:    pushq %rbp
; AVX2-NEXT:    pushq %r15
; AVX2-NEXT:    pushq %r14
; AVX2-NEXT:    pushq %r13
; AVX2-NEXT:    pushq %r12
; AVX2-NEXT:    pushq %rbx
; AVX2-NEXT:    subq $328, %rsp # imm = 0x148
; AVX2-NEXT:    vmovdqu %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; AVX2-NEXT:    movq %rdi, %rbx
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX2-NEXT:    vcvtph2ps %xmm1, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    xorl %r13d, %r13d
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    movabsq $-9223372036854775808, %rbp # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movabsq $9223372036854775807, %r15 # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rax
; AVX2-NEXT:    movq $-1, %r12
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovshdup {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r12, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilpd $1, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilps $255, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX2-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX2-NEXT:    vmovdqa %xmm0, (%rsp) # 16-byte Spill
; AVX2-NEXT:    vpsrld $16, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovshdup (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqa (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vpsrlq $48, %xmm0, %xmm0
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilpd $1, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[1,0]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r14
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vmovdqa (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %rdx
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %rdx
; AVX2-NEXT:    cmovaq %r14, %rax
; AVX2-NEXT:    movq $-1, %r12
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %rdx
; AVX2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    vpermilps $255, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    movq %rdx, %r14
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %rax
; AVX2-NEXT:    cmovbq %rbp, %r14
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %r15, %r14
; AVX2-NEXT:    movq %r15, %rbp
; AVX2-NEXT:    cmovaq %r12, %rax
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %rax
; AVX2-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX2-NEXT:    cmovpq %r13, %r14
; AVX2-NEXT:    vmovdqa (%rsp), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vpsrldq {{.*#+}} xmm0 = xmm0[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX2-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    movq %rax, %r15
; AVX2-NEXT:    movq %rdx, %r12
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovbq %r13, %r15
; AVX2-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rax, %r12
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    cmovaq %rbp, %r12
; AVX2-NEXT:    movq $-1, %rax
; AVX2-NEXT:    cmovaq %rax, %r15
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %r13, %r15
; AVX2-NEXT:    cmovpq %r13, %r12
; AVX2-NEXT:    vcvtph2ps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    movq %rax, %r13
; AVX2-NEXT:    movq %rdx, %rbp
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movl $0, %eax
; AVX2-NEXT:    cmovbq %rax, %r13
; AVX2-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rcx, %rbp
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rcx, %rbp
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %r13
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rax, %r13
; AVX2-NEXT:    cmovpq %rax, %rbp
; AVX2-NEXT:    vcvtph2ps (%rsp), %xmm0 # 16-byte Folded Reload
; AVX2-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX2-NEXT:    callq __fixsfti@PLT
; AVX2-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX2-NEXT:    cmovbq %rcx, %rdx
; AVX2-NEXT:    movl $0, %esi
; AVX2-NEXT:    cmovbq %rsi, %rax
; AVX2-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX2-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX2-NEXT:    cmovaq %rcx, %rdx
; AVX2-NEXT:    movq $-1, %rcx
; AVX2-NEXT:    cmovaq %rcx, %rax
; AVX2-NEXT:    vucomiss %xmm0, %xmm0
; AVX2-NEXT:    cmovpq %rsi, %rax
; AVX2-NEXT:    movl $0, %ecx
; AVX2-NEXT:    cmovpq %rcx, %rdx
; AVX2-NEXT:    movq %rdx, 136(%rbx)
; AVX2-NEXT:    movq %rax, 128(%rbx)
; AVX2-NEXT:    movq %rbp, 8(%rbx)
; AVX2-NEXT:    movq %r13, (%rbx)
; AVX2-NEXT:    movq %r12, 248(%rbx)
; AVX2-NEXT:    movq %r15, 240(%rbx)
; AVX2-NEXT:    movq %r14, 232(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 224(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 216(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 208(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 200(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 192(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 184(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 176(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 168(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 160(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 152(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 144(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 120(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 112(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 104(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 96(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 88(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 80(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 72(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 64(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 56(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 48(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 40(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 32(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 24(%rbx)
; AVX2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX2-NEXT:    movq %rax, 16(%rbx)
; AVX2-NEXT:    movq %rbx, %rax
; AVX2-NEXT:    addq $328, %rsp # imm = 0x148
; AVX2-NEXT:    popq %rbx
; AVX2-NEXT:    popq %r12
; AVX2-NEXT:    popq %r13
; AVX2-NEXT:    popq %r14
; AVX2-NEXT:    popq %r15
; AVX2-NEXT:    popq %rbp
; AVX2-NEXT:    retq
;
; AVX512-LABEL: test_signed_v16i128_v16f16:
; AVX512:       # %bb.0:
; AVX512-NEXT:    pushq %rbp
; AVX512-NEXT:    pushq %r15
; AVX512-NEXT:    pushq %r14
; AVX512-NEXT:    pushq %r13
; AVX512-NEXT:    pushq %r12
; AVX512-NEXT:    pushq %rbx
; AVX512-NEXT:    subq $328, %rsp # imm = 0x148
; AVX512-NEXT:    vmovdqu %ymm0, {{[-0-9]+}}(%r{{[sb]}}p) # 32-byte Spill
; AVX512-NEXT:    movq %rdi, %rbx
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm1
; AVX512-NEXT:    vcvtph2ps %xmm1, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    xorl %r13d, %r13d
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    movabsq $-9223372036854775808, %rbp # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movabsq $9223372036854775807, %r15 # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rax
; AVX512-NEXT:    movq $-1, %r12
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vmovshdup {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r12, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrlq $48, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilpd $1, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrldq $10, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilps $255, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrldq $14, {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps (%rsp), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vmovdqu {{[-0-9]+}}(%r{{[sb]}}p), %ymm0 # 32-byte Reload
; AVX512-NEXT:    vextracti128 $1, %ymm0, %xmm0
; AVX512-NEXT:    vmovdqa %xmm0, (%rsp) # 16-byte Spill
; AVX512-NEXT:    vpsrld $16, %xmm0, %xmm0
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    vzeroupper
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vmovshdup (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,1,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrlq $48, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilpd $1, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[1,0]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r14
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpsrldq $10, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[10,11,12,13,14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %rdx
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %rdx
; AVX512-NEXT:    cmovaq %r14, %rax
; AVX512-NEXT:    movq $-1, %r12
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %rdx
; AVX512-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    vpermilps $255, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[3,3,3,3]
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    movq %rdx, %r14
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %rax
; AVX512-NEXT:    cmovbq %rbp, %r14
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %r15, %r14
; AVX512-NEXT:    movq %r15, %rbp
; AVX512-NEXT:    cmovaq %r12, %rax
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %rax
; AVX512-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX512-NEXT:    cmovpq %r13, %r14
; AVX512-NEXT:    vpsrldq $14, (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    # xmm0 = mem[14,15],zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero,zero
; AVX512-NEXT:    vcvtph2ps %xmm0, %xmm0
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    movq %rax, %r15
; AVX512-NEXT:    movq %rdx, %r12
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovbq %r13, %r15
; AVX512-NEXT:    movabsq $-9223372036854775808, %rax # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rax, %r12
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    cmovaq %rbp, %r12
; AVX512-NEXT:    movq $-1, %rax
; AVX512-NEXT:    cmovaq %rax, %r15
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %r13, %r15
; AVX512-NEXT:    cmovpq %r13, %r12
; AVX512-NEXT:    vcvtph2ps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    movq %rax, %r13
; AVX512-NEXT:    movq %rdx, %rbp
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movl $0, %eax
; AVX512-NEXT:    cmovbq %rax, %r13
; AVX512-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rcx, %rbp
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rcx, %rbp
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %r13
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rax, %r13
; AVX512-NEXT:    cmovpq %rax, %rbp
; AVX512-NEXT:    vcvtph2ps (%rsp), %xmm0 # 16-byte Folded Reload
; AVX512-NEXT:    vmovaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; AVX512-NEXT:    callq __fixsfti@PLT
; AVX512-NEXT:    vmovaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movabsq $-9223372036854775808, %rcx # imm = 0x8000000000000000
; AVX512-NEXT:    cmovbq %rcx, %rdx
; AVX512-NEXT:    movl $0, %esi
; AVX512-NEXT:    cmovbq %rsi, %rax
; AVX512-NEXT:    vucomiss {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; AVX512-NEXT:    movabsq $9223372036854775807, %rcx # imm = 0x7FFFFFFFFFFFFFFF
; AVX512-NEXT:    cmovaq %rcx, %rdx
; AVX512-NEXT:    movq $-1, %rcx
; AVX512-NEXT:    cmovaq %rcx, %rax
; AVX512-NEXT:    vucomiss %xmm0, %xmm0
; AVX512-NEXT:    cmovpq %rsi, %rax
; AVX512-NEXT:    movl $0, %ecx
; AVX512-NEXT:    cmovpq %rcx, %rdx
; AVX512-NEXT:    movq %rdx, 136(%rbx)
; AVX512-NEXT:    movq %rax, 128(%rbx)
; AVX512-NEXT:    movq %rbp, 8(%rbx)
; AVX512-NEXT:    movq %r13, (%rbx)
; AVX512-NEXT:    movq %r12, 248(%rbx)
; AVX512-NEXT:    movq %r15, 240(%rbx)
; AVX512-NEXT:    movq %r14, 232(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 224(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 216(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 208(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 200(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 192(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 184(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 176(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 168(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 160(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 152(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 144(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 120(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 112(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 104(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 96(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 88(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 80(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 72(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 64(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 56(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 48(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 40(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 32(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 24(%rbx)
; AVX512-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX512-NEXT:    movq %rax, 16(%rbx)
; AVX512-NEXT:    movq %rbx, %rax
; AVX512-NEXT:    addq $328, %rsp # imm = 0x148
; AVX512-NEXT:    popq %rbx
; AVX512-NEXT:    popq %r12
; AVX512-NEXT:    popq %r13
; AVX512-NEXT:    popq %r14
; AVX512-NEXT:    popq %r15
; AVX512-NEXT:    popq %rbp
; AVX512-NEXT:    retq
  %x = call <16 x i128> @llvm.fptosi.sat.v16i128.v16f16(<16 x half> %f)
  ret <16 x i128> %x
}
