; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64 | FileCheck %s

define i16 @sext_i8_i16(float %0) {
; CHECK-LABEL: sext_i8_i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cvttss2si %xmm0, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %2 = fptosi float %0 to i8
  %3 = sext i8 %2 to i16
  ret i16 %3
}

define i32 @sext_i16_i32(float %0) {
; CHECK-LABEL: sext_i16_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cvttss2si %xmm0, %eax
; CHECK-NEXT:    retq
  %2 = fptosi float %0 to i16
  %3 = sext i16 %2 to i32
  ret i32 %3
}

define i64 @sext_i32_i64(float %0) {
; CHECK-LABEL: sext_i32_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cvttss2si %xmm0, %rax
; CHECK-NEXT:    retq
  %2 = fptosi float %0 to i32
  %3 = sext i32 %2 to i64
  ret i64 %3
}
