; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mattr=+sse2 < %s | FileCheck %s

define i32 @scalar_fptosi_fold(float %x) {
; CHECK-LABEL: scalar_fptosi_fold:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cvttss2si %xmm0, %eax
; CHECK-NEXT:    retq
  %abs = call float @llvm.fabs.f32(float %x)
  %cmp = fcmp olt float %abs, 2147483648.0
  %conv = fptosi float %x to i32
  %res = select i1 %cmp, i32 %conv, i32 -2147483648
  ret i32 %res
}

define <4 x i32> @vector_fptosi_fold(<4 x float> %x) {
; CHECK-LABEL: vector_fptosi_fold:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cvttps2dq %xmm0, %xmm0
; CHECK-NEXT:    retq
  %abs = call <4 x float> @llvm.fabs.v4f32(<4 x float> %x)
  %cmp = fcmp olt <4 x float> %abs, splat (float 2147483648.0)
  %conv = fptosi <4 x float> %x to <4 x i32>
  %res = select <4 x i1> %cmp, <4 x i32> %conv,
                     <4 x i32> splat (i32 -2147483648)
  ret <4 x i32> %res
}

define i32 @scalar_fptosi_fold_double(double %x) {
; CHECK-LABEL: scalar_fptosi_fold_double:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cvttsd2si %xmm0, %eax
; CHECK-NEXT:    retq
  %abs = call double @llvm.fabs.f64(double %x)
  %cmp = fcmp olt double %abs, 2147483648.0
  %conv = fptosi double %x to i32
  %res = select i1 %cmp, i32 %conv, i32 -2147483648
  ret i32 %res
}
