; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

declare void @bar(i32, i32)

define void @foo(i32 %0, i32 %1) nounwind "frame-pointer"="reserved" {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    movl %esi, %ebx
; CHECK-NEXT:    movl %edi, %r14d
; CHECK-NEXT:    callq bar@PLT
; CHECK-NEXT:    movl %r14d, %edi
; CHECK-NEXT:    movl %ebx, %esi
; CHECK-NEXT:    callq bar@PLT
; CHECK-NEXT:    addq $8, %rsp
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    retq
  call void @bar(i32 %0, i32 %1)
  call void @bar(i32 %0, i32 %1)
  ret void
}
