; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -combiner-topological-sorting -stop-after=finalize-isel -mtriple=x86_64-unknown < %s 2>&1 | FileCheck %s
define i32 @const() {
  ; CHECK-LABEL: name: const
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   [[MOV32ri:%[0-9]+]]:gr32 = MOV32ri 1
  ; CHECK-NEXT:   $eax = COPY [[MOV32ri]]
  ; CHECK-NEXT:   RET 0, $eax
  %y = freeze i32 1
  ret i32 %y
}

define i32 @fold(i32 %x) {
  ; CHECK-LABEL: name: fold
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $edi
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:gr32 = COPY $edi
  ; CHECK-NEXT:   $eax = COPY [[COPY]]
  ; CHECK-NEXT:   RET 0, $eax
  %y = freeze i32 %x
  %z = freeze i32 %y
  ret i32 %z
}
