; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-unknown-unknown -mattr=+f16c < %s | FileCheck %s

define void @freeze_undef_demanded_elts(ptr %p) minsize {
; CHECK-LABEL: freeze_undef_demanded_elts:
; CHECK:       # %bb.0:
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    je .LBB0_2
; CHECK-NEXT:  # %bb.1: # %bb
; CHECK-NEXT:    movl $31744, %eax # imm = 0x7C00
; CHECK-NEXT:    vmovd %eax, %xmm0
; CHECK-NEXT:    vpcmpeqw %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    movzwl {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %eax
; CHECK-NEXT:    vmovd %eax, %xmm1
; CHECK-NEXT:    vpand %xmm1, %xmm0, %xmm0
; CHECK-NEXT:    vcvtph2ps %xmm0, %xmm0
; CHECK-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; CHECK-NEXT:    vmulss %xmm1, %xmm0, %xmm0
; CHECK-NEXT:    vcvtps2ph $4, %xmm0, %xmm0
; CHECK-NEXT:    vpextrw $0, %xmm0, (%rdi)
; CHECK-NEXT:  .LBB0_2: # %ret
; CHECK-NEXT:    retq
  %poison.as.i16 = bitcast <2 x half> poison to <2 x i16>
  %cmp = icmp eq <2 x i16> %poison.as.i16, <i16 31744, i16 31744>
  br i1 poison, label %bb, label %ret

ret:
  ret void

bb:
  %sel = select <2 x i1> %cmp, <2 x half> <half 0xH3C00, half 0xH3C00>, <2 x half> zeroinitializer
  %mul = fmul <2 x half> %sel, zeroinitializer
  %sub = fsub <2 x half> %mul, zeroinitializer
  %elt = extractelement <2 x half> %sub, i64 0
  store half %elt, ptr %p, align 2
  br label %ret
}
