; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc  -mtriple=x86_64-unknown-unknown -mattr=+avx512f,+avx512bw,+avx512vl,+avx512dq -mcpu=znver5 < %s | FileCheck %s

%struct.pt = type { float, float, float, i32 }
%struct.res = type {<16 x float>, <16 x float>}

define <16 x float> @test_gather_16f32_1(ptr %x, ptr %arr, <16 x i1> %mask, <16 x float> %src0)  {
; CHECK-LABEL: test_gather_16f32_1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpsllw $7, %xmm0, %xmm0
; CHECK-NEXT:    vmovdqu64 (%rsi), %zmm2
; CHECK-NEXT:    vpmovb2m %xmm0, %k1
; CHECK-NEXT:    vpandd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm2, %zmm0
; CHECK-NEXT:    vpaddd %zmm0, %zmm0, %zmm0
; CHECK-NEXT:    vgatherdps (%rdi,%zmm0,8), %zmm1 {%k1}
; CHECK-NEXT:    vmovaps %zmm1, %zmm0
; CHECK-NEXT:    retq
  %wide.load = load <16 x i32>, ptr %arr, align 4
  %and = and <16 x i32> %wide.load, <i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911>
  %zext = zext <16 x i32> %and to <16 x i64>
  %ptrs = getelementptr inbounds %struct.pt, ptr %x, <16 x i64> %zext
  %res = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> %ptrs, i32 4, <16 x i1> %mask, <16 x float> %src0)
  ret <16 x float> %res
}

define <16 x float> @test_gather_16f32_2(ptr %x, ptr %arr, <16 x i1> %mask, <16 x float> %src0)  {
; CHECK-LABEL: test_gather_16f32_2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpsllw $7, %xmm0, %xmm0
; CHECK-NEXT:    vmovdqu64 (%rsi), %zmm2
; CHECK-NEXT:    vpmovb2m %xmm0, %k1
; CHECK-NEXT:    vpandd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm2, %zmm0
; CHECK-NEXT:    vpaddd %zmm0, %zmm0, %zmm0
; CHECK-NEXT:    vgatherdps 4(%rdi,%zmm0,8), %zmm1 {%k1}
; CHECK-NEXT:    vmovaps %zmm1, %zmm0
; CHECK-NEXT:    retq
  %wide.load = load <16 x i32>, ptr %arr, align 4
  %and = and <16 x i32> %wide.load, <i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911>
  %zext = zext <16 x i32> %and to <16 x i64>
  %ptrs = getelementptr inbounds %struct.pt, ptr %x, <16 x i64> %zext, i32 1
  %res = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> %ptrs, i32 4, <16 x i1> %mask, <16 x float> %src0)
  ret <16 x float> %res
}

define {<16 x float>, <16 x float>} @test_gather_16f32_3(ptr %x, ptr %arr, <16 x i1> %mask, <16 x float> %src0)  {
; CHECK-LABEL: test_gather_16f32_3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpsllw $7, %xmm0, %xmm0
; CHECK-NEXT:    vpmovb2m %xmm0, %k1
; CHECK-NEXT:    vmovdqu64 (%rsi), %zmm0
; CHECK-NEXT:    vpandd {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm0, %zmm0
; CHECK-NEXT:    kmovq %k1, %k2
; CHECK-NEXT:    vpaddd %zmm0, %zmm0, %zmm2
; CHECK-NEXT:    vmovaps %zmm1, %zmm0
; CHECK-NEXT:    vgatherdps (%rdi,%zmm2,8), %zmm0 {%k2}
; CHECK-NEXT:    vgatherdps 4(%rdi,%zmm2,8), %zmm1 {%k1}
; CHECK-NEXT:    retq
  %wide.load = load <16 x i32>, ptr %arr, align 4
  %and = and <16 x i32> %wide.load, <i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911, i32 536870911>
  %zext = zext <16 x i32> %and to <16 x i64>
  %ptrs1 = getelementptr inbounds %struct.pt, ptr %x, <16 x i64> %zext
  %res1 = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> %ptrs1, i32 4, <16 x i1> %mask, <16 x float> %src0)
  %ptrs = getelementptr inbounds %struct.pt, ptr %x, <16 x i64> %zext, i32 1
  %res = call <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr> %ptrs, i32 4, <16 x i1> %mask, <16 x float> %src0)
  %pair1 = insertvalue {<16 x float>, <16 x float>} undef, <16 x float> %res1, 0
  %pair2 = insertvalue {<16 x float>, <16 x float>} %pair1, <16 x float> %res, 1
  ret {<16 x float>, <16 x float>} %pair2
}

declare <16 x float> @llvm.masked.gather.v16f32.v16p0(<16 x ptr>, i32, <16 x i1>, <16 x float>)
