; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -O2 -mattr=avx512f -mtriple=x86_64-unknown | FileCheck %s

%struct.S1 = type { %struct.S1*, %struct.S1* }

define ptr @malloc_init_state(<64 x ptr> %tmp, i32 %ind) nounwind {
; CHECK-LABEL: malloc_init_state:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    movq %rsp, %rbp
; CHECK-NEXT:    andq $-64, %rsp
; CHECK-NEXT:    subq $576, %rsp # imm = 0x240
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    vpbroadcastq {{.*#+}} zmm8 = [16,16,16,16,16,16,16,16]
; CHECK-NEXT:    vpaddq %zmm8, %zmm0, %zmm0
; CHECK-NEXT:    vpaddq %zmm8, %zmm1, %zmm1
; CHECK-NEXT:    vpaddq %zmm8, %zmm2, %zmm2
; CHECK-NEXT:    vpaddq %zmm8, %zmm3, %zmm3
; CHECK-NEXT:    vpaddq %zmm8, %zmm4, %zmm4
; CHECK-NEXT:    vpaddq %zmm8, %zmm5, %zmm5
; CHECK-NEXT:    vpaddq %zmm8, %zmm6, %zmm6
; CHECK-NEXT:    vpaddq %zmm8, %zmm7, %zmm7
; CHECK-NEXT:    vmovdqa64 %zmm7, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    vmovdqa64 %zmm6, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    vmovdqa64 %zmm5, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    vmovdqa64 %zmm4, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    vmovdqa64 %zmm3, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    vmovdqa64 %zmm2, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    vmovdqa64 %zmm1, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    vmovdqa64 %zmm0, (%rsp)
; CHECK-NEXT:    andl $63, %edi
; CHECK-NEXT:    movq (%rsp,%rdi,8), %rax
; CHECK-NEXT:    movq %rbp, %rsp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
entry:
  %Vec = getelementptr inbounds %struct.S1*, <64 x %struct.S1**> %tmp , i64 2
  %ptr = extractelement <64 x %struct.S1**> %Vec, i32 %ind
  ret %struct.S1** %ptr
}

