; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-- -mattr=+avx512bw,+avx512f,+gfni | FileCheck %s --check-prefixes=AVX512

declare <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8>, <64 x i8>, i8)
declare <16 x i8> @llvm.x86.vgf2p8affineqb.128(<16 x i8>, <16 x i8>, i8)

define <64 x i8> @test_or_disjoint_fold_512(<64 x i8> %src, <64 x i8> %matrix) nounwind {
; AVX512-LABEL: test_or_disjoint_fold_512:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vgf2p8affineqb $8, %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 0)
  %or = or disjoint <64 x i8> %gfni, splat(i8 8)
  ret <64 x i8> %or
}

define <64 x i8> @test_or_disjoint_fold_nonzero_imm(<64 x i8> %src, <64 x i8> %matrix) nounwind {
; AVX512-LABEL: test_or_disjoint_fold_nonzero_imm:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vgf2p8affineqb $12, %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 4)
  %or = or disjoint <64 x i8> %gfni, splat(i8 8)
  ret <64 x i8> %or
}

define <16 x i8> @test_or_disjoint_fold_128(<16 x i8> %src, <16 x i8> %matrix) nounwind {
; AVX512-LABEL: test_or_disjoint_fold_128:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vgf2p8affineqb $8, %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    retq
  %gfni = call <16 x i8> @llvm.x86.vgf2p8affineqb.128(<16 x i8> %src, <16 x i8> %matrix, i8 0)
  %or = or disjoint <16 x i8> %gfni, splat(i8 8)
  ret <16 x i8> %or
}

define <64 x i8> @test_or_no_fold_not_disjoint(<64 x i8> %src, <64 x i8> %matrix) nounwind {
; AVX512-LABEL: test_or_no_fold_not_disjoint:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vgf2p8affineqb $8, %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    vpord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 8)
  %or = or <64 x i8> %gfni, splat(i8 8)
  ret <64 x i8> %or
}

define <64 x i8> @test_or_non_disjoint(<64 x i8> %src, <64 x i8> %matrix) {
; AVX512-LABEL: test_or_non_disjoint:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vgf2p8affineqb $4, %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    vpord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 4)
  ; Without the 'disjoint' keyword, the compiler cannot safely fold this into the immediate
  %or = or <64 x i8> %gfni, splat(i8 4)
  ret <64 x i8> %or
}

define <64 x i8> @test_or_no_fold_multi_use(<64 x i8> %src, <64 x i8> %matrix, ptr %out) nounwind {
; AVX512-LABEL: test_or_no_fold_multi_use:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vgf2p8affineqb $0, %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    vmovdqa64 %zmm0, (%rdi)
; AVX512-NEXT:    vpord {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to16}, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 0)
  store <64 x i8> %gfni, ptr %out                     ; second use
  %or = or disjoint <64 x i8> %gfni, splat(i8 8)
  ret <64 x i8> %or
}

define <64 x i8> @test_or_disjoint_overlap_with_imm(<64 x i8> %src, <64 x i8> %matrix) nounwind {
; AVX512-LABEL: test_or_disjoint_overlap_with_imm:
; AVX512:       # %bb.0:
; AVX512-NEXT:    vgf2p8affineqb $0, %zmm1, %zmm0, %zmm0
; AVX512-NEXT:    retq
  %gfni = call <64 x i8> @llvm.x86.vgf2p8affineqb.512(<64 x i8> %src, <64 x i8> %matrix, i8 8)
  %or = or disjoint <64 x i8> %gfni, splat(i8 8)
  ret <64 x i8> %or
}
