; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx512f,+avx512bw,+popcnt | FileCheck %s

; GH#195575: fold (and al, 7; movzx eax, al) -> (and eax, 7).
;
; When a v16i1 comparison result (in a k-register) is bitcast to i3 and then
; zero-extended, type legalization expands this to:
;   bitcast v16i1 -> i16, truncate i16 -> i8, and i8 C, zero_extend i8 -> i32
;
; The fold (zext (and (trunc x) C)) -> (and x C) in visitZERO_EXTEND (and
; symmetrically visitANY_EXTEND) avoids the suboptimal "andb; movzbl" sequence
; in favour of a single "andl" on the wider type.

define zeroext range(i8 0, 4) i8 @gh_195575(ptr nocapture nonnull readonly align 4 %p) {
; CHECK-LABEL: gh_195575:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vmovd {{.*#+}} xmm0 = mem[0],zero,zero,zero
; CHECK-NEXT:    vpbroadcastb {{.*#+}} xmm1 = [61,61,61,61,61,61,61,61,61,61,61,61,61,61,61,61]
; CHECK-NEXT:    vpcmpneqb %zmm1, %zmm0, %k0
; CHECK-NEXT:    kmovd %k0, %eax
; CHECK-NEXT:    andl $7, %eax
; CHECK-NEXT:    popcntl %eax, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %v = load <3 x i8>, ptr %p, align 4
  %cmp = icmp ne <3 x i8> %v, splat (i8 61)
  %bc = bitcast <3 x i1> %cmp to i3
  %ct = tail call range(i3 0, -4) i3 @llvm.ctpop.i3(i3 %bc)
  %ext = zext nneg i3 %ct to i8
  ret i8 %ext
}

declare i3 @llvm.ctpop.i3(i3)
