; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse2 -global-isel -verify-machineinstrs | FileCheck %s --check-prefix=SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+ssse3 -global-isel -verify-machineinstrs | FileCheck %s --check-prefix=SSSE3
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+sse4.1 -global-isel -verify-machineinstrs | FileCheck %s --check-prefix=SSE41
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx -global-isel -verify-machineinstrs | FileCheck %s --check-prefix=AVX
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx2 -global-isel -verify-machineinstrs | FileCheck %s --check-prefix=AVX2

; Test basic shuffle patterns in GlobalISel

; SHUFPS pattern
define <4 x float> @test_shufps(<4 x float> %a, <4 x float> %b) {
; SSE2-LABEL: test_shufps:
; SSE2:       # %bb.0:
; SSE2-NEXT:    shufps {{.*#+}} xmm0 = xmm0[0,1],xmm1[2,3]
; SSE2-NEXT:    retq
;
; AVX-LABEL: test_shufps:
; AVX:       # %bb.0:
; AVX-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[0,1],xmm1[2,3]
; AVX-NEXT:    retq
  %res = shufflevector <4 x float> %a, <4 x float> %b, <4 x i32> <i32 0, i32 1, i32 6, i32 7>
  ret <4 x float> %res
}

; UNPCKL pattern
define <4 x i32> @test_unpckl(<4 x i32> %a, <4 x i32> %b) {
; SSE2-LABEL: test_unpckl:
; SSE2:       # %bb.0:
; SSE2-NEXT:    punpckldq {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[1],xmm1[1]
; SSE2-NEXT:    retq
;
; AVX-LABEL: test_unpckl:
; AVX:       # %bb.0:
; AVX-NEXT:    vpunpckldq {{.*#+}} xmm0 = xmm0[0],xmm1[0],xmm0[1],xmm1[1]
; AVX-NEXT:    retq
  %res = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 0, i32 4, i32 1, i32 5>
  ret <4 x i32> %res
}

; UNPCKH pattern
define <4 x i32> @test_unpckh(<4 x i32> %a, <4 x i32> %b) {
; SSE2-LABEL: test_unpckh:
; SSE2:       # %bb.0:
; SSE2-NEXT:    punpckhdq {{.*#+}} xmm0 = xmm0[2],xmm1[2],xmm0[3],xmm1[3]
; SSE2-NEXT:    retq
;
; AVX-LABEL: test_unpckh:
; AVX:       # %bb.0:
; AVX-NEXT:    vpunpckhdq {{.*#+}} xmm0 = xmm0[2],xmm1[2],xmm0[3],xmm1[3]
; AVX-NEXT:    retq
  %res = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 2, i32 6, i32 3, i32 7>
  ret <4 x i32> %res
}

; PSHUFD pattern
define <4 x i32> @test_pshufd(<4 x i32> %a) {
; SSE2-LABEL: test_pshufd:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[3,2,1,0]
; SSE2-NEXT:    retq
;
; AVX-LABEL: test_pshufd:
; AVX:       # %bb.0:
; AVX-NEXT:    vpshufd {{.*#+}} xmm0 = xmm0[3,2,1,0]
; AVX-NEXT:    retq
  %res = shufflevector <4 x i32> %a, <4 x i32> poison, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
  ret <4 x i32> %res
}

; Broadcast pattern
define <4 x i32> @test_broadcast(<4 x i32> %a) {
; SSE2-LABEL: test_broadcast:
; SSE2:       # %bb.0:
; SSE2-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[1,1,1,1]
; SSE2-NEXT:    retq
;
; AVX-LABEL: test_broadcast:
; AVX:       # %bb.0:
; AVX-NEXT:    vbroadcastss {{.*#+}} xmm0 = xmm0[1,1,1,1]
; AVX-NEXT:    retq
  %res = shufflevector <4 x i32> %a, <4 x i32> poison, <4 x i32> <i32 1, i32 1, i32 1, i32 1>
  ret <4 x i32> %res
}

; BLENDV pattern
define <4 x i32> @test_blendv(<4 x i32> %a, <4 x i32> %b) {
; SSE2-LABEL: test_blendv:
; SSE2:       # %bb.0:
; SSE2-NEXT:    movss {{.*#+}} xmm0 = xmm1[0],xmm0[1,2,3]
; SSE2-NEXT:    retq
;
; SSE41-LABEL: test_blendv:
; SSE41:       # %bb.0:
; SSE41-NEXT:    pblendvb {{.*#+}} xmm0 = xmm1[0,1,2,3],xmm0[4,5,6,7,8,9,10,11,12,13,14,15]
; SSE41-NEXT:    retq
;
; AVX-LABEL: test_blendv:
; AVX:       # %bb.0:
; AVX-NEXT:    vpblendvb {{.*#+}} xmm0 = xmm1[0,1,2,3],xmm0[4,5,6,7,8,9,10,11,12,13,14,15]
; AVX-NEXT:    retq
  %res = shufflevector <4 x i32> %a, <4 x i32> %b, <4 x i32> <i32 4, i32 1, i32 2, i32 3>
  ret <4 x i32> %res
}

; VPERMILPS pattern (AVX in-lane permute)
define <4 x float> @test_vpermilps(<4 x float> %a) {
; SSE2-LABEL: test_vpermilps:
; SSE2:       # %bb.0:
; SSE2-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,1,0,3]
; SSE2-NEXT:    retq
;
; AVX-LABEL: test_vpermilps:
; AVX:       # %bb.0:
; AVX-NEXT:    vpermilps {{.*#+}} xmm0 = xmm0[2,1,0,3]
; AVX-NEXT:    retq
  %res = shufflevector <4 x float> %a, <4 x float> poison, <4 x i32> <i32 2, i32 1, i32 0, i32 3>
  ret <4 x float> %res
}

; VPERMQ pattern (AVX2 cross-lane)
define <4 x i64> @test_vpermq(<4 x i64> %a) {
; AVX-LABEL: test_vpermq:
; AVX:       # %bb.0:
; AVX-NEXT:    vextractf128 $1, %ymm0, %xmm1
; AVX-NEXT:    vpunpcklqdq {{.*#+}} xmm0 = xmm1[0],xmm0[0]
; AVX-NEXT:    vinsertf128 $1, %xmm0, %ymm1, %ymm0
; AVX-NEXT:    retq
;
; AVX2-LABEL: test_vpermq:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vpermq {{.*#+}} ymm0 = ymm0[2,0,3,2]
; AVX2-NEXT:    retq
  %res = shufflevector <4 x i64> %a, <4 x i64> poison, <4 x i32> <i32 2, i32 0, i32 3, i32 2>
  ret <4 x i64> %res
}

; 256-bit SHUFPS
define <8 x float> @test_shufps_256(<8 x float> %a, <8 x float> %b) {
; AVX-LABEL: test_shufps_256:
; AVX:       # %bb.0:
; AVX-NEXT:    vshufps {{.*#+}} ymm0 = ymm0[0,1],ymm1[0,1],ymm0[4,5],ymm1[4,5]
; AVX-NEXT:    retq
  %res = shufflevector <8 x float> %a, <8 x float> %b, <8 x i32> <i32 0, i32 1, i32 8, i32 9, i32 4, i32 5, i32 12, i32 13>
  ret <8 x float> %res
}
