; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64 -mattr=+cf | FileCheck %s

;; Test masked.load/store.v1* is generated in simplifycfg and not falls back to branch+load/store in following passes.
define void @basic(i1 %cond, ptr %b, ptr %p, ptr %q) {
; CHECK-LABEL: basic:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andb $1, %dil
; CHECK-NEXT:    negb %dil
; CHECK-NEXT:    cfcmovnew (%rdx), %ax
; CHECK-NEXT:    cfcmovnel (%rcx), %edi
; CHECK-NEXT:    cfcmovneq (%rsi), %r8
; CHECK-NEXT:    cfcmovnew %ax, (%rsi)
; CHECK-NEXT:    cfcmovnel %edi, (%rdx)
; CHECK-NEXT:    cfcmovneq %r8, (%rcx)
; CHECK-NEXT:    retq
entry:
  br i1 %cond, label %if.true, label %if.false

if.false:
  br label %if.end

if.true:
  %pv = load i16, ptr %p, align 2
  %qv = load i32, ptr %q, align 4
  %bv = load i64, ptr %b, align 8
  store i16 %pv, ptr %b, align 2
  store i32 %qv, ptr %p, align 4
  store i64 %bv, ptr %q, align 8
  br label %if.false

if.end:
  ret void
}

;; load + zext.
define void @load_zext(i1 %cond, ptr %b, ptr %p) {
; CHECK-LABEL: load_zext:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andb $1, %dil
; CHECK-NEXT:    negb %dil
; CHECK-NEXT:    cfcmovnew (%rsi), %ax
; CHECK-NEXT:    movzwl %ax, %eax
; CHECK-NEXT:    cfcmovnel %eax, (%rdx)
; CHECK-NEXT:    retq
entry:
  br i1 %cond, label %if.true, label %if.false

if.false:
  br label %if.end

if.true:
  %bv = load i16, ptr %b, align 2
  %zext = zext i16 %bv to i32
  store i32 %zext, ptr %p, align 4
  br label %if.false

if.end:
  ret void
}

;; load + sext.
define void @load_sext(i1 %cond, ptr %b, ptr %q) {
; CHECK-LABEL: load_sext:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    andb $1, %dil
; CHECK-NEXT:    negb %dil
; CHECK-NEXT:    cfcmovnel (%rsi), %eax
; CHECK-NEXT:    cltq
; CHECK-NEXT:    cfcmovneq %rax, (%rdx)
; CHECK-NEXT:    retq
entry:
  br i1 %cond, label %if.true, label %if.false

if.false:
  br label %if.end

if.true:
  %bv = load i32, ptr %b, align 4
  %sext = sext i32 %bv to i64
  store i64 %sext, ptr %q, align 8
  br label %if.false

if.end:
  ret void
}
