; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux | FileCheck %s

define i128 @div_by_7(i128 %x) {
; CHECK-LABEL: div_by_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movabsq $9223372036854775807, %rax # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    shldq $1, %rdi, %r8
; CHECK-NEXT:    addq %rdi, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rax, %r9
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $62, %rcx
; CHECK-NEXT:    cmpq %rdx, %r9
; CHECK-NEXT:    adcq %r8, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $5270498306774157605, %rdx # imm = 0x4924924924924925
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    shrq %rdx
; CHECK-NEXT:    leaq (,%rdx,8), %rax
; CHECK-NEXT:    subq %rax, %rdx
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    subq %rdx, %rdi
; CHECK-NEXT:    sbbq $0, %rsi
; CHECK-NEXT:    movabsq $-5270498306774157605, %rcx # imm = 0xB6DB6DB6DB6DB6DB
; CHECK-NEXT:    imulq %rdi, %rcx
; CHECK-NEXT:    movabsq $7905747460161236407, %r8 # imm = 0x6DB6DB6DB6DB6DB7
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    mulq %r8
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    imulq %rsi, %r8
; CHECK-NEXT:    addq %r8, %rdx
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 7
  ret i128 %div
}

define i128 @div_by_9(i128 %x) {
; CHECK-LABEL: div_by_9:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movabsq $1152921504606846975, %rax # imm = 0xFFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    shldq $4, %rdi, %r8
; CHECK-NEXT:    addq %rdi, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rax, %r9
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $56, %rcx
; CHECK-NEXT:    cmpq %rdx, %r9
; CHECK-NEXT:    adcq %r8, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $2049638230412172402, %rdx # imm = 0x1C71C71C71C71C72
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    leaq (%rdx,%rdx,8), %rax
; CHECK-NEXT:    subq %rax, %rcx
; CHECK-NEXT:    subq %rcx, %rdi
; CHECK-NEXT:    sbbq $0, %rsi
; CHECK-NEXT:    movabsq $4099276460824344803, %rcx # imm = 0x38E38E38E38E38E3
; CHECK-NEXT:    imulq %rdi, %rcx
; CHECK-NEXT:    movabsq $-8198552921648689607, %r8 # imm = 0x8E38E38E38E38E39
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    mulq %r8
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    imulq %rsi, %r8
; CHECK-NEXT:    addq %r8, %rdx
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 9
  ret i128 %div
}

define i128 @div_by_11(i128 %x) {
; CHECK-LABEL: div_by_11:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $1152921504606846975, %rax # imm = 0xFFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    shldq $4, %rdi, %r8
; CHECK-NEXT:    addq %rdi, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rax, %r9
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $56, %rcx
; CHECK-NEXT:    cmpq %rdx, %r9
; CHECK-NEXT:    adcq %r8, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $1676976733973595602, %rdx # imm = 0x1745D1745D1745D2
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    leaq (%rdx,%rdx,4), %rax
; CHECK-NEXT:    leaq (%rdx,%rax,2), %rax
; CHECK-NEXT:    subq %rax, %rcx
; CHECK-NEXT:    subq %rcx, %rdi
; CHECK-NEXT:    sbbq $0, %rsi
; CHECK-NEXT:    movabsq $-6707906935894382406, %rcx # imm = 0xA2E8BA2E8BA2E8BA
; CHECK-NEXT:    imulq %rdi, %rcx
; CHECK-NEXT:    movabsq $3353953467947191203, %r8 # imm = 0x2E8BA2E8BA2E8BA3
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    mulq %r8
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    imulq %rsi, %r8
; CHECK-NEXT:    addq %r8, %rdx
; CHECK-NEXT:    retq
  %div = udiv i128 %x, 11
  ret i128 %div
}

define i128 @div_by_22(i128 %x) {
; CHECK-LABEL: div_by_22:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $22, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    callq __udivti3@PLT
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 22
  ret i128 %div
}

define i128 @div_by_25(i128 %x) {
; CHECK-LABEL: div_by_25:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movabsq $1152921504606846975, %rax # imm = 0xFFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    shldq $4, %rdi, %r8
; CHECK-NEXT:    addq %rdi, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rax, %r9
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $56, %rcx
; CHECK-NEXT:    cmpq %rdx, %r9
; CHECK-NEXT:    adcq %r8, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $737869762948382065, %rdx # imm = 0xA3D70A3D70A3D71
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    leaq (%rdx,%rdx,4), %rax
; CHECK-NEXT:    leaq (%rax,%rax,4), %rax
; CHECK-NEXT:    subq %rax, %rcx
; CHECK-NEXT:    subq %rcx, %rdi
; CHECK-NEXT:    sbbq $0, %rsi
; CHECK-NEXT:    movabsq $2951479051793528258, %rcx # imm = 0x28F5C28F5C28F5C2
; CHECK-NEXT:    imulq %rdi, %rcx
; CHECK-NEXT:    movabsq $-8116567392432202711, %r8 # imm = 0x8F5C28F5C28F5C29
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    mulq %r8
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    imulq %rsi, %r8
; CHECK-NEXT:    addq %r8, %rdx
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 25
  ret i128 %div
}

define i128 @div_by_56(i128 %x) {
; CHECK-LABEL: div_by_56:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $56, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    callq __udivti3@PLT
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %div = udiv i128 %x, 56 ; 8 * 7
  ret i128 %div
}

define i128 @rem_by_7(i128 %x) {
; CHECK-LABEL: rem_by_7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $9223372036854775807, %rax # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shldq $1, %rdi, %rcx
; CHECK-NEXT:    addq %rdi, %rcx
; CHECK-NEXT:    andq %rax, %rdi
; CHECK-NEXT:    movq %rcx, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    shrq $62, %rsi
; CHECK-NEXT:    cmpq %rdi, %rdx
; CHECK-NEXT:    adcq %rsi, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $5270498306774157605, %rdx # imm = 0x4924924924924925
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    shrq %rdx
; CHECK-NEXT:    leaq (,%rdx,8), %rax
; CHECK-NEXT:    subq %rax, %rdx
; CHECK-NEXT:    addq %rdx, %rcx
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    retq
  %r = urem i128 %x, 7
  ret i128 %r
}

define i128 @rem_by_14(i128 %x) {
; CHECK-LABEL: rem_by_14:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $14, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    callq __umodti3@PLT
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %r = urem i128 %x, 14
  ret i128 %r
}

define <2 x i64> @v2i64_div_by_7(<2 x i64> %x) {
; CHECK-LABEL: v2i64_div_by_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %xmm0, %rcx
; CHECK-NEXT:    movabsq $2635249153387078803, %rsi # imm = 0x2492492492492493
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rsi
; CHECK-NEXT:    subq %rdx, %rcx
; CHECK-NEXT:    shrq %rcx
; CHECK-NEXT:    addq %rdx, %rcx
; CHECK-NEXT:    movq %rcx, %xmm1
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[2,3,2,3]
; CHECK-NEXT:    movq %xmm0, %rcx
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rsi
; CHECK-NEXT:    subq %rdx, %rcx
; CHECK-NEXT:    shrq %rcx
; CHECK-NEXT:    addq %rdx, %rcx
; CHECK-NEXT:    movq %rcx, %xmm0
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; CHECK-NEXT:    psrlq $2, %xmm1
; CHECK-NEXT:    movdqa %xmm1, %xmm0
; CHECK-NEXT:    retq
entry:
  %div = udiv <2 x i64> %x, <i64 7, i64 7>
  ret <2 x i64> %div
}

define <2 x i64> @v2i64_div_by_14(<2 x i64> %x) {
; CHECK-LABEL: v2i64_div_by_14:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %xmm0, %rax
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    movabsq $5270498306774157605, %rcx # imm = 0x4924924924924925
; CHECK-NEXT:    mulq %rcx
; CHECK-NEXT:    movq %rdx, %xmm1
; CHECK-NEXT:    pshufd {{.*#+}} xmm0 = xmm0[2,3,2,3]
; CHECK-NEXT:    movq %xmm0, %rax
; CHECK-NEXT:    shrq %rax
; CHECK-NEXT:    mulq %rcx
; CHECK-NEXT:    movq %rdx, %xmm0
; CHECK-NEXT:    punpcklqdq {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; CHECK-NEXT:    psrlq $1, %xmm1
; CHECK-NEXT:    movdqa %xmm1, %xmm0
; CHECK-NEXT:    retq
entry:
  %div = udiv <2 x i64> %x, <i64 14, i64 14>
  ret <2 x i64> %div
}

define <4 x i32> @v4i32_div_by_7(<4 x i32> %x) {
; CHECK-LABEL: v4i32_div_by_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movdqa {{.*#+}} xmm1 = [613566757,613566757,613566757,613566757]
; CHECK-NEXT:    movdqa %xmm0, %xmm2
; CHECK-NEXT:    pmuludq %xmm1, %xmm2
; CHECK-NEXT:    pshufd {{.*#+}} xmm2 = xmm2[1,3,2,3]
; CHECK-NEXT:    pshufd {{.*#+}} xmm3 = xmm0[1,1,3,3]
; CHECK-NEXT:    pmuludq %xmm1, %xmm3
; CHECK-NEXT:    pshufd {{.*#+}} xmm1 = xmm3[1,3,2,3]
; CHECK-NEXT:    punpckldq {{.*#+}} xmm2 = xmm2[0],xmm1[0],xmm2[1],xmm1[1]
; CHECK-NEXT:    psubd %xmm2, %xmm0
; CHECK-NEXT:    psrld $1, %xmm0
; CHECK-NEXT:    paddd %xmm2, %xmm0
; CHECK-NEXT:    psrld $2, %xmm0
; CHECK-NEXT:    retq
entry:
  %div = udiv <4 x i32> %x, <i32 7, i32 7, i32 7, i32 7>
  ret <4 x i32> %div
}

define <2 x i128> @v2i128_div_by_7(<2 x i128> %x) {
; CHECK-LABEL: v2i128_div_by_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    .cfi_offset %rbx, -40
; CHECK-NEXT:    .cfi_offset %r12, -32
; CHECK-NEXT:    .cfi_offset %r14, -24
; CHECK-NEXT:    .cfi_offset %r15, -16
; CHECK-NEXT:    movq %rcx, %r9
; CHECK-NEXT:    movq %rdx, %rcx
; CHECK-NEXT:    movabsq $9223372036854775807, %r11 # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rsi, %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    shldq $1, %rsi, %rdx
; CHECK-NEXT:    addq %rsi, %rdx
; CHECK-NEXT:    movq %rdx, %rbx
; CHECK-NEXT:    andq %r11, %rbx
; CHECK-NEXT:    movq %rcx, %r10
; CHECK-NEXT:    shrq $62, %r10
; CHECK-NEXT:    cmpq %rax, %rbx
; CHECK-NEXT:    adcq %rdx, %r10
; CHECK-NEXT:    andq %r11, %r10
; CHECK-NEXT:    movabsq $5270498306774157605, %r15 # imm = 0x4924924924924925
; CHECK-NEXT:    movq %r10, %rax
; CHECK-NEXT:    mulq %r15
; CHECK-NEXT:    shrq %rdx
; CHECK-NEXT:    leaq (,%rdx,8), %rax
; CHECK-NEXT:    subq %rax, %rdx
; CHECK-NEXT:    addq %r10, %rdx
; CHECK-NEXT:    subq %rdx, %rsi
; CHECK-NEXT:    sbbq $0, %rcx
; CHECK-NEXT:    movabsq $-5270498306774157605, %rbx # imm = 0xB6DB6DB6DB6DB6DB
; CHECK-NEXT:    movq %rsi, %r10
; CHECK-NEXT:    imulq %rbx, %r10
; CHECK-NEXT:    movabsq $7905747460161236407, %r14 # imm = 0x6DB6DB6DB6DB6DB7
; CHECK-NEXT:    movq %rsi, %rax
; CHECK-NEXT:    mulq %r14
; CHECK-NEXT:    movq %rax, %rsi
; CHECK-NEXT:    addq %r10, %rdx
; CHECK-NEXT:    imulq %r14, %rcx
; CHECK-NEXT:    addq %rdx, %rcx
; CHECK-NEXT:    movq %r9, %rax
; CHECK-NEXT:    andq %r11, %rax
; CHECK-NEXT:    movq %r8, %rdx
; CHECK-NEXT:    shldq $1, %r9, %rdx
; CHECK-NEXT:    addq %r9, %rdx
; CHECK-NEXT:    movq %rdx, %r12
; CHECK-NEXT:    andq %r11, %r12
; CHECK-NEXT:    movq %r8, %r10
; CHECK-NEXT:    shrq $62, %r10
; CHECK-NEXT:    cmpq %rax, %r12
; CHECK-NEXT:    adcq %rdx, %r10
; CHECK-NEXT:    andq %r11, %r10
; CHECK-NEXT:    movq %r10, %rax
; CHECK-NEXT:    mulq %r15
; CHECK-NEXT:    shrq %rdx
; CHECK-NEXT:    leaq (,%rdx,8), %rax
; CHECK-NEXT:    subq %rax, %rdx
; CHECK-NEXT:    addq %r10, %rdx
; CHECK-NEXT:    subq %rdx, %r9
; CHECK-NEXT:    sbbq $0, %r8
; CHECK-NEXT:    imulq %r9, %rbx
; CHECK-NEXT:    movq %r9, %rax
; CHECK-NEXT:    mulq %r14
; CHECK-NEXT:    addq %rbx, %rdx
; CHECK-NEXT:    imulq %r14, %r8
; CHECK-NEXT:    addq %rdx, %r8
; CHECK-NEXT:    movq %rax, 16(%rdi)
; CHECK-NEXT:    movq %rsi, (%rdi)
; CHECK-NEXT:    movq %r8, 24(%rdi)
; CHECK-NEXT:    movq %rcx, 8(%rdi)
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %div = udiv <2 x i128> %x, <i128 7, i128 7>
  ret <2 x i128> %div
}
