; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-linux-gnu   | FileCheck %s --check-prefix=X64
; RUN: llc < %s -mtriple=aarch64-linux-gnu  | FileCheck %s --check-prefix=A64
; RUN: llc < %s -mtriple=i686-linux-gnu     | FileCheck %s --check-prefix=X86-32

; Verify that sdiv+srem / udiv+urem on i128 with the same operands lower to a
; single __divmodti4 / __udivmodti4 call rather than two separate helper calls.
; DAGCombiner::useDivRem fuses the pair into ISD::SDIVREM/UDIVREM, which is
; then expanded to the fused libcall via ExpandIntRes_DIVREM in the type
; legalizer.

define void @sdivrem_i128(ptr %out, i128 %n, i128 %d) nounwind {
; X64-LABEL: sdivrem_i128:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $16, %rsp
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    movq %rdi, %rbx
; X64-NEXT:    movq %rsp, %r8
; X64-NEXT:    movq %rsi, %rdi
; X64-NEXT:    movq %rdx, %rsi
; X64-NEXT:    movq %rcx, %rdx
; X64-NEXT:    movq %rax, %rcx
; X64-NEXT:    callq __divmodti4@PLT
; X64-NEXT:    movaps (%rsp), %xmm0
; X64-NEXT:    movq %rdx, 8(%rbx)
; X64-NEXT:    movq %rax, (%rbx)
; X64-NEXT:    movaps %xmm0, 16(%rbx)
; X64-NEXT:    addq $16, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    retq
;
; A64-LABEL: sdivrem_i128:
; A64:       // %bb.0:
; A64-NEXT:    sub sp, sp, #32
; A64-NEXT:    mov x8, x4
; A64-NEXT:    stp x30, x19, [sp, #16] // 16-byte Folded Spill
; A64-NEXT:    mov x1, x3
; A64-NEXT:    mov x19, x0
; A64-NEXT:    mov x4, sp
; A64-NEXT:    mov x0, x2
; A64-NEXT:    mov x2, x8
; A64-NEXT:    mov x3, x5
; A64-NEXT:    bl __divmodti4
; A64-NEXT:    ldp x8, x9, [sp]
; A64-NEXT:    stp x0, x1, [x19]
; A64-NEXT:    stp x8, x9, [x19, #16]
; A64-NEXT:    ldp x30, x19, [sp, #16] // 16-byte Folded Reload
; A64-NEXT:    add sp, sp, #32
; A64-NEXT:    ret
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  %p0 = getelementptr inbounds {i128, i128}, ptr %out, i32 0, i32 0
  %p1 = getelementptr inbounds {i128, i128}, ptr %out, i32 0, i32 1
  store i128 %q, ptr %p0, align 16
  store i128 %r, ptr %p1, align 16
  ret void
}

define void @udivrem_i128(ptr %out, i128 %n, i128 %d) nounwind {
; X64-LABEL: udivrem_i128:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $16, %rsp
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    movq %rdi, %rbx
; X64-NEXT:    movq %rsp, %r8
; X64-NEXT:    movq %rsi, %rdi
; X64-NEXT:    movq %rdx, %rsi
; X64-NEXT:    movq %rcx, %rdx
; X64-NEXT:    movq %rax, %rcx
; X64-NEXT:    callq __udivmodti4@PLT
; X64-NEXT:    movaps (%rsp), %xmm0
; X64-NEXT:    movq %rdx, 8(%rbx)
; X64-NEXT:    movq %rax, (%rbx)
; X64-NEXT:    movaps %xmm0, 16(%rbx)
; X64-NEXT:    addq $16, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    retq
;
; A64-LABEL: udivrem_i128:
; A64:       // %bb.0:
; A64-NEXT:    sub sp, sp, #32
; A64-NEXT:    mov x8, x4
; A64-NEXT:    stp x30, x19, [sp, #16] // 16-byte Folded Spill
; A64-NEXT:    mov x1, x3
; A64-NEXT:    mov x19, x0
; A64-NEXT:    mov x4, sp
; A64-NEXT:    mov x0, x2
; A64-NEXT:    mov x2, x8
; A64-NEXT:    mov x3, x5
; A64-NEXT:    bl __udivmodti4
; A64-NEXT:    ldp x8, x9, [sp]
; A64-NEXT:    stp x0, x1, [x19]
; A64-NEXT:    stp x8, x9, [x19, #16]
; A64-NEXT:    ldp x30, x19, [sp, #16] // 16-byte Folded Reload
; A64-NEXT:    add sp, sp, #32
; A64-NEXT:    ret
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  %p0 = getelementptr inbounds {i128, i128}, ptr %out, i32 0, i32 0
  %p1 = getelementptr inbounds {i128, i128}, ptr %out, i32 0, i32 1
  store i128 %q, ptr %p0, align 16
  store i128 %r, ptr %p1, align 16
  ret void
}

; On 32-bit targets __divmodti4/__udivmodti4 are not registered (Int128RTLibcalls
; is only added to 64-bit targets), so the fallback path in ExpandIntRes_DIVREM
; fires: the SDIVREM node is replaced by separate SDIV + SREM, which then expand
; inline. Verify no fused call is emitted and the code compiles without crashing.

; X86-32-NOT: __divmodti4
; X86-32-NOT: __udivmodti4

define void @sdivrem_i128_fallback(ptr %out, i128 %n, i128 %d) nounwind {
; X64-LABEL: sdivrem_i128_fallback:
; X64:       # %bb.0:
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $16, %rsp
; X64-NEXT:    movq %r8, %rax
; X64-NEXT:    movq %rdi, %rbx
; X64-NEXT:    movq %rsp, %r8
; X64-NEXT:    movq %rsi, %rdi
; X64-NEXT:    movq %rdx, %rsi
; X64-NEXT:    movq %rcx, %rdx
; X64-NEXT:    movq %rax, %rcx
; X64-NEXT:    callq __divmodti4@PLT
; X64-NEXT:    movaps (%rsp), %xmm0
; X64-NEXT:    movq %rdx, 8(%rbx)
; X64-NEXT:    movq %rax, (%rbx)
; X64-NEXT:    movaps %xmm0, 16(%rbx)
; X64-NEXT:    addq $16, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    retq
;
; A64-LABEL: sdivrem_i128_fallback:
; A64:       // %bb.0:
; A64-NEXT:    sub sp, sp, #32
; A64-NEXT:    mov x8, x4
; A64-NEXT:    stp x30, x19, [sp, #16] // 16-byte Folded Spill
; A64-NEXT:    mov x1, x3
; A64-NEXT:    mov x19, x0
; A64-NEXT:    mov x4, sp
; A64-NEXT:    mov x0, x2
; A64-NEXT:    mov x2, x8
; A64-NEXT:    mov x3, x5
; A64-NEXT:    bl __divmodti4
; A64-NEXT:    ldp x8, x9, [sp]
; A64-NEXT:    stp x0, x1, [x19]
; A64-NEXT:    stp x8, x9, [x19, #16]
; A64-NEXT:    ldp x30, x19, [sp, #16] // 16-byte Folded Reload
; A64-NEXT:    add sp, sp, #32
; A64-NEXT:    ret
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  %p0 = getelementptr inbounds {i128, i128}, ptr %out, i32 0, i32 0
  %p1 = getelementptr inbounds {i128, i128}, ptr %out, i32 0, i32 1
  store i128 %q, ptr %p0, align 16
  store i128 %r, ptr %p1, align 16
  ret void
}
