; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=i386-linux-gnu          | FileCheck %s --check-prefix=LINUX-X86
; RUN: llc < %s -mtriple=i686-linux-gnu          | FileCheck %s --check-prefix=LINUX-X86
; RUN: llc < %s -mtriple=i686-pc-windows-msvc    | FileCheck %s --check-prefix=WIN32

define void @sdivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; LINUX-X86-LABEL: sdivrem_i128:
; LINUX-X86:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    pushl %ebp
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 8
; LINUX-X86-NEXT:    pushl %ebx
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 12
; LINUX-X86-NEXT:    pushl %edi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 16
; LINUX-X86-NEXT:    pushl %esi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 20
; LINUX-X86-NEXT:    subl $284, %esp # imm = 0x11C
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 304
; LINUX-X86-NEXT:    .cfi_offset %esi, -20
; LINUX-X86-NEXT:    .cfi_offset %edi, -16
; LINUX-X86-NEXT:    .cfi_offset %ebx, -12
; LINUX-X86-NEXT:    .cfi_offset %ebp, -8
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; LINUX-X86-NEXT:    movl %ebp, %esi
; LINUX-X86-NEXT:    sarl $31, %esi
; LINUX-X86-NEXT:    xorl %esi, %ebp
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    xorl %esi, %edx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    xorl %esi, %eax
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    xorl %esi, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    subl %esi, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %esi, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %esi, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %esi, %ebp
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    movl %ebx, %edx
; LINUX-X86-NEXT:    sarl $31, %edx
; LINUX-X86-NEXT:    xorl %edx, %ebx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; LINUX-X86-NEXT:    xorl %edx, %edi
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    xorl %edx, %eax
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    xorl %edx, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    subl %edx, %ecx
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %eax
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %edi
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %ebx
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %ebx, %eax
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %edi, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    sete {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %ebp, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    orl %eax, %edx
; LINUX-X86-NEXT:    orl %ecx, %edx
; LINUX-X86-NEXT:    sete %cl
; LINUX-X86-NEXT:    testl %ebx, %ebx
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    jne .LBB0_1
; LINUX-X86-NEXT:  # %bb.2: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl %edi, %ebp
; LINUX-X86-NEXT:    xorl $31, %ebp
; LINUX-X86-NEXT:    orl $32, %ebp
; LINUX-X86-NEXT:    jmp .LBB0_3
; LINUX-X86-NEXT:  .LBB0_1:
; LINUX-X86-NEXT:    bsrl %ebx, %ebp
; LINUX-X86-NEXT:    xorl $31, %ebp
; LINUX-X86-NEXT:  .LBB0_3: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    testl %edx, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    jne .LBB0_4
; LINUX-X86-NEXT:  # %bb.5: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl %esi, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    jmp .LBB0_6
; LINUX-X86-NEXT:  .LBB0_4:
; LINUX-X86-NEXT:    bsrl %edx, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:  .LBB0_6: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; LINUX-X86-NEXT:    jne .LBB0_8
; LINUX-X86-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    orl $64, %edx
; LINUX-X86-NEXT:    movl %edx, %ebp
; LINUX-X86-NEXT:  .LBB0_8: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    testl %ebx, %ebx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    jne .LBB0_9
; LINUX-X86-NEXT:  # %bb.10: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl %eax, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    testl %esi, %esi
; LINUX-X86-NEXT:    je .LBB0_13
; LINUX-X86-NEXT:  .LBB0_12:
; LINUX-X86-NEXT:    bsrl %esi, %esi
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:    jmp .LBB0_14
; LINUX-X86-NEXT:  .LBB0_9:
; LINUX-X86-NEXT:    bsrl %ebx, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    testl %esi, %esi
; LINUX-X86-NEXT:    jne .LBB0_12
; LINUX-X86-NEXT:  .LBB0_13: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:    orl $32, %esi
; LINUX-X86-NEXT:  .LBB0_14: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    orb %cl, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; LINUX-X86-NEXT:    orl %ebx, %eax
; LINUX-X86-NEXT:    jne .LBB0_16
; LINUX-X86-NEXT:  # %bb.15: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    orl $64, %esi
; LINUX-X86-NEXT:    movl %esi, %edx
; LINUX-X86-NEXT:  .LBB0_16: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    xorl %ebx, %ebx
; LINUX-X86-NEXT:    movl %ebp, %ecx
; LINUX-X86-NEXT:    subl %edx, %ecx
; LINUX-X86-NEXT:    movl $0, %edx
; LINUX-X86-NEXT:    sbbl %edx, %edx
; LINUX-X86-NEXT:    movl $0, %esi
; LINUX-X86-NEXT:    sbbl %esi, %esi
; LINUX-X86-NEXT:    movl $0, %edi
; LINUX-X86-NEXT:    sbbl %edi, %edi
; LINUX-X86-NEXT:    cmpb $0, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Reload
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    jne .LBB0_17
; LINUX-X86-NEXT:  # %bb.18: # %select.false.sink
; LINUX-X86-NEXT:    movl $127, %eax
; LINUX-X86-NEXT:    cmpl %ecx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %edx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %esi, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %edi, %eax
; LINUX-X86-NEXT:    setb %al
; LINUX-X86-NEXT:  .LBB0_19: # %select.end
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    xorl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    testb %al, %al
; LINUX-X86-NEXT:    movl $0, %edx
; LINUX-X86-NEXT:    movl $0, %ebp
; LINUX-X86-NEXT:    movl $0, %esi
; LINUX-X86-NEXT:    jne .LBB0_21
; LINUX-X86-NEXT:  # %bb.20: # %select.end
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    movl %edi, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:  .LBB0_21: # %select.end
; LINUX-X86-NEXT:    movl %edx, %edi
; LINUX-X86-NEXT:    jne .LBB0_22
; LINUX-X86-NEXT:  # %bb.29: # %select.end
; LINUX-X86-NEXT:    movl %ecx, %eax
; LINUX-X86-NEXT:    xorl $127, %eax
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %ecx, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    je .LBB0_30
; LINUX-X86-NEXT:  # %bb.27: # %udiv-bb15
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    xorb $127, %cl
; LINUX-X86-NEXT:    movl %ecx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    negb %al
; LINUX-X86-NEXT:    movsbl %al, %eax
; LINUX-X86-NEXT:    movl 264(%esp,%eax), %edi
; LINUX-X86-NEXT:    movl 268(%esp,%eax), %esi
; LINUX-X86-NEXT:    shldl %cl, %edi, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl 256(%esp,%eax), %ebp
; LINUX-X86-NEXT:    movl 260(%esp,%eax), %ebx
; LINUX-X86-NEXT:    shldl %cl, %ebx, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl %cl, %ebp, %ebx
; LINUX-X86-NEXT:    shll %cl, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl $1, %edx
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jb .LBB0_28
; LINUX-X86-NEXT:  # %bb.24: # %udiv-preheader4
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %ecx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    movzbl %al, %eax
; LINUX-X86-NEXT:    movl 220(%esp,%eax), %ebp
; LINUX-X86-NEXT:    movl 216(%esp,%eax), %edx
; LINUX-X86-NEXT:    movl %edx, %esi
; LINUX-X86-NEXT:    shrdl %cl, %ebp, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl 208(%esp,%eax), %edi
; LINUX-X86-NEXT:    movl 212(%esp,%eax), %esi
; LINUX-X86-NEXT:    movl %esi, %eax
; LINUX-X86-NEXT:    shrdl %cl, %edx, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shrl %cl, %ebp
; LINUX-X86-NEXT:    movl %ebp, %edx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    # kill: def $cl killed $cl killed $ecx
; LINUX-X86-NEXT:    shrdl %cl, %esi, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    addl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    .p2align 4
; LINUX-X86-NEXT:  .LBB0_25: # %udiv-do-while3
; LINUX-X86-NEXT:    # =>This Inner Loop Header: Depth=1
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %ebp, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edi, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %esi, %edi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edx, %esi
; LINUX-X86-NEXT:    shldl $1, %ecx, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    orl %eax, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl $1, %ebx, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %ecx, %ebx
; LINUX-X86-NEXT:    orl %eax, %ebx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl %ecx, %ecx
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    cmpl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %edi, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ebp, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    sarl $31, %edx
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    andl $1, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %edx, %ebx
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %edx, %eax
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    subl %edx, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %eax, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ebx, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ecx, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    addl $-1, %ecx
; LINUX-X86-NEXT:    adcl $-1, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %esi
; LINUX-X86-NEXT:    adcl $-1, %edi
; LINUX-X86-NEXT:    movl %ebp, %eax
; LINUX-X86-NEXT:    orl %edi, %eax
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %esi, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    jne .LBB0_25
; LINUX-X86-NEXT:  .LBB0_26: # %udiv-loop-exit2
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %ecx, %esi
; LINUX-X86-NEXT:    shldl $1, %ebx, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %eax, %ebx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    leal (%edx,%eax,2), %eax
; LINUX-X86-NEXT:    movl %ecx, %ebp
; LINUX-X86-NEXT:  .LBB0_23: # %udiv-end1
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:  .LBB0_30: # %udiv-end1
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    xorl %edx, %esi
; LINUX-X86-NEXT:    xorl %edx, %ebp
; LINUX-X86-NEXT:    xorl %edx, %ebx
; LINUX-X86-NEXT:    xorl %edx, %eax
; LINUX-X86-NEXT:    subl %edx, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %ebx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    subl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %eax, %edx
; LINUX-X86-NEXT:    sbbl %eax, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %eax, %ebx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    subl %ecx, %edi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ecx, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ecx, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ecx, %esi
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %esi, %eax
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %ebp, %edi
; LINUX-X86-NEXT:    orl %eax, %edi
; LINUX-X86-NEXT:    sete %al
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    orl %ebx, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    orl %ecx, %edx
; LINUX-X86-NEXT:    sete %cl
; LINUX-X86-NEXT:    testl %esi, %esi
; LINUX-X86-NEXT:    movl %ebx, %edi
; LINUX-X86-NEXT:    jne .LBB0_31
; LINUX-X86-NEXT:  # %bb.32: # %udiv-end1
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    bsrl %ebx, %ebp
; LINUX-X86-NEXT:    xorl $31, %ebp
; LINUX-X86-NEXT:    orl $32, %ebp
; LINUX-X86-NEXT:    jmp .LBB0_33
; LINUX-X86-NEXT:  .LBB0_31:
; LINUX-X86-NEXT:    bsrl %esi, %ebp
; LINUX-X86-NEXT:    xorl $31, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:  .LBB0_33: # %udiv-end1
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    testl %edx, %edx
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    jne .LBB0_34
; LINUX-X86-NEXT:  # %bb.35: # %udiv-end1
; LINUX-X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    jmp .LBB0_36
; LINUX-X86-NEXT:  .LBB0_34:
; LINUX-X86-NEXT:    bsrl %edx, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:  .LBB0_36: # %udiv-end1
; LINUX-X86-NEXT:    movl %ebx, %esi
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; LINUX-X86-NEXT:    jne .LBB0_38
; LINUX-X86-NEXT:  # %bb.37: # %udiv-end1
; LINUX-X86-NEXT:    orl $64, %edx
; LINUX-X86-NEXT:    movl %edx, %ebp
; LINUX-X86-NEXT:  .LBB0_38: # %udiv-end1
; LINUX-X86-NEXT:    testl %edi, %edi
; LINUX-X86-NEXT:    jne .LBB0_39
; LINUX-X86-NEXT:  # %bb.40: # %udiv-end1
; LINUX-X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    jmp .LBB0_41
; LINUX-X86-NEXT:  .LBB0_39:
; LINUX-X86-NEXT:    bsrl %edi, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:  .LBB0_41: # %udiv-end1
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    testl %esi, %esi
; LINUX-X86-NEXT:    jne .LBB0_42
; LINUX-X86-NEXT:  # %bb.43: # %udiv-end1
; LINUX-X86-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:    orl $32, %esi
; LINUX-X86-NEXT:    jmp .LBB0_44
; LINUX-X86-NEXT:  .LBB0_42:
; LINUX-X86-NEXT:    bsrl %esi, %esi
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:  .LBB0_44: # %udiv-end1
; LINUX-X86-NEXT:    orb %cl, %al
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %edi, %ecx
; LINUX-X86-NEXT:    jne .LBB0_46
; LINUX-X86-NEXT:  # %bb.45: # %udiv-end1
; LINUX-X86-NEXT:    orl $64, %esi
; LINUX-X86-NEXT:    movl %esi, %edx
; LINUX-X86-NEXT:  .LBB0_46: # %udiv-end1
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl %ebp, %ebx
; LINUX-X86-NEXT:    subl %edx, %ebx
; LINUX-X86-NEXT:    movl $0, %esi
; LINUX-X86-NEXT:    sbbl %esi, %esi
; LINUX-X86-NEXT:    movl $0, %ecx
; LINUX-X86-NEXT:    sbbl %ecx, %ecx
; LINUX-X86-NEXT:    movl $0, %edi
; LINUX-X86-NEXT:    sbbl %edi, %edi
; LINUX-X86-NEXT:    testb %al, %al
; LINUX-X86-NEXT:    jne .LBB0_47
; LINUX-X86-NEXT:  # %bb.48: # %select.false.sink8
; LINUX-X86-NEXT:    movl $127, %eax
; LINUX-X86-NEXT:    cmpl %ebx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %esi, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %ecx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %edi, %eax
; LINUX-X86-NEXT:    setb %al
; LINUX-X86-NEXT:  .LBB0_49: # %select.end7
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    testb %al, %al
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jne .LBB0_51
; LINUX-X86-NEXT:  # %bb.50: # %select.end7
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:  .LBB0_51: # %select.end7
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    jne .LBB0_52
; LINUX-X86-NEXT:  # %bb.58: # %select.end7
; LINUX-X86-NEXT:    movl %ebx, %eax
; LINUX-X86-NEXT:    xorl $127, %eax
; LINUX-X86-NEXT:    orl %ecx, %eax
; LINUX-X86-NEXT:    movl %esi, %ebp
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %esi, %ecx
; LINUX-X86-NEXT:    orl %edi, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    je .LBB0_59
; LINUX-X86-NEXT:  # %bb.56: # %udiv-bb1
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %ebx, %ecx
; LINUX-X86-NEXT:    xorb $127, %cl
; LINUX-X86-NEXT:    movl %ecx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    negb %al
; LINUX-X86-NEXT:    movsbl %al, %eax
; LINUX-X86-NEXT:    movl 200(%esp,%eax), %edx
; LINUX-X86-NEXT:    movl 204(%esp,%eax), %esi
; LINUX-X86-NEXT:    shldl %cl, %edx, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl 192(%esp,%eax), %esi
; LINUX-X86-NEXT:    movl 196(%esp,%eax), %eax
; LINUX-X86-NEXT:    shldl %cl, %eax, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl %cl, %esi, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shll %cl, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl $1, %ebx
; LINUX-X86-NEXT:    adcl $0, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    adcl $0, %edi
; LINUX-X86-NEXT:    jb .LBB0_57
; LINUX-X86-NEXT:  # %bb.53: # %udiv-preheader
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %ebx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    movzbl %al, %eax
; LINUX-X86-NEXT:    movl 156(%esp,%eax), %edx
; LINUX-X86-NEXT:    movl 152(%esp,%eax), %esi
; LINUX-X86-NEXT:    movl %esi, %ebp
; LINUX-X86-NEXT:    movl %ebx, %ecx
; LINUX-X86-NEXT:    shrdl %cl, %edx, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl 144(%esp,%eax), %ebp
; LINUX-X86-NEXT:    movl 148(%esp,%eax), %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shrdl %cl, %esi, %eax
; LINUX-X86-NEXT:    movl %eax, %esi
; LINUX-X86-NEXT:    shrl %cl, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    shrdl %cl, %eax, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    addl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    .p2align 4
; LINUX-X86-NEXT:  .LBB0_54: # %udiv-do-while
; LINUX-X86-NEXT:    # =>This Inner Loop Header: Depth=1
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %ebp, %edx
; LINUX-X86-NEXT:    movl %edx, %ebx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %esi, %ecx
; LINUX-X86-NEXT:    shldl $1, %esi, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %esi, %ecx
; LINUX-X86-NEXT:    shldl $1, %eax, %esi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edx, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    orl %edi, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %eax, %edx
; LINUX-X86-NEXT:    orl %edi, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edx, %eax
; LINUX-X86-NEXT:    orl %edi, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl %edx, %edx
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    cmpl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ecx, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ebp, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ebx, %eax
; LINUX-X86-NEXT:    sarl $31, %eax
; LINUX-X86-NEXT:    movl %eax, %edx
; LINUX-X86-NEXT:    andl $1, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl %eax, %ebx
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %eax, %edi
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %eax, %edx
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; LINUX-X86-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    subl %eax, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %ecx
; LINUX-X86-NEXT:    movl %ecx, %esi
; LINUX-X86-NEXT:    sbbl %edi, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ebx, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    addl $-1, %ebx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    adcl $-1, %ebp
; LINUX-X86-NEXT:    adcl $-1, %edi
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %edi, %eax
; LINUX-X86-NEXT:    movl %ebx, %ecx
; LINUX-X86-NEXT:    orl %ebp, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    jne .LBB0_54
; LINUX-X86-NEXT:  .LBB0_55: # %udiv-loop-exit
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edx, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %esi, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %eax, %esi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    leal (%ecx,%eax,2), %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:  .LBB0_59: # %udiv-end
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl %eax, (%ecx)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, 4(%ecx)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, 8(%ecx)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, 12(%ecx)
; LINUX-X86-NEXT:    movl %edx, %esi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    imull %eax, %esi
; LINUX-X86-NEXT:    movl %edx, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    mull %ebp
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl %esi, %edx
; LINUX-X86-NEXT:    imull %ebp, %ecx
; LINUX-X86-NEXT:    addl %edx, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    mull %ebx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    imull %edi, %esi
; LINUX-X86-NEXT:    addl %edx, %esi
; LINUX-X86-NEXT:    imull {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; LINUX-X86-NEXT:    addl %esi, %ebx
; LINUX-X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    adcl %ecx, %ebx
; LINUX-X86-NEXT:    movl %ebp, %eax
; LINUX-X86-NEXT:    mull %edi
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    mull %edi
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    movl %eax, %esi
; LINUX-X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; LINUX-X86-NEXT:    adcl $0, %ecx
; LINUX-X86-NEXT:    movl %ebp, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    mull %ebp
; LINUX-X86-NEXT:    movl %edx, %edi
; LINUX-X86-NEXT:    addl %esi, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    adcl %ecx, %edi
; LINUX-X86-NEXT:    setb %cl
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    mull %ebp
; LINUX-X86-NEXT:    addl %edi, %eax
; LINUX-X86-NEXT:    movzbl %cl, %ecx
; LINUX-X86-NEXT:    adcl %ecx, %edx
; LINUX-X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    adcl %ebx, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    subl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %edx, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    xorl %edx, %eax
; LINUX-X86-NEXT:    xorl %edx, %ecx
; LINUX-X86-NEXT:    xorl %edx, %esi
; LINUX-X86-NEXT:    xorl %edx, %edi
; LINUX-X86-NEXT:    subl %edx, %edi
; LINUX-X86-NEXT:    sbbl %edx, %esi
; LINUX-X86-NEXT:    sbbl %edx, %ecx
; LINUX-X86-NEXT:    sbbl %edx, %eax
; LINUX-X86-NEXT:    movl %eax, %edx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %edi, (%eax)
; LINUX-X86-NEXT:    movl %esi, 4(%eax)
; LINUX-X86-NEXT:    movl %ecx, 8(%eax)
; LINUX-X86-NEXT:    movl %edx, 12(%eax)
; LINUX-X86-NEXT:    addl $284, %esp # imm = 0x11C
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 20
; LINUX-X86-NEXT:    popl %esi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 16
; LINUX-X86-NEXT:    popl %edi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 12
; LINUX-X86-NEXT:    popl %ebx
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 8
; LINUX-X86-NEXT:    popl %ebp
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 4
; LINUX-X86-NEXT:    retl
; LINUX-X86-NEXT:  .LBB0_17:
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 304
; LINUX-X86-NEXT:    movb $1, %al
; LINUX-X86-NEXT:    jmp .LBB0_19
; LINUX-X86-NEXT:  .LBB0_28:
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jmp .LBB0_26
; LINUX-X86-NEXT:  .LBB0_47:
; LINUX-X86-NEXT:    movb $1, %al
; LINUX-X86-NEXT:    jmp .LBB0_49
; LINUX-X86-NEXT:  .LBB0_57:
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jmp .LBB0_55
; LINUX-X86-NEXT:  .LBB0_22:
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    jmp .LBB0_23
; LINUX-X86-NEXT:  .LBB0_52:
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    jmp .LBB0_59
;
; WIN32-LABEL: sdivrem_i128:
; WIN32:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    pushl %ebp
; WIN32-NEXT:    movl %esp, %ebp
; WIN32-NEXT:    pushl %ebx
; WIN32-NEXT:    pushl %edi
; WIN32-NEXT:    pushl %esi
; WIN32-NEXT:    andl $-16, %esp
; WIN32-NEXT:    subl $288, %esp # imm = 0x120
; WIN32-NEXT:    movl 36(%ebp), %edi
; WIN32-NEXT:    movl %edi, %esi
; WIN32-NEXT:    sarl $31, %esi
; WIN32-NEXT:    xorl %esi, %edi
; WIN32-NEXT:    movl 32(%ebp), %eax
; WIN32-NEXT:    xorl %esi, %eax
; WIN32-NEXT:    movl 28(%ebp), %ecx
; WIN32-NEXT:    xorl %esi, %ecx
; WIN32-NEXT:    movl 24(%ebp), %edx
; WIN32-NEXT:    xorl %esi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    subl %esi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %esi, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %esi, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %esi, %edi
; WIN32-NEXT:    movl 52(%ebp), %ebx
; WIN32-NEXT:    movl %ebx, %edx
; WIN32-NEXT:    sarl $31, %edx
; WIN32-NEXT:    xorl %edx, %ebx
; WIN32-NEXT:    movl 48(%ebp), %esi
; WIN32-NEXT:    xorl %edx, %esi
; WIN32-NEXT:    movl 44(%ebp), %eax
; WIN32-NEXT:    xorl %edx, %eax
; WIN32-NEXT:    movl 40(%ebp), %ecx
; WIN32-NEXT:    xorl %edx, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    subl %edx, %ecx
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %edx, %eax
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %edx, %esi
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %edx, %ebx
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %ebx, %eax
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %esi, %ecx
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    sete %al
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %edi, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; WIN32-NEXT:    orl %ecx, %edx
; WIN32-NEXT:    sete %cl
; WIN32-NEXT:    testl %ebx, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB0_1
; WIN32-NEXT:  # %bb.2: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl %esi, %edi
; WIN32-NEXT:    xorl $31, %edi
; WIN32-NEXT:    orl $32, %edi
; WIN32-NEXT:    jmp LBB0_3
; WIN32-NEXT:  LBB0_1:
; WIN32-NEXT:    bsrl %ebx, %edi
; WIN32-NEXT:    xorl $31, %edi
; WIN32-NEXT:  LBB0_3: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    testl %edx, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    jne LBB0_4
; WIN32-NEXT:  # %bb.5: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    jmp LBB0_6
; WIN32-NEXT:  LBB0_4:
; WIN32-NEXT:    bsrl %edx, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:  LBB0_6: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    jne LBB0_8
; WIN32-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    orl $64, %edx
; WIN32-NEXT:    movl %edx, %edi
; WIN32-NEXT:  LBB0_8: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    testl %edx, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    jne LBB0_9
; WIN32-NEXT:  # %bb.10: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl %ebx, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    je LBB0_13
; WIN32-NEXT:  LBB0_12:
; WIN32-NEXT:    bsrl %esi, %esi
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:    jmp LBB0_14
; WIN32-NEXT:  LBB0_9:
; WIN32-NEXT:    bsrl %edx, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    jne LBB0_12
; WIN32-NEXT:  LBB0_13: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:    orl $32, %esi
; WIN32-NEXT:  LBB0_14: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    orb %cl, %al
; WIN32-NEXT:    movl %ebx, %ecx
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    jne LBB0_16
; WIN32-NEXT:  # %bb.15: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    orl $64, %esi
; WIN32-NEXT:    movl %esi, %edx
; WIN32-NEXT:  LBB0_16: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    xorl %ebx, %ebx
; WIN32-NEXT:    subl %edx, %edi
; WIN32-NEXT:    movl $0, %ecx
; WIN32-NEXT:    sbbl %ecx, %ecx
; WIN32-NEXT:    movl $0, %edx
; WIN32-NEXT:    sbbl %edx, %edx
; WIN32-NEXT:    movl $0, %esi
; WIN32-NEXT:    sbbl %esi, %esi
; WIN32-NEXT:    testb %al, %al
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB0_17
; WIN32-NEXT:  # %bb.18: # %select.false.sink
; WIN32-NEXT:    movl $127, %eax
; WIN32-NEXT:    cmpl %edi, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %ecx, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %edx, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %esi, %eax
; WIN32-NEXT:    setb %al
; WIN32-NEXT:  LBB0_19: # %select.end
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    xorl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    testb %al, %al
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    movl $0, %edx
; WIN32-NEXT:    movl $0, %ecx
; WIN32-NEXT:    jne LBB0_21
; WIN32-NEXT:  # %bb.20: # %select.end
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:  LBB0_21: # %select.end
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB0_22
; WIN32-NEXT:  # %bb.28: # %select.end
; WIN32-NEXT:    movl %edi, %eax
; WIN32-NEXT:    xorl $127, %eax
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; WIN32-NEXT:    movl %edi, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    je LBB0_29
; WIN32-NEXT:  # %bb.26: # %udiv-bb15
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %esi, %eax
; WIN32-NEXT:    movl %eax, %ecx
; WIN32-NEXT:    movl %esi, %edi
; WIN32-NEXT:    xorb $127, %cl
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    negb %al
; WIN32-NEXT:    movsbl %al, %eax
; WIN32-NEXT:    movl 264(%esp,%eax), %esi
; WIN32-NEXT:    movl 268(%esp,%eax), %edx
; WIN32-NEXT:    shldl %cl, %esi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 256(%esp,%eax), %edx
; WIN32-NEXT:    movl 260(%esp,%eax), %ebx
; WIN32-NEXT:    shldl %cl, %ebx, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl %cl, %edx, %ebx
; WIN32-NEXT:    shll %cl, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl $1, %edi
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    jb LBB0_27
; WIN32-NEXT:  # %bb.23: # %udiv-preheader4
; WIN32-NEXT:    movl %edi, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    movzbl %al, %eax
; WIN32-NEXT:    movl 220(%esp,%eax), %edi
; WIN32-NEXT:    movl 216(%esp,%eax), %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shrdl %cl, %edi, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 208(%esp,%eax), %edx
; WIN32-NEXT:    movl 212(%esp,%eax), %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    shrdl %cl, %esi, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shrl %cl, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    # kill: def $cl killed $cl killed $ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shrdl %cl, %eax, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    addl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    .p2align 4
; WIN32-NEXT:  LBB0_24: # %udiv-do-while3
; WIN32-NEXT:    # =>This Inner Loop Header: Depth=1
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %esi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %esi
; WIN32-NEXT:    shldl $1, %ecx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edi, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    orl %edx, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl $1, %ebx, %edi
; WIN32-NEXT:    orl %edx, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %ecx, %ebx
; WIN32-NEXT:    orl %edx, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl %ecx, %ecx
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    cmpl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl %esi, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    sbbl %edx, %ecx
; WIN32-NEXT:    sarl $31, %ecx
; WIN32-NEXT:    movl %ecx, %edi
; WIN32-NEXT:    andl $1, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %edi
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %edi
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; WIN32-NEXT:    movl %ecx, %ebx
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    subl %ecx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %ebx, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    sbbl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl %edx, %eax
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    addl $-1, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %edi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %eax
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %edi, %edx
; WIN32-NEXT:    orl %ecx, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    jne LBB0_24
; WIN32-NEXT:  LBB0_25: # %udiv-loop-exit2
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edx, %ecx
; WIN32-NEXT:    shldl $1, %ebx, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %esi, %ebx
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    leal (%ecx,%esi,2), %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:  LBB0_29: # %udiv-end1
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    xorl %esi, %eax
; WIN32-NEXT:    xorl %esi, %edx
; WIN32-NEXT:    xorl %esi, %ebx
; WIN32-NEXT:    xorl %esi, %ecx
; WIN32-NEXT:    subl %esi, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %esi, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %esi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %esi, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    subl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    sbbl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    sbbl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    sbbl %ecx, %edi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    subl %ecx, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    sbbl %ecx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    sbbl %ecx, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    sbbl %ecx, %ebx
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %ebx, %eax
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %edx, %esi
; WIN32-NEXT:    orl %eax, %esi
; WIN32-NEXT:    sete {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl %edi, %eax
; WIN32-NEXT:    orl %edi, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; WIN32-NEXT:    orl %ecx, %edx
; WIN32-NEXT:    sete %cl
; WIN32-NEXT:    testl %ebx, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB0_30
; WIN32-NEXT:  # %bb.31: # %udiv-end1
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    bsrl %edi, %ebx
; WIN32-NEXT:    xorl $31, %ebx
; WIN32-NEXT:    orl $32, %ebx
; WIN32-NEXT:    jmp LBB0_32
; WIN32-NEXT:  LBB0_30:
; WIN32-NEXT:    bsrl %ebx, %ebx
; WIN32-NEXT:    xorl $31, %ebx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:  LBB0_32: # %udiv-end1
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    testl %edx, %edx
; WIN32-NEXT:    jne LBB0_33
; WIN32-NEXT:  # %bb.34: # %udiv-end1
; WIN32-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    jmp LBB0_35
; WIN32-NEXT:  LBB0_33:
; WIN32-NEXT:    bsrl %edx, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:  LBB0_35: # %udiv-end1
; WIN32-NEXT:    movl %edi, %esi
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    jne LBB0_37
; WIN32-NEXT:  # %bb.36: # %udiv-end1
; WIN32-NEXT:    orl $64, %edx
; WIN32-NEXT:    movl %edx, %ebx
; WIN32-NEXT:  LBB0_37: # %udiv-end1
; WIN32-NEXT:    testl %eax, %eax
; WIN32-NEXT:    jne LBB0_38
; WIN32-NEXT:  # %bb.39: # %udiv-end1
; WIN32-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    jmp LBB0_40
; WIN32-NEXT:  LBB0_38:
; WIN32-NEXT:    bsrl %eax, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:  LBB0_40: # %udiv-end1
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    jne LBB0_41
; WIN32-NEXT:  # %bb.42: # %udiv-end1
; WIN32-NEXT:    bsrl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:    orl $32, %esi
; WIN32-NEXT:    jmp LBB0_43
; WIN32-NEXT:  LBB0_41:
; WIN32-NEXT:    bsrl %esi, %esi
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:  LBB0_43: # %udiv-end1
; WIN32-NEXT:    orb %cl, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    jne LBB0_45
; WIN32-NEXT:  # %bb.44: # %udiv-end1
; WIN32-NEXT:    orl $64, %esi
; WIN32-NEXT:    movl %esi, %edx
; WIN32-NEXT:  LBB0_45: # %udiv-end1
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    subl %edx, %ebx
; WIN32-NEXT:    movl $0, %edi
; WIN32-NEXT:    sbbl %edi, %edi
; WIN32-NEXT:    movl $0, %ecx
; WIN32-NEXT:    sbbl %ecx, %ecx
; WIN32-NEXT:    movl $0, %edx
; WIN32-NEXT:    sbbl %edx, %edx
; WIN32-NEXT:    cmpb $0, {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Reload
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB0_46
; WIN32-NEXT:  # %bb.47: # %select.false.sink8
; WIN32-NEXT:    movl $127, %eax
; WIN32-NEXT:    cmpl %ebx, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %edi, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %ecx, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %edx, %eax
; WIN32-NEXT:    setb %al
; WIN32-NEXT:  LBB0_48: # %select.end7
; WIN32-NEXT:    testb %al, %al
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    movl $0, %edx
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    jne LBB0_50
; WIN32-NEXT:  # %bb.49: # %select.end7
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, %edx
; WIN32-NEXT:  LBB0_50: # %select.end7
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB0_51
; WIN32-NEXT:  # %bb.57: # %select.end7
; WIN32-NEXT:    movl %ebx, %eax
; WIN32-NEXT:    xorl $127, %eax
; WIN32-NEXT:    orl %ecx, %eax
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edi, %ecx
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    je LBB0_58
; WIN32-NEXT:  # %bb.55: # %udiv-bb1
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ebx, %ecx
; WIN32-NEXT:    xorb $127, %cl
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    negb %al
; WIN32-NEXT:    movsbl %al, %eax
; WIN32-NEXT:    movl 200(%esp,%eax), %esi
; WIN32-NEXT:    movl 204(%esp,%eax), %edx
; WIN32-NEXT:    shldl %cl, %esi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 192(%esp,%eax), %edx
; WIN32-NEXT:    movl 196(%esp,%eax), %eax
; WIN32-NEXT:    shldl %cl, %eax, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl %cl, %edx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shll %cl, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl $1, %ebx
; WIN32-NEXT:    adcl $0, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    jb LBB0_56
; WIN32-NEXT:  # %bb.52: # %udiv-preheader
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ebx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    movzbl %al, %eax
; WIN32-NEXT:    movl 156(%esp,%eax), %edi
; WIN32-NEXT:    movl 152(%esp,%eax), %esi
; WIN32-NEXT:    movl %esi, %edx
; WIN32-NEXT:    movl %ebx, %ecx
; WIN32-NEXT:    shrdl %cl, %edi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 144(%esp,%eax), %edx
; WIN32-NEXT:    movl 148(%esp,%eax), %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shrdl %cl, %esi, %eax
; WIN32-NEXT:    shrl %cl, %edi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    shrdl %cl, %esi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    addl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    .p2align 4
; WIN32-NEXT:  LBB0_53: # %udiv-do-while
; WIN32-NEXT:    # =>This Inner Loop Header: Depth=1
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edx, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, %ebx
; WIN32-NEXT:    shldl $1, %eax, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %ebx
; WIN32-NEXT:    shldl $1, %ecx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edi, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    orl %edx, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl $1, %esi, %edi
; WIN32-NEXT:    orl %edx, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %ecx, %esi
; WIN32-NEXT:    orl %edx, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl %ecx, %ecx
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    cmpl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl %ebx, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    sarl $31, %ecx
; WIN32-NEXT:    movl %ecx, %esi
; WIN32-NEXT:    andl $1, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %edx
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %esi
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    movl %ecx, %edi
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; WIN32-NEXT:    andl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    subl %ecx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %edi, %ebx
; WIN32-NEXT:    movl %ebx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    sbbl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    addl $-1, %ebx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    adcl $-1, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %esi
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %esi, %ecx
; WIN32-NEXT:    movl %ebx, %esi
; WIN32-NEXT:    orl %edx, %esi
; WIN32-NEXT:    orl %ecx, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    jne LBB0_53
; WIN32-NEXT:  LBB0_54: # %udiv-loop-exit
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edx, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl $1, %esi, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    leal (%ecx,%eax,2), %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:  LBB0_58: # %udiv-end
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl 8(%ebp), %ecx
; WIN32-NEXT:    movl %eax, (%ecx)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, 4(%ecx)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, 8(%ecx)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, 12(%ecx)
; WIN32-NEXT:    movl %edx, %esi
; WIN32-NEXT:    imull {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    movl %edx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    mull %edi
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl %esi, %edx
; WIN32-NEXT:    imull %edi, %ecx
; WIN32-NEXT:    addl %edx, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    movl %ebx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    mull %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    imull %ebx, %edi
; WIN32-NEXT:    addl %edx, %edi
; WIN32-NEXT:    imull {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    addl %edi, %esi
; WIN32-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    adcl %ecx, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    movl %edi, %eax
; WIN32-NEXT:    mull %ebx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    mull %ebx
; WIN32-NEXT:    movl %eax, %ecx
; WIN32-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    adcl $0, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edi, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    mull %ebx
; WIN32-NEXT:    movl %edx, %edi
; WIN32-NEXT:    addl %ecx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; WIN32-NEXT:    setb %cl
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    mull %ebx
; WIN32-NEXT:    addl %edi, %eax
; WIN32-NEXT:    movzbl %cl, %ecx
; WIN32-NEXT:    adcl %ecx, %edx
; WIN32-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; WIN32-NEXT:    adcl %esi, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    subl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl %eax, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    sbbl %edx, %ebx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    xorl %eax, %ebx
; WIN32-NEXT:    xorl %eax, %ecx
; WIN32-NEXT:    xorl %eax, %esi
; WIN32-NEXT:    xorl %eax, %edi
; WIN32-NEXT:    subl %eax, %edi
; WIN32-NEXT:    sbbl %eax, %esi
; WIN32-NEXT:    sbbl %eax, %ecx
; WIN32-NEXT:    sbbl %eax, %ebx
; WIN32-NEXT:    movl 12(%ebp), %eax
; WIN32-NEXT:    movl %edi, (%eax)
; WIN32-NEXT:    movl %esi, 4(%eax)
; WIN32-NEXT:    movl %ecx, 8(%eax)
; WIN32-NEXT:    movl %ebx, 12(%eax)
; WIN32-NEXT:    leal -12(%ebp), %esp
; WIN32-NEXT:    popl %esi
; WIN32-NEXT:    popl %edi
; WIN32-NEXT:    popl %ebx
; WIN32-NEXT:    popl %ebp
; WIN32-NEXT:    retl
; WIN32-NEXT:  LBB0_17:
; WIN32-NEXT:    movb $1, %al
; WIN32-NEXT:    jmp LBB0_19
; WIN32-NEXT:  LBB0_27:
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    jmp LBB0_25
; WIN32-NEXT:  LBB0_46:
; WIN32-NEXT:    movb $1, %al
; WIN32-NEXT:    jmp LBB0_48
; WIN32-NEXT:  LBB0_56:
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    jmp LBB0_54
; WIN32-NEXT:  LBB0_22:
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    jmp LBB0_29
; WIN32-NEXT:  LBB0_51:
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    jmp LBB0_58
  %q = sdiv i128 %n, %d
  %r = srem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}

define void @udivrem_i128(ptr %q_out, ptr %r_out, i128 %n, i128 %d) {
; LINUX-X86-LABEL: udivrem_i128:
; LINUX-X86:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    pushl %ebp
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 8
; LINUX-X86-NEXT:    pushl %ebx
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 12
; LINUX-X86-NEXT:    pushl %edi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 16
; LINUX-X86-NEXT:    pushl %esi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 20
; LINUX-X86-NEXT:    subl $236, %esp
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 256
; LINUX-X86-NEXT:    .cfi_offset %esi, -20
; LINUX-X86-NEXT:    .cfi_offset %edi, -16
; LINUX-X86-NEXT:    .cfi_offset %ebx, -12
; LINUX-X86-NEXT:    .cfi_offset %ebp, -8
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    movl %esi, %eax
; LINUX-X86-NEXT:    orl %ebp, %eax
; LINUX-X86-NEXT:    orl %ebx, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; LINUX-X86-NEXT:    sete %al
; LINUX-X86-NEXT:    movl %edi, %ecx
; LINUX-X86-NEXT:    orl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    orl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    orl %ecx, %edx
; LINUX-X86-NEXT:    sete %cl
; LINUX-X86-NEXT:    testl %ebp, %ebp
; LINUX-X86-NEXT:    jne .LBB1_2
; LINUX-X86-NEXT:  # %bb.1: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl %ebx, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    jmp .LBB1_3
; LINUX-X86-NEXT:  .LBB1_2:
; LINUX-X86-NEXT:    bsrl %ebp, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:  .LBB1_3: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    movl %ebx, %ebp
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    testl %esi, %esi
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    jne .LBB1_5
; LINUX-X86-NEXT:  # %bb.4: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    jmp .LBB1_6
; LINUX-X86-NEXT:  .LBB1_5:
; LINUX-X86-NEXT:    bsrl %esi, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:  .LBB1_6: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    movl %ebp, %esi
; LINUX-X86-NEXT:    orl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    jne .LBB1_8
; LINUX-X86-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    orl $64, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:  .LBB1_8: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    testl %ebx, %ebx
; LINUX-X86-NEXT:    jne .LBB1_11
; LINUX-X86-NEXT:  # %bb.9: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    testl %edi, %edi
; LINUX-X86-NEXT:    je .LBB1_12
; LINUX-X86-NEXT:  .LBB1_10:
; LINUX-X86-NEXT:    bsrl %edi, %esi
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:    jmp .LBB1_13
; LINUX-X86-NEXT:  .LBB1_11:
; LINUX-X86-NEXT:    bsrl %ebx, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    testl %edi, %edi
; LINUX-X86-NEXT:    jne .LBB1_10
; LINUX-X86-NEXT:  .LBB1_12: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    bsrl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:    orl $32, %esi
; LINUX-X86-NEXT:  .LBB1_13: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    orb %cl, %al
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    orl %ebx, %ecx
; LINUX-X86-NEXT:    jne .LBB1_15
; LINUX-X86-NEXT:  # %bb.14: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    orl $64, %esi
; LINUX-X86-NEXT:    movl %esi, %edx
; LINUX-X86-NEXT:  .LBB1_15: # %_udiv-special-cases_udiv-special-cases
; LINUX-X86-NEXT:    xorl %ebp, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    subl %edx, %ecx
; LINUX-X86-NEXT:    movl $0, %edx
; LINUX-X86-NEXT:    sbbl %edx, %edx
; LINUX-X86-NEXT:    movl $0, %ebx
; LINUX-X86-NEXT:    sbbl %ebx, %ebx
; LINUX-X86-NEXT:    movl $0, %edi
; LINUX-X86-NEXT:    sbbl %edi, %edi
; LINUX-X86-NEXT:    testb %al, %al
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    jne .LBB1_52
; LINUX-X86-NEXT:  # %bb.16: # %select.false.sink
; LINUX-X86-NEXT:    movl $127, %eax
; LINUX-X86-NEXT:    cmpl %ecx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %edx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %ebx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %edi, %eax
; LINUX-X86-NEXT:    setb %al
; LINUX-X86-NEXT:  .LBB1_17: # %select.end
; LINUX-X86-NEXT:    movl %edi, %edx
; LINUX-X86-NEXT:    testb %al, %al
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    movl $0, %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; LINUX-X86-NEXT:    jne .LBB1_19
; LINUX-X86-NEXT:  # %bb.18: # %select.end
; LINUX-X86-NEXT:    movl %esi, %ebp
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    movl %ebx, %ecx
; LINUX-X86-NEXT:  .LBB1_19: # %select.end
; LINUX-X86-NEXT:    movl %edx, %esi
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    jne .LBB1_25
; LINUX-X86-NEXT:  # %bb.20: # %select.end
; LINUX-X86-NEXT:    movl %edx, %eax
; LINUX-X86-NEXT:    xorl $127, %eax
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    movl %edi, %ecx
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %esi, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    je .LBB1_26
; LINUX-X86-NEXT:  # %bb.21: # %udiv-bb15
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %ebx, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    xorb $127, %cl
; LINUX-X86-NEXT:    movl %ecx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    negb %al
; LINUX-X86-NEXT:    movsbl %al, %eax
; LINUX-X86-NEXT:    movl 216(%esp,%eax), %esi
; LINUX-X86-NEXT:    movl 220(%esp,%eax), %ebp
; LINUX-X86-NEXT:    shldl %cl, %esi, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl 208(%esp,%eax), %ebx
; LINUX-X86-NEXT:    movl 212(%esp,%eax), %ebp
; LINUX-X86-NEXT:    shldl %cl, %ebp, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl %cl, %ebx, %ebp
; LINUX-X86-NEXT:    shll %cl, %ebx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl $1, %edx
; LINUX-X86-NEXT:    adcl $0, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jb .LBB1_53
; LINUX-X86-NEXT:  # %bb.22: # %udiv-preheader4
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %edx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    movzbl %al, %eax
; LINUX-X86-NEXT:    movl 172(%esp,%eax), %esi
; LINUX-X86-NEXT:    movl 168(%esp,%eax), %ebx
; LINUX-X86-NEXT:    movl %ebx, %edi
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    shrdl %cl, %esi, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    movl 160(%esp,%eax), %edx
; LINUX-X86-NEXT:    movl 164(%esp,%eax), %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shrdl %cl, %ebx, %edi
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shrl %cl, %esi
; LINUX-X86-NEXT:    movl %esi, %ebx
; LINUX-X86-NEXT:    # kill: def $cl killed $cl killed $ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    shrdl %cl, %eax, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    addl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    .p2align 4
; LINUX-X86-NEXT:  .LBB1_23: # %udiv-do-while3
; LINUX-X86-NEXT:    # =>This Inner Loop Header: Depth=1
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edx, %ebx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edi, %esi
; LINUX-X86-NEXT:    shldl $1, %edi, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edi, %esi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %ebx, %edi
; LINUX-X86-NEXT:    shldl $1, %eax, %ebx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    orl %edx, %ebx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl $1, %ebp, %eax
; LINUX-X86-NEXT:    orl %edx, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl $1, %ecx, %ebp
; LINUX-X86-NEXT:    orl %edx, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl %ecx, %ecx
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    cmpl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %esi, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Folded Reload
; LINUX-X86-NEXT:    sarl $31, %ebp
; LINUX-X86-NEXT:    movl %ebp, %eax
; LINUX-X86-NEXT:    andl $1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl %ebp, %ecx
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl %ebp, %ebx
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    movl %ebp, %eax
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %ebp
; LINUX-X86-NEXT:    subl %ebp, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %eax, %esi
; LINUX-X86-NEXT:    movl %esi, %edi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ecx, %ebx
; LINUX-X86-NEXT:    addl $-1, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    adcl $-1, %esi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %ecx
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %ecx, %eax
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    orl %esi, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    jne .LBB1_23
; LINUX-X86-NEXT:  .LBB1_24: # %udiv-loop-exit2
; LINUX-X86-NEXT:    shldl $1, %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    shldl $1, %ebp, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl $1, %ecx, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    leal (%eax,%ecx,2), %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:  .LBB1_25: # %udiv-end1
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:  .LBB1_26: # %udiv-end1
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %ecx, %edx
; LINUX-X86-NEXT:    movl %ebx, %edi
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    orl %ebx, %eax
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; LINUX-X86-NEXT:    orl %ebp, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    sete {{[-0-9]+}}(%e{{[sb]}}p) # 1-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    orl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl %edx, %esi
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    orl %edi, %edx
; LINUX-X86-NEXT:    orl %ecx, %edx
; LINUX-X86-NEXT:    sete %cl
; LINUX-X86-NEXT:    testl %ebp, %ebp
; LINUX-X86-NEXT:    jne .LBB1_28
; LINUX-X86-NEXT:  # %bb.27: # %udiv-end1
; LINUX-X86-NEXT:    bsrl %ebx, %edi
; LINUX-X86-NEXT:    xorl $31, %edi
; LINUX-X86-NEXT:    orl $32, %edi
; LINUX-X86-NEXT:    jmp .LBB1_29
; LINUX-X86-NEXT:  .LBB1_28:
; LINUX-X86-NEXT:    bsrl %ebp, %edi
; LINUX-X86-NEXT:    xorl $31, %edi
; LINUX-X86-NEXT:  .LBB1_29: # %udiv-end1
; LINUX-X86-NEXT:    movl %ebx, %ebp
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    testl %edx, %edx
; LINUX-X86-NEXT:    movl %eax, %ebx
; LINUX-X86-NEXT:    movl %esi, %eax
; LINUX-X86-NEXT:    jne .LBB1_31
; LINUX-X86-NEXT:  # %bb.30: # %udiv-end1
; LINUX-X86-NEXT:    bsrl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    jmp .LBB1_32
; LINUX-X86-NEXT:  .LBB1_31:
; LINUX-X86-NEXT:    bsrl %edx, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:  .LBB1_32: # %udiv-end1
; LINUX-X86-NEXT:    movl %ebp, %esi
; LINUX-X86-NEXT:    orl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    jne .LBB1_34
; LINUX-X86-NEXT:  # %bb.33: # %udiv-end1
; LINUX-X86-NEXT:    orl $64, %edx
; LINUX-X86-NEXT:    movl %edx, %edi
; LINUX-X86-NEXT:  .LBB1_34: # %udiv-end1
; LINUX-X86-NEXT:    testl %ebx, %ebx
; LINUX-X86-NEXT:    jne .LBB1_37
; LINUX-X86-NEXT:  # %bb.35: # %udiv-end1
; LINUX-X86-NEXT:    bsrl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    orl $32, %edx
; LINUX-X86-NEXT:    testl %eax, %eax
; LINUX-X86-NEXT:    je .LBB1_38
; LINUX-X86-NEXT:  .LBB1_36:
; LINUX-X86-NEXT:    bsrl %eax, %esi
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:    jmp .LBB1_39
; LINUX-X86-NEXT:  .LBB1_37:
; LINUX-X86-NEXT:    bsrl %ebx, %edx
; LINUX-X86-NEXT:    xorl $31, %edx
; LINUX-X86-NEXT:    testl %eax, %eax
; LINUX-X86-NEXT:    jne .LBB1_36
; LINUX-X86-NEXT:  .LBB1_38: # %udiv-end1
; LINUX-X86-NEXT:    bsrl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    xorl $31, %esi
; LINUX-X86-NEXT:    orl $32, %esi
; LINUX-X86-NEXT:  .LBB1_39: # %udiv-end1
; LINUX-X86-NEXT:    movzbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 1-byte Folded Reload
; LINUX-X86-NEXT:    orb %cl, %al
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    orl %ebx, %ecx
; LINUX-X86-NEXT:    jne .LBB1_41
; LINUX-X86-NEXT:  # %bb.40: # %udiv-end1
; LINUX-X86-NEXT:    orl $64, %esi
; LINUX-X86-NEXT:    movl %esi, %edx
; LINUX-X86-NEXT:  .LBB1_41: # %udiv-end1
; LINUX-X86-NEXT:    xorl %ebx, %ebx
; LINUX-X86-NEXT:    subl %edx, %edi
; LINUX-X86-NEXT:    movl %edi, %edx
; LINUX-X86-NEXT:    movl $0, %edi
; LINUX-X86-NEXT:    sbbl %edi, %edi
; LINUX-X86-NEXT:    movl $0, %ecx
; LINUX-X86-NEXT:    sbbl %ecx, %ecx
; LINUX-X86-NEXT:    movl $0, %ebp
; LINUX-X86-NEXT:    sbbl %ebp, %ebp
; LINUX-X86-NEXT:    testb %al, %al
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    jne .LBB1_54
; LINUX-X86-NEXT:  # %bb.42: # %select.false.sink8
; LINUX-X86-NEXT:    movl $127, %eax
; LINUX-X86-NEXT:    cmpl %edx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %edi, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %ecx, %eax
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    sbbl %ebp, %eax
; LINUX-X86-NEXT:    setb %al
; LINUX-X86-NEXT:  .LBB1_43: # %select.end7
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    testb %al, %al
; LINUX-X86-NEXT:    movl $0, %eax
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl $0, %ebp
; LINUX-X86-NEXT:    jne .LBB1_45
; LINUX-X86-NEXT:  # %bb.44: # %select.end7
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; LINUX-X86-NEXT:  .LBB1_45: # %select.end7
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    jne .LBB1_57
; LINUX-X86-NEXT:  # %bb.46: # %select.end7
; LINUX-X86-NEXT:    movl %edx, %eax
; LINUX-X86-NEXT:    xorl $127, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    orl %ebx, %eax
; LINUX-X86-NEXT:    movl %edi, %ecx
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    movl %ebp, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    je .LBB1_51
; LINUX-X86-NEXT:  # %bb.47: # %udiv-bb1
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; LINUX-X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %eax, %esi
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, %ecx
; LINUX-X86-NEXT:    xorb $127, %cl
; LINUX-X86-NEXT:    movl %ecx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    negb %al
; LINUX-X86-NEXT:    movsbl %al, %eax
; LINUX-X86-NEXT:    movl 152(%esp,%eax), %edx
; LINUX-X86-NEXT:    movl 156(%esp,%eax), %ebp
; LINUX-X86-NEXT:    shldl %cl, %edx, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl 144(%esp,%eax), %ebp
; LINUX-X86-NEXT:    movl 148(%esp,%eax), %eax
; LINUX-X86-NEXT:    shldl %cl, %eax, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl %cl, %ebp, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shll %cl, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl $1, %edx
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    adcl $0, %ebx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jb .LBB1_55
; LINUX-X86-NEXT:  # %bb.48: # %udiv-preheader
; LINUX-X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; LINUX-X86-NEXT:    movl %edx, %eax
; LINUX-X86-NEXT:    shrb $3, %al
; LINUX-X86-NEXT:    andb $12, %al
; LINUX-X86-NEXT:    movzbl %al, %eax
; LINUX-X86-NEXT:    movl 108(%esp,%eax), %ebp
; LINUX-X86-NEXT:    movl 104(%esp,%eax), %ebx
; LINUX-X86-NEXT:    movl %ebx, %esi
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    shrdl %cl, %ebp, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl 96(%esp,%eax), %esi
; LINUX-X86-NEXT:    movl 100(%esp,%eax), %eax
; LINUX-X86-NEXT:    movl %eax, %edi
; LINUX-X86-NEXT:    shrdl %cl, %ebx, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shrl %cl, %ebp
; LINUX-X86-NEXT:    shrdl %cl, %eax, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    addl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    adcl $-1, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    .p2align 4
; LINUX-X86-NEXT:  .LBB1_49: # %udiv-do-while
; LINUX-X86-NEXT:    # =>This Inner Loop Header: Depth=1
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edi, %ebp
; LINUX-X86-NEXT:    movl %ebp, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %ecx, %edi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %ebx, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edx, %ebx
; LINUX-X86-NEXT:    shldl $1, %eax, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    orl %ebp, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    shldl $1, %esi, %eax
; LINUX-X86-NEXT:    orl %ebp, %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %eax, %esi
; LINUX-X86-NEXT:    orl %ebp, %esi
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl %eax, %eax
; LINUX-X86-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    cmpl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ecx, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %edi, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    sarl $31, %eax
; LINUX-X86-NEXT:    movl %eax, %edx
; LINUX-X86-NEXT:    andl $1, %edx
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    movl %eax, %esi
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    movl %eax, %ebp
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %ebp
; LINUX-X86-NEXT:    movl %eax, %edx
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %edx
; LINUX-X86-NEXT:    andl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    subl %eax, %ebx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    sbbl %edx, %ecx
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %ebp, %edi
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    sbbl %esi, %ebp
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    addl $-1, %edx
; LINUX-X86-NEXT:    adcl $-1, %edi
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %ebx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    adcl $-1, %ecx
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %ecx, %eax
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    orl %ebx, %ecx
; LINUX-X86-NEXT:    orl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    jne .LBB1_49
; LINUX-X86-NEXT:  .LBB1_50: # %udiv-loop-exit
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %eax, %edx
; LINUX-X86-NEXT:    shldl $1, %esi, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    shldl $1, %edi, %esi
; LINUX-X86-NEXT:    movl %eax, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    leal (%eax,%edi,2), %eax
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %ecx, %edi
; LINUX-X86-NEXT:  .LBB1_51: # %udiv-end
; LINUX-X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    movl %eax, (%ecx)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, 4(%ecx)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, 8(%ecx)
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl %eax, 12(%ecx)
; LINUX-X86-NEXT:    movl %edi, %esi
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; LINUX-X86-NEXT:    imull %ebp, %esi
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; LINUX-X86-NEXT:    mull %edi
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    addl %esi, %edx
; LINUX-X86-NEXT:    imull %edi, %ecx
; LINUX-X86-NEXT:    addl %edx, %ecx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    movl %esi, %eax
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    mull %ebx
; LINUX-X86-NEXT:    movl %eax, %edi
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    imull %esi, %eax
; LINUX-X86-NEXT:    addl %edx, %eax
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebp # 4-byte Reload
; LINUX-X86-NEXT:    imull %ebp, %ebx
; LINUX-X86-NEXT:    addl %eax, %ebx
; LINUX-X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    adcl %ecx, %ebx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    mull %esi
; LINUX-X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    mull %esi
; LINUX-X86-NEXT:    movl %edx, %ecx
; LINUX-X86-NEXT:    movl %eax, %esi
; LINUX-X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; LINUX-X86-NEXT:    adcl $0, %ecx
; LINUX-X86-NEXT:    movl %edi, %eax
; LINUX-X86-NEXT:    mull %ebp
; LINUX-X86-NEXT:    movl %edx, %edi
; LINUX-X86-NEXT:    addl %esi, %eax
; LINUX-X86-NEXT:    movl %eax, %esi
; LINUX-X86-NEXT:    adcl %ecx, %edi
; LINUX-X86-NEXT:    setb %cl
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    mull %ebp
; LINUX-X86-NEXT:    addl %edi, %eax
; LINUX-X86-NEXT:    movzbl %cl, %ecx
; LINUX-X86-NEXT:    adcl %ecx, %edx
; LINUX-X86-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; LINUX-X86-NEXT:    adcl %ebx, %edx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %edi
; LINUX-X86-NEXT:    subl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; LINUX-X86-NEXT:    sbbl %esi, %ecx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; LINUX-X86-NEXT:    sbbl %eax, %esi
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebx
; LINUX-X86-NEXT:    sbbl %edx, %ebx
; LINUX-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; LINUX-X86-NEXT:    movl %edi, (%eax)
; LINUX-X86-NEXT:    movl %ecx, 4(%eax)
; LINUX-X86-NEXT:    movl %esi, 8(%eax)
; LINUX-X86-NEXT:    movl %ebx, 12(%eax)
; LINUX-X86-NEXT:    addl $236, %esp
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 20
; LINUX-X86-NEXT:    popl %esi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 16
; LINUX-X86-NEXT:    popl %edi
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 12
; LINUX-X86-NEXT:    popl %ebx
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 8
; LINUX-X86-NEXT:    popl %ebp
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 4
; LINUX-X86-NEXT:    retl
; LINUX-X86-NEXT:  .LBB1_52:
; LINUX-X86-NEXT:    .cfi_def_cfa_offset 256
; LINUX-X86-NEXT:    movb $1, %al
; LINUX-X86-NEXT:    jmp .LBB1_17
; LINUX-X86-NEXT:  .LBB1_53:
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jmp .LBB1_24
; LINUX-X86-NEXT:  .LBB1_54:
; LINUX-X86-NEXT:    movb $1, %al
; LINUX-X86-NEXT:    jmp .LBB1_43
; LINUX-X86-NEXT:  .LBB1_55:
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; LINUX-X86-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; LINUX-X86-NEXT:    jmp .LBB1_50
; LINUX-X86-NEXT:  .LBB1_57:
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; LINUX-X86-NEXT:    movl %ebp, %edx
; LINUX-X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; LINUX-X86-NEXT:    jmp .LBB1_51
;
; WIN32-LABEL: udivrem_i128:
; WIN32:       # %bb.0: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    pushl %ebp
; WIN32-NEXT:    movl %esp, %ebp
; WIN32-NEXT:    pushl %ebx
; WIN32-NEXT:    pushl %edi
; WIN32-NEXT:    pushl %esi
; WIN32-NEXT:    andl $-16, %esp
; WIN32-NEXT:    subl $240, %esp
; WIN32-NEXT:    movl 48(%ebp), %ebx
; WIN32-NEXT:    movl 40(%ebp), %ecx
; WIN32-NEXT:    movl 52(%ebp), %edi
; WIN32-NEXT:    movl 44(%ebp), %esi
; WIN32-NEXT:    movl %esi, %eax
; WIN32-NEXT:    orl %edi, %eax
; WIN32-NEXT:    orl %ebx, %ecx
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    sete %al
; WIN32-NEXT:    movl 28(%ebp), %ecx
; WIN32-NEXT:    orl 36(%ebp), %ecx
; WIN32-NEXT:    movl 24(%ebp), %edx
; WIN32-NEXT:    orl 32(%ebp), %edx
; WIN32-NEXT:    orl %ecx, %edx
; WIN32-NEXT:    sete %cl
; WIN32-NEXT:    testl %edi, %edi
; WIN32-NEXT:    jne LBB1_1
; WIN32-NEXT:  # %bb.2: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl %ebx, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    jmp LBB1_3
; WIN32-NEXT:  LBB1_1:
; WIN32-NEXT:    bsrl %edi, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:  LBB1_3: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    jne LBB1_4
; WIN32-NEXT:  # %bb.5: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl 40(%ebp), %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    jmp LBB1_6
; WIN32-NEXT:  LBB1_4:
; WIN32-NEXT:    bsrl %esi, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:  LBB1_6: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    movl %ebx, %esi
; WIN32-NEXT:    orl %edi, %esi
; WIN32-NEXT:    jne LBB1_8
; WIN32-NEXT:  # %bb.7: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    orl $64, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:  LBB1_8: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    movl 36(%ebp), %edi
; WIN32-NEXT:    testl %edi, %edi
; WIN32-NEXT:    movl 28(%ebp), %esi
; WIN32-NEXT:    jne LBB1_9
; WIN32-NEXT:  # %bb.10: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl 32(%ebp), %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    je LBB1_13
; WIN32-NEXT:  LBB1_12:
; WIN32-NEXT:    bsrl %esi, %esi
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:    jmp LBB1_14
; WIN32-NEXT:  LBB1_9:
; WIN32-NEXT:    bsrl %edi, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    jne LBB1_12
; WIN32-NEXT:  LBB1_13: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    bsrl 24(%ebp), %esi
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:    orl $32, %esi
; WIN32-NEXT:  LBB1_14: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    orb %cl, %al
; WIN32-NEXT:    movl 32(%ebp), %ecx
; WIN32-NEXT:    orl %edi, %ecx
; WIN32-NEXT:    jne LBB1_16
; WIN32-NEXT:  # %bb.15: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    orl $64, %esi
; WIN32-NEXT:    movl %esi, %edx
; WIN32-NEXT:  LBB1_16: # %_udiv-special-cases_udiv-special-cases
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    subl %edx, %ecx
; WIN32-NEXT:    movl $0, %esi
; WIN32-NEXT:    sbbl %esi, %esi
; WIN32-NEXT:    movl $0, %edi
; WIN32-NEXT:    sbbl %edi, %edi
; WIN32-NEXT:    movl $0, %ebx
; WIN32-NEXT:    sbbl %ebx, %ebx
; WIN32-NEXT:    testb %al, %al
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB1_17
; WIN32-NEXT:  # %bb.18: # %select.false.sink
; WIN32-NEXT:    movl $127, %eax
; WIN32-NEXT:    cmpl %ecx, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %esi, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    movl %edi, %ecx
; WIN32-NEXT:    sbbl %edi, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %ebx, %eax
; WIN32-NEXT:    setb %al
; WIN32-NEXT:  LBB1_19: # %select.end
; WIN32-NEXT:    movl 28(%ebp), %edx
; WIN32-NEXT:    movl %ebx, %edi
; WIN32-NEXT:    movl %edx, %ebx
; WIN32-NEXT:    movl 32(%ebp), %esi
; WIN32-NEXT:    testb %al, %al
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    movl $0, %edx
; WIN32-NEXT:    jne LBB1_21
; WIN32-NEXT:  # %bb.20: # %select.end
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 24(%ebp), %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, %eax
; WIN32-NEXT:    movl 36(%ebp), %edx
; WIN32-NEXT:  LBB1_21: # %select.end
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB1_22
; WIN32-NEXT:  # %bb.28: # %select.end
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %edx, %eax
; WIN32-NEXT:    xorl $127, %eax
; WIN32-NEXT:    orl %ecx, %eax
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    orl %edi, %ecx
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    movl 36(%ebp), %ecx
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    je LBB1_29
; WIN32-NEXT:  # %bb.26: # %udiv-bb15
; WIN32-NEXT:    movl 24(%ebp), %eax
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ebx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %edx, %ecx
; WIN32-NEXT:    xorb $127, %cl
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    negb %al
; WIN32-NEXT:    movsbl %al, %eax
; WIN32-NEXT:    movl 216(%esp,%eax), %edx
; WIN32-NEXT:    movl 220(%esp,%eax), %edi
; WIN32-NEXT:    shldl %cl, %edx, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, %edi
; WIN32-NEXT:    movl 208(%esp,%eax), %esi
; WIN32-NEXT:    movl 212(%esp,%eax), %eax
; WIN32-NEXT:    shldl %cl, %eax, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    shldl %cl, %esi, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shll %cl, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl $1, %edx
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    jb LBB1_27
; WIN32-NEXT:  # %bb.23: # %udiv-preheader4
; WIN32-NEXT:    movl 24(%ebp), %eax
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ebx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl 36(%ebp), %eax
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %edx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    movzbl %al, %eax
; WIN32-NEXT:    movl 172(%esp,%eax), %esi
; WIN32-NEXT:    movl %edx, %ecx
; WIN32-NEXT:    movl 168(%esp,%eax), %edx
; WIN32-NEXT:    movl %edx, %edi
; WIN32-NEXT:    shrdl %cl, %esi, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 160(%esp,%eax), %ebx
; WIN32-NEXT:    movl 164(%esp,%eax), %edi
; WIN32-NEXT:    movl %edi, %eax
; WIN32-NEXT:    shrdl %cl, %edx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shrl %cl, %esi
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    # kill: def $cl killed $cl killed $ecx
; WIN32-NEXT:    shrdl %cl, %edi, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 40(%ebp), %eax
; WIN32-NEXT:    addl $-1, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 44(%ebp), %eax
; WIN32-NEXT:    adcl $-1, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 48(%ebp), %ecx
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 52(%ebp), %ecx
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    .p2align 4
; WIN32-NEXT:  LBB1_24: # %udiv-do-while3
; WIN32-NEXT:    # =>This Inner Loop Header: Depth=1
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %ebx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edi, %ebx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %esi, %edi
; WIN32-NEXT:    shldl $1, %ecx, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    orl %eax, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl $1, %edx, %ecx
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %ecx, %edx
; WIN32-NEXT:    orl %eax, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl %ecx, %ecx
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    cmpl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl %ebx, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    sarl $31, %ecx
; WIN32-NEXT:    movl %ecx, %edx
; WIN32-NEXT:    andl $1, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    andl 52(%ebp), %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %esi
; WIN32-NEXT:    andl 48(%ebp), %esi
; WIN32-NEXT:    movl %ecx, %edx
; WIN32-NEXT:    andl 44(%ebp), %edx
; WIN32-NEXT:    andl 40(%ebp), %ecx
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    subl %ecx, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %edx, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    sbbl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    addl $-1, %edx
; WIN32-NEXT:    adcl $-1, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %edi
; WIN32-NEXT:    adcl $-1, %ebx
; WIN32-NEXT:    movl %eax, %ecx
; WIN32-NEXT:    orl %ebx, %ecx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %edi, %edx
; WIN32-NEXT:    orl %ecx, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    jne LBB1_24
; WIN32-NEXT:  LBB1_25: # %udiv-loop-exit2
; WIN32-NEXT:    shldl $1, %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    shldl $1, %edx, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    leal (%ecx,%eax,2), %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 36(%ebp), %ecx
; WIN32-NEXT:    movl 28(%ebp), %ebx
; WIN32-NEXT:  LBB1_29: # %udiv-end1
; WIN32-NEXT:    movl 40(%ebp), %eax
; WIN32-NEXT:    movl 48(%ebp), %esi
; WIN32-NEXT:    orl %esi, %eax
; WIN32-NEXT:    movl %ebx, %edx
; WIN32-NEXT:    movl %ecx, %ebx
; WIN32-NEXT:    movl 44(%ebp), %ecx
; WIN32-NEXT:    movl 52(%ebp), %edi
; WIN32-NEXT:    orl %edi, %ecx
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    sete %al
; WIN32-NEXT:    movl 24(%ebp), %ecx
; WIN32-NEXT:    orl 32(%ebp), %ecx
; WIN32-NEXT:    orl %ebx, %edx
; WIN32-NEXT:    orl %ecx, %edx
; WIN32-NEXT:    sete %cl
; WIN32-NEXT:    testl %edi, %edi
; WIN32-NEXT:    jne LBB1_30
; WIN32-NEXT:  # %bb.31: # %udiv-end1
; WIN32-NEXT:    bsrl %esi, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    jmp LBB1_32
; WIN32-NEXT:  LBB1_30:
; WIN32-NEXT:    bsrl %edi, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:  LBB1_32: # %udiv-end1
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, %ebx
; WIN32-NEXT:    movl 44(%ebp), %edx
; WIN32-NEXT:    testl %edx, %edx
; WIN32-NEXT:    movl 40(%ebp), %esi
; WIN32-NEXT:    jne LBB1_33
; WIN32-NEXT:  # %bb.34: # %udiv-end1
; WIN32-NEXT:    bsrl %esi, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    jmp LBB1_35
; WIN32-NEXT:  LBB1_33:
; WIN32-NEXT:    bsrl %edx, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:  LBB1_35: # %udiv-end1
; WIN32-NEXT:    movl %ebx, %esi
; WIN32-NEXT:    orl %edi, %esi
; WIN32-NEXT:    jne LBB1_37
; WIN32-NEXT:  # %bb.36: # %udiv-end1
; WIN32-NEXT:    orl $64, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:  LBB1_37: # %udiv-end1
; WIN32-NEXT:    movl 36(%ebp), %edx
; WIN32-NEXT:    testl %edx, %edx
; WIN32-NEXT:    movl 28(%ebp), %esi
; WIN32-NEXT:    jne LBB1_38
; WIN32-NEXT:  # %bb.39: # %udiv-end1
; WIN32-NEXT:    bsrl 32(%ebp), %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    orl $32, %edx
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    je LBB1_42
; WIN32-NEXT:  LBB1_41:
; WIN32-NEXT:    bsrl %esi, %esi
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:    jmp LBB1_43
; WIN32-NEXT:  LBB1_38:
; WIN32-NEXT:    bsrl %edx, %edx
; WIN32-NEXT:    xorl $31, %edx
; WIN32-NEXT:    testl %esi, %esi
; WIN32-NEXT:    jne LBB1_41
; WIN32-NEXT:  LBB1_42: # %udiv-end1
; WIN32-NEXT:    bsrl 24(%ebp), %esi
; WIN32-NEXT:    xorl $31, %esi
; WIN32-NEXT:    orl $32, %esi
; WIN32-NEXT:  LBB1_43: # %udiv-end1
; WIN32-NEXT:    orb %cl, %al
; WIN32-NEXT:    movl 32(%ebp), %ecx
; WIN32-NEXT:    orl 36(%ebp), %ecx
; WIN32-NEXT:    jne LBB1_45
; WIN32-NEXT:  # %bb.44: # %udiv-end1
; WIN32-NEXT:    orl $64, %esi
; WIN32-NEXT:    movl %esi, %edx
; WIN32-NEXT:  LBB1_45: # %udiv-end1
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    subl %edx, %ecx
; WIN32-NEXT:    movl $0, %edx
; WIN32-NEXT:    sbbl %edx, %edx
; WIN32-NEXT:    movl $0, %esi
; WIN32-NEXT:    sbbl %esi, %esi
; WIN32-NEXT:    movl $0, %edi
; WIN32-NEXT:    sbbl %edi, %edi
; WIN32-NEXT:    testb %al, %al
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB1_46
; WIN32-NEXT:  # %bb.47: # %select.false.sink8
; WIN32-NEXT:    movl $127, %eax
; WIN32-NEXT:    cmpl %ecx, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %edx, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %esi, %eax
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    sbbl %edi, %eax
; WIN32-NEXT:    setb %al
; WIN32-NEXT:  LBB1_48: # %select.end7
; WIN32-NEXT:    movl 28(%ebp), %ecx
; WIN32-NEXT:    movl 32(%ebp), %edx
; WIN32-NEXT:    movl %edi, %esi
; WIN32-NEXT:    testb %al, %al
; WIN32-NEXT:    movl $0, %edi
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl $0, %eax
; WIN32-NEXT:    jne LBB1_50
; WIN32-NEXT:  # %bb.49: # %select.end7
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 24(%ebp), %edi
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 36(%ebp), %eax
; WIN32-NEXT:  LBB1_50: # %select.end7
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    jne LBB1_51
; WIN32-NEXT:  # %bb.57: # %select.end7
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, %edi
; WIN32-NEXT:    xorl $127, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    orl %ebx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    orl %esi, %ecx
; WIN32-NEXT:    orl %eax, %ecx
; WIN32-NEXT:    movl 36(%ebp), %ecx
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    je LBB1_58
; WIN32-NEXT:  # %bb.55: # %udiv-bb1
; WIN32-NEXT:    movl 24(%ebp), %eax
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl 28(%ebp), %edx
; WIN32-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl 32(%ebp), %esi
; WIN32-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %edi, %eax
; WIN32-NEXT:    movl %eax, %ecx
; WIN32-NEXT:    movl %edi, %esi
; WIN32-NEXT:    xorb $127, %cl
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    negb %al
; WIN32-NEXT:    movsbl %al, %eax
; WIN32-NEXT:    movl 152(%esp,%eax), %edx
; WIN32-NEXT:    movl 156(%esp,%eax), %edi
; WIN32-NEXT:    shldl %cl, %edx, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 144(%esp,%eax), %edi
; WIN32-NEXT:    movl 148(%esp,%eax), %eax
; WIN32-NEXT:    shldl %cl, %eax, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl %cl, %edi, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shll %cl, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl $1, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    adcl $0, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    adcl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl 36(%ebp), %eax
; WIN32-NEXT:    jb LBB1_56
; WIN32-NEXT:  # %bb.52: # %udiv-preheader
; WIN32-NEXT:    movl 24(%ebp), %ecx
; WIN32-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl 28(%ebp), %ecx
; WIN32-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl 32(%ebp), %ecx
; WIN32-NEXT:    movl %ecx, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl $0, {{[0-9]+}}(%esp)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    shrb $3, %al
; WIN32-NEXT:    andb $12, %al
; WIN32-NEXT:    movzbl %al, %eax
; WIN32-NEXT:    movl 108(%esp,%eax), %edi
; WIN32-NEXT:    movl 104(%esp,%eax), %ebx
; WIN32-NEXT:    movl %ebx, %edx
; WIN32-NEXT:    shrdl %cl, %edi, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 96(%esp,%eax), %esi
; WIN32-NEXT:    movl 100(%esp,%eax), %eax
; WIN32-NEXT:    movl %eax, %edx
; WIN32-NEXT:    shrdl %cl, %ebx, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shrl %cl, %edi
; WIN32-NEXT:    # kill: def $cl killed $cl killed $ecx
; WIN32-NEXT:    shrdl %cl, %eax, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 40(%ebp), %ecx
; WIN32-NEXT:    addl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 44(%ebp), %ecx
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 48(%ebp), %eax
; WIN32-NEXT:    adcl $-1, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 52(%ebp), %ecx
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    .p2align 4
; WIN32-NEXT:  LBB1_53: # %udiv-do-while
; WIN32-NEXT:    # =>This Inner Loop Header: Depth=1
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %esi, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    shldl $1, %ebx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edi, %ebx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    orl %edx, %ebx
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    shldl $1, %ecx, %edi
; WIN32-NEXT:    orl %edx, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    shldl $1, %edi, %ecx
; WIN32-NEXT:    orl %edx, %ecx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl %edi, %edi
; WIN32-NEXT:    orl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Folded Reload
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    cmpl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl %esi, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    sbbl %edx, %ecx
; WIN32-NEXT:    sarl $31, %ecx
; WIN32-NEXT:    movl %ecx, %edi
; WIN32-NEXT:    andl $1, %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %edi
; WIN32-NEXT:    andl 52(%ebp), %edi
; WIN32-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ecx, %edi
; WIN32-NEXT:    andl 48(%ebp), %edi
; WIN32-NEXT:    movl %ecx, %ebx
; WIN32-NEXT:    andl 44(%ebp), %ebx
; WIN32-NEXT:    andl 40(%ebp), %ecx
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    subl %ecx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    sbbl %ebx, %esi
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    sbbl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Folded Reload
; WIN32-NEXT:    movl %edx, %edi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    addl $-1, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ecx
; WIN32-NEXT:    adcl $-1, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Reload
; WIN32-NEXT:    adcl $-1, %ebx
; WIN32-NEXT:    movl %ecx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %ebx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %ebx, %ecx
; WIN32-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    orl %eax, %esi
; WIN32-NEXT:    orl %ecx, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    jne LBB1_53
; WIN32-NEXT:  LBB1_54: # %udiv-loop-exit
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    shldl $1, %ecx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    shldl $1, %eax, %ecx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    leal (%edx,%eax,2), %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:  LBB1_58: # %udiv-end
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl 8(%ebp), %ecx
; WIN32-NEXT:    movl %eax, (%ecx)
; WIN32-NEXT:    movl %edx, 4(%ecx)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, 8(%ecx)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    movl %eax, 12(%ecx)
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl %ecx, %esi
; WIN32-NEXT:    movl 44(%ebp), %eax
; WIN32-NEXT:    imull %eax, %esi
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    movl 40(%ebp), %edi
; WIN32-NEXT:    mull %edi
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    addl %esi, %edx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; WIN32-NEXT:    imull %edi, %esi
; WIN32-NEXT:    addl %edx, %esi
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl %ecx, %eax
; WIN32-NEXT:    movl 48(%ebp), %ebx
; WIN32-NEXT:    mull %ebx
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 52(%ebp), %eax
; WIN32-NEXT:    imull %ecx, %eax
; WIN32-NEXT:    addl %edx, %eax
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; WIN32-NEXT:    imull %edi, %ebx
; WIN32-NEXT:    addl %eax, %ebx
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    addl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    adcl %esi, %ebx
; WIN32-NEXT:    movl 40(%ebp), %esi
; WIN32-NEXT:    movl %esi, %eax
; WIN32-NEXT:    mull %ecx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl 44(%ebp), %eax
; WIN32-NEXT:    mull %ecx
; WIN32-NEXT:    movl %eax, %ecx
; WIN32-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    adcl $0, %edx
; WIN32-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    movl %esi, %eax
; WIN32-NEXT:    mull %edi
; WIN32-NEXT:    movl %edx, %esi
; WIN32-NEXT:    addl %ecx, %eax
; WIN32-NEXT:    movl %eax, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; WIN32-NEXT:    adcl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Folded Reload
; WIN32-NEXT:    setb %cl
; WIN32-NEXT:    movl 44(%ebp), %eax
; WIN32-NEXT:    mull %edi
; WIN32-NEXT:    addl %esi, %eax
; WIN32-NEXT:    movzbl %cl, %ecx
; WIN32-NEXT:    adcl %ecx, %edx
; WIN32-NEXT:    addl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Folded Reload
; WIN32-NEXT:    adcl %ebx, %edx
; WIN32-NEXT:    movl 24(%ebp), %ebx
; WIN32-NEXT:    subl {{[-0-9]+}}(%e{{[sb]}}p), %ebx # 4-byte Folded Reload
; WIN32-NEXT:    movl 28(%ebp), %ecx
; WIN32-NEXT:    sbbl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Folded Reload
; WIN32-NEXT:    movl 32(%ebp), %esi
; WIN32-NEXT:    sbbl %eax, %esi
; WIN32-NEXT:    movl 36(%ebp), %edi
; WIN32-NEXT:    sbbl %edx, %edi
; WIN32-NEXT:    movl 12(%ebp), %eax
; WIN32-NEXT:    movl %ebx, (%eax)
; WIN32-NEXT:    movl %ecx, 4(%eax)
; WIN32-NEXT:    movl %esi, 8(%eax)
; WIN32-NEXT:    movl %edi, 12(%eax)
; WIN32-NEXT:    leal -12(%ebp), %esp
; WIN32-NEXT:    popl %esi
; WIN32-NEXT:    popl %edi
; WIN32-NEXT:    popl %ebx
; WIN32-NEXT:    popl %ebp
; WIN32-NEXT:    retl
; WIN32-NEXT:  LBB1_17:
; WIN32-NEXT:    movl %edi, %ecx
; WIN32-NEXT:    movb $1, %al
; WIN32-NEXT:    jmp LBB1_19
; WIN32-NEXT:  LBB1_27:
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    jmp LBB1_25
; WIN32-NEXT:  LBB1_46:
; WIN32-NEXT:    movb $1, %al
; WIN32-NEXT:    jmp LBB1_48
; WIN32-NEXT:  LBB1_56:
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %ecx # 4-byte Reload
; WIN32-NEXT:    movl $0, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; WIN32-NEXT:    jmp LBB1_54
; WIN32-NEXT:  LBB1_22:
; WIN32-NEXT:    movl 36(%ebp), %ecx
; WIN32-NEXT:    jmp LBB1_29
; WIN32-NEXT:  LBB1_51:
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; WIN32-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; WIN32-NEXT:    jmp LBB1_58
  %q = udiv i128 %n, %d
  %r = urem i128 %n, %d
  store i128 %q, ptr %q_out
  store i128 %r, ptr %r_out
  ret void
}
