; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=i686-pc-win32 | FileCheck %s

%Foo = type { i32, i32 }

declare void @f(ptr inalloca(%Foo) %b)

define void @a() {
; CHECK-LABEL: a:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    movl %esp, %eax
; CHECK-NEXT:    movl $42, 4(%eax)
; CHECK-NEXT:    movl $13, (%eax)
; CHECK-NEXT:    calll _f
; CHECK-NEXT:    movl %ebp, %esp
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    retl
entry:
  %b = alloca inalloca %Foo
  %f2 = getelementptr %Foo, ptr %b, i32 0, i32 1
  store i32 13, ptr %b
  store i32 42, ptr %f2
  call void @f(ptr inalloca(%Foo) %b)
  ret void
}

declare void @inreg_with_inalloca(i32 inreg %a, ptr inalloca(%Foo) %b)

define void @b() {
; CHECK-LABEL: b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    movl %esp, %eax
; CHECK-NEXT:    movl $42, 4(%eax)
; CHECK-NEXT:    movl $13, (%eax)
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    calll _inreg_with_inalloca
; CHECK-NEXT:    movl %ebp, %esp
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    retl
entry:
  %b = alloca inalloca %Foo
  %f2 = getelementptr %Foo, ptr %b, i32 0, i32 1
  store i32 13, ptr %b
  store i32 42, ptr %f2
  call void @inreg_with_inalloca(i32 inreg 1, ptr inalloca(%Foo) %b)
  ret void
}

declare x86_thiscallcc void @thiscall_with_inalloca(ptr %a, ptr inalloca(%Foo) %b)

define void @c() {
; CHECK-LABEL: c:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    movl %esp, %eax
; CHECK-NEXT:    movl $42, 4(%eax)
; CHECK-NEXT:    movl $13, (%eax)
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    calll _thiscall_with_inalloca
; CHECK-NEXT:    movl %ebp, %esp
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    retl
entry:
  %b = alloca inalloca %Foo
  %f2 = getelementptr %Foo, ptr %b, i32 0, i32 1
  store i32 13, ptr %b
  store i32 42, ptr %f2
  call x86_thiscallcc void @thiscall_with_inalloca(ptr null, ptr inalloca(%Foo) %b)
  ret void
}
