; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=i686-pc-win32 | FileCheck %s

%Foo = type { i32, i32 }

declare x86_stdcallcc void @f(ptr inalloca(%Foo) %a)
declare x86_stdcallcc void @i(i32 %a)

define void @g() {
; CHECK-LABEL: g:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    pushl %eax
; CHECK-NEXT:    movl %esp, %eax
; CHECK-NEXT:    movl $42, 4(%eax)
; CHECK-NEXT:    movl $13, (%eax)
; CHECK-NEXT:    calll _f@8
; CHECK-NEXT:    pushl $0
; CHECK-NEXT:    calll _i@4
; CHECK-NEXT:    movl %ebp, %esp
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    retl
  %b = alloca inalloca %Foo
  %f2 = getelementptr %Foo, ptr %b, i32 0, i32 1
  store i32 13, ptr %b
  store i32 42, ptr %f2
  call x86_stdcallcc void @f(ptr inalloca(%Foo) %b)
  call x86_stdcallcc void @i(i32 0)
  ret void
}
