; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test_ret_attr_drop(i32 %x, ptr %p) {
; CHECK-LABEL: test_ret_attr_drop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # %eax, %edi
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movl %eax, (%rsi)
; CHECK-NEXT:    retq
entry:
  %0 = call range(i32 0, 10) i32 asm sideeffect "# $0, $1", "=rm,rm"(i32 %x)
  store i32 %0, ptr %p
  ret void
}

define i32 @test_ret_attr_keep(i32 %x) {
; CHECK-LABEL: test_ret_attr_keep:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # %eax, %edi
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    retq
entry:
  %0 = call range(i32 0, 10) i32 asm "# $0, $1", "=r,rm"(i32 %x)
  ret i32 %0
}
