; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=x86_64-unknown-linux-gnu -inline-asm-prepare < %s | FileCheck %s

define void @test_ret_attr_drop(i32 %x, ptr %p) {
; CHECK-LABEL: define void @test_ret_attr_drop(
; CHECK-SAME: i32 [[X:%.*]], ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ASM_MEM:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[ASM_MEM1:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[X]], ptr [[ASM_MEM1]], align 4
; CHECK-NEXT:    call void asm sideeffect "mov $1, $0", "=*rm,*rm"(ptr elementtype(i32) [[ASM_MEM]], ptr elementtype(i32) [[ASM_MEM1]]) #[[ATTR0:[0-9]+]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ASM_MEM]], align 4
; CHECK-NEXT:    store i32 [[TMP0]], ptr [[P]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %0 = call range(i32 0, 10) i32 asm sideeffect "mov $1, $0", "=rm,rm"(i32 %x)
  store i32 %0, ptr %p
  ret void
}

define i32 @test_ret_attr_keep(i32 %x) {
; CHECK-LABEL: define i32 @test_ret_attr_keep(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ASM_MEM:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[X]], ptr [[ASM_MEM]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = call range(i32 0, 10) i32 asm "mov $0, $1", "=r,*rm"(ptr elementtype(i32) [[ASM_MEM]]) #[[ATTR0]]
; CHECK-NEXT:    ret i32 [[TMP0]]
;
entry:
  %0 = call range(i32 0, 10) i32 asm "mov $0, $1", "=r,rm"(i32 %x)
  ret i32 %0
}
