; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -O0 < %s | FileCheck --check-prefixes=O0 %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu     < %s | FileCheck --check-prefixes=O2 %s

define dso_local void @test_rm_input(i64 noundef %flags) local_unnamed_addr {
; O0-LABEL: test_rm_input:
; O0:       # %bb.0: # %entry
; O0-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; O0-NEXT:    movq -{{[0-9]+}}(%rsp), %rax
; O0-NEXT:    movq %rax, -{{[0-9]+}}(%rsp)
; O0-NEXT:    #APP
; O0-NEXT:    pushq -{{[0-9]+}}(%rsp)
; O0-NEXT:    popfq
; O0-NEXT:    #NO_APP
; O0-NEXT:    retq
;
; O2-LABEL: test_rm_input:
; O2:       # %bb.0: # %entry
; O2-NEXT:    #APP
; O2-NEXT:    pushq %rdi
; O2-NEXT:    popfq
; O2-NEXT:    #NO_APP
; O2-NEXT:    retq
entry:
  %flags.addr = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  tail call void asm sideeffect "push $0 ; popf", "rm,~{dirflag},~{fpsr},~{flags}"(i64 %flags)
  br label %asm.merge

asm.pref.mem:
  store i64 %flags, ptr %flags.addr, align 8
  %0 = load i64, ptr %flags.addr, align 8
  call void asm sideeffect "push $0 ; popf", "rm,~{dirflag},~{fpsr},~{flags}"(i64 %0)
  br label %asm.merge

asm.merge:
  ret void
}

define dso_local i64 @test_rm_output() local_unnamed_addr {
; O0-LABEL: test_rm_output:
; O0:       # %bb.0: # %entry
; O0-NEXT:    #APP
; O0-NEXT:    pushfq
; O0-NEXT:    popq -{{[0-9]+}}(%rsp)
; O0-NEXT:    #NO_APP
; O0-NEXT:    movq -{{[0-9]+}}(%rsp), %rax
; O0-NEXT:    retq
;
; O2-LABEL: test_rm_output:
; O2:       # %bb.0: # %entry
; O2-NEXT:    #APP
; O2-NEXT:    pushfq
; O2-NEXT:    popq %rax
; O2-NEXT:    #NO_APP
; O2-NEXT:    retq
entry:
  %out = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  %0 = tail call i64 asm sideeffect "pushf ; pop $0", "=rm,~{dirflag},~{fpsr},~{flags}"()
  br label %asm.merge

asm.pref.mem:
  call void asm sideeffect "pushf ; pop $0", "=*rm,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i64) %out)
  %1 = load i64, ptr %out, align 8
  br label %asm.merge

asm.merge:
  %2 = phi i64 [ %0, %asm.pref.reg ], [ %1, %asm.pref.mem ]
  ret i64 %2
}

define dso_local void @test_g_input(i64 noundef %flags) local_unnamed_addr {
; O0-LABEL: test_g_input:
; O0:       # %bb.0: # %entry
; O0-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; O0-NEXT:    movq -{{[0-9]+}}(%rsp), %rax
; O0-NEXT:    movq %rax, -{{[0-9]+}}(%rsp)
; O0-NEXT:    #APP
; O0-NEXT:    pushq -{{[0-9]+}}(%rsp)
; O0-NEXT:    popfq
; O0-NEXT:    #NO_APP
; O0-NEXT:    retq
;
; O2-LABEL: test_g_input:
; O2:       # %bb.0: # %entry
; O2-NEXT:    #APP
; O2-NEXT:    pushq %rdi
; O2-NEXT:    popfq
; O2-NEXT:    #NO_APP
; O2-NEXT:    retq
entry:
  %flags.addr = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  tail call void asm sideeffect "push $0 ; popf", "imr,~{dirflag},~{fpsr},~{flags}"(i64 %flags)
  br label %asm.merge

asm.pref.mem:
  store i64 %flags, ptr %flags.addr, align 8
  %0 = load i64, ptr %flags.addr, align 8
  call void asm sideeffect "push $0 ; popf", "imr,~{dirflag},~{fpsr},~{flags}"(i64 %0)
  br label %asm.merge

asm.merge:
  ret void
}

define dso_local i64 @test_g_output() local_unnamed_addr {
; O0-LABEL: test_g_output:
; O0:       # %bb.0: # %entry
; O0-NEXT:    #APP
; O0-NEXT:    pushfq
; O0-NEXT:    popq -{{[0-9]+}}(%rsp)
; O0-NEXT:    #NO_APP
; O0-NEXT:    movq -{{[0-9]+}}(%rsp), %rax
; O0-NEXT:    retq
;
; O2-LABEL: test_g_output:
; O2:       # %bb.0: # %entry
; O2-NEXT:    #APP
; O2-NEXT:    pushfq
; O2-NEXT:    popq %rax
; O2-NEXT:    #NO_APP
; O2-NEXT:    retq
entry:
  %out = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  %0 = tail call i64 asm sideeffect "pushf ; pop $0", "=imr,~{dirflag},~{fpsr},~{flags}"()
  br label %asm.merge

asm.pref.mem:
  call void asm sideeffect "pushf ; pop $0", "=*imr,~{dirflag},~{fpsr},~{flags}"(ptr elementtype(i64) %out)
  %1 = load i64, ptr %out, align 8
  br label %asm.merge

asm.merge:
  %2 = phi i64 [ %0, %asm.pref.reg ], [ %1, %asm.pref.mem ]
  ret i64 %2
}

define i32 @test_bundle(i32 %x) {
; O0-LABEL: test_bundle:
; O0:       # %bb.0: # %entry
; O0-NEXT:    movl %edi, -{{[0-9]+}}(%rsp)
; O0-NEXT:    #APP
; O0-NEXT:    # %eax, -{{[0-9]+}}(%rsp)
; O0-NEXT:    #NO_APP
; O0-NEXT:    retq
;
; O2-LABEL: test_bundle:
; O2:       # %bb.0: # %entry
; O2-NEXT:    #APP
; O2-NEXT:    # %eax, %edi
; O2-NEXT:    #NO_APP
; O2-NEXT:    retq
entry:
  %out = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  %0 = call i32 asm sideeffect "# $0, $1", "=r,rm"(i32 %x) [ "bundle"(i32 42) ]
  br label %asm.merge

asm.pref.mem:
  %1 = call i32 asm sideeffect "# $0, $1", "=r,rm"(i32 %x) [ "bundle"(i32 42) ]
  br label %asm.merge

asm.merge:
  %2 = phi i32 [ %0, %asm.pref.reg ], [ %1, %asm.pref.mem ]
  ret i32 %2
}

define dso_local i32 @test_asm_goto() local_unnamed_addr {
; O0-LABEL: test_asm_goto:
; O0:       # %bb.0: # %entry
; O0-NEXT:    movl $42, %eax
; O0-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; O0-NEXT:    #APP
; O0-NEXT:    # -{{[0-9]+}}(%rsp)
; O0-NEXT:    #NO_APP
; O0-NEXT:    jmp .LBB5_1
; O0-NEXT:  .LBB5_1: # %asm.pref.mem.asm.merge_crit_edge
; O0-NEXT:    movl -{{[0-9]+}}(%rsp), %eax
; O0-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; O0-NEXT:    jmp .LBB5_3
; O0-NEXT:  # %bb.2: # %indirect.split
; O0-NEXT:  .LBB5_3: # Inline asm indirect target
; O0-NEXT:    # %cleanup
; O0-NEXT:    # Label of block must be emitted
; O0-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; O0-NEXT:    retq
;
; O2-LABEL: test_asm_goto:
; O2:       # %bb.0: # %entry
; O2-NEXT:    #APP
; O2-NEXT:    # %eax
; O2-NEXT:    #NO_APP
; O2-NEXT:  # %bb.2: # %cleanup
; O2-NEXT:    retq
; O2-NEXT:  .LBB5_1: # Inline asm indirect target
; O2-NEXT:    # %indirect.split
; O2-NEXT:    # Label of block must be emitted
; O2-NEXT:    movl $42, %eax
; O2-NEXT:    retq
entry:
  %out = alloca i32, align 4
  call void @llvm.lifetime.start.p0(ptr nonnull %out)
  callbr void @llvm.asm.constraint.br()
          to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:                                     ; preds = %entry
  %0 = callbr i32 asm "# $0", "=rm,!i,~{dirflag},~{fpsr},~{flags}"()
          to label %cleanup [label %indirect.split]

asm.pref.mem:                                     ; preds = %entry
  callbr void asm "# $0", "=*rm,!i,~{dirflag},~{fpsr},~{flags}"(ptr nonnull elementtype(i32) %out)
          to label %asm.pref.mem.asm.merge_crit_edge [label %cleanup]

asm.pref.mem.asm.merge_crit_edge:                 ; preds = %asm.pref.mem
  %.pre = load i32, ptr %out, align 4
  br label %cleanup

indirect.split:                                   ; preds = %asm.pref.reg
  br label %cleanup

cleanup:                                          ; preds = %asm.pref.reg, %asm.pref.mem.asm.merge_crit_edge, %asm.pref.mem, %indirect.split
  %retval.0 = phi i32 [ 42, %asm.pref.mem ], [ 42, %indirect.split ], [ %.pre, %asm.pref.mem.asm.merge_crit_edge ], [ %0, %asm.pref.reg ]
  call void @llvm.lifetime.end.p0(ptr nonnull %out)
  ret i32 %retval.0
}


; Exhaust all 14 usable x86 GPRs: 6 inputs consume rdi/rsi/rdx/rcx/r8/r9, and
; the asm clobbers rax/rbx/rbp/r10-r15. The early-clobber output (=&rm) has
; no register left, so the greedy RA must fold it to a stack slot at O2. At O0,
; InlineAsmPrepare routes directly to the memory path.
define i64 @test_rm_output_pressure(i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f) {
; O0-LABEL: test_rm_output_pressure:
; O0:       # %bb.0: # %entry
; O0-NEXT:    pushq %rbp
; O0-NEXT:    .cfi_def_cfa_offset 16
; O0-NEXT:    pushq %r15
; O0-NEXT:    .cfi_def_cfa_offset 24
; O0-NEXT:    pushq %r14
; O0-NEXT:    .cfi_def_cfa_offset 32
; O0-NEXT:    pushq %r13
; O0-NEXT:    .cfi_def_cfa_offset 40
; O0-NEXT:    pushq %r12
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    pushq %rbx
; O0-NEXT:    .cfi_def_cfa_offset 56
; O0-NEXT:    .cfi_offset %rbx, -56
; O0-NEXT:    .cfi_offset %r12, -48
; O0-NEXT:    .cfi_offset %r13, -40
; O0-NEXT:    .cfi_offset %r14, -32
; O0-NEXT:    .cfi_offset %r15, -24
; O0-NEXT:    .cfi_offset %rbp, -16
; O0-NEXT:    #APP
; O0-NEXT:    # -{{[0-9]+}}(%rsp) %rdi %rsi %rdx %rcx %r8 %r9
; O0-NEXT:    #NO_APP
; O0-NEXT:    movq -{{[0-9]+}}(%rsp), %rax
; O0-NEXT:    popq %rbx
; O0-NEXT:    .cfi_def_cfa_offset 48
; O0-NEXT:    popq %r12
; O0-NEXT:    .cfi_def_cfa_offset 40
; O0-NEXT:    popq %r13
; O0-NEXT:    .cfi_def_cfa_offset 32
; O0-NEXT:    popq %r14
; O0-NEXT:    .cfi_def_cfa_offset 24
; O0-NEXT:    popq %r15
; O0-NEXT:    .cfi_def_cfa_offset 16
; O0-NEXT:    popq %rbp
; O0-NEXT:    .cfi_def_cfa_offset 8
; O0-NEXT:    retq
;
; O2-LABEL: test_rm_output_pressure:
; O2:       # %bb.0: # %entry
; O2-NEXT:    pushq %rbp
; O2-NEXT:    .cfi_def_cfa_offset 16
; O2-NEXT:    pushq %r15
; O2-NEXT:    .cfi_def_cfa_offset 24
; O2-NEXT:    pushq %r14
; O2-NEXT:    .cfi_def_cfa_offset 32
; O2-NEXT:    pushq %r13
; O2-NEXT:    .cfi_def_cfa_offset 40
; O2-NEXT:    pushq %r12
; O2-NEXT:    .cfi_def_cfa_offset 48
; O2-NEXT:    pushq %rbx
; O2-NEXT:    .cfi_def_cfa_offset 56
; O2-NEXT:    .cfi_offset %rbx, -56
; O2-NEXT:    .cfi_offset %r12, -48
; O2-NEXT:    .cfi_offset %r13, -40
; O2-NEXT:    .cfi_offset %r14, -32
; O2-NEXT:    .cfi_offset %r15, -24
; O2-NEXT:    .cfi_offset %rbp, -16
; O2-NEXT:    movq %r9, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; O2-NEXT:    movq %r8, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; O2-NEXT:    movq %rcx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; O2-NEXT:    movq %rdx, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; O2-NEXT:    movq %rsi, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; O2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r9 # 8-byte Reload
; O2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %r8 # 8-byte Reload
; O2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rcx # 8-byte Reload
; O2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rdx # 8-byte Reload
; O2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rsi # 8-byte Reload
; O2-NEXT:    #APP # 8-byte Folded Spill
; O2-NEXT:    # -{{[0-9]+}}(%rsp) %rdi %rsi %rdx %rcx %r8 %r9
; O2-NEXT:    #NO_APP
; O2-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; O2-NEXT:    popq %rbx
; O2-NEXT:    .cfi_def_cfa_offset 48
; O2-NEXT:    popq %r12
; O2-NEXT:    .cfi_def_cfa_offset 40
; O2-NEXT:    popq %r13
; O2-NEXT:    .cfi_def_cfa_offset 32
; O2-NEXT:    popq %r14
; O2-NEXT:    .cfi_def_cfa_offset 24
; O2-NEXT:    popq %r15
; O2-NEXT:    .cfi_def_cfa_offset 16
; O2-NEXT:    popq %rbp
; O2-NEXT:    .cfi_def_cfa_offset 8
; O2-NEXT:    retq
entry:
  %out = alloca i64, align 8
  callbr void @llvm.asm.constraint.br()
      to label %asm.pref.reg [label %asm.pref.mem]

asm.pref.reg:
  %0 = call i64 asm sideeffect "# $0 $1 $2 $3 $4 $5 $6",
      "=&rm,r,r,r,r,r,r,~{rax},~{rbx},~{rbp},~{r10},~{r11},~{r12},~{r13},~{r14},~{r15}"
      (i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f)
  br label %asm.merge

asm.pref.mem:
  call void asm sideeffect "# $0 $1 $2 $3 $4 $5 $6",
      "=*&rm,r,r,r,r,r,r,~{rax},~{rbx},~{rbp},~{r10},~{r11},~{r12},~{r13},~{r14},~{r15}"
      (ptr elementtype(i64) %out, i64 %a, i64 %b, i64 %c, i64 %d, i64 %e, i64 %f)
  %1 = load i64, ptr %out, align 8
  br label %asm.merge

asm.merge:
  %2 = phi i64 [ %0, %asm.pref.reg ], [ %1, %asm.pref.mem ]
  ret i64 %2
}

declare void @llvm.asm.constraint.br()
