; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

define void @test1(i32 %x) {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # %eax, %edi
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    retq
entry:
  %0 = call i32 asm sideeffect "# $0, $1", "=r,rm,~{dirflag},~{fpsr},~{flags}"(i32 %x)
  ret void
}

define void @test2(ptr %p) {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # %eax
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movl %eax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %0 = call i32 asm sideeffect "# $0", "=rm,~{dirflag},~{fpsr},~{flags}"()
  store i32 %0, ptr %p
  ret void
}

define void @test3(ptr %x_ptr) {
; CHECK-LABEL: test3:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl (%rdi), %eax
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # %eax
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movl %eax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %x = load i32, ptr %x_ptr
  %0 = call i32 asm sideeffect "# $0", "=rm,0,~{dirflag},~{fpsr},~{flags}"(i32 %x)
  store i32 %0, ptr %x_ptr
  ret void
}

define dso_local i64 @test4() local_unnamed_addr #0 {
; CHECK-LABEL: test4:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # %rax, $256
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    retq
entry:
  %0 = tail call i64 asm "# $0, $1", "=r,irm,~{dirflag},~{fpsr},~{flags}"(i32 256)
  ret i64 %0
}

; Tied output ("=rm,0", i.e. "+rm") must NOT be converted to indirect ("=*rm").
; The non-tied input ("rm") in the same asm IS converted to "*rm".
define void @test5(ptr %x_ptr, i32 %b) {
; CHECK-LABEL: test5:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl (%rdi), %eax
; CHECK-NEXT:    #APP
; CHECK-NEXT:    # %eax, %esi, %eax
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movl %eax, (%rdi)
; CHECK-NEXT:    retq
entry:
  %x = load i32, ptr %x_ptr
  %0 = call i32 asm sideeffect "# $0, $1, $2", "=rm,rm,0,~{dirflag},~{fpsr},~{flags}"(i32 %b, i32 %x)
  store i32 %0, ptr %x_ptr
  ret void
}
