; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -S -mtriple=x86_64-unknown-linux-gnu -inline-asm-prepare < %s | FileCheck %s

declare i32 @__gxx_personality_v0(...)

define i32 @test_invoke_rm(i32 %x) personality ptr @__gxx_personality_v0 {
; CHECK-LABEL: define i32 @test_invoke_rm(
; CHECK-SAME: i32 [[X:%.*]]) personality ptr @__gxx_personality_v0 {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ASM_MEM:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[X]], ptr [[ASM_MEM]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = invoke i32 asm "mov $0, $1", "=r,*rm"(ptr elementtype(i32) [[ASM_MEM]]) #[[ATTR1:[0-9]+]]
; CHECK-NEXT:            to label %[[NORMAL:.*]] unwind label %[[UNWIND:.*]]
; CHECK:       [[NORMAL]]:
; CHECK-NEXT:    ret i32 [[TMP0]]
; CHECK:       [[UNWIND]]:
; CHECK-NEXT:    [[TMP1:%.*]] = landingpad { ptr, i32 }
; CHECK-NEXT:            cleanup
; CHECK-NEXT:    resume { ptr, i32 } [[TMP1]]
;
entry:
  %0 = invoke i32 asm "mov $0, $1", "=r,rm"(i32 %x)
  to label %normal unwind label %unwind

normal:
  ret i32 %0

unwind:
  %1 = landingpad { ptr, i32 }
  cleanup
  resume { ptr, i32 } %1
}

define i32 @test_callbr_rm(i32 %x) {
; CHECK-LABEL: define i32 @test_callbr_rm(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ASM_MEM:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[X]], ptr [[ASM_MEM]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = callbr i32 asm "mov $1, $0", "=r,*rm,!i"(ptr elementtype(i32) [[ASM_MEM]]) #[[ATTR1]]
; CHECK-NEXT:            to label %[[NORMAL:.*]] [label %[[INDIRECT:.*]]]
; CHECK:       [[NORMAL]]:
; CHECK-NEXT:    ret i32 [[TMP0]]
; CHECK:       [[INDIRECT]]:
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 @llvm.callbr.landingpad.i32(i32 [[TMP0]])
; CHECK-NEXT:    ret i32 [[TMP1]]
;
entry:
  %0 = callbr i32 asm "mov $1, $0", "=r,rm,!i"(i32 %x)
  to label %normal [label %indirect]

normal:
  ret i32 %0

indirect:
  ret i32 %0
}

define i32 @test_callbr_convert(i32 %x) {
; CHECK-LABEL: define i32 @test_callbr_convert(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ASM_MEM:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[ASM_MEM1:%.*]] = alloca i32, align 4
; CHECK-NEXT:    store i32 [[X]], ptr [[ASM_MEM1]], align 4
; CHECK-NEXT:    callbr void asm "mov $1, $0", "=*rm,*rm,!i"(ptr elementtype(i32) [[ASM_MEM]], ptr elementtype(i32) [[ASM_MEM1]]) #[[ATTR1]]
; CHECK-NEXT:            to label %[[NORMAL:.*]] [label %[[INDIRECT:.*]]]
; CHECK:       [[NORMAL]]:
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ASM_MEM]], align 4
; CHECK-NEXT:    ret i32 [[TMP0]]
; CHECK:       [[INDIRECT]]:
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[ASM_MEM]], align 4
; CHECK-NEXT:    ret i32 [[TMP1]]
;
entry:
  %0 = callbr i32 asm "mov $1, $0", "=rm,rm,!i"(i32 %x)
  to label %normal [label %indirect]

normal:
  ret i32 %0

indirect:
  ret i32 %0
}
