; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=FAST_ISEL_GREEDY_RA %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=true --regalloc=fast < %s \
; RUN:     | FileCheck --check-prefix=FAST_ISEL_FAST_RA %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=greedy < %s \
; RUN:     | FileCheck --check-prefix=GREEDY_RA %s
; RUN: llc -mtriple=x86_64-unknown-linux-gnu --global-isel=false --fast-isel=false --regalloc=fast < %s \
; RUN:     | FileCheck --check-prefix=FAST_RA %s

declare i32 @__gxx_personality_v0(...)

define i32 @test_invoke_rm(i32 %x) personality ptr @__gxx_personality_v0 {
; FAST_ISEL_GREEDY_RA-LABEL: test_invoke_rm:
; FAST_ISEL_GREEDY_RA:       # %bb.0: # %entry
; FAST_ISEL_GREEDY_RA-NEXT:  .Ltmp0: # EH_LABEL
; FAST_ISEL_GREEDY_RA-NEXT:    #APP
; FAST_ISEL_GREEDY_RA-NEXT:    # %eax, %edi
; FAST_ISEL_GREEDY_RA-NEXT:    #NO_APP
; FAST_ISEL_GREEDY_RA-NEXT:  .Ltmp1: # EH_LABEL
; FAST_ISEL_GREEDY_RA-NEXT:  # %bb.1: # %normal
; FAST_ISEL_GREEDY_RA-NEXT:    retq
; FAST_ISEL_GREEDY_RA-NEXT:  .LBB0_2: # %unwind
; FAST_ISEL_GREEDY_RA-NEXT:    pushq %rax
; FAST_ISEL_GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_ISEL_GREEDY_RA-NEXT:  .Ltmp2: # EH_LABEL
; FAST_ISEL_GREEDY_RA-NEXT:    movq %rax, %rdi
; FAST_ISEL_GREEDY_RA-NEXT:    callq _Unwind_Resume@PLT
;
; FAST_ISEL_FAST_RA-LABEL: test_invoke_rm:
; FAST_ISEL_FAST_RA:       # %bb.0: # %entry
; FAST_ISEL_FAST_RA-NEXT:    pushq %rax
; FAST_ISEL_FAST_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_ISEL_FAST_RA-NEXT:  .Ltmp0: # EH_LABEL
; FAST_ISEL_FAST_RA-NEXT:    #APP
; FAST_ISEL_FAST_RA-NEXT:    # %eax, %edi
; FAST_ISEL_FAST_RA-NEXT:    #NO_APP
; FAST_ISEL_FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_ISEL_FAST_RA-NEXT:  .Ltmp1: # EH_LABEL
; FAST_ISEL_FAST_RA-NEXT:  # %bb.1: # %normal
; FAST_ISEL_FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_ISEL_FAST_RA-NEXT:    popq %rcx
; FAST_ISEL_FAST_RA-NEXT:    .cfi_def_cfa_offset 8
; FAST_ISEL_FAST_RA-NEXT:    retq
; FAST_ISEL_FAST_RA-NEXT:  .LBB0_2: # %unwind
; FAST_ISEL_FAST_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_ISEL_FAST_RA-NEXT:  .Ltmp2: # EH_LABEL
; FAST_ISEL_FAST_RA-NEXT:    movq %rax, %rdi
; FAST_ISEL_FAST_RA-NEXT:    callq _Unwind_Resume@PLT
;
; GREEDY_RA-LABEL: test_invoke_rm:
; GREEDY_RA:       # %bb.0: # %entry
; GREEDY_RA-NEXT:  .Ltmp0: # EH_LABEL
; GREEDY_RA-NEXT:    #APP
; GREEDY_RA-NEXT:    # %eax, %edi
; GREEDY_RA-NEXT:    #NO_APP
; GREEDY_RA-NEXT:  .Ltmp1: # EH_LABEL
; GREEDY_RA-NEXT:  # %bb.1: # %normal
; GREEDY_RA-NEXT:    retq
; GREEDY_RA-NEXT:  .LBB0_2: # %unwind
; GREEDY_RA-NEXT:    pushq %rax
; GREEDY_RA-NEXT:    .cfi_def_cfa_offset 16
; GREEDY_RA-NEXT:  .Ltmp2: # EH_LABEL
; GREEDY_RA-NEXT:    movq %rax, %rdi
; GREEDY_RA-NEXT:    callq _Unwind_Resume@PLT
;
; FAST_RA-LABEL: test_invoke_rm:
; FAST_RA:       # %bb.0: # %entry
; FAST_RA-NEXT:    pushq %rax
; FAST_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_RA-NEXT:  .Ltmp0: # EH_LABEL
; FAST_RA-NEXT:    #APP
; FAST_RA-NEXT:    # %eax, %edi
; FAST_RA-NEXT:    #NO_APP
; FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_RA-NEXT:  .Ltmp1: # EH_LABEL
; FAST_RA-NEXT:  # %bb.1: # %normal
; FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_RA-NEXT:    popq %rcx
; FAST_RA-NEXT:    .cfi_def_cfa_offset 8
; FAST_RA-NEXT:    retq
; FAST_RA-NEXT:  .LBB0_2: # %unwind
; FAST_RA-NEXT:    .cfi_def_cfa_offset 16
; FAST_RA-NEXT:  .Ltmp2: # EH_LABEL
; FAST_RA-NEXT:    movq %rax, %rdi
; FAST_RA-NEXT:    callq _Unwind_Resume@PLT
entry:
  %0 = invoke i32 asm "# $0, $1", "=r,rm"(i32 %x)
  to label %normal unwind label %unwind

normal:
  ret i32 %0

unwind:
  %1 = landingpad { ptr, i32 }
  cleanup
  resume { ptr, i32 } %1
}

define i32 @test_callbr_rm(i32 %x) {
; FAST_ISEL_GREEDY_RA-LABEL: test_callbr_rm:
; FAST_ISEL_GREEDY_RA:       # %bb.0: # %entry
; FAST_ISEL_GREEDY_RA-NEXT:    #APP
; FAST_ISEL_GREEDY_RA-NEXT:    # %eax, %edi
; FAST_ISEL_GREEDY_RA-NEXT:    #NO_APP
; FAST_ISEL_GREEDY_RA-NEXT:  .LBB1_1: # Inline asm indirect target
; FAST_ISEL_GREEDY_RA-NEXT:    # %indirect
; FAST_ISEL_GREEDY_RA-NEXT:    # Label of block must be emitted
; FAST_ISEL_GREEDY_RA-NEXT:    retq
;
; FAST_ISEL_FAST_RA-LABEL: test_callbr_rm:
; FAST_ISEL_FAST_RA:       # %bb.0: # %entry
; FAST_ISEL_FAST_RA-NEXT:    #APP
; FAST_ISEL_FAST_RA-NEXT:    # %eax, %edi
; FAST_ISEL_FAST_RA-NEXT:    #NO_APP
; FAST_ISEL_FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_ISEL_FAST_RA-NEXT:  # %bb.1: # %normal
; FAST_ISEL_FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_ISEL_FAST_RA-NEXT:    retq
; FAST_ISEL_FAST_RA-NEXT:  .LBB1_2: # Inline asm indirect target
; FAST_ISEL_FAST_RA-NEXT:    # %indirect
; FAST_ISEL_FAST_RA-NEXT:    # Label of block must be emitted
; FAST_ISEL_FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_ISEL_FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_ISEL_FAST_RA-NEXT:    retq
;
; GREEDY_RA-LABEL: test_callbr_rm:
; GREEDY_RA:       # %bb.0: # %entry
; GREEDY_RA-NEXT:    #APP
; GREEDY_RA-NEXT:    # %eax, %edi
; GREEDY_RA-NEXT:    #NO_APP
; GREEDY_RA-NEXT:  .LBB1_1: # Inline asm indirect target
; GREEDY_RA-NEXT:    # %indirect
; GREEDY_RA-NEXT:    # Label of block must be emitted
; GREEDY_RA-NEXT:    retq
;
; FAST_RA-LABEL: test_callbr_rm:
; FAST_RA:       # %bb.0: # %entry
; FAST_RA-NEXT:    #APP
; FAST_RA-NEXT:    # %eax, %edi
; FAST_RA-NEXT:    #NO_APP
; FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_RA-NEXT:  # %bb.1: # %normal
; FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_RA-NEXT:    retq
; FAST_RA-NEXT:  .LBB1_2: # Inline asm indirect target
; FAST_RA-NEXT:    # %indirect
; FAST_RA-NEXT:    # Label of block must be emitted
; FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_RA-NEXT:    retq
entry:
  %0 = callbr i32 asm "# $0, $1", "=r,rm,!i"(i32 %x)
  to label %normal [label %indirect]

normal:
  ret i32 %0

indirect:
  ret i32 %0
}

define i32 @test_callbr_convert(i32 %x) {
; FAST_ISEL_GREEDY_RA-LABEL: test_callbr_convert:
; FAST_ISEL_GREEDY_RA:       # %bb.0: # %entry
; FAST_ISEL_GREEDY_RA-NEXT:    #APP
; FAST_ISEL_GREEDY_RA-NEXT:    # %eax, %edi
; FAST_ISEL_GREEDY_RA-NEXT:    #NO_APP
; FAST_ISEL_GREEDY_RA-NEXT:  .LBB2_1: # Inline asm indirect target
; FAST_ISEL_GREEDY_RA-NEXT:    # %indirect
; FAST_ISEL_GREEDY_RA-NEXT:    # Label of block must be emitted
; FAST_ISEL_GREEDY_RA-NEXT:    retq
;
; FAST_ISEL_FAST_RA-LABEL: test_callbr_convert:
; FAST_ISEL_FAST_RA:       # %bb.0: # %entry
; FAST_ISEL_FAST_RA-NEXT:    #APP
; FAST_ISEL_FAST_RA-NEXT:    # %eax, %edi
; FAST_ISEL_FAST_RA-NEXT:    #NO_APP
; FAST_ISEL_FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_ISEL_FAST_RA-NEXT:  # %bb.1: # %normal
; FAST_ISEL_FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_ISEL_FAST_RA-NEXT:    retq
; FAST_ISEL_FAST_RA-NEXT:  .LBB2_2: # Inline asm indirect target
; FAST_ISEL_FAST_RA-NEXT:    # %indirect
; FAST_ISEL_FAST_RA-NEXT:    # Label of block must be emitted
; FAST_ISEL_FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_ISEL_FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_ISEL_FAST_RA-NEXT:    retq
;
; GREEDY_RA-LABEL: test_callbr_convert:
; GREEDY_RA:       # %bb.0: # %entry
; GREEDY_RA-NEXT:    #APP
; GREEDY_RA-NEXT:    # %eax, %edi
; GREEDY_RA-NEXT:    #NO_APP
; GREEDY_RA-NEXT:  .LBB2_1: # Inline asm indirect target
; GREEDY_RA-NEXT:    # %indirect
; GREEDY_RA-NEXT:    # Label of block must be emitted
; GREEDY_RA-NEXT:    retq
;
; FAST_RA-LABEL: test_callbr_convert:
; FAST_RA:       # %bb.0: # %entry
; FAST_RA-NEXT:    #APP
; FAST_RA-NEXT:    # %eax, %edi
; FAST_RA-NEXT:    #NO_APP
; FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_RA-NEXT:  # %bb.1: # %normal
; FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_RA-NEXT:    retq
; FAST_RA-NEXT:  .LBB2_2: # Inline asm indirect target
; FAST_RA-NEXT:    # %indirect
; FAST_RA-NEXT:    # Label of block must be emitted
; FAST_RA-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; FAST_RA-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; FAST_RA-NEXT:    retq
entry:
  %0 = callbr i32 asm "# $0, $1", "=rm,rm,!i"(i32 %x)
  to label %normal [label %indirect]

normal:
  ret i32 %0

indirect:
  ret i32 %0
}
