; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -mattr=+sse2 < %s | FileCheck %s

declare <16 x i8> @llvm.umax.v16i8(<16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.uaddsat.v16i8(<16 x i8>, <16 x i8>)
declare <16 x i8> @llvm.umin.v16i8(<16 x i8>, <16 x i8>)

define i1 @test_umax_extract_never_zero(<16 x i8> %x) {
; CHECK-LABEL: test_umax_extract_never_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movdqa {{.*#+}} xmm1 = [u,1,u,u,u,u,u,u,u,u,u,u,u,u,u,u]
; CHECK-NEXT:    por %xmm0, %xmm1
; CHECK-NEXT:    pmaxub %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    shrl $8, %eax
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %1 = insertelement <16 x i8> poison, i8 1, i32 1
  %2 = or <16 x i8> %x, %1
  %3 = call <16 x i8> @llvm.umax.v16i8(<16 x i8> %2, <16 x i8> %x)
  %ext = extractelement <16 x i8> %3, i32 1
  %cmp = icmp eq i8 %ext, 0
  ret i1 %cmp
}

define i1 @test_uaddsat_extract_never_zero(<16 x i8> %x) {
; CHECK-LABEL: test_uaddsat_extract_never_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $24, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    movaps %xmm0, %xmm1
; CHECK-NEXT:    movaps {{.*#+}} xmm0 = [u,1,u,u,u,u,u,u,u,u,u,u,u,u,u,u]
; CHECK-NEXT:    orps %xmm1, %xmm0
; CHECK-NEXT:    callq llvm.uaddsat.v16i8@PLT
; CHECK-NEXT:    movaps %xmm0, (%rsp)
; CHECK-NEXT:    cmpb $0, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    addq $24, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %1 = insertelement <16 x i8> poison, i8 1, i32 1
  %2 = or <16 x i8> %x, %1
  %3 = call <16 x i8> @llvm.uaddsat.v16i8(<16 x i8> %2, <16 x i8> %x)
  %ext = extractelement <16 x i8> %3, i32 1
  %cmp = icmp eq i8 %ext, 0
  ret i1 %cmp
}

define i1 @test_umin_extract_never_zero(<16 x i8> %x, <16 x i8> %y) {
; CHECK-LABEL: test_umin_extract_never_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    por {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    por {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm1
; CHECK-NEXT:    pminub %xmm0, %xmm1
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    shrl $8, %eax
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %1 = insertelement <16 x i8> poison, i8 1, i32 1
  %2 = insertelement <16 x i8> poison, i8 2, i32 1
  %or.x = or <16 x i8> %x, %1
  %or.y = or <16 x i8> %y, %2
  %3 = call <16 x i8> @llvm.umin.v16i8(<16 x i8> %or.x, <16 x i8> %or.y)
  %ext = extractelement <16 x i8> %3, i32 1
  %cmp = icmp eq i8 %ext, 0
  ret i1 %cmp
}
