; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-linux-gnu | FileCheck %s --check-prefixes=X64,DAG-X64
; RUN: llc < %s -mtriple=x86_64-linux-gnu -fast-isel | FileCheck %s --check-prefixes=X64,FASTISEL-X64
; RUN: llc < %s -mtriple=i686-linux-gnu | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -mtriple=i686-linux-gnu -fast-isel | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=2 | FileCheck %s --check-prefixes=GISEL-X64
; RUN: llc < %s -mtriple=i686-linux-gnu -global-isel -global-isel-abort=2 | FileCheck %s --check-prefixes=X86,GISEL-X86

define float @ceil_f32(float %a) nounwind readnone {
; DAG-X64-LABEL: ceil_f32:
; DAG-X64:       # %bb.0:
; DAG-X64-NEXT:    jmp ceilf@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: ceil_f32:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq ceilf@PLT
; FASTISEL-X64-NEXT:    popq %rax
; FASTISEL-X64-NEXT:    retq
;
; X86-LABEL: ceil_f32:
; X86:       # %bb.0:
; X86-NEXT:    subl $12, %esp
; X86-NEXT:    flds {{[0-9]+}}(%esp)
; X86-NEXT:    fstps (%esp)
; X86-NEXT:    calll ceilf
; X86-NEXT:    addl $12, %esp
; X86-NEXT:    retl
  %c = call float @llvm.ceil.f32(float %a)
  ret float %c
}

define double @ceil_f64(double %a) nounwind readnone {
; DAG-X64-LABEL: ceil_f64:
; DAG-X64:       # %bb.0:
; DAG-X64-NEXT:    jmp ceil@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: ceil_f64:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq ceil@PLT
; FASTISEL-X64-NEXT:    popq %rax
; FASTISEL-X64-NEXT:    retq
;
; X86-LABEL: ceil_f64:
; X86:       # %bb.0:
; X86-NEXT:    subl $12, %esp
; X86-NEXT:    fldl {{[0-9]+}}(%esp)
; X86-NEXT:    fstpl (%esp)
; X86-NEXT:    calll ceil
; X86-NEXT:    addl $12, %esp
; X86-NEXT:    retl
  %c = call double @llvm.ceil.f64(double %a)
  ret double %c
}

define x86_fp80 @ceil_f80(x86_fp80 %a) nounwind readnone {
; X64-LABEL: ceil_f80:
; X64:       # %bb.0:
; X64-NEXT:    subq $24, %rsp
; X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; X64-NEXT:    fstpt (%rsp)
; X64-NEXT:    callq ceill@PLT
; X64-NEXT:    addq $24, %rsp
; X64-NEXT:    retq
;
; X86-LABEL: ceil_f80:
; X86:       # %bb.0:
; X86-NEXT:    subl $12, %esp
; X86-NEXT:    fldt {{[0-9]+}}(%esp)
; X86-NEXT:    fstpt (%esp)
; X86-NEXT:    calll ceill
; X86-NEXT:    addl $12, %esp
; X86-NEXT:    retl
  %c = call x86_fp80 @llvm.ceil.f80(x86_fp80 %a)
  ret x86_fp80 %c
}
