; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=i686-linux-gnu | FileCheck %s --check-prefixes=X86,SDAG-X86
; RUN: llc < %s -mtriple=i686-linux-gnu -fast-isel -fast-isel-abort=1 | FileCheck %s --check-prefixes=X86,FASTISEL-X86
; RUN: llc < %s -mtriple=i686-linux-gnu -global-isel -global-isel-abort=1 | FileCheck %s --check-prefixes=GISEL-X86
; RUN: llc < %s -mtriple=x86_64-linux-gnu | FileCheck %s --check-prefixes=SDAG-X64
; RUN: llc < %s -mtriple=x86_64-linux-gnu -fast-isel -fast-isel-abort=1 | FileCheck %s --check-prefixes=FASTISEL-X64
; RUN: llc < %s -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=1 | FileCheck %s --check-prefixes=GISEL-X64

define i32 @test_lround_i32_f32(float %x) nounwind {
; SDAG-X86-LABEL: test_lround_i32_f32:
; SDAG-X86:       # %bb.0:
; SDAG-X86-NEXT:    jmp lroundf # TAILCALL
;
; FASTISEL-X86-LABEL: test_lround_i32_f32:
; FASTISEL-X86:       # %bb.0:
; FASTISEL-X86-NEXT:    subl $12, %esp
; FASTISEL-X86-NEXT:    flds {{[0-9]+}}(%esp)
; FASTISEL-X86-NEXT:    fstps (%esp)
; FASTISEL-X86-NEXT:    calll lroundf
; FASTISEL-X86-NEXT:    addl $12, %esp
; FASTISEL-X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_lround_i32_f32:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl %eax, (%esp)
; GISEL-X86-NEXT:    calll lroundf
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
;
; SDAG-X64-LABEL: test_lround_i32_f32:
; SDAG-X64:       # %bb.0:
; SDAG-X64-NEXT:    jmp lroundf@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: test_lround_i32_f32:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq lroundf@PLT
; FASTISEL-X64-NEXT:    popq %rcx
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_lround_i32_f32:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    pushq %rax
; GISEL-X64-NEXT:    callq lroundf
; GISEL-X64-NEXT:    popq %rcx
; GISEL-X64-NEXT:    retq
  %conv = call i32 @llvm.lround.i32.f32(float %x)
  ret i32 %conv
}

define i32 @test_lround_i32_f64(double %x) nounwind {
; SDAG-X86-LABEL: test_lround_i32_f64:
; SDAG-X86:       # %bb.0:
; SDAG-X86-NEXT:    jmp lround # TAILCALL
;
; FASTISEL-X86-LABEL: test_lround_i32_f64:
; FASTISEL-X86:       # %bb.0:
; FASTISEL-X86-NEXT:    subl $12, %esp
; FASTISEL-X86-NEXT:    fldl {{[0-9]+}}(%esp)
; FASTISEL-X86-NEXT:    fstpl (%esp)
; FASTISEL-X86-NEXT:    calll lround
; FASTISEL-X86-NEXT:    addl $12, %esp
; FASTISEL-X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_lround_i32_f64:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    leal {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movl 4(%eax), %eax
; GISEL-X86-NEXT:    xorl %edx, %edx
; GISEL-X86-NEXT:    addl %esp, %edx
; GISEL-X86-NEXT:    movl %ecx, (%esp)
; GISEL-X86-NEXT:    movl %eax, 4(%edx)
; GISEL-X86-NEXT:    calll lround
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
;
; SDAG-X64-LABEL: test_lround_i32_f64:
; SDAG-X64:       # %bb.0:
; SDAG-X64-NEXT:    jmp lround@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: test_lround_i32_f64:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq lround@PLT
; FASTISEL-X64-NEXT:    popq %rcx
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_lround_i32_f64:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    pushq %rax
; GISEL-X64-NEXT:    callq lround
; GISEL-X64-NEXT:    popq %rcx
; GISEL-X64-NEXT:    retq
  %conv = call i32 @llvm.lround.i32.f64(double %x)
  ret i32 %conv
}

define i32 @test_lround_i32_f80(x86_fp80 %x) nounwind {
; SDAG-X86-LABEL: test_lround_i32_f80:
; SDAG-X86:       # %bb.0:
; SDAG-X86-NEXT:    jmp lroundl # TAILCALL
;
; FASTISEL-X86-LABEL: test_lround_i32_f80:
; FASTISEL-X86:       # %bb.0:
; FASTISEL-X86-NEXT:    subl $12, %esp
; FASTISEL-X86-NEXT:    fldt {{[0-9]+}}(%esp)
; FASTISEL-X86-NEXT:    fstpt (%esp)
; FASTISEL-X86-NEXT:    calll lroundl
; FASTISEL-X86-NEXT:    addl $12, %esp
; FASTISEL-X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_lround_i32_f80:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    fldt {{[0-9]+}}(%esp)
; GISEL-X86-NEXT:    fstpt (%esp)
; GISEL-X86-NEXT:    calll lroundl
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
;
; SDAG-X64-LABEL: test_lround_i32_f80:
; SDAG-X64:       # %bb.0:
; SDAG-X64-NEXT:    jmp lroundl@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: test_lround_i32_f80:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    subq $24, %rsp
; FASTISEL-X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; FASTISEL-X64-NEXT:    fstpt (%rsp)
; FASTISEL-X64-NEXT:    callq lroundl@PLT
; FASTISEL-X64-NEXT:    addq $24, %rsp
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_lround_i32_f80:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    subq $24, %rsp
; GISEL-X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; GISEL-X64-NEXT:    fstpt (%rsp)
; GISEL-X64-NEXT:    callq lroundl
; GISEL-X64-NEXT:    addq $24, %rsp
; GISEL-X64-NEXT:    retq
  %conv = call i32 @llvm.lround.i32.f80(x86_fp80 %x)
  ret i32 %conv
}

define i64 @test_lround_i64_f32(float %x) nounwind {
; X86-LABEL: test_lround_i64_f32:
; X86:       # %bb.0:
; X86-NEXT:    subl $12, %esp
; X86-NEXT:    flds {{[0-9]+}}(%esp)
; X86-NEXT:    fstps (%esp)
; X86-NEXT:    calll lroundf
; X86-NEXT:    addl $12, %esp
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_lround_i64_f32:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl %eax, (%esp)
; GISEL-X86-NEXT:    calll lroundf
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
;
; SDAG-X64-LABEL: test_lround_i64_f32:
; SDAG-X64:       # %bb.0:
; SDAG-X64-NEXT:    jmp lroundf@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: test_lround_i64_f32:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq lroundf@PLT
; FASTISEL-X64-NEXT:    popq %rcx
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_lround_i64_f32:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    pushq %rax
; GISEL-X64-NEXT:    callq lroundf
; GISEL-X64-NEXT:    popq %rcx
; GISEL-X64-NEXT:    retq
  %conv = call i64 @llvm.lround.i64.f32(float %x)
  ret i64 %conv
}

define i64 @test_lround_i64_f64(double %x) nounwind {
; X86-LABEL: test_lround_i64_f64:
; X86:       # %bb.0:
; X86-NEXT:    subl $12, %esp
; X86-NEXT:    fldl {{[0-9]+}}(%esp)
; X86-NEXT:    fstpl (%esp)
; X86-NEXT:    calll lround
; X86-NEXT:    addl $12, %esp
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_lround_i64_f64:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    leal {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movl 4(%eax), %eax
; GISEL-X86-NEXT:    xorl %edx, %edx
; GISEL-X86-NEXT:    addl %esp, %edx
; GISEL-X86-NEXT:    movl %ecx, (%esp)
; GISEL-X86-NEXT:    movl %eax, 4(%edx)
; GISEL-X86-NEXT:    calll lround
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
;
; SDAG-X64-LABEL: test_lround_i64_f64:
; SDAG-X64:       # %bb.0:
; SDAG-X64-NEXT:    jmp lround@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: test_lround_i64_f64:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq lround@PLT
; FASTISEL-X64-NEXT:    popq %rcx
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_lround_i64_f64:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    pushq %rax
; GISEL-X64-NEXT:    callq lround
; GISEL-X64-NEXT:    popq %rcx
; GISEL-X64-NEXT:    retq
  %conv = call i64 @llvm.lround.i64.f64(double %x)
  ret i64 %conv
}

define i64 @test_lround_i64_f80(x86_fp80 %x) nounwind {
; X86-LABEL: test_lround_i64_f80:
; X86:       # %bb.0:
; X86-NEXT:    subl $12, %esp
; X86-NEXT:    fldt {{[0-9]+}}(%esp)
; X86-NEXT:    fstpt (%esp)
; X86-NEXT:    calll lroundl
; X86-NEXT:    addl $12, %esp
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: test_lround_i64_f80:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    fldt {{[0-9]+}}(%esp)
; GISEL-X86-NEXT:    fstpt (%esp)
; GISEL-X86-NEXT:    calll lroundl
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
;
; SDAG-X64-LABEL: test_lround_i64_f80:
; SDAG-X64:       # %bb.0:
; SDAG-X64-NEXT:    jmp lroundl@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: test_lround_i64_f80:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    subq $24, %rsp
; FASTISEL-X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; FASTISEL-X64-NEXT:    fstpt (%rsp)
; FASTISEL-X64-NEXT:    callq lroundl@PLT
; FASTISEL-X64-NEXT:    addq $24, %rsp
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: test_lround_i64_f80:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    subq $24, %rsp
; GISEL-X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; GISEL-X64-NEXT:    fstpt (%rsp)
; GISEL-X64-NEXT:    callq lroundl
; GISEL-X64-NEXT:    addq $24, %rsp
; GISEL-X64-NEXT:    retq
  %conv = call i64 @llvm.lround.i64.f80(x86_fp80 %x)
  ret i64 %conv
}
