; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=i386-linux-gnu                                   -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=NO-SSE,SDAG-NO-SSE
; RUN: llc -mtriple=i386-linux-gnu -fast-isel                        -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=NO-SSE,FAST-NO-SSE
; RUN: llc -mtriple=i386-linux-gnu -global-isel -global-isel-abort=1 -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=NO-SSE,GISEL-NO-SSE
; RUN: llc -mtriple=i386-linux-gnu                                   -mattr=+sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SSE,SDAG-SSE
; RUN: llc -mtriple=i386-linux-gnu -fast-isel                        -mattr=+sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SSE,FAST-SSE
; RUN: llc -mtriple=i386-linux-gnu -global-isel -global-isel-abort=1 -mattr=+sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SSE,GISEL-SSE
; RUN: llc -mtriple=i386-linux-gnu                                   -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX,SDAG-AVX
; RUN: llc -mtriple=i386-linux-gnu -fast-isel                        -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX,FAST-AVX
; RUN: llc -mtriple=i386-linux-gnu -global-isel -global-isel-abort=1 -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX,GISEL-AVX
; RUN: llc -mtriple=i386-linux-gnu                                   -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX512,SDAG-AVX512
; RUN: llc -mtriple=i386-linux-gnu -fast-isel                        -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX512,FAST-AVX512
; RUN: llc -mtriple=i386-linux-gnu -global-isel -global-isel-abort=1 -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX512,GISEL-AVX512

define ptr @inttoptr_p0_s32(i32 %val) {
; CHECK-LABEL: inttoptr_p0_s32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl 4(%esp), %eax
; CHECK-NEXT:    retl
; NO-SSE-LABEL: inttoptr_p0_s32:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; NO-SSE-NEXT:    retl
;
; SSE-LABEL: inttoptr_p0_s32:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SSE-NEXT:    retl
;
; AVX-LABEL: inttoptr_p0_s32:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    movl {{[0-9]+}}(%esp), %eax
; AVX-NEXT:    retl
;
; AVX512-LABEL: inttoptr_p0_s32:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    movl {{[0-9]+}}(%esp), %eax
; AVX512-NEXT:    retl
entry:
  %0 = inttoptr i32 %val to ptr
  ret ptr %0
}

define <4 x ptr> @inttoptr_v4p0_v4s32(<4 x i32> %val) {
; SDAG-NO-SSE-LABEL: inttoptr_v4p0_v4s32:
; SDAG-NO-SSE:       # %bb.0: # %entry
; SDAG-NO-SSE-NEXT:    pushl %edi
; SDAG-NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; SDAG-NO-SSE-NEXT:    pushl %esi
; SDAG-NO-SSE-NEXT:    .cfi_def_cfa_offset 12
; SDAG-NO-SSE-NEXT:    .cfi_offset %esi, -12
; SDAG-NO-SSE-NEXT:    .cfi_offset %edi, -8
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edx
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %esi
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edi
; SDAG-NO-SSE-NEXT:    movl %edi, 12(%eax)
; SDAG-NO-SSE-NEXT:    movl %esi, 8(%eax)
; SDAG-NO-SSE-NEXT:    movl %edx, 4(%eax)
; SDAG-NO-SSE-NEXT:    movl %ecx, (%eax)
; SDAG-NO-SSE-NEXT:    popl %esi
; SDAG-NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; SDAG-NO-SSE-NEXT:    popl %edi
; SDAG-NO-SSE-NEXT:    .cfi_def_cfa_offset 4
; SDAG-NO-SSE-NEXT:    retl $4
;
; FAST-NO-SSE-LABEL: inttoptr_v4p0_v4s32:
; FAST-NO-SSE:       # %bb.0: # %entry
; FAST-NO-SSE-NEXT:    pushl %edi
; FAST-NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; FAST-NO-SSE-NEXT:    pushl %esi
; FAST-NO-SSE-NEXT:    .cfi_def_cfa_offset 12
; FAST-NO-SSE-NEXT:    .cfi_offset %esi, -12
; FAST-NO-SSE-NEXT:    .cfi_offset %edi, -8
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edx
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %esi
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edi
; FAST-NO-SSE-NEXT:    movl %edi, (%eax)
; FAST-NO-SSE-NEXT:    movl %esi, 4(%eax)
; FAST-NO-SSE-NEXT:    movl %edx, 8(%eax)
; FAST-NO-SSE-NEXT:    movl %ecx, 12(%eax)
; FAST-NO-SSE-NEXT:    popl %esi
; FAST-NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; FAST-NO-SSE-NEXT:    popl %edi
; FAST-NO-SSE-NEXT:    .cfi_def_cfa_offset 4
; FAST-NO-SSE-NEXT:    retl $4
;
; GISEL-NO-SSE-LABEL: inttoptr_v4p0_v4s32:
; GISEL-NO-SSE:       # %bb.0: # %entry
; GISEL-NO-SSE-NEXT:    pushl %edi
; GISEL-NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; GISEL-NO-SSE-NEXT:    pushl %esi
; GISEL-NO-SSE-NEXT:    .cfi_def_cfa_offset 12
; GISEL-NO-SSE-NEXT:    .cfi_offset %esi, -12
; GISEL-NO-SSE-NEXT:    .cfi_offset %edi, -8
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edx
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %esi
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %edi
; GISEL-NO-SSE-NEXT:    movl %ecx, (%eax)
; GISEL-NO-SSE-NEXT:    movl %edx, 4(%eax)
; GISEL-NO-SSE-NEXT:    movl %esi, 8(%eax)
; GISEL-NO-SSE-NEXT:    movl %edi, 12(%eax)
; GISEL-NO-SSE-NEXT:    popl %esi
; GISEL-NO-SSE-NEXT:    .cfi_def_cfa_offset 8
; GISEL-NO-SSE-NEXT:    popl %edi
; GISEL-NO-SSE-NEXT:    .cfi_def_cfa_offset 4
; GISEL-NO-SSE-NEXT:    retl
;
; SSE-LABEL: inttoptr_v4p0_v4s32:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retl
;
; AVX-LABEL: inttoptr_v4p0_v4s32:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retl
;
; AVX512-LABEL: inttoptr_v4p0_v4s32:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retl
entry:
  %0 = inttoptr <4 x i32> %val to <4 x ptr>
  ret <4 x ptr> %0
}

define <8 x ptr> @inttoptr_v8p0_v8s32(<8 x i32> %val) {
; SDAG-NO-SSE-LABEL: inttoptr_v8p0_v8s32:
; SDAG-NO-SSE:       # %bb.0: # %entry
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, 28(%eax)
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, 24(%eax)
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, 20(%eax)
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, 16(%eax)
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, 12(%eax)
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, 8(%eax)
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, 4(%eax)
; SDAG-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; SDAG-NO-SSE-NEXT:    movl %ecx, (%eax)
; SDAG-NO-SSE-NEXT:    retl $4
;
; FAST-NO-SSE-LABEL: inttoptr_v8p0_v8s32:
; FAST-NO-SSE:       # %bb.0: # %entry
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, (%eax)
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, 4(%eax)
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, 8(%eax)
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, 12(%eax)
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, 16(%eax)
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, 20(%eax)
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, 24(%eax)
; FAST-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FAST-NO-SSE-NEXT:    movl %ecx, 28(%eax)
; FAST-NO-SSE-NEXT:    retl $4
;
; GISEL-NO-SSE-LABEL: inttoptr_v8p0_v8s32:
; GISEL-NO-SSE:       # %bb.0: # %entry
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, (%eax)
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, 4(%eax)
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, 8(%eax)
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, 12(%eax)
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, 16(%eax)
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, 20(%eax)
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, 24(%eax)
; GISEL-NO-SSE-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-NO-SSE-NEXT:    movl %ecx, 28(%eax)
; GISEL-NO-SSE-NEXT:    retl
;
; SSE-LABEL: inttoptr_v8p0_v8s32:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retl
;
; AVX-LABEL: inttoptr_v8p0_v8s32:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retl
;
; AVX512-LABEL: inttoptr_v8p0_v8s32:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retl
entry:
  %0 = inttoptr <8 x i32> %val to <8 x ptr>
  ret <8 x ptr> %0
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; FAST-AVX: {{.*}}
; FAST-AVX512: {{.*}}
; FAST-SSE: {{.*}}
; GISEL-AVX: {{.*}}
; GISEL-AVX512: {{.*}}
; GISEL-SSE: {{.*}}
; SDAG-AVX: {{.*}}
; SDAG-AVX512: {{.*}}
; SDAG-SSE: {{.*}}
