; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-linux-gnu                                   -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=NO-SSE,SDAG-NO-SSE
; RUN: llc -mtriple=x86_64-linux-gnu -fast-isel                        -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=NO-SSE,FAST-NO-SSE
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=1 -mattr=-sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=NO-SSE,GISEL-NO-SSE
; RUN: llc -mtriple=x86_64-linux-gnu                                   -mattr=+sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SSE,SDAG-SSE
; RUN: llc -mtriple=x86_64-linux-gnu -fast-isel                        -mattr=+sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SSE,FAST-SSE
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=1 -mattr=+sse2    -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=SSE,GISEL-SSE
; RUN: llc -mtriple=x86_64-linux-gnu                                   -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX,SDAG-AVX
; RUN: llc -mtriple=x86_64-linux-gnu -fast-isel                        -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX,FAST-AVX
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=1 -mattr=+avx     -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX,GISEL-AVX
; RUN: llc -mtriple=x86_64-linux-gnu                                   -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX512,SDAG-AVX512
; RUN: llc -mtriple=x86_64-linux-gnu -fast-isel                        -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX512,FAST-AVX512
; RUN: llc -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=1 -mattr=+avx512f -verify-machineinstrs < %s -o - | FileCheck %s --check-prefixes=AVX512,GISEL-AVX512

define ptr @inttoptr_p0_s64(i64 %val) {
; NO-SSE-LABEL: inttoptr_p0_s64:
; NO-SSE:       # %bb.0: # %entry
; NO-SSE-NEXT:    movq %rdi, %rax
; NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_p0_s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    movq %rdi, %rax
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_p0_s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    movq %rdi, %rax
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_p0_s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    movq %rdi, %rax
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr i64 %val to ptr
  ret ptr %0
}

define <2 x ptr> @inttoptr_v2p0_v2s64(<2 x i64> %val) {
; CHECK-LABEL: inttoptr_v2p0_v2s64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    retq
; SDAG-NO-SSE-LABEL: inttoptr_v2p0_v2s64:
; SDAG-NO-SSE:       # %bb.0: # %entry
; SDAG-NO-SSE-NEXT:    movq %rsi, %rdx
; SDAG-NO-SSE-NEXT:    movq %rdi, %rax
; SDAG-NO-SSE-NEXT:    retq
;
; FAST-NO-SSE-LABEL: inttoptr_v2p0_v2s64:
; FAST-NO-SSE:       # %bb.0: # %entry
; FAST-NO-SSE-NEXT:    movq %rsi, %rdx
; FAST-NO-SSE-NEXT:    movq %rdi, %rax
; FAST-NO-SSE-NEXT:    retq
;
; GISEL-NO-SSE-LABEL: inttoptr_v2p0_v2s64:
; GISEL-NO-SSE:       # %bb.0: # %entry
; GISEL-NO-SSE-NEXT:    movq %rdi, %rax
; GISEL-NO-SSE-NEXT:    movq %rsi, %rdx
; GISEL-NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_v2p0_v2s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_v2p0_v2s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_v2p0_v2s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr <2 x i64> %val to <2 x ptr>
  ret <2 x ptr> %0
}

define <4 x ptr> @inttoptr_v4p0_v4s64(<4 x i64> %val) {
; SDAG-NO-SSE-LABEL: inttoptr_v4p0_v4s64:
; SDAG-NO-SSE:       # %bb.0: # %entry
; SDAG-NO-SSE-NEXT:    movq %rdi, %rax
; SDAG-NO-SSE-NEXT:    movq %r8, 24(%rdi)
; SDAG-NO-SSE-NEXT:    movq %rcx, 16(%rdi)
; SDAG-NO-SSE-NEXT:    movq %rdx, 8(%rdi)
; SDAG-NO-SSE-NEXT:    movq %rsi, (%rdi)
; SDAG-NO-SSE-NEXT:    retq
;
; FAST-NO-SSE-LABEL: inttoptr_v4p0_v4s64:
; FAST-NO-SSE:       # %bb.0: # %entry
; FAST-NO-SSE-NEXT:    movq %rdi, %rax
; FAST-NO-SSE-NEXT:    movq %rsi, (%rdi)
; FAST-NO-SSE-NEXT:    movq %rdx, 8(%rdi)
; FAST-NO-SSE-NEXT:    movq %rcx, 16(%rdi)
; FAST-NO-SSE-NEXT:    movq %r8, 24(%rdi)
; FAST-NO-SSE-NEXT:    retq
;
; GISEL-NO-SSE-LABEL: inttoptr_v4p0_v4s64:
; GISEL-NO-SSE:       # %bb.0: # %entry
; GISEL-NO-SSE-NEXT:    movq %rdi, %rax
; GISEL-NO-SSE-NEXT:    movq %rsi, (%rdi)
; GISEL-NO-SSE-NEXT:    movq %rdx, 8(%rdi)
; GISEL-NO-SSE-NEXT:    movq %rcx, 16(%rdi)
; GISEL-NO-SSE-NEXT:    movq %r8, 24(%rdi)
; GISEL-NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_v4p0_v4s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_v4p0_v4s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_v4p0_v4s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr <4 x i64> %val to <4 x ptr>
  ret <4 x ptr> %0
}

define <8 x ptr> @inttoptr_v8p0_v8s64(<8 x i64> %val) {
; SDAG-NO-SSE-LABEL: inttoptr_v8p0_v8s64:
; SDAG-NO-SSE:       # %bb.0: # %entry
; SDAG-NO-SSE-NEXT:    movq %rdi, %rax
; SDAG-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; SDAG-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; SDAG-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r11
; SDAG-NO-SSE-NEXT:    movq %r11, 56(%rax)
; SDAG-NO-SSE-NEXT:    movq %r10, 48(%rax)
; SDAG-NO-SSE-NEXT:    movq %rdi, 40(%rax)
; SDAG-NO-SSE-NEXT:    movq %r9, 32(%rax)
; SDAG-NO-SSE-NEXT:    movq %r8, 24(%rax)
; SDAG-NO-SSE-NEXT:    movq %rcx, 16(%rax)
; SDAG-NO-SSE-NEXT:    movq %rdx, 8(%rax)
; SDAG-NO-SSE-NEXT:    movq %rsi, (%rax)
; SDAG-NO-SSE-NEXT:    retq
;
; FAST-NO-SSE-LABEL: inttoptr_v8p0_v8s64:
; FAST-NO-SSE:       # %bb.0: # %entry
; FAST-NO-SSE-NEXT:    movq %rdi, %rax
; FAST-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; FAST-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; FAST-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r11
; FAST-NO-SSE-NEXT:    movq %rsi, (%rax)
; FAST-NO-SSE-NEXT:    movq %rdx, 8(%rax)
; FAST-NO-SSE-NEXT:    movq %rcx, 16(%rax)
; FAST-NO-SSE-NEXT:    movq %r8, 24(%rax)
; FAST-NO-SSE-NEXT:    movq %r9, 32(%rax)
; FAST-NO-SSE-NEXT:    movq %r11, 40(%rax)
; FAST-NO-SSE-NEXT:    movq %r10, 48(%rax)
; FAST-NO-SSE-NEXT:    movq %rdi, 56(%rax)
; FAST-NO-SSE-NEXT:    retq
;
; GISEL-NO-SSE-LABEL: inttoptr_v8p0_v8s64:
; GISEL-NO-SSE:       # %bb.0: # %entry
; GISEL-NO-SSE-NEXT:    movq %rdi, %rax
; GISEL-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %rdi
; GISEL-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r10
; GISEL-NO-SSE-NEXT:    movq {{[0-9]+}}(%rsp), %r11
; GISEL-NO-SSE-NEXT:    movq %rsi, (%rax)
; GISEL-NO-SSE-NEXT:    movq %rdx, 8(%rax)
; GISEL-NO-SSE-NEXT:    movq %rcx, 16(%rax)
; GISEL-NO-SSE-NEXT:    movq %r8, 24(%rax)
; GISEL-NO-SSE-NEXT:    movq %r9, 32(%rax)
; GISEL-NO-SSE-NEXT:    movq %rdi, 40(%rax)
; GISEL-NO-SSE-NEXT:    movq %r10, 48(%rax)
; GISEL-NO-SSE-NEXT:    movq %r11, 56(%rax)
; GISEL-NO-SSE-NEXT:    retq
;
; SSE-LABEL: inttoptr_v8p0_v8s64:
; SSE:       # %bb.0: # %entry
; SSE-NEXT:    retq
;
; AVX-LABEL: inttoptr_v8p0_v8s64:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    retq
;
; AVX512-LABEL: inttoptr_v8p0_v8s64:
; AVX512:       # %bb.0: # %entry
; AVX512-NEXT:    retq
entry:
  %0 = inttoptr <8 x i64> %val to <8 x ptr>
  ret <8 x ptr> %0
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; FAST-AVX: {{.*}}
; FAST-AVX512: {{.*}}
; FAST-SSE: {{.*}}
; GISEL-AVX: {{.*}}
; GISEL-AVX512: {{.*}}
; GISEL-SSE: {{.*}}
; SDAG-AVX: {{.*}}
; SDAG-AVX512: {{.*}}
; SDAG-SSE: {{.*}}
