; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-linux-gnu -mattr=+sse4.1 | FileCheck %s --check-prefixes=X64,SDAG-ISEL
; RUN: llc < %s -mtriple=x86_64-linux-gnu -fast-isel -mattr=+sse4.1 | FileCheck %s --check-prefixes=X64,FAST-ISEL
; RUN: llc < %s -mtriple=x86_64-linux-gnu -global-isel -mattr=+sse4.1 | FileCheck %s --check-prefixes=X64,GLOBAL-ISEL

; RUN: llc < %s -mtriple=x86_64-linux-gnu -mattr=+avx | FileCheck %s --check-prefixes=X64,SDAG-AVX
; RUN: llc < %s -mtriple=x86_64-linux-gnu -fast-isel -mattr=+avx | FileCheck %s --check-prefixes=X64,FAST-AVX
; RUN: llc < %s -mtriple=x86_64-linux-gnu -global-isel -mattr=+avx2| FileCheck %s --check-prefixes=X64,GLOBAL-AVX

; NORUN: llc < %s -mtriple=x86_64-linux-gnu -mattr=+avx512f | FileCheck %s --check-prefixes=X64,SDAG-AVX512F
; NORUN: llc < %s -mtriple=x86_64-linux-gnu -fast-isel -mattr=+avx512f | FileCheck %s --check-prefixes=X64,FAST-AVX512F
; NORUN: llc < %s -mtriple=x86_64-linux-gnu -global-isel -mattr=+avx512f | FileCheck %s --check-prefixes=X64,GLOBAL-AVX512F

; SHUF

; Single source: both operands same register, mask <1, 0> =>imm 1
define <2 x double> @shufpd_v2f64_single_source(<2 x double> %a) nounwind {
; SDAG-ISEL-LABEL: shufpd_v2f64_single_source:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: shufpd_v2f64_single_source:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: shufpd_v2f64_single_source:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: shufpd_v2f64_single_source:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: shufpd_v2f64_single_source:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: shufpd_v2f64_single_source:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <2 x double> %a, <2 x double> %a, <2 x i32> <i32 1, i32 0>
  ret <2 x double> %s
}

; Single source: undef second operand, mask <1, 0> =>imm 1
define <2 x double> @shufpd_v2f64_undef_src2(<2 x double> %a) nounwind {
; SDAG-ISEL-LABEL: shufpd_v2f64_undef_src2:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: shufpd_v2f64_undef_src2:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: shufpd_v2f64_undef_src2:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: shufpd_v2f64_undef_src2:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: shufpd_v2f64_undef_src2:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[1,0]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: shufpd_v2f64_undef_src2:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <2 x double> %a, <2 x double> undef, <2 x i32> <i32 1, i32 0>
  ret <2 x double> %s
}

; Two sources: elem0=src1[0], elem1=src2[1], mask <0, 3> =>imm 2
define <2 x double> @shufpd_v2f64_two_source(<2 x double> %a, <2 x double> %b) nounwind {
; SDAG-ISEL-LABEL: shufpd_v2f64_two_source:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    blendps {{.*#+}} xmm0 = xmm0[0,1],xmm1[2,3]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: shufpd_v2f64_two_source:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    blendps {{.*#+}} xmm0 = xmm0[0,1],xmm1[2,3]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: shufpd_v2f64_two_source:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: shufpd_v2f64_two_source:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovsd {{.*#+}} xmm0 = xmm0[0],xmm1[1]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: shufpd_v2f64_two_source:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vmovsd {{.*#+}} xmm0 = xmm0[0],xmm1[1]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: shufpd_v2f64_two_source:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 0, i32 3>
  ret <2 x double> %s
}

; Two sources with swap: elem0=src2[0], elem1=src1[1], mask <2, 1> =>imm 2 (swapped)
define <2 x double> @shufpd_v2f64_swap(<2 x double> %a, <2 x double> %b) nounwind {
; SDAG-ISEL-LABEL: shufpd_v2f64_swap:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    movsd {{.*#+}} xmm0 = xmm1[0],xmm0[1]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: shufpd_v2f64_swap:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    movsd {{.*#+}} xmm0 = xmm1[0],xmm0[1]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: shufpd_v2f64_swap:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: shufpd_v2f64_swap:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovsd {{.*#+}} xmm0 = xmm1[0],xmm0[1]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: shufpd_v2f64_swap:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vmovsd {{.*#+}} xmm0 = xmm1[0],xmm0[1]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: shufpd_v2f64_swap:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 2, i32 1>
  ret <2 x double> %s
}

; Single source: reverse <3, 2, 1, 0> =>imm 27
define <4 x float> @shufps_v4f32_single_source(<4 x float> %a) nounwind {
; SDAG-ISEL-LABEL: shufps_v4f32_single_source:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,2,1,0]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: shufps_v4f32_single_source:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,2,1,0]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: shufps_v4f32_single_source:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: shufps_v4f32_single_source:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,2,1,0]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: shufps_v4f32_single_source:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vshufps {{.*#+}} xmm0 = xmm0[3,2,1,0]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: shufps_v4f32_single_source:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <4 x float> %a, <4 x float> %a, <4 x i32> <i32 3, i32 2, i32 1, i32 0>
  ret <4 x float> %s
}

; Two sources: low from src1, high from src2, mask <0, 1, 4, 5> =>imm 68
define <4 x float> @shufps_v4f32_two_source(<4 x float> %a, <4 x float> %b) nounwind {
; SDAG-ISEL-LABEL: shufps_v4f32_two_source:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    movlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: shufps_v4f32_two_source:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    movlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: shufps_v4f32_two_source:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: shufps_v4f32_two_source:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: shufps_v4f32_two_source:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: shufps_v4f32_two_source:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <4 x float> %a, <4 x float> %b, <4 x i32> <i32 0, i32 1, i32 4, i32 5>
  ret <4 x float> %s
}

; BLENDV

; Blend v4f32: elem0 from src2, elem1-2 from src1, elem3 from src2.
; Mixed within low/high halves so SHUFPS cannot match =>falls through to BLENDV.
define <4 x float> @blendv_v4f32(<4 x float> %a, <4 x float> %b) nounwind {
; SDAG-ISEL-LABEL: blendv_v4f32:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    blendps {{.*#+}} xmm0 = xmm1[0],xmm0[1,2],xmm1[3]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: blendv_v4f32:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    blendps {{.*#+}} xmm0 = xmm1[0],xmm0[1,2],xmm1[3]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: blendv_v4f32:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: blendv_v4f32:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vblendps {{.*#+}} xmm0 = xmm1[0],xmm0[1,2],xmm1[3]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: blendv_v4f32:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vblendps {{.*#+}} xmm0 = xmm1[0],xmm0[1,2],xmm1[3]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: blendv_v4f32:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <4 x float> %a, <4 x float> %b, <4 x i32> <i32 4, i32 1, i32 2, i32 7>
  ret <4 x float> %s
}

; Blend v8i16: 16-bit elements, SHUFP doesn't apply =>BLENDV is the only path.
define <8 x i16> @blendv_v8i16(<8 x i16> %a, <8 x i16> %b) nounwind {
; SDAG-ISEL-LABEL: blendv_v8i16:
; SDAG-ISEL:       # %bb.0:
; SDAG-ISEL-NEXT:    pblendw {{.*#+}} xmm0 = xmm1[0],xmm0[1,2,3,4,5,6],xmm1[7]
; SDAG-ISEL-NEXT:    retq
;
; FAST-ISEL-LABEL: blendv_v8i16:
; FAST-ISEL:       # %bb.0:
; FAST-ISEL-NEXT:    pblendw {{.*#+}} xmm0 = xmm1[0],xmm0[1,2,3,4,5,6],xmm1[7]
; FAST-ISEL-NEXT:    retq
;
; GLOBAL-ISEL-LABEL: blendv_v8i16:
; GLOBAL-ISEL:       # %bb.0:
; GLOBAL-ISEL-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-ISEL-NEXT:    retq
;
; SDAG-AVX-LABEL: blendv_v8i16:
; SDAG-AVX:       # %bb.0:
; SDAG-AVX-NEXT:    vpblendw {{.*#+}} xmm0 = xmm1[0],xmm0[1,2,3,4,5,6],xmm1[7]
; SDAG-AVX-NEXT:    retq
;
; FAST-AVX-LABEL: blendv_v8i16:
; FAST-AVX:       # %bb.0:
; FAST-AVX-NEXT:    vpblendw {{.*#+}} xmm0 = xmm1[0],xmm0[1,2,3,4,5,6],xmm1[7]
; FAST-AVX-NEXT:    retq
;
; GLOBAL-AVX-LABEL: blendv_v8i16:
; GLOBAL-AVX:       # %bb.0:
; GLOBAL-AVX-NEXT:    shufps {{.*#+}} xmm0 = xmm0[2,3,0,1]
; GLOBAL-AVX-NEXT:    retq
  %s = shufflevector <8 x i16> %a, <8 x i16> %b, <8 x i32> <i32 8, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 15>
  ret <8 x i16> %s
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; X64: {{.*}}
