; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+sse2 -verify-machineinstrs | FileCheck %s --check-prefixes=X64,SDAG-X64-SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx -verify-machineinstrs | FileCheck %s --check-prefixes=X64,SDAG-X64-AVX
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx2 -verify-machineinstrs | FileCheck %s --check-prefixes=X64,SDAG-X64-AVX2

; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+sse2 -global-isel -verify-machineinstrs | FileCheck %s --check-prefixes=X64,GISEL-X64-SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx -global-isel -verify-machineinstrs | FileCheck %s --check-prefixes=X64,GISEL-X64-AVX
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx2 -global-isel -verify-machineinstrs | FileCheck %s --check-prefixes=X64,GISEL-X64-AVX2


define <2 x double> @shuffle_op2_double(<2 x double> %a, <2 x double> %b) {
; SDAG-X64-SSE2-LABEL: shuffle_op2_double:
; SDAG-X64-SSE2:       # %bb.0:
; SDAG-X64-SSE2-NEXT:    movlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-X64-SSE2-NEXT:    retq
;
; SDAG-X64-AVX-LABEL: shuffle_op2_double:
; SDAG-X64-AVX:       # %bb.0:
; SDAG-X64-AVX-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-X64-AVX-NEXT:    retq
;
; SDAG-X64-AVX2-LABEL: shuffle_op2_double:
; SDAG-X64-AVX2:       # %bb.0:
; SDAG-X64-AVX2-NEXT:    vmovlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; SDAG-X64-AVX2-NEXT:    retq
;
; GISEL-X64-SSE2-LABEL: shuffle_op2_double:
; GISEL-X64-SSE2:       # %bb.0:
; GISEL-X64-SSE2-NEXT:    shufps {{.*#+}} xmm0 = xmm0[0,1],xmm1[0,1]
; GISEL-X64-SSE2-NEXT:    retq
;
; GISEL-X64-AVX-LABEL: shuffle_op2_double:
; GISEL-X64-AVX:       # %bb.0:
; GISEL-X64-AVX-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; GISEL-X64-AVX-NEXT:    retq
;
; GISEL-X64-AVX2-LABEL: shuffle_op2_double:
; GISEL-X64-AVX2:       # %bb.0:
; GISEL-X64-AVX2-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; GISEL-X64-AVX2-NEXT:    retq
  %result = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 0, i32 2>
  ret <2 x double> %result
}
