; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -combiner-topological-sorting < %s -O0 -mtriple=i686-linux-gnu -global-isel=0 -verify-machineinstrs | FileCheck %s --check-prefix=DAG
; RUN: llc -combiner-topological-sorting < %s -O0 -mtriple=i686-linux-gnu -fast-isel -fast-isel-abort=1        | FileCheck %s --check-prefix=DAG
; RUN: llc -combiner-topological-sorting < %s -O0 -mtriple=i686-linux-gnu -global-isel -global-isel-abort=1 -verify-machineinstrs | FileCheck %s --check-prefix=GISEL
; RUN: llc -combiner-topological-sorting < %s -O0 -mtriple=x86_64-linux-gnu -global-isel=0                     | FileCheck %s --check-prefix=DAG
; RUN: llc -combiner-topological-sorting < %s -O0 -mtriple=x86_64-linux-gnu -fast-isel -fast-isel-abort=1      | FileCheck %s --check-prefix=DAG
; RUN: llc -combiner-topological-sorting < %s -O0 -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=1  | FileCheck %s --check-prefix=GISEL

define void @uncondbr() {
; DAG-LABEL: uncondbr:
; DAG:       # %bb.0: # %entry
; DAG-NEXT:    jmp .LBB0_2
; DAG-NEXT:  .LBB0_1: # %end
; DAG-NEXT:    ret{{[l|q]}}
; DAG-NEXT:  .LBB0_2: # %bb2
; DAG-NEXT:    jmp .LBB0_1
;
; GISEL-LABEL: uncondbr:
; GISEL:       # %bb.1: # %entry
; GISEL-NEXT:    jmp .LBB0_3
; GISEL-NEXT:  .LBB0_2: # %end
; GISEL-NEXT:    ret{{[l|q]}}
; GISEL-NEXT:  .LBB0_3: # %bb2
; GISEL-NEXT:    jmp .LBB0_2
entry:
  br label %bb2
end:
  ret void
bb2:
  br label %end
}
