; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-linux-gnu | FileCheck %s --check-prefixes=X64,DAG-X64
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-linux-gnu -fast-isel | FileCheck %s --check-prefixes=X64,FASTISEL-X64
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=1 | FileCheck %s --check-prefixes=GISEL-X64
; RUN: llc -combiner-topological-sorting < %s -mtriple=i686-linux-gnu | FileCheck %s --check-prefixes=X86,DAG-X86
; RUN: llc -combiner-topological-sorting < %s -mtriple=i686-linux-gnu -fast-isel | FileCheck %s --check-prefixes=X86,FASTISEL-X86
; RUN: llc -combiner-topological-sorting < %s -mtriple=i686-linux-gnu -global-isel -global-isel-abort=1 | FileCheck %s --check-prefixes=GISEL-X86

define i8 @smax_i8(i8 %a, i8 %b) nounwind readnone {
; DAG-X64-LABEL: smax_i8:
; DAG-X64:       # %bb.0:
; DAG-X64-NEXT:    movl %esi, %eax
; DAG-X64-NEXT:    cmpb %al, %dil
; DAG-X64-NEXT:    cmovgl %edi, %eax
; DAG-X64-NEXT:    # kill: def $al killed $al killed $eax
; DAG-X64-NEXT:    retq
;
; FASTISEL-X64-LABEL: smax_i8:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    movzbl %dil, %ecx
; FASTISEL-X64-NEXT:    movzbl %sil, %eax
; FASTISEL-X64-NEXT:    cmpb %al, %cl
; FASTISEL-X64-NEXT:    cmovgl %ecx, %eax
; FASTISEL-X64-NEXT:    # kill: def $al killed $al killed $eax
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: smax_i8:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movl %esi, %eax
; GISEL-X64-NEXT:    xorl %ecx, %ecx
; GISEL-X64-NEXT:    cmpb %al, %dil
; GISEL-X64-NEXT:    setg %cl
; GISEL-X64-NEXT:    andl $1, %ecx
; GISEL-X64-NEXT:    cmovnew %di, %ax
; GISEL-X64-NEXT:    # kill: def $al killed $al killed $eax
; GISEL-X64-NEXT:    retq
;
; X86-LABEL: smax_i8:
; X86:       # %bb.0:
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpb %cl, %al
; X86-NEXT:    jg .LBB0_2
; X86-NEXT:  # %bb.1:
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:  .LBB0_2:
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: smax_i8:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    movzbl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movzbl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    xorl %edx, %edx
; GISEL-X86-NEXT:    cmpb %al, %cl
; GISEL-X86-NEXT:    setg %dl
; GISEL-X86-NEXT:    andl $1, %edx
; GISEL-X86-NEXT:    je .LBB0_2
; GISEL-X86-NEXT:  # %bb.1:
; GISEL-X86-NEXT:    movl %ecx, %eax
; GISEL-X86-NEXT:  .LBB0_2:
; GISEL-X86-NEXT:    # kill: def $al killed $al killed $eax
; GISEL-X86-NEXT:    retl
    %ret = call i8 @llvm.smax.i8(i8 %a, i8 %b)
    ret i8 %ret
}
define i16 @smax_i16(i16 %a, i16 %b) nounwind readnone {
; X64-LABEL: smax_i16:
; X64:       # %bb.0:
; X64-NEXT:    movl %esi, %eax
; X64-NEXT:    cmpw %ax, %di
; X64-NEXT:    cmovgl %edi, %eax
; X64-NEXT:    # kill: def $ax killed $ax killed $eax
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: smax_i16:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movl %edi, %eax
; GISEL-X64-NEXT:    xorl %ecx, %ecx
; GISEL-X64-NEXT:    cmpw %si, %ax
; GISEL-X64-NEXT:    setg %cl
; GISEL-X64-NEXT:    andl $1, %ecx
; GISEL-X64-NEXT:    cmovew %si, %ax
; GISEL-X64-NEXT:    # kill: def $ax killed $ax killed $eax
; GISEL-X64-NEXT:    retq
;
; DAG-X86-LABEL: smax_i16:
; DAG-X86:       # %bb.0:
; DAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; DAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; DAG-X86-NEXT:    cmpw %cx, %ax
; DAG-X86-NEXT:    jg .LBB1_2
; DAG-X86-NEXT:  # %bb.1:
; DAG-X86-NEXT:    movl %ecx, %eax
; DAG-X86-NEXT:  .LBB1_2:
; DAG-X86-NEXT:    # kill: def $ax killed $ax killed $eax
; DAG-X86-NEXT:    retl
;
; FASTISEL-X86-LABEL: smax_i16:
; FASTISEL-X86:       # %bb.0:
; FASTISEL-X86-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; FASTISEL-X86-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; FASTISEL-X86-NEXT:    cmpw %cx, %ax
; FASTISEL-X86-NEXT:    jg .LBB1_2
; FASTISEL-X86-NEXT:  # %bb.1:
; FASTISEL-X86-NEXT:    movl %ecx, %eax
; FASTISEL-X86-NEXT:  .LBB1_2:
; FASTISEL-X86-NEXT:    # kill: def $ax killed $ax killed $eax
; FASTISEL-X86-NEXT:    retl
;
; GISEL-X86-LABEL: smax_i16:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    xorl %edx, %edx
; GISEL-X86-NEXT:    cmpw %ax, %cx
; GISEL-X86-NEXT:    setg %dl
; GISEL-X86-NEXT:    andl $1, %edx
; GISEL-X86-NEXT:    je .LBB1_2
; GISEL-X86-NEXT:  # %bb.1:
; GISEL-X86-NEXT:    movl %ecx, %eax
; GISEL-X86-NEXT:  .LBB1_2:
; GISEL-X86-NEXT:    # kill: def $ax killed $ax killed $eax
; GISEL-X86-NEXT:    retl
    %ret = call i16 @llvm.smax.i16(i16 %a, i16 %b)
    ret i16 %ret
}
define i32 @smax_i32(i32 %a, i32 %b) nounwind readnone {
; X64-LABEL: smax_i32:
; X64:       # %bb.0:
; X64-NEXT:    movl %esi, %eax
; X64-NEXT:    cmpl %esi, %edi
; X64-NEXT:    cmovgl %edi, %eax
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: smax_i32:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movl %edi, %eax
; GISEL-X64-NEXT:    xorl %ecx, %ecx
; GISEL-X64-NEXT:    cmpl %esi, %edi
; GISEL-X64-NEXT:    setg %cl
; GISEL-X64-NEXT:    andl $1, %ecx
; GISEL-X64-NEXT:    cmovel %esi, %eax
; GISEL-X64-NEXT:    retq
;
; X86-LABEL: smax_i32:
; X86:       # %bb.0:
; X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    cmpl %ecx, %eax
; X86-NEXT:    jg .LBB2_2
; X86-NEXT:  # %bb.1:
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:  .LBB2_2:
; X86-NEXT:    retl
;
; GISEL-X86-LABEL: smax_i32:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    xorl %edx, %edx
; GISEL-X86-NEXT:    cmpl %eax, %ecx
; GISEL-X86-NEXT:    setg %dl
; GISEL-X86-NEXT:    andl $1, %edx
; GISEL-X86-NEXT:    je .LBB2_2
; GISEL-X86-NEXT:  # %bb.1:
; GISEL-X86-NEXT:    movl %ecx, %eax
; GISEL-X86-NEXT:  .LBB2_2:
; GISEL-X86-NEXT:    retl
    %ret = call i32 @llvm.smax.i32(i32 %a, i32 %b)
    ret i32 %ret
}
define i64 @smax_i64(i64 %a, i64 %b) nounwind readnone {
; X64-LABEL: smax_i64:
; X64:       # %bb.0:
; X64-NEXT:    movq %rsi, %rax
; X64-NEXT:    cmpq %rsi, %rdi
; X64-NEXT:    cmovgq %rdi, %rax
; X64-NEXT:    retq
;
; GISEL-X64-LABEL: smax_i64:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    movq %rdi, %rax
; GISEL-X64-NEXT:    xorl %ecx, %ecx
; GISEL-X64-NEXT:    cmpq %rsi, %rdi
; GISEL-X64-NEXT:    setg %cl
; GISEL-X64-NEXT:    andl $1, %ecx
; GISEL-X64-NEXT:    cmoveq %rsi, %rax
; GISEL-X64-NEXT:    retq
;
; DAG-X86-LABEL: smax_i64:
; DAG-X86:       # %bb.0:
; DAG-X86-NEXT:    pushl %edi
; DAG-X86-NEXT:    pushl %esi
; DAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; DAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; DAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; DAG-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; DAG-X86-NEXT:    cmpl %eax, %ecx
; DAG-X86-NEXT:    movl %esi, %edi
; DAG-X86-NEXT:    sbbl %edx, %edi
; DAG-X86-NEXT:    jl .LBB3_2
; DAG-X86-NEXT:  # %bb.1:
; DAG-X86-NEXT:    movl %ecx, %eax
; DAG-X86-NEXT:    movl %esi, %edx
; DAG-X86-NEXT:  .LBB3_2:
; DAG-X86-NEXT:    popl %esi
; DAG-X86-NEXT:    popl %edi
; DAG-X86-NEXT:    retl
;
; FASTISEL-X86-LABEL: smax_i64:
; FASTISEL-X86:       # %bb.0:
; FASTISEL-X86-NEXT:    pushl %edi
; FASTISEL-X86-NEXT:    pushl %esi
; FASTISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; FASTISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; FASTISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; FASTISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; FASTISEL-X86-NEXT:    cmpl %eax, %esi
; FASTISEL-X86-NEXT:    movl %ecx, %edi
; FASTISEL-X86-NEXT:    sbbl %edx, %edi
; FASTISEL-X86-NEXT:    jl .LBB3_2
; FASTISEL-X86-NEXT:  # %bb.1:
; FASTISEL-X86-NEXT:    movl %esi, %eax
; FASTISEL-X86-NEXT:    movl %ecx, %edx
; FASTISEL-X86-NEXT:  .LBB3_2:
; FASTISEL-X86-NEXT:    popl %esi
; FASTISEL-X86-NEXT:    popl %edi
; FASTISEL-X86-NEXT:    retl
;
; GISEL-X86-LABEL: smax_i64:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    pushl %ebp
; GISEL-X86-NEXT:    pushl %ebx
; GISEL-X86-NEXT:    pushl %edi
; GISEL-X86-NEXT:    pushl %esi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %esi
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ebp
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %edx
; GISEL-X86-NEXT:    cmpl %eax, %esi
; GISEL-X86-NEXT:    seta %bl
; GISEL-X86-NEXT:    xorl %ecx, %ecx
; GISEL-X86-NEXT:    cmpl %edx, %ebp
; GISEL-X86-NEXT:    setg %bh
; GISEL-X86-NEXT:    sete %cl
; GISEL-X86-NEXT:    testl %ecx, %ecx
; GISEL-X86-NEXT:    je .LBB3_2
; GISEL-X86-NEXT:  # %bb.1:
; GISEL-X86-NEXT:    movb %bl, %bh
; GISEL-X86-NEXT:  .LBB3_2:
; GISEL-X86-NEXT:    movzbl %bh, %edi
; GISEL-X86-NEXT:    andl $1, %edi
; GISEL-X86-NEXT:    je .LBB3_4
; GISEL-X86-NEXT:  # %bb.3:
; GISEL-X86-NEXT:    movl %esi, %eax
; GISEL-X86-NEXT:  .LBB3_4:
; GISEL-X86-NEXT:    testl %edi, %edi
; GISEL-X86-NEXT:    je .LBB3_6
; GISEL-X86-NEXT:  # %bb.5:
; GISEL-X86-NEXT:    movl %ebp, %edx
; GISEL-X86-NEXT:  .LBB3_6:
; GISEL-X86-NEXT:    popl %esi
; GISEL-X86-NEXT:    popl %edi
; GISEL-X86-NEXT:    popl %ebx
; GISEL-X86-NEXT:    popl %ebp
; GISEL-X86-NEXT:    retl
    %ret = call i64 @llvm.smax.i64(i64 %a, i64 %b)
    ret i64 %ret
}
