; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; NOTE: Fast Isel is not added because it does not support x87 stores.

; RUN: llc < %s -mtriple=x86_64-- -mattr=+x87,-sse,-sse2 -global-isel=0 | FileCheck %s --check-prefixes X64,SDAG-X64
; RUN: llc < %s -mtriple=x86_64-- -mattr=+x87,-sse,-sse2 -global-isel -global-isel-abort=2 | FileCheck %s --check-prefixes X64,GISEL-X64
; RUN: llc < %s -mtriple=i686-linux-gnu -mattr=+x87,-sse,-sse2 -global-isel=0 | FileCheck %s --check-prefixes I686,SDAG-I686
; RUN: llc < %s -mtriple=i686-linux-gnu -mattr=+x87,-sse,-sse2 -global-isel -global-isel-abort=2 | FileCheck %s --check-prefixes I686,GISEL-I686

define void @test_int8_to_float(i8 %x, ptr %p) nounwind {
; X64-LABEL: test_int8_to_float:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movsbl %dil, %eax
; X64-NEXT:    movw %ax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    filds -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstps (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int8_to_float:
; I686:       # %bb.0: # %entry
; I686-NEXT:    pushl %eax
; I686-NEXT:    movsbl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; I686-NEXT:    movw %ax, {{[0-9]+}}(%esp)
; I686-NEXT:    filds {{[0-9]+}}(%esp)
; I686-NEXT:    fstps (%ecx)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
entry:
  %conv = sitofp i8 %x to float
  store float %conv, ptr %p, align 4
  ret void
}

define void @test_int16_to_float(i16 %x, ptr %p) nounwind {
; X64-LABEL: test_int16_to_float:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movw %di, -{{[0-9]+}}(%rsp)
; X64-NEXT:    filds -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstps (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int16_to_float:
; I686:       # %bb.0: # %entry
; I686-NEXT:    pushl %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; I686-NEXT:    movw %cx, {{[0-9]+}}(%esp)
; I686-NEXT:    filds {{[0-9]+}}(%esp)
; I686-NEXT:    fstps (%eax)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
entry:
  %conv = sitofp i16 %x to float
  store float %conv, ptr %p, align 4
  ret void
}

define void @test_int32_to_float(i32 %x, ptr %p) nounwind {
; X64-LABEL: test_int32_to_float:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movl %edi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fildl -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstps (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int32_to_float:
; I686:       # %bb.0: # %entry
; I686-NEXT:    pushl %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; I686-NEXT:    movl %ecx, (%esp)
; I686-NEXT:    fildl (%esp)
; I686-NEXT:    fstps (%eax)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
entry:
  %conv = sitofp i32 %x to float
  store float %conv, ptr %p, align 4
  ret void
}

define void @test_int64_to_float(i64 %x, ptr %p) nounwind {
; X64-LABEL: test_int64_to_float:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fildll -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstps (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int64_to_float:
; I686:       # %bb.0: # %entry
; I686-NEXT:    movl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    fildll {{[0-9]+}}(%esp)
; I686-NEXT:    fstps (%eax)
; I686-NEXT:    retl
entry:
  %conv = sitofp i64 %x to float
  store float %conv, ptr %p, align 4
  ret void
}

define x86_fp80 @test_int8to_longdouble(i8 %a) nounwind {
; X64-LABEL: test_int8to_longdouble:
; X64:       # %bb.0:
; X64-NEXT:    movsbl %dil, %eax
; X64-NEXT:    movw %ax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    filds -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
;
; I686-LABEL: test_int8to_longdouble:
; I686:       # %bb.0:
; I686-NEXT:    pushl %eax
; I686-NEXT:    movsbl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movw %ax, {{[0-9]+}}(%esp)
; I686-NEXT:    filds {{[0-9]+}}(%esp)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
  %conv = sitofp i8 %a to x86_fp80
  ret x86_fp80 %conv
}

define x86_fp80 @test_int16_to_longdouble(i16 %a) nounwind {
; X64-LABEL: test_int16_to_longdouble:
; X64:       # %bb.0:
; X64-NEXT:    movw %di, -{{[0-9]+}}(%rsp)
; X64-NEXT:    filds -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
;
; I686-LABEL: test_int16_to_longdouble:
; I686:       # %bb.0:
; I686-NEXT:    pushl %eax
; I686-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movw %ax, {{[0-9]+}}(%esp)
; I686-NEXT:    filds {{[0-9]+}}(%esp)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
  %conv = sitofp i16 %a to x86_fp80
  ret x86_fp80 %conv
}

define x86_fp80 @test_int32_to_longdouble(i32 %a) nounwind {
; X64-LABEL: test_int32_to_longdouble:
; X64:       # %bb.0:
; X64-NEXT:    movl %edi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fildl -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
;
; I686-LABEL: test_int32_to_longdouble:
; I686:       # %bb.0:
; I686-NEXT:    pushl %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movl %eax, (%esp)
; I686-NEXT:    fildl (%esp)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
  %conv = sitofp i32 %a to x86_fp80
  ret x86_fp80 %conv
}

define x86_fp80 @test_int64_to_longdouble(i64 %a, ptr %p) nounwind {
; X64-LABEL: test_int64_to_longdouble:
; X64:       # %bb.0:
; X64-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fildll -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
;
; I686-LABEL: test_int64_to_longdouble:
; I686:       # %bb.0:
; I686-NEXT:    fildll {{[0-9]+}}(%esp)
; I686-NEXT:    retl
  %conv = sitofp i64 %a to x86_fp80
  ret x86_fp80 %conv
}


define void @test_int8to_double(i8 %x, ptr %p) nounwind {
; X64-LABEL: test_int8to_double:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movsbl %dil, %eax
; X64-NEXT:    movw %ax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    filds -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstpl (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int8to_double:
; I686:       # %bb.0: # %entry
; I686-NEXT:    pushl %eax
; I686-NEXT:    movsbl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; I686-NEXT:    movw %ax, {{[0-9]+}}(%esp)
; I686-NEXT:    filds {{[0-9]+}}(%esp)
; I686-NEXT:    fstpl (%ecx)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
entry:
  %conv = sitofp i8 %x to double
  store double %conv, ptr %p, align 4
  ret void
}

define void @test_int16_to_double(i16 %x, ptr %p) nounwind {
; X64-LABEL: test_int16_to_double:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movw %di, -{{[0-9]+}}(%rsp)
; X64-NEXT:    filds -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstpl (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int16_to_double:
; I686:       # %bb.0: # %entry
; I686-NEXT:    pushl %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movzwl {{[0-9]+}}(%esp), %ecx
; I686-NEXT:    movw %cx, {{[0-9]+}}(%esp)
; I686-NEXT:    filds {{[0-9]+}}(%esp)
; I686-NEXT:    fstpl (%eax)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
entry:
  %conv = sitofp i16 %x to double
  store double %conv, ptr %p, align 4
  ret void
}

define void @test_int32_to_double(i32 %x, ptr %p) nounwind {
; X64-LABEL: test_int32_to_double:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movl %edi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fildl -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstpl (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int32_to_double:
; I686:       # %bb.0: # %entry
; I686-NEXT:    pushl %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; I686-NEXT:    movl %ecx, (%esp)
; I686-NEXT:    fildl (%esp)
; I686-NEXT:    fstpl (%eax)
; I686-NEXT:    popl %eax
; I686-NEXT:    retl
entry:
  %conv = sitofp i32 %x to double
  store double %conv, ptr %p, align 4
  ret void
}

define void @test_int64_to_double(i64 %x, ptr %p) nounwind {
; X64-LABEL: test_int64_to_double:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fildll -{{[0-9]+}}(%rsp)
; X64-NEXT:    fstpl (%rsi)
; X64-NEXT:    retq
;
; I686-LABEL: test_int64_to_double:
; I686:       # %bb.0: # %entry
; I686-NEXT:    movl {{[0-9]+}}(%esp), %eax
; I686-NEXT:    fildll {{[0-9]+}}(%esp)
; I686-NEXT:    fstpl (%eax)
; I686-NEXT:    retl
entry:
  %conv = sitofp i64 %x to double
  store double %conv, ptr %p, align 4
  ret void
}
