; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+sse2 -verify-machineinstrs | FileCheck %s --check-prefixes=X64,SDAG-X64-SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx -verify-machineinstrs | FileCheck %s --check-prefixes=X64,SDAG-X64-AVX
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx2 -verify-machineinstrs | FileCheck %s --check-prefixes=X64,SDAG-X64-AVX2

; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+sse2 -global-isel -verify-machineinstrs | FileCheck %s --check-prefixes=X64,GISEL-X64-SSE2
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx -global-isel -verify-machineinstrs | FileCheck %s --check-prefixes=X64,GISEL-X64-AVX
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx2 -global-isel -verify-machineinstrs | FileCheck %s --check-prefixes=X64,GISEL-X64-AVX2

define <2 x double> @shuffle_all_poison_mask(<2 x double> %a, <2 x double> %b) {
; X64-LABEL: shuffle_all_poison_mask:
; X64:       # %bb.0:
; X64-NEXT:    retq
  %result = shufflevector <2 x double> %a, <2 x double> %b, <2 x i32> <i32 poison, i32 poison>
  ret <2 x double> %result
}

define <2 x double> @shuffle_v2_zero(<2 x double> %a) {
; SDAG-X64-SSE2-LABEL: shuffle_v2_zero:
; SDAG-X64-SSE2:       # %bb.0:
; SDAG-X64-SSE2-NEXT:    xorps %xmm0, %xmm0
; SDAG-X64-SSE2-NEXT:    retq
;
; SDAG-X64-AVX-LABEL: shuffle_v2_zero:
; SDAG-X64-AVX:       # %bb.0:
; SDAG-X64-AVX-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; SDAG-X64-AVX-NEXT:    retq
;
; SDAG-X64-AVX2-LABEL: shuffle_v2_zero:
; SDAG-X64-AVX2:       # %bb.0:
; SDAG-X64-AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; SDAG-X64-AVX2-NEXT:    retq
;
; GISEL-X64-SSE2-LABEL: shuffle_v2_zero:
; GISEL-X64-SSE2:       # %bb.0:
; GISEL-X64-SSE2-NEXT:    movaps {{.*#+}} xmm0 = [?]
; GISEL-X64-SSE2-NEXT:    retq
;
; GISEL-X64-AVX-LABEL: shuffle_v2_zero:
; GISEL-X64-AVX:       # %bb.0:
; GISEL-X64-AVX-NEXT:    vmovaps {{.*#+}} xmm0 = [?]
; GISEL-X64-AVX-NEXT:    retq
;
; GISEL-X64-AVX2-LABEL: shuffle_v2_zero:
; GISEL-X64-AVX2:       # %bb.0:
; GISEL-X64-AVX2-NEXT:    vmovaps {{.*#+}} xmm0 = [?]
; GISEL-X64-AVX2-NEXT:    retq
  %result = shufflevector <2 x double> %a, <2 x double> zeroinitializer, <2 x i32> <i32 2, i32 3>
  ret <2 x double> %result
}

define <2 x double> @shuffle_v1_undef(<2 x double> %b) {
; SDAG-X64-SSE2-LABEL: shuffle_v1_undef:
; SDAG-X64-SSE2:       # %bb.0:
; SDAG-X64-SSE2-NEXT:    retq
;
; SDAG-X64-AVX-LABEL: shuffle_v1_undef:
; SDAG-X64-AVX:       # %bb.0:
; SDAG-X64-AVX-NEXT:    retq
;
; SDAG-X64-AVX2-LABEL: shuffle_v1_undef:
; SDAG-X64-AVX2:       # %bb.0:
; SDAG-X64-AVX2-NEXT:    retq
;
; GISEL-X64-SSE2-LABEL: shuffle_v1_undef:
; GISEL-X64-SSE2:       # %bb.0:
; GISEL-X64-SSE2-NEXT:    movaps {{.*#+}} xmm0 = [?]
; GISEL-X64-SSE2-NEXT:    retq
;
; GISEL-X64-AVX-LABEL: shuffle_v1_undef:
; GISEL-X64-AVX:       # %bb.0:
; GISEL-X64-AVX-NEXT:    vmovaps {{.*#+}} xmm0 = [?]
; GISEL-X64-AVX-NEXT:    retq
;
; GISEL-X64-AVX2-LABEL: shuffle_v1_undef:
; GISEL-X64-AVX2:       # %bb.0:
; GISEL-X64-AVX2-NEXT:    vmovaps {{.*#+}} xmm0 = [?]
; GISEL-X64-AVX2-NEXT:    retq
  %result = shufflevector <2 x double> undef, <2 x double> %b, <2 x i32> <i32 0, i32 1>
  ret <2 x double> %result
}

define <2 x double> @shuffle_undef_and_zero() {
; SDAG-X64-SSE2-LABEL: shuffle_undef_and_zero:
; SDAG-X64-SSE2:       # %bb.0:
; SDAG-X64-SSE2-NEXT:    xorps %xmm0, %xmm0
; SDAG-X64-SSE2-NEXT:    retq
;
; SDAG-X64-AVX-LABEL: shuffle_undef_and_zero:
; SDAG-X64-AVX:       # %bb.0:
; SDAG-X64-AVX-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; SDAG-X64-AVX-NEXT:    retq
;
; SDAG-X64-AVX2-LABEL: shuffle_undef_and_zero:
; SDAG-X64-AVX2:       # %bb.0:
; SDAG-X64-AVX2-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; SDAG-X64-AVX2-NEXT:    retq
;
; GISEL-X64-SSE2-LABEL: shuffle_undef_and_zero:
; GISEL-X64-SSE2:       # %bb.0:
; GISEL-X64-SSE2-NEXT:    movaps {{.*#+}} xmm0 = [?]
; GISEL-X64-SSE2-NEXT:    retq
;
; GISEL-X64-AVX-LABEL: shuffle_undef_and_zero:
; GISEL-X64-AVX:       # %bb.0:
; GISEL-X64-AVX-NEXT:    vmovaps {{.*#+}} xmm0 = [?]
; GISEL-X64-AVX-NEXT:    retq
;
; GISEL-X64-AVX2-LABEL: shuffle_undef_and_zero:
; GISEL-X64-AVX2:       # %bb.0:
; GISEL-X64-AVX2-NEXT:    vmovaps {{.*#+}} xmm0 = [?]
; GISEL-X64-AVX2-NEXT:    retq
  %result = shufflevector <2 x double> undef, <2 x double> zeroinitializer, <2 x i32> <i32 0, i32 2>
  ret <2 x double> %result
}

; define <2 x double> @shuffle_poison_mask_and_zero(<2 x double> %a) {
;   %result = shufflevector <2 x double> %a, <2 x double> zeroinitializer, <2 x i32> <i32 poison, i32 3>
;   ret <2 x double> %result
; }

; define <2 x double> @shuffle_build_vector_fp_zeros(<2 x double> %a) {
;   %bv = insertelement <2 x double> poison, double 0.0, i32 0
;   %bv2 = insertelement <2 x double> %bv, double 0.0, i32 1
;   %result = shufflevector <2 x double> %a, <2 x double> %bv2, <2 x i32> <i32 2, i32 3>
;   ret <2 x double> %result
; }

; define <2 x double> @shuffle_build_vector_undef_elts(<2 x double> %a) {
;   %bv = insertelement <2 x double> poison, double undef, i32 0
;   %bv2 = insertelement <2 x double> %bv, double undef, i32 1
;   %result = shufflevector <2 x double> %a, <2 x double> %bv2, <2 x i32> <i32 2, i32 3>
;   ret <2 x double> %result
; }

define <2 x double> @shuffle_partial_zero(<2 x double> %a) {
; SDAG-X64-SSE2-LABEL: shuffle_partial_zero:
; SDAG-X64-SSE2:       # %bb.0:
; SDAG-X64-SSE2-NEXT:    movq {{.*#+}} xmm0 = xmm0[0],zero
; SDAG-X64-SSE2-NEXT:    retq
;
; SDAG-X64-AVX-LABEL: shuffle_partial_zero:
; SDAG-X64-AVX:       # %bb.0:
; SDAG-X64-AVX-NEXT:    vmovq {{.*#+}} xmm0 = xmm0[0],zero
; SDAG-X64-AVX-NEXT:    retq
;
; SDAG-X64-AVX2-LABEL: shuffle_partial_zero:
; SDAG-X64-AVX2:       # %bb.0:
; SDAG-X64-AVX2-NEXT:    vmovq {{.*#+}} xmm0 = xmm0[0],zero
; SDAG-X64-AVX2-NEXT:    retq
;
; GISEL-X64-SSE2-LABEL: shuffle_partial_zero:
; GISEL-X64-SSE2:       # %bb.0:
; GISEL-X64-SSE2-NEXT:    shufpd {{.*#+}} xmm0 = xmm0[0],mem[0]
; GISEL-X64-SSE2-NEXT:    retq
;
; GISEL-X64-AVX-LABEL: shuffle_partial_zero:
; GISEL-X64-AVX:       # %bb.0:
; GISEL-X64-AVX-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[0],mem[0]
; GISEL-X64-AVX-NEXT:    retq
;
; GISEL-X64-AVX2-LABEL: shuffle_partial_zero:
; GISEL-X64-AVX2:       # %bb.0:
; GISEL-X64-AVX2-NEXT:    vshufpd {{.*#+}} xmm0 = xmm0[0],mem[0]
; GISEL-X64-AVX2-NEXT:    retq
  %result = shufflevector <2 x double> %a, <2 x double> zeroinitializer, <2 x i32> <i32 0, i32 2>
  ret <2 x double> %result
}
