; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-linux-gnu | FileCheck %s --check-prefixes=X64,DAG-X64
; RUN: llc < %s -mtriple=x86_64-linux-gnu -fast-isel | FileCheck %s --check-prefixes=X64,FASTISEL-X64
; RUN: llc < %s -mtriple=i686-linux-gnu | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -mtriple=i686-linux-gnu -fast-isel | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -mtriple=x86_64-linux-gnu -global-isel -global-isel-abort=2 | FileCheck %s --check-prefixes=GISEL-X64
; RUN: llc < %s -mtriple=i686-linux-gnu -global-isel -global-isel-abort=2 | FileCheck %s --check-prefixes=X86,GISEL-X86

define float @floor_f32(float %a) nounwind readnone {
; DAG-X64-LABEL: floor_f32:
; DAG-X64:       # %bb.0:
; DAG-X64-NEXT:    jmp floorf@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: floor_f32:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq floorf@PLT
; FASTISEL-X64-NEXT:    popq %rax
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: floor_f32:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    pushq %rax
; GISEL-X64-NEXT:    callq floorf
; GISEL-X64-NEXT:    popq %rax
; GISEL-X64-NEXT:    retq
;
; GISEL-X86-LABEL: floor_f32:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl %eax, (%esp)
; GISEL-X86-NEXT:    calll floorf
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
  %c = call float @llvm.floor.f32(float %a)
  ret float %c
}

define double @floor_f64(double %a) nounwind readnone {
; DAG-X64-LABEL: floor_f64:
; DAG-X64:       # %bb.0:
; DAG-X64-NEXT:    jmp floor@PLT # TAILCALL
;
; FASTISEL-X64-LABEL: floor_f64:
; FASTISEL-X64:       # %bb.0:
; FASTISEL-X64-NEXT:    pushq %rax
; FASTISEL-X64-NEXT:    callq floor@PLT
; FASTISEL-X64-NEXT:    popq %rax
; FASTISEL-X64-NEXT:    retq
;
; GISEL-X64-LABEL: floor_f64:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    pushq %rax
; GISEL-X64-NEXT:    callq floor
; GISEL-X64-NEXT:    popq %rax
; GISEL-X64-NEXT:    retq
;
; GISEL-X86-LABEL: floor_f64:
; GISEL-X86:       # %bb.0:
; GISEL-X86-NEXT:    subl $12, %esp
; GISEL-X86-NEXT:    leal {{[0-9]+}}(%esp), %eax
; GISEL-X86-NEXT:    movl {{[0-9]+}}(%esp), %ecx
; GISEL-X86-NEXT:    movl 4(%eax), %eax
; GISEL-X86-NEXT:    xorl %edx, %edx
; GISEL-X86-NEXT:    addl %esp, %edx
; GISEL-X86-NEXT:    movl %ecx, (%esp)
; GISEL-X86-NEXT:    movl %eax, 4(%edx)
; GISEL-X86-NEXT:    calll floor
; GISEL-X86-NEXT:    addl $12, %esp
; GISEL-X86-NEXT:    retl
  %c = call double @llvm.floor.f64(double %a)
  ret double %c
}

define x86_fp80 @floor_f80(x86_fp80 %a) nounwind readnone {
; X64-LABEL: floor_f80:
; X64:       # %bb.0:
; X64-NEXT:    subq $24, %rsp
; X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; X64-NEXT:    fstpt (%rsp)
; X64-NEXT:    callq floorl@PLT
; X64-NEXT:    addq $24, %rsp
; X64-NEXT:    retq
;
; X86-LABEL: floor_f80:
; X86:       # %bb.0:
; X86-NEXT:    subl $12, %esp
; X86-NEXT:    fldt {{[0-9]+}}(%esp)
; X86-NEXT:    fstpt (%esp)
; X86-NEXT:    calll floorl
; X86-NEXT:    addl $12, %esp
; X86-NEXT:    retl
;
; GISEL-X64-LABEL: floor_f80:
; GISEL-X64:       # %bb.0:
; GISEL-X64-NEXT:    subq $24, %rsp
; GISEL-X64-NEXT:    fldt {{[0-9]+}}(%rsp)
; GISEL-X64-NEXT:    fstpt (%rsp)
; GISEL-X64-NEXT:    callq floorl
; GISEL-X64-NEXT:    addq $24, %rsp
; GISEL-X64-NEXT:    retq
  %c = call x86_fp80 @llvm.floor.f80(x86_fp80 %a)
  ret x86_fp80 %c
}
