; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v3 | FileCheck %s

define i1 @sqrt_neginf_f32(float %a0) {
; CHECK-LABEL: sqrt_neginf_f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsqrtss %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovd %xmm0, %eax
; CHECK-NEXT:    cmpl $-8388608, %eax # imm = 0xFF800000
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %sqr = call float @llvm.sqrt.f32(float %a0)
  %res = tail call i1 @llvm.is.fpclass.f32(float %sqr, i32 4)  ; 0x4 = "neginf"
  ret i1 %res
}

define i1 @sqrt_neginf_v4f32(<4 x float> %a0, ptr %p1) {
; CHECK-LABEL: sqrt_neginf_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsqrtps %xmm0, %xmm0
; CHECK-NEXT:    vmovaps %xmm0, (%rdi)
; CHECK-NEXT:    vextractps $0, %xmm0, %eax
; CHECK-NEXT:    cmpl $-8388608, %eax # imm = 0xFF800000
; CHECK-NEXT:    sete %al
; CHECK-NEXT:    retq
  %sqr = call <4 x float> @llvm.sqrt.v4f32(<4 x float> %a0)
  store <4 x float> %sqr, ptr %p1
  %elt = extractelement <4 x float> %sqr, i32 0
  %res = tail call i1 @llvm.is.fpclass.f32(float %elt, i32 4)  ; 0x4 = "neginf"
  ret i1 %res
}

define i1 @demanded_elts_safe_lane(float %unknown) {
; CHECK-LABEL: demanded_elts_safe_lane:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  %vec1 = insertelement <2 x float> poison, float %unknown, i32 0
  %vec2 = insertelement <2 x float> %vec1, float 1.000000e+00, i32 1

  %ext = extractelement <2 x float> %vec2, i32 1

  %cmp = fcmp uno float %ext, 0.000000e+00
  ret i1 %cmp
}

define i1 @demanded_elts_unknown_lane(float %unknown) {
; CHECK-LABEL: demanded_elts_unknown_lane:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vucomiss %xmm0, %xmm0
; CHECK-NEXT:    setp %al
; CHECK-NEXT:    retq
  %vec1 = insertelement <2 x float> poison, float %unknown, i32 0
  %vec2 = insertelement <2 x float> %vec1, float 1.000000e+00, i32 1

  %ext = extractelement <2 x float> %vec2, i32 0

  %cmp = fcmp uno float %ext, 0.000000e+00
  ret i1 %cmp
}
