; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-linux | FileCheck %s --check-prefix=NO-NDD
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-linux -mattr=+ndd | FileCheck %s --check-prefix=NDD

define i8 @lea8bit(i8 %in) {
; NO-NDD-LABEL: lea8bit:
; NO-NDD:       # %bb.0:
; NO-NDD-NEXT:    # kill: def $edi killed $edi def $rdi
; NO-NDD-NEXT:    leal (%rdi,%rdi), %eax
; NO-NDD-NEXT:    incb %al
; NO-NDD-NEXT:    # kill: def $al killed $al killed $eax
; NO-NDD-NEXT:    retq
;
; NDD-LABEL: lea8bit:
; NDD:       # %bb.0:
; NDD-NEXT:    # kill: def $edi killed $edi def $rdi
; NDD-NEXT:    leal 1(%rdi,%rdi), %eax
; NDD-NEXT:    # kill: def $al killed $al killed $eax
; NDD-NEXT:    retq
  %shl = shl i8 %in, 1
  %or = or i8 %shl, 1
  ret i8 %or
}
