; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=i686-unknown-linux-gnu -mattr=-sse -verify-machineinstrs < %s | FileCheck %s -check-prefixes=NOSSE,SDAG-X86-NOSSE
; RUN: llc -mtriple=i686-unknown-linux-gnu -fast-isel=1 -mattr=-sse -verify-machineinstrs < %s | FileCheck %s -check-prefixes=NOSSE,FASTISEL-X86-NOSSE
; RUN: llc -mtriple=i686-unknown-linux-gnu -global-isel=1 -global-isel-abort=2 -mattr=-sse -verify-machineinstrs < %s | FileCheck %s -check-prefixes=NOSSE,GISEL-X86-NOSSE
; RUN: llc -mtriple=i686-unknown-linux-gnu -mattr=+sse -verify-machineinstrs < %s | FileCheck %s -check-prefixes=SSE,SDAG-X86-SSE
; RUN: llc -mtriple=i686-unknown-linux-gnu -fast-isel=1 -mattr=+sse -verify-machineinstrs < %s | FileCheck %s -check-prefixes=SSE,FASTISEL-X86-SSE
; RUN: llc -mtriple=i686-unknown-linux-gnu -global-isel=1 -global-isel-abort=2 -mattr=+sse -verify-machineinstrs < %s | FileCheck %s -check-prefixes=SSE,GISEL-X86-SSE
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -verify-machineinstrs < %s | FileCheck %s -check-prefixes=X64,SDAG-X64
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -fast-isel=1 -verify-machineinstrs < %s | FileCheck %s -check-prefixes=X64,FASTISEL-X64
; RUN: llc -mtriple=x86_64-unknown-linux-gnu -global-isel=1 -global-isel-abort=2 -verify-machineinstrs < %s | FileCheck %s -check-prefixes=X64,GISEL-X64

declare void @llvm.set.rounding(i32 %x)

define void @func_01() nounwind {
; NOSSE-LABEL: func_01:
; NOSSE:       # %bb.0:
; NOSSE-NEXT:    pushl %eax
; NOSSE-NEXT:    fnstcw (%esp)
; NOSSE-NEXT:    orb $12, {{[0-9]+}}(%esp)
; NOSSE-NEXT:    fldcw (%esp)
; NOSSE-NEXT:    popl %eax
; NOSSE-NEXT:    retl
;
; SSE-LABEL: func_01:
; SSE:       # %bb.0:
; SSE-NEXT:    pushl %eax
; SSE-NEXT:    fnstcw (%esp)
; SSE-NEXT:    orb $12, {{[0-9]+}}(%esp)
; SSE-NEXT:    fldcw (%esp)
; SSE-NEXT:    stmxcsr (%esp)
; SSE-NEXT:    orb $96, {{[0-9]+}}(%esp)
; SSE-NEXT:    ldmxcsr (%esp)
; SSE-NEXT:    popl %eax
; SSE-NEXT:    retl
;
; X64-LABEL: func_01:
; X64:       # %bb.0:
; X64-NEXT:    fnstcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    orb $12, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    stmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    orb $96, -{{[0-9]+}}(%rsp)
; X64-NEXT:    ldmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
  call void @llvm.set.rounding(i32 0)  ; TowardZero (CW[11-10] = 11)
  ret void
}

define void @func_02() nounwind {
; NOSSE-LABEL: func_02:
; NOSSE:       # %bb.0:
; NOSSE-NEXT:    pushl %eax
; NOSSE-NEXT:    fnstcw (%esp)
; NOSSE-NEXT:    andb $-13, {{[0-9]+}}(%esp)
; NOSSE-NEXT:    fldcw (%esp)
; NOSSE-NEXT:    popl %eax
; NOSSE-NEXT:    retl
;
; SSE-LABEL: func_02:
; SSE:       # %bb.0:
; SSE-NEXT:    pushl %eax
; SSE-NEXT:    fnstcw (%esp)
; SSE-NEXT:    andb $-13, {{[0-9]+}}(%esp)
; SSE-NEXT:    fldcw (%esp)
; SSE-NEXT:    stmxcsr (%esp)
; SSE-NEXT:    andb $-97, {{[0-9]+}}(%esp)
; SSE-NEXT:    ldmxcsr (%esp)
; SSE-NEXT:    popl %eax
; SSE-NEXT:    retl
;
; X64-LABEL: func_02:
; X64:       # %bb.0:
; X64-NEXT:    fnstcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    andb $-13, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    stmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    andb $-97, -{{[0-9]+}}(%rsp)
; X64-NEXT:    ldmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
  call void @llvm.set.rounding(i32 1)  ; ToNearestTiesToEven (CW[11-10] = 00)
  ret void
}

define void @func_03() nounwind {
; NOSSE-LABEL: func_03:
; NOSSE:       # %bb.0:
; NOSSE-NEXT:    pushl %eax
; NOSSE-NEXT:    fnstcw (%esp)
; NOSSE-NEXT:    movl $-3073, %eax # imm = 0xF3FF
; NOSSE-NEXT:    andl (%esp), %eax
; NOSSE-NEXT:    orl $2048, %eax # imm = 0x800
; NOSSE-NEXT:    movw %ax, (%esp)
; NOSSE-NEXT:    fldcw (%esp)
; NOSSE-NEXT:    popl %eax
; NOSSE-NEXT:    retl
;
; SSE-LABEL: func_03:
; SSE:       # %bb.0:
; SSE-NEXT:    pushl %eax
; SSE-NEXT:    fnstcw (%esp)
; SSE-NEXT:    movl $-3073, %eax # imm = 0xF3FF
; SSE-NEXT:    andl (%esp), %eax
; SSE-NEXT:    orl $2048, %eax # imm = 0x800
; SSE-NEXT:    movw %ax, (%esp)
; SSE-NEXT:    fldcw (%esp)
; SSE-NEXT:    stmxcsr (%esp)
; SSE-NEXT:    movl $-24577, %eax # imm = 0x9FFF
; SSE-NEXT:    andl (%esp), %eax
; SSE-NEXT:    orl $16384, %eax # imm = 0x4000
; SSE-NEXT:    movl %eax, (%esp)
; SSE-NEXT:    ldmxcsr (%esp)
; SSE-NEXT:    popl %eax
; SSE-NEXT:    retl
;
; X64-LABEL: func_03:
; X64:       # %bb.0:
; X64-NEXT:    fnstcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl $-3073, %eax # imm = 0xF3FF
; X64-NEXT:    andl -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    orl $2048, %eax # imm = 0x800
; X64-NEXT:    movw %ax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    stmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl $-24577, %eax # imm = 0x9FFF
; X64-NEXT:    andl -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    orl $16384, %eax # imm = 0x4000
; X64-NEXT:    movl %eax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    ldmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
  call void @llvm.set.rounding(i32 2)  ; Upward (CW[11-10] = 10)
  ret void
}

define void @func_04() nounwind {
; NOSSE-LABEL: func_04:
; NOSSE:       # %bb.0:
; NOSSE-NEXT:    pushl %eax
; NOSSE-NEXT:    fnstcw (%esp)
; NOSSE-NEXT:    movl $-3073, %eax # imm = 0xF3FF
; NOSSE-NEXT:    andl (%esp), %eax
; NOSSE-NEXT:    orl $1024, %eax # imm = 0x400
; NOSSE-NEXT:    movw %ax, (%esp)
; NOSSE-NEXT:    fldcw (%esp)
; NOSSE-NEXT:    popl %eax
; NOSSE-NEXT:    retl
;
; SSE-LABEL: func_04:
; SSE:       # %bb.0:
; SSE-NEXT:    pushl %eax
; SSE-NEXT:    fnstcw (%esp)
; SSE-NEXT:    movl $-3073, %eax # imm = 0xF3FF
; SSE-NEXT:    andl (%esp), %eax
; SSE-NEXT:    orl $1024, %eax # imm = 0x400
; SSE-NEXT:    movw %ax, (%esp)
; SSE-NEXT:    fldcw (%esp)
; SSE-NEXT:    stmxcsr (%esp)
; SSE-NEXT:    movl $-24577, %eax # imm = 0x9FFF
; SSE-NEXT:    andl (%esp), %eax
; SSE-NEXT:    orl $8192, %eax # imm = 0x2000
; SSE-NEXT:    movl %eax, (%esp)
; SSE-NEXT:    ldmxcsr (%esp)
; SSE-NEXT:    popl %eax
; SSE-NEXT:    retl
;
; X64-LABEL: func_04:
; X64:       # %bb.0:
; X64-NEXT:    fnstcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl $-3073, %eax # imm = 0xF3FF
; X64-NEXT:    andl -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    orl $1024, %eax # imm = 0x400
; X64-NEXT:    movw %ax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    stmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl $-24577, %eax # imm = 0x9FFF
; X64-NEXT:    andl -{{[0-9]+}}(%rsp), %eax
; X64-NEXT:    orl $8192, %eax # imm = 0x2000
; X64-NEXT:    movl %eax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    ldmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
  call void @llvm.set.rounding(i32 3)  ; Downward (CW[11-10] = 01)
  ret void
}

define void @func_05(i32 %x) nounwind {
; NOSSE-LABEL: func_05:
; NOSSE:       # %bb.0:
; NOSSE-NEXT:    pushl %eax
; NOSSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; NOSSE-NEXT:    leal 4(%eax,%eax), %ecx
; NOSSE-NEXT:    movl $201, %eax
; NOSSE-NEXT:    # kill: def $cl killed $cl killed $ecx
; NOSSE-NEXT:    shll %cl, %eax
; NOSSE-NEXT:    andl $3072, %eax # imm = 0xC00
; NOSSE-NEXT:    fnstcw (%esp)
; NOSSE-NEXT:    movl $-3073, %ecx # imm = 0xF3FF
; NOSSE-NEXT:    andl (%esp), %ecx
; NOSSE-NEXT:    orl %eax, %ecx
; NOSSE-NEXT:    movw %cx, (%esp)
; NOSSE-NEXT:    fldcw (%esp)
; NOSSE-NEXT:    popl %eax
; NOSSE-NEXT:    retl
;
; SSE-LABEL: func_05:
; SSE:       # %bb.0:
; SSE-NEXT:    pushl %eax
; SSE-NEXT:    movl {{[0-9]+}}(%esp), %eax
; SSE-NEXT:    leal 4(%eax,%eax), %ecx
; SSE-NEXT:    movl $201, %eax
; SSE-NEXT:    # kill: def $cl killed $cl killed $ecx
; SSE-NEXT:    shll %cl, %eax
; SSE-NEXT:    andl $3072, %eax # imm = 0xC00
; SSE-NEXT:    fnstcw (%esp)
; SSE-NEXT:    movl $-3073, %ecx # imm = 0xF3FF
; SSE-NEXT:    andl (%esp), %ecx
; SSE-NEXT:    orl %eax, %ecx
; SSE-NEXT:    movw %cx, (%esp)
; SSE-NEXT:    fldcw (%esp)
; SSE-NEXT:    stmxcsr (%esp)
; SSE-NEXT:    movl $-24577, %ecx # imm = 0x9FFF
; SSE-NEXT:    andl (%esp), %ecx
; SSE-NEXT:    leal (%ecx,%eax,8), %eax
; SSE-NEXT:    movl %eax, (%esp)
; SSE-NEXT:    ldmxcsr (%esp)
; SSE-NEXT:    popl %eax
; SSE-NEXT:    retl
;
; X64-LABEL: func_05:
; X64:       # %bb.0:
; X64-NEXT:    # kill: def $edi killed $edi def $rdi
; X64-NEXT:    leal 4(%rdi,%rdi), %ecx
; X64-NEXT:    movl $201, %eax
; X64-NEXT:    # kill: def $cl killed $cl killed $ecx
; X64-NEXT:    shll %cl, %eax
; X64-NEXT:    andl $3072, %eax # imm = 0xC00
; X64-NEXT:    fnstcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl $-3073, %ecx # imm = 0xF3FF
; X64-NEXT:    andl -{{[0-9]+}}(%rsp), %ecx
; X64-NEXT:    orl %eax, %ecx
; X64-NEXT:    movw %cx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    fldcw -{{[0-9]+}}(%rsp)
; X64-NEXT:    stmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl $-24577, %ecx # imm = 0x9FFF
; X64-NEXT:    andl -{{[0-9]+}}(%rsp), %ecx
; X64-NEXT:    leal (%rcx,%rax,8), %eax
; X64-NEXT:    movl %eax, -{{[0-9]+}}(%rsp)
; X64-NEXT:    ldmxcsr -{{[0-9]+}}(%rsp)
; X64-NEXT:    retq
  call void @llvm.set.rounding(i32 %x)  ; Downward
  ret void
}

attributes #0 = { nounwind "use-soft-float"="true" }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; FASTISEL-X64: {{.*}}
; FASTISEL-X86-NOSSE: {{.*}}
; FASTISEL-X86-SSE: {{.*}}
; GISEL-X64: {{.*}}
; GISEL-X86-NOSSE: {{.*}}
; GISEL-X86-SSE: {{.*}}
; SDAG-X64: {{.*}}
; SDAG-X86-NOSSE: {{.*}}
; SDAG-X86-SSE: {{.*}}
