; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --no_x86_scrub_sp --version 5
; RUN: llc -combiner-topological-sorting < %s -mtriple=i386-unknown-linux-gnu  | FileCheck -check-prefix=X86 %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-linux-gnu  | FileCheck -check-prefix=X64 %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-apple-macosx10.9.0 | FileCheck --check-prefix=MACOS-SINCOS-STRET %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-apple-macosx10.8.0 | FileCheck --check-prefix=MACOS-NOSINCOS-STRET %s

define void @test_sincos_v4f32(<4 x float> %x, ptr noalias %out_sin, ptr noalias %out_cos) nounwind {
; X86-LABEL: test_sincos_v4f32:
; X86:       # %bb.0:
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    subl $52, %esp
; X86-NEXT:    movl 84(%esp), %esi
; X86-NEXT:    flds 76(%esp)
; X86-NEXT:    fstps {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    flds 64(%esp)
; X86-NEXT:    fstps {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    flds 72(%esp)
; X86-NEXT:    fstps {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    flds 68(%esp)
; X86-NEXT:    movl 80(%esp), %edi
; X86-NEXT:    leal 40(%esp), %eax
; X86-NEXT:    movl %eax, 8(%esp)
; X86-NEXT:    leal 4(%edi), %eax
; X86-NEXT:    movl %eax, 4(%esp)
; X86-NEXT:    fstps (%esp)
; X86-NEXT:    calll sincosf
; X86-NEXT:    leal 44(%esp), %eax
; X86-NEXT:    movl %eax, 8(%esp)
; X86-NEXT:    leal 8(%edi), %eax
; X86-NEXT:    movl %eax, 4(%esp)
; X86-NEXT:    flds {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    fstps (%esp)
; X86-NEXT:    calll sincosf
; X86-NEXT:    leal 36(%esp), %eax
; X86-NEXT:    movl %eax, 8(%esp)
; X86-NEXT:    movl %edi, 4(%esp)
; X86-NEXT:    flds {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    fstps (%esp)
; X86-NEXT:    calll sincosf
; X86-NEXT:    leal 48(%esp), %eax
; X86-NEXT:    movl %eax, 8(%esp)
; X86-NEXT:    addl $12, %edi
; X86-NEXT:    movl %edi, 4(%esp)
; X86-NEXT:    flds {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Reload
; X86-NEXT:    fstps (%esp)
; X86-NEXT:    calll sincosf
; X86-NEXT:    flds 36(%esp)
; X86-NEXT:    flds 40(%esp)
; X86-NEXT:    flds 44(%esp)
; X86-NEXT:    flds 48(%esp)
; X86-NEXT:    fstps 12(%esi)
; X86-NEXT:    fstps 8(%esi)
; X86-NEXT:    fstps 4(%esi)
; X86-NEXT:    fstps (%esi)
; X86-NEXT:    addl $52, %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    retl
;
; X64-LABEL: test_sincos_v4f32:
; X64:       # %bb.0:
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $56, %rsp
; X64-NEXT:    movq %rsi, %rbx
; X64-NEXT:    movq %rdi, %r14
; X64-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; X64-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; X64-NEXT:    leaq 4(%rsp), %rdi
; X64-NEXT:    movq %rsp, %rsi
; X64-NEXT:    callq sincosf@PLT
; X64-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; X64-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; X64-NEXT:    leaq 12(%rsp), %rdi
; X64-NEXT:    leaq 8(%rsp), %rsi
; X64-NEXT:    callq sincosf@PLT
; X64-NEXT:    leaq 28(%rsp), %rdi
; X64-NEXT:    leaq 24(%rsp), %rsi
; X64-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; X64-NEXT:    callq sincosf@PLT
; X64-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; X64-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; X64-NEXT:    leaq 20(%rsp), %rdi
; X64-NEXT:    leaq 16(%rsp), %rsi
; X64-NEXT:    callq sincosf@PLT
; X64-NEXT:    movss {{.*#+}} xmm0 = mem[0],zero,zero,zero
; X64-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; X64-NEXT:    unpcklps {{.*#+}} xmm1 = xmm1[0],xmm0[0],xmm1[1],xmm0[1]
; X64-NEXT:    movss {{.*#+}} xmm0 = mem[0],zero,zero,zero
; X64-NEXT:    movss {{.*#+}} xmm2 = mem[0],zero,zero,zero
; X64-NEXT:    unpcklps {{.*#+}} xmm0 = xmm0[0],xmm2[0],xmm0[1],xmm2[1]
; X64-NEXT:    movlhps {{.*#+}} xmm0 = xmm0[0],xmm1[0]
; X64-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; X64-NEXT:    movss {{.*#+}} xmm2 = mem[0],zero,zero,zero
; X64-NEXT:    unpcklps {{.*#+}} xmm2 = xmm2[0],xmm1[0],xmm2[1],xmm1[1]
; X64-NEXT:    movss {{.*#+}} xmm1 = mem[0],zero,zero,zero
; X64-NEXT:    movss {{.*#+}} xmm3 = mem[0],zero,zero,zero
; X64-NEXT:    unpcklps {{.*#+}} xmm1 = xmm1[0],xmm3[0],xmm1[1],xmm3[1]
; X64-NEXT:    movlhps {{.*#+}} xmm1 = xmm1[0],xmm2[0]
; X64-NEXT:    movups %xmm1, (%r14)
; X64-NEXT:    movups %xmm0, (%rbx)
; X64-NEXT:    addq $56, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r14
; X64-NEXT:    retq
;
; MACOS-SINCOS-STRET-LABEL: test_sincos_v4f32:
; MACOS-SINCOS-STRET:       ## %bb.0:
; MACOS-SINCOS-STRET-NEXT:    pushq %r14
; MACOS-SINCOS-STRET-NEXT:    pushq %rbx
; MACOS-SINCOS-STRET-NEXT:    subq $104, %rsp
; MACOS-SINCOS-STRET-NEXT:    movq %rsi, %rbx
; MACOS-SINCOS-STRET-NEXT:    movq %rdi, %r14
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; MACOS-SINCOS-STRET-NEXT:    callq ___sincosf_stret
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, (%rsp) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; MACOS-SINCOS-STRET-NEXT:    callq ___sincosf_stret
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; MACOS-SINCOS-STRET-NEXT:    unpcklps (%rsp), %xmm0 ## 16-byte Folded Reload
; MACOS-SINCOS-STRET-NEXT:    ## xmm0 = xmm0[0],mem[0],xmm0[1],mem[1]
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, (%rsp) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    callq ___sincosf_stret
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, %xmm1
; MACOS-SINCOS-STRET-NEXT:    shufps {{.*#+}} xmm1 = xmm1[1,1],xmm0[1,1]
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm1, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; MACOS-SINCOS-STRET-NEXT:    callq ___sincosf_stret
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    unpcklps {{.*#+}} xmm1 = xmm1[0],xmm0[0],xmm1[1],xmm0[1]
; MACOS-SINCOS-STRET-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    unpcklps {{.*#+}} xmm2 = xmm2[0],xmm0[0],xmm2[1],xmm0[1]
; MACOS-SINCOS-STRET-NEXT:    unpcklpd (%rsp), %xmm2 ## 16-byte Folded Reload
; MACOS-SINCOS-STRET-NEXT:    ## xmm2 = xmm2[0],mem[0]
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    unpcklps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Folded Reload
; MACOS-SINCOS-STRET-NEXT:    ## xmm0 = xmm0[0],mem[0],xmm0[1],mem[1]
; MACOS-SINCOS-STRET-NEXT:    movlhps {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; MACOS-SINCOS-STRET-NEXT:    movups %xmm1, (%r14)
; MACOS-SINCOS-STRET-NEXT:    movups %xmm2, (%rbx)
; MACOS-SINCOS-STRET-NEXT:    addq $104, %rsp
; MACOS-SINCOS-STRET-NEXT:    popq %rbx
; MACOS-SINCOS-STRET-NEXT:    popq %r14
; MACOS-SINCOS-STRET-NEXT:    retq
;
; MACOS-NOSINCOS-STRET-LABEL: test_sincos_v4f32:
; MACOS-NOSINCOS-STRET:       ## %bb.0:
; MACOS-NOSINCOS-STRET-NEXT:    pushq %r14
; MACOS-NOSINCOS-STRET-NEXT:    pushq %rbx
; MACOS-NOSINCOS-STRET-NEXT:    subq $104, %rsp
; MACOS-NOSINCOS-STRET-NEXT:    movq %rsi, %rbx
; MACOS-NOSINCOS-STRET-NEXT:    movq %rdi, %r14
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, (%rsp) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    shufps {{.*#+}} xmm0 = xmm0[3,3,3,3]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    callq _cosf
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    callq _cosf
; MACOS-NOSINCOS-STRET-NEXT:    unpcklps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Folded Reload
; MACOS-NOSINCOS-STRET-NEXT:    ## xmm0 = xmm0[0],mem[0],xmm0[1],mem[1]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    callq _cosf
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    shufps {{.*#+}} xmm0 = xmm0[1,1,1,1]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    callq _cosf
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    unpcklps {{.*#+}} xmm1 = xmm1[0],xmm0[0],xmm1[1],xmm0[1]
; MACOS-NOSINCOS-STRET-NEXT:    unpcklpd {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 ## 16-byte Folded Reload
; MACOS-NOSINCOS-STRET-NEXT:    ## xmm1 = xmm1[0],mem[0]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm1, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    callq _sinf
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    callq _sinf
; MACOS-NOSINCOS-STRET-NEXT:    unpcklps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Folded Reload
; MACOS-NOSINCOS-STRET-NEXT:    ## xmm0 = xmm0[0],mem[0],xmm0[1],mem[1]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    callq _sinf
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, (%rsp) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    callq _sinf
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm1 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    unpcklps {{.*#+}} xmm1 = xmm1[0],xmm0[0],xmm1[1],xmm0[1]
; MACOS-NOSINCOS-STRET-NEXT:    unpcklpd {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 ## 16-byte Folded Reload
; MACOS-NOSINCOS-STRET-NEXT:    ## xmm1 = xmm1[0],mem[0]
; MACOS-NOSINCOS-STRET-NEXT:    movups %xmm1, (%r14)
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    movups %xmm0, (%rbx)
; MACOS-NOSINCOS-STRET-NEXT:    addq $104, %rsp
; MACOS-NOSINCOS-STRET-NEXT:    popq %rbx
; MACOS-NOSINCOS-STRET-NEXT:    popq %r14
; MACOS-NOSINCOS-STRET-NEXT:    retq
  %result = call { <4 x float>, <4 x float> } @llvm.sincos.v4f32(<4 x float> %x)
  %result.0 = extractvalue { <4 x float>, <4 x float> } %result, 0
  %result.1 = extractvalue { <4 x float>, <4 x float> } %result, 1
  store <4 x float> %result.0, ptr %out_sin, align 4
  store <4 x float> %result.1, ptr %out_cos, align 4
  ret void
}

define void @test_sincos_v2f64(<2 x double> %x, ptr noalias %out_sin, ptr noalias %out_cos) nounwind {
; X86-LABEL: test_sincos_v2f64:
; X86:       # %bb.0:
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    subl $52, %esp
; X86-NEXT:    movl 84(%esp), %esi
; X86-NEXT:    fldl 72(%esp)
; X86-NEXT:    fstpl {{[-0-9]+}}(%e{{[sb]}}p) # 8-byte Folded Spill
; X86-NEXT:    fldl 64(%esp)
; X86-NEXT:    movl 80(%esp), %edi
; X86-NEXT:    leal 24(%esp), %eax
; X86-NEXT:    movl %eax, 12(%esp)
; X86-NEXT:    movl %edi, 8(%esp)
; X86-NEXT:    fstpl (%esp)
; X86-NEXT:    calll sincos
; X86-NEXT:    leal 32(%esp), %eax
; X86-NEXT:    movl %eax, 12(%esp)
; X86-NEXT:    addl $8, %edi
; X86-NEXT:    movl %edi, 8(%esp)
; X86-NEXT:    fldl {{[-0-9]+}}(%e{{[sb]}}p) # 8-byte Folded Reload
; X86-NEXT:    fstpl (%esp)
; X86-NEXT:    calll sincos
; X86-NEXT:    fldl 24(%esp)
; X86-NEXT:    fldl 32(%esp)
; X86-NEXT:    fstpl 8(%esi)
; X86-NEXT:    fstpl (%esi)
; X86-NEXT:    addl $52, %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    retl
;
; X64-LABEL: test_sincos_v2f64:
; X64:       # %bb.0:
; X64-NEXT:    pushq %r14
; X64-NEXT:    pushq %rbx
; X64-NEXT:    subq $56, %rsp
; X64-NEXT:    movq %rsi, %rbx
; X64-NEXT:    movq %rdi, %r14
; X64-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; X64-NEXT:    leaq 24(%rsp), %rdi
; X64-NEXT:    leaq 16(%rsp), %rsi
; X64-NEXT:    callq sincos@PLT
; X64-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 # 16-byte Reload
; X64-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; X64-NEXT:    leaq 8(%rsp), %rdi
; X64-NEXT:    movq %rsp, %rsi
; X64-NEXT:    callq sincos@PLT
; X64-NEXT:    movsd {{.*#+}} xmm0 = mem[0],zero
; X64-NEXT:    movhps {{.*#+}} xmm0 = xmm0[0,1],mem[0,1]
; X64-NEXT:    movsd {{.*#+}} xmm1 = mem[0],zero
; X64-NEXT:    movhps {{.*#+}} xmm1 = xmm1[0,1],mem[0,1]
; X64-NEXT:    movups %xmm1, (%r14)
; X64-NEXT:    movups %xmm0, (%rbx)
; X64-NEXT:    addq $56, %rsp
; X64-NEXT:    popq %rbx
; X64-NEXT:    popq %r14
; X64-NEXT:    retq
;
; MACOS-SINCOS-STRET-LABEL: test_sincos_v2f64:
; MACOS-SINCOS-STRET:       ## %bb.0:
; MACOS-SINCOS-STRET-NEXT:    pushq %r14
; MACOS-SINCOS-STRET-NEXT:    pushq %rbx
; MACOS-SINCOS-STRET-NEXT:    subq $56, %rsp
; MACOS-SINCOS-STRET-NEXT:    movq %rsi, %rbx
; MACOS-SINCOS-STRET-NEXT:    movq %rdi, %r14
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, (%rsp) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    callq ___sincos_stret
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    movaps %xmm1, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-SINCOS-STRET-NEXT:    movaps (%rsp), %xmm0 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; MACOS-SINCOS-STRET-NEXT:    callq ___sincos_stret
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm2 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    movlhps {{.*#+}} xmm2 = xmm2[0],xmm1[0]
; MACOS-SINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 ## 16-byte Reload
; MACOS-SINCOS-STRET-NEXT:    movlhps {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; MACOS-SINCOS-STRET-NEXT:    movups %xmm1, (%r14)
; MACOS-SINCOS-STRET-NEXT:    movups %xmm2, (%rbx)
; MACOS-SINCOS-STRET-NEXT:    addq $56, %rsp
; MACOS-SINCOS-STRET-NEXT:    popq %rbx
; MACOS-SINCOS-STRET-NEXT:    popq %r14
; MACOS-SINCOS-STRET-NEXT:    retq
;
; MACOS-NOSINCOS-STRET-LABEL: test_sincos_v2f64:
; MACOS-NOSINCOS-STRET:       ## %bb.0:
; MACOS-NOSINCOS-STRET-NEXT:    pushq %r14
; MACOS-NOSINCOS-STRET-NEXT:    pushq %rbx
; MACOS-NOSINCOS-STRET-NEXT:    subq $56, %rsp
; MACOS-NOSINCOS-STRET-NEXT:    movq %rsi, %rbx
; MACOS-NOSINCOS-STRET-NEXT:    movq %rdi, %r14
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, (%rsp) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    callq _cos
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    movhlps {{.*#+}} xmm0 = xmm0[1,1]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    callq _cos
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm1 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    movlhps {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm1, {{[-0-9]+}}(%r{{[sb]}}p) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    callq _sin
; MACOS-NOSINCOS-STRET-NEXT:    movaps %xmm0, (%rsp) ## 16-byte Spill
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    callq _sin
; MACOS-NOSINCOS-STRET-NEXT:    movaps (%rsp), %xmm1 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    movlhps {{.*#+}} xmm1 = xmm1[0],xmm0[0]
; MACOS-NOSINCOS-STRET-NEXT:    movups %xmm1, (%r14)
; MACOS-NOSINCOS-STRET-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm0 ## 16-byte Reload
; MACOS-NOSINCOS-STRET-NEXT:    movups %xmm0, (%rbx)
; MACOS-NOSINCOS-STRET-NEXT:    addq $56, %rsp
; MACOS-NOSINCOS-STRET-NEXT:    popq %rbx
; MACOS-NOSINCOS-STRET-NEXT:    popq %r14
; MACOS-NOSINCOS-STRET-NEXT:    retq
  %result = call { <2 x double>, <2 x double> } @llvm.sincos.v2f64(<2 x double> %x)
  %result.0 = extractvalue { <2 x double>, <2 x double> } %result, 0
  %result.1 = extractvalue { <2 x double>, <2 x double> } %result, 1
  store <2 x double> %result.0, ptr %out_sin, align 8
  store <2 x double> %result.1, ptr %out_cos, align 8
  ret void
}

