; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-unknown-linux-gnu < %s | FileCheck %s

; Test that consecutive byte loads combined via OR with AND masks on individual
; loads are folded into a single wider load + mask at the DAG level.
; This is the pattern from manual bitfield extraction code.
; https://github.com/llvm/llvm-project/issues/191193

; --- Positive tests (should fold to wide load + mask) ---

; High byte masked.
define i16 @load_2_bytes_high_masked(ptr %p) {
; CHECK-LABEL: load_2_bytes_high_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    andl $1023, %eax # imm = 0x3FF
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Low byte masked.
define i16 @load_2_bytes_low_masked(ptr %p) {
; CHECK-LABEL: load_2_bytes_low_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    andl $65343, %eax # imm = 0xFF3F
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %lo.m = and i8 %lo, 63
  %lo.ext = zext i8 %lo.m to i16
  %hi.ext = zext i8 %hi to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Both bytes masked.
define i16 @load_2_bytes_both_masked(ptr %p) {
; CHECK-LABEL: load_2_bytes_both_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl (%rdi), %eax
; CHECK-NEXT:    andl $783, %eax # imm = 0x30F
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %lo.m = and i8 %lo, 15
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo.m to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Four bytes, last byte masked.
define i32 @load_4_bytes_last_masked(ptr %p) {
; CHECK-LABEL: load_4_bytes_last_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl $1073741823, %eax # imm = 0x3FFFFFFF
; CHECK-NEXT:    andl (%rdi), %eax
; CHECK-NEXT:    retq
  %p1 = getelementptr i8, ptr %p, i64 1
  %p2 = getelementptr i8, ptr %p, i64 2
  %p3 = getelementptr i8, ptr %p, i64 3
  %l0 = load i8, ptr %p, align 1
  %l1 = load i8, ptr %p1, align 1
  %l2 = load i8, ptr %p2, align 1
  %l3 = load i8, ptr %p3, align 1
  %l3.m = and i8 %l3, 63
  %e0 = zext i8 %l0 to i32
  %e1 = zext i8 %l1 to i32
  %e2 = zext i8 %l2 to i32
  %e3 = zext i8 %l3.m to i32
  %s1 = shl i32 %e1, 8
  %s2 = shl i32 %e2, 16
  %s3 = shl i32 %e3, 24
  %o1 = or i32 %e0, %s1
  %o2 = or i32 %o1, %s2
  %o3 = or i32 %o2, %s3
  ret i32 %o3
}

; Big-endian byte order on LE target (requires bswap + mask).
define i32 @load_4_bytes_bswap_masked(ptr %p) {
; CHECK-LABEL: load_4_bytes_bswap_masked:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl (%rdi), %eax
; CHECK-NEXT:    bswapl %eax
; CHECK-NEXT:    andl $-193, %eax
; CHECK-NEXT:    retq
  %p1 = getelementptr i8, ptr %p, i64 1
  %p2 = getelementptr i8, ptr %p, i64 2
  %p3 = getelementptr i8, ptr %p, i64 3
  %b0 = load i8, ptr %p, align 1
  %b1 = load i8, ptr %p1, align 1
  %b2 = load i8, ptr %p2, align 1
  %b3 = load i8, ptr %p3, align 1
  %b3.m = and i8 %b3, 63
  %e0 = zext i8 %b0 to i32
  %e1 = zext i8 %b1 to i32
  %e2 = zext i8 %b2 to i32
  %e3 = zext i8 %b3.m to i32
  %s0 = shl i32 %e0, 24
  %s1 = shl i32 %e1, 16
  %s2 = shl i32 %e2, 8
  %o1 = or i32 %s0, %s1
  %o2 = or i32 %o1, %s2
  %result = or i32 %o2, %e3
  ret i32 %result
}

; --- Negative tests (should NOT fold) ---

; Non-adjacent loads (gap between them).
define i16 @negative_non_adjacent(ptr %p) {
; CHECK-LABEL: negative_non_adjacent:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl (%rdi), %ecx
; CHECK-NEXT:    movzbl 2(%rdi), %eax
; CHECK-NEXT:    andl $3, %eax
; CHECK-NEXT:    shll $8, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %p2 = getelementptr inbounds i8, ptr %p, i64 2
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p2, align 1
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Volatile load cannot be combined.
define i16 @negative_volatile(ptr %p) {
; CHECK-LABEL: negative_volatile:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl (%rdi), %ecx
; CHECK-NEXT:    movzbl 1(%rdi), %eax
; CHECK-NEXT:    andl $3, %eax
; CHECK-NEXT:    shll $8, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load volatile i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, 3
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Non-constant mask.
define i16 @negative_variable_mask(ptr %p, i8 %mask) {
; CHECK-LABEL: negative_variable_mask:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl (%rdi), %ecx
; CHECK-NEXT:    movzbl 1(%rdi), %eax
; CHECK-NEXT:    andl %esi, %eax
; CHECK-NEXT:    shll $8, %eax
; CHECK-NEXT:    orl %ecx, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, %mask
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}

; Multi-use: AND result is used elsewhere. The one-use check in
; calculateByteProvider should prevent combining since the AND can't be removed.
declare void @use.i8(i8)
define i16 @negative_multiuse_and(ptr %p) {
; CHECK-LABEL: negative_multiuse_and:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    .cfi_offset %rbx, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movzbl (%rdi), %ebp
; CHECK-NEXT:    movzbl 1(%rdi), %ebx
; CHECK-NEXT:    andl $3, %ebx
; CHECK-NEXT:    movl %ebx, %edi
; CHECK-NEXT:    callq use.i8@PLT
; CHECK-NEXT:    shll $8, %ebx
; CHECK-NEXT:    orl %ebp, %ebx
; CHECK-NEXT:    movl %ebx, %eax
; CHECK-NEXT:    addq $8, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
  %p1 = getelementptr inbounds i8, ptr %p, i64 1
  %lo = load i8, ptr %p, align 1
  %hi = load i8, ptr %p1, align 1
  %hi.m = and i8 %hi, 3
  call void @use.i8(i8 %hi.m)
  %lo.ext = zext i8 %lo to i16
  %hi.ext = zext i8 %hi.m to i16
  %hi.shift = shl i16 %hi.ext, 8
  %result = or i16 %hi.shift, %lo.ext
  ret i16 %result
}
