; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mcpu=znver5 | FileCheck %s

declare i64 @llvm.ctlz.i64(i64, i1 immarg)
declare i64 @llvm.cttz.i64(i64, i1 immarg)

define i64 @lzcnt64_add_iszero(i64 %x) {
; CHECK-LABEL: lzcnt64_add_iszero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lzcntq %rdi, %rax
; CHECK-NEXT:    adcq $0, %rax
; CHECK-NEXT:    retq
  %lzcnt = tail call i64 @llvm.ctlz.i64(i64 %x, i1 false)
  %cmp = icmp eq i64 %x, 0
  %ext = zext i1 %cmp to i64
  %add = add i64 %lzcnt, %ext
  ret i64 %add
}
define i64 @tzcnt64_add_iszero(i64 %x) {
; CHECK-LABEL: tzcnt64_add_iszero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    tzcntq %rdi, %rax
; CHECK-NEXT:    adcq $0, %rax
; CHECK-NEXT:    retq
  %tzcnt = tail call i64 @llvm.cttz.i64(i64 %x, i1 false)
  %cmp = icmp eq i64 %x, 0
  %ext = zext i1 %cmp to i64
  %add = add i64 %tzcnt, %ext
  ret i64 %add
}
