; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx2 | FileCheck %s

define i64 @mov_dec(<32 x i8> %x) local_unnamed_addr {
; CHECK-LABEL: mov_dec:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal -1(%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %dec = add i32 %mvmsk, -1
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %dec.ext = zext i32 %dec to i64
  %res = or disjoint i64 %shl, %dec.ext
  ret i64 %res
}

define i64 @mov_inc(<32 x i8> %x) local_unnamed_addr {
; CHECK-LABEL: mov_inc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal 1(%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %inc = add i32 %mvmsk, 1
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %inc.ext = zext i32 %inc to i64
  %res = or disjoint i64 %shl, %inc.ext
  ret i64 %res
}

define i64 @mov_inc_flags_live(<32 x i8> %x) local_unnamed_addr {
; CHECK-LABEL: mov_inc_flags_live:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    movl %ecx, %eax
; CHECK-NEXT:    incl %eax
; CHECK-NEXT:    cmovneq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %inc = add i32 %mvmsk, 1
  %iszero = icmp eq i32 %inc, 0
  %ext = zext i32 %mvmsk to i64
  %inc.ext = zext i32 %inc to i64
  %sel = select i1 %iszero, i64 %inc.ext, i64 %ext
  ret i64 %sel
}

define i64 @mov_dec_flags_live(<32 x i8> %x) local_unnamed_addr {
; CHECK-LABEL: mov_dec_flags_live:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    movl %ecx, %eax
; CHECK-NEXT:    decl %eax
; CHECK-NEXT:    cmovneq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %dec = add i32 %mvmsk, -1
  %iszero = icmp eq i32 %dec, 0
  %ext = zext i32 %mvmsk to i64
  %dec.ext = zext i32 %dec to i64
  %sel = select i1 %iszero, i64 %dec.ext, i64 %ext
  ret i64 %sel
}

define i64 @mov_inc_not_adjacent(<32 x i8> %x) local_unnamed_addr {
; CHECK-LABEL: mov_inc_not_adjacent:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %eax
; CHECK-NEXT:    movq %rax, %rcx
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    incl %eax
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    xorq $5, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %tmp = xor i64 %shl, 5
  %inc = add i32 %mvmsk, 1
  %inc.ext = zext i32 %inc to i64
  %res = xor i64 %tmp, %inc.ext
  ret i64 %res
}
