; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -mattr=+avx2 | FileCheck %s

define i64 @mov_dec(<32 x i8> %x) {
; CHECK-LABEL: mov_dec:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal -1(%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %dec = add i32 %mvmsk, -1
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %dec.ext = zext i32 %dec to i64
  %res = or disjoint i64 %shl, %dec.ext
  ret i64 %res
}

define i64 @mov_inc(<32 x i8> %x) {
; CHECK-LABEL: mov_inc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal 1(%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %inc = add i32 %mvmsk, 1
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %inc.ext = zext i32 %inc to i64
  %res = or disjoint i64 %shl, %inc.ext
  ret i64 %res
}

define i64 @mov_add_imm(<32 x i8> %x) {
; CHECK-LABEL: mov_add_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal 5(%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %add = add i32 %mvmsk, 5
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %add.ext = zext i32 %add to i64
  %res = or disjoint i64 %shl, %add.ext
  ret i64 %res
}

define i64 @mov_add_rr(<32 x i8> %x, i32 %y) {
; CHECK-LABEL: mov_add_rr:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal (%rdi,%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %add = add i32 %mvmsk, %y
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %add.ext = zext i32 %add to i64
  %res = or disjoint i64 %shl, %add.ext
  ret i64 %res
}

define i64 @mov_shl(<32 x i8> %x) {
; CHECK-LABEL: mov_shl:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal (,%rcx,4), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %shl_op = shl i32 %mvmsk, 2
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %shl_op.ext = zext i32 %shl_op to i64
  %res = or disjoint i64 %shl, %shl_op.ext
  ret i64 %res
}

define i64 @mov_sub_imm(<32 x i8> %x) {
; CHECK-LABEL: mov_sub_imm:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal -5(%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %sub = add i32 %mvmsk, -5
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %sub.ext = zext i32 %sub to i64
  %res = or disjoint i64 %shl, %sub.ext
  ret i64 %res
}

define i64 @mov_add_self(<32 x i8> %x) {
; CHECK-LABEL: mov_add_self:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vpmovmskb %ymm0, %ecx
; CHECK-NEXT:    leal (%rcx,%rcx), %eax
; CHECK-NEXT:    shlq $32, %rcx
; CHECK-NEXT:    orq %rcx, %rax
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %cmp = icmp slt <32 x i8> %x, zeroinitializer
  %mvmsk = bitcast <32 x i1> %cmp to i32
  %add = add i32 %mvmsk, %mvmsk
  %ext = zext i32 %mvmsk to i64
  %shl = shl nuw i64 %ext, 32
  %add.ext = zext i32 %add to i64
  %res = or disjoint i64 %shl, %add.ext
  ret i64 %res
}
