; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-- -verify-machineinstrs | FileCheck %s

; Make sure this does not crash with "Use not jointly dominated by defs."
; The load-folded compare was dropped from LocalMIs via a stale pointer and
; rewritten to use a not-yet-defined extension result.

@g = global i8 0

define void @pr199237() {
; CHECK-LABEL: pr199237:
; CHECK:       # %bb.0: # %BB
; CHECK-NEXT:    movq g@GOTPCREL(%rip), %rax
; CHECK-NEXT:    movzbl (%rax), %ecx
; CHECK-NEXT:    cmpb 0, %cl
; CHECK-NEXT:    setg (%rax)
; CHECK-NEXT:    setae 0
; CHECK-NEXT:    movsbq %cl, %rax
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  .LBB0_1: # %BB2
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    movq %rax, 0
; CHECK-NEXT:    jmp .LBB0_1
BB:
  %v = load i8, ptr @g, align 1
  %w = load i8, ptr null, align 1
  %c1 = icmp sgt i8 %v, %w
  store i1 %c1, ptr @g, align 1
  %c2 = icmp ule i8 %w, %v
  store i1 %c2, ptr null, align 1
  br label %BB2

BB2:
  %gep = getelementptr i8, ptr null, i8 %v
  store ptr %gep, ptr null, align 8
  br label %BB2
}
