# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=x86_64-- -run-pass=peephole-opt,liveintervals -o - %s | FileCheck %s

# Regression test for https://github.com/llvm/llvm-project/issues/199237: the
# peephole optimizer rewrote a use before its def, which crashed Live Interval
# Analysis with "Use not jointly dominated by defs". Check that it does not.

--- |
  @g13 = global i16 0
  @g14 = global i16 0
  @g20 = global i8 0
  @g29 = global i8 0
  define void @f10() { ret void }
...
---
name:            f10
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: f10
    ; CHECK: [[MOVZX32rm16_:%[0-9]+]]:gr32 = MOVZX32rm16 $rip, 1, $noreg, @g13, $noreg :: (load (s16) from @g13)
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gr16 = COPY [[MOVZX32rm16_]].sub_16bit
    ; CHECK-NEXT: CMP16rm [[COPY]], $rip, 1, $noreg, @g14, $noreg, implicit-def $eflags :: (load (s16) from @g14)
    ; CHECK-NEXT: SETCCm $rip, 1, $noreg, @g20, $noreg, 13, implicit $eflags :: (store (s8) into @g20)
    ; CHECK-NEXT: [[SETCCr:%[0-9]+]]:gr8 = SETCCr 14, implicit $eflags
    ; CHECK-NEXT: [[MOVSX32rr16_:%[0-9]+]]:gr32 = MOVSX32rr16 [[COPY]]
    ; CHECK-NEXT: CMP32ri [[MOVSX32rr16_]], 538, implicit-def $eflags
    ; CHECK-NEXT: SETCCm $rip, 1, $noreg, @g29, $noreg, 12, implicit $eflags :: (store (s8) into @g29)
    ; CHECK-NEXT: MOV8mr $rip, 1, $noreg, @g20, $noreg, [[SETCCr]] :: (store (s8) into @g20)
    ; CHECK-NEXT: RET 0
    %6:gr32 = MOVZX32rm16 $rip, 1, $noreg, @g13, $noreg :: (load (s16) from @g13)
    %7:gr16 = COPY %6.sub_16bit
    %8:gr16 = MOV16rm $rip, 1, $noreg, @g14, $noreg :: (load (s16) from @g14)
    %9:gr16 = SUB16rr %7, %8, implicit-def $eflags
    SETCCm $rip, 1, $noreg, @g20, $noreg, 13, implicit $eflags :: (store (s8) into @g20)
    %10:gr16 = SUB16rr %8, %7, implicit-def $eflags
    %1:gr8 = SETCCr 13, implicit $eflags
    %11:gr32 = MOVSX32rr16 %7
    %12:gr32 = SUB32ri %11, 538, implicit-def $eflags
    SETCCm $rip, 1, $noreg, @g29, $noreg, 12, implicit $eflags :: (store (s8) into @g29)
    MOV8mr $rip, 1, $noreg, @g20, $noreg, %1 :: (store (s8) into @g20)
    RET 0
...
