# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=x86_64-linux-gnu -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $ebx = MOV32ri 1
  ; CHECK-NEXT:   renamable $eax = COPY killed renamable $ebx, implicit undef $ecx
  ; CHECK-NEXT:   $ecx = MOV32ri 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $eax
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET 0, $eax
  bb.0:
    successors: %bb.1

    renamable $ebx = MOV32ri 1
    renamable $eax = COPY killed renamable $ebx, implicit undef $ecx
    $ecx = MOV32ri 0

  bb.1:
    liveins: $eax
    RET 0, $eax
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $ebx = MOV32ri 1
  ; CHECK-NEXT:   $edx = MOV32ri 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $ebx, $ecx
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $eax = COPY killed renamable $ebx, implicit-def $ecx, implicit internal $ecx
  ; CHECK-NEXT:   RET 0, $eax
  bb.0:
    successors: %bb.1

    renamable $ebx = MOV32ri 1
    renamable $eax = COPY killed renamable $ebx, implicit-def $ecx, implicit internal $ecx
    $edx = MOV32ri 0

  bb.1:
    liveins: $eax, $ecx
    RET 0, $eax
...
