; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64    | FileCheck %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v2 | FileCheck %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v3 | FileCheck %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v4 | FileCheck %s --check-prefix=AVX512

define i32 @PR135917(i1 %a0) {
; CHECK-LABEL: PR135917:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $edi killed $edi def $rdi
; CHECK-NEXT:    notl %edi
; CHECK-NEXT:    andl $1, %edi
; CHECK-NEXT:    leal (%rdi,%rdi), %eax
; CHECK-NEXT:    retq
;
; AVX512-LABEL: PR135917:
; AVX512:       # %bb.0:
; AVX512-NEXT:    kmovd %edi, %k0
; AVX512-NEXT:    knotw %k0, %k0
; AVX512-NEXT:    vpmovm2d %k0, %xmm0
; AVX512-NEXT:    vpbroadcastd %xmm0, %xmm0
; AVX512-NEXT:    vpmovd2m %xmm0, %k0
; AVX512-NEXT:    vpmovm2d %k0, %xmm0
; AVX512-NEXT:    vpsrld $31, %xmm0, %xmm0
; AVX512-NEXT:    vmovd %xmm0, %ecx
; AVX512-NEXT:    vpextrd $1, %xmm0, %eax
; AVX512-NEXT:    addl %ecx, %eax
; AVX512-NEXT:    retq
  %splat = insertelement <4 x i1> poison, i1 %a0, i64 0
  %xor = xor <4 x i1> %splat, splat (i1 true)
  %not = shufflevector <4 x i1> %xor, <4 x i1> poison, <4 x i32> zeroinitializer
  %zext = zext <4 x i1> %not to <4 x i32>
  %elt0 = extractelement <4 x i32> %zext, i64 0
  %elt1 = extractelement <4 x i32> %zext, i64 1
  %res = add i32 %elt0, %elt1
  ret i32 %res
}

