; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-- -mcpu=x86-64-v4 | FileCheck %s

define  { ptr, i8 } @PR132844(<4 x ptr> %0, <4 x ptr> %1) {
; CHECK-LABEL: PR132844:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vextractf128 $1, %ymm0, %xmm2
; CHECK-NEXT:    vinsertf128 $1, 16, %ymm2, %ymm2
; CHECK-NEXT:    vinsertf128 $1, %xmm0, %ymm1, %ymm0
; CHECK-NEXT:    vblendps {{.*#+}} ymm0 = ymm0[0,1],ymm2[2,3],ymm0[4,5],ymm2[6,7]
; CHECK-NEXT:    vmovups %ymm0, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  %3 = alloca [35 x ptr], i32 0, align 16
  %4 = load <4 x ptr>, ptr null, align 8
  %5 = getelementptr i8, ptr %3, i64 216
  %6 = extractelement <4 x ptr> %4, i64 3
  store ptr %6, ptr %5, align 8
  %7 = getelementptr i8, ptr %3, i64 208
  %8 = extractelement <4 x ptr> %0, i64 0
  store ptr %8, ptr %7, align 8
  %9 = getelementptr i8, ptr %3, i64 200
  %10 = extractelement <4 x ptr> %0, i64 3
  store ptr %10, ptr %9, align 8
  %11 = getelementptr i8, ptr %3, i64 192
  %12 = extractelement <4 x ptr> %1, i64 0
  store ptr %12, ptr %11, align 8
  ret { ptr, i8 } zeroinitializer
}
