; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=i686-unknown-unknown | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s --check-prefixes=X64

define i64 @foo(i64 %x) {
; X86-LABEL: foo:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shrl $15, %eax
; X86-NEXT:    cmpl $65509, %eax # imm = 0xFFE5
; X86-NEXT:    je .LBB0_1
; X86-NEXT:  # %bb.2: # %if.end
; X86-NEXT:    movl $3, %eax
; X86-NEXT:    movl $2146598912, %edx # imm = 0x7FF28000
; X86-NEXT:    retl
; X86-NEXT:  .LBB0_1: # %if.then
;
; X64-LABEL: foo:
; X64:       # %bb.0: # %entry
; X64-NEXT:    shrq $47, %rdi
; X64-NEXT:    cmpl $65509, %edi # imm = 0xFFE5
; X64-NEXT:    je .LBB0_1
; X64-NEXT:  # %bb.2: # %if.end
; X64-NEXT:    movabsq $9219572124669181952, %rax # imm = 0x7FF2800000000000
; X64-NEXT:    addq $3, %rax
; X64-NEXT:    retq
; X64-NEXT:  .LBB0_1: # %if.then
entry:
  %shr.mask = and i64 %x, -140737488355328
  %cmp = icmp eq i64 %shr.mask, 9219572124669181952
  br i1 %cmp, label %if.then, label %if.end

if.then:
  unreachable

if.end:
  ret i64 9219572124669181955
}
