; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64 | FileCheck %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64 -mattr=+egpr | FileCheck %s --check-prefix=EGPR

define coldcc i32 @foo() nounwind {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    callq bar@PLT
; CHECK-NEXT:    addq $8, %rsp
; CHECK-NEXT:    retq
;
; EGPR-LABEL: foo:
; EGPR:       # %bb.0:
; EGPR-NEXT:    pushq %rax
; EGPR-NEXT:    callq bar@PLT
; EGPR-NEXT:    popq %r16
; EGPR-NEXT:    retq
  %1 = tail call coldcc i32 @bar()
  ret i32 %1
}

declare coldcc i32 @bar()
