; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v4 -verify-machineinstrs | FileCheck %s

define void @pr163053(ptr %arg, ptr %arg1) #0 {
; CHECK-LABEL: pr163053:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps %ymm0, (%rdi)
; CHECK-NEXT:    vxorps %xmm0, %xmm0, %xmm0
; CHECK-NEXT:    vmovaps %zmm0, (%rsi)
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    xorl %esi, %esi
; CHECK-NEXT:    vxorps %ymm0, %ymm0, %ymm0
; CHECK-NEXT:    vxorps %zmm0, %zmm0, %zmm0
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
  store <16 x i16> zeroinitializer, ptr %arg, align 32
  store <32 x i16> zeroinitializer, ptr %arg1, align 64
  ret void
}

attributes #0 = { "zero-call-used-regs"="used" }
