; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v3 | FileCheck %s --check-prefixes=AVX2
; RUN: llc < %s -mtriple=x86_64-- -mcpu=x86-64-v4 | FileCheck %s --check-prefixes=AVX512

define i256 @PR173924(<8 x i256> %a0) {
; AVX2-LABEL: PR173924:
; AVX2:       # %bb.0:
; AVX2-NEXT:    movzbl {{[0-9]+}}(%rsp), %eax
; AVX2-NEXT:    andl $1, %r9d
; AVX2-NEXT:    andl $1, %esi
; AVX2-NEXT:    andb $1, %al
; AVX2-NEXT:    vmovd %esi, %xmm0
; AVX2-NEXT:    vpand {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0, %xmm0
; AVX2-NEXT:    vpinsrb $1, %r9d, %xmm0, %xmm0
; AVX2-NEXT:    vpinsrb $2, %eax, %xmm0, %xmm0
; AVX2-NEXT:    movzbl {{[0-9]+}}(%rsp), %eax
; AVX2-NEXT:    andb $1, %al
; AVX2-NEXT:    vpinsrb $3, %eax, %xmm0, %xmm0
; AVX2-NEXT:    movzbl {{[0-9]+}}(%rsp), %eax
; AVX2-NEXT:    andb $1, %al
; AVX2-NEXT:    vpinsrb $4, %eax, %xmm0, %xmm0
; AVX2-NEXT:    movzbl {{[0-9]+}}(%rsp), %eax
; AVX2-NEXT:    andb $1, %al
; AVX2-NEXT:    vpinsrb $5, %eax, %xmm0, %xmm0
; AVX2-NEXT:    movzbl {{[0-9]+}}(%rsp), %eax
; AVX2-NEXT:    andb $1, %al
; AVX2-NEXT:    vpinsrb $6, %eax, %xmm0, %xmm0
; AVX2-NEXT:    movzbl {{[0-9]+}}(%rsp), %eax
; AVX2-NEXT:    andb $1, %al
; AVX2-NEXT:    vpinsrb $7, %eax, %xmm0, %xmm0
; AVX2-NEXT:    movq %rdi, %rax
; AVX2-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; AVX2-NEXT:    vmovdqu %xmm1, 8(%rdi)
; AVX2-NEXT:    vpsadbw %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vmovq %xmm0, (%rdi)
; AVX2-NEXT:    movq $0, 24(%rdi)
; AVX2-NEXT:    retq
;
; AVX512-LABEL: PR173924:
; AVX512:       # %bb.0:
; AVX512-NEXT:    movq %rdi, %rax
; AVX512-NEXT:    movl {{[0-9]+}}(%rsp), %edi
; AVX512-NEXT:    movl {{[0-9]+}}(%rsp), %r8d
; AVX512-NEXT:    movl {{[0-9]+}}(%rsp), %r10d
; AVX512-NEXT:    movl {{[0-9]+}}(%rsp), %r11d
; AVX512-NEXT:    movl {{[0-9]+}}(%rsp), %edx
; AVX512-NEXT:    movl {{[0-9]+}}(%rsp), %ecx
; AVX512-NEXT:    andl $1, %ecx
; AVX512-NEXT:    andl $1, %edx
; AVX512-NEXT:    andl $1, %esi
; AVX512-NEXT:    andl $1, %r9d
; AVX512-NEXT:    andl $1, %r11d
; AVX512-NEXT:    andl $1, %r10d
; AVX512-NEXT:    andl $1, %r8d
; AVX512-NEXT:    andl $1, %edi
; AVX512-NEXT:    vmovd %edi, %xmm0
; AVX512-NEXT:    vmovd %r8d, %xmm1
; AVX512-NEXT:    vpunpcklbw {{.*#+}} xmm0 = xmm1[0],xmm0[0],xmm1[1],xmm0[1],xmm1[2],xmm0[2],xmm1[3],xmm0[3],xmm1[4],xmm0[4],xmm1[5],xmm0[5],xmm1[6],xmm0[6],xmm1[7],xmm0[7]
; AVX512-NEXT:    vpsllq $48, %xmm0, %xmm0
; AVX512-NEXT:    vmovd %r10d, %xmm1
; AVX512-NEXT:    vmovd %r11d, %xmm2
; AVX512-NEXT:    vpunpcklbw {{.*#+}} xmm1 = xmm2[0],xmm1[0],xmm2[1],xmm1[1],xmm2[2],xmm1[2],xmm2[3],xmm1[3],xmm2[4],xmm1[4],xmm2[5],xmm1[5],xmm2[6],xmm1[6],xmm2[7],xmm1[7]
; AVX512-NEXT:    vpbroadcastw %xmm1, %xmm1
; AVX512-NEXT:    vpblendw {{.*#+}} xmm0 = xmm1[0,1,2],xmm0[3],xmm1[4,5,6,7]
; AVX512-NEXT:    vmovd %r9d, %xmm1
; AVX512-NEXT:    vmovd %esi, %xmm2
; AVX512-NEXT:    vpunpcklbw {{.*#+}} xmm1 = xmm2[0],xmm1[0],xmm2[1],xmm1[1],xmm2[2],xmm1[2],xmm2[3],xmm1[3],xmm2[4],xmm1[4],xmm2[5],xmm1[5],xmm2[6],xmm1[6],xmm2[7],xmm1[7]
; AVX512-NEXT:    vmovd %edx, %xmm2
; AVX512-NEXT:    vmovd %ecx, %xmm3
; AVX512-NEXT:    vpunpcklbw {{.*#+}} xmm2 = xmm3[0],xmm2[0],xmm3[1],xmm2[1],xmm3[2],xmm2[2],xmm3[3],xmm2[3],xmm3[4],xmm2[4],xmm3[5],xmm2[5],xmm3[6],xmm2[6],xmm3[7],xmm2[7]
; AVX512-NEXT:    vpslld $16, %xmm2, %xmm2
; AVX512-NEXT:    vpblendw {{.*#+}} xmm1 = xmm1[0],xmm2[1],xmm1[2,3,4,5,6,7]
; AVX512-NEXT:    vpblendd {{.*#+}} xmm0 = xmm1[0],xmm0[1],xmm1[2,3]
; AVX512-NEXT:    vpxor %xmm1, %xmm1, %xmm1
; AVX512-NEXT:    vpsadbw %xmm1, %xmm0, %xmm0
; AVX512-NEXT:    vmovdqu %xmm1, 8(%rax)
; AVX512-NEXT:    vmovq %xmm0, (%rax)
; AVX512-NEXT:    movq $0, 24(%rax)
; AVX512-NEXT:    retq
  %m = and <8 x i256> %a0, splat (i256 1)
  %r = call i256 @llvm.vector.reduce.add.v8i256(<8 x i256> %m)
  ret i256 %r
}
