; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=+sse2 | FileCheck %s --check-prefixes=X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx | FileCheck %s --check-prefixes=X64

define i32 @_Z1ft(i16 zeroext %0) {
; X86-LABEL: _Z1ft:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    shll $3, %eax
; X86-NEXT:    retl
;
; X64-LABEL: _Z1ft:
; X64:       # %bb.0: # %entry
; X64-NEXT:    # kill: def $edi killed $edi def $rdi
; X64-NEXT:    leal (,%rdi,8), %eax
; X64-NEXT:    retq
entry:
  %3 = shl nuw i16 %0, 3
  %4 = zext i16 %3 to i32
  ret i32 %4
}

define i32 @_Z1gt(i16 zeroext %x) {
; X86-LABEL: _Z1gt:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    leal (,%eax,8), %ecx
; X86-NEXT:    shll $16, %eax
; X86-NEXT:    orl %ecx, %eax
; X86-NEXT:    retl
;
; X64-LABEL: _Z1gt:
; X64:       # %bb.0: # %entry
; X64-NEXT:    # kill: def $edi killed $edi def $rdi
; X64-NEXT:    leal (,%rdi,8), %eax
; X64-NEXT:    shll $16, %edi
; X64-NEXT:    orl %edi, %eax
; X64-NEXT:    retq
entry:
  %conv = zext nneg i16 %x to i32
  %shl = shl nuw i16 %x, 3
  %conv3 = zext i16 %shl to i32
  %shl5 = shl nuw nsw i32 %conv, 16
  %or = or disjoint i32 %shl5, %conv3
  ret i32 %or
}

