; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=i686-unknown-unknown -mattr=avx10.2 | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=avx10.2 | FileCheck %s --check-prefix=X64

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: write)
declare void @llvm.masked.store.v8i8.p1(<8 x i8>, ptr addrspace(1) captures(none), <8 x i1>) #0

define void @foo(<8 x i16> %arg, ptr addrspace(1) %add.ptr) {
; X86-LABEL: foo:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    vmovw %xmm0, %ecx
; X86-NEXT:    movb %ch, (%eax)
; X86-NEXT:    retl
;
; X64-LABEL: foo:
; X64:       # %bb.0: # %entry
; X64-NEXT:    vmovw %xmm0, %eax
; X64-NEXT:    movb %ah, (%rdi)
; X64-NEXT:    retq
entry:
  %i3 = shufflevector <8 x i16> %arg, <8 x i16> <i16 poison, i16 257, i16 257, i16 257, i16 257, i16 257, i16 257, i16 257>, <8 x i32> <i32 0, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %i4 = lshr <8 x i16> %i3, splat (i16 8)
  %i5 = trunc <8 x i16> %i4 to <8 x i8>
  call void @llvm.masked.store.v8i8.p1(<8 x i8> %i5, ptr addrspace(1) %add.ptr, <8 x i1> <i1 true, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false>)
  ret void
}

define void @bar(<8 x i64> %arg, ptr addrspace(1) %add.ptr) {
; X86-LABEL: bar:
; X86:       # %bb.0: # %entry
; X86-NEXT:    vpbroadcastd {{.*#+}} zmm1 = [257,257,257,257,257,257,257,257,257,257,257,257,257,257,257,257]
; X86-NEXT:    movb $2, %al
; X86-NEXT:    kmovd %eax, %k1
; X86-NEXT:    vmovdqa64 %zmm0, %zmm1 {%k1}
; X86-NEXT:    movl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    vpsrlq $16, %zmm1, %zmm0
; X86-NEXT:    vpmovqb %zmm0, (%eax) {%k1}
; X86-NEXT:    vzeroupper
; X86-NEXT:    retl
;
; X64-LABEL: bar:
; X64:       # %bb.0: # %entry
; X64-NEXT:    vpextrq $1, %xmm0, %rax
; X64-NEXT:    shrl $16, %eax
; X64-NEXT:    movb %al, 1(%rdi)
; X64-NEXT:    vzeroupper
; X64-NEXT:    retq
entry:
  %i3 = shufflevector <8 x i64> %arg, <8 x i64> <i64 257, i64 poison, i64 257, i64 257, i64 257, i64 257, i64 257, i64 257>, <8 x i32> <i32 8, i32 1, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15>
  %i4 = lshr <8 x i64> %i3, splat (i64 16)
  %i5 = trunc <8 x i64> %i4 to <8 x i8>
  call void @llvm.masked.store.v8i8.p1(<8 x i8> %i5, ptr addrspace(1) %add.ptr, <8 x i1> <i1 false, i1 true, i1 false, i1 false, i1 false, i1 false, i1 false, i1 false>)
  ret void
}

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(argmem: write) }
