; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -disable-constant-hoisting < %s | FileCheck %s
target datalayout = "e-m:e-p:32:32-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i386-unknown-linux-gnu"

@d = global i32 8, align 4

define i32 @main() {
; CHECK-LABEL: main:
; CHECK:       # BB#0: # %entry
; CHECK-NEXT:    movl d, %eax
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    shrl $31, %ecx
; CHECK-NEXT:    addl %eax, %eax
; CHECK-NEXT:    andl $16, %eax
; CHECK-NEXT:    cmpl $-1, %eax
; CHECK-NEXT:    sbbl $0, %ecx
; CHECK-NEXT:    sbbl %eax, %eax
; CHECK-NEXT:    andl $1, %eax
; CHECK-NEXT:    retl
entry:
  %load = load i32, i32* @d, align 4
  %conv1 = zext i32 %load to i64
  %shl = shl i64 %conv1, 1
  %mul = and i64 %shl, 4294967312
  %cmp = icmp ugt i64 4294967295, %mul
  %zext = zext i1 %cmp to i32
  ret i32 %zext
}
