; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -o - -O0 < %s | FileCheck %s
; RUN: llc -mattr=+zu -o - -O0 < %s | FileCheck %s -check-prefix=SETZUCC
; RUN: llc -mattr=+zu,+prefer-legacy-setcc -o - -O0 < %s | FileCheck %s -check-prefix=NO-SETZUCC

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @test1(i32 %x) #0 {
; CHECK-LABEL: test1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    cmpl $0, %edi
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    movzbl %al, %edi
; CHECK-NEXT:    andl $1, %edi
; CHECK-NEXT:    callq callee1@PLT
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    retq
;
; SETZUCC-LABEL: test1:
; SETZUCC:       # %bb.0: # %entry
; SETZUCC-NEXT:    pushq %rax
; SETZUCC-NEXT:    cmpl $0, %edi
; SETZUCC-NEXT:    setzune %al
; SETZUCC-NEXT:    movzbl %al, %edi
; SETZUCC-NEXT:    andl $1, %edi
; SETZUCC-NEXT:    callq callee1@PLT
; SETZUCC-NEXT:    popq %rax
; SETZUCC-NEXT:    retq
;
; NO-SETZUCC-LABEL: test1:
; NO-SETZUCC:       # %bb.0: # %entry
; NO-SETZUCC-NEXT:    pushq %rax
; NO-SETZUCC-NEXT:    cmpl $0, %edi
; NO-SETZUCC-NEXT:    setne %al
; NO-SETZUCC-NEXT:    movzbl %al, %edi
; NO-SETZUCC-NEXT:    andl $1, %edi
; NO-SETZUCC-NEXT:    callq callee1@PLT
; NO-SETZUCC-NEXT:    popq %rax
; NO-SETZUCC-NEXT:    retq
entry:
  %tobool = icmp ne i32 %x, 0
  call void @callee1(i1 zeroext %tobool)
  ret void
}

define void @test2(i32 %x) #0 {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    cmpl $0, %edi
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    movzbl %al, %edi
; CHECK-NEXT:    andl $1, %edi
; CHECK-NEXT:    negl %edi
; CHECK-NEXT:    callq callee2@PLT
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    retq
;
; SETZUCC-LABEL: test2:
; SETZUCC:       # %bb.0: # %entry
; SETZUCC-NEXT:    pushq %rax
; SETZUCC-NEXT:    cmpl $0, %edi
; SETZUCC-NEXT:    setzune %al
; SETZUCC-NEXT:    movzbl %al, %edi
; SETZUCC-NEXT:    andl $1, %edi
; SETZUCC-NEXT:    negl %edi
; SETZUCC-NEXT:    callq callee2@PLT
; SETZUCC-NEXT:    popq %rax
; SETZUCC-NEXT:    retq
;
; NO-SETZUCC-LABEL: test2:
; NO-SETZUCC:       # %bb.0: # %entry
; NO-SETZUCC-NEXT:    pushq %rax
; NO-SETZUCC-NEXT:    cmpl $0, %edi
; NO-SETZUCC-NEXT:    setne %al
; NO-SETZUCC-NEXT:    movzbl %al, %edi
; NO-SETZUCC-NEXT:    andl $1, %edi
; NO-SETZUCC-NEXT:    negl %edi
; NO-SETZUCC-NEXT:    callq callee2@PLT
; NO-SETZUCC-NEXT:    popq %rax
; NO-SETZUCC-NEXT:    retq
entry:
  %tobool = icmp ne i32 %x, 0
  call void @callee2(i1 signext %tobool)
  ret void
}

declare void @callee1(i1 zeroext)
declare void @callee2(i1 signext)

attributes #0 = { nounwind "target-cpu"="skylake-avx512" }
