; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mattr=+avx512f,+avx512bw | FileCheck %s

define <112 x i8> @pr34657(ptr %src) local_unnamed_addr {
; CHECK-LABEL: pr34657:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    vmovups (%rsi), %zmm0
; CHECK-NEXT:    vmovups 64(%rsi), %ymm1
; CHECK-NEXT:    vmovups 96(%rsi), %xmm2
; CHECK-NEXT:    vmovaps %xmm2, 96(%rdi)
; CHECK-NEXT:    vmovaps %ymm1, 64(%rdi)
; CHECK-NEXT:    vmovaps %zmm0, (%rdi)
; CHECK-NEXT:    vzeroupper
; CHECK-NEXT:    retq
entry:
  %wide.vec51 = load <112 x i8>, ptr %src, align 2
  ret <112 x i8> %wide.vec51
}
