; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-linux-gnu | FileCheck %s


define i32 @fn2() {
; CHECK-LABEL: fn2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    testb %al, %al
; CHECK-NEXT:    jne .LBB0_2
; CHECK-NEXT:  # %bb.1: # %bb1
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_2: # %bb2
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    retq
  %_tmp10 = icmp eq i8 0, 0
  %_tmp13 = icmp slt i8 undef, 1
  %_tmp151 = or i1 %_tmp10, %_tmp13
  %_tmp15 = zext i1 %_tmp151 to i8
  br i1 %_tmp151, label %bb1, label %bb2

bb1:                                              ; preds = %0, %0
  ret i32 0

bb2:                                              ; preds = %0, %0
  ret i32 1


}
