; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mtriple=i386-unknown-linux-gnu -mattr=cmov | FileCheck %s

define <2 x i32> @foo(<2 x i32> %tmp)  {
; CHECK-LABEL: foo:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl {{[0-9]+}}(%esp), %eax
; CHECK-NEXT:    leal 7(%eax), %ecx
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    cmovnsl %eax, %ecx
; CHECK-NEXT:    sarl $3, %ecx
; CHECK-NEXT:    movl $1717986919, %eax # imm = 0x66666667
; CHECK-NEXT:    imull {{[0-9]+}}(%esp)
; CHECK-NEXT:    movl %edx, %eax
; CHECK-NEXT:    shrl $31, %eax
; CHECK-NEXT:    sarl $2, %edx
; CHECK-NEXT:    addl %edx, %eax
; CHECK-NEXT:    movl %ecx, %edx
; CHECK-NEXT:    retl
entry:
  %tmp1 = sdiv <2 x i32> %tmp, <i32 10, i32 8>
  ret <2 x i32> %tmp1
}

