; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting -O0 -fast-isel -verify-machineinstrs -mtriple=x86_64 < %s | FileCheck %s

declare { ptr, i64 } @get()

declare void @use(ptr, i64)

define void @test(ptr %p) nounwind {
; CHECK-LABEL: test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    movq %rdi, (%rsp) # 8-byte Spill
; CHECK-NEXT:    callq get@PLT
; CHECK-NEXT:    movq (%rsp), %rdi # 8-byte Reload
; CHECK-NEXT:    movq %rdx, %rsi
; CHECK-NEXT:    movq %rsi, (%rdi)
; CHECK-NEXT:    # implicit-def: $rdi
; CHECK-NEXT:    callq use@PLT
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    retq
  %struct = call { ptr, i64 } @get()
  %struct.1 = extractvalue { ptr, i64 } %struct, 1
  store i64 %struct.1, ptr %p, align 8
  %struct.2 = extractvalue { ptr, i64 } %struct, 1
  call void @use(ptr undef, i64 %struct.2)
  ret void
}
