; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; REQUIRES: asserts
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-- | FileCheck %s

define i32 @PR61348() optsize {
; CHECK-LABEL: PR61348:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl $3, %ecx
; CHECK-NEXT:    xorl %edi, %edi
; CHECK-NEXT:    xorl %esi, %esi
; CHECK-NEXT:    rep;movsq (%rsi), %es:(%rdi)
; CHECK-NEXT:    movb 30, %al
; CHECK-NEXT:    movb %al, 30
; CHECK-NEXT:    movzwl 28, %eax
; CHECK-NEXT:    movw %ax, 28
; CHECK-NEXT:    movl 24, %eax
; CHECK-NEXT:    movl %eax, 24
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    retq
  tail call void @llvm.memcpy.p0.p0.i64(ptr align 1 null, ptr align 1 null, i64 31, i1 true)
  ret i32 0
}
declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg)
