; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc < %s -mtriple=x86_64-unknown-unknown | FileCheck %s

define i32 @_rnd(i32 %a0) {
; CHECK-LABEL: _rnd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %ecx
; CHECK-NEXT:    imull $40692, %edi, %eax # imm = 0x9EF4
; CHECK-NEXT:    movabsq $174770829514140, %rdx # imm = 0x9EF40135D59C
; CHECK-NEXT:    imulq %rcx, %rdx
; CHECK-NEXT:    shrq $63, %rdx
; CHECK-NEXT:    imull $2147483399, %edx, %ecx # imm = 0x7FFFFF07
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    retq
  %x = zext i32 %a0 to i64
  %y = mul i64 40692, %x
  %z = urem i64 %y, 2147483399
  %r = trunc i64 %z to i32
  ret i32 %r
}
