; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -combiner-topological-sorting --mtriple=x86_64 -o - %s | FileCheck %s

define i64 @test(i64 %x, i64 %y, i64 %a, i64 %b) {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    testq %rsi, %rsi
; CHECK-NEXT:    jg .LBB0_2
; CHECK-NEXT:  # %bb.1: # %entry
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    leaq -1(%rdi), %rcx
; CHECK-NEXT:    andq %rdi, %rcx
; CHECK-NEXT:    jne .LBB0_2
; CHECK-NEXT:  # %bb.3: # %if.end
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_2: # %if.then
; CHECK-NEXT:    movq %rdx, %rax
; CHECK-NEXT:    retq
entry:
  %ctpop = call i64 @llvm.ctpop.i64(i64 %x)
  %cmp1 = icmp ugt i64 %ctpop, 1
  %cmp2 = icmp sgt i64 %y, 0
  %cmp = or i1 %cmp2, %cmp1
  br i1 %cmp, label %if.then, label %if.end

if.then:
  br label %if.end

if.end:
  %res = phi i64 [ %a, %if.then ], [ %b, %entry ]
  ret i64 %res
}
