; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=x86_64-linux-gnu -verify-machineinstrs < %s -o - | FileCheck %s --check-prefix=CHECK

define i1 @ptrtoaddr_1(ptr %p) {
; CHECK-LABEL: ptrtoaddr_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    xorb $1, %al
; CHECK-NEXT:    # kill: def $al killed $al killed $rax
; CHECK-NEXT:    retq
entry:
  %addr = ptrtoaddr ptr %p to i1
  %ret = xor i1 %addr, 1
  ret i1 %ret
}

define i8 @ptrtoaddr_8(ptr %p) {
; CHECK-LABEL: ptrtoaddr_8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    notb %al
; CHECK-NEXT:    # kill: def $al killed $al killed $rax
; CHECK-NEXT:    retq
entry:
  %addr = ptrtoaddr ptr %p to i8
  %ret = xor i8 %addr, -1
  ret i8 %ret
}

define i16 @ptrtoaddr_16(ptr %p) {
; CHECK-LABEL: ptrtoaddr_16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    notl %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $rax
; CHECK-NEXT:    retq
entry:
  %addr = ptrtoaddr ptr %p to i16
  %ret = xor i16 %addr, -1
  ret i16 %ret
}

define i32 @ptrtoaddr_s32_p0(ptr %p) {
; CHECK-LABEL: ptrtoaddr_s32_p0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    notl %eax
; CHECK-NEXT:    # kill: def $eax killed $eax killed $rax
; CHECK-NEXT:    retq
entry:
  %addr = ptrtoaddr ptr %p to i32
  %ret = xor i32 %addr, -1
  ret i32 %ret
}

define i64 @ptrtoaddr_s64_p0(ptr %p) {
; CHECK-LABEL: ptrtoaddr_s64_p0:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    notq %rax
; CHECK-NEXT:    retq
entry:
  %addr = ptrtoaddr ptr %p to i64
  %ret = xor i64 %addr, -1
  ret i64 %ret
}
