; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-unknown-unknown | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64-linux -verify-machineinstrs | FileCheck %s --check-prefix=X64-LINUX
; RUN: llc < %s -mtriple=x86_64-win32 | FileCheck %s --check-prefix=X64-WIN32

define i64 @test1(i16 %a) {
; X86-LABEL: test1:
; X86:       # %bb.0:
; X86-NEXT:    movzwl {{[0-9]+}}(%esp), %eax
; X86-NEXT:    movl $42, %ecx
; X86-NEXT:    mull %ecx
; X86-NEXT:    retl
;
; X64-LINUX-LABEL: test1:
; X64-LINUX:       # %bb.0:
; X64-LINUX-NEXT:    movzwl %di, %eax
; X64-LINUX-NEXT:    imull $42, %eax, %eax
; X64-LINUX-NEXT:    retq
;
; X64-WIN32-LABEL: test1:
; X64-WIN32:       # %bb.0:
; X64-WIN32-NEXT:    movzwl %cx, %eax
; X64-WIN32-NEXT:    imull $42, %eax, %eax
; X64-WIN32-NEXT:    retq

  %zext_a = zext i16 %a to i64
  %mul = mul i64 %zext_a, 42
  ret i64 %mul
}
