# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=x86_64-unknown-linux-gnu -enable-subreg-liveness -verify-machineinstrs -start-before=register-coalescer -stop-after=register-coalescer %s -o - | FileCheck %s

# Coalescing can create an undef subrange PHI input on a predecessor edge where
# the usual PHI-copy insertion point is before a later terminator read of the
# same virtual register. The repair must be inserted on a split edge so it does
# not clobber the terminator read in the predecessor.

---
name: test
tracksRegLiveness: true
jumpTable:
  kind: block-address
  entries:
    - id: 0
      blocks: [ '%bb.5', '%bb.4' ]
body: |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $al, $dl
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].sub_8bit:gr16_abcd = COPY $al
  ; CHECK-NEXT:   [[COPY:%[0-9]+]].sub_8bit_hi:gr16_abcd = COPY $dl
  ; CHECK-NEXT:   JMP_1 %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   TEST32rr [[MOV32r0_]], [[MOV32r0_]], implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.3, 4, implicit killed $eflags
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   JMP_1 %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.6(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   KILL implicit [[COPY]].sub_8bit
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gr64_nosp = IMPLICIT_DEF
  ; CHECK-NEXT:   JMP64m $noreg, 8, [[DEF]], %jump-table.0, $noreg, implicit [[COPY]] :: (load (s64) from jump-table)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.6:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].sub_8bit_hi:gr16_abcd = IMPLICIT_DEF
  ; CHECK-NEXT:   JMP_1 %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5:
  ; CHECK-NEXT:   $al = COPY [[COPY]].sub_8bit_hi
  ; CHECK-NEXT:   RET 0, $al

  bb.0:
    successors: %bb.1
    liveins: $al, $dl

    %0:gr8 = COPY $al
    %7:gr8 = COPY $dl
    undef %1.sub_8bit:gr16_abcd = COPY %0
    JMP_1 %bb.1

  bb.1:
    successors: %bb.2, %bb.3

    %5:gr32 = MOV32r0 implicit-def dead $eflags
    TEST32rr %5, %5, implicit-def $eflags
    JCC_1 %bb.3, 4, implicit killed $eflags
    JMP_1 %bb.2

  bb.2:
    successors: %bb.5

    %1.sub_8bit_hi:gr16_abcd = COPY %7
    %2:gr8 = COPY %1.sub_8bit_hi
    JMP_1 %bb.5

  bb.3:
    successors: %bb.5, %bb.4

    %2:gr8 = IMPLICIT_DEF
    KILL implicit %1.sub_8bit
    %9:gr64_nosp = IMPLICIT_DEF
    JMP64m $noreg, 8, %9, %jump-table.0, $noreg, implicit %1 :: (load (s64) from jump-table)

  bb.4:
    RET 0

  bb.5:
    %4:gr8 = COPY %2
    $al = COPY %4
    RET 0, killed $al

...
---
name: test_inlineasm_target
tracksRegLiveness: true
jumpTable:
  kind: block-address
  entries:
    - id: 0
      blocks: [ '%bb.5', '%bb.4' ]
body: |
  ; CHECK-LABEL: name: test_inlineasm_target
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $al, $dl
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   undef [[COPY:%[0-9]+]].sub_8bit:gr16_abcd = COPY $al
  ; CHECK-NEXT:   [[COPY]].sub_8bit_hi:gr16_abcd = COPY $dl
  ; CHECK-NEXT:   JMP_1 %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[MOV32r0_:%[0-9]+]]:gr32 = MOV32r0 implicit-def dead $eflags
  ; CHECK-NEXT:   TEST32rr [[MOV32r0_]], [[MOV32r0_]], implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.3, 4, implicit killed $eflags
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   successors: %bb.5(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:gr8 = COPY [[COPY]].sub_8bit_hi
  ; CHECK-NEXT:   JMP_1 %bb.5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   successors: %bb.5(0x40000000), %bb.4(0x40000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY1]]:gr8 = IMPLICIT_DEF
  ; CHECK-NEXT:   KILL implicit [[COPY]].sub_8bit
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:gr64_nosp = IMPLICIT_DEF
  ; CHECK-NEXT:   JMP64m $noreg, 8, [[DEF]], %jump-table.0, $noreg, implicit [[COPY]] :: (load (s64) from jump-table)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.5 (inlineasm-br-indirect-target):
  ; CHECK-NEXT:   $al = COPY [[COPY1]]
  ; CHECK-NEXT:   RET 0, $al

  bb.0:
    successors: %bb.1
    liveins: $al, $dl

    %0:gr8 = COPY $al
    %7:gr8 = COPY $dl
    undef %1.sub_8bit:gr16_abcd = COPY %0
    JMP_1 %bb.1

  bb.1:
    successors: %bb.2, %bb.3

    %5:gr32 = MOV32r0 implicit-def dead $eflags
    TEST32rr %5, %5, implicit-def $eflags
    JCC_1 %bb.3, 4, implicit killed $eflags
    JMP_1 %bb.2

  bb.2:
    successors: %bb.5

    %1.sub_8bit_hi:gr16_abcd = COPY %7
    %2:gr8 = COPY %1.sub_8bit_hi
    JMP_1 %bb.5

  bb.3:
    successors: %bb.5, %bb.4

    %2:gr8 = IMPLICIT_DEF
    KILL implicit %1.sub_8bit
    %9:gr64_nosp = IMPLICIT_DEF
    JMP64m $noreg, 8, %9, %jump-table.0, $noreg, implicit %1 :: (load (s64) from jump-table)

  bb.4:
    RET 0

  bb.5 (inlineasm-br-indirect-target):
    %4:gr8 = COPY %2
    $al = COPY %4
    RET 0, killed $al

...
