; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -stack-symbol-ordering=0 -mtriple=i686-windows-msvc < %s | FileCheck %s

; 32-bit catch-all has to use a filter function because that's how it saves the
; exception code.

@str = linkonce_odr unnamed_addr constant [27 x i8] c"GetExceptionCode(): 0x%lx\0A\00", align 1

declare i32 @_except_handler3(...)
declare void @crash()
declare i32 @printf(ptr nocapture readonly, ...) nounwind
declare i32 @llvm.eh.typeid.for(ptr)
declare ptr @llvm.frameaddress(i32)
declare ptr @llvm.localrecover(ptr, ptr, i32)
declare void @llvm.localescape(...)
declare ptr @llvm.eh.recoverfp(ptr, ptr)

define i32 @main() personality ptr @_except_handler3 {
; CHECK-LABEL: main:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    pushl %ebx
; CHECK-NEXT:    pushl %edi
; CHECK-NEXT:    pushl %esi
; CHECK-NEXT:    andl $-8, %esp
; CHECK-NEXT:    subl $40, %esp
; CHECK-NEXT:    movl %esp, %esi
; CHECK-NEXT:    movl %ebp, 4(%esi)
; CHECK-NEXT:  Lmain$frame_escape_0 = 8
; CHECK-NEXT:    movl %esp, 12(%esi)
; CHECK-NEXT:    movl $-1, 32(%esi)
; CHECK-NEXT:    movl $L__ehtable$main, 28(%esi)
; CHECK-NEXT:    movl $__except_handler3, 24(%esi)
; CHECK-NEXT:    movl %fs:0, %eax
; CHECK-NEXT:    movl %eax, 20(%esi)
; CHECK-NEXT:    leal 20(%esi), %eax
; CHECK-NEXT:    movl %eax, %fs:0
; CHECK-NEXT:    movl $0, 32(%esi)
; CHECK-NEXT:    calll _crash
; CHECK-NEXT:  LBB0_2: # %__try.cont
; CHECK-NEXT:    movl 20(%esi), %eax
; CHECK-NEXT:    movl %eax, %fs:0
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    leal -12(%ebp), %esp
; CHECK-NEXT:    popl %esi
; CHECK-NEXT:    popl %edi
; CHECK-NEXT:    popl %ebx
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    retl
; CHECK-NEXT:  LBB0_1: # %__except
; CHECK-NEXT:  $ehgcr_0_1:
; CHECK-NEXT:    movl -24(%ebp), %esp
; CHECK-NEXT:    leal -36(%ebp), %esi
; CHECK-NEXT:    movl 4(%esi), %ebp
; CHECK-NEXT:    movl $-1, 32(%esi)
; CHECK-NEXT:    pushl 8(%esi)
; CHECK-NEXT:    pushl $_str
; CHECK-NEXT:    calll _printf
; CHECK-NEXT:    addl $8, %esp
; CHECK-NEXT:    jmp LBB0_2
; CHECK-NEXT:  Lfunc_end0:
entry:
  ; The EH code allocation is overaligned, triggering realignment.
  %__exceptioncode = alloca i32, align 8
  call void (...) @llvm.localescape(ptr %__exceptioncode)
  invoke void @crash() #5
          to label %__try.cont unwind label %lpad

lpad:                                             ; preds = %entry
  %cs1 = catchswitch within none [label %__except] unwind to caller

__except:                                         ; preds = %lpad
  %p = catchpad within %cs1 [ptr @"filt$main"]
  %code = load i32, ptr %__exceptioncode, align 4
  %call = call i32 (ptr, ...) @printf(ptr @str, i32 %code) #4 [ "funclet"(token %p) ]
  catchret from %p to label %__try.cont

__try.cont:                                       ; preds = %entry, %__except
  ret i32 0
}

define internal i32 @"filt$main"() {
; CHECK-LABEL: filt$main:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushl %ebp
; CHECK-NEXT:    movl %esp, %ebp
; CHECK-NEXT:    movl (%ebp), %eax
; CHECK-NEXT:    movl $Lmain$parent_frame_offset, %ecx
; CHECK-NEXT:    movl -20(%eax), %edx
; CHECK-NEXT:    subl %ecx, %eax
; CHECK-NEXT:    movl (%edx), %ecx
; CHECK-NEXT:    movl (%ecx), %ecx
; CHECK-NEXT:    movl $Lmain$frame_escape_0, %edx
; CHECK-NEXT:    movl %ecx, -24(%edx,%eax)
; CHECK-NEXT:    movl $1, %eax
; CHECK-NEXT:    popl %ebp
; CHECK-NEXT:    retl
entry:
  %ebp = tail call ptr @llvm.frameaddress(i32 1)
  %parentfp = tail call ptr @llvm.eh.recoverfp(ptr @main, ptr %ebp)
  %code.i8 = tail call ptr @llvm.localrecover(ptr @main, ptr %parentfp, i32 0)
  %info.addr = getelementptr inbounds i8, ptr %ebp, i32 -20
  %0 = load ptr, ptr %info.addr, align 4
  %1 = load ptr, ptr %0, align 4
  %2 = load i32, ptr %1, align 4
  store i32 %2, ptr %code.i8, align 4
  ret i32 1
}

; Check that we can get the exception code from eax to the printf.

; CHECK-LABEL: _main:
; CHECK: Lmain$frame_escape_0 = [[code_offs:[-0-9]+]]
; CHECK: movl %esp, [[reg_offs:[-0-9]+]](%esi)
; CHECK: movl $L__ehtable$main,
;       EH state 0
; CHECK: movl $0, 32(%esi)
; CHECK: calll _crash
; CHECK: retl
; CHECK: LBB0_[[lpbb:[0-9]+]]: # %__except
;       Restore ESP
; CHECK: movl -24(%ebp), %esp
;       Restore ESI
; CHECK: leal -36(%ebp), %esi
;       Restore EBP
; CHECK: movl 4(%esi), %ebp
; CHECK: movl [[code_offs]](%esi), %[[code:[a-z]+]]
; CHECK: pushl %[[code]]
; CHECK: pushl $_str
; CHECK: calll _printf

; CHECK: .section .xdata,"dr"
; CHECK: Lmain$parent_frame_offset = [[reg_offs]]
; CHECK: L__ehtable$main
; CHECK-NEXT: .long -1
; CHECK-NEXT: .long _filt$main
; CHECK-NEXT: .long LBB0_[[lpbb]]

; CHECK-LABEL: _filt$main:
; CHECK: pushl %ebp
; CHECK: movl %esp, %ebp
; CHECK: movl (%ebp), %[[oldebp:[a-z]+]]
; CHECK: movl -20(%[[oldebp]]), %[[ehinfo:[a-z]+]]
; CHECK: movl (%[[ehinfo]]), %[[ehrec:[a-z]+]]
; CHECK: movl (%[[ehrec]]), %[[ehcode:[a-z]+]]
; CHECK: movl %[[ehcode]], {{.*}}(%{{.*}})
