; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v2 | FileCheck %s
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mcpu=x86-64-v2 -mattr=+ndd | FileCheck --check-prefix=NDD %s

define i128 @select_eq_i128(ptr %a) {
; CHECK-LABEL: select_eq_i128:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movdqa (%rdi), %xmm0
; CHECK-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    ptest %xmm0, %xmm0
; CHECK-NEXT:    setne %al
; CHECK-NEXT:    addq $-1, %rax
; CHECK-NEXT:    movabsq $9223372036854775807, %rdx # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    adcq $0, %rdx
; CHECK-NEXT:    retq
;
; NDD-LABEL: select_eq_i128:
; NDD:       # %bb.0:
; NDD-NEXT:    movdqa (%rdi), %xmm0
; NDD-NEXT:    pxor {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; NDD-NEXT:    xorl %eax, %eax
; NDD-NEXT:    ptest %xmm0, %xmm0
; NDD-NEXT:    setne %al
; NDD-NEXT:    addq $-1, %rax
; NDD-NEXT:    movabsq $9223372036854775807, %rdx # imm = 0x7FFFFFFFFFFFFFFF
; NDD-NEXT:    adcq $0, %rdx
; NDD-NEXT:    retq
  %1 = load i128, ptr %a, align 16
  %cmp = icmp eq i128 %1, 1
  %cond = select i1 %cmp, i128 170141183460469231731687303715884105727, i128 -170141183460469231731687303715884105728
  ret i128 %cond
}
