# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=x86_64-gnu-linux -mcpu=sandybridge -run-pass=machine-combiner %s -o - | FileCheck %s --check-prefixes=FAST-SHLD
# RUN: llc -mtriple=x86_64-gnu-linux -mcpu=znver1     -run-pass=machine-combiner %s -o - | FileCheck %s --check-prefixes=SLOW-SHLD
# RUN: llc -mtriple=x86_64-gnu-linux -mcpu=btver2     -run-pass=machine-combiner %s -o - | FileCheck %s --check-prefixes=SLOW-SHLD-SLOW-LEA

---
name:            shld_rri32_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $eax, $ebx
    ; FAST-SHLD-LABEL: name: shld_rri32_small
    ; FAST-SHLD: liveins: $eax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: [[SHLD32rri8_:%[0-9]+]]:gr32 = SHLD32rri8 [[COPY]], [[COPY1]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: $eax = COPY [[SHLD32rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_rri32_small
    ; SLOW-SHLD: liveins: $eax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY1]], 30, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA32r:%[0-9]+]]:gr32 = LEA32r killed [[SHR32ri]], 4, [[COPY]], 0, $noreg
    ; SLOW-SHLD-NEXT: $eax = COPY [[LEA32r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_rri32_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $eax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY]], 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY1]], 30, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[OR32rr:%[0-9]+]]:gr32 = OR32rr killed [[SHL32ri]], killed [[SHR32ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: $eax = COPY [[OR32rr]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr32 = COPY $eax
    %0:gr32 = COPY $ebx
    %2:gr32 = SHLD32rri8 %1, %0, 2, implicit-def $eflags
    $eax = COPY %2
    RET 0, implicit $rax
...


---
name:            shld_rri32_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $eax, $ebx
    ; FAST-SHLD-LABEL: name: shld_rri32_mid
    ; FAST-SHLD: liveins: $eax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: [[SHLD32rri8_:%[0-9]+]]:gr32 = SHLD32rri8 [[COPY]], [[COPY1]], 16, implicit-def $eflags
    ; FAST-SHLD-NEXT: $eax = COPY [[SHLD32rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_rri32_mid
    ; SLOW-SHLD: liveins: $eax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY1]], 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA32r:%[0-9]+]]:gr32 = LEA32r killed [[SHL32ri]], 1, killed [[SHR32ri]], 0, $noreg
    ; SLOW-SHLD-NEXT: $eax = COPY [[LEA32r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_rri32_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $eax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY1]], 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[LEA32r:%[0-9]+]]:gr32 = LEA32r killed [[SHL32ri]], 1, killed [[SHR32ri]], 0, $noreg
    ; SLOW-SHLD-SLOW-LEA-NEXT: $eax = COPY [[LEA32r]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr32 = COPY $eax
    %0:gr32 = COPY $ebx
    %2:gr32 = SHLD32rri8 %1, %0, 16, implicit-def $eflags
    $eax = COPY %2
    RET 0, implicit $rax
...


---
name:            shrd_rri32_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $eax, $ebx
    ; FAST-SHLD-LABEL: name: shrd_rri32_small
    ; FAST-SHLD: liveins: $eax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: [[SHRD32rri8_:%[0-9]+]]:gr32 = SHRD32rri8 [[COPY]], [[COPY1]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: $eax = COPY [[SHRD32rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_rri32_small
    ; SLOW-SHLD: liveins: $eax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 2, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY1]], 30, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA32r:%[0-9]+]]:gr32 = LEA32r killed [[SHR32ri]], 1, killed [[SHL32ri]], 0, $noreg
    ; SLOW-SHLD-NEXT: $eax = COPY [[LEA32r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_rri32_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $eax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY1]], 30, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[LEA32r:%[0-9]+]]:gr32 = LEA32r killed [[SHR32ri]], 1, killed [[SHL32ri]], 0, $noreg
    ; SLOW-SHLD-SLOW-LEA-NEXT: $eax = COPY [[LEA32r]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr32 = COPY $eax
    %0:gr32 = COPY $ebx
    %2:gr32 = SHRD32rri8 %1, %0, 2, implicit-def $eflags
    $eax = COPY %2
    RET 0, implicit $rax
...


---
name:            shrd_rri32_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $eax, $ebx
    ; FAST-SHLD-LABEL: name: shrd_rri32_mid
    ; FAST-SHLD: liveins: $eax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: [[SHRD32rri8_:%[0-9]+]]:gr32 = SHRD32rri8 [[COPY]], [[COPY1]], 16, implicit-def $eflags
    ; FAST-SHLD-NEXT: $eax = COPY [[SHRD32rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_rri32_mid
    ; SLOW-SHLD: liveins: $eax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY1]], 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA32r:%[0-9]+]]:gr32 = LEA32r killed [[SHR32ri]], 1, killed [[SHL32ri]], 0, $noreg
    ; SLOW-SHLD-NEXT: $eax = COPY [[LEA32r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_rri32_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $eax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $eax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY1]], 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[LEA32r:%[0-9]+]]:gr32 = LEA32r killed [[SHR32ri]], 1, killed [[SHL32ri]], 0, $noreg
    ; SLOW-SHLD-SLOW-LEA-NEXT: $eax = COPY [[LEA32r]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr32 = COPY $eax
    %0:gr32 = COPY $ebx
    %2:gr32 = SHRD32rri8 %1, %0, 16, implicit-def $eflags
    $eax = COPY %2
    RET 0, implicit $rax
...


---
name:            shld_mri32_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $ebx

    ; FAST-SHLD-LABEL: name: shld_mri32_small
    ; FAST-SHLD: liveins: $rax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: SHLD32mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_mri32_small
    ; SLOW-SHLD: liveins: $rax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: SHL32mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 30, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHR32ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_mri32_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHL32mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 30, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHR32ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr32 = COPY $ebx
    SHLD32mri8 $rax, 1, $noreg, 0, $noreg, %0, 2, implicit-def $eflags

    RET 0, implicit $rax
...


---
name:            shld_mri32_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $ebx

    ; FAST-SHLD-LABEL: name: shld_mri32_mid
    ; FAST-SHLD: liveins: $rax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: SHLD32mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 16, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_mri32_mid
    ; SLOW-SHLD: liveins: $rax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: SHL32mi $rax, 1, $noreg, 0, $noreg, 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHR32ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_mri32_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHL32mi $rax, 1, $noreg, 0, $noreg, 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR32ri:%[0-9]+]]:gr32 = SHR32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHR32ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr32 = COPY $ebx
    SHLD32mri8 $rax, 1, $noreg, 0, $noreg, %0, 16, implicit-def $eflags

    RET 0, implicit $rax
...


---
name:            shrd_mri32_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $ebx

    ; FAST-SHLD-LABEL: name: shrd_mri32_small
    ; FAST-SHLD: liveins: $rax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: SHRD32mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_mri32_small
    ; SLOW-SHLD: liveins: $rax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: SHR32mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY]], 30, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHL32ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_mri32_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHR32mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY]], 30, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHL32ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr32 = COPY $ebx
    SHRD32mri8 $rax, 1, $noreg, 0, $noreg, %0, 2, implicit-def $eflags

    RET 0, implicit $rax
...


---
name:            shrd_mri32_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $ebx

    ; FAST-SHLD-LABEL: name: shrd_mri32_mid
    ; FAST-SHLD: liveins: $rax, $ebx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; FAST-SHLD-NEXT: SHRD32mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 16, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_mri32_mid
    ; SLOW-SHLD: liveins: $rax, $ebx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-NEXT: SHR32mi $rax, 1, $noreg, 0, $noreg, 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHL32ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_mri32_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr32 = COPY $ebx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHR32mi $rax, 1, $noreg, 0, $noreg, 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL32ri:%[0-9]+]]:gr32 = SHL32ri [[COPY]], 16, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR32mr $rax, 1, $noreg, 0, $noreg, killed [[SHL32ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr32 = COPY $ebx
    SHRD32mri8 $rax, 1, $noreg, 0, $noreg, %0, 16, implicit-def $eflags

    RET 0, implicit $rax
...


---
name:            shld_rri64_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx
    ; FAST-SHLD-LABEL: name: shld_rri64_small
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: [[SHLD64rri8_:%[0-9]+]]:gr64 = SHLD64rri8 [[COPY]], [[COPY1]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: $rax = COPY [[SHLD64rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_rri64_small
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY1]], 62, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA64r:%[0-9]+]]:gr64 = LEA64r killed [[SHR64ri]], 4, [[COPY]], 0, $noreg
    ; SLOW-SHLD-NEXT: $rax = COPY [[LEA64r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_rri64_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY]], 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY1]], 62, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[OR64rr:%[0-9]+]]:gr64 = OR64rr killed [[SHL64ri]], killed [[SHR64ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: $rax = COPY [[OR64rr]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr64 = COPY $rax
    %0:gr64 = COPY $rbx
    %2:gr64 = SHLD64rri8 %1, %0, 2, implicit-def $eflags
    $rax = COPY %2
    RET 0, implicit $rax
...


---
name:            shld_rri64_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx
    ; FAST-SHLD-LABEL: name: shld_rri64_mid
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: [[SHLD64rri8_:%[0-9]+]]:gr64 = SHLD64rri8 [[COPY]], [[COPY1]], 32, implicit-def $eflags
    ; FAST-SHLD-NEXT: $rax = COPY [[SHLD64rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_rri64_mid
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY1]], 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA64r:%[0-9]+]]:gr64 = LEA64r killed [[SHL64ri]], 1, killed [[SHR64ri]], 0, $noreg
    ; SLOW-SHLD-NEXT: $rax = COPY [[LEA64r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_rri64_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY1]], 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[LEA64r:%[0-9]+]]:gr64 = LEA64r killed [[SHL64ri]], 1, killed [[SHR64ri]], 0, $noreg
    ; SLOW-SHLD-SLOW-LEA-NEXT: $rax = COPY [[LEA64r]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr64 = COPY $rax
    %0:gr64 = COPY $rbx
    %2:gr64 = SHLD64rri8 %1, %0, 32, implicit-def $eflags
    $rax = COPY %2
    RET 0, implicit $rax
...


---
name:            shrd_rri64_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx
    ; FAST-SHLD-LABEL: name: shrd_rri64_small
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: [[SHRD64rri8_:%[0-9]+]]:gr64 = SHRD64rri8 [[COPY]], [[COPY1]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: $rax = COPY [[SHRD64rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_rri64_small
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 2, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY1]], 62, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA64r:%[0-9]+]]:gr64 = LEA64r killed [[SHR64ri]], 1, killed [[SHL64ri]], 0, $noreg
    ; SLOW-SHLD-NEXT: $rax = COPY [[LEA64r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_rri64_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY1]], 62, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[LEA64r:%[0-9]+]]:gr64 = LEA64r killed [[SHR64ri]], 1, killed [[SHL64ri]], 0, $noreg
    ; SLOW-SHLD-SLOW-LEA-NEXT: $rax = COPY [[LEA64r]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr64 = COPY $rax
    %0:gr64 = COPY $rbx
    %2:gr64 = SHRD64rri8 %1, %0, 2, implicit-def $eflags
    $rax = COPY %2
    RET 0, implicit $rax
...


---
name:            shrd_rri64_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx
    ; FAST-SHLD-LABEL: name: shrd_rri64_mid
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; FAST-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: [[SHRD64rri8_:%[0-9]+]]:gr64 = SHRD64rri8 [[COPY]], [[COPY1]], 32, implicit-def $eflags
    ; FAST-SHLD-NEXT: $rax = COPY [[SHRD64rri8_]]
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_rri64_mid
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY1]], 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[LEA64r:%[0-9]+]]:gr64 = LEA64r killed [[SHR64ri]], 1, killed [[SHL64ri]], 0, $noreg
    ; SLOW-SHLD-NEXT: $rax = COPY [[LEA64r]]
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_rri64_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY1]], 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[LEA64r:%[0-9]+]]:gr64 = LEA64r killed [[SHR64ri]], 1, killed [[SHL64ri]], 0, $noreg
    ; SLOW-SHLD-SLOW-LEA-NEXT: $rax = COPY [[LEA64r]]
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %1:gr64 = COPY $rax
    %0:gr64 = COPY $rbx
    %2:gr64 = SHRD64rri8 %1, %0, 32, implicit-def $eflags
    $rax = COPY %2
    RET 0, implicit $rax
...


---
name:            shld_mri64_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx

    ; FAST-SHLD-LABEL: name: shld_mri64_small
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: SHLD64mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_mri64_small
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: SHL64mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 62, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHR64ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_mri64_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHL64mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 62, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHR64ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr64 = COPY $rbx
    SHLD64mri8 $rax, 1, $noreg, 0, $noreg, %0, 2, implicit-def $eflags

    RET 0, implicit $rax
...


---
name:            shld_mri64_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx

    ; FAST-SHLD-LABEL: name: shld_mri64_mid
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: SHLD64mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 32, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shld_mri64_mid
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: SHL64mi $rax, 1, $noreg, 0, $noreg, 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHR64ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shld_mri64_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHL64mi $rax, 1, $noreg, 0, $noreg, 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHR64ri:%[0-9]+]]:gr64 = SHR64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHR64ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr64 = COPY $rbx
    SHLD64mri8 $rax, 1, $noreg, 0, $noreg, %0, 32, implicit-def $eflags

    RET 0, implicit $rax
...


---
name:            shrd_mri64_small
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx

    ; FAST-SHLD-LABEL: name: shrd_mri64_small
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: SHRD64mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 2, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_mri64_small
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: SHR64mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY]], 62, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHL64ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_mri64_small
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHR64mi $rax, 1, $noreg, 0, $noreg, 2, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY]], 62, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHL64ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr64 = COPY $rbx
    SHRD64mri8 $rax, 1, $noreg, 0, $noreg, %0, 2, implicit-def $eflags

    RET 0, implicit $rax
...


---
name:            shrd_mri64_mid
alignment:       16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx

    ; FAST-SHLD-LABEL: name: shrd_mri64_mid
    ; FAST-SHLD: liveins: $rax, $rbx
    ; FAST-SHLD-NEXT: {{  $}}
    ; FAST-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; FAST-SHLD-NEXT: SHRD64mri8 $rax, 1, $noreg, 0, $noreg, [[COPY]], 32, implicit-def $eflags
    ; FAST-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-LABEL: name: shrd_mri64_mid
    ; SLOW-SHLD: liveins: $rax, $rbx
    ; SLOW-SHLD-NEXT: {{  $}}
    ; SLOW-SHLD-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-NEXT: SHR64mi $rax, 1, $noreg, 0, $noreg, 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHL64ri]], implicit-def $eflags
    ; SLOW-SHLD-NEXT: RET 0, implicit $rax
    ;
    ; SLOW-SHLD-SLOW-LEA-LABEL: name: shrd_mri64_mid
    ; SLOW-SHLD-SLOW-LEA: liveins: $rax, $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: {{  $}}
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[COPY:%[0-9]+]]:gr64 = COPY $rbx
    ; SLOW-SHLD-SLOW-LEA-NEXT: SHR64mi $rax, 1, $noreg, 0, $noreg, 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: [[SHL64ri:%[0-9]+]]:gr64 = SHL64ri [[COPY]], 32, implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: OR64mr $rax, 1, $noreg, 0, $noreg, killed [[SHL64ri]], implicit-def $eflags
    ; SLOW-SHLD-SLOW-LEA-NEXT: RET 0, implicit $rax
    %0:gr64 = COPY $rbx
    SHRD64mri8 $rax, 1, $noreg, 0, $noreg, %0, 32, implicit-def $eflags

    RET 0, implicit $rax
...
