; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=i686-- | FileCheck %s --check-prefix=X86
; RUN: llc < %s -mtriple=x86_64-- | FileCheck %s --check-prefix=X64
;
; Test i256 shifts with narrow (i32) shift amounts. These use the
; ExpandShiftWithUnknownAmountBit path (parts expansion) rather than the
; shift-through-stack approach, because ExpandShiftWithKnownAmountBit
; cannot determine the high bit of the shift amount.

define void @shl_i256_by_i32(i256 %x, i32 %amt, ptr %r) nounwind {
; X86-LABEL: shl_i256_by_i32:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $112, %esp
; X86-NEXT:    movzbl 40(%ebp), %ecx
; X86-NEXT:    movl 8(%ebp), %eax
; X86-NEXT:    movl 12(%ebp), %edx
; X86-NEXT:    movl 16(%ebp), %esi
; X86-NEXT:    movl 36(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 32(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 28(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 24(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 20(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $3, %al
; X86-NEXT:    andb $28, %al
; X86-NEXT:    negb %al
; X86-NEXT:    movsbl %al, %edi
; X86-NEXT:    movl 68(%esp,%edi), %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 72(%esp,%edi), %eax
; X86-NEXT:    movl %eax, %esi
; X86-NEXT:    shldl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 76(%esp,%edi), %edx
; X86-NEXT:    movl %edx, %esi
; X86-NEXT:    shldl %cl, %eax, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 80(%esp,%edi), %eax
; X86-NEXT:    movl %eax, %esi
; X86-NEXT:    shldl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 84(%esp,%edi), %edx
; X86-NEXT:    movl %edx, %ebx
; X86-NEXT:    shldl %cl, %eax, %ebx
; X86-NEXT:    movl 88(%esp,%edi), %esi
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    shldl %cl, %edx, %eax
; X86-NEXT:    movl 64(%esp,%edi), %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 92(%esp,%edi), %edx
; X86-NEXT:    shldl %cl, %esi, %edx
; X86-NEXT:    movl 44(%ebp), %edi
; X86-NEXT:    movl %edx, 28(%edi)
; X86-NEXT:    movl %eax, 24(%edi)
; X86-NEXT:    movl %ebx, 20(%edi)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 16(%edi)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 12(%edi)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 8(%edi)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %esi # 4-byte Reload
; X86-NEXT:    movl %esi, %eax
; X86-NEXT:    shll %cl, %eax
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edx # 4-byte Reload
; X86-NEXT:    shldl %cl, %esi, %edx
; X86-NEXT:    movl %edx, 4(%edi)
; X86-NEXT:    movl %eax, (%edi)
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl
;
; X64-LABEL: shl_i256_by_i32:
; X64:       # %bb.0:
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r8d, %eax
; X64-NEXT:    shrb $3, %al
; X64-NEXT:    andb $24, %al
; X64-NEXT:    negb %al
; X64-NEXT:    movsbq %al, %rax
; X64-NEXT:    movq -40(%rsp,%rax), %rdx
; X64-NEXT:    movq -32(%rsp,%rax), %rsi
; X64-NEXT:    movq -24(%rsp,%rax), %rdi
; X64-NEXT:    movq %rdi, %r10
; X64-NEXT:    movl %r8d, %ecx
; X64-NEXT:    shldq %cl, %rsi, %r10
; X64-NEXT:    movq -16(%rsp,%rax), %rax
; X64-NEXT:    shldq %cl, %rdi, %rax
; X64-NEXT:    movq %rdx, %rdi
; X64-NEXT:    shlq %cl, %rdi
; X64-NEXT:    shldq %cl, %rdx, %rsi
; X64-NEXT:    movq %rax, 24(%r9)
; X64-NEXT:    movq %r10, 16(%r9)
; X64-NEXT:    movq %rsi, 8(%r9)
; X64-NEXT:    movq %rdi, (%r9)
; X64-NEXT:    retq
  %amt256 = zext i32 %amt to i256
  %res = shl i256 %x, %amt256
  store i256 %res, ptr %r
  ret void
}

define void @lshr_i256_by_i32(i256 %x, i32 %amt, ptr %r) nounwind {
; X86-LABEL: lshr_i256_by_i32:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $112, %esp
; X86-NEXT:    movzbl 40(%ebp), %ecx
; X86-NEXT:    movl 8(%ebp), %eax
; X86-NEXT:    movl 12(%ebp), %edx
; X86-NEXT:    movl 16(%ebp), %esi
; X86-NEXT:    movl 36(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 32(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 28(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 24(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 20(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl $0, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $5, %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    movl 40(%esp,%eax,4), %edx
; X86-NEXT:    movl 36(%esp,%eax,4), %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 44(%esp,%eax,4), %esi
; X86-NEXT:    shrdl %cl, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 48(%esp,%eax,4), %ebx
; X86-NEXT:    shrdl %cl, %ebx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 52(%esp,%eax,4), %esi
; X86-NEXT:    shrdl %cl, %esi, %ebx
; X86-NEXT:    movl 56(%esp,%eax,4), %edx
; X86-NEXT:    shrdl %cl, %edx, %esi
; X86-NEXT:    movl 32(%esp,%eax,4), %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 60(%esp,%eax,4), %eax
; X86-NEXT:    shrdl %cl, %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shrdl %cl, %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    shrl %cl, %eax
; X86-NEXT:    movl 44(%ebp), %ecx
; X86-NEXT:    movl %eax, 28(%ecx)
; X86-NEXT:    movl %edx, 24(%ecx)
; X86-NEXT:    movl %esi, 20(%ecx)
; X86-NEXT:    movl %ebx, 16(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 12(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 8(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 4(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, (%ecx)
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl
;
; X64-LABEL: lshr_i256_by_i32:
; X64:       # %bb.0:
; X64-NEXT:    xorps %xmm0, %xmm0
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movaps %xmm0, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r8d, %eax
; X64-NEXT:    shrb $6, %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    movq -56(%rsp,%rax,8), %rdx
; X64-NEXT:    movq -72(%rsp,%rax,8), %rsi
; X64-NEXT:    movq -64(%rsp,%rax,8), %rdi
; X64-NEXT:    movq %rdi, %r10
; X64-NEXT:    movl %r8d, %ecx
; X64-NEXT:    shrdq %cl, %rdx, %r10
; X64-NEXT:    movq -48(%rsp,%rax,8), %rax
; X64-NEXT:    shrdq %cl, %rax, %rdx
; X64-NEXT:    shrdq %cl, %rdi, %rsi
; X64-NEXT:    shrq %cl, %rax
; X64-NEXT:    movq %rax, 24(%r9)
; X64-NEXT:    movq %rdx, 16(%r9)
; X64-NEXT:    movq %r10, 8(%r9)
; X64-NEXT:    movq %rsi, (%r9)
; X64-NEXT:    retq
  %amt256 = zext i32 %amt to i256
  %res = lshr i256 %x, %amt256
  store i256 %res, ptr %r
  ret void
}

define void @ashr_i256_by_i32(i256 %x, i32 %amt, ptr %r) nounwind {
; X86-LABEL: ashr_i256_by_i32:
; X86:       # %bb.0:
; X86-NEXT:    pushl %ebp
; X86-NEXT:    movl %esp, %ebp
; X86-NEXT:    pushl %ebx
; X86-NEXT:    pushl %edi
; X86-NEXT:    pushl %esi
; X86-NEXT:    andl $-16, %esp
; X86-NEXT:    subl $112, %esp
; X86-NEXT:    movzbl 40(%ebp), %ecx
; X86-NEXT:    movl 8(%ebp), %eax
; X86-NEXT:    movl 12(%ebp), %edx
; X86-NEXT:    movl 16(%ebp), %esi
; X86-NEXT:    movl 32(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 28(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 24(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 20(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl 36(%ebp), %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %esi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edx, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %eax, {{[0-9]+}}(%esp)
; X86-NEXT:    sarl $31, %edi
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %edi, {{[0-9]+}}(%esp)
; X86-NEXT:    movl %ecx, %eax
; X86-NEXT:    shrb $5, %al
; X86-NEXT:    movzbl %al, %eax
; X86-NEXT:    movl 40(%esp,%eax,4), %edx
; X86-NEXT:    movl 36(%esp,%eax,4), %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    shrdl %cl, %edx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 44(%esp,%eax,4), %esi
; X86-NEXT:    shrdl %cl, %esi, %edx
; X86-NEXT:    movl %edx, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 48(%esp,%eax,4), %ebx
; X86-NEXT:    shrdl %cl, %ebx, %esi
; X86-NEXT:    movl %esi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 52(%esp,%eax,4), %esi
; X86-NEXT:    shrdl %cl, %esi, %ebx
; X86-NEXT:    movl 56(%esp,%eax,4), %edx
; X86-NEXT:    shrdl %cl, %edx, %esi
; X86-NEXT:    movl 32(%esp,%eax,4), %edi
; X86-NEXT:    movl %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Spill
; X86-NEXT:    movl 60(%esp,%eax,4), %eax
; X86-NEXT:    shrdl %cl, %eax, %edx
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %edi # 4-byte Reload
; X86-NEXT:    shrdl %cl, %edi, {{[-0-9]+}}(%e{{[sb]}}p) # 4-byte Folded Spill
; X86-NEXT:    sarl %cl, %eax
; X86-NEXT:    movl 44(%ebp), %ecx
; X86-NEXT:    movl %eax, 28(%ecx)
; X86-NEXT:    movl %edx, 24(%ecx)
; X86-NEXT:    movl %esi, 20(%ecx)
; X86-NEXT:    movl %ebx, 16(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 12(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 8(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, 4(%ecx)
; X86-NEXT:    movl {{[-0-9]+}}(%e{{[sb]}}p), %eax # 4-byte Reload
; X86-NEXT:    movl %eax, (%ecx)
; X86-NEXT:    leal -12(%ebp), %esp
; X86-NEXT:    popl %esi
; X86-NEXT:    popl %edi
; X86-NEXT:    popl %ebx
; X86-NEXT:    popl %ebp
; X86-NEXT:    retl
;
; X64-LABEL: ashr_i256_by_i32:
; X64:       # %bb.0:
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rsi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rdi, -{{[0-9]+}}(%rsp)
; X64-NEXT:    sarq $63, %rcx
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movq %rcx, -{{[0-9]+}}(%rsp)
; X64-NEXT:    movl %r8d, %eax
; X64-NEXT:    shrb $6, %al
; X64-NEXT:    movzbl %al, %eax
; X64-NEXT:    movq -56(%rsp,%rax,8), %rdx
; X64-NEXT:    movq -72(%rsp,%rax,8), %rsi
; X64-NEXT:    movq -64(%rsp,%rax,8), %rdi
; X64-NEXT:    movq %rdi, %r10
; X64-NEXT:    movl %r8d, %ecx
; X64-NEXT:    shrdq %cl, %rdx, %r10
; X64-NEXT:    movq -48(%rsp,%rax,8), %rax
; X64-NEXT:    shrdq %cl, %rax, %rdx
; X64-NEXT:    shrdq %cl, %rdi, %rsi
; X64-NEXT:    sarq %cl, %rax
; X64-NEXT:    movq %rax, 24(%r9)
; X64-NEXT:    movq %rdx, 16(%r9)
; X64-NEXT:    movq %r10, 8(%r9)
; X64-NEXT:    movq %rsi, (%r9)
; X64-NEXT:    retq
  %amt256 = zext i32 %amt to i256
  %res = ashr i256 %x, %amt256
  store i256 %res, ptr %r
  ret void
}
