; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;RUN: llc < %s | FileCheck %s

; This test case failed on legalization of "shl" node. PR29058.

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@structMember = external local_unnamed_addr global i64, align 8

define i32 @PR29058(i8 %x, i32 %y) {
; CHECK-LABEL: PR29058:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    testb %dil, %dil
; CHECK-NEXT:    movl $2147483646, %eax # imm = 0x7FFFFFFE
; CHECK-NEXT:    cmovnel %esi, %eax
; CHECK-NEXT:    cmpb $1, %dil
; CHECK-NEXT:    sbbb %dl, %dl
; CHECK-NEXT:    orb %dl, %cl
; CHECK-NEXT:    # kill: def $cl killed $cl killed $ecx
; CHECK-NEXT:    shll %cl, %eax
; CHECK-NEXT:    movq %rax, {{.*}}(%rip)
; CHECK-NEXT:    # kill: def $eax killed $eax killed $rax
; CHECK-NEXT:    retq
entry:
  %bool_1 = icmp ne i8 %x, 0
  %bool_2 = icmp eq i8 %x, 0
  %0 = select i1 %bool_2, i32 2147483646, i32 %y
  %or_1 = select i1 %bool_1, i32 %y, i32 -1
  %shl_1 = shl i32 %0, %or_1
  %conv = zext i32 %shl_1 to i64
  store i64 %conv, i64* @structMember, align 8
  %tmp = select i1 %bool_2, i32 2147483646, i32 %y
  %lnot = icmp eq i8 %x, 0
  %or_2 = select i1 %lnot, i32 -1, i32 %y
  %shl_2 = shl i32 %tmp, %or_2
  ret i32 %shl_2
}

