; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-linux -O2 | FileCheck %s
;
; Verify smax(X, -1) and smin(X, 0) fold to bitwise shift forms.
; smax(X, -1) = or(X,  ashr(X, BW-1)) -- saves a byte vs compare+cmov on x86-64
; smin(X,  0) = and(X, ashr(X, BW-1)) -- saves a byte vs compare+cmov on x86-64
; Both also reduce instruction count on AArch64/APX. GCC PR 125921, LLVM #206153.

define i32 @smax_allones_i32(i32 %x) {
; CHECK-LABEL: smax_allones_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    sarl $31, %eax
; CHECK-NEXT:    orl %edi, %eax
; CHECK-NEXT:    retq
  %r = call i32 @llvm.smax.i32(i32 %x, i32 -1)
  ret i32 %r
}

define i64 @smax_allones_i64(i64 %x) {
; CHECK-LABEL: smax_allones_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    sarq $63, %rax
; CHECK-NEXT:    orq %rdi, %rax
; CHECK-NEXT:    retq
  %r = call i64 @llvm.smax.i64(i64 %x, i64 -1)
  ret i64 %r
}

; smax(X, 0) should NOT transform -- no 2-instruction bitwise form
define i32 @smax_zero(i32 %x) {
; CHECK-LABEL: smax_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    testl %edi, %edi
; CHECK-NEXT:    cmovgl %edi, %eax
; CHECK-NEXT:    retq
  %r = call i32 @llvm.smax.i32(i32 %x, i32 0)
  ret i32 %r
}

define i32 @smin_zero_i32(i32 %x) {
; CHECK-LABEL: smin_zero_i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    sarl $31, %eax
; CHECK-NEXT:    andl %edi, %eax
; CHECK-NEXT:    retq
  %r = call i32 @llvm.smin.i32(i32 %x, i32 0)
  ret i32 %r
}

define i64 @smin_zero_i64(i64 %x) {
; CHECK-LABEL: smin_zero_i64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    sarq $63, %rax
; CHECK-NEXT:    andq %rdi, %rax
; CHECK-NEXT:    retq
  %r = call i64 @llvm.smin.i64(i64 %x, i64 0)
  ret i64 %r
}

; smin(X, -1) should NOT transform -- no 2-instruction bitwise form exists
define i32 @smin_allones(i32 %x) {
; CHECK-LABEL: smin_allones:
; CHECK:       # %bb.0:
; CHECK-NEXT:    cmpl $-1, %edi
; CHECK-NEXT:    movl $-1, %eax
; CHECK-NEXT:    cmovll %edi, %eax
; CHECK-NEXT:    retq
  %r = call i32 @llvm.smin.i32(i32 %x, i32 -1)
  ret i32 %r
}
