# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc %s -o - -mtriple=x86_64-unknown-linux -enable-spill2reg -mattr=+sse4.1 --run-pass=spill2reg -simplify-mir -spill2reg-mem-instrs=0 -spill2reg-vec-instrs=99999 | FileCheck %s

# Check that the liveins of a MBB get updated correctly if it contains a reload
# before a spill.

# bb.0:
#  spill stack.0
#  JMP bb.1
#
# bb.1:
#  reload stack.0
#  spill stack.0
#  JMP bb.2
#
# bb.2:
#  reload stack.0


--- |
  @D0 = dso_local local_unnamed_addr global i32 0, align 4
  @U0 = dso_local local_unnamed_addr global i32 0, align 4
  define void @func() { ret void }
...
---
name: func
alignment:       16
tracksRegLiveness: true
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    4
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: func
  ; CHECK: bb.0:
  ; CHECK-NEXT:   $eax = MOV32rm $rip, 1, $noreg, @D0, $noreg :: (dereferenceable load (s32) from @D0)
  ; CHECK-NEXT:   $xmm0 = MOVDI2PDIrr $eax
  ; CHECK-NEXT:   JMP_1 %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $xmm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $eax = MOVPDI2DIrr $xmm0
  ; CHECK-NEXT:   $xmm0 = MOVDI2PDIrr $eax
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $xmm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $eax = MOVPDI2DIrr $xmm0
  ; CHECK-NEXT:   RET 0



  bb.0:
    $eax = MOV32rm $rip, 1, $noreg, @D0, $noreg :: (dereferenceable load (s32) from @D0)
    ; Spill stack.0
    MOV32mr %stack.0, 1, $noreg, 0, $noreg, killed renamable $eax :: (store (s32) into %stack.0)
    JMP_1 %bb.1

  bb.1:
    ; Reload stack.0
    $eax = MOV32rm %stack.0, 1, $noreg, 0, $noreg :: (load (s32) from %stack.0)
    ; Spill stack.0
    MOV32mr %stack.0, 1, $noreg, 0, $noreg, killed renamable $eax :: (store (s32) into %stack.0)
    JMP_1 %bb.2

  bb.2:
    ; Reload
    $eax = MOV32rm %stack.0, 1, $noreg, 0, $noreg :: (load (s32) from %stack.0)
    RET 0
...
