; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc %s -o - -mtriple=x86_64-unknown-linux -enable-spill2reg -mattr=+sse4.1 | FileCheck %s
; RUN: llc %s -o - -mtriple=x86_64-unknown-linux -enable-spill2reg -mattr=+sse4.1 | FileCheck --check-prefix=AVX %s

; End-to-end check that Spill2Reg works with 64-bit registers.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@D0 = dso_local local_unnamed_addr global i64 0, align 4
@D1 = dso_local local_unnamed_addr global i64 0, align 4
@D2 = dso_local local_unnamed_addr global i64 0, align 4
@D3 = dso_local local_unnamed_addr global i64 0, align 4
@D4 = dso_local local_unnamed_addr global i64 0, align 4
@D5 = dso_local local_unnamed_addr global i64 0, align 4
@D6 = dso_local local_unnamed_addr global i64 0, align 4
@D7 = dso_local local_unnamed_addr global i64 0, align 4
@D8 = dso_local local_unnamed_addr global i64 0, align 4
@D9 = dso_local local_unnamed_addr global i64 0, align 4
@D10 = dso_local local_unnamed_addr global i64 0, align 4
@D11 = dso_local local_unnamed_addr global i64 0, align 4
@D12 = dso_local local_unnamed_addr global i64 0, align 4
@D13 = dso_local local_unnamed_addr global i64 0, align 4
@D14 = dso_local local_unnamed_addr global i64 0, align 4
@D15 = dso_local local_unnamed_addr global i64 0, align 4
@D16 = dso_local local_unnamed_addr global i64 0, align 4
@D17 = dso_local local_unnamed_addr global i64 0, align 4
@D18 = dso_local local_unnamed_addr global i64 0, align 4
@U0 = dso_local local_unnamed_addr global i64 0, align 4
@U1 = dso_local local_unnamed_addr global i64 0, align 4
@U2 = dso_local local_unnamed_addr global i64 0, align 4
@U3 = dso_local local_unnamed_addr global i64 0, align 4
@U4 = dso_local local_unnamed_addr global i64 0, align 4
@U5 = dso_local local_unnamed_addr global i64 0, align 4
@U6 = dso_local local_unnamed_addr global i64 0, align 4
@U7 = dso_local local_unnamed_addr global i64 0, align 4
@U8 = dso_local local_unnamed_addr global i64 0, align 4
@U9 = dso_local local_unnamed_addr global i64 0, align 4
@U10 = dso_local local_unnamed_addr global i64 0, align 4
@U11 = dso_local local_unnamed_addr global i64 0, align 4
@U12 = dso_local local_unnamed_addr global i64 0, align 4
@U13 = dso_local local_unnamed_addr global i64 0, align 4
@U14 = dso_local local_unnamed_addr global i64 0, align 4
@U15 = dso_local local_unnamed_addr global i64 0, align 4
@U16 = dso_local local_unnamed_addr global i64 0, align 4
@U17 = dso_local local_unnamed_addr global i64 0, align 4
@U18 = dso_local local_unnamed_addr global i64 0, align 4

; Function Attrs: mustprogress noinline nounwind uwtable
define dso_local void @_Z5spillv() local_unnamed_addr #0 {
; CHECK-LABEL: _Z5spillv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movq D0(%rip), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq D1(%rip), %rcx
; CHECK-NEXT:    movq D2(%rip), %rdx
; CHECK-NEXT:    movq D3(%rip), %rsi
; CHECK-NEXT:    movq D4(%rip), %rdi
; CHECK-NEXT:    movq D5(%rip), %r8
; CHECK-NEXT:    movq D6(%rip), %r9
; CHECK-NEXT:    movq D7(%rip), %r10
; CHECK-NEXT:    movq D8(%rip), %r11
; CHECK-NEXT:    movq D9(%rip), %rbx
; CHECK-NEXT:    movq D10(%rip), %r14
; CHECK-NEXT:    movq D11(%rip), %r15
; CHECK-NEXT:    movq D12(%rip), %r12
; CHECK-NEXT:    movq D13(%rip), %r13
; CHECK-NEXT:    movq D14(%rip), %rbp
; CHECK-NEXT:    movq D15(%rip), %rax
; CHECK-NEXT:    movq %rax, %xmm0
; CHECK-NEXT:    movq D16(%rip), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    movq D17(%rip), %rax
; CHECK-NEXT:    movq %rax, %xmm1
; CHECK-NEXT:    movq D18(%rip), %rax
; CHECK-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, U0(%rip)
; CHECK-NEXT:    movq %rcx, U1(%rip)
; CHECK-NEXT:    movq %rdx, U2(%rip)
; CHECK-NEXT:    movq %rsi, U3(%rip)
; CHECK-NEXT:    movq %rdi, U4(%rip)
; CHECK-NEXT:    movq %r8, U5(%rip)
; CHECK-NEXT:    movq %r9, U6(%rip)
; CHECK-NEXT:    movq %r10, U7(%rip)
; CHECK-NEXT:    movq %r11, U8(%rip)
; CHECK-NEXT:    movq %rbx, U9(%rip)
; CHECK-NEXT:    movq %r14, U10(%rip)
; CHECK-NEXT:    movq %r15, U11(%rip)
; CHECK-NEXT:    movq %r12, U12(%rip)
; CHECK-NEXT:    movq %r13, U13(%rip)
; CHECK-NEXT:    movq %rbp, U14(%rip)
; CHECK-NEXT:    movq %xmm0, %rax
; CHECK-NEXT:    movq %rax, U15(%rip)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, U16(%rip)
; CHECK-NEXT:    movq %xmm1, %rax
; CHECK-NEXT:    movq %rax, U17(%rip)
; CHECK-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; CHECK-NEXT:    movq %rax, U18(%rip)
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
;
; AVX-LABEL: _Z5spillv:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    pushq %rbp
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    pushq %r15
; AVX-NEXT:    .cfi_def_cfa_offset 24
; AVX-NEXT:    pushq %r14
; AVX-NEXT:    .cfi_def_cfa_offset 32
; AVX-NEXT:    pushq %r13
; AVX-NEXT:    .cfi_def_cfa_offset 40
; AVX-NEXT:    pushq %r12
; AVX-NEXT:    .cfi_def_cfa_offset 48
; AVX-NEXT:    pushq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 56
; AVX-NEXT:    .cfi_offset %rbx, -56
; AVX-NEXT:    .cfi_offset %r12, -48
; AVX-NEXT:    .cfi_offset %r13, -40
; AVX-NEXT:    .cfi_offset %r14, -32
; AVX-NEXT:    .cfi_offset %r15, -24
; AVX-NEXT:    .cfi_offset %rbp, -16
; AVX-NEXT:    movq D0(%rip), %rax
; AVX-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX-NEXT:    movq D1(%rip), %rcx
; AVX-NEXT:    movq D2(%rip), %rdx
; AVX-NEXT:    movq D3(%rip), %rsi
; AVX-NEXT:    movq D4(%rip), %rdi
; AVX-NEXT:    movq D5(%rip), %r8
; AVX-NEXT:    movq D6(%rip), %r9
; AVX-NEXT:    movq D7(%rip), %r10
; AVX-NEXT:    movq D8(%rip), %r11
; AVX-NEXT:    movq D9(%rip), %rbx
; AVX-NEXT:    movq D10(%rip), %r14
; AVX-NEXT:    movq D11(%rip), %r15
; AVX-NEXT:    movq D12(%rip), %r12
; AVX-NEXT:    movq D13(%rip), %r13
; AVX-NEXT:    movq D14(%rip), %rbp
; AVX-NEXT:    movq D15(%rip), %rax
; AVX-NEXT:    movq %rax, %xmm0
; AVX-NEXT:    movq D16(%rip), %rax
; AVX-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX-NEXT:    movq D17(%rip), %rax
; AVX-NEXT:    movq %rax, %xmm1
; AVX-NEXT:    movq D18(%rip), %rax
; AVX-NEXT:    movq %rax, {{[-0-9]+}}(%r{{[sb]}}p) # 8-byte Spill
; AVX-NEXT:    #APP
; AVX-NEXT:    #NO_APP
; AVX-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX-NEXT:    movq %rax, U0(%rip)
; AVX-NEXT:    movq %rcx, U1(%rip)
; AVX-NEXT:    movq %rdx, U2(%rip)
; AVX-NEXT:    movq %rsi, U3(%rip)
; AVX-NEXT:    movq %rdi, U4(%rip)
; AVX-NEXT:    movq %r8, U5(%rip)
; AVX-NEXT:    movq %r9, U6(%rip)
; AVX-NEXT:    movq %r10, U7(%rip)
; AVX-NEXT:    movq %r11, U8(%rip)
; AVX-NEXT:    movq %rbx, U9(%rip)
; AVX-NEXT:    movq %r14, U10(%rip)
; AVX-NEXT:    movq %r15, U11(%rip)
; AVX-NEXT:    movq %r12, U12(%rip)
; AVX-NEXT:    movq %r13, U13(%rip)
; AVX-NEXT:    movq %rbp, U14(%rip)
; AVX-NEXT:    movq %xmm0, %rax
; AVX-NEXT:    movq %rax, U15(%rip)
; AVX-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX-NEXT:    movq %rax, U16(%rip)
; AVX-NEXT:    movq %xmm1, %rax
; AVX-NEXT:    movq %rax, U17(%rip)
; AVX-NEXT:    movq {{[-0-9]+}}(%r{{[sb]}}p), %rax # 8-byte Reload
; AVX-NEXT:    movq %rax, U18(%rip)
; AVX-NEXT:    popq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 48
; AVX-NEXT:    popq %r12
; AVX-NEXT:    .cfi_def_cfa_offset 40
; AVX-NEXT:    popq %r13
; AVX-NEXT:    .cfi_def_cfa_offset 32
; AVX-NEXT:    popq %r14
; AVX-NEXT:    .cfi_def_cfa_offset 24
; AVX-NEXT:    popq %r15
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    popq %rbp
; AVX-NEXT:    .cfi_def_cfa_offset 8
; AVX-NEXT:    retq
entry:
  %0 = load i64, i64* @D0
  %1 = load i64, i64* @D1
  %2 = load i64, i64* @D2
  %3 = load i64, i64* @D3
  %4 = load i64, i64* @D4
  %5 = load i64, i64* @D5
  %6 = load i64, i64* @D6
  %7 = load i64, i64* @D7
  %8 = load i64, i64* @D8
  %9 = load i64, i64* @D9
  %10 = load i64, i64* @D10
  %11 = load i64, i64* @D11
  %12 = load i64, i64* @D12
  %13 = load i64, i64* @D13
  %14 = load i64, i64* @D14
  %15 = load i64, i64* @D15
  %16 = load i64, i64* @D16
  %17 = load i64, i64* @D17
  %18 = load i64, i64* @D18
  call void asm sideeffect "", "~{memory}"() #1
  store i64 %0, i64* @U0
  store i64 %1, i64* @U1
  store i64 %2, i64* @U2
  store i64 %3, i64* @U3
  store i64 %4, i64* @U4
  store i64 %5, i64* @U5
  store i64 %6, i64* @U6
  store i64 %7, i64* @U7
  store i64 %8, i64* @U8
  store i64 %9, i64* @U9
  store i64 %10, i64* @U10
  store i64 %11, i64* @U11
  store i64 %12, i64* @U12
  store i64 %13, i64* @U13
  store i64 %14, i64* @U14
  store i64 %15, i64* @U15
  store i64 %16, i64* @U16
  store i64 %17, i64* @U17
  store i64 %18, i64* @U18
  ret void
}

attributes #0 = { mustprogress noinline nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { nounwind }
