# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc %s -o - -mtriple=x86_64-unknown-linux -enable-spill2reg -mattr=+sse4.1 --run-pass=spill2reg -simplify-mir -spill2reg-mem-instrs=0 -spill2reg-vec-instrs=99999 | FileCheck %s

# Check that reg liveness works correctly when the live ranges cross like this:
# BB0 BB1
#  \  /
#   BB2
#  /  \
# BB3 BB4
#
# BB0:
#   [stack.0] = ...
#   JMP BB2
# BB1:
#   [stack.1] = ...
#   JMP BB2
# BB2:
#   ...
#   JMP BB3 or BB4
# BB3:
#   ... = [stack.0]
# BB4:
#   ... = [stack.1]

--- |
  @D0 = dso_local local_unnamed_addr global i32 0, align 4
  @D1 = dso_local local_unnamed_addr global i32 0, align 4
  @U0 = dso_local local_unnamed_addr global i32 0, align 4
  @U1 = dso_local local_unnamed_addr global i32 0, align 4
  @Cond = dso_local local_unnamed_addr global i32 0, align 4
  define void @func() { ret void }
...
---
name: func
alignment:       16
tracksRegLiveness: true
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    4
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
  - { id: 1, type: spill-slot, size: 4, alignment: 4 }
machineFunctionInfo: {}
body:             |
  ; CHECK-LABEL: name: func
  ; CHECK: bb.0:
  ; CHECK-NEXT:   liveins: $xmm1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $eax = MOV32rm $rip, 1, $noreg, @D0, $noreg :: (dereferenceable load (s32) from @D0)
  ; CHECK-NEXT:   $xmm0 = MOVDI2PDIrr $eax
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $xmm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $eax = MOV32rm $rip, 1, $noreg, @D1, $noreg :: (dereferenceable load (s32) from @D1)
  ; CHECK-NEXT:   $xmm1 = MOVDI2PDIrr $eax
  ; CHECK-NEXT:   JMP_1 %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $xmm0, $xmm1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $eax = MOV32rm $rip, 1, $noreg, @Cond, $noreg :: (dereferenceable load (s32) from @Cond)
  ; CHECK-NEXT:   TEST32rr $eax, $eax, implicit-def $eflags
  ; CHECK-NEXT:   JCC_1 %bb.3, 2, implicit $eflags
  ; CHECK-NEXT:   JMP_1 %bb.4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.3:
  ; CHECK-NEXT:   liveins: $xmm0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $eax = MOVPDI2DIrr $xmm0
  ; CHECK-NEXT:   MOV32mr $rip, 1, $noreg, @U0, $noreg, killed renamable $eax :: (store (s32) into @U0)
  ; CHECK-NEXT:   RET 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.4:
  ; CHECK-NEXT:   liveins: $xmm1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $eax = MOVPDI2DIrr $xmm1
  ; CHECK-NEXT:   MOV32mr $rip, 1, $noreg, @U1, $noreg, killed renamable $eax :: (store (s32) into @U1)
  ; CHECK-NEXT:   RET 0





  bb.0:
    successors: %bb.2
    $eax = MOV32rm $rip, 1, $noreg, @D0, $noreg :: (dereferenceable load (s32) from @D0)
    MOV32mr %stack.0, 1, $noreg, 0, $noreg, killed renamable $eax :: (store (s32) into %stack.0)
    JMP_1 %bb.2

  bb.1:
    successors: %bb.2
    $eax = MOV32rm $rip, 1, $noreg, @D1, $noreg :: (dereferenceable load (s32) from @D1)
    MOV32mr %stack.1, 1, $noreg, 0, $noreg, killed renamable $eax :: (store (s32) into %stack.1)
    JMP_1 %bb.2

  bb.2:
    $eax = MOV32rm $rip, 1, $noreg, @Cond, $noreg :: (dereferenceable load (s32) from @Cond)
    TEST32rr $eax, $eax, implicit-def $eflags
    JCC_1 %bb.3, 2, implicit $eflags
    JMP_1 %bb.4

  bb.3:
    $eax = MOV32rm %stack.0, 1, $noreg, 0, $noreg :: (load (s32) from %stack.0)
    MOV32mr $rip, 1, $noreg, @U0, $noreg, killed renamable $eax :: (store (s32) into @U0)
    RET 0

  bb.4:
    $eax = MOV32rm %stack.1, 1, $noreg, 0, $noreg :: (load (s32) from %stack.1)
    MOV32mr $rip, 1, $noreg, @U1, $noreg, killed renamable $eax :: (store (s32) into @U1)
    RET 0

...
