; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc %s -o - -mtriple=x86_64-unknown-linux -enable-spill2reg -mattr=+sse4.1 | FileCheck %s
; RUN: llc %s -o - -mtriple=x86_64-unknown-linux -enable-spill2reg -mattr=+sse4.1 | FileCheck --check-prefix=AVX %s

; End-to-end check that Spill2Reg works with 32-bit registers.

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

@D0 = dso_local local_unnamed_addr global i32 0, align 4
@D1 = dso_local local_unnamed_addr global i32 0, align 4
@D2 = dso_local local_unnamed_addr global i32 0, align 4
@D3 = dso_local local_unnamed_addr global i32 0, align 4
@D4 = dso_local local_unnamed_addr global i32 0, align 4
@D5 = dso_local local_unnamed_addr global i32 0, align 4
@D6 = dso_local local_unnamed_addr global i32 0, align 4
@D7 = dso_local local_unnamed_addr global i32 0, align 4
@D8 = dso_local local_unnamed_addr global i32 0, align 4
@D9 = dso_local local_unnamed_addr global i32 0, align 4
@D10 = dso_local local_unnamed_addr global i32 0, align 4
@D11 = dso_local local_unnamed_addr global i32 0, align 4
@D12 = dso_local local_unnamed_addr global i32 0, align 4
@D13 = dso_local local_unnamed_addr global i32 0, align 4
@D14 = dso_local local_unnamed_addr global i32 0, align 4
@D15 = dso_local local_unnamed_addr global i32 0, align 4
@D16 = dso_local local_unnamed_addr global i32 0, align 4
@D17 = dso_local local_unnamed_addr global i32 0, align 4
@D18 = dso_local local_unnamed_addr global i32 0, align 4
@U0 = dso_local local_unnamed_addr global i32 0, align 4
@U1 = dso_local local_unnamed_addr global i32 0, align 4
@U2 = dso_local local_unnamed_addr global i32 0, align 4
@U3 = dso_local local_unnamed_addr global i32 0, align 4
@U4 = dso_local local_unnamed_addr global i32 0, align 4
@U5 = dso_local local_unnamed_addr global i32 0, align 4
@U6 = dso_local local_unnamed_addr global i32 0, align 4
@U7 = dso_local local_unnamed_addr global i32 0, align 4
@U8 = dso_local local_unnamed_addr global i32 0, align 4
@U9 = dso_local local_unnamed_addr global i32 0, align 4
@U10 = dso_local local_unnamed_addr global i32 0, align 4
@U11 = dso_local local_unnamed_addr global i32 0, align 4
@U12 = dso_local local_unnamed_addr global i32 0, align 4
@U13 = dso_local local_unnamed_addr global i32 0, align 4
@U14 = dso_local local_unnamed_addr global i32 0, align 4
@U15 = dso_local local_unnamed_addr global i32 0, align 4
@U16 = dso_local local_unnamed_addr global i32 0, align 4
@U17 = dso_local local_unnamed_addr global i32 0, align 4
@U18 = dso_local local_unnamed_addr global i32 0, align 4

; Function Attrs: mustprogress noinline nounwind uwtable
define dso_local void @_Z5spillv() local_unnamed_addr #0 {
; CHECK-LABEL: _Z5spillv:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    pushq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    pushq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    pushq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    pushq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 56
; CHECK-NEXT:    .cfi_offset %rbx, -56
; CHECK-NEXT:    .cfi_offset %r12, -48
; CHECK-NEXT:    .cfi_offset %r13, -40
; CHECK-NEXT:    .cfi_offset %r14, -32
; CHECK-NEXT:    .cfi_offset %r15, -24
; CHECK-NEXT:    .cfi_offset %rbp, -16
; CHECK-NEXT:    movl D0(%rip), %eax
; CHECK-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    movl D1(%rip), %ecx
; CHECK-NEXT:    movl D2(%rip), %edx
; CHECK-NEXT:    movl D3(%rip), %esi
; CHECK-NEXT:    movl D4(%rip), %edi
; CHECK-NEXT:    movl D5(%rip), %r8d
; CHECK-NEXT:    movl D6(%rip), %r9d
; CHECK-NEXT:    movl D7(%rip), %r10d
; CHECK-NEXT:    movl D8(%rip), %r11d
; CHECK-NEXT:    movl D9(%rip), %ebx
; CHECK-NEXT:    movl D10(%rip), %ebp
; CHECK-NEXT:    movl D11(%rip), %r14d
; CHECK-NEXT:    movl D12(%rip), %r15d
; CHECK-NEXT:    movl D13(%rip), %r12d
; CHECK-NEXT:    movl D14(%rip), %r13d
; CHECK-NEXT:    movl D15(%rip), %eax
; CHECK-NEXT:    movd %eax, %xmm0
; CHECK-NEXT:    movl D16(%rip), %eax
; CHECK-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    movl D17(%rip), %eax
; CHECK-NEXT:    movd %eax, %xmm1
; CHECK-NEXT:    movl D18(%rip), %eax
; CHECK-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; CHECK-NEXT:    movl %eax, U0(%rip)
; CHECK-NEXT:    movl %ecx, U1(%rip)
; CHECK-NEXT:    movl %edx, U2(%rip)
; CHECK-NEXT:    movl %esi, U3(%rip)
; CHECK-NEXT:    movl %edi, U4(%rip)
; CHECK-NEXT:    movl %r8d, U5(%rip)
; CHECK-NEXT:    movl %r9d, U6(%rip)
; CHECK-NEXT:    movl %r10d, U7(%rip)
; CHECK-NEXT:    movl %r11d, U8(%rip)
; CHECK-NEXT:    movl %ebx, U9(%rip)
; CHECK-NEXT:    movl %ebp, U10(%rip)
; CHECK-NEXT:    movl %r14d, U11(%rip)
; CHECK-NEXT:    movl %r15d, U12(%rip)
; CHECK-NEXT:    movl %r12d, U13(%rip)
; CHECK-NEXT:    movl %r13d, U14(%rip)
; CHECK-NEXT:    movd %xmm0, %eax
; CHECK-NEXT:    movl %eax, U15(%rip)
; CHECK-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; CHECK-NEXT:    movl %eax, U16(%rip)
; CHECK-NEXT:    movd %xmm1, %eax
; CHECK-NEXT:    movl %eax, U17(%rip)
; CHECK-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; CHECK-NEXT:    movl %eax, U18(%rip)
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .cfi_def_cfa_offset 48
; CHECK-NEXT:    popq %r12
; CHECK-NEXT:    .cfi_def_cfa_offset 40
; CHECK-NEXT:    popq %r13
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    popq %r14
; CHECK-NEXT:    .cfi_def_cfa_offset 24
; CHECK-NEXT:    popq %r15
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
;
; AVX-LABEL: _Z5spillv:
; AVX:       # %bb.0: # %entry
; AVX-NEXT:    pushq %rbp
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    pushq %r15
; AVX-NEXT:    .cfi_def_cfa_offset 24
; AVX-NEXT:    pushq %r14
; AVX-NEXT:    .cfi_def_cfa_offset 32
; AVX-NEXT:    pushq %r13
; AVX-NEXT:    .cfi_def_cfa_offset 40
; AVX-NEXT:    pushq %r12
; AVX-NEXT:    .cfi_def_cfa_offset 48
; AVX-NEXT:    pushq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 56
; AVX-NEXT:    .cfi_offset %rbx, -56
; AVX-NEXT:    .cfi_offset %r12, -48
; AVX-NEXT:    .cfi_offset %r13, -40
; AVX-NEXT:    .cfi_offset %r14, -32
; AVX-NEXT:    .cfi_offset %r15, -24
; AVX-NEXT:    .cfi_offset %rbp, -16
; AVX-NEXT:    movl D0(%rip), %eax
; AVX-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; AVX-NEXT:    movl D1(%rip), %ecx
; AVX-NEXT:    movl D2(%rip), %edx
; AVX-NEXT:    movl D3(%rip), %esi
; AVX-NEXT:    movl D4(%rip), %edi
; AVX-NEXT:    movl D5(%rip), %r8d
; AVX-NEXT:    movl D6(%rip), %r9d
; AVX-NEXT:    movl D7(%rip), %r10d
; AVX-NEXT:    movl D8(%rip), %r11d
; AVX-NEXT:    movl D9(%rip), %ebx
; AVX-NEXT:    movl D10(%rip), %ebp
; AVX-NEXT:    movl D11(%rip), %r14d
; AVX-NEXT:    movl D12(%rip), %r15d
; AVX-NEXT:    movl D13(%rip), %r12d
; AVX-NEXT:    movl D14(%rip), %r13d
; AVX-NEXT:    movl D15(%rip), %eax
; AVX-NEXT:    movd %eax, %xmm0
; AVX-NEXT:    movl D16(%rip), %eax
; AVX-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; AVX-NEXT:    movl D17(%rip), %eax
; AVX-NEXT:    movd %eax, %xmm1
; AVX-NEXT:    movl D18(%rip), %eax
; AVX-NEXT:    movl %eax, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; AVX-NEXT:    #APP
; AVX-NEXT:    #NO_APP
; AVX-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; AVX-NEXT:    movl %eax, U0(%rip)
; AVX-NEXT:    movl %ecx, U1(%rip)
; AVX-NEXT:    movl %edx, U2(%rip)
; AVX-NEXT:    movl %esi, U3(%rip)
; AVX-NEXT:    movl %edi, U4(%rip)
; AVX-NEXT:    movl %r8d, U5(%rip)
; AVX-NEXT:    movl %r9d, U6(%rip)
; AVX-NEXT:    movl %r10d, U7(%rip)
; AVX-NEXT:    movl %r11d, U8(%rip)
; AVX-NEXT:    movl %ebx, U9(%rip)
; AVX-NEXT:    movl %ebp, U10(%rip)
; AVX-NEXT:    movl %r14d, U11(%rip)
; AVX-NEXT:    movl %r15d, U12(%rip)
; AVX-NEXT:    movl %r12d, U13(%rip)
; AVX-NEXT:    movl %r13d, U14(%rip)
; AVX-NEXT:    movd %xmm0, %eax
; AVX-NEXT:    movl %eax, U15(%rip)
; AVX-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; AVX-NEXT:    movl %eax, U16(%rip)
; AVX-NEXT:    movd %xmm1, %eax
; AVX-NEXT:    movl %eax, U17(%rip)
; AVX-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %eax # 4-byte Reload
; AVX-NEXT:    movl %eax, U18(%rip)
; AVX-NEXT:    popq %rbx
; AVX-NEXT:    .cfi_def_cfa_offset 48
; AVX-NEXT:    popq %r12
; AVX-NEXT:    .cfi_def_cfa_offset 40
; AVX-NEXT:    popq %r13
; AVX-NEXT:    .cfi_def_cfa_offset 32
; AVX-NEXT:    popq %r14
; AVX-NEXT:    .cfi_def_cfa_offset 24
; AVX-NEXT:    popq %r15
; AVX-NEXT:    .cfi_def_cfa_offset 16
; AVX-NEXT:    popq %rbp
; AVX-NEXT:    .cfi_def_cfa_offset 8
; AVX-NEXT:    retq
entry:
  %0 = load i32, i32* @D0
  %1 = load i32, i32* @D1
  %2 = load i32, i32* @D2
  %3 = load i32, i32* @D3
  %4 = load i32, i32* @D4
  %5 = load i32, i32* @D5
  %6 = load i32, i32* @D6
  %7 = load i32, i32* @D7
  %8 = load i32, i32* @D8
  %9 = load i32, i32* @D9
  %10 = load i32, i32* @D10
  %11 = load i32, i32* @D11
  %12 = load i32, i32* @D12
  %13 = load i32, i32* @D13
  %14 = load i32, i32* @D14
  %15 = load i32, i32* @D15
  %16 = load i32, i32* @D16
  %17 = load i32, i32* @D17
  %18 = load i32, i32* @D18
  call void asm sideeffect "", "~{memory}"() #1
  store i32 %0, i32* @U0
  store i32 %1, i32* @U1
  store i32 %2, i32* @U2
  store i32 %3, i32* @U3
  store i32 %4, i32* @U4
  store i32 %5, i32* @U5
  store i32 %6, i32* @U6
  store i32 %7, i32* @U7
  store i32 %8, i32* @U8
  store i32 %9, i32* @U9
  store i32 %10, i32* @U10
  store i32 %11, i32* @U11
  store i32 %12, i32* @U12
  store i32 %13, i32* @U13
  store i32 %14, i32* @U14
  store i32 %15, i32* @U15
  store i32 %16, i32* @U16
  store i32 %17, i32* @U17
  store i32 %18, i32* @U18
  ret void
}

attributes #0 = { mustprogress noinline nounwind uwtable "frame-pointer"="none" "min-legal-vector-width"="0" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+cx8,+fxsr,+mmx,+sse,+sse2,+x87" "tune-cpu"="generic" }
attributes #1 = { nounwind }

