# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=x86_64-- -run-pass=greedy -verify-regalloc -stress-regalloc=2 -o - %s | FileCheck %s

# Test verifier error which happened after 8476a5d480304 during
# rematerialization.

---
name:            remat_regclass_verifier_error
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $rax, $rbx, $rcx, $rdi

    ; CHECK-LABEL: name: remat_regclass_verifier_error
    ; CHECK: liveins: $rax, $rbx, $rcx, $rdi
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:gr64 = COPY $rax
    ; CHECK-NEXT: dead [[COPY1:%[0-9]+]]:gr64 = COPY $rbx
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:gr64 = COPY $rcx
    ; CHECK-NEXT: MOV64mr %stack.0, 1, $noreg, 0, $noreg, [[COPY2]] :: (store (s64) into %stack.0)
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:gr64 = COPY $rdi
    ; CHECK-NEXT: undef [[MOV32r0_:%[0-9]+]].sub_32bit:gr64_with_sub_8bit = MOV32r0 implicit-def dead $eflags
    ; CHECK-NEXT: dead [[COPY3:%[0-9]+]]:gr64 = CMOV64rr [[COPY3]], [[MOV32r0_]], 10, implicit undef $eflags
    ; CHECK-NEXT: undef [[MOV32r0_1:%[0-9]+]].sub_32bit:gr64_with_sub_8bit = MOV32r0 implicit-def dead $eflags
    ; CHECK-NEXT: [[MOV64rm:%[0-9]+]]:gr64 = MOV64rm %stack.0, 1, $noreg, 0, $noreg :: (load (s64) from %stack.0)
    ; CHECK-NEXT: [[MOV64rm:%[0-9]+]]:gr64 = CMOV64rr [[MOV64rm]], [[MOV32r0_1]], 10, implicit undef $eflags
    ; CHECK-NEXT: dead [[COPY4:%[0-9]+]]:gr64 = COPY $rdi
    ; CHECK-NEXT: undef [[MOV32r0_2:%[0-9]+]].sub_32bit:gr64_with_sub_8bit = MOV32r0 implicit-def dead $eflags
    ; CHECK-NEXT: [[CMOV64rr:%[0-9]+]]:gr64 = CMOV64rr [[MOV64rm]], [[MOV32r0_2]], 10, implicit undef $eflags
    ; CHECK-NEXT: $rax = COPY [[CMOV64rr]]
    ; CHECK-NEXT: RET 0, $rax
    %0:gr64 = COPY $rax
    %1:gr64 = COPY $rbx
    undef %2.sub_32bit:gr64_with_sub_8bit = MOV32r0 implicit-def dead $eflags
    %0:gr64 = COPY $rcx
    %1:gr64 = COPY %0
    %0:gr64 = COPY $rdi
    %0:gr64 = CMOV64rr %0, %2, 10, implicit undef $eflags
    %1:gr64 = CMOV64rr %1, %2, 10, implicit undef $eflags
    %3:gr64 = COPY $rdi
    %3:gr64 = CMOV64rr %1, %2, 10, implicit undef $eflags
    $rax = COPY %3
    RET 0, killed $rax
...

