; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mattr=sse4.2 | FileCheck %s

; Some of these patterns can be matched as SSE min or max. Some of
; them can be matched provided that the operands are swapped.
; Some of them can't be matched at all and require a comparison
; and a conditional branch.

; The naming convention is {,x_,y_}{o,u}{gt,lt,ge,le}{,_inverse}
;  _x: use 0.0 instead of %y
;  _y: use -0.0 instead of %y
; _inverse : swap the arms of the select.

define double @ogt(double %x, double %y)  {
; CHECK-LABEL: ogt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ogt double %x, %y
  %d = select nsz i1 %c, double %x, double %y
  ret double %d
}

define double @olt(double %x, double %y)  {
; CHECK-LABEL: olt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp olt double %x, %y
  %d = select nsz i1 %c, double %x, double %y
  ret double %d
}

define double @ogt_inverse(double %x, double %y)  {
; CHECK-LABEL: ogt_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ogt double %x, %y
  %d = select nsz nnan i1 %c, double %y, double %x
  ret double %d
}

define double @olt_inverse(double %x, double %y)  {
; CHECK-LABEL: olt_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp olt double %x, %y
  %d = select nsz nnan i1 %c, double %y, double %x
  ret double %d
}

define double @oge(double %x, double %y)  {
;
; RELAX-LABEL: oge:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: oge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp oge double %x, %y
  %d = select nsz i1 %c, double %x, double %y
  ret double %d
}

define double @ole(double %x, double %y)  {
;
; RELAX-LABEL: ole:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ole:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ole double %x, %y
  %d = select nsz i1 %c, double %x, double %y
  ret double %d
}

define double @oge_inverse(double %x, double %y)  {
;
; RELAX-LABEL: oge_inverse:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: oge_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp oge double %x, %y
  %d = select nsz nnan i1 %c, double %y, double %x
  ret double %d
}

define double @ole_inverse(double %x, double %y)  {
;
; RELAX-LABEL: ole_inverse:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ole_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ole double %x, %y
  %d = select nsz nnan i1 %c, double %y, double %x
  ret double %d
}

define double @ogt_x(double %x)  {
; CHECK-LABEL: ogt_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ogt double %x, 0.000000e+00
  %d = select nsz i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @olt_x(double %x)  {
; CHECK-LABEL: olt_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp olt double %x, 0.000000e+00
  %d = select nsz i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @ogt_inverse_x(double %x)  {
; CHECK-LABEL: ogt_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ogt double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @olt_inverse_x(double %x)  {
; CHECK-LABEL: olt_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp olt double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @oge_x(double %x)  {
;
; RELAX-LABEL: oge_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    maxsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: oge_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp oge double %x, 0.000000e+00
  %d = select nsz i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @ole_x(double %x)  {
;
; RELAX-LABEL: ole_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    minsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ole_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ole double %x, 0.000000e+00
  %d = select nsz i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @oge_inverse_x(double %x)  {
;
; RELAX-LABEL: oge_inverse_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: oge_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp oge double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @ole_inverse_x(double %x)  {
;
; RELAX-LABEL: ole_inverse_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ole_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ole double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @ugt(double %x, double %y)  {
;
; RELAX-LABEL: ugt:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ugt:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ugt double %x, %y
  %d = select nsz nnan i1 %c, double %x, double %y
  ret double %d
}

define double @ult(double %x, double %y)  {
;
; RELAX-LABEL: ult:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ult:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ult double %x, %y
  %d = select nsz nnan i1 %c, double %x, double %y
  ret double %d
}

define double @ugt_inverse(double nofpclass(nan) %x, double nofpclass(nan) %y)  {
;
; RELAX-LABEL: ugt_inverse:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ugt_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ugt double %x, %y
  %d = select nsz nnan i1 %c, double %y, double %x
  ret double %d
}

define double @ult_inverse(double nofpclass(nan) %x, double nofpclass(nan) %y)  {
;
; RELAX-LABEL: ult_inverse:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ult_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ult double %x, %y
  %d = select nsz nnan i1 %c, double %y, double %x
  ret double %d
}

define double @uge(double %x, double %y)  {
;
; RELAX-LABEL: uge:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: uge:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp uge double %x, %y
  %d = select nsz nnan i1 %c, double %x, double %y
  ret double %d
}

define double @ule(double %x, double %y)  {
;
; RELAX-LABEL: ule:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ule:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ule double %x, %y
  %d = select nsz nnan i1 %c, double %x, double %y
  ret double %d
}

define double @uge_inverse(double %x, double %y)  {
;
; RELAX-LABEL: uge_inverse:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: uge_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp uge double %x, %y
  %d = select nsz i1 %c, double %y, double %x
  ret double %d
}

define double @ule_inverse(double %x, double %y)  {
;
; RELAX-LABEL: ule_inverse:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ule_inverse:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ule double %x, %y
  %d = select nsz i1 %c, double %y, double %x
  ret double %d
}

define double @ugt_x(double %x)  {
;
; RELAX-LABEL: ugt_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    maxsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ugt_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ugt double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @ult_x(double %x)  {
;
; RELAX-LABEL: ult_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    minsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ult_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ult double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @ugt_inverse_x(double %x)  {
;
; RELAX-LABEL: ugt_inverse_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ugt_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ugt double %x, 0.000000e+00
  %d = select nsz i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @ult_inverse_x(double %x)  {
;
; RELAX-LABEL: ult_inverse_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ult_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ult double %x, 0.000000e+00
  %d = select nsz i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @uge_x(double %x)  {
;
; RELAX-LABEL: uge_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    maxsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: uge_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp uge double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @ule_x(double %x)  {
;
; RELAX-LABEL: ule_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    minsd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ule_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ule double %x, 0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double 0.000000e+00
  ret double %d
}

define double @uge_inverse_x(double %x)  {
;
; RELAX-LABEL: uge_inverse_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: uge_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    minsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp uge double %x, 0.000000e+00
  %d = select nsz i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @ule_inverse_x(double %x)  {
;
; RELAX-LABEL: ule_inverse_x:
; RELAX:       # %bb.0:
; RELAX-NEXT:    xorpd %xmm1, %xmm1
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ule_inverse_x:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xorpd %xmm1, %xmm1
; CHECK-NEXT:    maxsd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ule double %x, 0.000000e+00
  %d = select nsz i1 %c, double 0.000000e+00, double %x
  ret double %d
}

define double @ogt_y(double %x)  {
; CHECK-LABEL: ogt_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ogt double %x, -0.000000e+00
  %d = select nsz i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @olt_y(double %x)  {
; CHECK-LABEL: olt_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp olt double %x, -0.000000e+00
  %d = select nsz i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @ogt_inverse_y(double %x)  {
; CHECK-LABEL: ogt_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ogt double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double -0.000000e+00, double %x
  ret double %d
}

define double @olt_inverse_y(double %x)  {
; CHECK-LABEL: olt_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp olt double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double -0.000000e+00, double %x
  ret double %d
}

define double @oge_y(double %x)  {
;
; RELAX-LABEL: oge_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: oge_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp oge double %x, -0.000000e+00
  %d = select nsz i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @ole_y(double %x)  {
;
; RELAX-LABEL: ole_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ole_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ole double %x, -0.000000e+00
  %d = select nsz i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @oge_inverse_y(double %x)  {
;
; RELAX-LABEL: oge_inverse_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [-0.0E+0,0.0E+0]
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: oge_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp oge double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double -0.000000e+00, double %x
  ret double %d
}

define double @ole_inverse_y(double %x)  {
;
; RELAX-LABEL: ole_inverse_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [-0.0E+0,0.0E+0]
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ole_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ole double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double -0.000000e+00, double %x
  ret double %d
}

define double @ugt_y(double %x)  {
;
; RELAX-LABEL: ugt_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ugt_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ugt double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @ult_y(double %x)  {
;
; RELAX-LABEL: ult_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ult_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ult double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @ugt_inverse_y(double %x)  {
;
; RELAX-LABEL: ugt_inverse_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [-0.0E+0,0.0E+0]
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ugt_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ugt double %x, -0.000000e+00
  %d = select nsz i1 %c, double -0.000000e+00, double %x
  ret double %d
}

define double @ult_inverse_y(double %x)  {
;
; RELAX-LABEL: ult_inverse_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [-0.0E+0,0.0E+0]
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ult_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ult double %x, -0.000000e+00
  %d = select nsz i1 %c, double -0.000000e+00, double %x
  ret double %d
}

define double @uge_y(double %x)  {
;
; RELAX-LABEL: uge_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: uge_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp uge double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @ule_y(double %x)  {
;
; RELAX-LABEL: ule_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ule_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ule double %x, -0.000000e+00
  %d = select nsz nnan i1 %c, double %x, double -0.000000e+00
  ret double %d
}

define double @uge_inverse_y(double %x)  {
;
; RELAX-LABEL: uge_inverse_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [-0.0E+0,0.0E+0]
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: uge_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp uge double %x, -0.000000e+00
  %d = select nsz i1 %c, double -0.000000e+00, double %x
  ret double %d
}

define double @ule_inverse_y(double %x)  {
;
; RELAX-LABEL: ule_inverse_y:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [-0.0E+0,0.0E+0]
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: ule_inverse_y:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %c = fcmp ule double %x, -0.000000e+00
  %d = select nsz i1 %c, double -0.000000e+00, double %x
  ret double %d
}

; Test a few more misc. cases.

define double @clampTo3k_a(double %x)  {
; CHECK-LABEL: clampTo3k_a:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp ogt double %x, 3.000000e+03
  %y = select nsz nnan i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define double @clampTo3k_b(double %x)  {
;
; RELAX-LABEL: clampTo3k_b:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [3.0E+3,0.0E+0]
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: clampTo3k_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp uge double %x, 3.000000e+03
  %y = select nsz i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define double @clampTo3k_c(double %x)  {
; CHECK-LABEL: clampTo3k_c:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp olt double %x, 3.000000e+03
  %y = select nsz nnan i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define double @clampTo3k_d(double %x)  {
;
; RELAX-LABEL: clampTo3k_d:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [3.0E+3,0.0E+0]
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: clampTo3k_d:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp ule double %x, 3.000000e+03
  %y = select nsz i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define double @clampTo3k_e(double %x)  {
; CHECK-LABEL: clampTo3k_e:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp olt double %x, 3.000000e+03
  %y = select nsz nnan i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define double @clampTo3k_f(double %x)  {
;
; RELAX-LABEL: clampTo3k_f:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [3.0E+3,0.0E+0]
; RELAX-NEXT:    maxsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: clampTo3k_f:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp ule double %x, 3.000000e+03
  %y = select nsz i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define double @clampTo3k_g(double %x)  {
; CHECK-LABEL: clampTo3k_g:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp ogt double %x, 3.000000e+03
  %y = select nsz nnan i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define double @clampTo3k_h(double %x)  {
;
; RELAX-LABEL: clampTo3k_h:
; RELAX:       # %bb.0:
; RELAX-NEXT:    movsd {{.*#+}} xmm1 = [3.0E+3,0.0E+0]
; RELAX-NEXT:    minsd %xmm0, %xmm1
; RELAX-NEXT:    movapd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: clampTo3k_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minsd {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %t0 = fcmp uge double %x, 3.000000e+03
  %y = select nsz i1 %t0, double 3.000000e+03, double %x
  ret double %y
}

define <2 x double> @test_maxpd(<2 x double> %x, <2 x double> %y)  {
;
; RELAX-LABEL: test_maxpd:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxpd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_maxpd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxpd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %max_is_x = fcmp oge <2 x double> %x, %y
  %max = select nsz <2 x i1> %max_is_x, <2 x double> %x, <2 x double> %y
  ret <2 x double> %max
}

define <2 x double> @test_minpd(<2 x double> %x, <2 x double> %y)  {
;
; RELAX-LABEL: test_minpd:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minpd %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_minpd:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minpd %xmm1, %xmm0
; CHECK-NEXT:    retq
  %min_is_x = fcmp ole <2 x double> %x, %y
  %min = select nsz <2 x i1> %min_is_x, <2 x double> %x, <2 x double> %y
  ret <2 x double> %min
}

define <4 x float> @test_maxps(<4 x float> %x, <4 x float> %y)  {
;
; RELAX-LABEL: test_maxps:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxps %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_maxps:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxps %xmm1, %xmm0
; CHECK-NEXT:    retq
  %max_is_x = fcmp oge <4 x float> %x, %y
  %max = select nsz <4 x i1> %max_is_x, <4 x float> %x, <4 x float> %y
  ret <4 x float> %max
}

define <4 x float> @test_minps(<4 x float> %x, <4 x float> %y)  {
;
; RELAX-LABEL: test_minps:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minps %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_minps:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minps %xmm1, %xmm0
; CHECK-NEXT:    retq
  %min_is_x = fcmp ole <4 x float> %x, %y
  %min = select nsz <4 x i1> %min_is_x, <4 x float> %x, <4 x float> %y
  ret <4 x float> %min
}

define <2 x float> @test_maxps_illegal_v2f32(<2 x float> %x, <2 x float> %y)  {
;
; RELAX-LABEL: test_maxps_illegal_v2f32:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxps %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_maxps_illegal_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxps %xmm1, %xmm0
; CHECK-NEXT:    retq
  %max_is_x = fcmp oge <2 x float> %x, %y
  %max = select nsz <2 x i1> %max_is_x, <2 x float> %x, <2 x float> %y
  ret <2 x float> %max
}

define <2 x float> @test_minps_illegal_v2f32(<2 x float> %x, <2 x float> %y)  {
;
; RELAX-LABEL: test_minps_illegal_v2f32:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minps %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_minps_illegal_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minps %xmm1, %xmm0
; CHECK-NEXT:    retq
  %min_is_x = fcmp ole <2 x float> %x, %y
  %min = select nsz <2 x i1> %min_is_x, <2 x float> %x, <2 x float> %y
  ret <2 x float> %min
}

define <3 x float> @test_maxps_illegal_v3f32(<3 x float> %x, <3 x float> %y)  {
;
; RELAX-LABEL: test_maxps_illegal_v3f32:
; RELAX:       # %bb.0:
; RELAX-NEXT:    maxps %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_maxps_illegal_v3f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    maxps %xmm1, %xmm0
; CHECK-NEXT:    retq
  %max_is_x = fcmp oge <3 x float> %x, %y
  %max = select nsz <3 x i1> %max_is_x, <3 x float> %x, <3 x float> %y
  ret <3 x float> %max
}

define <3 x float> @test_minps_illegal_v3f32(<3 x float> %x, <3 x float> %y)  {
;
; RELAX-LABEL: test_minps_illegal_v3f32:
; RELAX:       # %bb.0:
; RELAX-NEXT:    minps %xmm1, %xmm0
; RELAX-NEXT:    retq
; CHECK-LABEL: test_minps_illegal_v3f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    minps %xmm1, %xmm0
; CHECK-NEXT:    retq
  %min_is_x = fcmp ole <3 x float> %x, %y
  %min = select nsz <3 x i1> %min_is_x, <3 x float> %x, <3 x float> %y
  ret <3 x float> %min
}

; OSS-Fuzz #13838
; https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13838
define float @ossfuzz13838(float %x) {
; ALL-NEXT:    retq
; CHECK-LABEL: ossfuzz13838:
; CHECK:       # %bb.0: # %bb
; CHECK-NEXT:    movss {{.*#+}} xmm0 = [2.55E+2,0.0E+0,0.0E+0,0.0E+0]
; CHECK-NEXT:    retq
bb:
  %cmp2 = fcmp fast olt float %x, 2.550000e+02
  %B1 = urem i1 %cmp2, %cmp2
  %min = select nsz i1 %B1, float %x, float 2.550000e+02
  %B = frem float %min, 0x47EFFFFFE0000000
  %cmp1 = fcmp fast olt float %B, 1.000000e+00
  %r = select nsz i1 %cmp1, float 1.000000e+00, float %min
  ret float %r
}
