; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-pc-linux-gnu < %s | FileCheck %s

; Test that the StackProtector pass uses llvm.ssp.protected to enable SSP even
; for allocas that would not normally be protected by IR-level type analysis.
; An integer array [4 x i32] is NOT protected by -fstack-protector on Linux
; (not a char array), but the intrinsic forces protection.

declare void @llvm.ssp.protected(ptr nocapture) nofree nosync nounwind memory(none)

; An int array with llvm.ssp.protected: SSP should be applied.
; On Linux x86_64 the guard is loaded from %fs:40 (TLS).
define void @test_intrinsic_triggers_ssp() ssp {
; CHECK-LABEL: test_intrinsic_triggers_ssp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $24, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    movq %fs:40, %rax
; CHECK-NEXT:    movq %rax, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    movq %fs:40, %rax
; CHECK-NEXT:    cmpq {{[0-9]+}}(%rsp), %rax
; CHECK-NEXT:    jne .LBB0_2
; CHECK-NEXT:  # %bb.1: # %SP_return
; CHECK-NEXT:    addq $24, %rsp
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
; CHECK-NEXT:  .LBB0_2: # %CallStackCheckFailBlk
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    callq __stack_chk_fail@PLT
  %buf = alloca [4 x i32], align 4
  call void @llvm.ssp.protected(ptr %buf)
  ret void
}

; An int array without the intrinsic: no SSP (IR-level fallback won't trigger).
define void @test_no_intrinsic_no_ssp() ssp {
; CHECK-LABEL: test_no_intrinsic_no_ssp:
; CHECK:       # %bb.0:
; CHECK-NEXT:    retq
  %buf = alloca [4 x i32], align 4
  ret void
}
