; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s | FileCheck %s

target triple = "x86_64-unknown-linux-gnu"

define void @quux() gc "statepoint-example" {
; CHECK-LABEL: quux:
; CHECK:       # %bb.0: # %bb1
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $4, %esi
; CHECK-NEXT:    callq wombat@PLT
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    popq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
bb1:
  %tmp = call token (i64, i32, i8 addrspace(1)* (i8 addrspace(1)*, i32)*, i32, i32, ...) @llvm.experimental.gc.statepoint.p0f_p1i8p1i8i32f(i64 2882400000, i32 0, i8 addrspace(1)* (i8 addrspace(1)*, i32)* nonnull elementtype(i8 addrspace(1)* (i8 addrspace(1)*, i32)) @wombat, i32 2, i32 0, i8 addrspace(1)* undef, i32 4, i32 0, i32 0) [ "gc-live"() ]
  %tmp2 = tail call i8 addrspace(1)* @llvm.experimental.gc.result.p1i8(token %tmp)
  br label %bb2

bb2:
  %tmp5 = tail call i8 addrspace(1)* @llvm.experimental.gc.result.p1i8(token %tmp)
  ret void
}

declare i8 addrspace(1)* @wombat(i8 addrspace(1)*, i32)

; Function Attrs: nounwind readnone
declare i8 addrspace(1)* @llvm.experimental.gc.result.p1i8(token) #0
declare token @llvm.experimental.gc.statepoint.p0f_p1i8p1i8i32f(i64, i32, i8 addrspace(1)* (i8 addrspace(1)*, i32)*, i32, i32, ...)
attributes #0 = { nounwind readnone }
