; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-pc-windows-gnu -mcpu=tigerlake | FileCheck %s

define <32 x i1> @v32i1_bitcast_crash(<4 x i8> %0) {
; CHECK-LABEL: v32i1_bitcast_crash:
; CHECK:       # %bb.0:
; CHECK-NEXT:    subq $24, %rsp
; CHECK-NEXT:    .seh_stackalloc 24
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    vmovaps (%rcx), %xmm0
; CHECK-NEXT:    vmovaps %xmm0, (%rsp)
; CHECK-NEXT:    kmovd (%rsp), %k0
; CHECK-NEXT:    vpmovm2b %k0, %ymm0
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    addq $24, %rsp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
  %2 = bitcast <4 x i8> %0 to <32 x i1>
  ret <32 x i1> %2
}
