; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -combiner-topological-sorting < %s -mtriple=i686-unknown-unknown -mattr=+sse2 -verify-machineinstrs | FileCheck %s --check-prefixes=X86
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-unknown-unknown -mattr=+sse2 -verify-machineinstrs | FileCheck %s --check-prefixes=X64

define i32 @foo() strictfp {
; X86-LABEL: foo:
; X86:       # %bb.0: # %entry
; X86-NEXT:    movl $1, %eax
; X86-NEXT:    #APP
; X86-NEXT:    #NO_APP
; X86-NEXT:    movl $-1, %eax
; X86-NEXT:    retl
;
; X64-LABEL: foo:
; X64:       # %bb.0: # %entry
; X64-NEXT:    movl $1, %eax
; X64-NEXT:    #APP
; X64-NEXT:    #NO_APP
; X64-NEXT:    movl $-1, %eax
; X64-NEXT:    retq
entry:
  tail call void asm sideeffect "", "r"(i32 1) #1, !srcloc !0
  ret i32 -1
}


!0 = !{i64 87}
