; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -O2 | FileCheck %s

declare void @llvm.assume(i1)

define i64 @and_assume_nonnegative_huge_mask(i64 %x) {
; CHECK-LABEL: and_assume_nonnegative_huge_mask:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    andq $-4, %rax
; CHECK-NEXT:    retq
  %nn = icmp sge i64 %x, 0
  call void @llvm.assume(i1 %nn)
  %r = and i64 %x, 9223372036854775804
  ret i64 %r
}

define i64 @and_huge_mask_without_known_zero(i64 %x) {
; CHECK-LABEL: and_huge_mask_without_known_zero:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movabsq $9223372036854775804, %rax
; CHECK-NEXT:    andq %rdi, %rax
; CHECK-NEXT:    retq
  %r = and i64 %x, 9223372036854775804
  ret i64 %r
}
