; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=x86_64 < %s | FileCheck %s

; When a narrow udiv-by-constant (i8, i16) is lowered via BuildUDIV, the
; Hacker's Delight algorithm may need an expensive add-and-shift fixup.
; A wider legal type (e.g. i32 for i8) has enough headroom for a simple
; Magic = ceil(2^Shift / C) that needs no fixup at all.

; --- i8 cases ---

define i8 @udiv_i8_by7(i8 %x) nounwind {
; CHECK-LABEL: udiv_i8_by7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    imull $293, %eax, %eax # imm = 0x125
; CHECK-NEXT:    shrl $11, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 7
  ret i8 %d
}

define i8 @udiv_i8_by5(i8 %x) nounwind {
; CHECK-LABEL: udiv_i8_by5:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    imull $205, %eax, %eax
; CHECK-NEXT:    shrl $10, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 5
  ret i8 %d
}

define i8 @udiv_i8_by3(i8 %x) nounwind {
; CHECK-LABEL: udiv_i8_by3:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    imull $171, %eax, %eax
; CHECK-NEXT:    shrl $9, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 3
  ret i8 %d
}

; Even divisor - stock uses pre-shift + magic; simple magic avoids pre-shift.
define i8 @udiv_i8_by78(i8 %x) nounwind {
; CHECK-LABEL: udiv_i8_by78:
; CHECK:       # %bb.0:
; CHECK-NEXT:    shrb %dil
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    imull $211, %eax, %eax
; CHECK-NEXT:    shrl $13, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 78
  ret i8 %d
}

define i8 @udiv_i8_by116(i8 %x) nounwind {
; CHECK-LABEL: udiv_i8_by116:
; CHECK:       # %bb.0:
; CHECK-NEXT:    shrb $2, %dil
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    imull $71, %eax, %eax
; CHECK-NEXT:    shrl $11, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 116
  ret i8 %d
}

; Power of 2 - should NOT fire (already lowered to shift).
define i8 @udiv_i8_by4(i8 %x) nounwind {
; CHECK-LABEL: udiv_i8_by4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    shrb $2, %al
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 4
  ret i8 %d
}

; Division by 1 - should NOT fire.
define i8 @udiv_i8_by1(i8 %x) nounwind {
; CHECK-LABEL: udiv_i8_by1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 1
  ret i8 %d
}

; Bare i8 udiv feeding another i8 op (no zext).
define i8 @udiv_i8_then_add(i8 %x, i8 %y) nounwind {
; CHECK-LABEL: udiv_i8_then_add:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzbl %dil, %eax
; CHECK-NEXT:    imull $293, %eax, %eax # imm = 0x125
; CHECK-NEXT:    shrl $11, %eax
; CHECK-NEXT:    addb %sil, %al
; CHECK-NEXT:    # kill: def $al killed $al killed $eax
; CHECK-NEXT:    retq
  %d = udiv i8 %x, 7
  %r = add i8 %d, %y
  ret i8 %r
}

; --- i16 cases ---

define i16 @udiv_i16_by7(i16 %x) nounwind {
; CHECK-LABEL: udiv_i16_by7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl %di, %eax
; CHECK-NEXT:    imulq $74899, %rax, %rax # imm = 0x12493
; CHECK-NEXT:    shrq $19, %rax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $rax
; CHECK-NEXT:    retq
  %d = udiv i16 %x, 7
  ret i16 %d
}

define i16 @udiv_i16_by100(i16 %x) nounwind {
; CHECK-LABEL: udiv_i16_by100:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl %di, %eax
; CHECK-NEXT:    shrl $2, %eax
; CHECK-NEXT:    imull $5243, %eax, %eax # imm = 0x147B
; CHECK-NEXT:    shrl $17, %eax
; CHECK-NEXT:    # kill: def $ax killed $ax killed $eax
; CHECK-NEXT:    retq
  %d = udiv i16 %x, 100
  ret i16 %d
}

; Vector narrow udiv - should NOT use the scalar narrow-magic widening path.
define <16 x i8> @udiv_v16i8_by7(<16 x i8> %x) nounwind {
; CHECK-LABEL: udiv_v16i8_by7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    pxor %xmm1, %xmm1
; CHECK-NEXT:    movdqa %xmm0, %xmm2
; CHECK-NEXT:    punpckhbw {{.*#+}} xmm2 = xmm2[8],xmm1[8],xmm2[9],xmm1[9],xmm2[10],xmm1[10],xmm2[11],xmm1[11],xmm2[12],xmm1[12],xmm2[13],xmm1[13],xmm2[14],xmm1[14],xmm2[15],xmm1[15]
; CHECK-NEXT:    movdqa {{.*#+}} xmm3 = [37,0,37,0,37,0,37,0,37,0,37,0,37,0,37,0]
; CHECK-NEXT:    pmullw %xmm3, %xmm2
; CHECK-NEXT:    psrlw $8, %xmm2
; CHECK-NEXT:    movdqa %xmm0, %xmm4
; CHECK-NEXT:    punpcklbw {{.*#+}} xmm4 = xmm4[0],xmm1[0],xmm4[1],xmm1[1],xmm4[2],xmm1[2],xmm4[3],xmm1[3],xmm4[4],xmm1[4],xmm4[5],xmm1[5],xmm4[6],xmm1[6],xmm4[7],xmm1[7]
; CHECK-NEXT:    pmullw %xmm3, %xmm4
; CHECK-NEXT:    psrlw $8, %xmm4
; CHECK-NEXT:    packuswb %xmm2, %xmm4
; CHECK-NEXT:    psubb %xmm4, %xmm0
; CHECK-NEXT:    psrlw $1, %xmm0
; CHECK-NEXT:    pand {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    paddb %xmm4, %xmm0
; CHECK-NEXT:    psrlw $2, %xmm0
; CHECK-NEXT:    pand {{\.?LCPI[0-9]+_[0-9]+}}(%rip), %xmm0
; CHECK-NEXT:    retq
  %d = udiv <16 x i8> %x, splat (i8 7)
  ret <16 x i8> %d
}

define <8 x i16> @udiv_v8i16_by7(<8 x i16> %x) nounwind {
; CHECK-LABEL: udiv_v8i16_by7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movdqa {{.*#+}} xmm1 = [9363,9363,9363,9363,9363,9363,9363,9363]
; CHECK-NEXT:    pmulhuw %xmm0, %xmm1
; CHECK-NEXT:    psubw %xmm1, %xmm0
; CHECK-NEXT:    psrlw $1, %xmm0
; CHECK-NEXT:    paddw %xmm1, %xmm0
; CHECK-NEXT:    psrlw $2, %xmm0
; CHECK-NEXT:    retq
  %d = udiv <8 x i16> %x, splat (i16 7)
  ret <8 x i16> %d
}

; zext(udiv i16) - should also improve.
define i32 @zext_udiv_i16_by7(i16 %x) nounwind {
; CHECK-LABEL: zext_udiv_i16_by7:
; CHECK:       # %bb.0:
; CHECK-NEXT:    movzwl %di, %eax
; CHECK-NEXT:    imulq $74899, %rax, %rax # imm = 0x12493
; CHECK-NEXT:    shrq $19, %rax
; CHECK-NEXT:    # kill: def $eax killed $eax killed $rax
; CHECK-NEXT:    retq
  %d = udiv i16 %x, 7
  %z = zext i16 %d to i32
  ret i32 %z
}
