; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -O2 | FileCheck %s

define i128 @div_by_7(i128 %x) {
; CHECK-LABEL: div_by_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movabsq $9223372036854775807, %rax # imm = 0x7FFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    shldq $1, %rdi, %r8
; CHECK-NEXT:    addq %rdi, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rax, %r9
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $62, %rcx
; CHECK-NEXT:    cmpq %rdx, %r9
; CHECK-NEXT:    adcq %r8, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $5270498306774157605, %rdx # imm = 0x4924924924924925
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    shrq %rdx
; CHECK-NEXT:    leaq (,%rdx,8), %rax
; CHECK-NEXT:    subq %rax, %rdx
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    subq %rdx, %rdi
; CHECK-NEXT:    sbbq $0, %rsi
; CHECK-NEXT:    movabsq $-5270498306774157605, %rcx # imm = 0xB6DB6DB6DB6DB6DB
; CHECK-NEXT:    imulq %rdi, %rcx
; CHECK-NEXT:    movabsq $7905747460161236407, %r8 # imm = 0x6DB6DB6DB6DB6DB7
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    mulq %r8
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    imulq %rsi, %r8
; CHECK-NEXT:    addq %r8, %rdx
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 7
  ret i128 %div
}

define i128 @div_by_9(i128 %x) {
; CHECK-LABEL: div_by_9:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movabsq $1152921504606846975, %rax # imm = 0xFFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    shldq $4, %rdi, %r8
; CHECK-NEXT:    addq %rdi, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rax, %r9
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $56, %rcx
; CHECK-NEXT:    cmpq %rdx, %r9
; CHECK-NEXT:    adcq %r8, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $2049638230412172402, %rdx # imm = 0x1C71C71C71C71C72
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    leaq (%rdx,%rdx,8), %rax
; CHECK-NEXT:    subq %rax, %rcx
; CHECK-NEXT:    subq %rcx, %rdi
; CHECK-NEXT:    sbbq $0, %rsi
; CHECK-NEXT:    movabsq $4099276460824344803, %rcx # imm = 0x38E38E38E38E38E3
; CHECK-NEXT:    imulq %rdi, %rcx
; CHECK-NEXT:    movabsq $-8198552921648689607, %r8 # imm = 0x8E38E38E38E38E39
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    mulq %r8
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    imulq %rsi, %r8
; CHECK-NEXT:    addq %r8, %rdx
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 9
  ret i128 %div
}

define i128 @div_by_25(i128 %x) {
; CHECK-LABEL: div_by_25:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movabsq $1152921504606846975, %rax # imm = 0xFFFFFFFFFFFFFFF
; CHECK-NEXT:    movq %rdi, %rdx
; CHECK-NEXT:    andq %rax, %rdx
; CHECK-NEXT:    movq %rsi, %r8
; CHECK-NEXT:    shldq $4, %rdi, %r8
; CHECK-NEXT:    addq %rdi, %r8
; CHECK-NEXT:    movq %r8, %r9
; CHECK-NEXT:    andq %rax, %r9
; CHECK-NEXT:    movq %rsi, %rcx
; CHECK-NEXT:    shrq $56, %rcx
; CHECK-NEXT:    cmpq %rdx, %r9
; CHECK-NEXT:    adcq %r8, %rcx
; CHECK-NEXT:    andq %rax, %rcx
; CHECK-NEXT:    movabsq $737869762948382065, %rdx # imm = 0xA3D70A3D70A3D71
; CHECK-NEXT:    movq %rcx, %rax
; CHECK-NEXT:    mulq %rdx
; CHECK-NEXT:    leaq (%rdx,%rdx,4), %rax
; CHECK-NEXT:    leaq (%rax,%rax,4), %rax
; CHECK-NEXT:    subq %rax, %rcx
; CHECK-NEXT:    subq %rcx, %rdi
; CHECK-NEXT:    sbbq $0, %rsi
; CHECK-NEXT:    movabsq $2951479051793528258, %rcx # imm = 0x28F5C28F5C28F5C2
; CHECK-NEXT:    imulq %rdi, %rcx
; CHECK-NEXT:    movabsq $-8116567392432202711, %r8 # imm = 0x8F5C28F5C28F5C29
; CHECK-NEXT:    movq %rdi, %rax
; CHECK-NEXT:    mulq %r8
; CHECK-NEXT:    addq %rcx, %rdx
; CHECK-NEXT:    imulq %rsi, %r8
; CHECK-NEXT:    addq %r8, %rdx
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 25
  ret i128 %div
}

define i128 @div_by_14(i128 %x) {
; CHECK-LABEL: div_by_14:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $14, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    callq __udivti3@PLT
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 14
  ret i128 %div
}

define i128 @div_by_22(i128 %x) {
; CHECK-LABEL: div_by_22:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    pushq %rax
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    movl $22, %edx
; CHECK-NEXT:    xorl %ecx, %ecx
; CHECK-NEXT:    callq __udivti3@PLT
; CHECK-NEXT:    popq %rcx
; CHECK-NEXT:    .cfi_def_cfa_offset 8
; CHECK-NEXT:    retq
entry:
  %div = udiv i128 %x, 22
  ret i128 %div
}
