; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx2 | FileCheck %s --check-prefix=AVX2
; RUN: llc < %s -mtriple=x86_64-unknown-unknown -mattr=+avx2,+fma | FileCheck %s --check-prefix=FMA

declare float @llvm.vector.reduce.fdot.v4f32(float, <4 x float>, <4 x float>)
declare double @llvm.vector.reduce.fdot.v4f64(double, <4 x double>, <4 x double>)

; Default: sequential vmulss + vaddss chain.
define float @fdot_f32(float %acc, <4 x float> %a, <4 x float> %b) {
; AVX2-LABEL: fdot_f32:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm3 = xmm1[1,1,3,3]
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm2[1,1,3,3]
; AVX2-NEXT:    vmulss %xmm4, %xmm3, %xmm3
; AVX2-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufpd {{.*#+}} xmm3 = xmm1[1,0]
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; AVX2-NEXT:    vmulss %xmm4, %xmm3, %xmm3
; AVX2-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufps {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX2-NEXT:    vshufps {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX2-NEXT:    vmulss %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddss %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f32:
; FMA:       # %bb.0:
; FMA-NEXT:    vmulss %xmm2, %xmm1, %xmm3
; FMA-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; FMA-NEXT:    vmovshdup {{.*#+}} xmm3 = xmm1[1,1,3,3]
; FMA-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm2[1,1,3,3]
; FMA-NEXT:    vmulss %xmm4, %xmm3, %xmm3
; FMA-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; FMA-NEXT:    vshufpd {{.*#+}} xmm3 = xmm1[1,0]
; FMA-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; FMA-NEXT:    vmulss %xmm4, %xmm3, %xmm3
; FMA-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; FMA-NEXT:    vshufps {{.*#+}} xmm1 = xmm1[3,3,3,3]
; FMA-NEXT:    vshufps {{.*#+}} xmm2 = xmm2[3,3,3,3]
; FMA-NEXT:    vmulss %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vaddss %xmm1, %xmm0, %xmm0
; FMA-NEXT:    retq
  %res = call float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With reassoc: pairwise vmulss + vaddss tree (unordered).
define float @fdot_f32_reassoc(float %acc, <4 x float> %a, <4 x float> %b) {
; AVX2-LABEL: fdot_f32_reassoc:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulps %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; AVX2-NEXT:    vaddps %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm1[1,1,3,3]
; AVX2-NEXT:    vaddss %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddss %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f32_reassoc:
; FMA:       # %bb.0:
; FMA-NEXT:    vmulps %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; FMA-NEXT:    vaddps %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm1[1,1,3,3]
; FMA-NEXT:    vaddss %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vaddss %xmm1, %xmm0, %xmm0
; FMA-NEXT:    retq
  %res = call reassoc float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With contract: DAGCombiner fuses to vfmadd chain when FMA hardware is available.
define float @fdot_f32_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; AVX2-LABEL: fdot_f32_contract:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulss %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm3 = xmm1[1,1,3,3]
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm2[1,1,3,3]
; AVX2-NEXT:    vmulss %xmm4, %xmm3, %xmm3
; AVX2-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufpd {{.*#+}} xmm3 = xmm1[1,0]
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; AVX2-NEXT:    vmulss %xmm4, %xmm3, %xmm3
; AVX2-NEXT:    vaddss %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufps {{.*#+}} xmm1 = xmm1[3,3,3,3]
; AVX2-NEXT:    vshufps {{.*#+}} xmm2 = xmm2[3,3,3,3]
; AVX2-NEXT:    vmulss %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddss %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f32_contract:
; FMA:       # %bb.0:
; FMA-NEXT:    vfmadd231ss {{.*#+}} xmm0 = (xmm1 * xmm2) + xmm0
; FMA-NEXT:    vmovshdup {{.*#+}} xmm3 = xmm1[1,1,3,3]
; FMA-NEXT:    vmovshdup {{.*#+}} xmm4 = xmm2[1,1,3,3]
; FMA-NEXT:    vfmadd213ss {{.*#+}} xmm4 = (xmm3 * xmm4) + xmm0
; FMA-NEXT:    vshufpd {{.*#+}} xmm0 = xmm1[1,0]
; FMA-NEXT:    vshufpd {{.*#+}} xmm3 = xmm2[1,0]
; FMA-NEXT:    vfmadd213ss {{.*#+}} xmm3 = (xmm0 * xmm3) + xmm4
; FMA-NEXT:    vshufps {{.*#+}} xmm1 = xmm1[3,3,3,3]
; FMA-NEXT:    vshufps {{.*#+}} xmm0 = xmm2[3,3,3,3]
; FMA-NEXT:    vfmadd213ss {{.*#+}} xmm0 = (xmm1 * xmm0) + xmm3
; FMA-NEXT:    retq
  %res = call contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With reassoc+contract: reassoc takes priority (tree reduction); contract flag
; preserved, backend may fuse muls+adds into FMAs within the tree.
define float @fdot_f32_reassoc_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; AVX2-LABEL: fdot_f32_reassoc_contract:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulps %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; AVX2-NEXT:    vaddps %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm1[1,1,3,3]
; AVX2-NEXT:    vaddss %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddss %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f32_reassoc_contract:
; FMA:       # %bb.0:
; FMA-NEXT:    vmulps %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; FMA-NEXT:    vaddps %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vmovshdup {{.*#+}} xmm2 = xmm1[1,1,3,3]
; FMA-NEXT:    vaddss %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vaddss %xmm1, %xmm0, %xmm0
; FMA-NEXT:    retq
  %res = call reassoc contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; f64 variants: same expansion patterns, but for double elements.
define double @fdot_f64(double %acc, <4 x double> %a, <4 x double> %b) {
; AVX2-LABEL: fdot_f64:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulsd %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufpd {{.*#+}} xmm3 = xmm1[1,0]
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; AVX2-NEXT:    vmulsd %xmm4, %xmm3, %xmm3
; AVX2-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vextractf128 $1, %ymm1, %xmm1
; AVX2-NEXT:    vextractf128 $1, %ymm2, %xmm2
; AVX2-NEXT:    vmulsd %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufpd {{.*#+}} xmm1 = xmm1[1,0]
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm2[1,0]
; AVX2-NEXT:    vmulsd %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddsd %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f64:
; FMA:       # %bb.0:
; FMA-NEXT:    vmulsd %xmm2, %xmm1, %xmm3
; FMA-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; FMA-NEXT:    vshufpd {{.*#+}} xmm3 = xmm1[1,0]
; FMA-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; FMA-NEXT:    vmulsd %xmm4, %xmm3, %xmm3
; FMA-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; FMA-NEXT:    vextractf128 $1, %ymm1, %xmm1
; FMA-NEXT:    vextractf128 $1, %ymm2, %xmm2
; FMA-NEXT:    vmulsd %xmm2, %xmm1, %xmm3
; FMA-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; FMA-NEXT:    vshufpd {{.*#+}} xmm1 = xmm1[1,0]
; FMA-NEXT:    vshufpd {{.*#+}} xmm2 = xmm2[1,0]
; FMA-NEXT:    vmulsd %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vaddsd %xmm1, %xmm0, %xmm0
; FMA-NEXT:    vzeroupper
; FMA-NEXT:    retq
  %res = call double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define double @fdot_f64_reassoc(double %acc, <4 x double> %a, <4 x double> %b) {
; AVX2-LABEL: fdot_f64_reassoc:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulpd %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX2-NEXT:    vaddpd %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; AVX2-NEXT:    vaddsd %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddsd %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f64_reassoc:
; FMA:       # %bb.0:
; FMA-NEXT:    vmulpd %ymm2, %ymm1, %ymm1
; FMA-NEXT:    vextractf128 $1, %ymm1, %xmm2
; FMA-NEXT:    vaddpd %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; FMA-NEXT:    vaddsd %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vaddsd %xmm1, %xmm0, %xmm0
; FMA-NEXT:    vzeroupper
; FMA-NEXT:    retq
  %res = call reassoc double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define double @fdot_f64_contract(double %acc, <4 x double> %a, <4 x double> %b) {
; AVX2-LABEL: fdot_f64_contract:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulsd %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufpd {{.*#+}} xmm3 = xmm1[1,0]
; AVX2-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; AVX2-NEXT:    vmulsd %xmm4, %xmm3, %xmm3
; AVX2-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vextractf128 $1, %ymm1, %xmm1
; AVX2-NEXT:    vextractf128 $1, %ymm2, %xmm2
; AVX2-NEXT:    vmulsd %xmm2, %xmm1, %xmm3
; AVX2-NEXT:    vaddsd %xmm3, %xmm0, %xmm0
; AVX2-NEXT:    vshufpd {{.*#+}} xmm1 = xmm1[1,0]
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm2[1,0]
; AVX2-NEXT:    vmulsd %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddsd %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f64_contract:
; FMA:       # %bb.0:
; FMA-NEXT:    vfmadd231sd {{.*#+}} xmm0 = (xmm1 * xmm2) + xmm0
; FMA-NEXT:    vshufpd {{.*#+}} xmm3 = xmm1[1,0]
; FMA-NEXT:    vshufpd {{.*#+}} xmm4 = xmm2[1,0]
; FMA-NEXT:    vfmadd213sd {{.*#+}} xmm4 = (xmm3 * xmm4) + xmm0
; FMA-NEXT:    vextractf128 $1, %ymm1, %xmm0
; FMA-NEXT:    vextractf128 $1, %ymm2, %xmm1
; FMA-NEXT:    vfmadd231sd {{.*#+}} xmm4 = (xmm0 * xmm1) + xmm4
; FMA-NEXT:    vshufpd {{.*#+}} xmm2 = xmm0[1,0]
; FMA-NEXT:    vshufpd {{.*#+}} xmm0 = xmm1[1,0]
; FMA-NEXT:    vfmadd213sd {{.*#+}} xmm0 = (xmm2 * xmm0) + xmm4
; FMA-NEXT:    vzeroupper
; FMA-NEXT:    retq
  %res = call contract double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define double @fdot_f64_reassoc_contract(double %acc, <4 x double> %a, <4 x double> %b) {
; AVX2-LABEL: fdot_f64_reassoc_contract:
; AVX2:       # %bb.0:
; AVX2-NEXT:    vmulpd %ymm2, %ymm1, %ymm1
; AVX2-NEXT:    vextractf128 $1, %ymm1, %xmm2
; AVX2-NEXT:    vaddpd %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; AVX2-NEXT:    vaddsd %xmm2, %xmm1, %xmm1
; AVX2-NEXT:    vaddsd %xmm1, %xmm0, %xmm0
; AVX2-NEXT:    vzeroupper
; AVX2-NEXT:    retq
;
; FMA-LABEL: fdot_f64_reassoc_contract:
; FMA:       # %bb.0:
; FMA-NEXT:    vmulpd %ymm2, %ymm1, %ymm1
; FMA-NEXT:    vextractf128 $1, %ymm1, %xmm2
; FMA-NEXT:    vaddpd %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vshufpd {{.*#+}} xmm2 = xmm1[1,0]
; FMA-NEXT:    vaddsd %xmm2, %xmm1, %xmm1
; FMA-NEXT:    vaddsd %xmm1, %xmm0, %xmm0
; FMA-NEXT:    vzeroupper
; FMA-NEXT:    retq
  %res = call reassoc contract double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}
