; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=x86_64-unknown-linux-gnu -O3 | FileCheck %s --check-prefix=X86

define void @foo(i64 %ptr, i1 %cond, <8 x i1> %arg, <8 x i1> %0) #0 {
; X86-LABEL: foo:
; X86:       # %bb.0: # %entry
; X86-NEXT:    testb $1, %sil
; X86-NEXT:    jne .LBB0_2
; X86-NEXT:  # %bb.1: # %bb0
; X86-NEXT:    vpsllw $15, %xmm0, %xmm0
; X86-NEXT:    vpmovw2m %xmm0, %k1
; X86-NEXT:    andl $-8, %edi
; X86-NEXT:    vmovd %edi, %xmm0
; X86-NEXT:    vxorpd %xmm1, %xmm1, %xmm1
; X86-NEXT:    vpcmpeqd %ymm2, %ymm2, %ymm2
; X86-NEXT:    vpsubq %ymm2, %ymm0, %ymm0
; X86-NEXT:    vpmovqd %ymm0, %xmm2
; X86-NEXT:    vpbroadcastd {{.*#+}} xmm3 = [1,1,1,1]
; X86-NEXT:    vinserti128 $1, %xmm3, %ymm2, %ymm2
; X86-NEXT:    vptestnmd %ymm2, %ymm2, %k2
; X86-NEXT:    kshiftrb $4, %k2, %k3
; X86-NEXT:    vbroadcastsd {{.*#+}} ymm2 = [1.0E+0,1.0E+0,1.0E+0,1.0E+0]
; X86-NEXT:    vmovapd %ymm2, %ymm3 {%k2} {z}
; X86-NEXT:    vpxor %xmm4, %xmm4, %xmm4
; X86-NEXT:    vpmadd52luq {{\.?LCPI[0-9]+_[0-9]+}}(%rip){1to4}, %ymm0, %ymm4
; X86-NEXT:    kshiftrb $4, %k1, %k2
; X86-NEXT:    vscatterqpd %ymm3, (,%ymm4) {%k1}
; X86-NEXT:    vmovapd %ymm2, %ymm0 {%k3} {z}
; X86-NEXT:    vscatterqpd %ymm0, 24640(,%ymm1) {%k2}
; X86-NEXT:  .LBB0_2: # %exit
; X86-NEXT:    vzeroupper
; X86-NEXT:    retq
entry:
  %i = and i64 %ptr, 4294967288
  br i1 %cond, label %exit, label %bb0

bb0:
  %.splatinsert = insertelement <8 x i64> zeroinitializer, i64 %i, i64 0
  %i2 = add <8 x i64> %.splatinsert, splat (i64 1)
  %i3 = trunc <8 x i64> %i2 to <8 x i32>
  %hir.cmp.264 = icmp eq <8 x i32> %i3, zeroinitializer
  %i6 = select <8 x i1> %hir.cmp.264, <8 x double> splat (double 1.000000e+00), <8 x double> zeroinitializer
  %i7 = getelementptr [55 x [56 x [55 x double]]], ptr null, <8 x i64> zeroinitializer, <8 x i64> %i2, i64 0, i64 0
  tail call void @llvm.masked.scatter.v8f64.v8p0(<8 x double> %i6, <8 x ptr> %i7, <8 x i1> %arg)
  ret void

exit:
  ret void
}

declare void @llvm.masked.scatter.v8f64.v8p0(<8 x double>, <8 x ptr>, <8 x i1>) #1

attributes #0 = { "min-legal-vector-width"="0" "target-cpu"="tigerlake" }
attributes #1 = { nocallback nofree nosync nounwind willreturn memory(write) }
