; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-windows-msvc | FileCheck %s --check-prefix=CHECK
; RUN: llc -combiner-topological-sorting < %s -mtriple=x86_64-windows-gnu | FileCheck %s --check-prefix=CHECK

define i32 @pass_bool(i1 zeroext %b) {
; CHECK-LABEL: pass_bool:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xorl %edx, %edx
; CHECK-NEXT:    testb %cl, %cl
; CHECK-NEXT:    movl $66, %eax
; CHECK-NEXT:    cmovel %edx, %eax
; CHECK-NEXT:    retq
entry:
  %cond = select i1 %b, i32 66, i32 0
  ret i32 %cond
}

define zeroext i1 @ret_true() {
; CHECK-LABEL: ret_true:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    movb $1, %al
; CHECK-NEXT:    retq
entry:
  ret i1 true
}
