; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=x86_64-unknown-windows-msvc -mattr=+egpr -o - %s | FileCheck %s

; EGPR is enabled to verify V3 + EGPR compiles without errors.
; R16-R31 are caller-saved on Win64, so they won't appear in SEH push/pop.

; V3 uses a module-wide default via a file-level .seh_unwindversion 3 directive.
; Functions should NOT have per-function .seh_unwindversion or .seh_unwindv2start.

; Unlike V1/V2, there is a .seh_* directive *before* each real instruction in
; the prolog AND before each instruction in the epilog.

; CHECK:        .seh_unwindversion 3

define dso_local void @no_epilog() local_unnamed_addr {
; CHECK-LABEL: no_epilog:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    retq
entry:
  ret void
}

define dso_local void @stack_alloc_no_pushes() local_unnamed_addr {
; CHECK-LABEL: stack_alloc_no_pushes:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    callq a
; CHECK-NEXT:    nop
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  call void @a()
  ret void
}

define dso_local i32 @stack_alloc_and_pushes(i32 %x) local_unnamed_addr {
; CHECK-LABEL: stack_alloc_and_pushes:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_pushreg %rsi
; CHECK-NEXT:    pushq %rsi
; CHECK-NEXT:    .seh_pushreg %rdi
; CHECK-NEXT:    pushq %rdi
; CHECK-NEXT:    .seh_pushreg %rbx
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .seh_stackalloc 32
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    movl %ecx, %esi
; CHECK-NEXT:    callq c
; CHECK-NEXT:    movl %eax, %edi
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    callq c
; CHECK-NEXT:    movl %eax, %ebx
; CHECK-NEXT:    addl %edi, %ebx
; CHECK-NEXT:    movl %esi, %ecx
; CHECK-NEXT:    callq c
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    callq c
; CHECK-NEXT:    addl %ebx, %eax
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 32
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    .seh_pushreg %rbx
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .seh_pushreg %rdi
; CHECK-NEXT:    popq %rdi
; CHECK-NEXT:    .seh_pushreg %rsi
; CHECK-NEXT:    popq %rsi
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  %call = tail call i32 @c(i32 %x)
  %call1 = tail call i32 @c(i32 %x)
  %add = add nsw i32 %call1, %call
  %call2 = tail call i32 @c(i32 %x)
  %call3 = tail call i32 @c(i32 %call2)
  %add4 = add nsw i32 %add, %call3
  ret i32 %add4
}

define dso_local i32 @multiple_epilogs(i32 %x) local_unnamed_addr {
; CHECK-LABEL: multiple_epilogs:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    callq c
; CHECK-NEXT:    testl %eax, %eax
; CHECK-NEXT:    jle .LBB3_2
; CHECK-NEXT:  # %bb.1: # %if.then
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    jmp c # TAILCALL
; CHECK-NEXT:  .LBB3_2: # %if.else
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    jmp b # TAILCALL
; CHECK-NEXT:    .seh_endproc
entry:
  %call = tail call i32 @c(i32 noundef %x)
  %cmp = icmp sgt i32 %call, 0
  br i1 %cmp, label %if.then, label %if.else

if.then:
  %call1 = tail call i32 @c(i32 noundef %call)
  ret i32 %call1

if.else:
  %call2 = tail call i32 @b()
  ret i32 %call2
}

define dso_local i32 @tail_call(i32 %x) local_unnamed_addr {
; CHECK-LABEL: tail_call:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    callq c
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    addq $40, %rsp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    jmp c # TAILCALL
; CHECK-NEXT:    .seh_endproc
entry:
  %call = tail call i32 @c(i32 %x)
  %call1 = tail call i32 @c(i32 %call)
  ret i32 %call1
}

define dso_local void @dynamic_stack_alloc(i32 %x) local_unnamed_addr {
; CHECK-LABEL: dynamic_stack_alloc:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .seh_setframe %rbp, 0
; CHECK-NEXT:    movq %rsp, %rbp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    movl %ecx, %eax
; CHECK-NEXT:    leaq 15(,%rax,4), %rax
; CHECK-NEXT:    andq $-16, %rax
; CHECK-NEXT:    callq __chkstk
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_setframe %rbp, 0
; CHECK-NEXT:    movq %rbp, %rsp
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  %y = alloca i32, i32 %x
  ret void
}

define dso_local void @large_aligned_alloc() align 16 {
; CHECK-LABEL: large_aligned_alloc:
; CHECK:       # %bb.0:
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .seh_stackalloc 176
; CHECK-NEXT:    subq $176, %rsp
; CHECK-NEXT:    .seh_setframe %rbp, 128
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rbp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    andq $-64, %rsp
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_setframe %rbp, 128
; CHECK-NEXT:    .seh_stackalloc 176
; CHECK-NEXT:    leaq 48(%rbp), %rsp
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
  %1 = alloca [128 x i8], align 64
  ret void
}

attributes #1 = { noreturn }
define dso_local void @no_return_func() local_unnamed_addr #1 {
; CHECK-LABEL: no_return_func:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_stackalloc 40
; CHECK-NEXT:    subq $40, %rsp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    callq d
; CHECK-NEXT:    int3
; CHECK-NEXT:    .seh_endproc
entry:
  call void @d()
  unreachable
}

define dso_local i32 @has_funclet(i32 %x) local_unnamed_addr personality ptr @__C_specific_handler {
; CHECK-LABEL: has_funclet:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .seh_pushreg %rsi
; CHECK-NEXT:    pushq %rsi
; CHECK-NEXT:    .seh_pushreg %rdi
; CHECK-NEXT:    pushq %rdi
; CHECK-NEXT:    .seh_stackalloc 48
; CHECK-NEXT:    subq $48, %rsp
; CHECK-NEXT:    .seh_setframe %rbp, 48
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rbp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:  .Ltmp0: # EH_LABEL
; CHECK-NEXT:    movl %ecx, {{[-0-9]+}}(%r{{[sb]}}p) # 4-byte Spill
; CHECK-NEXT:    callq c
; CHECK-NEXT:    nop
; CHECK-NEXT:  .Ltmp1: # EH_LABEL
; CHECK-NEXT:  # %bb.1: # %call.block.1
; CHECK-NEXT:  .Ltmp2: # EH_LABEL
; CHECK-NEXT:    movl %eax, %esi
; CHECK-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Reload
; CHECK-NEXT:    callq c
; CHECK-NEXT:    nop
; CHECK-NEXT:  .Ltmp3: # EH_LABEL
; CHECK-NEXT:  # %bb.2: # %call.block.2
; CHECK-NEXT:  .Ltmp4: # EH_LABEL
; CHECK-NEXT:    movl %eax, %edi
; CHECK-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Reload
; CHECK-NEXT:    callq c
; CHECK-NEXT:    nop
; CHECK-NEXT:  .Ltmp5: # EH_LABEL
; CHECK-NEXT:  # %bb.3: # %call.block.3
; CHECK-NEXT:  .Ltmp6: # EH_LABEL
; CHECK-NEXT:    movl %eax, %ecx
; CHECK-NEXT:    callq c
; CHECK-NEXT:    nop
; CHECK-NEXT:  .Ltmp7: # EH_LABEL
; CHECK-NEXT:  # %bb.4: # %call.block.4
; CHECK-NEXT:    addl %esi, %edi
; CHECK-NEXT:    addl %eax, %edi
; CHECK-NEXT:    movl %edi, %eax
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 48
; CHECK-NEXT:    addq $48, %rsp
; CHECK-NEXT:    .seh_pushreg %rdi
; CHECK-NEXT:    popq %rdi
; CHECK-NEXT:    .seh_pushreg %rsi
; CHECK-NEXT:    popq %rsi
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_handlerdata
; CHECK-NEXT:  .Lhas_funclet$parent_frame_offset = 48
; CHECK-NEXT:    .long (.Llsda_end0-.Llsda_begin0)/16 # Number of call sites
; CHECK-NEXT:  .Llsda_begin0:
; CHECK-NEXT:    .long .Ltmp0@IMGREL # LabelStart
; CHECK-NEXT:    .long .Ltmp7@IMGREL # LabelEnd
; CHECK-NEXT:    .long "?dtor$5@?0?has_funclet@4HA"@IMGREL # FinallyFunclet
; CHECK-NEXT:    .long 0 # Null
; CHECK-NEXT:  .Llsda_end0:
; CHECK-NEXT:    .text
; CHECK-NEXT:    .seh_endproc
; CHECK-NEXT:    .def "?dtor$5@?0?has_funclet@4HA";
; CHECK-NEXT:    .scl 3;
; CHECK-NEXT:    .type 32;
; CHECK-NEXT:    .endef
; CHECK-NEXT:    .p2align 4
; CHECK-NEXT:  "?dtor$5@?0?has_funclet@4HA":
; CHECK-NEXT:  .seh_proc "?dtor$5@?0?has_funclet@4HA"
; CHECK-NEXT:  .LBB8_5: # %cleanup
; CHECK-NEXT:    movq %rdx, {{[0-9]+}}(%rsp)
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .seh_pushreg %rsi
; CHECK-NEXT:    pushq %rsi
; CHECK-NEXT:    .seh_pushreg %rdi
; CHECK-NEXT:    pushq %rdi
; CHECK-NEXT:    .seh_stackalloc 32
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    leaq 48(%rdx), %rbp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    movl {{[-0-9]+}}(%r{{[sb]}}p), %ecx # 4-byte Reload
; CHECK-NEXT:    callq cleanup_helper
; CHECK-NEXT:    nop
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 32
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    .seh_pushreg %rdi
; CHECK-NEXT:    popq %rdi
; CHECK-NEXT:    .seh_pushreg %rsi
; CHECK-NEXT:    popq %rsi
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq # CLEANUPRET
; CHECK-NEXT:  .Lfunc_end0:
; CHECK-NEXT:    .seh_handlerdata
; CHECK-NEXT:    .text
; CHECK-NEXT:    .seh_endproc
entry:
  %call = invoke i32 @c(i32 %x)
    to label %call.block.1 unwind label %cleanup

call.block.1:
  %call1 = invoke i32 @c(i32 %x)
    to label %call.block.2 unwind label %cleanup

call.block.2:
  %add = add nsw i32 %call1, %call
  %call2 = invoke i32 @c(i32 %x)
    to label %call.block.3 unwind label %cleanup

call.block.3:
  %call3 = invoke i32 @c(i32 %call2)
    to label %call.block.4 unwind label %cleanup

call.block.4:
  %add4 = add nsw i32 %add, %call3
  ret i32 %add4

cleanup:
  %cleanup_token = cleanuppad within none []
  call fastcc void @cleanup_helper(i32 %x) #18 [ "funclet"(token %cleanup_token) ]
  cleanupret from %cleanup_token unwind to caller
}

define internal fastcc void @cleanup_helper(i32 %x) local_unnamed_addr {
; CHECK-LABEL: cleanup_helper:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .seh_setframe %rbp, 0
; CHECK-NEXT:    movq %rsp, %rbp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    movl %ecx, %eax
; CHECK-NEXT:    leaq 15(,%rax,4), %rax
; CHECK-NEXT:    andq $-16, %rax
; CHECK-NEXT:    callq __chkstk
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_setframe %rbp, 0
; CHECK-NEXT:    movq %rbp, %rsp
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  %y = alloca i32, i32 %x
  ret void
}

declare void @a() local_unnamed_addr
declare i32 @b() local_unnamed_addr
declare i32 @c(i32) local_unnamed_addr
declare void @d() local_unnamed_addr #1
declare dso_local i32 @__C_specific_handler(...)
declare i64 @llvm.x86.flags.read.u64()

; ---- XMM callee-saved saves: SEH_SaveXMM before movaps in V3 ----
define dso_local void @xmm_saves() local_unnamed_addr {
; CHECK-LABEL: xmm_saves:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_stackalloc 72
; CHECK-NEXT:    subq $72, %rsp
; CHECK-NEXT:    .seh_savexmm %xmm7, 48
; CHECK-NEXT:    movaps %xmm7, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    .seh_savexmm %xmm6, 32
; CHECK-NEXT:    movaps %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    callq a
; CHECK-NEXT:    nop
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_savexmm %xmm6, 32
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm6 # 16-byte Reload
; CHECK-NEXT:    .seh_savexmm %xmm7, 48
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm7 # 16-byte Reload
; CHECK-NEXT:    .seh_stackalloc 72
; CHECK-NEXT:    addq $72, %rsp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  call void asm sideeffect "", "~{xmm6},~{xmm7}"()
  call void @a()
  ret void
}

define dso_local void @xmm_and_gpr_saves(ptr %p) local_unnamed_addr {
; CHECK-LABEL: xmm_and_gpr_saves:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_pushreg %rbx
; CHECK-NEXT:    pushq %rbx
; CHECK-NEXT:    .seh_stackalloc 48
; CHECK-NEXT:    subq $48, %rsp
; CHECK-NEXT:    .seh_savexmm %xmm6, 32
; CHECK-NEXT:    movaps %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    callq a
; CHECK-NEXT:    nop
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_savexmm %xmm6, 32
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm6 # 16-byte Reload
; CHECK-NEXT:    .seh_stackalloc 48
; CHECK-NEXT:    addq $48, %rsp
; CHECK-NEXT:    .seh_pushreg %rbx
; CHECK-NEXT:    popq %rbx
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  call void asm sideeffect "", "~{xmm6},~{rbx}"()
  call void @a()
  ret void
}

define dso_local void @large_stack_alloc() local_unnamed_addr {
; CHECK-LABEL: large_stack_alloc:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_stackalloc 8232
; CHECK-NEXT:    movl $8232, %eax # imm = 0x2028
; CHECK-NEXT:    callq __chkstk
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    callq a
; CHECK-NEXT:    nop
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_stackalloc 8232
; CHECK-NEXT:    addq $8232, %rsp # imm = 0x2028
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  %buf = alloca [8192 x i8], align 1
  call void @a()
  ret void
}

define dso_local void @large_dynalloc_frame(i32 %n) local_unnamed_addr {
; CHECK-LABEL: large_dynalloc_frame:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .seh_stackalloc 4096
; CHECK-NEXT:    movl $4096, %eax # imm = 0x1000
; CHECK-NEXT:    callq __chkstk
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    .seh_setframe %rbp, 128
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rbp
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    movl %ecx, %eax
; CHECK-NEXT:    leaq 15(,%rax,4), %rax
; CHECK-NEXT:    andq $-16, %rax
; CHECK-NEXT:    callq __chkstk
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    callq a
; CHECK-NEXT:    nop
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_setframe %rbp, 128
; CHECK-NEXT:    .seh_stackalloc 4096
; CHECK-NEXT:    leaq 3968(%rbp), %rsp
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  %buf = alloca [4096 x i8], align 16
  %dyn = alloca i32, i32 %n
  call void @a()
  ret void
}

define dso_local void @xmm_with_dynalloc(i32 %n) local_unnamed_addr {
; CHECK-LABEL: xmm_with_dynalloc:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    pushq %rbp
; CHECK-NEXT:    .seh_stackalloc 32
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    .seh_setframe %rbp, 32
; CHECK-NEXT:    leaq {{[0-9]+}}(%rsp), %rbp
; CHECK-NEXT:    .seh_savexmm %xmm7, 16
; CHECK-NEXT:    movaps %xmm7, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    .seh_savexmm %xmm6, 0
; CHECK-NEXT:    movaps %xmm6, {{[-0-9]+}}(%r{{[sb]}}p) # 16-byte Spill
; CHECK-NEXT:    .seh_endprologue
; CHECK-NEXT:    #APP
; CHECK-NEXT:    #NO_APP
; CHECK-NEXT:    movl %ecx, %eax
; CHECK-NEXT:    leaq 15(,%rax,4), %rax
; CHECK-NEXT:    andq $-16, %rax
; CHECK-NEXT:    callq __chkstk
; CHECK-NEXT:    subq %rax, %rsp
; CHECK-NEXT:    subq $32, %rsp
; CHECK-NEXT:    callq a
; CHECK-NEXT:    addq $32, %rsp
; CHECK-NEXT:    .seh_startepilogue
; CHECK-NEXT:    .seh_savexmm %xmm6, 0
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm6 # 16-byte Reload
; CHECK-NEXT:    .seh_savexmm %xmm7, 16
; CHECK-NEXT:    movaps {{[-0-9]+}}(%r{{[sb]}}p), %xmm7 # 16-byte Reload
; CHECK-NEXT:    .seh_setframe %rbp, 32
; CHECK-NEXT:    .seh_stackalloc 32
; CHECK-NEXT:    movq %rbp, %rsp
; CHECK-NEXT:    .seh_pushreg %rbp
; CHECK-NEXT:    popq %rbp
; CHECK-NEXT:    .seh_endepilogue
; CHECK-NEXT:    retq
; CHECK-NEXT:    .seh_endproc
entry:
  call void asm sideeffect "", "~{xmm6},~{xmm7}"()
  %dyn = alloca i32, i32 %n
  call void @a()
  ret void
}

!llvm.module.flags = !{!0}
!0 = !{i32 1, !"winx64-eh-unwind", i32 3}
