; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -combiner-topological-sorting < %s -mcpu=nehalem | FileCheck %s

target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-s0:64:64-f80:128:128"
target triple = "x86_64-apple-darwin8"

define i32 @foo() nounwind uwtable "xray-instruction-threshold"="1" {
; CHECK-LABEL: foo:
; CHECK:       ## %bb.0: ## %entry
; CHECK-NEXT:    .p2align 1
; CHECK-NEXT:  Lxray_sled_0:
; CHECK-NEXT:    .ascii "\353\t"
; CHECK-NEXT:    nopw 512(%rax,%rax)
; CHECK-NEXT:    xorl %eax, %eax
; CHECK-NEXT:    .p2align 1
; CHECK-NEXT:  Lxray_sled_1:
; CHECK-NEXT:    retq
; CHECK-NEXT:    nopw %cs:512(%rax,%rax)
entry:
  ret i32 0
}
