; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; RUN: opt -passes=loop-idiom -S %s | FileCheck %s

target datalayout = "p:16:16"

;.
; CHECK: @.crctable = private constant [256 x i32] zeroinitializer
;.
define void @test_with_dl() {
; CHECK-LABEL: define void @test_with_dl() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[PH:.*]]
; CHECK:       [[PH_LOOPEXIT:.*]]:
; CHECK-NEXT:    [[CRC_NEXT_LCSSA:%.*]] = phi i32 [ [[CRC_NEXT3:%.*]], %[[LOOP:.*]] ]
; CHECK-NEXT:    br label %[[PH]]
; CHECK:       [[PH]]:
; CHECK-NEXT:    [[CRC_USE:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[CRC_NEXT_LCSSA]], %[[PH_LOOPEXIT]] ]
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i16 [ 0, %[[PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[CRC2:%.*]] = phi i32 [ 0, %[[PH]] ], [ [[CRC_NEXT3]], %[[LOOP]] ]
; CHECK-NEXT:    [[INDEXER_LO:%.*]] = trunc i32 [[CRC2]] to i8
; CHECK-NEXT:    [[INDEXER_EXT:%.*]] = zext i8 [[INDEXER_LO]] to i16
; CHECK-NEXT:    [[TBL_PTRADD:%.*]] = getelementptr inbounds i32, ptr @.crctable, i16 [[INDEXER_EXT]]
; CHECK-NEXT:    [[TBL_LD:%.*]] = load i32, ptr [[TBL_PTRADD]], align 4
; CHECK-NEXT:    [[CRC_LE_SHIFT:%.*]] = lshr i32 [[CRC2]], 8
; CHECK-NEXT:    [[CRC_NEXT3]] = xor i32 [[CRC_LE_SHIFT]], [[TBL_LD]]
; CHECK-NEXT:    [[IV_NEXT]] = add i16 [[IV]], 1
; CHECK-NEXT:    [[EXIT_COND1:%.*]] = icmp ne i16 [[IV]], 0
; CHECK-NEXT:    br i1 [[EXIT_COND1]], label %[[LOOP]], label %[[PH_LOOPEXIT]]
;
entry:
  br label %ph

ph:
  %crc.use = phi i32 [ 0, %entry ], [ %crc.next, %loop ]
  br label %loop

loop:
  %iv = phi i16 [ 0, %ph ], [ %iv.next, %loop ]
  %crc = phi i32 [ 0, %ph ], [ %crc.next, %loop ]
  %lshr.crc.1 = lshr i32 %crc, 1
  %crc.and.1 = and i32 %crc, 1
  %sb.check = icmp eq i32 %crc.and.1, 0
  %xor = xor i32 %lshr.crc.1, 0
  %crc.next = select i1 %sb.check, i32 %lshr.crc.1, i32 %xor
  %iv.next = add i16 %iv, 1
  %exit.cond = icmp ult i16 %iv, 7
  br i1 %exit.cond, label %loop, label %ph
}
