; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-idiom < %s -S | FileCheck %s

declare void @foo()
%arr = type { [50 x i8] }
%arr_i16 = type { [50 x i16] }
%arr_too_short = type { [49 x i8] }
%arr_elements_have_padding = type { [50 x i9] }
%arr_floats = type { [50 x float] }
%arr_ptr = type { [50 x ptr] }

define i1 @memcmp_idiom_int8_array(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @memcmp_idiom_int8_array(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[MEMCMP:%.*]] = call i32 @memcmp(ptr [[LHS]], ptr [[RHS]], i64 50)
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq i32 [[MEMCMP]], 0
; CHECK-NEXT:    ret i1 [[TMP0]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @memcmp_idiom_int16_array(ptr byval(%arr_i16) align 8 %lhs, ptr byval(%arr_i16) align 8 %rhs) {
; CHECK-LABEL: define i1 @memcmp_idiom_int16_array(
; CHECK-SAME: ptr byval([[ARR_I16:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR_I16]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i16, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i16, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i16, ptr [[LHS_ADDR]], align 2
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i16, ptr [[RHS_ADDR]], align 2
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i16 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[MEMCMP:%.*]] = call i32 @memcmp(ptr [[LHS]], ptr [[RHS]], i64 100)
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq i32 [[MEMCMP]], 0
; CHECK-NEXT:    ret i1 [[TMP0]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i16, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i16, ptr %rhs, i64 %indvar
  %lhs_val = load i16, ptr %lhs_addr, align 2
  %rhs_val = load i16, ptr %rhs_addr, align 2
  %equal = icmp eq i16 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @memcmp_idiom_ptr_array(ptr byval(%arr_ptr) align 8 %lhs, ptr byval(%arr_ptr) align 8 %rhs) {
; CHECK-LABEL: define i1 @memcmp_idiom_ptr_array(
; CHECK-SAME: ptr byval([[ARR_PTR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR_PTR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw ptr, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw ptr, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load ptr, ptr [[LHS_ADDR]], align 8
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load ptr, ptr [[RHS_ADDR]], align 8
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq ptr [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[MEMCMP:%.*]] = call i32 @memcmp(ptr [[LHS]], ptr [[RHS]], i64 400)
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq i32 [[MEMCMP]], 0
; CHECK-NEXT:    ret i1 [[TMP0]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw ptr, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw ptr, ptr %rhs, i64 %indvar
  %lhs_val = load ptr, ptr %lhs_addr
  %rhs_val = load ptr, ptr %rhs_addr
  %equal = icmp eq ptr %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @memcmp_idiom_offset_from_base_pointer(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @memcmp_idiom_offset_from_base_pointer(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[LHS_OFFSET:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 8
; CHECK-NEXT:    [[RHS_OFFSET:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 8
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 40
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS_OFFSET]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS_OFFSET]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[MEMCMP:%.*]] = call i32 @memcmp(ptr [[LHS_OFFSET]], ptr [[RHS_OFFSET]], i64 40)
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq i32 [[MEMCMP]], 0
; CHECK-NEXT:    ret i1 [[TMP0]]
;

entry:
  %lhs_offset = getelementptr inbounds nuw i8, ptr %lhs, i64 8
  %rhs_offset = getelementptr inbounds nuw i8, ptr %rhs, i64 8
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 40
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs_offset, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs_offset, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_cond_block_side_effect(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_cond_block_side_effect(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    store i8 0, ptr [[LHS]], align 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  store i8 0, ptr %lhs
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_cond_block_makes_call(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_cond_block_makes_call(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  call void @foo()
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_body_block_side_effect(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_body_block_side_effect(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    store i8 0, ptr [[LHS]], align 1
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  store i8 0, ptr %lhs
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_body_block_makes_call(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_body_block_makes_call(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    call void @foo()
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  call void @foo()
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_multiple_lcssa_phi(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_multiple_lcssa_phi(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    [[EXTRA_PHI:%.*]] = phi i8 [ [[LHS_VAL]], %[[BODY]] ], [ [[LHS_VAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  %extra_phi = phi i8 [%lhs_val, %body], [%lhs_val, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_bad_cmp_predicate(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_bad_cmp_predicate(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp ne i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp ne i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_volatile_loads(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_volatile_loads(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load volatile i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load volatile i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[TMP0]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load volatile i8, ptr %lhs_addr, align 1
  %rhs_val = load volatile i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_atomic_loads(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_atomic_loads(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load atomic i8, ptr [[LHS_ADDR]] unordered, align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load atomic i8, ptr [[RHS_ADDR]] unordered, align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load atomic i8, ptr %lhs_addr unordered, align 1
  %rhs_val = load atomic i8, ptr %rhs_addr unordered, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_has_padding(ptr byval(%arr_elements_have_padding) align 8 %lhs, ptr byval(%arr_elements_have_padding) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_has_padding(
; CHECK-SAME: ptr byval([[ARR_ELEMENTS_HAVE_PADDING:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR_ELEMENTS_HAVE_PADDING]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i9, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i9, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i9 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i9, ptr %lhs_addr, align 1
  %rhs_val = load i9, ptr %rhs_addr, align 1
  %equal = icmp eq i9 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_float_array(ptr byval(%arr_floats) align 8 %lhs, ptr byval(%arr_floats) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_float_array(
; CHECK-SAME: ptr byval([[ARR_FLOATS:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR_FLOATS]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw float, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw float, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load float, ptr [[LHS_ADDR]], align 4
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load float, ptr [[RHS_ADDR]], align 4
; CHECK-NEXT:    [[EQUAL:%.*]] = fcmp oeq float [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw float, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw float, ptr %rhs, i64 %indvar
  %lhs_val = load float, ptr %lhs_addr
  %rhs_val = load float, ptr %rhs_addr
  %equal = fcmp oeq float %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_loads_skip_bytes(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_loads_skip_bytes(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 25
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[DOUBLEINDVAR:%.*]] = mul i64 [[INDVAR]], 2
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[DOUBLEINDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[DOUBLEINDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 25
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %doubleindvar = mul i64 %indvar, 2
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %doubleindvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %doubleindvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_potential_out_of_bounds_read(ptr byval(%arr_too_short) align 8 %lhs, ptr byval(%arr_too_short) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_potential_out_of_bounds_read(
; CHECK-SAME: ptr byval([[ARR_TOO_SHORT:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR_TOO_SHORT]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 50
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 50
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %indvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

define i1 @no_idiom_load_pair_has_mismatched_stride(ptr byval(%arr) align 8 %lhs, ptr byval(%arr) align 8 %rhs) {
; CHECK-LABEL: define i1 @no_idiom_load_pair_has_mismatched_stride(
; CHECK-SAME: ptr byval([[ARR:%.*]]) align 8 [[LHS:%.*]], ptr byval([[ARR]]) align 8 [[RHS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[BODY:.*]]
; CHECK:       [[COND:.*]]:
; CHECK-NEXT:    [[INC:%.*]] = add nuw nsw i64 [[INDVAR:%.*]], 1
; CHECK-NEXT:    [[STOP_LOOP:%.*]] = icmp eq i64 [[INC]], 25
; CHECK-NEXT:    br i1 [[STOP_LOOP]], label %[[EXIT:.*]], label %[[BODY]]
; CHECK:       [[BODY]]:
; CHECK-NEXT:    [[INDVAR]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INC]], %[[COND]] ]
; CHECK-NEXT:    [[DOUBLEINDVAR:%.*]] = mul i64 [[INDVAR]], 2
; CHECK-NEXT:    [[LHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[LHS]], i64 [[DOUBLEINDVAR]]
; CHECK-NEXT:    [[RHS_ADDR:%.*]] = getelementptr inbounds nuw i8, ptr [[RHS]], i64 [[INDVAR]]
; CHECK-NEXT:    [[LHS_VAL:%.*]] = load i8, ptr [[LHS_ADDR]], align 1
; CHECK-NEXT:    [[RHS_VAL:%.*]] = load i8, ptr [[RHS_ADDR]], align 1
; CHECK-NEXT:    [[EQUAL:%.*]] = icmp eq i8 [[LHS_VAL]], [[RHS_VAL]]
; CHECK-NEXT:    br i1 [[EQUAL]], label %[[COND]], label %[[EXIT]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RET:%.*]] = phi i1 [ [[EQUAL]], %[[BODY]] ], [ [[EQUAL]], %[[COND]] ]
; CHECK-NEXT:    ret i1 [[RET]]
;
entry:
  br label %body
cond:
  %inc = add nuw nsw i64 %indvar, 1
  %stop_loop = icmp eq i64 %inc, 25
  br i1 %stop_loop, label %exit, label %body
body:
  %indvar = phi i64 [ 0, %entry ], [ %inc, %cond ]
  %doubleindvar = mul i64 %indvar, 2
  %lhs_addr = getelementptr inbounds nuw i8, ptr %lhs, i64 %doubleindvar
  %rhs_addr = getelementptr inbounds nuw i8, ptr %rhs, i64 %indvar
  %lhs_val = load i8, ptr %lhs_addr, align 1
  %rhs_val = load i8, ptr %rhs_addr, align 1
  %equal = icmp eq i8 %lhs_val, %rhs_val
  br i1 %equal, label %cond, label %exit
exit:
  %ret = phi i1 [ %equal, %body ], [ %equal, %cond ]
  ret i1 %ret
}

; Test stolen from a miscompile from an old attempt at recognizing memcmp idioms in loops,
; before it was reverted. https://bugs.llvm.org/show_bug.cgi?id=43206
;
; bool do_check(int i_max, int j_max, int**bptr, int* fillch) {
;   for (int i = 0; i < i_max; i++)
;       for (int j = 0; j < j_max; j++)
;         if (bptr[i][j] != fillch[i])
;           return 1;
;   return 0;
; }
;
; The loads proceed differently here - fillch[i] changes once per outer loop,
; while bptr[i][j] changes both in inner loop, and in outer loop.
define i1 @no_idiom_different_loops(i32 %i_max, i32 %j_max, i32** %bptr, i32* %fillch) {
; CHECK-LABEL: define i1 @no_idiom_different_loops(
; CHECK-SAME: i32 [[I_MAX:%.*]], i32 [[J_MAX:%.*]], ptr [[BPTR:%.*]], ptr [[FILLCH:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP31:%.*]] = icmp sgt i32 [[I_MAX]], 0
; CHECK-NEXT:    [[CMP229:%.*]] = icmp sgt i32 [[J_MAX]], 0
; CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[CMP31]], [[CMP229]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[FOR_COND1_PREHEADER_US_PREHEADER:.*]], label %[[CLEANUP12:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_US_PREHEADER]]:
; CHECK-NEXT:    [[WIDE_TRIP_COUNT38:%.*]] = zext i32 [[I_MAX]] to i64
; CHECK-NEXT:    [[WIDE_TRIP_COUNT:%.*]] = zext i32 [[J_MAX]] to i64
; CHECK-NEXT:    br label %[[FOR_COND1_PREHEADER_US:.*]]
; CHECK:       [[FOR_COND1_PREHEADER_US]]:
; CHECK-NEXT:    [[INDVARS_IV36:%.*]] = phi i64 [ 0, %[[FOR_COND1_PREHEADER_US_PREHEADER]] ], [ [[INDVARS_IV_NEXT37:%.*]], %[[FOR_COND1_FOR_INC10_CRIT_EDGE_US:.*]] ]
; CHECK-NEXT:    [[ARRAYIDX_US:%.*]] = getelementptr inbounds ptr, ptr [[BPTR]], i64 [[INDVARS_IV36]]
; CHECK-NEXT:    [[V0:%.*]] = load ptr, ptr [[ARRAYIDX_US]], align 8
; CHECK-NEXT:    [[ARRAYIDX8_US:%.*]] = getelementptr inbounds i32, ptr [[FILLCH]], i64 [[INDVARS_IV36]]
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[ARRAYIDX8_US]], align 4
; CHECK-NEXT:    br label %[[FOR_BODY4_US:.*]]
; CHECK:       [[FOR_COND1_US:.*]]:
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT:%.*]], [[WIDE_TRIP_COUNT]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[FOR_COND1_FOR_INC10_CRIT_EDGE_US]], label %[[FOR_BODY4_US]]
; CHECK:       [[FOR_BODY4_US]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[FOR_COND1_PREHEADER_US]] ], [ [[INDVARS_IV_NEXT]], %[[FOR_COND1_US]] ]
; CHECK-NEXT:    [[ARRAYIDX6_US:%.*]] = getelementptr inbounds i32, ptr [[V0]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[ARRAYIDX6_US]], align 4
; CHECK-NEXT:    [[CMP9_US:%.*]] = icmp eq i32 [[V2]], [[V1]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    br i1 [[CMP9_US]], label %[[FOR_COND1_US]], label %[[CLEANUP12_LOOPEXIT:.*]]
; CHECK:       [[FOR_COND1_FOR_INC10_CRIT_EDGE_US]]:
; CHECK-NEXT:    [[INDVARS_IV_NEXT37]] = add nuw nsw i64 [[INDVARS_IV36]], 1
; CHECK-NEXT:    [[EXITCOND39:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT37]], [[WIDE_TRIP_COUNT38]]
; CHECK-NEXT:    br i1 [[EXITCOND39]], label %[[CLEANUP12_LOOPEXIT1:.*]], label %[[FOR_COND1_PREHEADER_US]]
; CHECK:       [[CLEANUP12_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[CLEANUP12]]
; CHECK:       [[CLEANUP12_LOOPEXIT1]]:
; CHECK-NEXT:    br label %[[CLEANUP12]]
; CHECK:       [[CLEANUP12]]:
; CHECK-NEXT:    [[V3:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[CLEANUP12_LOOPEXIT]] ], [ false, %[[CLEANUP12_LOOPEXIT1]] ]
; CHECK-NEXT:    ret i1 [[V3]]
;
entry:
  %cmp31 = icmp sgt i32 %i_max, 0
  %cmp229 = icmp sgt i32 %j_max, 0
  %or.cond = and i1 %cmp31, %cmp229
  br i1 %or.cond, label %for.cond1.preheader.us.preheader, label %cleanup12

for.cond1.preheader.us.preheader:                 ; preds = %entry
  %wide.trip.count38 = zext i32 %i_max to i64
  %wide.trip.count = zext i32 %j_max to i64
  br label %for.cond1.preheader.us

for.cond1.preheader.us:                           ; preds = %for.cond1.for.inc10_crit_edge.us, %for.cond1.preheader.us.preheader
  %indvars.iv36 = phi i64 [ 0, %for.cond1.preheader.us.preheader ], [ %indvars.iv.next37, %for.cond1.for.inc10_crit_edge.us ]
  %arrayidx.us = getelementptr inbounds i32*, i32** %bptr, i64 %indvars.iv36
  %v0 = load i32*, i32** %arrayidx.us, align 8
  %arrayidx8.us = getelementptr inbounds i32, i32* %fillch, i64 %indvars.iv36
  %v1 = load i32, i32* %arrayidx8.us, align 4
  br label %for.body4.us

for.cond1.us:                                     ; preds = %for.body4.us
  %exitcond = icmp eq i64 %indvars.iv.next, %wide.trip.count
  br i1 %exitcond, label %for.cond1.for.inc10_crit_edge.us, label %for.body4.us

for.body4.us:                                     ; preds = %for.cond1.us, %for.cond1.preheader.us
  %indvars.iv = phi i64 [ 0, %for.cond1.preheader.us ], [ %indvars.iv.next, %for.cond1.us ]
  %arrayidx6.us = getelementptr inbounds i32, i32* %v0, i64 %indvars.iv
  %v2 = load i32, i32* %arrayidx6.us, align 4
  %cmp9.us = icmp eq i32 %v2, %v1
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  br i1 %cmp9.us, label %for.cond1.us, label %cleanup12

for.cond1.for.inc10_crit_edge.us:                 ; preds = %for.cond1.us
  %indvars.iv.next37 = add nuw nsw i64 %indvars.iv36, 1
  %exitcond39 = icmp eq i64 %indvars.iv.next37, %wide.trip.count38
  br i1 %exitcond39, label %cleanup12, label %for.cond1.preheader.us

cleanup12:                                        ; preds = %for.cond1.for.inc10_crit_edge.us, %for.body4.us, %entry
  %v3 = phi i1 [ false, %entry ], [ true, %for.body4.us ], [ false, %for.cond1.for.inc10_crit_edge.us ]
  ret i1 %v3
}
