; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 3
; RUN: opt -passes=vector-widen -vw-override-target-consider-to-widen=1 -S %s 2>&1 | FileCheck %s


define void @fp_ext(<8 x half> %a, <8 x half> %b, ptr %ptr, ptr %ptr1) {
; CHECK-LABEL: define void @fp_ext(
; CHECK-SAME: <8 x half> [[A:%.*]], <8 x half> [[B:%.*]], ptr [[PTR:%.*]], ptr [[PTR1:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = call <16 x half> @llvm.vector.insert.v16f16.v8f16(<16 x half> undef, <8 x half> [[B]], i64 0)
; CHECK-NEXT:    [[TMP1:%.*]] = call <16 x half> @llvm.vector.insert.v16f16.v8f16(<16 x half> [[TMP0]], <8 x half> [[A]], i64 8)
; CHECK-NEXT:    [[TMP2:%.*]] = fpext <16 x half> [[TMP1]] to <16 x double>
; CHECK-NEXT:    [[TMP3:%.*]] = call <8 x double> @llvm.vector.extract.v8f64.v16f64(<16 x double> [[TMP2]], i64 0)
; CHECK-NEXT:    [[TMP4:%.*]] = call <8 x double> @llvm.vector.extract.v8f64.v16f64(<16 x double> [[TMP2]], i64 8)
; CHECK-NEXT:    store <8 x double> [[TMP4]], ptr [[PTR]], align 16
; CHECK-NEXT:    store <8 x double> [[TMP3]], ptr [[PTR1]], align 16
; CHECK-NEXT:    ret void
;
entry:
  %0 = fpext <8 x half> %a to <8 x double>
  %1 = fpext <8 x half> %b to <8 x double>
  store <8 x double> %0, ptr %ptr, align 16
  store <8 x double> %1, ptr %ptr1, align 16
  ret void
}
