// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv32 -target-feature +experimental-p -emit-llvm %s -o - \
// RUN:     -disable-O0-optnone | opt -S -passes=mem2reg \
// RUN:     | FileCheck %s  -check-prefix=RV32P

#include <riscv_simd.h>

// RV32P-LABEL: @pslli_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pslli.b.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pslli_b(uint32_t rs1, int32_t rs2) {
  return __riscv_pslli_b(rs1, 1);
}

// RV32P-LABEL: @pslli_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pslli.h.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pslli_h(uint32_t rs1, int32_t rs2) {
  return __riscv_pslli_h(rs1, 1);
}

// RV32P-LABEL: @psslai_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psslai.h.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psslai_h(uint32_t rs1, int32_t rs2) {
  return __riscv_psslai_h(rs1, 1);
}

// RV32P-LABEL: @sslai(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sslai.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t sslai(uint32_t rs1, int32_t rs2) {
  return __riscv_sslai(rs1, 1);
}

// RV32P-LABEL: @psll_bs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psll.bs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psll_bs(uint32_t rs1, uint32_t rs2) {
  return __riscv_psll_bs(rs1, rs2);
}

// RV32P-LABEL: @psll_hs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psll.hs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psll_hs(uint32_t rs1, uint32_t rs2) {
  return __riscv_psll_hs(rs1, rs2);
}

// RV32P-LABEL: @padd_bs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.padd.bs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t padd_bs(uint32_t rs1, uint32_t rs2) {
  return __riscv_padd_bs(rs1, rs2);
}

// RV32P-LABEL: @padd_hs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.padd.hs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t padd_hs(uint32_t rs1, uint32_t rs2) {
  return __riscv_padd_hs(rs1, rs2);
}

// RV32P-LABEL: @pusati_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pusati.h.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pusati_h(uint32_t rs1, int32_t rs2) {
  return __riscv_pusati_h(rs1, 1);
}

// RV32P-LABEL: @usati(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.usati.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t usati(uint32_t rs1, int32_t rs2) {
  return __riscv_usati(rs1, 1);
}

// RV32P-LABEL: @psrai_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psrai.b.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psrai_b(uint32_t rs1, int32_t rs2) {
  return __riscv_psrai_b(rs1, 1);
}

// RV32P-LABEL: @psrai_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psrai.h.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psrai_h(uint32_t rs1, int32_t rs2) {
  return __riscv_psrai_h(rs1, 1);
}

// RV32P-LABEL: @psrari_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psrari.h.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psrari_h(uint32_t rs1, int32_t rs2) {
  return __riscv_psrari_h(rs1, 1);
}

// RV32P-LABEL: @srari(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.srari.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t srari(int32_t rs1, int32_t rs2) {
  return __riscv_srari(rs1, 1);
}

// RV32P-LABEL: @psati_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psati.h.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psati_h(uint32_t rs1, int32_t rs2) {
  return __riscv_psati_h(rs1, 1);
}

// RV32P-LABEL: @sati(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sati.i32.i32(i32 [[RS1:%.*]], i32 1)
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t sati(int32_t rs1, int32_t rs2) {
  return __riscv_sati(rs1, 1);
}

// RV32P-LABEL: @psrl_bs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psrl.bs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psrl_bs(uint32_t rs1, uint32_t rs2) {
  return __riscv_psrl_bs(rs1, rs2);
}

// RV32P-LABEL: @psrl_hs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psrl.hs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psrl_hs(uint32_t rs1, uint32_t rs2) {
  return __riscv_psrl_hs(rs1, rs2);
}

// RV32P-LABEL: @predsum_bs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.predsum.bs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t predsum_bs(uint32_t rs1, uint32_t rs2) {
  return __riscv_predsum_bs(rs1, rs2);
}

// RV32P-LABEL: @predsum_hs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.predsum.hs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t predsum_hs(uint32_t rs1, uint32_t rs2) {
  return __riscv_predsum_hs(rs1, rs2);
}

// RV32P-LABEL: @predsumu_bs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.predsumu.bs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t predsumu_bs(uint32_t rs1, uint32_t rs2) {
  return __riscv_predsumu_bs(rs1, rs2);
}

// RV32P-LABEL: @predsumu_hs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.predsumu.hs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t predsumu_hs(uint32_t rs1, uint32_t rs2) {
  return __riscv_predsumu_hs(rs1, rs2);
}

// RV32P-LABEL: @psra_bs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psra.bs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psra_bs(uint32_t rs1, uint32_t rs2) {
  return __riscv_psra_bs(rs1, rs2);
}

// RV32P-LABEL: @psra_hs(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psra.hs.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psra_hs(uint32_t rs1, uint32_t rs2) {
  return __riscv_psra_hs(rs1, rs2);
}

// RV32P-LABEL: @padd_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.padd.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t padd_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_padd_b(rs1, rs2);
}

// RV32P-LABEL: @padd_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.padd.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t padd_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_padd_h(rs1, rs2);
}

// RV32P-LABEL: @sadd(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.sadd.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t sadd(int32_t rs1, int32_t rs2) {
  return __riscv_sadd(rs1, rs2);
}

// RV32P-LABEL: @psadd_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psadd.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psadd_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_psadd_b(rs1, rs2);
}

// RV32P-LABEL: @psadd_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psadd.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psadd_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_psadd_h(rs1, rs2);
}

// RV32P-LABEL: @aadd(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.aadd.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t aadd(int32_t rs1, int32_t rs2) {
  return __riscv_aadd(rs1, rs2);
}

// RV32P-LABEL: @paadd_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.paadd.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t paadd_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_paadd_b(rs1, rs2);
}

// RV32P-LABEL: @paadd_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.paadd.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t paadd_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_paadd_h(rs1, rs2);
}

// RV32P-LABEL: @saddu(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.saddu.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t saddu(uint32_t rs1, uint32_t rs2) {
  return __riscv_saddu(rs1, rs2);
}

// RV32P-LABEL: @psaddu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psaddu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psaddu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_psaddu_b(rs1, rs2);
}

// RV32P-LABEL: @psaddu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psaddu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psaddu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_psaddu_h(rs1, rs2);
}

// RV32P-LABEL: @aaddu(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.aaddu.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t aaddu(uint32_t rs1, uint32_t rs2) {
  return __riscv_aaddu(rs1, rs2);
}

// RV32P-LABEL: @paaddu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.paaddu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t paaddu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_paaddu_b(rs1, rs2);
}

// RV32P-LABEL: @paaddu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.paaddu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t paaddu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_paaddu_h(rs1, rs2);
}

// RV32P-LABEL: @psub_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psub.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psub_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_psub_b(rs1, rs2);
}

// RV32P-LABEL: @psub_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psub.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psub_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_psub_h(rs1, rs2);
}

// RV32P-LABEL: @ssub(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ssub.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t ssub(int32_t rs1, int32_t rs2) {
  return __riscv_ssub(rs1, rs2);
}

// RV32P-LABEL: @pssub_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pssub.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pssub_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pssub_b(rs1, rs2);
}

// RV32P-LABEL: @pssub_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pssub.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pssub_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pssub_h(rs1, rs2);
}

// RV32P-LABEL: @asub(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.asub.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t asub(int32_t rs1, int32_t rs2) {
  return __riscv_asub(rs1, rs2);
}

// RV32P-LABEL: @pasub_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pasub.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pasub_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pasub_b(rs1, rs2);
}

// RV32P-LABEL: @pasub_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pasub.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pasub_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pasub_h(rs1, rs2);
}

// RV32P-LABEL: @ssubu(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ssubu.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t ssubu(uint32_t rs1, uint32_t rs2) {
  return __riscv_ssubu(rs1, rs2);
}

// RV32P-LABEL: @pssubu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pssubu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pssubu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pssubu_b(rs1, rs2);
}

// RV32P-LABEL: @pssubu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pssubu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pssubu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pssubu_h(rs1, rs2);
}

// RV32P-LABEL: @asubu(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.asubu.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t asubu(uint32_t rs1, uint32_t rs2) {
  return __riscv_asubu(rs1, rs2);
}

// RV32P-LABEL: @pasubu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pasubu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pasubu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pasubu_b(rs1, rs2);
}

// RV32P-LABEL: @pasubu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pasubu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pasubu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pasubu_h(rs1, rs2);
}

// RV32P-LABEL: @pdif_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pdif.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pdif_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pdif_b(rs1, rs2);
}

// RV32P-LABEL: @pdif_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pdif.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pdif_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pdif_h(rs1, rs2);
}

// RV32P-LABEL: @pdifu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pdifu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pdifu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pdifu_b(rs1, rs2);
}

// RV32P-LABEL: @pdifu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pdifu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pdifu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pdifu_h(rs1, rs2);
}

// RV32P-LABEL: @pmul_h_b01(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmul.h.b01.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmul_h_b01(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmul_h_b01(rs1, rs2);
}

// RV32P-LABEL: @pmulu_h_b01(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulu.h.b01.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulu_h_b01(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulu_h_b01(rs1, rs2);
}

// RV32P-LABEL: @mul_h01(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mul.h01.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mul_h01(uint32_t rs1, uint32_t rs2) {
  return __riscv_mul_h01(rs1, rs2);
}

// RV32P-LABEL: @mulu_h01(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulu.h01.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulu_h01(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulu_h01(rs1, rs2);
}

// RV32P-LABEL: @slx(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.slx.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t slx(uint32_t rs1, uint32_t rs2) {
  return __riscv_slx(rs1, rs2);
}

// RV32P-LABEL: @psh1add_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psh1add.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psh1add_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_psh1add_h(rs1, rs2);
}

// RV32P-LABEL: @ssh1sadd(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ssh1sadd.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t ssh1sadd(int32_t rs1, int32_t rs2) {
  return __riscv_ssh1sadd(rs1, rs2);
}

// RV32P-LABEL: @pssh1sadd_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pssh1sadd.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pssh1sadd_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pssh1sadd_h(rs1, rs2);
}

// RV32P-LABEL: @pmul_h_b00(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmul.h.b00.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmul_h_b00(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmul_h_b00(rs1, rs2);
}

// RV32P-LABEL: @pmul_h_b11(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmul.h.b11.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmul_h_b11(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmul_h_b11(rs1, rs2);
}

// RV32P-LABEL: @pmulu_h_b00(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulu.h.b00.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulu_h_b00(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulu_h_b00(rs1, rs2);
}

// RV32P-LABEL: @pmulu_h_b11(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulu.h.b11.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulu_h_b11(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulu_h_b11(rs1, rs2);
}

// RV32P-LABEL: @pmulsu_h_b00(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulsu.h.b00.i32.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulsu_h_b00(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulsu_h_b00(rs1, rs2);
}

// RV32P-LABEL: @pmulsu_h_b11(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulsu.h.b11.i32.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulsu_h_b11(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulsu_h_b11(rs1, rs2);
}

// RV32P-LABEL: @mul_h00(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mul.h00.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mul_h00(uint32_t rs1, uint32_t rs2) {
  return __riscv_mul_h00(rs1, rs2);
}

// RV32P-LABEL: @mul_h11(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mul.h11.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mul_h11(uint32_t rs1, uint32_t rs2) {
  return __riscv_mul_h11(rs1, rs2);
}

// RV32P-LABEL: @mulu_h00(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulu.h00.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulu_h00(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulu_h00(rs1, rs2);
}

// RV32P-LABEL: @mulu_h11(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulu.h11.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulu_h11(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulu_h11(rs1, rs2);
}

// RV32P-LABEL: @mulsu_h00(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulsu.h00.i32.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulsu_h00(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulsu_h00(rs1, rs2);
}

// RV32P-LABEL: @mulsu_h11(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulsu.h11.i32.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulsu_h11(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulsu_h11(rs1, rs2);
}

// RV32P-LABEL: @ppack_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ppack.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t ppack_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_ppack_h(rs1, rs2);
}

// RV32P-LABEL: @ppackbt_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ppackbt.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t ppackbt_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_ppackbt_h(rs1, rs2);
}

// RV32P-LABEL: @packbt(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.packbt.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t packbt(int32_t rs1, int32_t rs2) {
  return __riscv_packbt(rs1, rs2);
}

// RV32P-LABEL: @ppacktb_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ppacktb.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t ppacktb_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_ppacktb_h(rs1, rs2);
}

// RV32P-LABEL: @packtb(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.packtb.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t packtb(int32_t rs1, int32_t rs2) {
  return __riscv_packtb(rs1, rs2);
}

// RV32P-LABEL: @ppackt_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.ppackt.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t ppackt_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_ppackt_h(rs1, rs2);
}

// RV32P-LABEL: @packt(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.packt.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t packt(int32_t rs1, int32_t rs2) {
  return __riscv_packt(rs1, rs2);
}

// RV32P-LABEL: @pas_hx(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pas.hx.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pas_hx(uint32_t rs1, uint32_t rs2) {
  return __riscv_pas_hx(rs1, rs2);
}

// RV32P-LABEL: @psa_hx(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psa.hx.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psa_hx(uint32_t rs1, uint32_t rs2) {
  return __riscv_psa_hx(rs1, rs2);
}

// RV32P-LABEL: @psas_hx(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.psas.hx.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t psas_hx(uint32_t rs1, uint32_t rs2) {
  return __riscv_psas_hx(rs1, rs2);
}

// RV32P-LABEL: @pssa_hx(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pssa.hx.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pssa_hx(uint32_t rs1, uint32_t rs2) {
  return __riscv_pssa_hx(rs1, rs2);
}

// RV32P-LABEL: @paas_hx(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.paas.hx.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t paas_hx(uint32_t rs1, uint32_t rs2) {
  return __riscv_paas_hx(rs1, rs2);
}

// RV32P-LABEL: @pasa_hx(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pasa.hx.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pasa_hx(uint32_t rs1, uint32_t rs2) {
  return __riscv_pasa_hx(rs1, rs2);
}

// RV32P-LABEL: @mseq(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mseq.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t mseq(int32_t rs1, int32_t rs2) {
  return __riscv_mseq(rs1, rs2);
}

// RV32P-LABEL: @pmseq_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmseq.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmseq_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmseq_b(rs1, rs2);
}

// RV32P-LABEL: @pmseq_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmseq.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmseq_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmseq_h(rs1, rs2);
}

// RV32P-LABEL: @mslt(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mslt.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t mslt(int32_t rs1, int32_t rs2) {
  return __riscv_mslt(rs1, rs2);
}

// RV32P-LABEL: @pmslt_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmslt.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmslt_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmslt_b(rs1, rs2);
}

// RV32P-LABEL: @pmslt_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmslt.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmslt_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmslt_h(rs1, rs2);
}

// RV32P-LABEL: @msltu(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.msltu.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t msltu(uint32_t rs1, uint32_t rs2) {
  return __riscv_msltu(rs1, rs2);
}

// RV32P-LABEL: @pmsltu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmsltu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmsltu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmsltu_b(rs1, rs2);
}

// RV32P-LABEL: @pmsltu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmsltu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmsltu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmsltu_h(rs1, rs2);
}

// RV32P-LABEL: @pmin_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmin.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmin_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmin_b(rs1, rs2);
}

// RV32P-LABEL: @pmin_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmin.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmin_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmin_h(rs1, rs2);
}

// RV32P-LABEL: @pminu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pminu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pminu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pminu_b(rs1, rs2);
}

// RV32P-LABEL: @pminu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pminu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pminu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pminu_h(rs1, rs2);
}

// RV32P-LABEL: @pmax_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmax.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmax_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmax_b(rs1, rs2);
}

// RV32P-LABEL: @pmax_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmax.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmax_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmax_h(rs1, rs2);
}

// RV32P-LABEL: @pmaxu_b(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmaxu.b.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmaxu_b(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmaxu_b(rs1, rs2);
}

// RV32P-LABEL: @pmaxu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmaxu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmaxu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmaxu_h(rs1, rs2);
}

// RV32P-LABEL: @pmulh_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulh.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulh_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulh_h(rs1, rs2);
}

// RV32P-LABEL: @pmulh_h_b0(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulh.h.b0.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulh_h_b0(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulh_h_b0(rs1, rs2);
}

// RV32P-LABEL: @pmulh_h_b1(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulh.h.b1.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulh_h_b1(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulh_h_b1(rs1, rs2);
}

// RV32P-LABEL: @pmulhu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulhu.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulhu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulhu_h(rs1, rs2);
}

// RV32P-LABEL: @pmulhr_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulhr.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulhr_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulhr_h(rs1, rs2);
}

// RV32P-LABEL: @pmulhru_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulhru.h.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulhru_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulhru_h(rs1, rs2);
}

// RV32P-LABEL: @pmulhsu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulhsu.h.i32.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulhsu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulhsu_h(rs1, rs2);
}

// RV32P-LABEL: @pmulhsu_h_b0(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulhsu.h.b0.i32.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulhsu_h_b0(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulhsu_h_b0(rs1, rs2);
}

// RV32P-LABEL: @pmulhsu_h_b1(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulhsu.h.b1.i32.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulhsu_h_b1(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulhsu_h_b1(rs1, rs2);
}

// RV32P-LABEL: @pmulhrsu_h(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.pmulhrsu.h.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t pmulhrsu_h(uint32_t rs1, uint32_t rs2) {
  return __riscv_pmulhrsu_h(rs1, rs2);
}

// RV32P-LABEL: @mulh_h1(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulh.h1.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulh_h1(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulh_h1(rs1, rs2);
}

// RV32P-LABEL: @mulhr(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhr.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
int32_t mulhr(int32_t rs1, int32_t rs2) {
  return __riscv_mulhr(rs1, rs2);
}

// RV32P-LABEL: @mulhru(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhru.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulhru(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulhru(rs1, rs2);
}

// RV32P-LABEL: @mulh_h0(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulh.h0.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulh_h0(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulh_h0(rs1, rs2);
}

// RV32P-LABEL: @mulhsu_h0(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhsu.h0.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulhsu_h0(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulhsu_h0(rs1, rs2);
}

// RV32P-LABEL: @mulhsu_h1(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhsu.h1.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulhsu_h1(uint32_t rs1, uint32_t rs2) {
  return __riscv_mulhsu_h1(rs1, rs2);
}

// RV32P-LABEL: @mulhrsu(
// RV32P-NEXT:  entry:
// RV32P-NEXT:    [[TMP0:%.*]] = call i32 @llvm.riscv.mulhrsu.i32.i32(i32 [[RS1:%.*]], i32 [[RS2:%.*]])
// RV32P-NEXT:    ret i32 [[TMP0]]
//
uint32_t mulhrsu(uint32_t rs1, int32_t rs2) {
  return __riscv_mulhrsu(rs1, rs2);
}
