; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "^middle.block:" --version 4
; RUN: opt -mtriple=riscv64-none-linux-gnu -S --passes=loop-vectorize -tail-folding-policy=must-fold-tail -force-tail-folding-style=data-and-control \
; RUN:     -enable-wide-lane-mask=disable -force-vector-interleave=2 < %s | FileCheck %s -check-prefix CHECK-ALM
; RUN: opt -mtriple=riscv64-none-linux-gnu -S --passes=loop-vectorize -tail-folding-policy=must-fold-tail -force-tail-folding-style=data-and-control \
; RUN:     -enable-wide-lane-mask=default -force-vector-interleave=2 < %s | FileCheck %s -check-prefix CHECK-ALM
; RUN: opt -mtriple=riscv64-none-linux-gnu -S --passes=loop-vectorize -tail-folding-policy=must-fold-tail -force-tail-folding-style=data-and-control \
; RUN:     -enable-wide-lane-mask=force -force-vector-interleave=2 < %s | FileCheck %s -check-prefix CHECK-WIDE-ALM

define void @scalable_wide_active_lane_mask(ptr noalias %dst, ptr readonly %src, i64 %n) #0 {
; CHECK-ALM-LABEL: define void @scalable_wide_active_lane_mask(
; CHECK-ALM-SAME: ptr noalias [[DST:%.*]], ptr readonly [[SRC:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-ALM-NEXT:  entry:
; CHECK-ALM-NEXT:    br label [[VECTOR_PH:%.*]]
; CHECK-ALM:       vector.ph:
; CHECK-ALM-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-ALM-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-ALM-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; CHECK-ALM-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 0, i64 [[N]])
; CHECK-ALM-NEXT:    [[ACTIVE_LANE_MASK_ENTRY1:%.*]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP1]], i64 [[N]])
; CHECK-ALM-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-ALM:       vector.body:
; CHECK-ALM-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-ALM-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY]], [[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-ALM-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = phi <vscale x 4 x i1> [ [[ACTIVE_LANE_MASK_ENTRY1]], [[VECTOR_PH]] ], [ [[ACTIVE_LANE_MASK_NEXT4:%.*]], [[VECTOR_BODY]] ]
; CHECK-ALM-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[INDEX]]
; CHECK-ALM-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 [[TMP1]]
; CHECK-ALM-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP3]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i32> poison)
; CHECK-ALM-NEXT:    [[WIDE_MASKED_LOAD3:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP4]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]], <vscale x 4 x i32> poison)
; CHECK-ALM-NEXT:    [[TMP5:%.*]] = mul <vscale x 4 x i32> [[WIDE_MASKED_LOAD]], splat (i32 3)
; CHECK-ALM-NEXT:    [[TMP6:%.*]] = mul <vscale x 4 x i32> [[WIDE_MASKED_LOAD3]], splat (i32 3)
; CHECK-ALM-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; CHECK-ALM-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i64 [[TMP1]]
; CHECK-ALM-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP5]], ptr align 4 [[TMP7]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-ALM-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP6]], ptr align 4 [[TMP8]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK2]])
; CHECK-ALM-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-ALM-NEXT:    [[TMP9:%.*]] = add i64 [[INDEX_NEXT]], [[TMP1]]
; CHECK-ALM-NEXT:    [[ACTIVE_LANE_MASK_NEXT]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[INDEX_NEXT]], i64 [[N]])
; CHECK-ALM-NEXT:    [[ACTIVE_LANE_MASK_NEXT4]] = call <vscale x 4 x i1> @llvm.get.active.lane.mask.nxv4i1.i64(i64 [[TMP9]], i64 [[N]])
; CHECK-ALM-NEXT:    [[TMP10:%.*]] = extractelement <vscale x 4 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0
; CHECK-ALM-NEXT:    [[TMP11:%.*]] = xor i1 [[TMP10]], true
; CHECK-ALM-NEXT:    br i1 [[TMP11]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-ALM:       middle.block:
;
; CHECK-WIDE-ALM-LABEL: define void @scalable_wide_active_lane_mask(
; CHECK-WIDE-ALM-SAME: ptr noalias [[DST:%.*]], ptr readonly [[SRC:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-WIDE-ALM-NEXT:  entry:
; CHECK-WIDE-ALM-NEXT:    br label [[VECTOR_PH:%.*]]
; CHECK-WIDE-ALM:       vector.ph:
; CHECK-WIDE-ALM-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-WIDE-ALM-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-WIDE-ALM-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP1]], 1
; CHECK-WIDE-ALM-NEXT:    [[ACTIVE_LANE_MASK_ENTRY:%.*]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 0, i64 [[N]])
; CHECK-WIDE-ALM-NEXT:    [[TMP3:%.*]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK_ENTRY]], i64 4)
; CHECK-WIDE-ALM-NEXT:    [[TMP4:%.*]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK_ENTRY]], i64 0)
; CHECK-WIDE-ALM-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-WIDE-ALM:       vector.body:
; CHECK-WIDE-ALM-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-WIDE-ALM-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = phi <vscale x 4 x i1> [ [[TMP4]], [[VECTOR_PH]] ], [ [[TMP12:%.*]], [[VECTOR_BODY]] ]
; CHECK-WIDE-ALM-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = phi <vscale x 4 x i1> [ [[TMP3]], [[VECTOR_PH]] ], [ [[TMP11:%.*]], [[VECTOR_BODY]] ]
; CHECK-WIDE-ALM-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[SRC]], i64 [[INDEX]]
; CHECK-WIDE-ALM-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[TMP1]]
; CHECK-WIDE-ALM-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP5]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]], <vscale x 4 x i32> poison)
; CHECK-WIDE-ALM-NEXT:    [[WIDE_MASKED_LOAD2:%.*]] = call <vscale x 4 x i32> @llvm.masked.load.nxv4i32.p0(ptr align 4 [[TMP6]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK1]], <vscale x 4 x i32> poison)
; CHECK-WIDE-ALM-NEXT:    [[TMP7:%.*]] = mul <vscale x 4 x i32> [[WIDE_MASKED_LOAD]], splat (i32 3)
; CHECK-WIDE-ALM-NEXT:    [[TMP8:%.*]] = mul <vscale x 4 x i32> [[WIDE_MASKED_LOAD2]], splat (i32 3)
; CHECK-WIDE-ALM-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[DST]], i64 [[INDEX]]
; CHECK-WIDE-ALM-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP9]], i64 [[TMP1]]
; CHECK-WIDE-ALM-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP7]], ptr align 4 [[TMP9]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK]])
; CHECK-WIDE-ALM-NEXT:    call void @llvm.masked.store.nxv4i32.p0(<vscale x 4 x i32> [[TMP8]], ptr align 4 [[TMP10]], <vscale x 4 x i1> [[ACTIVE_LANE_MASK1]])
; CHECK-WIDE-ALM-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], [[TMP2]]
; CHECK-WIDE-ALM-NEXT:    [[ACTIVE_LANE_MASK_NEXT:%.*]] = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 [[INDEX_NEXT]], i64 [[N]])
; CHECK-WIDE-ALM-NEXT:    [[TMP11]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 4)
; CHECK-WIDE-ALM-NEXT:    [[TMP12]] = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1(<vscale x 8 x i1> [[ACTIVE_LANE_MASK_NEXT]], i64 0)
; CHECK-WIDE-ALM-NEXT:    [[TMP13:%.*]] = extractelement <vscale x 4 x i1> [[TMP12]], i64 0
; CHECK-WIDE-ALM-NEXT:    [[TMP14:%.*]] = xor i1 [[TMP13]], true
; CHECK-WIDE-ALM-NEXT:    br i1 [[TMP14]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-WIDE-ALM:       middle.block:
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %arrayidx1 = getelementptr inbounds i32, ptr %src, i64 %iv
  %ld = load i32, ptr %arrayidx1
  %mul = mul i32 %ld, 3
  %arrayidx2 = getelementptr inbounds i32, ptr %dst, i64 %iv
  store i32 %mul, ptr %arrayidx2
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %n
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret void
}

attributes #0 = { "target-features"="+v" }
