; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -p loop-vectorize -S -mtriple=riscv64 -mattr=+v -prefer-control-flow %s -scalable-vectorization=on -force-vector-width=4| FileCheck %s

define void @conditional_store(ptr %addr, i64 %N, i64 %M) {
; CHECK-LABEL: define void @conditional_store(
; CHECK-SAME: ptr [[ADDR:%.*]], i64 [[N:%.*]], i64 [[M:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[M]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[EVL_BASED_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_EVL_NEXT:%.*]], %[[LOOP_IF_SPLIT:.*]] ]
; CHECK-NEXT:    [[AVL:%.*]] = phi i64 [ [[N]], %[[VECTOR_PH]] ], [ [[AVL_NEXT:%.*]], %[[LOOP_IF_SPLIT]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i64, ptr [[ADDR]], i64 [[EVL_BASED_IV]]
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[TMP1]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP0]])
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <vscale x 4 x i64> [[VP_OP_LOAD]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP7:%.*]] = call <vscale x 4 x i1> @llvm.vp.merge.nxv4i1(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i1> [[TMP2]], <vscale x 4 x i1> zeroinitializer, i32 [[TMP0]])
; CHECK-NEXT:    [[TMP4:%.*]] = freeze <vscale x 4 x i1> [[TMP7]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP4]])
; CHECK-NEXT:    br i1 [[TMP3]], label %[[VECTOR_IF_BB:.*]], label %[[LOOP_IF_SPLIT]]
; CHECK:       [[VECTOR_IF_BB]]:
; CHECK-NEXT:    [[TMP8:%.*]] = add <vscale x 4 x i64> [[VP_OP_LOAD]], splat (i64 1)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP8]], ptr align 8 [[TMP1]], <vscale x 4 x i1> [[TMP2]], i32 [[TMP0]])
; CHECK-NEXT:    br label %[[LOOP_IF_SPLIT]]
; CHECK:       [[LOOP_IF_SPLIT]]:
; CHECK-NEXT:    [[TMP5:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[INDEX_EVL_NEXT]] = add i64 [[TMP5]], [[EVL_BASED_IV]]
; CHECK-NEXT:    [[AVL_NEXT]] = sub nuw i64 [[AVL]], [[TMP5]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[AVL_NEXT]], 0
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.cont ]
  %arrayidx = getelementptr inbounds i64, ptr %addr, i64 %iv
  %2 = load i64, ptr %arrayidx, align 8
  %or.cond.not = icmp eq i64 %2, %M
  br i1 %or.cond.not, label %loop.if, label %loop.cont

loop.if:
  %stored.val = add i64 %2, 1
  store i64 %stored.val, ptr %arrayidx, align 8
  br label %loop.cont

loop.cont:
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, %N
  br i1 %exitcond.not, label %exit, label %loop

exit:
  ret void
}

; Test for control flow along with live-out calculated in the conditional block.
define i64 @conditional_liveout_and_store(ptr %addr, i64 %N, i64 %M) {
; CHECK-LABEL: define i64 @conditional_liveout_and_store(
; CHECK-SAME: ptr [[ADDR:%.*]], i64 [[N:%.*]], i64 [[M:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[VECTOR_PH:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[M]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY1:.*]]
; CHECK:       [[VECTOR_BODY1]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_BODY]] ], [ [[CURRENT_ITERATION_NEXT:%.*]], %[[LOOP_IF_SPLIT:.*]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i64> [ zeroinitializer, %[[VECTOR_BODY]] ], [ [[TMP8:%.*]], %[[LOOP_IF_SPLIT]] ]
; CHECK-NEXT:    [[AVL:%.*]] = phi i64 [ [[N]], %[[VECTOR_BODY]] ], [ [[AVL_NEXT:%.*]], %[[LOOP_IF_SPLIT]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i64, ptr [[ADDR]], i64 [[INDEX]]
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[TMP1]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP0]])
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <vscale x 4 x i64> [[VP_OP_LOAD]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i1> @llvm.vp.merge.nxv4i1(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i1> [[TMP2]], <vscale x 4 x i1> zeroinitializer, i32 [[TMP0]])
; CHECK-NEXT:    [[TMP4:%.*]] = freeze <vscale x 4 x i1> [[TMP5]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP4]])
; CHECK-NEXT:    br i1 [[TMP3]], label %[[VECTOR_IF_BB:.*]], label %[[LOOP_IF_SPLIT]]
; CHECK:       [[VECTOR_IF_BB]]:
; CHECK-NEXT:    [[TMP6:%.*]] = add <vscale x 4 x i64> [[VP_OP_LOAD]], splat (i64 1)
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP6]], ptr align 8 [[TMP1]], <vscale x 4 x i1> [[TMP2]], i32 [[TMP0]])
; CHECK-NEXT:    br label %[[LOOP_IF_SPLIT]]
; CHECK:       [[LOOP_IF_SPLIT]]:
; CHECK-NEXT:    [[TMP7:%.*]] = add <vscale x 4 x i64> [[VEC_PHI]], splat (i64 1)
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP2]], <vscale x 4 x i64> [[TMP7]], <vscale x 4 x i64> [[VEC_PHI]]
; CHECK-NEXT:    [[TMP8]] = call <vscale x 4 x i64> @llvm.vp.merge.nxv4i64(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i64> [[PREDPHI]], <vscale x 4 x i64> [[VEC_PHI]], i32 [[TMP0]])
; CHECK-NEXT:    [[TMP11:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[CURRENT_ITERATION_NEXT]] = add i64 [[TMP11]], [[INDEX]]
; CHECK-NEXT:    [[AVL_NEXT]] = sub nuw i64 [[AVL]], [[TMP11]]
; CHECK-NEXT:    [[TMP10:%.*]] = icmp eq i64 [[AVL_NEXT]], 0
; CHECK-NEXT:    br i1 [[TMP10]], label %[[EXIT:.*]], label %[[VECTOR_BODY1]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[TMP9:%.*]] = call i64 @llvm.vector.reduce.add.nxv4i64(<vscale x 4 x i64> [[TMP8]])
; CHECK-NEXT:    br label %[[EXIT1:.*]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    ret i64 [[TMP9]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.cont ]
  %sum = phi i64 [ 0, %entry ], [ %sum.next, %loop.cont ]
  %arrayidx = getelementptr inbounds i64, ptr %addr, i64 %iv
  %val = load i64, ptr %arrayidx, align 8
  %cond = icmp eq i64 %val, %M
  br i1 %cond, label %loop.if, label %loop.cont

loop.if:
  %new_val = add i64 %val, 1
  store i64 %new_val, ptr %arrayidx, align 8
  %sum.inc = add i64 %sum, 1
  br label %loop.cont

loop.cont:
  %sum.next = phi i64 [ %sum.inc, %loop.if ], [ %sum, %loop ]
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, %N
  br i1 %exitcond, label %exit, label %loop

exit:
  ret i64 %sum.next
}

; Test for control flow with live-out calculated in both paths.
define i64 @conditional_liveout_both_path(ptr %addr, i64 %N, i64 %M) {
; CHECK-LABEL: define i64 @conditional_liveout_both_path(
; CHECK-SAME: ptr [[ADDR:%.*]], i64 [[N:%.*]], i64 [[M:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i64> poison, i64 [[M]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i64> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i64> poison, <vscale x 4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[VAL:%.*]] = phi i64 [ 0, %[[LOOP]] ], [ [[ACC_ELSE:%.*]], %[[LOOP_ELSE:.*]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i64> [ zeroinitializer, %[[LOOP]] ], [ [[TMP9:%.*]], %[[LOOP_ELSE]] ]
; CHECK-NEXT:    [[AVL:%.*]] = phi i64 [ [[N]], %[[LOOP]] ], [ [[AVL_NEXT:%.*]], %[[LOOP_ELSE]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 4, i1 true)
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i64, ptr [[ADDR]], i64 [[VAL]]
; CHECK-NEXT:    [[VP_OP_LOAD:%.*]] = call <vscale x 4 x i64> @llvm.vp.load.nxv4i64.p0(ptr align 8 [[TMP1]], <vscale x 4 x i1> splat (i1 true), i32 [[TMP0]])
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <vscale x 4 x i64> [[VP_OP_LOAD]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP3:%.*]] = add <vscale x 4 x i64> [[VEC_PHI]], [[VP_OP_LOAD]]
; CHECK-NEXT:    [[TMP4:%.*]] = add <vscale x 4 x i64> [[VP_OP_LOAD]], splat (i64 1)
; CHECK-NEXT:    [[TMP5:%.*]] = call <vscale x 4 x i1> @llvm.vp.merge.nxv4i1(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i1> [[TMP2]], <vscale x 4 x i1> zeroinitializer, i32 [[TMP0]])
; CHECK-NEXT:    [[TMP6:%.*]] = freeze <vscale x 4 x i1> [[TMP5]]
; CHECK-NEXT:    [[COND:%.*]] = call i1 @llvm.vector.reduce.or.nxv4i1(<vscale x 4 x i1> [[TMP6]])
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP_IF:.*]], label %[[LOOP_ELSE]]
; CHECK:       [[LOOP_IF]]:
; CHECK-NEXT:    call void @llvm.vp.store.nxv4i64.p0(<vscale x 4 x i64> [[TMP4]], ptr align 8 [[TMP1]], <vscale x 4 x i1> [[TMP2]], i32 [[TMP0]])
; CHECK-NEXT:    br label %[[LOOP_ELSE]]
; CHECK:       [[LOOP_ELSE]]:
; CHECK-NEXT:    [[TMP8:%.*]] = add <vscale x 4 x i64> [[VEC_PHI]], [[TMP4]]
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <vscale x 4 x i1> [[TMP2]], <vscale x 4 x i64> [[TMP8]], <vscale x 4 x i64> [[TMP3]]
; CHECK-NEXT:    [[TMP9]] = call <vscale x 4 x i64> @llvm.vp.merge.nxv4i64(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i64> [[PREDPHI]], <vscale x 4 x i64> [[VEC_PHI]], i32 [[TMP0]])
; CHECK-NEXT:    [[ACC:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-NEXT:    [[ACC_ELSE]] = add i64 [[ACC]], [[VAL]]
; CHECK-NEXT:    [[AVL_NEXT]] = sub nuw i64 [[AVL]], [[ACC]]
; CHECK-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[AVL_NEXT]], 0
; CHECK-NEXT:    br i1 [[TMP11]], label %[[LOOP_CONT:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[LOOP_CONT]]:
; CHECK-NEXT:    [[ACC_NEXT_LCSSA:%.*]] = call i64 @llvm.vector.reduce.add.nxv4i64(<vscale x 4 x i64> [[TMP9]])
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret i64 [[ACC_NEXT_LCSSA]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop.cont ]
  %acc = phi i64 [ 0, %entry ], [ %acc.next, %loop.cont ]
  %arrayidx = getelementptr inbounds i64, ptr %addr, i64 %iv
  %val = load i64, ptr %arrayidx, align 8
  %cond = icmp eq i64 %val, %M
  br i1 %cond, label %loop.if, label %loop.else

loop.if:
  %new_val = add i64 %val, 1
  store i64 %new_val, ptr %arrayidx, align 8
  %acc.if = add i64 %acc, %new_val
  br label %loop.cont

loop.else:
  %acc.else = add i64 %acc, %val
  br label %loop.cont

loop.cont:
  %acc.next = phi i64 [ %acc.if, %loop.if ], [ %acc.else, %loop.else ]
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond = icmp eq i64 %iv.next, %N
  br i1 %exitcond, label %exit, label %loop

exit:
  ret i64 %acc.next
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META1]], [[META2]]}
; CHECK: [[LOOP4]] = distinct !{[[LOOP4]], [[META1]], [[META2]]}
;.
