; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -p loop-vectorize -mattr=+v -S %s | FileCheck %s

target triple = "riscv32-unknown-linux-gnu"

; Test case for https://github.com/llvm/llvm-project/issues/175909.
define void @test_vp_load_store_cost(ptr %A, ptr %B) {
; CHECK-LABEL: define void @test_vp_load_store_cost(
; CHECK-SAME: ptr [[A:%.*]], ptr [[B:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PTR_IV_0:%.*]] = phi ptr [ [[A]], %[[ENTRY]] ], [ [[PTR_IV_0_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR_IV_1:%.*]] = phi ptr [ [[B]], %[[ENTRY]] ], [ [[PTR_IV_1_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[PTR_IV_0_NEXT]] = getelementptr i8, ptr [[PTR_IV_0]], i32 -16
; CHECK-NEXT:    [[PTR_IV_1_NEXT]] = getelementptr i8, ptr [[PTR_IV_1]], i32 -16
; CHECK-NEXT:    [[L:%.*]] = load double, ptr [[PTR_IV_0_NEXT]], align 8
; CHECK-NEXT:    store double [[L]], ptr [[PTR_IV_1_NEXT]], align 8
; CHECK-NEXT:    [[PTR_IV_1_8:%.*]] = getelementptr i8, ptr [[PTR_IV_1]], i32 -8
; CHECK-NEXT:    store i64 0, ptr [[PTR_IV_1_8]], align 8
; CHECK-NEXT:    [[EC:%.*]] = icmp eq ptr [[B]], [[PTR_IV_0_NEXT]]
; CHECK-NEXT:    br i1 [[EC]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %ptr.iv.0 = phi ptr [ %A, %entry ], [ %ptr.iv.0.next, %loop ]
  %ptr.iv.1 = phi ptr [ %B, %entry ], [ %ptr.iv.1.next, %loop ]
  %ptr.iv.0.next = getelementptr i8, ptr %ptr.iv.0, i32 -16
  %ptr.iv.1.next = getelementptr i8, ptr %ptr.iv.1, i32 -16
  %l = load double, ptr %ptr.iv.0.next, align 8
  store double %l, ptr %ptr.iv.1.next, align 8
  %ptr.iv.1.8 = getelementptr i8, ptr %ptr.iv.1, i32 -8
  store i64 0, ptr %ptr.iv.1.8, align 8
  %ec = icmp eq ptr %B, %ptr.iv.0.next
  br i1 %ec, label %exit, label %loop

exit:
  ret void
}
