; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -p loop-vectorize -mtriple riscv64 -mattr=+v,+zvl1024b < %s -S | FileCheck %s

define void @foo(i32 %0, ptr %p) {
; CHECK-LABEL: define void @foo(
; CHECK-SAME: i32 [[TMP0:%.*]], ptr [[P:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i32 [[TMP0]], 308
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i32 [[TMP0]], 309
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i32 [[TMP0]], 160
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq i32 [[TMP0]], 243
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i32 [[TMP0]], 53
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i32 [[TMP0]], 162
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[TMP0]], 161
; CHECK-NEXT:    [[TMP8:%.*]] = icmp eq i32 [[TMP0]], 172
; CHECK-NEXT:    [[TMP21:%.*]] = icmp eq i32 [[TMP0]], 159
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 8 x i1> poison, i1 [[TMP21]], i64 0
; CHECK-NEXT:    [[TMP9:%.*]] = shufflevector <vscale x 8 x i1> [[BROADCAST_SPLATINSERT1]], <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP10:%.*]] = or i1 [[TMP1]], [[TMP2]]
; CHECK-NEXT:    [[TMP11:%.*]] = or i1 [[TMP10]], [[TMP3]]
; CHECK-NEXT:    [[TMP12:%.*]] = or i1 [[TMP11]], [[TMP4]]
; CHECK-NEXT:    [[TMP13:%.*]] = or i1 [[TMP12]], [[TMP5]]
; CHECK-NEXT:    [[TMP14:%.*]] = or i1 [[TMP13]], [[TMP6]]
; CHECK-NEXT:    [[TMP15:%.*]] = or i1 [[TMP14]], [[TMP7]]
; CHECK-NEXT:    [[TMP22:%.*]] = or i1 [[TMP15]], [[TMP8]]
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i1> poison, i1 [[TMP22]], i64 0
; CHECK-NEXT:    [[TMP16:%.*]] = shufflevector <vscale x 8 x i1> [[BROADCAST_SPLATINSERT]], <vscale x 8 x i1> poison, <vscale x 8 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP17:%.*]] = or <vscale x 8 x i1> [[TMP16]], [[TMP9]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[CURRENT_ITERATION_IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[CURRENT_ITERATION_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[AVL:%.*]] = phi i64 [ 524, %[[VECTOR_PH]] ], [ [[AVL_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP18:%.*]] = call i32 @llvm.experimental.get.vector.length.i64(i64 [[AVL]], i32 8, i1 true)
; CHECK-NEXT:    [[TMP19:%.*]] = call <vscale x 8 x i1> @llvm.vp.merge.nxv8i1(<vscale x 8 x i1> splat (i1 true), <vscale x 8 x i1> [[TMP17]], <vscale x 8 x i1> zeroinitializer, i32 [[TMP18]])
; CHECK-NEXT:    [[TMP20:%.*]] = xor <vscale x 8 x i1> [[TMP19]], splat (i1 true)
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr i8, ptr [[P]], i64 [[CURRENT_ITERATION_IV]]
; CHECK-NEXT:    call void @llvm.vp.store.nxv8i8.p0(<vscale x 8 x i8> zeroinitializer, ptr align 1 [[TMP23]], <vscale x 8 x i1> [[TMP20]], i32 [[TMP18]])
; CHECK-NEXT:    [[TMP24:%.*]] = zext i32 [[TMP18]] to i64
; CHECK-NEXT:    [[CURRENT_ITERATION_NEXT]] = add nuw i64 [[TMP24]], [[CURRENT_ITERATION_IV]]
; CHECK-NEXT:    [[AVL_NEXT]] = sub nuw i64 [[AVL]], [[TMP24]]
; CHECK-NEXT:    [[TMP25:%.*]] = icmp eq i64 [[AVL_NEXT]], 0
; CHECK-NEXT:    br i1 [[TMP25]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

exit:
  ret void

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %exiting ]
  switch i32 %0, label %loop.split [
  i32 308, label %exiting
  i32 309, label %exiting
  i32 160, label %exiting
  i32 243, label %exiting
  i32 53, label %exiting
  i32 162, label %exiting
  i32 161, label %exiting
  i32 172, label %exiting
  i32 159, label %exiting
  ]

loop.split:
  %arridx = getelementptr i8, ptr %p, i64 %iv
  store i8 0, ptr %arridx, align 1
  br label %exiting

exiting:
  %iv.next = add i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv, 523
  br i1 %exitcond.not, label %exit, label %loop
}
