; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=vector-combine,dce,vector-combine -mtriple=arm64-apple-darwinos -S %s | FileCheck %s

define noundef i32 @load_ext_extract(ptr %src) {
; CHECK-LABEL: define noundef i32 @load_ext_extract(
; CHECK-SAME: ptr [[SRC:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[SRC]], align 4
; CHECK-NEXT:    [[TMP15:%.*]] = lshr i32 [[TMP14]], 24
; CHECK-NEXT:    [[TMP16:%.*]] = lshr i32 [[TMP14]], 16
; CHECK-NEXT:    [[TMP17:%.*]] = and i32 [[TMP16]], 255
; CHECK-NEXT:    [[TMP18:%.*]] = lshr i32 [[TMP14]], 8
; CHECK-NEXT:    [[TMP19:%.*]] = and i32 [[TMP18]], 255
; CHECK-NEXT:    [[TMP20:%.*]] = and i32 [[TMP14]], 255
; CHECK-NEXT:    [[ADD1:%.*]] = add i32 [[TMP20]], [[TMP19]]
; CHECK-NEXT:    [[ADD2:%.*]] = add i32 [[ADD1]], [[TMP17]]
; CHECK-NEXT:    [[ADD3:%.*]] = add i32 [[ADD2]], [[TMP15]]
; CHECK-NEXT:    ret i32 [[ADD3]]
;
entry:
  %x = load <4 x i8>, ptr %src, align 4
  %ext = zext nneg <4 x i8> %x to <4 x i32>
  %ext.0 = extractelement <4 x i32> %ext, i64 0
  %ext.1 = extractelement <4 x i32> %ext, i64 1
  %ext.2 = extractelement <4 x i32> %ext, i64 2
  %ext.3 = extractelement <4 x i32> %ext, i64 3

  %add1 = add i32 %ext.0, %ext.1
  %add2 = add i32 %add1, %ext.2
  %add3 = add i32 %add2, %ext.3
  ret i32 %add3
}
