; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -mattr=+wavefrontsize64 -verify-machineinstrs -stop-after=finalize-isel -amdgpu-late-wave-transform=1 < %s | FileCheck -check-prefixes=GFX90A %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -verify-machineinstrs -stop-after=finalize-isel -amdgpu-late-wave-transform=1 < %s | FileCheck -check-prefixes=GFX1200 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1200 -verify-machineinstrs -stop-after=finalize-isel -amdgpu-late-wave-transform=1 < %s | FileCheck -check-prefixes=GISEL %s

; __global__ void switch_i1(int *filter,  int *out) {
;  int id = __builtin_amdgcn_workitem_id_x();
;  bool sel = false;
;  int x = filter[id];
;  switch (id) {
;  case 0:
;    sel |= x > 3;
;  case 1:
;    sel |= x > 5;
;  case 2:
;    sel |= x > 7;
;    break;
;  default:
;    sel |= x > 11;
;  }
;  if (sel)
;    out[id] = x;
; }
define amdgpu_kernel void @switch_i1(ptr addrspace(1) %filter.coerce, ptr addrspace(1) %out.coerce) {
  ; GFX90A-LABEL: name: switch_i1
  ; GFX90A: bb.0.entry:
  ; GFX90A-NEXT:   successors: %bb.1(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0, $sgpr8_sgpr9
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[COPY:%[0-9]+]]:sgpr_64(p4) = COPY $sgpr8_sgpr9
  ; GFX90A-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32(s32) = COPY $vgpr0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1.NodeBlock4:
  ; GFX90A-NEXT:   successors: %bb.4(0x30000000), %bb.2(0x50000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[COPY]](p4), 0, 0 :: (dereferenceable invariant load (s128) from %ir.filter.coerce.kernarg.offset1, addrspace 4)
  ; GFX90A-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub1
  ; GFX90A-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub0
  ; GFX90A-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:sreg_64_xexec_xnull = REG_SEQUENCE killed [[COPY3]], %subreg.sub0, killed [[COPY2]], %subreg.sub1
  ; GFX90A-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1023
  ; GFX90A-NEXT:   [[V_AND_B32_e64_:%[0-9]+]]:vgpr_32 = V_AND_B32_e64 [[COPY1]](s32), killed [[S_MOV_B32_]], implicit $exec
  ; GFX90A-NEXT:   [[COPY4:%[0-9]+]]:vgpr_32 = COPY [[V_AND_B32_e64_]]
  ; GFX90A-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; GFX90A-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:vreg_64_align2 = REG_SEQUENCE [[V_AND_B32_e64_]], %subreg.sub0, killed [[V_MOV_B32_e32_]], %subreg.sub1
  ; GFX90A-NEXT:   [[COPY5:%[0-9]+]]:av_64_align2 = COPY [[REG_SEQUENCE1]]
  ; GFX90A-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX90A-NEXT:   [[V_LSHLREV_B32_e64_:%[0-9]+]]:vgpr_32 = nuw nsw V_LSHLREV_B32_e64 killed [[S_MOV_B32_1]], [[V_AND_B32_e64_]], implicit $exec
  ; GFX90A-NEXT:   [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR killed [[REG_SEQUENCE]], killed [[V_LSHLREV_B32_e64_]], 0, 0, implicit $exec :: (load (s32) from %ir.arrayidx, addrspace 1)
  ; GFX90A-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GFX90A-NEXT:   [[V_CMP_LT_I32_e64_:%[0-9]+]]:sreg_64 = V_CMP_LT_I32_e64 [[V_AND_B32_e64_]], killed [[S_MOV_B32_2]], implicit $exec
  ; GFX90A-NEXT:   SI_BRCOND %bb.4, killed [[V_CMP_LT_I32_e64_]]
  ; GFX90A-NEXT:   S_BRANCH %bb.2
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2.NodeBlock:
  ; GFX90A-NEXT:   successors: %bb.5(0x40000000), %bb.3(0x40000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX90A-NEXT:   [[V_CMP_LT_I32_e64_1:%[0-9]+]]:sreg_64 = V_CMP_LT_I32_e64 [[COPY4]], killed [[S_MOV_B32_3]], implicit $exec
  ; GFX90A-NEXT:   [[S_MOV_B64_:%[0-9]+]]:sreg_64_xexec = S_MOV_B64 0
  ; GFX90A-NEXT:   [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_MOV_B64_]], implicit $exec
  ; GFX90A-NEXT:   SI_BRCOND %bb.5, killed [[V_CMP_LT_I32_e64_1]]
  ; GFX90A-NEXT:   S_BRANCH %bb.3
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.3.LeafBlock:
  ; GFX90A-NEXT:   successors: %bb.6(0x40000000), %bb.7(0x40000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[S_MOV_B32_4:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX90A-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_64 = V_CMP_EQ_U32_e64 [[COPY4]], killed [[S_MOV_B32_4]], implicit $exec
  ; GFX90A-NEXT:   [[S_MOV_B64_1:%[0-9]+]]:sreg_64_xexec = S_MOV_B64 0
  ; GFX90A-NEXT:   [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_MOV_B64_1]], implicit $exec
  ; GFX90A-NEXT:   SI_BRCOND %bb.6, killed [[V_CMP_EQ_U32_e64_]]
  ; GFX90A-NEXT:   S_BRANCH %bb.7
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.4.sw.bb:
  ; GFX90A-NEXT:   successors: %bb.5(0x80000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[S_MOV_B32_5:%[0-9]+]]:sreg_32 = S_MOV_B32 3
  ; GFX90A-NEXT:   [[V_CMP_GT_I32_e64_:%[0-9]+]]:sreg_64_xexec = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_5]], implicit $exec
  ; GFX90A-NEXT:   [[V_CNDMASK_B32_e64_2:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[V_CMP_GT_I32_e64_]], implicit $exec
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.5.sw.bb4:
  ; GFX90A-NEXT:   successors: %bb.6(0x80000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[PHI:%[0-9]+]]:vgpr_32 = PHI [[V_CNDMASK_B32_e64_]], %bb.2, [[V_CNDMASK_B32_e64_2]], %bb.4
  ; GFX90A-NEXT:   [[S_MOV_B32_6:%[0-9]+]]:sreg_32 = S_MOV_B32 5
  ; GFX90A-NEXT:   [[V_CMP_GT_I32_e64_1:%[0-9]+]]:sreg_64 = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_6]], implicit $exec
  ; GFX90A-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_64 = V_CMP_NE_U32_e64 [[PHI]], 0, implicit $exec
  ; GFX90A-NEXT:   [[S_OR_B64_:%[0-9]+]]:sreg_64_xexec = S_OR_B64 killed [[V_CMP_GT_I32_e64_1]], [[V_CMP_NE_U32_e64_]], implicit-def dead $scc
  ; GFX90A-NEXT:   [[V_CNDMASK_B32_e64_3:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_OR_B64_]], implicit $exec
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.6.sw.bb12:
  ; GFX90A-NEXT:   successors: %bb.8(0x80000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[PHI1:%[0-9]+]]:vgpr_32 = PHI [[V_CNDMASK_B32_e64_1]], %bb.3, [[V_CNDMASK_B32_e64_3]], %bb.5
  ; GFX90A-NEXT:   [[S_MOV_B32_7:%[0-9]+]]:sreg_32 = S_MOV_B32 7
  ; GFX90A-NEXT:   [[V_CMP_GT_I32_e64_2:%[0-9]+]]:sreg_64 = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_7]], implicit $exec
  ; GFX90A-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_64 = V_CMP_NE_U32_e64 [[PHI1]], 0, implicit $exec
  ; GFX90A-NEXT:   [[S_OR_B64_1:%[0-9]+]]:sreg_64_xexec = S_OR_B64 killed [[V_CMP_GT_I32_e64_2]], [[V_CMP_NE_U32_e64_1]], implicit-def dead $scc
  ; GFX90A-NEXT:   [[V_CNDMASK_B32_e64_4:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_OR_B64_1]], implicit $exec
  ; GFX90A-NEXT:   S_BRANCH %bb.8
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.7.sw.default:
  ; GFX90A-NEXT:   successors: %bb.8(0x80000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[S_MOV_B32_8:%[0-9]+]]:sreg_32 = S_MOV_B32 11
  ; GFX90A-NEXT:   [[V_CMP_GT_I32_e64_3:%[0-9]+]]:sreg_64_xexec = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_8]], implicit $exec
  ; GFX90A-NEXT:   [[V_CNDMASK_B32_e64_5:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[V_CMP_GT_I32_e64_3]], implicit $exec
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.8.sw.epilog:
  ; GFX90A-NEXT:   successors: %bb.9(0x40000000), %bb.10(0x40000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[PHI2:%[0-9]+]]:vgpr_32 = PHI [[V_CNDMASK_B32_e64_5]], %bb.7, [[V_CNDMASK_B32_e64_4]], %bb.6
  ; GFX90A-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_64_xexec = V_CMP_NE_U32_e64 [[PHI2]], 0, implicit $exec
  ; GFX90A-NEXT:   [[V_CNDMASK_B32_e64_6:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, 1, [[V_CMP_NE_U32_e64_2]], implicit $exec
  ; GFX90A-NEXT:   [[S_MOV_B32_9:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GFX90A-NEXT:   [[V_CMP_NE_U32_e64_3:%[0-9]+]]:sreg_64 = V_CMP_NE_U32_e64 killed [[V_CNDMASK_B32_e64_6]], killed [[S_MOV_B32_9]], implicit $exec
  ; GFX90A-NEXT:   SI_BRCOND %bb.10, killed [[V_CMP_NE_U32_e64_3]]
  ; GFX90A-NEXT:   S_BRANCH %bb.9
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.9.if.then:
  ; GFX90A-NEXT:   successors: %bb.10(0x80000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[COPY6:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub3
  ; GFX90A-NEXT:   [[COPY7:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub2
  ; GFX90A-NEXT:   [[REG_SEQUENCE2:%[0-9]+]]:sreg_64_xexec_xnull = REG_SEQUENCE killed [[COPY7]], %subreg.sub0, killed [[COPY6]], %subreg.sub1
  ; GFX90A-NEXT:   [[COPY8:%[0-9]+]]:vgpr_32 = COPY [[COPY5]].sub0
  ; GFX90A-NEXT:   [[S_MOV_B32_10:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX90A-NEXT:   [[V_LSHLREV_B32_e64_1:%[0-9]+]]:vgpr_32 = nuw nsw V_LSHLREV_B32_e64 killed [[S_MOV_B32_10]], killed [[COPY8]], implicit $exec
  ; GFX90A-NEXT:   GLOBAL_STORE_DWORD_SADDR killed [[V_LSHLREV_B32_e64_1]], [[GLOBAL_LOAD_DWORD_SADDR]], killed [[REG_SEQUENCE2]], 0, 0, implicit $exec :: (store (s32) into %ir.arrayidx29, addrspace 1)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.10.if.end:
  ; GFX90A-NEXT:   S_ENDPGM 0
  ;
  ; GFX1200-LABEL: name: switch_i1
  ; GFX1200: bb.0.entry:
  ; GFX1200-NEXT:   successors: %bb.1(0x80000000)
  ; GFX1200-NEXT:   liveins: $vgpr0, $sgpr4_sgpr5
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[COPY:%[0-9]+]]:sgpr_64(p4) = COPY $sgpr4_sgpr5
  ; GFX1200-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32(s32) = COPY $vgpr0
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.1.NodeBlock4:
  ; GFX1200-NEXT:   successors: %bb.4(0x30000000), %bb.2(0x50000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[COPY]](p4), 0, 0 :: (dereferenceable invariant load (s128) from %ir.filter.coerce.kernarg.offset1, addrspace 4)
  ; GFX1200-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub1
  ; GFX1200-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub0
  ; GFX1200-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:sreg_64_xexec_xnull = REG_SEQUENCE killed [[COPY3]], %subreg.sub0, killed [[COPY2]], %subreg.sub1
  ; GFX1200-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1023
  ; GFX1200-NEXT:   [[V_AND_B32_e64_:%[0-9]+]]:vgpr_32 = V_AND_B32_e64 [[COPY1]](s32), killed [[S_MOV_B32_]], implicit $exec
  ; GFX1200-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; GFX1200-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:vreg_64 = REG_SEQUENCE [[V_AND_B32_e64_]], %subreg.sub0, killed [[V_MOV_B32_e32_]], %subreg.sub1
  ; GFX1200-NEXT:   [[COPY4:%[0-9]+]]:vreg_64 = COPY [[REG_SEQUENCE1]]
  ; GFX1200-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX1200-NEXT:   [[V_LSHLREV_B32_e64_:%[0-9]+]]:vgpr_32 = nuw nsw V_LSHLREV_B32_e64 killed [[S_MOV_B32_1]], [[V_AND_B32_e64_]], implicit $exec
  ; GFX1200-NEXT:   [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR killed [[REG_SEQUENCE]], killed [[V_LSHLREV_B32_e64_]], 0, 0, implicit $exec :: (load (s32) from %ir.arrayidx, addrspace 1)
  ; GFX1200-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GFX1200-NEXT:   [[V_CMP_LT_I32_e64_:%[0-9]+]]:sreg_32 = V_CMP_LT_I32_e64 [[V_AND_B32_e64_]], killed [[S_MOV_B32_2]], implicit $exec
  ; GFX1200-NEXT:   SI_BRCOND %bb.4, killed [[V_CMP_LT_I32_e64_]]
  ; GFX1200-NEXT:   S_BRANCH %bb.2
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.2.NodeBlock:
  ; GFX1200-NEXT:   successors: %bb.5(0x40000000), %bb.3(0x40000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX1200-NEXT:   [[V_CMP_LT_I32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_LT_I32_e64 [[V_AND_B32_e64_]], killed [[S_MOV_B32_3]], implicit $exec
  ; GFX1200-NEXT:   [[S_MOV_B32_4:%[0-9]+]]:sreg_32_xm0_xexec = S_MOV_B32 0
  ; GFX1200-NEXT:   [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_MOV_B32_4]], implicit $exec
  ; GFX1200-NEXT:   SI_BRCOND %bb.5, killed [[V_CMP_LT_I32_e64_1]]
  ; GFX1200-NEXT:   S_BRANCH %bb.3
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.3.LeafBlock:
  ; GFX1200-NEXT:   successors: %bb.6(0x40000000), %bb.7(0x40000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[S_MOV_B32_5:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX1200-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[V_AND_B32_e64_]], killed [[S_MOV_B32_5]], implicit $exec
  ; GFX1200-NEXT:   [[S_MOV_B32_6:%[0-9]+]]:sreg_32_xm0_xexec = S_MOV_B32 0
  ; GFX1200-NEXT:   [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_MOV_B32_6]], implicit $exec
  ; GFX1200-NEXT:   SI_BRCOND %bb.6, killed [[V_CMP_EQ_U32_e64_]]
  ; GFX1200-NEXT:   S_BRANCH %bb.7
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.4.sw.bb:
  ; GFX1200-NEXT:   successors: %bb.5(0x80000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[S_MOV_B32_7:%[0-9]+]]:sreg_32 = S_MOV_B32 3
  ; GFX1200-NEXT:   [[V_CMP_GT_I32_e64_:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_7]], implicit $exec
  ; GFX1200-NEXT:   [[V_CNDMASK_B32_e64_2:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[V_CMP_GT_I32_e64_]], implicit $exec
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.5.sw.bb4:
  ; GFX1200-NEXT:   successors: %bb.6(0x80000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[PHI:%[0-9]+]]:vgpr_32 = PHI [[V_CNDMASK_B32_e64_]], %bb.2, [[V_CNDMASK_B32_e64_2]], %bb.4
  ; GFX1200-NEXT:   [[S_MOV_B32_8:%[0-9]+]]:sreg_32 = S_MOV_B32 5
  ; GFX1200-NEXT:   [[V_CMP_GT_I32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_8]], implicit $exec
  ; GFX1200-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[PHI]], 0, implicit $exec
  ; GFX1200-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_OR_B32 killed [[V_CMP_GT_I32_e64_1]], [[V_CMP_NE_U32_e64_]], implicit-def dead $scc
  ; GFX1200-NEXT:   [[V_CNDMASK_B32_e64_3:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_OR_B32_]], implicit $exec
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.6.sw.bb12:
  ; GFX1200-NEXT:   successors: %bb.8(0x80000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[PHI1:%[0-9]+]]:vgpr_32 = PHI [[V_CNDMASK_B32_e64_1]], %bb.3, [[V_CNDMASK_B32_e64_3]], %bb.5
  ; GFX1200-NEXT:   [[S_MOV_B32_9:%[0-9]+]]:sreg_32 = S_MOV_B32 7
  ; GFX1200-NEXT:   [[V_CMP_GT_I32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_9]], implicit $exec
  ; GFX1200-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[PHI1]], 0, implicit $exec
  ; GFX1200-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_OR_B32 killed [[V_CMP_GT_I32_e64_2]], [[V_CMP_NE_U32_e64_1]], implicit-def dead $scc
  ; GFX1200-NEXT:   [[V_CNDMASK_B32_e64_4:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[S_OR_B32_1]], implicit $exec
  ; GFX1200-NEXT:   S_BRANCH %bb.8
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.7.sw.default:
  ; GFX1200-NEXT:   successors: %bb.8(0x80000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[S_MOV_B32_10:%[0-9]+]]:sreg_32 = S_MOV_B32 11
  ; GFX1200-NEXT:   [[V_CMP_GT_I32_e64_3:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], killed [[S_MOV_B32_10]], implicit $exec
  ; GFX1200-NEXT:   [[V_CNDMASK_B32_e64_5:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, -1, [[V_CMP_GT_I32_e64_3]], implicit $exec
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.8.sw.epilog:
  ; GFX1200-NEXT:   successors: %bb.9(0x40000000), %bb.10(0x40000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[PHI2:%[0-9]+]]:vgpr_32 = PHI [[V_CNDMASK_B32_e64_5]], %bb.7, [[V_CNDMASK_B32_e64_4]], %bb.6
  ; GFX1200-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_NE_U32_e64 [[PHI2]], 0, implicit $exec
  ; GFX1200-NEXT:   [[V_CNDMASK_B32_e64_6:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 0, 0, 1, [[V_CMP_NE_U32_e64_2]], implicit $exec
  ; GFX1200-NEXT:   [[S_MOV_B32_11:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GFX1200-NEXT:   [[V_CMP_NE_U32_e64_3:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 killed [[V_CNDMASK_B32_e64_6]], killed [[S_MOV_B32_11]], implicit $exec
  ; GFX1200-NEXT:   SI_BRCOND %bb.10, killed [[V_CMP_NE_U32_e64_3]]
  ; GFX1200-NEXT:   S_BRANCH %bb.9
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.9.if.then:
  ; GFX1200-NEXT:   successors: %bb.10(0x80000000)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT:   [[COPY5:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub3
  ; GFX1200-NEXT:   [[COPY6:%[0-9]+]]:sreg_32 = COPY [[S_LOAD_DWORDX4_IMM]].sub2
  ; GFX1200-NEXT:   [[REG_SEQUENCE2:%[0-9]+]]:sreg_64_xexec_xnull = REG_SEQUENCE killed [[COPY6]], %subreg.sub0, killed [[COPY5]], %subreg.sub1
  ; GFX1200-NEXT:   [[COPY7:%[0-9]+]]:vgpr_32 = COPY [[COPY4]].sub0
  ; GFX1200-NEXT:   [[S_MOV_B32_12:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GFX1200-NEXT:   [[V_LSHLREV_B32_e64_1:%[0-9]+]]:vgpr_32 = nuw nsw V_LSHLREV_B32_e64 killed [[S_MOV_B32_12]], killed [[COPY7]], implicit $exec
  ; GFX1200-NEXT:   GLOBAL_STORE_DWORD_SADDR killed [[V_LSHLREV_B32_e64_1]], [[GLOBAL_LOAD_DWORD_SADDR]], killed [[REG_SEQUENCE2]], 0, 0, implicit $exec :: (store (s32) into %ir.arrayidx29, addrspace 1)
  ; GFX1200-NEXT: {{  $}}
  ; GFX1200-NEXT: bb.10.if.end:
  ; GFX1200-NEXT:   S_ENDPGM 0
  ;
  ; GISEL-LABEL: name: switch_i1
  ; GISEL: bb.1.entry:
  ; GISEL-NEXT:   successors: %bb.2(0x80000000)
  ; GISEL-NEXT:   liveins: $sgpr4_sgpr5, $vgpr0
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[COPY:%[0-9]+]]:sreg_64 = COPY $sgpr4_sgpr5
  ; GISEL-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.2.NodeBlock4:
  ; GISEL-NEXT:   successors: %bb.5(0x30000000), %bb.3(0x50000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[S_LOAD_DWORDX4_IMM:%[0-9]+]]:sgpr_128 = S_LOAD_DWORDX4_IMM [[COPY]], 0, 0 :: (dereferenceable invariant load (<2 x s64>) from %ir.filter.coerce.kernarg.offset1, addrspace 4)
  ; GISEL-NEXT:   [[COPY2:%[0-9]+]]:sreg_64 = COPY [[S_LOAD_DWORDX4_IMM]].sub0_sub1
  ; GISEL-NEXT:   [[COPY3:%[0-9]+]]:sreg_64 = COPY [[S_LOAD_DWORDX4_IMM]].sub2_sub3
  ; GISEL-NEXT:   [[COPY4:%[0-9]+]]:sreg_64_xexec_xnull = COPY [[COPY2]]
  ; GISEL-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1023
  ; GISEL-NEXT:   [[COPY5:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_]]
  ; GISEL-NEXT:   [[V_AND_B32_e64_:%[0-9]+]]:vgpr_32 = V_AND_B32_e64 [[COPY1]], [[COPY5]], implicit $exec
  ; GISEL-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GISEL-NEXT:   [[COPY6:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_1]]
  ; GISEL-NEXT:   [[V_LSHLREV_B32_e64_:%[0-9]+]]:vgpr_32 = nuw nsw V_LSHLREV_B32_e64 [[COPY6]], [[V_AND_B32_e64_]], implicit $exec
  ; GISEL-NEXT:   [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[COPY4]], [[V_LSHLREV_B32_e64_]], 0, 0, implicit $exec :: (load (s32) from %ir.arrayidx, addrspace 1)
  ; GISEL-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GISEL-NEXT:   [[COPY7:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_2]]
  ; GISEL-NEXT:   [[V_CMP_LT_I32_e64_:%[0-9]+]]:sreg_32 = V_CMP_LT_I32_e64 [[V_AND_B32_e64_]], [[COPY7]], implicit $exec
  ; GISEL-NEXT:   $vcc_lo = COPY [[V_CMP_LT_I32_e64_]]
  ; GISEL-NEXT:   S_CBRANCH_VCCNZ %bb.5, implicit $vcc_lo
  ; GISEL-NEXT:   S_BRANCH %bb.3
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.3.NodeBlock:
  ; GISEL-NEXT:   successors: %bb.6(0x40000000), %bb.4(0x40000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[S_MOV_B32_3:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GISEL-NEXT:   [[COPY8:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_3]]
  ; GISEL-NEXT:   [[V_CMP_LT_I32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_LT_I32_e64 [[V_AND_B32_e64_]], [[COPY8]], implicit $exec
  ; GISEL-NEXT:   [[S_MOV_B32_4:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; GISEL-NEXT:   $vcc_lo = COPY [[V_CMP_LT_I32_e64_1]]
  ; GISEL-NEXT:   S_CBRANCH_VCCNZ %bb.6, implicit $vcc_lo
  ; GISEL-NEXT:   S_BRANCH %bb.4
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.4.LeafBlock:
  ; GISEL-NEXT:   successors: %bb.7(0x40000000), %bb.8(0x40000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[S_MOV_B32_5:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GISEL-NEXT:   [[COPY9:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_5]]
  ; GISEL-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[V_AND_B32_e64_]], [[COPY9]], implicit $exec
  ; GISEL-NEXT:   [[S_MOV_B32_6:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; GISEL-NEXT:   $vcc_lo = COPY [[V_CMP_EQ_U32_e64_]]
  ; GISEL-NEXT:   S_CBRANCH_VCCNZ %bb.7, implicit $vcc_lo
  ; GISEL-NEXT:   S_BRANCH %bb.8
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.5.sw.bb:
  ; GISEL-NEXT:   successors: %bb.6(0x80000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[S_MOV_B32_7:%[0-9]+]]:sreg_32 = S_MOV_B32 3
  ; GISEL-NEXT:   [[COPY10:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_7]]
  ; GISEL-NEXT:   [[V_CMP_GT_I32_e64_:%[0-9]+]]:sreg_32 = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], [[COPY10]], implicit $exec
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.6.sw.bb4:
  ; GISEL-NEXT:   successors: %bb.7(0x80000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_4]], %bb.3, [[V_CMP_GT_I32_e64_]], %bb.5
  ; GISEL-NEXT:   [[S_MOV_B32_8:%[0-9]+]]:sreg_32 = S_MOV_B32 5
  ; GISEL-NEXT:   [[COPY11:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_8]]
  ; GISEL-NEXT:   [[V_CMP_GT_I32_e64_1:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], [[COPY11]], implicit $exec
  ; GISEL-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_OR_B32 [[V_CMP_GT_I32_e64_1]], [[PHI]], implicit-def dead $scc
  ; GISEL-NEXT:   [[COPY12:%[0-9]+]]:sreg_32 = COPY [[S_OR_B32_]]
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.7.sw.bb12:
  ; GISEL-NEXT:   successors: %bb.9(0x80000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_6]], %bb.4, [[COPY12]], %bb.6
  ; GISEL-NEXT:   [[S_MOV_B32_9:%[0-9]+]]:sreg_32 = S_MOV_B32 7
  ; GISEL-NEXT:   [[COPY13:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_9]]
  ; GISEL-NEXT:   [[V_CMP_GT_I32_e64_2:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], [[COPY13]], implicit $exec
  ; GISEL-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32_xm0_xexec = S_OR_B32 [[V_CMP_GT_I32_e64_2]], [[PHI1]], implicit-def dead $scc
  ; GISEL-NEXT:   [[COPY14:%[0-9]+]]:sreg_32 = COPY [[S_OR_B32_1]]
  ; GISEL-NEXT:   S_BRANCH %bb.9
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.8.sw.default:
  ; GISEL-NEXT:   successors: %bb.9(0x80000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[S_MOV_B32_10:%[0-9]+]]:sreg_32 = S_MOV_B32 11
  ; GISEL-NEXT:   [[COPY15:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_10]]
  ; GISEL-NEXT:   [[V_CMP_GT_I32_e64_3:%[0-9]+]]:sreg_32 = V_CMP_GT_I32_e64 [[GLOBAL_LOAD_DWORD_SADDR]], [[COPY15]], implicit $exec
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.9.sw.epilog:
  ; GISEL-NEXT:   successors: %bb.10(0x40000000), %bb.11(0x40000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[V_CMP_GT_I32_e64_3]], %bb.8, [[COPY14]], %bb.7
  ; GISEL-NEXT:   [[S_MOV_B32_11:%[0-9]+]]:sreg_32_xm0_xexec = S_MOV_B32 -1
  ; GISEL-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32_xm0_xexec = S_XOR_B32 [[PHI2]], [[S_MOV_B32_11]], implicit-def dead $scc
  ; GISEL-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def dead $scc
  ; GISEL-NEXT:   $vcc_lo = COPY [[S_AND_B32_]]
  ; GISEL-NEXT:   S_CBRANCH_VCCNZ %bb.11, implicit $vcc_lo
  ; GISEL-NEXT:   S_BRANCH %bb.10
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.10.if.then:
  ; GISEL-NEXT:   successors: %bb.11(0x80000000)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT:   [[COPY16:%[0-9]+]]:sreg_64 = COPY [[S_LOAD_DWORDX4_IMM]].sub0_sub1
  ; GISEL-NEXT:   [[COPY17:%[0-9]+]]:sreg_64 = COPY [[S_LOAD_DWORDX4_IMM]].sub2_sub3
  ; GISEL-NEXT:   [[COPY18:%[0-9]+]]:sreg_64_xexec_xnull = COPY [[COPY17]]
  ; GISEL-NEXT:   [[S_MOV_B32_12:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GISEL-NEXT:   [[COPY19:%[0-9]+]]:vgpr_32 = COPY [[S_MOV_B32_12]]
  ; GISEL-NEXT:   [[V_LSHLREV_B32_e64_1:%[0-9]+]]:vgpr_32 = nuw nsw V_LSHLREV_B32_e64 [[COPY19]], [[V_AND_B32_e64_]], implicit $exec
  ; GISEL-NEXT:   GLOBAL_STORE_DWORD_SADDR [[V_LSHLREV_B32_e64_1]], [[GLOBAL_LOAD_DWORD_SADDR]], [[COPY18]], 0, 0, implicit $exec :: (store (s32) into %ir.arrayidx29, addrspace 1)
  ; GISEL-NEXT: {{  $}}
  ; GISEL-NEXT: bb.11.if.end:
  ; GISEL-NEXT:   S_ENDPGM 0
entry:
  %id = tail call noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x()
  %idxprom = zext nneg i32 %id to i64
  %arrayidx = getelementptr inbounds nuw i32, ptr addrspace(1) %filter.coerce, i64 %idxprom
  %x = load i32, ptr addrspace(1) %arrayidx, align 4
  switch i32 %id, label %sw.default [
    i32 0, label %sw.bb
    i32 1, label %sw.bb4
    i32 2, label %sw.bb12
  ]

sw.bb:                                            ; preds = %entry
  %cmp = icmp sgt i32 %x, 3
  br label %sw.bb4

sw.bb4:                                           ; preds = %entry, %sw.bb
  %sel.0.off0 = phi i1 [ false, %entry ], [ %cmp, %sw.bb ]
  %cmp5 = icmp sgt i32 %x, 5
  %or9 = or i1 %cmp5, %sel.0.off0
  br label %sw.bb12

sw.bb12:                                          ; preds = %entry, %sw.bb4
  %sel.1.off0 = phi i1 [ false, %entry ], [ %or9, %sw.bb4 ]
  %cmp13 = icmp sgt i32 %x, 7
  %or17 = or i1 %cmp13, %sel.1.off0
  br label %sw.epilog

sw.default:                                       ; preds = %entry
  %cmp20 = icmp sgt i32 %x, 11
  br label %sw.epilog

sw.epilog:                                        ; preds = %sw.default, %sw.bb12
  %sel.2.off0 = phi i1 [ %cmp20, %sw.default ], [ %or17, %sw.bb12 ]
  br i1 %sel.2.off0, label %if.then, label %if.end

if.then:                                          ; preds = %sw.epilog
  %arrayidx29 = getelementptr inbounds nuw i32, ptr addrspace(1) %out.coerce, i64 %idxprom
  store i32 %x, ptr addrspace(1) %arrayidx29, align 4
  br label %if.end

if.end:                                           ; preds = %if.then, %sw.epilog
  ret void
}

declare noundef i32 @llvm.amdgcn.workitem.id.x()
