# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# REQUIRES: asserts
# RUN: llc -march=amdgcn -mcpu=gfx1010 -verify-machineinstrs -amdgpu-late-wave-transform=1 -run-pass=amdgpu-wave-transform -amdgpu-wave-transform-print-final=1 -o - %s 2>&1 | FileCheck -check-prefixes=POSTWT %s

---


name: if_then_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: if_then_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT:   liveins: $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[COPY]], killed [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.2, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0

    %8:vgpr_32 = COPY $vgpr0
    %15:sreg_32 = S_MOV_B32 0
    %16:sreg_32 = V_CMP_EQ_U32_e64 %8, killed %15, implicit $exec
    SI_BRCOND %bb.2, killed %16
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2

    S_BRANCH %bb.2

  bb.2:
    S_ENDPGM 0
...

---


name: if_then_divergent_with_no_terminator
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: if_then_divergent_with_no_terminator
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT:   liveins: $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[COPY]], killed [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.2, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0

    %8:vgpr_32 = COPY $vgpr0
    %15:sreg_32 = S_MOV_B32 0
    %16:sreg_32 = V_CMP_EQ_U32_e64 %8, killed %15, implicit $exec
    SI_BRCOND %bb.2, killed %16
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2

  bb.2:
    S_ENDPGM 0
...
---


name: if_then_else_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: if_then_else_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT:   liveins: $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[COPY]], killed [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.4(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[COPY1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.3(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0

    %8:vgpr_32 = COPY $vgpr0
    %15:sreg_32 = S_MOV_B32 0
    %16:sreg_32 = V_CMP_EQ_U32_e64 %8, killed %15, implicit $exec
    SI_BRCOND %bb.2, killed %16
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3

    S_BRANCH %bb.3

  bb.2:
    successors: %bb.3

    S_BRANCH %bb.3

  bb.3:
    S_ENDPGM 0
...
---


name: if_then_else_uniform
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: if_then_else_uniform
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 [[COPY]], killed [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.3(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $sgpr0

    %8:sgpr_32 = COPY $sgpr0
    %15:sreg_32 = S_MOV_B32 0
    %16:sreg_32 = V_CMP_EQ_U32_e64 %8, killed %15, implicit $exec
    SI_BRCOND_UNIFORM %bb.2, killed %16
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3

    S_BRANCH %bb.3

  bb.2:
    successors: %bb.3

    S_BRANCH %bb.3

  bb.3:
    S_ENDPGM 0
...
---

#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#   3 4   5 6
#    \ \ / /
#     ->7<-
#


name: if_then_else_nested_divergent_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: if_then_else_nested_divergent_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.10(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY1]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_1]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.10, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[COPY4]], %bb.0, %33, %bb.10, %33, %bb.4
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[COPY3]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY2]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_2]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[COPY5:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_2]]
  ; POSTWT-NEXT:   [[S_XOR_B32_5:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY6:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_5]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_4]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.10(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.10
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.10:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_6:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_5:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_6]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[COPY4]], [[S_AND_B32_5]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.6(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY6]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_7:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_6:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_7]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_AND_B32_3]], [[S_AND_B32_6]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[COPY5]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_1]], %bb.6, [[S_AND_B32_3]], %bb.9, [[S_OR_B32_1]], %bb.8
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0, $vgpr1, $vgpr2

    %8:vgpr_32 = COPY $vgpr0
    %9:vgpr_32 = COPY $vgpr1
    %10:vgpr_32 = COPY $vgpr2
    %15:sreg_32 = S_MOV_B32 0
    %16:sreg_32 = V_CMP_EQ_U32_e64 killed %8, %15, implicit $exec
    SI_BRCOND %bb.2, killed %16
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    %17:sreg_32 = V_CMP_EQ_U32_e64 killed %9, %15, implicit $exec
    SI_BRCOND %bb.3, killed %17
    S_BRANCH %bb.4

  bb.2:
    successors: %bb.5, %bb.6

    %18:sreg_32 = V_CMP_EQ_U32_e64 killed %10, %15, implicit $exec
    SI_BRCOND %bb.6, killed %18
    S_BRANCH %bb.5

  bb.3:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.4:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.5:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.6:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.7:
    S_ENDPGM 0
...
---

#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#   3 4   5 6
#    \ \ / /
#     ->7<-
#


name: if_then_else_nested_uniform_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: if_then_else_nested_uniform_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $vgpr1, $vgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY1]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_1]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY2]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_2]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_2]]
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_2]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.6(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[COPY3]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_AND_B32_3]], %bb.4, [[S_AND_B32_4]], %bb.6, [[S_AND_B32_3]], %bb.9, [[S_AND_B32_4]], %bb.8
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $sgpr0, $vgpr1, $vgpr2

    %8:sgpr_32 = COPY $sgpr0
    %9:vgpr_32 = COPY $vgpr1
    %10:vgpr_32 = COPY $vgpr2
    %15:sreg_32 = S_MOV_B32 0
    %16:sreg_32 = V_CMP_EQ_U32_e64 killed %8, %15, implicit $exec
    SI_BRCOND_UNIFORM %bb.2, killed %16
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    %17:sreg_32 = V_CMP_EQ_U32_e64 killed %9, %15, implicit $exec
    SI_BRCOND %bb.3, killed %17
    S_BRANCH %bb.4

  bb.2:
    successors: %bb.5, %bb.6

    %18:sreg_32 = V_CMP_EQ_U32_e64 killed %10, %15, implicit $exec
    SI_BRCOND %bb.6, killed %18
    S_BRANCH %bb.5

  bb.3:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.4:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.5:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.6:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.7:
    S_ENDPGM 0
...
---

#
#       0
#      / \
#     /   \
#    1     2
#   / \   / \
#   3 4   5 6
#    \ \ / /
#     ->7<-
#



name: if_then_else_nested_divergent_uniform
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: if_then_else_nested_divergent_uniform
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $sgpr1, $sgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_EQ_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_EQ_U32_e64_]]
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY1]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_EQ_U32_e64_1]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.3, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_EQ_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[COPY3]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_EQ_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_EQ_U32_e64 killed [[COPY2]], [[S_MOV_B32_]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_EQ_U32_e64_2]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.6, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.8(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.8
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1, %bb.2
    liveins: $vgpr0, $sgpr1, $sgpr2

    %8:vgpr_32 = COPY $vgpr0
    %9:sgpr_32 = COPY $sgpr1
    %10:sgpr_32 = COPY $sgpr2
    %15:sreg_32 = S_MOV_B32 0
    %16:sreg_32 = V_CMP_EQ_U32_e64 killed %8, %15, implicit $exec
    SI_BRCOND %bb.2, killed %16
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.3, %bb.4

    %17:sreg_32 = V_CMP_EQ_U32_e64 killed %9, %15, implicit $exec
    SI_BRCOND_UNIFORM %bb.3, killed %17
    S_BRANCH %bb.4

  bb.2:
    successors: %bb.5, %bb.6

    %18:sreg_32 = V_CMP_EQ_U32_e64 killed %10, %15, implicit $exec
    SI_BRCOND_UNIFORM %bb.6, killed %18 
    S_BRANCH %bb.5

  bb.3:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.4:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.5:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.6:
    successors: %bb.7
    S_BRANCH %bb.7

  bb.7:
    S_ENDPGM 0
...
