# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# REQUIRES: asserts
# RUN: llc -march=amdgcn -mcpu=gfx1010 -verify-machineinstrs -amdgpu-late-wave-transform=1 -run-pass=amdgpu-wave-transform -amdgpu-wave-transform-print-final=1 -o - %s 2>&1 | FileCheck -check-prefixes=POSTWT %s

# TODO: Test some of the generated MIR. This is currently not done because
#       of high fluctuations in the MIR.

---


name: simple_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: simple_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $vgpr0
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %12, %bb.1
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %3, %bb.1
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.2, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: simple_divergent
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $vgpr0
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %12, %bb.1
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %3, %bb.1
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_]], implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.2, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $vgpr0

    %0:vgpr_32 = COPY $vgpr0
    %1:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.1, %bb.2

    %10:sreg_32 = PHI %1, %bb.0, %11, %bb.1
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND %bb.1, killed %12
    S_BRANCH %bb.2

  bb.2:
    S_ENDPGM 0
...
---


name: two_backedges_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: two_backedges_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $vgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %23, %bb.4
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.4
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.4(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[COPY3]], [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[COPY3]], %bb.1, [[S_OR_B32_]], %bb.2
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: two_backedges_divergent
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $vgpr0, $vgpr1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %23, %bb.4
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.4
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; CFG-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.4(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[COPY3]], [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[COPY3]], %bb.1, [[S_OR_B32_]], %bb.2
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY4]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI2]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_1]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI2]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $vgpr0, $vgpr1

    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.1, %bb.2

    %10:sreg_32 = PHI %9, %bb.0, %11, %bb.1, %11, %bb.2
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND %bb.1, killed %12
    S_BRANCH %bb.2

  bb.2:
    successors: %bb.1, %bb.3

    %20:sreg_32 = V_CMP_NE_U32_e64 %11, %1, implicit $exec
    SI_BRCOND %bb.1, killed %20
    S_BRANCH %bb.3

  bb.3:
    S_ENDPGM 0
...
---


name: two_backedges_uniform_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: two_backedges_uniform_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $vgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, [[PHI]], %bb.1, %14, %bb.2
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.1, %4, %bb.2
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: two_backedges_uniform_divergent
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $sgpr0, $vgpr1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, [[PHI]], %bb.1, %14, %bb.2
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.1, %4, %bb.2
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $sgpr0, $vgpr1

    %0:sgpr_32 = COPY $sgpr0
    %1:vgpr_32 = COPY $vgpr1
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.1, %bb.2

    %10:sreg_32 = PHI %9, %bb.0, %11, %bb.1, %11, %bb.2
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %12
    S_BRANCH %bb.2

  bb.2:
    successors: %bb.1, %bb.3

    %20:sreg_32 = V_CMP_NE_U32_e64 %11, %1, implicit $exec
    SI_BRCOND %bb.1, killed %20
    S_BRANCH %bb.3

  bb.3:
    S_ENDPGM 0
...
---


name: two_backedges_divergent_uniform
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: two_backedges_divergent_uniform
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $sgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %23, %bb.4
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.4
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.4(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[COPY3]], [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[COPY3]], %bb.1, [[S_OR_B32_]], %bb.2
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: two_backedges_divergent_uniform
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $vgpr0, $sgpr1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %23, %bb.4
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.4
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; CFG-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[S_XOR_B32_1]]
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.4(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[COPY3]], [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[COPY3]], %bb.1, [[S_OR_B32_]], %bb.2
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[COPY4]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI2]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_1]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI2]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $vgpr0, $sgpr1

    %0:vgpr_32 = COPY $vgpr0
    %1:sgpr_32 = COPY $sgpr1
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.1, %bb.2

    %10:sreg_32 = PHI %9, %bb.0, %11, %bb.1, %11, %bb.2
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND %bb.1, killed %12
    S_BRANCH %bb.2

  bb.2:
    successors: %bb.1, %bb.3

    %20:sreg_32 = V_CMP_NE_U32_e64 %11, %1, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %20
    S_BRANCH %bb.3

  bb.3:
    S_ENDPGM 0
...
---

#
#         0
#         |
#    v---<1<--\
#    |    |   |
#    | v-<2<\ |
#    | |  | | |
#    | |  3-^ |
#    |/   \   |
#    4     ---^
#


name: nested_uniform
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: nested_uniform
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.3
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[PHI]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.3, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_2]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: nested_uniform
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.3
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[PHI]], [[COPY]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.3(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.3, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_2]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $sgpr0, $sgpr1, $sgpr2

    %0:sgpr_32 = COPY $sgpr0
    %1:sgpr_32 = COPY $sgpr1
    %2:sgpr_32 = COPY $sgpr2
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.4

    %10:sreg_32 = PHI %9, %bb.0, %20, %bb.3
    %11:sreg_32 = V_CMP_NE_U32_e64 %10, %0, implicit $exec
    SI_BRCOND_UNIFORM %bb.2, killed %11
    S_BRANCH %bb.4

  bb.2:
    successors: %bb.3, %bb.4

    %20:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %21:sreg_32 = V_CMP_NE_U32_e64 %20, %1, implicit $exec
    SI_BRCOND_UNIFORM %bb.3, killed %21
    S_BRANCH %bb.4

  bb.3:
    %30:sreg_32 = V_CMP_NE_U32_e64 %20, %2, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %30
    S_BRANCH %bb.2

  bb.4:
    S_ENDPGM 0
...
---

#
#         0
#         |
#    v---<1<--\
#    |    |   |
#    | v-<2<\ |
#    | |  | | |
#    | |  3-^ |
#    |/   \   |
#    4     ---^
#


name: nested_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: nested_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; POSTWT-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.0, %37, %bb.5
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.0, [[S_MOV_B32_1]], %bb.5
  ; POSTWT-NEXT:   [[PHI2:%[0-9]+]]:vgpr_32 = PHI [[V_MOV_B32_e32_]], %bb.0, %5, %bb.5
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[PHI2]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.5(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %28, %bb.3
  ; POSTWT-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[PHI1]], %bb.1, [[S_MOV_B32_1]], %bb.3
  ; POSTWT-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %13, %bb.3
  ; POSTWT-NEXT:   [[V_ADD_U32_e64_:%[0-9]+]]:vgpr_32 = V_ADD_U32_e64 [[PHI2]], 1, 0, implicit $exec
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI4]], [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI3]], [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_OR_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.5, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.5(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_]], [[COPY2]], implicit $exec
  ; POSTWT-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI5]], [[V_CMP_NE_U32_e64_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_4:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_OR_B32_2]], [[S_XOR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.5, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_2]], %bb.2, [[S_OR_B32_4]], %bb.3
  ; POSTWT-NEXT:   [[PHI7:%[0-9]+]]:sreg_32 = PHI [[PHI5]], %bb.2, [[S_OR_B32_3]], %bb.3
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI7]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_5:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_OR_B32_]], [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI7]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   [[PHI8:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_]], %bb.1, [[S_OR_B32_5]], %bb.5
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI8]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: nested_divergent
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; CFG-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.0, %37, %bb.5
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.0, [[S_MOV_B32_1]], %bb.5
  ; CFG-NEXT:   [[PHI2:%[0-9]+]]:vgpr_32 = PHI [[V_MOV_B32_e32_]], %bb.0, %5, %bb.5
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[PHI2]], [[COPY]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_]], implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.3(0x40000000), %bb.5(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %28, %bb.3
  ; CFG-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[PHI1]], %bb.1, [[S_MOV_B32_1]], %bb.3
  ; CFG-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %13, %bb.3
  ; CFG-NEXT:   [[V_ADD_U32_e64_:%[0-9]+]]:vgpr_32 = V_ADD_U32_e64 [[PHI2]], 1, 0, implicit $exec
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI4]], [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI3]], [[S_AND_B32_]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[S_OR_B32_1]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.5, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.3
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.5(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_]], [[COPY2]], implicit $exec
  ; CFG-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI5]], [[V_CMP_NE_U32_e64_2]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_4:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_OR_B32_2]], [[S_XOR_B32_3]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_1]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.5, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.5:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_2]], %bb.2, [[S_OR_B32_4]], %bb.3
  ; CFG-NEXT:   [[PHI7:%[0-9]+]]:sreg_32 = PHI [[PHI5]], %bb.2, [[S_OR_B32_3]], %bb.3
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI7]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_5:%[0-9]+]]:sreg_32 = S_OR_B32 [[S_OR_B32_]], [[S_AND_B32_2]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI7]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   [[PHI8:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_]], %bb.1, [[S_OR_B32_5]], %bb.5
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI8]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $vgpr0, $vgpr1, $vgpr2

    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = COPY $vgpr2
    %9:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.4

    %10:vgpr_32 = PHI %9, %bb.0, %20, %bb.3
    %11:sreg_32 = V_CMP_NE_U32_e64 %10, %0, implicit $exec
    SI_BRCOND %bb.2, killed %11
    S_BRANCH %bb.4

  bb.2:
    successors: %bb.3, %bb.4

    %20:vgpr_32 = V_ADD_U32_e64 %10, 1, 0, implicit $exec
    %21:sreg_32 = V_CMP_NE_U32_e64 %20, %1, implicit $exec
    SI_BRCOND %bb.3, killed %21
    S_BRANCH %bb.4

  bb.3:
    %30:sreg_32 = V_CMP_NE_U32_e64 %20, %2, implicit $exec
    SI_BRCOND %bb.1, killed %30
    S_BRANCH %bb.2

  bb.4:
    S_ENDPGM 0
...
---

#
#         0
#         |
#      /->1
#      |  |
#      | [2
#      |  |
#      ^-<3
#         |
#         4
#


name: nested2_uniform_uniform
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: nested2_uniform_uniform
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $sgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.3
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %7, %bb.2
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[S_ADD_U32_1:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_1]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: nested2_uniform_uniform
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $sgpr0, $sgpr1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %4, %bb.3
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %7, %bb.2
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI1]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.3
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[S_ADD_U32_1:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_1]], [[COPY]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $sgpr0, $sgpr1

    %0:sgpr_32 = COPY $sgpr0
    %1:sgpr_32 = COPY $sgpr1
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2

    %10:sreg_32 = PHI %9, %bb.0, %30, %bb.3
    %19:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.2

  bb.2:
    successors: %bb.2, %bb.3

    %20:sreg_32 = PHI %19, %bb.1, %21, %bb.2
    %21:sreg_32 = S_ADD_U32 %20, 1, implicit-def $scc
    %22:sreg_32 = V_CMP_NE_U32_e64 %21, %1, implicit $exec
    SI_BRCOND_UNIFORM %bb.2, killed %22
    S_BRANCH %bb.3

  bb.3:
    %30:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %31:sreg_32 = V_CMP_NE_U32_e64 %30, %0, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %31
    S_BRANCH %bb.4

  bb.4:
    S_ENDPGM 0
...
---

#
#         0
#         |
#      /->1
#      |  |
#      | [2
#      |  |
#      ^-<3
#         |
#         4
#


name: nested2_divergent_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: nested2_divergent_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $vgpr1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.0, %24, %bb.3
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:vgpr_32 = PHI [[V_MOV_B32_e32_]], %bb.0, %4, %bb.3
  ; POSTWT-NEXT:   [[V_MOV_B32_e32_1:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %20, %bb.2
  ; POSTWT-NEXT:   [[PHI3:%[0-9]+]]:vgpr_32 = PHI [[V_MOV_B32_e32_1]], %bb.1, %7, %bb.2
  ; POSTWT-NEXT:   [[V_ADD_U32_e64_:%[0-9]+]]:vgpr_32 = V_ADD_U32_e64 [[PHI3]], 1, 0, implicit $exec
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_XOR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[V_ADD_U32_e64_1:%[0-9]+]]:vgpr_32 = V_ADD_U32_e64 [[PHI1]], 1, 0, implicit $exec
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_1]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: nested2_divergent_divergent
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $vgpr0, $vgpr1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; CFG-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.0, %24, %bb.3
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:vgpr_32 = PHI [[V_MOV_B32_e32_]], %bb.0, %4, %bb.3
  ; CFG-NEXT:   [[V_MOV_B32_e32_1:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; CFG-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_1]], %bb.1, %20, %bb.2
  ; CFG-NEXT:   [[PHI3:%[0-9]+]]:vgpr_32 = PHI [[V_MOV_B32_e32_1]], %bb.1, %7, %bb.2
  ; CFG-NEXT:   [[V_ADD_U32_e64_:%[0-9]+]]:vgpr_32 = V_ADD_U32_e64 [[PHI3]], 1, 0, implicit $exec
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_]], implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_XOR_B32_]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.3, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_]], implicit-def $scc
  ; CFG-NEXT:   [[V_ADD_U32_e64_1:%[0-9]+]]:vgpr_32 = V_ADD_U32_e64 [[PHI1]], 1, 0, implicit $exec
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[V_ADD_U32_e64_1]], [[COPY]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[V_CMP_NE_U32_e64_1]], implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_XOR_B32_1]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.4, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_1]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $vgpr0, $vgpr1

    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %9:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2

    %10:vgpr_32 = PHI %9, %bb.0, %30, %bb.3
    %19:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    S_BRANCH %bb.2

  bb.2:
    successors: %bb.2, %bb.3

    %20:vgpr_32 = PHI %19, %bb.1, %21, %bb.2
    %21:vgpr_32 = V_ADD_U32_e64 %20, 1, 0, implicit $exec
    %22:sreg_32 = V_CMP_NE_U32_e64 %21, %1, implicit $exec
    SI_BRCOND %bb.2, killed %22
    S_BRANCH %bb.3

  bb.3:
    %30:vgpr_32 = V_ADD_U32_e64 %10, 1, 0, implicit $exec
    %31:sreg_32 = V_CMP_NE_U32_e64 %30, %0, implicit $exec
    SI_BRCOND %bb.1, killed %31
    S_BRANCH %bb.4

  bb.4:
    S_ENDPGM 0
...
---

#
#         0
#         |
#     /-->1<--\
#     |  / \  |
#     ^-2   3-^
#       |   |
#       4   5
#        \ /
#         6
#


name: multi_backedge_exits_divergent_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: multi_backedge_exits_divergent_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.10(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %44, %bb.9
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %32, %bb.9
  ; POSTWT-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %26, %bb.9
  ; POSTWT-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.9
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI3]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.10, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.10(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_1]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI1]], [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.10
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.10:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[PHI1]], %bb.1, [[S_OR_B32_]], %bb.2
  ; POSTWT-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.1, [[COPY4]], %bb.2
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI5]], [[V_CMP_NE_U32_e64_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_AND_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, %49, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_5:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI4]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[PHI2]], %bb.10, [[S_OR_B32_2]], %bb.3
  ; POSTWT-NEXT:   [[PHI7:%[0-9]+]]:sreg_32 = PHI [[PHI5]], %bb.10, [[S_OR_B32_1]], %bb.3
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_5:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI7]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_6:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_5]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_6]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI7]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_6:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_7:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_6]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI6]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_5]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: multi_backedge_exits_divergent_divergent
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.10(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %44, %bb.9
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %32, %bb.9
  ; CFG-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %26, %bb.9
  ; CFG-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.9
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI3]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.10, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.10(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_1]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI1]], [[S_AND_B32_2]], implicit-def $scc
  ; CFG-NEXT:   S_BRANCH %bb.10
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.10:
  ; CFG-NEXT:   successors: %bb.3(0x40000000), %bb.9(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[PHI1]], %bb.1, [[S_OR_B32_]], %bb.2
  ; CFG-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.1, [[COPY4]], %bb.2
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.3
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.9(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; CFG-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI5]], [[V_CMP_NE_U32_e64_2]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_AND_B32_4]], implicit-def $scc
  ; CFG-NEXT:   S_BRANCH %bb.9
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.7:
  ; CFG-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, %49, implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI4]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_5:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI4]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   successors: %bb.6(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.6
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.9:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[PHI2]], %bb.10, [[S_OR_B32_2]], %bb.3
  ; CFG-NEXT:   [[PHI7:%[0-9]+]]:sreg_32 = PHI [[PHI5]], %bb.10, [[S_OR_B32_1]], %bb.3
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_3]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_5:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI7]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_6:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_5]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_6]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI7]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.8:
  ; CFG-NEXT:   successors: %bb.5(0x40000000), %bb.7(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_3]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_6:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_7:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_6]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI6]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.5
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.5:
  ; CFG-NEXT:   successors: %bb.7(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.7
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.6:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_5]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $vgpr0, $vgpr1, $vgpr2

    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = COPY $vgpr2
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.3

    %10:sreg_32 = PHI %9, %bb.0, %11, %bb.2, %11, %bb.3
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND %bb.2, killed %12
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.1, %bb.4

    %20:sreg_32 = V_CMP_NE_U32_e64 %11, %1, implicit $exec
    SI_BRCOND %bb.1, killed %20
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.1, %bb.5

    %30:sreg_32 = V_CMP_NE_U32_e64 %11, %2, implicit $exec
    SI_BRCOND %bb.1, killed %30
    S_BRANCH %bb.5

  bb.4:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0
...
---

#
#         0
#         |
#     /-->1<--\
#     |  / \  |
#     ^-2   3-^
#       |   |
#       4   5
#        \ /
#         6
#


name: multi_backedge_exits_uniform_divergent
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: multi_backedge_exits_uniform_divergent
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $vgpr1, $vgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %29, %bb.2, %28, %bb.3
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %23, %bb.2, [[PHI1]], %bb.3
  ; POSTWT-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, [[PHI2]], %bb.2, %17, %bb.3
  ; POSTWT-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.2, %5, %bb.3
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI3]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_1]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI1]], [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_2]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, %36, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, %26, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term %26
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_1]], %bb.2, [[S_OR_B32_3]], %bb.3
  ; POSTWT-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_]], %bb.2, [[PHI1]], %bb.3
  ; POSTWT-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[PHI2]], %bb.2, [[S_OR_B32_2]], %bb.3
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_5:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI6]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: multi_backedge_exits_uniform_divergent
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $sgpr0, $vgpr1, $vgpr2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %29, %bb.2, %28, %bb.3
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %23, %bb.2, [[PHI1]], %bb.3
  ; CFG-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, [[PHI2]], %bb.2, %17, %bb.3
  ; CFG-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.2, %5, %bb.3
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI3]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.3
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_1]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI1]], [[S_AND_B32_]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_1]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_AND_B32_2]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_3]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_2]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.7:
  ; CFG-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, %36, implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, %26, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term %26
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   successors: %bb.6(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.6
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.8:
  ; CFG-NEXT:   successors: %bb.5(0x40000000), %bb.7(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_1]], %bb.2, [[S_OR_B32_3]], %bb.3
  ; CFG-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_OR_B32_]], %bb.2, [[PHI1]], %bb.3
  ; CFG-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[PHI2]], %bb.2, [[S_OR_B32_2]], %bb.3
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[PHI4]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_5:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI6]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.5
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.5:
  ; CFG-NEXT:   successors: %bb.7(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.7
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.6:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_4]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $sgpr0, $vgpr1, $vgpr2

    %0:sgpr_32 = COPY $sgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = COPY $vgpr2
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.3

    %10:sreg_32 = PHI %9, %bb.0, %11, %bb.2, %11, %bb.3
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND_UNIFORM %bb.2, killed %12
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.1, %bb.4

    %20:sreg_32 = V_CMP_NE_U32_e64 %11, %1, implicit $exec
    SI_BRCOND %bb.1, killed %20
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.1, %bb.5

    %30:sreg_32 = V_CMP_NE_U32_e64 %11, %2, implicit $exec
    SI_BRCOND %bb.1, killed %30
    S_BRANCH %bb.5

  bb.4:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0
...
---

#
#         0
#         |
#     /-->1<--\
#     |  / \  |
#     ^-2   3-^
#       |   |
#       4   5
#        \ /
#         6
#


name: multi_backedge_exits_divergent_uniform
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: multi_backedge_exits_divergent_uniform
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $vgpr0, $sgpr1, $sgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; POSTWT-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.10(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %44, %bb.9
  ; POSTWT-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %32, %bb.9
  ; POSTWT-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %26, %bb.9
  ; POSTWT-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.9
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI3]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.10, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.10(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_1]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI1]], [[S_AND_B32_2]], implicit-def $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.10
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.10:
  ; POSTWT-NEXT:   successors: %bb.3(0x40000000), %bb.9(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[PHI1]], %bb.1, [[S_OR_B32_]], %bb.2
  ; POSTWT-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.1, [[COPY4]], %bb.2
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.9(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; POSTWT-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI5]], [[V_CMP_NE_U32_e64_2]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_AND_B32_4]], implicit-def $scc
  ; POSTWT-NEXT:   S_BRANCH %bb.9
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.7:
  ; POSTWT-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, %49, implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI4]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_5:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI4]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.9:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[PHI2]], %bb.10, [[S_OR_B32_2]], %bb.3
  ; POSTWT-NEXT:   [[PHI7:%[0-9]+]]:sreg_32 = PHI [[PHI5]], %bb.10, [[S_OR_B32_1]], %bb.3
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_5:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI7]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_6:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_5]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_6]], implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI7]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.8:
  ; POSTWT-NEXT:   successors: %bb.5(0x40000000), %bb.7(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_3]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_XOR_B32_6:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; POSTWT-NEXT:   [[S_AND_B32_7:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_6]], $exec_lo, implicit-def $scc
  ; POSTWT-NEXT:   $exec_lo = S_MOV_B32_term [[PHI6]]
  ; POSTWT-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; POSTWT-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.7(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.7
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_5]], implicit-def $scc
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: multi_backedge_exits_divergent_uniform
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $vgpr0, $sgpr1, $sgpr2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 -1
  ; CFG-NEXT:   [[S_MOV_B32_2:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $exec_lo
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.10(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %44, %bb.9
  ; CFG-NEXT:   [[PHI1:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %32, %bb.9
  ; CFG-NEXT:   [[PHI2:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.0, %26, %bb.9
  ; CFG-NEXT:   [[PHI3:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.9
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI3]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   [[S_XOR_B32_:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_1:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.10, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.10(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   [[COPY4:%[0-9]+]]:sreg_32 = COPY [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   [[S_XOR_B32_1:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_1]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_2:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_1]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI1]], [[S_AND_B32_2]], implicit-def $scc
  ; CFG-NEXT:   S_BRANCH %bb.10
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.10:
  ; CFG-NEXT:   successors: %bb.3(0x40000000), %bb.9(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI4:%[0-9]+]]:sreg_32 = PHI [[PHI1]], %bb.1, [[S_OR_B32_]], %bb.2
  ; CFG-NEXT:   [[PHI5:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_2]], %bb.1, [[COPY4]], %bb.2
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_1]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_2:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[S_AND_B32_]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_3:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_2]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[S_AND_B32_]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.9, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.3
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.9(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; CFG-NEXT:   [[S_OR_B32_1:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI5]], [[V_CMP_NE_U32_e64_2]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_3:%[0-9]+]]:sreg_32 = S_XOR_B32 [[V_CMP_NE_U32_e64_2]], -1, implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_4:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_3]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_2:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI2]], [[S_AND_B32_4]], implicit-def $scc
  ; CFG-NEXT:   S_BRANCH %bb.9
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.7:
  ; CFG-NEXT:   successors: %bb.4(0x40000000), %bb.6(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, %49, implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_4:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI4]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_5:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_4]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI4]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.6, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   successors: %bb.6(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.6
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.9:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.8(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI6:%[0-9]+]]:sreg_32 = PHI [[PHI2]], %bb.10, [[S_OR_B32_2]], %bb.3
  ; CFG-NEXT:   [[PHI7:%[0-9]+]]:sreg_32 = PHI [[PHI5]], %bb.10, [[S_OR_B32_1]], %bb.3
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_3]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_5:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI7]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_6:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_5]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   [[S_OR_B32_3:%[0-9]+]]:sreg_32 = S_OR_B32 [[PHI]], [[S_AND_B32_6]], implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI7]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.8, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.8:
  ; CFG-NEXT:   successors: %bb.5(0x40000000), %bb.7(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_OR_B32_3]], implicit-def $scc
  ; CFG-NEXT:   [[S_XOR_B32_6:%[0-9]+]]:sreg_32 = S_XOR_B32 $exec_lo, [[PHI6]], implicit-def $scc
  ; CFG-NEXT:   [[S_AND_B32_7:%[0-9]+]]:sreg_32 = S_AND_B32 [[S_XOR_B32_6]], $exec_lo, implicit-def $scc
  ; CFG-NEXT:   $exec_lo = S_MOV_B32_term [[PHI6]]
  ; CFG-NEXT:   SI_WAVE_CF_EDGE implicit-def $scc
  ; CFG-NEXT:   S_CBRANCH_EXECZ %bb.7, implicit $exec
  ; CFG-NEXT:   S_BRANCH %bb.5
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.5:
  ; CFG-NEXT:   successors: %bb.7(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.7
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.6:
  ; CFG-NEXT:   $exec_lo = S_OR_B32 $exec_lo, [[S_AND_B32_5]], implicit-def $scc
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $vgpr0, $sgpr1, $sgpr2

    %0:vgpr_32 = COPY $vgpr0
    %1:sgpr_32 = COPY $sgpr1
    %2:sgpr_32 = COPY $sgpr2
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.3

    %10:sreg_32 = PHI %9, %bb.0, %11, %bb.2, %11, %bb.3
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND %bb.2, killed %12
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.1, %bb.4

    %20:sreg_32 = V_CMP_NE_U32_e64 %11, %1, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %20
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.1, %bb.5

    %30:sreg_32 = V_CMP_NE_U32_e64 %11, %2, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %30
    S_BRANCH %bb.5

  bb.4:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0
...
---

#
#         0
#         |
#     /-->1<--\
#     |  / \  |
#     ^-2   3-^
#       |   |
#       4   5
#        \ /
#         6
#


name: multi_backedge_exits_uniform_uniform
tracksRegLiveness: true
body:             |
  ; POSTWT-LABEL: name: multi_backedge_exits_uniform_uniform
  ; POSTWT: bb.0:
  ; POSTWT-NEXT:   successors: %bb.1(0x80000000)
  ; POSTWT-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; POSTWT-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; POSTWT-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; POSTWT-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; POSTWT-NEXT:   S_BRANCH %bb.1
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.1:
  ; POSTWT-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.2, %5, %bb.3
  ; POSTWT-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI]], 1, implicit-def $scc
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.3
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.2:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_1]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.4
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.3:
  ; POSTWT-NEXT:   successors: %bb.1(0x40000000), %bb.5(0x40000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; POSTWT-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_2]]
  ; POSTWT-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; POSTWT-NEXT:   S_BRANCH %bb.5
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.4:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.5:
  ; POSTWT-NEXT:   successors: %bb.6(0x80000000)
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT:   S_BRANCH %bb.6
  ; POSTWT-NEXT: {{  $}}
  ; POSTWT-NEXT: bb.6:
  ; POSTWT-NEXT:   S_ENDPGM 0
  ; CFG-LABEL: name: multi_backedge_exits_uniform_uniform
  ; CFG: bb.0:
  ; CFG-NEXT:   successors: %bb.1(0x80000000)
  ; CFG-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[COPY:%[0-9]+]]:sgpr_32 = COPY $sgpr0
  ; CFG-NEXT:   [[COPY1:%[0-9]+]]:sgpr_32 = COPY $sgpr1
  ; CFG-NEXT:   [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr2
  ; CFG-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; CFG-NEXT:   S_BRANCH %bb.1
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.1:
  ; CFG-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[PHI:%[0-9]+]]:sreg_32 = PHI [[S_MOV_B32_]], %bb.0, %5, %bb.2, %5, %bb.3
  ; CFG-NEXT:   [[S_ADD_U32_:%[0-9]+]]:sreg_32 = S_ADD_U32 [[PHI]], 1, implicit-def $scc
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.2, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.3
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.2:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.4(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_1:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY1]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_1]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.4
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.3:
  ; CFG-NEXT:   successors: %bb.1(0x40000000), %bb.5(0x40000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   [[V_CMP_NE_U32_e64_2:%[0-9]+]]:sreg_32 = V_CMP_NE_U32_e64 [[S_ADD_U32_]], [[COPY2]], implicit $exec
  ; CFG-NEXT:   $vcc_lo = COPY [[V_CMP_NE_U32_e64_2]]
  ; CFG-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; CFG-NEXT:   S_BRANCH %bb.5
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.4:
  ; CFG-NEXT:   successors: %bb.6(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.6
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.5:
  ; CFG-NEXT:   successors: %bb.6(0x80000000)
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT:   S_BRANCH %bb.6
  ; CFG-NEXT: {{  $}}
  ; CFG-NEXT: bb.6:
  ; CFG-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $sgpr0, $sgpr1, $sgpr2

    %0:sgpr_32 = COPY $sgpr0
    %1:sgpr_32 = COPY $sgpr1
    %2:sgpr_32 = COPY $sgpr2
    %9:sreg_32 = S_MOV_B32 0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.3

    %10:sreg_32 = PHI %9, %bb.0, %11, %bb.2, %11, %bb.3
    %11:sreg_32 = S_ADD_U32 %10, 1, implicit-def $scc
    %12:sreg_32 = V_CMP_NE_U32_e64 %11, %0, implicit $exec
    SI_BRCOND_UNIFORM %bb.2, killed %12
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.1, %bb.4

    %20:sreg_32 = V_CMP_NE_U32_e64 %11, %1, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %20
    S_BRANCH %bb.4

  bb.3:
    successors: %bb.1, %bb.5

    %30:sreg_32 = V_CMP_NE_U32_e64 %11, %2, implicit $exec
    SI_BRCOND_UNIFORM %bb.1, killed %30
    S_BRANCH %bb.5

  bb.4:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.5:
    successors: %bb.6

    S_BRANCH %bb.6

  bb.6:
    S_ENDPGM 0
...
