; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc < %s -mtriple=thumbv7-apple-ios | FileCheck %s

define void @bar(ptr %p, i32 %lane, <4 x i32> %phitmp) nounwind {
; CHECK-LABEL: bar:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    push {r4, r7, lr}
; CHECK-NEXT:    add r7, sp, #4
; CHECK-NEXT:    sub sp, #20
; CHECK-NEXT:    mov r4, sp
; CHECK-NEXT:    bfc r4, #0, #4
; CHECK-NEXT:    mov sp, r4
; CHECK-NEXT:    and r1, r1, #3
; CHECK-NEXT:    vldr d17, [r7, #8]
; CHECK-NEXT:    vmov d16, r2, r3
; CHECK-NEXT:    mov r2, sp
; CHECK-NEXT:    lsls r1, r1, #2
; CHECK-NEXT:    subs r4, r7, #4
; CHECK-NEXT:    vst1.64 {d16, d17}, [r2:128], r1
; CHECK-NEXT:    vld1.32 {d16[], d17[]}, [r2:32]
; CHECK-NEXT:    vst1.32 {d16, d17}, [r0]
; CHECK-NEXT:    mov sp, r4
; CHECK-NEXT:    pop {r4, r7, pc}
  %val = extractelement <4 x i32> %phitmp, i32 %lane
  %r1 = insertelement <4 x i32> undef, i32 %val, i32 1
  %r2 = insertelement <4 x i32> %r1, i32 %val, i32 2
  %r3 = insertelement <4 x i32> %r2, i32 %val, i32 3
  store <4 x i32> %r3, ptr %p, align 4
  ret void
}
