; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=thumb-eabi -mcpu=arm1156t2-s -mattr=+thumb2 %s -o - | FileCheck %s

define i32 @sbfx1(i32 %a) {
; CHECK-LABEL: sbfx1:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    lsls r0, r0, #14
; CHECK-NEXT:    sbfx r0, r0, #21, #11
; CHECK-NEXT:    bx lr
	%t1 = lshr i32 %a, 7
	%t2 = trunc i32 %t1 to i11
	%t3 = sext i11 %t2 to i32
	ret i32 %t3
}

define i32 @ubfx1(i32 %a) {
; CHECK-LABEL: ubfx1:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    ubfx r0, r0, #7, #11
; CHECK-NEXT:    bx lr
	%t1 = lshr i32 %a, 7
	%t2 = trunc i32 %t1 to i11
	%t3 = zext i11 %t2 to i32
	ret i32 %t3
}

define i32 @ubfx2(i32 %a) {
; CHECK-LABEL: ubfx2:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    ubfx r0, r0, #7, #11
; CHECK-NEXT:    bx lr
	%t1 = lshr i32 %a, 7
	%t2 = and i32 %t1, 2047
	ret i32 %t2
}

