; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=thumbv7-none-eabi   -mcpu=cortex-m3 | FileCheck %s -check-prefix=CHECK -check-prefix=NONE
; RUN: llc < %s -mtriple=thumbv7-none-eabihf -mcpu=cortex-m4 | FileCheck %s -check-prefix=CHECK -check-prefix=HARD -check-prefix=SP
; RUN: llc < %s -mtriple=thumbv7-none-eabihf -mcpu=cortex-m7 | FileCheck %s -check-prefix=CHECK -check-prefix=HARD -check-prefix=DP
; RUN: llc < %s -mtriple=thumbv7-none-eabihf -mcpu=cortex-a8 | FileCheck %s -check-prefix=CHECK -check-prefix=HARD -check-prefix=DP

define i1 @cmp_f_false(float %a, float %b) {
; CHECK-LABEL: cmp_f_false:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r0, #0
; CHECK-NEXT:    bx lr
  %1 = fcmp false float %a, %b
  ret i1 %1
}

define i1 @cmp_f_oeq(float %a, float %b) {
; NONE-LABEL: cmp_f_oeq:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpeq
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_oeq:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it eq
; SP-NEXT:    moveq r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp oeq float %a, %b
  ret i1 %1
}

define i1 @cmp_f_ogt(float %a, float %b) {
; NONE-LABEL: cmp_f_ogt:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpgt
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_ogt:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it gt
; SP-NEXT:    movgt r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp ogt float %a, %b
  ret i1 %1
}

define i1 @cmp_f_oge(float %a, float %b) {
; NONE-LABEL: cmp_f_oge:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpge
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_oge:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it ge
; SP-NEXT:    movge r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp oge float %a, %b
  ret i1 %1
}

define i1 @cmp_f_olt(float %a, float %b) {
; NONE-LABEL: cmp_f_olt:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmplt
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_olt:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it mi
; SP-NEXT:    movmi r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp olt float %a, %b
  ret i1 %1
}
define i1 @cmp_f_ole(float %a, float %b) {
; NONE-LABEL: cmp_f_ole:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmple
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_ole:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it ls
; SP-NEXT:    movls r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp ole float %a, %b
  ret i1 %1
}

define i1 @cmp_f_one(float %a, float %b) {
; NONE-LABEL: cmp_f_one:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r4, r5, r6, lr}
; NONE-NEXT:    push {r4, r5, r6, lr}
; NONE-NEXT:    mov r4, r1
; NONE-NEXT:    mov r5, r0
; NONE-NEXT:    bl __aeabi_fcmpeq
; NONE-NEXT:    mov r6, r0
; NONE-NEXT:    mov r0, r5
; NONE-NEXT:    mov r1, r4
; NONE-NEXT:    bl __aeabi_fcmpun
; NONE-NEXT:    orrs r0, r6
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r4, r5, r6, pc}
;
; SP-LABEL: cmp_f_one:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it mi
; SP-NEXT:    movmi r0, #1
; SP-NEXT:    it gt
; SP-NEXT:    movgt r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp one float %a, %b
  ret i1 %1
}
define i1 @cmp_f_ord(float %a, float %b) {
; NONE-LABEL: cmp_f_ord:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpun
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_ord:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it vc
; SP-NEXT:    movvc r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp ord float %a, %b
  ret i1 %1
}

define i1 @cmp_f_ueq(float %a, float %b) {
; NONE-LABEL: cmp_f_ueq:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r4, r5, r6, lr}
; NONE-NEXT:    push {r4, r5, r6, lr}
; NONE-NEXT:    mov r4, r1
; NONE-NEXT:    mov r5, r0
; NONE-NEXT:    bl __aeabi_fcmpeq
; NONE-NEXT:    mov r6, r0
; NONE-NEXT:    mov r0, r5
; NONE-NEXT:    mov r1, r4
; NONE-NEXT:    bl __aeabi_fcmpun
; NONE-NEXT:    orrs r0, r6
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r4, r5, r6, pc}
;
; SP-LABEL: cmp_f_ueq:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it eq
; SP-NEXT:    moveq r0, #1
; SP-NEXT:    it vs
; SP-NEXT:    movvs r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp ueq float %a, %b
  ret i1 %1
}
define i1 @cmp_f_ugt(float %a, float %b) {
; NONE-LABEL: cmp_f_ugt:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmple
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_ugt:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it hi
; SP-NEXT:    movhi r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp ugt float %a, %b
  ret i1 %1
}
define i1 @cmp_f_uge(float %a, float %b) {
; NONE-LABEL: cmp_f_uge:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmplt
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_uge:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it pl
; SP-NEXT:    movpl r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp uge float %a, %b
  ret i1 %1
}

define i1 @cmp_f_ult(float %a, float %b) {
; NONE-LABEL: cmp_f_ult:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpge
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_ult:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it lt
; SP-NEXT:    movlt r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp ult float %a, %b
  ret i1 %1
}
define i1 @cmp_f_ule(float %a, float %b) {
; NONE-LABEL: cmp_f_ule:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpgt
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_ule:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it le
; SP-NEXT:    movle r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp ule float %a, %b
  ret i1 %1
}

define i1 @cmp_f_une(float %a, float %b) {
; NONE-LABEL: cmp_f_une:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpeq
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_une:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp une float %a, %b
  ret i1 %1
}

define i1 @cmp_f_uno(float %a, float %b) {
; NONE-LABEL: cmp_f_uno:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_fcmpun
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_f_uno:
; SP:       @ %bb.0:
; SP-NEXT:    vcmp.f32 s0, s1
; SP-NEXT:    movs r0, #0
; SP-NEXT:    vmrs APSR_nzcv, fpscr
; SP-NEXT:    it vs
; SP-NEXT:    movvs r0, #1
; SP-NEXT:    bx lr
  %1 = fcmp uno float %a, %b
  ret i1 %1
}
define i1 @cmp_f_true(float %a, float %b) {
; CHECK-LABEL: cmp_f_true:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r0, #1
; CHECK-NEXT:    bx lr
  %1 = fcmp true float %a, %b
  ret i1 %1
}

define i1 @cmp_d_false(double %a, double %b) {
; CHECK-LABEL: cmp_d_false:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r0, #0
; CHECK-NEXT:    bx lr
  %1 = fcmp false double %a, %b
  ret i1 %1
}
define i1 @cmp_d_oeq(double %a, double %b) {
; NONE-LABEL: cmp_d_oeq:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpeq
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_oeq:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpeq
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp oeq double %a, %b
  ret i1 %1
}
define i1 @cmp_d_ogt(double %a, double %b) {
; NONE-LABEL: cmp_d_ogt:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpgt
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_ogt:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpgt
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp ogt double %a, %b
  ret i1 %1
}

define i1 @cmp_d_oge(double %a, double %b) {
; NONE-LABEL: cmp_d_oge:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpge
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_oge:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpge
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp oge double %a, %b
  ret i1 %1
}
define i1 @cmp_d_olt(double %a, double %b) {
; NONE-LABEL: cmp_d_olt:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmplt
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_olt:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmplt
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp olt double %a, %b
  ret i1 %1
}

define i1 @cmp_d_ole(double %a, double %b) {
; NONE-LABEL: cmp_d_ole:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmple
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_ole:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmple
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp ole double %a, %b
  ret i1 %1
}

define i1 @cmp_d_one(double %a, double %b) {
; NONE-LABEL: cmp_d_one:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r4, r5, r6, r7, r8, lr}
; NONE-NEXT:    push.w {r4, r5, r6, r7, r8, lr}
; NONE-NEXT:    mov r4, r3
; NONE-NEXT:    mov r5, r2
; NONE-NEXT:    mov r6, r1
; NONE-NEXT:    mov r7, r0
; NONE-NEXT:    bl __aeabi_dcmpeq
; NONE-NEXT:    mov r8, r0
; NONE-NEXT:    mov r0, r7
; NONE-NEXT:    mov r1, r6
; NONE-NEXT:    mov r2, r5
; NONE-NEXT:    mov r3, r4
; NONE-NEXT:    bl __aeabi_dcmpun
; NONE-NEXT:    orr.w r0, r0, r8
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop.w {r4, r5, r6, r7, r8, pc}
;
; SP-LABEL: cmp_d_one:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r4, r5, r6, r7, r8, lr}
; SP-NEXT:    push.w {r4, r5, r6, r7, r8, lr}
; SP-NEXT:    vmov r4, r5, d0
; SP-NEXT:    vmov r6, r7, d1
; SP-NEXT:    mov r0, r4
; SP-NEXT:    mov r1, r5
; SP-NEXT:    mov r2, r6
; SP-NEXT:    mov r3, r7
; SP-NEXT:    bl __aeabi_dcmpun
; SP-NEXT:    eor r8, r0, #1
; SP-NEXT:    mov r0, r4
; SP-NEXT:    mov r1, r5
; SP-NEXT:    mov r2, r6
; SP-NEXT:    mov r3, r7
; SP-NEXT:    bl __aeabi_dcmpeq
; SP-NEXT:    clz r0, r0
; SP-NEXT:    lsrs r0, r0, #5
; SP-NEXT:    ands.w r0, r0, r8
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop.w {r4, r5, r6, r7, r8, pc}

  %1 = fcmp one double %a, %b
  ret i1 %1
}

define i1 @cmp_d_ord(double %a, double %b) {
; NONE-LABEL: cmp_d_ord:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpun
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_ord:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpun
; SP-NEXT:    clz r0, r0
; SP-NEXT:    lsrs r0, r0, #5
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp ord double %a, %b
  ret i1 %1
}

define i1 @cmp_d_ugt(double %a, double %b) {
; NONE-LABEL: cmp_d_ugt:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmple
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_ugt:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmple
; SP-NEXT:    clz r0, r0
; SP-NEXT:    lsrs r0, r0, #5
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp ugt double %a, %b
  ret i1 %1
}

define i1 @cmp_d_ult(double %a, double %b) {
; NONE-LABEL: cmp_d_ult:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpge
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_ult:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpge
; SP-NEXT:    clz r0, r0
; SP-NEXT:    lsrs r0, r0, #5
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp ult double %a, %b
  ret i1 %1
}

define i1 @cmp_d_uno(double %a, double %b) {
; NONE-LABEL: cmp_d_uno:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpun
; NONE-NEXT:    cmp r0, #0
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_uno:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpun
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp uno double %a, %b
  ret i1 %1
}
define i1 @cmp_d_true(double %a, double %b) {
; CHECK-LABEL: cmp_d_true:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r0, #1
; CHECK-NEXT:    bx lr
  %1 = fcmp true double %a, %b
  ret i1 %1
}
define i1 @cmp_d_ueq(double %a, double %b) {
; NONE-LABEL: cmp_d_ueq:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r4, r5, r6, r7, r8, lr}
; NONE-NEXT:    push.w {r4, r5, r6, r7, r8, lr}
; NONE-NEXT:    mov r4, r3
; NONE-NEXT:    mov r5, r2
; NONE-NEXT:    mov r6, r1
; NONE-NEXT:    mov r7, r0
; NONE-NEXT:    bl __aeabi_dcmpeq
; NONE-NEXT:    mov r8, r0
; NONE-NEXT:    mov r0, r7
; NONE-NEXT:    mov r1, r6
; NONE-NEXT:    mov r2, r5
; NONE-NEXT:    mov r3, r4
; NONE-NEXT:    bl __aeabi_dcmpun
; NONE-NEXT:    orrs.w r0, r0, r8
; NONE-NEXT:    it ne
; NONE-NEXT:    movne r0, #1
; NONE-NEXT:    pop.w {r4, r5, r6, r7, r8, pc}
;
; SP-LABEL: cmp_d_ueq:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r4, r5, r6, r7, r8, lr}
; SP-NEXT:    push.w {r4, r5, r6, r7, r8, lr}
; SP-NEXT:    vmov r4, r5, d0
; SP-NEXT:    vmov r6, r8, d1
; SP-NEXT:    mov r0, r4
; SP-NEXT:    mov r1, r5
; SP-NEXT:    mov r2, r6
; SP-NEXT:    mov r3, r8
; SP-NEXT:    bl __aeabi_dcmpeq
; SP-NEXT:    mov r7, r0
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    mov r0, r4
; SP-NEXT:    mov r1, r5
; SP-NEXT:    mov r2, r6
; SP-NEXT:    mov r3, r8
; SP-NEXT:    it ne
; SP-NEXT:    movne r7, #1
; SP-NEXT:    bl __aeabi_dcmpun
; SP-NEXT:    cmp r0, #0
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    orrs r0, r7
; SP-NEXT:    it ne
; SP-NEXT:    movne r0, #1
; SP-NEXT:    pop.w {r4, r5, r6, r7, r8, pc}
  %1 = fcmp ueq double %a, %b
  ret i1 %1
}

define i1 @cmp_d_uge(double %a, double %b) {
; NONE-LABEL: cmp_d_uge:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmplt
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_uge:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmplt
; SP-NEXT:    clz r0, r0
; SP-NEXT:    lsrs r0, r0, #5
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp uge double %a, %b
  ret i1 %1
}

define i1 @cmp_d_ule(double %a, double %b) {
; NONE-LABEL: cmp_d_ule:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpgt
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_ule:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpgt
; SP-NEXT:    clz r0, r0
; SP-NEXT:    lsrs r0, r0, #5
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp ule double %a, %b
  ret i1 %1
}

define i1 @cmp_d_une(double %a, double %b) {
; NONE-LABEL: cmp_d_une:
; NONE:       @ %bb.0:
; NONE-NEXT:    .save {r7, lr}
; NONE-NEXT:    push {r7, lr}
; NONE-NEXT:    bl __aeabi_dcmpeq
; NONE-NEXT:    clz r0, r0
; NONE-NEXT:    lsrs r0, r0, #5
; NONE-NEXT:    pop {r7, pc}
;
; SP-LABEL: cmp_d_une:
; SP:       @ %bb.0:
; SP-NEXT:    .save {r7, lr}
; SP-NEXT:    push {r7, lr}
; SP-NEXT:    vmov r0, r1, d0
; SP-NEXT:    vmov r2, r3, d1
; SP-NEXT:    bl __aeabi_dcmpeq
; SP-NEXT:    clz r0, r0
; SP-NEXT:    lsrs r0, r0, #5
; SP-NEXT:    pop {r7, pc}
  %1 = fcmp une double %a, %b
  ret i1 %1
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; DP: {{.*}}
; HARD: {{.*}}
