; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=thumbv7-apple-darwin -arm-atomic-cfg-tidy=0 -mcpu=cortex-a8 -relocation-model=pic -frame-pointer=all | FileCheck %s
; rdar://7352504

%0 = type { i16, i8, i8 }
%1 = type { [2 x i32], [2 x i32] }
%2 = type { ptr }
%struct.FILE_POS = type { i8, i8, i16, i32 }
%struct.GAP = type { i8, i8, i16 }
%struct.LIST = type { ptr, ptr }
%struct.STYLE = type { %union.anon, %union.anon, i16, i16, i32 }
%struct.head_type = type { [2 x %struct.LIST], %union.FIRST_UNION, %union.SECOND_UNION, %union.THIRD_UNION, %union.FOURTH_UNION, ptr, %2, ptr, ptr, ptr, ptr, ptr, ptr, ptr, ptr, i32 }
%union.FIRST_UNION = type { %struct.FILE_POS }
%union.FOURTH_UNION = type { %struct.STYLE }
%union.SECOND_UNION = type { %0 }
%union.THIRD_UNION = type { %1 }
%union.anon = type { %struct.GAP }
%union.rec = type { %struct.head_type }

@zz_hold = external global ptr            ; <ptr> [#uses=2]
@zz_res = external global ptr             ; <ptr> [#uses=1]

define ptr @Manifest(ptr %x, ptr %env, ptr %style, ptr %bthr, ptr %fthr, ptr %target, ptr %crs, i32 %ok, i32 %need_expand, ptr %enclose, i32 %fcr) nounwind {
; CHECK-LABEL: Manifest:
; CHECK:       @ %bb.0: @ %entry
; CHECK-NEXT:    push {r4, r5, r6, r7, lr}
; CHECK-NEXT:    add r7, sp, #12
; CHECK-NEXT:    push.w {r8, r10, r11}
; CHECK-NEXT:    sub sp, #292
; CHECK-NEXT:    add.w r10, r7, #8
; CHECK-NEXT:    movs r5, #0
; CHECK-NEXT:    ldr.w r12, [r7, #28]
; CHECK-NEXT:    cmp r5, #0
; CHECK-NEXT:    ldm.w r10, {r4, r9, r10}
; CHECK-NEXT:    ldrd r8, lr, [r7, #20]
; CHECK-NEXT:    ittt ne
; CHECK-NEXT:    addne sp, #292
; CHECK-NEXT:    popne.w {r8, r10, r11}
; CHECK-NEXT:    popne {r4, r5, r6, r7, pc}
; CHECK-NEXT:  LBB0_1: @ %bb20
; CHECK-NEXT:    movs r5, #1
; CHECK-NEXT:    cmp r5, #0
; CHECK-NEXT:    bne LBB0_4
; CHECK-NEXT:  @ %bb.2: @ %bb20
; CHECK-NEXT:    beq LBB0_5
; CHECK-NEXT:  @ %bb.3: @ %bb420
; CHECK-NEXT:    movw r5, :lower16:(L_zz_hold$non_lazy_ptr-(LPC0_0+4))
; CHECK-NEXT:    movt r5, :upper16:(L_zz_hold$non_lazy_ptr-(LPC0_0+4))
; CHECK-NEXT:    movw r11, :lower16:(L_zz_res$non_lazy_ptr-(LPC0_1+4))
; CHECK-NEXT:  LPC0_0:
; CHECK-NEXT:    add r5, pc
; CHECK-NEXT:    movt r11, :upper16:(L_zz_res$non_lazy_ptr-(LPC0_1+4))
; CHECK-NEXT:  LPC0_1:
; CHECK-NEXT:    add r11, pc
; CHECK-NEXT:    ldr r5, [r5]
; CHECK-NEXT:    str r5, [sp, #32] @ 4-byte Spill
; CHECK-NEXT:    ldr.w r5, [r11]
; CHECK-NEXT:    mov.w r11, #0
; CHECK-NEXT:    str r5, [sp, #28] @ 4-byte Spill
; CHECK-NEXT:    ldr r5, [sp, #32] @ 4-byte Reload
; CHECK-NEXT:    str.w r11, [r5]
; CHECK-NEXT:    movs r5, #0
; CHECK-NEXT:    ldr r6, [sp, #28] @ 4-byte Reload
; CHECK-NEXT:    str r5, [r6]
; CHECK-NEXT:    ldr r5, [sp, #32] @ 4-byte Reload
; CHECK-NEXT:    str r0, [r5]
; CHECK-NEXT:    ldr r0, [r7, #32]
; CHECK-NEXT:    stm.w sp, {r4, r9, r10}
; CHECK-NEXT:    strd r8, lr, [sp, #12]
; CHECK-NEXT:    str.w r12, [sp, #20]
; CHECK-NEXT:    str r0, [sp, #24]
; CHECK-NEXT:    bl _Manifest
; CHECK-NEXT:    trap
; CHECK-NEXT:  LBB0_4: @ %bb20
; CHECK-NEXT:    itt ne
; CHECK-NEXT:    movne r0, #0
; CHECK-NEXT:    cmpne r0, #0
; CHECK-NEXT:  LBB0_5: @ %bb20
; CHECK-NEXT:    trap
entry:
  %xgaps.i = alloca [32 x ptr], align 4   ; <ptr> [#uses=0]
  %ycomp.i = alloca [32 x ptr], align 4   ; <ptr> [#uses=0]
  br label %bb20

bb20:                                             ; preds = %entry
  switch i32 undef, label %bb1287 [
    i32 110, label %bb119
    i32 120, label %bb119
    i32 210, label %bb420
    i32 230, label %bb420
    i32 450, label %bb438
    i32 460, label %bb438
    i32 550, label %bb533
    i32 560, label %bb569
    i32 640, label %bb745
    i32 780, label %bb1098
  ]

bb119:                                            ; preds = %bb20, %bb20
  unreachable

bb420:                                            ; preds = %bb20, %bb20
  store volatile ptr null, ptr @zz_hold, align 4
  store ptr null, ptr @zz_res, align 4
  store volatile ptr %x, ptr @zz_hold, align 4
  %0 = call  ptr @Manifest(ptr undef, ptr %env, ptr %style, ptr %bthr, ptr %fthr, ptr %target, ptr %crs, i32 %ok, i32 %need_expand, ptr %enclose, i32 %fcr) nounwind ; <ptr> [#uses=0]
  unreachable

bb438:                                            ; preds = %bb20, %bb20
  unreachable

bb533:                                            ; preds = %bb20
  ret ptr %x

bb569:                                            ; preds = %bb20
  unreachable

bb745:                                            ; preds = %bb20
  unreachable

bb1098:                                           ; preds = %bb20
  unreachable

bb1287:                                           ; preds = %bb20
  unreachable
}
