# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=thumbv8.1m.main-none-none-eabi -mattr=+mve.fp -run-pass arm-mve-vpt %s -o - | FileCheck %s

---
name:            vpt_2_blocks_ctrl_flow
alignment:       4
exposesReturnsTwice: false
legalized:       false
regBankSelected: false
selected:        false
failedISel:      false
tracksRegLiveness: true
hasWinCFI:       false
registers:       []
liveins:
  - { reg: '$q0', virtual-reg: '' }
  - { reg: '$q1', virtual-reg: '' }
  - { reg: '$q2', virtual-reg: '' }
  - { reg: '$r0', virtual-reg: '' }
frameInfo:
  isFrameAddressTaken: false
  isReturnAddressTaken: false
  hasStackMap:     false
  hasPatchPoint:   false
  stackSize:       0
  offsetAdjustment: 0
  maxAlignment:    0
  adjustsStack:    false
  hasCalls:        false
  stackProtector:  ''
  maxCallFrameSize: 0
  cvBytesOfCalleeSavedRegisters: 0
  hasOpaqueSPAdjustment: false
  hasVAStart:      false
  hasMustTailInVarArgFunc: false
  localFrameSize:  0
  savePoint:       []
  restorePoint:    []
fixedStack:      []
stack:           []
constants:       []
body:             |
  ; CHECK-LABEL: name: vpt_2_blocks_ctrl_flow
  ; CHECK: bb.0:
  ; CHECK:   successors: %bb.1(0x80000000)
  ; CHECK:   liveins: $q0, $q1, $q2, $r0
  ; CHECK:   $vpr = VMSR_P0 killed $r0, 14 /* CC::al */, $noreg
  ; CHECK:   $q3 = MVE_VORR $q0, $q0, 0, $noreg, $noreg, undef $q3
  ; CHECK:   BUNDLE implicit-def $q3, implicit-def $q1, implicit $vpr, implicit killed $q1, implicit $q2, implicit killed $q3 {
  ; CHECK:     MVE_VPST 4, implicit $vpr
  ; CHECK:     renamable $q3 = nnan ninf nsz MVE_VMINNMf32 killed renamable $q1, renamable $q2, 1, renamable $vpr, $noreg, killed renamable $q3
  ; CHECK:     renamable $q1 = nnan ninf nsz MVE_VMINNMf32 internal renamable $q3, internal renamable $q3, 1, renamable $vpr, $noreg, undef renamable $q1
  ; CHECK:   }
  ; CHECK: bb.1:
  ; CHECK:   liveins: $q0, $q1, $q2, $q3, $vpr
  ; CHECK:   BUNDLE implicit-def dead $q3, implicit-def $q0, implicit killed $vpr, implicit killed $q1, implicit killed $q2, implicit killed $q3, implicit killed $q0 {
  ; CHECK:     MVE_VPST 4, implicit $vpr
  ; CHECK:     renamable $q3 = nnan ninf nsz MVE_VMINNMf32 killed renamable $q1, renamable $q2, 1, renamable $vpr, $noreg, killed renamable $q3
  ; CHECK:     renamable $q0 = nnan ninf nsz MVE_VMINNMf32 internal killed renamable $q3, killed renamable $q2, 1, killed renamable $vpr, $noreg, killed renamable $q0
  ; CHECK:   }
  ; CHECK:   tBX_RET 14 /* CC::al */, $noreg, implicit $q0
  bb.0:
    liveins: $q0, $q1, $q2, $r0

    $vpr = VMSR_P0 killed $r0, 14, $noreg
    $q3 = MVE_VORR $q0, $q0, 0, $noreg, $noreg, undef $q3
    renamable $q3 = nnan ninf nsz MVE_VMINNMf32 killed renamable $q1, renamable $q2, 1, renamable $vpr, $noreg, killed renamable $q3
    renamable $q1 = nnan ninf nsz MVE_VMINNMf32 renamable $q3, renamable $q3, 1, renamable $vpr, $noreg, undef renamable $q1

  bb.1:
    liveins: $q0, $q1, $q2, $q3, $vpr

    renamable $q3 = nnan ninf nsz MVE_VMINNMf32 killed renamable $q1, renamable $q2, 1, renamable $vpr, $noreg, killed renamable $q3
    renamable $q0 = nnan ninf nsz MVE_VMINNMf32 killed renamable $q3, killed renamable $q2, 1, killed renamable $vpr, $noreg, killed renamable $q0
    tBX_RET 14, $noreg, implicit $q0

...
