; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=thumbv8.1m.main-none-none-eabi -mattr=+mve.fp,+fp64 -verify-machineinstrs %s -o - | FileCheck %s

declare float @llvm.vector.reduce.fdot.v4f32(float, <4 x float>, <4 x float>)
declare double @llvm.vector.reduce.fdot.v4f64(double, <4 x double>, <4 x double>)

; Default: sequential vmla.f32 chain (mul + accumulate).
define arm_aapcs_vfpcc float @fdot_f32(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: fdot_f32:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmla.f32 s0, s4, s8
; CHECK-NEXT:    vmla.f32 s0, s5, s9
; CHECK-NEXT:    vmla.f32 s0, s6, s10
; CHECK-NEXT:    vmla.f32 s0, s7, s11
; CHECK-NEXT:    bx lr
  %res = call float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With contract: vfma.f32 chain.
define arm_aapcs_vfpcc float @fdot_f32_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: fdot_f32_contract:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vfma.f32 s0, s4, s8
; CHECK-NEXT:    vfma.f32 s0, s5, s9
; CHECK-NEXT:    vfma.f32 s0, s6, s10
; CHECK-NEXT:    vfma.f32 s0, s7, s11
; CHECK-NEXT:    bx lr
  %res = call contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

; With reassoc: tree-reduction vmul.f32 + vadd.f32 (unordered).
define arm_aapcs_vfpcc float @fdot_f32_reassoc(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: fdot_f32_reassoc:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmul.f32 q1, q1, q2
; CHECK-NEXT:    vadd.f32 s2, s6, s7
; CHECK-NEXT:    vadd.f32 s4, s4, s5
; CHECK-NEXT:    vadd.f32 s2, s4, s2
; CHECK-NEXT:    vadd.f32 s0, s0, s2
; CHECK-NEXT:    bx lr
  %res = call reassoc float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

define arm_aapcs_vfpcc float @fdot_f32_reassoc_contract(float %acc, <4 x float> %a, <4 x float> %b) {
; CHECK-LABEL: fdot_f32_reassoc_contract:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmul.f32 q1, q1, q2
; CHECK-NEXT:    vadd.f32 s2, s6, s7
; CHECK-NEXT:    vadd.f32 s4, s4, s5
; CHECK-NEXT:    vadd.f32 s2, s4, s2
; CHECK-NEXT:    vadd.f32 s0, s0, s2
; CHECK-NEXT:    bx lr
  %res = call reassoc contract float @llvm.vector.reduce.fdot.v4f32(float %acc, <4 x float> %a, <4 x float> %b)
  ret float %res
}

define arm_aapcs_vfpcc double @fdot_f64(double %acc, <4 x double> %a, <4 x double> %b) {
; CHECK-LABEL: fdot_f64:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vmla.f64 d0, d2, d6
; CHECK-NEXT:    mov r0, sp
; CHECK-NEXT:    vmla.f64 d0, d3, d7
; CHECK-NEXT:    vldrw.u32 q1, [r0]
; CHECK-NEXT:    vmla.f64 d0, d4, d2
; CHECK-NEXT:    vmla.f64 d0, d5, d3
; CHECK-NEXT:    bx lr
  %res = call double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define arm_aapcs_vfpcc double @fdot_f64_contract(double %acc, <4 x double> %a, <4 x double> %b) {
; CHECK-LABEL: fdot_f64_contract:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    vfma.f64 d0, d2, d6
; CHECK-NEXT:    mov r0, sp
; CHECK-NEXT:    vfma.f64 d0, d3, d7
; CHECK-NEXT:    vldrw.u32 q1, [r0]
; CHECK-NEXT:    vfma.f64 d0, d4, d2
; CHECK-NEXT:    vfma.f64 d0, d5, d3
; CHECK-NEXT:    bx lr
  %res = call contract double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define arm_aapcs_vfpcc double @fdot_f64_reassoc(double %acc, <4 x double> %a, <4 x double> %b) {
; CHECK-LABEL: fdot_f64_reassoc:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    .vsave {d8, d9}
; CHECK-NEXT:    vpush {d8, d9}
; CHECK-NEXT:    add r0, sp, #16
; CHECK-NEXT:    vmul.f64 d3, d3, d7
; CHECK-NEXT:    vldrw.u32 q4, [r0]
; CHECK-NEXT:    vmul.f64 d1, d5, d9
; CHECK-NEXT:    vmla.f64 d1, d4, d8
; CHECK-NEXT:    vmla.f64 d3, d2, d6
; CHECK-NEXT:    vadd.f64 d1, d3, d1
; CHECK-NEXT:    vadd.f64 d0, d0, d1
; CHECK-NEXT:    vpop {d8, d9}
; CHECK-NEXT:    bx lr
  %res = call reassoc double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}

define arm_aapcs_vfpcc double @fdot_f64_reassoc_contract(double %acc, <4 x double> %a, <4 x double> %b) {
; CHECK-LABEL: fdot_f64_reassoc_contract:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    .vsave {d8, d9}
; CHECK-NEXT:    vpush {d8, d9}
; CHECK-NEXT:    add r0, sp, #16
; CHECK-NEXT:    vldrw.u32 q4, [r0]
; CHECK-NEXT:    vfma.f64 d0, d5, d9
; CHECK-NEXT:    vfma.f64 d0, d4, d8
; CHECK-NEXT:    vfma.f64 d0, d3, d7
; CHECK-NEXT:    vfma.f64 d0, d2, d6
; CHECK-NEXT:    vpop {d8, d9}
; CHECK-NEXT:    bx lr
  %res = call reassoc contract double @llvm.vector.reduce.fdot.v4f64(double %acc, <4 x double> %a, <4 x double> %b)
  ret double %res
}
