; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+d,+zvfh,+zfbfmin,+zvfbfmin,+v -target-abi=ilp32d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFH
; RUN: llc -mtriple=riscv64 -mattr=+d,+zvfh,+zfbfmin,+zvfbfmin,+v -target-abi=lp64d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFH
; RUN: llc -mtriple=riscv32 -mattr=+d,+zfhmin,+zvfhmin,+experimental-zvfbfa,+v \
; RUN:     -target-abi=ilp32d -verify-machineinstrs < %s | FileCheck %s \
; RUN:     --check-prefixes=CHECK,ZVFBFA
; RUN: llc -mtriple=riscv64 -mattr=+d,+zfhmin,+zvfhmin,+experimental-zvfbfa,+v \
; RUN:     -target-abi=lp64d -verify-machineinstrs < %s | FileCheck %s \
; RUN:     --check-prefixes=CHECK,ZVFBFA

; This tests a mix of vfmacc and vfmadd by using different operand orders to
; trigger commuting in TwoAddressInstructionPass.

define <1 x bfloat> @vfmadd_vv_v1bf16(<1 x bfloat> %va, <1 x bfloat> %vb, <1 x bfloat> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v1bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v11, v10
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v9
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v9, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFH-NEXT:    vfmadd.vv v9, v10, v11
; ZVFH-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v1bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 1, e16alt, mf4, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v8, v9, v10
; ZVFBFA-NEXT:    ret
  %vd = call <1 x bfloat> @llvm.experimental.constrained.fma.v1bf16(<1 x bfloat> %va, <1 x bfloat> %vb, <1 x bfloat> %vc, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <1 x bfloat> %vd
}

define <2 x bfloat> @vfmadd_vv_v2bf16(<2 x bfloat> %va, <2 x bfloat> %vb, <2 x bfloat> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v2bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v11, v9
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v9, v10
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFH-NEXT:    vfmadd.vv v10, v9, v11
; ZVFH-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v10
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v2bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 2, e16alt, mf4, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v8, v10, v9
; ZVFBFA-NEXT:    ret
  %vd = call <2 x bfloat> @llvm.experimental.constrained.fma.v2bf16(<2 x bfloat> %va, <2 x bfloat> %vc, <2 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <2 x bfloat> %vd
}

define <4 x bfloat> @vfmadd_vv_v4bf16(<4 x bfloat> %va, <4 x bfloat> %vb, <4 x bfloat> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v4bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v11, v10
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v8
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v12, v9
; ZVFH-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVFH-NEXT:    vfmadd.vv v12, v10, v11
; ZVFH-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v12
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v4bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 4, e16alt, mf2, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v8, v9, v10
; ZVFBFA-NEXT:    ret
  %vd = call <4 x bfloat> @llvm.experimental.constrained.fma.v4bf16(<4 x bfloat> %vb, <4 x bfloat> %va, <4 x bfloat> %vc, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <4 x bfloat> %vd
}

define <8 x bfloat> @vfmadd_vv_v8bf16(<8 x bfloat> %va, <8 x bfloat> %vb, <8 x bfloat> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v8bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v12, v8
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v14, v10
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v9
; ZVFH-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; ZVFH-NEXT:    vfmadd.vv v10, v14, v12
; ZVFH-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v10
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v8bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 8, e16alt, m1, ta, ma
; ZVFBFA-NEXT:    vfmacc.vv v8, v10, v9
; ZVFBFA-NEXT:    ret
  %vd = call <8 x bfloat> @llvm.experimental.constrained.fma.v8bf16(<8 x bfloat> %vb, <8 x bfloat> %vc, <8 x bfloat> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <8 x bfloat> %vd
}

define <16 x bfloat> @vfmadd_vv_v16bf16(<16 x bfloat> %va, <16 x bfloat> %vb, <16 x bfloat> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v16bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v16, v10
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v20, v8
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v24, v12
; ZVFH-NEXT:    vsetvli zero, zero, e32, m4, ta, ma
; ZVFH-NEXT:    vfmadd.vv v24, v20, v16
; ZVFH-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v24
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v16bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 16, e16alt, m2, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v8, v12, v10
; ZVFBFA-NEXT:    ret
  %vd = call <16 x bfloat> @llvm.experimental.constrained.fma.v16bf16(<16 x bfloat> %vc, <16 x bfloat> %va, <16 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <16 x bfloat> %vd
}

define <32 x bfloat> @vfmadd_vv_v32bf16(<32 x bfloat> %va, <32 x bfloat> %vb, <32 x bfloat> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v32bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    li a0, 32
; ZVFH-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v24, v8
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v0, v16
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v16, v12
; ZVFH-NEXT:    vsetvli zero, zero, e32, m8, ta, ma
; ZVFH-NEXT:    vfmadd.vv v16, v0, v24
; ZVFH-NEXT:    vsetvli zero, zero, e16, m4, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v16
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v32bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    li a0, 32
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, m4, ta, ma
; ZVFBFA-NEXT:    vfmacc.vv v8, v16, v12
; ZVFBFA-NEXT:    ret
  %vd = call <32 x bfloat> @llvm.experimental.constrained.fma.v32bf16(<32 x bfloat> %vb, <32 x bfloat> %vc, <32 x bfloat> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <32 x bfloat> %vd
}

define <2 x half> @vfmadd_vv_v2f16(<2 x half> %va, <2 x half> %vb, <2 x half> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v2f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFH-NEXT:    vfmadd.vv v8, v10, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v2f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v11, v9
; ZVFBFA-NEXT:    vfwcvt.f.f.v v9, v10
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v10, v9, v11
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v10
; ZVFBFA-NEXT:    ret
  %vd = call <2 x half> @llvm.experimental.constrained.fma.v2f16(<2 x half> %va, <2 x half> %vc, <2 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <2 x half> %vd
}

define <2 x half> @vfmadd_vf_v2f16(<2 x half> %va, <2 x half> %vb, half %c) strictfp {
; ZVFH-LABEL: vfmadd_vf_v2f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFH-NEXT:    vfmacc.vf v8, fa0, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vf_v2f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v8
; ZVFBFA-NEXT:    vmv.v.x v8, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v11, v9
; ZVFBFA-NEXT:    vfwcvt.f.f.v v9, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v9, v11, v10
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v9
; ZVFBFA-NEXT:    ret
  %head = insertelement <2 x half> poison, half %c, i32 0
  %splat = shufflevector <2 x half> %head, <2 x half> poison, <2 x i32> zeroinitializer
  %vd = call <2 x half> @llvm.experimental.constrained.fma.v2f16(<2 x half> %vb, <2 x half> %splat, <2 x half> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <2 x half> %vd
}

define <4 x half> @vfmadd_vv_v4f16(<4 x half> %va, <4 x half> %vb, <4 x half> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v4f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFH-NEXT:    vfmadd.vv v8, v9, v10
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v4f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v11, v10
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v9
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v12, v10, v11
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v12
; ZVFBFA-NEXT:    ret
  %vd = call <4 x half> @llvm.experimental.constrained.fma.v4f16(<4 x half> %vb, <4 x half> %va, <4 x half> %vc, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <4 x half> %vd
}

define <4 x half> @vfmadd_vf_v4f16(<4 x half> %va, <4 x half> %vb, half %c) strictfp {
; ZVFH-LABEL: vfmadd_vf_v4f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFH-NEXT:    vfmadd.vf v8, fa0, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vf_v4f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v9
; ZVFBFA-NEXT:    vmv.v.x v9, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v11, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v9
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v12, v11, v10
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v12
; ZVFBFA-NEXT:    ret
  %head = insertelement <4 x half> poison, half %c, i32 0
  %splat = shufflevector <4 x half> %head, <4 x half> poison, <4 x i32> zeroinitializer
  %vd = call <4 x half> @llvm.experimental.constrained.fma.v4f16(<4 x half> %va, <4 x half> %splat, <4 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <4 x half> %vd
}

define <8 x half> @vfmadd_vv_v8f16(<8 x half> %va, <8 x half> %vb, <8 x half> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v8f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFH-NEXT:    vfmacc.vv v8, v10, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v8f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v14, v10
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v9
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v10, v14, v12
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v10
; ZVFBFA-NEXT:    ret
  %vd = call <8 x half> @llvm.experimental.constrained.fma.v8f16(<8 x half> %vb, <8 x half> %vc, <8 x half> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <8 x half> %vd
}

define <8 x half> @vfmadd_vf_v8f16(<8 x half> %va, <8 x half> %vb, half %c) strictfp {
; ZVFH-LABEL: vfmadd_vf_v8f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFH-NEXT:    vfmacc.vf v8, fa0, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vf_v8f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v8
; ZVFBFA-NEXT:    vmv.v.x v8, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v9
; ZVFBFA-NEXT:    vfwcvt.f.f.v v14, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v14, v12, v10
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v14
; ZVFBFA-NEXT:    ret
  %head = insertelement <8 x half> poison, half %c, i32 0
  %splat = shufflevector <8 x half> %head, <8 x half> poison, <8 x i32> zeroinitializer
  %vd = call <8 x half> @llvm.experimental.constrained.fma.v8f16(<8 x half> %vb, <8 x half> %splat, <8 x half> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <8 x half> %vd
}

define <16 x half> @vfmadd_vv_v16f16(<16 x half> %va, <16 x half> %vb, <16 x half> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v16f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFH-NEXT:    vfmadd.vv v8, v12, v10
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v16f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v16, v10
; ZVFBFA-NEXT:    vfwcvt.f.f.v v20, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v24, v12
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m4, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v24, v20, v16
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v24
; ZVFBFA-NEXT:    ret
  %vd = call <16 x half> @llvm.experimental.constrained.fma.v16f16(<16 x half> %vc, <16 x half> %va, <16 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <16 x half> %vd
}

define <16 x half> @vfmadd_vf_v16f16(<16 x half> %va, <16 x half> %vb, half %c) strictfp {
; ZVFH-LABEL: vfmadd_vf_v16f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFH-NEXT:    vfmadd.vf v8, fa0, v10
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vf_v16f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v10
; ZVFBFA-NEXT:    vmv.v.x v10, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v16, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v20, v10
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m4, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v20, v16, v12
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v20
; ZVFBFA-NEXT:    ret
  %head = insertelement <16 x half> poison, half %c, i32 0
  %splat = shufflevector <16 x half> %head, <16 x half> poison, <16 x i32> zeroinitializer
  %vd = call <16 x half> @llvm.experimental.constrained.fma.v16f16(<16 x half> %va, <16 x half> %splat, <16 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <16 x half> %vd
}

define <32 x half> @vfmadd_vv_v32f16(<32 x half> %va, <32 x half> %vb, <32 x half> %vc) strictfp {
; ZVFH-LABEL: vfmadd_vv_v32f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    li a0, 32
; ZVFH-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFH-NEXT:    vfmacc.vv v8, v16, v12
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vv_v32f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    addi sp, sp, -16
; ZVFBFA-NEXT:    .cfi_def_cfa_offset 16
; ZVFBFA-NEXT:    csrr a0, vlenb
; ZVFBFA-NEXT:    slli a0, a0, 2
; ZVFBFA-NEXT:    sub sp, sp, a0
; ZVFBFA-NEXT:    .cfi_escape 0x0f, 0x0d, 0x72, 0x00, 0x11, 0x10, 0x22, 0x11, 0x04, 0x92, 0xa2, 0x38, 0x00, 0x1e, 0x22 # sp + 16 + 4 * vlenb
; ZVFBFA-NEXT:    addi a0, sp, 16
; ZVFBFA-NEXT:    vs4r.v v16, (a0) # vscale x 32-byte Folded Spill
; ZVFBFA-NEXT:    li a0, 32
; ZVFBFA-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v16, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v0, v12
; ZVFBFA-NEXT:    addi a0, sp, 16
; ZVFBFA-NEXT:    vl4r.v v8, (a0) # vscale x 32-byte Folded Reload
; ZVFBFA-NEXT:    vfwcvt.f.f.v v24, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m8, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v24, v0, v16
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v24
; ZVFBFA-NEXT:    csrr a0, vlenb
; ZVFBFA-NEXT:    slli a0, a0, 2
; ZVFBFA-NEXT:    add sp, sp, a0
; ZVFBFA-NEXT:    .cfi_def_cfa sp, 16
; ZVFBFA-NEXT:    addi sp, sp, 16
; ZVFBFA-NEXT:    .cfi_def_cfa_offset 0
; ZVFBFA-NEXT:    ret
  %vd = call <32 x half> @llvm.experimental.constrained.fma.v32f16(<32 x half> %vc, <32 x half> %vb, <32 x half> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <32 x half> %vd
}

define <32 x half> @vfmadd_vf_v32f16(<32 x half> %va, <32 x half> %vb, half %c) strictfp {
; ZVFH-LABEL: vfmadd_vf_v32f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    li a0, 32
; ZVFH-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFH-NEXT:    vfmacc.vf v8, fa0, v12
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfmadd_vf_v32f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    li a0, 32
; ZVFBFA-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFBFA-NEXT:    vmv4r.v v4, v12
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vmv.v.x v12, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v16, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v24, v4
; ZVFBFA-NEXT:    vfwcvt.f.f.v v0, v12
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m8, ta, ma
; ZVFBFA-NEXT:    vfmadd.vv v0, v24, v16
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v0
; ZVFBFA-NEXT:    ret
  %head = insertelement <32 x half> poison, half %c, i32 0
  %splat = shufflevector <32 x half> %head, <32 x half> poison, <32 x i32> zeroinitializer
  %vd = call <32 x half> @llvm.experimental.constrained.fma.v32f16(<32 x half> %vb, <32 x half> %splat, <32 x half> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <32 x half> %vd
}

define <2 x float> @vfmadd_vv_v2f32(<2 x float> %va, <2 x float> %vb, <2 x float> %vc) strictfp {
; CHECK-LABEL: vfmadd_vv_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vfmadd.vv v8, v10, v9
; CHECK-NEXT:    ret
  %vd = call <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float> %va, <2 x float> %vc, <2 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <2 x float> %vd
}

define <2 x float> @vfmadd_vf_v2f32(<2 x float> %va, <2 x float> %vb, float %c) strictfp {
; CHECK-LABEL: vfmadd_vf_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vfmacc.vf v8, fa0, v9
; CHECK-NEXT:    ret
  %head = insertelement <2 x float> poison, float %c, i32 0
  %splat = shufflevector <2 x float> %head, <2 x float> poison, <2 x i32> zeroinitializer
  %vd = call <2 x float> @llvm.experimental.constrained.fma.v2f32(<2 x float> %vb, <2 x float> %splat, <2 x float> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <2 x float> %vd
}

define <4 x float> @vfmadd_vv_v4f32(<4 x float> %va, <4 x float> %vb, <4 x float> %vc) strictfp {
; CHECK-LABEL: vfmadd_vv_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vfmadd.vv v8, v9, v10
; CHECK-NEXT:    ret
  %vd = call <4 x float> @llvm.experimental.constrained.fma.v4f32(<4 x float> %vb, <4 x float> %va, <4 x float> %vc, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <4 x float> %vd
}

define <4 x float> @vfmadd_vf_v4f32(<4 x float> %va, <4 x float> %vb, float %c) strictfp {
; CHECK-LABEL: vfmadd_vf_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vfmadd.vf v8, fa0, v9
; CHECK-NEXT:    ret
  %head = insertelement <4 x float> poison, float %c, i32 0
  %splat = shufflevector <4 x float> %head, <4 x float> poison, <4 x i32> zeroinitializer
  %vd = call <4 x float> @llvm.experimental.constrained.fma.v4f32(<4 x float> %va, <4 x float> %splat, <4 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <4 x float> %vd
}

define <8 x float> @vfmadd_vv_v8f32(<8 x float> %va, <8 x float> %vb, <8 x float> %vc) strictfp {
; CHECK-LABEL: vfmadd_vv_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vfmacc.vv v8, v12, v10
; CHECK-NEXT:    ret
  %vd = call <8 x float> @llvm.experimental.constrained.fma.v8f32(<8 x float> %vb, <8 x float> %vc, <8 x float> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <8 x float> %vd
}

define <8 x float> @vfmadd_vf_v8f32(<8 x float> %va, <8 x float> %vb, float %c) strictfp {
; CHECK-LABEL: vfmadd_vf_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vfmacc.vf v8, fa0, v10
; CHECK-NEXT:    ret
  %head = insertelement <8 x float> poison, float %c, i32 0
  %splat = shufflevector <8 x float> %head, <8 x float> poison, <8 x i32> zeroinitializer
  %vd = call <8 x float> @llvm.experimental.constrained.fma.v8f32(<8 x float> %vb, <8 x float> %splat, <8 x float> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <8 x float> %vd
}

define <16 x float> @vfmadd_vv_v16f32(<16 x float> %va, <16 x float> %vb, <16 x float> %vc) strictfp {
; CHECK-LABEL: vfmadd_vv_v16f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vfmadd.vv v8, v16, v12
; CHECK-NEXT:    ret
  %vd = call <16 x float> @llvm.experimental.constrained.fma.v16f32(<16 x float> %vc, <16 x float> %va, <16 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <16 x float> %vd
}

define <16 x float> @vfmadd_vf_v16f32(<16 x float> %va, <16 x float> %vb, float %c) strictfp {
; CHECK-LABEL: vfmadd_vf_v16f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vfmadd.vf v8, fa0, v12
; CHECK-NEXT:    ret
  %head = insertelement <16 x float> poison, float %c, i32 0
  %splat = shufflevector <16 x float> %head, <16 x float> poison, <16 x i32> zeroinitializer
  %vd = call <16 x float> @llvm.experimental.constrained.fma.v16f32(<16 x float> %va, <16 x float> %splat, <16 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <16 x float> %vd
}

define <2 x double> @vfmadd_vv_v2f64(<2 x double> %va, <2 x double> %vb, <2 x double> %vc) strictfp {
; CHECK-LABEL: vfmadd_vv_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vfmadd.vv v8, v10, v9
; CHECK-NEXT:    ret
  %vd = call <2 x double> @llvm.experimental.constrained.fma.v2f64(<2 x double> %va, <2 x double> %vc, <2 x double> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <2 x double> %vd
}

define <2 x double> @vfmadd_vf_v2f64(<2 x double> %va, <2 x double> %vb, double %c) strictfp {
; CHECK-LABEL: vfmadd_vf_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vfmacc.vf v8, fa0, v9
; CHECK-NEXT:    ret
  %head = insertelement <2 x double> poison, double %c, i32 0
  %splat = shufflevector <2 x double> %head, <2 x double> poison, <2 x i32> zeroinitializer
  %vd = call <2 x double> @llvm.experimental.constrained.fma.v2f64(<2 x double> %vb, <2 x double> %splat, <2 x double> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <2 x double> %vd
}

define <4 x double> @vfmadd_vv_v4f64(<4 x double> %va, <4 x double> %vb, <4 x double> %vc) strictfp {
; CHECK-LABEL: vfmadd_vv_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vfmadd.vv v8, v10, v12
; CHECK-NEXT:    ret
  %vd = call <4 x double> @llvm.experimental.constrained.fma.v4f64(<4 x double> %vb, <4 x double> %va, <4 x double> %vc, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <4 x double> %vd
}

define <4 x double> @vfmadd_vf_v4f64(<4 x double> %va, <4 x double> %vb, double %c) strictfp {
; CHECK-LABEL: vfmadd_vf_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vfmadd.vf v8, fa0, v10
; CHECK-NEXT:    ret
  %head = insertelement <4 x double> poison, double %c, i32 0
  %splat = shufflevector <4 x double> %head, <4 x double> poison, <4 x i32> zeroinitializer
  %vd = call <4 x double> @llvm.experimental.constrained.fma.v4f64(<4 x double> %va, <4 x double> %splat, <4 x double> %vb, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <4 x double> %vd
}

define <8 x double> @vfmadd_vv_v8f64(<8 x double> %va, <8 x double> %vb, <8 x double> %vc) strictfp {
; CHECK-LABEL: vfmadd_vv_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vfmacc.vv v8, v16, v12
; CHECK-NEXT:    ret
  %vd = call <8 x double> @llvm.experimental.constrained.fma.v8f64(<8 x double> %vb, <8 x double> %vc, <8 x double> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <8 x double> %vd
}

define <8 x double> @vfmadd_vf_v8f64(<8 x double> %va, <8 x double> %vb, double %c) strictfp {
; CHECK-LABEL: vfmadd_vf_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vfmacc.vf v8, fa0, v12
; CHECK-NEXT:    ret
  %head = insertelement <8 x double> poison, double %c, i32 0
  %splat = shufflevector <8 x double> %head, <8 x double> poison, <8 x i32> zeroinitializer
  %vd = call <8 x double> @llvm.experimental.constrained.fma.v8f64(<8 x double> %vb, <8 x double> %splat, <8 x double> %va, metadata !"round.dynamic", metadata !"fpexcept.strict")
  ret <8 x double> %vd
}
