; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+v,+d,+zvfh,+zvfbfmin -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFH,ZVFH_RV32
; RUN: llc -mtriple=riscv64 -mattr=+v,+d,+zvfh,+zvfbfmin -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFH,ZVFH_RV64
; RUN: llc -mtriple=riscv32 -mattr=+v,+d,+zvfh,+experimental-zvfbfa -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFBFA,ZVFBFA_RV32
; RUN: llc -mtriple=riscv64 -mattr=+v,+d,+zvfh,+experimental-zvfbfa -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFBFA,ZVFBFA_RV64

define <1 x i8> @vp_splat_v1i8(i8 %val, <1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v1i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <1 x i8> @llvm.experimental.vp.splat.v1i8(i8 %val, <1 x i1> %m, i32 %evl)
  ret <1 x i8> %splat
}

define <2 x i8> @vp_splat_v2i8(i8 %val, <2 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v2i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, mf8, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <2 x i8> @llvm.experimental.vp.splat.v2i8(i8 %val, <2 x i1> %m, i32 %evl)
  ret <2 x i8> %splat
}

define <4 x i8> @vp_splat_v4i8(i8 %val, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v4i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, mf4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <4 x i8> @llvm.experimental.vp.splat.v4i8(i8 %val, <4 x i1> %m, i32 %evl)
  ret <4 x i8> %splat
}

define <8 x i8> @vp_splat_v8i8(i8 %val, <8 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v8i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <8 x i8> @llvm.experimental.vp.splat.v8i8(i8 %val, <8 x i1> %m, i32 %evl)
  ret <8 x i8> %splat
}

define <16 x i8> @vp_splat_v16i8(i8 %val, <16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v16i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <16 x i8> @llvm.experimental.vp.splat.v16i8(i8 %val, <16 x i1> %m, i32 %evl)
  ret <16 x i8> %splat
}

define <32 x i8> @vp_splat_v32i8(i8 %val, <32 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v32i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <32 x i8> @llvm.experimental.vp.splat.v32i8(i8 %val, <32 x i1> %m, i32 %evl)
  ret <32 x i8> %splat
}

define <64 x i8> @vp_splat_v64i8(i8 %val, <64 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v64i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e8, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <64 x i8> @llvm.experimental.vp.splat.v64i8(i8 %val, <64 x i1> %m, i32 %evl)
  ret <64 x i8> %splat
}

define <1 x i16> @vp_splat_v1i16(i16 %val, <1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v1i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <1 x i16> @llvm.experimental.vp.splat.v1i16(i16 %val, <1 x i1> %m, i32 %evl)
  ret <1 x i16> %splat
}

define <2 x i16> @vp_splat_v2i16(i16 %val, <2 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v2i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <2 x i16> @llvm.experimental.vp.splat.v2i16(i16 %val, <2 x i1> %m, i32 %evl)
  ret <2 x i16> %splat
}

define <4 x i16> @vp_splat_v4i16(i16 %val, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v4i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <4 x i16> @llvm.experimental.vp.splat.v4i16(i16 %val, <4 x i1> %m, i32 %evl)
  ret <4 x i16> %splat
}

define <8 x i16> @vp_splat_v8i16(i16 %val, <8 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v8i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <8 x i16> @llvm.experimental.vp.splat.v8i16(i16 %val, <8 x i1> %m, i32 %evl)
  ret <8 x i16> %splat
}

define <16 x i16> @vp_splat_v16i16(i16 %val, <16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v16i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <16 x i16> @llvm.experimental.vp.splat.v16i16(i16 %val, <16 x i1> %m, i32 %evl)
  ret <16 x i16> %splat
}

define <32 x i16> @vp_splat_v32i16(i16 %val, <32 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v32i16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <32 x i16> @llvm.experimental.vp.splat.v32i16(i16 %val, <32 x i1> %m, i32 %evl)
  ret <32 x i16> %splat
}

define <1 x i32> @vp_splat_v1i32(i32 %val, <1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v1i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <1 x i32> @llvm.experimental.vp.splat.v1i32(i32 %val, <1 x i1> %m, i32 %evl)
  ret <1 x i32> %splat
}

define <2 x i32> @vp_splat_v2i32(i32 %val, <2 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v2i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, mf2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <2 x i32> @llvm.experimental.vp.splat.v2i32(i32 %val, <2 x i1> %m, i32 %evl)
  ret <2 x i32> %splat
}

define <4 x i32> @vp_splat_v4i32(i32 %val, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v4i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m1, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <4 x i32> @llvm.experimental.vp.splat.v4i32(i32 %val, <4 x i1> %m, i32 %evl)
  ret <4 x i32> %splat
}

define <8 x i32> @vp_splat_v8i32(i32 %val, <8 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v8i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m2, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <8 x i32> @llvm.experimental.vp.splat.v8i32(i32 %val, <8 x i1> %m, i32 %evl)
  ret <8 x i32> %splat
}

define <16 x i32> @vp_splat_v16i32(i32 %val, <16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v16i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <16 x i32> @llvm.experimental.vp.splat.v16i32(i32 %val, <16 x i1> %m, i32 %evl)
  ret <16 x i32> %splat
}

define <1 x i64> @vp_splat_v1i64(i64 %val, <1 x i1> %m, i32 zeroext %evl) {
; ZVFH_RV32-LABEL: vp_splat_v1i64:
; ZVFH_RV32:       # %bb.0:
; ZVFH_RV32-NEXT:    addi sp, sp, -16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFH_RV32-NEXT:    sw a0, 8(sp)
; ZVFH_RV32-NEXT:    sw a1, 12(sp)
; ZVFH_RV32-NEXT:    addi a0, sp, 8
; ZVFH_RV32-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; ZVFH_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFH_RV32-NEXT:    addi sp, sp, 16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFH_RV32-NEXT:    ret
;
; ZVFH_RV64-LABEL: vp_splat_v1i64:
; ZVFH_RV64:       # %bb.0:
; ZVFH_RV64-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; ZVFH_RV64-NEXT:    vmv.v.x v8, a0
; ZVFH_RV64-NEXT:    ret
;
; ZVFBFA_RV32-LABEL: vp_splat_v1i64:
; ZVFBFA_RV32:       # %bb.0:
; ZVFBFA_RV32-NEXT:    addi sp, sp, -16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFBFA_RV32-NEXT:    sw a0, 8(sp)
; ZVFBFA_RV32-NEXT:    sw a1, 12(sp)
; ZVFBFA_RV32-NEXT:    addi a0, sp, 8
; ZVFBFA_RV32-NEXT:    vsetivli zero, 1, e64, m1, ta, ma
; ZVFBFA_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFBFA_RV32-NEXT:    addi sp, sp, 16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFBFA_RV32-NEXT:    ret
;
; ZVFBFA_RV64-LABEL: vp_splat_v1i64:
; ZVFBFA_RV64:       # %bb.0:
; ZVFBFA_RV64-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; ZVFBFA_RV64-NEXT:    vmv.v.x v8, a0
; ZVFBFA_RV64-NEXT:    ret
  %splat = call <1 x i64> @llvm.experimental.vp.splat.v1i64(i64 %val, <1 x i1> %m, i32 %evl)
  ret <1 x i64> %splat
}

define <2 x i64> @vp_splat_v2i64(i64 %val, <2 x i1> %m, i32 zeroext %evl) {
; ZVFH_RV32-LABEL: vp_splat_v2i64:
; ZVFH_RV32:       # %bb.0:
; ZVFH_RV32-NEXT:    addi sp, sp, -16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFH_RV32-NEXT:    sw a0, 8(sp)
; ZVFH_RV32-NEXT:    sw a1, 12(sp)
; ZVFH_RV32-NEXT:    addi a0, sp, 8
; ZVFH_RV32-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; ZVFH_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFH_RV32-NEXT:    addi sp, sp, 16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFH_RV32-NEXT:    ret
;
; ZVFH_RV64-LABEL: vp_splat_v2i64:
; ZVFH_RV64:       # %bb.0:
; ZVFH_RV64-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; ZVFH_RV64-NEXT:    vmv.v.x v8, a0
; ZVFH_RV64-NEXT:    ret
;
; ZVFBFA_RV32-LABEL: vp_splat_v2i64:
; ZVFBFA_RV32:       # %bb.0:
; ZVFBFA_RV32-NEXT:    addi sp, sp, -16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFBFA_RV32-NEXT:    sw a0, 8(sp)
; ZVFBFA_RV32-NEXT:    sw a1, 12(sp)
; ZVFBFA_RV32-NEXT:    addi a0, sp, 8
; ZVFBFA_RV32-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; ZVFBFA_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFBFA_RV32-NEXT:    addi sp, sp, 16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFBFA_RV32-NEXT:    ret
;
; ZVFBFA_RV64-LABEL: vp_splat_v2i64:
; ZVFBFA_RV64:       # %bb.0:
; ZVFBFA_RV64-NEXT:    vsetvli zero, a1, e64, m1, ta, ma
; ZVFBFA_RV64-NEXT:    vmv.v.x v8, a0
; ZVFBFA_RV64-NEXT:    ret
  %splat = call <2 x i64> @llvm.experimental.vp.splat.v2i64(i64 %val, <2 x i1> %m, i32 %evl)
  ret <2 x i64> %splat
}

define <4 x i64> @vp_splat_v4i64(i64 %val, <4 x i1> %m, i32 zeroext %evl) {
; ZVFH_RV32-LABEL: vp_splat_v4i64:
; ZVFH_RV32:       # %bb.0:
; ZVFH_RV32-NEXT:    addi sp, sp, -16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFH_RV32-NEXT:    sw a0, 8(sp)
; ZVFH_RV32-NEXT:    sw a1, 12(sp)
; ZVFH_RV32-NEXT:    addi a0, sp, 8
; ZVFH_RV32-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; ZVFH_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFH_RV32-NEXT:    addi sp, sp, 16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFH_RV32-NEXT:    ret
;
; ZVFH_RV64-LABEL: vp_splat_v4i64:
; ZVFH_RV64:       # %bb.0:
; ZVFH_RV64-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; ZVFH_RV64-NEXT:    vmv.v.x v8, a0
; ZVFH_RV64-NEXT:    ret
;
; ZVFBFA_RV32-LABEL: vp_splat_v4i64:
; ZVFBFA_RV32:       # %bb.0:
; ZVFBFA_RV32-NEXT:    addi sp, sp, -16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFBFA_RV32-NEXT:    sw a0, 8(sp)
; ZVFBFA_RV32-NEXT:    sw a1, 12(sp)
; ZVFBFA_RV32-NEXT:    addi a0, sp, 8
; ZVFBFA_RV32-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; ZVFBFA_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFBFA_RV32-NEXT:    addi sp, sp, 16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFBFA_RV32-NEXT:    ret
;
; ZVFBFA_RV64-LABEL: vp_splat_v4i64:
; ZVFBFA_RV64:       # %bb.0:
; ZVFBFA_RV64-NEXT:    vsetvli zero, a1, e64, m2, ta, ma
; ZVFBFA_RV64-NEXT:    vmv.v.x v8, a0
; ZVFBFA_RV64-NEXT:    ret
  %splat = call <4 x i64> @llvm.experimental.vp.splat.v4i64(i64 %val, <4 x i1> %m, i32 %evl)
  ret <4 x i64> %splat
}

define <8 x i64> @vp_splat_v8i64(i64 %val, <8 x i1> %m, i32 zeroext %evl) {
; ZVFH_RV32-LABEL: vp_splat_v8i64:
; ZVFH_RV32:       # %bb.0:
; ZVFH_RV32-NEXT:    addi sp, sp, -16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFH_RV32-NEXT:    sw a0, 8(sp)
; ZVFH_RV32-NEXT:    sw a1, 12(sp)
; ZVFH_RV32-NEXT:    addi a0, sp, 8
; ZVFH_RV32-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; ZVFH_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFH_RV32-NEXT:    addi sp, sp, 16
; ZVFH_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFH_RV32-NEXT:    ret
;
; ZVFH_RV64-LABEL: vp_splat_v8i64:
; ZVFH_RV64:       # %bb.0:
; ZVFH_RV64-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; ZVFH_RV64-NEXT:    vmv.v.x v8, a0
; ZVFH_RV64-NEXT:    ret
;
; ZVFBFA_RV32-LABEL: vp_splat_v8i64:
; ZVFBFA_RV32:       # %bb.0:
; ZVFBFA_RV32-NEXT:    addi sp, sp, -16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 16
; ZVFBFA_RV32-NEXT:    sw a0, 8(sp)
; ZVFBFA_RV32-NEXT:    sw a1, 12(sp)
; ZVFBFA_RV32-NEXT:    addi a0, sp, 8
; ZVFBFA_RV32-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; ZVFBFA_RV32-NEXT:    vlse64.v v8, (a0), zero
; ZVFBFA_RV32-NEXT:    addi sp, sp, 16
; ZVFBFA_RV32-NEXT:    .cfi_def_cfa_offset 0
; ZVFBFA_RV32-NEXT:    ret
;
; ZVFBFA_RV64-LABEL: vp_splat_v8i64:
; ZVFBFA_RV64:       # %bb.0:
; ZVFBFA_RV64-NEXT:    vsetvli zero, a1, e64, m4, ta, ma
; ZVFBFA_RV64-NEXT:    vmv.v.x v8, a0
; ZVFBFA_RV64-NEXT:    ret
  %splat = call <8 x i64> @llvm.experimental.vp.splat.v8i64(i64 %val, <8 x i1> %m, i32 %evl)
  ret <8 x i64> %splat
}

define <1 x bfloat> @vp_splat_v1bf16(bfloat %val, <1 x i1> %m, i32 zeroext %evl) {
; ZVFH-LABEL: vp_splat_v1bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    fmv.x.w a1, fa0
; ZVFH-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; ZVFH-NEXT:    vmv.v.x v8, a1
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vp_splat_v1bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, mf4, ta, ma
; ZVFBFA-NEXT:    vfmv.v.f v8, fa0
; ZVFBFA-NEXT:    ret
  %splat = call <1 x bfloat> @llvm.experimental.vp.splat.v1bf16(bfloat %val, <1 x i1> %m, i32 %evl)
  ret <1 x bfloat> %splat
}

define <2 x bfloat> @vp_splat_v2bf16(bfloat %val, <2 x i1> %m, i32 zeroext %evl) {
; ZVFH-LABEL: vp_splat_v2bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    fmv.x.w a1, fa0
; ZVFH-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; ZVFH-NEXT:    vmv.v.x v8, a1
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vp_splat_v2bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, mf4, ta, ma
; ZVFBFA-NEXT:    vfmv.v.f v8, fa0
; ZVFBFA-NEXT:    ret
  %splat = call <2 x bfloat> @llvm.experimental.vp.splat.v2bf16(bfloat %val, <2 x i1> %m, i32 %evl)
  ret <2 x bfloat> %splat
}

define <4 x bfloat> @vp_splat_v4bf16(bfloat %val, <4 x i1> %m, i32 zeroext %evl) {
; ZVFH-LABEL: vp_splat_v4bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    fmv.x.w a1, fa0
; ZVFH-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; ZVFH-NEXT:    vmv.v.x v8, a1
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vp_splat_v4bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, mf2, ta, ma
; ZVFBFA-NEXT:    vfmv.v.f v8, fa0
; ZVFBFA-NEXT:    ret
  %splat = call <4 x bfloat> @llvm.experimental.vp.splat.v4bf16(bfloat %val, <4 x i1> %m, i32 %evl)
  ret <4 x bfloat> %splat
}

define <8 x bfloat> @vp_splat_v8bf16(bfloat %val, <8 x i1> %m, i32 zeroext %evl) {
; ZVFH-LABEL: vp_splat_v8bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    fmv.x.w a1, fa0
; ZVFH-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; ZVFH-NEXT:    vmv.v.x v8, a1
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vp_splat_v8bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, m1, ta, ma
; ZVFBFA-NEXT:    vfmv.v.f v8, fa0
; ZVFBFA-NEXT:    ret
  %splat = call <8 x bfloat> @llvm.experimental.vp.splat.v8bf16(bfloat %val, <8 x i1> %m, i32 %evl)
  ret <8 x bfloat> %splat
}

define <16 x bfloat> @vp_splat_v16bf16(bfloat %val, <16 x i1> %m, i32 zeroext %evl) {
; ZVFH-LABEL: vp_splat_v16bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    fmv.x.w a1, fa0
; ZVFH-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; ZVFH-NEXT:    vmv.v.x v8, a1
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vp_splat_v16bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, m2, ta, ma
; ZVFBFA-NEXT:    vfmv.v.f v8, fa0
; ZVFBFA-NEXT:    ret
  %splat = call <16 x bfloat> @llvm.experimental.vp.splat.v16bf16(bfloat %val, <16 x i1> %m, i32 %evl)
  ret <16 x bfloat> %splat
}

define <32 x bfloat> @vp_splat_v32bf16(bfloat %val, <32 x i1> %m, i32 zeroext %evl) {
; ZVFH-LABEL: vp_splat_v32bf16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    fmv.x.w a1, fa0
; ZVFH-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFH-NEXT:    vmv.v.x v8, a1
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vp_splat_v32bf16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, m4, ta, ma
; ZVFBFA-NEXT:    vfmv.v.f v8, fa0
; ZVFBFA-NEXT:    ret
  %splat = call <32 x bfloat> @llvm.experimental.vp.splat.v32bf16(bfloat %val, <32 x i1> %m, i32 %evl)
  ret <32 x bfloat> %splat
}

define <1 x half> @vp_splat_v1f16(half %val, <1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v1f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <1 x half> @llvm.experimental.vp.splat.v1f16(half %val, <1 x i1> %m, i32 %evl)
  ret <1 x half> %splat
}

define <2 x half> @vp_splat_v2f16(half %val, <2 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v2f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <2 x half> @llvm.experimental.vp.splat.v2f16(half %val, <2 x i1> %m, i32 %evl)
  ret <2 x half> %splat
}

define <4 x half> @vp_splat_v4f16(half %val, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <4 x half> @llvm.experimental.vp.splat.v4f16(half %val, <4 x i1> %m, i32 %evl)
  ret <4 x half> %splat
}

define <8 x half> @vp_splat_v8f16(half %val, <8 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v8f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <8 x half> @llvm.experimental.vp.splat.v8f16(half %val, <8 x i1> %m, i32 %evl)
  ret <8 x half> %splat
}

define <16 x half> @vp_splat_v16f16(half %val, <16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v16f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <16 x half> @llvm.experimental.vp.splat.v16f16(half %val, <16 x i1> %m, i32 %evl)
  ret <16 x half> %splat
}

define <32 x half> @vp_splat_v32f16(half %val, <32 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v32f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <32 x half> @llvm.experimental.vp.splat.v32f16(half %val, <32 x i1> %m, i32 %evl)
  ret <32 x half> %splat
}

define <1 x float> @vp_splat_v1f32(float %val, <1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v1f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <1 x float> @llvm.experimental.vp.splat.v1f32(float %val, <1 x i1> %m, i32 %evl)
  ret <1 x float> %splat
}

define <2 x float> @vp_splat_v2f32(float %val, <2 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <2 x float> @llvm.experimental.vp.splat.v2f32(float %val, <2 x i1> %m, i32 %evl)
  ret <2 x float> %splat
}

define <4 x float> @vp_splat_v4f32(float %val, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <4 x float> @llvm.experimental.vp.splat.v4f32(float %val, <4 x i1> %m, i32 %evl)
  ret <4 x float> %splat
}

define <8 x float> @vp_splat_v8f32(float %val, <8 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <8 x float> @llvm.experimental.vp.splat.v8f32(float %val, <8 x i1> %m, i32 %evl)
  ret <8 x float> %splat
}

define <16 x float> @vp_splat_v16f32(float %val, <16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v16f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <16 x float> @llvm.experimental.vp.splat.v16f32(float %val, <16 x i1> %m, i32 %evl)
  ret <16 x float> %splat
}

define <1 x double> @vp_splat_v1f64(double %val, <1 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v1f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <1 x double> @llvm.experimental.vp.splat.v1f64(double %val, <1 x i1> %m, i32 %evl)
  ret <1 x double> %splat
}

define <2 x double> @vp_splat_v2f64(double %val, <2 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <2 x double> @llvm.experimental.vp.splat.v2f64(double %val, <2 x i1> %m, i32 %evl)
  ret <2 x double> %splat
}

define <4 x double> @vp_splat_v4f64(double %val, <4 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <4 x double> @llvm.experimental.vp.splat.v4f64(double %val, <4 x i1> %m, i32 %evl)
  ret <4 x double> %splat
}

define <8 x double> @vp_splat_v8f64(double %val, <8 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, ma
; CHECK-NEXT:    vfmv.v.f v8, fa0
; CHECK-NEXT:    ret
  %splat = call <8 x double> @llvm.experimental.vp.splat.v8f64(double %val, <8 x i1> %m, i32 %evl)
  ret <8 x double> %splat
}

define <16 x i31> @vp_splat_v16i31(i31 %val, <16 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v16i31:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <16 x i31> @llvm.experimental.vp.splat.v16i31(i31 %val, <16 x i1> %m, i32 %evl)
  ret <16 x i31> %splat
}

define <15 x i32> @vp_splat_v15i32(i32 %val, <15 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v15i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m4, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <15 x i32> @llvm.experimental.vp.splat.v15i32(i32 %val, <15 x i1> %m, i32 %evl)
  ret <15 x i32> %splat
}

; Split case.
define <32 x i32> @vp_splat_v32i32(i32 %val, <32 x i1> %m, i32 zeroext %evl) {
; CHECK-LABEL: vp_splat_v32i32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a1, e32, m8, ta, ma
; CHECK-NEXT:    vmv.v.x v8, a0
; CHECK-NEXT:    ret
  %splat = call <32 x i32> @llvm.experimental.vp.splat.v32i32(i32 %val, <32 x i1> %m, i32 %evl)
  ret <32 x i32> %splat
}
