; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv32 -mattr=+v,+zvfh,+zvfbfmin -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfh,+zvfbfmin -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV64

define <4 x float> @canonicalize_v4f32(<4 x float> %a) {
; CHECK-LABEL: canonicalize_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetvli a0, zero, e32, m1, ta, ma
; CHECK-NEXT:    vfmul.vf v8, v8, fa5
; CHECK-NEXT:    ret
  %r = call <4 x float> @llvm.canonicalize.v4f32(<4 x float> %a)
  ret <4 x float> %r
}

define <2 x double> @canonicalize_v2f64(<2 x double> %a) {
; RV32-LABEL: canonicalize_v2f64:
; RV32:       # %bb.0:
; RV32-NEXT:    lui a0, %hi(.LCPI1_0)
; RV32-NEXT:    fld fa5, %lo(.LCPI1_0)(a0)
; RV32-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; RV32-NEXT:    vfmul.vf v8, v8, fa5
; RV32-NEXT:    ret
;
; RV64-LABEL: canonicalize_v2f64:
; RV64:       # %bb.0:
; RV64-NEXT:    li a0, 1023
; RV64-NEXT:    slli a0, a0, 52
; RV64-NEXT:    fmv.d.x fa5, a0
; RV64-NEXT:    vsetvli a0, zero, e64, m1, ta, ma
; RV64-NEXT:    vfmul.vf v8, v8, fa5
; RV64-NEXT:    ret
  %r = call <2 x double> @llvm.canonicalize.v2f64(<2 x double> %a)
  ret <2 x double> %r
}

define <4 x half> @canonicalize_v4f16(<4 x half> %a) {
; CHECK-LABEL: canonicalize_v4f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 15
; CHECK-NEXT:    slli a0, a0, 10
; CHECK-NEXT:    fmv.h.x fa5, a0
; CHECK-NEXT:    vsetvli a0, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vfmul.vf v8, v8, fa5
; CHECK-NEXT:    ret
  %r = call <4 x half> @llvm.canonicalize.v4f16(<4 x half> %a)
  ret <4 x half> %r
}

define <4 x bfloat> @canonicalize_v4bf16(<4 x bfloat> %a) {
; CHECK-LABEL: canonicalize_v4bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 260096
; CHECK-NEXT:    fmv.w.x fa5, a0
; CHECK-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; CHECK-NEXT:    vfwcvtbf16.f.f.v v9, v8
; CHECK-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; CHECK-NEXT:    vfmul.vf v9, v9, fa5
; CHECK-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vfncvtbf16.f.f.w v8, v9
; CHECK-NEXT:    ret
  %r = call <4 x bfloat> @llvm.canonicalize.v4bf16(<4 x bfloat> %a)
  ret <4 x bfloat> %r
}
