; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+d,+zvfh,+zfbfmin,+zvfbfmin,+v -target-abi=ilp32d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFH
; RUN: llc -mtriple=riscv64 -mattr=+d,+zvfh,+zfbfmin,+zvfbfmin,+v -target-abi=lp64d \
; RUN:     -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,ZVFH
; RUN: llc -mtriple=riscv32 -mattr=+d,+zfhmin,+zvfhmin,+experimental-zvfbfa,+v \
; RUN:     -target-abi=ilp32d -verify-machineinstrs < %s | FileCheck %s \
; RUN:     --check-prefixes=CHECK,ZVFBFA
; RUN: llc -mtriple=riscv64 -mattr=+d,+zfhmin,+zvfhmin,+experimental-zvfbfa,+v \
; RUN:     -target-abi=lp64d -verify-machineinstrs < %s | FileCheck %s \
; RUN:     --check-prefixes=CHECK,ZVFBFA

define <1 x bfloat> @vfadd_vv_v1bf16(<1 x bfloat> %va, <1 x bfloat> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v1bf16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v9
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v9, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFH-NEXT:    vfadd.vv v9, v9, v10
; ZVFH-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v1bf16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 1, e16alt, mf4, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v8, v8, v9
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <1 x bfloat> @llvm.experimental.constrained.fadd.v1bf16(<1 x bfloat> %va, <1 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <1 x bfloat> %vc
}

define <2 x bfloat> @vfadd_vv_v2bf16(<2 x bfloat> %va, <2 x bfloat> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v2bf16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v9
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v9, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFH-NEXT:    vfadd.vv v9, v9, v10
; ZVFH-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v2bf16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 2, e16alt, mf4, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v8, v8, v9
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <2 x bfloat> @llvm.experimental.constrained.fadd.v2bf16(<2 x bfloat> %va, <2 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <2 x bfloat> %vc
}

define <4 x bfloat> @vfadd_vv_v4bf16(<4 x bfloat> %va, <4 x bfloat> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v4bf16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v9
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v9, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVFH-NEXT:    vfadd.vv v9, v9, v10
; ZVFH-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v4bf16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 4, e16alt, mf2, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v8, v8, v9
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <4 x bfloat> @llvm.experimental.constrained.fadd.v4bf16(<4 x bfloat> %va, <4 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <4 x bfloat> %vc
}

define <8 x bfloat> @vfadd_vv_v8bf16(<8 x bfloat> %va, <8 x bfloat> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v8bf16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v10, v9
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v12, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; ZVFH-NEXT:    vfadd.vv v10, v12, v10
; ZVFH-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v10
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v8bf16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 8, e16alt, m1, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v8, v8, v9
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <8 x bfloat> @llvm.experimental.constrained.fadd.v8bf16(<8 x bfloat> %va, <8 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <8 x bfloat> %vc
}

define <16 x bfloat> @vfadd_vv_v16bf16(<16 x bfloat> %va, <16 x bfloat> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v16bf16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v12, v10
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v16, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, m4, ta, ma
; ZVFH-NEXT:    vfadd.vv v12, v16, v12
; ZVFH-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v12
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v16bf16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 16, e16alt, m2, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v8, v8, v10
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <16 x bfloat> @llvm.experimental.constrained.fadd.v16bf16(<16 x bfloat> %va, <16 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <16 x bfloat> %vc
}

define <32 x bfloat> @vfadd_vv_v32bf16(<32 x bfloat> %va, <32 x bfloat> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v32bf16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    li a0, 32
; ZVFH-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v16, v12
; ZVFH-NEXT:    vfwcvtbf16.f.f.v v24, v8
; ZVFH-NEXT:    vsetvli zero, zero, e32, m8, ta, ma
; ZVFH-NEXT:    vfadd.vv v16, v24, v16
; ZVFH-NEXT:    vsetvli zero, zero, e16, m4, ta, ma
; ZVFH-NEXT:    vfncvtbf16.f.f.w v8, v16
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v32bf16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    li a0, 32
; ZVFBFA-NEXT:    vsetvli zero, a0, e16alt, m4, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v8, v8, v12
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <32 x bfloat> @llvm.experimental.constrained.fadd.v32bf16(<32 x bfloat> %va, <32 x bfloat> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <32 x bfloat> %vc
}

define <2 x half> @vfadd_vv_v2f16(<2 x half> %va, <2 x half> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v2f16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFH-NEXT:    vfadd.vv v8, v8, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v2f16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v9
; ZVFBFA-NEXT:    vfwcvt.f.f.v v9, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v9, v9, v10
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v9
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <2 x half> @llvm.experimental.constrained.fadd.v2f16(<2 x half> %va, <2 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <2 x half> %vc
}

define <2 x half> @vfadd_vf_v2f16(<2 x half> %va, half %b) strictfp {
; ZVFH-LABEL: vfadd_vf_v2f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFH-NEXT:    vfadd.vf v8, v8, fa0
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vf_v2f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 2, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vmv.v.x v9, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v8, v9
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, mf2, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v9, v10, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v9
; ZVFBFA-NEXT:    ret
  %head = insertelement <2 x half> poison, half %b, i32 0
  %splat = shufflevector <2 x half> %head, <2 x half> poison, <2 x i32> zeroinitializer
  %vc = call <2 x half> @llvm.experimental.constrained.fadd.v2f16(<2 x half> %va, <2 x half> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <2 x half> %vc
}

define <4 x half> @vfadd_vv_v4f16(<4 x half> %va, <4 x half> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v4f16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFH-NEXT:    vfadd.vv v8, v8, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v4f16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v9
; ZVFBFA-NEXT:    vfwcvt.f.f.v v9, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v9, v9, v10
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v9
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <4 x half> @llvm.experimental.constrained.fadd.v4f16(<4 x half> %va, <4 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <4 x half> %vc
}

define <4 x half> @vfadd_vf_v4f16(<4 x half> %va, half %b) strictfp {
; ZVFH-LABEL: vfadd_vf_v4f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFH-NEXT:    vfadd.vf v8, v8, fa0
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vf_v4f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 4, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vmv.v.x v9, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v8, v9
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m1, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v9, v10, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, mf2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v9
; ZVFBFA-NEXT:    ret
  %head = insertelement <4 x half> poison, half %b, i32 0
  %splat = shufflevector <4 x half> %head, <4 x half> poison, <4 x i32> zeroinitializer
  %vc = call <4 x half> @llvm.experimental.constrained.fadd.v4f16(<4 x half> %va, <4 x half> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <4 x half> %vc
}

define <8 x half> @vfadd_vv_v8f16(<8 x half> %va, <8 x half> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v8f16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFH-NEXT:    vfadd.vv v8, v8, v9
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v8f16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v9
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v10, v12, v10
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v10
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <8 x half> @llvm.experimental.constrained.fadd.v8f16(<8 x half> %va, <8 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <8 x half> %vc
}

define <8 x half> @vfadd_vf_v8f16(<8 x half> %va, half %b) strictfp {
; ZVFH-LABEL: vfadd_vf_v8f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFH-NEXT:    vfadd.vf v8, v8, fa0
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vf_v8f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 8, e16, m1, ta, ma
; ZVFBFA-NEXT:    vmv.v.x v12, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v10, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v8, v12
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m2, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v10, v10, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m1, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v10
; ZVFBFA-NEXT:    ret
  %head = insertelement <8 x half> poison, half %b, i32 0
  %splat = shufflevector <8 x half> %head, <8 x half> poison, <8 x i32> zeroinitializer
  %vc = call <8 x half> @llvm.experimental.constrained.fadd.v8f16(<8 x half> %va, <8 x half> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <8 x half> %vc
}

define <16 x half> @vfadd_vv_v16f16(<16 x half> %va, <16 x half> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v16f16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFH-NEXT:    vfadd.vv v8, v8, v10
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v16f16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v10
; ZVFBFA-NEXT:    vfwcvt.f.f.v v16, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m4, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v12, v16, v12
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v12
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <16 x half> @llvm.experimental.constrained.fadd.v16f16(<16 x half> %va, <16 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <16 x half> %vc
}

define <16 x half> @vfadd_vf_v16f16(<16 x half> %va, half %b) strictfp {
; ZVFH-LABEL: vfadd_vf_v16f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFH-NEXT:    vfadd.vf v8, v8, fa0
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vf_v16f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    vsetivli zero, 16, e16, m2, ta, ma
; ZVFBFA-NEXT:    vmv.v.x v16, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v12, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v8, v16
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m4, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v12, v12, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m2, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v12
; ZVFBFA-NEXT:    ret
  %head = insertelement <16 x half> poison, half %b, i32 0
  %splat = shufflevector <16 x half> %head, <16 x half> poison, <16 x i32> zeroinitializer
  %vc = call <16 x half> @llvm.experimental.constrained.fadd.v16f16(<16 x half> %va, <16 x half> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <16 x half> %vc
}

define <32 x half> @vfadd_vv_v32f16(<32 x half> %va, <32 x half> %vb) strictfp {
; ZVFH-LABEL: vfadd_vv_v32f16:
; ZVFH:       # %bb.0: # %entry
; ZVFH-NEXT:    li a0, 32
; ZVFH-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFH-NEXT:    vfadd.vv v8, v8, v12
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vv_v32f16:
; ZVFBFA:       # %bb.0: # %entry
; ZVFBFA-NEXT:    li a0, 32
; ZVFBFA-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFBFA-NEXT:    vfwcvt.f.f.v v16, v12
; ZVFBFA-NEXT:    vfwcvt.f.f.v v24, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m8, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v16, v24, v16
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v16
; ZVFBFA-NEXT:    ret
entry:
  %vc = call <32 x half> @llvm.experimental.constrained.fadd.v32f16(<32 x half> %va, <32 x half> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <32 x half> %vc
}

define <32 x half> @vfadd_vf_v32f16(<32 x half> %va, half %b) strictfp {
; ZVFH-LABEL: vfadd_vf_v32f16:
; ZVFH:       # %bb.0:
; ZVFH-NEXT:    li a0, 32
; ZVFH-NEXT:    vsetvli zero, a0, e16, m4, ta, ma
; ZVFH-NEXT:    vfadd.vf v8, v8, fa0
; ZVFH-NEXT:    ret
;
; ZVFBFA-LABEL: vfadd_vf_v32f16:
; ZVFBFA:       # %bb.0:
; ZVFBFA-NEXT:    fmv.x.h a0, fa0
; ZVFBFA-NEXT:    li a1, 32
; ZVFBFA-NEXT:    vsetvli zero, a1, e16, m4, ta, ma
; ZVFBFA-NEXT:    vmv.v.x v24, a0
; ZVFBFA-NEXT:    vfwcvt.f.f.v v16, v8
; ZVFBFA-NEXT:    vfwcvt.f.f.v v8, v24
; ZVFBFA-NEXT:    vsetvli zero, zero, e32, m8, ta, ma
; ZVFBFA-NEXT:    vfadd.vv v16, v16, v8
; ZVFBFA-NEXT:    vsetvli zero, zero, e16, m4, ta, ma
; ZVFBFA-NEXT:    vfncvt.f.f.w v8, v16
; ZVFBFA-NEXT:    ret
  %head = insertelement <32 x half> poison, half %b, i32 0
  %splat = shufflevector <32 x half> %head, <32 x half> poison, <32 x i32> zeroinitializer
  %vc = call <32 x half> @llvm.experimental.constrained.fadd.v32f16(<32 x half> %va, <32 x half> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <32 x half> %vc
}

define <2 x float> @vfadd_vv_v2f32(<2 x float> %va, <2 x float> %vb) strictfp {
; CHECK-LABEL: vfadd_vv_v2f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %vc = call <2 x float> @llvm.experimental.constrained.fadd.v2f32(<2 x float> %va, <2 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <2 x float> %vc
}

define <2 x float> @vfadd_vf_v2f32(<2 x float> %va, float %b) strictfp {
; CHECK-LABEL: vfadd_vf_v2f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; CHECK-NEXT:    vfadd.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <2 x float> poison, float %b, i32 0
  %splat = shufflevector <2 x float> %head, <2 x float> poison, <2 x i32> zeroinitializer
  %vc = call <2 x float> @llvm.experimental.constrained.fadd.v2f32(<2 x float> %va, <2 x float> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <2 x float> %vc
}

define <4 x float> @vfadd_vv_v4f32(<4 x float> %va, <4 x float> %vb) strictfp {
; CHECK-LABEL: vfadd_vv_v4f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %vc = call <4 x float> @llvm.experimental.constrained.fadd.v4f32(<4 x float> %va, <4 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <4 x float> %vc
}

define <4 x float> @vfadd_vf_v4f32(<4 x float> %va, float %b) strictfp {
; CHECK-LABEL: vfadd_vf_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e32, m1, ta, ma
; CHECK-NEXT:    vfadd.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <4 x float> poison, float %b, i32 0
  %splat = shufflevector <4 x float> %head, <4 x float> poison, <4 x i32> zeroinitializer
  %vc = call <4 x float> @llvm.experimental.constrained.fadd.v4f32(<4 x float> %va, <4 x float> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <4 x float> %vc
}

define <8 x float> @vfadd_vv_v8f32(<8 x float> %va, <8 x float> %vb) strictfp {
; CHECK-LABEL: vfadd_vv_v8f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v10
; CHECK-NEXT:    ret
entry:
  %vc = call <8 x float> @llvm.experimental.constrained.fadd.v8f32(<8 x float> %va, <8 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <8 x float> %vc
}

define <8 x float> @vfadd_vf_v8f32(<8 x float> %va, float %b) strictfp {
; CHECK-LABEL: vfadd_vf_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e32, m2, ta, ma
; CHECK-NEXT:    vfadd.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <8 x float> poison, float %b, i32 0
  %splat = shufflevector <8 x float> %head, <8 x float> poison, <8 x i32> zeroinitializer
  %vc = call <8 x float> @llvm.experimental.constrained.fadd.v8f32(<8 x float> %va, <8 x float> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <8 x float> %vc
}

define <16 x float> @vfadd_vv_v16f32(<16 x float> %va, <16 x float> %vb) strictfp {
; CHECK-LABEL: vfadd_vv_v16f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v12
; CHECK-NEXT:    ret
entry:
  %vc = call <16 x float> @llvm.experimental.constrained.fadd.v16f32(<16 x float> %va, <16 x float> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <16 x float> %vc
}

define <16 x float> @vfadd_vf_v16f32(<16 x float> %va, float %b) strictfp {
; CHECK-LABEL: vfadd_vf_v16f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e32, m4, ta, ma
; CHECK-NEXT:    vfadd.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <16 x float> poison, float %b, i32 0
  %splat = shufflevector <16 x float> %head, <16 x float> poison, <16 x i32> zeroinitializer
  %vc = call <16 x float> @llvm.experimental.constrained.fadd.v16f32(<16 x float> %va, <16 x float> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <16 x float> %vc
}

define <2 x double> @vfadd_vv_v2f64(<2 x double> %va, <2 x double> %vb) strictfp {
; CHECK-LABEL: vfadd_vv_v2f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v9
; CHECK-NEXT:    ret
entry:
  %vc = call <2 x double> @llvm.experimental.constrained.fadd.v2f64(<2 x double> %va, <2 x double> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <2 x double> %vc
}

define <2 x double> @vfadd_vf_v2f64(<2 x double> %va, double %b) strictfp {
; CHECK-LABEL: vfadd_vf_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; CHECK-NEXT:    vfadd.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <2 x double> poison, double %b, i32 0
  %splat = shufflevector <2 x double> %head, <2 x double> poison, <2 x i32> zeroinitializer
  %vc = call <2 x double> @llvm.experimental.constrained.fadd.v2f64(<2 x double> %va, <2 x double> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <2 x double> %vc
}

define <4 x double> @vfadd_vv_v4f64(<4 x double> %va, <4 x double> %vb) strictfp {
; CHECK-LABEL: vfadd_vv_v4f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v10
; CHECK-NEXT:    ret
entry:
  %vc = call <4 x double> @llvm.experimental.constrained.fadd.v4f64(<4 x double> %va, <4 x double> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <4 x double> %vc
}

define <4 x double> @vfadd_vf_v4f64(<4 x double> %va, double %b) strictfp {
; CHECK-LABEL: vfadd_vf_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vfadd.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <4 x double> poison, double %b, i32 0
  %splat = shufflevector <4 x double> %head, <4 x double> poison, <4 x i32> zeroinitializer
  %vc = call <4 x double> @llvm.experimental.constrained.fadd.v4f64(<4 x double> %va, <4 x double> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <4 x double> %vc
}

define <8 x double> @vfadd_vv_v8f64(<8 x double> %va, <8 x double> %vb) strictfp {
; CHECK-LABEL: vfadd_vv_v8f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vfadd.vv v8, v8, v12
; CHECK-NEXT:    ret
entry:
  %vc = call <8 x double> @llvm.experimental.constrained.fadd.v8f64(<8 x double> %va, <8 x double> %vb, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <8 x double> %vc
}

define <8 x double> @vfadd_vf_v8f64(<8 x double> %va, double %b) strictfp {
; CHECK-LABEL: vfadd_vf_v8f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e64, m4, ta, ma
; CHECK-NEXT:    vfadd.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <8 x double> poison, double %b, i32 0
  %splat = shufflevector <8 x double> %head, <8 x double> poison, <8 x i32> zeroinitializer
  %vc = call <8 x double> @llvm.experimental.constrained.fadd.v8f64(<8 x double> %va, <8 x double> %splat, metadata !"round.dynamic", metadata !"fpexcept.ignore")
  ret <8 x double> %vc
}
