; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=V,V32
; RUN: llc -mtriple=riscv32 -mattr=+v,+zvfbfmin -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=ZVFBFMIN,ZVFBFMIN32
; RUN: llc -mtriple=riscv32 -mattr=+v,+zvfhmin -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=ZVFHMIN
; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=V,V64
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfbfmin -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefixes=ZVFBFMIN,ZVFBFMIN64
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfhmin -verify-machineinstrs < %s \
; RUN:   | FileCheck %s --check-prefix=ZVFHMIN

define <4 x bfloat> @insertelt_v4bf16(<4 x bfloat> %v, bfloat %elt) {
; V-LABEL: insertelt_v4bf16:
; V:       # %bb.0:
; V-NEXT:    fmv.x.w a1, fa4
; V-NEXT:    fmv.x.w a2, fa1
; V-NEXT:    fmv.x.w a3, fa2
; V-NEXT:    fmv.x.w a4, fa3
; V-NEXT:    sh a1, 0(a0)
; V-NEXT:    sh a2, 2(a0)
; V-NEXT:    sh a3, 4(a0)
; V-NEXT:    sh a4, 6(a0)
; V-NEXT:    ret
;
; ZVFBFMIN-LABEL: insertelt_v4bf16:
; ZVFBFMIN:       # %bb.0:
; ZVFBFMIN-NEXT:    fmv.x.w a0, fa0
; ZVFBFMIN-NEXT:    vsetivli zero, 4, e16, m1, tu, ma
; ZVFBFMIN-NEXT:    vmv.s.x v8, a0
; ZVFBFMIN-NEXT:    ret
;
; ZVFHMIN-LABEL: insertelt_v4bf16:
; ZVFHMIN:       # %bb.0:
; ZVFHMIN-NEXT:    fmv.x.w a1, fa4
; ZVFHMIN-NEXT:    fmv.x.w a2, fa1
; ZVFHMIN-NEXT:    fmv.x.w a3, fa2
; ZVFHMIN-NEXT:    fmv.x.w a4, fa3
; ZVFHMIN-NEXT:    sh a1, 0(a0)
; ZVFHMIN-NEXT:    sh a2, 2(a0)
; ZVFHMIN-NEXT:    sh a3, 4(a0)
; ZVFHMIN-NEXT:    sh a4, 6(a0)
; ZVFHMIN-NEXT:    ret
  %r = insertelement <4 x bfloat> %v, bfloat %elt, i32 0
  ret <4 x bfloat> %r
}

define <4 x half> @insertelt_v4f16(<4 x half> %v, half %elt) {
; V32-LABEL: insertelt_v4f16:
; V32:       # %bb.0:
; V32-NEXT:    fmv.x.w a2, fa0
; V32-NEXT:    lh a3, 4(a1)
; V32-NEXT:    lh a4, 8(a1)
; V32-NEXT:    lh a1, 12(a1)
; V32-NEXT:    sh a2, 0(a0)
; V32-NEXT:    sh a3, 2(a0)
; V32-NEXT:    sh a4, 4(a0)
; V32-NEXT:    sh a1, 6(a0)
; V32-NEXT:    ret
;
; ZVFBFMIN32-LABEL: insertelt_v4f16:
; ZVFBFMIN32:       # %bb.0:
; ZVFBFMIN32-NEXT:    fmv.x.w a2, fa0
; ZVFBFMIN32-NEXT:    lh a3, 4(a1)
; ZVFBFMIN32-NEXT:    lh a4, 8(a1)
; ZVFBFMIN32-NEXT:    lh a1, 12(a1)
; ZVFBFMIN32-NEXT:    sh a2, 0(a0)
; ZVFBFMIN32-NEXT:    sh a3, 2(a0)
; ZVFBFMIN32-NEXT:    sh a4, 4(a0)
; ZVFBFMIN32-NEXT:    sh a1, 6(a0)
; ZVFBFMIN32-NEXT:    ret
;
; ZVFHMIN-LABEL: insertelt_v4f16:
; ZVFHMIN:       # %bb.0:
; ZVFHMIN-NEXT:    fmv.x.w a0, fa0
; ZVFHMIN-NEXT:    vsetivli zero, 4, e16, m1, tu, ma
; ZVFHMIN-NEXT:    vmv.s.x v8, a0
; ZVFHMIN-NEXT:    ret
;
; V64-LABEL: insertelt_v4f16:
; V64:       # %bb.0:
; V64-NEXT:    fmv.x.w a2, fa0
; V64-NEXT:    lh a3, 8(a1)
; V64-NEXT:    lh a4, 16(a1)
; V64-NEXT:    lh a1, 24(a1)
; V64-NEXT:    sh a2, 0(a0)
; V64-NEXT:    sh a3, 2(a0)
; V64-NEXT:    sh a4, 4(a0)
; V64-NEXT:    sh a1, 6(a0)
; V64-NEXT:    ret
;
; ZVFBFMIN64-LABEL: insertelt_v4f16:
; ZVFBFMIN64:       # %bb.0:
; ZVFBFMIN64-NEXT:    fmv.x.w a2, fa0
; ZVFBFMIN64-NEXT:    lh a3, 8(a1)
; ZVFBFMIN64-NEXT:    lh a4, 16(a1)
; ZVFBFMIN64-NEXT:    lh a1, 24(a1)
; ZVFBFMIN64-NEXT:    sh a2, 0(a0)
; ZVFBFMIN64-NEXT:    sh a3, 2(a0)
; ZVFBFMIN64-NEXT:    sh a4, 4(a0)
; ZVFBFMIN64-NEXT:    sh a1, 6(a0)
; ZVFBFMIN64-NEXT:    ret
  %r = insertelement <4 x half> %v, half %elt, i32 0
  ret <4 x half> %r
}
