; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+experimental-zvfbfa,+v -verify-machineinstrs < %s | FileCheck %s
; RUN: llc -mtriple=riscv64 -mattr=+experimental-zvfbfa,+v -verify-machineinstrs < %s | FileCheck %s

define <1 x bfloat> @vrsub_vf_nxv1bf16(<1 x bfloat> %va, bfloat %b) {
; CHECK-LABEL: vrsub_vf_nxv1bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 1, e16alt, mf4, ta, ma
; CHECK-NEXT:    vfrsub.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <1 x bfloat> poison, bfloat %b, i32 0
  %splat = shufflevector <1 x bfloat> %head, <1 x bfloat> poison, <1 x i32> zeroinitializer
  %vc = fsub <1 x bfloat> %splat, %va
  ret <1 x bfloat> %vc
}

define <2 x bfloat> @vrsub_vf_nxv2bf16(<2 x bfloat> %va, bfloat %b) {
; CHECK-LABEL: vrsub_vf_nxv2bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 2, e16alt, mf4, ta, ma
; CHECK-NEXT:    vfrsub.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <2 x bfloat> poison, bfloat %b, i32 0
  %splat = shufflevector <2 x bfloat> %head, <2 x bfloat> poison, <2 x i32> zeroinitializer
  %vc = fsub <2 x bfloat> %splat, %va
  ret <2 x bfloat> %vc
}

define <4 x bfloat> @vrsub_vf_nxv4bf16(<4 x bfloat> %va, bfloat %b) {
; CHECK-LABEL: vrsub_vf_nxv4bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e16alt, mf2, ta, ma
; CHECK-NEXT:    vfrsub.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <4 x bfloat> poison, bfloat %b, i32 0
  %splat = shufflevector <4 x bfloat> %head, <4 x bfloat> poison, <4 x i32> zeroinitializer
  %vc = fsub <4 x bfloat> %splat, %va
  ret <4 x bfloat> %vc
}

define <8 x bfloat> @vrsub_vf_nxv8bf16(<8 x bfloat> %va, bfloat %b) {
; CHECK-LABEL: vrsub_vf_nxv8bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 8, e16alt, m1, ta, ma
; CHECK-NEXT:    vfrsub.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <8 x bfloat> poison, bfloat %b, i32 0
  %splat = shufflevector <8 x bfloat> %head, <8 x bfloat> poison, <8 x i32> zeroinitializer
  %vc = fsub <8 x bfloat> %splat, %va
  ret <8 x bfloat> %vc
}

define <16 x bfloat> @vrsub_vf_nxv16bf16(<16 x bfloat> %va, bfloat %b) {
; CHECK-LABEL: vrsub_vf_nxv16bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 16, e16alt, m2, ta, ma
; CHECK-NEXT:    vfrsub.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <16 x bfloat> poison, bfloat %b, i32 0
  %splat = shufflevector <16 x bfloat> %head, <16 x bfloat> poison, <16 x i32> zeroinitializer
  %vc = fsub <16 x bfloat> %splat, %va
  ret <16 x bfloat> %vc
}

define <32 x bfloat> @vrsub_vf_nxv32bf16(<32 x bfloat> %va, bfloat %b) {
; CHECK-LABEL: vrsub_vf_nxv32bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    li a0, 32
; CHECK-NEXT:    vsetvli zero, a0, e16alt, m4, ta, ma
; CHECK-NEXT:    vfrsub.vf v8, v8, fa0
; CHECK-NEXT:    ret
  %head = insertelement <32 x bfloat> poison, bfloat %b, i32 0
  %splat = shufflevector <32 x bfloat> %head, <32 x bfloat> poison, <32 x i32> zeroinitializer
  %vc = fsub <32 x bfloat> %splat, %va
  ret <32 x bfloat> %vc
}
