; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+m,+v -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK

define void @test_2x4bit_mask_with_extracts(i64 %i, i64 %n) #0 {
; CHECK-LABEL: test_2x4bit_mask_with_extracts:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    vsetvli a3, zero, e64, m4, ta, ma
; CHECK-NEXT:    vid.v v8
; CHECK-NEXT:    srli a2, a2, 1
; CHECK-NEXT:    vsaddu.vx v12, v8, a0
; CHECK-NEXT:    vmsltu.vx v0, v12, a1
; CHECK-NEXT:    add a2, a0, a2
; CHECK-NEXT:    sltu a0, a2, a0
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    or a0, a0, a2
; CHECK-NEXT:    vsaddu.vx v12, v8, a0
; CHECK-NEXT:    vmsltu.vx v8, v12, a1
; CHECK-NEXT:    tail use
  %r = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 %i, i64 %n)
  %v0 = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 0)
  %v1 = call <vscale x 4 x i1> @llvm.vector.extract.nxv4i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 4)
  tail call void @use(<vscale x 4 x i1> %v0, <vscale x 4 x i1> %v1)
  ret void
}

define void @test_2x8bit_mask_with_extracts(i64 %i, i64 %n) #0 {
; CHECK-LABEL: test_2x8bit_mask_with_extracts:
; CHECK:       # %bb.0:
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    vsetvli a3, zero, e64, m8, ta, ma
; CHECK-NEXT:    vid.v v8
; CHECK-NEXT:    vsaddu.vx v16, v8, a0
; CHECK-NEXT:    add a2, a0, a2
; CHECK-NEXT:    vmsltu.vx v0, v16, a1
; CHECK-NEXT:    sltu a0, a2, a0
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    or a0, a0, a2
; CHECK-NEXT:    vsaddu.vx v16, v8, a0
; CHECK-NEXT:    vmsltu.vx v8, v16, a1
; CHECK-NEXT:    tail use
  %r = call <vscale x 16 x i1> @llvm.get.active.lane.mask.nxv16i1.i64(i64 %i, i64 %n)
  %v0 = call <vscale x 8 x i1> @llvm.vector.extract.nxv8i1.nxv16i1.i64(<vscale x 16 x i1> %r, i64 0)
  %v1 = call <vscale x 8 x i1> @llvm.vector.extract.nxv8i1.nxv16i1.i64(<vscale x 16 x i1> %r, i64 8)
  tail call void @use(<vscale x 8 x i1> %v0, <vscale x 8 x i1> %v1)
  ret void
}

define void @test_fixed_2x4bit_mask_with_extract(i64 %i, i64 %n) #0 {
; CHECK-LABEL: test_fixed_2x4bit_mask_with_extract:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; CHECK-NEXT:    vid.v v8
; CHECK-NEXT:    addi a2, a0, 4
; CHECK-NEXT:    vsaddu.vx v10, v8, a0
; CHECK-NEXT:    sltu a0, a2, a0
; CHECK-NEXT:    vmsltu.vx v0, v10, a1
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    or a0, a0, a2
; CHECK-NEXT:    vsaddu.vx v10, v8, a0
; CHECK-NEXT:    vmsltu.vx v8, v10, a1
; CHECK-NEXT:    tail use
  %r = call <8 x i1> @llvm.get.active.lane.mask.v8i1.i64(i64 %i, i64 %n)
  %v0 = call <4 x i1> @llvm.vector.extract.v4i1.v8i1.i64(<8 x i1> %r, i64 0)
  %v1 = call <4 x i1> @llvm.vector.extract.v4i1.v8i1.i64(<8 x i1> %r, i64 4)
  tail call void @use(<4 x i1> %v0, <4 x i1> %v1)
  ret void
}

define void @test_4x2bit_mask_with_extracts_and_reinterpret_casts(i64 %i, i64 %n) #0 {
; CHECK-LABEL: test_4x2bit_mask_with_extracts_and_reinterpret_casts:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetvli a2, zero, e64, m2, ta, ma
; CHECK-NEXT:    vid.v v10
; CHECK-NEXT:    vsaddu.vx v8, v10, a0
; CHECK-NEXT:    vmsltu.vx v0, v8, a1
; CHECK-NEXT:    vfirst.m a2, v0
; CHECK-NEXT:    bnez a2, .LBB3_2
; CHECK-NEXT:  # %bb.1: # %if.then
; CHECK-NEXT:    csrr a2, vlenb
; CHECK-NEXT:    srli a2, a2, 2
; CHECK-NEXT:    add a3, a0, a2
; CHECK-NEXT:    sltu a0, a3, a0
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    or a0, a0, a3
; CHECK-NEXT:    vsaddu.vx v12, v10, a0
; CHECK-NEXT:    add a3, a0, a2
; CHECK-NEXT:    vmsltu.vx v8, v12, a1
; CHECK-NEXT:    sltu a0, a3, a0
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    or a0, a0, a3
; CHECK-NEXT:    vsaddu.vx v12, v10, a0
; CHECK-NEXT:    add a2, a0, a2
; CHECK-NEXT:    vmsltu.vx v9, v12, a1
; CHECK-NEXT:    sltu a0, a2, a0
; CHECK-NEXT:    neg a0, a0
; CHECK-NEXT:    or a0, a0, a2
; CHECK-NEXT:    vsaddu.vx v12, v10, a0
; CHECK-NEXT:    vmsltu.vx v10, v12, a1
; CHECK-NEXT:    tail use
; CHECK-NEXT:  .LBB3_2: # %if.end
; CHECK-NEXT:    ret
entry:
    %r = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i32(i64 %i, i64 %n)
    %v0 = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 0)
    %v1 = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 2)
    %v2 = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 4)
    %v3 = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 6)
    %elt0 = extractelement <vscale x 8 x i1> %r, i32 0
    br i1 %elt0, label %if.then, label %if.end

if.then:
    tail call void @use(<vscale x 2 x i1> %v0, <vscale x 2 x i1> %v1, <vscale x 2 x i1> %v2, <vscale x 2 x i1> %v3)
    br label %if.end

if.end:
    ret void
}

; Negative test where the extract types are correct but we are not extracting all parts of the mask
define void @test_partial_extract_legal_types(i64 %i, i64 %n) #0 {
; CHECK-LABEL: test_partial_extract_legal_types:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a2, zero, e64, m8, ta, ma
; CHECK-NEXT:    vid.v v8
; CHECK-NEXT:    vsaddu.vx v8, v8, a0
; CHECK-NEXT:    vmsltu.vx v0, v8, a1
; CHECK-NEXT:    vsetvli zero, zero, e8, m1, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    vmerge.vim v8, v8, 1, v0
; CHECK-NEXT:    srli a0, a0, 1
; CHECK-NEXT:    vslidedown.vx v8, v8, a0
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmsne.vi v8, v8, 0
; CHECK-NEXT:    tail use
  %r = call <vscale x 8 x i1> @llvm.get.active.lane.mask.nxv8i1.i64(i64 %i, i64 %n)
  %v0 = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 0)
  %v1 = call <vscale x 2 x i1> @llvm.vector.extract.nxv2i1.nxv8i1.i64(<vscale x 8 x i1> %r, i64 4)
  tail call void @use(<vscale x 2 x i1> %v0, <vscale x 2 x i1> %v1)
  ret void
}

declare void @use(...)

attributes #0 = { nounwind }
