; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=riscv64 -mattr=+zve64f,+zvl512b < %s | FileCheck %s

; Previously, an incorrect (extract_subvector (extract_subvector X, C), 0) DAG combine crashed
; this snippet.

define <8 x i16> @gsm_encode(ptr %p) {
; CHECK-LABEL: gsm_encode:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vsetivli zero, 19, e16, m1, ta, ma
; CHECK-NEXT:    vle16.v v9, (a0)
; CHECK-NEXT:    vslidedown.vi v8, v9, 12
; CHECK-NEXT:    vmv.x.s a0, v8
; CHECK-NEXT:    vsetivli zero, 8, e16, mf4, ta, ma
; CHECK-NEXT:    vmv.v.i v8, 0
; CHECK-NEXT:    vsetivli zero, 1, e16, m1, ta, ma
; CHECK-NEXT:    vslidedown.vi v9, v9, 9
; CHECK-NEXT:    vmv.x.s a1, v9
; CHECK-NEXT:    vmv.s.x v9, a1
; CHECK-NEXT:    vsetivli zero, 6, e16, mf4, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v9, 5
; CHECK-NEXT:    vmv.s.x v9, a0
; CHECK-NEXT:    vsetivli zero, 7, e16, mf4, tu, ma
; CHECK-NEXT:    vslideup.vi v8, v9, 6
; CHECK-NEXT:    ret
entry:
  %0 = load <19 x i16>, ptr %p, align 2
  %1 = shufflevector <19 x i16> zeroinitializer, <19 x i16> %0, <9 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 28, i32 31, i32 poison, i32 poison>
  %2 = shufflevector <9 x i16> %1, <9 x i16> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 15>
  ret <8 x i16> %2
}
