; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 < %s | FileCheck %s --check-prefixes=CHECK,RVNOV,RV32,RV32NOV
; RUN: llc -mtriple=riscv64 < %s | FileCheck %s --check-prefixes=CHECK,RVNOV,RV64,RV64NOV
; RUN: llc -mtriple=riscv32 -mattr=+v < %s | FileCheck %s --check-prefixes=CHECK,RV32,RVV,RV32V,RV32NOHALF
; RUN: llc -mtriple=riscv64 -mattr=+v < %s | FileCheck %s --check-prefixes=CHECK,RV64,RVV,RV64V,RV64NOHALF
; RUN: llc -mtriple=riscv32 -mattr=+v,+zvfh < %s | FileCheck %s --check-prefixes=CHECK,RV32,RVV,RV32V,RV32ZVFH
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfh < %s | FileCheck %s --check-prefixes=CHECK,RV64,RVV,RV64V,RV64ZVFH

define i64 @unaligned_i64_factor4(ptr %p) {
; RV32NOV-LABEL: unaligned_i64_factor4:
; RV32NOV:       # %bb.0:
; RV32NOV-NEXT:    lhu a1, 2(a0)
; RV32NOV-NEXT:    lhu a2, 0(a0)
; RV32NOV-NEXT:    lhu a3, 6(a0)
; RV32NOV-NEXT:    lhu a4, 4(a0)
; RV32NOV-NEXT:    slli a0, a1, 16
; RV32NOV-NEXT:    or a0, a0, a2
; RV32NOV-NEXT:    slli a1, a3, 16
; RV32NOV-NEXT:    or a1, a1, a4
; RV32NOV-NEXT:    ret
;
; RV64NOV-LABEL: unaligned_i64_factor4:
; RV64NOV:       # %bb.0:
; RV64NOV-NEXT:    lhu a1, 2(a0)
; RV64NOV-NEXT:    lhu a2, 0(a0)
; RV64NOV-NEXT:    lhu a3, 4(a0)
; RV64NOV-NEXT:    lhu a0, 6(a0)
; RV64NOV-NEXT:    slli a1, a1, 16
; RV64NOV-NEXT:    or a1, a1, a2
; RV64NOV-NEXT:    slli a3, a3, 32
; RV64NOV-NEXT:    slli a0, a0, 48
; RV64NOV-NEXT:    or a0, a0, a3
; RV64NOV-NEXT:    or a0, a0, a1
; RV64NOV-NEXT:    ret
;
; RV32V-LABEL: unaligned_i64_factor4:
; RV32V:       # %bb.0:
; RV32V-NEXT:    vsetivli zero, 2, e32, mf2, ta, ma
; RV32V-NEXT:    vle16.v v8, (a0)
; RV32V-NEXT:    addi a0, a0, 4
; RV32V-NEXT:    vle16.v v9, (a0)
; RV32V-NEXT:    vmv.x.s a0, v8
; RV32V-NEXT:    vmv.x.s a1, v9
; RV32V-NEXT:    ret
;
; RV64V-LABEL: unaligned_i64_factor4:
; RV64V:       # %bb.0:
; RV64V-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RV64V-NEXT:    vle16.v v8, (a0)
; RV64V-NEXT:    vmv.x.s a0, v8
; RV64V-NEXT:    ret
  %ld = load i64, ptr %p, align 2
  ret i64 %ld
}

define double @unaligned_f64_factor4(ptr %p) {
; RV32NOV-LABEL: unaligned_f64_factor4:
; RV32NOV:       # %bb.0:
; RV32NOV-NEXT:    lhu a1, 2(a0)
; RV32NOV-NEXT:    lhu a2, 0(a0)
; RV32NOV-NEXT:    lhu a3, 6(a0)
; RV32NOV-NEXT:    lhu a4, 4(a0)
; RV32NOV-NEXT:    slli a0, a1, 16
; RV32NOV-NEXT:    or a0, a0, a2
; RV32NOV-NEXT:    slli a1, a3, 16
; RV32NOV-NEXT:    or a1, a1, a4
; RV32NOV-NEXT:    ret
;
; RV64NOV-LABEL: unaligned_f64_factor4:
; RV64NOV:       # %bb.0:
; RV64NOV-NEXT:    lhu a1, 2(a0)
; RV64NOV-NEXT:    lhu a2, 0(a0)
; RV64NOV-NEXT:    lhu a3, 4(a0)
; RV64NOV-NEXT:    lhu a0, 6(a0)
; RV64NOV-NEXT:    slli a1, a1, 16
; RV64NOV-NEXT:    or a1, a1, a2
; RV64NOV-NEXT:    slli a3, a3, 32
; RV64NOV-NEXT:    slli a0, a0, 48
; RV64NOV-NEXT:    or a0, a0, a3
; RV64NOV-NEXT:    or a0, a0, a1
; RV64NOV-NEXT:    ret
;
; RV32NOHALF-LABEL: unaligned_f64_factor4:
; RV32NOHALF:       # %bb.0:
; RV32NOHALF-NEXT:    addi sp, sp, -16
; RV32NOHALF-NEXT:    .cfi_def_cfa_offset 16
; RV32NOHALF-NEXT:    lhu a1, 6(a0)
; RV32NOHALF-NEXT:    lhu a2, 4(a0)
; RV32NOHALF-NEXT:    slli a1, a1, 16
; RV32NOHALF-NEXT:    or a1, a1, a2
; RV32NOHALF-NEXT:    sw a1, 12(sp)
; RV32NOHALF-NEXT:    lhu a1, 2(a0)
; RV32NOHALF-NEXT:    lhu a0, 0(a0)
; RV32NOHALF-NEXT:    slli a1, a1, 16
; RV32NOHALF-NEXT:    or a0, a1, a0
; RV32NOHALF-NEXT:    sw a0, 8(sp)
; RV32NOHALF-NEXT:    fld fa0, 8(sp)
; RV32NOHALF-NEXT:    addi sp, sp, 16
; RV32NOHALF-NEXT:    .cfi_def_cfa_offset 0
; RV32NOHALF-NEXT:    ret
;
; RV64NOHALF-LABEL: unaligned_f64_factor4:
; RV64NOHALF:       # %bb.0:
; RV64NOHALF-NEXT:    lhu a1, 2(a0)
; RV64NOHALF-NEXT:    lhu a2, 0(a0)
; RV64NOHALF-NEXT:    lhu a3, 4(a0)
; RV64NOHALF-NEXT:    lhu a0, 6(a0)
; RV64NOHALF-NEXT:    slli a1, a1, 16
; RV64NOHALF-NEXT:    or a1, a1, a2
; RV64NOHALF-NEXT:    slli a3, a3, 32
; RV64NOHALF-NEXT:    slli a0, a0, 48
; RV64NOHALF-NEXT:    or a0, a0, a3
; RV64NOHALF-NEXT:    or a0, a0, a1
; RV64NOHALF-NEXT:    fmv.d.x fa0, a0
; RV64NOHALF-NEXT:    ret
;
; RV32ZVFH-LABEL: unaligned_f64_factor4:
; RV32ZVFH:       # %bb.0:
; RV32ZVFH-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RV32ZVFH-NEXT:    vle16.v v8, (a0)
; RV32ZVFH-NEXT:    vfmv.f.s fa0, v8
; RV32ZVFH-NEXT:    ret
;
; RV64ZVFH-LABEL: unaligned_f64_factor4:
; RV64ZVFH:       # %bb.0:
; RV64ZVFH-NEXT:    vsetivli zero, 4, e64, m2, ta, ma
; RV64ZVFH-NEXT:    vle16.v v8, (a0)
; RV64ZVFH-NEXT:    vfmv.f.s fa0, v8
; RV64ZVFH-NEXT:    ret
  %ld = load double, ptr %p, align 2
  ret double %ld
}

define double @unaligned_f64_factor2(ptr %p) {
; RV32NOV-LABEL: unaligned_f64_factor2:
; RV32NOV:       # %bb.0:
; RV32NOV-NEXT:    lw a2, 0(a0)
; RV32NOV-NEXT:    lw a1, 4(a0)
; RV32NOV-NEXT:    mv a0, a2
; RV32NOV-NEXT:    ret
;
; RV64NOV-LABEL: unaligned_f64_factor2:
; RV64NOV:       # %bb.0:
; RV64NOV-NEXT:    lw a1, 4(a0)
; RV64NOV-NEXT:    lwu a0, 0(a0)
; RV64NOV-NEXT:    slli a1, a1, 32
; RV64NOV-NEXT:    or a0, a1, a0
; RV64NOV-NEXT:    ret
;
; RVV-LABEL: unaligned_f64_factor2:
; RVV:       # %bb.0:
; RVV-NEXT:    vsetivli zero, 2, e64, m1, ta, ma
; RVV-NEXT:    vle32.v v8, (a0)
; RVV-NEXT:    vfmv.f.s fa0, v8
; RVV-NEXT:    ret
  %ld = load double, ptr %p, align 4
  ret double %ld
}

define void @extload_unaligned_i16_factor2(ptr %p, ptr %q) {
; RVNOV-LABEL: extload_unaligned_i16_factor2:
; RVNOV:       # %bb.0:
; RVNOV-NEXT:    lbu a2, 1(a0)
; RVNOV-NEXT:    lbu a0, 0(a0)
; RVNOV-NEXT:    slli a2, a2, 8
; RVNOV-NEXT:    or a0, a2, a0
; RVNOV-NEXT:    sh a0, 0(a1)
; RVNOV-NEXT:    ret
;
; RVV-LABEL: extload_unaligned_i16_factor2:
; RVV:       # %bb.0:
; RVV-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; RVV-NEXT:    vle8.v v8, (a0)
; RVV-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; RVV-NEXT:    vse16.v v8, (a1)
; RVV-NEXT:    ret
  %ld = load <1 x i16>, ptr %p, align 1
  store <1 x i16> %ld, ptr %q
  ret void
}

define void @extload_unaligned_f16_factor2(ptr %p, ptr %q) {
; RVNOV-LABEL: extload_unaligned_f16_factor2:
; RVNOV:       # %bb.0:
; RVNOV-NEXT:    lbu a2, 1(a0)
; RVNOV-NEXT:    lbu a0, 0(a0)
; RVNOV-NEXT:    slli a2, a2, 8
; RVNOV-NEXT:    or a0, a2, a0
; RVNOV-NEXT:    sh a0, 0(a1)
; RVNOV-NEXT:    ret
;
; RV32NOHALF-LABEL: extload_unaligned_f16_factor2:
; RV32NOHALF:       # %bb.0:
; RV32NOHALF-NEXT:    lbu a2, 1(a0)
; RV32NOHALF-NEXT:    lbu a0, 0(a0)
; RV32NOHALF-NEXT:    slli a2, a2, 8
; RV32NOHALF-NEXT:    or a0, a2, a0
; RV32NOHALF-NEXT:    sh a0, 0(a1)
; RV32NOHALF-NEXT:    ret
;
; RV64NOHALF-LABEL: extload_unaligned_f16_factor2:
; RV64NOHALF:       # %bb.0:
; RV64NOHALF-NEXT:    lbu a2, 1(a0)
; RV64NOHALF-NEXT:    lbu a0, 0(a0)
; RV64NOHALF-NEXT:    slli a2, a2, 8
; RV64NOHALF-NEXT:    or a0, a2, a0
; RV64NOHALF-NEXT:    sh a0, 0(a1)
; RV64NOHALF-NEXT:    ret
;
; RV32ZVFH-LABEL: extload_unaligned_f16_factor2:
; RV32ZVFH:       # %bb.0:
; RV32ZVFH-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; RV32ZVFH-NEXT:    vle8.v v8, (a0)
; RV32ZVFH-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; RV32ZVFH-NEXT:    vse16.v v8, (a1)
; RV32ZVFH-NEXT:    ret
;
; RV64ZVFH-LABEL: extload_unaligned_f16_factor2:
; RV64ZVFH:       # %bb.0:
; RV64ZVFH-NEXT:    vsetivli zero, 2, e8, mf8, ta, ma
; RV64ZVFH-NEXT:    vle8.v v8, (a0)
; RV64ZVFH-NEXT:    vsetivli zero, 1, e16, mf4, ta, ma
; RV64ZVFH-NEXT:    vse16.v v8, (a1)
; RV64ZVFH-NEXT:    ret
  %ld = load <1 x half>, ptr %p, align 1
  store <1 x half> %ld, ptr %q
  ret void
}

define i22 @unaligned_illegal_i22(ptr %p) {
; CHECK-LABEL: unaligned_illegal_i22:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a1, 2(a0)
; CHECK-NEXT:    lhu a0, 0(a0)
; CHECK-NEXT:    slli a1, a1, 16
; CHECK-NEXT:    or a0, a0, a1
; CHECK-NEXT:    ret
  %ld = load i22, ptr %p, align 2
  ret i22 %ld
}

define i64 @aligned_i64(ptr %p) {
; RV32-LABEL: aligned_i64:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a2, 0(a0)
; RV32-NEXT:    lw a1, 4(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: aligned_i64:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    ret
  %ld = load i64, ptr %p
  ret i64 %ld
}

define void @extload_aligned_i1(ptr %p, ptr %q) {
; CHECK-LABEL: extload_aligned_i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 0(a0)
; CHECK-NEXT:    andi a0, a0, 1
; CHECK-NEXT:    sb a0, 0(a1)
; CHECK-NEXT:    ret
  %ld = load <1 x i1>, ptr %p
  store <1 x i1> %ld, ptr %q
  ret void
}

define void @extload_aligned_i8(ptr %p, ptr %q) {
; CHECK-LABEL: extload_aligned_i8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lbu a0, 0(a0)
; CHECK-NEXT:    sb a0, 0(a1)
; CHECK-NEXT:    ret
  %ld = load <1 x i8>, ptr %p
  store <1 x i8> %ld, ptr %q
  ret void
}

define void @extload_aligned_f16(ptr %p, ptr %q) {
; CHECK-LABEL: extload_aligned_f16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lh a0, 0(a0)
; CHECK-NEXT:    sh a0, 0(a1)
; CHECK-NEXT:    ret
  %ld = load <1 x half>, ptr %p
  store <1 x half> %ld, ptr %q
  ret void
}
