; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv32 < %s | FileCheck %s --check-prefixes=RV32,RV32NOV
; RUN: llc -mtriple=riscv64 < %s | FileCheck %s --check-prefixes=RV64,RV64NOV
; RUN: llc -mtriple=riscv32 -mattr=+v < %s | FileCheck %s --check-prefixes=RV32,RVV,RV32V,RV32NOHALF
; RUN: llc -mtriple=riscv64 -mattr=+v < %s | FileCheck %s --check-prefixes=RV64,RVV,RV64V,RV64NOHALF
; RUN: llc -mtriple=riscv32 -mattr=+v,+zvfh < %s | FileCheck %s --check-prefixes=RV32,RVV,RV32V,RV32ZVFH
; RUN: llc -mtriple=riscv64 -mattr=+v,+zvfh < %s | FileCheck %s --check-prefixes=RV64,RVV,RV64V,RV64ZVFH

define i64 @misaligned_i64_factor4(ptr %p) {
; RV32-LABEL: misaligned_i64_factor4:
; RV32:       # %bb.0:
; RV32-NEXT:    lhu a1, 2(a0)
; RV32-NEXT:    lhu a2, 0(a0)
; RV32-NEXT:    lhu a3, 6(a0)
; RV32-NEXT:    lhu a4, 4(a0)
; RV32-NEXT:    slli a0, a1, 16
; RV32-NEXT:    or a0, a0, a2
; RV32-NEXT:    slli a1, a3, 16
; RV32-NEXT:    or a1, a1, a4
; RV32-NEXT:    ret
;
; RV64-LABEL: misaligned_i64_factor4:
; RV64:       # %bb.0:
; RV64-NEXT:    lhu a1, 2(a0)
; RV64-NEXT:    lhu a2, 0(a0)
; RV64-NEXT:    lhu a3, 4(a0)
; RV64-NEXT:    lhu a0, 6(a0)
; RV64-NEXT:    slli a1, a1, 16
; RV64-NEXT:    or a1, a1, a2
; RV64-NEXT:    slli a3, a3, 32
; RV64-NEXT:    slli a0, a0, 48
; RV64-NEXT:    or a0, a0, a3
; RV64-NEXT:    or a0, a0, a1
; RV64-NEXT:    ret
  %ld = load i64, ptr %p, align 2
  ret i64 %ld
}

define double @misaligned_f64_factor4_half(ptr %p) {
; RV32NOV-LABEL: misaligned_f64_factor4_half:
; RV32NOV:       # %bb.0:
; RV32NOV-NEXT:    lhu a1, 2(a0)
; RV32NOV-NEXT:    lhu a2, 0(a0)
; RV32NOV-NEXT:    lhu a3, 6(a0)
; RV32NOV-NEXT:    lhu a4, 4(a0)
; RV32NOV-NEXT:    slli a0, a1, 16
; RV32NOV-NEXT:    or a0, a0, a2
; RV32NOV-NEXT:    slli a1, a3, 16
; RV32NOV-NEXT:    or a1, a1, a4
; RV32NOV-NEXT:    ret
;
; RV64NOV-LABEL: misaligned_f64_factor4_half:
; RV64NOV:       # %bb.0:
; RV64NOV-NEXT:    lhu a1, 2(a0)
; RV64NOV-NEXT:    lhu a2, 0(a0)
; RV64NOV-NEXT:    lhu a3, 4(a0)
; RV64NOV-NEXT:    lhu a0, 6(a0)
; RV64NOV-NEXT:    slli a1, a1, 16
; RV64NOV-NEXT:    or a1, a1, a2
; RV64NOV-NEXT:    slli a3, a3, 32
; RV64NOV-NEXT:    slli a0, a0, 48
; RV64NOV-NEXT:    or a0, a0, a3
; RV64NOV-NEXT:    or a0, a0, a1
; RV64NOV-NEXT:    ret
;
; RV32V-LABEL: misaligned_f64_factor4_half:
; RV32V:       # %bb.0:
; RV32V-NEXT:    addi sp, sp, -16
; RV32V-NEXT:    .cfi_def_cfa_offset 16
; RV32V-NEXT:    lhu a1, 6(a0)
; RV32V-NEXT:    lhu a2, 4(a0)
; RV32V-NEXT:    slli a1, a1, 16
; RV32V-NEXT:    or a1, a1, a2
; RV32V-NEXT:    sw a1, 12(sp)
; RV32V-NEXT:    lhu a1, 2(a0)
; RV32V-NEXT:    lhu a0, 0(a0)
; RV32V-NEXT:    slli a1, a1, 16
; RV32V-NEXT:    or a0, a1, a0
; RV32V-NEXT:    sw a0, 8(sp)
; RV32V-NEXT:    fld fa0, 8(sp)
; RV32V-NEXT:    addi sp, sp, 16
; RV32V-NEXT:    .cfi_def_cfa_offset 0
; RV32V-NEXT:    ret
;
; RV64V-LABEL: misaligned_f64_factor4_half:
; RV64V:       # %bb.0:
; RV64V-NEXT:    lhu a1, 2(a0)
; RV64V-NEXT:    lhu a2, 0(a0)
; RV64V-NEXT:    lhu a3, 4(a0)
; RV64V-NEXT:    lhu a0, 6(a0)
; RV64V-NEXT:    slli a1, a1, 16
; RV64V-NEXT:    or a1, a1, a2
; RV64V-NEXT:    slli a3, a3, 32
; RV64V-NEXT:    slli a0, a0, 48
; RV64V-NEXT:    or a0, a0, a3
; RV64V-NEXT:    or a0, a0, a1
; RV64V-NEXT:    fmv.d.x fa0, a0
; RV64V-NEXT:    ret
  %ld = load double, ptr %p, align 2
  ret double %ld
}

define double @misaligned_f64_factor2(ptr %p) {
; RV32NOV-LABEL: misaligned_f64_factor2:
; RV32NOV:       # %bb.0:
; RV32NOV-NEXT:    lw a2, 0(a0)
; RV32NOV-NEXT:    lw a1, 4(a0)
; RV32NOV-NEXT:    mv a0, a2
; RV32NOV-NEXT:    ret
;
; RV64NOV-LABEL: misaligned_f64_factor2:
; RV64NOV:       # %bb.0:
; RV64NOV-NEXT:    lw a1, 4(a0)
; RV64NOV-NEXT:    lwu a0, 0(a0)
; RV64NOV-NEXT:    slli a1, a1, 32
; RV64NOV-NEXT:    or a0, a1, a0
; RV64NOV-NEXT:    ret
;
; RV32V-LABEL: misaligned_f64_factor2:
; RV32V:       # %bb.0:
; RV32V-NEXT:    addi sp, sp, -16
; RV32V-NEXT:    .cfi_def_cfa_offset 16
; RV32V-NEXT:    lw a1, 4(a0)
; RV32V-NEXT:    sw a1, 12(sp)
; RV32V-NEXT:    lw a0, 0(a0)
; RV32V-NEXT:    sw a0, 8(sp)
; RV32V-NEXT:    fld fa0, 8(sp)
; RV32V-NEXT:    addi sp, sp, 16
; RV32V-NEXT:    .cfi_def_cfa_offset 0
; RV32V-NEXT:    ret
;
; RV64V-LABEL: misaligned_f64_factor2:
; RV64V:       # %bb.0:
; RV64V-NEXT:    lw a1, 4(a0)
; RV64V-NEXT:    lwu a0, 0(a0)
; RV64V-NEXT:    slli a1, a1, 32
; RV64V-NEXT:    or a0, a1, a0
; RV64V-NEXT:    fmv.d.x fa0, a0
; RV64V-NEXT:    ret
  %ld = load double, ptr %p, align 4
  ret double %ld
}

define i64 @aligned(ptr %p) {
; RV32-LABEL: aligned:
; RV32:       # %bb.0:
; RV32-NEXT:    lw a2, 0(a0)
; RV32-NEXT:    lw a1, 4(a0)
; RV32-NEXT:    mv a0, a2
; RV32-NEXT:    ret
;
; RV64-LABEL: aligned:
; RV64:       # %bb.0:
; RV64-NEXT:    ld a0, 0(a0)
; RV64-NEXT:    ret
  %ld = load i64, ptr %p, align 8
  ret i64 %ld
}

define i22 @post_legalize_i22(ptr %p) {
; RV32-LABEL: post_legalize_i22:
; RV32:       # %bb.0:
; RV32-NEXT:    lbu a1, 2(a0)
; RV32-NEXT:    lhu a0, 0(a0)
; RV32-NEXT:    slli a1, a1, 16
; RV32-NEXT:    or a0, a0, a1
; RV32-NEXT:    ret
;
; RV64-LABEL: post_legalize_i22:
; RV64:       # %bb.0:
; RV64-NEXT:    lbu a1, 2(a0)
; RV64-NEXT:    lhu a0, 0(a0)
; RV64-NEXT:    slli a1, a1, 16
; RV64-NEXT:    or a0, a0, a1
; RV64-NEXT:    ret
  %ld = load i22, ptr %p, align 2
  ret i22 %ld
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32NOHALF: {{.*}}
; RV32ZVFH: {{.*}}
; RV64NOHALF: {{.*}}
; RV64ZVFH: {{.*}}
; RVV: {{.*}}
