# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=riscv64 -mcpu=sifive-p670 -run-pass=machine-combiner %s -o - | FileCheck %s

---
name:            vfmadd_vv
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0, $v8, $v16, $v24

    ; CHECK-LABEL: name: vfmadd_vv
    ; CHECK: liveins: $v0, $v8, $v16, $v24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vrm8 = COPY $v0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vrm8 = COPY $v8
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vrm8 = COPY $v16
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vrm8 = COPY $v24
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, [[COPY2]], [[COPY2]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M8_E64_1:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, [[COPY1]], [[COPY1]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMADD_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMADD_VV_M8_E64 [[COPY]], [[COPY]], killed [[PseudoVFMUL_VV_M8_E64_1]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMADD_VV_M8_E64_1:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMADD_VV_M8_E64 [[COPY3]], [[COPY3]], killed [[PseudoVFMUL_VV_M8_E64_]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFADD_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFADD_VV_M8_E64 $noreg, killed [[PseudoVFMADD_VV_M8_E64_1]], killed [[PseudoVFMADD_VV_M8_E64_]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVFADD_VV_M8_E64_]]
    ; CHECK-NEXT: PseudoRET implicit $v8
    %16:vrm8 = COPY $v0
    %17:vrm8 = COPY $v8
    %18:vrm8 = COPY $v16
    %19:vrm8 = COPY $v24
    %20:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %19, %19, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %21:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %18, %18, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %22:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %17, %17, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %23:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %16, %16, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %32:vrm8 = contract reassoc PseudoVFADD_VV_M8_E64 $noreg, killed %23, killed %22, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %33:vrm8 = contract reassoc PseudoVFADD_VV_M8_E64 $noreg, killed %20, killed %21, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %34:vrm8 = contract reassoc PseudoVFADD_VV_M8_E64 $noreg, killed %33, killed %32, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    $v8 = COPY %34
    PseudoRET implicit $v8
...
---
name:            vfmsub_vv
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0, $v8, $v16, $v24

    ; CHECK-LABEL: name: vfmsub_vv
    ; CHECK: liveins: $v0, $v8, $v16, $v24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vrm8 = COPY $v0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vrm8 = COPY $v8
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vrm8 = COPY $v16
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vrm8 = COPY $v24
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, [[COPY2]], [[COPY2]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M8_E64_1:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, [[COPY1]], [[COPY1]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMSUB_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMSUB_VV_M8_E64 [[COPY]], [[COPY]], killed [[PseudoVFMUL_VV_M8_E64_1]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMSUB_VV_M8_E64_1:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMSUB_VV_M8_E64 [[COPY3]], [[COPY3]], killed [[PseudoVFMUL_VV_M8_E64_]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFSUB_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed [[PseudoVFMSUB_VV_M8_E64_1]], killed [[PseudoVFMSUB_VV_M8_E64_]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVFSUB_VV_M8_E64_]]
    ; CHECK-NEXT: PseudoRET implicit $v8
    %16:vrm8 = COPY $v0
    %17:vrm8 = COPY $v8
    %18:vrm8 = COPY $v16
    %19:vrm8 = COPY $v24
    %20:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %19, %19, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %21:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %18, %18, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %22:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %17, %17, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %23:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %16, %16, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %32:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed %23, killed %22, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %33:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed %20, killed %21, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %34:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed %33, killed %32, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    $v8 = COPY %34
    PseudoRET implicit $v8
...
---
name:            vfnmsub_vv
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0, $v8, $v16, $v24

    ; CHECK-LABEL: name: vfnmsub_vv
    ; CHECK: liveins: $v0, $v8, $v16, $v24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vrm8 = COPY $v0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vrm8 = COPY $v8
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vrm8 = COPY $v16
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vrm8 = COPY $v24
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, [[COPY2]], [[COPY2]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFNMSUB_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFNMSUB_VV_M8_E64 [[COPY1]], [[COPY1]], killed [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMSUB_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMSUB_VV_M8_E64 [[COPY3]], [[COPY3]], killed [[PseudoVFMUL_VV_M8_E64_]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFSUB_VV_M8_E64_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed [[PseudoVFMSUB_VV_M8_E64_]], killed [[PseudoVFNMSUB_VV_M8_E64_]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVFSUB_VV_M8_E64_]]
    ; CHECK-NEXT: PseudoRET implicit $v8
    %16:vrm8 = COPY $v0
    %17:vrm8 = COPY $v8
    %18:vrm8 = COPY $v16
    %19:vrm8 = COPY $v24
    %20:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %19, %19, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %21:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %18, %18, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %22:vrm8 = contract reassoc PseudoVFMUL_VV_M8_E64 $noreg, %17, %17, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %32:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed %16, killed %22, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %33:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed %20, killed %21, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %34:vrm8 = contract reassoc PseudoVFSUB_VV_M8_E64 $noreg, killed %33, killed %32, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    $v8 = COPY %34
    PseudoRET implicit $v8
...
---
name:            vfmadd_vv_bf16
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0, $v8, $v16, $v24

    ; CHECK-LABEL: name: vfmadd_vv_bf16
    ; CHECK: liveins: $v0, $v8, $v16, $v24
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vrm8 = COPY $v0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vrm8 = COPY $v8
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vrm8 = COPY $v16
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vrm8 = COPY $v24
    ; CHECK-NEXT: [[PseudoVFMUL_ALT_VV_M8_E16_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMUL_ALT_VV_M8_E16 $noreg, [[COPY2]], [[COPY2]], 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMUL_ALT_VV_M8_E16_1:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMUL_ALT_VV_M8_E16 $noreg, [[COPY1]], [[COPY1]], 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMADD_ALT_VV_M8_E16_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMADD_ALT_VV_M8_E16 [[COPY]], [[COPY]], killed [[PseudoVFMUL_ALT_VV_M8_E16_1]], 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMADD_ALT_VV_M8_E16_1:%[0-9]+]]:vrm8 = contract reassoc PseudoVFMADD_ALT_VV_M8_E16 [[COPY3]], [[COPY3]], killed [[PseudoVFMUL_ALT_VV_M8_E16_]], 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFADD_ALT_VV_M8_E16_:%[0-9]+]]:vrm8 = contract reassoc PseudoVFADD_ALT_VV_M8_E16 $noreg, killed [[PseudoVFMADD_ALT_VV_M8_E16_1]], killed [[PseudoVFMADD_ALT_VV_M8_E16_]], 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVFADD_ALT_VV_M8_E16_]]
    ; CHECK-NEXT: PseudoRET implicit $v8
    %16:vrm8 = COPY $v0
    %17:vrm8 = COPY $v8
    %18:vrm8 = COPY $v16
    %19:vrm8 = COPY $v24
    %20:vrm8 = contract reassoc PseudoVFMUL_ALT_VV_M8_E16 $noreg, %19, %19, 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    %21:vrm8 = contract reassoc PseudoVFMUL_ALT_VV_M8_E16 $noreg, %18, %18, 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    %22:vrm8 = contract reassoc PseudoVFMUL_ALT_VV_M8_E16 $noreg, %17, %17, 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    %23:vrm8 = contract reassoc PseudoVFMUL_ALT_VV_M8_E16 $noreg, %16, %16, 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    %32:vrm8 = contract reassoc PseudoVFADD_ALT_VV_M8_E16 $noreg, killed %23, killed %22, 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    %33:vrm8 = contract reassoc PseudoVFADD_ALT_VV_M8_E16 $noreg, killed %20, killed %21, 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    %34:vrm8 = contract reassoc PseudoVFADD_ALT_VV_M8_E16 $noreg, killed %33, killed %32, 7, 16, 4 /* e16 */, 1 /* ta, mu */, implicit $frm
    $v8 = COPY %34
    PseudoRET implicit $v8
...
---
name:            vfmadd_vv_mask
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0, $v4, $v8, $v12, $v16

    ; CHECK-LABEL: name: vfmadd_vv_mask
    ; CHECK: liveins: $v0, $v4, $v8, $v12, $v16
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vmv0 = COPY $v0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vrm4nov0 = COPY $v4
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vrm4nov0 = COPY $v8
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vrm4nov0 = COPY $v12
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vrm4nov0 = COPY $v16
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK [[COPY4]], [[COPY4]], [[COPY4]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M4_E64_MASK1:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK [[COPY2]], [[COPY1]], [[COPY2]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMADD_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMADD_VV_M4_E64_MASK [[COPY1]], [[COPY3]], killed [[PseudoVFMUL_VV_M4_E64_MASK1]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMADD_VV_M4_E64_MASK1:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMADD_VV_M4_E64_MASK [[COPY3]], [[COPY2]], killed [[PseudoVFMUL_VV_M4_E64_MASK]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFADD_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK [[COPY1]], killed [[PseudoVFMADD_VV_M4_E64_MASK1]], killed [[PseudoVFMADD_VV_M4_E64_MASK]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVFADD_VV_M4_E64_MASK]]
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:vmv0 = COPY $v0
    %16:vrm4nov0 = COPY $v4
    %17:vrm4nov0 = COPY $v8
    %18:vrm4nov0 = COPY $v12
    %19:vrm4nov0 = COPY $v16
    %20:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %19, %19, %19, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %21:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %18, %18, %17, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %22:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %17, %16, %17, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %23:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %16, %18, %16, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %32:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK %16, killed %23, killed %22, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %33:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK %18, killed %20, killed %21, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %34:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK %16, killed %33, killed %32, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    $v8 = COPY %34
    PseudoRET implicit $v8
...
---
name:            vfmacc_vv_mask
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0, $v4, $v8, $v12, $v16

    ; CHECK-LABEL: name: vfmacc_vv_mask
    ; CHECK: liveins: $v0, $v4, $v8, $v12, $v16
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vmv0 = COPY $v0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vrm4nov0 = COPY $v4
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vrm4nov0 = COPY $v8
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vrm4nov0 = COPY $v12
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vrm4nov0 = COPY $v16
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK [[COPY4]], [[COPY4]], [[COPY4]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M4_E64_MASK1:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK [[COPY2]], [[COPY1]], [[COPY2]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMACC_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMACC_VV_M4_E64_MASK killed [[PseudoVFMUL_VV_M4_E64_MASK1]], [[COPY3]], [[COPY1]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMACC_VV_M4_E64_MASK1:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMACC_VV_M4_E64_MASK killed [[PseudoVFMUL_VV_M4_E64_MASK]], [[COPY3]], [[COPY2]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFADD_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK [[COPY1]], killed [[PseudoVFMACC_VV_M4_E64_MASK1]], killed [[PseudoVFMACC_VV_M4_E64_MASK]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVFADD_VV_M4_E64_MASK]]
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:vmv0 = COPY $v0
    %16:vrm4nov0 = COPY $v4
    %17:vrm4nov0 = COPY $v8
    %18:vrm4nov0 = COPY $v12
    %19:vrm4nov0 = COPY $v16
    %20:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %19, %19, %19, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %21:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %20, %18, %17, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %22:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %17, %16, %17, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %23:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %22, %18, %16, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %32:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK %22, killed %23, killed %22, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %33:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK %20, killed %20, killed %21, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %34:vrm4nov0 = contract reassoc PseudoVFADD_VV_M4_E64_MASK %16, killed %33, killed %32, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    $v8 = COPY %34
    PseudoRET implicit $v8
...
---
name:            vfmsac_vv_mask
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v0, $v4, $v8, $v12, $v16

    ; CHECK-LABEL: name: vfmsac_vv_mask
    ; CHECK: liveins: $v0, $v4, $v8, $v12, $v16
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vmv0 = COPY $v0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vrm4nov0 = COPY $v4
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vrm4nov0 = COPY $v8
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vrm4nov0 = COPY $v12
    ; CHECK-NEXT: [[COPY4:%[0-9]+]]:vrm4nov0 = COPY $v16
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK [[COPY4]], [[COPY4]], [[COPY4]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMUL_VV_M4_E64_MASK1:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK [[COPY2]], [[COPY1]], [[COPY2]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFMSAC_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFMSAC_VV_M4_E64_MASK killed [[PseudoVFMUL_VV_M4_E64_MASK1]], [[COPY3]], [[COPY1]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFNMSAC_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFNMSAC_VV_M4_E64_MASK killed [[PseudoVFMUL_VV_M4_E64_MASK]], [[COPY3]], [[COPY2]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: [[PseudoVFSUB_VV_M4_E64_MASK:%[0-9]+]]:vrm4nov0 = contract reassoc PseudoVFSUB_VV_M4_E64_MASK [[COPY1]], killed [[PseudoVFNMSAC_VV_M4_E64_MASK]], killed [[PseudoVFMSAC_VV_M4_E64_MASK]], [[COPY]], 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    ; CHECK-NEXT: $v8 = COPY [[PseudoVFSUB_VV_M4_E64_MASK]]
    ; CHECK-NEXT: PseudoRET implicit $v8
    %0:vmv0 = COPY $v0
    %16:vrm4nov0 = COPY $v4
    %17:vrm4nov0 = COPY $v8
    %18:vrm4nov0 = COPY $v12
    %19:vrm4nov0 = COPY $v16
    %20:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %19, %19, %19, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %21:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %20, %18, %17, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %22:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %17, %16, %17, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %23:vrm4nov0 = contract reassoc PseudoVFMUL_VV_M4_E64_MASK %22, %18, %16, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %32:vrm4nov0 = contract reassoc PseudoVFSUB_VV_M4_E64_MASK %22, killed %23, killed %22, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %33:vrm4nov0 = contract reassoc PseudoVFSUB_VV_M4_E64_MASK %20, killed %20, killed %21, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    %34:vrm4nov0 = contract reassoc PseudoVFSUB_VV_M4_E64_MASK %16, killed %33, killed %32, %0, 7, 16, 6 /* e64 */, 1 /* ta, mu */, implicit $frm
    $v8 = COPY %34
    PseudoRET implicit $v8
...
