; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple riscv32 -mattr=+v | FileCheck %s
; RUN: llc < %s -mtriple riscv64 -mattr=+v | FileCheck %s

define <vscale x 1 x i1> @nxv1i1(<vscale x 1 x i1> %m) {
; CHECK-LABEL: nxv1i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf8, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 1 x i1> @llvm.mask.beforefirst(<vscale x 1 x i1> %m)
  ret <vscale x 1 x i1> %x
}

define <vscale x 2 x i1> @nxv2i1(<vscale x 2 x i1> %m) {
; CHECK-LABEL: nxv2i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf4, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 2 x i1> @llvm.mask.beforefirst(<vscale x 2 x i1> %m)
  ret <vscale x 2 x i1> %x
}

define <vscale x 4 x i1> @nxv4i1(<vscale x 4 x i1> %m) {
; CHECK-LABEL: nxv4i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 4 x i1> @llvm.mask.beforefirst(<vscale x 4 x i1> %m)
  ret <vscale x 4 x i1> %x
}

define <vscale x 8 x i1> @nxv8i1(<vscale x 8 x i1> %m) {
; CHECK-LABEL: nxv8i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m1, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv.v.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 8 x i1> @llvm.mask.beforefirst(<vscale x 8 x i1> %m)
  ret <vscale x 8 x i1> %x
}

define <vscale x 16 x i1> @nxv16i1(<vscale x 16 x i1> %m) {
; CHECK-LABEL: nxv16i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m2, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 16 x i1> @llvm.mask.beforefirst(<vscale x 16 x i1> %m)
  ret <vscale x 16 x i1> %x
}

define <vscale x 32 x i1> @nxv32i1(<vscale x 32 x i1> %m) {
; CHECK-LABEL: nxv32i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m4, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 32 x i1> @llvm.mask.beforefirst(<vscale x 32 x i1> %m)
  ret <vscale x 32 x i1> %x
}

define <vscale x 64 x i1> @nxv64i1(<vscale x 64 x i1> %m) {
; CHECK-LABEL: nxv64i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m8, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 64 x i1> @llvm.mask.beforefirst(<vscale x 64 x i1> %m)
  ret <vscale x 64 x i1> %x
}

; Widening

define <vscale x 3 x i1> @nxv3i1(<vscale x 3 x i1> %m) {
; CHECK-LABEL: nxv3i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, mf2, ta, ma
; CHECK-NEXT:    vmsbf.m v8, v0
; CHECK-NEXT:    vmv1r.v v0, v8
; CHECK-NEXT:    ret
  %x = call <vscale x 3 x i1> @llvm.mask.beforefirst(<vscale x 3 x i1> %m)
  ret <vscale x 3 x i1> %x
}

; Splitting

define <vscale x 128 x i1> @nxv128i1(<vscale x 128 x i1> %m) {
; CHECK-LABEL: nxv128i1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli a0, zero, e8, m8, ta, ma
; CHECK-NEXT:    vmsbf.m v9, v0
; CHECK-NEXT:    vcpop.m a0, v9
; CHECK-NEXT:    snez a0, a0
; CHECK-NEXT:    vmv.v.x v16, a0
; CHECK-NEXT:    vmsne.vi v10, v16, 0
; CHECK-NEXT:    vmsbf.m v11, v8
; CHECK-NEXT:    vmandn.mm v8, v11, v10
; CHECK-NEXT:    vmv1r.v v0, v9
; CHECK-NEXT:    ret
  %x = call <vscale x 128 x i1> @llvm.mask.beforefirst(<vscale x 128 x i1> %m)
  ret <vscale x 128 x i1> %x
}
