; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=riscv32 -mattr=+v -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: llc -mtriple=riscv64 -mattr=+v -verify-machineinstrs < %s | FileCheck %s --check-prefixes=CHECK,RV64
;
; testcase from:
; int reduc_plus (int *a, int n)  {
;  int r = 13;
;  for (int i = 0; i < n; ++i)
;   r += a[i];
;  return r;
; }


define dso_local signext i32 @reduc_plus(ptr noundef readonly captures(none) %0, i64 noundef %1, <vscale x 4 x i32> %a10, i32 %vl) {
; RV32-LABEL: reduc_plus:
; RV32:       # %bb.0:
; RV32-NEXT:    beqz a2, .LBB0_3
; RV32-NEXT:  # %bb.1:
; RV32-NEXT:    srli a0, a2, 31
; RV32-NEXT:    beqz a0, .LBB0_4
; RV32-NEXT:  .LBB0_2:
; RV32-NEXT:    li a0, 13
; RV32-NEXT:    ret
; RV32-NEXT:  .LBB0_3:
; RV32-NEXT:    seqz a0, a1
; RV32-NEXT:    bnez a0, .LBB0_2
; RV32-NEXT:  .LBB0_4: # %.preheader
; RV32-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV32-NEXT:    vmv.v.i v10, 0
; RV32-NEXT:  .LBB0_5: # =>This Inner Loop Header: Depth=1
; RV32-NEXT:    sltu a0, a1, a3
; RV32-NEXT:    sub a1, a1, a3
; RV32-NEXT:    sub a2, a2, a0
; RV32-NEXT:    or a0, a1, a2
; RV32-NEXT:    vsetvli zero, a3, e32, m2, tu, ma
; RV32-NEXT:    vadd.vv v10, v8, v10
; RV32-NEXT:    bnez a0, .LBB0_5
; RV32-NEXT:  # %bb.6:
; RV32-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; RV32-NEXT:    vmv.v.i v8, 13
; RV32-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV32-NEXT:    vredsum.vs v8, v10, v8
; RV32-NEXT:    vmv.x.s a0, v8
; RV32-NEXT:    ret
;
; RV64-LABEL: reduc_plus:
; RV64:       # %bb.0:
; RV64-NEXT:    blez a1, .LBB0_4
; RV64-NEXT:  # %bb.1: # %.preheader
; RV64-NEXT:    neg a0, a1
; RV64-NEXT:    slli a1, a2, 32
; RV64-NEXT:    srli a1, a1, 32
; RV64-NEXT:    vsetvli a2, zero, e32, m2, ta, ma
; RV64-NEXT:    vmv.v.i v10, 0
; RV64-NEXT:  .LBB0_2: # =>This Inner Loop Header: Depth=1
; RV64-NEXT:    add a0, a0, a1
; RV64-NEXT:    vsetvli zero, a1, e32, m2, tu, ma
; RV64-NEXT:    vadd.vv v10, v8, v10
; RV64-NEXT:    bnez a0, .LBB0_2
; RV64-NEXT:  # %bb.3:
; RV64-NEXT:    vsetivli zero, 1, e32, m1, ta, ma
; RV64-NEXT:    vmv.v.i v8, 13
; RV64-NEXT:    vsetvli a0, zero, e32, m2, ta, ma
; RV64-NEXT:    vredsum.vs v8, v10, v8
; RV64-NEXT:    vmv.x.s a0, v8
; RV64-NEXT:    ret
; RV64-NEXT:  .LBB0_4:
; RV64-NEXT:    li a0, 13
; RV64-NEXT:    ret
  %3 = icmp sgt i64 %1, 0
  br i1 %3, label %4, label %19

4:
  %5 = phi i64 [ %14, %4 ], [ 0, %2 ]
  %6 = phi <vscale x 4 x i32> [ %12, %4 ], [ insertelement (<vscale x 4 x i32> zeroinitializer, i32 13, i32 0), %2 ]
  %7 = phi i64 [ %15, %4 ], [ %1, %2 ]
  %11 = add <vscale x 4 x i32> %a10, %6
  %12 = tail call <vscale x 4 x i32> @llvm.vp.merge.nxv4i32(<vscale x 4 x i1> splat (i1 true), <vscale x 4 x i32> %11, <vscale x 4 x i32> %6, i32 %vl)
  %13 = zext i32 %vl to i64
  %14 = add i64 %5, %13
  %15 = sub nuw i64 %7, %13
  %16 = icmp eq i64 %15, 0
  br i1 %16, label %17, label %4

17:
  %18 = tail call i32 @llvm.vector.reduce.add.nxv4i32(<vscale x 4 x i32> %12)
  br label %19

19:
  %20 = phi i32 [ 13, %2 ], [ %18, %17 ]
  ret i32 %20
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
