# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 3
# RUN: llc %s -o - -mtriple=riscv64 -mattr=+v -run-pass=liveintervals,twoaddressinstruction,register-coalescer -verify-machineinstrs | FileCheck %s

...
---
name:            f
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v8
    ; CHECK-LABEL: name: f
    ; CHECK: liveins: $v8
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: KILL $v8
    ; CHECK-NEXT: PseudoRET
    %0:vr = COPY killed $v8
    %2:vrm8 = INSERT_SUBREG undef %1:vrm8, killed %0, %subreg.sub_vrm1_0
    %3:vrm4 = COPY %2.sub_vrm4_0:vrm8

    PseudoRET

...
---
name:            g
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $v8, $v16
    ; CHECK-LABEL: name: g
    ; CHECK: liveins: $v8, $v16
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: KILL $v8
    ; CHECK-NEXT: dead [[COPY:%[0-9]+]]:vrm8 = COPY $v16
    ; CHECK-NEXT: PseudoRET
    %0:vr = COPY killed $v8
    %1:vrm8 = COPY killed $v16
    %2:vrm8 = INSERT_SUBREG %1:vrm8, killed %0, %subreg.sub_vrm1_0
    %3:vrm4 = COPY %2.sub_vrm4_0:vrm8

    PseudoRET

...
