; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=riscv32 -mattr=+v,+zvfbfmin -verify-machineinstrs | FileCheck %s
; RUN: llc < %s -mtriple=riscv64 -mattr=+v,+zvfbfmin -verify-machineinstrs | FileCheck %s

define <vscale x 1 x bfloat> @nxv1bf16(<vscale x 1 x bfloat> %va) {
; CHECK-LABEL: nxv1bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vsetvli a1, zero, e16, mf4, ta, ma
; CHECK-NEXT:    vxor.vx v8, v8, a0
; CHECK-NEXT:    ret
  %vb = fneg <vscale x 1 x bfloat> %va
  ret <vscale x 1 x bfloat> %vb
}

define <vscale x 2 x bfloat> @nxv2bf16(<vscale x 2 x bfloat> %va) {
; CHECK-LABEL: nxv2bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vsetvli a1, zero, e16, mf2, ta, ma
; CHECK-NEXT:    vxor.vx v8, v8, a0
; CHECK-NEXT:    ret
  %vb = fneg <vscale x 2 x bfloat> %va
  ret <vscale x 2 x bfloat> %vb
}

define <vscale x 4 x bfloat> @nxv4bf16(<vscale x 4 x bfloat> %va) {
; CHECK-LABEL: nxv4bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vsetvli a1, zero, e16, m1, ta, ma
; CHECK-NEXT:    vxor.vx v8, v8, a0
; CHECK-NEXT:    ret
  %vb = fneg <vscale x 4 x bfloat> %va
  ret <vscale x 4 x bfloat> %vb
}

define <vscale x 8 x bfloat> @nxv8bf16(<vscale x 8 x bfloat> %va) {
; CHECK-LABEL: nxv8bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vsetvli a1, zero, e16, m2, ta, ma
; CHECK-NEXT:    vxor.vx v8, v8, a0
; CHECK-NEXT:    ret
  %vb = fneg <vscale x 8 x bfloat> %va
  ret <vscale x 8 x bfloat> %vb
}

define <vscale x 16 x bfloat> @nxv16bf16(<vscale x 16 x bfloat> %va) {
; CHECK-LABEL: nxv16bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vsetvli a1, zero, e16, m4, ta, ma
; CHECK-NEXT:    vxor.vx v8, v8, a0
; CHECK-NEXT:    ret
  %vb = fneg <vscale x 16 x bfloat> %va
  ret <vscale x 16 x bfloat> %vb
}

define <vscale x 32 x bfloat> @nxv32bf16(<vscale x 32 x bfloat> %va) {
; CHECK-LABEL: nxv32bf16:
; CHECK:       # %bb.0:
; CHECK-NEXT:    lui a0, 8
; CHECK-NEXT:    vsetvli a1, zero, e16, m8, ta, ma
; CHECK-NEXT:    vxor.vx v8, v8, a0
; CHECK-NEXT:    ret
  %vb = fneg <vscale x 32 x bfloat> %va
  ret <vscale x 32 x bfloat> %vb
}
