# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -o - -mtriple=riscv64 -mattr=+v -run-pass=riscv-vl-optimizer -verify-machineinstrs | FileCheck %s

---
name: test
body: |
  bb.0:
    liveins: $x11

    ; CHECK-LABEL: name: test
    ; CHECK: liveins: $x11
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:gpr = COPY $x11
    ; CHECK-NEXT: [[LD:%[0-9]+]]:gpr = LD [[COPY]], 32
    ; CHECK-NEXT: [[LD1:%[0-9]+]]:gpr = LD [[LD]], 0
    ; CHECK-NEXT: [[LD2:%[0-9]+]]:gpr = LD [[LD]], 8
    ; CHECK-NEXT: [[LD3:%[0-9]+]]:gpr = LD [[LD]], 16
    ; CHECK-NEXT: [[ADDI:%[0-9]+]]:gpr = ADDI killed [[LD3]], 64
    ; CHECK-NEXT: [[LW:%[0-9]+]]:gpr = LW [[LD1]], 4
    ; CHECK-NEXT: [[LW1:%[0-9]+]]:gpr = LW [[LD1]], 0
    ; CHECK-NEXT: [[LWU:%[0-9]+]]:gpr = LWU [[LD1]], 12
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:gpr = XOR [[LW]], [[LW1]]
    ; CHECK-NEXT: [[LUI:%[0-9]+]]:gpr = LUI 113938
    ; CHECK-NEXT: [[ADDI1:%[0-9]+]]:gpr = ADDI killed [[LUI]], -1062
    ; CHECK-NEXT: [[XOR1:%[0-9]+]]:gpr = XOR killed [[XOR]], killed [[ADDI1]]
    ; CHECK-NEXT: [[LW2:%[0-9]+]]:gpr = LW [[LD1]], 8
    ; CHECK-NEXT: [[SLLI:%[0-9]+]]:gpr = SLLI killed [[LW2]], 32
    ; CHECK-NEXT: [[OR:%[0-9]+]]:gpr = OR killed [[SLLI]], killed [[LWU]]
    ; CHECK-NEXT: [[PseudoVID_V_M1_:%[0-9]+]]:vr = PseudoVID_V_M1 $noreg, 4, 6 /* e64 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_M1_:%[0-9]+]]:vr = PseudoVADD_VX_M1 $noreg, killed [[PseudoVID_V_M1_]], killed [[OR]], 4, 6 /* e64 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVNSRL_WI_MF2_:%[0-9]+]]:vr = PseudoVNSRL_WI_MF2 $noreg, [[PseudoVADD_VX_M1_]], 0, 4, 5 /* e32 */, 3 /* ta, ma */
    ; CHECK-NEXT: [[ADDI2:%[0-9]+]]:gpr = ADDI $x0, 32
    ; CHECK-NEXT: [[PseudoVNSRL_WX_MF2_:%[0-9]+]]:vr = PseudoVNSRL_WX_MF2 $noreg, [[PseudoVADD_VX_M1_]], killed [[ADDI2]], 4, 5 /* e32 */, 3 /* ta, ma */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, killed [[PseudoVNSRL_WI_MF2_]], [[LW1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_1:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, killed [[PseudoVNSRL_WX_MF2_]], [[LW]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, killed [[PseudoVADD_VX_MF2_]], [[PseudoVADD_VX_MF2_1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVADD_VX_MF2_1]], 19, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVADD_VX_MF2_1]], 13, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_]], killed [[PseudoVSRL_VI_MF2_]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_]], killed [[PseudoVOR_VV_MF2_]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_1:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_]], [[PseudoVADD_VV_MF2_]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_1:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_]], 17, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_1:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_]], 15, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_1:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_1]], killed [[PseudoVSRL_VI_MF2_1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_1:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_1]], killed [[PseudoVOR_VV_MF2_1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_2:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_1]], [[PseudoVADD_VV_MF2_1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_2:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_1]], 6, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_2:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_1]], 26, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_2:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_2]], killed [[PseudoVSRL_VI_MF2_2]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_2:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_2]], killed [[PseudoVOR_VV_MF2_2]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_3:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_2]], [[PseudoVADD_VV_MF2_2]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_3:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_2]], 26, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_3:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_2]], 6, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_3:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_3]], killed [[PseudoVSRL_VI_MF2_3]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_3:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_3]], killed [[PseudoVOR_VV_MF2_3]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_2:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, [[PseudoVADD_VV_MF2_3]], [[LW]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_3:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, killed [[PseudoVXOR_VV_MF2_3]], [[XOR1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VI_MF2_:%[0-9]+]]:vr = PseudoVADD_VI_MF2 $noreg, killed [[PseudoVADD_VX_MF2_3]], 1, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_4:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, killed [[PseudoVADD_VX_MF2_2]], [[PseudoVADD_VI_MF2_]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_4:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_]], 15, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_4:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_]], 17, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_4:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_4]], killed [[PseudoVSRL_VI_MF2_4]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_4:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_4]], killed [[PseudoVOR_VV_MF2_4]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_5:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_4]], [[PseudoVADD_VV_MF2_4]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_5:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_4]], 3, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_5:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_4]], 29, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_5:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_5]], killed [[PseudoVSRL_VI_MF2_5]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_5:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_5]], killed [[PseudoVOR_VV_MF2_5]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_6:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_5]], [[PseudoVADD_VV_MF2_5]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_6:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_5]], 16, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_6:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_5]], 16, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_6:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_6]], killed [[PseudoVSRL_VI_MF2_6]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_6:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_6]], killed [[PseudoVOR_VV_MF2_6]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_7:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_6]], [[PseudoVADD_VV_MF2_6]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_7:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_6]], 8, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_7:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_6]], 24, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_7:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_7]], killed [[PseudoVSRL_VI_MF2_7]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_7:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_7]], killed [[PseudoVOR_VV_MF2_7]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_4:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, [[PseudoVADD_VV_MF2_7]], [[XOR1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_5:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, killed [[PseudoVXOR_VV_MF2_7]], [[LW1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VI_MF2_1:%[0-9]+]]:vr = PseudoVADD_VI_MF2 $noreg, killed [[PseudoVADD_VX_MF2_5]], 2, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_8:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, killed [[PseudoVADD_VX_MF2_4]], [[PseudoVADD_VI_MF2_1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_8:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_1]], 19, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_8:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_1]], 13, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_8:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_8]], killed [[PseudoVSRL_VI_MF2_8]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_8:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_8]], killed [[PseudoVOR_VV_MF2_8]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_9:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_8]], [[PseudoVADD_VV_MF2_8]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_9:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_8]], 17, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_9:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_8]], 15, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_9:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_9]], killed [[PseudoVSRL_VI_MF2_9]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_9:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_9]], killed [[PseudoVOR_VV_MF2_9]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_10:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_9]], [[PseudoVADD_VV_MF2_9]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_10:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_9]], 6, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_10:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_9]], 26, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_10:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_10]], killed [[PseudoVSRL_VI_MF2_10]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_10:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_10]], killed [[PseudoVOR_VV_MF2_10]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_11:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_10]], [[PseudoVADD_VV_MF2_10]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_11:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_10]], 26, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_11:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_10]], 6, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_11:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_11]], killed [[PseudoVSRL_VI_MF2_11]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_11:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_11]], killed [[PseudoVOR_VV_MF2_11]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_6:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, [[PseudoVADD_VV_MF2_11]], [[LW1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_7:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, killed [[PseudoVXOR_VV_MF2_11]], [[LW]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VI_MF2_2:%[0-9]+]]:vr = PseudoVADD_VI_MF2 $noreg, killed [[PseudoVADD_VX_MF2_7]], 3, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_12:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, killed [[PseudoVADD_VX_MF2_6]], [[PseudoVADD_VI_MF2_2]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_12:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_2]], 15, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_12:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_2]], 17, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_12:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_12]], killed [[PseudoVSRL_VI_MF2_12]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_12:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_12]], killed [[PseudoVOR_VV_MF2_12]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_13:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_12]], [[PseudoVADD_VV_MF2_12]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_13:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_12]], 3, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_13:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_12]], 29, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_13:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_13]], killed [[PseudoVSRL_VI_MF2_13]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_13:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_13]], killed [[PseudoVOR_VV_MF2_13]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_14:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_13]], [[PseudoVADD_VV_MF2_13]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_14:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_13]], 16, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_14:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_13]], 16, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_14:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_14]], killed [[PseudoVSRL_VI_MF2_14]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_14:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_14]], killed [[PseudoVOR_VV_MF2_14]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_15:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_14]], [[PseudoVADD_VV_MF2_14]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_15:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_14]], 8, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_15:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_14]], 24, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_15:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_15]], killed [[PseudoVSRL_VI_MF2_15]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_15:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_15]], killed [[PseudoVOR_VV_MF2_15]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_8:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, [[PseudoVADD_VV_MF2_15]], [[LW]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_9:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, killed [[PseudoVXOR_VV_MF2_15]], [[XOR1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VI_MF2_3:%[0-9]+]]:vr = PseudoVADD_VI_MF2 $noreg, killed [[PseudoVADD_VX_MF2_9]], 4, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_16:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, killed [[PseudoVADD_VX_MF2_8]], [[PseudoVADD_VI_MF2_3]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_16:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_3]], 19, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_16:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVADD_VI_MF2_3]], 13, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_16:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_16]], killed [[PseudoVSRL_VI_MF2_16]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_16:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_16]], killed [[PseudoVOR_VV_MF2_16]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_17:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_16]], [[PseudoVADD_VV_MF2_16]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_17:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_16]], 17, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_17:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_16]], 15, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_17:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_17]], killed [[PseudoVSRL_VI_MF2_17]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_17:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_17]], killed [[PseudoVOR_VV_MF2_17]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_18:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_17]], [[PseudoVADD_VV_MF2_17]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_18:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_17]], 6, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_18:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_17]], 26, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_18:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_18]], killed [[PseudoVSRL_VI_MF2_18]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_18:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_18]], killed [[PseudoVOR_VV_MF2_18]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VV_MF2_19:%[0-9]+]]:vr = PseudoVADD_VV_MF2 $noreg, [[PseudoVXOR_VV_MF2_18]], [[PseudoVADD_VV_MF2_18]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSRL_VI_MF2_19:%[0-9]+]]:vr = PseudoVSRL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_18]], 26, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVSLL_VI_MF2_19:%[0-9]+]]:vr = PseudoVSLL_VI_MF2 $noreg, [[PseudoVXOR_VV_MF2_18]], 6, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVOR_VV_MF2_19:%[0-9]+]]:vr = PseudoVOR_VV_MF2 $noreg, killed [[PseudoVSLL_VI_MF2_19]], killed [[PseudoVSRL_VI_MF2_19]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVXOR_VV_MF2_19:%[0-9]+]]:vr = PseudoVXOR_VV_MF2 $noreg, [[PseudoVADD_VV_MF2_19]], killed [[PseudoVOR_VV_MF2_19]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_10:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, [[PseudoVADD_VV_MF2_19]], [[XOR1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VX_MF2_11:%[0-9]+]]:vr = PseudoVADD_VX_MF2 $noreg, killed [[PseudoVXOR_VV_MF2_19]], [[LW1]], 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: [[PseudoVADD_VI_MF2_4:%[0-9]+]]:vr = PseudoVADD_VI_MF2 $noreg, killed [[PseudoVADD_VX_MF2_11]], 5, 4, 5 /* e32 */, 1 /* ta, mu */
    ; CHECK-NEXT: PseudoVSE32_V_MF2 killed [[PseudoVADD_VX_MF2_10]], killed [[LD2]], 4, 5 /* e32 */
    ; CHECK-NEXT: PseudoVSE32_V_MF2 killed [[PseudoVADD_VI_MF2_4]], killed [[ADDI]], 4, 5 /* e32 */
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:gpr = COPY $x0
    ; CHECK-NEXT: $x10 = COPY [[COPY1]]
    ; CHECK-NEXT: PseudoRET implicit $x10
    %1:gpr = COPY $x11
    %3:gpr = LD %1, 32
    %4:gpr = LD %3, 0
    %5:gpr = LD %3, 8
    %6:gpr = LD %3, 16
    %7:gpr = ADDI killed %6, 64
    %8:gpr = LW %4, 4
    %9:gpr = LW %4, 0
    %10:gpr = LWU %4, 12
    %11:gpr = XOR %8, %9
    %12:gpr = LUI 113938
    %13:gpr = ADDI killed %12, -1062
    %14:gpr = XOR killed %11, killed %13
    %15:gpr = LW %4, 8
    %16:gpr = SLLI killed %15, 32
    %17:gpr = OR killed %16, killed %10
    %18:vr = PseudoVID_V_M1 $noreg, 4, 6 /* e64 */, 1 /* ta, mu */
    %19:vr = PseudoVADD_VX_M1 $noreg, killed %18, killed %17, 4, 6 /* e64 */, 1 /* ta, mu */
    %20:vr = PseudoVNSRL_WI_MF2 $noreg, %19, 0, 4, 5 /* e32 */, 3 /* ta, ma */
    %21:gpr = ADDI $x0, 32
    %22:vr = PseudoVNSRL_WX_MF2 $noreg, %19, killed %21, 4, 5 /* e32 */, 3 /* ta, ma */
    %23:vr = PseudoVADD_VX_MF2 $noreg, killed %20, %9, 4, 5 /* e32 */, 1 /* ta, mu */
    %24:vr = PseudoVADD_VX_MF2 $noreg, killed %22, %8, 4, 5 /* e32 */, 1 /* ta, mu */
    %25:vr = PseudoVADD_VV_MF2 $noreg, killed %23, %24, 4, 5 /* e32 */, 1 /* ta, mu */
    %26:vr = PseudoVSRL_VI_MF2 $noreg, %24, 19, 4, 5 /* e32 */, 1 /* ta, mu */
    %27:vr = PseudoVSLL_VI_MF2 $noreg, %24, 13, 4, 5 /* e32 */, 1 /* ta, mu */
    %28:vr = PseudoVOR_VV_MF2 $noreg, killed %27, killed %26, 4, 5 /* e32 */, 1 /* ta, mu */
    %29:vr = PseudoVXOR_VV_MF2 $noreg, %25, killed %28, 4, 5 /* e32 */, 1 /* ta, mu */
    %30:vr = PseudoVADD_VV_MF2 $noreg, %29, %25, 4, 5 /* e32 */, 1 /* ta, mu */
    %31:vr = PseudoVSRL_VI_MF2 $noreg, %29, 17, 4, 5 /* e32 */, 1 /* ta, mu */
    %32:vr = PseudoVSLL_VI_MF2 $noreg, %29, 15, 4, 5 /* e32 */, 1 /* ta, mu */
    %33:vr = PseudoVOR_VV_MF2 $noreg, killed %32, killed %31, 4, 5 /* e32 */, 1 /* ta, mu */
    %34:vr = PseudoVXOR_VV_MF2 $noreg, %30, killed %33, 4, 5 /* e32 */, 1 /* ta, mu */
    %35:vr = PseudoVADD_VV_MF2 $noreg, %34, %30, 4, 5 /* e32 */, 1 /* ta, mu */
    %36:vr = PseudoVSRL_VI_MF2 $noreg, %34, 6, 4, 5 /* e32 */, 1 /* ta, mu */
    %37:vr = PseudoVSLL_VI_MF2 $noreg, %34, 26, 4, 5 /* e32 */, 1 /* ta, mu */
    %38:vr = PseudoVOR_VV_MF2 $noreg, killed %37, killed %36, 4, 5 /* e32 */, 1 /* ta, mu */
    %39:vr = PseudoVXOR_VV_MF2 $noreg, %35, killed %38, 4, 5 /* e32 */, 1 /* ta, mu */
    %40:vr = PseudoVADD_VV_MF2 $noreg, %39, %35, 4, 5 /* e32 */, 1 /* ta, mu */
    %41:vr = PseudoVSRL_VI_MF2 $noreg, %39, 26, 4, 5 /* e32 */, 1 /* ta, mu */
    %42:vr = PseudoVSLL_VI_MF2 $noreg, %39, 6, 4, 5 /* e32 */, 1 /* ta, mu */
    %43:vr = PseudoVOR_VV_MF2 $noreg, killed %42, killed %41, 4, 5 /* e32 */, 1 /* ta, mu */
    %44:vr = PseudoVXOR_VV_MF2 $noreg, %40, killed %43, 4, 5 /* e32 */, 1 /* ta, mu */
    %45:vr = PseudoVADD_VX_MF2 $noreg, %40, %8, 4, 5 /* e32 */, 1 /* ta, mu */
    %46:vr = PseudoVADD_VX_MF2 $noreg, killed %44, %14, 4, 5 /* e32 */, 1 /* ta, mu */
    %47:vr = PseudoVADD_VI_MF2 $noreg, killed %46, 1, 4, 5 /* e32 */, 1 /* ta, mu */
    %48:vr = PseudoVADD_VV_MF2 $noreg, killed %45, %47, 4, 5 /* e32 */, 1 /* ta, mu */
    %49:vr = PseudoVSRL_VI_MF2 $noreg, %47, 15, 4, 5 /* e32 */, 1 /* ta, mu */
    %50:vr = PseudoVSLL_VI_MF2 $noreg, %47, 17, 4, 5 /* e32 */, 1 /* ta, mu */
    %51:vr = PseudoVOR_VV_MF2 $noreg, killed %50, killed %49, 4, 5 /* e32 */, 1 /* ta, mu */
    %52:vr = PseudoVXOR_VV_MF2 $noreg, %48, killed %51, 4, 5 /* e32 */, 1 /* ta, mu */
    %53:vr = PseudoVADD_VV_MF2 $noreg, %52, %48, 4, 5 /* e32 */, 1 /* ta, mu */
    %54:vr = PseudoVSRL_VI_MF2 $noreg, %52, 3, 4, 5 /* e32 */, 1 /* ta, mu */
    %55:vr = PseudoVSLL_VI_MF2 $noreg, %52, 29, 4, 5 /* e32 */, 1 /* ta, mu */
    %56:vr = PseudoVOR_VV_MF2 $noreg, killed %55, killed %54, 4, 5 /* e32 */, 1 /* ta, mu */
    %57:vr = PseudoVXOR_VV_MF2 $noreg, %53, killed %56, 4, 5 /* e32 */, 1 /* ta, mu */
    %58:vr = PseudoVADD_VV_MF2 $noreg, %57, %53, 4, 5 /* e32 */, 1 /* ta, mu */
    %59:vr = PseudoVSRL_VI_MF2 $noreg, %57, 16, 4, 5 /* e32 */, 1 /* ta, mu */
    %60:vr = PseudoVSLL_VI_MF2 $noreg, %57, 16, 4, 5 /* e32 */, 1 /* ta, mu */
    %61:vr = PseudoVOR_VV_MF2 $noreg, killed %60, killed %59, 4, 5 /* e32 */, 1 /* ta, mu */
    %62:vr = PseudoVXOR_VV_MF2 $noreg, %58, killed %61, 4, 5 /* e32 */, 1 /* ta, mu */
    %63:vr = PseudoVADD_VV_MF2 $noreg, %62, %58, 4, 5 /* e32 */, 1 /* ta, mu */
    %64:vr = PseudoVSRL_VI_MF2 $noreg, %62, 8, 4, 5 /* e32 */, 1 /* ta, mu */
    %65:vr = PseudoVSLL_VI_MF2 $noreg, %62, 24, 4, 5 /* e32 */, 1 /* ta, mu */
    %66:vr = PseudoVOR_VV_MF2 $noreg, killed %65, killed %64, 4, 5 /* e32 */, 1 /* ta, mu */
    %67:vr = PseudoVXOR_VV_MF2 $noreg, %63, killed %66, 4, 5 /* e32 */, 1 /* ta, mu */
    %68:vr = PseudoVADD_VX_MF2 $noreg, %63, %14, 4, 5 /* e32 */, 1 /* ta, mu */
    %69:vr = PseudoVADD_VX_MF2 $noreg, killed %67, %9, 4, 5 /* e32 */, 1 /* ta, mu */
    %70:vr = PseudoVADD_VI_MF2 $noreg, killed %69, 2, 4, 5 /* e32 */, 1 /* ta, mu */
    %71:vr = PseudoVADD_VV_MF2 $noreg, killed %68, %70, 4, 5 /* e32 */, 1 /* ta, mu */
    %72:vr = PseudoVSRL_VI_MF2 $noreg, %70, 19, 4, 5 /* e32 */, 1 /* ta, mu */
    %73:vr = PseudoVSLL_VI_MF2 $noreg, %70, 13, 4, 5 /* e32 */, 1 /* ta, mu */
    %74:vr = PseudoVOR_VV_MF2 $noreg, killed %73, killed %72, 4, 5 /* e32 */, 1 /* ta, mu */
    %75:vr = PseudoVXOR_VV_MF2 $noreg, %71, killed %74, 4, 5 /* e32 */, 1 /* ta, mu */
    %76:vr = PseudoVADD_VV_MF2 $noreg, %75, %71, 4, 5 /* e32 */, 1 /* ta, mu */
    %77:vr = PseudoVSRL_VI_MF2 $noreg, %75, 17, 4, 5 /* e32 */, 1 /* ta, mu */
    %78:vr = PseudoVSLL_VI_MF2 $noreg, %75, 15, 4, 5 /* e32 */, 1 /* ta, mu */
    %79:vr = PseudoVOR_VV_MF2 $noreg, killed %78, killed %77, 4, 5 /* e32 */, 1 /* ta, mu */
    %80:vr = PseudoVXOR_VV_MF2 $noreg, %76, killed %79, 4, 5 /* e32 */, 1 /* ta, mu */
    %81:vr = PseudoVADD_VV_MF2 $noreg, %80, %76, 4, 5 /* e32 */, 1 /* ta, mu */
    %82:vr = PseudoVSRL_VI_MF2 $noreg, %80, 6, 4, 5 /* e32 */, 1 /* ta, mu */
    %83:vr = PseudoVSLL_VI_MF2 $noreg, %80, 26, 4, 5 /* e32 */, 1 /* ta, mu */
    %84:vr = PseudoVOR_VV_MF2 $noreg, killed %83, killed %82, 4, 5 /* e32 */, 1 /* ta, mu */
    %85:vr = PseudoVXOR_VV_MF2 $noreg, %81, killed %84, 4, 5 /* e32 */, 1 /* ta, mu */
    %86:vr = PseudoVADD_VV_MF2 $noreg, %85, %81, 4, 5 /* e32 */, 1 /* ta, mu */
    %87:vr = PseudoVSRL_VI_MF2 $noreg, %85, 26, 4, 5 /* e32 */, 1 /* ta, mu */
    %88:vr = PseudoVSLL_VI_MF2 $noreg, %85, 6, 4, 5 /* e32 */, 1 /* ta, mu */
    %89:vr = PseudoVOR_VV_MF2 $noreg, killed %88, killed %87, 4, 5 /* e32 */, 1 /* ta, mu */
    %90:vr = PseudoVXOR_VV_MF2 $noreg, %86, killed %89, 4, 5 /* e32 */, 1 /* ta, mu */
    %91:vr = PseudoVADD_VX_MF2 $noreg, %86, %9, 4, 5 /* e32 */, 1 /* ta, mu */
    %92:vr = PseudoVADD_VX_MF2 $noreg, killed %90, %8, 4, 5 /* e32 */, 1 /* ta, mu */
    %93:vr = PseudoVADD_VI_MF2 $noreg, killed %92, 3, 4, 5 /* e32 */, 1 /* ta, mu */
    %94:vr = PseudoVADD_VV_MF2 $noreg, killed %91, %93, 4, 5 /* e32 */, 1 /* ta, mu */
    %95:vr = PseudoVSRL_VI_MF2 $noreg, %93, 15, 4, 5 /* e32 */, 1 /* ta, mu */
    %96:vr = PseudoVSLL_VI_MF2 $noreg, %93, 17, 4, 5 /* e32 */, 1 /* ta, mu */
    %97:vr = PseudoVOR_VV_MF2 $noreg, killed %96, killed %95, 4, 5 /* e32 */, 1 /* ta, mu */
    %98:vr = PseudoVXOR_VV_MF2 $noreg, %94, killed %97, 4, 5 /* e32 */, 1 /* ta, mu */
    %99:vr = PseudoVADD_VV_MF2 $noreg, %98, %94, 4, 5 /* e32 */, 1 /* ta, mu */
    %100:vr = PseudoVSRL_VI_MF2 $noreg, %98, 3, 4, 5 /* e32 */, 1 /* ta, mu */
    %101:vr = PseudoVSLL_VI_MF2 $noreg, %98, 29, 4, 5 /* e32 */, 1 /* ta, mu */
    %102:vr = PseudoVOR_VV_MF2 $noreg, killed %101, killed %100, 4, 5 /* e32 */, 1 /* ta, mu */
    %103:vr = PseudoVXOR_VV_MF2 $noreg, %99, killed %102, 4, 5 /* e32 */, 1 /* ta, mu */
    %104:vr = PseudoVADD_VV_MF2 $noreg, %103, %99, 4, 5 /* e32 */, 1 /* ta, mu */
    %105:vr = PseudoVSRL_VI_MF2 $noreg, %103, 16, 4, 5 /* e32 */, 1 /* ta, mu */
    %106:vr = PseudoVSLL_VI_MF2 $noreg, %103, 16, 4, 5 /* e32 */, 1 /* ta, mu */
    %107:vr = PseudoVOR_VV_MF2 $noreg, killed %106, killed %105, 4, 5 /* e32 */, 1 /* ta, mu */
    %108:vr = PseudoVXOR_VV_MF2 $noreg, %104, killed %107, 4, 5 /* e32 */, 1 /* ta, mu */
    %109:vr = PseudoVADD_VV_MF2 $noreg, %108, %104, 4, 5 /* e32 */, 1 /* ta, mu */
    %110:vr = PseudoVSRL_VI_MF2 $noreg, %108, 8, 4, 5 /* e32 */, 1 /* ta, mu */
    %111:vr = PseudoVSLL_VI_MF2 $noreg, %108, 24, 4, 5 /* e32 */, 1 /* ta, mu */
    %112:vr = PseudoVOR_VV_MF2 $noreg, killed %111, killed %110, 4, 5 /* e32 */, 1 /* ta, mu */
    %113:vr = PseudoVXOR_VV_MF2 $noreg, %109, killed %112, 4, 5 /* e32 */, 1 /* ta, mu */
    %114:vr = PseudoVADD_VX_MF2 $noreg, %109, %8, 4, 5 /* e32 */, 1 /* ta, mu */
    %115:vr = PseudoVADD_VX_MF2 $noreg, killed %113, %14, 4, 5 /* e32 */, 1 /* ta, mu */
    %116:vr = PseudoVADD_VI_MF2 $noreg, killed %115, 4, 4, 5 /* e32 */, 1 /* ta, mu */
    %117:vr = PseudoVADD_VV_MF2 $noreg, killed %114, %116, 4, 5 /* e32 */, 1 /* ta, mu */
    %118:vr = PseudoVSRL_VI_MF2 $noreg, %116, 19, 4, 5 /* e32 */, 1 /* ta, mu */
    %119:vr = PseudoVSLL_VI_MF2 $noreg, %116, 13, 4, 5 /* e32 */, 1 /* ta, mu */
    %120:vr = PseudoVOR_VV_MF2 $noreg, killed %119, killed %118, 4, 5 /* e32 */, 1 /* ta, mu */
    %121:vr = PseudoVXOR_VV_MF2 $noreg, %117, killed %120, 4, 5 /* e32 */, 1 /* ta, mu */
    %122:vr = PseudoVADD_VV_MF2 $noreg, %121, %117, 4, 5 /* e32 */, 1 /* ta, mu */
    %123:vr = PseudoVSRL_VI_MF2 $noreg, %121, 17, 4, 5 /* e32 */, 1 /* ta, mu */
    %124:vr = PseudoVSLL_VI_MF2 $noreg, %121, 15, 4, 5 /* e32 */, 1 /* ta, mu */
    %125:vr = PseudoVOR_VV_MF2 $noreg, killed %124, killed %123, 4, 5 /* e32 */, 1 /* ta, mu */
    %126:vr = PseudoVXOR_VV_MF2 $noreg, %122, killed %125, 4, 5 /* e32 */, 1 /* ta, mu */
    %127:vr = PseudoVADD_VV_MF2 $noreg, %126, %122, 4, 5 /* e32 */, 1 /* ta, mu */
    %128:vr = PseudoVSRL_VI_MF2 $noreg, %126, 6, 4, 5 /* e32 */, 1 /* ta, mu */
    %129:vr = PseudoVSLL_VI_MF2 $noreg, %126, 26, 4, 5 /* e32 */, 1 /* ta, mu */
    %130:vr = PseudoVOR_VV_MF2 $noreg, killed %129, killed %128, 4, 5 /* e32 */, 1 /* ta, mu */
    %131:vr = PseudoVXOR_VV_MF2 $noreg, %127, killed %130, 4, 5 /* e32 */, 1 /* ta, mu */
    %132:vr = PseudoVADD_VV_MF2 $noreg, %131, %127, 4, 5 /* e32 */, 1 /* ta, mu */
    %133:vr = PseudoVSRL_VI_MF2 $noreg, %131, 26, 4, 5 /* e32 */, 1 /* ta, mu */
    %134:vr = PseudoVSLL_VI_MF2 $noreg, %131, 6, 4, 5 /* e32 */, 1 /* ta, mu */
    %135:vr = PseudoVOR_VV_MF2 $noreg, killed %134, killed %133, 4, 5 /* e32 */, 1 /* ta, mu */
    %136:vr = PseudoVXOR_VV_MF2 $noreg, %132, killed %135, 4, 5 /* e32 */, 1 /* ta, mu */
    %137:vr = PseudoVADD_VX_MF2 $noreg, %132, %14, 4, 5 /* e32 */, 1 /* ta, mu */
    %138:vr = PseudoVADD_VX_MF2 $noreg, killed %136, %9, 4, 5 /* e32 */, 1 /* ta, mu */
    %139:vr = PseudoVADD_VI_MF2 $noreg, killed %138, 5, 4, 5 /* e32 */, 1 /* ta, mu */
    PseudoVSE32_V_MF2 killed %137, killed %5, 4, 5 /* e32 */
    PseudoVSE32_V_MF2 killed %139, killed %7, 4, 5 /* e32 */
    %140:gpr = COPY $x0
    $x10 = COPY %140
    PseudoRET implicit $x10
...
