; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v,+zvfh,+zvfbfmin,+experimental-zvzip \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v,+zvfh,+zvfbfmin,+experimental-zvzip \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV64

define <vscale x 1 x i8> @test_vpairo_i8mf8(<vscale x 1 x i8> %passthru, <vscale x 1 x i8> %arg1, <vscale x 1 x i8> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i8mf8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i8> @llvm.riscv.vpairo(
    <vscale x 1 x i8> %passthru,
    <vscale x 1 x i8> %arg1,
    <vscale x 1 x i8> %arg2,
    iXLen %vl)
  ret <vscale x 1 x i8> %a
}

define <vscale x 1 x i8> @test_vpairo_mask_i8mf8(<vscale x 1 x i8> %passthru, <vscale x 1 x i8> %arg1, <vscale x 1 x i8> %arg2, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i8mf8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i8> @llvm.riscv.vpairo.mask(
    <vscale x 1 x i8> %passthru,
    <vscale x 1 x i8> %arg1,
    <vscale x 1 x i8> %arg2,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i8> %a
}

define <vscale x 2 x i8> @test_vpairo_i8mf4(<vscale x 2 x i8> %passthru, <vscale x 2 x i8> %arg1, <vscale x 2 x i8> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i8mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i8> @llvm.riscv.vpairo(
    <vscale x 2 x i8> %passthru,
    <vscale x 2 x i8> %arg1,
    <vscale x 2 x i8> %arg2,
    iXLen %vl)
  ret <vscale x 2 x i8> %a
}

define <vscale x 2 x i8> @test_vpairo_mask_i8mf4(<vscale x 2 x i8> %passthru, <vscale x 2 x i8> %arg1, <vscale x 2 x i8> %arg2, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i8mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i8> @llvm.riscv.vpairo.mask(
    <vscale x 2 x i8> %passthru,
    <vscale x 2 x i8> %arg1,
    <vscale x 2 x i8> %arg2,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i8> %a
}

define <vscale x 4 x i8> @test_vpairo_i8mf2(<vscale x 4 x i8> %passthru, <vscale x 4 x i8> %arg1, <vscale x 4 x i8> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i8mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i8> @llvm.riscv.vpairo(
    <vscale x 4 x i8> %passthru,
    <vscale x 4 x i8> %arg1,
    <vscale x 4 x i8> %arg2,
    iXLen %vl)
  ret <vscale x 4 x i8> %a
}

define <vscale x 4 x i8> @test_vpairo_mask_i8mf2(<vscale x 4 x i8> %passthru, <vscale x 4 x i8> %arg1, <vscale x 4 x i8> %arg2, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i8mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i8> @llvm.riscv.vpairo.mask(
    <vscale x 4 x i8> %passthru,
    <vscale x 4 x i8> %arg1,
    <vscale x 4 x i8> %arg2,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i8> %a
}

define <vscale x 8 x i8> @test_vpairo_i8m1(<vscale x 8 x i8> %passthru, <vscale x 8 x i8> %arg1, <vscale x 8 x i8> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i8m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i8> @llvm.riscv.vpairo(
    <vscale x 8 x i8> %passthru,
    <vscale x 8 x i8> %arg1,
    <vscale x 8 x i8> %arg2,
    iXLen %vl)
  ret <vscale x 8 x i8> %a
}

define <vscale x 8 x i8> @test_vpairo_mask_i8m1(<vscale x 8 x i8> %passthru, <vscale x 8 x i8> %arg1, <vscale x 8 x i8> %arg2, <vscale x 8 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i8m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i8> @llvm.riscv.vpairo.mask(
    <vscale x 8 x i8> %passthru,
    <vscale x 8 x i8> %arg1,
    <vscale x 8 x i8> %arg2,
    <vscale x 8 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x i8> %a
}

define <vscale x 16 x i8> @test_vpairo_i8m2(<vscale x 16 x i8> %passthru, <vscale x 16 x i8> %arg1, <vscale x 16 x i8> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i8m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i8> @llvm.riscv.vpairo(
    <vscale x 16 x i8> %passthru,
    <vscale x 16 x i8> %arg1,
    <vscale x 16 x i8> %arg2,
    iXLen %vl)
  ret <vscale x 16 x i8> %a
}

define <vscale x 16 x i8> @test_vpairo_mask_i8m2(<vscale x 16 x i8> %passthru, <vscale x 16 x i8> %arg1, <vscale x 16 x i8> %arg2, <vscale x 16 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i8m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i8> @llvm.riscv.vpairo.mask(
    <vscale x 16 x i8> %passthru,
    <vscale x 16 x i8> %arg1,
    <vscale x 16 x i8> %arg2,
    <vscale x 16 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 16 x i8> %a
}

define <vscale x 32 x i8> @test_vpairo_i8m4(<vscale x 32 x i8> %passthru, <vscale x 32 x i8> %arg1, <vscale x 32 x i8> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i8m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 32 x i8> @llvm.riscv.vpairo(
    <vscale x 32 x i8> %passthru,
    <vscale x 32 x i8> %arg1,
    <vscale x 32 x i8> %arg2,
    iXLen %vl)
  ret <vscale x 32 x i8> %a
}

define <vscale x 32 x i8> @test_vpairo_mask_i8m4(<vscale x 32 x i8> %passthru, <vscale x 32 x i8> %arg1, <vscale x 32 x i8> %arg2, <vscale x 32 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i8m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 32 x i8> @llvm.riscv.vpairo.mask(
    <vscale x 32 x i8> %passthru,
    <vscale x 32 x i8> %arg1,
    <vscale x 32 x i8> %arg2,
    <vscale x 32 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 32 x i8> %a
}

define <vscale x 64 x i8> @test_vpairo_i8m8(<vscale x 64 x i8> %passthru, <vscale x 64 x i8> %arg1, <vscale x 64 x i8> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i8m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8r.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %a = call <vscale x 64 x i8> @llvm.riscv.vpairo(
    <vscale x 64 x i8> %passthru,
    <vscale x 64 x i8> %arg1,
    <vscale x 64 x i8> %arg2,
    iXLen %vl)
  ret <vscale x 64 x i8> %a
}

define <vscale x 64 x i8> @test_vpairo_mask_i8m8(<vscale x 64 x i8> %passthru, <vscale x 64 x i8> %arg1, <vscale x 64 x i8> %arg2, <vscale x 64 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i8m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8r.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e8, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 64 x i8> @llvm.riscv.vpairo.mask(
    <vscale x 64 x i8> %passthru,
    <vscale x 64 x i8> %arg1,
    <vscale x 64 x i8> %arg2,
    <vscale x 64 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 64 x i8> %a
}

define <vscale x 1 x i16> @test_vpairo_i16mf4(<vscale x 1 x i16> %passthru, <vscale x 1 x i16> %arg1, <vscale x 1 x i16> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i16> @llvm.riscv.vpairo(
    <vscale x 1 x i16> %passthru,
    <vscale x 1 x i16> %arg1,
    <vscale x 1 x i16> %arg2,
    iXLen %vl)
  ret <vscale x 1 x i16> %a
}

define <vscale x 1 x i16> @test_vpairo_mask_i16mf4(<vscale x 1 x i16> %passthru, <vscale x 1 x i16> %arg1, <vscale x 1 x i16> %arg2, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i16> @llvm.riscv.vpairo.mask(
    <vscale x 1 x i16> %passthru,
    <vscale x 1 x i16> %arg1,
    <vscale x 1 x i16> %arg2,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i16> %a
}

define <vscale x 2 x i16> @test_vpairo_i16mf2(<vscale x 2 x i16> %passthru, <vscale x 2 x i16> %arg1, <vscale x 2 x i16> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i16> @llvm.riscv.vpairo(
    <vscale x 2 x i16> %passthru,
    <vscale x 2 x i16> %arg1,
    <vscale x 2 x i16> %arg2,
    iXLen %vl)
  ret <vscale x 2 x i16> %a
}

define <vscale x 2 x i16> @test_vpairo_mask_i16mf2(<vscale x 2 x i16> %passthru, <vscale x 2 x i16> %arg1, <vscale x 2 x i16> %arg2, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i16> @llvm.riscv.vpairo.mask(
    <vscale x 2 x i16> %passthru,
    <vscale x 2 x i16> %arg1,
    <vscale x 2 x i16> %arg2,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i16> %a
}

define <vscale x 4 x i16> @test_vpairo_i16m1(<vscale x 4 x i16> %passthru, <vscale x 4 x i16> %arg1, <vscale x 4 x i16> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i16> @llvm.riscv.vpairo(
    <vscale x 4 x i16> %passthru,
    <vscale x 4 x i16> %arg1,
    <vscale x 4 x i16> %arg2,
    iXLen %vl)
  ret <vscale x 4 x i16> %a
}

define <vscale x 4 x i16> @test_vpairo_mask_i16m1(<vscale x 4 x i16> %passthru, <vscale x 4 x i16> %arg1, <vscale x 4 x i16> %arg2, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i16> @llvm.riscv.vpairo.mask(
    <vscale x 4 x i16> %passthru,
    <vscale x 4 x i16> %arg1,
    <vscale x 4 x i16> %arg2,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i16> %a
}

define <vscale x 8 x i16> @test_vpairo_i16m2(<vscale x 8 x i16> %passthru, <vscale x 8 x i16> %arg1, <vscale x 8 x i16> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i16> @llvm.riscv.vpairo(
    <vscale x 8 x i16> %passthru,
    <vscale x 8 x i16> %arg1,
    <vscale x 8 x i16> %arg2,
    iXLen %vl)
  ret <vscale x 8 x i16> %a
}

define <vscale x 8 x i16> @test_vpairo_mask_i16m2(<vscale x 8 x i16> %passthru, <vscale x 8 x i16> %arg1, <vscale x 8 x i16> %arg2, <vscale x 8 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i16> @llvm.riscv.vpairo.mask(
    <vscale x 8 x i16> %passthru,
    <vscale x 8 x i16> %arg1,
    <vscale x 8 x i16> %arg2,
    <vscale x 8 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x i16> %a
}

define <vscale x 16 x i16> @test_vpairo_i16m4(<vscale x 16 x i16> %passthru, <vscale x 16 x i16> %arg1, <vscale x 16 x i16> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i16> @llvm.riscv.vpairo(
    <vscale x 16 x i16> %passthru,
    <vscale x 16 x i16> %arg1,
    <vscale x 16 x i16> %arg2,
    iXLen %vl)
  ret <vscale x 16 x i16> %a
}

define <vscale x 16 x i16> @test_vpairo_mask_i16m4(<vscale x 16 x i16> %passthru, <vscale x 16 x i16> %arg1, <vscale x 16 x i16> %arg2, <vscale x 16 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i16> @llvm.riscv.vpairo.mask(
    <vscale x 16 x i16> %passthru,
    <vscale x 16 x i16> %arg1,
    <vscale x 16 x i16> %arg2,
    <vscale x 16 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 16 x i16> %a
}

define <vscale x 32 x i16> @test_vpairo_i16m8(<vscale x 32 x i16> %passthru, <vscale x 32 x i16> %arg1, <vscale x 32 x i16> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i16m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re16.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %a = call <vscale x 32 x i16> @llvm.riscv.vpairo(
    <vscale x 32 x i16> %passthru,
    <vscale x 32 x i16> %arg1,
    <vscale x 32 x i16> %arg2,
    iXLen %vl)
  ret <vscale x 32 x i16> %a
}

define <vscale x 32 x i16> @test_vpairo_mask_i16m8(<vscale x 32 x i16> %passthru, <vscale x 32 x i16> %arg1, <vscale x 32 x i16> %arg2, <vscale x 32 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i16m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re16.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 32 x i16> @llvm.riscv.vpairo.mask(
    <vscale x 32 x i16> %passthru,
    <vscale x 32 x i16> %arg1,
    <vscale x 32 x i16> %arg2,
    <vscale x 32 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 32 x i16> %a
}

define <vscale x 1 x i32> @test_vpairo_i32mf2(<vscale x 1 x i32> %passthru, <vscale x 1 x i32> %arg1, <vscale x 1 x i32> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i32> @llvm.riscv.vpairo(
    <vscale x 1 x i32> %passthru,
    <vscale x 1 x i32> %arg1,
    <vscale x 1 x i32> %arg2,
    iXLen %vl)
  ret <vscale x 1 x i32> %a
}

define <vscale x 1 x i32> @test_vpairo_mask_i32mf2(<vscale x 1 x i32> %passthru, <vscale x 1 x i32> %arg1, <vscale x 1 x i32> %arg2, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i32> @llvm.riscv.vpairo.mask(
    <vscale x 1 x i32> %passthru,
    <vscale x 1 x i32> %arg1,
    <vscale x 1 x i32> %arg2,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i32> %a
}

define <vscale x 2 x i32> @test_vpairo_i32m1(<vscale x 2 x i32> %passthru, <vscale x 2 x i32> %arg1, <vscale x 2 x i32> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i32> @llvm.riscv.vpairo(
    <vscale x 2 x i32> %passthru,
    <vscale x 2 x i32> %arg1,
    <vscale x 2 x i32> %arg2,
    iXLen %vl)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @test_vpairo_mask_i32m1(<vscale x 2 x i32> %passthru, <vscale x 2 x i32> %arg1, <vscale x 2 x i32> %arg2, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i32> @llvm.riscv.vpairo.mask(
    <vscale x 2 x i32> %passthru,
    <vscale x 2 x i32> %arg1,
    <vscale x 2 x i32> %arg2,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i32> %a
}

define <vscale x 4 x i32> @test_vpairo_i32m2(<vscale x 4 x i32> %passthru, <vscale x 4 x i32> %arg1, <vscale x 4 x i32> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i32> @llvm.riscv.vpairo(
    <vscale x 4 x i32> %passthru,
    <vscale x 4 x i32> %arg1,
    <vscale x 4 x i32> %arg2,
    iXLen %vl)
  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @test_vpairo_mask_i32m2(<vscale x 4 x i32> %passthru, <vscale x 4 x i32> %arg1, <vscale x 4 x i32> %arg2, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i32> @llvm.riscv.vpairo.mask(
    <vscale x 4 x i32> %passthru,
    <vscale x 4 x i32> %arg1,
    <vscale x 4 x i32> %arg2,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i32> %a
}

define <vscale x 8 x i32> @test_vpairo_i32m4(<vscale x 8 x i32> %passthru, <vscale x 8 x i32> %arg1, <vscale x 8 x i32> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i32> @llvm.riscv.vpairo(
    <vscale x 8 x i32> %passthru,
    <vscale x 8 x i32> %arg1,
    <vscale x 8 x i32> %arg2,
    iXLen %vl)
  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @test_vpairo_mask_i32m4(<vscale x 8 x i32> %passthru, <vscale x 8 x i32> %arg1, <vscale x 8 x i32> %arg2, <vscale x 8 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i32> @llvm.riscv.vpairo.mask(
    <vscale x 8 x i32> %passthru,
    <vscale x 8 x i32> %arg1,
    <vscale x 8 x i32> %arg2,
    <vscale x 8 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x i32> %a
}

define <vscale x 16 x i32> @test_vpairo_i32m8(<vscale x 16 x i32> %passthru, <vscale x 16 x i32> %arg1, <vscale x 16 x i32> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i32m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re32.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e32, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i32> @llvm.riscv.vpairo(
    <vscale x 16 x i32> %passthru,
    <vscale x 16 x i32> %arg1,
    <vscale x 16 x i32> %arg2,
    iXLen %vl)
  ret <vscale x 16 x i32> %a
}

define <vscale x 16 x i32> @test_vpairo_mask_i32m8(<vscale x 16 x i32> %passthru, <vscale x 16 x i32> %arg1, <vscale x 16 x i32> %arg2, <vscale x 16 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i32m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re32.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e32, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i32> @llvm.riscv.vpairo.mask(
    <vscale x 16 x i32> %passthru,
    <vscale x 16 x i32> %arg1,
    <vscale x 16 x i32> %arg2,
    <vscale x 16 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 16 x i32> %a
}

define <vscale x 1 x i64> @test_vpairo_i64m1(<vscale x 1 x i64> %passthru, <vscale x 1 x i64> %arg1, <vscale x 1 x i64> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i64> @llvm.riscv.vpairo(
    <vscale x 1 x i64> %passthru,
    <vscale x 1 x i64> %arg1,
    <vscale x 1 x i64> %arg2,
    iXLen %vl)
  ret <vscale x 1 x i64> %a
}

define <vscale x 1 x i64> @test_vpairo_mask_i64m1(<vscale x 1 x i64> %passthru, <vscale x 1 x i64> %arg1, <vscale x 1 x i64> %arg2, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i64> @llvm.riscv.vpairo.mask(
    <vscale x 1 x i64> %passthru,
    <vscale x 1 x i64> %arg1,
    <vscale x 1 x i64> %arg2,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i64> %a
}

define <vscale x 2 x i64> @test_vpairo_i64m2(<vscale x 2 x i64> %passthru, <vscale x 2 x i64> %arg1, <vscale x 2 x i64> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.riscv.vpairo(
    <vscale x 2 x i64> %passthru,
    <vscale x 2 x i64> %arg1,
    <vscale x 2 x i64> %arg2,
    iXLen %vl)
  ret <vscale x 2 x i64> %a
}

define <vscale x 2 x i64> @test_vpairo_mask_i64m2(<vscale x 2 x i64> %passthru, <vscale x 2 x i64> %arg1, <vscale x 2 x i64> %arg2, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.riscv.vpairo.mask(
    <vscale x 2 x i64> %passthru,
    <vscale x 2 x i64> %arg1,
    <vscale x 2 x i64> %arg2,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i64> %a
}

define <vscale x 4 x i64> @test_vpairo_i64m4(<vscale x 4 x i64> %passthru, <vscale x 4 x i64> %arg1, <vscale x 4 x i64> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i64> @llvm.riscv.vpairo(
    <vscale x 4 x i64> %passthru,
    <vscale x 4 x i64> %arg1,
    <vscale x 4 x i64> %arg2,
    iXLen %vl)
  ret <vscale x 4 x i64> %a
}

define <vscale x 4 x i64> @test_vpairo_mask_i64m4(<vscale x 4 x i64> %passthru, <vscale x 4 x i64> %arg1, <vscale x 4 x i64> %arg2, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i64> @llvm.riscv.vpairo.mask(
    <vscale x 4 x i64> %passthru,
    <vscale x 4 x i64> %arg1,
    <vscale x 4 x i64> %arg2,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i64> %a
}

define <vscale x 8 x i64> @test_vpairo_i64m8(<vscale x 8 x i64> %passthru, <vscale x 8 x i64> %arg1, <vscale x 8 x i64> %arg2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_i64m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re64.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i64> @llvm.riscv.vpairo(
    <vscale x 8 x i64> %passthru,
    <vscale x 8 x i64> %arg1,
    <vscale x 8 x i64> %arg2,
    iXLen %vl)
  ret <vscale x 8 x i64> %a
}

define <vscale x 8 x i64> @test_vpairo_mask_i64m8(<vscale x 8 x i64> %passthru, <vscale x 8 x i64> %arg1, <vscale x 8 x i64> %arg2, <vscale x 8 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_i64m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re64.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i64> @llvm.riscv.vpairo.mask(
    <vscale x 8 x i64> %passthru,
    <vscale x 8 x i64> %arg1,
    <vscale x 8 x i64> %arg2,
    <vscale x 8 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x i64> %a
}

; Floating-point types

; f16
define <vscale x 1 x half> @test_vpairo_f16mf4(<vscale x 1 x half> %passthru, <vscale x 1 x half> %a1, <vscale x 1 x half> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x half> @llvm.riscv.vpairo(
    <vscale x 1 x half> %passthru,
    <vscale x 1 x half> %a1,
    <vscale x 1 x half> %a2,
    iXLen %vl)
  ret <vscale x 1 x half> %r
}

define <vscale x 1 x half> @test_vpairo_mask_f16mf4(<vscale x 1 x half> %passthru, <vscale x 1 x half> %a1, <vscale x 1 x half> %a2, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x half> @llvm.riscv.vpairo.mask(
    <vscale x 1 x half> %passthru,
    <vscale x 1 x half> %a1,
    <vscale x 1 x half> %a2,
    <vscale x 1 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 1 x half> %r
}

define <vscale x 2 x half> @test_vpairo_f16mf2(<vscale x 2 x half> %passthru, <vscale x 2 x half> %a1, <vscale x 2 x half> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x half> @llvm.riscv.vpairo(
    <vscale x 2 x half> %passthru,
    <vscale x 2 x half> %a1,
    <vscale x 2 x half> %a2,
    iXLen %vl)
  ret <vscale x 2 x half> %r
}

define <vscale x 2 x half> @test_vpairo_mask_f16mf2(<vscale x 2 x half> %passthru, <vscale x 2 x half> %a1, <vscale x 2 x half> %a2, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x half> @llvm.riscv.vpairo.mask(
    <vscale x 2 x half> %passthru,
    <vscale x 2 x half> %a1,
    <vscale x 2 x half> %a2,
    <vscale x 2 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 2 x half> %r
}

define <vscale x 4 x half> @test_vpairo_f16m1(<vscale x 4 x half> %passthru, <vscale x 4 x half> %a1, <vscale x 4 x half> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x half> @llvm.riscv.vpairo(
    <vscale x 4 x half> %passthru,
    <vscale x 4 x half> %a1,
    <vscale x 4 x half> %a2,
    iXLen %vl)
  ret <vscale x 4 x half> %r
}

define <vscale x 4 x half> @test_vpairo_mask_f16m1(<vscale x 4 x half> %passthru, <vscale x 4 x half> %a1, <vscale x 4 x half> %a2, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x half> @llvm.riscv.vpairo.mask(
    <vscale x 4 x half> %passthru,
    <vscale x 4 x half> %a1,
    <vscale x 4 x half> %a2,
    <vscale x 4 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 4 x half> %r
}

define <vscale x 8 x half> @test_vpairo_f16m2(<vscale x 8 x half> %passthru, <vscale x 8 x half> %a1, <vscale x 8 x half> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x half> @llvm.riscv.vpairo(
    <vscale x 8 x half> %passthru,
    <vscale x 8 x half> %a1,
    <vscale x 8 x half> %a2,
    iXLen %vl)
  ret <vscale x 8 x half> %r
}

define <vscale x 8 x half> @test_vpairo_mask_f16m2(<vscale x 8 x half> %passthru, <vscale x 8 x half> %a1, <vscale x 8 x half> %a2, <vscale x 8 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x half> @llvm.riscv.vpairo.mask(
    <vscale x 8 x half> %passthru,
    <vscale x 8 x half> %a1,
    <vscale x 8 x half> %a2,
    <vscale x 8 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 8 x half> %r
}

define <vscale x 16 x half> @test_vpairo_f16m4(<vscale x 16 x half> %passthru, <vscale x 16 x half> %a1, <vscale x 16 x half> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x half> @llvm.riscv.vpairo(
    <vscale x 16 x half> %passthru,
    <vscale x 16 x half> %a1,
    <vscale x 16 x half> %a2,
    iXLen %vl)
  ret <vscale x 16 x half> %r
}

define <vscale x 16 x half> @test_vpairo_mask_f16m4(<vscale x 16 x half> %passthru, <vscale x 16 x half> %a1, <vscale x 16 x half> %a2, <vscale x 16 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x half> @llvm.riscv.vpairo.mask(
    <vscale x 16 x half> %passthru,
    <vscale x 16 x half> %a1,
    <vscale x 16 x half> %a2,
    <vscale x 16 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 16 x half> %r
}

define <vscale x 32 x half> @test_vpairo_f16m8(<vscale x 32 x half> %passthru, <vscale x 32 x half> %a1, <vscale x 32 x half> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f16m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re16.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %r = call <vscale x 32 x half> @llvm.riscv.vpairo(
    <vscale x 32 x half> %passthru,
    <vscale x 32 x half> %a1,
    <vscale x 32 x half> %a2,
    iXLen %vl)
  ret <vscale x 32 x half> %r
}

define <vscale x 32 x half> @test_vpairo_mask_f16m8(<vscale x 32 x half> %passthru, <vscale x 32 x half> %a1, <vscale x 32 x half> %a2, <vscale x 32 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f16m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re16.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 32 x half> @llvm.riscv.vpairo.mask(
    <vscale x 32 x half> %passthru,
    <vscale x 32 x half> %a1,
    <vscale x 32 x half> %a2,
    <vscale x 32 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 32 x half> %r
}

; bf16
define <vscale x 1 x bfloat> @test_vpairo_bf16mf4(<vscale x 1 x bfloat> %passthru, <vscale x 1 x bfloat> %a1, <vscale x 1 x bfloat> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_bf16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x bfloat> @llvm.riscv.vpairo(
    <vscale x 1 x bfloat> %passthru,
    <vscale x 1 x bfloat> %a1,
    <vscale x 1 x bfloat> %a2,
    iXLen %vl)
  ret <vscale x 1 x bfloat> %r
}

define <vscale x 1 x bfloat> @test_vpairo_mask_bf16mf4(<vscale x 1 x bfloat> %passthru, <vscale x 1 x bfloat> %a1, <vscale x 1 x bfloat> %a2, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_bf16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x bfloat> @llvm.riscv.vpairo.mask(
    <vscale x 1 x bfloat> %passthru,
    <vscale x 1 x bfloat> %a1,
    <vscale x 1 x bfloat> %a2,
    <vscale x 1 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 1 x bfloat> %r
}

define <vscale x 2 x bfloat> @test_vpairo_bf16mf2(<vscale x 2 x bfloat> %passthru, <vscale x 2 x bfloat> %a1, <vscale x 2 x bfloat> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_bf16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x bfloat> @llvm.riscv.vpairo(
    <vscale x 2 x bfloat> %passthru,
    <vscale x 2 x bfloat> %a1,
    <vscale x 2 x bfloat> %a2,
    iXLen %vl)
  ret <vscale x 2 x bfloat> %r
}

define <vscale x 2 x bfloat> @test_vpairo_mask_bf16mf2(<vscale x 2 x bfloat> %passthru, <vscale x 2 x bfloat> %a1, <vscale x 2 x bfloat> %a2, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_bf16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x bfloat> @llvm.riscv.vpairo.mask(
    <vscale x 2 x bfloat> %passthru,
    <vscale x 2 x bfloat> %a1,
    <vscale x 2 x bfloat> %a2,
    <vscale x 2 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 2 x bfloat> %r
}

define <vscale x 4 x bfloat> @test_vpairo_bf16m1(<vscale x 4 x bfloat> %passthru, <vscale x 4 x bfloat> %a1, <vscale x 4 x bfloat> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_bf16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vpairo(
    <vscale x 4 x bfloat> %passthru,
    <vscale x 4 x bfloat> %a1,
    <vscale x 4 x bfloat> %a2,
    iXLen %vl)
  ret <vscale x 4 x bfloat> %r
}

define <vscale x 4 x bfloat> @test_vpairo_mask_bf16m1(<vscale x 4 x bfloat> %passthru, <vscale x 4 x bfloat> %a1, <vscale x 4 x bfloat> %a2, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_bf16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vpairo.mask(
    <vscale x 4 x bfloat> %passthru,
    <vscale x 4 x bfloat> %a1,
    <vscale x 4 x bfloat> %a2,
    <vscale x 4 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 4 x bfloat> %r
}

define <vscale x 8 x bfloat> @test_vpairo_bf16m2(<vscale x 8 x bfloat> %passthru, <vscale x 8 x bfloat> %a1, <vscale x 8 x bfloat> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_bf16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x bfloat> @llvm.riscv.vpairo(
    <vscale x 8 x bfloat> %passthru,
    <vscale x 8 x bfloat> %a1,
    <vscale x 8 x bfloat> %a2,
    iXLen %vl)
  ret <vscale x 8 x bfloat> %r
}

define <vscale x 8 x bfloat> @test_vpairo_mask_bf16m2(<vscale x 8 x bfloat> %passthru, <vscale x 8 x bfloat> %a1, <vscale x 8 x bfloat> %a2, <vscale x 8 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_bf16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x bfloat> @llvm.riscv.vpairo.mask(
    <vscale x 8 x bfloat> %passthru,
    <vscale x 8 x bfloat> %a1,
    <vscale x 8 x bfloat> %a2,
    <vscale x 8 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 8 x bfloat> %r
}

define <vscale x 16 x bfloat> @test_vpairo_bf16m4(<vscale x 16 x bfloat> %passthru, <vscale x 16 x bfloat> %a1, <vscale x 16 x bfloat> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_bf16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x bfloat> @llvm.riscv.vpairo(
    <vscale x 16 x bfloat> %passthru,
    <vscale x 16 x bfloat> %a1,
    <vscale x 16 x bfloat> %a2,
    iXLen %vl)
  ret <vscale x 16 x bfloat> %r
}

define <vscale x 16 x bfloat> @test_vpairo_mask_bf16m4(<vscale x 16 x bfloat> %passthru, <vscale x 16 x bfloat> %a1, <vscale x 16 x bfloat> %a2, <vscale x 16 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_bf16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x bfloat> @llvm.riscv.vpairo.mask(
    <vscale x 16 x bfloat> %passthru,
    <vscale x 16 x bfloat> %a1,
    <vscale x 16 x bfloat> %a2,
    <vscale x 16 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 16 x bfloat> %r
}

define <vscale x 32 x bfloat> @test_vpairo_bf16m8(<vscale x 32 x bfloat> %passthru, <vscale x 32 x bfloat> %a1, <vscale x 32 x bfloat> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_bf16m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re16.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %r = call <vscale x 32 x bfloat> @llvm.riscv.vpairo(
    <vscale x 32 x bfloat> %passthru,
    <vscale x 32 x bfloat> %a1,
    <vscale x 32 x bfloat> %a2,
    iXLen %vl)
  ret <vscale x 32 x bfloat> %r
}

define <vscale x 32 x bfloat> @test_vpairo_mask_bf16m8(<vscale x 32 x bfloat> %passthru, <vscale x 32 x bfloat> %a1, <vscale x 32 x bfloat> %a2, <vscale x 32 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_bf16m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re16.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e16, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 32 x bfloat> @llvm.riscv.vpairo.mask(
    <vscale x 32 x bfloat> %passthru,
    <vscale x 32 x bfloat> %a1,
    <vscale x 32 x bfloat> %a2,
    <vscale x 32 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 32 x bfloat> %r
}

; f32
define <vscale x 1 x float> @test_vpairo_f32mf2(<vscale x 1 x float> %passthru, <vscale x 1 x float> %a1, <vscale x 1 x float> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x float> @llvm.riscv.vpairo(
    <vscale x 1 x float> %passthru,
    <vscale x 1 x float> %a1,
    <vscale x 1 x float> %a2,
    iXLen %vl)
  ret <vscale x 1 x float> %r
}

define <vscale x 1 x float> @test_vpairo_mask_f32mf2(<vscale x 1 x float> %passthru, <vscale x 1 x float> %a1, <vscale x 1 x float> %a2, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x float> @llvm.riscv.vpairo.mask(
    <vscale x 1 x float> %passthru,
    <vscale x 1 x float> %a1,
    <vscale x 1 x float> %a2,
    <vscale x 1 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 1 x float> %r
}

define <vscale x 2 x float> @test_vpairo_f32m1(<vscale x 2 x float> %passthru, <vscale x 2 x float> %a1, <vscale x 2 x float> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x float> @llvm.riscv.vpairo(
    <vscale x 2 x float> %passthru,
    <vscale x 2 x float> %a1,
    <vscale x 2 x float> %a2,
    iXLen %vl)
  ret <vscale x 2 x float> %r
}

define <vscale x 2 x float> @test_vpairo_mask_f32m1(<vscale x 2 x float> %passthru, <vscale x 2 x float> %a1, <vscale x 2 x float> %a2, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x float> @llvm.riscv.vpairo.mask(
    <vscale x 2 x float> %passthru,
    <vscale x 2 x float> %a1,
    <vscale x 2 x float> %a2,
    <vscale x 2 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 2 x float> %r
}

define <vscale x 4 x float> @test_vpairo_f32m2(<vscale x 4 x float> %passthru, <vscale x 4 x float> %a1, <vscale x 4 x float> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x float> @llvm.riscv.vpairo(
    <vscale x 4 x float> %passthru,
    <vscale x 4 x float> %a1,
    <vscale x 4 x float> %a2,
    iXLen %vl)
  ret <vscale x 4 x float> %r
}

define <vscale x 4 x float> @test_vpairo_mask_f32m2(<vscale x 4 x float> %passthru, <vscale x 4 x float> %a1, <vscale x 4 x float> %a2, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x float> @llvm.riscv.vpairo.mask(
    <vscale x 4 x float> %passthru,
    <vscale x 4 x float> %a1,
    <vscale x 4 x float> %a2,
    <vscale x 4 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 4 x float> %r
}

define <vscale x 8 x float> @test_vpairo_f32m4(<vscale x 8 x float> %passthru, <vscale x 8 x float> %a1, <vscale x 8 x float> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x float> @llvm.riscv.vpairo(
    <vscale x 8 x float> %passthru,
    <vscale x 8 x float> %a1,
    <vscale x 8 x float> %a2,
    iXLen %vl)
  ret <vscale x 8 x float> %r
}

define <vscale x 8 x float> @test_vpairo_mask_f32m4(<vscale x 8 x float> %passthru, <vscale x 8 x float> %a1, <vscale x 8 x float> %a2, <vscale x 8 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x float> @llvm.riscv.vpairo.mask(
    <vscale x 8 x float> %passthru,
    <vscale x 8 x float> %a1,
    <vscale x 8 x float> %a2,
    <vscale x 8 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 8 x float> %r
}

define <vscale x 16 x float> @test_vpairo_f32m8(<vscale x 16 x float> %passthru, <vscale x 16 x float> %a1, <vscale x 16 x float> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f32m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re32.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e32, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x float> @llvm.riscv.vpairo(
    <vscale x 16 x float> %passthru,
    <vscale x 16 x float> %a1,
    <vscale x 16 x float> %a2,
    iXLen %vl)
  ret <vscale x 16 x float> %r
}

define <vscale x 16 x float> @test_vpairo_mask_f32m8(<vscale x 16 x float> %passthru, <vscale x 16 x float> %a1, <vscale x 16 x float> %a2, <vscale x 16 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f32m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re32.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e32, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x float> @llvm.riscv.vpairo.mask(
    <vscale x 16 x float> %passthru,
    <vscale x 16 x float> %a1,
    <vscale x 16 x float> %a2,
    <vscale x 16 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 16 x float> %r
}

; f64
define <vscale x 1 x double> @test_vpairo_f64m1(<vscale x 1 x double> %passthru, <vscale x 1 x double> %a1, <vscale x 1 x double> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v9, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x double> @llvm.riscv.vpairo(
    <vscale x 1 x double> %passthru,
    <vscale x 1 x double> %a1,
    <vscale x 1 x double> %a2,
    iXLen %vl)
  ret <vscale x 1 x double> %r
}

define <vscale x 1 x double> @test_vpairo_mask_f64m1(<vscale x 1 x double> %passthru, <vscale x 1 x double> %a1, <vscale x 1 x double> %a2, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v9, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x double> @llvm.riscv.vpairo.mask(
    <vscale x 1 x double> %passthru,
    <vscale x 1 x double> %a1,
    <vscale x 1 x double> %a2,
    <vscale x 1 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 1 x double> %r
}

define <vscale x 2 x double> @test_vpairo_f64m2(<vscale x 2 x double> %passthru, <vscale x 2 x double> %a1, <vscale x 2 x double> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v10, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x double> @llvm.riscv.vpairo(
    <vscale x 2 x double> %passthru,
    <vscale x 2 x double> %a1,
    <vscale x 2 x double> %a2,
    iXLen %vl)
  ret <vscale x 2 x double> %r
}

define <vscale x 2 x double> @test_vpairo_mask_f64m2(<vscale x 2 x double> %passthru, <vscale x 2 x double> %a1, <vscale x 2 x double> %a2, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v10, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x double> @llvm.riscv.vpairo.mask(
    <vscale x 2 x double> %passthru,
    <vscale x 2 x double> %a1,
    <vscale x 2 x double> %a2,
    <vscale x 2 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 2 x double> %r
}

define <vscale x 4 x double> @test_vpairo_f64m4(<vscale x 4 x double> %passthru, <vscale x 4 x double> %a1, <vscale x 4 x double> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v12, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x double> @llvm.riscv.vpairo(
    <vscale x 4 x double> %passthru,
    <vscale x 4 x double> %a1,
    <vscale x 4 x double> %a2,
    iXLen %vl)
  ret <vscale x 4 x double> %r
}

define <vscale x 4 x double> @test_vpairo_mask_f64m4(<vscale x 4 x double> %passthru, <vscale x 4 x double> %a1, <vscale x 4 x double> %a2, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v12, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x double> @llvm.riscv.vpairo.mask(
    <vscale x 4 x double> %passthru,
    <vscale x 4 x double> %a1,
    <vscale x 4 x double> %a2,
    <vscale x 4 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 4 x double> %r
}

define <vscale x 8 x double> @test_vpairo_f64m8(<vscale x 8 x double> %passthru, <vscale x 8 x double> %a1, <vscale x 8 x double> %a2, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_f64m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re64.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, tu, ma
; CHECK-NEXT:    vpairo.vv v8, v16, v24
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x double> @llvm.riscv.vpairo(
    <vscale x 8 x double> %passthru,
    <vscale x 8 x double> %a1,
    <vscale x 8 x double> %a2,
    iXLen %vl)
  ret <vscale x 8 x double> %r
}

define <vscale x 8 x double> @test_vpairo_mask_f64m8(<vscale x 8 x double> %passthru, <vscale x 8 x double> %a1, <vscale x 8 x double> %a2, <vscale x 8 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vpairo_mask_f64m8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vl8re64.v v24, (a0)
; CHECK-NEXT:    vsetvli zero, a1, e64, m8, ta, mu
; CHECK-NEXT:    vpairo.vv v8, v16, v24, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x double> @llvm.riscv.vpairo.mask(
    <vscale x 8 x double> %passthru,
    <vscale x 8 x double> %a1,
    <vscale x 8 x double> %a2,
    <vscale x 8 x i1> %m,
    iXLen %vl,
    iXLen 1)
  ret <vscale x 8 x double> %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32: {{.*}}
; RV64: {{.*}}
