; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i32/g' %s | llc -mtriple=riscv32 -mattr=+v,+zvfh,+zvfbfmin,+experimental-zvzip \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV32
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+v,+zvfh,+zvfbfmin,+experimental-zvzip \
; RUN:   -verify-machineinstrs | FileCheck %s --check-prefixes=CHECK,RV64

define <vscale x 1 x i8> @test_vunzipe_i8mf8(<vscale x 1 x i8> %passthru, <vscale x 2 x i8> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i8mf8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i8> @llvm.riscv.vunzipe(
    <vscale x 1 x i8> %passthru,
    <vscale x 2 x i8> %arg1,
    iXLen %vl)
  ret <vscale x 1 x i8> %a
}

define <vscale x 1 x i8> @test_vunzipe_mask_i8mf8(<vscale x 1 x i8> %passthru, <vscale x 2 x i8> %arg1, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i8mf8:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf8, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i8> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x i8> %passthru,
    <vscale x 2 x i8> %arg1,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i8> %a
}

define <vscale x 2 x i8> @test_vunzipe_i8mf4(<vscale x 2 x i8> %passthru, <vscale x 4 x i8> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i8mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i8> @llvm.riscv.vunzipe(
    <vscale x 2 x i8> %passthru,
    <vscale x 4 x i8> %arg1,
    iXLen %vl)
  ret <vscale x 2 x i8> %a
}

define <vscale x 2 x i8> @test_vunzipe_mask_i8mf4(<vscale x 2 x i8> %passthru, <vscale x 4 x i8> %arg1, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i8mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i8> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x i8> %passthru,
    <vscale x 4 x i8> %arg1,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i8> %a
}

define <vscale x 4 x i8> @test_vunzipe_i8mf2(<vscale x 4 x i8> %passthru, <vscale x 8 x i8> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i8mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i8> @llvm.riscv.vunzipe(
    <vscale x 4 x i8> %passthru,
    <vscale x 8 x i8> %arg1,
    iXLen %vl)
  ret <vscale x 4 x i8> %a
}

define <vscale x 4 x i8> @test_vunzipe_mask_i8mf2(<vscale x 4 x i8> %passthru, <vscale x 8 x i8> %arg1, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i8mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, mf2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i8> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x i8> %passthru,
    <vscale x 8 x i8> %arg1,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i8> %a
}

define <vscale x 8 x i8> @test_vunzipe_i8m1(<vscale x 8 x i8> %passthru, <vscale x 16 x i8> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i8m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i8> @llvm.riscv.vunzipe(
    <vscale x 8 x i8> %passthru,
    <vscale x 16 x i8> %arg1,
    iXLen %vl)
  ret <vscale x 8 x i8> %a
}

define <vscale x 8 x i8> @test_vunzipe_mask_i8m1(<vscale x 8 x i8> %passthru, <vscale x 16 x i8> %arg1, <vscale x 8 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i8m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i8> @llvm.riscv.vunzipe.mask(
    <vscale x 8 x i8> %passthru,
    <vscale x 16 x i8> %arg1,
    <vscale x 8 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x i8> %a
}

define <vscale x 16 x i8> @test_vunzipe_i8m2(<vscale x 16 x i8> %passthru, <vscale x 32 x i8> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i8m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i8> @llvm.riscv.vunzipe(
    <vscale x 16 x i8> %passthru,
    <vscale x 32 x i8> %arg1,
    iXLen %vl)
  ret <vscale x 16 x i8> %a
}

define <vscale x 16 x i8> @test_vunzipe_mask_i8m2(<vscale x 16 x i8> %passthru, <vscale x 32 x i8> %arg1, <vscale x 16 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i8m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i8> @llvm.riscv.vunzipe.mask(
    <vscale x 16 x i8> %passthru,
    <vscale x 32 x i8> %arg1,
    <vscale x 16 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 16 x i8> %a
}

define <vscale x 32 x i8> @test_vunzipe_i8m4(<vscale x 32 x i8> %passthru, <vscale x 64 x i8> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i8m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 32 x i8> @llvm.riscv.vunzipe(
    <vscale x 32 x i8> %passthru,
    <vscale x 64 x i8> %arg1,
    iXLen %vl)
  ret <vscale x 32 x i8> %a
}

define <vscale x 32 x i8> @test_vunzipe_mask_i8m4(<vscale x 32 x i8> %passthru, <vscale x 64 x i8> %arg1, <vscale x 32 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i8m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e8, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 32 x i8> @llvm.riscv.vunzipe.mask(
    <vscale x 32 x i8> %passthru,
    <vscale x 64 x i8> %arg1,
    <vscale x 32 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 32 x i8> %a
}

define <vscale x 1 x i16> @test_vunzipe_i16mf4(<vscale x 1 x i16> %passthru, <vscale x 2 x i16> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i16> @llvm.riscv.vunzipe(
    <vscale x 1 x i16> %passthru,
    <vscale x 2 x i16> %arg1,
    iXLen %vl)
  ret <vscale x 1 x i16> %a
}

define <vscale x 1 x i16> @test_vunzipe_mask_i16mf4(<vscale x 1 x i16> %passthru, <vscale x 2 x i16> %arg1, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i16> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x i16> %passthru,
    <vscale x 2 x i16> %arg1,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i16> %a
}

define <vscale x 2 x i16> @test_vunzipe_i16mf2(<vscale x 2 x i16> %passthru, <vscale x 4 x i16> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i16> @llvm.riscv.vunzipe(
    <vscale x 2 x i16> %passthru,
    <vscale x 4 x i16> %arg1,
    iXLen %vl)
  ret <vscale x 2 x i16> %a
}

define <vscale x 2 x i16> @test_vunzipe_mask_i16mf2(<vscale x 2 x i16> %passthru, <vscale x 4 x i16> %arg1, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i16> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x i16> %passthru,
    <vscale x 4 x i16> %arg1,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i16> %a
}

define <vscale x 4 x i16> @test_vunzipe_i16m1(<vscale x 4 x i16> %passthru, <vscale x 8 x i16> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i16> @llvm.riscv.vunzipe(
    <vscale x 4 x i16> %passthru,
    <vscale x 8 x i16> %arg1,
    iXLen %vl)
  ret <vscale x 4 x i16> %a
}

define <vscale x 4 x i16> @test_vunzipe_mask_i16m1(<vscale x 4 x i16> %passthru, <vscale x 8 x i16> %arg1, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i16> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x i16> %passthru,
    <vscale x 8 x i16> %arg1,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i16> %a
}

define <vscale x 8 x i16> @test_vunzipe_i16m2(<vscale x 8 x i16> %passthru, <vscale x 16 x i16> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i16> @llvm.riscv.vunzipe(
    <vscale x 8 x i16> %passthru,
    <vscale x 16 x i16> %arg1,
    iXLen %vl)
  ret <vscale x 8 x i16> %a
}

define <vscale x 8 x i16> @test_vunzipe_mask_i16m2(<vscale x 8 x i16> %passthru, <vscale x 16 x i16> %arg1, <vscale x 8 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i16> @llvm.riscv.vunzipe.mask(
    <vscale x 8 x i16> %passthru,
    <vscale x 16 x i16> %arg1,
    <vscale x 8 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x i16> %a
}

define <vscale x 16 x i16> @test_vunzipe_i16m4(<vscale x 16 x i16> %passthru, <vscale x 32 x i16> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i16> @llvm.riscv.vunzipe(
    <vscale x 16 x i16> %passthru,
    <vscale x 32 x i16> %arg1,
    iXLen %vl)
  ret <vscale x 16 x i16> %a
}

define <vscale x 16 x i16> @test_vunzipe_mask_i16m4(<vscale x 16 x i16> %passthru, <vscale x 32 x i16> %arg1, <vscale x 16 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 16 x i16> @llvm.riscv.vunzipe.mask(
    <vscale x 16 x i16> %passthru,
    <vscale x 32 x i16> %arg1,
    <vscale x 16 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 16 x i16> %a
}

define <vscale x 1 x i32> @test_vunzipe_i32mf2(<vscale x 1 x i32> %passthru, <vscale x 2 x i32> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i32> @llvm.riscv.vunzipe(
    <vscale x 1 x i32> %passthru,
    <vscale x 2 x i32> %arg1,
    iXLen %vl)
  ret <vscale x 1 x i32> %a
}

define <vscale x 1 x i32> @test_vunzipe_mask_i32mf2(<vscale x 1 x i32> %passthru, <vscale x 2 x i32> %arg1, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i32> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x i32> %passthru,
    <vscale x 2 x i32> %arg1,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i32> %a
}

define <vscale x 2 x i32> @test_vunzipe_i32m1(<vscale x 2 x i32> %passthru, <vscale x 4 x i32> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i32> @llvm.riscv.vunzipe(
    <vscale x 2 x i32> %passthru,
    <vscale x 4 x i32> %arg1,
    iXLen %vl)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @test_vunzipe_mask_i32m1(<vscale x 2 x i32> %passthru, <vscale x 4 x i32> %arg1, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i32> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x i32> %passthru,
    <vscale x 4 x i32> %arg1,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i32> %a
}

define <vscale x 4 x i32> @test_vunzipe_i32m2(<vscale x 4 x i32> %passthru, <vscale x 8 x i32> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i32> @llvm.riscv.vunzipe(
    <vscale x 4 x i32> %passthru,
    <vscale x 8 x i32> %arg1,
    iXLen %vl)
  ret <vscale x 4 x i32> %a
}

define <vscale x 4 x i32> @test_vunzipe_mask_i32m2(<vscale x 4 x i32> %passthru, <vscale x 8 x i32> %arg1, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i32> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x i32> %passthru,
    <vscale x 8 x i32> %arg1,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i32> %a
}

define <vscale x 8 x i32> @test_vunzipe_i32m4(<vscale x 8 x i32> %passthru, <vscale x 16 x i32> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i32> @llvm.riscv.vunzipe(
    <vscale x 8 x i32> %passthru,
    <vscale x 16 x i32> %arg1,
    iXLen %vl)
  ret <vscale x 8 x i32> %a
}

define <vscale x 8 x i32> @test_vunzipe_mask_i32m4(<vscale x 8 x i32> %passthru, <vscale x 16 x i32> %arg1, <vscale x 8 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 8 x i32> @llvm.riscv.vunzipe.mask(
    <vscale x 8 x i32> %passthru,
    <vscale x 16 x i32> %arg1,
    <vscale x 8 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x i32> %a
}

define <vscale x 1 x i64> @test_vunzipe_i64m1(<vscale x 1 x i64> %passthru, <vscale x 2 x i64> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i64> @llvm.riscv.vunzipe(
    <vscale x 1 x i64> %passthru,
    <vscale x 2 x i64> %arg1,
    iXLen %vl)
  ret <vscale x 1 x i64> %a
}

define <vscale x 1 x i64> @test_vunzipe_mask_i64m1(<vscale x 1 x i64> %passthru, <vscale x 2 x i64> %arg1, <vscale x 1 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 1 x i64> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x i64> %passthru,
    <vscale x 2 x i64> %arg1,
    <vscale x 1 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x i64> %a
}

define <vscale x 2 x i64> @test_vunzipe_i64m2(<vscale x 2 x i64> %passthru, <vscale x 4 x i64> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.riscv.vunzipe(
    <vscale x 2 x i64> %passthru,
    <vscale x 4 x i64> %arg1,
    iXLen %vl)
  ret <vscale x 2 x i64> %a
}

define <vscale x 2 x i64> @test_vunzipe_mask_i64m2(<vscale x 2 x i64> %passthru, <vscale x 4 x i64> %arg1, <vscale x 2 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 2 x i64> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x i64> %passthru,
    <vscale x 4 x i64> %arg1,
    <vscale x 2 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x i64> %a
}

define <vscale x 4 x i64> @test_vunzipe_i64m4(<vscale x 4 x i64> %passthru, <vscale x 8 x i64> %arg1, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_i64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i64> @llvm.riscv.vunzipe(
    <vscale x 4 x i64> %passthru,
    <vscale x 8 x i64> %arg1,
    iXLen %vl)
  ret <vscale x 4 x i64> %a
}

define <vscale x 4 x i64> @test_vunzipe_mask_i64m4(<vscale x 4 x i64> %passthru, <vscale x 8 x i64> %arg1, <vscale x 4 x i1> %mask, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_i64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %a = call <vscale x 4 x i64> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x i64> %passthru,
    <vscale x 8 x i64> %arg1,
    <vscale x 4 x i1> %mask,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x i64> %a
}

; Floating-point types

; f16
define <vscale x 1 x half> @test_vunzipe_f16mf4(<vscale x 1 x half> %passthru, <vscale x 2 x half> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x half> @llvm.riscv.vunzipe(
    <vscale x 1 x half> %passthru,
    <vscale x 2 x half> %src,
    iXLen %vl)
  ret <vscale x 1 x half> %r
}

define <vscale x 1 x half> @test_vunzipe_mask_f16mf4(<vscale x 1 x half> %passthru, <vscale x 2 x half> %src, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x half> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x half> %passthru,
    <vscale x 2 x half> %src,
    <vscale x 1 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x half> %r
}

define <vscale x 2 x half> @test_vunzipe_f16mf2(<vscale x 2 x half> %passthru, <vscale x 4 x half> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x half> @llvm.riscv.vunzipe(
    <vscale x 2 x half> %passthru,
    <vscale x 4 x half> %src,
    iXLen %vl)
  ret <vscale x 2 x half> %r
}

define <vscale x 2 x half> @test_vunzipe_mask_f16mf2(<vscale x 2 x half> %passthru, <vscale x 4 x half> %src, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x half> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x half> %passthru,
    <vscale x 4 x half> %src,
    <vscale x 2 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x half> %r
}

define <vscale x 4 x half> @test_vunzipe_f16m1(<vscale x 4 x half> %passthru, <vscale x 8 x half> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x half> @llvm.riscv.vunzipe(
    <vscale x 4 x half> %passthru,
    <vscale x 8 x half> %src,
    iXLen %vl)
  ret <vscale x 4 x half> %r
}

define <vscale x 4 x half> @test_vunzipe_mask_f16m1(<vscale x 4 x half> %passthru, <vscale x 8 x half> %src, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x half> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x half> %passthru,
    <vscale x 8 x half> %src,
    <vscale x 4 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x half> %r
}

define <vscale x 8 x half> @test_vunzipe_f16m2(<vscale x 8 x half> %passthru, <vscale x 16 x half> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x half> @llvm.riscv.vunzipe(
    <vscale x 8 x half> %passthru,
    <vscale x 16 x half> %src,
    iXLen %vl)
  ret <vscale x 8 x half> %r
}

define <vscale x 8 x half> @test_vunzipe_mask_f16m2(<vscale x 8 x half> %passthru, <vscale x 16 x half> %src, <vscale x 8 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x half> @llvm.riscv.vunzipe.mask(
    <vscale x 8 x half> %passthru,
    <vscale x 16 x half> %src,
    <vscale x 8 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x half> %r
}

define <vscale x 16 x half> @test_vunzipe_f16m4(<vscale x 16 x half> %passthru, <vscale x 32 x half> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x half> @llvm.riscv.vunzipe(
    <vscale x 16 x half> %passthru,
    <vscale x 32 x half> %src,
    iXLen %vl)
  ret <vscale x 16 x half> %r
}

define <vscale x 16 x half> @test_vunzipe_mask_f16m4(<vscale x 16 x half> %passthru, <vscale x 32 x half> %src, <vscale x 16 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x half> @llvm.riscv.vunzipe.mask(
    <vscale x 16 x half> %passthru,
    <vscale x 32 x half> %src,
    <vscale x 16 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 16 x half> %r
}

; bf16
define <vscale x 1 x bfloat> @test_vunzipe_bf16mf4(<vscale x 1 x bfloat> %passthru, <vscale x 2 x bfloat> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_bf16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x bfloat> @llvm.riscv.vunzipe(
    <vscale x 1 x bfloat> %passthru,
    <vscale x 2 x bfloat> %src,
    iXLen %vl)
  ret <vscale x 1 x bfloat> %r
}

define <vscale x 1 x bfloat> @test_vunzipe_mask_bf16mf4(<vscale x 1 x bfloat> %passthru, <vscale x 2 x bfloat> %src, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_bf16mf4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x bfloat> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x bfloat> %passthru,
    <vscale x 2 x bfloat> %src,
    <vscale x 1 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x bfloat> %r
}

define <vscale x 2 x bfloat> @test_vunzipe_bf16mf2(<vscale x 2 x bfloat> %passthru, <vscale x 4 x bfloat> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_bf16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x bfloat> @llvm.riscv.vunzipe(
    <vscale x 2 x bfloat> %passthru,
    <vscale x 4 x bfloat> %src,
    iXLen %vl)
  ret <vscale x 2 x bfloat> %r
}

define <vscale x 2 x bfloat> @test_vunzipe_mask_bf16mf2(<vscale x 2 x bfloat> %passthru, <vscale x 4 x bfloat> %src, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_bf16mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, mf2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x bfloat> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x bfloat> %passthru,
    <vscale x 4 x bfloat> %src,
    <vscale x 2 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x bfloat> %r
}

define <vscale x 4 x bfloat> @test_vunzipe_bf16m1(<vscale x 4 x bfloat> %passthru, <vscale x 8 x bfloat> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_bf16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vunzipe(
    <vscale x 4 x bfloat> %passthru,
    <vscale x 8 x bfloat> %src,
    iXLen %vl)
  ret <vscale x 4 x bfloat> %r
}

define <vscale x 4 x bfloat> @test_vunzipe_mask_bf16m1(<vscale x 4 x bfloat> %passthru, <vscale x 8 x bfloat> %src, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_bf16m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x bfloat> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x bfloat> %passthru,
    <vscale x 8 x bfloat> %src,
    <vscale x 4 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x bfloat> %r
}

define <vscale x 8 x bfloat> @test_vunzipe_bf16m2(<vscale x 8 x bfloat> %passthru, <vscale x 16 x bfloat> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_bf16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x bfloat> @llvm.riscv.vunzipe(
    <vscale x 8 x bfloat> %passthru,
    <vscale x 16 x bfloat> %src,
    iXLen %vl)
  ret <vscale x 8 x bfloat> %r
}

define <vscale x 8 x bfloat> @test_vunzipe_mask_bf16m2(<vscale x 8 x bfloat> %passthru, <vscale x 16 x bfloat> %src, <vscale x 8 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_bf16m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x bfloat> @llvm.riscv.vunzipe.mask(
    <vscale x 8 x bfloat> %passthru,
    <vscale x 16 x bfloat> %src,
    <vscale x 8 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x bfloat> %r
}

define <vscale x 16 x bfloat> @test_vunzipe_bf16m4(<vscale x 16 x bfloat> %passthru, <vscale x 32 x bfloat> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_bf16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x bfloat> @llvm.riscv.vunzipe(
    <vscale x 16 x bfloat> %passthru,
    <vscale x 32 x bfloat> %src,
    iXLen %vl)
  ret <vscale x 16 x bfloat> %r
}

define <vscale x 16 x bfloat> @test_vunzipe_mask_bf16m4(<vscale x 16 x bfloat> %passthru, <vscale x 32 x bfloat> %src, <vscale x 16 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_bf16m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e16, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 16 x bfloat> @llvm.riscv.vunzipe.mask(
    <vscale x 16 x bfloat> %passthru,
    <vscale x 32 x bfloat> %src,
    <vscale x 16 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 16 x bfloat> %r
}

; f32
define <vscale x 1 x float> @test_vunzipe_f32mf2(<vscale x 1 x float> %passthru, <vscale x 2 x float> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v9
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x float> @llvm.riscv.vunzipe(
    <vscale x 1 x float> %passthru,
    <vscale x 2 x float> %src,
    iXLen %vl)
  ret <vscale x 1 x float> %r
}

define <vscale x 1 x float> @test_vunzipe_mask_f32mf2(<vscale x 1 x float> %passthru, <vscale x 2 x float> %src, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f32mf2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, mf2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v9, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x float> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x float> %passthru,
    <vscale x 2 x float> %src,
    <vscale x 1 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x float> %r
}

define <vscale x 2 x float> @test_vunzipe_f32m1(<vscale x 2 x float> %passthru, <vscale x 4 x float> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x float> @llvm.riscv.vunzipe(
    <vscale x 2 x float> %passthru,
    <vscale x 4 x float> %src,
    iXLen %vl)
  ret <vscale x 2 x float> %r
}

define <vscale x 2 x float> @test_vunzipe_mask_f32m1(<vscale x 2 x float> %passthru, <vscale x 4 x float> %src, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f32m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x float> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x float> %passthru,
    <vscale x 4 x float> %src,
    <vscale x 2 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x float> %r
}

define <vscale x 4 x float> @test_vunzipe_f32m2(<vscale x 4 x float> %passthru, <vscale x 8 x float> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x float> @llvm.riscv.vunzipe(
    <vscale x 4 x float> %passthru,
    <vscale x 8 x float> %src,
    iXLen %vl)
  ret <vscale x 4 x float> %r
}

define <vscale x 4 x float> @test_vunzipe_mask_f32m2(<vscale x 4 x float> %passthru, <vscale x 8 x float> %src, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f32m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x float> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x float> %passthru,
    <vscale x 8 x float> %src,
    <vscale x 4 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x float> %r
}

define <vscale x 8 x float> @test_vunzipe_f32m4(<vscale x 8 x float> %passthru, <vscale x 16 x float> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x float> @llvm.riscv.vunzipe(
    <vscale x 8 x float> %passthru,
    <vscale x 16 x float> %src,
    iXLen %vl)
  ret <vscale x 8 x float> %r
}

define <vscale x 8 x float> @test_vunzipe_mask_f32m4(<vscale x 8 x float> %passthru, <vscale x 16 x float> %src, <vscale x 8 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f32m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e32, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 8 x float> @llvm.riscv.vunzipe.mask(
    <vscale x 8 x float> %passthru,
    <vscale x 16 x float> %src,
    <vscale x 8 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 8 x float> %r
}

; f64
define <vscale x 1 x double> @test_vunzipe_f64m1(<vscale x 1 x double> %passthru, <vscale x 2 x double> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v10
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x double> @llvm.riscv.vunzipe(
    <vscale x 1 x double> %passthru,
    <vscale x 2 x double> %src,
    iXLen %vl)
  ret <vscale x 1 x double> %r
}

define <vscale x 1 x double> @test_vunzipe_mask_f64m1(<vscale x 1 x double> %passthru, <vscale x 2 x double> %src, <vscale x 1 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f64m1:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m1, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v10, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 1 x double> @llvm.riscv.vunzipe.mask(
    <vscale x 1 x double> %passthru,
    <vscale x 2 x double> %src,
    <vscale x 1 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 1 x double> %r
}

define <vscale x 2 x double> @test_vunzipe_f64m2(<vscale x 2 x double> %passthru, <vscale x 4 x double> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v12
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x double> @llvm.riscv.vunzipe(
    <vscale x 2 x double> %passthru,
    <vscale x 4 x double> %src,
    iXLen %vl)
  ret <vscale x 2 x double> %r
}

define <vscale x 2 x double> @test_vunzipe_mask_f64m2(<vscale x 2 x double> %passthru, <vscale x 4 x double> %src, <vscale x 2 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f64m2:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m2, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v12, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 2 x double> @llvm.riscv.vunzipe.mask(
    <vscale x 2 x double> %passthru,
    <vscale x 4 x double> %src,
    <vscale x 2 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 2 x double> %r
}

define <vscale x 4 x double> @test_vunzipe_f64m4(<vscale x 4 x double> %passthru, <vscale x 8 x double> %src, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_f64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, tu, ma
; CHECK-NEXT:    vunzipe.v v8, v16
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x double> @llvm.riscv.vunzipe(
    <vscale x 4 x double> %passthru,
    <vscale x 8 x double> %src,
    iXLen %vl)
  ret <vscale x 4 x double> %r
}

define <vscale x 4 x double> @test_vunzipe_mask_f64m4(<vscale x 4 x double> %passthru, <vscale x 8 x double> %src, <vscale x 4 x i1> %m, iXLen %vl) nounwind {
; CHECK-LABEL: test_vunzipe_mask_f64m4:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vsetvli zero, a0, e64, m4, ta, mu
; CHECK-NEXT:    vunzipe.v v8, v16, v0.t
; CHECK-NEXT:    ret
  %r = call <vscale x 4 x double> @llvm.riscv.vunzipe.mask(
    <vscale x 4 x double> %passthru,
    <vscale x 8 x double> %src,
    <vscale x 4 x i1> %m,
    iXLen %vl, iXLen 1)
  ret <vscale x 4 x double> %r
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RV32: {{.*}}
; RV64: {{.*}}
