; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=riscv64 -mattr=+v,+m < %s | FileCheck %s

define void @widen_deinterleave(<9 x i32> %v, ptr %dst0, ptr %dst1, ptr %dst2) nounwind {
; CHECK-LABEL: widen_deinterleave:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 2
; CHECK-NEXT:    sub sp, sp, a3
; CHECK-NEXT:    vsetivli zero, 4, e32, m4, ta, ma
; CHECK-NEXT:    vslidedown.vi v12, v8, 8
; CHECK-NEXT:    vsetivli zero, 4, e32, m2, ta, ma
; CHECK-NEXT:    vslidedown.vi v10, v8, 4
; CHECK-NEXT:    vmv1r.v v9, v10
; CHECK-NEXT:    vmv2r.v v10, v12
; CHECK-NEXT:    addi a3, sp, 16
; CHECK-NEXT:    vs4r.v v8, (a3)
; CHECK-NEXT:    vsetvli a4, zero, e32, m1, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a3)
; CHECK-NEXT:    vsetivli zero, 3, e32, m1, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vse32.v v9, (a1)
; CHECK-NEXT:    vse32.v v10, (a2)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 2
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %d = call {<3 x i32>, <3 x i32>, <3 x i32>} @llvm.vector.deinterleave3(<9 x i32> %v)
  %f0 = extractvalue {<3 x i32>, <3 x i32>, <3 x i32>} %d, 0
  %f1 = extractvalue {<3 x i32>, <3 x i32>, <3 x i32>} %d, 1
  %f2 = extractvalue {<3 x i32>, <3 x i32>, <3 x i32>} %d, 2
  store <3 x i32> %f0, ptr %dst0
  store <3 x i32> %f1, ptr %dst1
  store <3 x i32> %f2, ptr %dst2
  ret void
}

define void @widen_deinterleave_scalable(<vscale x 9 x i32> %v, ptr %dst0, ptr %dst1, ptr %dst2) nounwind {
; CHECK-LABEL: widen_deinterleave_scalable:
; CHECK:       # %bb.0:
; CHECK-NEXT:    addi sp, sp, -16
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    slli a3, a3, 3
; CHECK-NEXT:    sub sp, sp, a3
; CHECK-NEXT:    addi a3, sp, 16
; CHECK-NEXT:    vs8r.v v8, (a3)
; CHECK-NEXT:    vsetvli a4, zero, e32, m2, ta, ma
; CHECK-NEXT:    vlseg3e32.v v8, (a3)
; CHECK-NEXT:    csrr a3, vlenb
; CHECK-NEXT:    srli a4, a3, 3
; CHECK-NEXT:    srli a3, a3, 2
; CHECK-NEXT:    add a3, a3, a4
; CHECK-NEXT:    vsetvli zero, a3, e32, m2, ta, ma
; CHECK-NEXT:    vse32.v v8, (a0)
; CHECK-NEXT:    vse32.v v10, (a1)
; CHECK-NEXT:    vse32.v v12, (a2)
; CHECK-NEXT:    csrr a0, vlenb
; CHECK-NEXT:    slli a0, a0, 3
; CHECK-NEXT:    add sp, sp, a0
; CHECK-NEXT:    addi sp, sp, 16
; CHECK-NEXT:    ret
  %d = call {<vscale x 3 x i32>, <vscale x 3 x i32>, <vscale x 3 x i32>} @llvm.vector.deinterleave3(<vscale x 9 x i32> %v)
  %f0 = extractvalue {<vscale x 3 x i32>, <vscale x 3 x i32>, <vscale x 3 x i32>} %d, 0
  %f1 = extractvalue {<vscale x 3 x i32>, <vscale x 3 x i32>, <vscale x 3 x i32>} %d, 1
  %f2 = extractvalue {<vscale x 3 x i32>, <vscale x 3 x i32>, <vscale x 3 x i32>} %d, 2
  store <vscale x 3 x i32> %f0, ptr %dst0
  store <vscale x 3 x i32> %f1, ptr %dst1
  store <vscale x 3 x i32> %f2, ptr %dst2
  ret void
}
