; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=mergereturn -S < %s | FileCheck %s

define i32 @test0() {
; CHECK-LABEL: define i32 @test0() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    br label %[[LOOP]]
; CHECK:       [[DEOPT:.*:]]
; CHECK-NEXT:    [[DEOPT_RES:%.*]] = call i32 (...) @llvm.experimental.deoptimize.i32() [ "deopt"() ]
; CHECK-NEXT:    ret i32 [[DEOPT_RES]]
; CHECK:       [[EXIT:.*:]]
; CHECK-NEXT:    ret i32 0
;
entry:
  br label %loop

loop:                                             ; preds = %loop, %entry
  br label %loop

deopt:                                            ; No predecessors!
  %deopt_res = call i32 (...) @llvm.experimental.deoptimize.i32() [ "deopt"() ]
  ret i32 %deopt_res

exit:                                             ; No predecessors!
  ret i32 0
}

declare i32 @llvm.experimental.deoptimize.i32(...)
