; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=load-store-vectorizer %s -S | FileCheck %s
; RUN: opt -aa-pipeline=basic-aa -passes='function(load-store-vectorizer)' %s -S | FileCheck %s

; Check that setting wrapping flags after a SCEV node is created
; does not invalidate "sorted by complexity" invariant for
; operands of commutative and associative SCEV operators.

target triple = "x86_64--"

@global_value0 = external constant i32
@global_value1 = external constant i32
@other_value = external global float
@a = external global float
@b = external global float
@c = external global float
@d = external global float
@plus1 = external global i32
@cnd = external global i8

; Function Attrs: nounwind
define void @main() local_unnamed_addr #0 {
; CHECK-LABEL: define void @main(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP:%.*]] = load i32, ptr @global_value0, align 4, !range [[RNG0:![0-9]+]]
; CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr @global_value1, align 4
; CHECK-NEXT:    [[AND_I_I:%.*]] = and i32 [[TMP2]], 2
; CHECK-NEXT:    [[ADD_NUW_NSW_I_I:%.*]] = add nuw nsw i32 [[AND_I_I]], 0
; CHECK-NEXT:    [[MUL_I_I:%.*]] = shl nuw nsw i32 [[ADD_NUW_NSW_I_I]], 1
; CHECK-NEXT:    [[AND6_I_I:%.*]] = and i32 [[TMP2]], 3
; CHECK-NEXT:    [[AND9_I_I:%.*]] = and i32 [[TMP2]], 4
; CHECK-NEXT:    [[ADD_NUW_NSW10_I_I:%.*]] = add nuw nsw i32 [[AND6_I_I]], [[AND9_I_I]]
; CHECK-NEXT:    [[CONV3_I42_I:%.*]] = add nuw nsw i32 [[MUL_I_I]], 1
; CHECK-NEXT:    [[REASS_ADD346_7:%.*]] = add nuw nsw i32 [[ADD_NUW_NSW10_I_I]], 56
; CHECK-NEXT:    [[REASS_MUL347_7:%.*]] = mul nuw nsw i32 [[TMP]], [[REASS_ADD346_7]]
; CHECK-NEXT:    [[ADD7_I_7:%.*]] = add nuw nsw i32 [[REASS_MUL347_7]], 0
; CHECK-NEXT:    [[PREHEADER_ADDRESS0_IDX:%.*]] = add nuw nsw i32 [[ADD7_I_7]], [[MUL_I_I]]
; CHECK-NEXT:    [[PREHEADER_ADDRESS0_IDX_ZEXT:%.*]] = zext i32 [[PREHEADER_ADDRESS0_IDX]] to i64
; CHECK-NEXT:    [[PREHEADER_LOAD0_ADDRESS:%.*]] = getelementptr inbounds float, ptr @other_value, i64 [[PREHEADER_ADDRESS0_IDX_ZEXT]]
; CHECK-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[PREHEADER_LOAD0_ADDRESS]], align 4, !tbaa [[FLOAT_TBAA1:![0-9]+]]
; CHECK-NEXT:    [[PREHEADER_LOAD0_1:%.*]] = extractelement <2 x float> [[TMP0]], i32 0
; CHECK-NEXT:    [[PREHEADER_LOAD1_2:%.*]] = extractelement <2 x float> [[TMP0]], i32 1
; CHECK-NEXT:    [[COMMON_ADDRESS_IDX:%.*]] = add nuw nsw i32 [[ADD7_I_7]], [[CONV3_I42_I]]
; CHECK-NEXT:    [[PREHEADER_HEADER_COMMON_ADDRESS_IDX_ZEXT:%.*]] = zext i32 [[COMMON_ADDRESS_IDX]] to i64
; CHECK-NEXT:    br label %[[FOR_BODY23:.*]]
; CHECK:       [[FOR_BODY23]]:
; CHECK-NEXT:    [[LOOP_HEADER_LOAD0_ADDRESS:%.*]] = getelementptr inbounds float, ptr @other_value, i64 [[PREHEADER_HEADER_COMMON_ADDRESS_IDX_ZEXT]]
; CHECK-NEXT:    [[LOOP_HEADER_LOAD0_:%.*]] = load float, ptr [[LOOP_HEADER_LOAD0_ADDRESS]], align 4, !tbaa [[FLOAT_TBAA1]]
; CHECK-NEXT:    [[REASS_MUL343_7:%.*]] = mul nuw nsw i32 [[REASS_ADD346_7]], 72
; CHECK-NEXT:    [[ADD7_I286_7_7:%.*]] = add nuw nsw i32 [[REASS_MUL343_7]], 56
; CHECK-NEXT:    [[ADD9_I288_7_7:%.*]] = add nuw nsw i32 [[ADD7_I286_7_7]], [[MUL_I_I]]
; CHECK-NEXT:    [[LOOP_HEADER_ADDRESS1_IDX:%.*]] = add nuw nsw i32 [[ADD9_I288_7_7]], 1
; CHECK-NEXT:    [[LOOP_HEADER_ADDRESS1_IDX_ZEXT:%.*]] = zext i32 [[LOOP_HEADER_ADDRESS1_IDX]] to i64
; CHECK-NEXT:    [[LOOP_HEADER_LOAD1_ADDRESS:%.*]] = getelementptr inbounds float, ptr @other_value, i64 [[LOOP_HEADER_ADDRESS1_IDX_ZEXT]]
; CHECK-NEXT:    [[LOOP_HEADER_LOAD1_:%.*]] = load float, ptr [[LOOP_HEADER_LOAD1_ADDRESS]], align 4, !tbaa [[FLOAT_TBAA1]]
; CHECK-NEXT:    store float [[PREHEADER_LOAD0_1]], ptr @a, align 4, !tbaa [[FLOAT_TBAA1]]
; CHECK-NEXT:    store float [[PREHEADER_LOAD1_2]], ptr @b, align 4, !tbaa [[FLOAT_TBAA1]]
; CHECK-NEXT:    store float [[LOOP_HEADER_LOAD0_]], ptr @c, align 4, !tbaa [[FLOAT_TBAA1]]
; CHECK-NEXT:    store float [[LOOP_HEADER_LOAD1_]], ptr @d, align 4, !tbaa [[FLOAT_TBAA1]]
; CHECK-NEXT:    [[LOADED_CND:%.*]] = load i8, ptr @cnd, align 1
; CHECK-NEXT:    [[CONDITION:%.*]] = trunc i8 [[LOADED_CND]] to i1
; CHECK-NEXT:    br i1 [[CONDITION]], label %[[FOR_BODY23]], label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  %tmp = load i32, ptr @global_value0, !range !0
  %tmp2 = load i32, ptr @global_value1
  %and.i.i = and i32 %tmp2, 2
  %add.nuw.nsw.i.i = add nuw nsw i32 %and.i.i, 0
  %mul.i.i = shl nuw nsw i32 %add.nuw.nsw.i.i, 1
  %and6.i.i = and i32 %tmp2, 3
  %and9.i.i = and i32 %tmp2, 4
  %add.nuw.nsw10.i.i = add nuw nsw i32 %and6.i.i, %and9.i.i
  %conv3.i42.i = add nuw nsw i32 %mul.i.i, 1
  %reass.add346.7 = add nuw nsw i32 %add.nuw.nsw10.i.i, 56
  %reass.mul347.7 = mul nuw nsw i32 %tmp, %reass.add346.7
  %add7.i.7 = add nuw nsw i32 %reass.mul347.7, 0
  %preheader.address0.idx = add nuw nsw i32 %add7.i.7, %mul.i.i
  %preheader.address0.idx.zext = zext i32 %preheader.address0.idx to i64
  %preheader.load0.address = getelementptr inbounds float, ptr @other_value, i64 %preheader.address0.idx.zext
  %preheader.load0. = load float, ptr %preheader.load0.address, align 4, !tbaa !1
  %common.address.idx = add nuw nsw i32 %add7.i.7, %conv3.i42.i
  %preheader.header.common.address.idx.zext = zext i32 %common.address.idx to i64
  %preheader.load1.address = getelementptr inbounds float, ptr @other_value, i64 %preheader.header.common.address.idx.zext
  %preheader.load1. = load float, ptr %preheader.load1.address, align 4, !tbaa !1
  br label %for.body23

for.body23:                                       ; preds = %for.body23, %entry
  %loop.header.load0.address = getelementptr inbounds float, ptr @other_value, i64 %preheader.header.common.address.idx.zext
  %loop.header.load0. = load float, ptr %loop.header.load0.address, align 4, !tbaa !1
  %reass.mul343.7 = mul nuw nsw i32 %reass.add346.7, 72
  %add7.i286.7.7 = add nuw nsw i32 %reass.mul343.7, 56
  %add9.i288.7.7 = add nuw nsw i32 %add7.i286.7.7, %mul.i.i
  %loop.header.address1.idx = add nuw nsw i32 %add9.i288.7.7, 1
  %loop.header.address1.idx.zext = zext i32 %loop.header.address1.idx to i64
  %loop.header.load1.address = getelementptr inbounds float, ptr @other_value, i64 %loop.header.address1.idx.zext
  %loop.header.load1. = load float, ptr %loop.header.load1.address, align 4, !tbaa !1
  store float %preheader.load0., ptr @a, align 4, !tbaa !1
  store float %preheader.load1., ptr @b, align 4, !tbaa !1
  store float %loop.header.load0., ptr @c, align 4, !tbaa !1
  store float %loop.header.load1., ptr @d, align 4, !tbaa !1
  %loaded.cnd = load i8, ptr @cnd
  %condition = trunc i8 %loaded.cnd to i1
  br i1 %condition, label %for.body23, label %exit

exit:
  ret void
}

attributes #0 = { nounwind }

!0 = !{i32 0, i32 65536}
!1 = !{!2, !2, i64 0}
!2 = !{!"float", !3, i64 0}
!3 = !{!"omnipotent char", !4, i64 0}
!4 = !{!"Simple C++ TBAA"}
;.
; CHECK: [[RNG0]] = !{i32 0, i32 65536}
; CHECK: [[FLOAT_TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
; CHECK: [[META2]] = !{!"float", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"Simple C++ TBAA"}
;.
