; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=x86_64-unknown-linux-gnu -passes=load-store-vectorizer -mcpu haswell -S -o - %s | FileCheck --check-prefix=CHECK-HSW %s
; RUN: opt -mtriple=x86_64-unknown-linux-gnu -passes=load-store-vectorizer -mcpu knl -S -o - %s | FileCheck --check-prefix=CHECK-KNL %s
; RUN: opt -mtriple=x86_64-unknown-linux-gnu -aa-pipeline=basic-aa -passes='function(load-store-vectorizer)' -mcpu haswell -S -o - %s | FileCheck --check-prefix=CHECK-HSW %s
; RUN: opt -mtriple=x86_64-unknown-linux-gnu -aa-pipeline=basic-aa -passes='function(load-store-vectorizer)' -mcpu knl -S -o - %s | FileCheck --check-prefix=CHECK-KNL %s

define <8 x double> @loadwidth_insert_extract(ptr %ptr) {
; CHECK-HSW-LABEL: define <8 x double> @loadwidth_insert_extract(
; CHECK-HSW-SAME: ptr [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-HSW-NEXT:    [[C:%.*]] = getelementptr <2 x double>, ptr [[PTR]], i32 2
; CHECK-HSW-NEXT:    [[TMP1:%.*]] = load <4 x b64>, ptr [[PTR]], align 16
; CHECK-HSW-NEXT:    [[LA1:%.*]] = shufflevector <4 x b64> [[TMP1]], <4 x b64> poison, <2 x i32> <i32 0, i32 1>
; CHECK-HSW-NEXT:    [[TMP2:%.*]] = bitcast <2 x b64> [[LA1]] to <2 x double>
; CHECK-HSW-NEXT:    [[LB2:%.*]] = shufflevector <4 x b64> [[TMP1]], <4 x b64> poison, <2 x i32> <i32 2, i32 3>
; CHECK-HSW-NEXT:    [[TMP3:%.*]] = bitcast <2 x b64> [[LB2]] to <2 x double>
; CHECK-HSW-NEXT:    [[TMP4:%.*]] = load <4 x b64>, ptr [[C]], align 16
; CHECK-HSW-NEXT:    [[LC3:%.*]] = shufflevector <4 x b64> [[TMP4]], <4 x b64> poison, <2 x i32> <i32 0, i32 1>
; CHECK-HSW-NEXT:    [[TMP5:%.*]] = bitcast <2 x b64> [[LC3]] to <2 x double>
; CHECK-HSW-NEXT:    [[LD4:%.*]] = shufflevector <4 x b64> [[TMP4]], <4 x b64> poison, <2 x i32> <i32 2, i32 3>
; CHECK-HSW-NEXT:    [[TMP6:%.*]] = bitcast <2 x b64> [[LD4]] to <2 x double>
; CHECK-HSW-NEXT:    [[V1:%.*]] = extractelement <2 x double> [[TMP2]], i32 0
; CHECK-HSW-NEXT:    [[V2:%.*]] = extractelement <2 x double> [[TMP2]], i32 1
; CHECK-HSW-NEXT:    [[V3:%.*]] = extractelement <2 x double> [[TMP3]], i32 0
; CHECK-HSW-NEXT:    [[V4:%.*]] = extractelement <2 x double> [[TMP3]], i32 1
; CHECK-HSW-NEXT:    [[V5:%.*]] = extractelement <2 x double> [[TMP5]], i32 0
; CHECK-HSW-NEXT:    [[V6:%.*]] = extractelement <2 x double> [[TMP5]], i32 1
; CHECK-HSW-NEXT:    [[V7:%.*]] = extractelement <2 x double> [[TMP6]], i32 0
; CHECK-HSW-NEXT:    [[V8:%.*]] = extractelement <2 x double> [[TMP6]], i32 1
; CHECK-HSW-NEXT:    [[I1:%.*]] = insertelement <8 x double> poison, double [[V1]], i32 0
; CHECK-HSW-NEXT:    [[I2:%.*]] = insertelement <8 x double> [[I1]], double [[V2]], i32 1
; CHECK-HSW-NEXT:    [[I3:%.*]] = insertelement <8 x double> [[I2]], double [[V3]], i32 2
; CHECK-HSW-NEXT:    [[I4:%.*]] = insertelement <8 x double> [[I3]], double [[V4]], i32 3
; CHECK-HSW-NEXT:    [[I5:%.*]] = insertelement <8 x double> [[I4]], double [[V5]], i32 4
; CHECK-HSW-NEXT:    [[I6:%.*]] = insertelement <8 x double> [[I5]], double [[V6]], i32 5
; CHECK-HSW-NEXT:    [[I7:%.*]] = insertelement <8 x double> [[I6]], double [[V7]], i32 6
; CHECK-HSW-NEXT:    [[I8:%.*]] = insertelement <8 x double> [[I7]], double [[V8]], i32 7
; CHECK-HSW-NEXT:    ret <8 x double> [[I8]]
;
; CHECK-KNL-LABEL: define <8 x double> @loadwidth_insert_extract(
; CHECK-KNL-SAME: ptr [[PTR:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-KNL-NEXT:    [[TMP1:%.*]] = load <8 x b64>, ptr [[PTR]], align 16
; CHECK-KNL-NEXT:    [[LA1:%.*]] = shufflevector <8 x b64> [[TMP1]], <8 x b64> poison, <2 x i32> <i32 0, i32 1>
; CHECK-KNL-NEXT:    [[TMP2:%.*]] = bitcast <2 x b64> [[LA1]] to <2 x double>
; CHECK-KNL-NEXT:    [[LB2:%.*]] = shufflevector <8 x b64> [[TMP1]], <8 x b64> poison, <2 x i32> <i32 2, i32 3>
; CHECK-KNL-NEXT:    [[TMP3:%.*]] = bitcast <2 x b64> [[LB2]] to <2 x double>
; CHECK-KNL-NEXT:    [[LC3:%.*]] = shufflevector <8 x b64> [[TMP1]], <8 x b64> poison, <2 x i32> <i32 4, i32 5>
; CHECK-KNL-NEXT:    [[TMP4:%.*]] = bitcast <2 x b64> [[LC3]] to <2 x double>
; CHECK-KNL-NEXT:    [[LD4:%.*]] = shufflevector <8 x b64> [[TMP1]], <8 x b64> poison, <2 x i32> <i32 6, i32 7>
; CHECK-KNL-NEXT:    [[TMP5:%.*]] = bitcast <2 x b64> [[LD4]] to <2 x double>
; CHECK-KNL-NEXT:    [[V1:%.*]] = extractelement <2 x double> [[TMP2]], i32 0
; CHECK-KNL-NEXT:    [[V2:%.*]] = extractelement <2 x double> [[TMP2]], i32 1
; CHECK-KNL-NEXT:    [[V3:%.*]] = extractelement <2 x double> [[TMP3]], i32 0
; CHECK-KNL-NEXT:    [[V4:%.*]] = extractelement <2 x double> [[TMP3]], i32 1
; CHECK-KNL-NEXT:    [[V5:%.*]] = extractelement <2 x double> [[TMP4]], i32 0
; CHECK-KNL-NEXT:    [[V6:%.*]] = extractelement <2 x double> [[TMP4]], i32 1
; CHECK-KNL-NEXT:    [[V7:%.*]] = extractelement <2 x double> [[TMP5]], i32 0
; CHECK-KNL-NEXT:    [[V8:%.*]] = extractelement <2 x double> [[TMP5]], i32 1
; CHECK-KNL-NEXT:    [[I1:%.*]] = insertelement <8 x double> poison, double [[V1]], i32 0
; CHECK-KNL-NEXT:    [[I2:%.*]] = insertelement <8 x double> [[I1]], double [[V2]], i32 1
; CHECK-KNL-NEXT:    [[I3:%.*]] = insertelement <8 x double> [[I2]], double [[V3]], i32 2
; CHECK-KNL-NEXT:    [[I4:%.*]] = insertelement <8 x double> [[I3]], double [[V4]], i32 3
; CHECK-KNL-NEXT:    [[I5:%.*]] = insertelement <8 x double> [[I4]], double [[V5]], i32 4
; CHECK-KNL-NEXT:    [[I6:%.*]] = insertelement <8 x double> [[I5]], double [[V6]], i32 5
; CHECK-KNL-NEXT:    [[I7:%.*]] = insertelement <8 x double> [[I6]], double [[V7]], i32 6
; CHECK-KNL-NEXT:    [[I8:%.*]] = insertelement <8 x double> [[I7]], double [[V8]], i32 7
; CHECK-KNL-NEXT:    ret <8 x double> [[I8]]
;
  %b = getelementptr <2 x double>, ptr %ptr, i32 1
  %c = getelementptr <2 x double>, ptr %ptr, i32 2
  %d = getelementptr <2 x double>, ptr %ptr, i32 3
  %la = load <2 x double>, ptr %ptr
  %lb = load <2 x double>, ptr %b
  %lc = load <2 x double>, ptr %c
  %ld = load <2 x double>, ptr %d
  ; Scalarize everything - Explicitly not a shufflevector to test this code
  ; path in the LSV
  %v1 = extractelement <2 x double> %la, i32 0
  %v2 = extractelement <2 x double> %la, i32 1
  %v3 = extractelement <2 x double> %lb, i32 0
  %v4 = extractelement <2 x double> %lb, i32 1
  %v5 = extractelement <2 x double> %lc, i32 0
  %v6 = extractelement <2 x double> %lc, i32 1
  %v7 = extractelement <2 x double> %ld, i32 0
  %v8 = extractelement <2 x double> %ld, i32 1
  ; Make a vector again
  %i1 = insertelement <8 x double> poison, double %v1, i32 0
  %i2 = insertelement <8 x double> %i1, double %v2, i32 1
  %i3 = insertelement <8 x double> %i2, double %v3, i32 2
  %i4 = insertelement <8 x double> %i3, double %v4, i32 3
  %i5 = insertelement <8 x double> %i4, double %v5, i32 4
  %i6 = insertelement <8 x double> %i5, double %v6, i32 5
  %i7 = insertelement <8 x double> %i6, double %v7, i32 6
  %i8 = insertelement <8 x double> %i7, double %v8, i32 7
  ret <8 x double> %i8
}
