; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt %s -mtriple=x86_64-unknown-linux-gnu -passes=load-store-vectorizer -S -o - | FileCheck %s
;
; Test that LoadStoreVectorizer handles `or disjoint` in GEP index
; computations, vectorizing loads with zext(or disjoint %idx, K) indices.

target datalayout = "e-p:64:64-i64:64-n32:64"

; Case A (baseline): zext(add nuw) - vectorizes on x86 as <3 x i32> + scalar.
define void @test_zext_add(ptr %base, i32 %idx) {
; CHECK-LABEL: define void @test_zext_add(
; CHECK-SAME: ptr [[BASE:%.*]], i32 [[IDX:%.*]]) {
; CHECK-NEXT:    [[I0:%.*]] = zext i32 [[IDX]] to i64
; CHECK-NEXT:    [[G0:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I0]]
; CHECK-NEXT:    [[TMP1:%.*]] = load <3 x b32>, ptr [[G0]], align 4
; CHECK-NEXT:    [[V1:%.*]] = extractelement <3 x b32> [[TMP1]], i32 0
; CHECK-NEXT:    [[V01:%.*]] = bitcast b32 [[V1]] to i32
; CHECK-NEXT:    [[V13:%.*]] = extractelement <3 x b32> [[TMP1]], i32 1
; CHECK-NEXT:    [[V12:%.*]] = bitcast b32 [[V13]] to i32
; CHECK-NEXT:    [[V24:%.*]] = extractelement <3 x b32> [[TMP1]], i32 2
; CHECK-NEXT:    [[V23:%.*]] = bitcast b32 [[V24]] to i32
; CHECK-NEXT:    [[IDX3:%.*]] = add nuw i32 [[IDX]], 3
; CHECK-NEXT:    [[I3:%.*]] = zext i32 [[IDX3]] to i64
; CHECK-NEXT:    [[G3:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I3]]
; CHECK-NEXT:    [[V3:%.*]] = load i32, ptr [[G3]], align 4
; CHECK-NEXT:    [[S:%.*]] = add i32 [[V01]], [[V12]]
; CHECK-NEXT:    [[S2:%.*]] = add i32 [[S]], [[V23]]
; CHECK-NEXT:    [[S3:%.*]] = add i32 [[S2]], [[V3]]
; CHECK-NEXT:    [[OUT_IDX:%.*]] = sext i32 [[S3]] to i64
; CHECK-NEXT:    [[OUT:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[OUT_IDX]]
; CHECK-NEXT:    store i32 [[S3]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  %i0 = zext i32 %idx to i64
  %g0 = getelementptr inbounds i32, ptr %base, i64 %i0
  %v0 = load i32, ptr %g0, align 4

  %idx1 = add nuw i32 %idx, 1
  %i1 = zext i32 %idx1 to i64
  %g1 = getelementptr inbounds i32, ptr %base, i64 %i1
  %v1 = load i32, ptr %g1, align 4

  %idx2 = add nuw i32 %idx, 2
  %i2 = zext i32 %idx2 to i64
  %g2 = getelementptr inbounds i32, ptr %base, i64 %i2
  %v2 = load i32, ptr %g2, align 4

  %idx3 = add nuw i32 %idx, 3
  %i3 = zext i32 %idx3 to i64
  %g3 = getelementptr inbounds i32, ptr %base, i64 %i3
  %v3 = load i32, ptr %g3, align 4

  %s = add i32 %v0, %v1
  %s2 = add i32 %s, %v2
  %s3 = add i32 %s2, %v3
  %out_idx = sext i32 %s3 to i64
  %out = getelementptr inbounds i32, ptr %base, i64 %out_idx
  store i32 %s3, ptr %out, align 4
  ret void
}

; Case B: zext(or disjoint) - same x86 vectorization shape as add nuw.
define void @test_zext_or_disjoint(ptr %base, i32 %idx) {
; CHECK-LABEL: define void @test_zext_or_disjoint(
; CHECK-SAME: ptr [[BASE:%.*]], i32 [[IDX:%.*]]) {
; CHECK-NEXT:    [[I0:%.*]] = zext i32 [[IDX]] to i64
; CHECK-NEXT:    [[G0:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I0]]
; CHECK-NEXT:    [[TMP1:%.*]] = load <3 x b32>, ptr [[G0]], align 4
; CHECK-NEXT:    [[V1:%.*]] = extractelement <3 x b32> [[TMP1]], i32 0
; CHECK-NEXT:    [[V01:%.*]] = bitcast b32 [[V1]] to i32
; CHECK-NEXT:    [[V13:%.*]] = extractelement <3 x b32> [[TMP1]], i32 1
; CHECK-NEXT:    [[V12:%.*]] = bitcast b32 [[V13]] to i32
; CHECK-NEXT:    [[V24:%.*]] = extractelement <3 x b32> [[TMP1]], i32 2
; CHECK-NEXT:    [[V23:%.*]] = bitcast b32 [[V24]] to i32
; CHECK-NEXT:    [[B3:%.*]] = or disjoint i32 [[IDX]], 3
; CHECK-NEXT:    [[I3:%.*]] = zext i32 [[B3]] to i64
; CHECK-NEXT:    [[G3:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I3]]
; CHECK-NEXT:    [[V3:%.*]] = load i32, ptr [[G3]], align 4
; CHECK-NEXT:    [[S:%.*]] = add i32 [[V01]], [[V12]]
; CHECK-NEXT:    [[S2:%.*]] = add i32 [[S]], [[V23]]
; CHECK-NEXT:    [[S3:%.*]] = add i32 [[S2]], [[V3]]
; CHECK-NEXT:    [[OUT_IDX:%.*]] = sext i32 [[S3]] to i64
; CHECK-NEXT:    [[OUT:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[OUT_IDX]]
; CHECK-NEXT:    store i32 [[S3]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  %i0 = zext i32 %idx to i64
  %g0 = getelementptr inbounds i32, ptr %base, i64 %i0
  %v0 = load i32, ptr %g0, align 4

  %b1 = or disjoint i32 %idx, 1
  %i1 = zext i32 %b1 to i64
  %g1 = getelementptr inbounds i32, ptr %base, i64 %i1
  %v1 = load i32, ptr %g1, align 4

  %b2 = or disjoint i32 %idx, 2
  %i2 = zext i32 %b2 to i64
  %g2 = getelementptr inbounds i32, ptr %base, i64 %i2
  %v2 = load i32, ptr %g2, align 4

  %b3 = or disjoint i32 %idx, 3
  %i3 = zext i32 %b3 to i64
  %g3 = getelementptr inbounds i32, ptr %base, i64 %i3
  %v3 = load i32, ptr %g3, align 4

  %s = add i32 %v0, %v1
  %s2 = add i32 %s, %v2
  %s3 = add i32 %s2, %v3
  %out_idx = sext i32 %s3 to i64
  %out = getelementptr inbounds i32, ptr %base, i64 %out_idx
  store i32 %s3, ptr %out, align 4
  ret void
}

; Plain or (not disjoint) - should NOT vectorize.
define void @test_zext_or_plain(ptr %base, i32 %idx) {
; CHECK-LABEL: define void @test_zext_or_plain(
; CHECK-SAME: ptr [[BASE:%.*]], i32 [[IDX:%.*]]) {
; CHECK-NEXT:    [[I0:%.*]] = zext i32 [[IDX]] to i64
; CHECK-NEXT:    [[G0:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I0]]
; CHECK-NEXT:    [[V0:%.*]] = load i32, ptr [[G0]], align 4
; CHECK-NEXT:    [[B1:%.*]] = or i32 [[IDX]], 1
; CHECK-NEXT:    [[I1:%.*]] = zext i32 [[B1]] to i64
; CHECK-NEXT:    [[G1:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I1]]
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[G1]], align 4
; CHECK-NEXT:    [[B2:%.*]] = or i32 [[IDX]], 2
; CHECK-NEXT:    [[I2:%.*]] = zext i32 [[B2]] to i64
; CHECK-NEXT:    [[G2:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I2]]
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[G2]], align 4
; CHECK-NEXT:    [[B3:%.*]] = or i32 [[IDX]], 3
; CHECK-NEXT:    [[I3:%.*]] = zext i32 [[B3]] to i64
; CHECK-NEXT:    [[G3:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[I3]]
; CHECK-NEXT:    [[V3:%.*]] = load i32, ptr [[G3]], align 4
; CHECK-NEXT:    [[S:%.*]] = add i32 [[V0]], [[V1]]
; CHECK-NEXT:    [[S2:%.*]] = add i32 [[S]], [[V2]]
; CHECK-NEXT:    [[S3:%.*]] = add i32 [[S2]], [[V3]]
; CHECK-NEXT:    [[OUT_IDX:%.*]] = sext i32 [[S3]] to i64
; CHECK-NEXT:    [[OUT:%.*]] = getelementptr inbounds i32, ptr [[BASE]], i64 [[OUT_IDX]]
; CHECK-NEXT:    store i32 [[S3]], ptr [[OUT]], align 4
; CHECK-NEXT:    ret void
;
  %i0 = zext i32 %idx to i64
  %g0 = getelementptr inbounds i32, ptr %base, i64 %i0
  %v0 = load i32, ptr %g0, align 4

  %b1 = or i32 %idx, 1
  %i1 = zext i32 %b1 to i64
  %g1 = getelementptr inbounds i32, ptr %base, i64 %i1
  %v1 = load i32, ptr %g1, align 4

  %b2 = or i32 %idx, 2
  %i2 = zext i32 %b2 to i64
  %g2 = getelementptr inbounds i32, ptr %base, i64 %i2
  %v2 = load i32, ptr %g2, align 4

  %b3 = or i32 %idx, 3
  %i3 = zext i32 %b3 to i64
  %g3 = getelementptr inbounds i32, ptr %base, i64 %i3
  %v3 = load i32, ptr %g3, align 4

  %s = add i32 %v0, %v1
  %s2 = add i32 %s, %v2
  %s3 = add i32 %s2, %v3
  %out_idx = sext i32 %s3 to i64
  %out = getelementptr inbounds i32, ptr %base, i64 %out_idx
  store i32 %s3, ptr %out, align 4
  ret void
}
