; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=x86_64-unknown-linux-gnu -passes=load-store-vectorizer -S -o - %s | FileCheck %s

define void @test(ptr %ptr) {
; CHECK-LABEL: define void @test(
; CHECK-SAME: ptr [[PTR:%.*]]) {
; CHECK-NEXT:    [[TMP1:%.*]] = load <2 x b32>, ptr [[PTR]], align 8
; CHECK-NEXT:    [[LD01:%.*]] = extractelement <2 x b32> [[TMP1]], i32 0
; CHECK-NEXT:    [[TMP2:%.*]] = bitcast b32 [[LD01]] to i32
; CHECK-NEXT:    [[LD12:%.*]] = extractelement <2 x b32> [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP3:%.*]] = bitcast b32 [[LD12]] to i32
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds i8, ptr [[PTR]], i32 8
; CHECK-NEXT:    [[TMP4:%.*]] = load <2 x b32>, ptr [[GEP2]], align 8
; CHECK-NEXT:    [[LD23:%.*]] = shufflevector <2 x b32> [[TMP4]], <2 x b32> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[TMP5:%.*]] = bitcast <2 x b32> [[LD23]] to <2 x i32>
; CHECK-NEXT:    [[LD34:%.*]] = extractelement <2 x b32> [[TMP4]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = bitcast b32 [[LD34]] to i32
; CHECK-NEXT:    ret void
;
  %ld0 = load i32, ptr %ptr, align 8
  %gep1 = getelementptr inbounds i8, ptr %ptr, i32 4
  %ld1 = load i32, ptr %gep1, align 4
  %gep2 = getelementptr inbounds i8, ptr %ptr, i32 8
  %ld2 = load <2 x i32>, ptr %gep2, align 8
  %gep3 = getelementptr inbounds i8, ptr %ptr, i32 8
  %ld3 = load i32, ptr %gep3, align 4
  ret void
}

