// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple s390x-linux-gnu -O1 -emit-llvm %s -o - | FileCheck %s
//
// Test __atomic_is_lock_free() and __atomic_always_lock_free() for __int128
// with 16 byte alignment.

#include <stdatomic.h>
#include <stdint.h>

__int128 Int128_Al16 __attribute__((aligned(16)));

// CHECK-LABEL: @fun_PtrAl16_is_lock_free(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CALL:%.*]] = tail call zeroext i1 @__atomic_is_lock_free(i64 noundef 16, ptr noundef nonnull @Int128_Al16) #[[ATTR2]]
// CHECK-NEXT:    ret i1 [[CALL]]
//
_Bool fun_PtrAl16_is_lock_free() {
  return __atomic_is_lock_free(16, &Int128_Al16);
}

// CHECK-LABEL: @fun_PtrAl16_always_lock_free(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i1 false
//
_Bool fun_PtrAl16_always_lock_free() {
  return __atomic_always_lock_free(16, &Int128_Al16);
}

// Also test these with a 16 byte size and null-pointer.
// CHECK-LABEL: @fun_noptr_is_lock_free(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i1 true
//
_Bool fun_noptr_is_lock_free() {
  return __atomic_is_lock_free(16, 0);
}

// CHECK-LABEL: @fun_noptr_always_lock_free(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i1 true
//
_Bool fun_noptr_always_lock_free() {
  return __atomic_always_lock_free(16, 0);
}

// Also test __c11_atomic_is_lock_free() with a 16 byte size.
// CHECK-LABEL: @fun_c11_is_lock_free(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    ret i1 true
//
_Bool fun_c11_is_lock_free() {
  return __c11_atomic_is_lock_free(16);
}

