; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes='loop-interchange' -cache-line-size=64 < %s | FileCheck %s

;  // Loop nest with multiple loops at same depth
;    for (i = 0; i < 64; i++)
;    {
;      for (j = 0; j < 64; j++)
;        {
;          #pragma clang loop unroll(disable)
;          for (r = 0; r < 64; r++)
;            {
;              C[j][r] = B[j][r] + i;
;            }
;        }
;
;      for (k = 0; k < 64; k++)
;        {
;          #pragma clang loop unroll(disable)
;          for (l = 0; l < 64; l++)
;            {
;              A[l][k] = A[l][k] + 1;
;            }
;        }
;    }

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnueabi"

@B = dso_local local_unnamed_addr global [64 x [64 x i32]] zeroinitializer, align 4
@C = dso_local local_unnamed_addr global [64 x [64 x i32]] zeroinitializer, align 4
@A = dso_local local_unnamed_addr global [64 x [64 x i32]] zeroinitializer, align 4

; Function Attrs: nofree norecurse nosync nounwind memory(readwrite, argmem: none, inaccessiblemem: none, target_mem0: none, target_mem1: none) uwtable
define dso_local void @foo(i32 noundef %n, i32 noundef %m, i32 noundef %p) local_unnamed_addr #0 {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_COND1_PREHEADER:%.*]]
; CHECK:       for.cond1.preheader:
; CHECK-NEXT:    [[I_058:%.*]] = phi i32 [ 0, [[ENTRY:%.*]] ], [ [[INC38:%.*]], [[FOR_INC37:%.*]] ]
; CHECK-NEXT:    br label [[FOR_COND4_PREHEADER:%.*]]
; CHECK:       for.cond4.preheader:
; CHECK-NEXT:    [[INDVARS_IV60:%.*]] = phi i64 [ 0, [[FOR_COND1_PREHEADER]] ], [ [[INDVARS_IV_NEXT61:%.*]], [[FOR_INC13:%.*]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [64 x i32], ptr @B, i64 [[INDVARS_IV60]]
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds nuw [64 x i32], ptr @C, i64 [[INDVARS_IV60]]
; CHECK-NEXT:    br label [[FOR_BODY6:%.*]]
; CHECK:       for.body6:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, [[FOR_COND4_PREHEADER]] ], [ [[INDVARS_IV_NEXT:%.*]], [[FOR_BODY6]] ]
; CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds nuw i32, ptr [[ARRAYIDX]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[ARRAYIDX8]], align 4, !tbaa [[TBAA5:![0-9]+]]
; CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[I_058]]
; CHECK-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds nuw i32, ptr [[ARRAYIDX10]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    store i32 [[ADD]], ptr [[ARRAYIDX12]], align 4, !tbaa [[TBAA5]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 64
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label [[FOR_INC13]], label [[FOR_BODY6]], !llvm.loop [[LOOP9:![0-9]+]]
; CHECK:       for.inc13:
; CHECK-NEXT:    [[INDVARS_IV_NEXT61]] = add nuw nsw i64 [[INDVARS_IV60]], 1
; CHECK-NEXT:    [[EXITCOND63_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT61]], 64
; CHECK-NEXT:    br i1 [[EXITCOND63_NOT]], label [[FOR_BODY21_PREHEADER:%.*]], label [[FOR_COND4_PREHEADER]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       for.cond19.preheader.preheader:
; CHECK-NEXT:    br label [[FOR_COND19_PREHEADER:%.*]]
; CHECK:       for.cond19.preheader:
; CHECK-NEXT:    [[INDVARS_IV68:%.*]] = phi i64 [ [[INDVARS_IV_NEXT69:%.*]], [[FOR_INC34:%.*]] ], [ 0, [[FOR_COND19_PREHEADER_PREHEADER:%.*]] ]
; CHECK-NEXT:    [[INVARIANT_GEP:%.*]] = getelementptr inbounds nuw i32, ptr @A, i64 [[INDVARS_IV68]]
; CHECK-NEXT:    br label [[FOR_BODY21_SPLIT1:%.*]]
; CHECK:       for.body21.preheader:
; CHECK-NEXT:    br label [[FOR_BODY21:%.*]]
; CHECK:       for.body21:
; CHECK-NEXT:    [[INDVARS_IV64:%.*]] = phi i64 [ [[TMP2:%.*]], [[FOR_BODY21_SPLIT:%.*]] ], [ 0, [[FOR_BODY21_PREHEADER]] ]
; CHECK-NEXT:    br label [[FOR_COND19_PREHEADER_PREHEADER]]
; CHECK:       for.body21.split1:
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds nuw [64 x i32], ptr [[INVARIANT_GEP]], i64 [[INDVARS_IV64]]
; CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[GEP]], align 4, !tbaa [[TBAA5]]
; CHECK-NEXT:    [[ADD26:%.*]] = add nsw i32 [[TMP1]], 1
; CHECK-NEXT:    store i32 [[ADD26]], ptr [[GEP]], align 4, !tbaa [[TBAA5]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT65:%.*]] = add nuw nsw i64 [[INDVARS_IV64]], 1
; CHECK-NEXT:    [[EXITCOND67_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT65]], 64
; CHECK-NEXT:    br label [[FOR_INC34]]
; CHECK:       for.body21.split:
; CHECK-NEXT:    [[TMP2]] = add nuw nsw i64 [[INDVARS_IV64]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[TMP2]], 64
; CHECK-NEXT:    br i1 [[TMP3]], label [[FOR_INC37]], label [[FOR_BODY21]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       for.inc34:
; CHECK-NEXT:    [[INDVARS_IV_NEXT69]] = add nuw nsw i64 [[INDVARS_IV68]], 1
; CHECK-NEXT:    [[EXITCOND71_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT69]], 64
; CHECK-NEXT:    br i1 [[EXITCOND71_NOT]], label [[FOR_BODY21_SPLIT]], label [[FOR_COND19_PREHEADER]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       for.inc37:
; CHECK-NEXT:    [[INC38]] = add nuw nsw i32 [[I_058]], 1
; CHECK-NEXT:    [[EXITCOND72_NOT:%.*]] = icmp eq i32 [[INC38]], 64
; CHECK-NEXT:    br i1 [[EXITCOND72_NOT]], label [[FOR_END39:%.*]], label [[FOR_COND1_PREHEADER]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       for.end39:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.cond1.preheader

for.cond1.preheader:                              ; preds = %entry, %for.inc37
  %i.058 = phi i32 [ 0, %entry ], [ %inc38, %for.inc37 ]
  br label %for.cond4.preheader

for.cond4.preheader:                              ; preds = %for.cond1.preheader, %for.inc13
  %indvars.iv60 = phi i64 [ 0, %for.cond1.preheader ], [ %indvars.iv.next61, %for.inc13 ]
  %arrayidx = getelementptr inbounds nuw [64 x i32], ptr @B, i64 %indvars.iv60
  %arrayidx10 = getelementptr inbounds nuw [64 x i32], ptr @C, i64 %indvars.iv60
  br label %for.body6

for.body6:                                        ; preds = %for.cond4.preheader, %for.body6
  %indvars.iv = phi i64 [ 0, %for.cond4.preheader ], [ %indvars.iv.next, %for.body6 ]
  %arrayidx8 = getelementptr inbounds nuw i32, ptr %arrayidx, i64 %indvars.iv
  %0 = load i32, ptr %arrayidx8, align 4, !tbaa !5
  %add = add nsw i32 %0, %i.058
  %arrayidx12 = getelementptr inbounds nuw i32, ptr %arrayidx10, i64 %indvars.iv
  store i32 %add, ptr %arrayidx12, align 4, !tbaa !5
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 64
  br i1 %exitcond.not, label %for.inc13, label %for.body6, !llvm.loop !9

for.inc13:                                        ; preds = %for.body6
  %indvars.iv.next61 = add nuw nsw i64 %indvars.iv60, 1
  %exitcond63.not = icmp eq i64 %indvars.iv.next61, 64
  br i1 %exitcond63.not, label %for.cond19.preheader.preheader, label %for.cond4.preheader, !llvm.loop !12

for.cond19.preheader.preheader:                   ; preds = %for.inc13
  br label %for.cond19.preheader

for.cond19.preheader:                             ; preds = %for.cond19.preheader.preheader, %for.inc34
  %indvars.iv68 = phi i64 [ %indvars.iv.next69, %for.inc34 ], [ 0, %for.cond19.preheader.preheader ]
  %invariant.gep = getelementptr inbounds nuw i32, ptr @A, i64 %indvars.iv68
  br label %for.body21

for.body21:                                       ; preds = %for.cond19.preheader, %for.body21
  %indvars.iv64 = phi i64 [ 0, %for.cond19.preheader ], [ %indvars.iv.next65, %for.body21 ]
  %gep = getelementptr inbounds nuw [64 x i32], ptr %invariant.gep, i64 %indvars.iv64
  %1 = load i32, ptr %gep, align 4, !tbaa !5
  %add26 = add nsw i32 %1, 1
  store i32 %add26, ptr %gep, align 4, !tbaa !5
  %indvars.iv.next65 = add nuw nsw i64 %indvars.iv64, 1
  %exitcond67.not = icmp eq i64 %indvars.iv.next65, 64
  br i1 %exitcond67.not, label %for.inc34, label %for.body21, !llvm.loop !13

for.inc34:                                        ; preds = %for.body21
  %indvars.iv.next69 = add nuw nsw i64 %indvars.iv68, 1
  %exitcond71.not = icmp eq i64 %indvars.iv.next69, 64
  br i1 %exitcond71.not, label %for.inc37, label %for.cond19.preheader, !llvm.loop !14

for.inc37:                                        ; preds = %for.inc34
  %inc38 = add nuw nsw i32 %i.058, 1
  %exitcond72.not = icmp eq i32 %inc38, 64
  br i1 %exitcond72.not, label %for.end39, label %for.cond1.preheader, !llvm.loop !15

for.end39:                                        ; preds = %for.inc37
  ret void
}

attributes #0 = { nofree norecurse nosync nounwind memory(readwrite, argmem: none, inaccessiblemem: none, target_mem0: none, target_mem1: none) uwtable "frame-pointer"="non-leaf-no-reserve" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="generic" "target-features"="+fp-armv8,+neon,+v8a,-fmv" }

!llvm.module.flags = !{!0, !1, !2, !3}
!llvm.ident = !{!4}
!llvm.errno.tbaa = !{!5}

!0 = !{i32 8, !"PIC Level", i32 2}
!1 = !{i32 7, !"PIE Level", i32 2}
!2 = !{i32 7, !"uwtable", i32 2}
!3 = !{i32 7, !"frame-pointer", i32 4}
!4 = !{!"clang version 23.0.0git (ssh://git-hexagon-lv.quicinc.com:29418/llvm/llvm-project 0b3252c0b4f1cb5394a6db1eba0f70190fc88827)"}
!5 = !{!6, !6, i64 0}
!6 = !{!"int", !7, i64 0}
!7 = !{!"omnipotent char", !8, i64 0}
!8 = !{!"Simple C/C++ TBAA"}
!9 = distinct !{!9, !10, !11}
!10 = !{!"llvm.loop.mustprogress"}
!11 = !{!"llvm.loop.unroll.disable"}
!12 = distinct !{!12, !10}
!13 = distinct !{!13, !10, !11}
!14 = distinct !{!14, !10}
!15 = distinct !{!15, !10}
