; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=loop-interchange -S -loop-interchange-profitabilities=ignore -loop-interchange-max-meminstr-count=1 \
; RUN:          -loop-interchange-max-meminstr-squared-ratio=1 | FileCheck %s --check-prefixes=CHECK,CHECK-SQUARED-RATIO-1
; RUN: opt < %s -passes=loop-interchange -S -loop-interchange-profitabilities=ignore -loop-interchange-max-meminstr-count=1 \
; RUN:          -loop-interchange-max-meminstr-squared-ratio=100 | FileCheck %s --check-prefixes=CHECK,CHECK-SQUARED-RATIO-100

define void @f(ptr noalias %A) {
; CHECK-SQUARED-RATIO-1-LABEL: define void @f(
; CHECK-SQUARED-RATIO-1-SAME: ptr noalias [[A:%.*]]) {
; CHECK-SQUARED-RATIO-1-NEXT:  [[ENTRY:.*]]:
; CHECK-SQUARED-RATIO-1-NEXT:    br label %[[LOOP_I_HEADER:.*]]
; CHECK-SQUARED-RATIO-1:       [[LOOP_I_HEADER]]:
; CHECK-SQUARED-RATIO-1-NEXT:    [[I:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[I_INC:%.*]], %[[LOOP_I_LATCH:.*]] ]
; CHECK-SQUARED-RATIO-1-NEXT:    br label %[[LOOP_J:.*]]
; CHECK-SQUARED-RATIO-1:       [[LOOP_J]]:
; CHECK-SQUARED-RATIO-1-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[LOOP_I_HEADER]] ], [ [[J_INC:%.*]], %[[LOOP_J]] ]
; CHECK-SQUARED-RATIO-1-NEXT:    [[GEP:%.*]] = getelementptr [10 x i8], ptr [[A]], i64 [[J]], i64 [[I]]
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-1-NEXT:    [[J_INC]] = add i64 [[J]], 1
; CHECK-SQUARED-RATIO-1-NEXT:    [[EC_J:%.*]] = icmp eq i64 [[J_INC]], 10
; CHECK-SQUARED-RATIO-1-NEXT:    br i1 [[EC_J]], label %[[LOOP_I_LATCH]], label %[[LOOP_J]]
; CHECK-SQUARED-RATIO-1:       [[LOOP_I_LATCH]]:
; CHECK-SQUARED-RATIO-1-NEXT:    [[I_INC]] = add i64 [[I]], 1
; CHECK-SQUARED-RATIO-1-NEXT:    [[EC_I:%.*]] = icmp eq i64 [[I_INC]], 10
; CHECK-SQUARED-RATIO-1-NEXT:    br i1 [[EC_I]], label %[[EXIT:.*]], label %[[LOOP_I_HEADER]]
; CHECK-SQUARED-RATIO-1:       [[EXIT]]:
; CHECK-SQUARED-RATIO-1-NEXT:    ret void
;
; CHECK-SQUARED-RATIO-100-LABEL: define void @f(
; CHECK-SQUARED-RATIO-100-SAME: ptr noalias [[A:%.*]]) {
; CHECK-SQUARED-RATIO-100-NEXT:  [[ENTRY:.*:]]
; CHECK-SQUARED-RATIO-100-NEXT:    br label %[[LOOP_J_PREHEADER:.*]]
; CHECK-SQUARED-RATIO-100:       [[LOOP_I_HEADER_PREHEADER:.*]]:
; CHECK-SQUARED-RATIO-100-NEXT:    br label %[[LOOP_I_HEADER:.*]]
; CHECK-SQUARED-RATIO-100:       [[LOOP_I_HEADER]]:
; CHECK-SQUARED-RATIO-100-NEXT:    [[I:%.*]] = phi i64 [ [[I_INC:%.*]], %[[LOOP_I_LATCH:.*]] ], [ 0, %[[LOOP_I_HEADER_PREHEADER]] ]
; CHECK-SQUARED-RATIO-100-NEXT:    br label %[[LOOP_J_SPLIT1:.*]]
; CHECK-SQUARED-RATIO-100:       [[LOOP_J_PREHEADER]]:
; CHECK-SQUARED-RATIO-100-NEXT:    br label %[[LOOP_J:.*]]
; CHECK-SQUARED-RATIO-100:       [[LOOP_J]]:
; CHECK-SQUARED-RATIO-100-NEXT:    [[J:%.*]] = phi i64 [ [[TMP0:%.*]], %[[LOOP_J_SPLIT:.*]] ], [ 0, %[[LOOP_J_PREHEADER]] ]
; CHECK-SQUARED-RATIO-100-NEXT:    br label %[[LOOP_I_HEADER_PREHEADER]]
; CHECK-SQUARED-RATIO-100:       [[LOOP_J_SPLIT1]]:
; CHECK-SQUARED-RATIO-100-NEXT:    [[GEP:%.*]] = getelementptr [10 x i8], ptr [[A]], i64 [[J]], i64 [[I]]
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    store i8 0, ptr [[GEP]], align 1
; CHECK-SQUARED-RATIO-100-NEXT:    [[J_INC:%.*]] = add i64 [[J]], 1
; CHECK-SQUARED-RATIO-100-NEXT:    [[EC_J:%.*]] = icmp eq i64 [[J_INC]], 10
; CHECK-SQUARED-RATIO-100-NEXT:    br label %[[LOOP_I_LATCH]]
; CHECK-SQUARED-RATIO-100:       [[LOOP_J_SPLIT]]:
; CHECK-SQUARED-RATIO-100-NEXT:    [[TMP0]] = add i64 [[J]], 1
; CHECK-SQUARED-RATIO-100-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[TMP0]], 10
; CHECK-SQUARED-RATIO-100-NEXT:    br i1 [[TMP1]], label %[[EXIT:.*]], label %[[LOOP_J]]
; CHECK-SQUARED-RATIO-100:       [[LOOP_I_LATCH]]:
; CHECK-SQUARED-RATIO-100-NEXT:    [[I_INC]] = add i64 [[I]], 1
; CHECK-SQUARED-RATIO-100-NEXT:    [[EC_I:%.*]] = icmp eq i64 [[I_INC]], 10
; CHECK-SQUARED-RATIO-100-NEXT:    br i1 [[EC_I]], label %[[LOOP_J_SPLIT]], label %[[LOOP_I_HEADER]]
; CHECK-SQUARED-RATIO-100:       [[EXIT]]:
; CHECK-SQUARED-RATIO-100-NEXT:    ret void
;
entry:
  br label %loop.i.header

loop.i.header:
  %i = phi i64 [ 0, %entry ], [ %i.inc, %loop.i.latch ]
  br label %loop.j

loop.j:
  %j = phi i64 [ 0, %loop.i.header ], [ %j.inc, %loop.j ]
  %gep = getelementptr [10 x i8], ptr %A, i64 %j, i64 %i
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  store i8 0, ptr %gep
  %j.inc = add i64 %j, 1
  %ec.j = icmp eq i64 %j.inc, 10
  br i1 %ec.j, label %loop.i.latch, label %loop.j

loop.i.latch:
  %i.inc = add i64 %i, 1
  %ec.i = icmp eq i64 %i.inc, 10
  br i1 %ec.i, label %exit, label %loop.i.header

exit:
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
