; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=loop-interchange -loop-interchange-profitabilities=ignore -S | FileCheck %s

; This is a test for the assert that checks that we only replace phis iff the
; phi-uses are in the loop nest exit or the incoming value is defined in the
; inner header. We only want to check this when the user is a phi, which does
; not always need to be the case.

define i64 @non_phi_lcssa_phi_user(ptr %A) {
; CHECK-LABEL: define i64 @non_phi_lcssa_phi_user(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[INNER_PREHEADER:.*]]
; CHECK:       [[OUTER_HEADER_PREHEADER:.*]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER:.*]]
; CHECK:       [[OUTER_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[I_NEXT:%.*]], %[[OUTER_LATCH:.*]] ], [ 0, %[[OUTER_HEADER_PREHEADER]] ]
; CHECK-NEXT:    br label %[[INNER_SPLIT1:.*]]
; CHECK:       [[INNER_PREHEADER]]:
; CHECK-NEXT:    br label %[[INNER:.*]]
; CHECK:       [[INNER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ [[TMP1:%.*]], %[[INNER_SPLIT:.*]] ], [ 0, %[[INNER_PREHEADER]] ]
; CHECK-NEXT:    br label %[[OUTER_HEADER_PREHEADER]]
; CHECK:       [[INNER_SPLIT1]]:
; CHECK-NEXT:    [[PTR:%.*]] = getelementptr inbounds [100 x i32], ptr [[A]], i64 [[J]], i64 [[I]]
; CHECK-NEXT:    store i32 0, ptr [[PTR]], align 4
; CHECK-NEXT:    [[J_NEXT:%.*]] = add i64 [[J]], 1
; CHECK-NEXT:    [[EXITCOND_INNER:%.*]] = icmp eq i64 [[J]], 99
; CHECK-NEXT:    br label %[[INNER_EXIT:.*]]
; CHECK:       [[INNER_SPLIT]]:
; CHECK-NEXT:    [[TMP0:%.*]] = phi i64 [ [[USE_J:%.*]], %[[OUTER_LATCH]] ]
; CHECK-NEXT:    [[TMP1]] = add i64 [[J]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[J]], 99
; CHECK-NEXT:    br i1 [[TMP2]], label %[[EXIT:.*]], label %[[INNER]]
; CHECK:       [[INNER_EXIT]]:
; CHECK-NEXT:    br label %[[OUTER_LATCH]]
; CHECK:       [[OUTER_LATCH]]:
; CHECK-NEXT:    [[USE_J]] = add i64 [[J]], 1
; CHECK-NEXT:    [[I_NEXT]] = add i64 [[I]], 1
; CHECK-NEXT:    [[EXITCOND_OUTER:%.*]] = icmp eq i64 [[I]], 99
; CHECK-NEXT:    br i1 [[EXITCOND_OUTER]], label %[[INNER_SPLIT]], label %[[OUTER_HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[RESULT:%.*]] = phi i64 [ [[TMP0]], %[[INNER_SPLIT]] ]
; CHECK-NEXT:    ret i64 [[RESULT]]
;
entry:
  br label %outer.header

outer.header:
  %i = phi i64 [ 0, %entry ], [ %i.next, %outer.latch ]
  br label %inner

inner:
  %j = phi i64 [ 0, %outer.header ], [ %j.next, %inner ]
  %ptr = getelementptr inbounds [100 x i32], ptr %A, i64 %j, i64 %i
  store i32 0, ptr %ptr
  %j.next = add i64 %j, 1
  %exitcond.inner = icmp eq i64 %j, 99
  br i1 %exitcond.inner, label %inner.exit, label %inner

inner.exit:
  %j.lcssa = phi i64 [ %j, %inner ]
  br label %outer.latch

outer.latch:
  %j.latch = phi i64 [ %j.lcssa, %inner.exit ]
  %use.j = add i64 %j.latch, 1
  %i.next = add i64 %i, 1
  %exitcond.outer = icmp eq i64 %i, 99
  br i1 %exitcond.outer, label %exit, label %outer.header

exit:
  %result = phi i64 [ %use.j, %outer.latch ]
  ret i64 %result
}
