; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=loop-interchange -loop-interchange-profitabilities=ignore -cache-line-size=64 -verify-dom-info -verify-loop-info -verify-scev -verify-loop-lcssa -S | FileCheck %s

; Test case for issue: https://github.com/llvm/llvm-project/issues/163954

define void @test() {
; CHECK-LABEL: define void @test() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[OUTER_HEADER:.*]]
; CHECK:       [[OUTER_HEADER]]:
; CHECK-NEXT:    [[I:%.*]] = phi i8 [ 0, %[[ENTRY]] ], [ [[DOTLCSSA:%.*]], %[[OUTER_LATCH:.*]] ]
; CHECK-NEXT:    br label %[[INNER_HEADER:.*]]
; CHECK:       [[INNER_HEADER]]:
; CHECK-NEXT:    [[J:%.*]] = phi i64 [ 0, %[[OUTER_HEADER]] ], [ [[J_NEXT:%.*]], %[[INNER_LATCH:.*]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = phi i8 [ [[I]], %[[OUTER_HEADER]] ], [ [[TMP1:%.*]], %[[INNER_LATCH]] ]
; CHECK-NEXT:    br label %[[INNER_BODY:.*]]
; CHECK:       [[INNER_BODY]]:
; CHECK-NEXT:    br i1 true, label %[[INNER_LATCH]], label %[[INNER_BODY]]
; CHECK:       [[INNER_LATCH]]:
; CHECK-NEXT:    [[TMP1]] = or i8 [[TMP0]], 0
; CHECK-NEXT:    [[J_NEXT]] = add i64 [[J]], 1
; CHECK-NEXT:    br i1 true, label %[[OUTER_LATCH]], label %[[INNER_HEADER]]
; CHECK:       [[OUTER_LATCH]]:
; CHECK-NEXT:    [[DOTLCSSA]] = phi i8 [ [[TMP1]], %[[INNER_LATCH]] ]
; CHECK-NEXT:    br i1 true, label %[[EXIT:.*]], label %[[OUTER_HEADER]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %outer.header

outer.header:
  %i = phi i8 [ 0, %entry ], [ %1, %outer.latch ]
  br label %inner.header

inner.header:
  %j = phi i64 [ 0, %outer.header ], [ %j.next, %inner.latch ]
  %0 = phi i8 [ %i, %outer.header ], [ %1, %inner.latch ]
  br label %inner.body

inner.body:
  br i1 true, label %inner.latch, label %inner.body   ; another (self) loop, but never taken

inner.latch:
  %1 = or i8 %0, 0
  %j.next = add i64 %j, 1
  br i1 true, label %outer.latch, label %inner.header

outer.latch:
  br i1 true, label %exit, label %outer.header

exit:
  ret void
}
