// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// REQUIRES: riscv-registered-target
// RUN: %clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-llvm %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefixes=CHECK-RV64,CHECK-RV64-OGCG %s
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-llvm -fclangir %s -o - | \
// RUN:   opt -S -passes=mem2reg | \
// RUN:   FileCheck --check-prefix=CHECK-RV64 %s %}
// RUN: %if cir-enabled %{%clang_cc1 -triple riscv64 -target-feature +v -disable-O0-optnone -emit-cir -fclangir %s -o - | \
// RUN:   FileCheck --check-prefix=CIR %s %}

#include <riscv_vector.h>

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8mf8_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[1] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8mf8_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv1i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8mf8_i8m1_tu(vint8m1_t maskedoff, vint8mf8_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8mf8_i8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8mf4_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[2] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8mf4_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv2i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8mf4_i8m1_tu(vint8m1_t maskedoff, vint8mf4_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8mf4_i8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8mf2_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[4] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8mf2_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv4i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8mf2_i8m1_tu(vint8m1_t maskedoff, vint8mf2_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8mf2_i8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m1_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m1_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m1_i8m1_tu(vint8m1_t maskedoff, vint8m1_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m1_i8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m2_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[16] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m2_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv16i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m2_i8m1_tu(vint8m1_t maskedoff, vint8m2_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m2_i8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m4_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[32] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m4_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv32i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m4_i8m1_tu(vint8m1_t maskedoff, vint8m4_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m4_i8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m8_i8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[64] x !s8i>, !cir.vector<[8] x !s8i>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m8_i8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv64i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m8_i8m1_tu(vint8m1_t maskedoff, vint8m8_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m8_i8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16mf4_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[1] x !s16i>, !cir.vector<[4] x !s16i>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16mf4_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv1i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16mf4_i16m1_tu(vint16m1_t maskedoff, vint16mf4_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16mf4_i16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16mf2_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[2] x !s16i>, !cir.vector<[4] x !s16i>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16mf2_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv2i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16mf2_i16m1_tu(vint16m1_t maskedoff, vint16mf2_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16mf2_i16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m1_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m1_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m1_i16m1_tu(vint16m1_t maskedoff, vint16m1_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m1_i16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m2_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[8] x !s16i>, !cir.vector<[4] x !s16i>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m2_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv8i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m2_i16m1_tu(vint16m1_t maskedoff, vint16m2_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m2_i16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m4_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[16] x !s16i>, !cir.vector<[4] x !s16i>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m4_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv16i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m4_i16m1_tu(vint16m1_t maskedoff, vint16m4_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m4_i16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m8_i16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[32] x !s16i>, !cir.vector<[4] x !s16i>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m8_i16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv32i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m8_i16m1_tu(vint16m1_t maskedoff, vint16m8_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m8_i16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32mf2_i32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[1] x !s32i>, !cir.vector<[2] x !s32i>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32mf2_i32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv1i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32mf2_i32m1_tu(vint32m1_t maskedoff, vint32mf2_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32mf2_i32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m1_i32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m1_i32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m1_i32m1_tu(vint32m1_t maskedoff, vint32m1_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m1_i32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m2_i32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[4] x !s32i>, !cir.vector<[2] x !s32i>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m2_i32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m2_i32m1_tu(vint32m1_t maskedoff, vint32m2_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m2_i32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m4_i32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[8] x !s32i>, !cir.vector<[2] x !s32i>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m4_i32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv8i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m4_i32m1_tu(vint32m1_t maskedoff, vint32m4_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m4_i32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m8_i32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[16] x !s32i>, !cir.vector<[2] x !s32i>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m8_i32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv16i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m8_i32m1_tu(vint32m1_t maskedoff, vint32m8_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m8_i32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m1_i64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m1_i64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m1_i64m1_tu(vint64m1_t maskedoff, vint64m1_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m1_i64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m2_i64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[2] x !s64i>, !cir.vector<[1] x !s64i>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m2_i64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv2i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m2_i64m1_tu(vint64m1_t maskedoff, vint64m2_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m2_i64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m4_i64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[4] x !s64i>, !cir.vector<[1] x !s64i>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m4_i64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv4i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m4_i64m1_tu(vint64m1_t maskedoff, vint64m4_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m4_i64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m8_i64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[8] x !s64i>, !cir.vector<[1] x !s64i>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m8_i64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv8i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m8_i64m1_tu(vint64m1_t maskedoff, vint64m8_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m8_i64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8mf8_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[1] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8mf8_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv1i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8mf8_u8m1_tu(vuint8m1_t maskedoff, vuint8mf8_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8mf8_u8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8mf4_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[2] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8mf4_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv2i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8mf4_u8m1_tu(vuint8m1_t maskedoff, vuint8mf4_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8mf4_u8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8mf2_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[4] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8mf2_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv4i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8mf2_u8m1_tu(vuint8m1_t maskedoff, vuint8mf2_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8mf2_u8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m1_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m1_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m1_u8m1_tu(vuint8m1_t maskedoff, vuint8m1_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m1_u8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m2_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[16] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m2_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv16i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m2_u8m1_tu(vuint8m1_t maskedoff, vuint8m2_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m2_u8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m4_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[32] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m4_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv32i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m4_u8m1_tu(vuint8m1_t maskedoff, vuint8m4_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m4_u8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m8_u8m1_tu(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[64] x !u8i>, !cir.vector<[8] x !u8i>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m8_u8m1_tu
// CHECK-RV64-SAME: (<vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.nxv8i8.nxv64i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m8_u8m1_tu(vuint8m1_t maskedoff, vuint8m8_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m8_u8m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16mf4_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[1] x !u16i>, !cir.vector<[4] x !u16i>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16mf4_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv1i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16mf4_u16m1_tu(vuint16m1_t maskedoff, vuint16mf4_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16mf4_u16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16mf2_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[2] x !u16i>, !cir.vector<[4] x !u16i>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16mf2_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv2i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16mf2_u16m1_tu(vuint16m1_t maskedoff, vuint16mf2_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16mf2_u16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m1_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m1_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m1_u16m1_tu(vuint16m1_t maskedoff, vuint16m1_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m1_u16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m2_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[8] x !u16i>, !cir.vector<[4] x !u16i>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m2_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv8i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m2_u16m1_tu(vuint16m1_t maskedoff, vuint16m2_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m2_u16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m4_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[16] x !u16i>, !cir.vector<[4] x !u16i>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m4_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv16i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m4_u16m1_tu(vuint16m1_t maskedoff, vuint16m4_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m4_u16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m8_u16m1_tu(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[32] x !u16i>, !cir.vector<[4] x !u16i>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m8_u16m1_tu
// CHECK-RV64-SAME: (<vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.nxv4i16.nxv32i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m8_u16m1_tu(vuint16m1_t maskedoff, vuint16m8_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m8_u16m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32mf2_u32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[1] x !u32i>, !cir.vector<[2] x !u32i>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32mf2_u32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv1i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32mf2_u32m1_tu(vuint32m1_t maskedoff, vuint32mf2_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32mf2_u32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m1_u32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m1_u32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m1_u32m1_tu(vuint32m1_t maskedoff, vuint32m1_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m1_u32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m2_u32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[4] x !u32i>, !cir.vector<[2] x !u32i>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m2_u32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m2_u32m1_tu(vuint32m1_t maskedoff, vuint32m2_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m2_u32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m4_u32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[8] x !u32i>, !cir.vector<[2] x !u32i>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m4_u32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv8i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m4_u32m1_tu(vuint32m1_t maskedoff, vuint32m4_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m4_u32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m8_u32m1_tu(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[16] x !u32i>, !cir.vector<[2] x !u32i>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m8_u32m1_tu
// CHECK-RV64-SAME: (<vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.nxv2i32.nxv16i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m8_u32m1_tu(vuint32m1_t maskedoff, vuint32m8_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m8_u32m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m1_u64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m1_u64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m1_u64m1_tu(vuint64m1_t maskedoff, vuint64m1_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m1_u64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m2_u64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[2] x !u64i>, !cir.vector<[1] x !u64i>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m2_u64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv2i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m2_u64m1_tu(vuint64m1_t maskedoff, vuint64m2_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m2_u64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m4_u64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[4] x !u64i>, !cir.vector<[1] x !u64i>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m4_u64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv4i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m4_u64m1_tu(vuint64m1_t maskedoff, vuint64m4_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m4_u64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m8_u64m1_tu(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[8] x !u64i>, !cir.vector<[1] x !u64i>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m8_u64m1_tu
// CHECK-RV64-SAME: (<vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.nxv1i64.nxv8i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m8_u64m1_tu(vuint64m1_t maskedoff, vuint64m8_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m8_u64m1_tu(maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8mf8_i8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[1] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8mf8_i8m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv1i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8mf8_i8m1_tum(vbool64_t mask, vint8m1_t maskedoff, vint8mf8_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8mf8_i8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8mf4_i8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[2] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8mf4_i8m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv2i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8mf4_i8m1_tum(vbool32_t mask, vint8m1_t maskedoff, vint8mf4_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8mf4_i8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8mf2_i8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[4] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8mf2_i8m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv4i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8mf2_i8m1_tum(vbool16_t mask, vint8m1_t maskedoff, vint8mf2_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8mf2_i8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m1_i8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m1_i8m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m1_i8m1_tum(vbool8_t mask, vint8m1_t maskedoff, vint8m1_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m1_i8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m2_i8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[16] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m2_i8m1_tum
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv16i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m2_i8m1_tum(vbool4_t mask, vint8m1_t maskedoff, vint8m2_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m2_i8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m4_i8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[32] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m4_i8m1_tum
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv32i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 32 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m4_i8m1_tum(vbool2_t mask, vint8m1_t maskedoff, vint8m4_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m4_i8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i8m8_i8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !s8i>, !cir.vector<[64] x !s8i>, !cir.vector<[8] x !s8i>, !cir.vector<[64] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !s8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_i8m8_i8m1_tum
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv64i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 64 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vint8m1_t test_vredsum_vs_i8m8_i8m1_tum(vbool1_t mask, vint8m1_t maskedoff, vint8m8_t vector, vint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i8m8_i8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16mf4_i16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[1] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16mf4_i16m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv1i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16mf4_i16m1_tum(vbool64_t mask, vint16m1_t maskedoff, vint16mf4_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16mf4_i16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16mf2_i16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[2] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16mf2_i16m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv2i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16mf2_i16m1_tum(vbool32_t mask, vint16m1_t maskedoff, vint16mf2_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16mf2_i16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m1_i16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m1_i16m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m1_i16m1_tum(vbool16_t mask, vint16m1_t maskedoff, vint16m1_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m1_i16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m2_i16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[8] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m2_i16m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv8i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m2_i16m1_tum(vbool8_t mask, vint16m1_t maskedoff, vint16m2_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m2_i16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m4_i16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[16] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m4_i16m1_tum
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv16i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m4_i16m1_tum(vbool4_t mask, vint16m1_t maskedoff, vint16m4_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m4_i16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i16m8_i16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !s16i>, !cir.vector<[32] x !s16i>, !cir.vector<[4] x !s16i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !s16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_i16m8_i16m1_tum
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv32i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 32 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vint16m1_t test_vredsum_vs_i16m8_i16m1_tum(vbool2_t mask, vint16m1_t maskedoff, vint16m8_t vector, vint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i16m8_i16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32mf2_i32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[1] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32mf2_i32m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv1i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32mf2_i32m1_tum(vbool64_t mask, vint32m1_t maskedoff, vint32mf2_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32mf2_i32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m1_i32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m1_i32m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m1_i32m1_tum(vbool32_t mask, vint32m1_t maskedoff, vint32m1_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m1_i32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m2_i32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[4] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m2_i32m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m2_i32m1_tum(vbool16_t mask, vint32m1_t maskedoff, vint32m2_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m2_i32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m4_i32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[8] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m4_i32m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv8i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m4_i32m1_tum(vbool8_t mask, vint32m1_t maskedoff, vint32m4_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m4_i32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i32m8_i32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !s32i>, !cir.vector<[16] x !s32i>, !cir.vector<[2] x !s32i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !s32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_i32m8_i32m1_tum
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv16i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vint32m1_t test_vredsum_vs_i32m8_i32m1_tum(vbool4_t mask, vint32m1_t maskedoff, vint32m8_t vector, vint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i32m8_i32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m1_i64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m1_i64m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m1_i64m1_tum(vbool64_t mask, vint64m1_t maskedoff, vint64m1_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m1_i64m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m2_i64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[2] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m2_i64m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv2i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m2_i64m1_tum(vbool32_t mask, vint64m1_t maskedoff, vint64m2_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m2_i64m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m4_i64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[4] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m4_i64m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv4i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m4_i64m1_tum(vbool16_t mask, vint64m1_t maskedoff, vint64m4_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m4_i64m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_i64m8_i64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !s64i>, !cir.vector<[8] x !s64i>, !cir.vector<[1] x !s64i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !s64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_i64m8_i64m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv8i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vint64m1_t test_vredsum_vs_i64m8_i64m1_tum(vbool8_t mask, vint64m1_t maskedoff, vint64m8_t vector, vint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_i64m8_i64m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8mf8_u8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[1] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8mf8_u8m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 1 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv1i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 1 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8mf8_u8m1_tum(vbool64_t mask, vuint8m1_t maskedoff, vuint8mf8_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8mf8_u8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8mf4_u8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[2] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8mf4_u8m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 2 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv2i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 2 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8mf4_u8m1_tum(vbool32_t mask, vuint8m1_t maskedoff, vuint8mf4_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8mf4_u8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8mf2_u8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[4] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8mf2_u8m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 4 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv4i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 4 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8mf2_u8m1_tum(vbool16_t mask, vuint8m1_t maskedoff, vuint8mf2_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8mf2_u8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m1_u8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m1_u8m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 8 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv8i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 8 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m1_u8m1_tum(vbool8_t mask, vuint8m1_t maskedoff, vuint8m1_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m1_u8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m2_u8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[16] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m2_u8m1_tum
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 16 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv16i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 16 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m2_u8m1_tum(vbool4_t mask, vuint8m1_t maskedoff, vuint8m2_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m2_u8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m4_u8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[32] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m4_u8m1_tum
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 32 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv32i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 32 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 32 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m4_u8m1_tum(vbool2_t mask, vuint8m1_t maskedoff, vuint8m4_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m4_u8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u8m8_u8m1_tum(
// CIR-SAME: -> !cir.vector<[8]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[8] x !u8i>, !cir.vector<[64] x !u8i>, !cir.vector<[8] x !u8i>, !cir.vector<[64] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[8] x !u8i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 8 x i8> @test_vredsum_vs_u8m8_u8m1_tum
// CHECK-RV64-SAME: (<vscale x 64 x i1> [[MASK:%.*]], <vscale x 8 x i8> [[MASKEDOFF:%.*]], <vscale x 64 x i8> [[VECTOR:%.*]], <vscale x 8 x i8> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 8 x i8> @llvm.riscv.vredsum.mask.nxv8i8.nxv64i8.i64(<vscale x 8 x i8> [[MASKEDOFF]], <vscale x 64 x i8> [[VECTOR]], <vscale x 8 x i8> [[SCALAR]], <vscale x 64 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 8 x i8> [[TMP0]]
//
vuint8m1_t test_vredsum_vs_u8m8_u8m1_tum(vbool1_t mask, vuint8m1_t maskedoff, vuint8m8_t vector, vuint8m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u8m8_u8m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16mf4_u16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[1] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16mf4_u16m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 1 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv1i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 1 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16mf4_u16m1_tum(vbool64_t mask, vuint16m1_t maskedoff, vuint16mf4_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16mf4_u16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16mf2_u16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[2] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16mf2_u16m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 2 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv2i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 2 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16mf2_u16m1_tum(vbool32_t mask, vuint16m1_t maskedoff, vuint16mf2_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16mf2_u16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m1_u16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m1_u16m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 4 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv4i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 4 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m1_u16m1_tum(vbool16_t mask, vuint16m1_t maskedoff, vuint16m1_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m1_u16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m2_u16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[8] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m2_u16m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 8 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv8i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 8 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m2_u16m1_tum(vbool8_t mask, vuint16m1_t maskedoff, vuint16m2_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m2_u16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m4_u16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[16] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m4_u16m1_tum
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 16 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv16i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 16 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m4_u16m1_tum(vbool4_t mask, vuint16m1_t maskedoff, vuint16m4_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m4_u16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u16m8_u16m1_tum(
// CIR-SAME: -> !cir.vector<[4]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[4] x !u16i>, !cir.vector<[32] x !u16i>, !cir.vector<[4] x !u16i>, !cir.vector<[32] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[4] x !u16i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 4 x i16> @test_vredsum_vs_u16m8_u16m1_tum
// CHECK-RV64-SAME: (<vscale x 32 x i1> [[MASK:%.*]], <vscale x 4 x i16> [[MASKEDOFF:%.*]], <vscale x 32 x i16> [[VECTOR:%.*]], <vscale x 4 x i16> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 4 x i16> @llvm.riscv.vredsum.mask.nxv4i16.nxv32i16.i64(<vscale x 4 x i16> [[MASKEDOFF]], <vscale x 32 x i16> [[VECTOR]], <vscale x 4 x i16> [[SCALAR]], <vscale x 32 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 4 x i16> [[TMP0]]
//
vuint16m1_t test_vredsum_vs_u16m8_u16m1_tum(vbool2_t mask, vuint16m1_t maskedoff, vuint16m8_t vector, vuint16m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u16m8_u16m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32mf2_u32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[1] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32mf2_u32m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 1 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv1i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 1 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32mf2_u32m1_tum(vbool64_t mask, vuint32m1_t maskedoff, vuint32mf2_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32mf2_u32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m1_u32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m1_u32m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 2 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv2i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 2 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m1_u32m1_tum(vbool32_t mask, vuint32m1_t maskedoff, vuint32m1_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m1_u32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m2_u32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[4] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m2_u32m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 4 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv4i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 4 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m2_u32m1_tum(vbool16_t mask, vuint32m1_t maskedoff, vuint32m2_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m2_u32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m4_u32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[8] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m4_u32m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 8 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv8i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 8 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m4_u32m1_tum(vbool8_t mask, vuint32m1_t maskedoff, vuint32m4_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m4_u32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u32m8_u32m1_tum(
// CIR-SAME: -> !cir.vector<[2]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[2] x !u32i>, !cir.vector<[16] x !u32i>, !cir.vector<[2] x !u32i>, !cir.vector<[16] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[2] x !u32i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 2 x i32> @test_vredsum_vs_u32m8_u32m1_tum
// CHECK-RV64-SAME: (<vscale x 16 x i1> [[MASK:%.*]], <vscale x 2 x i32> [[MASKEDOFF:%.*]], <vscale x 16 x i32> [[VECTOR:%.*]], <vscale x 2 x i32> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 2 x i32> @llvm.riscv.vredsum.mask.nxv2i32.nxv16i32.i64(<vscale x 2 x i32> [[MASKEDOFF]], <vscale x 16 x i32> [[VECTOR]], <vscale x 2 x i32> [[SCALAR]], <vscale x 16 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 2 x i32> [[TMP0]]
//
vuint32m1_t test_vredsum_vs_u32m8_u32m1_tum(vbool4_t mask, vuint32m1_t maskedoff, vuint32m8_t vector, vuint32m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u32m8_u32m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m1_u64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[1] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m1_u64m1_tum
// CHECK-RV64-SAME: (<vscale x 1 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 1 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv1i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 1 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 1 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m1_u64m1_tum(vbool64_t mask, vuint64m1_t maskedoff, vuint64m1_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m1_u64m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m2_u64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[2] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[2] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m2_u64m1_tum
// CHECK-RV64-SAME: (<vscale x 2 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 2 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv2i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 2 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 2 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m2_u64m1_tum(vbool32_t mask, vuint64m1_t maskedoff, vuint64m2_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m2_u64m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m4_u64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[4] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[4] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m4_u64m1_tum
// CHECK-RV64-SAME: (<vscale x 4 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 4 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv4i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 4 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 4 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m4_u64m1_tum(vbool16_t mask, vuint64m1_t maskedoff, vuint64m4_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m4_u64m1_tum(mask, maskedoff, vector, scalar, vl);
}

// CIR-LABEL: cir.func{{.*}} @test_vredsum_vs_u64m8_u64m1_tum(
// CIR-SAME: -> !cir.vector<[1]
// CIR: {{%.*}} = cir.call_llvm_intrinsic "riscv.vredsum.mask" {{%.*}} : (!cir.vector<[1] x !u64i>, !cir.vector<[8] x !u64i>, !cir.vector<[1] x !u64i>, !cir.vector<[8] x !cir.int<u, 1>>, !u64i) -> !cir.vector<[1] x !u64i>
//
// CHECK-RV64-LABEL: define dso_local <vscale x 1 x i64> @test_vredsum_vs_u64m8_u64m1_tum
// CHECK-RV64-SAME: (<vscale x 8 x i1> [[MASK:%.*]], <vscale x 1 x i64> [[MASKEDOFF:%.*]], <vscale x 8 x i64> [[VECTOR:%.*]], <vscale x 1 x i64> [[SCALAR:%.*]], i64 noundef [[VL:%.*]]) #[[ATTR0]] {
// CHECK-RV64-OGCG-NEXT:  entry:
// CHECK-RV64:    [[TMP0:%.*]] = call <vscale x 1 x i64> @llvm.riscv.vredsum.mask.nxv1i64.nxv8i64.i64(<vscale x 1 x i64> [[MASKEDOFF]], <vscale x 8 x i64> [[VECTOR]], <vscale x 1 x i64> [[SCALAR]], <vscale x 8 x i1> [[MASK]], i64 [[VL]])
// CHECK-RV64-NEXT:    ret <vscale x 1 x i64> [[TMP0]]
//
vuint64m1_t test_vredsum_vs_u64m8_u64m1_tum(vbool8_t mask, vuint64m1_t maskedoff, vuint64m8_t vector, vuint64m1_t scalar, size_t vl) {
  return __riscv_vredsum_vs_u64m8_u64m1_tum(mask, maskedoff, vector, scalar, vl);
}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK-RV64: {{.*}}
