; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: -p --version 6
; RUN: opt -mtriple=nvptx64-nvidia-cuda -mcpu=sm_70 -passes=loop-unroll -unroll-runtime -unroll-allow-partial -S < %s | FileCheck %s

declare i32 @llvm.nvvm.shfl.down.i32(i32, i32, i32)
declare i32 @llvm.nvvm.read.ptx.sreg.tid.x()

; This loop has a convergent shfl_down intrinsic and a runtime trip count that
; is uniform (kernel argument). Since the trip count is uniform across all
; threads, runtime unrolling with a remainder is safe.
;
define void @runtime_unroll_uniform_trip_count(ptr %out, ptr %in, i32 %n) {
; CHECK-LABEL: define ptx_kernel void @runtime_unroll_uniform_trip_count(ptr %out, ptr %in, i32 %n) #2 {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    %0 = add i32 %n, -1
; CHECK-NEXT:    %xtraiter = and i32 %n, 3
; CHECK-NEXT:    %1 = icmp ult i32 %0, 3
; CHECK-NEXT:    br i1 %1, label %for.body.epil.preheader, label %entry.new
; CHECK:       entry.new:
; CHECK-NEXT:    %unroll_iter = sub i32 %n, %xtraiter
; CHECK-NEXT:    br label %for.body
; CHECK:       for.body:
; CHECK-NEXT:    %indvars.iv = phi i32 [ 0, %entry.new ], [ %indvars.iv.next.3, %for.body ]
; CHECK-NEXT:    %sum.02 = phi i32 [ 0, %entry.new ], [ %add.3, %for.body ]
; CHECK-NEXT:    %niter = phi i32 [ 0, %entry.new ], [ %niter.next.3, %for.body ]
; CHECK-NEXT:    %arrayidx.in = getelementptr inbounds i32, ptr %in, i32 %indvars.iv
; CHECK-NEXT:    %arrayidx.out = getelementptr inbounds i32, ptr %out, i32 %indvars.iv
; CHECK-NEXT:    %load = load i32, ptr %arrayidx.in, align 4
; CHECK-NEXT:    %shfl = call i32 @llvm.nvvm.shfl.down.i32(i32 %sum.02, i32 1, i32 31)
; CHECK-NEXT:    %add = add i32 %load, %shfl
; CHECK-NEXT:    store i32 %add, ptr %arrayidx.out, align 4
; CHECK-NEXT:    %indvars.iv.next = add nuw nsw i32 %indvars.iv, 1
; CHECK-NEXT:    %arrayidx.in.1 = getelementptr inbounds i32, ptr %in, i32 %indvars.iv.next
; CHECK-NEXT:    %arrayidx.out.1 = getelementptr inbounds i32, ptr %out, i32 %indvars.iv.next
; CHECK-NEXT:    %load.1 = load i32, ptr %arrayidx.in.1, align 4
; CHECK-NEXT:    %shfl.1 = call i32 @llvm.nvvm.shfl.down.i32(i32 %add, i32 1, i32 31)
; CHECK-NEXT:    %add.1 = add i32 %load.1, %shfl.1
; CHECK-NEXT:    store i32 %add.1, ptr %arrayidx.out.1, align 4
; CHECK-NEXT:    %indvars.iv.next.1 = add nuw nsw i32 %indvars.iv, 2
; CHECK-NEXT:    %arrayidx.in.2 = getelementptr inbounds i32, ptr %in, i32 %indvars.iv.next.1
; CHECK-NEXT:    %arrayidx.out.2 = getelementptr inbounds i32, ptr %out, i32 %indvars.iv.next.1
; CHECK-NEXT:    %load.2 = load i32, ptr %arrayidx.in.2, align 4
; CHECK-NEXT:    %shfl.2 = call i32 @llvm.nvvm.shfl.down.i32(i32 %add.1, i32 1, i32 31)
; CHECK-NEXT:    %add.2 = add i32 %load.2, %shfl.2
; CHECK-NEXT:    store i32 %add.2, ptr %arrayidx.out.2, align 4
; CHECK-NEXT:    %indvars.iv.next.2 = add nuw nsw i32 %indvars.iv, 3
; CHECK-NEXT:    %arrayidx.in.3 = getelementptr inbounds i32, ptr %in, i32 %indvars.iv.next.2
; CHECK-NEXT:    %arrayidx.out.3 = getelementptr inbounds i32, ptr %out, i32 %indvars.iv.next.2
; CHECK-NEXT:    %load.3 = load i32, ptr %arrayidx.in.3, align 4
; CHECK-NEXT:    %shfl.3 = call i32 @llvm.nvvm.shfl.down.i32(i32 %add.2, i32 1, i32 31)
; CHECK-NEXT:    %add.3 = add i32 %load.3, %shfl.3
; CHECK-NEXT:    store i32 %add.3, ptr %arrayidx.out.3, align 4
; CHECK-NEXT:    %indvars.iv.next.3 = add i32 %indvars.iv, 4
; CHECK-NEXT:    %niter.next.3 = add i32 %niter, 4
; CHECK-NEXT:    %niter.ncmp.3 = icmp eq i32 %niter.next.3, %unroll_iter
; CHECK-NEXT:    br i1 %niter.ncmp.3, label %for.end.unr-lcssa, label %for.body
; CHECK:       for.end.unr-lcssa:
; CHECK-NEXT:    %indvars.iv.unr = phi i32 [ %indvars.iv.next.3, %for.body ]
; CHECK-NEXT:    %sum.02.unr = phi i32 [ %add.3, %for.body ]
; CHECK-NEXT:    %lcmp.mod = icmp ne i32 %xtraiter, 0
; CHECK-NEXT:    br i1 %lcmp.mod, label %for.body.epil.preheader, label %for.end
; CHECK:       for.body.epil.preheader:
; CHECK-NEXT:    %indvars.iv.epil.init = phi i32 [ 0, %entry ], [ %indvars.iv.unr, %for.end.unr-lcssa ]
; CHECK-NEXT:    %sum.02.epil.init = phi i32 [ 0, %entry ], [ %sum.02.unr, %for.end.unr-lcssa ]
; CHECK-NEXT:    %lcmp.mod1 = icmp ne i32 %xtraiter, 0
; CHECK-NEXT:    call void @llvm.assume(i1 %lcmp.mod1)
; CHECK-NEXT:    br label %for.body.epil
; CHECK:       for.body.epil:
; CHECK-NEXT:    %indvars.iv.epil = phi i32 [ %indvars.iv.next.epil, %for.body.epil ], [ %indvars.iv.epil.init, %for.body.epil.preheader ]
; CHECK-NEXT:    %sum.02.epil = phi i32 [ %add.epil, %for.body.epil ], [ %sum.02.epil.init, %for.body.epil.preheader ]
; CHECK-NEXT:    %epil.iter = phi i32 [ 0, %for.body.epil.preheader ], [ %epil.iter.next, %for.body.epil ]
; CHECK-NEXT:    %arrayidx.in.epil = getelementptr inbounds i32, ptr %in, i32 %indvars.iv.epil
; CHECK-NEXT:    %arrayidx.out.epil = getelementptr inbounds i32, ptr %out, i32 %indvars.iv.epil
; CHECK-NEXT:    %load.epil = load i32, ptr %arrayidx.in.epil, align 4
; CHECK-NEXT:    %shfl.epil = call i32 @llvm.nvvm.shfl.down.i32(i32 %sum.02.epil, i32 1, i32 31)
; CHECK-NEXT:    %add.epil = add i32 %load.epil, %shfl.epil
; CHECK-NEXT:    store i32 %add.epil, ptr %arrayidx.out.epil, align 4
; CHECK-NEXT:    %indvars.iv.next.epil = add i32 %indvars.iv.epil, 1
; CHECK-NEXT:    %exitcond.epil = icmp eq i32 %indvars.iv.next.epil, %n
; CHECK-NEXT:    %epil.iter.next = add i32 %epil.iter, 1
; CHECK-NEXT:    %epil.iter.cmp = icmp ne i32 %epil.iter.next, %xtraiter
; CHECK-NEXT:    br i1 %epil.iter.cmp, label %for.body.epil, label %for.end.epilog-lcssa, !llvm.loop !0
; CHECK:       for.end.epilog-lcssa:
; CHECK-NEXT:    br label %for.end
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %indvars.iv = phi i32 [ %indvars.iv.next, %for.body ], [ 0, %entry ]
  %sum.02 = phi i32 [ %add, %for.body ], [ 0, %entry ]
  %arrayidx.in = getelementptr inbounds i32, ptr %in, i32 %indvars.iv
  %arrayidx.out = getelementptr inbounds i32, ptr %out, i32 %indvars.iv
  %load = load i32, ptr %arrayidx.in
  %shfl = call i32 @llvm.nvvm.shfl.down.i32(i32 %sum.02, i32 1, i32 31)
  %add = add i32 %load, %shfl
  store i32 %add, ptr %arrayidx.out
  %indvars.iv.next = add i32 %indvars.iv, 1
  %exitcond = icmp eq i32 %indvars.iv.next, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}

; This loop has a convergent shfl_down intrinsic and a divergent trip count
; (derived from tid.x, which is divergent on NVPTX). Since the trip count is
; divergent, runtime unrolling with a remainder must still be blocked.
;
define void @runtime_unroll_divergent_trip_count(ptr %out, ptr %in) {
; CHECK-LABEL: define ptx_kernel void @runtime_unroll_divergent_trip_count(ptr %out, ptr %in) #2 {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    %tid = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
; CHECK-NEXT:    %n = add i32 %tid, 1
; CHECK-NEXT:    br label %for.body
; CHECK:       for.body:
; CHECK-NEXT:    %indvars.iv = phi i32 [ %indvars.iv.next, %for.body ], [ 0, %entry ]
; CHECK-NEXT:    %sum.02 = phi i32 [ %add, %for.body ], [ 0, %entry ]
; CHECK-NEXT:    %arrayidx.in = getelementptr inbounds i32, ptr %in, i32 %indvars.iv
; CHECK-NEXT:    %arrayidx.out = getelementptr inbounds i32, ptr %out, i32 %indvars.iv
; CHECK-NEXT:    %load = load i32, ptr %arrayidx.in, align 4
; CHECK-NEXT:    %shfl = call i32 @llvm.nvvm.shfl.down.i32(i32 %sum.02, i32 1, i32 31)
; CHECK-NEXT:    %add = add i32 %load, %shfl
; CHECK-NEXT:    store i32 %add, ptr %arrayidx.out, align 4
; CHECK-NEXT:    %indvars.iv.next = add i32 %indvars.iv, 1
; CHECK-NEXT:    %exitcond = icmp eq i32 %indvars.iv.next, %n
; CHECK-NEXT:    br i1 %exitcond, label %for.end, label %for.body
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
entry:
  %tid = call i32 @llvm.nvvm.read.ptx.sreg.tid.x()
  %n = add i32 %tid, 1
  br label %for.body

for.body:
  %indvars.iv = phi i32 [ %indvars.iv.next, %for.body ], [ 0, %entry ]
  %sum.02 = phi i32 [ %add, %for.body ], [ 0, %entry ]
  %arrayidx.in = getelementptr inbounds i32, ptr %in, i32 %indvars.iv
  %arrayidx.out = getelementptr inbounds i32, ptr %out, i32 %indvars.iv
  %load = load i32, ptr %arrayidx.in
  %shfl = call i32 @llvm.nvvm.shfl.down.i32(i32 %sum.02, i32 1, i32 31)
  %add = add i32 %load, %shfl
  store i32 %add, ptr %arrayidx.out
  %indvars.iv.next = add i32 %indvars.iv, 1
  %exitcond = icmp eq i32 %indvars.iv.next, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}

!nvvm.annotations = !{!0, !1}
!0 = !{ptr @runtime_unroll_uniform_trip_count, !"kernel", i32 1}
!1 = !{ptr @runtime_unroll_divergent_trip_count, !"kernel", i32 1}
