; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

define <32 x i8> @bitclri_v32i8(<32 x i8> %a) nounwind {
; CHECK-LABEL: bitclri_v32i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitclri.b $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = and <32 x i8> %a, splat (i8 -5)
    ret <32 x i8> %0
}

define <16 x i16> @bitclri_v16i16(<16 x i16> %a) nounwind {
; CHECK-LABEL: bitclri_v16i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitclri.h $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = and <16 x i16> %a, splat (i16 -5)
    ret <16 x i16> %0
}

define <8 x i32> @bitclri_v8i32(<8 x i32> %a) nounwind {
; CHECK-LABEL: bitclri_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitclri.w $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = and <8 x i32> %a, splat (i32 -5)
    ret <8 x i32> %0
}

define <4 x i64> @bitclri_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitclri_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitclri.d $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = and <4 x i64> %a, splat (i64 -5)
    ret <4 x i64> %0
}

define <8 x i32> @bitclri_v32i8_v8i32(<8 x i32> %a) nounwind {
; CHECK-LABEL: bitclri_v32i8_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvandi.b $xr0, $xr0, 251
; CHECK-NEXT:    ret
entry:
    %0 = and <8 x i32> %a, splat (i32 -67372037)
    ret <8 x i32> %0
}

define <8 x i32> @bitclri_v16i16_v8i32(<8 x i32> %a) nounwind {
; CHECK-LABEL: bitclri_v16i16_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitclri.h $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = and <8 x i32> %a, splat (i32 -262149)
    ret <8 x i32> %0
}

define <4 x i64> @bitclri_v32i8_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitclri_v32i8_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvandi.b $xr0, $xr0, 251
; CHECK-NEXT:    ret
entry:
    %0 = and <4 x i64> %a, splat (i64 -289360691352306693)
    ret <4 x i64> %0
}

define <4 x i64> @bitclri_v16i16_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitclri_v16i16_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitclri.h $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = and <4 x i64> %a, splat (i64 -1125917086973957)
    ret <4 x i64> %0
}

define <4 x i64> @bitclri_v8i32_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitclri_v8i32_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitclri.w $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = and <4 x i64> %a, splat (i64 -17179869189)
    ret <4 x i64> %0
}
