; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

define <32 x i8> @bitrevi_v32i8(<32 x i8> %a) nounwind {
; CHECK-LABEL: bitrevi_v32i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitrevi.b $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = xor <32 x i8> %a, splat (i8 4)
    ret <32 x i8> %0
}

define <16 x i16> @bitrevi_v16i16(<16 x i16> %a) nounwind {
; CHECK-LABEL: bitrevi_v16i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitrevi.h $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = xor <16 x i16> %a, splat (i16 4)
    ret <16 x i16> %0
}

define <8 x i32> @bitrevi_v8i32(<8 x i32> %a) nounwind {
; CHECK-LABEL: bitrevi_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitrevi.w $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = xor <8 x i32> %a, splat (i32 4)
    ret <8 x i32> %0
}

define <4 x i64> @bitrevi_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitrevi_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitrevi.d $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = xor <4 x i64> %a, splat (i64 4)
    ret <4 x i64> %0
}

define <8 x i32> @bitrevi_v32i8_v8i32(<8 x i32> %a) nounwind {
; CHECK-LABEL: bitrevi_v32i8_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvxori.b $xr0, $xr0, 4
; CHECK-NEXT:    ret
entry:
    %0 = xor <8 x i32> %a, splat (i32 67372036)
    ret <8 x i32> %0
}

define <8 x i32> @bitrevi_v16i16_v8i32(<8 x i32> %a) nounwind {
; CHECK-LABEL: bitrevi_v16i16_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitrevi.h $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = xor <8 x i32> %a, splat (i32 262148)
    ret <8 x i32> %0
}

define <4 x i64> @bitrevi_v32i8_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitrevi_v32i8_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvxori.b $xr0, $xr0, 4
; CHECK-NEXT:    ret
entry:
    %0 = xor <4 x i64> %a, splat (i64 289360691352306692)
    ret <4 x i64> %0
}

define <4 x i64> @bitrevi_v16i16_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitrevi_v16i16_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitrevi.h $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = xor <4 x i64> %a, splat (i64 1125917086973956)
    ret <4 x i64> %0
}

define <4 x i64> @bitrevi_v8i32_v4i64(<4 x i64> %a) nounwind {
; CHECK-LABEL: bitrevi_v8i32_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvbitrevi.w $xr0, $xr0, 2
; CHECK-NEXT:    ret
entry:
    %0 = xor <4 x i64> %a, splat (i64 17179869188)
    ret <4 x i64> %0
}
