; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

declare <32 x i8> @llvm.loongarch.lasx.xvpcnt.b(<32 x i8>)

define <32 x i8> @lasx_xvpcnt_b(<32 x i8> %va) nounwind {
; CHECK-LABEL: lasx_xvpcnt_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpcnt.b $xr0, $xr0
; CHECK-NEXT:    ret
entry:
  %res = call <32 x i8> @llvm.loongarch.lasx.xvpcnt.b(<32 x i8> %va)
  ret <32 x i8> %res
}

declare <16 x i16> @llvm.loongarch.lasx.xvpcnt.h(<16 x i16>)

define <16 x i16> @lasx_xvpcnt_h(<16 x i16> %va) nounwind {
; CHECK-LABEL: lasx_xvpcnt_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpcnt.h $xr0, $xr0
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i16> @llvm.loongarch.lasx.xvpcnt.h(<16 x i16> %va)
  ret <16 x i16> %res
}

declare <8 x i32> @llvm.loongarch.lasx.xvpcnt.w(<8 x i32>)

define <8 x i32> @lasx_xvpcnt_w(<8 x i32> %va) nounwind {
; CHECK-LABEL: lasx_xvpcnt_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpcnt.w $xr0, $xr0
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i32> @llvm.loongarch.lasx.xvpcnt.w(<8 x i32> %va)
  ret <8 x i32> %res
}

declare <4 x i64> @llvm.loongarch.lasx.xvpcnt.d(<4 x i64>)

define <4 x i64> @lasx_xvpcnt_d(<4 x i64> %va) nounwind {
; CHECK-LABEL: lasx_xvpcnt_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpcnt.d $xr0, $xr0
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i64> @llvm.loongarch.lasx.xvpcnt.d(<4 x i64> %va)
  ret <4 x i64> %res
}
