; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

declare <32 x i8> @llvm.loongarch.lasx.xvshuf4i.b(<32 x i8>, i32)

define <32 x i8> @lasx_xvshuf4i_b(<32 x i8> %va) nounwind {
; CHECK-LABEL: lasx_xvshuf4i_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvshuf4i.b $xr0, $xr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call <32 x i8> @llvm.loongarch.lasx.xvshuf4i.b(<32 x i8> %va, i32 1)
  ret <32 x i8> %res
}

declare <16 x i16> @llvm.loongarch.lasx.xvshuf4i.h(<16 x i16>, i32)

define <16 x i16> @lasx_xvshuf4i_h(<16 x i16> %va) nounwind {
; CHECK-LABEL: lasx_xvshuf4i_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvshuf4i.h $xr0, $xr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call <16 x i16> @llvm.loongarch.lasx.xvshuf4i.h(<16 x i16> %va, i32 1)
  ret <16 x i16> %res
}

declare <8 x i32> @llvm.loongarch.lasx.xvshuf4i.w(<8 x i32>, i32)

define <8 x i32> @lasx_xvshuf4i_w(<8 x i32> %va) nounwind {
; CHECK-LABEL: lasx_xvshuf4i_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvshuf4i.w $xr0, $xr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call <8 x i32> @llvm.loongarch.lasx.xvshuf4i.w(<8 x i32> %va, i32 1)
  ret <8 x i32> %res
}

declare <4 x i64> @llvm.loongarch.lasx.xvshuf4i.d(<4 x i64>, <4 x i64>, i32)

define <4 x i64> @lasx_xvshuf4i_d(<4 x i64> %va, <4 x i64> %vb) nounwind {
; CHECK-LABEL: lasx_xvshuf4i_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvshuf4i.d $xr0, $xr1, 1
; CHECK-NEXT:    ret
entry:
  %res = call <4 x i64> @llvm.loongarch.lasx.xvshuf4i.d(<4 x i64> %va, <4 x i64> %vb, i32 1)
  ret <4 x i64> %res
}
