; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s --check-prefixes=CHECK,LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s --check-prefixes=CHECK,LA64

declare i32 @llvm.loongarch.lasx.xvpickve2gr.w(<8 x i32>, i32)

define i32 @lasx_xvpickve2gr_w(<8 x i32> %va) nounwind {
; CHECK-LABEL: lasx_xvpickve2gr_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpickve2gr.w $a0, $xr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lasx.xvpickve2gr.w(<8 x i32> %va, i32 1)
  ret i32 %res
}

declare i32 @llvm.loongarch.lasx.xvpickve2gr.wu(<8 x i32>, i32)

define i32 @lasx_xvpickve2gr_wu(<8 x i32> %va) nounwind {
; CHECK-LABEL: lasx_xvpickve2gr_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpickve2gr.wu $a0, $xr0, 1
; CHECK-NEXT:    ret
entry:
  %res = call i32 @llvm.loongarch.lasx.xvpickve2gr.wu(<8 x i32> %va, i32 1)
  ret i32 %res
}

define i1 @lasx_xvpickve2gr_wu_cmp(<8 x i32> %va) nounwind {
; LA32-LABEL: lasx_xvpickve2gr_wu_cmp:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    xvpickve2gr.wu $a0, $xr0, 1
; LA32-NEXT:    sltui $a0, $a0, 1
; LA32-NEXT:    ret
;
; LA64-LABEL: lasx_xvpickve2gr_wu_cmp:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    xvpickve2gr.wu $a0, $xr0, 1
; LA64-NEXT:    addi.w $a0, $a0, 0
; LA64-NEXT:    sltui $a0, $a0, 1
; LA64-NEXT:    ret
entry:
  %val = call i32 @llvm.loongarch.lasx.xvpickve2gr.wu(<8 x i32> %va, i32 1)
  %tmp = and i32 %val, 4294967295
  %res = icmp eq i32 %tmp, 0
  ret i1 %res
}
