; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple loongarch64 -mattr=+lasx < %s | FileCheck %s

define <8 x i32> @udot(<8 x i32> %acc, <32 x i8> %u, <32 x i8> %s) {
; CHECK-LABEL: udot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvmulwod.h.bu $xr3, $xr2, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr3, $xr3, $xr3
; CHECK-NEXT:    xvmulwev.h.bu $xr1, $xr2, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr3
; CHECK-NEXT:    xvadd.w $xr0, $xr1, $xr0
; CHECK-NEXT:    ret
  %u.wide = zext <32 x i8> %u to <32 x i32>
  %s.wide = zext <32 x i8> %s to <32 x i32>
  %mult = mul nuw nsw <32 x i32> %s.wide, %u.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mult)
  ret <8 x i32> %partial.reduce
}

define <8 x i32> @udot_in_loop(ptr %p1, ptr %p2){
; CHECK-LABEL: udot_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    xvrepli.b $xr1, 0
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB1_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    xvldx $xr2, $a0, $a2
; CHECK-NEXT:    xvldx $xr3, $a1, $a2
; CHECK-NEXT:    xvori.b $xr0, $xr1, 0
; CHECK-NEXT:    xvmulwod.h.bu $xr1, $xr2, $xr3
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvmulwev.h.bu $xr2, $xr2, $xr3
; CHECK-NEXT:    xvhaddw.w.h $xr2, $xr2, $xr2
; CHECK-NEXT:    xvadd.w $xr1, $xr2, $xr1
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr0
; CHECK-NEXT:    bne $a2, $a3, .LBB1_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <8 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <32 x i8>, ptr %gep1, align 16
  %load1.wide = zext <32 x i8> %load1 to <32 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <32 x i8>, ptr %gep2, align 16
  %load2.wide = zext <32 x i8> %load2 to <32 x i32>
  %mul = mul nuw nsw <32 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <8 x i32> %acc
}

define <8 x i32> @sdot(<8 x i32> %acc, <32 x i8> %u, <32 x i8> %s) {
; CHECK-LABEL: sdot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvmulwod.h.b $xr3, $xr2, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr3, $xr3, $xr3
; CHECK-NEXT:    xvmulwev.h.b $xr1, $xr2, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr3
; CHECK-NEXT:    xvadd.w $xr0, $xr1, $xr0
; CHECK-NEXT:    ret
  %u.wide = sext <32 x i8> %u to <32 x i32>
  %s.wide = sext <32 x i8> %s to <32 x i32>
  %mult = mul nuw nsw <32 x i32> %s.wide, %u.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mult)
  ret <8 x i32> %partial.reduce
}

define <8 x i32> @usdot(<8 x i32> %acc, <32 x i8> %u, <32 x i8> %s) {
; CHECK-LABEL: usdot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvmulwod.h.bu.b $xr3, $xr1, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr3, $xr3, $xr3
; CHECK-NEXT:    xvmulwev.h.bu.b $xr1, $xr1, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr3
; CHECK-NEXT:    xvadd.w $xr0, $xr1, $xr0
; CHECK-NEXT:    ret
  %u.wide = zext <32 x i8> %u to <32 x i32>
  %s.wide = sext <32 x i8> %s to <32 x i32>
  %mult = mul nuw nsw <32 x i32> %s.wide, %u.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mult)
  ret <8 x i32> %partial.reduce
}

define <8 x i32> @usdot_in_loop(ptr %p1, ptr %p2){
; CHECK-LABEL: usdot_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    xvrepli.b $xr1, 0
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB4_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    xvldx $xr2, $a0, $a2
; CHECK-NEXT:    xvldx $xr3, $a1, $a2
; CHECK-NEXT:    xvori.b $xr0, $xr1, 0
; CHECK-NEXT:    xvmulwod.h.bu.b $xr1, $xr3, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvmulwev.h.bu.b $xr2, $xr3, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr2, $xr2, $xr2
; CHECK-NEXT:    xvadd.w $xr1, $xr2, $xr1
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr0
; CHECK-NEXT:    bne $a2, $a3, .LBB4_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <8 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <32 x i8>, ptr %gep1, align 16
  %load1.wide = sext <32 x i8> %load1 to <32 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <32 x i8>, ptr %gep2, align 16
  %load2.wide = zext <32 x i8> %load2 to <32 x i32>
  %mul = mul nuw nsw <32 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <8 x i32> %acc
}

; Same as @usdot_in_loop, but with a non-zero initial accumulator carried
; across iterations. Validates that the SUMLA -> 2x udot identity composes
; correctly when the accumulator is not zero on entry.
define <8 x i32> @usdot_in_loop_nonzero_acc(ptr %p1, ptr %p2, <8 x i32> %init){
; CHECK-LABEL: usdot_in_loop_nonzero_acc:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB5_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    xvldx $xr2, $a0, $a2
; CHECK-NEXT:    xvldx $xr3, $a1, $a2
; CHECK-NEXT:    xvori.b $xr1, $xr0, 0
; CHECK-NEXT:    xvmulwod.h.bu.b $xr0, $xr3, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr0, $xr0, $xr0
; CHECK-NEXT:    xvmulwev.h.bu.b $xr2, $xr3, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr2, $xr2, $xr2
; CHECK-NEXT:    xvadd.w $xr0, $xr2, $xr0
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    xvadd.w $xr0, $xr0, $xr1
; CHECK-NEXT:    bne $a2, $a3, .LBB5_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    xvori.b $xr0, $xr1, 0
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <8 x i32> [ %init, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <32 x i8>, ptr %gep1, align 16
  %load1.wide = sext <32 x i8> %load1 to <32 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <32 x i8>, ptr %gep2, align 16
  %load2.wide = zext <32 x i8> %load2 to <32 x i32>
  %mul = mul nuw nsw <32 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <8 x i32> %acc
}

define <8 x i32> @sudot(<8 x i32> %acc, <32 x i8> %u, <32 x i8> %s) #0{
; CHECK-LABEL: sudot:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvmulwod.h.bu.b $xr3, $xr2, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr3, $xr3, $xr3
; CHECK-NEXT:    xvmulwev.h.bu.b $xr1, $xr2, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr3
; CHECK-NEXT:    xvadd.w $xr0, $xr1, $xr0
; CHECK-NEXT:    ret
  %s.wide = sext <32 x i8> %u to <32 x i32>
  %u.wide = zext <32 x i8> %s to <32 x i32>
  %mult = mul nuw nsw <32 x i32> %u.wide, %s.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mult)
  ret <8 x i32> %partial.reduce
}

define <8 x i32> @sudot_in_loop(ptr %p1, ptr %p2){
; CHECK-LABEL: sudot_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a2, $zero
; CHECK-NEXT:    xvrepli.b $xr1, 0
; CHECK-NEXT:    ori $a3, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB7_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    xvldx $xr2, $a0, $a2
; CHECK-NEXT:    xvldx $xr3, $a1, $a2
; CHECK-NEXT:    xvori.b $xr0, $xr1, 0
; CHECK-NEXT:    xvmulwod.h.bu.b $xr1, $xr2, $xr3
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvmulwev.h.bu.b $xr2, $xr2, $xr3
; CHECK-NEXT:    xvhaddw.w.h $xr2, $xr2, $xr2
; CHECK-NEXT:    xvadd.w $xr1, $xr2, $xr1
; CHECK-NEXT:    addi.d $a2, $a2, 16
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr0
; CHECK-NEXT:    bne $a2, $a3, .LBB7_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <8 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep1 = getelementptr i8, ptr %p1, i64 %index
  %load1 = load <32 x i8>, ptr %gep1, align 16
  %load1.wide = zext <32 x i8> %load1 to <32 x i32>
  %gep2 = getelementptr i8, ptr %p2, i64 %index
  %load2 = load <32 x i8>, ptr %gep2, align 16
  %load2.wide = sext <32 x i8> %load2 to <32 x i32>
  %mul = mul nuw nsw <32 x i32> %load1.wide, %load2.wide
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %mul)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <8 x i32> %acc
}

define <8 x i32> @udot_no_bin_op(<8 x i32> %acc, <32 x i8> %a){
; CHECK-LABEL: udot_no_bin_op:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvrepli.b $xr2, 1
; CHECK-NEXT:    xvmulwod.h.bu $xr3, $xr1, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr3, $xr3, $xr3
; CHECK-NEXT:    xvmulwev.h.bu $xr1, $xr1, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr3
; CHECK-NEXT:    xvadd.w $xr0, $xr1, $xr0
; CHECK-NEXT:    ret
  %a.wide = zext <32 x i8> %a to <32 x i32>
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %a.wide)
  ret <8 x i32> %partial.reduce
}

define <8 x i32> @udot_no_bin_op_in_loop(ptr %p){
; CHECK-LABEL: udot_no_bin_op_in_loop:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    move $a1, $zero
; CHECK-NEXT:    xvrepli.b $xr2, 0
; CHECK-NEXT:    xvrepli.b $xr1, 1
; CHECK-NEXT:    ori $a2, $zero, 16
; CHECK-NEXT:    .p2align 4, , 16
; CHECK-NEXT:  .LBB9_1: # %vector.body
; CHECK-NEXT:    # =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    xvldx $xr3, $a0, $a1
; CHECK-NEXT:    xvori.b $xr0, $xr2, 0
; CHECK-NEXT:    xvmulwod.h.bu $xr2, $xr3, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr2, $xr2, $xr2
; CHECK-NEXT:    xvmulwev.h.bu $xr3, $xr3, $xr1
; CHECK-NEXT:    xvhaddw.w.h $xr3, $xr3, $xr3
; CHECK-NEXT:    xvadd.w $xr2, $xr3, $xr2
; CHECK-NEXT:    addi.d $a1, $a1, 16
; CHECK-NEXT:    xvadd.w $xr2, $xr2, $xr0
; CHECK-NEXT:    bne $a1, $a2, .LBB9_1
; CHECK-NEXT:  # %bb.2: # %end
; CHECK-NEXT:    ret
entry:
  br label %vector.body

vector.body:
  %index = phi i64 [ 0, %entry ], [ %index.next, %vector.body ]
  %acc = phi <8 x i32> [ zeroinitializer, %entry ], [ %partial.reduce, %vector.body ]
  %gep = getelementptr i8, ptr %p, i64 %index
  %load = load <32 x i8>, ptr %gep, align 16
  %load.wide = zext <32 x i8> %load to <32 x i32>
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %load.wide)
  %index.next = add nuw i64 %index, 16
  %cmp = icmp eq i64 %index.next, 16
  br i1 %cmp, label %end, label %vector.body

end:
  ret <8 x i32> %acc
}

define <8 x i32> @sdot_no_bin_op(<8 x i32> %acc, <32 x i8> %a){
; CHECK-LABEL: sdot_no_bin_op:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvrepli.b $xr2, 1
; CHECK-NEXT:    xvmulwod.h.b $xr3, $xr1, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr3, $xr3, $xr3
; CHECK-NEXT:    xvmulwev.h.b $xr1, $xr1, $xr2
; CHECK-NEXT:    xvhaddw.w.h $xr1, $xr1, $xr1
; CHECK-NEXT:    xvadd.w $xr1, $xr1, $xr3
; CHECK-NEXT:    xvadd.w $xr0, $xr1, $xr0
; CHECK-NEXT:    ret
  %a.wide = sext <32 x i8> %a to <32 x i32>
  %partial.reduce = tail call <8 x i32> @llvm.vector.partial.reduce.add.v8i32.v32i32(<8 x i32> %acc, <32 x i32> %a.wide)
  ret <8 x i32> %partial.reduce
}
