; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

define <32 x i8> @srar_b(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: srar_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsra.b $xr2, $xr0, $xr1
; CHECK-NEXT:    xvsubi.bu $xr3, $xr1, 1
; CHECK-NEXT:    xvsrl.b $xr3, $xr0, $xr3
; CHECK-NEXT:    xvandi.b $xr3, $xr3, 1
; CHECK-NEXT:    xvadd.b $xr2, $xr3, $xr2
; CHECK-NEXT:    xvseqi.b $xr1, $xr1, 0
; CHECK-NEXT:    xvbitsel.v $xr0, $xr2, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <32 x i8> %a, %b
  %1 = add <32 x i8> %b, splat (i8 -1)
  %2 = lshr <32 x i8> %a, %1
  %3 = and <32 x i8> %2, splat (i8 1)
  %4 = add <32 x i8> %3, %0
  %5 = icmp eq <32 x i8> %b, zeroinitializer
  %6 = select <32 x i1> %5, <32 x i8> %a, <32 x i8> %4
  ret <32 x i8> %6
}

define <16 x i16> @srar_h(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: srar_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsra.h $xr2, $xr0, $xr1
; CHECK-NEXT:    xvsubi.hu $xr3, $xr1, 1
; CHECK-NEXT:    xvsrl.h $xr3, $xr0, $xr3
; CHECK-NEXT:    xvrepli.h $xr4, 1
; CHECK-NEXT:    xvand.v $xr3, $xr3, $xr4
; CHECK-NEXT:    xvadd.h $xr2, $xr3, $xr2
; CHECK-NEXT:    xvseqi.h $xr1, $xr1, 0
; CHECK-NEXT:    xvbitsel.v $xr0, $xr2, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i16> %a, %b
  %1 = add <16 x i16> %b, splat (i16 -1)
  %2 = lshr <16 x i16> %a, %1
  %3 = and <16 x i16> %2, splat (i16 1)
  %4 = add <16 x i16> %3, %0
  %5 = icmp eq <16 x i16> %b, zeroinitializer
  %6 = select <16 x i1> %5, <16 x i16> %a, <16 x i16> %4
  ret <16 x i16> %6
}

define <8 x i32> @srar_w(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: srar_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsra.w $xr2, $xr0, $xr1
; CHECK-NEXT:    xvsubi.wu $xr3, $xr1, 1
; CHECK-NEXT:    xvsrl.w $xr3, $xr0, $xr3
; CHECK-NEXT:    xvrepli.w $xr4, 1
; CHECK-NEXT:    xvand.v $xr3, $xr3, $xr4
; CHECK-NEXT:    xvadd.w $xr2, $xr3, $xr2
; CHECK-NEXT:    xvseqi.w $xr1, $xr1, 0
; CHECK-NEXT:    xvbitsel.v $xr0, $xr2, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i32> %a, %b
  %1 = add <8 x i32> %b, splat (i32 -1)
  %2 = lshr <8 x i32> %a, %1
  %3 = and <8 x i32> %2, splat (i32 1)
  %4 = add <8 x i32> %3, %0
  %5 = icmp eq <8 x i32> %b, zeroinitializer
  %6 = select <8 x i1> %5, <8 x i32> %a, <8 x i32> %4
  ret <8 x i32> %6
}

define <4 x i64> @srar_d(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: srar_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsra.d $xr2, $xr0, $xr1
; CHECK-NEXT:    xvsubi.du $xr3, $xr1, 1
; CHECK-NEXT:    xvsrl.d $xr3, $xr0, $xr3
; CHECK-NEXT:    xvrepli.d $xr4, 1
; CHECK-NEXT:    xvand.v $xr3, $xr3, $xr4
; CHECK-NEXT:    xvadd.d $xr2, $xr3, $xr2
; CHECK-NEXT:    xvseqi.d $xr1, $xr1, 0
; CHECK-NEXT:    xvbitsel.v $xr0, $xr2, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i64> %a, %b
  %1 = add <4 x i64> %b, splat (i64 -1)
  %2 = lshr <4 x i64> %a, %1
  %3 = and <4 x i64> %2, splat (i64 1)
  %4 = add <4 x i64> %3, %0
  %5 = icmp eq <4 x i64> %b, zeroinitializer
  %6 = select <4 x i1> %5, <4 x i64> %a, <4 x i64> %4
  ret <4 x i64> %6
}

define <32 x i8> @srar_b_1(<32 x i8> %a) nounwind {
; CHECK-LABEL: srar_b_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.b $xr1, $xr0, 1
; CHECK-NEXT:    xvandi.b $xr0, $xr0, 1
; CHECK-NEXT:    xvadd.b $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <32 x i8> %a, splat (i8 1)
  %1 = and <32 x i8> %a, splat (i8 1)
  %2 = add nsw <32 x i8> %1, %0
  ret <32 x i8> %2
}

define <32 x i8> @srar_b_7(<32 x i8> %a) nounwind {
; CHECK-LABEL: srar_b_7:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.b $xr1, $xr0, 7
; CHECK-NEXT:    xvsrli.b $xr0, $xr0, 6
; CHECK-NEXT:    xvandi.b $xr0, $xr0, 1
; CHECK-NEXT:    xvadd.b $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <32 x i8> %a, splat (i8 7)
  %1 = lshr <32 x i8> %a, splat (i8 6)
  %2 = and <32 x i8> %1, splat (i8 1)
  %3 = add nsw <32 x i8> %2, %0
  ret <32 x i8> %3
}

define <16 x i16> @srar_h_1(<16 x i16> %a) nounwind {
; CHECK-LABEL: srar_h_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.h $xr1, $xr0, 1
; CHECK-NEXT:    xvrepli.h $xr2, 1
; CHECK-NEXT:    xvand.v $xr0, $xr0, $xr2
; CHECK-NEXT:    xvadd.h $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i16> %a, splat (i16 1)
  %1 = and <16 x i16> %a, splat (i16 1)
  %2 = add nsw <16 x i16> %1, %0
  ret <16 x i16> %2
}

define <16 x i16> @srar_h_15(<16 x i16> %a) nounwind {
; CHECK-LABEL: srar_h_15:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.h $xr1, $xr0, 15
; CHECK-NEXT:    xvsrli.h $xr0, $xr0, 14
; CHECK-NEXT:    xvrepli.h $xr2, 1
; CHECK-NEXT:    xvand.v $xr0, $xr0, $xr2
; CHECK-NEXT:    xvadd.h $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i16> %a, splat (i16 15)
  %1 = lshr <16 x i16> %a, splat (i16 14)
  %2 = and <16 x i16> %1, splat (i16 1)
  %3 = add nsw <16 x i16> %2, %0
  ret <16 x i16> %3
}

define <8 x i32> @srar_w_1(<8 x i32> %a) nounwind {
; CHECK-LABEL: srar_w_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.w $xr1, $xr0, 1
; CHECK-NEXT:    xvrepli.w $xr2, 1
; CHECK-NEXT:    xvand.v $xr0, $xr0, $xr2
; CHECK-NEXT:    xvadd.w $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i32> %a, splat (i32 1)
  %1 = and <8 x i32> %a, splat (i32 1)
  %2 = add nsw <8 x i32> %1, %0
  ret <8 x i32> %2
}

define <8 x i32> @srar_w_31(<8 x i32> %a) nounwind {
; CHECK-LABEL: srar_w_31:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.w $xr1, $xr0, 31
; CHECK-NEXT:    xvsrli.w $xr0, $xr0, 30
; CHECK-NEXT:    xvrepli.w $xr2, 1
; CHECK-NEXT:    xvand.v $xr0, $xr0, $xr2
; CHECK-NEXT:    xvadd.w $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i32> %a, splat (i32 31)
  %1 = lshr <8 x i32> %a, splat (i32 30)
  %2 = and <8 x i32> %1, splat (i32 1)
  %3 = add nsw <8 x i32> %2, %0
  ret <8 x i32> %3
}

define <4 x i64> @srar_d_1(<4 x i64> %a) nounwind {
; CHECK-LABEL: srar_d_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.d $xr1, $xr0, 1
; CHECK-NEXT:    xvrepli.d $xr2, 1
; CHECK-NEXT:    xvand.v $xr0, $xr0, $xr2
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i64> %a, splat (i64 1)
  %1 = and <4 x i64> %a, splat (i64 1)
  %2 = add nsw <4 x i64> %1, %0
  ret <4 x i64> %2
}

define <4 x i64> @srar_d_63(<4 x i64> %a) nounwind {
; CHECK-LABEL: srar_d_63:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvsrai.d $xr1, $xr0, 63
; CHECK-NEXT:    xvsrli.d $xr0, $xr0, 62
; CHECK-NEXT:    xvrepli.d $xr2, 1
; CHECK-NEXT:    xvand.v $xr0, $xr0, $xr2
; CHECK-NEXT:    xvadd.d $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i64> %a, splat (i64 63)
  %1 = lshr <4 x i64> %a, splat (i64 62)
  %2 = and <4 x i64> %1, splat (i64 1)
  %3 = add nsw <4 x i64> %2, %0
  ret <4 x i64> %3
}
