; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=globalopt -o - < %s | FileCheck %s

target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @caller1() {
; CHECK-LABEL: define void @caller1() local_unnamed_addr {
; CHECK-NEXT:    call void @callee1()
; CHECK-NEXT:    ret void
;
  call void @callee1()
  ret void
}

define internal void @callee1() "target-features"="+egpr" {
; CHECK-LABEL: define internal void @callee1(
; CHECK-SAME: ) unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @caller2() "target-features"="+egpr" {
; CHECK-LABEL: define void @caller2(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:    call void @callee2()
; CHECK-NEXT:    ret void
;
  call void @callee2()
  ret void
}

define internal void @callee2() {
; CHECK-LABEL: define internal void @callee2() unnamed_addr {
; CHECK-NEXT:    ret void
;
  ret void
}

define void @caller3() "target-features"="+egpr" {
; CHECK-LABEL: define void @caller3(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:    call fastcc void @callee3()
; CHECK-NEXT:    ret void
;
  call void @callee3()
  ret void
}

define internal void @callee3() "target-features"="+egpr" {
; CHECK-LABEL: define internal fastcc void @callee3(
; CHECK-SAME: ) unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:    ret void
;
  ret void
}
