; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt < %s -passes=dse -S | FileCheck %s

; Check a dbg.assign is inserted that sets the dead middle bits to no-location (see tryToSplitMiddle).

define void @_Z22overwrite_middle_localv() !dbg !23 {
; CHECK-LABEL: define void @_Z22overwrite_middle_localv(
; CHECK-SAME: ) !dbg [[DBG16:![0-9]+]] {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BLOB:%.*]] = alloca [1000 x i8], align 16, !DIAssignID [[DIASSIGNID25:![0-9]+]]
; CHECK-NEXT:      #dbg_assign(i1 undef, [[META20:![0-9]+]], !DIExpression(), [[DIASSIGNID25]], ptr [[BLOB]], !DIExpression(), [[META26:![0-9]+]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr [[BLOB]], i64 976
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 16 dereferenceable(24) [[TMP0]], i8 5, i64 24, i1 false), !dbg [[META26]], !DIAssignID [[DIASSIGNID27:![0-9]+]]
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 16 dereferenceable(10) [[BLOB]], i8 5, i64 10, i1 false), !dbg [[META26]], !DIAssignID [[DIASSIGNID27]]
; CHECK-NEXT:      #dbg_assign(i1 undef, [[META20]], !DIExpression(), [[DIASSIGNID27]], ptr [[BLOB]], !DIExpression(), [[META26]])
; CHECK-NEXT:      #dbg_assign(i1 undef, [[META20]], !DIExpression(DW_OP_LLVM_fragment, 80, 7920), [[META28:![0-9]+]], ptr poison, !DIExpression(), [[META26]])
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[BLOB]], i64 10, !dbg [[META26]]
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr noundef nonnull align 2 dereferenceable(980) [[ADD_PTR]], i8 3, i64 980, i1 false), !dbg [[META26]], !DIAssignID [[DIASSIGNID29:![0-9]+]]
; CHECK-NEXT:      #dbg_assign(i1 undef, [[META20]], !DIExpression(DW_OP_LLVM_fragment, 80, 7840), [[DIASSIGNID29]], ptr [[ADD_PTR]], !DIExpression(), [[META26]])
; CHECK-NEXT:    call void @_Z3escPc(ptr noundef nonnull [[BLOB]]), !dbg [[META26]]
; CHECK-NEXT:    ret void, !dbg [[META26]]
;
entry:
  %blob = alloca [1000 x i8], align 16, !DIAssignID !33
  #dbg_assign(i1 undef, !28, !DIExpression(), !33, ptr %blob, !DIExpression(), !34)
  call void @llvm.memset.p0.i64(ptr noundef nonnull align 16 dereferenceable(1000) %blob, i8 5, i64 1000, i1 false), !dbg !34, !DIAssignID !35
  #dbg_assign(i1 undef, !28, !DIExpression(), !35, ptr %blob, !DIExpression(), !34)
  %add.ptr = getelementptr inbounds i8, ptr %blob, i64 10, !dbg !34
  call void @llvm.memset.p0.i64(ptr noundef nonnull align 2 dereferenceable(980) %add.ptr, i8 3, i64 980, i1 false), !dbg !34, !DIAssignID !36
  #dbg_assign(i1 undef, !28, !DIExpression(DW_OP_LLVM_fragment, 80, 7840), !36, ptr %add.ptr, !DIExpression(), !34)
  call void @_Z3escPc(ptr noundef nonnull %blob), !dbg !34
  ret void, !dbg !34
}

declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)

declare void @_Z3escPc(ptr noundef)

declare void @llvm.dbg.assign(metadata, metadata, metadata, metadata, metadata, metadata)

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!15, !16, !21}
!llvm.ident = !{!22}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 18.0.0", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, imports: !2, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "debuginfo.cpp", directory: "/")
!2 = !{!3}
!3 = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: !4, entity: !5, file: !1, line: 81)
!4 = !DINamespace(name: "std", scope: null)
!5 = !DISubprogram(name: "memset", scope: !1, file: !1, line: 61, type: !7, flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
!7 = !DISubroutineType(types: !8)
!8 = !{!9, !9, !10, !11}
!9 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
!10 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!11 = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: !1, line: 13, baseType: !13)
!13 = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
!15 = !{i32 7, !"Dwarf Version", i32 5}
!16 = !{i32 2, !"Debug Info Version", i32 3}
!21 = !{i32 7, !"debug-info-assignment-tracking", i1 true}
!22 = !{!"clang version 18.0.0"}
!23 = distinct !DISubprogram(name: "overwrite_middle_local", linkageName: "_Z22overwrite_middle_localv", scope: !1, file: !1, line: 3, type: !25, scopeLine: 3, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !27)
!25 = !DISubroutineType(types: !26)
!26 = !{null}
!27 = !{!28}
!28 = !DILocalVariable(name: "blob", scope: !23, file: !1, line: 4, type: !29)
!29 = !DICompositeType(tag: DW_TAG_array_type, baseType: !30, size: 8000, elements: !31)
!30 = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
!31 = !{!32}
!32 = !DISubrange(count: 1000)
!33 = distinct !DIAssignID()
!34 = !DILocation(line: 0, scope: !23)
!35 = distinct !DIAssignID()
!36 = distinct !DIAssignID()
;.
; CHECK: [[META0:![0-9]+]] = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: [[META1:![0-9]+]], producer: "{{.*}}clang version {{.*}}", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, imports: [[META2:![0-9]+]], splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META1]] = !DIFile(filename: "debuginfo.cpp", directory: {{.*}})
; CHECK: [[META2]] = !{[[META3:![0-9]+]]}
; CHECK: [[META3]] = !DIImportedEntity(tag: DW_TAG_imported_declaration, scope: [[META4:![0-9]+]], entity: [[META5:![0-9]+]], file: [[META1]], line: 81)
; CHECK: [[META4]] = !DINamespace(name: "std", scope: null)
; CHECK: [[META5]] = !DISubprogram(name: "memset", scope: [[META1]], file: [[META1]], line: 61, type: [[META6:![0-9]+]], flags: DIFlagPrototyped, spFlags: DISPFlagOptimized)
; CHECK: [[META6]] = !DISubroutineType(types: [[META7:![0-9]+]])
; CHECK: [[META7]] = !{[[META8:![0-9]+]], [[META8]], [[META9:![0-9]+]], [[META10:![0-9]+]]}
; CHECK: [[META8]] = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: null, size: 64)
; CHECK: [[META9]] = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
; CHECK: [[META10]] = !DIDerivedType(tag: DW_TAG_typedef, name: "size_t", file: [[META1]], line: 13, baseType: [[META11:![0-9]+]])
; CHECK: [[META11]] = !DIBasicType(name: "unsigned long", size: 64, encoding: DW_ATE_unsigned)
; CHECK: [[DBG16]] = distinct !DISubprogram(name: "overwrite_middle_local", linkageName: "_Z22overwrite_middle_localv", scope: [[META1]], file: [[META1]], line: 3, type: [[META17:![0-9]+]], scopeLine: 3, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: [[META0]], retainedNodes: [[META19:![0-9]+]])
; CHECK: [[META17]] = !DISubroutineType(types: [[META18:![0-9]+]])
; CHECK: [[META18]] = !{null}
; CHECK: [[META19]] = !{[[META20]]}
; CHECK: [[META20]] = !DILocalVariable(name: "blob", scope: [[DBG16]], file: [[META1]], line: 4, type: [[META21:![0-9]+]])
; CHECK: [[META21]] = !DICompositeType(tag: DW_TAG_array_type, baseType: [[META22:![0-9]+]], size: 8000, elements: [[META23:![0-9]+]])
; CHECK: [[META22]] = !DIBasicType(name: "char", size: 8, encoding: DW_ATE_signed_char)
; CHECK: [[META23]] = !{[[META24:![0-9]+]]}
; CHECK: [[META24]] = !DISubrange(count: 1000)
; CHECK: [[DIASSIGNID25]] = distinct !DIAssignID()
; CHECK: [[META26]] = !DILocation(line: 0, scope: [[DBG16]])
; CHECK: [[DIASSIGNID27]] = distinct !DIAssignID()
; CHECK: [[META28]] = distinct !DIAssignID()
; CHECK: [[DIASSIGNID29]] = distinct !DIAssignID()
;.
