// RUN: cir-opt %s -cir-to-mlir -o - | FileCheck %s -check-prefix=MLIR
// RUN: cir-opt %s -cir-to-mlir -cir-mlir-to-llvm -o - | mlir-translate -mlir-to-llvmir | FileCheck %s -check-prefix=LLVM

!u32i = !cir.int<u, 32>
module {
  cir.func @foo() -> !u32i {
    %0 = cir.alloca !u32i, !cir.ptr<!u32i>, ["x", init] {alignment = 4 : i64}
    %1 = cir.const #cir.int<1> : !u32i
    cir.store %1, %0 : !u32i, !cir.ptr<!u32i>
    %2 = cir.load %0 : !cir.ptr<!u32i>, !u32i
    cir.return %2 : !u32i
  }
}

//      MLIR: module {
// MLIR-NEXT:   func @foo() -> i32 {
// MLIR-NEXT:     [[alloca:%[a-z0-9]+]] = memref.alloca() {alignment = 4 : i64} : memref<1xi32>
// MLIR-NEXT:     %c1_i32 = arith.constant 1 : i32
// MLIR-NEXT:     [[const0:%[a-z0-9_]+]] = arith.constant 0 : index
// MLIR-NEXT:     memref.store %c1_i32, [[alloca]][[[const0]]] : memref<1xi32>
// MLIR-NEXT:     [[const0_1:%[a-z0-9_]+]] = arith.constant 0 : index
// MLIR-NEXT:     [[load:%[a-z0-9]+]] = memref.load [[alloca]][[[const0_1]]] : memref<1xi32>
// MLIR-NEXT:     return [[load]] : i32
// MLIR-NEXT:   }
// MLIR-NEXT: }

//      LLVM: define i32 @foo()
// LLVM-NEXT:   %1 = alloca i32, i64
// LLVM-NEXT:   %2 = insertvalue { ptr, ptr, i64, [1 x i64], [1 x i64] } poison, ptr %1, 0
// LLVM-NEXT:   %3 = insertvalue { ptr, ptr, i64, [1 x i64], [1 x i64] } %2, ptr %1, 1
// LLVM-NEXT:   %4 = insertvalue { ptr, ptr, i64, [1 x i64], [1 x i64] } %3, i64 0, 2
// LLVM-NEXT:   %5 = insertvalue { ptr, ptr, i64, [1 x i64], [1 x i64] } %4, i64 1, 3, 0
// LLVM-NEXT:   %6 = insertvalue { ptr, ptr, i64, [1 x i64], [1 x i64] } %5, i64 1, 4, 0
// LLVM-NEXT:   %7 = extractvalue { ptr, ptr, i64, [1 x i64], [1 x i64] } %6, 1
// LLVM-NEXT:   %8 = getelementptr inbounds nuw i32, ptr %7, i64 0
// LLVM-NEXT:   store i32 1, ptr %8, align 4
// LLVM-NEXT:   %9 = extractvalue { ptr, ptr, i64, [1 x i64], [1 x i64] } %6, 1
// LLVM-NEXT:   %10 = getelementptr inbounds nuw i32, ptr %9, i64 0
// LLVM-NEXT:   %11 = load i32, ptr %10, align 4
// LLVM-NEXT:   ret i32 %11
