// RUN: cir-opt %s -cir-to-mlir -o - | FileCheck %s -check-prefix=MLIR
// RUN: cir-opt %s -cir-to-mlir -cir-mlir-to-llvm -o - | mlir-translate -mlir-to-llvmir | FileCheck %s -check-prefix=LLVM

!u32i = !cir.int<u, 32>
module {
  cir.func @foo() {
    cir.scope {
      %0 = cir.alloca !u32i, !cir.ptr<!u32i>, ["a", init] {alignment = 4 : i64}
      %1 = cir.const #cir.int<4> : !u32i
      cir.store %1, %0 : !u32i, !cir.ptr<!u32i>
    }
    cir.return
  }

//      MLIR: func.func @foo()
// MLIR-NEXT:   memref.alloca_scope
// MLIR-NEXT:     %alloca = memref.alloca() {alignment = 4 : i64} : memref<1xi32>
// MLIR-NEXT:     %c4_i32 = arith.constant 4 : i32
// MLIR-NEXT:     %c0 = arith.constant 0 : index
// MLIR-NEXT:     memref.store %c4_i32, %alloca[%c0] : memref<1xi32>
// MLIR-NEXT:   }
// MLIR-NEXT:   return

// LLVM:      define void @foo() {
// LLVM-NEXT:   %1 = call ptr @llvm.stacksave.p0()
// LLVM-NEXT:   br label %2
// LLVM-EMPTY:
// LLVM-NEXT: 2:
// LLVM-NEXT:   %3 = alloca i32, i64 1, align 4
// LLVM:        store i32 4, ptr {{.*}}, align 4
// LLVM-NEXT:   call void @llvm.stackrestore.p0(ptr %1)
// LLVM-NEXT:   br label %[[BRANCH:[0-9]+]]
// LLVM-EMPTY:
// LLVM-NEXT: [[BRANCH]]:
// LLVM-NEXT:   ret void
// LLVM-NEXT: }

  // Should drop empty scopes.
  cir.func @empty_scope() {
    cir.scope {
    }
    cir.return
  }
  //      MLIR: func.func @empty_scope()
  // MLIR-NEXT:   return
  // MLIR-NEXT: }

  // LLVM: define void @empty_scope()
  // LLVM:   ret void
}
