// RUN: cir-opt %s -cir-to-mlir -o %t.mlir
// RUN: FileCheck %s --input-file %t.mlir

module {
  cir.func @foo() {
    %1 = cir.const #cir.fp<1.0> : !cir.float
    %2 = cir.const #cir.fp<2.0> : !cir.double
    %3 = cir.const #cir.fp<3.0> : !cir.long_double<!cir.f80>
    %4 = cir.const #cir.fp<4.0> : !cir.long_double<!cir.double>
    %5 = cir.tan %1 : !cir.float
    %6 = cir.tan %2 : !cir.double
    %7 = cir.tan %3 : !cir.long_double<!cir.f80>
    %8 = cir.tan %4 : !cir.long_double<!cir.double>
    cir.return
  }
}

// CHECK:      module {
// CHECK-NEXT:   func.func @foo() {
// CHECK-NEXT:     %[[C0:.+]] = arith.constant 1.000000e+00 : f32
// CHECK-NEXT:     %[[C1:.+]] = arith.constant 2.000000e+00 : f64
// CHECK-NEXT:     %[[C2:.+]] = arith.constant 3.000000e+00 : f80
// CHECK-NEXT:     %[[C3:.+]] = arith.constant 4.000000e+00 : f64
// CHECK-NEXT:     %{{.+}} = math.tan %[[C0]] : f32
// CHECK-NEXT:     %{{.+}} = math.tan %[[C1]] : f64
// CHECK-NEXT:     %{{.+}} = math.tan %[[C2]] : f80
// CHECK-NEXT:     %{{.+}} = math.tan %[[C3]] : f64
// CHECK-NEXT:     return
// CHECK-NEXT:   }
// CHECK-NEXT: }
