// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -cc1 -triple amdgcn-amd-amdhsa -emit-llvm -fsanitize=function %s -o - | FileCheck %s

// CHECK-LABEL: define dso_local void @function(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] !func_sanitize [[META2:![0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    ret void
//
void function() {}

// CHECK-LABEL: define dso_local amdgpu_kernel void @kernel(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    call void @function() #[[ATTR1:[0-9]+]]
// CHECK-NEXT:    ret void
//
[[clang::device_kernel]] void kernel() { function(); }
//.
// CHECK: [[META2]] = !{i32 -1056584962, i32 1717976574}
//.
