name: Build Portable Linux Artifacts

on:
  workflow_dispatch:
    inputs:
      amdgpu_families:
        type: string
        default: gfx94X-dcgpu
      artifact_group:
        type: string
        default: gfx94X-dcgpu
      build_variant_label:
        type: string
        description: "A label for the build variant (ex: 'release', 'asan')"
        default: "release"
      build_variant_suffix:
        type: string
        description: "The build variant suffix (ex: 'asan' suffix -> 'gfx94X-dcgpu-asan')"
        default: ""
      build_variant_cmake_preset:
        type: string
        description: "The name of the cmake preset to use for this build variant, matching an entry in CMakePresets.json (ex: 'linux-release-asan')"
        default: ""
      package_version:
        type: string
        default: ADHOCBUILD
      expect_failure:
        type: boolean
        default: false
      extra_cmake_options:
        type: string

  workflow_call:
    inputs:
      package_version:
        type: string
        default: ADHOCBUILD
      amdgpu_families:
        type: string
      artifact_group:
        type: string
      build_variant_label:
        type: string
      build_variant_suffix:
        type: string
      build_variant_cmake_preset:
        type: string
      expect_failure:
        type: boolean
      extra_cmake_options:
        type: string
      test_type:
        type: string

# See the details regarding permissions from the link:
# https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc
permissions:
  contents: read

jobs:
  build_portable_linux_artifacts:
    name: Build (xfail ${{ inputs.expect_failure }})
    # azure-linux-scale-rocm are used for regular CI builds
    # azure-linux-scale-rocm-heavy are used for CI builds that require more resources (ex: ASAN builds)
    runs-on: ${{ inputs.build_variant_label == 'asan' && 'azure-linux-u2404-hx176-cpu-rocm' || 'azure-linux-scale-rocm' }}
    continue-on-error: ${{ inputs.expect_failure }}
    timeout-minutes: 720 # 12 hour timeout
    permissions:
      id-token: write
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:6e8242d347af7e0c43c82d5031a3ac67b669f24898ea8dc2f1d5b7e4798b66bd
      options: -v /runner/config:/home/awsconfig/
    env:
      AWS_SHARED_CREDENTIALS_FILE: /home/awsconfig/credentials.ini
      CACHE_DIR: ${{ github.workspace }}/.container-cache
      # The ccache.conf will be written by setup_ccache.py before this gets used.
      CCACHE_CONFIGPATH: ${{ github.workspace }}/.ccache/ccache.conf
      AMDGPU_FAMILIES: ${{ inputs.amdgpu_families }}
      TEATIME_FORCE_INTERACTIVE: 0
      IS_PR_FROM_FORK: ${{ github.event.pull_request.head.repo.fork }}
    steps:
      - name: Checkout TheRock repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: "ROCm/TheRock"
          ref: 'compiler/amd-staging'

      - name: Update Submodule Pointer to the PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git config --global --add safe.directory $PWD
          # Fetch the latest commit SHA from the PR branch          
          PR_SHA=${{ github.event.pull_request.head.sha }}
          # Update the submodule pointer using cacheinfo
          git update-index --cacheinfo 160000,$PR_SHA,compiler/amd-llvm
          git config --global user.email "z1-cciauto@amd.com"
          git config --global user.name "Z1 cciauto"
          git commit -m "Update submodule reference for compiler/amd-llvm"
          # Verify the pointer update
          git submodule status
          git submodule

      - name: Download LLVM, SPIRV and HIPIFY PR's stored in file
        if: ${{ github.event_name == 'workflow_dispatch' }}
        continue-on-error: true 
        uses: actions/download-artifact@v4
        with:
          name: multiple-pr-build-params
          path: .

      - name: Check for parameterised PR trigger
        id: check_parameterised_trigger
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          if [ -f "./${{ github.run_id }}_PR_params.env" ]; then
            echo "parameterised_trigger=true" >> "$GITHUB_OUTPUT"
          else
            echo "parameterised_trigger=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Source the multiple PR's of params
        if: ${{ github.event_name == 'workflow_dispatch' && steps.check_parameterised_trigger.outputs.parameterised_trigger == 'true' }}
        run: |
          set -a
          source ./${{ github.run_id }}_PR_params.env
          set +a
          echo "LLVM_PR_URL=$LLVM_PR_URL" >> "$GITHUB_ENV"
          echo "SPIRV_PR_URL=$SPIRV_PR_URL" >> "$GITHUB_ENV"
          echo "HIPIFY_PR_URL=$HIPIFY_PR_URL" >> "$GITHUB_ENV"

      - name: Update submodule pointers from provided parameter PR values
        if: ${{ github.event_name == 'workflow_dispatch' && steps.check_parameterised_trigger.outputs.parameterised_trigger == 'true' }}
        run: |
          git config --global --add safe.directory "$PWD"
          # Function to get SHA with git-ls
          get_pr_sha() {
             local pr_url="$1"
             local base_repo_url=$(echo "$pr_url" | sed 's|/pull/.*||')
             local pr_num=$(echo "$pr_url" | sed 's|.*/pull/||')
             git ls-remote "${base_repo_url}.git" "refs/pull/${pr_num}/head" | awk '{print $1}'
          }
        
          # LLVM PR
          LLVM_SHA="$(get_pr_sha "$LLVM_PR_URL")"
          echo "LLVM head SHA: $LLVM_SHA"
          git update-index --cacheinfo 160000,"$LLVM_SHA","compiler/amd-llvm"
        
          # SPIRV PR
          if [[ -n "$SPIRV_PR_URL" ]]; then
              SPIRV_SHA="$(get_pr_sha "$SPIRV_PR_URL")"
              echo "SPIRV head SHA: $SPIRV_SHA"
              git update-index --cacheinfo 160000,"$SPIRV_SHA","compiler/spirv-llvm-translator"
          else
              SPIRV_SHA="$(git ls-remote https://github.com/ROCm/SPIRV-LLVM-Translator.git refs/heads/amd-staging | awk '{print $1}')"
              echo "SPIRV PR NOT Passed, defaulting to the amd-staging tip : $SPIRV_SHA"
              git update-index --cacheinfo 160000,"$SPIRV_SHA","compiler/spirv-llvm-translator"
          fi

          # HIPIFY PR
          if [[ -n "$HIPIFY_PR_URL" ]]; then
              HIPIFY_SHA="$(get_pr_sha "$HIPIFY_PR_URL")"
              echo "HIPIFY head SHA: $HIPIFY_SHA"
              git update-index --cacheinfo 160000,"$HIPIFY_SHA","compiler/hipify"
          else
              HIPIFY_SHA="$(git ls-remote https://github.com/ROCm/HIPIFY.git refs/heads/amd-staging | awk '{print $1}')"
              echo "HIPIFY PR NOT Passed, defaulting to the amd-staging tip : $HIPIFY_SHA"
              git update-index --cacheinfo 160000,"$HIPIFY_SHA","compiler/hipify"
          fi
          git config --global user.email "z1-cciauto@amd.com"
          git config --global user.name "Z1 cciauto"
          git commit -m "Update submodule references from PR URLs"
          git submodule status
          git submodule
 
      - name: Install python deps
        run: |
          pip install -r requirements.txt

      # safe.directory must be set before Runner Health Status
      - name: Adjust git config
        run: |
          git config --global --add safe.directory $PWD
          git config fetch.parallel 10

      # TODO: We shouldn't be using a cache on actual release branches, but it
      # really helps for iteration time.
      - name: Setup ccache
        run: |
          ./build_tools/setup_ccache.py \
            --config-preset "github-oss-presubmit" \
            --dir "$(dirname $CCACHE_CONFIGPATH)" \
            --local-path "$CACHE_DIR/ccache"

      - name: Runner health status
        run: |
          ./build_tools/health_status.py

      - name: Remove ununsed existing patchces
        run: |
          rm -fv patches/amd-mainline/llvm-project/0001-Ensure-to-use-libamdhip64-with-major-version.patch

      - name: Fetch sources
        timeout-minutes: 30
        run: |
          ./build_tools/fetch_sources.py --jobs 12

      - name: TheRock and llvm SHA
        if: ${{ github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' }}
        run: |
             git config --global --add safe.directory $PWD
             git log --oneline -1
             ls -l compiler/amd-llvm
             cd compiler/amd-llvm/llvm  
             ls -l
             git log --oneline -3
             cd -

      - name: Configure PR Projects
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.test_type != 'full') }}
        env:
          cmake_preset: ${{ inputs.build_variant_cmake_preset }}
          amdgpu_families: ${{ inputs.amdgpu_families }}
          package_version: ${{ inputs.package_version }}
          extra_cmake_options: "-DTHEROCK_ENABLE_ALL=OFF -DTHEROCK_ENABLE_COMPILER=ON  -DTHEROCK_ENABLE_CORE_RUNTIME=ON -DTHEROCK_ENABLE_HIP_RUNTIME=ON -DTHEROCK_ENABLE_RCCL=ON -DTHEROCK_ENABLE_PRIM=ON -DTHEROCK_ENABLE_BLAS=ON -DTHEROCK_ENABLE_RAND=ON -DTHEROCK_ENABLE_SOLVER=ON -DTHEROCK_ENABLE_SPARSE=ON -DTHEROCK_ENABLE_SYSDEPS=OFF  -DTHEROCK_ENABLE_COMPOSABLE_KERNEL=OFF -DTHEROCK_ENABLE_OCL_RUNTIME=ON  -DTHEROCK_ENABLE_MATH_LIBS=ON -DLLVM_SMREV_REPO='' -DLLVM_SMREV_REVISION=''"
          BUILD_DIR: build
        run: |
          python3 build_tools/github_actions/build_configure.py --manylinux

      - name: Configure All Projects
        if: ${{ github.event_name != 'pull_request' && inputs.test_type == 'full' }}
        env:
          cmake_preset: ${{ inputs.build_variant_cmake_preset }}
          amdgpu_families: ${{ inputs.amdgpu_families }}
          package_version: ${{ inputs.package_version }}
          extra_cmake_options: ${{ inputs.extra_cmake_options }}
          BUILD_DIR: build
        run: |
          python3 build_tools/github_actions/build_configure.py --manylinux

      - name: Build therock-archives and therock-dist
        run: |
          cmake --build build --target therock-archives therock-dist -- -j32

      - name: Test Packaging
        if: ${{ github.event.repository.name == 'TheRock' }}
        run: |
          ctest --test-dir build --output-on-failure

      - name: Report
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          if [ -d "./build" ]; then
            echo "Full SDK du:"
            echo "------------"
            du -h -d 1 build/dist/rocm
            echo "Artifact Archives:"
            echo "------------------"
            ls -lh build/artifacts/*.tar.xz
            echo "Artifacts:"
            echo "----------"
            du -h -d 1 build/artifacts
            echo "CCache Stats:"
            echo "-------------"
            ccache -s -v
            tail -v -n +1 .ccache/compiler_check_cache/* > build/logs/ccache_compiler_check_cache.log
          else
            echo "[ERROR] Build directory ./build does not exist. Skipping report!"
            echo "        This should only happen if the CI is cancelled before the build step."
            exit 1
          fi

      # Analyze ninja build log to generate per-component timing report
      - name: Analyze Build Times
        if: ${{ !cancelled() }}
        run: |
          python3 build_tools/analyze_build_times.py --build-dir build

      - name: Configure AWS Credentials for non-forked repos
        if: ${{ github.repository == 'ROCm/TheRock' }}
        uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-ci-external

      - name: Post Build Upload
        if: always()
        run: |
          python3 build_tools/github_actions/post_build_upload.py \
            --run-id ${{ github.run_id }} \
            --artifact-group "${{ inputs.artifact_group }}" \
            --build-dir build \
            --upload
