name: Commit Access Review

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 7 1 * *'

permissions:
  contents: read
  issues: write

jobs:
  commit-access-review:
    if: github.repository_owner == 'llvm'
    environment: main-branch-only
    runs-on: ubuntu-24.04
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      
      - name: Install dependencies
        run: |
          pip install --require-hashes -r ./llvm/utils/git/requirements.txt

      - id: app-token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3  # v3.1.1
        with:
          app-id: ${{ secrets.LLVM_TOKEN_GENERATOR_CLIENT_ID }}
          private-key: ${{ secrets.LLVM_TOKEN_GENERATOR_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          permission-members: read
          permission-contents: read
      
      - name: Run Script
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          python3 .github/workflows/commit-access-review.py $GITHUB_TOKEN

      - name: Upload Triage List
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: triagers
          path: triagers.log

      - name: Create the issue
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # There is a limit to the number of mentions you can have in one comment, so
          # we need to limit the number of users we mention.
          cat triagers.log | head -n 25 | python3 .github/workflows/commit-create-issue.py $GITHUB_TOKEN
