name: HLSL Tests

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - llvm/**/DirectX/**
      - .github/workflows/hlsl*
      - clang/*HLSL*/**/*
      - clang/**/*HLSL*
      - llvm/**/Frontend/HLSL/**/*

jobs:
  HLSL-Tests:
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - windows-2022

    uses: ./.github/workflows/hlsl-test-all.yaml
    with:
      SKU: ${{ matrix.runs-on }}
      TestTarget: check-hlsl-clang-warp-d3d12
      LLVM-ref: ${{ github.ref }}
