name: LLVM Premerge Checks

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      # When a PR is closed, we still start this workflow, but then skip
      # all the jobs, which makes it effectively a no-op.  The reason to
      # do this is that it allows us to take advantage of concurrency groups
      # to cancel in progress CI jobs whenever the PR is closed.
      - closed
  push:
    branches:
      - 'main'
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  premerge-checks-linux:
    name: Linux Premerge Checks (Test Only - Please Ignore Results)
    defaults:
      run:
        # The premerge Linux docker instance keeps a pristine clone of LLVM in
        # /home/gha/llvm-project; that should be used as our main workdir.
        working-directory: /home/gha/llvm-project
    if: >-
        github.repository_owner == 'llvm' &&
        (github.event_name != 'pull_request' || github.event.action != 'closed')
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/gburgessiv/llvm-ci-with-checkout:latest
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          path: /home/gha/llvm-project
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@a1209f81afb8c005c13b4296c32e363431bffea5 # v1.2.17
        with:
          max-size: "2000M"
      - name: Build and Test
        # Mark the job as a success even if the step fails so that people do
        # not get notified while the new premerge pipeline is in an
        # experimental state.
        # TODO(boomanaiden154): Remove this once the pipeline is stable and we
        # are ready for people to start recieving notifications.
        continue-on-error: true
        run: |
          ls /home/gha
          exit 1
