name: CI Checks

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      # When a PR is closed, we still start this workflow, but then skip
      # all the jobs, which makes it effectively a no-op.  The reason to
      # do this is that it allows us to take advantage of concurrency groups
      # to cancel in progress CI jobs whenever the PR is closed.
      - closed
  push:
    branches:
      - 'release/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  premerge-checks-windows:
    name: Build and Test Windows ${{ matrix.index }}
    strategy:
      matrix:
        index:
         - 1
         - 2
         - 3
         - 4
         - 5
         - 6
         - 7
         - 8
         - 9
         - 10
         - 11
         - 12
         - 13
         - 14
         - 15
         - 16
         - 17
         - 18
         - 19
         - 20
         - 21
         - 22
         - 23
         - 24
         - 25
         - 26
         - 27
         - 28
         - 29
         - 30
    if: >-
        github.repository_owner == 'llvm' &&
        (github.event_name != 'pull_request' || github.event.action != 'closed')
    runs-on: llvm-premerge-windows-2022-runners
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout LLVM
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 2
      - name: Compute Projects
        id: vars
        run: |
          echo "windows-projects=clang;clang-tools-extra;lld;llvm;mlir;polly" >> $GITHUB_OUTPUT
          echo "windows-check-targets=all llvm-test-depends clang-test-depends lld-test-depends" >> $GITHUB_OUTPUT
          echo "windows-runtimes=" >> $GITHUB_OUTPUT
          echo "windows-runtimes-check-targets=" >> $GITHUB_OUTPUT
      - name: Build and Test
        timeout-minutes: 180
        if: ${{ steps.vars.outputs.windows-projects != '' }}
        shell: cmd
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          call C:\\BuildTools\\Common7\\Tools\\VsDevCmd.bat -arch=amd64 -host_arch=amd64
          # See the comments above in the Linux job for why we define each of
          # these environment variables.
          bash -c "export SCCACHE_GCS_BUCKET=$CACHE_GCS_BUCKET; export SCCACHE_GCS_RW_MODE=READ_WRITE; export SCCACHE_IDLE_TIMEOUT=0; mkdir artifacts; SCCACHE_LOG=info SCCACHE_ERROR_LOG=$(pwd)/artifacts/sccache.log sccache --start-server; .ci/monolithic-windows.sh \"${{ steps.vars.outputs.windows-projects }}\" \"${{ steps.vars.outputs.windows-check-targets }}\" \"${{ steps.vars.outputs.windows-runtimes }}\" \"${{ steps.vars.outputs.windows-runtimes-check-targets }}\""
