name: Release llvm-testing-tools

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '.github/workflows/release-llvm-testing-tools.yml'
      - 'llvm/utils/llvm-testing-tools/**'

jobs:
  build-package:
    name: Build Package
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-26]
    runs-on: ${{ matrix.os }}
    if: github.repository == 'llvm/llvm-project'
    steps:
      - name: Fetch LLVM sources
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Build Binaries
        run: |
          mkdir build
          cd build
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ../llvm
          ninja split-file FileCheck
      - name: Build Package
        shell: bash
        run: |
          pip3 install --break-system-packages build==1.4.2
          cd ./llvm/utils/llvm-testing-tools
          mkdir ./src/llvm_testing_tools/binaries
          cp ../../../build/bin/FileCheck ./src/llvm_testing_tools/binaries/FileCheck
          cp ../../../build/bin/split-file ./src/llvm_testing_tools/binaries/split-file
          python3 -m build
      - name: Upload Packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages-${{ matrix.os }}
          path: ./llvm/utils/llvm-testing-tools/dist/*
