name: Ripple CI Tests

permissions:
  contents: read

on:
  push:
    branches:
      - ripple
      - ripple_rebase
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - ripple
    paths:
      - "llvm/lib/**"
      - "llvm/include/**"
      - "llvm/test/Transforms/Ripple/**"
      - "clang/lib/**"
      - "clang/include/**"
      - "clang/test/Ripple/**"
      - "compiler-rt/lib/ripple/**"
      - ".github/**"

env:
  LIT_OPTS: --no-progress-bar -v --show-unsupported --show-xfail --time-tests

jobs:
  build_and_test:
    if: github.repository_owner == 'Ripple-Programming'
    name: Build and Test ripple
    runs-on: [ubuntu-24.04]
    strategy:
      matrix:
        targets:
          - { arch: X86, triple: x86_64-pc-linux-gnu }
          - { arch: AArch64, triple: aarch64-linux-gnu }

    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Configure
        run: |
          cmake -G Ninja -S llvm -B build \
            ${CMAKE_HOST_OPT-} \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD=${{ matrix.targets.arch }} \
            -DLLVM_DEFAULT_TARGET_TRIPLE=${{ matrix.targets.triple }}

      - name: Clang Ripple Lit Tests
        run: cmake --build build --target check-clang-ripple

      - name: Clang AST Lit Tests (Ripple Parallel)
        run: cmake --build build --target check-clang-ast

      - name: Ripple LLVM Lit Tests
        run: cmake --build build --target check-llvm-transforms-ripple

  hexagon_build_and_test:
    if: github.repository_owner == 'Ripple-Programming'
    name: Build and Test ripple
    runs-on: [ubuntu-24.04]
    strategy:
      fail-fast: true
      matrix:
        targets:
          - arch: Hexagon
            triple: hexagon-unknown-unknown-elf
            cxx_flags: -stdlib=libc++ -D_USE_GENERIC_XLOCALE_SHIMS -D_LIBCPP_PROVIDES_DEFAULT_RUNE_TABLE -D_C99 -D_C_AS_CPP -D_HAS_GENERIC_TEMPLATES=0
            sysroot: $HEXAGON_SDK/tools/HEXAGON_Tools/19.0.04/Tools/target/hexagon

    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Clone eld
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          repository: qualcomm/eld
          path: eld

      - name: Configure
        run: |
          cmake -G Ninja -S llvm -B build \
            ${CMAKE_HOST_OPT-} \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_EXTERNAL_PROJECTS=eld \
            -DLLVM_EXTERNAL_ELD_SOURCE_DIR=eld \
            -DLLVM_TARGETS_TO_BUILD=${{ matrix.targets.arch }} \
            -DLLVM_DEFAULT_TARGET_TRIPLE=${{ matrix.targets.triple }}

      - name: Build Ripple Compiler
        run: cmake --build build

      - name: Install Ripple Compiler
        run: cmake --install build --prefix ${{ github.workspace }}/install

      - name: Configure compiler-rt
        run: |
          cmake -G Ninja -S compiler-rt -B build-compiler-rt \
            -DLLVM_CMAKE_DIR=${{ github.workspace }}/install \
            -DCMAKE_SYSTEM_NAME=Linux \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_C_COMPILER=${{ github.workspace }}/install/bin/clang \
            -DCMAKE_CXX_COMPILER=${{ github.workspace }}/install/bin/clang++ \
            -DCOMPILER_RT_OS_DIR= \
            -DCOMPILER_RT_BUILD_BUILTINS=OFF \
            -DCOMPILER_RT_BUILD_RIPPLE=ON \
            -DCOMPILER_RT_BUILD_CRT=OFF \
            -DCOMPILER_RT_BUILD_CTX_PROFILE=OFF \
            -DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
            -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
            -DCOMPILER_RT_BUILD_MEMPROF=OFF \
            -DCOMPILER_RT_BUILD_ORC=OFF \
            -DCOMPILER_RT_BUILD_PROFILE=OFF \
            -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
            -DCOMPILER_RT_BUILD_XRAY=OFF \
            -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
            -DCMAKE_TRY_COMPILE_TARGET_TYPE=STATIC_LIBRARY \
            -DCMAKE_C_COMPILER_TARGET=${{ matrix.targets.triple }} \
            -DCMAKE_CXX_COMPILER_TARGET=${{ matrix.targets.triple }} \
            -DCMAKE_CXX_FLAGS="${{ matrix.targets.cxx_flags }}" \
            -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=eld" \
            -DCMAKE_SYSROOT="${{ matrix.targets.sysroot }}"

      - name: Build Ripple compiler-rt
        run: cmake --build build-compiler-rt

      - name: Install Ripple compiler-rt
        run: cmake --install build-compiler-rt --prefix $(${{ github.workspace }}/install/bin/clang --print-resource-dir)

      - name: Clang Ripple Lit Tests
        run: cmake --build build --target check-clang-ripple

      - name: Clang AST Lit Tests (Ripple Parallel)
        run: cmake --build build --target check-clang-ast

      - name: Ripple LLVM Lit Tests
        run: cmake --build build --target check-llvm-transforms-ripple
