name: Ripple CI Tests

permissions:
  contents: read

on:
  push:
    branches:
      - ripple
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - ripple

jobs:
  build_and_test:
    if: github.repository_owner == 'Ripple-Programming'
    name: Build and Test ripple
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        targets:
          - { arch: X86, triple: x86_64-pc-linux-gnu }
          - { arch: Hexagon, triple: hexagon-unknown-elf }
          - { arch: AArch64, triple: aarch64-linux-gnu }
        include:
          - cc: clang-18
            cxx: clang++-18

    steps:
      - name: Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Install test requirements
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6-dev

      - name: Configure
        run: |
          cmake -G Ninja -S ${{ github.workspace }}/llvm -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            -DCMAKE_C_COMPILER=${{ matrix.cc }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx }} \
            -DLLVM_USE_LINKER=lld \
            -DLLVM_ENABLE_PROJECTS="clang" \
            -DLLVM_TARGETS_TO_BUILD=${{ matrix.targets.arch }} \
            -DLLVM_DEFAULT_TARGET_TRIPLE=${{ matrix.targets.triple }} \
            -DLLVM_PARALLEL_LINK_JOBS=1

      - name: Ripple Clang Lit Tests
        run: |
          cmake --build build --target check-clang-ripple
          cmake --build build --target check-clang-ast

      - name: Ripple LLVM Lit Tests
        run: cmake --build build --target check-llvm-transforms-ripple
