on:
  push:

jobs:
  wix-test:
    runs-on: windows-11-arm
    steps:
      - shell: bash
        run: |
          dotnet tool install --global wix
          echo "int main(int argc, char **argv) { }" > test.c
          echo "cmake_minimum_required(VERSION 3.20.0)" > CMakeLists.txt
          echo "add_executable(test test.c)" >> CMakeLists.txt
          echo "include(CPack)" >> CMakeLists.txt
          cmake -G Ninja -S . -B build -DCPACK_GENERATOR=WIX
          ninja -C build package


