# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            const_i32
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[CONST_I32_:%[0-9]+]]:i32 = CONST_I32 0, implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[CONST_I32_]], implicit-def $arguments
    %0:i32regbank(s32) = G_CONSTANT i32 0
    RETURN %0(s32), implicit-def $arguments
...
---
name:            const_i64
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[CONST_I64_:%[0-9]+]]:i64 = CONST_I64 0, implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[CONST_I64_]], implicit-def $arguments
    %0:i64regbank(s64) = G_CONSTANT i64 0
    RETURN %0(s64), implicit-def $arguments
...

---
name:            implicit_i32
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i32 = IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]], implicit-def $arguments
    %0:i32regbank(s32) = G_IMPLICIT_DEF
    RETURN %0(s32), implicit-def $arguments
...
---
name:            implicit_i64
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i64 = IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]], implicit-def $arguments
    %0:i64regbank(s64) = G_IMPLICIT_DEF
    RETURN %0(s64), implicit-def $arguments
...
