# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=instruction-select -verify-machineinstrs %s -o - | FileCheck %s

---
name:            anyext
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: anyext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[I64_EXTEND_U_I32_:%[0-9]+]]:i64 = I64_EXTEND_U_I32 [[ARGUMENT_i32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I64_EXTEND_U_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i64regbank(s64) = G_ANYEXT %0
    RETURN %1(s64), implicit-def $arguments
...
---
name:            sext
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[I64_EXTEND_S_I32_:%[0-9]+]]:i64 = I64_EXTEND_S_I32 [[ARGUMENT_i32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I64_EXTEND_S_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i64regbank(s64) = G_SEXT %0
    RETURN %1(s64), implicit-def $arguments
...
---
name:            zext
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: zext
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[I64_EXTEND_U_I32_:%[0-9]+]]:i64 = I64_EXTEND_U_I32 [[ARGUMENT_i32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I64_EXTEND_U_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i64regbank(s64) = G_ZEXT %0
    RETURN %1(s64), implicit-def $arguments
...
---
name:            trunc
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: trunc
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[I32_WRAP_I64_:%[0-9]+]]:i32 = I32_WRAP_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_WRAP_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i32regbank(s32) = G_TRUNC %0
    RETURN %1(s32), implicit-def $arguments
...

---
name:            sext_inreg_i32_8
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i32_8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[I32_EXTEND8_S_I32_:%[0-9]+]]:i32 = I32_EXTEND8_S_I32 [[ARGUMENT_i32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_EXTEND8_S_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32regbank(s32) = G_SEXT_INREG %0, 8
    RETURN %1(s32), implicit-def $arguments
...
---
name:            sext_inreg_i64_8
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i64_8
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[I64_EXTEND8_S_I64_:%[0-9]+]]:i64 = I64_EXTEND8_S_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I64_EXTEND8_S_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64regbank(s64) = G_SEXT_INREG %0, 8
    RETURN %1(s64), implicit-def $arguments
...

---
name:            sext_inreg_i32_16
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i32_16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32 = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[I32_EXTEND16_S_I32_:%[0-9]+]]:i32 = I32_EXTEND16_S_I32 [[ARGUMENT_i32_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I32_EXTEND16_S_I32_]], implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32regbank(s32) = G_SEXT_INREG %0, 16
    RETURN %1(s32), implicit-def $arguments
...
---
name:            sext_inreg_i64_16
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i64_16
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[I64_EXTEND16_S_I64_:%[0-9]+]]:i64 = I64_EXTEND16_S_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I64_EXTEND16_S_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64regbank(s64) = G_SEXT_INREG %0, 16
    RETURN %1(s64), implicit-def $arguments
...

---
name:            sext_inreg_i64_32
alignment:       1
legalized:       true
regBankSelected: true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: sext_inreg_i64_32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64 = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[I64_EXTEND32_S_I64_:%[0-9]+]]:i64 = I64_EXTEND32_S_I64 [[ARGUMENT_i64_]], implicit-def dead $arguments
    ; CHECK-NEXT: RETURN [[I64_EXTEND32_S_I64_]], implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64regbank(s64) = G_SEXT_INREG %0, 32
    RETURN %1(s64), implicit-def $arguments
...
