# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -run-pass=legalizer %s -o - | FileCheck %s

---
name:            test_brjt_s32
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.1', '%bb.2' ]

body:             |
  ; CHECK-LABEL: name: test_brjt_s32
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[JUMP_TABLE:%[0-9]+]]:_(p0) = G_JUMP_TABLE %jump-table.0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $x10
  ; CHECK-NEXT:   [[ASSERT_ZEXT:%[0-9]+]]:_(s64) = G_ASSERT_ZEXT [[COPY]], 32
  ; CHECK-NEXT:   [[TRUNC:%[0-9]+]]:_(s32) = G_TRUNC [[ASSERT_ZEXT]](s64)
  ; CHECK-NEXT:   G_BRJT [[JUMP_TABLE]](p0), %jump-table.0, [[TRUNC]](s32)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET
  bb.0.entry:
    liveins: $x10

    %1:_(p0) = G_JUMP_TABLE %jump-table.0
    %2:_(s64) = COPY $x10
    %3:_(s64) = G_ASSERT_ZEXT %2, 32
    %4:_(s32) = G_TRUNC %3
    G_BRJT %1(p0), %jump-table.0, %4(s32)

  bb.1:
    PseudoRET

  bb.2:
    PseudoRET
...
---
name:            test_brjt_s64
jumpTable:
  kind:            block-address
  entries:
    - id:              0
      blocks:          [ '%bb.1', '%bb.2' ]

body:             |
  ; CHECK-LABEL: name: test_brjt_s64
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   liveins: $x10
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[JUMP_TABLE:%[0-9]+]]:_(p0) = G_JUMP_TABLE %jump-table.0
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s64) = COPY $x10
  ; CHECK-NEXT:   G_BRJT [[JUMP_TABLE]](p0), %jump-table.0, [[COPY]](s64)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   PseudoRET
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   PseudoRET
  bb.0.entry:
    liveins: $x10

    %1:_(p0) = G_JUMP_TABLE %jump-table.0
    %2:_(s64) = COPY $x10
    G_BRJT %1(p0), %jump-table.0, %2(s64)

  bb.1:
    PseudoRET

  bb.2:
    PseudoRET
...

