# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=riscv64 -run-pass=legalizer %s -o - \
# RUN: | FileCheck %s
---
name:            and_i8
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: and_i8
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[AND]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s8) = G_TRUNC %0(s64)
    %3:_(s8) = G_TRUNC %1(s64)
    %4:_(s8) = G_AND %2, %3
    %5:_(s64) = G_ANYEXT %4(s8)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            and_i16
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: and_i16
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[AND]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s16) = G_TRUNC %0(s64)
    %3:_(s16) = G_TRUNC %1(s64)
    %4:_(s16) = G_AND %2, %3
    %5:_(s64) = G_ANYEXT %4(s16)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            and_i32
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: and_i32
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[AND]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s32) = G_TRUNC %0(s64)
    %3:_(s32) = G_TRUNC %1(s64)
    %4:_(s32) = G_AND %2, %3
    %5:_(s64) = G_ANYEXT %4(s32)
    $x10 = COPY %5(s64)
    PseudoRET implicit $x10

...
---
name:            and_i64
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: and_i64
    ; CHECK: [[COPY:%[0-9]+]]:_(s64) = COPY $x10
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:_(s64) = COPY $x11
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND [[COPY]], [[COPY1]]
    ; CHECK-NEXT: $x10 = COPY [[AND]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10
    %0:_(s64) = COPY $x10
    %1:_(s64) = COPY $x11
    %2:_(s64) = G_AND %0, %1
    $x10 = COPY %2(s64)
    PseudoRET implicit $x10

...
---
name:            and_i128
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: and_i128
    ; CHECK: %hi1:_(s64) = COPY $x10
    ; CHECK-NEXT: %lo1:_(s64) = COPY $x11
    ; CHECK-NEXT: %hi2:_(s64) = COPY $x12
    ; CHECK-NEXT: %lo2:_(s64) = COPY $x13
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND %hi1, %hi2
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND %lo1, %lo2
    ; CHECK-NEXT: $x10 = COPY [[AND]](s64)
    ; CHECK-NEXT: $x11 = COPY [[AND1]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10, implicit $x11
    %hi1:_(s64) = COPY $x10
    %lo1:_(s64) = COPY $x11
    %hi2:_(s64) = COPY $x12
    %lo2:_(s64) = COPY $x13
    %x1:_(s128) = G_MERGE_VALUES %hi1(s64), %lo1(s64)
    %x2:_(s128) = G_MERGE_VALUES %hi2(s64), %lo2(s64)
    %y:_(s128) = G_AND %x1, %x2
    %hiy:_(s64), %loy:_(s64) = G_UNMERGE_VALUES %y(s128)
    $x10 = COPY %hiy(s64)
    $x11 = COPY %loy(s64)
    PseudoRET implicit $x10, implicit $x11

...
---
name:            and_i192
body:             |
  bb.0.entry:
    ; CHECK-LABEL: name: and_i192
    ; CHECK: %hi1:_(s64) = COPY $x10
    ; CHECK-NEXT: %mid1:_(s64) = COPY $x11
    ; CHECK-NEXT: %lo1:_(s64) = COPY $x12
    ; CHECK-NEXT: %hi2:_(s64) = COPY $x13
    ; CHECK-NEXT: %mid2:_(s64) = COPY $x14
    ; CHECK-NEXT: %lo2:_(s64) = COPY $x15
    ; CHECK-NEXT: [[AND:%[0-9]+]]:_(s64) = G_AND %hi1, %hi2
    ; CHECK-NEXT: [[AND1:%[0-9]+]]:_(s64) = G_AND %mid1, %mid2
    ; CHECK-NEXT: [[AND2:%[0-9]+]]:_(s64) = G_AND %lo1, %lo2
    ; CHECK-NEXT: $x10 = COPY [[AND]](s64)
    ; CHECK-NEXT: $x11 = COPY [[AND1]](s64)
    ; CHECK-NEXT: $x12 = COPY [[AND2]](s64)
    ; CHECK-NEXT: PseudoRET implicit $x10, implicit $x11, implicit $x12
    %hi1:_(s64) = COPY $x10
    %mid1:_(s64) = COPY $x11
    %lo1:_(s64) = COPY $x12
    %hi2:_(s64) = COPY $x13
    %mid2:_(s64) = COPY $x14
    %lo2:_(s64) = COPY $x15
    %x1:_(s192) = G_MERGE_VALUES %hi1(s64), %mid1(s64), %lo1(s64)
    %x2:_(s192) = G_MERGE_VALUES %hi2(s64), %mid2(s64), %lo2(s64)
    %y:_(s192) = G_AND %x1, %x2
    %hi:_(s64), %mid:_(s64), %lo:_(s64) = G_UNMERGE_VALUES %y(s192)
    $x10 = COPY %hi(s64)
    $x11 = COPY %mid(s64)
    $x12 = COPY %lo(s64)
    PseudoRET implicit $x10, implicit $x11, implicit $x12

...
