// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// RUN: %clang_cc1 -triple arm64-none-linux-gnu -target-feature +neon \
// RUN:     -S \
// RUN:  -emit-llvm -o - %s -fsanitize=memory \
// RUN: | FileCheck %s

// REQUIRES: aarch64-registered-target || arm-registered-target

#include <arm_neon.h>
#include <sanitizer/msan_interface.h>

// CHECK-LABEL: define dso_local noundef i32 @test_vst1(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.donothing()
// CHECK-NEXT:    [[__P0_ADDR_I:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = xor i64 [[TMP0]], 193514046488576
// CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[TMP1]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP2]], i8 -1, i64 2, i1 false)
// CHECK-NEXT:    [[__RET_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = xor i64 [[TMP3]], 193514046488576
// CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[TMP4]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP5]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[VEC1:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[DST1:%.*]] = alloca [8 x i16], align 2
// CHECK-NEXT:    [[__S1:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[VEC1]]) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    [[TMP6:%.*]] = ptrtoint ptr [[VEC1]] to i64
// CHECK-NEXT:    [[TMP7:%.*]] = xor i64 [[TMP6]], 193514046488576
// CHECK-NEXT:    [[TMP8:%.*]] = inttoptr i64 [[TMP7]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP8]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[TMP9:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP9]], 193514046488576
// CHECK-NEXT:    [[TMP11:%.*]] = inttoptr i64 [[TMP10]] to ptr
// CHECK-NEXT:    store i16 0, ptr [[TMP11]], align 2
// CHECK-NEXT:    store i16 15, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP13:%.*]] = xor i64 [[TMP12]], 193514046488576
// CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i64 [[TMP13]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP14]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP16:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP17:%.*]] = xor i64 [[TMP16]], 193514046488576
// CHECK-NEXT:    [[TMP18:%.*]] = inttoptr i64 [[TMP17]] to ptr
// CHECK-NEXT:    [[_MSLD:%.*]] = load i16, ptr [[TMP18]], align 2
// CHECK-NEXT:    [[_MSPROP:%.*]] = insertelement <8 x i16> <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>, i16 [[_MSLD]], i32 0
// CHECK-NEXT:    [[VECINIT_I:%.*]] = insertelement <8 x i16> poison, i16 [[TMP15]], i32 0
// CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP20:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP21:%.*]] = xor i64 [[TMP20]], 193514046488576
// CHECK-NEXT:    [[TMP22:%.*]] = inttoptr i64 [[TMP21]] to ptr
// CHECK-NEXT:    [[_MSLD2:%.*]] = load i16, ptr [[TMP22]], align 2
// CHECK-NEXT:    [[_MSPROP3:%.*]] = insertelement <8 x i16> [[_MSPROP]], i16 [[_MSLD2]], i32 1
// CHECK-NEXT:    [[VECINIT1_I:%.*]] = insertelement <8 x i16> [[VECINIT_I]], i16 [[TMP19]], i32 1
// CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP24:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP25:%.*]] = xor i64 [[TMP24]], 193514046488576
// CHECK-NEXT:    [[TMP26:%.*]] = inttoptr i64 [[TMP25]] to ptr
// CHECK-NEXT:    [[_MSLD4:%.*]] = load i16, ptr [[TMP26]], align 2
// CHECK-NEXT:    [[_MSPROP5:%.*]] = insertelement <8 x i16> [[_MSPROP3]], i16 [[_MSLD4]], i32 2
// CHECK-NEXT:    [[VECINIT2_I:%.*]] = insertelement <8 x i16> [[VECINIT1_I]], i16 [[TMP23]], i32 2
// CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP28:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP29:%.*]] = xor i64 [[TMP28]], 193514046488576
// CHECK-NEXT:    [[TMP30:%.*]] = inttoptr i64 [[TMP29]] to ptr
// CHECK-NEXT:    [[_MSLD6:%.*]] = load i16, ptr [[TMP30]], align 2
// CHECK-NEXT:    [[_MSPROP7:%.*]] = insertelement <8 x i16> [[_MSPROP5]], i16 [[_MSLD6]], i32 3
// CHECK-NEXT:    [[VECINIT3_I:%.*]] = insertelement <8 x i16> [[VECINIT2_I]], i16 [[TMP27]], i32 3
// CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP32:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP33:%.*]] = xor i64 [[TMP32]], 193514046488576
// CHECK-NEXT:    [[TMP34:%.*]] = inttoptr i64 [[TMP33]] to ptr
// CHECK-NEXT:    [[_MSLD8:%.*]] = load i16, ptr [[TMP34]], align 2
// CHECK-NEXT:    [[_MSPROP9:%.*]] = insertelement <8 x i16> [[_MSPROP7]], i16 [[_MSLD8]], i32 4
// CHECK-NEXT:    [[VECINIT4_I:%.*]] = insertelement <8 x i16> [[VECINIT3_I]], i16 [[TMP31]], i32 4
// CHECK-NEXT:    [[TMP35:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP36:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP37:%.*]] = xor i64 [[TMP36]], 193514046488576
// CHECK-NEXT:    [[TMP38:%.*]] = inttoptr i64 [[TMP37]] to ptr
// CHECK-NEXT:    [[_MSLD10:%.*]] = load i16, ptr [[TMP38]], align 2
// CHECK-NEXT:    [[_MSPROP11:%.*]] = insertelement <8 x i16> [[_MSPROP9]], i16 [[_MSLD10]], i32 5
// CHECK-NEXT:    [[VECINIT5_I:%.*]] = insertelement <8 x i16> [[VECINIT4_I]], i16 [[TMP35]], i32 5
// CHECK-NEXT:    [[TMP39:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP40:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP41:%.*]] = xor i64 [[TMP40]], 193514046488576
// CHECK-NEXT:    [[TMP42:%.*]] = inttoptr i64 [[TMP41]] to ptr
// CHECK-NEXT:    [[_MSLD12:%.*]] = load i16, ptr [[TMP42]], align 2
// CHECK-NEXT:    [[_MSPROP13:%.*]] = insertelement <8 x i16> [[_MSPROP11]], i16 [[_MSLD12]], i32 6
// CHECK-NEXT:    [[VECINIT6_I:%.*]] = insertelement <8 x i16> [[VECINIT5_I]], i16 [[TMP39]], i32 6
// CHECK-NEXT:    [[TMP43:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP44:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP45:%.*]] = xor i64 [[TMP44]], 193514046488576
// CHECK-NEXT:    [[TMP46:%.*]] = inttoptr i64 [[TMP45]] to ptr
// CHECK-NEXT:    [[_MSLD14:%.*]] = load i16, ptr [[TMP46]], align 2
// CHECK-NEXT:    [[_MSPROP15:%.*]] = insertelement <8 x i16> [[_MSPROP13]], i16 [[_MSLD14]], i32 7
// CHECK-NEXT:    [[VECINIT7_I:%.*]] = insertelement <8 x i16> [[VECINIT6_I]], i16 [[TMP43]], i32 7
// CHECK-NEXT:    [[TMP47:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP48:%.*]] = xor i64 [[TMP47]], 193514046488576
// CHECK-NEXT:    [[TMP49:%.*]] = inttoptr i64 [[TMP48]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSPROP15]], ptr [[TMP49]], align 16
// CHECK-NEXT:    store <8 x i16> [[VECINIT7_I]], ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP50:%.*]] = load <8 x i16>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP51:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP52:%.*]] = xor i64 [[TMP51]], 193514046488576
// CHECK-NEXT:    [[TMP53:%.*]] = inttoptr i64 [[TMP52]] to ptr
// CHECK-NEXT:    [[_MSLD16:%.*]] = load <8 x i16>, ptr [[TMP53]], align 16
// CHECK-NEXT:    [[TMP54:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP55:%.*]] = xor i64 [[TMP54]], 193514046488576
// CHECK-NEXT:    [[TMP56:%.*]] = inttoptr i64 [[TMP55]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD16]], ptr [[TMP56]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP50]], ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP57:%.*]] = load <8 x i16>, ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP58:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP59:%.*]] = xor i64 [[TMP58]], 193514046488576
// CHECK-NEXT:    [[TMP60:%.*]] = inttoptr i64 [[TMP59]] to ptr
// CHECK-NEXT:    [[_MSLD17:%.*]] = load <8 x i16>, ptr [[TMP60]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP61:%.*]] = ptrtoint ptr [[VEC1]] to i64
// CHECK-NEXT:    [[TMP62:%.*]] = xor i64 [[TMP61]], 193514046488576
// CHECK-NEXT:    [[TMP63:%.*]] = inttoptr i64 [[TMP62]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD17]], ptr [[TMP63]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP57]], ptr [[VEC1]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[DST1]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP64:%.*]] = ptrtoint ptr [[DST1]] to i64
// CHECK-NEXT:    [[TMP65:%.*]] = xor i64 [[TMP64]], 193514046488576
// CHECK-NEXT:    [[TMP66:%.*]] = inttoptr i64 [[TMP65]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP66]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP67:%.*]] = ptrtoint ptr [[__S1]] to i64
// CHECK-NEXT:    [[TMP68:%.*]] = xor i64 [[TMP67]], 193514046488576
// CHECK-NEXT:    [[TMP69:%.*]] = inttoptr i64 [[TMP68]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP69]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[TMP70:%.*]] = load <8 x i16>, ptr [[VEC1]], align 16
// CHECK-NEXT:    [[TMP71:%.*]] = ptrtoint ptr [[VEC1]] to i64
// CHECK-NEXT:    [[TMP72:%.*]] = xor i64 [[TMP71]], 193514046488576
// CHECK-NEXT:    [[TMP73:%.*]] = inttoptr i64 [[TMP72]] to ptr
// CHECK-NEXT:    [[_MSLD18:%.*]] = load <8 x i16>, ptr [[TMP73]], align 16
// CHECK-NEXT:    [[TMP74:%.*]] = ptrtoint ptr [[__S1]] to i64
// CHECK-NEXT:    [[TMP75:%.*]] = xor i64 [[TMP74]], 193514046488576
// CHECK-NEXT:    [[TMP76:%.*]] = inttoptr i64 [[TMP75]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD18]], ptr [[TMP76]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP70]], ptr [[__S1]], align 16
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [8 x i16], ptr [[DST1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP77:%.*]] = load <8 x i16>, ptr [[__S1]], align 16
// CHECK-NEXT:    [[TMP78:%.*]] = ptrtoint ptr [[__S1]] to i64
// CHECK-NEXT:    [[TMP79:%.*]] = xor i64 [[TMP78]], 193514046488576
// CHECK-NEXT:    [[TMP80:%.*]] = inttoptr i64 [[TMP79]] to ptr
// CHECK-NEXT:    [[_MSLD19:%.*]] = load <8 x i16>, ptr [[TMP80]], align 16
// CHECK-NEXT:    [[TMP81:%.*]] = bitcast <8 x i16> [[_MSLD19]] to <16 x i8>
// CHECK-NEXT:    [[TMP82:%.*]] = bitcast <8 x i16> [[TMP77]] to <16 x i8>
// CHECK-NEXT:    [[TMP83:%.*]] = bitcast <16 x i8> [[TMP81]] to <8 x i16>
// CHECK-NEXT:    [[TMP84:%.*]] = bitcast <16 x i8> [[TMP82]] to <8 x i16>
// CHECK-NEXT:    [[TMP85:%.*]] = ptrtoint ptr [[ARRAYDECAY]] to i64
// CHECK-NEXT:    [[TMP86:%.*]] = xor i64 [[TMP85]], 193514046488576
// CHECK-NEXT:    [[TMP87:%.*]] = inttoptr i64 [[TMP86]] to ptr
// CHECK-NEXT:    store <8 x i16> [[TMP83]], ptr [[TMP87]], align 2
// CHECK-NEXT:    store <8 x i16> [[TMP84]], ptr [[ARRAYDECAY]], align 2
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[ARRAYDECAY1:%.*]] = getelementptr inbounds [8 x i16], ptr [[DST1]], i64 0, i64 0
// CHECK-NEXT:    call void @__msan_print_shadow(ptr noundef [[ARRAYDECAY1]], i64 noundef 16)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP88:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP89:%.*]] = xor i64 [[TMP88]], 193514046488576
// CHECK-NEXT:    [[TMP90:%.*]] = inttoptr i64 [[TMP89]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP90]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP91:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP92:%.*]] = xor i64 [[TMP91]], 193514046488576
// CHECK-NEXT:    [[TMP93:%.*]] = inttoptr i64 [[TMP92]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP93]], align 4
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP94:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP95:%.*]] = xor i64 [[TMP94]], 193514046488576
// CHECK-NEXT:    [[TMP96:%.*]] = inttoptr i64 [[TMP95]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP96]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP97:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP98:%.*]] = xor i64 [[TMP97]], 193514046488576
// CHECK-NEXT:    [[TMP99:%.*]] = inttoptr i64 [[TMP98]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP99]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[TMP100:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP101:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP102:%.*]] = xor i64 [[TMP101]], 193514046488576
// CHECK-NEXT:    [[TMP103:%.*]] = inttoptr i64 [[TMP102]] to ptr
// CHECK-NEXT:    [[_MSLD20:%.*]] = load i32, ptr [[TMP103]], align 4
// CHECK-NEXT:    [[_MSPROP21:%.*]] = or i32 [[_MSLD20]], 0
// CHECK-NEXT:    [[TMP104:%.*]] = icmp ne i32 [[_MSPROP21]], 0
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP100]], 8
// CHECK-NEXT:    br i1 [[TMP104]], label [[TMP105:%.*]], label [[TMP106:%.*]], !prof [[PROF2:![0-9]+]]
// CHECK:       105:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7:[0-9]+]]
// CHECK-NEXT:    unreachable
// CHECK:       106:
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_COND_CLEANUP:%.*]]
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    br label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[TMP107:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP108:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP109:%.*]] = xor i64 [[TMP108]], 193514046488576
// CHECK-NEXT:    [[TMP110:%.*]] = inttoptr i64 [[TMP109]] to ptr
// CHECK-NEXT:    [[_MSLD22:%.*]] = load i32, ptr [[TMP110]], align 4
// CHECK-NEXT:    [[_MSPROP23:%.*]] = sext i32 [[_MSLD22]] to i64
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP107]] to i64
// CHECK-NEXT:    [[_MSPROP24:%.*]] = or i64 0, [[_MSPROP23]]
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [8 x i16], ptr [[DST1]], i64 0, i64 [[IDXPROM]]
// CHECK-NEXT:    [[_MSCMP:%.*]] = icmp ne i64 [[_MSPROP24]], 0
// CHECK-NEXT:    br i1 [[_MSCMP]], label [[TMP111:%.*]], label [[TMP112:%.*]], !prof [[PROF2]]
// CHECK:       111:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       112:
// CHECK-NEXT:    [[TMP113:%.*]] = load i16, ptr [[ARRAYIDX]], align 2
// CHECK-NEXT:    [[TMP114:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64
// CHECK-NEXT:    [[TMP115:%.*]] = xor i64 [[TMP114]], 193514046488576
// CHECK-NEXT:    [[TMP116:%.*]] = inttoptr i64 [[TMP115]] to ptr
// CHECK-NEXT:    [[_MSLD25:%.*]] = load i16, ptr [[TMP116]], align 2
// CHECK-NEXT:    [[_MSPROP26:%.*]] = sext i16 [[_MSLD25]] to i32
// CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP113]] to i32
// CHECK-NEXT:    [[TMP117:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP118:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP119:%.*]] = xor i64 [[TMP118]], 193514046488576
// CHECK-NEXT:    [[TMP120:%.*]] = inttoptr i64 [[TMP119]] to ptr
// CHECK-NEXT:    [[_MSLD27:%.*]] = load i32, ptr [[TMP120]], align 4
// CHECK-NEXT:    [[_MSPROP28:%.*]] = or i32 [[_MSLD27]], [[_MSPROP26]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP117]], [[CONV]]
// CHECK-NEXT:    [[TMP121:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP122:%.*]] = xor i64 [[TMP121]], 193514046488576
// CHECK-NEXT:    [[TMP123:%.*]] = inttoptr i64 [[TMP122]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP28]], ptr [[TMP123]], align 4
// CHECK-NEXT:    store i32 [[ADD]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label [[FOR_INC:%.*]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[TMP124:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP125:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP126:%.*]] = xor i64 [[TMP125]], 193514046488576
// CHECK-NEXT:    [[TMP127:%.*]] = inttoptr i64 [[TMP126]] to ptr
// CHECK-NEXT:    [[_MSLD29:%.*]] = load i32, ptr [[TMP127]], align 4
// CHECK-NEXT:    [[_MSPROP30:%.*]] = or i32 [[_MSLD29]], 0
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP124]], 1
// CHECK-NEXT:    [[TMP128:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP129:%.*]] = xor i64 [[TMP128]], 193514046488576
// CHECK-NEXT:    [[TMP130:%.*]] = inttoptr i64 [[TMP129]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP30]], ptr [[TMP130]], align 4
// CHECK-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP3:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    [[TMP131:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP132:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP133:%.*]] = xor i64 [[TMP132]], 193514046488576
// CHECK-NEXT:    [[TMP134:%.*]] = inttoptr i64 [[TMP133]] to ptr
// CHECK-NEXT:    [[_MSLD31:%.*]] = load i32, ptr [[TMP134]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[DST1]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[VEC1]]) #[[ATTR4]]
// CHECK-NEXT:    [[_MSCMP32:%.*]] = icmp ne i32 [[_MSLD31]], 0
// CHECK-NEXT:    br i1 [[_MSCMP32]], label [[TMP135:%.*]], label [[TMP136:%.*]], !prof [[PROF2]]
// CHECK:       135:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       136:
// CHECK-NEXT:    ret i32 [[TMP131]]
//
int test_vst1(void) {
  int16x8_t vec1;
  vec1 = vdupq_n_s16(15);
  int16_t dst1[8*1];
  vst1q_s16(dst1, vec1);

  __msan_print_shadow(dst1, sizeof(int16_t)*8*1);

  int sum = 0;
  for (int i = 0; i < 8*1; i++)
    sum += dst1[i];

  return sum;
}

// Initialization is only partial to make the shadows more interesting
// CHECK-LABEL: define dso_local noundef i32 @test_vst2(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.donothing()
// CHECK-NEXT:    [[__P0_ADDR_I:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = xor i64 [[TMP0]], 193514046488576
// CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[TMP1]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP2]], i8 -1, i64 2, i1 false)
// CHECK-NEXT:    [[__RET_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = xor i64 [[TMP3]], 193514046488576
// CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[TMP4]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP5]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[VEC2:%.*]] = alloca [[STRUCT_INT16X8X2_T:%.*]], align 16
// CHECK-NEXT:    [[DST2:%.*]] = alloca [16 x i16], align 2
// CHECK-NEXT:    [[__S1:%.*]] = alloca [[STRUCT_INT16X8X2_T]], align 16
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr [[VEC2]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP6:%.*]] = ptrtoint ptr [[VEC2]] to i64
// CHECK-NEXT:    [[TMP7:%.*]] = xor i64 [[TMP6]], 193514046488576
// CHECK-NEXT:    [[TMP8:%.*]] = inttoptr i64 [[TMP7]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP8]], i8 -1, i64 32, i1 false)
// CHECK-NEXT:    [[TMP9:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP9]], 193514046488576
// CHECK-NEXT:    [[TMP11:%.*]] = inttoptr i64 [[TMP10]] to ptr
// CHECK-NEXT:    store i16 0, ptr [[TMP11]], align 2
// CHECK-NEXT:    store i16 16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP13:%.*]] = xor i64 [[TMP12]], 193514046488576
// CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i64 [[TMP13]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP14]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP16:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP17:%.*]] = xor i64 [[TMP16]], 193514046488576
// CHECK-NEXT:    [[TMP18:%.*]] = inttoptr i64 [[TMP17]] to ptr
// CHECK-NEXT:    [[_MSLD:%.*]] = load i16, ptr [[TMP18]], align 2
// CHECK-NEXT:    [[_MSPROP:%.*]] = insertelement <8 x i16> <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>, i16 [[_MSLD]], i32 0
// CHECK-NEXT:    [[VECINIT_I:%.*]] = insertelement <8 x i16> poison, i16 [[TMP15]], i32 0
// CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP20:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP21:%.*]] = xor i64 [[TMP20]], 193514046488576
// CHECK-NEXT:    [[TMP22:%.*]] = inttoptr i64 [[TMP21]] to ptr
// CHECK-NEXT:    [[_MSLD7:%.*]] = load i16, ptr [[TMP22]], align 2
// CHECK-NEXT:    [[_MSPROP8:%.*]] = insertelement <8 x i16> [[_MSPROP]], i16 [[_MSLD7]], i32 1
// CHECK-NEXT:    [[VECINIT1_I:%.*]] = insertelement <8 x i16> [[VECINIT_I]], i16 [[TMP19]], i32 1
// CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP24:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP25:%.*]] = xor i64 [[TMP24]], 193514046488576
// CHECK-NEXT:    [[TMP26:%.*]] = inttoptr i64 [[TMP25]] to ptr
// CHECK-NEXT:    [[_MSLD9:%.*]] = load i16, ptr [[TMP26]], align 2
// CHECK-NEXT:    [[_MSPROP10:%.*]] = insertelement <8 x i16> [[_MSPROP8]], i16 [[_MSLD9]], i32 2
// CHECK-NEXT:    [[VECINIT2_I:%.*]] = insertelement <8 x i16> [[VECINIT1_I]], i16 [[TMP23]], i32 2
// CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP28:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP29:%.*]] = xor i64 [[TMP28]], 193514046488576
// CHECK-NEXT:    [[TMP30:%.*]] = inttoptr i64 [[TMP29]] to ptr
// CHECK-NEXT:    [[_MSLD11:%.*]] = load i16, ptr [[TMP30]], align 2
// CHECK-NEXT:    [[_MSPROP12:%.*]] = insertelement <8 x i16> [[_MSPROP10]], i16 [[_MSLD11]], i32 3
// CHECK-NEXT:    [[VECINIT3_I:%.*]] = insertelement <8 x i16> [[VECINIT2_I]], i16 [[TMP27]], i32 3
// CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP32:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP33:%.*]] = xor i64 [[TMP32]], 193514046488576
// CHECK-NEXT:    [[TMP34:%.*]] = inttoptr i64 [[TMP33]] to ptr
// CHECK-NEXT:    [[_MSLD13:%.*]] = load i16, ptr [[TMP34]], align 2
// CHECK-NEXT:    [[_MSPROP14:%.*]] = insertelement <8 x i16> [[_MSPROP12]], i16 [[_MSLD13]], i32 4
// CHECK-NEXT:    [[VECINIT4_I:%.*]] = insertelement <8 x i16> [[VECINIT3_I]], i16 [[TMP31]], i32 4
// CHECK-NEXT:    [[TMP35:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP36:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP37:%.*]] = xor i64 [[TMP36]], 193514046488576
// CHECK-NEXT:    [[TMP38:%.*]] = inttoptr i64 [[TMP37]] to ptr
// CHECK-NEXT:    [[_MSLD15:%.*]] = load i16, ptr [[TMP38]], align 2
// CHECK-NEXT:    [[_MSPROP16:%.*]] = insertelement <8 x i16> [[_MSPROP14]], i16 [[_MSLD15]], i32 5
// CHECK-NEXT:    [[VECINIT5_I:%.*]] = insertelement <8 x i16> [[VECINIT4_I]], i16 [[TMP35]], i32 5
// CHECK-NEXT:    [[TMP39:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP40:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP41:%.*]] = xor i64 [[TMP40]], 193514046488576
// CHECK-NEXT:    [[TMP42:%.*]] = inttoptr i64 [[TMP41]] to ptr
// CHECK-NEXT:    [[_MSLD17:%.*]] = load i16, ptr [[TMP42]], align 2
// CHECK-NEXT:    [[_MSPROP18:%.*]] = insertelement <8 x i16> [[_MSPROP16]], i16 [[_MSLD17]], i32 6
// CHECK-NEXT:    [[VECINIT6_I:%.*]] = insertelement <8 x i16> [[VECINIT5_I]], i16 [[TMP39]], i32 6
// CHECK-NEXT:    [[TMP43:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP44:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP45:%.*]] = xor i64 [[TMP44]], 193514046488576
// CHECK-NEXT:    [[TMP46:%.*]] = inttoptr i64 [[TMP45]] to ptr
// CHECK-NEXT:    [[_MSLD19:%.*]] = load i16, ptr [[TMP46]], align 2
// CHECK-NEXT:    [[_MSPROP20:%.*]] = insertelement <8 x i16> [[_MSPROP18]], i16 [[_MSLD19]], i32 7
// CHECK-NEXT:    [[VECINIT7_I:%.*]] = insertelement <8 x i16> [[VECINIT6_I]], i16 [[TMP43]], i32 7
// CHECK-NEXT:    [[TMP47:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP48:%.*]] = xor i64 [[TMP47]], 193514046488576
// CHECK-NEXT:    [[TMP49:%.*]] = inttoptr i64 [[TMP48]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSPROP20]], ptr [[TMP49]], align 16
// CHECK-NEXT:    store <8 x i16> [[VECINIT7_I]], ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP50:%.*]] = load <8 x i16>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP51:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP52:%.*]] = xor i64 [[TMP51]], 193514046488576
// CHECK-NEXT:    [[TMP53:%.*]] = inttoptr i64 [[TMP52]] to ptr
// CHECK-NEXT:    [[_MSLD21:%.*]] = load <8 x i16>, ptr [[TMP53]], align 16
// CHECK-NEXT:    [[TMP54:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP55:%.*]] = xor i64 [[TMP54]], 193514046488576
// CHECK-NEXT:    [[TMP56:%.*]] = inttoptr i64 [[TMP55]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD21]], ptr [[TMP56]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP50]], ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP57:%.*]] = load <8 x i16>, ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP58:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP59:%.*]] = xor i64 [[TMP58]], 193514046488576
// CHECK-NEXT:    [[TMP60:%.*]] = inttoptr i64 [[TMP59]] to ptr
// CHECK-NEXT:    [[_MSLD22:%.*]] = load <8 x i16>, ptr [[TMP60]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[VAL:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X2_T]], ptr [[VEC2]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [2 x <8 x i16>], ptr [[VAL]], i64 0, i64 1
// CHECK-NEXT:    [[TMP61:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64
// CHECK-NEXT:    [[TMP62:%.*]] = xor i64 [[TMP61]], 193514046488576
// CHECK-NEXT:    [[TMP63:%.*]] = inttoptr i64 [[TMP62]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD22]], ptr [[TMP63]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP57]], ptr [[ARRAYIDX]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr [[DST2]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP64:%.*]] = ptrtoint ptr [[DST2]] to i64
// CHECK-NEXT:    [[TMP65:%.*]] = xor i64 [[TMP64]], 193514046488576
// CHECK-NEXT:    [[TMP66:%.*]] = inttoptr i64 [[TMP65]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP66]], i8 -1, i64 32, i1 false)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 32, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP67:%.*]] = ptrtoint ptr [[__S1]] to i64
// CHECK-NEXT:    [[TMP68:%.*]] = xor i64 [[TMP67]], 193514046488576
// CHECK-NEXT:    [[TMP69:%.*]] = inttoptr i64 [[TMP68]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP69]], i8 -1, i64 32, i1 false)
// CHECK-NEXT:    [[TMP70:%.*]] = call ptr @__msan_memcpy(ptr [[__S1]], ptr [[VEC2]], i64 32)
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [16 x i16], ptr [[DST2]], i64 0, i64 0
// CHECK-NEXT:    [[VAL1:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X2_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [2 x <8 x i16>], ptr [[VAL1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP71:%.*]] = load <8 x i16>, ptr [[ARRAYIDX2]], align 16
// CHECK-NEXT:    [[TMP72:%.*]] = ptrtoint ptr [[ARRAYIDX2]] to i64
// CHECK-NEXT:    [[TMP73:%.*]] = xor i64 [[TMP72]], 193514046488576
// CHECK-NEXT:    [[TMP74:%.*]] = inttoptr i64 [[TMP73]] to ptr
// CHECK-NEXT:    [[_MSLD23:%.*]] = load <8 x i16>, ptr [[TMP74]], align 16
// CHECK-NEXT:    [[TMP75:%.*]] = bitcast <8 x i16> [[_MSLD23]] to <16 x i8>
// CHECK-NEXT:    [[TMP76:%.*]] = bitcast <8 x i16> [[TMP71]] to <16 x i8>
// CHECK-NEXT:    [[VAL3:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X2_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds [2 x <8 x i16>], ptr [[VAL3]], i64 0, i64 1
// CHECK-NEXT:    [[TMP77:%.*]] = load <8 x i16>, ptr [[ARRAYIDX4]], align 16
// CHECK-NEXT:    [[TMP78:%.*]] = ptrtoint ptr [[ARRAYIDX4]] to i64
// CHECK-NEXT:    [[TMP79:%.*]] = xor i64 [[TMP78]], 193514046488576
// CHECK-NEXT:    [[TMP80:%.*]] = inttoptr i64 [[TMP79]] to ptr
// CHECK-NEXT:    [[_MSLD24:%.*]] = load <8 x i16>, ptr [[TMP80]], align 16
// CHECK-NEXT:    [[TMP81:%.*]] = bitcast <8 x i16> [[_MSLD24]] to <16 x i8>
// CHECK-NEXT:    [[TMP82:%.*]] = bitcast <8 x i16> [[TMP77]] to <16 x i8>
// CHECK-NEXT:    [[TMP83:%.*]] = bitcast <16 x i8> [[TMP75]] to <8 x i16>
// CHECK-NEXT:    [[TMP84:%.*]] = bitcast <16 x i8> [[TMP76]] to <8 x i16>
// CHECK-NEXT:    [[TMP85:%.*]] = bitcast <16 x i8> [[TMP81]] to <8 x i16>
// CHECK-NEXT:    [[TMP86:%.*]] = bitcast <16 x i8> [[TMP82]] to <8 x i16>
// CHECK-NEXT:    [[TMP87:%.*]] = bitcast <8 x i16> [[TMP83]] to i128
// CHECK-NEXT:    [[_MSCMP:%.*]] = icmp ne i128 [[TMP87]], 0
// CHECK-NEXT:    [[TMP88:%.*]] = bitcast <8 x i16> [[TMP85]] to i128
// CHECK-NEXT:    [[_MSCMP37:%.*]] = icmp ne i128 [[TMP88]], 0
// CHECK-NEXT:    [[_MSOR:%.*]] = or i1 [[_MSCMP]], [[_MSCMP37]]
// CHECK-NEXT:    br i1 [[_MSOR]], label [[TMP89:%.*]], label [[TMP90:%.*]], !prof [[PROF2]]
// CHECK:       89:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       90:
// CHECK-NEXT:    call void @llvm.aarch64.neon.st2.v8i16.p0(<8 x i16> [[TMP84]], <8 x i16> [[TMP86]], ptr [[ARRAYDECAY]])
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[ARRAYDECAY5:%.*]] = getelementptr inbounds [16 x i16], ptr [[DST2]], i64 0, i64 0
// CHECK-NEXT:    call void @__msan_print_shadow(ptr noundef [[ARRAYDECAY5]], i64 noundef 32)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP91:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP92:%.*]] = xor i64 [[TMP91]], 193514046488576
// CHECK-NEXT:    [[TMP93:%.*]] = inttoptr i64 [[TMP92]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP93]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP94:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP95:%.*]] = xor i64 [[TMP94]], 193514046488576
// CHECK-NEXT:    [[TMP96:%.*]] = inttoptr i64 [[TMP95]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP96]], align 4
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP97:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP98:%.*]] = xor i64 [[TMP97]], 193514046488576
// CHECK-NEXT:    [[TMP99:%.*]] = inttoptr i64 [[TMP98]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP99]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP100:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP101:%.*]] = xor i64 [[TMP100]], 193514046488576
// CHECK-NEXT:    [[TMP102:%.*]] = inttoptr i64 [[TMP101]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP102]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[TMP103:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP104:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP105:%.*]] = xor i64 [[TMP104]], 193514046488576
// CHECK-NEXT:    [[TMP106:%.*]] = inttoptr i64 [[TMP105]] to ptr
// CHECK-NEXT:    [[_MSLD25:%.*]] = load i32, ptr [[TMP106]], align 4
// CHECK-NEXT:    [[_MSPROP26:%.*]] = or i32 [[_MSLD25]], 0
// CHECK-NEXT:    [[TMP107:%.*]] = icmp ne i32 [[_MSPROP26]], 0
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP103]], 16
// CHECK-NEXT:    br i1 [[TMP107]], label [[TMP108:%.*]], label [[TMP109:%.*]], !prof [[PROF2]]
// CHECK:       108:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       109:
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_COND_CLEANUP:%.*]]
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    br label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[TMP110:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP111:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP112:%.*]] = xor i64 [[TMP111]], 193514046488576
// CHECK-NEXT:    [[TMP113:%.*]] = inttoptr i64 [[TMP112]] to ptr
// CHECK-NEXT:    [[_MSLD27:%.*]] = load i32, ptr [[TMP113]], align 4
// CHECK-NEXT:    [[_MSPROP28:%.*]] = sext i32 [[_MSLD27]] to i64
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP110]] to i64
// CHECK-NEXT:    [[_MSPROP29:%.*]] = or i64 0, [[_MSPROP28]]
// CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [16 x i16], ptr [[DST2]], i64 0, i64 [[IDXPROM]]
// CHECK-NEXT:    [[_MSCMP38:%.*]] = icmp ne i64 [[_MSPROP29]], 0
// CHECK-NEXT:    br i1 [[_MSCMP38]], label [[TMP114:%.*]], label [[TMP115:%.*]], !prof [[PROF2]]
// CHECK:       114:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       115:
// CHECK-NEXT:    [[TMP116:%.*]] = load i16, ptr [[ARRAYIDX6]], align 2
// CHECK-NEXT:    [[TMP117:%.*]] = ptrtoint ptr [[ARRAYIDX6]] to i64
// CHECK-NEXT:    [[TMP118:%.*]] = xor i64 [[TMP117]], 193514046488576
// CHECK-NEXT:    [[TMP119:%.*]] = inttoptr i64 [[TMP118]] to ptr
// CHECK-NEXT:    [[_MSLD30:%.*]] = load i16, ptr [[TMP119]], align 2
// CHECK-NEXT:    [[_MSPROP31:%.*]] = sext i16 [[_MSLD30]] to i32
// CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP116]] to i32
// CHECK-NEXT:    [[TMP120:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP121:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP122:%.*]] = xor i64 [[TMP121]], 193514046488576
// CHECK-NEXT:    [[TMP123:%.*]] = inttoptr i64 [[TMP122]] to ptr
// CHECK-NEXT:    [[_MSLD32:%.*]] = load i32, ptr [[TMP123]], align 4
// CHECK-NEXT:    [[_MSPROP33:%.*]] = or i32 [[_MSLD32]], [[_MSPROP31]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP120]], [[CONV]]
// CHECK-NEXT:    [[TMP124:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP125:%.*]] = xor i64 [[TMP124]], 193514046488576
// CHECK-NEXT:    [[TMP126:%.*]] = inttoptr i64 [[TMP125]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP33]], ptr [[TMP126]], align 4
// CHECK-NEXT:    store i32 [[ADD]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label [[FOR_INC:%.*]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[TMP127:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP128:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP129:%.*]] = xor i64 [[TMP128]], 193514046488576
// CHECK-NEXT:    [[TMP130:%.*]] = inttoptr i64 [[TMP129]] to ptr
// CHECK-NEXT:    [[_MSLD34:%.*]] = load i32, ptr [[TMP130]], align 4
// CHECK-NEXT:    [[_MSPROP35:%.*]] = or i32 [[_MSLD34]], 0
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP127]], 1
// CHECK-NEXT:    [[TMP131:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP132:%.*]] = xor i64 [[TMP131]], 193514046488576
// CHECK-NEXT:    [[TMP133:%.*]] = inttoptr i64 [[TMP132]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP35]], ptr [[TMP133]], align 4
// CHECK-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP5:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    [[TMP134:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP135:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP136:%.*]] = xor i64 [[TMP135]], 193514046488576
// CHECK-NEXT:    [[TMP137:%.*]] = inttoptr i64 [[TMP136]] to ptr
// CHECK-NEXT:    [[_MSLD36:%.*]] = load i32, ptr [[TMP137]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr [[DST2]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 32, ptr [[VEC2]]) #[[ATTR4]]
// CHECK-NEXT:    [[_MSCMP39:%.*]] = icmp ne i32 [[_MSLD36]], 0
// CHECK-NEXT:    br i1 [[_MSCMP39]], label [[TMP138:%.*]], label [[TMP139:%.*]], !prof [[PROF2]]
// CHECK:       138:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       139:
// CHECK-NEXT:    ret i32 [[TMP134]]
//
int test_vst2(void) {
  int16x8x2_t vec2;
  vec2.val[1] = vdupq_n_s16(16);
  int16_t dst2[8*2];
  vst2q_s16(dst2, vec2);

  __msan_print_shadow(dst2, sizeof(int16_t)*8*2);

  int sum = 0;
  for (int i = 0; i < 8*2; i++)
    sum += dst2[i];

  return sum;
}

// CHECK-LABEL: define dso_local noundef i32 @test_vst3(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.donothing()
// CHECK-NEXT:    [[__P0_ADDR_I:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = xor i64 [[TMP0]], 193514046488576
// CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[TMP1]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP2]], i8 -1, i64 2, i1 false)
// CHECK-NEXT:    [[__RET_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = xor i64 [[TMP3]], 193514046488576
// CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[TMP4]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP5]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[VEC3:%.*]] = alloca [[STRUCT_INT16X8X3_T:%.*]], align 16
// CHECK-NEXT:    [[DST3:%.*]] = alloca [24 x i16], align 2
// CHECK-NEXT:    [[__S1:%.*]] = alloca [[STRUCT_INT16X8X3_T]], align 16
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 48, ptr [[VEC3]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP6:%.*]] = ptrtoint ptr [[VEC3]] to i64
// CHECK-NEXT:    [[TMP7:%.*]] = xor i64 [[TMP6]], 193514046488576
// CHECK-NEXT:    [[TMP8:%.*]] = inttoptr i64 [[TMP7]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP8]], i8 -1, i64 48, i1 false)
// CHECK-NEXT:    [[TMP9:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP9]], 193514046488576
// CHECK-NEXT:    [[TMP11:%.*]] = inttoptr i64 [[TMP10]] to ptr
// CHECK-NEXT:    store i16 0, ptr [[TMP11]], align 2
// CHECK-NEXT:    store i16 17, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP13:%.*]] = xor i64 [[TMP12]], 193514046488576
// CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i64 [[TMP13]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP14]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP16:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP17:%.*]] = xor i64 [[TMP16]], 193514046488576
// CHECK-NEXT:    [[TMP18:%.*]] = inttoptr i64 [[TMP17]] to ptr
// CHECK-NEXT:    [[_MSLD:%.*]] = load i16, ptr [[TMP18]], align 2
// CHECK-NEXT:    [[_MSPROP:%.*]] = insertelement <8 x i16> <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>, i16 [[_MSLD]], i32 0
// CHECK-NEXT:    [[VECINIT_I:%.*]] = insertelement <8 x i16> poison, i16 [[TMP15]], i32 0
// CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP20:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP21:%.*]] = xor i64 [[TMP20]], 193514046488576
// CHECK-NEXT:    [[TMP22:%.*]] = inttoptr i64 [[TMP21]] to ptr
// CHECK-NEXT:    [[_MSLD9:%.*]] = load i16, ptr [[TMP22]], align 2
// CHECK-NEXT:    [[_MSPROP10:%.*]] = insertelement <8 x i16> [[_MSPROP]], i16 [[_MSLD9]], i32 1
// CHECK-NEXT:    [[VECINIT1_I:%.*]] = insertelement <8 x i16> [[VECINIT_I]], i16 [[TMP19]], i32 1
// CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP24:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP25:%.*]] = xor i64 [[TMP24]], 193514046488576
// CHECK-NEXT:    [[TMP26:%.*]] = inttoptr i64 [[TMP25]] to ptr
// CHECK-NEXT:    [[_MSLD11:%.*]] = load i16, ptr [[TMP26]], align 2
// CHECK-NEXT:    [[_MSPROP12:%.*]] = insertelement <8 x i16> [[_MSPROP10]], i16 [[_MSLD11]], i32 2
// CHECK-NEXT:    [[VECINIT2_I:%.*]] = insertelement <8 x i16> [[VECINIT1_I]], i16 [[TMP23]], i32 2
// CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP28:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP29:%.*]] = xor i64 [[TMP28]], 193514046488576
// CHECK-NEXT:    [[TMP30:%.*]] = inttoptr i64 [[TMP29]] to ptr
// CHECK-NEXT:    [[_MSLD13:%.*]] = load i16, ptr [[TMP30]], align 2
// CHECK-NEXT:    [[_MSPROP14:%.*]] = insertelement <8 x i16> [[_MSPROP12]], i16 [[_MSLD13]], i32 3
// CHECK-NEXT:    [[VECINIT3_I:%.*]] = insertelement <8 x i16> [[VECINIT2_I]], i16 [[TMP27]], i32 3
// CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP32:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP33:%.*]] = xor i64 [[TMP32]], 193514046488576
// CHECK-NEXT:    [[TMP34:%.*]] = inttoptr i64 [[TMP33]] to ptr
// CHECK-NEXT:    [[_MSLD15:%.*]] = load i16, ptr [[TMP34]], align 2
// CHECK-NEXT:    [[_MSPROP16:%.*]] = insertelement <8 x i16> [[_MSPROP14]], i16 [[_MSLD15]], i32 4
// CHECK-NEXT:    [[VECINIT4_I:%.*]] = insertelement <8 x i16> [[VECINIT3_I]], i16 [[TMP31]], i32 4
// CHECK-NEXT:    [[TMP35:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP36:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP37:%.*]] = xor i64 [[TMP36]], 193514046488576
// CHECK-NEXT:    [[TMP38:%.*]] = inttoptr i64 [[TMP37]] to ptr
// CHECK-NEXT:    [[_MSLD17:%.*]] = load i16, ptr [[TMP38]], align 2
// CHECK-NEXT:    [[_MSPROP18:%.*]] = insertelement <8 x i16> [[_MSPROP16]], i16 [[_MSLD17]], i32 5
// CHECK-NEXT:    [[VECINIT5_I:%.*]] = insertelement <8 x i16> [[VECINIT4_I]], i16 [[TMP35]], i32 5
// CHECK-NEXT:    [[TMP39:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP40:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP41:%.*]] = xor i64 [[TMP40]], 193514046488576
// CHECK-NEXT:    [[TMP42:%.*]] = inttoptr i64 [[TMP41]] to ptr
// CHECK-NEXT:    [[_MSLD19:%.*]] = load i16, ptr [[TMP42]], align 2
// CHECK-NEXT:    [[_MSPROP20:%.*]] = insertelement <8 x i16> [[_MSPROP18]], i16 [[_MSLD19]], i32 6
// CHECK-NEXT:    [[VECINIT6_I:%.*]] = insertelement <8 x i16> [[VECINIT5_I]], i16 [[TMP39]], i32 6
// CHECK-NEXT:    [[TMP43:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP44:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP45:%.*]] = xor i64 [[TMP44]], 193514046488576
// CHECK-NEXT:    [[TMP46:%.*]] = inttoptr i64 [[TMP45]] to ptr
// CHECK-NEXT:    [[_MSLD21:%.*]] = load i16, ptr [[TMP46]], align 2
// CHECK-NEXT:    [[_MSPROP22:%.*]] = insertelement <8 x i16> [[_MSPROP20]], i16 [[_MSLD21]], i32 7
// CHECK-NEXT:    [[VECINIT7_I:%.*]] = insertelement <8 x i16> [[VECINIT6_I]], i16 [[TMP43]], i32 7
// CHECK-NEXT:    [[TMP47:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP48:%.*]] = xor i64 [[TMP47]], 193514046488576
// CHECK-NEXT:    [[TMP49:%.*]] = inttoptr i64 [[TMP48]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSPROP22]], ptr [[TMP49]], align 16
// CHECK-NEXT:    store <8 x i16> [[VECINIT7_I]], ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP50:%.*]] = load <8 x i16>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP51:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP52:%.*]] = xor i64 [[TMP51]], 193514046488576
// CHECK-NEXT:    [[TMP53:%.*]] = inttoptr i64 [[TMP52]] to ptr
// CHECK-NEXT:    [[_MSLD23:%.*]] = load <8 x i16>, ptr [[TMP53]], align 16
// CHECK-NEXT:    [[TMP54:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP55:%.*]] = xor i64 [[TMP54]], 193514046488576
// CHECK-NEXT:    [[TMP56:%.*]] = inttoptr i64 [[TMP55]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD23]], ptr [[TMP56]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP50]], ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP57:%.*]] = load <8 x i16>, ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP58:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP59:%.*]] = xor i64 [[TMP58]], 193514046488576
// CHECK-NEXT:    [[TMP60:%.*]] = inttoptr i64 [[TMP59]] to ptr
// CHECK-NEXT:    [[_MSLD24:%.*]] = load <8 x i16>, ptr [[TMP60]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[VAL:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X3_T]], ptr [[VEC3]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [3 x <8 x i16>], ptr [[VAL]], i64 0, i64 1
// CHECK-NEXT:    [[TMP61:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64
// CHECK-NEXT:    [[TMP62:%.*]] = xor i64 [[TMP61]], 193514046488576
// CHECK-NEXT:    [[TMP63:%.*]] = inttoptr i64 [[TMP62]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD24]], ptr [[TMP63]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP57]], ptr [[ARRAYIDX]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 48, ptr [[DST3]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP64:%.*]] = ptrtoint ptr [[DST3]] to i64
// CHECK-NEXT:    [[TMP65:%.*]] = xor i64 [[TMP64]], 193514046488576
// CHECK-NEXT:    [[TMP66:%.*]] = inttoptr i64 [[TMP65]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP66]], i8 -1, i64 48, i1 false)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 48, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP67:%.*]] = ptrtoint ptr [[__S1]] to i64
// CHECK-NEXT:    [[TMP68:%.*]] = xor i64 [[TMP67]], 193514046488576
// CHECK-NEXT:    [[TMP69:%.*]] = inttoptr i64 [[TMP68]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP69]], i8 -1, i64 48, i1 false)
// CHECK-NEXT:    [[TMP70:%.*]] = call ptr @__msan_memcpy(ptr [[__S1]], ptr [[VEC3]], i64 48)
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [24 x i16], ptr [[DST3]], i64 0, i64 0
// CHECK-NEXT:    [[VAL1:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X3_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [3 x <8 x i16>], ptr [[VAL1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP71:%.*]] = load <8 x i16>, ptr [[ARRAYIDX2]], align 16
// CHECK-NEXT:    [[TMP72:%.*]] = ptrtoint ptr [[ARRAYIDX2]] to i64
// CHECK-NEXT:    [[TMP73:%.*]] = xor i64 [[TMP72]], 193514046488576
// CHECK-NEXT:    [[TMP74:%.*]] = inttoptr i64 [[TMP73]] to ptr
// CHECK-NEXT:    [[_MSLD25:%.*]] = load <8 x i16>, ptr [[TMP74]], align 16
// CHECK-NEXT:    [[TMP75:%.*]] = bitcast <8 x i16> [[_MSLD25]] to <16 x i8>
// CHECK-NEXT:    [[TMP76:%.*]] = bitcast <8 x i16> [[TMP71]] to <16 x i8>
// CHECK-NEXT:    [[VAL3:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X3_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds [3 x <8 x i16>], ptr [[VAL3]], i64 0, i64 1
// CHECK-NEXT:    [[TMP77:%.*]] = load <8 x i16>, ptr [[ARRAYIDX4]], align 16
// CHECK-NEXT:    [[TMP78:%.*]] = ptrtoint ptr [[ARRAYIDX4]] to i64
// CHECK-NEXT:    [[TMP79:%.*]] = xor i64 [[TMP78]], 193514046488576
// CHECK-NEXT:    [[TMP80:%.*]] = inttoptr i64 [[TMP79]] to ptr
// CHECK-NEXT:    [[_MSLD26:%.*]] = load <8 x i16>, ptr [[TMP80]], align 16
// CHECK-NEXT:    [[TMP81:%.*]] = bitcast <8 x i16> [[_MSLD26]] to <16 x i8>
// CHECK-NEXT:    [[TMP82:%.*]] = bitcast <8 x i16> [[TMP77]] to <16 x i8>
// CHECK-NEXT:    [[VAL5:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X3_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [3 x <8 x i16>], ptr [[VAL5]], i64 0, i64 2
// CHECK-NEXT:    [[TMP83:%.*]] = load <8 x i16>, ptr [[ARRAYIDX6]], align 16
// CHECK-NEXT:    [[TMP84:%.*]] = ptrtoint ptr [[ARRAYIDX6]] to i64
// CHECK-NEXT:    [[TMP85:%.*]] = xor i64 [[TMP84]], 193514046488576
// CHECK-NEXT:    [[TMP86:%.*]] = inttoptr i64 [[TMP85]] to ptr
// CHECK-NEXT:    [[_MSLD27:%.*]] = load <8 x i16>, ptr [[TMP86]], align 16
// CHECK-NEXT:    [[TMP87:%.*]] = bitcast <8 x i16> [[_MSLD27]] to <16 x i8>
// CHECK-NEXT:    [[TMP88:%.*]] = bitcast <8 x i16> [[TMP83]] to <16 x i8>
// CHECK-NEXT:    [[TMP89:%.*]] = bitcast <16 x i8> [[TMP75]] to <8 x i16>
// CHECK-NEXT:    [[TMP90:%.*]] = bitcast <16 x i8> [[TMP76]] to <8 x i16>
// CHECK-NEXT:    [[TMP91:%.*]] = bitcast <16 x i8> [[TMP81]] to <8 x i16>
// CHECK-NEXT:    [[TMP92:%.*]] = bitcast <16 x i8> [[TMP82]] to <8 x i16>
// CHECK-NEXT:    [[TMP93:%.*]] = bitcast <16 x i8> [[TMP87]] to <8 x i16>
// CHECK-NEXT:    [[TMP94:%.*]] = bitcast <16 x i8> [[TMP88]] to <8 x i16>
// CHECK-NEXT:    [[TMP95:%.*]] = bitcast <8 x i16> [[TMP89]] to i128
// CHECK-NEXT:    [[_MSCMP:%.*]] = icmp ne i128 [[TMP95]], 0
// CHECK-NEXT:    [[TMP96:%.*]] = bitcast <8 x i16> [[TMP91]] to i128
// CHECK-NEXT:    [[_MSCMP40:%.*]] = icmp ne i128 [[TMP96]], 0
// CHECK-NEXT:    [[_MSOR:%.*]] = or i1 [[_MSCMP]], [[_MSCMP40]]
// CHECK-NEXT:    [[TMP97:%.*]] = bitcast <8 x i16> [[TMP93]] to i128
// CHECK-NEXT:    [[_MSCMP41:%.*]] = icmp ne i128 [[TMP97]], 0
// CHECK-NEXT:    [[_MSOR42:%.*]] = or i1 [[_MSOR]], [[_MSCMP41]]
// CHECK-NEXT:    br i1 [[_MSOR42]], label [[TMP98:%.*]], label [[TMP99:%.*]], !prof [[PROF2]]
// CHECK:       98:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       99:
// CHECK-NEXT:    call void @llvm.aarch64.neon.st3.v8i16.p0(<8 x i16> [[TMP90]], <8 x i16> [[TMP92]], <8 x i16> [[TMP94]], ptr [[ARRAYDECAY]])
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 48, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[ARRAYDECAY7:%.*]] = getelementptr inbounds [24 x i16], ptr [[DST3]], i64 0, i64 0
// CHECK-NEXT:    call void @__msan_print_shadow(ptr noundef [[ARRAYDECAY7]], i64 noundef 48)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP100:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP101:%.*]] = xor i64 [[TMP100]], 193514046488576
// CHECK-NEXT:    [[TMP102:%.*]] = inttoptr i64 [[TMP101]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP102]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP103:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP104:%.*]] = xor i64 [[TMP103]], 193514046488576
// CHECK-NEXT:    [[TMP105:%.*]] = inttoptr i64 [[TMP104]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP105]], align 4
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP106:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP107:%.*]] = xor i64 [[TMP106]], 193514046488576
// CHECK-NEXT:    [[TMP108:%.*]] = inttoptr i64 [[TMP107]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP108]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP109:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP110:%.*]] = xor i64 [[TMP109]], 193514046488576
// CHECK-NEXT:    [[TMP111:%.*]] = inttoptr i64 [[TMP110]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP111]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[TMP112:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP113:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP114:%.*]] = xor i64 [[TMP113]], 193514046488576
// CHECK-NEXT:    [[TMP115:%.*]] = inttoptr i64 [[TMP114]] to ptr
// CHECK-NEXT:    [[_MSLD28:%.*]] = load i32, ptr [[TMP115]], align 4
// CHECK-NEXT:    [[_MSPROP29:%.*]] = or i32 [[_MSLD28]], 0
// CHECK-NEXT:    [[TMP116:%.*]] = icmp ne i32 [[_MSPROP29]], 0
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP112]], 24
// CHECK-NEXT:    br i1 [[TMP116]], label [[TMP117:%.*]], label [[TMP118:%.*]], !prof [[PROF2]]
// CHECK:       117:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       118:
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_COND_CLEANUP:%.*]]
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    br label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[TMP119:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP120:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP121:%.*]] = xor i64 [[TMP120]], 193514046488576
// CHECK-NEXT:    [[TMP122:%.*]] = inttoptr i64 [[TMP121]] to ptr
// CHECK-NEXT:    [[_MSLD30:%.*]] = load i32, ptr [[TMP122]], align 4
// CHECK-NEXT:    [[_MSPROP31:%.*]] = sext i32 [[_MSLD30]] to i64
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP119]] to i64
// CHECK-NEXT:    [[_MSPROP32:%.*]] = or i64 0, [[_MSPROP31]]
// CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [24 x i16], ptr [[DST3]], i64 0, i64 [[IDXPROM]]
// CHECK-NEXT:    [[_MSCMP43:%.*]] = icmp ne i64 [[_MSPROP32]], 0
// CHECK-NEXT:    br i1 [[_MSCMP43]], label [[TMP123:%.*]], label [[TMP124:%.*]], !prof [[PROF2]]
// CHECK:       123:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       124:
// CHECK-NEXT:    [[TMP125:%.*]] = load i16, ptr [[ARRAYIDX8]], align 2
// CHECK-NEXT:    [[TMP126:%.*]] = ptrtoint ptr [[ARRAYIDX8]] to i64
// CHECK-NEXT:    [[TMP127:%.*]] = xor i64 [[TMP126]], 193514046488576
// CHECK-NEXT:    [[TMP128:%.*]] = inttoptr i64 [[TMP127]] to ptr
// CHECK-NEXT:    [[_MSLD33:%.*]] = load i16, ptr [[TMP128]], align 2
// CHECK-NEXT:    [[_MSPROP34:%.*]] = sext i16 [[_MSLD33]] to i32
// CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP125]] to i32
// CHECK-NEXT:    [[TMP129:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP130:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP131:%.*]] = xor i64 [[TMP130]], 193514046488576
// CHECK-NEXT:    [[TMP132:%.*]] = inttoptr i64 [[TMP131]] to ptr
// CHECK-NEXT:    [[_MSLD35:%.*]] = load i32, ptr [[TMP132]], align 4
// CHECK-NEXT:    [[_MSPROP36:%.*]] = or i32 [[_MSLD35]], [[_MSPROP34]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP129]], [[CONV]]
// CHECK-NEXT:    [[TMP133:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP134:%.*]] = xor i64 [[TMP133]], 193514046488576
// CHECK-NEXT:    [[TMP135:%.*]] = inttoptr i64 [[TMP134]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP36]], ptr [[TMP135]], align 4
// CHECK-NEXT:    store i32 [[ADD]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label [[FOR_INC:%.*]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[TMP136:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP137:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP138:%.*]] = xor i64 [[TMP137]], 193514046488576
// CHECK-NEXT:    [[TMP139:%.*]] = inttoptr i64 [[TMP138]] to ptr
// CHECK-NEXT:    [[_MSLD37:%.*]] = load i32, ptr [[TMP139]], align 4
// CHECK-NEXT:    [[_MSPROP38:%.*]] = or i32 [[_MSLD37]], 0
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP136]], 1
// CHECK-NEXT:    [[TMP140:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP141:%.*]] = xor i64 [[TMP140]], 193514046488576
// CHECK-NEXT:    [[TMP142:%.*]] = inttoptr i64 [[TMP141]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP38]], ptr [[TMP142]], align 4
// CHECK-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP6:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    [[TMP143:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP144:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP145:%.*]] = xor i64 [[TMP144]], 193514046488576
// CHECK-NEXT:    [[TMP146:%.*]] = inttoptr i64 [[TMP145]] to ptr
// CHECK-NEXT:    [[_MSLD39:%.*]] = load i32, ptr [[TMP146]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 48, ptr [[DST3]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 48, ptr [[VEC3]]) #[[ATTR4]]
// CHECK-NEXT:    [[_MSCMP44:%.*]] = icmp ne i32 [[_MSLD39]], 0
// CHECK-NEXT:    br i1 [[_MSCMP44]], label [[TMP147:%.*]], label [[TMP148:%.*]], !prof [[PROF2]]
// CHECK:       147:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       148:
// CHECK-NEXT:    ret i32 [[TMP143]]
//
int test_vst3(void) {
  int16x8x3_t vec3;
  vec3.val[1] = vdupq_n_s16(17);
  int16_t dst3[8*3];
  vst3q_s16(dst3, vec3);

  __msan_print_shadow(dst3, sizeof(int16_t)*8*3);

  int sum = 0;
  for (int i = 0; i < 8*3; i++)
    sum += dst3[i];

  return sum;
}

// CHECK-LABEL: define dso_local noundef i32 @test_vst4(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.donothing()
// CHECK-NEXT:    [[__P0_ADDR_I:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = xor i64 [[TMP0]], 193514046488576
// CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[TMP1]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP2]], i8 -1, i64 2, i1 false)
// CHECK-NEXT:    [[__RET_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[DOTCOMPOUNDLITERAL_I:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = xor i64 [[TMP3]], 193514046488576
// CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[TMP4]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP5]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[VEC4:%.*]] = alloca [[STRUCT_INT16X8X4_T:%.*]], align 16
// CHECK-NEXT:    [[DST4:%.*]] = alloca [32 x i16], align 2
// CHECK-NEXT:    [[__S1:%.*]] = alloca [[STRUCT_INT16X8X4_T]], align 16
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 64, ptr [[VEC4]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP6:%.*]] = ptrtoint ptr [[VEC4]] to i64
// CHECK-NEXT:    [[TMP7:%.*]] = xor i64 [[TMP6]], 193514046488576
// CHECK-NEXT:    [[TMP8:%.*]] = inttoptr i64 [[TMP7]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP8]], i8 -1, i64 64, i1 false)
// CHECK-NEXT:    [[TMP9:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP9]], 193514046488576
// CHECK-NEXT:    [[TMP11:%.*]] = inttoptr i64 [[TMP10]] to ptr
// CHECK-NEXT:    store i16 0, ptr [[TMP11]], align 2
// CHECK-NEXT:    store i16 18, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP13:%.*]] = xor i64 [[TMP12]], 193514046488576
// CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i64 [[TMP13]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP14]], i8 -1, i64 16, i1 false)
// CHECK-NEXT:    [[TMP15:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP16:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP17:%.*]] = xor i64 [[TMP16]], 193514046488576
// CHECK-NEXT:    [[TMP18:%.*]] = inttoptr i64 [[TMP17]] to ptr
// CHECK-NEXT:    [[_MSLD:%.*]] = load i16, ptr [[TMP18]], align 2
// CHECK-NEXT:    [[_MSPROP:%.*]] = insertelement <8 x i16> <i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1, i16 -1>, i16 [[_MSLD]], i32 0
// CHECK-NEXT:    [[VECINIT_I:%.*]] = insertelement <8 x i16> poison, i16 [[TMP15]], i32 0
// CHECK-NEXT:    [[TMP19:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP20:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP21:%.*]] = xor i64 [[TMP20]], 193514046488576
// CHECK-NEXT:    [[TMP22:%.*]] = inttoptr i64 [[TMP21]] to ptr
// CHECK-NEXT:    [[_MSLD11:%.*]] = load i16, ptr [[TMP22]], align 2
// CHECK-NEXT:    [[_MSPROP12:%.*]] = insertelement <8 x i16> [[_MSPROP]], i16 [[_MSLD11]], i32 1
// CHECK-NEXT:    [[VECINIT1_I:%.*]] = insertelement <8 x i16> [[VECINIT_I]], i16 [[TMP19]], i32 1
// CHECK-NEXT:    [[TMP23:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP24:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP25:%.*]] = xor i64 [[TMP24]], 193514046488576
// CHECK-NEXT:    [[TMP26:%.*]] = inttoptr i64 [[TMP25]] to ptr
// CHECK-NEXT:    [[_MSLD13:%.*]] = load i16, ptr [[TMP26]], align 2
// CHECK-NEXT:    [[_MSPROP14:%.*]] = insertelement <8 x i16> [[_MSPROP12]], i16 [[_MSLD13]], i32 2
// CHECK-NEXT:    [[VECINIT2_I:%.*]] = insertelement <8 x i16> [[VECINIT1_I]], i16 [[TMP23]], i32 2
// CHECK-NEXT:    [[TMP27:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP28:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP29:%.*]] = xor i64 [[TMP28]], 193514046488576
// CHECK-NEXT:    [[TMP30:%.*]] = inttoptr i64 [[TMP29]] to ptr
// CHECK-NEXT:    [[_MSLD15:%.*]] = load i16, ptr [[TMP30]], align 2
// CHECK-NEXT:    [[_MSPROP16:%.*]] = insertelement <8 x i16> [[_MSPROP14]], i16 [[_MSLD15]], i32 3
// CHECK-NEXT:    [[VECINIT3_I:%.*]] = insertelement <8 x i16> [[VECINIT2_I]], i16 [[TMP27]], i32 3
// CHECK-NEXT:    [[TMP31:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP32:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP33:%.*]] = xor i64 [[TMP32]], 193514046488576
// CHECK-NEXT:    [[TMP34:%.*]] = inttoptr i64 [[TMP33]] to ptr
// CHECK-NEXT:    [[_MSLD17:%.*]] = load i16, ptr [[TMP34]], align 2
// CHECK-NEXT:    [[_MSPROP18:%.*]] = insertelement <8 x i16> [[_MSPROP16]], i16 [[_MSLD17]], i32 4
// CHECK-NEXT:    [[VECINIT4_I:%.*]] = insertelement <8 x i16> [[VECINIT3_I]], i16 [[TMP31]], i32 4
// CHECK-NEXT:    [[TMP35:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP36:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP37:%.*]] = xor i64 [[TMP36]], 193514046488576
// CHECK-NEXT:    [[TMP38:%.*]] = inttoptr i64 [[TMP37]] to ptr
// CHECK-NEXT:    [[_MSLD19:%.*]] = load i16, ptr [[TMP38]], align 2
// CHECK-NEXT:    [[_MSPROP20:%.*]] = insertelement <8 x i16> [[_MSPROP18]], i16 [[_MSLD19]], i32 5
// CHECK-NEXT:    [[VECINIT5_I:%.*]] = insertelement <8 x i16> [[VECINIT4_I]], i16 [[TMP35]], i32 5
// CHECK-NEXT:    [[TMP39:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP40:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP41:%.*]] = xor i64 [[TMP40]], 193514046488576
// CHECK-NEXT:    [[TMP42:%.*]] = inttoptr i64 [[TMP41]] to ptr
// CHECK-NEXT:    [[_MSLD21:%.*]] = load i16, ptr [[TMP42]], align 2
// CHECK-NEXT:    [[_MSPROP22:%.*]] = insertelement <8 x i16> [[_MSPROP20]], i16 [[_MSLD21]], i32 6
// CHECK-NEXT:    [[VECINIT6_I:%.*]] = insertelement <8 x i16> [[VECINIT5_I]], i16 [[TMP39]], i32 6
// CHECK-NEXT:    [[TMP43:%.*]] = load i16, ptr [[__P0_ADDR_I]], align 2
// CHECK-NEXT:    [[TMP44:%.*]] = ptrtoint ptr [[__P0_ADDR_I]] to i64
// CHECK-NEXT:    [[TMP45:%.*]] = xor i64 [[TMP44]], 193514046488576
// CHECK-NEXT:    [[TMP46:%.*]] = inttoptr i64 [[TMP45]] to ptr
// CHECK-NEXT:    [[_MSLD23:%.*]] = load i16, ptr [[TMP46]], align 2
// CHECK-NEXT:    [[_MSPROP24:%.*]] = insertelement <8 x i16> [[_MSPROP22]], i16 [[_MSLD23]], i32 7
// CHECK-NEXT:    [[VECINIT7_I:%.*]] = insertelement <8 x i16> [[VECINIT6_I]], i16 [[TMP43]], i32 7
// CHECK-NEXT:    [[TMP47:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP48:%.*]] = xor i64 [[TMP47]], 193514046488576
// CHECK-NEXT:    [[TMP49:%.*]] = inttoptr i64 [[TMP48]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSPROP24]], ptr [[TMP49]], align 16
// CHECK-NEXT:    store <8 x i16> [[VECINIT7_I]], ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP50:%.*]] = load <8 x i16>, ptr [[DOTCOMPOUNDLITERAL_I]], align 16
// CHECK-NEXT:    [[TMP51:%.*]] = ptrtoint ptr [[DOTCOMPOUNDLITERAL_I]] to i64
// CHECK-NEXT:    [[TMP52:%.*]] = xor i64 [[TMP51]], 193514046488576
// CHECK-NEXT:    [[TMP53:%.*]] = inttoptr i64 [[TMP52]] to ptr
// CHECK-NEXT:    [[_MSLD25:%.*]] = load <8 x i16>, ptr [[TMP53]], align 16
// CHECK-NEXT:    [[TMP54:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP55:%.*]] = xor i64 [[TMP54]], 193514046488576
// CHECK-NEXT:    [[TMP56:%.*]] = inttoptr i64 [[TMP55]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD25]], ptr [[TMP56]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP50]], ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP57:%.*]] = load <8 x i16>, ptr [[__RET_I]], align 16
// CHECK-NEXT:    [[TMP58:%.*]] = ptrtoint ptr [[__RET_I]] to i64
// CHECK-NEXT:    [[TMP59:%.*]] = xor i64 [[TMP58]], 193514046488576
// CHECK-NEXT:    [[TMP60:%.*]] = inttoptr i64 [[TMP59]] to ptr
// CHECK-NEXT:    [[_MSLD26:%.*]] = load <8 x i16>, ptr [[TMP60]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 16, ptr [[__RET_I]]) #[[ATTR4]]
// CHECK-NEXT:    [[VAL:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X4_T]], ptr [[VEC4]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x <8 x i16>], ptr [[VAL]], i64 0, i64 2
// CHECK-NEXT:    [[TMP61:%.*]] = ptrtoint ptr [[ARRAYIDX]] to i64
// CHECK-NEXT:    [[TMP62:%.*]] = xor i64 [[TMP61]], 193514046488576
// CHECK-NEXT:    [[TMP63:%.*]] = inttoptr i64 [[TMP62]] to ptr
// CHECK-NEXT:    store <8 x i16> [[_MSLD26]], ptr [[TMP63]], align 16
// CHECK-NEXT:    store <8 x i16> [[TMP57]], ptr [[ARRAYIDX]], align 16
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 64, ptr [[DST4]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP64:%.*]] = ptrtoint ptr [[DST4]] to i64
// CHECK-NEXT:    [[TMP65:%.*]] = xor i64 [[TMP64]], 193514046488576
// CHECK-NEXT:    [[TMP66:%.*]] = inttoptr i64 [[TMP65]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 2 [[TMP66]], i8 -1, i64 64, i1 false)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 64, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP67:%.*]] = ptrtoint ptr [[__S1]] to i64
// CHECK-NEXT:    [[TMP68:%.*]] = xor i64 [[TMP67]], 193514046488576
// CHECK-NEXT:    [[TMP69:%.*]] = inttoptr i64 [[TMP68]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[TMP69]], i8 -1, i64 64, i1 false)
// CHECK-NEXT:    [[TMP70:%.*]] = call ptr @__msan_memcpy(ptr [[__S1]], ptr [[VEC4]], i64 64)
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [32 x i16], ptr [[DST4]], i64 0, i64 0
// CHECK-NEXT:    [[VAL1:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X4_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds [4 x <8 x i16>], ptr [[VAL1]], i64 0, i64 0
// CHECK-NEXT:    [[TMP71:%.*]] = load <8 x i16>, ptr [[ARRAYIDX2]], align 16
// CHECK-NEXT:    [[TMP72:%.*]] = ptrtoint ptr [[ARRAYIDX2]] to i64
// CHECK-NEXT:    [[TMP73:%.*]] = xor i64 [[TMP72]], 193514046488576
// CHECK-NEXT:    [[TMP74:%.*]] = inttoptr i64 [[TMP73]] to ptr
// CHECK-NEXT:    [[_MSLD27:%.*]] = load <8 x i16>, ptr [[TMP74]], align 16
// CHECK-NEXT:    [[TMP75:%.*]] = bitcast <8 x i16> [[_MSLD27]] to <16 x i8>
// CHECK-NEXT:    [[TMP76:%.*]] = bitcast <8 x i16> [[TMP71]] to <16 x i8>
// CHECK-NEXT:    [[VAL3:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X4_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds [4 x <8 x i16>], ptr [[VAL3]], i64 0, i64 1
// CHECK-NEXT:    [[TMP77:%.*]] = load <8 x i16>, ptr [[ARRAYIDX4]], align 16
// CHECK-NEXT:    [[TMP78:%.*]] = ptrtoint ptr [[ARRAYIDX4]] to i64
// CHECK-NEXT:    [[TMP79:%.*]] = xor i64 [[TMP78]], 193514046488576
// CHECK-NEXT:    [[TMP80:%.*]] = inttoptr i64 [[TMP79]] to ptr
// CHECK-NEXT:    [[_MSLD28:%.*]] = load <8 x i16>, ptr [[TMP80]], align 16
// CHECK-NEXT:    [[TMP81:%.*]] = bitcast <8 x i16> [[_MSLD28]] to <16 x i8>
// CHECK-NEXT:    [[TMP82:%.*]] = bitcast <8 x i16> [[TMP77]] to <16 x i8>
// CHECK-NEXT:    [[VAL5:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X4_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX6:%.*]] = getelementptr inbounds [4 x <8 x i16>], ptr [[VAL5]], i64 0, i64 2
// CHECK-NEXT:    [[TMP83:%.*]] = load <8 x i16>, ptr [[ARRAYIDX6]], align 16
// CHECK-NEXT:    [[TMP84:%.*]] = ptrtoint ptr [[ARRAYIDX6]] to i64
// CHECK-NEXT:    [[TMP85:%.*]] = xor i64 [[TMP84]], 193514046488576
// CHECK-NEXT:    [[TMP86:%.*]] = inttoptr i64 [[TMP85]] to ptr
// CHECK-NEXT:    [[_MSLD29:%.*]] = load <8 x i16>, ptr [[TMP86]], align 16
// CHECK-NEXT:    [[TMP87:%.*]] = bitcast <8 x i16> [[_MSLD29]] to <16 x i8>
// CHECK-NEXT:    [[TMP88:%.*]] = bitcast <8 x i16> [[TMP83]] to <16 x i8>
// CHECK-NEXT:    [[VAL7:%.*]] = getelementptr inbounds [[STRUCT_INT16X8X4_T]], ptr [[__S1]], i32 0, i32 0
// CHECK-NEXT:    [[ARRAYIDX8:%.*]] = getelementptr inbounds [4 x <8 x i16>], ptr [[VAL7]], i64 0, i64 3
// CHECK-NEXT:    [[TMP89:%.*]] = load <8 x i16>, ptr [[ARRAYIDX8]], align 16
// CHECK-NEXT:    [[TMP90:%.*]] = ptrtoint ptr [[ARRAYIDX8]] to i64
// CHECK-NEXT:    [[TMP91:%.*]] = xor i64 [[TMP90]], 193514046488576
// CHECK-NEXT:    [[TMP92:%.*]] = inttoptr i64 [[TMP91]] to ptr
// CHECK-NEXT:    [[_MSLD30:%.*]] = load <8 x i16>, ptr [[TMP92]], align 16
// CHECK-NEXT:    [[TMP93:%.*]] = bitcast <8 x i16> [[_MSLD30]] to <16 x i8>
// CHECK-NEXT:    [[TMP94:%.*]] = bitcast <8 x i16> [[TMP89]] to <16 x i8>
// CHECK-NEXT:    [[TMP95:%.*]] = bitcast <16 x i8> [[TMP75]] to <8 x i16>
// CHECK-NEXT:    [[TMP96:%.*]] = bitcast <16 x i8> [[TMP76]] to <8 x i16>
// CHECK-NEXT:    [[TMP97:%.*]] = bitcast <16 x i8> [[TMP81]] to <8 x i16>
// CHECK-NEXT:    [[TMP98:%.*]] = bitcast <16 x i8> [[TMP82]] to <8 x i16>
// CHECK-NEXT:    [[TMP99:%.*]] = bitcast <16 x i8> [[TMP87]] to <8 x i16>
// CHECK-NEXT:    [[TMP100:%.*]] = bitcast <16 x i8> [[TMP88]] to <8 x i16>
// CHECK-NEXT:    [[TMP101:%.*]] = bitcast <16 x i8> [[TMP93]] to <8 x i16>
// CHECK-NEXT:    [[TMP102:%.*]] = bitcast <16 x i8> [[TMP94]] to <8 x i16>
// CHECK-NEXT:    [[TMP103:%.*]] = bitcast <8 x i16> [[TMP95]] to i128
// CHECK-NEXT:    [[_MSCMP:%.*]] = icmp ne i128 [[TMP103]], 0
// CHECK-NEXT:    [[TMP104:%.*]] = bitcast <8 x i16> [[TMP97]] to i128
// CHECK-NEXT:    [[_MSCMP43:%.*]] = icmp ne i128 [[TMP104]], 0
// CHECK-NEXT:    [[_MSOR:%.*]] = or i1 [[_MSCMP]], [[_MSCMP43]]
// CHECK-NEXT:    [[TMP105:%.*]] = bitcast <8 x i16> [[TMP99]] to i128
// CHECK-NEXT:    [[_MSCMP44:%.*]] = icmp ne i128 [[TMP105]], 0
// CHECK-NEXT:    [[_MSOR45:%.*]] = or i1 [[_MSOR]], [[_MSCMP44]]
// CHECK-NEXT:    [[TMP106:%.*]] = bitcast <8 x i16> [[TMP101]] to i128
// CHECK-NEXT:    [[_MSCMP46:%.*]] = icmp ne i128 [[TMP106]], 0
// CHECK-NEXT:    [[_MSOR47:%.*]] = or i1 [[_MSOR45]], [[_MSCMP46]]
// CHECK-NEXT:    br i1 [[_MSOR47]], label [[TMP107:%.*]], label [[TMP108:%.*]], !prof [[PROF2]]
// CHECK:       107:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       108:
// CHECK-NEXT:    call void @llvm.aarch64.neon.st4.v8i16.p0(<8 x i16> [[TMP96]], <8 x i16> [[TMP98]], <8 x i16> [[TMP100]], <8 x i16> [[TMP102]], ptr [[ARRAYDECAY]])
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 64, ptr [[__S1]]) #[[ATTR4]]
// CHECK-NEXT:    [[ARRAYDECAY9:%.*]] = getelementptr inbounds [32 x i16], ptr [[DST4]], i64 0, i64 0
// CHECK-NEXT:    call void @__msan_print_shadow(ptr noundef [[ARRAYDECAY9]], i64 noundef 64)
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP109:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP110:%.*]] = xor i64 [[TMP109]], 193514046488576
// CHECK-NEXT:    [[TMP111:%.*]] = inttoptr i64 [[TMP110]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP111]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP112:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP113:%.*]] = xor i64 [[TMP112]], 193514046488576
// CHECK-NEXT:    [[TMP114:%.*]] = inttoptr i64 [[TMP113]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP114]], align 4
// CHECK-NEXT:    store i32 0, ptr [[SUM]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP115:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP116:%.*]] = xor i64 [[TMP115]], 193514046488576
// CHECK-NEXT:    [[TMP117:%.*]] = inttoptr i64 [[TMP116]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP117]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[TMP118:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP119:%.*]] = xor i64 [[TMP118]], 193514046488576
// CHECK-NEXT:    [[TMP120:%.*]] = inttoptr i64 [[TMP119]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP120]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND:%.*]]
// CHECK:       for.cond:
// CHECK-NEXT:    [[TMP121:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP122:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP123:%.*]] = xor i64 [[TMP122]], 193514046488576
// CHECK-NEXT:    [[TMP124:%.*]] = inttoptr i64 [[TMP123]] to ptr
// CHECK-NEXT:    [[_MSLD31:%.*]] = load i32, ptr [[TMP124]], align 4
// CHECK-NEXT:    [[_MSPROP32:%.*]] = or i32 [[_MSLD31]], 0
// CHECK-NEXT:    [[TMP125:%.*]] = icmp ne i32 [[_MSPROP32]], 0
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP121]], 32
// CHECK-NEXT:    br i1 [[TMP125]], label [[TMP126:%.*]], label [[TMP127:%.*]], !prof [[PROF2]]
// CHECK:       126:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       127:
// CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY:%.*]], label [[FOR_COND_CLEANUP:%.*]]
// CHECK:       for.cond.cleanup:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[I]]) #[[ATTR4]]
// CHECK-NEXT:    br label [[FOR_END:%.*]]
// CHECK:       for.body:
// CHECK-NEXT:    [[TMP128:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP129:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP130:%.*]] = xor i64 [[TMP129]], 193514046488576
// CHECK-NEXT:    [[TMP131:%.*]] = inttoptr i64 [[TMP130]] to ptr
// CHECK-NEXT:    [[_MSLD33:%.*]] = load i32, ptr [[TMP131]], align 4
// CHECK-NEXT:    [[_MSPROP34:%.*]] = sext i32 [[_MSLD33]] to i64
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP128]] to i64
// CHECK-NEXT:    [[_MSPROP35:%.*]] = or i64 0, [[_MSPROP34]]
// CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds [32 x i16], ptr [[DST4]], i64 0, i64 [[IDXPROM]]
// CHECK-NEXT:    [[_MSCMP48:%.*]] = icmp ne i64 [[_MSPROP35]], 0
// CHECK-NEXT:    br i1 [[_MSCMP48]], label [[TMP132:%.*]], label [[TMP133:%.*]], !prof [[PROF2]]
// CHECK:       132:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       133:
// CHECK-NEXT:    [[TMP134:%.*]] = load i16, ptr [[ARRAYIDX10]], align 2
// CHECK-NEXT:    [[TMP135:%.*]] = ptrtoint ptr [[ARRAYIDX10]] to i64
// CHECK-NEXT:    [[TMP136:%.*]] = xor i64 [[TMP135]], 193514046488576
// CHECK-NEXT:    [[TMP137:%.*]] = inttoptr i64 [[TMP136]] to ptr
// CHECK-NEXT:    [[_MSLD36:%.*]] = load i16, ptr [[TMP137]], align 2
// CHECK-NEXT:    [[_MSPROP37:%.*]] = sext i16 [[_MSLD36]] to i32
// CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP134]] to i32
// CHECK-NEXT:    [[TMP138:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP139:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP140:%.*]] = xor i64 [[TMP139]], 193514046488576
// CHECK-NEXT:    [[TMP141:%.*]] = inttoptr i64 [[TMP140]] to ptr
// CHECK-NEXT:    [[_MSLD38:%.*]] = load i32, ptr [[TMP141]], align 4
// CHECK-NEXT:    [[_MSPROP39:%.*]] = or i32 [[_MSLD38]], [[_MSPROP37]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP138]], [[CONV]]
// CHECK-NEXT:    [[TMP142:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP143:%.*]] = xor i64 [[TMP142]], 193514046488576
// CHECK-NEXT:    [[TMP144:%.*]] = inttoptr i64 [[TMP143]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP39]], ptr [[TMP144]], align 4
// CHECK-NEXT:    store i32 [[ADD]], ptr [[SUM]], align 4
// CHECK-NEXT:    br label [[FOR_INC:%.*]]
// CHECK:       for.inc:
// CHECK-NEXT:    [[TMP145:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP146:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP147:%.*]] = xor i64 [[TMP146]], 193514046488576
// CHECK-NEXT:    [[TMP148:%.*]] = inttoptr i64 [[TMP147]] to ptr
// CHECK-NEXT:    [[_MSLD40:%.*]] = load i32, ptr [[TMP148]], align 4
// CHECK-NEXT:    [[_MSPROP41:%.*]] = or i32 [[_MSLD40]], 0
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP145]], 1
// CHECK-NEXT:    [[TMP149:%.*]] = ptrtoint ptr [[I]] to i64
// CHECK-NEXT:    [[TMP150:%.*]] = xor i64 [[TMP149]], 193514046488576
// CHECK-NEXT:    [[TMP151:%.*]] = inttoptr i64 [[TMP150]] to ptr
// CHECK-NEXT:    store i32 [[_MSPROP41]], ptr [[TMP151]], align 4
// CHECK-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-NEXT:    br label [[FOR_COND]], !llvm.loop [[LOOP7:![0-9]+]]
// CHECK:       for.end:
// CHECK-NEXT:    [[TMP152:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP153:%.*]] = ptrtoint ptr [[SUM]] to i64
// CHECK-NEXT:    [[TMP154:%.*]] = xor i64 [[TMP153]], 193514046488576
// CHECK-NEXT:    [[TMP155:%.*]] = inttoptr i64 [[TMP154]] to ptr
// CHECK-NEXT:    [[_MSLD42:%.*]] = load i32, ptr [[TMP155]], align 4
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 4, ptr [[SUM]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 64, ptr [[DST4]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(i64 64, ptr [[VEC4]]) #[[ATTR4]]
// CHECK-NEXT:    [[_MSCMP49:%.*]] = icmp ne i32 [[_MSLD42]], 0
// CHECK-NEXT:    br i1 [[_MSCMP49]], label [[TMP156:%.*]], label [[TMP157:%.*]], !prof [[PROF2]]
// CHECK:       156:
// CHECK-NEXT:    call void @__msan_warning_noreturn() #[[ATTR7]]
// CHECK-NEXT:    unreachable
// CHECK:       157:
// CHECK-NEXT:    ret i32 [[TMP152]]
//
int test_vst4(void) {
  int16x8x4_t vec4;
  vec4.val[2] = vdupq_n_s16(18);
  int16_t dst4[8*4];
  vst4q_s16(dst4, vec4);

  __msan_print_shadow(dst4, sizeof(int16_t)*8*4);

  int sum = 0;
  for (int i = 0; i < 8*4; i++)
    sum += dst4[i];

  return sum;
}

// CHECK-LABEL: define dso_local noundef i32 @main(
// CHECK-SAME: i32 noundef [[ARGC:%.*]], ptr noundef [[ARGV:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    call void @llvm.donothing()
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP0:%.*]] = ptrtoint ptr [[RETVAL]] to i64
// CHECK-NEXT:    [[TMP1:%.*]] = xor i64 [[TMP0]], 193514046488576
// CHECK-NEXT:    [[TMP2:%.*]] = inttoptr i64 [[TMP1]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP2]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[ARGC_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP3:%.*]] = ptrtoint ptr [[ARGC_ADDR]] to i64
// CHECK-NEXT:    [[TMP4:%.*]] = xor i64 [[TMP3]], 193514046488576
// CHECK-NEXT:    [[TMP5:%.*]] = inttoptr i64 [[TMP4]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 4 [[TMP5]], i8 -1, i64 4, i1 false)
// CHECK-NEXT:    [[ARGV_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP6:%.*]] = ptrtoint ptr [[ARGV_ADDR]] to i64
// CHECK-NEXT:    [[TMP7:%.*]] = xor i64 [[TMP6]], 193514046488576
// CHECK-NEXT:    [[TMP8:%.*]] = inttoptr i64 [[TMP7]] to ptr
// CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 8 [[TMP8]], i8 -1, i64 8, i1 false)
// CHECK-NEXT:    [[TMP9:%.*]] = ptrtoint ptr [[RETVAL]] to i64
// CHECK-NEXT:    [[TMP10:%.*]] = xor i64 [[TMP9]], 193514046488576
// CHECK-NEXT:    [[TMP11:%.*]] = inttoptr i64 [[TMP10]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP11]], align 4
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    [[TMP12:%.*]] = ptrtoint ptr [[ARGC_ADDR]] to i64
// CHECK-NEXT:    [[TMP13:%.*]] = xor i64 [[TMP12]], 193514046488576
// CHECK-NEXT:    [[TMP14:%.*]] = inttoptr i64 [[TMP13]] to ptr
// CHECK-NEXT:    store i32 0, ptr [[TMP14]], align 4
// CHECK-NEXT:    store i32 [[ARGC]], ptr [[ARGC_ADDR]], align 4
// CHECK-NEXT:    [[TMP15:%.*]] = ptrtoint ptr [[ARGV_ADDR]] to i64
// CHECK-NEXT:    [[TMP16:%.*]] = xor i64 [[TMP15]], 193514046488576
// CHECK-NEXT:    [[TMP17:%.*]] = inttoptr i64 [[TMP16]] to ptr
// CHECK-NEXT:    store i64 0, ptr [[TMP17]], align 8
// CHECK-NEXT:    store ptr [[ARGV]], ptr [[ARGV_ADDR]], align 8
// CHECK-NEXT:    [[CALL:%.*]] = call noundef i32 @test_vst1()
// CHECK-NEXT:    [[CALL1:%.*]] = call noundef i32 @test_vst2()
// CHECK-NEXT:    [[CALL2:%.*]] = call noundef i32 @test_vst3()
// CHECK-NEXT:    [[CALL3:%.*]] = call noundef i32 @test_vst4()
// CHECK-NEXT:    ret i32 0
//
int main (int argc, char* argv[]) {
    test_vst1();
    test_vst2();
    test_vst3();
    test_vst4();

    return 0;
}
//.
// CHECK: [[PROF2]] = !{!"branch_weights", i32 1, i32 1048575}
// CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META4:![0-9]+]]}
// CHECK: [[META4]] = !{!"llvm.loop.mustprogress"}
// CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META4]]}
// CHECK: [[LOOP6]] = distinct !{[[LOOP6]], [[META4]]}
// CHECK: [[LOOP7]] = distinct !{[[LOOP7]], [[META4]]}
//.
