// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1    -fsanitize=alloc-token -fsanitize-alloc-token-extended -triple x86_64-linux-gnu -emit-llvm -disable-llvm-passes %s -o - | FileCheck --check-prefix=CHECK-CODEGEN %s
// RUN: %clang_cc1    -fsanitize=alloc-token -fsanitize-alloc-token-extended -triple x86_64-linux-gnu -emit-llvm                      %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O -fsanitize=alloc-token -fsanitize-alloc-token-extended -triple x86_64-linux-gnu -emit-llvm                      %s -o - | FileCheck --check-prefix=CHECK-O1 %s

typedef __typeof(sizeof(int)) size_t;
typedef size_t gfp_t;

void *custom_malloc(size_t size) __attribute__((malloc));
void *__kmalloc(size_t size, gfp_t flags) __attribute__((alloc_size(1)));

void *sink;

// CHECK-LABEL: @test_nonlibcall_alloc(
// CHECK-CODEGEN-LABEL: define dso_local void @test_nonlibcall_alloc(
// CHECK-CODEGEN-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-CODEGEN-NEXT:  [[ENTRY:.*:]]
// CHECK-CODEGEN-NEXT:    [[CALL:%.*]] = call noalias ptr @custom_malloc(i64 noundef 4), !alloc_token [[META2:![0-9]+]]
// CHECK-CODEGEN-NEXT:    store ptr [[CALL]], ptr @sink, align 8
// CHECK-CODEGEN-NEXT:    [[CALL1:%.*]] = call ptr @__kmalloc(i64 noundef 4, i64 noundef 0) #[[ATTR3:[0-9]+]], !alloc_token [[META2]]
// CHECK-CODEGEN-NEXT:    store ptr [[CALL1]], ptr @sink, align 8
// CHECK-CODEGEN-NEXT:    ret void
//
// CHECK-O0-LABEL: define dso_local void @test_nonlibcall_alloc(
// CHECK-O0-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[TMP0:%.*]] = call noalias ptr @__alloc_token_custom_malloc(i64 noundef 4, i64 2689373973731826898), !alloc_token [[META2:![0-9]+]]
// CHECK-O0-NEXT:    store ptr [[TMP0]], ptr @sink, align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = call ptr @__alloc_token___kmalloc(i64 noundef 4, i64 noundef 0, i64 2689373973731826898) #[[ATTR3:[0-9]+]], !alloc_token [[META2]]
// CHECK-O0-NEXT:    store ptr [[TMP1]], ptr @sink, align 8
// CHECK-O0-NEXT:    ret void
//
// CHECK-O1-LABEL: define dso_local void @test_nonlibcall_alloc(
// CHECK-O1-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O1-NEXT:  [[ENTRY:.*:]]
// CHECK-O1-NEXT:    [[TMP0:%.*]] = tail call noalias ptr @__alloc_token_custom_malloc(i64 noundef 4, i64 2689373973731826898) #[[ATTR3:[0-9]+]], !alloc_token [[META2:![0-9]+]]
// CHECK-O1-NEXT:    store ptr [[TMP0]], ptr @sink, align 8, !tbaa [[TBAA3:![0-9]+]]
// CHECK-O1-NEXT:    [[TMP1:%.*]] = tail call dereferenceable_or_null(4) ptr @__alloc_token___kmalloc(i64 noundef 4, i64 noundef 0, i64 2689373973731826898) #[[ATTR4:[0-9]+]], !alloc_token [[META2]]
// CHECK-O1-NEXT:    store ptr [[TMP1]], ptr @sink, align 8, !tbaa [[TBAA3]]
// CHECK-O1-NEXT:    ret void
//
void test_nonlibcall_alloc() {
  sink = custom_malloc(sizeof(int));
  sink = __kmalloc(sizeof(int), 0);
}
//.
// CHECK-CODEGEN: [[META2]] = !{!"int", i1 false}
//.
// CHECK-O0: [[META2]] = !{!"int", i1 false}
//.
// CHECK-O1: [[META2]] = !{!"int", i1 false}
// CHECK-O1: [[TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
// CHECK-O1: [[META4]] = !{!"any pointer", [[META5:![0-9]+]], i64 0}
// CHECK-O1: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// CHECK-O1: [[META6]] = !{!"Simple C/C++ TBAA"}
//.
