// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -std=c23 -triple x86_64-unknown-linux-gnu -emit-llvm %s -o - | FileCheck %s
// RUN: %clang_cc1 -std=c2y -triple x86_64-unknown-linux-gnu -emit-llvm %s -o - | FileCheck %s
//
// Atomic operations on _BitInt(N). load/store/exchange/compare-exchange and
// bitwise RMW lower directly; arithmetic RMW on a padded width and any RMW on a
// width too wide for an inline atomicrmw lower to a compare-exchange loop that
// computes at the value width.

typedef _BitInt(37)          S37;
typedef unsigned _BitInt(37) U37;
typedef _BitInt(64)          S64;
typedef _BitInt(128)         S128;
typedef _BitInt(256)         S256;

// CHECK-LABEL: define dso_local i64 @ld37(
// CHECK-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i37, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load atomic i64, ptr [[TMP0]] seq_cst, align 8
// CHECK-NEXT:    store i64 [[TMP1]], ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i64 [[TMP2]] to i37
// CHECK-NEXT:    store i37 [[LOADEDV]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i37, ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[COERCE_VAL_II:%.*]] = zext i37 [[TMP3]] to i64
// CHECK-NEXT:    ret i64 [[COERCE_VAL_II]]
//
S37 ld37(_Atomic(S37) *p) { return __c11_atomic_load(p, __ATOMIC_SEQ_CST); }

// CHECK-LABEL: define dso_local void @st37(
// CHECK-SAME: ptr noundef [[P:%.*]], i64 noundef [[V_COERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i64 [[V_COERCE]], ptr [[V]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[V]], align 8
// CHECK-NEXT:    [[V1:%.*]] = trunc i64 [[TMP0]] to i37
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = sext i37 [[V1]] to i64
// CHECK-NEXT:    store i64 [[STOREDV]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i64 [[TMP2]] to i37
// CHECK-NEXT:    [[STOREDV2:%.*]] = sext i37 [[LOADEDV]] to i64
// CHECK-NEXT:    store i64 [[STOREDV2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    store atomic i64 [[TMP3]], ptr [[TMP1]] seq_cst, align 8
// CHECK-NEXT:    ret void
//
void st37(_Atomic(S37) *p, S37 v) { __c11_atomic_store(p, v, __ATOMIC_SEQ_CST); }

// CHECK-LABEL: define dso_local i64 @xchg37(
// CHECK-SAME: ptr noundef [[P:%.*]], i64 noundef [[V_COERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i37, align 8
// CHECK-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i64 [[V_COERCE]], ptr [[V]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[V]], align 8
// CHECK-NEXT:    [[V1:%.*]] = trunc i64 [[TMP0]] to i37
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = sext i37 [[V1]] to i64
// CHECK-NEXT:    store i64 [[STOREDV]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i64 [[TMP2]] to i37
// CHECK-NEXT:    [[STOREDV2:%.*]] = sext i37 [[LOADEDV]] to i64
// CHECK-NEXT:    store i64 [[STOREDV2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = atomicrmw xchg ptr [[TMP1]], i64 [[TMP3]] seq_cst, align 8
// CHECK-NEXT:    store i64 [[TMP4]], ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[LOADEDV3:%.*]] = trunc i64 [[TMP5]] to i37
// CHECK-NEXT:    store i37 [[LOADEDV3]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load i37, ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[COERCE_VAL_II:%.*]] = zext i37 [[TMP6]] to i64
// CHECK-NEXT:    ret i64 [[COERCE_VAL_II]]
//
S37 xchg37(_Atomic(S37) *p, S37 v) {
  return __c11_atomic_exchange(p, v, __ATOMIC_SEQ_CST);
}

// CHECK-LABEL: define dso_local zeroext i1 @cas37(
// CHECK-SAME: ptr noundef [[P:%.*]], ptr noundef [[E:%.*]], i64 noundef [[D_COERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[D:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[E_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[CMPXCHG_BOOL:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i64 [[D_COERCE]], ptr [[D]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[D]], align 8
// CHECK-NEXT:    [[D1:%.*]] = trunc i64 [[TMP0]] to i37
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store ptr [[E]], ptr [[E_ADDR]], align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = sext i37 [[D1]] to i64
// CHECK-NEXT:    store i64 [[STOREDV]], ptr [[D_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[E_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[D_ADDR]], align 8
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i64 [[TMP3]] to i37
// CHECK-NEXT:    [[STOREDV2:%.*]] = sext i37 [[LOADEDV]] to i64
// CHECK-NEXT:    store i64 [[STOREDV2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr [[TMP2]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = cmpxchg ptr [[TMP1]], i64 [[TMP4]], i64 [[TMP5]] seq_cst seq_cst, align 8
// CHECK-NEXT:    [[TMP7:%.*]] = extractvalue { i64, i1 } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { i64, i1 } [[TMP6]], 1
// CHECK-NEXT:    br i1 [[TMP8]], label %[[CMPXCHG_CONTINUE:.*]], label %[[CMPXCHG_STORE_EXPECTED:.*]]
// CHECK:       [[CMPXCHG_STORE_EXPECTED]]:
// CHECK-NEXT:    store i64 [[TMP7]], ptr [[TMP2]], align 8
// CHECK-NEXT:    br label %[[CMPXCHG_CONTINUE]]
// CHECK:       [[CMPXCHG_CONTINUE]]:
// CHECK-NEXT:    [[STOREDV3:%.*]] = zext i1 [[TMP8]] to i8
// CHECK-NEXT:    store i8 [[STOREDV3]], ptr [[CMPXCHG_BOOL]], align 1
// CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[CMPXCHG_BOOL]], align 1
// CHECK-NEXT:    [[LOADEDV4:%.*]] = icmp ne i8 [[TMP9]], 0
// CHECK-NEXT:    ret i1 [[LOADEDV4]]
//
_Bool cas37(_Atomic(S37) *p, S37 *e, S37 d) {
  return __c11_atomic_compare_exchange_strong(p, e, d, __ATOMIC_SEQ_CST,
                                              __ATOMIC_SEQ_CST);
}

// Bitwise RMW on a padded width keeps the direct atomicrmw: it is exact.
// CHECK-LABEL: define dso_local i64 @and37(
// CHECK-SAME: ptr noundef [[P:%.*]], i64 noundef [[V_COERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i37, align 8
// CHECK-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i64 [[V_COERCE]], ptr [[V]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[V]], align 8
// CHECK-NEXT:    [[V1:%.*]] = trunc i64 [[TMP0]] to i37
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = sext i37 [[V1]] to i64
// CHECK-NEXT:    store i64 [[STOREDV]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i64 [[TMP2]] to i37
// CHECK-NEXT:    [[STOREDV2:%.*]] = sext i37 [[LOADEDV]] to i64
// CHECK-NEXT:    store i64 [[STOREDV2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = atomicrmw and ptr [[TMP1]], i64 [[TMP3]] seq_cst, align 8
// CHECK-NEXT:    store i64 [[TMP4]], ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[LOADEDV3:%.*]] = trunc i64 [[TMP5]] to i37
// CHECK-NEXT:    store i37 [[LOADEDV3]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load i37, ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[COERCE_VAL_II:%.*]] = zext i37 [[TMP6]] to i64
// CHECK-NEXT:    ret i64 [[COERCE_VAL_II]]
//
S37 and37(_Atomic(S37) *p, S37 v) {
  return __c11_atomic_fetch_and(p, v, __ATOMIC_SEQ_CST);
}

// Arithmetic RMW on a padded width becomes a compare-exchange loop, not a bare
// atomicrmw that would carry into the padding bits.
// CHECK-LABEL: define dso_local i64 @add37(
// CHECK-SAME: ptr noundef [[P:%.*]], i64 noundef [[V_COERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i37, align 8
// CHECK-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i64 [[V_COERCE]], ptr [[V]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[V]], align 8
// CHECK-NEXT:    [[V1:%.*]] = trunc i64 [[TMP0]] to i37
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = sext i37 [[V1]] to i64
// CHECK-NEXT:    store i64 [[STOREDV]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i64 [[TMP2]] to i37
// CHECK-NEXT:    [[STOREDV2:%.*]] = sext i37 [[LOADEDV]] to i64
// CHECK-NEXT:    store i64 [[STOREDV2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[LOADEDV3:%.*]] = trunc i64 [[TMP3]] to i37
// CHECK-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, ptr [[TMP1]] seq_cst, align 8
// CHECK-NEXT:    br label %[[ATOMIC_CONT:.*]]
// CHECK:       [[ATOMIC_CONT]]:
// CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ [[ATOMIC_LOAD]], %[[ENTRY]] ], [ [[TMP7:%.*]], %[[ATOMIC_CONT]] ]
// CHECK-NEXT:    [[LOADEDV4:%.*]] = trunc i64 [[TMP4]] to i37
// CHECK-NEXT:    [[NEW:%.*]] = add i37 [[LOADEDV4]], [[LOADEDV3]]
// CHECK-NEXT:    [[STOREDV5:%.*]] = sext i37 [[NEW]] to i64
// CHECK-NEXT:    store atomic i64 [[STOREDV5]], ptr [[ATOMIC_TEMP]] seq_cst, align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i64, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = cmpxchg ptr [[TMP1]], i64 [[TMP4]], i64 [[TMP5]] seq_cst seq_cst, align 8
// CHECK-NEXT:    [[TMP7]] = extractvalue { i64, i1 } [[TMP6]], 0
// CHECK-NEXT:    [[TMP8:%.*]] = extractvalue { i64, i1 } [[TMP6]], 1
// CHECK-NEXT:    br i1 [[TMP8]], label %[[ATOMIC_EXIT:.*]], label %[[ATOMIC_CONT]]
// CHECK:       [[ATOMIC_EXIT]]:
// CHECK-NEXT:    store i37 [[LOADEDV4]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP9:%.*]] = load i37, ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[COERCE_VAL_II:%.*]] = zext i37 [[TMP9]] to i64
// CHECK-NEXT:    ret i64 [[COERCE_VAL_II]]
//
S37 add37(_Atomic(S37) *p, S37 v) {
  return __c11_atomic_fetch_add(p, v, __ATOMIC_SEQ_CST);
}

// Signed min is computed at the value width, so the sign bit is at bit N-1.
// CHECK-LABEL: define dso_local i64 @min37(
// CHECK-SAME: ptr noundef [[P:%.*]], i64 noundef [[V_COERCE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i37, align 8
// CHECK-NEXT:    [[V:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i64 [[V_COERCE]], ptr [[V]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[V]], align 8
// CHECK-NEXT:    [[V1:%.*]] = trunc i64 [[TMP0]] to i37
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[STOREDV:%.*]] = sext i37 [[V1]] to i64
// CHECK-NEXT:    store i64 [[STOREDV]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[LOADEDV:%.*]] = trunc i64 [[TMP2]] to i37
// CHECK-NEXT:    [[STOREDV2:%.*]] = sext i37 [[LOADEDV]] to i64
// CHECK-NEXT:    store i64 [[STOREDV2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[LOADEDV3:%.*]] = trunc i64 [[TMP3]] to i37
// CHECK-NEXT:    [[ATOMIC_LOAD:%.*]] = load atomic i64, ptr [[TMP1]] seq_cst, align 8
// CHECK-NEXT:    br label %[[ATOMIC_CONT:.*]]
// CHECK:       [[ATOMIC_CONT]]:
// CHECK-NEXT:    [[TMP4:%.*]] = phi i64 [ [[ATOMIC_LOAD]], %[[ENTRY]] ], [ [[TMP8:%.*]], %[[ATOMIC_CONT]] ]
// CHECK-NEXT:    [[LOADEDV4:%.*]] = trunc i64 [[TMP4]] to i37
// CHECK-NEXT:    [[TMP5:%.*]] = icmp sle i37 [[LOADEDV4]], [[LOADEDV3]]
// CHECK-NEXT:    [[NEW:%.*]] = select i1 [[TMP5]], i37 [[LOADEDV4]], i37 [[LOADEDV3]]
// CHECK-NEXT:    [[STOREDV5:%.*]] = sext i37 [[NEW]] to i64
// CHECK-NEXT:    store atomic i64 [[STOREDV5]], ptr [[ATOMIC_TEMP]] seq_cst, align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[TMP7:%.*]] = cmpxchg ptr [[TMP1]], i64 [[TMP4]], i64 [[TMP6]] seq_cst seq_cst, align 8
// CHECK-NEXT:    [[TMP8]] = extractvalue { i64, i1 } [[TMP7]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = extractvalue { i64, i1 } [[TMP7]], 1
// CHECK-NEXT:    br i1 [[TMP9]], label %[[ATOMIC_EXIT:.*]], label %[[ATOMIC_CONT]]
// CHECK:       [[ATOMIC_EXIT]]:
// CHECK-NEXT:    store i37 [[LOADEDV4]], ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[TMP10:%.*]] = load i37, ptr [[RETVAL]], align 8
// CHECK-NEXT:    [[COERCE_VAL_II:%.*]] = zext i37 [[TMP10]] to i64
// CHECK-NEXT:    ret i64 [[COERCE_VAL_II]]
//
U37 min37(_Atomic(S37) *p, S37 v) {
  return __c11_atomic_fetch_min(p, v, __ATOMIC_SEQ_CST);
}

// No padding: direct atomicrmw, no loop.
// CHECK-LABEL: define dso_local i64 @add64(
// CHECK-SAME: ptr noundef [[P:%.*]], i64 noundef [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i64 [[V]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store i64 [[TMP1]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = atomicrmw add ptr [[TMP0]], i64 [[TMP2]] seq_cst, align 8
// CHECK-NEXT:    store i64 [[TMP3]], ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = load i64, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    ret i64 [[TMP4]]
//
S64 add64(_Atomic(S64) *p, S64 v) {
  return __c11_atomic_fetch_add(p, v, __ATOMIC_SEQ_CST);
}

// CHECK-LABEL: define dso_local i128 @add128(
// CHECK-SAME: ptr noundef [[P:%.*]], i128 noundef [[V:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i128, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i128, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i128, align 16
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i128 [[V]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load i128, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store i128 [[TMP1]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i128, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = atomicrmw add ptr [[TMP0]], i128 [[TMP2]] seq_cst, align 16
// CHECK-NEXT:    store i128 [[TMP3]], ptr [[ATOMIC_TEMP]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load i128, ptr [[ATOMIC_TEMP]], align 16
// CHECK-NEXT:    ret i128 [[TMP4]]
//
S128 add128(_Atomic(S128) *p, S128 v) {
  return __c11_atomic_fetch_add(p, v, __ATOMIC_SEQ_CST);
}

// Wide: no inline atomicrmw and no arbitrary-width __atomic_fetch_add libcall,
// so the loop calls __atomic_compare_exchange.
// CHECK-LABEL: define dso_local void @add256(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(i256) align 8 [[AGG_RESULT:%.*]], ptr noundef [[P:%.*]], ptr noundef byval(i256) align 8 [[TMP0:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP1:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP2:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[V:%.*]] = load i256, ptr [[TMP0]], align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i256 [[V]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i256, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store i256 [[TMP2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i256, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    call void @__atomic_load(i64 noundef 32, ptr noundef [[TMP1]], ptr noundef [[ATOMIC_TEMP]], i32 noundef 5)
// CHECK-NEXT:    br label %[[ATOMIC_CONT:.*]]
// CHECK:       [[ATOMIC_CONT]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i256, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[NEW:%.*]] = add i256 [[TMP4]], [[TMP3]]
// CHECK-NEXT:    store i256 [[NEW]], ptr [[ATOMIC_TEMP2]], align 8
// CHECK-NEXT:    call void @__atomic_store(i64 noundef 32, ptr noundef [[ATOMIC_TEMP1]], ptr noundef [[ATOMIC_TEMP2]], i32 noundef 5)
// CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange(i64 noundef 32, ptr noundef [[TMP1]], ptr noundef [[ATOMIC_TEMP]], ptr noundef [[ATOMIC_TEMP1]], i32 noundef 5, i32 noundef 5)
// CHECK-NEXT:    br i1 [[CALL]], label %[[ATOMIC_EXIT:.*]], label %[[ATOMIC_CONT]]
// CHECK:       [[ATOMIC_EXIT]]:
// CHECK-NEXT:    store i256 [[TMP4]], ptr [[AGG_RESULT]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i256, ptr [[AGG_RESULT]], align 8
// CHECK-NEXT:    store i256 [[TMP5]], ptr [[AGG_RESULT]], align 8
// CHECK-NEXT:    ret void
//
S256 add256(_Atomic(S256) *p, S256 v) {
  return __c11_atomic_fetch_add(p, v, __ATOMIC_SEQ_CST);
}

// Wide bitwise also needs the loop: the wide path has no inline atomicrmw.
// CHECK-LABEL: define dso_local void @or256(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(i256) align 8 [[AGG_RESULT:%.*]], ptr noundef [[P:%.*]], ptr noundef byval(i256) align 8 [[TMP0:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[V_ADDR:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[DOTATOMICTMP:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP1:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[ATOMIC_TEMP2:%.*]] = alloca i256, align 8
// CHECK-NEXT:    [[V:%.*]] = load i256, ptr [[TMP0]], align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8
// CHECK-NEXT:    store i256 [[V]], ptr [[V_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[P_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i256, ptr [[V_ADDR]], align 8
// CHECK-NEXT:    store i256 [[TMP2]], ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load i256, ptr [[DOTATOMICTMP]], align 8
// CHECK-NEXT:    call void @__atomic_load(i64 noundef 32, ptr noundef [[TMP1]], ptr noundef [[ATOMIC_TEMP]], i32 noundef 5)
// CHECK-NEXT:    br label %[[ATOMIC_CONT:.*]]
// CHECK:       [[ATOMIC_CONT]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i256, ptr [[ATOMIC_TEMP]], align 8
// CHECK-NEXT:    [[NEW:%.*]] = or i256 [[TMP4]], [[TMP3]]
// CHECK-NEXT:    store i256 [[NEW]], ptr [[ATOMIC_TEMP2]], align 8
// CHECK-NEXT:    call void @__atomic_store(i64 noundef 32, ptr noundef [[ATOMIC_TEMP1]], ptr noundef [[ATOMIC_TEMP2]], i32 noundef 5)
// CHECK-NEXT:    [[CALL:%.*]] = call zeroext i1 @__atomic_compare_exchange(i64 noundef 32, ptr noundef [[TMP1]], ptr noundef [[ATOMIC_TEMP]], ptr noundef [[ATOMIC_TEMP1]], i32 noundef 5, i32 noundef 5)
// CHECK-NEXT:    br i1 [[CALL]], label %[[ATOMIC_EXIT:.*]], label %[[ATOMIC_CONT]]
// CHECK:       [[ATOMIC_EXIT]]:
// CHECK-NEXT:    store i256 [[TMP4]], ptr [[AGG_RESULT]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i256, ptr [[AGG_RESULT]], align 8
// CHECK-NEXT:    store i256 [[TMP5]], ptr [[AGG_RESULT]], align 8
// CHECK-NEXT:    ret void
//
S256 or256(_Atomic(S256) *p, S256 v) {
  return __c11_atomic_fetch_or(p, v, __ATOMIC_SEQ_CST);
}
