// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-attributes --version 6
// RUN: %clang_cc1 -emit-llvm %s -triple x86_64-unknown-linux-gnu -o - | FileCheck %s --check-prefix=C
// RUN: %clang_cc1 -emit-llvm -x c++ %s -triple x86_64-unknown-linux-gnu -o - | FileCheck %s --check-prefix=CXX

// C: Function Attrs: noinline nooutline nounwind optnone
// C-LABEL: define dso_local i32 @t1(
// C-SAME: i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// C-NEXT:  [[ENTRY:.*:]]
// C-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// C-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// C-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// C-NEXT:    ret i32 [[TMP0]]
//
// CXX: Function Attrs: mustprogress noinline nooutline nounwind optnone
// CXX-LABEL: define dso_local noundef i32 @_Z2t1i(
// CXX-SAME: i32 noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CXX-NEXT:  [[ENTRY:.*:]]
// CXX-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CXX-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CXX-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CXX-NEXT:    ret i32 [[TMP0]]
//
[[clang::nooutline]] int t1(int x) {
  return x;
}
