// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -emit-llvm -triple x86_64-windows-pc -ffp-exception-behavior=maytrap -o - %s | FileCheck %s --check-prefixes=CHECK,FP16
// RUN: %clang_cc1 -emit-llvm -triple ppc64-be -ffp-exception-behavior=maytrap -o - %s | FileCheck %s --check-prefixes=CHECK,NOFP16

// test to ensure that these builtins don't do the variadic promotion of float->double.

// Test that the constrained intrinsics are picking up the exception
// metadata from the AST instead of the global default from the command line.

#pragma float_control(except, on)

// FP16-LABEL: define dso_local void @test_half(
// FP16-SAME: ptr noundef [[H:%.*]], ptr noundef [[H2:%.*]]) #[[ATTR0:[0-9]+]] {
// FP16-NEXT:  [[ENTRY:.*:]]
// FP16-NEXT:    [[H2_ADDR:%.*]] = alloca ptr, align 8
// FP16-NEXT:    [[H_ADDR:%.*]] = alloca ptr, align 8
// FP16-NEXT:    store ptr [[H2]], ptr [[H2_ADDR]], align 8
// FP16-NEXT:    store ptr [[H]], ptr [[H_ADDR]], align 8
// FP16-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[H_ADDR]], align 8
// FP16-NEXT:    [[TMP1:%.*]] = load half, ptr [[TMP0]], align 2
// FP16-NEXT:    [[CONV:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP1]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[H2_ADDR]], align 8
// FP16-NEXT:    [[TMP3:%.*]] = load half, ptr [[TMP2]], align 2
// FP16-NEXT:    [[CONV1:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP3]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV]], float [[CONV1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP4:%.*]] = zext i1 [[CMP]] to i32
// FP16-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[H_ADDR]], align 8
// FP16-NEXT:    [[TMP6:%.*]] = load half, ptr [[TMP5]], align 2
// FP16-NEXT:    [[TMP7:%.*]] = call i1 @llvm.is.fpclass.f16(half [[TMP6]], i32 516) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP8:%.*]] = zext i1 [[TMP7]] to i32
// FP16-NEXT:    ret void
//
// NOFP16-LABEL: define dso_local void @test_half(
// NOFP16-SAME: ptr noundef [[H:%.*]], ptr noundef [[H2:%.*]]) #[[ATTR0:[0-9]+]] {
// NOFP16-NEXT:  [[ENTRY:.*:]]
// NOFP16-NEXT:    [[H_ADDR:%.*]] = alloca ptr, align 8
// NOFP16-NEXT:    [[H2_ADDR:%.*]] = alloca ptr, align 8
// NOFP16-NEXT:    store ptr [[H]], ptr [[H_ADDR]], align 8
// NOFP16-NEXT:    store ptr [[H2]], ptr [[H2_ADDR]], align 8
// NOFP16-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[H_ADDR]], align 8
// NOFP16-NEXT:    [[TMP1:%.*]] = load i16, ptr [[TMP0]], align 2
// NOFP16-NEXT:    [[TMP2:%.*]] = bitcast i16 [[TMP1]] to half
// NOFP16-NEXT:    [[CONV:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP2]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[H2_ADDR]], align 8
// NOFP16-NEXT:    [[TMP4:%.*]] = load i16, ptr [[TMP3]], align 2
// NOFP16-NEXT:    [[TMP5:%.*]] = bitcast i16 [[TMP4]] to half
// NOFP16-NEXT:    [[CONV1:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP5]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV]], float [[CONV1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP6:%.*]] = zext i1 [[CMP]] to i32
// NOFP16-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[H_ADDR]], align 8
// NOFP16-NEXT:    [[TMP8:%.*]] = load i16, ptr [[TMP7]], align 2
// NOFP16-NEXT:    [[TMP9:%.*]] = bitcast i16 [[TMP8]] to half
// NOFP16-NEXT:    [[CONV2:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP9]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP10:%.*]] = call i1 @llvm.is.fpclass.f32(float [[CONV2]], i32 516) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP11:%.*]] = zext i1 [[TMP10]] to i32
// NOFP16-NEXT:    ret void
//
void test_half(__fp16 *H, __fp16 *H2) {
  (void)__builtin_isgreater(*H, *H2);
  (void)__builtin_isinf(*H);
}

// FP16-LABEL: define dso_local void @test_mixed(
// FP16-SAME: double noundef [[D1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FP16-NEXT:  [[ENTRY:.*:]]
// FP16-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FP16-NEXT:    [[D1_ADDR:%.*]] = alloca double, align 8
// FP16-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FP16-NEXT:    store double [[D1]], ptr [[D1_ADDR]], align 8
// FP16-NEXT:    [[TMP0:%.*]] = load double, ptr [[D1_ADDR]], align 8
// FP16-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FP16-NEXT:    [[CONV:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP1]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[CONV]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP2:%.*]] = zext i1 [[CMP]] to i32
// FP16-NEXT:    [[TMP3:%.*]] = load double, ptr [[D1_ADDR]], align 8
// FP16-NEXT:    [[TMP4:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FP16-NEXT:    [[CONV1:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP4]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[CMP2:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP3]], double [[CONV1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP5:%.*]] = zext i1 [[CMP2]] to i32
// FP16-NEXT:    [[TMP6:%.*]] = load double, ptr [[D1_ADDR]], align 8
// FP16-NEXT:    [[TMP7:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FP16-NEXT:    [[CONV3:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP7]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[CMP4:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP6]], double [[CONV3]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP8:%.*]] = zext i1 [[CMP4]] to i32
// FP16-NEXT:    [[TMP9:%.*]] = load double, ptr [[D1_ADDR]], align 8
// FP16-NEXT:    [[TMP10:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FP16-NEXT:    [[CONV5:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP10]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[CMP6:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP9]], double [[CONV5]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP11:%.*]] = zext i1 [[CMP6]] to i32
// FP16-NEXT:    [[TMP12:%.*]] = load double, ptr [[D1_ADDR]], align 8
// FP16-NEXT:    [[TMP13:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FP16-NEXT:    [[CONV7:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP13]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[CMP8:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP12]], double [[CONV7]], metadata !"one") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP14:%.*]] = zext i1 [[CMP8]] to i32
// FP16-NEXT:    [[TMP15:%.*]] = load double, ptr [[D1_ADDR]], align 8
// FP16-NEXT:    [[TMP16:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FP16-NEXT:    [[CONV9:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP16]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[CMP10:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP15]], double [[CONV9]], metadata !"uno") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// FP16-NEXT:    [[TMP17:%.*]] = zext i1 [[CMP10]] to i32
// FP16-NEXT:    ret void
//
// NOFP16-LABEL: define dso_local void @test_mixed(
// NOFP16-SAME: double noundef [[D1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// NOFP16-NEXT:  [[ENTRY:.*:]]
// NOFP16-NEXT:    [[D1_ADDR:%.*]] = alloca double, align 8
// NOFP16-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// NOFP16-NEXT:    store double [[D1]], ptr [[D1_ADDR]], align 8
// NOFP16-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// NOFP16-NEXT:    [[TMP0:%.*]] = load double, ptr [[D1_ADDR]], align 8
// NOFP16-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// NOFP16-NEXT:    [[CONV:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP1]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[CONV]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP2:%.*]] = zext i1 [[CMP]] to i32
// NOFP16-NEXT:    [[TMP3:%.*]] = load double, ptr [[D1_ADDR]], align 8
// NOFP16-NEXT:    [[TMP4:%.*]] = load float, ptr [[F2_ADDR]], align 4
// NOFP16-NEXT:    [[CONV1:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP4]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[CMP2:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP3]], double [[CONV1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP5:%.*]] = zext i1 [[CMP2]] to i32
// NOFP16-NEXT:    [[TMP6:%.*]] = load double, ptr [[D1_ADDR]], align 8
// NOFP16-NEXT:    [[TMP7:%.*]] = load float, ptr [[F2_ADDR]], align 4
// NOFP16-NEXT:    [[CONV3:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP7]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[CMP4:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP6]], double [[CONV3]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP8:%.*]] = zext i1 [[CMP4]] to i32
// NOFP16-NEXT:    [[TMP9:%.*]] = load double, ptr [[D1_ADDR]], align 8
// NOFP16-NEXT:    [[TMP10:%.*]] = load float, ptr [[F2_ADDR]], align 4
// NOFP16-NEXT:    [[CONV5:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP10]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[CMP6:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP9]], double [[CONV5]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP11:%.*]] = zext i1 [[CMP6]] to i32
// NOFP16-NEXT:    [[TMP12:%.*]] = load double, ptr [[D1_ADDR]], align 8
// NOFP16-NEXT:    [[TMP13:%.*]] = load float, ptr [[F2_ADDR]], align 4
// NOFP16-NEXT:    [[CONV7:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP13]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[CMP8:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP12]], double [[CONV7]], metadata !"one") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP14:%.*]] = zext i1 [[CMP8]] to i32
// NOFP16-NEXT:    [[TMP15:%.*]] = load double, ptr [[D1_ADDR]], align 8
// NOFP16-NEXT:    [[TMP16:%.*]] = load float, ptr [[F2_ADDR]], align 4
// NOFP16-NEXT:    [[CONV9:%.*]] = call double @llvm.fpext.f64.f32(float [[TMP16]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[CMP10:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP15]], double [[CONV9]], metadata !"uno") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOFP16-NEXT:    [[TMP17:%.*]] = zext i1 [[CMP10]] to i32
// NOFP16-NEXT:    ret void
//
void test_mixed(double d1, float f2) {
  (void)__builtin_isgreater(d1, f2);
  (void)__builtin_isgreaterequal(d1, f2);
  (void)__builtin_isless(d1, f2);
  (void)__builtin_islessequal(d1, f2);
  (void)__builtin_islessgreater(d1, f2);
  (void)__builtin_isunordered(d1, f2);
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
