// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -emit-llvm -o - %s | FileCheck %s

// Test integer types
// CHECK-LABEL: define i32 @test_int(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_int(int cond, int a, int b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define i64 @test_long(
// CHECK-SAME: i32 noundef [[COND:%.*]], i64 noundef [[A:%.*]], i64 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// CHECK-NEXT:    store i64 [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.ct.select.i64(i1 [[TOBOOL]], i64 [[TMP1]], i64 [[TMP2]])
// CHECK-NEXT:    ret i64 [[TMP3]]
//
long long test_long(int cond, long long a, long long b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define i16 @test_short(
// CHECK-SAME: i32 noundef [[COND:%.*]], i16 noundef [[A:%.*]], i16 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i16 [[A]], ptr [[A_ADDR]], align 2
// CHECK-NEXT:    store i16 [[B]], ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[A_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call i16 @llvm.ct.select.i16(i1 [[TOBOOL]], i16 [[TMP1]], i16 [[TMP2]])
// CHECK-NEXT:    ret i16 [[TMP3]]
//
short test_short(int cond, short a, short b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define i8 @test_uchar(
// CHECK-SAME: i32 noundef [[COND:%.*]], i8 noundef [[A:%.*]], i8 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i8 [[A]], ptr [[A_ADDR]], align 1
// CHECK-NEXT:    store i8 [[B]], ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[A_ADDR]], align 1
// CHECK-NEXT:    [[TMP2:%.*]] = load i8, ptr [[B_ADDR]], align 1
// CHECK-NEXT:    [[TMP3:%.*]] = call i8 @llvm.ct.select.i8(i1 [[TOBOOL]], i8 [[TMP1]], i8 [[TMP2]])
// CHECK-NEXT:    ret i8 [[TMP3]]
//
unsigned char test_uchar(int cond, unsigned char a, unsigned char b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define i64 @test_longlong(
// CHECK-SAME: i32 noundef [[COND:%.*]], i64 noundef [[A:%.*]], i64 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i64 [[A]], ptr [[A_ADDR]], align 8
// CHECK-NEXT:    store i64 [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.ct.select.i64(i1 [[TOBOOL]], i64 [[TMP1]], i64 [[TMP2]])
// CHECK-NEXT:    ret i64 [[TMP3]]
//
long long test_longlong(int cond, long long a, long long b) {
  return __builtin_ct_select(cond, a, b);
}

// Test floating point types
// CHECK-LABEL: define float @test_float(
// CHECK-SAME: i32 noundef [[COND:%.*]], float noundef [[A:%.*]], float noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store float [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store float [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call float @llvm.ct.select.f32(i1 [[TOBOOL]], float [[TMP1]], float [[TMP2]])
// CHECK-NEXT:    ret float [[TMP3]]
//
float test_float(int cond, float a, float b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define double @test_double(
// CHECK-SAME: i32 noundef [[COND:%.*]], double noundef [[A:%.*]], double noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca double, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca double, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store double [[A]], ptr [[A_ADDR]], align 8
// CHECK-NEXT:    store double [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call double @llvm.ct.select.f64(i1 [[TOBOOL]], double [[TMP1]], double [[TMP2]])
// CHECK-NEXT:    ret double [[TMP3]]
//
double test_double(int cond, double a, double b) {
  return __builtin_ct_select(cond, a, b);
}

// Test pointer types
// CHECK-LABEL: define ptr @test_pointer(
// CHECK-SAME: i32 noundef [[COND:%.*]], ptr noundef [[A:%.*]], ptr noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call ptr @llvm.ct.select.p0(i1 [[TOBOOL]], ptr [[TMP1]], ptr [[TMP2]])
// CHECK-NEXT:    ret ptr [[TMP3]]
//
int *test_pointer(int cond, int *a, int *b) {
  return __builtin_ct_select(cond, a, b);
}

// Test with different condition types
// CHECK-LABEL: define i32 @test_char_cond(
// CHECK-SAME: i8 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i8 [[COND]], ptr [[COND_ADDR]], align 1
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[COND_ADDR]], align 1
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i8 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_char_cond(char cond, int a, int b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define i32 @test_long_cond(
// CHECK-SAME: i64 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i64 [[COND]], ptr [[COND_ADDR]], align 8
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[COND_ADDR]], align 8
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i64 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_long_cond(long long cond, int a, int b) {
  return __builtin_ct_select(cond, a, b);
}

// Test with boolean condition
// CHECK-LABEL: define i32 @test_bool_cond(
// CHECK-SAME: i1 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[STOREDV:%.*]] = zext i1 [[COND]] to i8
// CHECK-NEXT:    store i8 [[STOREDV]], ptr [[COND_ADDR]], align 1
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[COND_ADDR]], align 1
// CHECK-NEXT:    [[LOADEDV:%.*]] = icmp ne i8 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[LOADEDV]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_bool_cond(_Bool cond, int a, int b) {
  return __builtin_ct_select(cond, a, b);
}

// Test with constants
// CHECK-LABEL: define i32 @test_constant_cond(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.ct.select.i32(i1 true, i32 42, i32 24)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int test_constant_cond(void) {
  return __builtin_ct_select(1, 42, 24);
}

// CHECK-LABEL: define i32 @test_zero_cond(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.ct.select.i32(i1 false, i32 42, i32 24)
// CHECK-NEXT:    ret i32 [[TMP0]]
//
int test_zero_cond(void) {
  return __builtin_ct_select(0, 42, 24);
}

// Test type promotion
// CHECK-LABEL: define i32 @test_promotion(
// CHECK-SAME: i32 noundef [[COND:%.*]], i16 noundef [[A:%.*]], i16 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i16, align 2
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i16 [[A]], ptr [[A_ADDR]], align 2
// CHECK-NEXT:    store i16 [[B]], ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i16, ptr [[A_ADDR]], align 2
// CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP1]] to i32
// CHECK-NEXT:    [[TMP2:%.*]] = load i16, ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[CONV1:%.*]] = sext i16 [[TMP2]] to i32
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[CONV]], i32 [[CONV1]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_promotion(int cond, short a, short b) {
  return __builtin_ct_select(cond, (int)a, (int)b);
}

// Test mixed signedness
// CHECK-LABEL: define i32 @test_mixed_signedness(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[CONV:%.*]] = sext i32 [[TMP1]] to i64
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[CONV1:%.*]] = zext i32 [[TMP2]] to i64
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.ct.select.i64(i1 [[TOBOOL]], i64 [[CONV]], i64 [[CONV1]])
// CHECK-NEXT:    [[CONV2:%.*]] = trunc i64 [[TMP3]] to i32
// CHECK-NEXT:    ret i32 [[CONV2]]
//
unsigned int test_mixed_signedness(int cond, int a, unsigned int b) {
  return __builtin_ct_select(cond, (long long)a, (long long)b);
}

// Test complex expression
// CHECK-LABEL: define i32 @test_complex_expr_alt(
// CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[Y:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    store i32 [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP1]], [[TMP2]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    [[TMP5:%.*]] = call i32 @llvm.ct.select.i32(i1 [[CMP]], i32 [[ADD]], i32 [[SUB]])
// CHECK-NEXT:    ret i32 [[TMP5]]
//
int test_complex_expr_alt(int x, int y) {
  // Separate the final sequence to ensure proper ordering
  return __builtin_ct_select(x > 0, x + y, x - y);
}

// Test nested calls
// CHECK-LABEL: define i32 @test_nested_structured(
// CHECK-SAME: i32 noundef [[COND1:%.*]], i32 noundef [[COND2:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND1_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND2_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND1]], ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND2]], ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    store i32 [[C]], ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL1]], i32 [[TMP2]], i32 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP4]], i32 [[TMP5]])
// CHECK-NEXT:    ret i32 [[TMP6]]
//
int test_nested_structured(int cond1, int cond2, int a, int b, int c) {
  // Phase 1: Conditions (order doesn't matter)

  // Phase 2: Inner select (must happen before outer)

  // Phase 3: Outer select (must use inner result)
  return __builtin_ct_select(cond1, __builtin_ct_select(cond2, a, b), c);
}

// Test with function calls
// CHECK-LABEL: define i32 @helper(
// CHECK-SAME: i32 noundef [[X:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[MUL:%.*]] = mul nsw i32 [[TMP0]], 2
// CHECK-NEXT:    ret i32 [[MUL]]
//
int helper(int x) { return x * 2; }
// CHECK-LABEL: define i32 @test_function_calls(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[X:%.*]], i32 noundef [[Y:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    store i32 [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call i32 @helper(i32 noundef [[TMP1]])
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[CALL1:%.*]] = call i32 @helper(i32 noundef [[TMP2]])
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[CALL]], i32 [[CALL1]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_function_calls(int cond, int x, int y) {
  return __builtin_ct_select(cond, helper(x), helper(y));
}

// Test using ct_select as condition for another ct_select
// CHECK-LABEL: define i32 @test_intrinsic_condition(
// CHECK-SAME: i32 noundef [[COND1:%.*]], i32 noundef [[COND2:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]], i32 noundef [[D:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND1_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND2_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND1]], ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND2]], ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    store i32 [[C]], ptr [[C_ADDR]], align 4
// CHECK-NEXT:    store i32 [[D]], ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP3]], 0
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL1]], i32 [[TMP4]], i32 [[TMP5]])
// CHECK-NEXT:    ret i32 [[TMP6]]
//
int test_intrinsic_condition(int cond1, int cond2, int a, int b, int c, int d) {
  return __builtin_ct_select(__builtin_ct_select(cond1, cond2, a), b, c);
}

// Test using comparison result of ct_select as condition
// CHECK-LABEL: define i32 @test_comparison_condition(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]], i32 noundef [[D:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    store i32 [[C]], ptr [[C_ADDR]], align 4
// CHECK-NEXT:    store i32 [[D]], ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ct.select.i32(i1 [[CMP]], i32 [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    ret i32 [[TMP7]]
//
int test_comparison_condition(int cond, int a, int b, int c, int d) {
  return __builtin_ct_select(__builtin_ct_select(cond, a, b) > c, d, a);
}

// Test using ct_select result in arithmetic as condition
// CHECK-LABEL: define i32 @test_arithmetic_condition(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]], i32 noundef [[D:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    store i32 [[C]], ptr [[C_ADDR]], align 4
// CHECK-NEXT:    store i32 [[D]], ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[ADD]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL1]], i32 [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    ret i32 [[TMP7]]
//
int test_arithmetic_condition(int cond, int a, int b, int c, int d) {
  return __builtin_ct_select(__builtin_ct_select(cond, a, b) + c, d, a);
}

// Test chained ct_select as conditions
// CHECK-LABEL: define i32 @test_chained_conditions(
// CHECK-SAME: i32 noundef [[COND1:%.*]], i32 noundef [[COND2:%.*]], i32 noundef [[COND3:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]], i32 noundef [[D:%.*]], i32 noundef [[E:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND1_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND2_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND3_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[E_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[FIRST_SELECT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[SECOND_SELECT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND1]], ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND2]], ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND3]], ptr [[COND3_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    store i32 [[C]], ptr [[C_ADDR]], align 4
// CHECK-NEXT:    store i32 [[D]], ptr [[D_ADDR]], align 4
// CHECK-NEXT:    store i32 [[E]], ptr [[E_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    store i32 [[TMP3]], ptr [[FIRST_SELECT]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP4]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[FIRST_SELECT]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL1]], i32 [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    store i32 [[TMP7]], ptr [[SECOND_SELECT]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[SECOND_SELECT]], align 4
// CHECK-NEXT:    [[TOBOOL2:%.*]] = icmp ne i32 [[TMP8]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[E_ADDR]], align 4
// CHECK-NEXT:    [[TMP11:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL2]], i32 [[TMP9]], i32 [[TMP10]])
// CHECK-NEXT:    ret i32 [[TMP11]]
//
int test_chained_conditions(int cond1, int cond2, int cond3, int a, int b, int c, int d, int e) {
  int first_select = __builtin_ct_select(cond1, a, b);
  int second_select = __builtin_ct_select(cond2, first_select, c);
  return __builtin_ct_select(second_select, d, e);
}

// Test using ct_select with pointer condition
//int test_pointer_condition(int *ptr1, int *ptr2, int a, int b, int c) {
  // NO-CHECK-LABEL: define {{.*}} @test_pointer_condition
  // NO-CHECK: [[PTR_COND:%.*]] = icmp ne ptr %{{.*}}, null
  // NO-CHECK: [[PTR_SELECT:%.*]] = call ptr @llvm.ct.select.p0(i1 [[PTR_COND]], ptr %{{.*}}, ptr %{{.*}})
  // NO-CHECK: [[FINAL_COND:%.*]] = icmp ne ptr [[PTR_SELECT]], null
  // NO-CHECK: [[RESULT:%.*]] = call i32 @llvm.ct.select.i32(i1 [[FINAL_COND]], i32 %{{.*}}, i32 %{{.*}})
  // NO-CHECK: ret i32 [[RESULT]]
//  return __builtin_ct_select(__builtin_ct_select(ptr1, ptr1, ptr2), a, b);
//}


// Test using ct_select result in logical operations as condition
// CHECK-LABEL: define i32 @test_logical_condition(
// CHECK-SAME: i32 noundef [[COND1:%.*]], i32 noundef [[COND2:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]], i32 noundef [[D:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[COND1_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND2_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND1]], ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND2]], ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    store i32 [[C]], ptr [[C_ADDR]], align 4
// CHECK-NEXT:    store i32 [[D]], ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP3]], 0
// CHECK-NEXT:    br i1 [[TOBOOL1]], label %[[LAND_RHS:.*]], label %[[LAND_END:.*]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL2:%.*]] = icmp ne i32 [[TMP4]], 0
// CHECK-NEXT:    br label %[[LAND_END]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP5:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ [[TOBOOL2]], %[[LAND_RHS]] ]
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TMP5]], i32 [[TMP6]], i32 [[TMP7]])
// CHECK-NEXT:    ret i32 [[TMP8]]
//
int test_logical_condition(int cond1, int cond2, int a, int b, int c, int d) {
  return __builtin_ct_select(__builtin_ct_select(cond1, a, b) && cond2, c, d);
}

// Test multiple levels of ct_select as conditions
// CHECK-LABEL: define i32 @test_deep_condition_nesting(
// CHECK-SAME: i32 noundef [[COND1:%.*]], i32 noundef [[COND2:%.*]], i32 noundef [[COND3:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]], i32 noundef [[C:%.*]], i32 noundef [[D:%.*]], i32 noundef [[E:%.*]], i32 noundef [[F:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND1_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND2_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND3_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[E_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[F_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND1]], ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND2]], ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND3]], ptr [[COND3_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    store i32 [[C]], ptr [[C_ADDR]], align 4
// CHECK-NEXT:    store i32 [[D]], ptr [[D_ADDR]], align 4
// CHECK-NEXT:    store i32 [[E]], ptr [[E_ADDR]], align 4
// CHECK-NEXT:    store i32 [[F]], ptr [[F_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL1]], i32 [[TMP2]], i32 [[TMP3]])
// CHECK-NEXT:    [[TOBOOL2:%.*]] = icmp ne i32 [[TMP4]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[C_ADDR]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[D_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL2]], i32 [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[E_ADDR]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP7]], i32 [[TMP8]])
// CHECK-NEXT:    [[TOBOOL3:%.*]] = icmp ne i32 [[TMP9]], 0
// CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[F_ADDR]], align 4
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP12:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL3]], i32 [[TMP10]], i32 [[TMP11]])
// CHECK-NEXT:    ret i32 [[TMP12]]
//
int test_deep_condition_nesting(int cond1, int cond2, int cond3, int a, int b, int c, int d, int e, int f) {
  return __builtin_ct_select(__builtin_ct_select(cond1, __builtin_ct_select(__builtin_ct_select(cond2, a, b), c, d), e), f, a);
}

// Test ct_select with complex condition expressions
// CHECK-LABEL: define i32 @test_complex_condition_expr(
// CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[Y:%.*]], i32 noundef [[Z:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[Z_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    store i32 [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    store i32 [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.ct.select.i32(i1 [[CMP]], i32 [[TMP2]], i32 [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[Z_ADDR]], align 4
// CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[TMP4]], [[TMP5]]
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = call i32 @llvm.ct.select.i32(i1 [[CMP1]], i32 [[TMP6]], i32 [[TMP7]])
// CHECK-NEXT:    ret i32 [[TMP8]]
//
int test_complex_condition_expr(int x, int y, int z, int a, int b) {
  return __builtin_ct_select(__builtin_ct_select(x > y, x, y) < z, a, b);
}

// Test vector types - 128-bit vectors
typedef int __attribute__((vector_size(16))) int4;
typedef float __attribute__((vector_size(16))) float4;
typedef short __attribute__((vector_size(16))) short8;
typedef char __attribute__((vector_size(16))) char16;

// CHECK-LABEL: define <4 x i32> @test_vector_int4(
// CHECK-SAME: i32 noundef [[COND:%.*]], <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <4 x i32> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <4 x i32> @llvm.ct.select.v4i32(i1 [[TOBOOL]], <4 x i32> [[TMP1]], <4 x i32> [[TMP2]])
// CHECK-NEXT:    ret <4 x i32> [[TMP3]]
//
int4 test_vector_int4(int cond, int4 a, int4 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <4 x float> @test_vector_float4(
// CHECK-SAME: i32 noundef [[COND:%.*]], <4 x float> noundef [[A:%.*]], <4 x float> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <4 x float> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x float> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL]], <4 x float> [[TMP1]], <4 x float> [[TMP2]])
// CHECK-NEXT:    ret <4 x float> [[TMP3]]
//
float4 test_vector_float4(int cond, float4 a, float4 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <8 x i16> @test_vector_short8(
// CHECK-SAME: i32 noundef [[COND:%.*]], <8 x i16> noundef [[A:%.*]], <8 x i16> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <8 x i16>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <8 x i16> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <8 x i16> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x i16>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <8 x i16>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <8 x i16> @llvm.ct.select.v8i16(i1 [[TOBOOL]], <8 x i16> [[TMP1]], <8 x i16> [[TMP2]])
// CHECK-NEXT:    ret <8 x i16> [[TMP3]]
//
short8 test_vector_short8(int cond, short8 a, short8 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <16 x i8> @test_vector_char16(
// CHECK-SAME: i32 noundef [[COND:%.*]], <16 x i8> noundef [[A:%.*]], <16 x i8> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <16 x i8> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <16 x i8> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <16 x i8> @llvm.ct.select.v16i8(i1 [[TOBOOL]], <16 x i8> [[TMP1]], <16 x i8> [[TMP2]])
// CHECK-NEXT:    ret <16 x i8> [[TMP3]]
//
char16 test_vector_char16(int cond, char16 a, char16 b) {
  return __builtin_ct_select(cond, a, b);
}

// Test 256-bit vectors
typedef int __attribute__((vector_size(32))) int8;
typedef float __attribute__((vector_size(32))) float8;
typedef double __attribute__((vector_size(32))) double4;

// CHECK-LABEL: define void @test_vector_int8(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(<8 x i32>) align 16 [[AGG_RESULT:%.*]], i32 noundef [[COND:%.*]], ptr noundef dead_on_return [[TMP0:%.*]], ptr noundef dead_on_return [[TMP1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <8 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <8 x i32>, align 16
// CHECK-NEXT:    [[A:%.*]] = load <8 x i32>, ptr [[TMP0]], align 16
// CHECK-NEXT:    [[B:%.*]] = load <8 x i32>, ptr [[TMP1]], align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <8 x i32> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <8 x i32> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP2]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load <8 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP5:%.*]] = call <8 x i32> @llvm.ct.select.v8i32(i1 [[TOBOOL]], <8 x i32> [[TMP3]], <8 x i32> [[TMP4]])
// CHECK-NEXT:    store <8 x i32> [[TMP5]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <8 x i32>, ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    store <8 x i32> [[TMP6]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    ret void
//
int8 test_vector_int8(int cond, int8 a, int8 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define void @test_vector_float8(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(<8 x float>) align 16 [[AGG_RESULT:%.*]], i32 noundef [[COND:%.*]], ptr noundef dead_on_return [[TMP0:%.*]], ptr noundef dead_on_return [[TMP1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <8 x float>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <8 x float>, align 16
// CHECK-NEXT:    [[A:%.*]] = load <8 x float>, ptr [[TMP0]], align 16
// CHECK-NEXT:    [[B:%.*]] = load <8 x float>, ptr [[TMP1]], align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <8 x float> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <8 x float> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP2]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = load <8 x float>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load <8 x float>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP5:%.*]] = call <8 x float> @llvm.ct.select.v8f32(i1 [[TOBOOL]], <8 x float> [[TMP3]], <8 x float> [[TMP4]])
// CHECK-NEXT:    store <8 x float> [[TMP5]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <8 x float>, ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    store <8 x float> [[TMP6]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    ret void
//
float8 test_vector_float8(int cond, float8 a, float8 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define void @test_vector_double4(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(<4 x double>) align 16 [[AGG_RESULT:%.*]], i32 noundef [[COND:%.*]], ptr noundef dead_on_return [[TMP0:%.*]], ptr noundef dead_on_return [[TMP1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x double>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x double>, align 16
// CHECK-NEXT:    [[A:%.*]] = load <4 x double>, ptr [[TMP0]], align 16
// CHECK-NEXT:    [[B:%.*]] = load <4 x double>, ptr [[TMP1]], align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <4 x double> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x double> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP2]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x double>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load <4 x double>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP5:%.*]] = call <4 x double> @llvm.ct.select.v4f64(i1 [[TOBOOL]], <4 x double> [[TMP3]], <4 x double> [[TMP4]])
// CHECK-NEXT:    store <4 x double> [[TMP5]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <4 x double>, ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    store <4 x double> [[TMP6]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    ret void
//
double4 test_vector_double4(int cond, double4 a, double4 b) {
  return __builtin_ct_select(cond, a, b);
}

// Test 512-bit vectors
typedef int __attribute__((vector_size(64))) int16;
typedef float __attribute__((vector_size(64))) float16;

// CHECK-LABEL: define void @test_vector_int16(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(<16 x i32>) align 16 [[AGG_RESULT:%.*]], i32 noundef [[COND:%.*]], ptr noundef dead_on_return [[TMP0:%.*]], ptr noundef dead_on_return [[TMP1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x i32>, align 16
// CHECK-NEXT:    [[A:%.*]] = load <16 x i32>, ptr [[TMP0]], align 16
// CHECK-NEXT:    [[B:%.*]] = load <16 x i32>, ptr [[TMP1]], align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <16 x i32> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <16 x i32> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP2]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load <16 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP5:%.*]] = call <16 x i32> @llvm.ct.select.v16i32(i1 [[TOBOOL]], <16 x i32> [[TMP3]], <16 x i32> [[TMP4]])
// CHECK-NEXT:    store <16 x i32> [[TMP5]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <16 x i32>, ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    store <16 x i32> [[TMP6]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    ret void
//
int16 test_vector_int16(int cond, int16 a, int16 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define void @test_vector_float16(
// CHECK-SAME: ptr dead_on_unwind noalias writable sret(<16 x float>) align 16 [[AGG_RESULT:%.*]], i32 noundef [[COND:%.*]], ptr noundef dead_on_return [[TMP0:%.*]], ptr noundef dead_on_return [[TMP1:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x float>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x float>, align 16
// CHECK-NEXT:    [[A:%.*]] = load <16 x float>, ptr [[TMP0]], align 16
// CHECK-NEXT:    [[B:%.*]] = load <16 x float>, ptr [[TMP1]], align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <16 x float> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <16 x float> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP2]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = load <16 x float>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load <16 x float>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP5:%.*]] = call <16 x float> @llvm.ct.select.v16f32(i1 [[TOBOOL]], <16 x float> [[TMP3]], <16 x float> [[TMP4]])
// CHECK-NEXT:    store <16 x float> [[TMP5]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <16 x float>, ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    store <16 x float> [[TMP6]], ptr [[AGG_RESULT]], align 16
// CHECK-NEXT:    ret void
//
float16 test_vector_float16(int cond, float16 a, float16 b) {
  return __builtin_ct_select(cond, a, b);
}

// Test vector operations with different condition types
// CHECK-LABEL: define <4 x i32> @test_vector_char_cond(
// CHECK-SAME: i8 noundef [[COND:%.*]], <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store i8 [[COND]], ptr [[COND_ADDR]], align 1
// CHECK-NEXT:    store <4 x i32> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[COND_ADDR]], align 1
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i8 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <4 x i32> @llvm.ct.select.v4i32(i1 [[TOBOOL]], <4 x i32> [[TMP1]], <4 x i32> [[TMP2]])
// CHECK-NEXT:    ret <4 x i32> [[TMP3]]
//
int4 test_vector_char_cond(char cond, int4 a, int4 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <4 x float> @test_vector_long_cond(
// CHECK-SAME: i64 noundef [[COND:%.*]], <4 x float> noundef [[A:%.*]], <4 x float> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store i64 [[COND]], ptr [[COND_ADDR]], align 8
// CHECK-NEXT:    store <4 x float> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x float> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[COND_ADDR]], align 8
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i64 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL]], <4 x float> [[TMP1]], <4 x float> [[TMP2]])
// CHECK-NEXT:    ret <4 x float> [[TMP3]]
//
float4 test_vector_long_cond(long long cond, float4 a, float4 b) {
  return __builtin_ct_select(cond, a, b);
}

// Test vector constants
// CHECK-LABEL: define <4 x i32> @test_vector_constant_cond(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store <4 x i32> <i32 1, i32 2, i32 3, i32 4>, ptr [[A]], align 16
// CHECK-NEXT:    store <4 x i32> <i32 5, i32 6, i32 7, i32 8>, ptr [[B]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[A]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[B]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x i32> @llvm.ct.select.v4i32(i1 true, <4 x i32> [[TMP0]], <4 x i32> [[TMP1]])
// CHECK-NEXT:    ret <4 x i32> [[TMP2]]
//
int4 test_vector_constant_cond(void) {
  int4 a = {1, 2, 3, 4};
  int4 b = {5, 6, 7, 8};
  return __builtin_ct_select(1, a, b);
}

// CHECK-LABEL: define <4 x float> @test_vector_zero_cond(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[B:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store <4 x float> <float 1.000000e+00, float 2.000000e+00, float 3.000000e+00, float 4.000000e+00>, ptr [[A]], align 16
// CHECK-NEXT:    store <4 x float> <float 5.000000e+00, float 6.000000e+00, float 7.000000e+00, float 8.000000e+00>, ptr [[B]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr [[A]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[B]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 false, <4 x float> [[TMP0]], <4 x float> [[TMP1]])
// CHECK-NEXT:    ret <4 x float> [[TMP2]]
//
float4 test_vector_zero_cond(void) {
  float4 a = {1.0f, 2.0f, 3.0f, 4.0f};
  float4 b = {5.0f, 6.0f, 7.0f, 8.0f};
  return __builtin_ct_select(0, a, b);
}

// Test nested vector selections
// CHECK-LABEL: define <4 x i32> @test_vector_nested(
// CHECK-SAME: i32 noundef [[COND1:%.*]], i32 noundef [[COND2:%.*]], <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]], <4 x i32> noundef [[C:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND1_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND2_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store i32 [[COND1]], ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND2]], ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    store <4 x i32> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[C]], ptr [[C_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <4 x i32> @llvm.ct.select.v4i32(i1 [[TOBOOL1]], <4 x i32> [[TMP2]], <4 x i32> [[TMP3]])
// CHECK-NEXT:    [[TMP5:%.*]] = load <4 x i32>, ptr [[C_ADDR]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = call <4 x i32> @llvm.ct.select.v4i32(i1 [[TOBOOL]], <4 x i32> [[TMP4]], <4 x i32> [[TMP5]])
// CHECK-NEXT:    ret <4 x i32> [[TMP6]]
//
int4 test_vector_nested(int cond1, int cond2, int4 a, int4 b, int4 c) {
  return __builtin_ct_select(cond1, __builtin_ct_select(cond2, a, b), c);
}

// Test vector selection with complex expressions
// CHECK-LABEL: define <4 x float> @test_vector_complex_expr(
// CHECK-SAME: i32 noundef [[X:%.*]], i32 noundef [[Y:%.*]], <4 x float> noundef [[A:%.*]], <4 x float> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store i32 [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    store i32 [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    store <4 x float> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x float> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp sgt i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x float>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[CMP]], <4 x float> [[TMP2]], <4 x float> [[TMP3]])
// CHECK-NEXT:    ret <4 x float> [[TMP4]]
//
float4 test_vector_complex_expr(int x, int y, float4 a, float4 b) {
  return __builtin_ct_select(x > y, a, b);
}

// Test vector with different element sizes
typedef long long __attribute__((vector_size(16))) long2;
typedef double __attribute__((vector_size(16))) double2;

// CHECK-LABEL: define <2 x i64> @test_vector_long2(
// CHECK-SAME: i32 noundef [[COND:%.*]], <2 x i64> noundef [[A:%.*]], <2 x i64> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <2 x i64>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <2 x i64> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <2 x i64> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x i64>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x i64>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <2 x i64> @llvm.ct.select.v2i64(i1 [[TOBOOL]], <2 x i64> [[TMP1]], <2 x i64> [[TMP2]])
// CHECK-NEXT:    ret <2 x i64> [[TMP3]]
//
long2 test_vector_long2(int cond, long2 a, long2 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <2 x double> @test_vector_double2(
// CHECK-SAME: i32 noundef [[COND:%.*]], <2 x double> noundef [[A:%.*]], <2 x double> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <2 x double>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <2 x double> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <2 x double> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <2 x double>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <2 x double>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <2 x double> @llvm.ct.select.v2f64(i1 [[TOBOOL]], <2 x double> [[TMP1]], <2 x double> [[TMP2]])
// CHECK-NEXT:    ret <2 x double> [[TMP3]]
//
double2 test_vector_double2(int cond, double2 a, double2 b) {
  return __builtin_ct_select(cond, a, b);
}

// Test mixed vector operations
// CHECK-LABEL: define <4 x i32> @test_vector_from_scalar_condition(
// CHECK-SAME: <4 x i32> noundef [[VEC_COND:%.*]], <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[VEC_COND_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[SCALAR_COND:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store <4 x i32> [[VEC_COND]], ptr [[VEC_COND_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load <4 x i32>, ptr [[VEC_COND_ADDR]], align 16
// CHECK-NEXT:    [[VECEXT:%.*]] = extractelement <4 x i32> [[TMP0]], i32 0
// CHECK-NEXT:    store i32 [[VECEXT]], ptr [[SCALAR_COND]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[SCALAR_COND]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = call <4 x i32> @llvm.ct.select.v4i32(i1 [[TOBOOL]], <4 x i32> [[TMP2]], <4 x i32> [[TMP3]])
// CHECK-NEXT:    ret <4 x i32> [[TMP4]]
//
int4 test_vector_from_scalar_condition(int4 vec_cond, int4 a, int4 b) {
  // Extract first element and use as condition
  int scalar_cond = vec_cond[0];
  return __builtin_ct_select(scalar_cond, a, b);
}

// Test vector chaining
// CHECK-LABEL: define <4 x float> @test_vector_chaining(
// CHECK-SAME: i32 noundef [[COND1:%.*]], i32 noundef [[COND2:%.*]], i32 noundef [[COND3:%.*]], <4 x float> noundef [[A:%.*]], <4 x float> noundef [[B:%.*]], <4 x float> noundef [[C:%.*]], <4 x float> noundef [[D:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND1_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND2_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[COND3_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[C_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[D_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[FIRST:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[SECOND:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store i32 [[COND1]], ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND2]], ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    store i32 [[COND3]], ptr [[COND3_ADDR]], align 4
// CHECK-NEXT:    store <4 x float> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x float> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    store <4 x float> [[C]], ptr [[C_ADDR]], align 16
// CHECK-NEXT:    store <4 x float> [[D]], ptr [[D_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND1_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL]], <4 x float> [[TMP1]], <4 x float> [[TMP2]])
// CHECK-NEXT:    store <4 x float> [[TMP3]], ptr [[FIRST]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COND2_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL1:%.*]] = icmp ne i32 [[TMP4]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr [[FIRST]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <4 x float>, ptr [[C_ADDR]], align 16
// CHECK-NEXT:    [[TMP7:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL1]], <4 x float> [[TMP5]], <4 x float> [[TMP6]])
// CHECK-NEXT:    store <4 x float> [[TMP7]], ptr [[SECOND]], align 16
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[COND3_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL2:%.*]] = icmp ne i32 [[TMP8]], 0
// CHECK-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr [[SECOND]], align 16
// CHECK-NEXT:    [[TMP10:%.*]] = load <4 x float>, ptr [[D_ADDR]], align 16
// CHECK-NEXT:    [[TMP11:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL2]], <4 x float> [[TMP9]], <4 x float> [[TMP10]])
// CHECK-NEXT:    ret <4 x float> [[TMP11]]
//
float4 test_vector_chaining(int cond1, int cond2, int cond3, float4 a, float4 b, float4 c, float4 d) {
  float4 first = __builtin_ct_select(cond1, a, b);
  float4 second = __builtin_ct_select(cond2, first, c);
  return __builtin_ct_select(cond3, second, d);
}

// Test special floating point values - NaN
// CHECK-LABEL: define float @test_nan_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[NAN_VAL:%.*]] = alloca float, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store float +qnan, ptr [[NAN_VAL]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[NAN_VAL]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call float @llvm.ct.select.f32(i1 [[TOBOOL]], float [[TMP1]], float 1.000000e+00)
// CHECK-NEXT:    ret float [[TMP2]]
//
float test_nan_operands(int cond) {
  float nan_val = __builtin_nanf("");
  return __builtin_ct_select(cond, nan_val, 1.0f);
}

// CHECK-LABEL: define double @test_nan_double_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[NAN_VAL:%.*]] = alloca double, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store double +qnan, ptr [[NAN_VAL]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[NAN_VAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call double @llvm.ct.select.f64(i1 [[TOBOOL]], double [[TMP1]], double 2.000000e+00)
// CHECK-NEXT:    ret double [[TMP2]]
//
double test_nan_double_operands(int cond) {
  double nan_val = __builtin_nan("");
  return __builtin_ct_select(cond, nan_val, 2.0);
}

// Test infinity values
// CHECK-LABEL: define float @test_infinity_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[POS_INF:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[NEG_INF:%.*]] = alloca float, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store float +inf, ptr [[POS_INF]], align 4
// CHECK-NEXT:    store float -inf, ptr [[NEG_INF]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[POS_INF]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[NEG_INF]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call float @llvm.ct.select.f32(i1 [[TOBOOL]], float [[TMP1]], float [[TMP2]])
// CHECK-NEXT:    ret float [[TMP3]]
//
float test_infinity_operands(int cond) {
  float pos_inf = __builtin_inff();
  float neg_inf = -__builtin_inff();
  return __builtin_ct_select(cond, pos_inf, neg_inf);
}

// CHECK-LABEL: define double @test_infinity_double_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[POS_INF:%.*]] = alloca double, align 8
// CHECK-NEXT:    [[NEG_INF:%.*]] = alloca double, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store double +inf, ptr [[POS_INF]], align 8
// CHECK-NEXT:    store double -inf, ptr [[NEG_INF]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[POS_INF]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[NEG_INF]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call double @llvm.ct.select.f64(i1 [[TOBOOL]], double [[TMP1]], double [[TMP2]])
// CHECK-NEXT:    ret double [[TMP3]]
//
double test_infinity_double_operands(int cond) {
  double pos_inf = __builtin_inf();
  double neg_inf = -__builtin_inf();
  return __builtin_ct_select(cond, pos_inf, neg_inf);
}

// Test subnormal/denormal values
// CHECK-LABEL: define float @test_subnormal_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[SUBNORMAL1:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[SUBNORMAL2:%.*]] = alloca float, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store float 9.999940e-41, ptr [[SUBNORMAL1]], align 4
// CHECK-NEXT:    store float 1.401300e-45, ptr [[SUBNORMAL2]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[SUBNORMAL1]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[SUBNORMAL2]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call float @llvm.ct.select.f32(i1 [[TOBOOL]], float [[TMP1]], float [[TMP2]])
// CHECK-NEXT:    ret float [[TMP3]]
//
float test_subnormal_operands(int cond) {
  // Very small subnormal values
  float subnormal1 = 1e-40f;
  float subnormal2 = 1e-45f;
  return __builtin_ct_select(cond, subnormal1, subnormal2);
}

// Test integer overflow boundaries
// CHECK-LABEL: define i32 @test_integer_overflow_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[MAX_INT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[MIN_INT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 2147483647, ptr [[MAX_INT]], align 4
// CHECK-NEXT:    store i32 -2147483648, ptr [[MIN_INT]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[MAX_INT]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[MIN_INT]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_integer_overflow_operands(int cond) {
  int max_int = __INT_MAX__;
  int min_int = (-__INT_MAX__ - 1);
  return __builtin_ct_select(cond, max_int, min_int);
}

// CHECK-LABEL: define i64 @test_longlong_overflow_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[MAX_LL:%.*]] = alloca i64, align 8
// CHECK-NEXT:    [[MIN_LL:%.*]] = alloca i64, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i64 9223372036854775807, ptr [[MAX_LL]], align 8
// CHECK-NEXT:    store i64 -9223372036854775808, ptr [[MIN_LL]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i64, ptr [[MAX_LL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[MIN_LL]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call i64 @llvm.ct.select.i64(i1 [[TOBOOL]], i64 [[TMP1]], i64 [[TMP2]])
// CHECK-NEXT:    ret i64 [[TMP3]]
//
long long test_longlong_overflow_operands(int cond) {
  long long max_ll = __LONG_LONG_MAX__;
  long long min_ll = (-__LONG_LONG_MAX__ - 1);
  return __builtin_ct_select(cond, max_ll, min_ll);
}

// Test unsigned overflow boundaries
// CHECK-LABEL: define i32 @test_unsigned_overflow_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[MAX_UINT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[MIN_UINT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 -1, ptr [[MAX_UINT]], align 4
// CHECK-NEXT:    store i32 0, ptr [[MIN_UINT]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[MAX_UINT]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[MIN_UINT]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
unsigned int test_unsigned_overflow_operands(int cond) {
  unsigned int max_uint = 4294967295;
  unsigned int min_uint = 0;
  return __builtin_ct_select(cond, max_uint, min_uint);
}

// Test null pointer dereference avoidance
// CHECK-LABEL: define ptr @test_null_pointer_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]], ptr noundef [[VALID_PTR:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[VALID_PTR_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[NULL_PTR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store ptr [[VALID_PTR]], ptr [[VALID_PTR_ADDR]], align 8
// CHECK-NEXT:    store ptr null, ptr [[NULL_PTR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[NULL_PTR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[VALID_PTR_ADDR]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call ptr @llvm.ct.select.p0(i1 [[TOBOOL]], ptr [[TMP1]], ptr [[TMP2]])
// CHECK-NEXT:    ret ptr [[TMP3]]
//
int* test_null_pointer_operands(int cond, int* valid_ptr) {
  int* null_ptr = (int*)0;
  return __builtin_ct_select(cond, null_ptr, valid_ptr);
}

// Test volatile operations
volatile int global_volatile = 42;
// CHECK-LABEL: define i32 @test_volatile_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[VOL_VAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load volatile i32, ptr @global_volatile, align 4
// CHECK-NEXT:    store volatile i32 [[TMP0]], ptr [[VOL_VAL]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile i32, ptr [[VOL_VAL]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP2]], i32 100)
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_volatile_operands(int cond) {
  volatile int vol_val = global_volatile;
  return __builtin_ct_select(cond, vol_val, 100);
}

// Test uninitialized variable behavior (should still work with ct_select)
// CHECK-LABEL: define i32 @test_uninitialized_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[INITIALIZED:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[INITIALIZED_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[UNINITIALIZED:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[INITIALIZED]], ptr [[INITIALIZED_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[UNINITIALIZED]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[INITIALIZED_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP1]], i32 [[TMP2]])
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_uninitialized_operands(int cond, int initialized) {
  int uninitialized; // Intentionally uninitialized
  return __builtin_ct_select(cond, uninitialized, initialized);
}

// Test zero division avoidance patterns
// CHECK-LABEL: define i32 @test_division_by_zero_avoidance(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[DIVIDEND:%.*]], i32 noundef [[DIVISOR:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DIVIDEND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DIVISOR_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[SAFE_DIVISOR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[DIVIDEND]], ptr [[DIVIDEND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[DIVISOR]], ptr [[DIVISOR_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[DIVISOR_ADDR]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[DIVISOR_ADDR]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = call i32 @llvm.ct.select.i32(i1 [[CMP]], i32 [[TMP1]], i32 1)
// CHECK-NEXT:    store i32 [[TMP2]], ptr [[SAFE_DIVISOR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[DIVIDEND_ADDR]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[SAFE_DIVISOR]], align 4
// CHECK-NEXT:    [[DIV:%.*]] = sdiv i32 [[TMP3]], [[TMP4]]
// CHECK-NEXT:    ret i32 [[DIV]]
//
int test_division_by_zero_avoidance(int cond, int dividend, int divisor) {
  // First get a safe divisor (never zero)
  int safe_divisor = __builtin_ct_select(divisor != 0, divisor, 1);
  // Then perform division with guaranteed non-zero divisor
  return dividend / safe_divisor;
}

// Test array bounds checking patterns
// CHECK-LABEL: define i32 @test_array_bounds_protection(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[INDEX:%.*]], ptr noundef [[ARRAY:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[INDEX_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[ARRAY_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[SAFE_INDEX:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[INDEX]], ptr [[INDEX_ADDR]], align 4
// CHECK-NEXT:    store ptr [[ARRAY]], ptr [[ARRAY_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp sge i32 [[TMP0]], 0
// CHECK-NEXT:    br i1 [[CMP]], label %[[LAND_RHS:.*]], label %[[LAND_END:.*]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-NEXT:    [[CMP1:%.*]] = icmp slt i32 [[TMP1]], 10
// CHECK-NEXT:    br label %[[LAND_END]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP2:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ [[CMP1]], %[[LAND_RHS]] ]
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[INDEX_ADDR]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TMP2]], i32 [[TMP3]], i32 0)
// CHECK-NEXT:    store i32 [[TMP4]], ptr [[SAFE_INDEX]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[ARRAY_ADDR]], align 8
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[SAFE_INDEX]], align 4
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP6]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    ret i32 [[TMP7]]
//
int test_array_bounds_protection(int cond, int index, int* array) {
  // Use ct_select to ensure safe array indexing
  int safe_index = __builtin_ct_select(index >= 0 && index < 10, index, 0);
  return array[safe_index];
}

// Test bit manipulation edge cases
// CHECK-LABEL: define i32 @test_bit_manipulation_edge_cases(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[VALUE:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[VALUE_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[LEFT_SHIFT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[RIGHT_SHIFT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[VALUE]], ptr [[VALUE_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[VALUE_ADDR]], align 4
// CHECK-NEXT:    [[SHL:%.*]] = shl i32 [[TMP0]], 31
// CHECK-NEXT:    store i32 [[SHL]], ptr [[LEFT_SHIFT]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[VALUE_ADDR]], align 4
// CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[TMP1]], 31
// CHECK-NEXT:    store i32 [[SHR]], ptr [[RIGHT_SHIFT]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP2]], 0
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[LEFT_SHIFT]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[RIGHT_SHIFT]], align 4
// CHECK-NEXT:    [[TMP5:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP3]], i32 [[TMP4]])
// CHECK-NEXT:    ret i32 [[TMP5]]
//
unsigned int test_bit_manipulation_edge_cases(int cond, unsigned int value) {
  // Test extreme bit shifts that could cause undefined behavior
  unsigned int left_shift = value << 31;   // Could overflow
  unsigned int right_shift = value >> 31;  // Extract sign bit
  return __builtin_ct_select(cond, left_shift, right_shift);
}

// Test signed integer wraparound
// CHECK-LABEL: define i32 @test_signed_wraparound(
// CHECK-SAME: i32 noundef [[COND:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[SUM:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DIFF:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store i32 [[A]], ptr [[A_ADDR]], align 4
// CHECK-NEXT:    store i32 [[B]], ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP0]], [[TMP1]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[A_ADDR]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[B_ADDR]], align 4
// CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[TMP2]], [[TMP3]]
// CHECK-NEXT:    store i32 [[SUB]], ptr [[DIFF]], align 4
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP4]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[SUM]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[DIFF]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP5]], i32 [[TMP6]])
// CHECK-NEXT:    ret i32 [[TMP7]]
//
int test_signed_wraparound(int cond, int a, int b) {
  int sum = a + b;      // Could overflow
  int diff = a - b;     // Could underflow
  return __builtin_ct_select(cond, sum, diff);
}

// Test vector NaN handling
// CHECK-LABEL: define <4 x float> @test_vector_nan_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[NAN_VAL:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[NAN_VEC:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[NORMAL_VEC:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store float +qnan, ptr [[NAN_VAL]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[NAN_VAL]], align 4
// CHECK-NEXT:    [[VECINIT:%.*]] = insertelement <4 x float> poison, float [[TMP0]], i32 0
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[NAN_VAL]], align 4
// CHECK-NEXT:    [[VECINIT1:%.*]] = insertelement <4 x float> [[VECINIT]], float [[TMP1]], i32 1
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[NAN_VAL]], align 4
// CHECK-NEXT:    [[VECINIT2:%.*]] = insertelement <4 x float> [[VECINIT1]], float [[TMP2]], i32 2
// CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[NAN_VAL]], align 4
// CHECK-NEXT:    [[VECINIT3:%.*]] = insertelement <4 x float> [[VECINIT2]], float [[TMP3]], i32 3
// CHECK-NEXT:    store <4 x float> [[VECINIT3]], ptr [[NAN_VEC]], align 16
// CHECK-NEXT:    store <4 x float> <float 1.000000e+00, float 2.000000e+00, float 3.000000e+00, float 4.000000e+00>, ptr [[NORMAL_VEC]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP4]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr [[NAN_VEC]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <4 x float>, ptr [[NORMAL_VEC]], align 16
// CHECK-NEXT:    [[TMP7:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL]], <4 x float> [[TMP5]], <4 x float> [[TMP6]])
// CHECK-NEXT:    ret <4 x float> [[TMP7]]
//
float4 test_vector_nan_operands(int cond) {
  float nan_val = __builtin_nanf("");
  float4 nan_vec = {nan_val, nan_val, nan_val, nan_val};
  float4 normal_vec = {1.0f, 2.0f, 3.0f, 4.0f};
  return __builtin_ct_select(cond, nan_vec, normal_vec);
}

// Test vector infinity handling
// CHECK-LABEL: define <4 x float> @test_vector_infinity_operands(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[POS_INF:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[NEG_INF:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[INF_VEC:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[ZERO_VEC:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store float +inf, ptr [[POS_INF]], align 4
// CHECK-NEXT:    store float -inf, ptr [[NEG_INF]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[POS_INF]], align 4
// CHECK-NEXT:    [[VECINIT:%.*]] = insertelement <4 x float> poison, float [[TMP0]], i32 0
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[NEG_INF]], align 4
// CHECK-NEXT:    [[VECINIT1:%.*]] = insertelement <4 x float> [[VECINIT]], float [[TMP1]], i32 1
// CHECK-NEXT:    [[TMP2:%.*]] = load float, ptr [[POS_INF]], align 4
// CHECK-NEXT:    [[VECINIT2:%.*]] = insertelement <4 x float> [[VECINIT1]], float [[TMP2]], i32 2
// CHECK-NEXT:    [[TMP3:%.*]] = load float, ptr [[NEG_INF]], align 4
// CHECK-NEXT:    [[VECINIT3:%.*]] = insertelement <4 x float> [[VECINIT2]], float [[TMP3]], i32 3
// CHECK-NEXT:    store <4 x float> [[VECINIT3]], ptr [[INF_VEC]], align 16
// CHECK-NEXT:    store <4 x float> zeroinitializer, ptr [[ZERO_VEC]], align 16
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP4]], 0
// CHECK-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr [[INF_VEC]], align 16
// CHECK-NEXT:    [[TMP6:%.*]] = load <4 x float>, ptr [[ZERO_VEC]], align 16
// CHECK-NEXT:    [[TMP7:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL]], <4 x float> [[TMP5]], <4 x float> [[TMP6]])
// CHECK-NEXT:    ret <4 x float> [[TMP7]]
//
float4 test_vector_infinity_operands(int cond) {
  float pos_inf = __builtin_inff();
  float neg_inf = -__builtin_inff();
  float4 inf_vec = {pos_inf, neg_inf, pos_inf, neg_inf};
  float4 zero_vec = {0.0f, 0.0f, 0.0f, 0.0f};
  return __builtin_ct_select(cond, inf_vec, zero_vec);
}

// Test mixed special values
// CHECK-LABEL: define double @test_mixed_special_values(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[NAN_VAL:%.*]] = alloca double, align 8
// CHECK-NEXT:    [[INF_VAL:%.*]] = alloca double, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store double +qnan, ptr [[NAN_VAL]], align 8
// CHECK-NEXT:    store double +inf, ptr [[INF_VAL]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load double, ptr [[NAN_VAL]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load double, ptr [[INF_VAL]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = call double @llvm.ct.select.f64(i1 [[TOBOOL]], double [[TMP1]], double [[TMP2]])
// CHECK-NEXT:    ret double [[TMP3]]
//
double test_mixed_special_values(int cond) {
  double nan_val = __builtin_nan("");
  double inf_val = __builtin_inf();
  return __builtin_ct_select(cond, nan_val, inf_val);
}

// Test constant-time memory access pattern
// CHECK-LABEL: define i32 @test_constant_time_memory_access(
// CHECK-SAME: i32 noundef [[SECRET_INDEX:%.*]], ptr noundef [[DATA_ARRAY:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[SECRET_INDEX_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DATA_ARRAY_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[RESULT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[IS_TARGET:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[CURRENT_VALUE:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[SELECTED_VALUE:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[SECRET_INDEX]], ptr [[SECRET_INDEX_ADDR]], align 4
// CHECK-NEXT:    store ptr [[DATA_ARRAY]], ptr [[DATA_ARRAY_ADDR]], align 8
// CHECK-NEXT:    store i32 0, ptr [[RESULT]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label %[[FOR_COND:.*]]
// CHECK:       [[FOR_COND]]:
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP0]], 8
// CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY:.*]], label %[[FOR_END:.*]]
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[SECRET_INDEX_ADDR]], align 4
// CHECK-NEXT:    [[CMP1:%.*]] = icmp eq i32 [[TMP1]], [[TMP2]]
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[CMP1]] to i32
// CHECK-NEXT:    store i32 [[CONV]], ptr [[IS_TARGET]], align 4
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[DATA_ARRAY_ADDR]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP4]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    store i32 [[TMP5]], ptr [[CURRENT_VALUE]], align 4
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[IS_TARGET]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP6]], 0
// CHECK-NEXT:    [[TMP7:%.*]] = load i32, ptr [[CURRENT_VALUE]], align 4
// CHECK-NEXT:    [[TMP8:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL]], i32 [[TMP7]], i32 0)
// CHECK-NEXT:    store i32 [[TMP8]], ptr [[SELECTED_VALUE]], align 4
// CHECK-NEXT:    [[TMP9:%.*]] = load i32, ptr [[SELECTED_VALUE]], align 4
// CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[RESULT]], align 4
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[TMP10]], [[TMP9]]
// CHECK-NEXT:    store i32 [[ADD]], ptr [[RESULT]], align 4
// CHECK-NEXT:    br label %[[FOR_INC:.*]]
// CHECK:       [[FOR_INC]]:
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP11]], 1
// CHECK-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-NEXT:    br label %[[FOR_COND]], !llvm.loop [[LOOP1:![0-9]+]]
// CHECK:       [[FOR_END]]:
// CHECK-NEXT:    [[TMP12:%.*]] = load i32, ptr [[RESULT]], align 4
// CHECK-NEXT:    ret i32 [[TMP12]]
//
int test_constant_time_memory_access(int secret_index, int* data_array) {
  // This pattern ensures constant-time memory access regardless of secret_index value
  int result = 0;
  // Use ct_select to accumulate values without revealing the secret index
  for (int i = 0; i < 8; i++) {
    int is_target = (i == secret_index);
    int current_value = data_array[i];
    int selected_value = __builtin_ct_select(is_target, current_value, 0);
    result += selected_value;
  }
  return result;
}

// Test timing-attack resistant comparison
// CHECK-LABEL: define i32 @test_timing_resistant_comparison(
// CHECK-SAME: ptr noundef [[SECRET:%.*]], ptr noundef [[GUESS:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[SECRET_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[GUESS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[MATCH:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[CHARS_EQUAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[BOTH_NULL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[STILL_MATCHING:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store ptr [[SECRET]], ptr [[SECRET_ADDR]], align 8
// CHECK-NEXT:    store ptr [[GUESS]], ptr [[GUESS_ADDR]], align 8
// CHECK-NEXT:    store i32 1, ptr [[MATCH]], align 4
// CHECK-NEXT:    store i32 0, ptr [[I]], align 4
// CHECK-NEXT:    br label %[[FOR_COND:.*]]
// CHECK:       [[FOR_COND]]:
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[CMP:%.*]] = icmp slt i32 [[TMP0]], 32
// CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY:.*]], label %[[FOR_END:.*]]
// CHECK:       [[FOR_BODY]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[SECRET_ADDR]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[IDXPROM:%.*]] = sext i32 [[TMP2]] to i64
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i8, ptr [[TMP1]], i64 [[IDXPROM]]
// CHECK-NEXT:    [[TMP3:%.*]] = load i8, ptr [[ARRAYIDX]], align 1
// CHECK-NEXT:    [[CONV:%.*]] = sext i8 [[TMP3]] to i32
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[GUESS_ADDR]], align 8
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[IDXPROM1:%.*]] = sext i32 [[TMP5]] to i64
// CHECK-NEXT:    [[ARRAYIDX2:%.*]] = getelementptr inbounds i8, ptr [[TMP4]], i64 [[IDXPROM1]]
// CHECK-NEXT:    [[TMP6:%.*]] = load i8, ptr [[ARRAYIDX2]], align 1
// CHECK-NEXT:    [[CONV3:%.*]] = sext i8 [[TMP6]] to i32
// CHECK-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[CONV]], [[CONV3]]
// CHECK-NEXT:    [[CONV5:%.*]] = zext i1 [[CMP4]] to i32
// CHECK-NEXT:    store i32 [[CONV5]], ptr [[CHARS_EQUAL]], align 4
// CHECK-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[SECRET_ADDR]], align 8
// CHECK-NEXT:    [[TMP8:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[IDXPROM6:%.*]] = sext i32 [[TMP8]] to i64
// CHECK-NEXT:    [[ARRAYIDX7:%.*]] = getelementptr inbounds i8, ptr [[TMP7]], i64 [[IDXPROM6]]
// CHECK-NEXT:    [[TMP9:%.*]] = load i8, ptr [[ARRAYIDX7]], align 1
// CHECK-NEXT:    [[CONV8:%.*]] = sext i8 [[TMP9]] to i32
// CHECK-NEXT:    [[CMP9:%.*]] = icmp eq i32 [[CONV8]], 0
// CHECK-NEXT:    br i1 [[CMP9]], label %[[LAND_RHS:.*]], label %[[LAND_END:.*]]
// CHECK:       [[LAND_RHS]]:
// CHECK-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[GUESS_ADDR]], align 8
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[IDXPROM11:%.*]] = sext i32 [[TMP11]] to i64
// CHECK-NEXT:    [[ARRAYIDX12:%.*]] = getelementptr inbounds i8, ptr [[TMP10]], i64 [[IDXPROM11]]
// CHECK-NEXT:    [[TMP12:%.*]] = load i8, ptr [[ARRAYIDX12]], align 1
// CHECK-NEXT:    [[CONV13:%.*]] = sext i8 [[TMP12]] to i32
// CHECK-NEXT:    [[CMP14:%.*]] = icmp eq i32 [[CONV13]], 0
// CHECK-NEXT:    br label %[[LAND_END]]
// CHECK:       [[LAND_END]]:
// CHECK-NEXT:    [[TMP13:%.*]] = phi i1 [ false, %[[FOR_BODY]] ], [ [[CMP14]], %[[LAND_RHS]] ]
// CHECK-NEXT:    [[LAND_EXT:%.*]] = zext i1 [[TMP13]] to i32
// CHECK-NEXT:    store i32 [[LAND_EXT]], ptr [[BOTH_NULL]], align 4
// CHECK-NEXT:    [[TMP14:%.*]] = load i32, ptr [[CHARS_EQUAL]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP14]], 0
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[LOR_END:.*]], label %[[LOR_RHS:.*]]
// CHECK:       [[LOR_RHS]]:
// CHECK-NEXT:    [[TMP15:%.*]] = load i32, ptr [[BOTH_NULL]], align 4
// CHECK-NEXT:    [[TOBOOL16:%.*]] = icmp ne i32 [[TMP15]], 0
// CHECK-NEXT:    br label %[[LOR_END]]
// CHECK:       [[LOR_END]]:
// CHECK-NEXT:    [[TMP16:%.*]] = phi i1 [ true, %[[LAND_END]] ], [ [[TOBOOL16]], %[[LOR_RHS]] ]
// CHECK-NEXT:    [[TMP17:%.*]] = load i32, ptr [[MATCH]], align 4
// CHECK-NEXT:    [[TMP18:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TMP16]], i32 [[TMP17]], i32 0)
// CHECK-NEXT:    store i32 [[TMP18]], ptr [[STILL_MATCHING]], align 4
// CHECK-NEXT:    [[TMP19:%.*]] = load i32, ptr [[BOTH_NULL]], align 4
// CHECK-NEXT:    [[TOBOOL17:%.*]] = icmp ne i32 [[TMP19]], 0
// CHECK-NEXT:    [[TMP20:%.*]] = load i32, ptr [[MATCH]], align 4
// CHECK-NEXT:    [[TMP21:%.*]] = load i32, ptr [[STILL_MATCHING]], align 4
// CHECK-NEXT:    [[TMP22:%.*]] = call i32 @llvm.ct.select.i32(i1 [[TOBOOL17]], i32 [[TMP20]], i32 [[TMP21]])
// CHECK-NEXT:    store i32 [[TMP22]], ptr [[MATCH]], align 4
// CHECK-NEXT:    br label %[[FOR_INC:.*]]
// CHECK:       [[FOR_INC]]:
// CHECK-NEXT:    [[TMP23:%.*]] = load i32, ptr [[I]], align 4
// CHECK-NEXT:    [[INC:%.*]] = add nsw i32 [[TMP23]], 1
// CHECK-NEXT:    store i32 [[INC]], ptr [[I]], align 4
// CHECK-NEXT:    br label %[[FOR_COND]], !llvm.loop [[LOOP3:![0-9]+]]
// CHECK:       [[FOR_END]]:
// CHECK-NEXT:    [[TMP24:%.*]] = load i32, ptr [[MATCH]], align 4
// CHECK-NEXT:    ret i32 [[TMP24]]
//
int test_timing_resistant_comparison(const char* secret, const char* guess) {
  // Constant-time string comparison using ct_select
  int match = 1;
  for (int i = 0; i < 32; i++) {
    int chars_equal = (secret[i] == guess[i]);
    int both_null = (secret[i] == 0) && (guess[i] == 0);
    int still_matching = __builtin_ct_select(chars_equal || both_null, match, 0);
    match = __builtin_ct_select(both_null, match, still_matching);
  }
  return match;
}

// Test ext_vector_type vectors -- should lower identically to vector_size.
typedef int __attribute__((ext_vector_type(4))) int4_ext;
typedef float __attribute__((ext_vector_type(4))) float4_ext;
typedef char __attribute__((ext_vector_type(16))) char16_ext;

// CHECK-LABEL: define <4 x i32> @test_ext_vector_int4(
// CHECK-SAME: i32 noundef [[COND:%.*]], <4 x i32> noundef [[A:%.*]], <4 x i32> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x i32>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <4 x i32> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x i32> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x i32>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x i32>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <4 x i32> @llvm.ct.select.v4i32(i1 [[TOBOOL]], <4 x i32> [[TMP1]], <4 x i32> [[TMP2]])
// CHECK-NEXT:    ret <4 x i32> [[TMP3]]
//
int4_ext test_ext_vector_int4(int cond, int4_ext a, int4_ext b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <4 x float> @test_ext_vector_float4(
// CHECK-SAME: i32 noundef [[COND:%.*]], <4 x float> noundef [[A:%.*]], <4 x float> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <4 x float>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <4 x float> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <4 x float> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <4 x float>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <4 x float> @llvm.ct.select.v4f32(i1 [[TOBOOL]], <4 x float> [[TMP1]], <4 x float> [[TMP2]])
// CHECK-NEXT:    ret <4 x float> [[TMP3]]
//
float4_ext test_ext_vector_float4(int cond, float4_ext a, float4_ext b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <16 x i8> @test_ext_vector_char16(
// CHECK-SAME: i32 noundef [[COND:%.*]], <16 x i8> noundef [[A:%.*]], <16 x i8> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <16 x i8>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <16 x i8> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <16 x i8> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <16 x i8>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <16 x i8>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <16 x i8> @llvm.ct.select.v16i8(i1 [[TOBOOL]], <16 x i8> [[TMP1]], <16 x i8> [[TMP2]])
// CHECK-NEXT:    ret <16 x i8> [[TMP3]]
//
char16_ext test_ext_vector_char16(int cond, char16_ext a, char16_ext b) {
  return __builtin_ct_select(cond, a, b);
}

// Test half and bfloat scalar types.
// CHECK-LABEL: define half @test_half(
// CHECK-SAME: i32 noundef [[COND:%.*]], half noundef [[A:%.*]], half noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca half, align 2
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca half, align 2
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store half [[A]], ptr [[A_ADDR]], align 2
// CHECK-NEXT:    store half [[B]], ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load half, ptr [[A_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load half, ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call half @llvm.ct.select.f16(i1 [[TOBOOL]], half [[TMP1]], half [[TMP2]])
// CHECK-NEXT:    ret half [[TMP3]]
//
_Float16 test_half(int cond, _Float16 a, _Float16 b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define bfloat @test_bfloat(
// CHECK-SAME: i32 noundef [[COND:%.*]], bfloat noundef [[A:%.*]], bfloat noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca bfloat, align 2
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca bfloat, align 2
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store bfloat [[A]], ptr [[A_ADDR]], align 2
// CHECK-NEXT:    store bfloat [[B]], ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load bfloat, ptr [[A_ADDR]], align 2
// CHECK-NEXT:    [[TMP2:%.*]] = load bfloat, ptr [[B_ADDR]], align 2
// CHECK-NEXT:    [[TMP3:%.*]] = call bfloat @llvm.ct.select.bf16(i1 [[TOBOOL]], bfloat [[TMP1]], bfloat [[TMP2]])
// CHECK-NEXT:    ret bfloat [[TMP3]]
//
__bf16 test_bfloat(int cond, __bf16 a, __bf16 b) {
  return __builtin_ct_select(cond, a, b);
}

// Test half and bfloat ext_vector_type vectors.
typedef _Float16 __attribute__((ext_vector_type(8))) half8_ext;
typedef __bf16 __attribute__((ext_vector_type(8))) bfloat8_ext;

// CHECK-LABEL: define <8 x half> @test_ext_vector_half8(
// CHECK-SAME: i32 noundef [[COND:%.*]], <8 x half> noundef [[A:%.*]], <8 x half> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <8 x half>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <8 x half> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <8 x half> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x half>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <8 x half>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <8 x half> @llvm.ct.select.v8f16(i1 [[TOBOOL]], <8 x half> [[TMP1]], <8 x half> [[TMP2]])
// CHECK-NEXT:    ret <8 x half> [[TMP3]]
//
half8_ext test_ext_vector_half8(int cond, half8_ext a, half8_ext b) {
  return __builtin_ct_select(cond, a, b);
}

// CHECK-LABEL: define <8 x bfloat> @test_ext_vector_bfloat8(
// CHECK-SAME: i32 noundef [[COND:%.*]], <8 x bfloat> noundef [[A:%.*]], <8 x bfloat> noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca <8 x bfloat>, align 16
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca <8 x bfloat>, align 16
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    store <8 x bfloat> [[A]], ptr [[A_ADDR]], align 16
// CHECK-NEXT:    store <8 x bfloat> [[B]], ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = load <8 x bfloat>, ptr [[A_ADDR]], align 16
// CHECK-NEXT:    [[TMP2:%.*]] = load <8 x bfloat>, ptr [[B_ADDR]], align 16
// CHECK-NEXT:    [[TMP3:%.*]] = call <8 x bfloat> @llvm.ct.select.v8bf16(i1 [[TOBOOL]], <8 x bfloat> [[TMP1]], <8 x bfloat> [[TMP2]])
// CHECK-NEXT:    ret <8 x bfloat> [[TMP3]]
//
bfloat8_ext test_ext_vector_bfloat8(int cond, bfloat8_ext a, bfloat8_ext b) {
  return __builtin_ct_select(cond, a, b);
}

// Array arguments decay to pointers before the operand type check.
// CHECK-LABEL: define i32 @test_array_decay(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[ARR1:%.*]] = alloca [4 x i32], align 4
// CHECK-NEXT:    [[ARR2:%.*]] = alloca [4 x i32], align 4
// CHECK-NEXT:    [[R:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARR1]], i64 0, i64 0
// CHECK-NEXT:    [[ARRAYDECAY1:%.*]] = getelementptr inbounds [4 x i32], ptr [[ARR2]], i64 0, i64 0
// CHECK-NEXT:    [[TMP1:%.*]] = call ptr @llvm.ct.select.p0(i1 [[TOBOOL]], ptr [[ARRAYDECAY]], ptr [[ARRAYDECAY1]])
// CHECK-NEXT:    store ptr [[TMP1]], ptr [[R]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = load ptr, ptr [[R]], align 8
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 0
// CHECK-NEXT:    [[TMP3:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// CHECK-NEXT:    ret i32 [[TMP3]]
//
int test_array_decay(int cond) {
  int arr1[4], arr2[4];
  int *r = __builtin_ct_select(cond, arr1, arr2);
  return r[0];
}

// Function arguments decay to function pointers before the operand type check.
typedef void (*fnptr)(void);
void fn_a(void);
void fn_b(void);
// CHECK-LABEL: define ptr @test_func_decay(
// CHECK-SAME: i32 noundef [[COND:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[COND_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 [[COND]], ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr [[COND_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = call ptr @llvm.ct.select.p0(i1 [[TOBOOL]], ptr @fn_a, ptr @fn_b)
// CHECK-NEXT:    ret ptr [[TMP1]]
//
fnptr test_func_decay(int cond) {
  return __builtin_ct_select(cond, fn_a, fn_b);
}
//.
// CHECK: [[LOOP1]] = distinct !{[[LOOP1]], [[META2:![0-9]+]]}
// CHECK: [[META2]] = !{!"llvm.loop.mustprogress"}
// CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]]}
//.
