// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -O2 -emit-llvm -o - %s | FileCheck %s --check-prefix=X86_64
// RUN: %clang_cc1 -triple i386-unknown-unknown -O2 -emit-llvm -o - %s | FileCheck %s --check-prefix=I386

struct s {
  char x;
  short count;
  int array[] __attribute__((counted_by(count)));
};

// X86_64-LABEL: define dso_local noalias noundef ptr @test1(
// X86_64-SAME: i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// X86_64-NEXT:  [[ENTRY:.*:]]
// X86_64-NEXT:    [[CONV:%.*]] = sext i32 [[SIZE]] to i64
// X86_64-NEXT:    [[MUL:%.*]] = shl nsw i64 [[CONV]], 2
// X86_64-NEXT:    [[ADD:%.*]] = add nsw i64 [[MUL]], 4
// X86_64-NEXT:    [[CALL:%.*]] = tail call ptr @malloc(i64 noundef [[ADD]]) #[[ATTR3:[0-9]+]]
// X86_64-NEXT:    [[CONV1:%.*]] = trunc i32 [[SIZE]] to i16
// X86_64-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw i8, ptr [[CALL]], i64 2
// X86_64-NEXT:    store i16 [[CONV1]], ptr [[COUNT]], align 2, !tbaa [[TBAA2:![0-9]+]]
// X86_64-NEXT:    ret ptr [[CALL]]
//
// I386-LABEL: define dso_local noalias noundef ptr @test1(
// I386-SAME: i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// I386-NEXT:  [[ENTRY:.*:]]
// I386-NEXT:    [[MUL:%.*]] = shl i32 [[SIZE]], 2
// I386-NEXT:    [[ADD:%.*]] = add i32 [[MUL]], 4
// I386-NEXT:    [[CALL:%.*]] = tail call ptr @malloc(i32 noundef [[ADD]]) #[[ATTR3:[0-9]+]]
// I386-NEXT:    [[CONV:%.*]] = trunc i32 [[SIZE]] to i16
// I386-NEXT:    [[COUNT:%.*]] = getelementptr inbounds nuw i8, ptr [[CALL]], i32 2
// I386-NEXT:    store i16 [[CONV]], ptr [[COUNT]], align 2, !tbaa [[TBAA3:![0-9]+]]
// I386-NEXT:    ret ptr [[CALL]]
//
struct s *test1(int size) {
  struct s *p = __builtin_malloc(sizeof(struct s) + sizeof(int) * size);

  *__builtin_get_counted_by(p->array) = size;
  *__builtin_get_counted_by(&p->array[0]) = size;
  return p;
}

struct z {
  char x;
  short count;
  int array[];
};

// X86_64-LABEL: define dso_local noalias noundef ptr @test2(
// X86_64-SAME: i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// X86_64-NEXT:  [[ENTRY:.*:]]
// X86_64-NEXT:    [[CONV:%.*]] = sext i32 [[SIZE]] to i64
// X86_64-NEXT:    [[MUL:%.*]] = shl nsw i64 [[CONV]], 2
// X86_64-NEXT:    [[ADD:%.*]] = add nsw i64 [[MUL]], 4
// X86_64-NEXT:    [[CALL:%.*]] = tail call ptr @malloc(i64 noundef [[ADD]]) #[[ATTR3]]
// X86_64-NEXT:    ret ptr [[CALL]]
//
// I386-LABEL: define dso_local noalias noundef ptr @test2(
// I386-SAME: i32 noundef [[SIZE:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] {
// I386-NEXT:  [[ENTRY:.*:]]
// I386-NEXT:    [[MUL:%.*]] = shl i32 [[SIZE]], 2
// I386-NEXT:    [[ADD:%.*]] = add i32 [[MUL]], 4
// I386-NEXT:    [[CALL:%.*]] = tail call ptr @malloc(i32 noundef [[ADD]]) #[[ATTR3]]
// I386-NEXT:    ret ptr [[CALL]]
//
struct z *test2(int size) {
  struct z *p = __builtin_malloc(sizeof(struct z) + sizeof(int) * size);

  if (__builtin_get_counted_by(&p->array[0]))
    *__builtin_get_counted_by(&p->array[0]) = size;

  return p;
}
//.
// X86_64: [[TBAA2]] = !{[[META3:![0-9]+]], [[META3]], i64 0}
// X86_64: [[META3]] = !{!"short", [[META4:![0-9]+]], i64 0}
// X86_64: [[META4]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// X86_64: [[META5]] = !{!"Simple C/C++ TBAA"}
//.
// I386: [[TBAA3]] = !{[[META4:![0-9]+]], [[META4]], i64 0}
// I386: [[META4]] = !{!"short", [[META5:![0-9]+]], i64 0}
// I386: [[META5]] = !{!"omnipotent char", [[META6:![0-9]+]], i64 0}
// I386: [[META6]] = !{!"Simple C/C++ TBAA"}
//.
