// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm %s -o - | FileCheck %s

#define FP_NAN 3
#define FP_INFINITE 516
#define FP_ZERO 96
#define FP_SUBNORMAL 144
#define FP_NORMAL 264

// CHECK-LABEL: define dso_local i32 @test_fpclassify_float(
// CHECK-SAME: float noundef [[X:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = call i1 @llvm.is.fpclass.f32(float [[TMP0]], i32 3)
// CHECK-NEXT:    br i1 [[TMP1]], label %[[FPCLASSIFY_END:.*]], label %[[FPCLASSIFY_NOT_NAN:.*]]
// CHECK:       [[FPCLASSIFY_NOT_NAN]]:
// CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.is.fpclass.f32(float [[TMP0]], i32 516)
// CHECK-NEXT:    br i1 [[TMP2]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_INFINITE:.*]]
// CHECK:       [[FPCLASSIFY_NOT_INFINITE]]:
// CHECK-NEXT:    [[TMP3:%.*]] = call i1 @llvm.is.fpclass.f32(float [[TMP0]], i32 264)
// CHECK-NEXT:    br i1 [[TMP3]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_NORMAL:.*]]
// CHECK:       [[FPCLASSIFY_NOT_NORMAL]]:
// CHECK-NEXT:    [[TMP4:%.*]] = call i1 @llvm.is.fpclass.f32(float [[TMP0]], i32 144)
// CHECK-NEXT:    br i1 [[TMP4]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_SUBNORMAL:.*]]
// CHECK:       [[FPCLASSIFY_NOT_SUBNORMAL]]:
// CHECK-NEXT:    br label %[[FPCLASSIFY_END]]
// CHECK:       [[FPCLASSIFY_END]]:
// CHECK-NEXT:    [[FPCLASSIFY_RESULT:%.*]] = phi i32 [ 3, %[[ENTRY]] ], [ 516, %[[FPCLASSIFY_NOT_NAN]] ], [ 264, %[[FPCLASSIFY_NOT_INFINITE]] ], [ 144, %[[FPCLASSIFY_NOT_NORMAL]] ], [ 96, %[[FPCLASSIFY_NOT_SUBNORMAL]] ]
// CHECK-NEXT:    ret i32 [[FPCLASSIFY_RESULT]]
//
int test_fpclassify_float(float x) {
  return __builtin_fpclassify(FP_NAN, FP_INFINITE, FP_NORMAL, FP_SUBNORMAL,
                              FP_ZERO, x);
}

// CHECK-LABEL: define dso_local i32 @test_fpclassify_double(
// CHECK-SAME: double noundef [[X:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca double, align 8
// CHECK-NEXT:    store double [[X]], ptr [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr [[X_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call i1 @llvm.is.fpclass.f64(double [[TMP0]], i32 3)
// CHECK-NEXT:    br i1 [[TMP1]], label %[[FPCLASSIFY_END:.*]], label %[[FPCLASSIFY_NOT_NAN:.*]]
// CHECK:       [[FPCLASSIFY_NOT_NAN]]:
// CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.is.fpclass.f64(double [[TMP0]], i32 516)
// CHECK-NEXT:    br i1 [[TMP2]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_INFINITE:.*]]
// CHECK:       [[FPCLASSIFY_NOT_INFINITE]]:
// CHECK-NEXT:    [[TMP3:%.*]] = call i1 @llvm.is.fpclass.f64(double [[TMP0]], i32 264)
// CHECK-NEXT:    br i1 [[TMP3]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_NORMAL:.*]]
// CHECK:       [[FPCLASSIFY_NOT_NORMAL]]:
// CHECK-NEXT:    [[TMP4:%.*]] = call i1 @llvm.is.fpclass.f64(double [[TMP0]], i32 144)
// CHECK-NEXT:    br i1 [[TMP4]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_SUBNORMAL:.*]]
// CHECK:       [[FPCLASSIFY_NOT_SUBNORMAL]]:
// CHECK-NEXT:    br label %[[FPCLASSIFY_END]]
// CHECK:       [[FPCLASSIFY_END]]:
// CHECK-NEXT:    [[FPCLASSIFY_RESULT:%.*]] = phi i32 [ 3, %[[ENTRY]] ], [ 516, %[[FPCLASSIFY_NOT_NAN]] ], [ 264, %[[FPCLASSIFY_NOT_INFINITE]] ], [ 144, %[[FPCLASSIFY_NOT_NORMAL]] ], [ 96, %[[FPCLASSIFY_NOT_SUBNORMAL]] ]
// CHECK-NEXT:    ret i32 [[FPCLASSIFY_RESULT]]
//
int test_fpclassify_double(double x) {
  return __builtin_fpclassify(FP_NAN, FP_INFINITE, FP_NORMAL, FP_SUBNORMAL,
                              FP_ZERO, x);
}

// CHECK-LABEL: define dso_local i32 @test_fpclassify_long_double(
// CHECK-SAME: x86_fp80 noundef [[X:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*]]:
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca x86_fp80, align 16
// CHECK-NEXT:    store x86_fp80 [[X]], ptr [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP0:%.*]] = load x86_fp80, ptr [[X_ADDR]], align 16
// CHECK-NEXT:    [[TMP1:%.*]] = call i1 @llvm.is.fpclass.f80(x86_fp80 [[TMP0]], i32 3)
// CHECK-NEXT:    br i1 [[TMP1]], label %[[FPCLASSIFY_END:.*]], label %[[FPCLASSIFY_NOT_NAN:.*]]
// CHECK:       [[FPCLASSIFY_NOT_NAN]]:
// CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.is.fpclass.f80(x86_fp80 [[TMP0]], i32 516)
// CHECK-NEXT:    br i1 [[TMP2]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_INFINITE:.*]]
// CHECK:       [[FPCLASSIFY_NOT_INFINITE]]:
// CHECK-NEXT:    [[TMP3:%.*]] = call i1 @llvm.is.fpclass.f80(x86_fp80 [[TMP0]], i32 264)
// CHECK-NEXT:    br i1 [[TMP3]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_NORMAL:.*]]
// CHECK:       [[FPCLASSIFY_NOT_NORMAL]]:
// CHECK-NEXT:    [[TMP4:%.*]] = call i1 @llvm.is.fpclass.f80(x86_fp80 [[TMP0]], i32 144)
// CHECK-NEXT:    br i1 [[TMP4]], label %[[FPCLASSIFY_END]], label %[[FPCLASSIFY_NOT_SUBNORMAL:.*]]
// CHECK:       [[FPCLASSIFY_NOT_SUBNORMAL]]:
// CHECK-NEXT:    br label %[[FPCLASSIFY_END]]
// CHECK:       [[FPCLASSIFY_END]]:
// CHECK-NEXT:    [[FPCLASSIFY_RESULT:%.*]] = phi i32 [ 3, %[[ENTRY]] ], [ 516, %[[FPCLASSIFY_NOT_NAN]] ], [ 264, %[[FPCLASSIFY_NOT_INFINITE]] ], [ 144, %[[FPCLASSIFY_NOT_NORMAL]] ], [ 96, %[[FPCLASSIFY_NOT_SUBNORMAL]] ]
// CHECK-NEXT:    ret i32 [[FPCLASSIFY_RESULT]]
//
int test_fpclassify_long_double(long double x) {
  return __builtin_fpclassify(FP_NAN, FP_INFINITE, FP_NORMAL, FP_SUBNORMAL,
                              FP_ZERO, x);
}
