// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -cc1 -triple x86_64-pc-linux-gnu -emit-llvm -o - %s | FileCheck %s

static_assert(__has_builtin(__builtin_experimental_provenance_begin), "");
static_assert(__has_builtin(__builtin_experimental_provenance_end), "");

void *Ptr;

// CHECK-LABEL: define dso_local void @_Z4testv(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[PTRPROV:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr @Ptr, align 8
// CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr @Ptr, align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call ptr @llvm.experimental.provenance.begin.p0.p0(ptr [[TMP1]])
// CHECK-NEXT:    store ptr [[TMP2]], ptr [[PTRPROV]], align 8
// CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[PTRPROV]], align 8
// CHECK-NEXT:    call void @llvm.experimental.provenance.end.p0(ptr [[TMP3]])
// CHECK-NEXT:    ret void
//
void test(){
    void *PtrProv = __builtin_experimental_provenance_begin(Ptr);
    __builtin_experimental_provenance_end(PtrProv);
}
