// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple riscv32-linux-elf -O3  -target-feature +xmipsexectl -emit-llvm -o - %s  | FileCheck %s

// CHECK-LABEL: define dso_local void @test_mips_pause(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.riscv.mips.pause()
// CHECK-NEXT:    ret void
//
void test_mips_pause()
{
	__builtin_riscv_mips_pause();
}

// CHECK-LABEL: define dso_local void @test_mips_ehb(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.riscv.mips.ehb()
// CHECK-NEXT:    ret void
//
void test_mips_ehb()
{
	__builtin_riscv_mips_ehb();
}

// CHECK-LABEL: define dso_local void @test_mips_ihb(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.riscv.mips.ihb()
// CHECK-NEXT:    ret void
//
void test_mips_ihb()
{
	__builtin_riscv_mips_ihb();
}
