// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple x86_64-unknown-unknown -ffp-exception-behavior=maytrap -emit-llvm -o - %s | FileCheck --implicit-check-not=fpexcept.maytrap --implicit-check-not=round.tonearest %s


// Test that the constrained intrinsics are picking up the exception
// metadata from the AST instead of the global default from the command line.
// Include rounding metadata in the testing.
// Any cases of "fpexcept.maytrap" in this test are clang bugs.
// Any cases of "round.tonearest" in this test are clang bugs.

#pragma float_control(except, on)
#pragma STDC FENV_ROUND FE_UPWARD

_Complex double g1, g2;
_Complex float cf;
double D;

// CHECK-LABEL: @test3a(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr @D, align 8
// CHECK-NEXT:    [[CF_REAL:%.*]] = load float, ptr @cf, align 4
// CHECK-NEXT:    [[CF_IMAG:%.*]] = load float, ptr getelementptr inbounds nuw (i8, ptr @cf, i64 4), align 4
// CHECK-NEXT:    [[CONV:%.*]] = call double @llvm.fpext.f64.f32(float [[CF_REAL]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[CONV1:%.*]] = call double @llvm.fpext.f64.f32(float [[CF_IMAG]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[ADD_R:%.*]] = call double @llvm.fadd.f64(double [[CONV]], double [[TMP0]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[CONV2:%.*]] = call float @llvm.fptrunc.f32.f64(double [[ADD_R]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[CONV3:%.*]] = call float @llvm.fptrunc.f32.f64(double [[CONV1]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    store float [[CONV2]], ptr @cf, align 4
// CHECK-NEXT:    store float [[CONV3]], ptr getelementptr inbounds nuw (i8, ptr @cf, i64 4), align 4
// CHECK-NEXT:    ret void
//
void test3a(void) {
  cf += D;
}

// CHECK-LABEL: @test3b(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CF_REAL:%.*]] = load float, ptr @cf, align 4
// CHECK-NEXT:    [[CF_IMAG:%.*]] = load float, ptr getelementptr inbounds nuw (i8, ptr @cf, i64 4), align 4
// CHECK-NEXT:    [[CONV:%.*]] = call double @llvm.fpext.f64.f32(float [[CF_REAL]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[CONV1:%.*]] = call double @llvm.fpext.f64.f32(float [[CF_IMAG]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr @D, align 8
// CHECK-NEXT:    [[ADD_R:%.*]] = call double @llvm.fadd.f64(double [[TMP0]], double [[CONV]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    store double [[ADD_R]], ptr @D, align 8
// CHECK-NEXT:    ret void
//
void test3b(void) {
  D += cf;
}

// CHECK-LABEL: @test3c(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[G1_REAL:%.*]] = load double, ptr @g1, align 8
// CHECK-NEXT:    [[G1_IMAG:%.*]] = load double, ptr getelementptr inbounds nuw (i8, ptr @g1, i64 8), align 8
// CHECK-NEXT:    [[CF_REAL:%.*]] = load float, ptr @cf, align 4
// CHECK-NEXT:    [[CF_IMAG:%.*]] = load float, ptr getelementptr inbounds nuw (i8, ptr @cf, i64 4), align 4
// CHECK-NEXT:    [[CONV:%.*]] = call double @llvm.fpext.f64.f32(float [[CF_REAL]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[CONV1:%.*]] = call double @llvm.fpext.f64.f32(float [[CF_IMAG]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[CALL:%.*]] = call { double, double } @__divdc3(double noundef [[CONV]], double noundef [[CONV1]], double noundef [[G1_REAL]], double noundef [[G1_IMAG]]) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    [[TMP0:%.*]] = extractvalue { double, double } [[CALL]], 0
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { double, double } [[CALL]], 1
// CHECK-NEXT:    [[CONV2:%.*]] = call float @llvm.fptrunc.f32.f64(double [[TMP0]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    [[CONV3:%.*]] = call float @llvm.fptrunc.f32.f64(double [[TMP1]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    store float [[CONV2]], ptr @cf, align 4
// CHECK-NEXT:    store float [[CONV3]], ptr getelementptr inbounds nuw (i8, ptr @cf, i64 4), align 4
// CHECK-NEXT:    ret void
//
void test3c(void) {
  cf /= g1;
}

// CHECK-LABEL: @test3d(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[G1_REAL:%.*]] = load double, ptr @g1, align 8
// CHECK-NEXT:    [[G1_IMAG:%.*]] = load double, ptr getelementptr inbounds nuw (i8, ptr @g1, i64 8), align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr @D, align 8
// CHECK-NEXT:    [[ADD_R:%.*]] = call double @llvm.fadd.f64(double [[G1_REAL]], double [[TMP0]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    store double [[ADD_R]], ptr @g1, align 8
// CHECK-NEXT:    store double [[G1_IMAG]], ptr getelementptr inbounds nuw (i8, ptr @g1, i64 8), align 8
// CHECK-NEXT:    ret void
//
void test3d(void) {
  g1 = g1 + D;
}

// CHECK-LABEL: @test3e(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr @D, align 8
// CHECK-NEXT:    [[G1_REAL:%.*]] = load double, ptr @g1, align 8
// CHECK-NEXT:    [[G1_IMAG:%.*]] = load double, ptr getelementptr inbounds nuw (i8, ptr @g1, i64 8), align 8
// CHECK-NEXT:    [[ADD_R:%.*]] = call double @llvm.fadd.f64(double [[TMP0]], double [[G1_REAL]]) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    store double [[ADD_R]], ptr @g1, align 8
// CHECK-NEXT:    store double [[G1_IMAG]], ptr getelementptr inbounds nuw (i8, ptr @g1, i64 8), align 8
// CHECK-NEXT:    ret void
//
void test3e(void) {
  g1 = D + g1;
}

// CHECK-LABEL: @t1(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = call float @llvm.fptrunc.f32.f64(double 4.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    store float [[CONV]], ptr @cf, align 4
// CHECK-NEXT:    ret void
//
void t1(void) {
  (__real__ cf) = 4.0;
}

// CHECK-LABEL: @t2(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[CONV:%.*]] = call float @llvm.fptrunc.f32.f64(double 4.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    store float [[CONV]], ptr getelementptr inbounds nuw (i8, ptr @cf, i64 4), align 4
// CHECK-NEXT:    ret void
//
void t2(void) {
  (__imag__ cf) = 4.0;
}

// CHECK-LABEL: @t91(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[C:%.*]] = alloca [0 x i8], align 1
// CHECK-NEXT:    br i1 false, label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
// CHECK:       cond.true:
// CHECK-NEXT:    [[CONV:%.*]] = call double @llvm.fpext.f64.f32(float 2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    br label [[COND_END:%.*]]
// CHECK:       cond.false:
// CHECK-NEXT:    [[CONV1:%.*]] = call double @llvm.fpext.f64.f32(float 2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    br label [[COND_END]]
// CHECK:       cond.end:
// CHECK-NEXT:    [[COND_R:%.*]] = phi double [ [[CONV]], [[COND_TRUE]] ], [ [[CONV1]], [[COND_FALSE]] ]
// CHECK-NEXT:    [[COND_I:%.*]] = phi double [ 0.000000e+00, [[COND_TRUE]] ], [ 0.000000e+00, [[COND_FALSE]] ]
// CHECK-NEXT:    ret void
//
void t91(void) {
  // Check for proper type promotion of conditional expression
  char c[(int)(sizeof(typeof((0 ? 2.0f : (_Complex double) 2.0f))) - sizeof(_Complex double))];
  // Check for proper codegen
  (0 ? 2.0f : (_Complex double) 2.0f);
}

// CHECK-LABEL: @t92(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[C:%.*]] = alloca [0 x i8], align 1
// CHECK-NEXT:    br i1 false, label [[COND_TRUE:%.*]], label [[COND_FALSE:%.*]]
// CHECK:       cond.true:
// CHECK-NEXT:    [[CONV:%.*]] = call double @llvm.fpext.f64.f32(float 2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    br label [[COND_END:%.*]]
// CHECK:       cond.false:
// CHECK-NEXT:    [[CONV1:%.*]] = call double @llvm.fpext.f64.f32(float 2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rtp") ]
// CHECK-NEXT:    br label [[COND_END]]
// CHECK:       cond.end:
// CHECK-NEXT:    [[COND_R:%.*]] = phi double [ [[CONV]], [[COND_TRUE]] ], [ [[CONV1]], [[COND_FALSE]] ]
// CHECK-NEXT:    [[COND_I:%.*]] = phi double [ 0.000000e+00, [[COND_TRUE]] ], [ 0.000000e+00, [[COND_FALSE]] ]
// CHECK-NEXT:    ret void
//
void t92(void) {
  // Check for proper type promotion of conditional expression
  char c[(int)(sizeof(typeof((0 ? (_Complex double) 2.0f : 2.0f))) - sizeof(_Complex double))];
  // Check for proper codegen
  (0 ? (_Complex double) 2.0f : 2.0f);
}

