// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-unknown %s -emit-llvm -o - | FileCheck %s
// RUN: %clang_cc1 -triple x86_64-unknown-unknown %s -ffp-exception-behavior=maytrap -emit-llvm -o - | FileCheck %s

// Test codegen of constrained floating point to bool conversion
//
// Test that the constrained intrinsics are picking up the exception
// metadata from the AST instead of the global default from the command line.

#pragma float_control(except, on)

// CHECK-LABEL: define dso_local void @eMaisUma(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[T:%.*]] = alloca [1 x double], align 8
// CHECK-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [1 x double], ptr [[T]], i64 0, i64 0
// CHECK-NEXT:    [[TMP0:%.*]] = load double, ptr [[ARRAYDECAY]], align 8
// CHECK-NEXT:    [[TOBOOL:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double 0.000000e+00, metadata !"une") #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    br label %[[IF_END]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    ret void
//
void eMaisUma(void) {
  double t[1];
  if (*t)
    return;
}

