// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: x86-registered-target
// UNSUPPORTED: target={{.*}}-zos{{.*}}
// RUN: %clang -S -emit-llvm -fenable-matrix -ffp-model=fast %s -o - \
// RUN: | FileCheck %s --check-prefixes=CHECK,CHECK-FAST

// RUN: %clang -S -emit-llvm -fenable-matrix -ffp-model=aggressive %s -o - \
// RUN: | FileCheck %s --check-prefixes=CHECK,CHECK-AGGRESSIVE

// RUN: %clang -S -emit-llvm -fenable-matrix -ffp-model=precise %s -o - \
// RUN: | FileCheck %s --check-prefixes=CHECK,CHECK-PRECISE

// RUN: %clang -S -emit-llvm -fenable-matrix -ffp-model=strict %s -o - \
// RUN: -target x86_64 | FileCheck %s --check-prefixes=CHECK,CHECK-STRICT

// RUN: %clang -S -emit-llvm -fenable-matrix -ffp-model=strict -ffast-math \
// RUN: -target x86_64 %s -o - | FileCheck %s \
// RUN: --check-prefixes CHECK,CHECK-STRICT-FAST

// RUN: %clang -S -emit-llvm -fenable-matrix -ffp-model=precise -ffast-math \
// RUN: %s -o - | FileCheck %s --check-prefixes CHECK,CHECK-FAST1

// CHECK-FAST-LABEL: define dso_local float @mymuladd(
// CHECK-FAST-SAME: float noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], float noundef [[TMP2:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-FAST-NEXT:    [[TMP4:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    [[TMP5:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[TMP0]], ptr [[TMP4]], align 4
// CHECK-FAST-NEXT:    store float [[TMP1]], ptr [[TMP5]], align 4
// CHECK-FAST-NEXT:    store float [[TMP2]], ptr [[TMP6]], align 4
// CHECK-FAST-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP4]], align 4
// CHECK-FAST-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP5]], align 4
// CHECK-FAST-NEXT:    [[TMP9:%.*]] = fmul reassoc nsz arcp contract afn float [[TMP7]], [[TMP8]]
// CHECK-FAST-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-FAST-NEXT:    [[TMP11:%.*]] = fadd reassoc nsz arcp contract afn float [[TMP9]], [[TMP10]]
// CHECK-FAST-NEXT:    ret float [[TMP11]]
//
// CHECK-AGGRESSIVE-LABEL: define dso_local nofpclass(nan inf) float @mymuladd(
// CHECK-AGGRESSIVE-SAME: float noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], float noundef nofpclass(nan inf) [[TMP2:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-AGGRESSIVE-NEXT:    [[TMP4:%.*]] = alloca float, align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP5:%.*]] = alloca float, align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-AGGRESSIVE-NEXT:    store float [[TMP0]], ptr [[TMP4]], align 4
// CHECK-AGGRESSIVE-NEXT:    store float [[TMP1]], ptr [[TMP5]], align 4
// CHECK-AGGRESSIVE-NEXT:    store float [[TMP2]], ptr [[TMP6]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP4]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP5]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP9:%.*]] = fmul fast float [[TMP7]], [[TMP8]]
// CHECK-AGGRESSIVE-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP11:%.*]] = fadd fast float [[TMP9]], [[TMP10]]
// CHECK-AGGRESSIVE-NEXT:    ret float [[TMP11]]
//
// CHECK-PRECISE-LABEL: define dso_local float @mymuladd(
// CHECK-PRECISE-SAME: float noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], float noundef [[TMP2:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-PRECISE-NEXT:    [[TMP4:%.*]] = alloca float, align 4
// CHECK-PRECISE-NEXT:    [[TMP5:%.*]] = alloca float, align 4
// CHECK-PRECISE-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-PRECISE-NEXT:    store float [[TMP0]], ptr [[TMP4]], align 4
// CHECK-PRECISE-NEXT:    store float [[TMP1]], ptr [[TMP5]], align 4
// CHECK-PRECISE-NEXT:    store float [[TMP2]], ptr [[TMP6]], align 4
// CHECK-PRECISE-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP4]], align 4
// CHECK-PRECISE-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP5]], align 4
// CHECK-PRECISE-NEXT:    [[TMP9:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-PRECISE-NEXT:    [[TMP10:%.*]] = call float @llvm.fmuladd.f32(float [[TMP7]], float [[TMP8]], float [[TMP9]])
// CHECK-PRECISE-NEXT:    ret float [[TMP10]]
//
// CHECK-STRICT-LABEL: define dso_local float @mymuladd(
// CHECK-STRICT-SAME: float noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], float noundef [[TMP2:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-STRICT-NEXT:    [[TMP4:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[TMP5:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    store float [[TMP0]], ptr [[TMP4]], align 4
// CHECK-STRICT-NEXT:    store float [[TMP1]], ptr [[TMP5]], align 4
// CHECK-STRICT-NEXT:    store float [[TMP2]], ptr [[TMP6]], align 4
// CHECK-STRICT-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP4]], align 4
// CHECK-STRICT-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP5]], align 4
// CHECK-STRICT-NEXT:    [[TMP9:%.*]] = fmul float [[TMP7]], [[TMP8]]
// CHECK-STRICT-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-STRICT-NEXT:    [[TMP11:%.*]] = fadd float [[TMP9]], [[TMP10]]
// CHECK-STRICT-NEXT:    ret float [[TMP11]]
//
// CHECK-STRICT-FAST-LABEL: define dso_local nofpclass(nan inf) float @mymuladd(
// CHECK-STRICT-FAST-SAME: float noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], float noundef nofpclass(nan inf) [[TMP2:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-STRICT-FAST-NEXT:    [[TMP4:%.*]] = alloca float, align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP5:%.*]] = alloca float, align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-STRICT-FAST-NEXT:    store float [[TMP0]], ptr [[TMP4]], align 4
// CHECK-STRICT-FAST-NEXT:    store float [[TMP1]], ptr [[TMP5]], align 4
// CHECK-STRICT-FAST-NEXT:    store float [[TMP2]], ptr [[TMP6]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP4]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP5]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP9:%.*]] = fmul fast float [[TMP7]], [[TMP8]]
// CHECK-STRICT-FAST-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP11:%.*]] = fadd fast float [[TMP9]], [[TMP10]]
// CHECK-STRICT-FAST-NEXT:    ret float [[TMP11]]
//
// CHECK-FAST1-LABEL: define dso_local nofpclass(nan inf) float @mymuladd(
// CHECK-FAST1-SAME: float noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], float noundef nofpclass(nan inf) [[TMP2:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-FAST1-NEXT:    [[TMP4:%.*]] = alloca float, align 4
// CHECK-FAST1-NEXT:    [[TMP5:%.*]] = alloca float, align 4
// CHECK-FAST1-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-FAST1-NEXT:    store float [[TMP0]], ptr [[TMP4]], align 4
// CHECK-FAST1-NEXT:    store float [[TMP1]], ptr [[TMP5]], align 4
// CHECK-FAST1-NEXT:    store float [[TMP2]], ptr [[TMP6]], align 4
// CHECK-FAST1-NEXT:    [[TMP7:%.*]] = load float, ptr [[TMP4]], align 4
// CHECK-FAST1-NEXT:    [[TMP8:%.*]] = load float, ptr [[TMP5]], align 4
// CHECK-FAST1-NEXT:    [[TMP9:%.*]] = fmul fast float [[TMP7]], [[TMP8]]
// CHECK-FAST1-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-FAST1-NEXT:    [[TMP11:%.*]] = fadd fast float [[TMP9]], [[TMP10]]
// CHECK-FAST1-NEXT:    ret float [[TMP11]]
//
float mymuladd(float x, float y, float z) {
  return x * y + z;






}

typedef float __attribute__((ext_vector_type(2))) v2f;

// CHECK-FAST-LABEL: define dso_local void @my_vec_muladd(
// CHECK-FAST-SAME: double noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], double noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR0]] {
// CHECK-FAST-NEXT:    [[TMP5:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST-NEXT:    [[TMP6:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST-NEXT:    [[TMP7:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST-NEXT:    [[TMP8:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    [[TMP9:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST-NEXT:    [[TMP10:%.*]] = alloca ptr, align 8
// CHECK-FAST-NEXT:    store double [[TMP0]], ptr [[TMP5]], align 8
// CHECK-FAST-NEXT:    [[TMP11:%.*]] = load <2 x float>, ptr [[TMP5]], align 8
// CHECK-FAST-NEXT:    store double [[TMP2]], ptr [[TMP6]], align 8
// CHECK-FAST-NEXT:    [[TMP12:%.*]] = load <2 x float>, ptr [[TMP6]], align 8
// CHECK-FAST-NEXT:    store <2 x float> [[TMP11]], ptr [[TMP7]], align 8
// CHECK-FAST-NEXT:    store float [[TMP1]], ptr [[TMP8]], align 4
// CHECK-FAST-NEXT:    store <2 x float> [[TMP12]], ptr [[TMP9]], align 8
// CHECK-FAST-NEXT:    store ptr [[TMP3]], ptr [[TMP10]], align 8
// CHECK-FAST-NEXT:    [[TMP13:%.*]] = load <2 x float>, ptr [[TMP7]], align 8
// CHECK-FAST-NEXT:    [[TMP14:%.*]] = load float, ptr [[TMP8]], align 4
// CHECK-FAST-NEXT:    [[TMP15:%.*]] = insertelement <2 x float> poison, float [[TMP14]], i64 0
// CHECK-FAST-NEXT:    [[TMP16:%.*]] = shufflevector <2 x float> [[TMP15]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-FAST-NEXT:    [[TMP17:%.*]] = fmul reassoc nsz arcp contract afn <2 x float> [[TMP13]], [[TMP16]]
// CHECK-FAST-NEXT:    [[TMP18:%.*]] = load <2 x float>, ptr [[TMP9]], align 8
// CHECK-FAST-NEXT:    [[TMP19:%.*]] = fadd reassoc nsz arcp contract afn <2 x float> [[TMP17]], [[TMP18]]
// CHECK-FAST-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-FAST-NEXT:    store <2 x float> [[TMP19]], ptr [[TMP20]], align 8
// CHECK-FAST-NEXT:    ret void
//
// CHECK-AGGRESSIVE-LABEL: define dso_local void @my_vec_muladd(
// CHECK-AGGRESSIVE-SAME: double noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], double noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR0]] {
// CHECK-AGGRESSIVE-NEXT:    [[TMP5:%.*]] = alloca <2 x float>, align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP6:%.*]] = alloca <2 x float>, align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP7:%.*]] = alloca <2 x float>, align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP8:%.*]] = alloca float, align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP9:%.*]] = alloca <2 x float>, align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP10:%.*]] = alloca ptr, align 8
// CHECK-AGGRESSIVE-NEXT:    store double [[TMP0]], ptr [[TMP5]], align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP11:%.*]] = load <2 x float>, ptr [[TMP5]], align 8
// CHECK-AGGRESSIVE-NEXT:    store double [[TMP2]], ptr [[TMP6]], align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP12:%.*]] = load <2 x float>, ptr [[TMP6]], align 8
// CHECK-AGGRESSIVE-NEXT:    store <2 x float> [[TMP11]], ptr [[TMP7]], align 8
// CHECK-AGGRESSIVE-NEXT:    store float [[TMP1]], ptr [[TMP8]], align 4
// CHECK-AGGRESSIVE-NEXT:    store <2 x float> [[TMP12]], ptr [[TMP9]], align 8
// CHECK-AGGRESSIVE-NEXT:    store ptr [[TMP3]], ptr [[TMP10]], align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP13:%.*]] = load <2 x float>, ptr [[TMP7]], align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP14:%.*]] = load float, ptr [[TMP8]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP15:%.*]] = insertelement <2 x float> poison, float [[TMP14]], i64 0
// CHECK-AGGRESSIVE-NEXT:    [[TMP16:%.*]] = shufflevector <2 x float> [[TMP15]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-AGGRESSIVE-NEXT:    [[TMP17:%.*]] = fmul fast <2 x float> [[TMP13]], [[TMP16]]
// CHECK-AGGRESSIVE-NEXT:    [[TMP18:%.*]] = load <2 x float>, ptr [[TMP9]], align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP19:%.*]] = fadd fast <2 x float> [[TMP17]], [[TMP18]]
// CHECK-AGGRESSIVE-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-AGGRESSIVE-NEXT:    store <2 x float> [[TMP19]], ptr [[TMP20]], align 8
// CHECK-AGGRESSIVE-NEXT:    ret void
//
// CHECK-PRECISE-LABEL: define dso_local void @my_vec_muladd(
// CHECK-PRECISE-SAME: double noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], double noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR0]] {
// CHECK-PRECISE-NEXT:    [[TMP5:%.*]] = alloca <2 x float>, align 8
// CHECK-PRECISE-NEXT:    [[TMP6:%.*]] = alloca <2 x float>, align 8
// CHECK-PRECISE-NEXT:    [[TMP7:%.*]] = alloca <2 x float>, align 8
// CHECK-PRECISE-NEXT:    [[TMP8:%.*]] = alloca float, align 4
// CHECK-PRECISE-NEXT:    [[TMP9:%.*]] = alloca <2 x float>, align 8
// CHECK-PRECISE-NEXT:    [[TMP10:%.*]] = alloca ptr, align 8
// CHECK-PRECISE-NEXT:    store double [[TMP0]], ptr [[TMP5]], align 8
// CHECK-PRECISE-NEXT:    [[TMP11:%.*]] = load <2 x float>, ptr [[TMP5]], align 8
// CHECK-PRECISE-NEXT:    store double [[TMP2]], ptr [[TMP6]], align 8
// CHECK-PRECISE-NEXT:    [[TMP12:%.*]] = load <2 x float>, ptr [[TMP6]], align 8
// CHECK-PRECISE-NEXT:    store <2 x float> [[TMP11]], ptr [[TMP7]], align 8
// CHECK-PRECISE-NEXT:    store float [[TMP1]], ptr [[TMP8]], align 4
// CHECK-PRECISE-NEXT:    store <2 x float> [[TMP12]], ptr [[TMP9]], align 8
// CHECK-PRECISE-NEXT:    store ptr [[TMP3]], ptr [[TMP10]], align 8
// CHECK-PRECISE-NEXT:    [[TMP13:%.*]] = load <2 x float>, ptr [[TMP7]], align 8
// CHECK-PRECISE-NEXT:    [[TMP14:%.*]] = load float, ptr [[TMP8]], align 4
// CHECK-PRECISE-NEXT:    [[TMP15:%.*]] = insertelement <2 x float> poison, float [[TMP14]], i64 0
// CHECK-PRECISE-NEXT:    [[TMP16:%.*]] = shufflevector <2 x float> [[TMP15]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-PRECISE-NEXT:    [[TMP17:%.*]] = load <2 x float>, ptr [[TMP9]], align 8
// CHECK-PRECISE-NEXT:    [[TMP18:%.*]] = call <2 x float> @llvm.fmuladd.v2f32(<2 x float> [[TMP13]], <2 x float> [[TMP16]], <2 x float> [[TMP17]])
// CHECK-PRECISE-NEXT:    [[TMP19:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-PRECISE-NEXT:    store <2 x float> [[TMP18]], ptr [[TMP19]], align 8
// CHECK-PRECISE-NEXT:    ret void
//
// CHECK-STRICT-LABEL: define dso_local void @my_vec_muladd(
// CHECK-STRICT-SAME: double noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], double noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR0]] {
// CHECK-STRICT-NEXT:    [[TMP5:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-NEXT:    [[TMP6:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-NEXT:    [[TMP7:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-NEXT:    [[TMP8:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[TMP9:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-NEXT:    [[TMP10:%.*]] = alloca ptr, align 8
// CHECK-STRICT-NEXT:    store double [[TMP0]], ptr [[TMP5]], align 8
// CHECK-STRICT-NEXT:    [[TMP11:%.*]] = load <2 x float>, ptr [[TMP5]], align 8
// CHECK-STRICT-NEXT:    store double [[TMP2]], ptr [[TMP6]], align 8
// CHECK-STRICT-NEXT:    [[TMP12:%.*]] = load <2 x float>, ptr [[TMP6]], align 8
// CHECK-STRICT-NEXT:    store <2 x float> [[TMP11]], ptr [[TMP7]], align 8
// CHECK-STRICT-NEXT:    store float [[TMP1]], ptr [[TMP8]], align 4
// CHECK-STRICT-NEXT:    store <2 x float> [[TMP12]], ptr [[TMP9]], align 8
// CHECK-STRICT-NEXT:    store ptr [[TMP3]], ptr [[TMP10]], align 8
// CHECK-STRICT-NEXT:    [[TMP13:%.*]] = load <2 x float>, ptr [[TMP7]], align 8
// CHECK-STRICT-NEXT:    [[TMP14:%.*]] = load float, ptr [[TMP8]], align 4
// CHECK-STRICT-NEXT:    [[TMP15:%.*]] = insertelement <2 x float> poison, float [[TMP14]], i64 0
// CHECK-STRICT-NEXT:    [[TMP16:%.*]] = shufflevector <2 x float> [[TMP15]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-STRICT-NEXT:    [[TMP17:%.*]] = fmul <2 x float> [[TMP13]], [[TMP16]]
// CHECK-STRICT-NEXT:    [[TMP18:%.*]] = load <2 x float>, ptr [[TMP9]], align 8
// CHECK-STRICT-NEXT:    [[TMP19:%.*]] = fadd <2 x float> [[TMP17]], [[TMP18]]
// CHECK-STRICT-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-STRICT-NEXT:    store <2 x float> [[TMP19]], ptr [[TMP20]], align 8
// CHECK-STRICT-NEXT:    ret void
//
// CHECK-STRICT-FAST-LABEL: define dso_local void @my_vec_muladd(
// CHECK-STRICT-FAST-SAME: double noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], double noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR0]] {
// CHECK-STRICT-FAST-NEXT:    [[TMP5:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP6:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP7:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP8:%.*]] = alloca float, align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP9:%.*]] = alloca <2 x float>, align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP10:%.*]] = alloca ptr, align 8
// CHECK-STRICT-FAST-NEXT:    store double [[TMP0]], ptr [[TMP5]], align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP11:%.*]] = load <2 x float>, ptr [[TMP5]], align 8
// CHECK-STRICT-FAST-NEXT:    store double [[TMP2]], ptr [[TMP6]], align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP12:%.*]] = load <2 x float>, ptr [[TMP6]], align 8
// CHECK-STRICT-FAST-NEXT:    store <2 x float> [[TMP11]], ptr [[TMP7]], align 8
// CHECK-STRICT-FAST-NEXT:    store float [[TMP1]], ptr [[TMP8]], align 4
// CHECK-STRICT-FAST-NEXT:    store <2 x float> [[TMP12]], ptr [[TMP9]], align 8
// CHECK-STRICT-FAST-NEXT:    store ptr [[TMP3]], ptr [[TMP10]], align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP13:%.*]] = load <2 x float>, ptr [[TMP7]], align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP14:%.*]] = load float, ptr [[TMP8]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP15:%.*]] = insertelement <2 x float> poison, float [[TMP14]], i64 0
// CHECK-STRICT-FAST-NEXT:    [[TMP16:%.*]] = shufflevector <2 x float> [[TMP15]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-STRICT-FAST-NEXT:    [[TMP17:%.*]] = fmul fast <2 x float> [[TMP13]], [[TMP16]]
// CHECK-STRICT-FAST-NEXT:    [[TMP18:%.*]] = load <2 x float>, ptr [[TMP9]], align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP19:%.*]] = fadd fast <2 x float> [[TMP17]], [[TMP18]]
// CHECK-STRICT-FAST-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-STRICT-FAST-NEXT:    store <2 x float> [[TMP19]], ptr [[TMP20]], align 8
// CHECK-STRICT-FAST-NEXT:    ret void
//
// CHECK-FAST1-LABEL: define dso_local void @my_vec_muladd(
// CHECK-FAST1-SAME: double noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], double noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR0]] {
// CHECK-FAST1-NEXT:    [[TMP5:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST1-NEXT:    [[TMP6:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST1-NEXT:    [[TMP7:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST1-NEXT:    [[TMP8:%.*]] = alloca float, align 4
// CHECK-FAST1-NEXT:    [[TMP9:%.*]] = alloca <2 x float>, align 8
// CHECK-FAST1-NEXT:    [[TMP10:%.*]] = alloca ptr, align 8
// CHECK-FAST1-NEXT:    store double [[TMP0]], ptr [[TMP5]], align 8
// CHECK-FAST1-NEXT:    [[TMP11:%.*]] = load <2 x float>, ptr [[TMP5]], align 8
// CHECK-FAST1-NEXT:    store double [[TMP2]], ptr [[TMP6]], align 8
// CHECK-FAST1-NEXT:    [[TMP12:%.*]] = load <2 x float>, ptr [[TMP6]], align 8
// CHECK-FAST1-NEXT:    store <2 x float> [[TMP11]], ptr [[TMP7]], align 8
// CHECK-FAST1-NEXT:    store float [[TMP1]], ptr [[TMP8]], align 4
// CHECK-FAST1-NEXT:    store <2 x float> [[TMP12]], ptr [[TMP9]], align 8
// CHECK-FAST1-NEXT:    store ptr [[TMP3]], ptr [[TMP10]], align 8
// CHECK-FAST1-NEXT:    [[TMP13:%.*]] = load <2 x float>, ptr [[TMP7]], align 8
// CHECK-FAST1-NEXT:    [[TMP14:%.*]] = load float, ptr [[TMP8]], align 4
// CHECK-FAST1-NEXT:    [[TMP15:%.*]] = insertelement <2 x float> poison, float [[TMP14]], i64 0
// CHECK-FAST1-NEXT:    [[TMP16:%.*]] = shufflevector <2 x float> [[TMP15]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-FAST1-NEXT:    [[TMP17:%.*]] = fmul fast <2 x float> [[TMP13]], [[TMP16]]
// CHECK-FAST1-NEXT:    [[TMP18:%.*]] = load <2 x float>, ptr [[TMP9]], align 8
// CHECK-FAST1-NEXT:    [[TMP19:%.*]] = fadd fast <2 x float> [[TMP17]], [[TMP18]]
// CHECK-FAST1-NEXT:    [[TMP20:%.*]] = load ptr, ptr [[TMP10]], align 8
// CHECK-FAST1-NEXT:    store <2 x float> [[TMP19]], ptr [[TMP20]], align 8
// CHECK-FAST1-NEXT:    ret void
//
void my_vec_muladd(v2f x, float y, v2f z, v2f *res) {
  *res = x * y + z;






}

typedef float __attribute__((matrix_type(2, 1))) m21f;

// CHECK-FAST-LABEL: define dso_local void @my_m21_muladd(
// CHECK-FAST-SAME: <2 x float> noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], <2 x float> noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR1:[0-9]+]] {
// CHECK-FAST-NEXT:    [[TMP5:%.*]] = alloca [2 x float], align 4
// CHECK-FAST-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    [[TMP7:%.*]] = alloca [2 x float], align 4
// CHECK-FAST-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-FAST-NEXT:    store <2 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-FAST-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-FAST-NEXT:    store <2 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-FAST-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-FAST-NEXT:    [[TMP9:%.*]] = load <2 x float>, ptr [[TMP5]], align 4
// CHECK-FAST-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-FAST-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> poison, float [[TMP10]], i64 0
// CHECK-FAST-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP11]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-FAST-NEXT:    [[TMP13:%.*]] = fmul reassoc nsz arcp contract afn <2 x float> [[TMP9]], [[TMP12]]
// CHECK-FAST-NEXT:    [[TMP14:%.*]] = load <2 x float>, ptr [[TMP7]], align 4
// CHECK-FAST-NEXT:    [[TMP15:%.*]] = fadd reassoc nsz arcp contract afn <2 x float> [[TMP13]], [[TMP14]]
// CHECK-FAST-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-FAST-NEXT:    store <2 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-FAST-NEXT:    ret void
//
// CHECK-AGGRESSIVE-LABEL: define dso_local void @my_m21_muladd(
// CHECK-AGGRESSIVE-SAME: <2 x float> noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], <2 x float> noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR1:[0-9]+]] {
// CHECK-AGGRESSIVE-NEXT:    [[TMP5:%.*]] = alloca [2 x float], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP7:%.*]] = alloca [2 x float], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-AGGRESSIVE-NEXT:    store <2 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-AGGRESSIVE-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-AGGRESSIVE-NEXT:    store <2 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-AGGRESSIVE-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP9:%.*]] = load <2 x float>, ptr [[TMP5]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> poison, float [[TMP10]], i64 0
// CHECK-AGGRESSIVE-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP11]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-AGGRESSIVE-NEXT:    [[TMP13:%.*]] = fmul fast <2 x float> [[TMP9]], [[TMP12]]
// CHECK-AGGRESSIVE-NEXT:    [[TMP14:%.*]] = load <2 x float>, ptr [[TMP7]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP15:%.*]] = fadd fast <2 x float> [[TMP13]], [[TMP14]]
// CHECK-AGGRESSIVE-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-AGGRESSIVE-NEXT:    store <2 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-AGGRESSIVE-NEXT:    ret void
//
// CHECK-PRECISE-LABEL: define dso_local void @my_m21_muladd(
// CHECK-PRECISE-SAME: <2 x float> noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], <2 x float> noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-PRECISE-NEXT:    [[TMP5:%.*]] = alloca [2 x float], align 4
// CHECK-PRECISE-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-PRECISE-NEXT:    [[TMP7:%.*]] = alloca [2 x float], align 4
// CHECK-PRECISE-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-PRECISE-NEXT:    store <2 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-PRECISE-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-PRECISE-NEXT:    store <2 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-PRECISE-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-PRECISE-NEXT:    [[TMP9:%.*]] = load <2 x float>, ptr [[TMP5]], align 4
// CHECK-PRECISE-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-PRECISE-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> poison, float [[TMP10]], i64 0
// CHECK-PRECISE-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP11]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-PRECISE-NEXT:    [[TMP13:%.*]] = load <2 x float>, ptr [[TMP7]], align 4
// CHECK-PRECISE-NEXT:    [[TMP14:%.*]] = call <2 x float> @llvm.fmuladd.v2f32(<2 x float> [[TMP9]], <2 x float> [[TMP12]], <2 x float> [[TMP13]])
// CHECK-PRECISE-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-PRECISE-NEXT:    store <2 x float> [[TMP14]], ptr [[TMP15]], align 4
// CHECK-PRECISE-NEXT:    ret void
//
// CHECK-STRICT-LABEL: define dso_local void @my_m21_muladd(
// CHECK-STRICT-SAME: <2 x float> noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], <2 x float> noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR1:[0-9]+]] {
// CHECK-STRICT-NEXT:    [[TMP5:%.*]] = alloca [2 x float], align 4
// CHECK-STRICT-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[TMP7:%.*]] = alloca [2 x float], align 4
// CHECK-STRICT-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-STRICT-NEXT:    store <2 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-STRICT-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-STRICT-NEXT:    store <2 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-STRICT-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-STRICT-NEXT:    [[TMP9:%.*]] = load <2 x float>, ptr [[TMP5]], align 4
// CHECK-STRICT-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-STRICT-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> poison, float [[TMP10]], i64 0
// CHECK-STRICT-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP11]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-STRICT-NEXT:    [[TMP13:%.*]] = fmul <2 x float> [[TMP9]], [[TMP12]]
// CHECK-STRICT-NEXT:    [[TMP14:%.*]] = load <2 x float>, ptr [[TMP7]], align 4
// CHECK-STRICT-NEXT:    [[TMP15:%.*]] = fadd <2 x float> [[TMP13]], [[TMP14]]
// CHECK-STRICT-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-STRICT-NEXT:    store <2 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-STRICT-NEXT:    ret void
//
// CHECK-STRICT-FAST-LABEL: define dso_local void @my_m21_muladd(
// CHECK-STRICT-FAST-SAME: <2 x float> noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], <2 x float> noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR1:[0-9]+]] {
// CHECK-STRICT-FAST-NEXT:    [[TMP5:%.*]] = alloca [2 x float], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP7:%.*]] = alloca [2 x float], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-STRICT-FAST-NEXT:    store <2 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-STRICT-FAST-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-STRICT-FAST-NEXT:    store <2 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-STRICT-FAST-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP9:%.*]] = load <2 x float>, ptr [[TMP5]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> poison, float [[TMP10]], i64 0
// CHECK-STRICT-FAST-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP11]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-STRICT-FAST-NEXT:    [[TMP13:%.*]] = fmul fast <2 x float> [[TMP9]], [[TMP12]]
// CHECK-STRICT-FAST-NEXT:    [[TMP14:%.*]] = load <2 x float>, ptr [[TMP7]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP15:%.*]] = fadd fast <2 x float> [[TMP13]], [[TMP14]]
// CHECK-STRICT-FAST-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-STRICT-FAST-NEXT:    store <2 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-STRICT-FAST-NEXT:    ret void
//
// CHECK-FAST1-LABEL: define dso_local void @my_m21_muladd(
// CHECK-FAST1-SAME: <2 x float> noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], <2 x float> noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR1:[0-9]+]] {
// CHECK-FAST1-NEXT:    [[TMP5:%.*]] = alloca [2 x float], align 4
// CHECK-FAST1-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-FAST1-NEXT:    [[TMP7:%.*]] = alloca [2 x float], align 4
// CHECK-FAST1-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-FAST1-NEXT:    store <2 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-FAST1-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-FAST1-NEXT:    store <2 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-FAST1-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-FAST1-NEXT:    [[TMP9:%.*]] = load <2 x float>, ptr [[TMP5]], align 4
// CHECK-FAST1-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-FAST1-NEXT:    [[TMP11:%.*]] = insertelement <2 x float> poison, float [[TMP10]], i64 0
// CHECK-FAST1-NEXT:    [[TMP12:%.*]] = shufflevector <2 x float> [[TMP11]], <2 x float> poison, <2 x i32> zeroinitializer
// CHECK-FAST1-NEXT:    [[TMP13:%.*]] = fmul fast <2 x float> [[TMP9]], [[TMP12]]
// CHECK-FAST1-NEXT:    [[TMP14:%.*]] = load <2 x float>, ptr [[TMP7]], align 4
// CHECK-FAST1-NEXT:    [[TMP15:%.*]] = fadd fast <2 x float> [[TMP13]], [[TMP14]]
// CHECK-FAST1-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-FAST1-NEXT:    store <2 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-FAST1-NEXT:    ret void
//
void my_m21_muladd(m21f x, float y, m21f z, m21f *res) {
  *res = x * y + z;






}

typedef float __attribute__((matrix_type(2, 2))) m22f;

// CHECK-FAST-LABEL: define dso_local void @my_m22_muladd(
// CHECK-FAST-SAME: <4 x float> noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], <4 x float> noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-FAST-NEXT:    [[TMP5:%.*]] = alloca [4 x float], align 4
// CHECK-FAST-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    [[TMP7:%.*]] = alloca [4 x float], align 4
// CHECK-FAST-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-FAST-NEXT:    store <4 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-FAST-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-FAST-NEXT:    store <4 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-FAST-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-FAST-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr [[TMP5]], align 4
// CHECK-FAST-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-FAST-NEXT:    [[TMP11:%.*]] = insertelement <4 x float> poison, float [[TMP10]], i64 0
// CHECK-FAST-NEXT:    [[TMP12:%.*]] = shufflevector <4 x float> [[TMP11]], <4 x float> poison, <4 x i32> zeroinitializer
// CHECK-FAST-NEXT:    [[TMP13:%.*]] = fmul reassoc nsz arcp contract afn <4 x float> [[TMP9]], [[TMP12]]
// CHECK-FAST-NEXT:    [[TMP14:%.*]] = load <4 x float>, ptr [[TMP7]], align 4
// CHECK-FAST-NEXT:    [[TMP15:%.*]] = fadd reassoc nsz arcp contract afn <4 x float> [[TMP13]], [[TMP14]]
// CHECK-FAST-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-FAST-NEXT:    store <4 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-FAST-NEXT:    ret void
//
// CHECK-AGGRESSIVE-LABEL: define dso_local void @my_m22_muladd(
// CHECK-AGGRESSIVE-SAME: <4 x float> noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], <4 x float> noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-AGGRESSIVE-NEXT:    [[TMP5:%.*]] = alloca [4 x float], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP7:%.*]] = alloca [4 x float], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-AGGRESSIVE-NEXT:    store <4 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-AGGRESSIVE-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-AGGRESSIVE-NEXT:    store <4 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-AGGRESSIVE-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-AGGRESSIVE-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr [[TMP5]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP11:%.*]] = insertelement <4 x float> poison, float [[TMP10]], i64 0
// CHECK-AGGRESSIVE-NEXT:    [[TMP12:%.*]] = shufflevector <4 x float> [[TMP11]], <4 x float> poison, <4 x i32> zeroinitializer
// CHECK-AGGRESSIVE-NEXT:    [[TMP13:%.*]] = fmul fast <4 x float> [[TMP9]], [[TMP12]]
// CHECK-AGGRESSIVE-NEXT:    [[TMP14:%.*]] = load <4 x float>, ptr [[TMP7]], align 4
// CHECK-AGGRESSIVE-NEXT:    [[TMP15:%.*]] = fadd fast <4 x float> [[TMP13]], [[TMP14]]
// CHECK-AGGRESSIVE-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-AGGRESSIVE-NEXT:    store <4 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-AGGRESSIVE-NEXT:    ret void
//
// CHECK-PRECISE-LABEL: define dso_local void @my_m22_muladd(
// CHECK-PRECISE-SAME: <4 x float> noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], <4 x float> noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR3:[0-9]+]] {
// CHECK-PRECISE-NEXT:    [[TMP5:%.*]] = alloca [4 x float], align 4
// CHECK-PRECISE-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-PRECISE-NEXT:    [[TMP7:%.*]] = alloca [4 x float], align 4
// CHECK-PRECISE-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-PRECISE-NEXT:    store <4 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-PRECISE-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-PRECISE-NEXT:    store <4 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-PRECISE-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-PRECISE-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr [[TMP5]], align 4
// CHECK-PRECISE-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-PRECISE-NEXT:    [[TMP11:%.*]] = insertelement <4 x float> poison, float [[TMP10]], i64 0
// CHECK-PRECISE-NEXT:    [[TMP12:%.*]] = shufflevector <4 x float> [[TMP11]], <4 x float> poison, <4 x i32> zeroinitializer
// CHECK-PRECISE-NEXT:    [[TMP13:%.*]] = load <4 x float>, ptr [[TMP7]], align 4
// CHECK-PRECISE-NEXT:    [[TMP14:%.*]] = call <4 x float> @llvm.fmuladd.v4f32(<4 x float> [[TMP9]], <4 x float> [[TMP12]], <4 x float> [[TMP13]])
// CHECK-PRECISE-NEXT:    [[TMP15:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-PRECISE-NEXT:    store <4 x float> [[TMP14]], ptr [[TMP15]], align 4
// CHECK-PRECISE-NEXT:    ret void
//
// CHECK-STRICT-LABEL: define dso_local void @my_m22_muladd(
// CHECK-STRICT-SAME: <4 x float> noundef [[TMP0:%.*]], float noundef [[TMP1:%.*]], <4 x float> noundef [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-STRICT-NEXT:    [[TMP5:%.*]] = alloca [4 x float], align 4
// CHECK-STRICT-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[TMP7:%.*]] = alloca [4 x float], align 4
// CHECK-STRICT-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-STRICT-NEXT:    store <4 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-STRICT-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-STRICT-NEXT:    store <4 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-STRICT-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-STRICT-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr [[TMP5]], align 4
// CHECK-STRICT-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-STRICT-NEXT:    [[TMP11:%.*]] = insertelement <4 x float> poison, float [[TMP10]], i64 0
// CHECK-STRICT-NEXT:    [[TMP12:%.*]] = shufflevector <4 x float> [[TMP11]], <4 x float> poison, <4 x i32> zeroinitializer
// CHECK-STRICT-NEXT:    [[TMP13:%.*]] = fmul <4 x float> [[TMP9]], [[TMP12]]
// CHECK-STRICT-NEXT:    [[TMP14:%.*]] = load <4 x float>, ptr [[TMP7]], align 4
// CHECK-STRICT-NEXT:    [[TMP15:%.*]] = fadd <4 x float> [[TMP13]], [[TMP14]]
// CHECK-STRICT-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-STRICT-NEXT:    store <4 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-STRICT-NEXT:    ret void
//
// CHECK-STRICT-FAST-LABEL: define dso_local void @my_m22_muladd(
// CHECK-STRICT-FAST-SAME: <4 x float> noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], <4 x float> noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-STRICT-FAST-NEXT:    [[TMP5:%.*]] = alloca [4 x float], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP7:%.*]] = alloca [4 x float], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-STRICT-FAST-NEXT:    store <4 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-STRICT-FAST-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-STRICT-FAST-NEXT:    store <4 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-STRICT-FAST-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-STRICT-FAST-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr [[TMP5]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP11:%.*]] = insertelement <4 x float> poison, float [[TMP10]], i64 0
// CHECK-STRICT-FAST-NEXT:    [[TMP12:%.*]] = shufflevector <4 x float> [[TMP11]], <4 x float> poison, <4 x i32> zeroinitializer
// CHECK-STRICT-FAST-NEXT:    [[TMP13:%.*]] = fmul fast <4 x float> [[TMP9]], [[TMP12]]
// CHECK-STRICT-FAST-NEXT:    [[TMP14:%.*]] = load <4 x float>, ptr [[TMP7]], align 4
// CHECK-STRICT-FAST-NEXT:    [[TMP15:%.*]] = fadd fast <4 x float> [[TMP13]], [[TMP14]]
// CHECK-STRICT-FAST-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-STRICT-FAST-NEXT:    store <4 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-STRICT-FAST-NEXT:    ret void
//
// CHECK-FAST1-LABEL: define dso_local void @my_m22_muladd(
// CHECK-FAST1-SAME: <4 x float> noundef nofpclass(nan inf) [[TMP0:%.*]], float noundef nofpclass(nan inf) [[TMP1:%.*]], <4 x float> noundef nofpclass(nan inf) [[TMP2:%.*]], ptr noundef [[TMP3:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-FAST1-NEXT:    [[TMP5:%.*]] = alloca [4 x float], align 4
// CHECK-FAST1-NEXT:    [[TMP6:%.*]] = alloca float, align 4
// CHECK-FAST1-NEXT:    [[TMP7:%.*]] = alloca [4 x float], align 4
// CHECK-FAST1-NEXT:    [[TMP8:%.*]] = alloca ptr, align 8
// CHECK-FAST1-NEXT:    store <4 x float> [[TMP0]], ptr [[TMP5]], align 4
// CHECK-FAST1-NEXT:    store float [[TMP1]], ptr [[TMP6]], align 4
// CHECK-FAST1-NEXT:    store <4 x float> [[TMP2]], ptr [[TMP7]], align 4
// CHECK-FAST1-NEXT:    store ptr [[TMP3]], ptr [[TMP8]], align 8
// CHECK-FAST1-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr [[TMP5]], align 4
// CHECK-FAST1-NEXT:    [[TMP10:%.*]] = load float, ptr [[TMP6]], align 4
// CHECK-FAST1-NEXT:    [[TMP11:%.*]] = insertelement <4 x float> poison, float [[TMP10]], i64 0
// CHECK-FAST1-NEXT:    [[TMP12:%.*]] = shufflevector <4 x float> [[TMP11]], <4 x float> poison, <4 x i32> zeroinitializer
// CHECK-FAST1-NEXT:    [[TMP13:%.*]] = fmul fast <4 x float> [[TMP9]], [[TMP12]]
// CHECK-FAST1-NEXT:    [[TMP14:%.*]] = load <4 x float>, ptr [[TMP7]], align 4
// CHECK-FAST1-NEXT:    [[TMP15:%.*]] = fadd fast <4 x float> [[TMP13]], [[TMP14]]
// CHECK-FAST1-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP8]], align 8
// CHECK-FAST1-NEXT:    store <4 x float> [[TMP15]], ptr [[TMP16]], align 4
// CHECK-FAST1-NEXT:    ret void
//
void my_m22_muladd(m22f x, float y, m22f z, m22f *res) {
  *res = x * y + z;






}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
