// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -O2 %s -emit-llvm -o - | FileCheck %s --check-prefixes=CHECK,CHECK-NOPRAGMA-NOFLAG
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -O2 -force-unroll-pragma %s -emit-llvm -o - | FileCheck %s --check-prefixes=CHECK,CHECK-NOPRAGMA-FLAG
// RUN: %clang_cc1 -DPRAGMA_UNROLL -triple x86_64-unknown-linux-gnu -O2 %s -emit-llvm -o - | FileCheck %s --check-prefixes=CHECK,CHECK-PRAGMA-NOFLAG
// RUN: %clang_cc1 -DPRAGMA_UNROLL -triple x86_64-unknown-linux-gnu -O2 -force-unroll-pragma %s -emit-llvm -o - | FileCheck %s --check-prefixes=CHECK,CHECK-PRAGMA-FLAG

const int output_vec_size = 4;
struct ArgVec {
  float v[output_vec_size];
};

// CHECK-LABEL: define dso_local i32 @calc_offset(
// CHECK-SAME: i32 noundef [[INPUT_OFFSET:%.*]], i32 noundef [[OFF1:%.*]], i32 noundef [[OFF2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[OFF1]], [[INPUT_OFFSET]]
// CHECK-NEXT:    [[ADD1:%.*]] = add nsw i32 [[ADD]], [[OFF2]]
// CHECK-NEXT:    ret i32 [[ADD1]]
//
int calc_offset(int input_offset, int off1, int off2) {
  return input_offset + off1 + off2;
}


// CHECK-NOPRAGMA-NOFLAG-LABEL: define dso_local void @complex_loop(
// CHECK-NOPRAGMA-NOFLAG-SAME: i32 noundef [[INPUT_OFFSET:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[N:%.*]], i32 noundef [[OFF1:%.*]], i32 noundef [[OFF2:%.*]], ptr noundef readonly captures(none) [[REDUCE_BUFFER:%.*]], ptr noundef captures(none) [[VALUE:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NOPRAGMA-NOFLAG-NEXT:  [[ENTRY:.*:]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[CMP23:%.*]] = icmp slt i32 [[INPUT_OFFSET]], [[N]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    br i1 [[CMP23]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_END14:.*]]
// CHECK-NOPRAGMA-NOFLAG:       [[FOR_BODY_LR_PH]]:
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ADD_I:%.*]] = add i32 [[OFF2]], [[OFF1]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP0:%.*]] = sext i32 [[INPUT_OFFSET]] to i64
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP1:%.*]] = sext i32 [[STEP]] to i64
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP2:%.*]] = sext i32 [[N]] to i64
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[DOTPRE:%.*]] = load float, ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6:![0-9]+]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ARRAYIDX5_1_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 4
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[DOTPRE27:%.*]] = load float, ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ARRAYIDX5_2_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 8
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[DOTPRE28:%.*]] = load float, ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ARRAYIDX5_3_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 12
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[DOTPRE29:%.*]] = load float, ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    br label %[[FOR_BODY:.*]]
// CHECK-NOPRAGMA-NOFLAG:       [[FOR_BODY]]:
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP3:%.*]] = phi float [ [[DOTPRE29]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_3:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP4:%.*]] = phi float [ [[DOTPRE28]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_2:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP5:%.*]] = phi float [ [[DOTPRE27]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_1:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP6:%.*]] = phi float [ [[DOTPRE]], %[[FOR_BODY_LR_PH]] ], [ [[ADD:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[TMP0]], %[[FOR_BODY_LR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[TMP7:%.*]] = trunc nsw i64 [[INDVARS_IV]] to i32
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ADD1_I:%.*]] = add i32 [[ADD_I]], [[TMP7]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[IDXPROM:%.*]] = sext i32 [[ADD1_I]] to i64
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC:%.*]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD:%.*]] = load float, ptr [[ARRAYIDX]], align 4
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 4
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 8
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 12
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX]], align 4, !tbaa [[CHAR_TBAA8:![0-9]+]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ADD]] = fadd float [[TMP6]], [[NEXT_SROA_0_0_COPYLOAD]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    store float [[ADD]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ADD_1]] = fadd float [[TMP5]], [[NEXT_SROA_4_0_COPYLOAD]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    store float [[ADD_1]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ADD_2]] = fadd float [[TMP4]], [[NEXT_SROA_5_0_COPYLOAD]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    store float [[ADD_2]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[ADD_3]] = fadd float [[TMP3]], [[NEXT_SROA_6_0_COPYLOAD]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    store float [[ADD_3]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], [[TMP1]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    [[CMP:%.*]] = icmp slt i64 [[INDVARS_IV_NEXT]], [[TMP2]]
// CHECK-NOPRAGMA-NOFLAG-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END14]], !llvm.loop [[LOOP9:![0-9]+]]
// CHECK-NOPRAGMA-NOFLAG:       [[FOR_END14]]:
// CHECK-NOPRAGMA-NOFLAG-NEXT:    ret void
//
// CHECK-NOPRAGMA-FLAG-LABEL: define dso_local void @complex_loop(
// CHECK-NOPRAGMA-FLAG-SAME: i32 noundef [[INPUT_OFFSET:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[N:%.*]], i32 noundef [[OFF1:%.*]], i32 noundef [[OFF2:%.*]], ptr noundef readonly captures(none) [[REDUCE_BUFFER:%.*]], ptr noundef captures(none) [[VALUE:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NOPRAGMA-FLAG-NEXT:  [[ENTRY:.*:]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[CMP23:%.*]] = icmp slt i32 [[INPUT_OFFSET]], [[N]]
// CHECK-NOPRAGMA-FLAG-NEXT:    br i1 [[CMP23]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_END14:.*]]
// CHECK-NOPRAGMA-FLAG:       [[FOR_BODY_LR_PH]]:
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ADD_I:%.*]] = add i32 [[OFF2]], [[OFF1]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP0:%.*]] = sext i32 [[INPUT_OFFSET]] to i64
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP1:%.*]] = sext i32 [[STEP]] to i64
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP2:%.*]] = sext i32 [[N]] to i64
// CHECK-NOPRAGMA-FLAG-NEXT:    [[DOTPRE:%.*]] = load float, ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6:![0-9]+]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ARRAYIDX5_1_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 4
// CHECK-NOPRAGMA-FLAG-NEXT:    [[DOTPRE27:%.*]] = load float, ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ARRAYIDX5_2_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 8
// CHECK-NOPRAGMA-FLAG-NEXT:    [[DOTPRE28:%.*]] = load float, ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ARRAYIDX5_3_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 12
// CHECK-NOPRAGMA-FLAG-NEXT:    [[DOTPRE29:%.*]] = load float, ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-FLAG-NEXT:    br label %[[FOR_BODY:.*]]
// CHECK-NOPRAGMA-FLAG:       [[FOR_BODY]]:
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP3:%.*]] = phi float [ [[DOTPRE29]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_3:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP4:%.*]] = phi float [ [[DOTPRE28]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_2:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP5:%.*]] = phi float [ [[DOTPRE27]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_1:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP6:%.*]] = phi float [ [[DOTPRE]], %[[FOR_BODY_LR_PH]] ], [ [[ADD:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[TMP0]], %[[FOR_BODY_LR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[TMP7:%.*]] = trunc nsw i64 [[INDVARS_IV]] to i32
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ADD1_I:%.*]] = add i32 [[ADD_I]], [[TMP7]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[IDXPROM:%.*]] = sext i32 [[ADD1_I]] to i64
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC:%.*]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD:%.*]] = load float, ptr [[ARRAYIDX]], align 4
// CHECK-NOPRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 4
// CHECK-NOPRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-NOPRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 8
// CHECK-NOPRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-NOPRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 12
// CHECK-NOPRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX]], align 4, !tbaa [[CHAR_TBAA8:![0-9]+]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ADD]] = fadd float [[TMP6]], [[NEXT_SROA_0_0_COPYLOAD]]
// CHECK-NOPRAGMA-FLAG-NEXT:    store float [[ADD]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ADD_1]] = fadd float [[TMP5]], [[NEXT_SROA_4_0_COPYLOAD]]
// CHECK-NOPRAGMA-FLAG-NEXT:    store float [[ADD_1]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ADD_2]] = fadd float [[TMP4]], [[NEXT_SROA_5_0_COPYLOAD]]
// CHECK-NOPRAGMA-FLAG-NEXT:    store float [[ADD_2]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[ADD_3]] = fadd float [[TMP3]], [[NEXT_SROA_6_0_COPYLOAD]]
// CHECK-NOPRAGMA-FLAG-NEXT:    store float [[ADD_3]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], [[TMP1]]
// CHECK-NOPRAGMA-FLAG-NEXT:    [[CMP:%.*]] = icmp slt i64 [[INDVARS_IV_NEXT]], [[TMP2]]
// CHECK-NOPRAGMA-FLAG-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END14]], !llvm.loop [[LOOP9:![0-9]+]]
// CHECK-NOPRAGMA-FLAG:       [[FOR_END14]]:
// CHECK-NOPRAGMA-FLAG-NEXT:    ret void
//
// CHECK-PRAGMA-NOFLAG-LABEL: define dso_local void @complex_loop(
// CHECK-PRAGMA-NOFLAG-SAME: i32 noundef [[INPUT_OFFSET:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[N:%.*]], i32 noundef [[OFF1:%.*]], i32 noundef [[OFF2:%.*]], ptr noundef readonly captures(none) [[REDUCE_BUFFER:%.*]], ptr noundef captures(none) [[VALUE:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-PRAGMA-NOFLAG-NEXT:  [[ENTRY:.*:]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[CMP23:%.*]] = icmp slt i32 [[INPUT_OFFSET]], [[N]]
// CHECK-PRAGMA-NOFLAG-NEXT:    br i1 [[CMP23]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_END14:.*]]
// CHECK-PRAGMA-NOFLAG:       [[FOR_BODY_LR_PH]]:
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ADD_I:%.*]] = add i32 [[OFF2]], [[OFF1]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP0:%.*]] = sext i32 [[INPUT_OFFSET]] to i64
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP1:%.*]] = sext i32 [[STEP]] to i64
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP2:%.*]] = sext i32 [[N]] to i64
// CHECK-PRAGMA-NOFLAG-NEXT:    [[DOTPRE:%.*]] = load float, ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6:![0-9]+]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ARRAYIDX5_1_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 4
// CHECK-PRAGMA-NOFLAG-NEXT:    [[DOTPRE27:%.*]] = load float, ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ARRAYIDX5_2_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 8
// CHECK-PRAGMA-NOFLAG-NEXT:    [[DOTPRE28:%.*]] = load float, ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ARRAYIDX5_3_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 12
// CHECK-PRAGMA-NOFLAG-NEXT:    [[DOTPRE29:%.*]] = load float, ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-NOFLAG-NEXT:    br label %[[FOR_BODY:.*]]
// CHECK-PRAGMA-NOFLAG:       [[FOR_BODY]]:
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP3:%.*]] = phi float [ [[DOTPRE29]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_3:%.*]], %[[FOR_BODY]] ]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP4:%.*]] = phi float [ [[DOTPRE28]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_2:%.*]], %[[FOR_BODY]] ]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP5:%.*]] = phi float [ [[DOTPRE27]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_1:%.*]], %[[FOR_BODY]] ]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP6:%.*]] = phi float [ [[DOTPRE]], %[[FOR_BODY_LR_PH]] ], [ [[ADD:%.*]], %[[FOR_BODY]] ]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[TMP0]], %[[FOR_BODY_LR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[FOR_BODY]] ]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[TMP7:%.*]] = trunc nsw i64 [[INDVARS_IV]] to i32
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ADD1_I:%.*]] = add i32 [[ADD_I]], [[TMP7]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[IDXPROM:%.*]] = sext i32 [[ADD1_I]] to i64
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC:%.*]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD:%.*]] = load float, ptr [[ARRAYIDX]], align 4
// CHECK-PRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 4
// CHECK-PRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-PRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 8
// CHECK-PRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-PRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 12
// CHECK-PRAGMA-NOFLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX]], align 4, !tbaa [[CHAR_TBAA8:![0-9]+]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ADD]] = fadd float [[TMP6]], [[NEXT_SROA_0_0_COPYLOAD]]
// CHECK-PRAGMA-NOFLAG-NEXT:    store float [[ADD]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ADD_1]] = fadd float [[TMP5]], [[NEXT_SROA_4_0_COPYLOAD]]
// CHECK-PRAGMA-NOFLAG-NEXT:    store float [[ADD_1]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ADD_2]] = fadd float [[TMP4]], [[NEXT_SROA_5_0_COPYLOAD]]
// CHECK-PRAGMA-NOFLAG-NEXT:    store float [[ADD_2]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[ADD_3]] = fadd float [[TMP3]], [[NEXT_SROA_6_0_COPYLOAD]]
// CHECK-PRAGMA-NOFLAG-NEXT:    store float [[ADD_3]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[INDVARS_IV_NEXT]] = add nsw i64 [[INDVARS_IV]], [[TMP1]]
// CHECK-PRAGMA-NOFLAG-NEXT:    [[CMP:%.*]] = icmp slt i64 [[INDVARS_IV_NEXT]], [[TMP2]]
// CHECK-PRAGMA-NOFLAG-NEXT:    br i1 [[CMP]], label %[[FOR_BODY]], label %[[FOR_END14]], !llvm.loop [[LOOP9:![0-9]+]]
// CHECK-PRAGMA-NOFLAG:       [[FOR_END14]]:
// CHECK-PRAGMA-NOFLAG-NEXT:    ret void
//
// CHECK-PRAGMA-FLAG-LABEL: define dso_local void @complex_loop(
// CHECK-PRAGMA-FLAG-SAME: i32 noundef [[INPUT_OFFSET:%.*]], i32 noundef [[STEP:%.*]], i32 noundef [[N:%.*]], i32 noundef [[OFF1:%.*]], i32 noundef [[OFF2:%.*]], ptr noundef readonly captures(none) [[REDUCE_BUFFER:%.*]], ptr noundef captures(none) [[VALUE:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-PRAGMA-FLAG-NEXT:  [[ENTRY:.*:]]
// CHECK-PRAGMA-FLAG-NEXT:    [[CMP23:%.*]] = icmp slt i32 [[INPUT_OFFSET]], [[N]]
// CHECK-PRAGMA-FLAG-NEXT:    br i1 [[CMP23]], label %[[FOR_BODY_LR_PH:.*]], label %[[FOR_END14:.*]]
// CHECK-PRAGMA-FLAG:       [[FOR_BODY_LR_PH]]:
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_I:%.*]] = add i32 [[OFF2]], [[OFF1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP0:%.*]] = sext i32 [[INPUT_OFFSET]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP1:%.*]] = sext i32 [[STEP]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP2:%.*]] = sext i32 [[N]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTPRE:%.*]] = load float, ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6:![0-9]+]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX5_1_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTPRE27:%.*]] = load float, ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX5_2_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTPRE28:%.*]] = load float, ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX5_3_PHI_TRANS_INSERT:%.*]] = getelementptr inbounds nuw i8, ptr [[VALUE]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTPRE29:%.*]] = load float, ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP3:%.*]] = add nsw i64 [[TMP1]], [[TMP0]]
// CHECK-PRAGMA-FLAG-NEXT:    [[SMAX:%.*]] = tail call i64 @llvm.smax.i64(i64 [[TMP3]], i64 [[TMP2]])
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP4:%.*]] = icmp slt i64 [[TMP3]], [[TMP2]]
// CHECK-PRAGMA-FLAG-NEXT:    [[UMIN:%.*]] = zext i1 [[TMP4]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP5:%.*]] = add nsw i64 [[TMP3]], [[UMIN]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP6:%.*]] = sub i64 [[SMAX]], [[TMP5]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP7:%.*]] = udiv i64 [[TMP6]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP8:%.*]] = add i64 [[TMP7]], [[UMIN]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP9:%.*]] = add i64 [[TMP8]], 1
// CHECK-PRAGMA-FLAG-NEXT:    [[XTRAITER:%.*]] = and i64 [[TMP9]], 7
// CHECK-PRAGMA-FLAG-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0
// CHECK-PRAGMA-FLAG-NEXT:    br i1 [[LCMP_MOD_NOT]], label %[[FOR_BODY_PROL_LOOPEXIT:.*]], label %[[FOR_BODY_PROL:.*]]
// CHECK-PRAGMA-FLAG:       [[FOR_BODY_PROL]]:
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP10:%.*]] = phi float [ [[ADD_3_PROL:%.*]], %[[FOR_BODY_PROL]] ], [ [[DOTPRE29]], %[[FOR_BODY_LR_PH]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP11:%.*]] = phi float [ [[ADD_2_PROL:%.*]], %[[FOR_BODY_PROL]] ], [ [[DOTPRE28]], %[[FOR_BODY_LR_PH]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP12:%.*]] = phi float [ [[ADD_1_PROL:%.*]], %[[FOR_BODY_PROL]] ], [ [[DOTPRE27]], %[[FOR_BODY_LR_PH]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP13:%.*]] = phi float [ [[ADD_PROL:%.*]], %[[FOR_BODY_PROL]] ], [ [[DOTPRE]], %[[FOR_BODY_LR_PH]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_PROL:%.*]] = phi i64 [ [[INDVARS_IV_NEXT_PROL:%.*]], %[[FOR_BODY_PROL]] ], [ [[TMP0]], %[[FOR_BODY_LR_PH]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[PROL_ITER:%.*]] = phi i64 [ [[PROL_ITER_NEXT:%.*]], %[[FOR_BODY_PROL]] ], [ 0, %[[FOR_BODY_LR_PH]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP14:%.*]] = trunc nsw i64 [[INDVARS_IV_PROL]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_PROL:%.*]] = add i32 [[ADD_I]], [[TMP14]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_PROL:%.*]] = sext i32 [[ADD1_I_PROL]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_PROL:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC:%.*]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_PROL]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_PROL:%.*]] = load float, ptr [[ARRAYIDX_PROL]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_PROL:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_PROL]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_PROL:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_PROL]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_PROL:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_PROL]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_PROL:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_PROL]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_PROL:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_PROL]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_PROL:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_PROL]], align 4, !tbaa [[CHAR_TBAA8:![0-9]+]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_PROL]] = fadd float [[TMP13]], [[NEXT_SROA_0_0_COPYLOAD_PROL]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_PROL]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_PROL]] = fadd float [[TMP12]], [[NEXT_SROA_4_0_COPYLOAD_PROL]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_PROL]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_PROL]] = fadd float [[TMP11]], [[NEXT_SROA_5_0_COPYLOAD_PROL]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_PROL]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_PROL]] = fadd float [[TMP10]], [[NEXT_SROA_6_0_COPYLOAD_PROL]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_PROL]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_PROL]] = add nsw i64 [[INDVARS_IV_PROL]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[PROL_ITER_NEXT]] = add i64 [[PROL_ITER]], 1
// CHECK-PRAGMA-FLAG-NEXT:    [[PROL_ITER_CMP_NOT:%.*]] = icmp eq i64 [[PROL_ITER_NEXT]], [[XTRAITER]]
// CHECK-PRAGMA-FLAG-NEXT:    br i1 [[PROL_ITER_CMP_NOT]], label %[[FOR_BODY_PROL_LOOPEXIT]], label %[[FOR_BODY_PROL]], !llvm.loop [[LOOP9:![0-9]+]]
// CHECK-PRAGMA-FLAG:       [[FOR_BODY_PROL_LOOPEXIT]]:
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTUNR:%.*]] = phi float [ [[DOTPRE29]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_3_PROL]], %[[FOR_BODY_PROL]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTUNR30:%.*]] = phi float [ [[DOTPRE28]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_2_PROL]], %[[FOR_BODY_PROL]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTUNR31:%.*]] = phi float [ [[DOTPRE27]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_1_PROL]], %[[FOR_BODY_PROL]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[DOTUNR32:%.*]] = phi float [ [[DOTPRE]], %[[FOR_BODY_LR_PH]] ], [ [[ADD_PROL]], %[[FOR_BODY_PROL]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_UNR:%.*]] = phi i64 [ [[TMP0]], %[[FOR_BODY_LR_PH]] ], [ [[INDVARS_IV_NEXT_PROL]], %[[FOR_BODY_PROL]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP15:%.*]] = icmp ult i64 [[TMP8]], 7
// CHECK-PRAGMA-FLAG-NEXT:    br i1 [[TMP15]], label %[[FOR_END14]], label %[[FOR_BODY:.*]]
// CHECK-PRAGMA-FLAG:       [[FOR_BODY]]:
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP16:%.*]] = phi float [ [[ADD_3_7:%.*]], %[[FOR_BODY]] ], [ [[DOTUNR]], %[[FOR_BODY_PROL_LOOPEXIT]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP17:%.*]] = phi float [ [[ADD_2_7:%.*]], %[[FOR_BODY]] ], [ [[DOTUNR30]], %[[FOR_BODY_PROL_LOOPEXIT]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP18:%.*]] = phi float [ [[ADD_1_7:%.*]], %[[FOR_BODY]] ], [ [[DOTUNR31]], %[[FOR_BODY_PROL_LOOPEXIT]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP19:%.*]] = phi float [ [[ADD_7:%.*]], %[[FOR_BODY]] ], [ [[DOTUNR32]], %[[FOR_BODY_PROL_LOOPEXIT]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT_7:%.*]], %[[FOR_BODY]] ], [ [[INDVARS_IV_UNR]], %[[FOR_BODY_PROL_LOOPEXIT]] ]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP20:%.*]] = trunc nsw i64 [[INDVARS_IV]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I:%.*]] = add i32 [[ADD_I]], [[TMP20]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM:%.*]] = sext i32 [[ADD1_I]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD:%.*]] = load float, ptr [[ARRAYIDX]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD:%.*]] = fadd float [[TMP19]], [[NEXT_SROA_0_0_COPYLOAD]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1:%.*]] = fadd float [[TMP18]], [[NEXT_SROA_4_0_COPYLOAD]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2:%.*]] = fadd float [[TMP17]], [[NEXT_SROA_5_0_COPYLOAD]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3:%.*]] = fadd float [[TMP16]], [[NEXT_SROA_6_0_COPYLOAD]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT:%.*]] = add nsw i64 [[INDVARS_IV]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP21:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_1:%.*]] = add i32 [[ADD_I]], [[TMP21]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_1:%.*]] = sext i32 [[ADD1_I_1]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_1:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_1:%.*]] = load float, ptr [[ARRAYIDX_1]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_1]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_1:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_1]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_1]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_1:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_1]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_1:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_1]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_1:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_1]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_133:%.*]] = fadd float [[ADD]], [[NEXT_SROA_0_0_COPYLOAD_1]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_133]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_1:%.*]] = fadd float [[ADD_1]], [[NEXT_SROA_4_0_COPYLOAD_1]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_1]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_1:%.*]] = fadd float [[ADD_2]], [[NEXT_SROA_5_0_COPYLOAD_1]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_1]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_1:%.*]] = fadd float [[ADD_3]], [[NEXT_SROA_6_0_COPYLOAD_1]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_1]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_1:%.*]] = add nsw i64 [[INDVARS_IV_NEXT]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP22:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT_1]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_2:%.*]] = add i32 [[ADD_I]], [[TMP22]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_2:%.*]] = sext i32 [[ADD1_I_2]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_2:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_2]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_2:%.*]] = load float, ptr [[ARRAYIDX_2]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_2:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_2]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_2:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_2]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_2:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_2]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_2:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_2]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_2:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_2]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_2:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_2]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_234:%.*]] = fadd float [[ADD_133]], [[NEXT_SROA_0_0_COPYLOAD_2]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_234]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_2:%.*]] = fadd float [[ADD_1_1]], [[NEXT_SROA_4_0_COPYLOAD_2]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_2]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_2:%.*]] = fadd float [[ADD_2_1]], [[NEXT_SROA_5_0_COPYLOAD_2]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_2]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_2:%.*]] = fadd float [[ADD_3_1]], [[NEXT_SROA_6_0_COPYLOAD_2]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_2]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_2:%.*]] = add nsw i64 [[INDVARS_IV_NEXT_1]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP23:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT_2]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_3:%.*]] = add i32 [[ADD_I]], [[TMP23]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_3:%.*]] = sext i32 [[ADD1_I_3]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_3:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_3]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_3:%.*]] = load float, ptr [[ARRAYIDX_3]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_3]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_3:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_3]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_3]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_3:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_3]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_3]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_3:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_3]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_335:%.*]] = fadd float [[ADD_234]], [[NEXT_SROA_0_0_COPYLOAD_3]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_335]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_3:%.*]] = fadd float [[ADD_1_2]], [[NEXT_SROA_4_0_COPYLOAD_3]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_3]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_3:%.*]] = fadd float [[ADD_2_2]], [[NEXT_SROA_5_0_COPYLOAD_3]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_3]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_3:%.*]] = fadd float [[ADD_3_2]], [[NEXT_SROA_6_0_COPYLOAD_3]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_3]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_3:%.*]] = add nsw i64 [[INDVARS_IV_NEXT_2]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP24:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT_3]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_4:%.*]] = add i32 [[ADD_I]], [[TMP24]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_4:%.*]] = sext i32 [[ADD1_I_4]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_4:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_4]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_4:%.*]] = load float, ptr [[ARRAYIDX_4]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_4:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_4]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_4:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_4]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_4:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_4]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_4:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_4]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_4:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_4]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_4:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_4]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_4:%.*]] = fadd float [[ADD_335]], [[NEXT_SROA_0_0_COPYLOAD_4]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_4]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_4:%.*]] = fadd float [[ADD_1_3]], [[NEXT_SROA_4_0_COPYLOAD_4]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_4]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_4:%.*]] = fadd float [[ADD_2_3]], [[NEXT_SROA_5_0_COPYLOAD_4]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_4]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_4:%.*]] = fadd float [[ADD_3_3]], [[NEXT_SROA_6_0_COPYLOAD_4]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_4]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_4:%.*]] = add nsw i64 [[INDVARS_IV_NEXT_3]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP25:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT_4]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_5:%.*]] = add i32 [[ADD_I]], [[TMP25]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_5:%.*]] = sext i32 [[ADD1_I_5]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_5:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_5]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_5:%.*]] = load float, ptr [[ARRAYIDX_5]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_5:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_5]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_5:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_5]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_5:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_5]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_5:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_5]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_5:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_5]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_5:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_5]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_5:%.*]] = fadd float [[ADD_4]], [[NEXT_SROA_0_0_COPYLOAD_5]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_5]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_5:%.*]] = fadd float [[ADD_1_4]], [[NEXT_SROA_4_0_COPYLOAD_5]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_5]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_5:%.*]] = fadd float [[ADD_2_4]], [[NEXT_SROA_5_0_COPYLOAD_5]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_5]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_5:%.*]] = fadd float [[ADD_3_4]], [[NEXT_SROA_6_0_COPYLOAD_5]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_5]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_5:%.*]] = add nsw i64 [[INDVARS_IV_NEXT_4]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP26:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT_5]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_6:%.*]] = add i32 [[ADD_I]], [[TMP26]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_6:%.*]] = sext i32 [[ADD1_I_6]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_6:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_6:%.*]] = load float, ptr [[ARRAYIDX_6]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_6:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_6]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_6:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_6]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_6:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_6]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_6:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_6]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_6:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_6]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_6:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_6]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_6:%.*]] = fadd float [[ADD_5]], [[NEXT_SROA_0_0_COPYLOAD_6]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_6]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_6:%.*]] = fadd float [[ADD_1_5]], [[NEXT_SROA_4_0_COPYLOAD_6]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_6]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_6:%.*]] = fadd float [[ADD_2_5]], [[NEXT_SROA_5_0_COPYLOAD_6]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_6]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_6:%.*]] = fadd float [[ADD_3_5]], [[NEXT_SROA_6_0_COPYLOAD_6]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_6]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_6:%.*]] = add nsw i64 [[INDVARS_IV_NEXT_5]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[TMP27:%.*]] = trunc nsw i64 [[INDVARS_IV_NEXT_6]] to i32
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD1_I_7:%.*]] = add i32 [[ADD_I]], [[TMP27]]
// CHECK-PRAGMA-FLAG-NEXT:    [[IDXPROM_7:%.*]] = sext i32 [[ADD1_I_7]] to i64
// CHECK-PRAGMA-FLAG-NEXT:    [[ARRAYIDX_7:%.*]] = getelementptr inbounds [[STRUCT_ARGVEC]], ptr [[REDUCE_BUFFER]], i64 [[IDXPROM_7]]
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_0_0_COPYLOAD_7:%.*]] = load float, ptr [[ARRAYIDX_7]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_7:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_7]], i64 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_4_0_COPYLOAD_7:%.*]] = load float, ptr [[NEXT_SROA_4_0_ARRAYIDX_SROA_IDX_7]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_7:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_7]], i64 8
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_5_0_COPYLOAD_7:%.*]] = load float, ptr [[NEXT_SROA_5_0_ARRAYIDX_SROA_IDX_7]], align 4
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_7:%.*]] = getelementptr inbounds nuw i8, ptr [[ARRAYIDX_7]], i64 12
// CHECK-PRAGMA-FLAG-NEXT:    [[NEXT_SROA_6_0_COPYLOAD_7:%.*]] = load float, ptr [[NEXT_SROA_6_0_ARRAYIDX_SROA_IDX_7]], align 4, !tbaa [[CHAR_TBAA8]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_7]] = fadd float [[ADD_6]], [[NEXT_SROA_0_0_COPYLOAD_7]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_7]], ptr [[VALUE]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_1_7]] = fadd float [[ADD_1_6]], [[NEXT_SROA_4_0_COPYLOAD_7]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_1_7]], ptr [[ARRAYIDX5_1_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_2_7]] = fadd float [[ADD_2_6]], [[NEXT_SROA_5_0_COPYLOAD_7]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_2_7]], ptr [[ARRAYIDX5_2_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[ADD_3_7]] = fadd float [[ADD_3_6]], [[NEXT_SROA_6_0_COPYLOAD_7]]
// CHECK-PRAGMA-FLAG-NEXT:    store float [[ADD_3_7]], ptr [[ARRAYIDX5_3_PHI_TRANS_INSERT]], align 4, !tbaa [[FLOAT_TBAA6]]
// CHECK-PRAGMA-FLAG-NEXT:    [[INDVARS_IV_NEXT_7]] = add nsw i64 [[INDVARS_IV_NEXT_6]], [[TMP1]]
// CHECK-PRAGMA-FLAG-NEXT:    [[CMP_7:%.*]] = icmp slt i64 [[INDVARS_IV_NEXT_7]], [[TMP2]]
// CHECK-PRAGMA-FLAG-NEXT:    br i1 [[CMP_7]], label %[[FOR_BODY]], label %[[FOR_END14]], !llvm.loop [[LOOP11:![0-9]+]]
// CHECK-PRAGMA-FLAG:       [[FOR_END14]]:
// CHECK-PRAGMA-FLAG-NEXT:    ret void
//
void complex_loop(int input_offset, int step, int n, int off1, int off2, const struct ArgVec* reduce_buffer, struct ArgVec* value) {
#ifdef PRAGMA_UNROLL
  #pragma unroll
#endif
  for (; input_offset < n; input_offset += step) {
    int idx = calc_offset(input_offset, off1, off2);
    struct ArgVec next = reduce_buffer[idx];
    #pragma unroll
    for (int i = 0; i < output_vec_size; i++) {
      value->v[i] = value->v[i] + next.v[i];
    }
  }
}

//.
// CHECK-NOPRAGMA-NOFLAG: [[META4:![0-9]+]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK-NOPRAGMA-NOFLAG: [[META5]] = !{!"Simple C/C++ TBAA"}
// CHECK-NOPRAGMA-NOFLAG: [[FLOAT_TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// CHECK-NOPRAGMA-NOFLAG: [[META7]] = !{!"float", [[META4]], i64 0}
// CHECK-NOPRAGMA-NOFLAG: [[CHAR_TBAA8]] = !{[[META4]], [[META4]], i64 0}
// CHECK-NOPRAGMA-NOFLAG: [[LOOP9]] = distinct !{[[LOOP9]], [[META10:![0-9]+]]}
// CHECK-NOPRAGMA-NOFLAG: [[META10]] = !{!"llvm.loop.mustprogress"}
//.
// CHECK-NOPRAGMA-FLAG: [[META4:![0-9]+]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK-NOPRAGMA-FLAG: [[META5]] = !{!"Simple C/C++ TBAA"}
// CHECK-NOPRAGMA-FLAG: [[FLOAT_TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// CHECK-NOPRAGMA-FLAG: [[META7]] = !{!"float", [[META4]], i64 0}
// CHECK-NOPRAGMA-FLAG: [[CHAR_TBAA8]] = !{[[META4]], [[META4]], i64 0}
// CHECK-NOPRAGMA-FLAG: [[LOOP9]] = distinct !{[[LOOP9]], [[META10:![0-9]+]]}
// CHECK-NOPRAGMA-FLAG: [[META10]] = !{!"llvm.loop.mustprogress"}
//.
// CHECK-PRAGMA-NOFLAG: [[META4:![0-9]+]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK-PRAGMA-NOFLAG: [[META5]] = !{!"Simple C/C++ TBAA"}
// CHECK-PRAGMA-NOFLAG: [[FLOAT_TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// CHECK-PRAGMA-NOFLAG: [[META7]] = !{!"float", [[META4]], i64 0}
// CHECK-PRAGMA-NOFLAG: [[CHAR_TBAA8]] = !{[[META4]], [[META4]], i64 0}
// CHECK-PRAGMA-NOFLAG: [[LOOP9]] = distinct !{[[LOOP9]], [[META10:![0-9]+]], [[META11:![0-9]+]]}
// CHECK-PRAGMA-NOFLAG: [[META10]] = !{!"llvm.loop.mustprogress"}
// CHECK-PRAGMA-NOFLAG: [[META11]] = !{!"llvm.loop.unroll.enable"}
//.
// CHECK-PRAGMA-FLAG: [[META4:![0-9]+]] = !{!"omnipotent char", [[META5:![0-9]+]], i64 0}
// CHECK-PRAGMA-FLAG: [[META5]] = !{!"Simple C/C++ TBAA"}
// CHECK-PRAGMA-FLAG: [[FLOAT_TBAA6]] = !{[[META7:![0-9]+]], [[META7]], i64 0}
// CHECK-PRAGMA-FLAG: [[META7]] = !{!"float", [[META4]], i64 0}
// CHECK-PRAGMA-FLAG: [[CHAR_TBAA8]] = !{[[META4]], [[META4]], i64 0}
// CHECK-PRAGMA-FLAG: [[LOOP9]] = distinct !{[[LOOP9]], [[META10:![0-9]+]]}
// CHECK-PRAGMA-FLAG: [[META10]] = !{!"llvm.loop.unroll.disable"}
// CHECK-PRAGMA-FLAG: [[LOOP11]] = distinct !{[[LOOP11]], [[META12:![0-9]+]], [[META10]]}
// CHECK-PRAGMA-FLAG: [[META12]] = !{!"llvm.loop.mustprogress"}
//.
