// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -O3 -triple %itanium_abi_triple \
// RUN:   -emit-llvm -o - %s \
// RUN:   | FileCheck -check-prefixes=COMMON,CHECK %s
// RUN: %clang_cc1 -fexperimental-strict-floating-point \
// RUN:   -ffp-exception-behavior=strict -O3 \
// RUN:   -triple %itanium_abi_triple -emit-llvm -o - %s \
// RUN:   | FileCheck -check-prefixes=COMMON,STRICT %s

// Is FP_CONTRACT honored in a simple case?
// CHECK-LABEL: define dso_local noundef float @_Z13fp_contract_1fff(
// CHECK-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[MUL:%.*]] = fmul contract float [[A]], [[B]]
// CHECK-NEXT:    [[ADD:%.*]] = fadd contract float [[MUL]], [[C]]
// CHECK-NEXT:    ret float [[ADD]]
//
// STRICT-LABEL: define dso_local noundef float @_Z13fp_contract_1fff(
// STRICT-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[MUL:%.*]] = call contract float @llvm.fmul.f32(float [[A]], float [[B]]) #[[ATTR3:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    [[ADD:%.*]] = call contract float @llvm.fadd.f32(float [[MUL]], float [[C]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
float fp_contract_1(float a, float b, float c) {

#pragma clang fp contract(fast)
  return a * b + c;
}

// Is FP_CONTRACT state cleared on exiting compound statements?
// CHECK-LABEL: define dso_local noundef float @_Z13fp_contract_2fff(
// CHECK-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[MUL:%.*]] = fmul float [[A]], [[B]]
// CHECK-NEXT:    [[ADD:%.*]] = fadd float [[MUL]], [[C]]
// CHECK-NEXT:    ret float [[ADD]]
//
// STRICT-LABEL: define dso_local noundef float @_Z13fp_contract_2fff(
// STRICT-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[A]], float [[B]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[MUL]], float [[C]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
float fp_contract_2(float a, float b, float c) {
  {
#pragma clang fp contract(fast)
  }
  return a * b + c;
}

// Does FP_CONTRACT survive template instantiation?
class Foo {};
Foo operator+(Foo, Foo);

template <typename T>
T template_muladd(T a, T b, T c) {
#pragma clang fp contract(fast)
  return a * b + c;
}

// CHECK-LABEL: define dso_local noundef float @_Z13fp_contract_3fff(
// CHECK-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[MUL_I:%.*]] = fmul contract float [[A]], [[B]]
// CHECK-NEXT:    [[ADD_I:%.*]] = fadd contract float [[MUL_I]], [[C]]
// CHECK-NEXT:    ret float [[ADD_I]]
//
// STRICT-LABEL: define dso_local noundef float @_Z13fp_contract_3fff(
// STRICT-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[MUL_I:%.*]] = call contract float @llvm.fmul.f32(float [[A]], float [[B]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    [[ADD_I:%.*]] = call contract noundef float @llvm.fadd.f32(float [[MUL_I]], float [[C]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD_I]]
//
float fp_contract_3(float a, float b, float c) {
  return template_muladd<float>(a, b, c);
}

template <typename T>
class fp_contract_4 {
  float method(float a, float b, float c) {
#pragma clang fp contract(fast)
    return a * b + c;
  }
};

// CHECK-LABEL: define weak_odr noundef float @_ZN13fp_contract_4IiE6methodEfff(
// CHECK-SAME: ptr noundef nonnull align 1 dereferenceable(1) [[THIS:%.*]], float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] comdat align 2 {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[MUL:%.*]] = fmul contract float [[A]], [[B]]
// CHECK-NEXT:    [[ADD:%.*]] = fadd contract float [[MUL]], [[C]]
// CHECK-NEXT:    ret float [[ADD]]
//
// STRICT-LABEL: define weak_odr noundef float @_ZN13fp_contract_4IiE6methodEfff(
// STRICT-SAME: ptr noundef nonnull align 1 dereferenceable(1) [[THIS:%.*]], float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR2:[0-9]+]] comdat align 2 {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[MUL:%.*]] = call contract float @llvm.fmul.f32(float [[A]], float [[B]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    [[ADD:%.*]] = call contract float @llvm.fadd.f32(float [[MUL]], float [[C]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
template class fp_contract_4<int>;

// Check file-scoped FP_CONTRACT
#pragma clang fp contract(fast)
// CHECK-LABEL: define dso_local noundef float @_Z13fp_contract_5fff(
// CHECK-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[MUL:%.*]] = fmul contract float [[A]], [[B]]
// CHECK-NEXT:    [[ADD:%.*]] = fadd contract float [[MUL]], [[C]]
// CHECK-NEXT:    ret float [[ADD]]
//
// STRICT-LABEL: define dso_local noundef float @_Z13fp_contract_5fff(
// STRICT-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[MUL:%.*]] = call contract float @llvm.fmul.f32(float [[A]], float [[B]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    [[ADD:%.*]] = call contract float @llvm.fadd.f32(float [[MUL]], float [[C]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
float fp_contract_5(float a, float b, float c) {
  return a * b + c;
}

// Verify that we can handle multiple flags on the same pragma
#pragma clang fp contract(fast) contract(off)
// CHECK-LABEL: define dso_local noundef float @_Z13fp_contract_6fff(
// CHECK-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[MUL:%.*]] = fmul float [[A]], [[B]]
// CHECK-NEXT:    [[ADD:%.*]] = fadd float [[MUL]], [[C]]
// CHECK-NEXT:    ret float [[ADD]]
//
// STRICT-LABEL: define dso_local noundef float @_Z13fp_contract_6fff(
// STRICT-SAME: float noundef [[A:%.*]], float noundef [[B:%.*]], float noundef [[C:%.*]]) local_unnamed_addr #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[A]], float [[B]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[MUL]], float [[C]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
float fp_contract_6(float a, float b, float c) {
  return a * b + c;
}


#pragma clang fp contract(fast)
// CHECK-LABEL: define dso_local noundef float @_Z13fp_contract_7f(
// CHECK-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call contract float @llvm.sqrt.f32(float [[A]])
// CHECK-NEXT:    ret float [[TMP0]]
//
// STRICT-LABEL: define dso_local noundef float @_Z13fp_contract_7f(
// STRICT-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[TMP0:%.*]] = call contract float @llvm.sqrt.f32(float [[A]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[TMP0]]
//
float fp_contract_7(float a) {
  return __builtin_sqrtf(a);
}

// CHECK-LABEL: define dso_local noundef float @_Z13fp_contract_8f(
// CHECK-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP0:%.*]] = tail call float @llvm.sqrt.f32(float [[A]])
// CHECK-NEXT:    ret float [[TMP0]]
//
// STRICT-LABEL: define dso_local noundef float @_Z13fp_contract_8f(
// STRICT-SAME: float noundef [[A:%.*]]) local_unnamed_addr #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[TMP0:%.*]] = call float @llvm.sqrt.f32(float [[A]]) #[[ATTR3]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[TMP0]]
//
float fp_contract_8(float a) {
#pragma clang fp contract(off)
  return __builtin_sqrtf(a);
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// COMMON: {{.*}}
