// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-linux-gnu -ffp-contract=on -DDEFAULT=1 -emit-llvm -o - %s | FileCheck --check-prefix=CHECK-DDEFAULT %s
// RUN: %clang_cc1 -triple x86_64-linux-gnu -ffp-contract=on -DEBSTRICT=1 -ffp-exception-behavior=strict -emit-llvm -o - %s | FileCheck --check-prefix=CHECK-DEBSTRICT %s
// RUN: %clang_cc1 -triple x86_64-linux-gnu -DFAST=1 -ffast-math -ffp-contract=fast -emit-llvm -o - %s | FileCheck --check-prefix=CHECK-FAST %s
// RUN: %clang_cc1 -triple x86_64-linux-gnu -ffp-contract=on -DNOHONOR=1 -ffinite-math-only -menable-no-infs -menable-no-nans -emit-llvm -o - %s | FileCheck --check-prefix=CHECK-NOHONOR %s

#define FUN(n) \
  (float z) { return n * z + n; }

// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z11fun_defaultf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 1.000000e+00, float [[TMP0]], float 1.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z11fun_defaultf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[CONV:%.*]] = call float @llvm.sitofp.f32.i32(i32 1) #[[ATTR7:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[CONV1:%.*]] = call float @llvm.sitofp.f32.i32(i32 1) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float [[CONV]], float [[TMP0]], float [[CONV1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11fun_defaultf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[MUL:%.*]] = fmul fast float 1.000000e+00, [[TMP0]]
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 1.000000e+00
// CHECK-FAST-NEXT:    ret float [[ADD]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11fun_defaultf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call nnan ninf float @llvm.fmuladd.f32(float 1.000000e+00, float [[TMP0]], float 1.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
float fun_default FUN(1)
//CHECK-LABEL: define {{.*}} @_Z11fun_defaultf{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
// Note that backend wants constrained intrinsics used
// throughout the function if they are needed anywhere in the function.
// In that case, operations are built with constrained intrinsics operator
// but using default settings for exception behavior and rounding mode.
#endif
#if FAST
#endif

#pragma float_control(push)
#ifndef FAST
// Rule: precise must be enabled
#pragma float_control(except, on)
#endif
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z6exc_onf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[CONV:%.*]] = call float @llvm.sitofp.f32.i32(i32 2) #[[ATTR7:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[CONV1:%.*]] = call float @llvm.sitofp.f32.i32(i32 2) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float [[CONV]], float [[TMP0]], float [[CONV1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z6exc_onf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[CONV:%.*]] = call float @llvm.sitofp.f32.i32(i32 2) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[CONV1:%.*]] = call float @llvm.sitofp.f32.i32(i32 2) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float [[CONV]], float [[TMP0]], float [[CONV1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z6exc_onf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[MUL:%.*]] = fmul fast float 2.000000e+00, [[TMP0]]
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 2.000000e+00
// CHECK-FAST-NEXT:    ret float [[ADD]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z6exc_onf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[CONV:%.*]] = call nnan ninf float @llvm.sitofp.f32.i32(i32 2) #[[ATTR7:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[CONV1:%.*]] = call nnan ninf float @llvm.sitofp.f32.i32(i32 2) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call nnan ninf float @llvm.fmuladd.f32(float [[CONV]], float [[TMP0]], float [[CONV1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
    float exc_on FUN(2)
//CHECK-LABEL: define {{.*}} @_Z6exc_onf{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
#endif
#if FAST
//Not possible to enable float_control(except) in FAST mode.
#endif

#pragma float_control(pop)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z7exc_popf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 5.000000e+00, float [[TMP0]], float 5.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z7exc_popf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[CONV:%.*]] = call float @llvm.sitofp.f32.i32(i32 5) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[CONV1:%.*]] = call float @llvm.sitofp.f32.i32(i32 5) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float [[CONV]], float [[TMP0]], float [[CONV1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z7exc_popf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[MUL:%.*]] = fmul fast float 5.000000e+00, [[TMP0]]
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 5.000000e+00
// CHECK-FAST-NEXT:    ret float [[ADD]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z7exc_popf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call nnan ninf float @llvm.fmuladd.f32(float 5.000000e+00, float [[TMP0]], float 5.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
    float exc_pop FUN(5)
//CHECK-LABEL: define {{.*}} @_Z7exc_popf{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
#endif
#if FAST
#endif

#pragma float_control(except, off)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z7exc_offf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 5.000000e+00, float [[TMP0]], float 5.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z7exc_offf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2:[0-9]+]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 5.000000e+00, float [[TMP0]], float 5.000000e+00)
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z7exc_offf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[MUL:%.*]] = fmul fast float 5.000000e+00, [[TMP0]]
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 5.000000e+00
// CHECK-FAST-NEXT:    ret float [[ADD]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z7exc_offf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call nnan ninf float @llvm.fmuladd.f32(float 5.000000e+00, float [[TMP0]], float 5.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
        float exc_off FUN(5)
//CHECK-LABEL: define {{.*}} @_Z7exc_offf{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
#endif
#if FAST
#endif

#pragma float_control(precise, on, push)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z10precise_onf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z10precise_onf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z10precise_onf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR1:[0-9]+]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-FAST-NEXT:    ret float [[TMP1]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z10precise_onf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
            float precise_on FUN(3)
//CHECK-LABEL: define {{.*}} @_Z10precise_onf{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
// If precise is pushed then all fast-math should be off!
#endif
#if FAST
#endif

#pragma float_control(pop)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z11precise_popf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z11precise_popf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11precise_popf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[MUL:%.*]] = fmul fast float 3.000000e+00, [[TMP0]]
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 3.000000e+00
// CHECK-FAST-NEXT:    ret float [[ADD]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11precise_popf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call nnan ninf float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
                float precise_pop FUN(3)
//CHECK-LABEL: define {{.*}} @_Z11precise_popf{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
#endif
#if FAST
#endif
#pragma float_control(precise, off)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z11precise_offf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-DDEFAULT-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-DDEFAULT-NEXT:    ret float [[ADD]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z11precise_offf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-DEBSTRICT-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-DEBSTRICT-NEXT:    ret float [[ADD]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11precise_offf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-FAST-NEXT:    ret float [[ADD]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11precise_offf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-NOHONOR-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-NOHONOR-NEXT:    ret float [[ADD]]
//
                    float precise_off FUN(4)
//CHECK-LABEL: define {{.*}} @_Z11precise_offf{{.*}}
#if DEFAULT
// Note: precise_off enables fp_contract=fast and the instructions
// generated do not include the contract flag, although it was enabled
// in IRBuilder.
#endif
#if EBSTRICT
#endif
#if NOHONOR
// fast math should be enabled, and contract should be fast
#endif
#if FAST
#endif

#pragma float_control(precise, on)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z11precise_on2f(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z11precise_on2f(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11precise_on2f(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR1]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-FAST-NEXT:    ret float [[TMP1]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z11precise_on2f(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
                        float precise_on2 FUN(3)
//CHECK-LABEL: define {{.*}} @_Z11precise_on2f{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
// fast math should be off, and contract should be on
#endif
#if FAST
#endif

#pragma float_control(push)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z12precise_pushf(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z12precise_pushf(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z12precise_pushf(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR1]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-FAST-NEXT:    ret float [[TMP1]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z12precise_pushf(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
                            float precise_push FUN(3)
//CHECK-LABEL: define {{.*}} @_Z12precise_pushf{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
#endif
#if FAST
#endif

#pragma float_control(precise, off)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z12precise_off2f(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-DDEFAULT-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-DDEFAULT-NEXT:    ret float [[ADD]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z12precise_off2f(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-DEBSTRICT-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-DEBSTRICT-NEXT:    ret float [[ADD]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z12precise_off2f(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-FAST-NEXT:    ret float [[ADD]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z12precise_off2f(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[MUL:%.*]] = fmul fast float 4.000000e+00, [[TMP0]]
// CHECK-NOHONOR-NEXT:    [[ADD:%.*]] = fadd fast float [[MUL]], 4.000000e+00
// CHECK-NOHONOR-NEXT:    ret float [[ADD]]
//
                                float precise_off2 FUN(4)
//CHECK-LABEL: define {{.*}} @_Z12precise_off2f{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
// fast math settings since precise is off
#endif
#if FAST
#endif

#pragma float_control(pop)
// CHECK-DDEFAULT-LABEL: define dso_local noundef float @_Z12precise_pop2f(
// CHECK-DDEFAULT-SAME: float noundef [[Z:%.*]]) #[[ATTR0]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DDEFAULT-NEXT:    ret float [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local noundef float @_Z12precise_pop2f(
// CHECK-DEBSTRICT-SAME: float noundef [[Z:%.*]]) #[[ATTR2]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-DEBSTRICT-NEXT:    ret float [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z12precise_pop2f(
// CHECK-FAST-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR1]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-FAST-NEXT:    ret float [[TMP1]]
//
// CHECK-NOHONOR-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z12precise_pop2f(
// CHECK-NOHONOR-SAME: float noundef nofpclass(nan inf) [[Z:%.*]]) #[[ATTR0]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = call float @llvm.fmuladd.f32(float 3.000000e+00, float [[TMP0]], float 3.000000e+00)
// CHECK-NOHONOR-NEXT:    ret float [[TMP1]]
//
                                    float precise_pop2 FUN(3)
//CHECK-LABEL: define {{.*}} @_Z12precise_pop2f{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
#endif
#if FAST
#endif

#ifndef FAST
// Rule: precise must be enabled
#pragma float_control(except, on)
#endif
                                        float y();
// CHECK-DDEFAULT-LABEL: define linkonce_odr void @_ZN2ONC1Ev(
// CHECK-DDEFAULT-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR2]] comdat align 2 {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DDEFAULT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    call void @_ZN2ONC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-DDEFAULT-NEXT:    ret void
//
// CHECK-DEBSTRICT-LABEL: define linkonce_odr void @_ZN2ONC1Ev(
// CHECK-DEBSTRICT-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DEBSTRICT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    call void @_ZN2ONC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-DEBSTRICT-NEXT:    ret void
//
// CHECK-FAST-LABEL: define linkonce_odr void @_ZN2ONC1Ev(
// CHECK-FAST-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-FAST-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    call void @_ZN2ONC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-FAST-NEXT:    ret void
//
// CHECK-NOHONOR-LABEL: define linkonce_odr void @_ZN2ONC1Ev(
// CHECK-NOHONOR-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR2]] comdat align 2 {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NOHONOR-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    call void @_ZN2ONC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-NOHONOR-NEXT:    ret void
//
class ON {
  // Settings for top level class initializer use program source setting.
  float z = 2 + y() * 7;
//CHECK-LABEL: define {{.*}} void @_ZN2ONC2Ev{{.*}}
#if DEFAULT
#endif
#if EBSTRICT
#endif
#if NOHONOR
#endif
#if FAST
#endif
};
ON on;
#pragma float_control(except, off)
// CHECK-DDEFAULT-LABEL: define linkonce_odr void @_ZN3OFFC1Ev(
// CHECK-DDEFAULT-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DDEFAULT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    call void @_ZN3OFFC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-DDEFAULT-NEXT:    ret void
//
// CHECK-DEBSTRICT-LABEL: define linkonce_odr void @_ZN3OFFC1Ev(
// CHECK-DEBSTRICT-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR2]] comdat align 2 {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DEBSTRICT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    call void @_ZN3OFFC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-DEBSTRICT-NEXT:    ret void
//
// CHECK-FAST-LABEL: define linkonce_odr void @_ZN3OFFC1Ev(
// CHECK-FAST-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-FAST-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    call void @_ZN3OFFC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-FAST-NEXT:    ret void
//
// CHECK-NOHONOR-LABEL: define linkonce_odr void @_ZN3OFFC1Ev(
// CHECK-NOHONOR-SAME: ptr noundef nonnull align 4 dereferenceable(4) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NOHONOR-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    call void @_ZN3OFFC2Ev(ptr noundef nonnull align 4 dereferenceable(4) [[THIS1]])
// CHECK-NOHONOR-NEXT:    ret void
//
class OFF {
  float w = 2 + y() * 7;
};
OFF off;

// CHECK-DDEFAULT-LABEL: define dso_local <2 x float> @_Z6useAddv(
// CHECK-DDEFAULT-SAME: ) #[[ATTR4:[0-9]+]] {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-DDEFAULT-NEXT:    [[A:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DDEFAULT-NEXT:    [[B:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DDEFAULT-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DDEFAULT-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[A]], float noundef 1.000000e+00, float noundef 3.000000e+00)
// CHECK-DDEFAULT-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[B]], float noundef 2.000000e+00, float noundef 4.000000e+00)
// CHECK-DDEFAULT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[AGG_TMP]], ptr align 4 [[B]], i64 8, i1 false)
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[AGG_TMP]], align 4
// CHECK-DDEFAULT-NEXT:    [[CALL:%.*]] = call <2 x float> @_ZNK9MyComplexplES_(ptr noundef nonnull align 4 dereferenceable(8) [[A]], <2 x float> [[TMP0]])
// CHECK-DDEFAULT-NEXT:    store <2 x float> [[CALL]], ptr [[RETVAL]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-DDEFAULT-NEXT:    ret <2 x float> [[TMP1]]
//
// CHECK-DEBSTRICT-LABEL: define dso_local <2 x float> @_Z6useAddv(
// CHECK-DEBSTRICT-SAME: ) #[[ATTR4:[0-9]+]] {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-DEBSTRICT-NEXT:    [[A:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DEBSTRICT-NEXT:    [[B:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DEBSTRICT-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DEBSTRICT-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[A]], float noundef 1.000000e+00, float noundef 3.000000e+00)
// CHECK-DEBSTRICT-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[B]], float noundef 2.000000e+00, float noundef 4.000000e+00)
// CHECK-DEBSTRICT-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[AGG_TMP]], ptr align 4 [[B]], i64 8, i1 false)
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[AGG_TMP]], align 4
// CHECK-DEBSTRICT-NEXT:    [[CALL:%.*]] = call <2 x float> @_ZNK9MyComplexplES_(ptr noundef nonnull align 4 dereferenceable(8) [[A]], <2 x float> [[TMP0]])
// CHECK-DEBSTRICT-NEXT:    store <2 x float> [[CALL]], ptr [[RETVAL]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-DEBSTRICT-NEXT:    ret <2 x float> [[TMP1]]
//
// CHECK-FAST-LABEL: define dso_local <2 x float> @_Z6useAddv(
// CHECK-FAST-SAME: ) #[[ATTR4:[0-9]+]] {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-FAST-NEXT:    [[A:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-FAST-NEXT:    [[B:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-FAST-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-FAST-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[A]], float noundef nofpclass(nan inf) 1.000000e+00, float noundef nofpclass(nan inf) 3.000000e+00)
// CHECK-FAST-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[B]], float noundef nofpclass(nan inf) 2.000000e+00, float noundef nofpclass(nan inf) 4.000000e+00)
// CHECK-FAST-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[AGG_TMP]], ptr align 4 [[B]], i64 8, i1 false)
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[AGG_TMP]], align 4
// CHECK-FAST-NEXT:    [[CALL:%.*]] = call fast <2 x float> @_ZNK9MyComplexplES_(ptr noundef nonnull align 4 dereferenceable(8) [[A]], <2 x float> [[TMP0]])
// CHECK-FAST-NEXT:    store <2 x float> [[CALL]], ptr [[RETVAL]], align 4
// CHECK-FAST-NEXT:    [[TMP1:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-FAST-NEXT:    ret <2 x float> [[TMP1]]
//
// CHECK-NOHONOR-LABEL: define dso_local <2 x float> @_Z6useAddv(
// CHECK-NOHONOR-SAME: ) #[[ATTR4:[0-9]+]] {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-NOHONOR-NEXT:    [[A:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-NOHONOR-NEXT:    [[B:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-NOHONOR-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-NOHONOR-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[A]], float noundef nofpclass(nan inf) 1.000000e+00, float noundef nofpclass(nan inf) 3.000000e+00)
// CHECK-NOHONOR-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[B]], float noundef nofpclass(nan inf) 2.000000e+00, float noundef nofpclass(nan inf) 4.000000e+00)
// CHECK-NOHONOR-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 4 [[AGG_TMP]], ptr align 4 [[B]], i64 8, i1 false)
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[AGG_TMP]], align 4
// CHECK-NOHONOR-NEXT:    [[CALL:%.*]] = call nnan ninf <2 x float> @_ZNK9MyComplexplES_(ptr noundef nonnull align 4 dereferenceable(8) [[A]], <2 x float> [[TMP0]])
// CHECK-NOHONOR-NEXT:    store <2 x float> [[CALL]], ptr [[RETVAL]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-NOHONOR-NEXT:    ret <2 x float> [[TMP1]]
//
#pragma clang fp reassociate(on)
struct MyComplex {
  float xx;
  float yy;
// CHECK-DDEFAULT-LABEL: define linkonce_odr void @_ZN9MyComplexC1Eff(
// CHECK-DDEFAULT-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], float noundef [[X:%.*]], float noundef [[Y:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DDEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-DDEFAULT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-DDEFAULT-NEXT:    call void @_ZN9MyComplexC2Eff(ptr noundef nonnull align 4 dereferenceable(8) [[THIS1]], float noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-DDEFAULT-NEXT:    ret void
//
// CHECK-DEBSTRICT-LABEL: define linkonce_odr void @_ZN9MyComplexC1Eff(
// CHECK-DEBSTRICT-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], float noundef [[X:%.*]], float noundef [[Y:%.*]]) unnamed_addr #[[ATTR2]] comdat align 2 {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DEBSTRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-DEBSTRICT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-DEBSTRICT-NEXT:    call void @_ZN9MyComplexC2Eff(ptr noundef nonnull align 4 dereferenceable(8) [[THIS1]], float noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-DEBSTRICT-NEXT:    ret void
//
// CHECK-FAST-LABEL: define linkonce_odr void @_ZN9MyComplexC1Eff(
// CHECK-FAST-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], float noundef nofpclass(nan inf) [[X:%.*]], float noundef nofpclass(nan inf) [[Y:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-FAST-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-FAST-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-FAST-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-FAST-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-FAST-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-FAST-NEXT:    call void @_ZN9MyComplexC2Eff(ptr noundef nonnull align 4 dereferenceable(8) [[THIS1]], float noundef nofpclass(nan inf) [[TMP0]], float noundef nofpclass(nan inf) [[TMP1]])
// CHECK-FAST-NEXT:    ret void
//
// CHECK-NOHONOR-LABEL: define linkonce_odr void @_ZN9MyComplexC1Eff(
// CHECK-NOHONOR-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], float noundef nofpclass(nan inf) [[X:%.*]], float noundef nofpclass(nan inf) [[Y:%.*]]) unnamed_addr #[[ATTR0]] comdat align 2 {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NOHONOR-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-NOHONOR-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-NOHONOR-NEXT:    call void @_ZN9MyComplexC2Eff(ptr noundef nonnull align 4 dereferenceable(8) [[THIS1]], float noundef nofpclass(nan inf) [[TMP0]], float noundef nofpclass(nan inf) [[TMP1]])
// CHECK-NOHONOR-NEXT:    ret void
//
  MyComplex(float x, float y) {
    xx = x;
    yy = y;
  }
  MyComplex() {}
// CHECK-DDEFAULT-LABEL: define linkonce_odr <2 x float> @_ZNK9MyComplexplES_(
// CHECK-DDEFAULT-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], <2 x float> [[OTHER_COERCE:%.*]]) #[[ATTR4:[0-9]+]] comdat align 2 {
// CHECK-DDEFAULT-NEXT:  [[ENTRY:.*:]]
// CHECK-DDEFAULT-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-DDEFAULT-NEXT:    [[OTHER:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DDEFAULT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DDEFAULT-NEXT:    store <2 x float> [[OTHER_COERCE]], ptr [[OTHER]], align 4
// CHECK-DDEFAULT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DDEFAULT-NEXT:    [[XX:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 0
// CHECK-DDEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[XX]], align 4
// CHECK-DDEFAULT-NEXT:    [[XX2:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 0
// CHECK-DDEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[XX2]], align 4
// CHECK-DDEFAULT-NEXT:    [[ADD:%.*]] = fadd reassoc float [[TMP0]], [[TMP1]]
// CHECK-DDEFAULT-NEXT:    [[YY:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 1
// CHECK-DDEFAULT-NEXT:    [[TMP2:%.*]] = load float, ptr [[YY]], align 4
// CHECK-DDEFAULT-NEXT:    [[YY3:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 1
// CHECK-DDEFAULT-NEXT:    [[TMP3:%.*]] = load float, ptr [[YY3]], align 4
// CHECK-DDEFAULT-NEXT:    [[ADD4:%.*]] = fadd reassoc float [[TMP2]], [[TMP3]]
// CHECK-DDEFAULT-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[RETVAL]], float noundef [[ADD]], float noundef [[ADD4]])
// CHECK-DDEFAULT-NEXT:    [[TMP4:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-DDEFAULT-NEXT:    ret <2 x float> [[TMP4]]
//
// CHECK-DEBSTRICT-LABEL: define linkonce_odr <2 x float> @_ZNK9MyComplexplES_(
// CHECK-DEBSTRICT-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], <2 x float> [[OTHER_COERCE:%.*]]) #[[ATTR4:[0-9]+]] comdat align 2 {
// CHECK-DEBSTRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-DEBSTRICT-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-DEBSTRICT-NEXT:    [[OTHER:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-DEBSTRICT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-DEBSTRICT-NEXT:    store <2 x float> [[OTHER_COERCE]], ptr [[OTHER]], align 4
// CHECK-DEBSTRICT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-DEBSTRICT-NEXT:    [[XX:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 0
// CHECK-DEBSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[XX]], align 4
// CHECK-DEBSTRICT-NEXT:    [[XX2:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 0
// CHECK-DEBSTRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[XX2]], align 4
// CHECK-DEBSTRICT-NEXT:    [[ADD:%.*]] = fadd reassoc float [[TMP0]], [[TMP1]]
// CHECK-DEBSTRICT-NEXT:    [[YY:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 1
// CHECK-DEBSTRICT-NEXT:    [[TMP2:%.*]] = load float, ptr [[YY]], align 4
// CHECK-DEBSTRICT-NEXT:    [[YY3:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 1
// CHECK-DEBSTRICT-NEXT:    [[TMP3:%.*]] = load float, ptr [[YY3]], align 4
// CHECK-DEBSTRICT-NEXT:    [[ADD4:%.*]] = fadd reassoc float [[TMP2]], [[TMP3]]
// CHECK-DEBSTRICT-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[RETVAL]], float noundef [[ADD]], float noundef [[ADD4]])
// CHECK-DEBSTRICT-NEXT:    [[TMP4:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-DEBSTRICT-NEXT:    ret <2 x float> [[TMP4]]
//
// CHECK-FAST-LABEL: define linkonce_odr <2 x float> @_ZNK9MyComplexplES_(
// CHECK-FAST-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], <2 x float> [[OTHER_COERCE:%.*]]) #[[ATTR4:[0-9]+]] comdat align 2 {
// CHECK-FAST-NEXT:  [[ENTRY:.*:]]
// CHECK-FAST-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-FAST-NEXT:    [[OTHER:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-FAST-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-FAST-NEXT:    store <2 x float> [[OTHER_COERCE]], ptr [[OTHER]], align 4
// CHECK-FAST-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-FAST-NEXT:    [[XX:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 0
// CHECK-FAST-NEXT:    [[TMP0:%.*]] = load float, ptr [[XX]], align 4
// CHECK-FAST-NEXT:    [[XX2:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 0
// CHECK-FAST-NEXT:    [[TMP1:%.*]] = load float, ptr [[XX2]], align 4
// CHECK-FAST-NEXT:    [[ADD:%.*]] = fadd reassoc float [[TMP0]], [[TMP1]]
// CHECK-FAST-NEXT:    [[YY:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 1
// CHECK-FAST-NEXT:    [[TMP2:%.*]] = load float, ptr [[YY]], align 4
// CHECK-FAST-NEXT:    [[YY3:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 1
// CHECK-FAST-NEXT:    [[TMP3:%.*]] = load float, ptr [[YY3]], align 4
// CHECK-FAST-NEXT:    [[ADD4:%.*]] = fadd reassoc float [[TMP2]], [[TMP3]]
// CHECK-FAST-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[RETVAL]], float noundef nofpclass(nan inf) [[ADD]], float noundef nofpclass(nan inf) [[ADD4]])
// CHECK-FAST-NEXT:    [[TMP4:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-FAST-NEXT:    ret <2 x float> [[TMP4]]
//
// CHECK-NOHONOR-LABEL: define linkonce_odr <2 x float> @_ZNK9MyComplexplES_(
// CHECK-NOHONOR-SAME: ptr noundef nonnull align 4 dereferenceable(8) [[THIS:%.*]], <2 x float> [[OTHER_COERCE:%.*]]) #[[ATTR4:[0-9]+]] comdat align 2 {
// CHECK-NOHONOR-NEXT:  [[ENTRY:.*:]]
// CHECK-NOHONOR-NEXT:    [[RETVAL:%.*]] = alloca [[STRUCT_MYCOMPLEX:%.*]], align 4
// CHECK-NOHONOR-NEXT:    [[OTHER:%.*]] = alloca [[STRUCT_MYCOMPLEX]], align 4
// CHECK-NOHONOR-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NOHONOR-NEXT:    store <2 x float> [[OTHER_COERCE]], ptr [[OTHER]], align 4
// CHECK-NOHONOR-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-NOHONOR-NEXT:    [[XX:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 0
// CHECK-NOHONOR-NEXT:    [[TMP0:%.*]] = load float, ptr [[XX]], align 4
// CHECK-NOHONOR-NEXT:    [[XX2:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 0
// CHECK-NOHONOR-NEXT:    [[TMP1:%.*]] = load float, ptr [[XX2]], align 4
// CHECK-NOHONOR-NEXT:    [[ADD:%.*]] = fadd reassoc float [[TMP0]], [[TMP1]]
// CHECK-NOHONOR-NEXT:    [[YY:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[THIS1]], i32 0, i32 1
// CHECK-NOHONOR-NEXT:    [[TMP2:%.*]] = load float, ptr [[YY]], align 4
// CHECK-NOHONOR-NEXT:    [[YY3:%.*]] = getelementptr inbounds nuw [[STRUCT_MYCOMPLEX]], ptr [[OTHER]], i32 0, i32 1
// CHECK-NOHONOR-NEXT:    [[TMP3:%.*]] = load float, ptr [[YY3]], align 4
// CHECK-NOHONOR-NEXT:    [[ADD4:%.*]] = fadd reassoc float [[TMP2]], [[TMP3]]
// CHECK-NOHONOR-NEXT:    call void @_ZN9MyComplexC1Eff(ptr noundef nonnull align 4 dereferenceable(8) [[RETVAL]], float noundef nofpclass(nan inf) [[ADD]], float noundef nofpclass(nan inf) [[ADD4]])
// CHECK-NOHONOR-NEXT:    [[TMP4:%.*]] = load <2 x float>, ptr [[RETVAL]], align 4
// CHECK-NOHONOR-NEXT:    ret <2 x float> [[TMP4]]
//
  const MyComplex operator+(const MyComplex other) const {
    return MyComplex(xx + other.xx, yy + other.yy);
  }
};
MyComplex useAdd() {
  MyComplex a (1, 3);
  MyComplex b (2, 4);
   return a + b;
}
