// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-linux-gnu -emit-llvm -o - %s | FileCheck %s
// RUN: %clang_cc1 -triple x86_64-linux-gnu -emit-llvm -fdelayed-template-parsing -o - %s | FileCheck %s

template <typename T>
T templ_01(T x, T y) {
#pragma STDC FENV_ACCESS ON
  return x + y;
}

// CHECK-LABEL: define dso_local noundef float @_Z7func_01ff(
// CHECK-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call noundef float @_Z8templ_01IfET_S0_S0_(float noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-NEXT:    ret float [[CALL]]
//
float func_01(float x, float y) {
  return templ_01(x, y);
}



template <typename Ty>
Ty templ_02(Ty x, Ty y) {
  return x + y;
}

#pragma STDC FENV_ROUND FE_UPWARD

template <typename Ty>
Ty templ_03(Ty x, Ty y) {
  return x - y;
}

#pragma STDC FENV_ROUND FE_TONEAREST

// CHECK-LABEL: define dso_local noundef float @_Z7func_02ff(
// CHECK-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call noundef float @_Z8templ_02IfET_S0_S0_(float noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-NEXT:    ret float [[CALL]]
//
float func_02(float x, float y) {
  return templ_02(x, y);
}


// CHECK-LABEL: define dso_local noundef float @_Z7func_03ff(
// CHECK-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-NEXT:    [[CALL:%.*]] = call noundef float @_Z8templ_03IfET_S0_S0_(float noundef [[TMP0]], float noundef [[TMP1]])
// CHECK-NEXT:    ret float [[CALL]]
//
float func_03(float x, float y) {
  return templ_03(x, y);
}



#pragma STDC FENV_ROUND FE_TONEAREST

namespace PR63542 {
  template <class Compare> float stable_sort(float x, Compare) {
    float result = x + x;
    stable_sort(x, int());
    return result;
  }
// CHECK-LABEL: define dso_local noundef float @_ZN7PR6354212linkage_wrapEv(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[CALL:%.*]] = call noundef float @_ZN7PR6354211stable_sortIiEEffT_(float noundef 0.000000e+00, i32 noundef 1)
// CHECK-NEXT:    ret float [[CALL]]
//
  float linkage_wrap() { return stable_sort(0.0, 1); }
}


// These pragmas set non-default FP environment before delayed parsing occurs.
// It is used to check that the parsing uses FP options defined by command line
// options or by pragma before the template definition but not by these pragmas.
#pragma STDC FENV_ROUND FE_TOWARDZERO
#pragma STDC FENV_ACCESS ON

