// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// REQUIRES: arm-registered-target
// RUN: %clang_cc1 -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - -triple arm-none-linux-gnueabi %s | FileCheck %s --check-prefix=NOTNATIVE --check-prefix=CHECK -vv -dump-input=fail
// RUN: %clang_cc1 -ffp-exception-behavior=maytrap -emit-llvm -o - -triple aarch64 %s | FileCheck %s --check-prefix=NOTNATIVE --check-prefix=CHECK
// RUN: %clang_cc1 -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - -triple x86_64-linux-gnu %s | FileCheck %s --check-prefix=NOTNATIVE --check-prefix=CHECK
// RUN: %clang_cc1 -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - -triple arm-none-linux-gnueabi -fnative-half-type %s \
// RUN:   | FileCheck %s --check-prefix=NATIVE-HALF --check-prefix=CHECK
// RUN: %clang_cc1 -ffp-exception-behavior=maytrap -emit-llvm -o - -triple aarch64 -fnative-half-type %s \
// RUN:   | FileCheck %s --check-prefix=NATIVE-HALF --check-prefix=CHECK
//
// Test that the constrained intrinsics are picking up the exception
// metadata from the AST instead of the global default from the command line.

#pragma float_control(except, on)

typedef unsigned cond_t;
typedef __fp16 float16_t;

volatile cond_t test;
volatile int i0;
volatile __fp16 h0 = 0.0, h1 = 1.0, h2;
volatile float f0, f1, f2;
volatile double d0;
short s0;

// NOTNATIVE-LABEL: define dso_local void @foo(
// NOTNATIVE-SAME: ) #[[ATTR0:[0-9]+]] {
// NOTNATIVE-NEXT:  [[ENTRY:.*:]]
// NOTNATIVE-NEXT:    [[TMP0:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP0]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV1:%.*]] = call i32 @llvm.fptoui.i32.f32(float [[CONV]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile i32 [[CONV1]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP1:%.*]] = load volatile i32, ptr @test, align 4
// NOTNATIVE-NEXT:    [[CONV2:%.*]] = call float @llvm.uitofp.f32.i32(i32 [[TMP1]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV3:%.*]] = call half @llvm.fptrunc.f16.f32(float [[CONV2]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV3]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP2:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV4:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP2]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TOBOOL:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV4]], float 0.000000e+00, metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[LNOT:%.*]] = xor i1 [[TOBOOL]], true
// NOTNATIVE-NEXT:    [[LNOT_EXT:%.*]] = zext i1 [[LNOT]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[LNOT_EXT]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP3:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV5:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP3]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[FNEG:%.*]] = fneg float [[CONV5]]
// NOTNATIVE-NEXT:    [[CONV6:%.*]] = call half @llvm.fptrunc.f16.f32(float [[FNEG]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV6]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP4:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV7:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP4]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV8:%.*]] = call half @llvm.fptrunc.f16.f32(float [[CONV7]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV8]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP5:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[INCDEC_CONV:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP5]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[INC:%.*]] = call float @llvm.fadd.f32(float [[INCDEC_CONV]], float 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[INCDEC_CONV9:%.*]] = call half @llvm.fptrunc.f16.f32(float [[INC]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[INCDEC_CONV9]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP6:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[INCDEC_CONV10:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP6]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[INC11:%.*]] = call float @llvm.fadd.f32(float [[INCDEC_CONV10]], float 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[INCDEC_CONV12:%.*]] = call half @llvm.fptrunc.f16.f32(float [[INC11]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[INCDEC_CONV12]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP7:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[INCDEC_CONV13:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP7]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DEC:%.*]] = call float @llvm.fadd.f32(float [[INCDEC_CONV13]], float -1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[INCDEC_CONV14:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DEC]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[INCDEC_CONV14]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP8:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[INCDEC_CONV15:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP8]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DEC16:%.*]] = call float @llvm.fadd.f32(float [[INCDEC_CONV15]], float -1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[INCDEC_CONV17:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DEC16]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[INCDEC_CONV17]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP9:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV18:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP9]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP10:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV19:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP10]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[CONV18]], float [[CONV19]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV20:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV20]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP11:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV21:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP11]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV22:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV23:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV22]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL24:%.*]] = call float @llvm.fmul.f32(float [[CONV21]], float [[CONV23]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV25:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL24]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV25]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP12:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV26:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP12]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP13:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[MUL27:%.*]] = call float @llvm.fmul.f32(float [[CONV26]], float [[TMP13]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV28:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL27]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV28]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP14:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[TMP15:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV29:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP15]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL30:%.*]] = call float @llvm.fmul.f32(float [[TMP14]], float [[CONV29]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV31:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL30]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV31]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP16:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV32:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP16]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP17:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV33:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP17]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL34:%.*]] = call float @llvm.fmul.f32(float [[CONV32]], float [[CONV33]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV35:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL34]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV35]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP18:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV36:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP18]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP19:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV37:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP19]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV:%.*]] = call float @llvm.fdiv.f32(float [[CONV36]], float [[CONV37]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV38:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV38]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP20:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV39:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP20]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV40:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV41:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV40]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV42:%.*]] = call float @llvm.fdiv.f32(float [[CONV39]], float [[CONV41]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV43:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV42]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV43]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP21:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV44:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP21]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP22:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[DIV45:%.*]] = call float @llvm.fdiv.f32(float [[CONV44]], float [[TMP22]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV46:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV45]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV46]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP23:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[TMP24:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV47:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP24]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV48:%.*]] = call float @llvm.fdiv.f32(float [[TMP23]], float [[CONV47]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV49:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV48]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV49]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP25:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV50:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP25]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP26:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV51:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP26]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV52:%.*]] = call float @llvm.fdiv.f32(float [[CONV50]], float [[CONV51]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV53:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV52]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV53]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP27:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV54:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP27]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP28:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV55:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP28]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[CONV54]], float [[CONV55]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV56:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV56]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV57:%.*]] = call half @llvm.fptrunc.f16.f64(double -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV58:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV57]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP29:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV59:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP29]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD60:%.*]] = call float @llvm.fadd.f32(float [[CONV58]], float [[CONV59]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV61:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD60]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV61]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP30:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV62:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP30]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP31:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[ADD63:%.*]] = call float @llvm.fadd.f32(float [[CONV62]], float [[TMP31]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV64:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD63]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV64]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP32:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP33:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV65:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP33]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD66:%.*]] = call float @llvm.fadd.f32(float [[TMP32]], float [[CONV65]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV67:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD66]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV67]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP34:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV68:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP34]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP35:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV69:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP35]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD70:%.*]] = call float @llvm.fadd.f32(float [[CONV68]], float [[CONV69]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV71:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD70]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV71]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP36:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV72:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP36]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP37:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV73:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP37]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[CONV72]], float [[CONV73]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV74:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV74]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV75:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV76:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV75]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP38:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV77:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP38]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB78:%.*]] = call float @llvm.fsub.f32(float [[CONV76]], float [[CONV77]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV79:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB78]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV79]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP39:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV80:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP39]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP40:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[SUB81:%.*]] = call float @llvm.fsub.f32(float [[CONV80]], float [[TMP40]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV82:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB81]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV82]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP41:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP42:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV83:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP42]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB84:%.*]] = call float @llvm.fsub.f32(float [[TMP41]], float [[CONV83]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV85:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB84]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV85]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP43:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV86:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP43]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP44:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV87:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP44]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB88:%.*]] = call float @llvm.fsub.f32(float [[CONV86]], float [[CONV87]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV89:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB88]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV89]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP45:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV90:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP45]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP46:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV91:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP46]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV90]], float [[CONV91]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV92:%.*]] = zext i1 [[CMP]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV92]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP47:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV93:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP47]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV94:%.*]] = call half @llvm.fptrunc.f16.f64(double 4.200000e+01) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV95:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV94]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP96:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV93]], float [[CONV95]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV97:%.*]] = zext i1 [[CMP96]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV97]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP48:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV98:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP48]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP49:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[CMP99:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV98]], float [[TMP49]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV100:%.*]] = zext i1 [[CMP99]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV100]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP50:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP51:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV101:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP51]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP102:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP50]], float [[CONV101]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV103:%.*]] = zext i1 [[CMP102]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV103]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP52:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV104:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP52]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP53:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV105:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP53]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP106:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV104]], float [[CONV105]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV107:%.*]] = zext i1 [[CMP106]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV107]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP54:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV108:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP54]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP55:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV109:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP55]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP110:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV108]], float [[CONV109]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV111:%.*]] = zext i1 [[CMP110]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV111]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP56:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV112:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP56]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP57:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV113:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP57]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP114:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV112]], float [[CONV113]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV115:%.*]] = zext i1 [[CMP114]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV115]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[CONV116:%.*]] = call half @llvm.fptrunc.f16.f64(double 4.200000e+01) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV117:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV116]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP58:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV118:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP58]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP119:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV117]], float [[CONV118]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV120:%.*]] = zext i1 [[CMP119]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV120]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP59:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV121:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP59]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP60:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[CMP122:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV121]], float [[TMP60]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV123:%.*]] = zext i1 [[CMP122]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV123]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP61:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[TMP62:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV124:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP62]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP125:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP61]], float [[CONV124]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV126:%.*]] = zext i1 [[CMP125]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV126]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP63:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV127:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP63]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP64:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV128:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP64]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP129:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV127]], float [[CONV128]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV130:%.*]] = zext i1 [[CMP129]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV130]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP65:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV131:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP65]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP66:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV132:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP66]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP133:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV131]], float [[CONV132]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV134:%.*]] = zext i1 [[CMP133]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV134]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP67:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV135:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP67]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP68:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV136:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP68]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP137:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV135]], float [[CONV136]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV138:%.*]] = zext i1 [[CMP137]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV138]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP69:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV139:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP69]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV140:%.*]] = call half @llvm.fptrunc.f16.f64(double 4.200000e+01) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV141:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV140]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP142:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV139]], float [[CONV141]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV143:%.*]] = zext i1 [[CMP142]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV143]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP70:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV144:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP70]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP71:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[CMP145:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV144]], float [[TMP71]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV146:%.*]] = zext i1 [[CMP145]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV146]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP72:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP73:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV147:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP73]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP148:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP72]], float [[CONV147]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV149:%.*]] = zext i1 [[CMP148]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV149]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP74:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV150:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP74]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP75:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV151:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP75]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP152:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV150]], float [[CONV151]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV153:%.*]] = zext i1 [[CMP152]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV153]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP76:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV154:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP76]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP77:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV155:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP77]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP156:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV154]], float [[CONV155]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV157:%.*]] = zext i1 [[CMP156]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV157]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP78:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV158:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP78]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP79:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV159:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP79]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP160:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV158]], float [[CONV159]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV161:%.*]] = zext i1 [[CMP160]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV161]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP80:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV162:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP80]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV163:%.*]] = call half @llvm.fptrunc.f16.f64(double -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV164:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV163]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP165:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV162]], float [[CONV164]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV166:%.*]] = zext i1 [[CMP165]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV166]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP81:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV167:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP81]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP82:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[CMP168:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV167]], float [[TMP82]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV169:%.*]] = zext i1 [[CMP168]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV169]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP83:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[TMP84:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV170:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP84]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP171:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP83]], float [[CONV170]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV172:%.*]] = zext i1 [[CMP171]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV172]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP85:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV173:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP85]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP86:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV174:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP86]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP175:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV173]], float [[CONV174]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV176:%.*]] = zext i1 [[CMP175]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV176]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP87:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV177:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP87]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP88:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV178:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP88]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP179:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV177]], float [[CONV178]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV180:%.*]] = zext i1 [[CMP179]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV180]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP89:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV181:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP89]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP90:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV182:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP90]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP183:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV181]], float [[CONV182]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV184:%.*]] = zext i1 [[CMP183]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV184]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP91:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV185:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP91]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV186:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV187:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV186]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP188:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV185]], float [[CONV187]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV189:%.*]] = zext i1 [[CMP188]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV189]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP92:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV190:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP92]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP93:%.*]] = load volatile float, ptr @f1, align 4
// NOTNATIVE-NEXT:    [[CMP191:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV190]], float [[TMP93]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV192:%.*]] = zext i1 [[CMP191]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV192]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP94:%.*]] = load volatile float, ptr @f1, align 4
// NOTNATIVE-NEXT:    [[TMP95:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV193:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP95]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP194:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP94]], float [[CONV193]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV195:%.*]] = zext i1 [[CMP194]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV195]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP96:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV196:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP96]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP97:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV197:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP97]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP198:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV196]], float [[CONV197]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV199:%.*]] = zext i1 [[CMP198]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV199]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP98:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV200:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP98]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP99:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV201:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP99]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP202:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV200]], float [[CONV201]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV203:%.*]] = zext i1 [[CMP202]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV203]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP100:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV204:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP100]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP101:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV205:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP101]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP206:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV204]], float [[CONV205]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV207:%.*]] = zext i1 [[CMP206]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV207]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP102:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV208:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP102]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV209:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV210:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV209]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP211:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV208]], float [[CONV210]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV212:%.*]] = zext i1 [[CMP211]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV212]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP103:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV213:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP103]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP104:%.*]] = load volatile float, ptr @f1, align 4
// NOTNATIVE-NEXT:    [[CMP214:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV213]], float [[TMP104]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV215:%.*]] = zext i1 [[CMP214]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV215]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP105:%.*]] = load volatile float, ptr @f1, align 4
// NOTNATIVE-NEXT:    [[TMP106:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV216:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP106]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP217:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP105]], float [[CONV216]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV218:%.*]] = zext i1 [[CMP217]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV218]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP107:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV219:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP107]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP108:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV220:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP108]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP221:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV219]], float [[CONV220]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV222:%.*]] = zext i1 [[CMP221]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV222]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP109:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV223:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP109]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP110:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV224:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP110]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CMP225:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV223]], float [[CONV224]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV226:%.*]] = zext i1 [[CMP225]] to i32
// NOTNATIVE-NEXT:    store volatile i32 [[CONV226]], ptr @test, align 4
// NOTNATIVE-NEXT:    [[TMP111:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV227:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP111]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TOBOOL228:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV227]], float 0.000000e+00, metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    br i1 [[TOBOOL228]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
// NOTNATIVE:       [[COND_TRUE]]:
// NOTNATIVE-NEXT:    [[TMP112:%.*]] = load volatile half, ptr @h2, align 2
// NOTNATIVE-NEXT:    [[CONV229:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP112]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    br label %[[COND_END:.*]]
// NOTNATIVE:       [[COND_FALSE]]:
// NOTNATIVE-NEXT:    [[TMP113:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV230:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP113]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    br label %[[COND_END]]
// NOTNATIVE:       [[COND_END]]:
// NOTNATIVE-NEXT:    [[COND:%.*]] = phi float [ [[CONV229]], %[[COND_TRUE]] ], [ [[CONV230]], %[[COND_FALSE]] ]
// NOTNATIVE-NEXT:    [[CONV231:%.*]] = call half @llvm.fptrunc.f16.f32(float [[COND]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV231]], ptr @h1, align 2
// NOTNATIVE-NEXT:    [[TMP114:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    store volatile half [[TMP114]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV232:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV232]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP115:%.*]] = load volatile float, ptr @f0, align 4
// NOTNATIVE-NEXT:    [[CONV233:%.*]] = call half @llvm.fptrunc.f16.f32(float [[TMP115]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV233]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP116:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV234:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP116]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV235:%.*]] = call half @llvm.fptrunc.f16.f32(float [[CONV234]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV235]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP117:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV236:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP117]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV237:%.*]] = call i32 @llvm.fptosi.i32.f32(float [[CONV236]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile i32 [[CONV237]], ptr @i0, align 4
// NOTNATIVE-NEXT:    [[TMP118:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV238:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP118]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP119:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV239:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP119]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD240:%.*]] = call float @llvm.fadd.f32(float [[CONV239]], float [[CONV238]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV241:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD240]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV241]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV242:%.*]] = call half @llvm.fptrunc.f16.f32(float 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV243:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV242]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP120:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV244:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP120]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD245:%.*]] = call float @llvm.fadd.f32(float [[CONV244]], float [[CONV243]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV246:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD245]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV246]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP121:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP122:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV247:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP122]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD248:%.*]] = call float @llvm.fadd.f32(float [[CONV247]], float [[TMP121]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV249:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD248]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV249]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP123:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV250:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP123]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP124:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV251:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP124]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD252:%.*]] = call float @llvm.fadd.f32(float [[CONV251]], float [[CONV250]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV253:%.*]] = call i32 @llvm.fptosi.i32.f32(float [[ADD252]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile i32 [[CONV253]], ptr @i0, align 4
// NOTNATIVE-NEXT:    [[TMP125:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV254:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP125]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP126:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV255:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP126]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD256:%.*]] = call float @llvm.fadd.f32(float [[CONV255]], float [[CONV254]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV257:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD256]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV257]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP127:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV258:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP127]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP128:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV259:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP128]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB260:%.*]] = call float @llvm.fsub.f32(float [[CONV259]], float [[CONV258]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV261:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB260]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV261]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV262:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV263:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV262]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP129:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV264:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP129]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB265:%.*]] = call float @llvm.fsub.f32(float [[CONV264]], float [[CONV263]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV266:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB265]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV266]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP130:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP131:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV267:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP131]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB268:%.*]] = call float @llvm.fsub.f32(float [[CONV267]], float [[TMP130]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV269:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB268]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV269]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP132:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV270:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP132]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP133:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV271:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP133]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB272:%.*]] = call float @llvm.fsub.f32(float [[CONV271]], float [[CONV270]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV273:%.*]] = call i32 @llvm.fptosi.i32.f32(float [[SUB272]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile i32 [[CONV273]], ptr @i0, align 4
// NOTNATIVE-NEXT:    [[TMP134:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV274:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP134]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP135:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV275:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP135]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[SUB276:%.*]] = call float @llvm.fsub.f32(float [[CONV275]], float [[CONV274]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV277:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB276]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV277]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP136:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV278:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP136]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP137:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV279:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP137]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL280:%.*]] = call float @llvm.fmul.f32(float [[CONV279]], float [[CONV278]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV281:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL280]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV281]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV282:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV283:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV282]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP138:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV284:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP138]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL285:%.*]] = call float @llvm.fmul.f32(float [[CONV284]], float [[CONV283]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV286:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL285]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV286]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP139:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP140:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV287:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP140]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL288:%.*]] = call float @llvm.fmul.f32(float [[CONV287]], float [[TMP139]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV289:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL288]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV289]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP141:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV290:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP141]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP142:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV291:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP142]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL292:%.*]] = call float @llvm.fmul.f32(float [[CONV291]], float [[CONV290]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV293:%.*]] = call i32 @llvm.fptosi.i32.f32(float [[MUL292]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile i32 [[CONV293]], ptr @i0, align 4
// NOTNATIVE-NEXT:    [[TMP143:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV294:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP143]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP144:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV295:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP144]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[MUL296:%.*]] = call float @llvm.fmul.f32(float [[CONV295]], float [[CONV294]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV297:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL296]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV297]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP145:%.*]] = load volatile half, ptr @h1, align 2
// NOTNATIVE-NEXT:    [[CONV298:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP145]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP146:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV299:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP146]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV300:%.*]] = call float @llvm.fdiv.f32(float [[CONV299]], float [[CONV298]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV301:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV300]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV301]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV302:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV303:%.*]] = call float @llvm.fpext.f32.f16(half [[CONV302]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP147:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV304:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP147]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV305:%.*]] = call float @llvm.fdiv.f32(float [[CONV304]], float [[CONV303]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV306:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV305]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV306]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP148:%.*]] = load volatile float, ptr @f2, align 4
// NOTNATIVE-NEXT:    [[TMP149:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV307:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP149]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV308:%.*]] = call float @llvm.fdiv.f32(float [[CONV307]], float [[TMP148]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV309:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV308]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV309]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP150:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV310:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP150]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP151:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV311:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP151]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV312:%.*]] = call float @llvm.fdiv.f32(float [[CONV311]], float [[CONV310]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV313:%.*]] = call i32 @llvm.fptosi.i32.f32(float [[DIV312]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile i32 [[CONV313]], ptr @i0, align 4
// NOTNATIVE-NEXT:    [[TMP152:%.*]] = load volatile i32, ptr @i0, align 4
// NOTNATIVE-NEXT:    [[CONV314:%.*]] = call float @llvm.sitofp.f32.i32(i32 [[TMP152]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP153:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV315:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP153]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[DIV316:%.*]] = call float @llvm.fdiv.f32(float [[CONV315]], float [[CONV314]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV317:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV316]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV317]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP154:%.*]] = load volatile double, ptr @d0, align 8
// NOTNATIVE-NEXT:    [[CONV318:%.*]] = call half @llvm.fptrunc.f16.f64(double [[TMP154]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV318]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP155:%.*]] = load volatile double, ptr @d0, align 8
// NOTNATIVE-NEXT:    [[CONV319:%.*]] = call float @llvm.fptrunc.f32.f64(double [[TMP155]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV320:%.*]] = call half @llvm.fptrunc.f16.f32(float [[CONV319]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV320]], ptr @h0, align 2
// NOTNATIVE-NEXT:    [[TMP156:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV321:%.*]] = call double @llvm.fpext.f64.f16(half [[TMP156]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile double [[CONV321]], ptr @d0, align 8
// NOTNATIVE-NEXT:    [[TMP157:%.*]] = load volatile half, ptr @h0, align 2
// NOTNATIVE-NEXT:    [[CONV322:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP157]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV323:%.*]] = call double @llvm.fpext.f64.f32(float [[CONV322]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile double [[CONV323]], ptr @d0, align 8
// NOTNATIVE-NEXT:    [[TMP158:%.*]] = load i16, ptr @s0, align 2
// NOTNATIVE-NEXT:    [[CONV324:%.*]] = call float @llvm.sitofp.f32.i16(i16 [[TMP158]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV325:%.*]] = call half @llvm.fptrunc.f16.f32(float [[CONV324]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store volatile half [[CONV325]], ptr @h0, align 2
// NOTNATIVE-NEXT:    ret void
//
// NATIVE-HALF-LABEL: define dso_local void @foo(
// NATIVE-HALF-SAME: ) #[[ATTR0:[0-9]+]] {
// NATIVE-HALF-NEXT:  [[ENTRY:.*:]]
// NATIVE-HALF-NEXT:    [[TMP0:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV:%.*]] = call i32 @llvm.fptoui.i32.f16(half [[TMP0]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP1:%.*]] = load volatile i32, ptr @test, align 4
// NATIVE-HALF-NEXT:    [[CONV1:%.*]] = call half @llvm.uitofp.f16.i32(i32 [[TMP1]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV1]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP2:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TOBOOL:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP2]], half 0xH0000, metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[LNOT:%.*]] = xor i1 [[TOBOOL]], true
// NATIVE-HALF-NEXT:    [[LNOT_EXT:%.*]] = zext i1 [[LNOT]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[LNOT_EXT]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP3:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[FNEG:%.*]] = fneg half [[TMP3]]
// NATIVE-HALF-NEXT:    store volatile half [[FNEG]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP4:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    store volatile half [[TMP4]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP5:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[INC:%.*]] = call half @llvm.fadd.f16(half [[TMP5]], half 0xH3C00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[INC]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP6:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[INC2:%.*]] = call half @llvm.fadd.f16(half [[TMP6]], half 0xH3C00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[INC2]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP7:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[DEC:%.*]] = call half @llvm.fadd.f16(half [[TMP7]], half 0xHBC00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DEC]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP8:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[DEC3:%.*]] = call half @llvm.fadd.f16(half [[TMP8]], half 0xHBC00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DEC3]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP9:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP10:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[MUL:%.*]] = call half @llvm.fmul.f16(half [[TMP9]], half [[TMP10]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[MUL]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP11:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV4:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[MUL5:%.*]] = call half @llvm.fmul.f16(half [[TMP11]], half [[CONV4]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[MUL5]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP12:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV6:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP12]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP13:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[MUL7:%.*]] = call float @llvm.fmul.f32(float [[CONV6]], float [[TMP13]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV8:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL7]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV8]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP14:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[TMP15:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV9:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP15]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[MUL10:%.*]] = call float @llvm.fmul.f32(float [[TMP14]], float [[CONV9]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV11:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL10]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV11]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP16:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP17:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV12:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP17]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[MUL13:%.*]] = call half @llvm.fmul.f16(half [[TMP16]], half [[CONV12]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[MUL13]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP18:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP19:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[DIV:%.*]] = call half @llvm.fdiv.f16(half [[TMP18]], half [[TMP19]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DIV]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP20:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV14:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[DIV15:%.*]] = call half @llvm.fdiv.f16(half [[TMP20]], half [[CONV14]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DIV15]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP21:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV16:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP21]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP22:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[DIV17:%.*]] = call float @llvm.fdiv.f32(float [[CONV16]], float [[TMP22]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV18:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV17]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV18]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP23:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[TMP24:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV19:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP24]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[DIV20:%.*]] = call float @llvm.fdiv.f32(float [[TMP23]], float [[CONV19]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV21:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV20]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV21]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP25:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP26:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV22:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP26]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[DIV23:%.*]] = call half @llvm.fdiv.f16(half [[TMP25]], half [[CONV22]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DIV23]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP27:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[TMP28:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[ADD:%.*]] = call half @llvm.fadd.f16(half [[TMP27]], half [[TMP28]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[ADD]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV24:%.*]] = call half @llvm.fptrunc.f16.f64(double -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP29:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[ADD25:%.*]] = call half @llvm.fadd.f16(half [[CONV24]], half [[TMP29]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[ADD25]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP30:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV26:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP30]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP31:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[ADD27:%.*]] = call float @llvm.fadd.f32(float [[CONV26]], float [[TMP31]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV28:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD27]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV28]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP32:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP33:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV29:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP33]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[ADD30:%.*]] = call float @llvm.fadd.f32(float [[TMP32]], float [[CONV29]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV31:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD30]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV31]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP34:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP35:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV32:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP35]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[ADD33:%.*]] = call half @llvm.fadd.f16(half [[TMP34]], half [[CONV32]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[ADD33]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP36:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[TMP37:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[SUB:%.*]] = call half @llvm.fsub.f16(half [[TMP36]], half [[TMP37]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[SUB]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV34:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP38:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[SUB35:%.*]] = call half @llvm.fsub.f16(half [[CONV34]], half [[TMP38]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[SUB35]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP39:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV36:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP39]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP40:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[SUB37:%.*]] = call float @llvm.fsub.f32(float [[CONV36]], float [[TMP40]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV38:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB37]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV38]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP41:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP42:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV39:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP42]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[SUB40:%.*]] = call float @llvm.fsub.f32(float [[TMP41]], float [[CONV39]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV41:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB40]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV41]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP43:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP44:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV42:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP44]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[SUB43:%.*]] = call half @llvm.fsub.f16(half [[TMP43]], half [[CONV42]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[SUB43]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP45:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[TMP46:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP45]], half [[TMP46]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV44:%.*]] = zext i1 [[CMP]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV44]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP47:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV45:%.*]] = call half @llvm.fptrunc.f16.f64(double 4.200000e+01) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP46:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP47]], half [[CONV45]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV47:%.*]] = zext i1 [[CMP46]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV47]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP48:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV48:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP48]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP49:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[CMP49:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV48]], float [[TMP49]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV50:%.*]] = zext i1 [[CMP49]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV50]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP50:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP51:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV51:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP51]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP52:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP50]], float [[CONV51]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV53:%.*]] = zext i1 [[CMP52]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV53]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP52:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV54:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP52]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP53:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP55:%.*]] = call i1 @llvm.fcmp.f16(half [[CONV54]], half [[TMP53]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV56:%.*]] = zext i1 [[CMP55]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV56]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP54:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP55:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV57:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP55]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP58:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP54]], half [[CONV57]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV59:%.*]] = zext i1 [[CMP58]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV59]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP56:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP57:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CMP60:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP56]], half [[TMP57]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV61:%.*]] = zext i1 [[CMP60]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV61]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[CONV62:%.*]] = call half @llvm.fptrunc.f16.f64(double 4.200000e+01) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP58:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CMP63:%.*]] = call i1 @llvm.fcmp.f16(half [[CONV62]], half [[TMP58]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV64:%.*]] = zext i1 [[CMP63]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV64]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP59:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV65:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP59]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP60:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[CMP66:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV65]], float [[TMP60]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV67:%.*]] = zext i1 [[CMP66]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV67]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP61:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[TMP62:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV68:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP62]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP69:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP61]], float [[CONV68]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV70:%.*]] = zext i1 [[CMP69]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV70]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP63:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV71:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP63]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP64:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP72:%.*]] = call i1 @llvm.fcmp.f16(half [[CONV71]], half [[TMP64]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV73:%.*]] = zext i1 [[CMP72]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV73]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP65:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP66:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV74:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP66]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP75:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP65]], half [[CONV74]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV76:%.*]] = zext i1 [[CMP75]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV76]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP67:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[TMP68:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP77:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP67]], half [[TMP68]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV78:%.*]] = zext i1 [[CMP77]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV78]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP69:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV79:%.*]] = call half @llvm.fptrunc.f16.f64(double 4.200000e+01) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP80:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP69]], half [[CONV79]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV81:%.*]] = zext i1 [[CMP80]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV81]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP70:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV82:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP70]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP71:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[CMP83:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV82]], float [[TMP71]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV84:%.*]] = zext i1 [[CMP83]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV84]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP72:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP73:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV85:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP73]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP86:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP72]], float [[CONV85]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV87:%.*]] = zext i1 [[CMP86]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV87]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP74:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV88:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP74]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP75:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP89:%.*]] = call i1 @llvm.fcmp.f16(half [[CONV88]], half [[TMP75]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV90:%.*]] = zext i1 [[CMP89]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV90]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP76:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP77:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV91:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP77]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP92:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP76]], half [[CONV91]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV93:%.*]] = zext i1 [[CMP92]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV93]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP78:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP79:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CMP94:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP78]], half [[TMP79]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV95:%.*]] = zext i1 [[CMP94]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV95]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP80:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV96:%.*]] = call half @llvm.fptrunc.f16.f64(double -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP97:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP80]], half [[CONV96]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV98:%.*]] = zext i1 [[CMP97]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV98]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP81:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV99:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP81]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP82:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[CMP100:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV99]], float [[TMP82]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV101:%.*]] = zext i1 [[CMP100]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV101]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP83:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[TMP84:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CONV102:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP84]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP103:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP83]], float [[CONV102]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV104:%.*]] = zext i1 [[CMP103]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV104]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP85:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV105:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP85]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP86:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP106:%.*]] = call i1 @llvm.fcmp.f16(half [[CONV105]], half [[TMP86]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV107:%.*]] = zext i1 [[CMP106]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV107]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP87:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP88:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV108:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP88]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP109:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP87]], half [[CONV108]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV110:%.*]] = zext i1 [[CMP109]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV110]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP89:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP90:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CMP111:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP89]], half [[TMP90]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV112:%.*]] = zext i1 [[CMP111]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV112]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP91:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV113:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP114:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP91]], half [[CONV113]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV115:%.*]] = zext i1 [[CMP114]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV115]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP92:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV116:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP92]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP93:%.*]] = load volatile float, ptr @f1, align 4
// NATIVE-HALF-NEXT:    [[CMP117:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV116]], float [[TMP93]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV118:%.*]] = zext i1 [[CMP117]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV118]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP94:%.*]] = load volatile float, ptr @f1, align 4
// NATIVE-HALF-NEXT:    [[TMP95:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV119:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP95]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP120:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP94]], float [[CONV119]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV121:%.*]] = zext i1 [[CMP120]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV121]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP96:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV122:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP96]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP97:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP123:%.*]] = call i1 @llvm.fcmp.f16(half [[CONV122]], half [[TMP97]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV124:%.*]] = zext i1 [[CMP123]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV124]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP98:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP99:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV125:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP99]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP126:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP98]], half [[CONV125]], metadata !"oeq") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV127:%.*]] = zext i1 [[CMP126]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV127]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP100:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP101:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    [[CMP128:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP100]], half [[TMP101]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV129:%.*]] = zext i1 [[CMP128]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV129]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP102:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV130:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP131:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP102]], half [[CONV130]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV132:%.*]] = zext i1 [[CMP131]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV132]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP103:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV133:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP103]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP104:%.*]] = load volatile float, ptr @f1, align 4
// NATIVE-HALF-NEXT:    [[CMP134:%.*]] = call i1 @llvm.fcmp.f32(float [[CONV133]], float [[TMP104]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV135:%.*]] = zext i1 [[CMP134]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV135]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP105:%.*]] = load volatile float, ptr @f1, align 4
// NATIVE-HALF-NEXT:    [[TMP106:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[CONV136:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP106]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP137:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP105]], float [[CONV136]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV138:%.*]] = zext i1 [[CMP137]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV138]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP107:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV139:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP107]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP108:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CMP140:%.*]] = call i1 @llvm.fcmp.f16(half [[CONV139]], half [[TMP108]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV141:%.*]] = zext i1 [[CMP140]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV141]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP109:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP110:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV142:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP110]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CMP143:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP109]], half [[CONV142]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV144:%.*]] = zext i1 [[CMP143]] to i32
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV144]], ptr @test, align 4
// NATIVE-HALF-NEXT:    [[TMP111:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TOBOOL145:%.*]] = call i1 @llvm.fcmp.f16(half [[TMP111]], half 0xH0000, metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    br i1 [[TOBOOL145]], label %[[COND_TRUE:.*]], label %[[COND_FALSE:.*]]
// NATIVE-HALF:       [[COND_TRUE]]:
// NATIVE-HALF-NEXT:    [[TMP112:%.*]] = load volatile half, ptr @h2, align 2
// NATIVE-HALF-NEXT:    br label %[[COND_END:.*]]
// NATIVE-HALF:       [[COND_FALSE]]:
// NATIVE-HALF-NEXT:    [[TMP113:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    br label %[[COND_END]]
// NATIVE-HALF:       [[COND_END]]:
// NATIVE-HALF-NEXT:    [[COND:%.*]] = phi half [ [[TMP112]], %[[COND_TRUE]] ], [ [[TMP113]], %[[COND_FALSE]] ]
// NATIVE-HALF-NEXT:    store volatile half [[COND]], ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP114:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    store volatile half [[TMP114]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV146:%.*]] = call half @llvm.fptrunc.f16.f32(float -2.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV146]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP115:%.*]] = load volatile float, ptr @f0, align 4
// NATIVE-HALF-NEXT:    [[CONV147:%.*]] = call half @llvm.fptrunc.f16.f32(float [[TMP115]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV147]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP116:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV148:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP116]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV148]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP117:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV149:%.*]] = call i32 @llvm.fptosi.i32.f16(half [[TMP117]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV149]], ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[TMP118:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP119:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[ADD150:%.*]] = call half @llvm.fadd.f16(half [[TMP119]], half [[TMP118]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[ADD150]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV151:%.*]] = call half @llvm.fptrunc.f16.f32(float 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP120:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[ADD152:%.*]] = call half @llvm.fadd.f16(half [[TMP120]], half [[CONV151]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[ADD152]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP121:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP122:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV153:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP122]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[ADD154:%.*]] = call float @llvm.fadd.f32(float [[CONV153]], float [[TMP121]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV155:%.*]] = call half @llvm.fptrunc.f16.f32(float [[ADD154]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV155]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP123:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP124:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV156:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP124]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[ADD157:%.*]] = call half @llvm.fadd.f16(half [[CONV156]], half [[TMP123]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV158:%.*]] = call i32 @llvm.fptosi.i32.f16(half [[ADD157]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV158]], ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[TMP125:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV159:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP125]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP126:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[ADD160:%.*]] = call half @llvm.fadd.f16(half [[TMP126]], half [[CONV159]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[ADD160]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP127:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP128:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[SUB161:%.*]] = call half @llvm.fsub.f16(half [[TMP128]], half [[TMP127]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[SUB161]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV162:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP129:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[SUB163:%.*]] = call half @llvm.fsub.f16(half [[TMP129]], half [[CONV162]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[SUB163]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP130:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP131:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV164:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP131]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[SUB165:%.*]] = call float @llvm.fsub.f32(float [[CONV164]], float [[TMP130]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV166:%.*]] = call half @llvm.fptrunc.f16.f32(float [[SUB165]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV166]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP132:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP133:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV167:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP133]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[SUB168:%.*]] = call half @llvm.fsub.f16(half [[CONV167]], half [[TMP132]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV169:%.*]] = call i32 @llvm.fptosi.i32.f16(half [[SUB168]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV169]], ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[TMP134:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV170:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP134]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP135:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[SUB171:%.*]] = call half @llvm.fsub.f16(half [[TMP135]], half [[CONV170]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[SUB171]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP136:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP137:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[MUL172:%.*]] = call half @llvm.fmul.f16(half [[TMP137]], half [[TMP136]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[MUL172]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV173:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP138:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[MUL174:%.*]] = call half @llvm.fmul.f16(half [[TMP138]], half [[CONV173]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[MUL174]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP139:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP140:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV175:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP140]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[MUL176:%.*]] = call float @llvm.fmul.f32(float [[CONV175]], float [[TMP139]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV177:%.*]] = call half @llvm.fptrunc.f16.f32(float [[MUL176]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV177]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP141:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP142:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV178:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP142]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[MUL179:%.*]] = call half @llvm.fmul.f16(half [[CONV178]], half [[TMP141]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV180:%.*]] = call i32 @llvm.fptosi.i32.f16(half [[MUL179]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV180]], ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[TMP143:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV181:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP143]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP144:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[MUL182:%.*]] = call half @llvm.fmul.f16(half [[TMP144]], half [[CONV181]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[MUL182]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP145:%.*]] = load volatile half, ptr @h1, align 2
// NATIVE-HALF-NEXT:    [[TMP146:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[DIV183:%.*]] = call half @llvm.fdiv.f16(half [[TMP146]], half [[TMP145]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DIV183]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV184:%.*]] = call half @llvm.fptrunc.f16.f64(double 1.000000e+00) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP147:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[DIV185:%.*]] = call half @llvm.fdiv.f16(half [[TMP147]], half [[CONV184]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DIV185]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP148:%.*]] = load volatile float, ptr @f2, align 4
// NATIVE-HALF-NEXT:    [[TMP149:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV186:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP149]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[DIV187:%.*]] = call float @llvm.fdiv.f32(float [[CONV186]], float [[TMP148]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV188:%.*]] = call half @llvm.fptrunc.f16.f32(float [[DIV187]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV188]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP150:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP151:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV189:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP151]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[DIV190:%.*]] = call half @llvm.fdiv.f16(half [[CONV189]], half [[TMP150]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV191:%.*]] = call i32 @llvm.fptosi.i32.f16(half [[DIV190]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile i32 [[CONV191]], ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[TMP152:%.*]] = load volatile i32, ptr @i0, align 4
// NATIVE-HALF-NEXT:    [[CONV192:%.*]] = call half @llvm.sitofp.f16.i32(i32 [[TMP152]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[TMP153:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[DIV193:%.*]] = call half @llvm.fdiv.f16(half [[TMP153]], half [[CONV192]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[DIV193]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP154:%.*]] = load volatile double, ptr @d0, align 8
// NATIVE-HALF-NEXT:    [[CONV194:%.*]] = call half @llvm.fptrunc.f16.f64(double [[TMP154]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV194]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP155:%.*]] = load volatile double, ptr @d0, align 8
// NATIVE-HALF-NEXT:    [[CONV195:%.*]] = call float @llvm.fptrunc.f32.f64(double [[TMP155]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV196:%.*]] = call half @llvm.fptrunc.f16.f32(float [[CONV195]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV196]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[TMP156:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV197:%.*]] = call double @llvm.fpext.f64.f16(half [[TMP156]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile double [[CONV197]], ptr @d0, align 8
// NATIVE-HALF-NEXT:    [[TMP157:%.*]] = load volatile half, ptr @h0, align 2
// NATIVE-HALF-NEXT:    [[CONV198:%.*]] = call float @llvm.fpext.f32.f16(half [[TMP157]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    [[CONV199:%.*]] = call double @llvm.fpext.f64.f32(float [[CONV198]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile double [[CONV199]], ptr @d0, align 8
// NATIVE-HALF-NEXT:    [[TMP158:%.*]] = load i16, ptr @s0, align 2
// NATIVE-HALF-NEXT:    [[CONV200:%.*]] = call half @llvm.sitofp.f16.i16(i16 [[TMP158]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store volatile half [[CONV200]], ptr @h0, align 2
// NATIVE-HALF-NEXT:    ret void
//
void foo(void) {

  // Check unary ops

  test = (h0);

  h0 = (test);

  test = (!h1);

  h1 = -h1;

  h1 = +h1;

  h1++;

  ++h1;

  --h1;

  h1--;

  // Check binary ops with various operands
  h1 = h0 * h2;

  h1 = h0 * (__fp16) -2.0f;

  h1 = h0 * f2;

  h1 = f0 * h2;

  h1 = h0 * i0;

  h1 = (h0 / h2);

  h1 = (h0 / (__fp16) -2.0f);

  h1 = (h0 / f2);

  h1 = (f0 / h2);

  h1 = (h0 / i0);

  h1 = (h2 + h0);

  h1 = ((__fp16)-2.0 + h0);

  h1 = (h2 + f0);

  h1 = (f2 + h0);

  h1 = (h0 + i0);

  h1 = (h2 - h0);

  h1 = ((__fp16)-2.0f - h0);

  h1 = (h2 - f0);

  h1 = (f2 - h0);

  h1 = (h0 - i0);

  test = (h2 < h0);

  test = (h2 < (__fp16)42.0);

  test = (h2 < f0);

  test = (f2 < h0);

  test = (i0 < h0);

  test = (h0 < i0);

  test = (h0 > h2);

  test = ((__fp16)42.0 > h2);

  test = (h0 > f2);

  test = (f0 > h2);

  test = (i0 > h0);

  test = (h0 > i0);

  test = (h2 <= h0);

  test = (h2 <= (__fp16)42.0);

  test = (h2 <= f0);

  test = (f2 <= h0);

  test = (i0 <= h0);

  test = (h0 <= i0);


  test = (h0 >= h2);

  test = (h0 >= (__fp16)-2.0);

  test = (h0 >= f2);

  test = (f0 >= h2);

  test = (i0 >= h0);

  test = (h0 >= i0);

  test = (h1 == h2);

  test = (h1 == (__fp16)1.0);

  test = (h1 == f1);

  test = (f1 == h1);

  test = (i0 == h0);

  test = (h0 == i0);

  test = (h1 != h2);

  test = (h1 != (__fp16)1.0);

  test = (h1 != f1);

  test = (f1 != h1);

  test = (i0 != h0);

  test = (h0 != i0);

  h1 = (h1 ? h2 : h0);

  // Check assignments (inc. compound)
  // xATIVE-HALF: store {{.*}} half 0xHC000 // FIXME: We should be folding here.
  h0 = h1;

  h0 = (__fp16)-2.0f;

  h0 = f0;

  h0 = i0;

  i0 = h0;

  h0 += h1;

  h0 += (__fp16)1.0f;

  h0 += f2;

  i0 += h0;

  h0 += i0;

  h0 -= h1;

  h0 -= (__fp16)1.0;

  h0 -= f2;

  i0 -= h0;

  h0 -= i0;

  h0 *= h1;

  h0 *= (__fp16)1.0;

  h0 *= f2;

  i0 *= h0;

  h0 *= i0;

  h0 /= h1;

  h0 /= (__fp16)1.0;

  h0 /= f2;

  i0 /= h0;

  h0 /= i0;

  // Check conversions to/from double
  h0 = d0;

  h0 = (float)d0;

  d0 = h0;

  d0 = (float)h0;

  h0 = s0;
}


// NOTNATIVE-LABEL: define dso_local void @testTypeDef(
// NOTNATIVE-SAME: ) #[[ATTR0]] {
// NOTNATIVE-NEXT:  [[ENTRY:.*:]]
// NOTNATIVE-NEXT:    [[T0:%.*]] = alloca <4 x half>, align 8
// NOTNATIVE-NEXT:    [[T1:%.*]] = alloca <4 x half>, align 8
// NOTNATIVE-NEXT:    [[TMP0:%.*]] = load <4 x half>, ptr [[T0]], align 8
// NOTNATIVE-NEXT:    [[CONV:%.*]] = call <4 x float> @llvm.fpext.v4f32.v4f16(<4 x half> [[TMP0]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[TMP1:%.*]] = load <4 x half>, ptr [[T1]], align 8
// NOTNATIVE-NEXT:    [[CONV1:%.*]] = call <4 x float> @llvm.fpext.v4f32.v4f16(<4 x half> [[TMP1]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[ADD:%.*]] = call <4 x float> @llvm.fadd.v4f32(<4 x float> [[CONV]], <4 x float> [[CONV1]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    [[CONV2:%.*]] = call <4 x half> @llvm.fptrunc.v4f16.v4f32(<4 x float> [[ADD]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NOTNATIVE-NEXT:    store <4 x half> [[CONV2]], ptr [[T1]], align 8
// NOTNATIVE-NEXT:    ret void
//
// NATIVE-HALF-LABEL: define dso_local void @testTypeDef(
// NATIVE-HALF-SAME: ) #[[ATTR0]] {
// NATIVE-HALF-NEXT:  [[ENTRY:.*:]]
// NATIVE-HALF-NEXT:    [[T0:%.*]] = alloca <4 x half>, align 8
// NATIVE-HALF-NEXT:    [[T1:%.*]] = alloca <4 x half>, align 8
// NATIVE-HALF-NEXT:    [[TMP0:%.*]] = load <4 x half>, ptr [[T0]], align 8
// NATIVE-HALF-NEXT:    [[TMP1:%.*]] = load <4 x half>, ptr [[T1]], align 8
// NATIVE-HALF-NEXT:    [[ADD:%.*]] = call <4 x half> @llvm.fadd.v4f16(<4 x half> [[TMP0]], <4 x half> [[TMP1]]) #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// NATIVE-HALF-NEXT:    store <4 x half> [[ADD]], ptr [[T1]], align 8
// NATIVE-HALF-NEXT:    ret void
//
void testTypeDef() {
  __fp16 t0 __attribute__((vector_size(8)));
  float16_t t1 __attribute__((vector_size(8)));
  t1 = t0 + t1;
}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
