// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -ffp-exception-behavior=ignore -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=FCMP
// RUN: %clang_cc1 -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=EXCEPT
// RUN: %clang_cc1 -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=MAYTRAP
// RUN: %clang_cc1 -frounding-math -ffp-exception-behavior=ignore -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=IGNORE
// RUN: %clang_cc1 -frounding-math -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=FCMP
// RUN: %clang_cc1 -frounding-math -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=MAYTRAP-RND

// FCMP-LABEL: define dso_local zeroext i1 @QuietEqual(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp oeq double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietEqual(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietEqual(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietEqual(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietEqual(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietEqual(double f1, double f2) {

  return f1 == f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp une double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietNotEqual(double f1, double f2) {

  return f1 != f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingLess(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp olt double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingLess(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingLess(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingLess(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingLess(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingLess(double f1, double f2) {

  return f1 < f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ole double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingLessEqual(double f1, double f2) {

  return f1 <= f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingGreater(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ogt double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingGreater(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingGreater(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingGreater(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingGreater(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingGreater(double f1, double f2) {

  return f1 > f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp oge double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingGreaterEqual(double f1, double f2) {

  return f1 >= f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietLess(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp olt double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietLess(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietLess(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietLess(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietLess(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietLess(double f1, double f2) {

  return __builtin_isless(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ole double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietLessEqual(double f1, double f2) {

  return __builtin_islessequal(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietGreater(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ogt double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietGreater(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietGreater(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietGreater(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietGreater(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietGreater(double f1, double f2) {

  return __builtin_isgreater(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp oge double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietGreaterEqual(double f1, double f2) {

  return __builtin_isgreaterequal(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp one double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietLessGreater(double f1, double f2) {

  return __builtin_islessgreater(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietUnordered(
// FCMP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// FCMP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// FCMP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// FCMP-NEXT:    [[CMP:%.*]] = fcmp uno double [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietUnordered(
// EXCEPT-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// EXCEPT-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// EXCEPT-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietUnordered(
// MAYTRAP-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietUnordered(
// IGNORE-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// IGNORE-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// IGNORE-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietUnordered(
// MAYTRAP-RND-SAME: double noundef [[F1:%.*]], double noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca double, align 8
// MAYTRAP-RND-NEXT:    store double [[F1]], ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    store double [[F2]], ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load double, ptr [[F1_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load double, ptr [[F2_ADDR]], align 8
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f64(double [[TMP0]], double [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietUnordered(double f1, double f2) {

  return __builtin_isunordered(f1, f2);

}

//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
