// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -ffp-exception-behavior=ignore -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=FCMP
// RUN: %clang_cc1 -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=EXCEPT
// RUN: %clang_cc1 -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=MAYTRAP
// RUN: %clang_cc1 -frounding-math -ffp-exception-behavior=ignore -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=IGNORE
// RUN: %clang_cc1 -frounding-math -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=FCMP
// RUN: %clang_cc1 -frounding-math -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=CHECK -check-prefix=MAYTRAP-RND

// FCMP-LABEL: define dso_local zeroext i1 @QuietEqual(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp oeq float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietEqual(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietEqual(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietEqual(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietEqual(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0:[0-9]+]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oeq") #[[ATTR2:[0-9]+]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietEqual(float f1, float f2) {

  return f1 == f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp une float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietNotEqual(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"une") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietNotEqual(float f1, float f2) {

  return f1 != f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingLess(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp olt float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingLess(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingLess(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingLess(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingLess(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingLess(float f1, float f2) {

  return f1 < f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ole float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingLessEqual(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingLessEqual(float f1, float f2) {

  return f1 <= f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingGreater(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ogt float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingGreater(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingGreater(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingGreater(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingGreater(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingGreater(float f1, float f2) {

  return f1 > f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp oge float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @SignalingGreaterEqual(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool SignalingGreaterEqual(float f1, float f2) {

  return f1 >= f2;

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietLess(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp olt float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietLess(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietLess(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietLess(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietLess(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"olt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietLess(float f1, float f2) {

  return __builtin_isless(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ole float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietLessEqual(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ole") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietLessEqual(float f1, float f2) {

  return __builtin_islessequal(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietGreater(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp ogt float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietGreater(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietGreater(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietGreater(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietGreater(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"ogt") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietGreater(float f1, float f2) {

  return __builtin_isgreater(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp oge float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietGreaterEqual(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"oge") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietGreaterEqual(float f1, float f2) {

  return __builtin_isgreaterequal(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp one float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietLessGreater(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"one") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietLessGreater(float f1, float f2) {

  return __builtin_islessgreater(f1, f2);

}

// FCMP-LABEL: define dso_local zeroext i1 @QuietUnordered(
// FCMP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// FCMP-NEXT:  [[ENTRY:.*:]]
// FCMP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// FCMP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// FCMP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// FCMP-NEXT:    [[CMP:%.*]] = fcmp uno float [[TMP0]], [[TMP1]]
// FCMP-NEXT:    ret i1 [[CMP]]
//
// EXCEPT-LABEL: define dso_local zeroext i1 @QuietUnordered(
// EXCEPT-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// EXCEPT-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// EXCEPT-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-LABEL: define dso_local zeroext i1 @QuietUnordered(
// MAYTRAP-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    ret i1 [[CMP]]
//
// IGNORE-LABEL: define dso_local zeroext i1 @QuietUnordered(
// IGNORE-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// IGNORE-NEXT:  [[ENTRY:.*:]]
// IGNORE-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// IGNORE-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// IGNORE-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// IGNORE-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.except"(metadata !"ignore") ]
// IGNORE-NEXT:    ret i1 [[CMP]]
//
// MAYTRAP-RND-LABEL: define dso_local zeroext i1 @QuietUnordered(
// MAYTRAP-RND-SAME: float noundef [[F1:%.*]], float noundef [[F2:%.*]]) #[[ATTR0]] {
// MAYTRAP-RND-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-RND-NEXT:    [[F1_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    [[F2_ADDR:%.*]] = alloca float, align 4
// MAYTRAP-RND-NEXT:    store float [[F1]], ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    store float [[F2]], ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[F1_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[F2_ADDR]], align 4
// MAYTRAP-RND-NEXT:    [[CMP:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP0]], float [[TMP1]], metadata !"uno") #[[ATTR2]] [ "fp.except"(metadata !"maytrap") ]
// MAYTRAP-RND-NEXT:    ret i1 [[CMP]]
//
_Bool QuietUnordered(float f1, float f2) {

  return __builtin_isunordered(f1, f2);

}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
