// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -x c++ -fexceptions -fcxx-exceptions -frounding-math -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=FPMODELSTRICT
// RUN: %clang_cc1 -x c++ -ffp-contract=fast -fexceptions -fcxx-exceptions -emit-llvm -o - %s | FileCheck %s -check-prefix=PRECISE
// RUN: %clang_cc1 -x c++ -ffast-math -fexceptions -fcxx-exceptions -ffp-contract=fast -emit-llvm -o - %s | FileCheck %s -check-prefix=FAST
// RUN: %clang_cc1 -x c++ -ffast-math -fexceptions -fcxx-exceptions -emit-llvm -o - %s | FileCheck %s -check-prefix=FASTNOCONTRACT
// RUN: %clang_cc1 -x c++ -ffast-math -fexceptions -fcxx-exceptions -ffp-contract=fast -ffp-exception-behavior=ignore -emit-llvm -o - %s | FileCheck %s -check-prefix=FAST
// RUN: %clang_cc1 -x c++ -ffast-math -fexceptions -fcxx-exceptions -ffp-contract=fast -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=EXCEPT
// RUN: %clang_cc1 -x c++ -ffast-math -fexceptions -fcxx-exceptions -ffp-contract=fast -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=MAYTRAP

float f0, f1, f2;

  template <class>
  class aaaa {
   public:
    ~aaaa();
    void b();
  };

  template <class c>
  aaaa<c>::~aaaa() { try {
    b();
  // CHECK-LABEL: define {{.*}}void @_ZN4aaaaIiED2Ev{{.*}}

  } catch (...) {
    // STRICTEXCEPT: fadd float
    // STRICTNOEXCEPT: llvm.fadd.f32(float %{{.*}}, float %{{.*}}) #{{.*}} [ "fp.except"(metadata !"ignore") ]
    f0 = f1 + f2;

    // CHECK: ret void
  }
  }

  class d {
   public:
    d(const char *, int);
    aaaa<int> e;
  };

// FPMODELSTRICT-LABEL: define dso_local noundef float @_Z3foov(
// FPMODELSTRICT-SAME: ) #[[ATTR0:[0-9]+]] {
// FPMODELSTRICT-NEXT:  [[ENTRY:.*:]]
// FPMODELSTRICT-NEXT:    [[X:%.*]] = alloca [[CLASS_D:%.*]], align 1
// FPMODELSTRICT-NEXT:    [[A:%.*]] = alloca [[CLASS_AAAA:%.*]], align 1
// FPMODELSTRICT-NEXT:    call void @_ZN1dC1EPKci(ptr noundef nonnull align 1 dereferenceable(1) [[X]], ptr noundef @.str, i32 noundef 1) #[[ATTR4:[0-9]+]]
// FPMODELSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr @f0, align 4
// FPMODELSTRICT-NEXT:    call void @_ZN4aaaaIiED1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[A]]) #[[ATTR5:[0-9]+]]
// FPMODELSTRICT-NEXT:    call void @_ZN1dD1Ev(ptr noundef nonnull align 1 dead_on_return(1) dereferenceable(1) [[X]]) #[[ATTR5]]
// FPMODELSTRICT-NEXT:    ret float [[TMP0]]
//
// PRECISE-LABEL: define dso_local noundef float @_Z3foov(
// PRECISE-SAME: ) #[[ATTR0:[0-9]+]] {
// PRECISE-NEXT:  [[ENTRY:.*:]]
// PRECISE-NEXT:    [[X:%.*]] = alloca [[CLASS_D:%.*]], align 1
// PRECISE-NEXT:    [[A:%.*]] = alloca [[CLASS_AAAA:%.*]], align 1
// PRECISE-NEXT:    call void @_ZN1dC1EPKci(ptr noundef nonnull align 1 dereferenceable(1) [[X]], ptr noundef @.str, i32 noundef 1)
// PRECISE-NEXT:    [[TMP0:%.*]] = load float, ptr @f0, align 4
// PRECISE-NEXT:    call void @_ZN4aaaaIiED1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[A]]) #[[ATTR4:[0-9]+]]
// PRECISE-NEXT:    call void @_ZN1dD1Ev(ptr noundef nonnull align 1 dead_on_return(1) dereferenceable(1) [[X]]) #[[ATTR4]]
// PRECISE-NEXT:    ret float [[TMP0]]
//
// FAST-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z3foov(
// FAST-SAME: ) #[[ATTR0:[0-9]+]] {
// FAST-NEXT:  [[ENTRY:.*:]]
// FAST-NEXT:    [[X:%.*]] = alloca [[CLASS_D:%.*]], align 1
// FAST-NEXT:    [[A:%.*]] = alloca [[CLASS_AAAA:%.*]], align 1
// FAST-NEXT:    call void @_ZN1dC1EPKci(ptr noundef nonnull align 1 dereferenceable(1) [[X]], ptr noundef @.str, i32 noundef 1)
// FAST-NEXT:    [[TMP0:%.*]] = load float, ptr @f0, align 4
// FAST-NEXT:    call void @_ZN4aaaaIiED1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[A]]) #[[ATTR4:[0-9]+]]
// FAST-NEXT:    call void @_ZN1dD1Ev(ptr noundef nonnull align 1 dead_on_return(1) dereferenceable(1) [[X]]) #[[ATTR4]]
// FAST-NEXT:    ret float [[TMP0]]
//
// FASTNOCONTRACT-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z3foov(
// FASTNOCONTRACT-SAME: ) #[[ATTR0:[0-9]+]] {
// FASTNOCONTRACT-NEXT:  [[ENTRY:.*:]]
// FASTNOCONTRACT-NEXT:    [[X:%.*]] = alloca [[CLASS_D:%.*]], align 1
// FASTNOCONTRACT-NEXT:    [[A:%.*]] = alloca [[CLASS_AAAA:%.*]], align 1
// FASTNOCONTRACT-NEXT:    call void @_ZN1dC1EPKci(ptr noundef nonnull align 1 dereferenceable(1) [[X]], ptr noundef @.str, i32 noundef 1)
// FASTNOCONTRACT-NEXT:    [[TMP0:%.*]] = load float, ptr @f0, align 4
// FASTNOCONTRACT-NEXT:    call void @_ZN4aaaaIiED1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[A]]) #[[ATTR4:[0-9]+]]
// FASTNOCONTRACT-NEXT:    call void @_ZN1dD1Ev(ptr noundef nonnull align 1 dead_on_return(1) dereferenceable(1) [[X]]) #[[ATTR4]]
// FASTNOCONTRACT-NEXT:    ret float [[TMP0]]
//
// EXCEPT-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z3foov(
// EXCEPT-SAME: ) #[[ATTR0:[0-9]+]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[X:%.*]] = alloca [[CLASS_D:%.*]], align 1
// EXCEPT-NEXT:    [[A:%.*]] = alloca [[CLASS_AAAA:%.*]], align 1
// EXCEPT-NEXT:    call void @_ZN1dC1EPKci(ptr noundef nonnull align 1 dereferenceable(1) [[X]], ptr noundef @.str, i32 noundef 1) #[[ATTR5:[0-9]+]]
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr @f0, align 4
// EXCEPT-NEXT:    call void @_ZN4aaaaIiED1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[A]]) #[[ATTR6:[0-9]+]]
// EXCEPT-NEXT:    call void @_ZN1dD1Ev(ptr noundef nonnull align 1 dead_on_return(1) dereferenceable(1) [[X]]) #[[ATTR6]]
// EXCEPT-NEXT:    ret float [[TMP0]]
//
// MAYTRAP-LABEL: define dso_local noundef nofpclass(nan inf) float @_Z3foov(
// MAYTRAP-SAME: ) #[[ATTR0:[0-9]+]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[X:%.*]] = alloca [[CLASS_D:%.*]], align 1
// MAYTRAP-NEXT:    [[A:%.*]] = alloca [[CLASS_AAAA:%.*]], align 1
// MAYTRAP-NEXT:    call void @_ZN1dC1EPKci(ptr noundef nonnull align 1 dereferenceable(1) [[X]], ptr noundef @.str, i32 noundef 1) #[[ATTR5:[0-9]+]]
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr @f0, align 4
// MAYTRAP-NEXT:    call void @_ZN4aaaaIiED1Ev(ptr noundef nonnull align 1 dereferenceable(1) [[A]]) #[[ATTR6:[0-9]+]]
// MAYTRAP-NEXT:    call void @_ZN1dD1Ev(ptr noundef nonnull align 1 dead_on_return(1) dereferenceable(1) [[X]]) #[[ATTR6]]
// MAYTRAP-NEXT:    ret float [[TMP0]]
//
float foo() {
  d x("", 1);
  aaaa<int> a;
  return f0;
}

