// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -frounding-math -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=FPMODELSTRICT
// RUN: %clang_cc1 -ffp-contract=fast -emit-llvm -o - %s | FileCheck %s -check-prefix=PRECISE
// RUN: %clang_cc1 -ffast-math -ffp-contract=fast -emit-llvm -o - %s | FileCheck %s -check-prefix=FAST
// RUN: %clang_cc1 -ffast-math -emit-llvm -o - %s | FileCheck %s -check-prefix=FASTNOCONTRACT
// RUN: %clang_cc1 -ffast-math -ffp-contract=fast -ffp-exception-behavior=ignore -emit-llvm -o - %s | FileCheck %s -check-prefix=FAST
// RUN: %clang_cc1 -ffast-math -ffp-contract=fast -ffp-exception-behavior=strict -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=EXCEPT
// RUN: %clang_cc1 -ffast-math -ffp-contract=fast -ffp-exception-behavior=maytrap -fexperimental-strict-floating-point -emit-llvm -o - %s | FileCheck %s -check-prefix=MAYTRAP

float f0, f1, f2;

// FPMODELSTRICT-LABEL: define dso_local void @foo(
// FPMODELSTRICT-SAME: ) #[[ATTR0:[0-9]+]] {
// FPMODELSTRICT-NEXT:  [[ENTRY:.*:]]
// FPMODELSTRICT-NEXT:    [[TMP0:%.*]] = load float, ptr @f1, align 4
// FPMODELSTRICT-NEXT:    [[TMP1:%.*]] = load float, ptr @f2, align 4
// FPMODELSTRICT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// FPMODELSTRICT-NEXT:    store float [[ADD]], ptr @f0, align 4
// FPMODELSTRICT-NEXT:    ret void
//
// PRECISE-LABEL: define dso_local void @foo(
// PRECISE-SAME: ) #[[ATTR0:[0-9]+]] {
// PRECISE-NEXT:  [[ENTRY:.*:]]
// PRECISE-NEXT:    [[TMP0:%.*]] = load float, ptr @f1, align 4
// PRECISE-NEXT:    [[TMP1:%.*]] = load float, ptr @f2, align 4
// PRECISE-NEXT:    [[ADD:%.*]] = fadd contract float [[TMP0]], [[TMP1]]
// PRECISE-NEXT:    store float [[ADD]], ptr @f0, align 4
// PRECISE-NEXT:    ret void
//
// FAST-LABEL: define dso_local void @foo(
// FAST-SAME: ) #[[ATTR0:[0-9]+]] {
// FAST-NEXT:  [[ENTRY:.*:]]
// FAST-NEXT:    [[TMP0:%.*]] = load float, ptr @f1, align 4
// FAST-NEXT:    [[TMP1:%.*]] = load float, ptr @f2, align 4
// FAST-NEXT:    [[ADD:%.*]] = fadd fast float [[TMP0]], [[TMP1]]
// FAST-NEXT:    store float [[ADD]], ptr @f0, align 4
// FAST-NEXT:    ret void
//
// FASTNOCONTRACT-LABEL: define dso_local void @foo(
// FASTNOCONTRACT-SAME: ) #[[ATTR0:[0-9]+]] {
// FASTNOCONTRACT-NEXT:  [[ENTRY:.*:]]
// FASTNOCONTRACT-NEXT:    [[TMP0:%.*]] = load float, ptr @f1, align 4
// FASTNOCONTRACT-NEXT:    [[TMP1:%.*]] = load float, ptr @f2, align 4
// FASTNOCONTRACT-NEXT:    [[ADD:%.*]] = fadd reassoc nnan ninf nsz arcp afn float [[TMP0]], [[TMP1]]
// FASTNOCONTRACT-NEXT:    store float [[ADD]], ptr @f0, align 4
// FASTNOCONTRACT-NEXT:    ret void
//
// EXCEPT-LABEL: define dso_local void @foo(
// EXCEPT-SAME: ) #[[ATTR0:[0-9]+]] {
// EXCEPT-NEXT:  [[ENTRY:.*:]]
// EXCEPT-NEXT:    [[TMP0:%.*]] = load float, ptr @f1, align 4
// EXCEPT-NEXT:    [[TMP1:%.*]] = load float, ptr @f2, align 4
// EXCEPT-NEXT:    [[ADD:%.*]] = call fast float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// EXCEPT-NEXT:    store float [[ADD]], ptr @f0, align 4
// EXCEPT-NEXT:    ret void
//
// MAYTRAP-LABEL: define dso_local void @foo(
// MAYTRAP-SAME: ) #[[ATTR0:[0-9]+]] {
// MAYTRAP-NEXT:  [[ENTRY:.*:]]
// MAYTRAP-NEXT:    [[TMP0:%.*]] = load float, ptr @f1, align 4
// MAYTRAP-NEXT:    [[TMP1:%.*]] = load float, ptr @f2, align 4
// MAYTRAP-NEXT:    [[ADD:%.*]] = call fast float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// MAYTRAP-NEXT:    store float [[ADD]], ptr @f0, align 4
// MAYTRAP-NEXT:    ret void
//
void foo(void) {
  f0 = f1 + f2;
}
