// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// RUN: %clang_cc1 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: define dso_local i8 @func1n(
// CHECK-SAME: i8 noundef [[FPM8:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[FPM8_ADDR:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[F1N:%.*]] = alloca [10 x i8], align 1
// CHECK-NEXT:    store i8 [[FPM8]], ptr [[FPM8_ADDR]], align 1
// CHECK-NEXT:    [[TMP0:%.*]] = load i8, ptr [[FPM8_ADDR]], align 1
// CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [10 x i8], ptr [[F1N]], i64 0, i64 2
// CHECK-NEXT:    store i8 [[TMP0]], ptr [[ARRAYIDX]], align 1
// CHECK-NEXT:    [[ARRAYIDX1:%.*]] = getelementptr inbounds [10 x i8], ptr [[F1N]], i64 0, i64 2
// CHECK-NEXT:    [[TMP1:%.*]] = load i8, ptr [[ARRAYIDX1]], align 1
// CHECK-NEXT:    ret i8 [[TMP1]]
//
__fpm8 func1n(__fpm8 fpm8) {
  __fpm8 f1n[10];
  f1n[2] = fpm8;
  return f1n[2];
}



