// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-attributes
// RUN: %clang_cc1 -O1 -triple spirv64 %s -emit-llvm -o - | FileCheck %s --check-prefix=SPIRV64
// RUN: %clang_cc1 -O1 -triple spirv64-amd-amdhsa %s -emit-llvm -o - | FileCheck %s --check-prefix=AMDHSA
// RUN: %clang_cc1 -O1 -triple nvptx64 -emit-llvm %s -o - | FileCheck %s --check-prefix=NVPTX
// RUN: %clang_cc1 -O1 -triple amdgcn -emit-llvm %s -o - | FileCheck %s --check-prefix=AMDGCN

#include <stdint.h>

// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @num_blocks_x(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.x()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @num_blocks_x(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.num.blocks.x()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @num_blocks_x(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.x()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @num_blocks_x(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.x()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t num_blocks_x(void) {
  return __builtin_gpu_num_blocks_x();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @num_blocks_y(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.y()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @num_blocks_y(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.num.blocks.y()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @num_blocks_y(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.y()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @num_blocks_y(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.y()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t num_blocks_y(void) {
  return __builtin_gpu_num_blocks_y();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @num_blocks_z(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.z()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @num_blocks_z(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.num.blocks.z()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @num_blocks_z(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.z()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @num_blocks_z(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.blocks.z()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t num_blocks_z(void) {
  return __builtin_gpu_num_blocks_z();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @block_id_x(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.x()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @block_id_x(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.block.id.x()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @block_id_x(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.x()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @block_id_x(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.x()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t block_id_x(void) {
  return __builtin_gpu_block_id_x();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @block_id_y(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.y()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @block_id_y(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.block.id.y()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @block_id_y(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.y()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @block_id_y(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.y()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t block_id_y(void) {
  return __builtin_gpu_block_id_y();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @block_id_z(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.z()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @block_id_z(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.block.id.z()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @block_id_z(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.z()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @block_id_z(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.block.id.z()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t block_id_z(void) {
  return __builtin_gpu_block_id_z();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @num_threads_x(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.x()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @num_threads_x(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.num.threads.x()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @num_threads_x(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.x()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @num_threads_x(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.x()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t num_threads_x(void) {
  return __builtin_gpu_num_threads_x();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @num_threads_y(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.y()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @num_threads_y(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.num.threads.y()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @num_threads_y(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.y()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @num_threads_y(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.y()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t num_threads_y(void) {
  return __builtin_gpu_num_threads_y();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @num_threads_z(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.z()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @num_threads_z(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.num.threads.z()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @num_threads_z(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.z()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @num_threads_z(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.threads.z()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t num_threads_z(void) {
  return __builtin_gpu_num_threads_z();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @thread_id_x(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.x()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @thread_id_x(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.thread.id.x()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @thread_id_x(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.x()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @thread_id_x(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.x()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t thread_id_x(void) {
  return __builtin_gpu_thread_id_x();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @thread_id_y(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.y()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @thread_id_y(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.thread.id.y()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @thread_id_y(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.y()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @thread_id_y(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.y()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t thread_id_y(void) {
  return __builtin_gpu_thread_id_y();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @thread_id_z(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.z()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @thread_id_z(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.thread.id.z()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @thread_id_z(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.z()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @thread_id_z(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.thread.id.z()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t thread_id_z(void) {
  return __builtin_gpu_thread_id_z();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @num_lanes(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.lanes()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @num_lanes(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.num.lanes()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @num_lanes(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.lanes()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @num_lanes(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.num.lanes()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t num_lanes(void) {
  return __builtin_gpu_num_lanes();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @lane_id(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.lane.id()
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @lane_id(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.lane.id()
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @lane_id(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.lane.id()
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @lane_id(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.lane.id()
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
uint32_t lane_id(void) {
  return __builtin_gpu_lane_id();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @lane_mask(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.gpu.lane.mask()
// SPIRV64-NEXT:    ret i64 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @lane_mask(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i64 @llvm.gpu.lane.mask()
// AMDHSA-NEXT:    ret i64 [[TMP0]]
//
// NVPTX: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @lane_mask(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.gpu.lane.mask()
// NVPTX-NEXT:    ret i64 [[TMP0]]
//
// AMDGCN: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @lane_mask(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.gpu.lane.mask()
// AMDGCN-NEXT:    ret i64 [[TMP0]]
//
uint64_t lane_mask(void) {
  return __builtin_gpu_lane_mask();
}


uint32_t
// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @read_first_lane_u32(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.read.first.lane.u32(i64 [[__LANE_MASK:%.*]], i32 [[__X:%.*]])
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @read_first_lane_u32(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.read.first.lane.u32(i64 [[__LANE_MASK:%.*]], i32 [[__X:%.*]])
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @read_first_lane_u32(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.read.first.lane.u32(i64 [[__LANE_MASK:%.*]], i32 [[__X:%.*]])
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @read_first_lane_u32(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.read.first.lane.u32(i64 [[__LANE_MASK:%.*]], i32 [[__X:%.*]])
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
read_first_lane_u32(uint64_t __lane_mask, uint32_t __x) {
  return __builtin_gpu_read_first_lane_u32(__lane_mask, __x);
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @ballot(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.gpu.ballot(i64 [[__LANE_MASK:%.*]], i1 [[__X:%.*]])
// SPIRV64-NEXT:    ret i64 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @ballot(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i64 @llvm.gpu.ballot(i64 [[__LANE_MASK:%.*]], i1 [[__X:%.*]])
// AMDHSA-NEXT:    ret i64 [[TMP0]]
//
// NVPTX: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @ballot(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.gpu.ballot(i64 [[__LANE_MASK:%.*]], i1 [[__X:%.*]])
// NVPTX-NEXT:    ret i64 [[TMP0]]
//
// AMDGCN: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @ballot(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i64 @llvm.gpu.ballot(i64 [[__LANE_MASK:%.*]], i1 [[__X:%.*]])
// AMDGCN-NEXT:    ret i64 [[TMP0]]
//
uint64_t ballot(uint64_t __lane_mask,
                            _Bool __x) {
  return __builtin_gpu_ballot(__lane_mask, __x);
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
// SPIRV64-LABEL: @sync_threads(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    tail call void @llvm.gpu.sync.threads()
// SPIRV64-NEXT:    ret void
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
// AMDHSA-LABEL: @sync_threads(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    tail call addrspace(4) void @llvm.gpu.sync.threads()
// AMDHSA-NEXT:    ret void
//
// NVPTX: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn
// NVPTX-LABEL: @sync_threads(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    tail call void @llvm.gpu.sync.threads()
// NVPTX-NEXT:    ret void
//
// AMDGCN: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn
// AMDGCN-LABEL: @sync_threads(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    tail call void @llvm.gpu.sync.threads()
// AMDGCN-NEXT:    ret void
//
void sync_threads(void) {
  return __builtin_gpu_sync_threads();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
// SPIRV64-LABEL: @sync_lane(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    tail call void @llvm.gpu.sync.lane(i64 [[__LANE_MASK:%.*]])
// SPIRV64-NEXT:    ret void
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
// AMDHSA-LABEL: @sync_lane(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    tail call addrspace(4) void @llvm.gpu.sync.lane(i64 [[__LANE_MASK:%.*]])
// AMDHSA-NEXT:    ret void
//
// NVPTX: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn
// NVPTX-LABEL: @sync_lane(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    tail call void @llvm.gpu.sync.lane(i64 [[__LANE_MASK:%.*]])
// NVPTX-NEXT:    ret void
//
// AMDGCN: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn
// AMDGCN-LABEL: @sync_lane(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    tail call void @llvm.gpu.sync.lane(i64 [[__LANE_MASK:%.*]])
// AMDGCN-NEXT:    ret void
//
void sync_lane(uint64_t __lane_mask) {
  return __builtin_gpu_sync_lane(__lane_mask);
}


uint32_t
// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// SPIRV64-LABEL: @shuffle_idx_u32(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.shuffle.idx.u32(i64 [[__LANE_MASK:%.*]], i32 [[__IDX:%.*]], i32 [[__X:%.*]], i32 [[__WIDTH:%.*]])
// SPIRV64-NEXT:    ret i32 [[TMP0]]
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDHSA-LABEL: @shuffle_idx_u32(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    [[TMP0:%.*]] = tail call addrspace(4) i32 @llvm.gpu.shuffle.idx.u32(i64 [[__LANE_MASK:%.*]], i32 [[__IDX:%.*]], i32 [[__X:%.*]], i32 [[__WIDTH:%.*]])
// AMDHSA-NEXT:    ret i32 [[TMP0]]
//
// NVPTX: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// NVPTX-LABEL: @shuffle_idx_u32(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.shuffle.idx.u32(i64 [[__LANE_MASK:%.*]], i32 [[__IDX:%.*]], i32 [[__X:%.*]], i32 [[__WIDTH:%.*]])
// NVPTX-NEXT:    ret i32 [[TMP0]]
//
// AMDGCN: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
// AMDGCN-LABEL: @shuffle_idx_u32(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    [[TMP0:%.*]] = tail call i32 @llvm.gpu.shuffle.idx.u32(i64 [[__LANE_MASK:%.*]], i32 [[__IDX:%.*]], i32 [[__X:%.*]], i32 [[__WIDTH:%.*]])
// AMDGCN-NEXT:    ret i32 [[TMP0]]
//
shuffle_idx_u32(uint64_t __lane_mask, uint32_t __idx, uint32_t __x,
                      uint32_t __width) {
  return __builtin_gpu_shuffle_idx_u32(__lane_mask, __idx, __x, __width);
}

// SPIRV64: Function Attrs: nofree norecurse noreturn nosync nounwind
// SPIRV64-LABEL: @gpu_exit(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    tail call void @llvm.gpu.exit()
// SPIRV64-NEXT:    unreachable
//
// AMDHSA: Function Attrs: nofree norecurse noreturn nosync nounwind
// AMDHSA-LABEL: @gpu_exit(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    tail call addrspace(4) void @llvm.gpu.exit()
// AMDHSA-NEXT:    unreachable
//
// NVPTX: Function Attrs: convergent nofree norecurse noreturn nosync nounwind
// NVPTX-LABEL: @gpu_exit(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    tail call void @llvm.gpu.exit()
// NVPTX-NEXT:    unreachable
//
// AMDGCN: Function Attrs: convergent nofree norecurse noreturn nosync nounwind
// AMDGCN-LABEL: @gpu_exit(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    tail call void @llvm.gpu.exit()
// AMDGCN-NEXT:    unreachable
//
void gpu_exit(void) {
  return __builtin_gpu_exit();
}


// SPIRV64: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
// SPIRV64-LABEL: @thread_suspend(
// SPIRV64-NEXT:  entry:
// SPIRV64-NEXT:    tail call void @llvm.gpu.thread.suspend()
// SPIRV64-NEXT:    ret void
//
// AMDHSA: Function Attrs: mustprogress nofree norecurse nosync nounwind willreturn
// AMDHSA-LABEL: @thread_suspend(
// AMDHSA-NEXT:  entry:
// AMDHSA-NEXT:    tail call addrspace(4) void @llvm.gpu.thread.suspend()
// AMDHSA-NEXT:    ret void
//
// NVPTX: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn
// NVPTX-LABEL: @thread_suspend(
// NVPTX-NEXT:  entry:
// NVPTX-NEXT:    tail call void @llvm.gpu.thread.suspend()
// NVPTX-NEXT:    ret void
//
// AMDGCN: Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn
// AMDGCN-LABEL: @thread_suspend(
// AMDGCN-NEXT:  entry:
// AMDGCN-NEXT:    tail call void @llvm.gpu.thread.suspend()
// AMDGCN-NEXT:    ret void
//
void thread_suspend(void) {
  return __builtin_gpu_thread_suspend();
}
