// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals none --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm -o - %s -O1 -disable-llvm-passes | FileCheck %s
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm -o - %s -O1 -disable-llvm-passes -fexceptions | FileCheck %s --check-prefix=EXCEPTIONS

struct Trivial {
  int x[100];
};


// CHECK-LABEL: define dso_local void @cleanup(
// CHECK-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8, !tbaa [[INTPTR_TBAA6:![0-9]+]]
// CHECK-NEXT:    ret void
//
// EXCEPTIONS-LABEL: define dso_local void @cleanup(
// EXCEPTIONS-SAME: ptr noundef [[P:%.*]]) #[[ATTR0:[0-9]+]] {
// EXCEPTIONS-NEXT:  [[ENTRY:.*:]]
// EXCEPTIONS-NEXT:    [[P_ADDR:%.*]] = alloca ptr, align 8
// EXCEPTIONS-NEXT:    store ptr [[P]], ptr [[P_ADDR]], align 8, !tbaa [[INTPTR_TBAA6:![0-9]+]]
// EXCEPTIONS-NEXT:    ret void
//
void cleanup(int *p) {}
void func(struct Trivial t);
struct Trivial gen(void);

// CHECK-LABEL: define dso_local void @test(
// CHECK-SAME: ) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[X:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_TRIVIAL:%.*]], align 8
// CHECK-NEXT:    [[AGG_TMP1:%.*]] = alloca [[STRUCT_TRIVIAL]], align 8
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[X]]) #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[AGG_TMP]]) #[[ATTR3]]
// CHECK-NEXT:    call void @gen(ptr dead_on_unwind writable sret([[STRUCT_TRIVIAL]]) align 4 [[AGG_TMP]])
// CHECK-NEXT:    call void @func(ptr noundef byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP]])
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[AGG_TMP]]) #[[ATTR3]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[AGG_TMP1]]) #[[ATTR3]]
// CHECK-NEXT:    call void @gen(ptr dead_on_unwind writable sret([[STRUCT_TRIVIAL]]) align 4 [[AGG_TMP1]])
// CHECK-NEXT:    call void @func(ptr noundef byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP1]])
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[AGG_TMP1]]) #[[ATTR3]]
// CHECK-NEXT:    call void @cleanup(ptr noundef [[X]])
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[X]]) #[[ATTR3]]
// CHECK-NEXT:    ret void
//
// EXCEPTIONS-LABEL: define dso_local void @test(
// EXCEPTIONS-SAME: ) #[[ATTR1:[0-9]+]] personality ptr @__gcc_personality_v0 {
// EXCEPTIONS-NEXT:  [[ENTRY:.*:]]
// EXCEPTIONS-NEXT:    [[X:%.*]] = alloca i32, align 4
// EXCEPTIONS-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_TRIVIAL:%.*]], align 8
// EXCEPTIONS-NEXT:    [[EXN_SLOT:%.*]] = alloca ptr, align 8
// EXCEPTIONS-NEXT:    [[EHSELECTOR_SLOT:%.*]] = alloca i32, align 4
// EXCEPTIONS-NEXT:    [[AGG_TMP3:%.*]] = alloca [[STRUCT_TRIVIAL]], align 8
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.start.p0(ptr [[X]]) #[[ATTR4:[0-9]+]]
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.start.p0(ptr [[AGG_TMP]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    invoke void @gen(ptr dead_on_unwind writable sret([[STRUCT_TRIVIAL]]) align 4 [[AGG_TMP]])
// EXCEPTIONS-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[LPAD1:.*]]
// EXCEPTIONS:       [[INVOKE_CONT]]:
// EXCEPTIONS-NEXT:    invoke void @func(ptr noundef byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP]])
// EXCEPTIONS-NEXT:            to label %[[INVOKE_CONT2:.*]] unwind label %[[LPAD1]]
// EXCEPTIONS:       [[INVOKE_CONT2]]:
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.end.p0(ptr [[AGG_TMP]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.start.p0(ptr [[AGG_TMP3]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    invoke void @gen(ptr dead_on_unwind writable sret([[STRUCT_TRIVIAL]]) align 4 [[AGG_TMP3]])
// EXCEPTIONS-NEXT:            to label %[[INVOKE_CONT5:.*]] unwind label %[[LPAD4:.*]]
// EXCEPTIONS:       [[INVOKE_CONT5]]:
// EXCEPTIONS-NEXT:    invoke void @func(ptr noundef byval([[STRUCT_TRIVIAL]]) align 8 [[AGG_TMP3]])
// EXCEPTIONS-NEXT:            to label %[[INVOKE_CONT6:.*]] unwind label %[[LPAD4]]
// EXCEPTIONS:       [[INVOKE_CONT6]]:
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.end.p0(ptr [[AGG_TMP3]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    call void @cleanup(ptr noundef [[X]])
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.end.p0(ptr [[X]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    ret void
// EXCEPTIONS:       [[LPAD:.*:]]
// EXCEPTIONS-NEXT:    [[TMP0:%.*]] = landingpad { ptr, i32 }
// EXCEPTIONS-NEXT:            cleanup
// EXCEPTIONS-NEXT:    [[TMP1:%.*]] = extractvalue { ptr, i32 } [[TMP0]], 0
// EXCEPTIONS-NEXT:    store ptr [[TMP1]], ptr [[EXN_SLOT]], align 8
// EXCEPTIONS-NEXT:    [[TMP2:%.*]] = extractvalue { ptr, i32 } [[TMP0]], 1
// EXCEPTIONS-NEXT:    store i32 [[TMP2]], ptr [[EHSELECTOR_SLOT]], align 4
// EXCEPTIONS-NEXT:    br label %[[EHCLEANUP7:.*]]
// EXCEPTIONS:       [[LPAD1]]:
// EXCEPTIONS-NEXT:    [[TMP3:%.*]] = landingpad { ptr, i32 }
// EXCEPTIONS-NEXT:            cleanup
// EXCEPTIONS-NEXT:    [[TMP4:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 0
// EXCEPTIONS-NEXT:    store ptr [[TMP4]], ptr [[EXN_SLOT]], align 8
// EXCEPTIONS-NEXT:    [[TMP5:%.*]] = extractvalue { ptr, i32 } [[TMP3]], 1
// EXCEPTIONS-NEXT:    store i32 [[TMP5]], ptr [[EHSELECTOR_SLOT]], align 4
// EXCEPTIONS-NEXT:    br label %[[EHCLEANUP:.*]]
// EXCEPTIONS:       [[LPAD4]]:
// EXCEPTIONS-NEXT:    [[TMP6:%.*]] = landingpad { ptr, i32 }
// EXCEPTIONS-NEXT:            cleanup
// EXCEPTIONS-NEXT:    [[TMP7:%.*]] = extractvalue { ptr, i32 } [[TMP6]], 0
// EXCEPTIONS-NEXT:    store ptr [[TMP7]], ptr [[EXN_SLOT]], align 8
// EXCEPTIONS-NEXT:    [[TMP8:%.*]] = extractvalue { ptr, i32 } [[TMP6]], 1
// EXCEPTIONS-NEXT:    store i32 [[TMP8]], ptr [[EHSELECTOR_SLOT]], align 4
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.end.p0(ptr [[AGG_TMP3]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    br label %[[EHCLEANUP]]
// EXCEPTIONS:       [[EHCLEANUP]]:
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.end.p0(ptr [[AGG_TMP]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    br label %[[EHCLEANUP7]]
// EXCEPTIONS:       [[EHCLEANUP7]]:
// EXCEPTIONS-NEXT:    call void @cleanup(ptr noundef [[X]])
// EXCEPTIONS-NEXT:    call void @llvm.lifetime.end.p0(ptr [[X]]) #[[ATTR4]]
// EXCEPTIONS-NEXT:    br label %[[EH_RESUME:.*]]
// EXCEPTIONS:       [[EH_RESUME]]:
// EXCEPTIONS-NEXT:    [[EXN:%.*]] = load ptr, ptr [[EXN_SLOT]], align 8
// EXCEPTIONS-NEXT:    [[SEL:%.*]] = load i32, ptr [[EHSELECTOR_SLOT]], align 4
// EXCEPTIONS-NEXT:    [[LPAD_VAL:%.*]] = insertvalue { ptr, i32 } poison, ptr [[EXN]], 0
// EXCEPTIONS-NEXT:    [[LPAD_VAL9:%.*]] = insertvalue { ptr, i32 } [[LPAD_VAL]], i32 [[SEL]], 1
// EXCEPTIONS-NEXT:    resume { ptr, i32 } [[LPAD_VAL9]]
//
void test() {
  int x __attribute__((cleanup(cleanup)));

  func(gen());
  func(gen());
}
