// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --check-globals none --version 6
// RUN: %clang_cc1 -O2 -emit-llvm -disable-llvm-passes %s -o - | FileCheck %s

struct {
} __trans_tmp_85;
struct bkey_s_c {
} bch2_trans_update_extent_k;
int bch2_trans_update_extent_k_0;
struct bkey_s_c bch2_btree_iter_peek_max();
// CHECK-LABEL: define dso_local void @bch2_trans_update_extent(
// CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[DONE:%.*]] = alloca i8, align 1
// CHECK-NEXT:    [[TMP:%.*]] = alloca [[STRUCT_BKEY_S_C:%.*]], align 1
// CHECK-NEXT:    [[AGG_TMP:%.*]] = alloca [[STRUCT_ANON:%.*]], align 1
// CHECK-NEXT:    [[UNDEF_AGG_TMP:%.*]] = alloca [[STRUCT_BKEY_S_C]], align 1
// CHECK-NEXT:    [[CLEANUP_DEST_SLOT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[DONE]]) #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[TMP]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr [[AGG_TMP]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 1 [[AGG_TMP]], ptr align 1 @__trans_tmp_85, i64 0, i1 false), !tbaa.struct [[TBAA_STRUCT6:![0-9]+]]
// CHECK-NEXT:    call void (...) @bch2_btree_iter_peek_max()
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[AGG_TMP]]) #[[ATTR4]]
// CHECK-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 1 @bch2_trans_update_extent_k, ptr align 1 [[UNDEF_AGG_TMP]], i64 0, i1 false), !tbaa.struct [[TBAA_STRUCT6]]
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[TMP]]) #[[ATTR4]]
// CHECK-NEXT:    [[TMP0:%.*]] = load i32, ptr @bch2_trans_update_extent_k_0, align 4, !tbaa [[INT_TBAA2:![0-9]+]]
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP0]], 0
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    store i32 2, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP:.*]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    store i32 0, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP]]
// CHECK:       [[CLEANUP]]:
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr [[DONE]]) #[[ATTR4]]
// CHECK-NEXT:    [[CLEANUP_DEST:%.*]] = load i32, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    switch i32 [[CLEANUP_DEST]], label %[[UNREACHABLE:.*]] [
// CHECK-NEXT:      i32 0, label %[[CLEANUP_CONT:.*]]
// CHECK-NEXT:      i32 2, label %[[ERR:.*]]
// CHECK-NEXT:    ]
// CHECK:       [[CLEANUP_CONT]]:
// CHECK-NEXT:    br label %[[ERR]]
// CHECK:       [[ERR]]:
// CHECK-NEXT:    ret void
// CHECK:       [[UNREACHABLE]]:
// CHECK-NEXT:    unreachable
//
void bch2_trans_update_extent() {
  {
    _Bool done;
    bch2_trans_update_extent_k = bch2_btree_iter_peek_max((0, __trans_tmp_85));
    if (bch2_trans_update_extent_k_0)
      goto err;
  }
err:
}

