// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -fexperimental-strict-floating-point -ffp-exception-behavior=strict -triple %itanium_abi_triple -emit-llvm %s -o - | FileCheck --check-prefixes=CHECK,STRICT %s
// RUN: %clang_cc1 -fexperimental-strict-floating-point -frounding-math -ffp-exception-behavior=strict -triple %itanium_abi_triple -emit-llvm %s -o - | FileCheck --check-prefixes=CHECK,STRICT-RND %s
// RUN: %clang_cc1 -fexperimental-strict-floating-point -ffp-exception-behavior=strict -triple %itanium_abi_triple -emit-llvm %s -o - -fms-extensions -DMS | FileCheck --check-prefixes=CHECK,STRICT %s
// RUN: %clang_cc1 -fexperimental-strict-floating-point -frounding-math -ffp-exception-behavior=strict -triple %itanium_abi_triple -emit-llvm %s -o - -fms-extensions -DMS | FileCheck --check-prefixes=CHECK,STRICT-RND %s
// RUN: %clang_cc1 -fexperimental-strict-floating-point -triple %itanium_abi_triple -emit-llvm %s -o - | FileCheck --check-prefixes=CHECK,DEFAULT %s
// RUN: %clang_cc1 -fexperimental-strict-floating-point -frounding-math -triple %itanium_abi_triple -emit-llvm %s -o - | FileCheck --check-prefixes=CHECK,DEFAULT-RND %s

// STRICT-LABEL: define dso_local float @func_00(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0:[0-9]+]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_00(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0:[0-9]+]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_00(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0:[0-9]+]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_00(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0:[0-9]+]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7:[0-9]+]] [ "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_00(float x, float y) {
  return x + y;
}


#ifdef MS
#pragma fenv_access (on)
#else
#pragma STDC FENV_ACCESS ON
#endif

// STRICT-LABEL: define dso_local float @func_01(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_01(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_01(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1:[0-9]+]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_01(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_01(float x, float y) {
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_02(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_02(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6:[0-9]+]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_02(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7:[0-9]+]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_02(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_02(float x, float y) {
  #pragma float_control(except, off)
  #pragma STDC FENV_ACCESS OFF
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_03(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_03(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_03(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_03(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_03(float x, float y) {
  return x + y;
}


#ifdef MS
#pragma fenv_access (off)
#else
#pragma STDC FENV_ACCESS OFF
#endif

// STRICT-LABEL: define dso_local float @func_04(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_04(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_04(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_04(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR2:[0-9]+]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_04(float x, float y) {
  #pragma float_control(except, off)
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_04a(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_04a(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_04a(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_04a(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_04a(float x, float y) {
  #pragma float_control(except, on)
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_05(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_05(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_05(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_05(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_05(float x, float y) {
  #pragma STDC FENV_ACCESS ON
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_06(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_06(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_06(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_06(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR2]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_06(float x, float y) {
  #pragma float_control(except, off)
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_07(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP2:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TOBOOL:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP2]], float 0.000000e+00, metadata !"une") #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// STRICT:       [[IF_THEN]]:
// STRICT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[MUL:%.*]] = fmul float [[TMP3]], 2.000000e+00
// STRICT-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    br label %[[IF_END]]
// STRICT:       [[IF_END]]:
// STRICT-NEXT:    [[TMP4:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP4]], float 4.000000e+00) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_07(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TOBOOL:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP2]], float 0.000000e+00, metadata !"une") #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// STRICT-RND:       [[IF_THEN]]:
// STRICT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[MUL:%.*]] = fmul float [[TMP3]], 2.000000e+00
// STRICT-RND-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    br label %[[IF_END]]
// STRICT-RND:       [[IF_END]]:
// STRICT-RND-NEXT:    [[TMP4:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP4]], float 4.000000e+00) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_07(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP2:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TOBOOL:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP2]], float 0.000000e+00, metadata !"une") #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// DEFAULT:       [[IF_THEN]]:
// DEFAULT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[MUL:%.*]] = fmul float [[TMP3]], 2.000000e+00
// DEFAULT-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    br label %[[IF_END]]
// DEFAULT:       [[IF_END]]:
// DEFAULT-NEXT:    [[TMP4:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP4]], float 4.000000e+00) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_07(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TOBOOL:%.*]] = call i1 @llvm.fcmp.f32(float [[TMP2]], float 0.000000e+00, metadata !"une") #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    br i1 [[TOBOOL]], label %[[IF_THEN:.*]], label %[[IF_END:.*]]
// DEFAULT-RND:       [[IF_THEN]]:
// DEFAULT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[MUL:%.*]] = fmul float [[TMP3]], 2.000000e+00
// DEFAULT-RND-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    br label %[[IF_END]]
// DEFAULT-RND:       [[IF_END]]:
// DEFAULT-RND-NEXT:    [[TMP4:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP4]], float 4.000000e+00) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_07(float x, float y) {
  x -= y;
  if (x) {
    #pragma STDC FENV_ACCESS ON
    y *= 2.0F;
  }
  return y + 4.0F;
}


// STRICT-LABEL: define dso_local float @func_08(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtp") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_08(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtp") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_08(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtp") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_08(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtp") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_08(float x, float y) {
  #pragma STDC FENV_ROUND FE_UPWARD
  #pragma STDC FENV_ACCESS ON
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_09(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_09(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_09(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_09(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_09(float x, float y) {
  #pragma STDC FENV_ROUND FE_TONEAREST
  #pragma STDC FENV_ACCESS ON
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_10(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_10(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_10(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_10(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_10(float x, float y) {
  #pragma STDC FENV_ROUND FE_TONEAREST
  #pragma clang fp exceptions(ignore)
  #pragma STDC FENV_ACCESS ON
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_11(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_11(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_11(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_11(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR2]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_11(float x, float y) {
  #pragma STDC FENV_ROUND FE_TONEAREST
  #pragma clang fp exceptions(ignore)
  #pragma STDC FENV_ACCESS OFF
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_12(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.except"(metadata !"maytrap") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_12(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.except"(metadata !"maytrap") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_12(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.except"(metadata !"maytrap") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_12(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.except"(metadata !"maytrap") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_12(float x, float y) {
  #pragma clang fp exceptions(maytrap)
  #pragma STDC FENV_ACCESS ON
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_13(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtp"), "fp.except"(metadata !"maytrap") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_13(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtp"), "fp.except"(metadata !"maytrap") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_13(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtp"), "fp.except"(metadata !"maytrap") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_13(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtp"), "fp.except"(metadata !"maytrap") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_13(float x, float y) {
  #pragma clang fp exceptions(maytrap)
  #pragma STDC FENV_ROUND FE_UPWARD
  #pragma STDC FENV_ACCESS ON
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_14(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[RES:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[MUL:%.*]] = fmul float [[TMP0]], [[TMP1]]
// STRICT-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// STRICT-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// STRICT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_14(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[RES:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[MUL:%.*]] = fmul float [[TMP0]], [[TMP1]]
// STRICT-RND-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// STRICT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// STRICT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_14(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[RES:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[MUL:%.*]] = fmul float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// DEFAULT-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// DEFAULT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_14(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[RES:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[MUL:%.*]] = fmul float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// DEFAULT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// DEFAULT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_14(float x, float y, float z) {
  #pragma STDC FENV_ACCESS ON
  float res = x * y;
  {
    #pragma STDC FENV_ACCESS OFF
    return res + z;
  }
}


// STRICT-LABEL: define dso_local float @func_15(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[RES:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtz") ]
// STRICT-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// STRICT-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// STRICT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR6]] [ "fp.control"(metadata !"rtz") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_15(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[RES:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtz") ]
// STRICT-RND-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// STRICT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// STRICT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR6]] [ "fp.control"(metadata !"rtz") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_15(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[RES:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtz") ]
// DEFAULT-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// DEFAULT-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// DEFAULT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR7]] [ "fp.control"(metadata !"rtz"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_15(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[RES:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtz") ]
// DEFAULT-RND-NEXT:    store float [[MUL]], ptr [[RES]], align 4
// DEFAULT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[RES]], align 4
// DEFAULT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Z_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP2]], float [[TMP3]]) #[[ATTR7]] [ "fp.control"(metadata !"rtz"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_15(float x, float y, float z) {
  #pragma STDC FENV_ROUND FE_TOWARDZERO
  #pragma STDC FENV_ACCESS ON
  float res = x * y;
  {
    #pragma STDC FENV_ACCESS OFF
    return res + z;
  }
}


// STRICT-LABEL: define dso_local float @func_16(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP2:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP2]], float 2.000000e+00) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = fadd float [[TMP3]], 4.000000e+00
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_16(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP2]], float 2.000000e+00) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP3]], 4.000000e+00
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_16(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP2:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP2]], float 2.000000e+00) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// DEFAULT-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP3]], 4.000000e+00
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_16(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[SUB:%.*]] = call float @llvm.fsub.f32(float [[TMP1]], float [[TMP0]]) #[[ATTR7]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    store float [[SUB]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP2:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[MUL:%.*]] = call float @llvm.fmul.f32(float [[TMP2]], float 2.000000e+00) #[[ATTR7]] [ "fp.control"(metadata !"rte") ]
// DEFAULT-RND-NEXT:    store float [[MUL]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP3:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP3]], 4.000000e+00
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_16(float x, float y) {
  x -= y;
  {
    #pragma STDC FENV_ROUND FE_TONEAREST
    #pragma STDC FENV_ACCESS ON
    y *= 2.0F;
  }
  {
    #pragma STDC FENV_ACCESS ON
    return y + 4.0F;
  }
}


// STRICT-LABEL: define dso_local float @func_17(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_17(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_17(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_17(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_17(float x, float y) {
  #pragma STDC FENV_ROUND FE_DYNAMIC
  #pragma STDC FENV_ACCESS ON
  return x + y;
}


// STRICT-LABEL: define dso_local float @func_18(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_18(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_18(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_18(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR2]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_18(float x, float y) {
  #pragma STDC FENV_ROUND FE_DYNAMIC
  return x + y;
}

#pragma STDC FENV_ACCESS ON
// STRICT-LABEL: define dso_local float @func_19(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_19(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_19(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR1]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_19(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_19(float x, float y) {
  return x + y;
}

#pragma STDC FENV_ACCESS OFF
// STRICT-LABEL: define dso_local float @func_20(
// STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-NEXT:    ret float [[ADD]]
//
// STRICT-RND-LABEL: define dso_local float @func_20(
// STRICT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// STRICT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// STRICT-RND-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte") ]
// STRICT-RND-NEXT:    ret float [[ADD]]
//
// DEFAULT-LABEL: define dso_local float @func_20(
// DEFAULT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR0]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-NEXT:    ret float [[ADD]]
//
// DEFAULT-RND-LABEL: define dso_local float @func_20(
// DEFAULT-RND-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]]) #[[ATTR2]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// DEFAULT-RND-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// DEFAULT-RND-NEXT:    [[ADD:%.*]] = fadd float [[TMP0]], [[TMP1]]
// DEFAULT-RND-NEXT:    ret float [[ADD]]
//
float func_20(float x, float y) {
  return x + y;
}

typedef double vector4double __attribute__((__vector_size__(32)));
typedef float  vector4float  __attribute__((__vector_size__(16)));
// STRICT-LABEL: define dso_local <4 x float> @func_21(
// STRICT-SAME: ptr noundef byval(<4 x double>) align 32 [[TMP0:%.*]]) #[[ATTR2:[0-9]+]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca <4 x double>, align 32
// STRICT-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[TMP0]], align 32
// STRICT-NEXT:    store <4 x double> [[X]], ptr [[X_ADDR]], align 32
// STRICT-NEXT:    [[TMP1:%.*]] = load <4 x double>, ptr [[X_ADDR]], align 32
// STRICT-NEXT:    [[CONV:%.*]] = call <4 x float> @llvm.fptrunc.v4f32.v4f64(<4 x double> [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtp") ]
// STRICT-NEXT:    ret <4 x float> [[CONV]]
//
// STRICT-RND-LABEL: define dso_local <4 x float> @func_21(
// STRICT-RND-SAME: ptr noundef byval(<4 x double>) align 32 [[TMP0:%.*]]) #[[ATTR2:[0-9]+]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <4 x double>, align 32
// STRICT-RND-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[TMP0]], align 32
// STRICT-RND-NEXT:    store <4 x double> [[X]], ptr [[X_ADDR]], align 32
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load <4 x double>, ptr [[X_ADDR]], align 32
// STRICT-RND-NEXT:    [[CONV:%.*]] = call <4 x float> @llvm.fptrunc.v4f32.v4f64(<4 x double> [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtp") ]
// STRICT-RND-NEXT:    ret <4 x float> [[CONV]]
//
// DEFAULT-LABEL: define dso_local <4 x float> @func_21(
// DEFAULT-SAME: ptr noundef byval(<4 x double>) align 32 [[TMP0:%.*]]) #[[ATTR3:[0-9]+]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca <4 x double>, align 32
// DEFAULT-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[TMP0]], align 32
// DEFAULT-NEXT:    store <4 x double> [[X]], ptr [[X_ADDR]], align 32
// DEFAULT-NEXT:    [[TMP1:%.*]] = load <4 x double>, ptr [[X_ADDR]], align 32
// DEFAULT-NEXT:    [[CONV:%.*]] = call <4 x float> @llvm.fptrunc.v4f32.v4f64(<4 x double> [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtp"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret <4 x float> [[CONV]]
//
// DEFAULT-RND-LABEL: define dso_local <4 x float> @func_21(
// DEFAULT-RND-SAME: ptr noundef byval(<4 x double>) align 32 [[TMP0:%.*]]) #[[ATTR3:[0-9]+]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <4 x double>, align 32
// DEFAULT-RND-NEXT:    [[X:%.*]] = load <4 x double>, ptr [[TMP0]], align 32
// DEFAULT-RND-NEXT:    store <4 x double> [[X]], ptr [[X_ADDR]], align 32
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load <4 x double>, ptr [[X_ADDR]], align 32
// DEFAULT-RND-NEXT:    [[CONV:%.*]] = call <4 x float> @llvm.fptrunc.v4f32.v4f64(<4 x double> [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtp"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret <4 x float> [[CONV]]
//
vector4float func_21(vector4double x) {
  #pragma STDC FENV_ROUND FE_UPWARD
  return __builtin_convertvector(x, vector4float);
}

typedef short vector8short __attribute__((__vector_size__(16)));
typedef double vector8double __attribute__((__vector_size__(64)));
// STRICT-LABEL: define dso_local <8 x double> @func_24(
// STRICT-SAME: <8 x i16> noundef [[X:%.*]]) #[[ATTR3:[0-9]+]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// STRICT-NEXT:    store <8 x i16> [[X]], ptr [[X_ADDR]], align 16
// STRICT-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[X_ADDR]], align 16
// STRICT-NEXT:    [[CONV:%.*]] = call <8 x double> @llvm.sitofp.v8f64.v8i16(<8 x i16> [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rtz") ]
// STRICT-NEXT:    ret <8 x double> [[CONV]]
//
// STRICT-RND-LABEL: define dso_local <8 x double> @func_24(
// STRICT-RND-SAME: <8 x i16> noundef [[X:%.*]]) #[[ATTR3:[0-9]+]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// STRICT-RND-NEXT:    store <8 x i16> [[X]], ptr [[X_ADDR]], align 16
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[X_ADDR]], align 16
// STRICT-RND-NEXT:    [[CONV:%.*]] = call <8 x double> @llvm.sitofp.v8f64.v8i16(<8 x i16> [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rtz") ]
// STRICT-RND-NEXT:    ret <8 x double> [[CONV]]
//
// DEFAULT-LABEL: define dso_local <8 x double> @func_24(
// DEFAULT-SAME: <8 x i16> noundef [[X:%.*]]) #[[ATTR4:[0-9]+]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// DEFAULT-NEXT:    store <8 x i16> [[X]], ptr [[X_ADDR]], align 16
// DEFAULT-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[X_ADDR]], align 16
// DEFAULT-NEXT:    [[CONV:%.*]] = call <8 x double> @llvm.sitofp.v8f64.v8i16(<8 x i16> [[TMP0]]) #[[ATTR7]] [ "fp.control"(metadata !"rtz"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret <8 x double> [[CONV]]
//
// DEFAULT-RND-LABEL: define dso_local <8 x double> @func_24(
// DEFAULT-RND-SAME: <8 x i16> noundef [[X:%.*]]) #[[ATTR4:[0-9]+]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <8 x i16>, align 16
// DEFAULT-RND-NEXT:    store <8 x i16> [[X]], ptr [[X_ADDR]], align 16
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load <8 x i16>, ptr [[X_ADDR]], align 16
// DEFAULT-RND-NEXT:    [[CONV:%.*]] = call <8 x double> @llvm.sitofp.v8f64.v8i16(<8 x i16> [[TMP0]]) #[[ATTR7]] [ "fp.control"(metadata !"rtz"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret <8 x double> [[CONV]]
//
vector8double func_24(vector8short x) {
  #pragma STDC FENV_ROUND FE_TOWARDZERO
  return __builtin_convertvector(x, vector8double);
}

typedef unsigned int vector16uint __attribute__((__vector_size__(64)));
typedef double vector16double __attribute__((__vector_size__(128)));
// STRICT-LABEL: define dso_local <16 x double> @func_25(
// STRICT-SAME: ptr noundef byval(<16 x i32>) align 64 [[TMP0:%.*]]) #[[ATTR4:[0-9]+]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// STRICT-NEXT:    [[X:%.*]] = load <16 x i32>, ptr [[TMP0]], align 64
// STRICT-NEXT:    store <16 x i32> [[X]], ptr [[X_ADDR]], align 64
// STRICT-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr [[X_ADDR]], align 64
// STRICT-NEXT:    [[CONV:%.*]] = call <16 x double> @llvm.uitofp.v16f64.v16i32(<16 x i32> [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtn") ]
// STRICT-NEXT:    ret <16 x double> [[CONV]]
//
// STRICT-RND-LABEL: define dso_local <16 x double> @func_25(
// STRICT-RND-SAME: ptr noundef byval(<16 x i32>) align 64 [[TMP0:%.*]]) #[[ATTR4:[0-9]+]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// STRICT-RND-NEXT:    [[X:%.*]] = load <16 x i32>, ptr [[TMP0]], align 64
// STRICT-RND-NEXT:    store <16 x i32> [[X]], ptr [[X_ADDR]], align 64
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr [[X_ADDR]], align 64
// STRICT-RND-NEXT:    [[CONV:%.*]] = call <16 x double> @llvm.uitofp.v16f64.v16i32(<16 x i32> [[TMP1]]) #[[ATTR6]] [ "fp.control"(metadata !"rtn") ]
// STRICT-RND-NEXT:    ret <16 x double> [[CONV]]
//
// DEFAULT-LABEL: define dso_local <16 x double> @func_25(
// DEFAULT-SAME: ptr noundef byval(<16 x i32>) align 64 [[TMP0:%.*]]) #[[ATTR5:[0-9]+]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// DEFAULT-NEXT:    [[X:%.*]] = load <16 x i32>, ptr [[TMP0]], align 64
// DEFAULT-NEXT:    store <16 x i32> [[X]], ptr [[X_ADDR]], align 64
// DEFAULT-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr [[X_ADDR]], align 64
// DEFAULT-NEXT:    [[CONV:%.*]] = call <16 x double> @llvm.uitofp.v16f64.v16i32(<16 x i32> [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtn"), "fp.except"(metadata !"ignore") ]
// DEFAULT-NEXT:    ret <16 x double> [[CONV]]
//
// DEFAULT-RND-LABEL: define dso_local <16 x double> @func_25(
// DEFAULT-RND-SAME: ptr noundef byval(<16 x i32>) align 64 [[TMP0:%.*]]) #[[ATTR5:[0-9]+]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <16 x i32>, align 64
// DEFAULT-RND-NEXT:    [[X:%.*]] = load <16 x i32>, ptr [[TMP0]], align 64
// DEFAULT-RND-NEXT:    store <16 x i32> [[X]], ptr [[X_ADDR]], align 64
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load <16 x i32>, ptr [[X_ADDR]], align 64
// DEFAULT-RND-NEXT:    [[CONV:%.*]] = call <16 x double> @llvm.uitofp.v16f64.v16i32(<16 x i32> [[TMP1]]) #[[ATTR7]] [ "fp.control"(metadata !"rtn"), "fp.except"(metadata !"ignore") ]
// DEFAULT-RND-NEXT:    ret <16 x double> [[CONV]]
//
vector16double func_25(vector16uint x) {
  #pragma STDC FENV_ROUND FE_DOWNWARD
  return __builtin_convertvector(x, vector16double);
}

typedef float vector2float __attribute__((__vector_size__(8)));
typedef char vector2char __attribute__((__vector_size__(2)));
// STRICT-LABEL: define dso_local i16 @func_22(
// STRICT-SAME: double noundef [[X_COERCE:%.*]]) #[[ATTR0]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// STRICT-NEXT:    [[X:%.*]] = alloca <2 x float>, align 8
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca <2 x float>, align 8
// STRICT-NEXT:    store double [[X_COERCE]], ptr [[X]], align 8
// STRICT-NEXT:    [[X1:%.*]] = load <2 x float>, ptr [[X]], align 8
// STRICT-NEXT:    store <2 x float> [[X1]], ptr [[X_ADDR]], align 8
// STRICT-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[X_ADDR]], align 8
// STRICT-NEXT:    [[CONV:%.*]] = call <2 x i8> @llvm.fptosi.v2i8.v2f32(<2 x float> [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-NEXT:    store <2 x i8> [[CONV]], ptr [[RETVAL]], align 2
// STRICT-NEXT:    [[TMP1:%.*]] = load i16, ptr [[RETVAL]], align 2
// STRICT-NEXT:    ret i16 [[TMP1]]
//
// STRICT-RND-LABEL: define dso_local i16 @func_22(
// STRICT-RND-SAME: double noundef [[X_COERCE:%.*]]) #[[ATTR0]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// STRICT-RND-NEXT:    [[X:%.*]] = alloca <2 x float>, align 8
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <2 x float>, align 8
// STRICT-RND-NEXT:    store double [[X_COERCE]], ptr [[X]], align 8
// STRICT-RND-NEXT:    [[X1:%.*]] = load <2 x float>, ptr [[X]], align 8
// STRICT-RND-NEXT:    store <2 x float> [[X1]], ptr [[X_ADDR]], align 8
// STRICT-RND-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[X_ADDR]], align 8
// STRICT-RND-NEXT:    [[CONV:%.*]] = call <2 x i8> @llvm.fptosi.v2i8.v2f32(<2 x float> [[TMP0]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-RND-NEXT:    store <2 x i8> [[CONV]], ptr [[RETVAL]], align 2
// STRICT-RND-NEXT:    [[TMP1:%.*]] = load i16, ptr [[RETVAL]], align 2
// STRICT-RND-NEXT:    ret i16 [[TMP1]]
//
// DEFAULT-LABEL: define dso_local i16 @func_22(
// DEFAULT-SAME: double noundef [[X_COERCE:%.*]]) #[[ATTR0]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// DEFAULT-NEXT:    [[X:%.*]] = alloca <2 x float>, align 8
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca <2 x float>, align 8
// DEFAULT-NEXT:    store double [[X_COERCE]], ptr [[X]], align 8
// DEFAULT-NEXT:    [[X1:%.*]] = load <2 x float>, ptr [[X]], align 8
// DEFAULT-NEXT:    store <2 x float> [[X1]], ptr [[X_ADDR]], align 8
// DEFAULT-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[X_ADDR]], align 8
// DEFAULT-NEXT:    [[CONV:%.*]] = fptosi <2 x float> [[TMP0]] to <2 x i8>
// DEFAULT-NEXT:    store <2 x i8> [[CONV]], ptr [[RETVAL]], align 2
// DEFAULT-NEXT:    [[TMP1:%.*]] = load i16, ptr [[RETVAL]], align 2
// DEFAULT-NEXT:    ret i16 [[TMP1]]
//
// DEFAULT-RND-LABEL: define dso_local i16 @func_22(
// DEFAULT-RND-SAME: double noundef [[X_COERCE:%.*]]) #[[ATTR2]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[RETVAL:%.*]] = alloca <2 x i8>, align 2
// DEFAULT-RND-NEXT:    [[X:%.*]] = alloca <2 x float>, align 8
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <2 x float>, align 8
// DEFAULT-RND-NEXT:    store double [[X_COERCE]], ptr [[X]], align 8
// DEFAULT-RND-NEXT:    [[X1:%.*]] = load <2 x float>, ptr [[X]], align 8
// DEFAULT-RND-NEXT:    store <2 x float> [[X1]], ptr [[X_ADDR]], align 8
// DEFAULT-RND-NEXT:    [[TMP0:%.*]] = load <2 x float>, ptr [[X_ADDR]], align 8
// DEFAULT-RND-NEXT:    [[CONV:%.*]] = fptosi <2 x float> [[TMP0]] to <2 x i8>
// DEFAULT-RND-NEXT:    store <2 x i8> [[CONV]], ptr [[RETVAL]], align 2
// DEFAULT-RND-NEXT:    [[TMP1:%.*]] = load i16, ptr [[RETVAL]], align 2
// DEFAULT-RND-NEXT:    ret i16 [[TMP1]]
//
vector2char func_22(vector2float x) {
  #pragma float_control(except, off)
  return __builtin_convertvector(x, vector2char);
}

typedef float vector3float __attribute__((__vector_size__(12)));
typedef unsigned long long vector3ulong __attribute__((__vector_size__(24)));
// STRICT-LABEL: define dso_local <3 x i64> @func_23(
// STRICT-SAME: <3 x float> noundef [[X:%.*]]) #[[ATTR5:[0-9]+]] {
// STRICT-NEXT:  [[ENTRY:.*:]]
// STRICT-NEXT:    [[X_ADDR:%.*]] = alloca <3 x float>, align 16
// STRICT-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[X]], <3 x float> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// STRICT-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[X_ADDR]], align 16
// STRICT-NEXT:    [[LOADVECN:%.*]] = load <4 x float>, ptr [[X_ADDR]], align 16
// STRICT-NEXT:    [[EXTRACTVEC1:%.*]] = shufflevector <4 x float> [[LOADVECN]], <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
// STRICT-NEXT:    [[CONV:%.*]] = call <3 x i64> @llvm.fptoui.v3i64.v3f32(<3 x float> [[EXTRACTVEC1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-NEXT:    ret <3 x i64> [[CONV]]
//
// STRICT-RND-LABEL: define dso_local <3 x i64> @func_23(
// STRICT-RND-SAME: <3 x float> noundef [[X:%.*]]) #[[ATTR5:[0-9]+]] {
// STRICT-RND-NEXT:  [[ENTRY:.*:]]
// STRICT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <3 x float>, align 16
// STRICT-RND-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[X]], <3 x float> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// STRICT-RND-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[X_ADDR]], align 16
// STRICT-RND-NEXT:    [[LOADVECN:%.*]] = load <4 x float>, ptr [[X_ADDR]], align 16
// STRICT-RND-NEXT:    [[EXTRACTVEC1:%.*]] = shufflevector <4 x float> [[LOADVECN]], <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
// STRICT-RND-NEXT:    [[CONV:%.*]] = call <3 x i64> @llvm.fptoui.v3i64.v3f32(<3 x float> [[EXTRACTVEC1]]) #[[ATTR6]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// STRICT-RND-NEXT:    ret <3 x i64> [[CONV]]
//
// DEFAULT-LABEL: define dso_local <3 x i64> @func_23(
// DEFAULT-SAME: <3 x float> noundef [[X:%.*]]) #[[ATTR6:[0-9]+]] {
// DEFAULT-NEXT:  [[ENTRY:.*:]]
// DEFAULT-NEXT:    [[X_ADDR:%.*]] = alloca <3 x float>, align 16
// DEFAULT-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[X]], <3 x float> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// DEFAULT-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[X_ADDR]], align 16
// DEFAULT-NEXT:    [[LOADVECN:%.*]] = load <4 x float>, ptr [[X_ADDR]], align 16
// DEFAULT-NEXT:    [[EXTRACTVEC1:%.*]] = shufflevector <4 x float> [[LOADVECN]], <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
// DEFAULT-NEXT:    [[CONV:%.*]] = fptoui <3 x float> [[EXTRACTVEC1]] to <3 x i64>
// DEFAULT-NEXT:    ret <3 x i64> [[CONV]]
//
// DEFAULT-RND-LABEL: define dso_local <3 x i64> @func_23(
// DEFAULT-RND-SAME: <3 x float> noundef [[X:%.*]]) #[[ATTR6:[0-9]+]] {
// DEFAULT-RND-NEXT:  [[ENTRY:.*:]]
// DEFAULT-RND-NEXT:    [[X_ADDR:%.*]] = alloca <3 x float>, align 16
// DEFAULT-RND-NEXT:    [[EXTRACTVEC:%.*]] = shufflevector <3 x float> [[X]], <3 x float> undef, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
// DEFAULT-RND-NEXT:    store <4 x float> [[EXTRACTVEC]], ptr [[X_ADDR]], align 16
// DEFAULT-RND-NEXT:    [[LOADVECN:%.*]] = load <4 x float>, ptr [[X_ADDR]], align 16
// DEFAULT-RND-NEXT:    [[EXTRACTVEC1:%.*]] = shufflevector <4 x float> [[LOADVECN]], <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
// DEFAULT-RND-NEXT:    [[CONV:%.*]] = fptoui <3 x float> [[EXTRACTVEC1]] to <3 x i64>
// DEFAULT-RND-NEXT:    ret <3 x i64> [[CONV]]
//
vector3ulong func_23(vector3float x) {
  #pragma float_control(except, off)
  return __builtin_convertvector(x, vector3ulong);
}
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CHECK: {{.*}}
