// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-llvm -o - %s | FileCheck --check-prefix=CHECK-DEF %s
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -ffp-exception-behavior=strict -emit-llvm -o - %s | FileCheck --check-prefix=CHECK-STRICT %s

// REQUIRES: x86-registered-target

// CHECK-DEF-LABEL: define dso_local noundef float @_Z7func_01fff(
// CHECK-DEF-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-DEF-NEXT:  [[ENTRY:.*:]]
// CHECK-DEF-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-DEF-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-DEF-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-DEF-NEXT:    [[RES:%.*]] = alloca float, align 4
// CHECK-DEF-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-DEF-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-DEF-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-DEF-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-DEF-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-DEF-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"ignore") ]
// CHECK-DEF-NEXT:    store float [[ADD]], ptr [[RES]], align 4
// CHECK-DEF-NEXT:    [[TMP2:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-DEF-NEXT:    [[TMP3:%.*]] = load float, ptr [[RES]], align 4
// CHECK-DEF-NEXT:    [[ADD1:%.*]] = call float @llvm.fadd.f32(float [[TMP3]], float [[TMP2]]) #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// CHECK-DEF-NEXT:    store float [[ADD1]], ptr [[RES]], align 4
// CHECK-DEF-NEXT:    [[TMP4:%.*]] = load float, ptr [[RES]], align 4
// CHECK-DEF-NEXT:    ret float [[TMP4]]
//
// CHECK-STRICT-LABEL: define dso_local noundef float @_Z7func_01fff(
// CHECK-STRICT-SAME: float noundef [[X:%.*]], float noundef [[Y:%.*]], float noundef [[Z:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-STRICT-NEXT:  [[ENTRY:.*:]]
// CHECK-STRICT-NEXT:    [[X_ADDR:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[Y_ADDR:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[Z_ADDR:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    [[RES:%.*]] = alloca float, align 4
// CHECK-STRICT-NEXT:    store float [[X]], ptr [[X_ADDR]], align 4
// CHECK-STRICT-NEXT:    store float [[Y]], ptr [[Y_ADDR]], align 4
// CHECK-STRICT-NEXT:    store float [[Z]], ptr [[Z_ADDR]], align 4
// CHECK-STRICT-NEXT:    [[TMP0:%.*]] = load float, ptr [[X_ADDR]], align 4
// CHECK-STRICT-NEXT:    [[TMP1:%.*]] = load float, ptr [[Y_ADDR]], align 4
// CHECK-STRICT-NEXT:    [[ADD:%.*]] = call float @llvm.fadd.f32(float [[TMP0]], float [[TMP1]]) #[[ATTR2:[0-9]+]] [ "fp.control"(metadata !"rte") ]
// CHECK-STRICT-NEXT:    store float [[ADD]], ptr [[RES]], align 4
// CHECK-STRICT-NEXT:    [[TMP2:%.*]] = load float, ptr [[Z_ADDR]], align 4
// CHECK-STRICT-NEXT:    [[TMP3:%.*]] = load float, ptr [[RES]], align 4
// CHECK-STRICT-NEXT:    [[ADD1:%.*]] = call float @llvm.fadd.f32(float [[TMP3]], float [[TMP2]]) #[[ATTR2]] [ "fp.control"(metadata !"rte"), "fp.except"(metadata !"maytrap") ]
// CHECK-STRICT-NEXT:    store float [[ADD1]], ptr [[RES]], align 4
// CHECK-STRICT-NEXT:    [[TMP4:%.*]] = load float, ptr [[RES]], align 4
// CHECK-STRICT-NEXT:    ret float [[TMP4]]
//
float func_01(float x, float y, float z) {
  float res = x + y;
  {
#pragma clang fp exceptions(maytrap)
    res += z;
  }
  return res;
}

