// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// RUN: %clang_cc1 -O1 -emit-llvm -fsanitize=signed-integer-overflow -fsanitize-trap=signed-integer-overflow %s -o - | FileCheck %s
// RUN: %clang_cc1 -O1 -emit-llvm -fsanitize=signed-integer-overflow -fsanitize-trap=signed-integer-overflow -mllvm -remove-traps-random-rate=1 %s -o - | FileCheck %s --implicit-check-not="call void @llvm.ubsantrap" --check-prefixes=REMOVE

// CHECK-LABEL: define dso_local noundef i32 @test(
// CHECK-SAME: i32 noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[X]], i32 123), !nosanitize [[META2:![0-9]+]]
// CHECK-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i1 } [[TMP0]], 1, !nosanitize [[META2]]
// CHECK-NEXT:    br i1 [[TMP1]], label [[TRAP:%.*]], label [[CONT:%.*]], !nosanitize [[META2]]
// CHECK:       trap:
// CHECK-NEXT:    tail call void @llvm.ubsantrap(i8 0) #[[ATTR5:[0-9]+]], !nosanitize [[META2]]
// CHECK-NEXT:    unreachable, !nosanitize [[META2]]
// CHECK:       cont:
// CHECK-NEXT:    [[TMP2:%.*]] = extractvalue { i32, i1 } [[TMP0]], 0, !nosanitize [[META2]]
// CHECK-NEXT:    ret i32 [[TMP2]]
//
// REMOVE-LABEL: define dso_local noundef i32 @test(
// REMOVE-SAME: i32 noundef [[X:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// REMOVE-NEXT:  entry:
// REMOVE-NEXT:    [[TMP0:%.*]] = tail call { i32, i1 } @llvm.sadd.with.overflow.i32(i32 [[X]], i32 123), !nosanitize [[META2:![0-9]+]]
// REMOVE-NEXT:    [[TMP1:%.*]] = extractvalue { i32, i1 } [[TMP0]], 1, !nosanitize [[META2]]
// REMOVE-NEXT:    [[TMP2:%.*]] = xor i1 [[TMP1]], true
// REMOVE-NEXT:    tail call void @llvm.assume(i1 [[TMP2]])
// REMOVE-NEXT:    [[TMP3:%.*]] = extractvalue { i32, i1 } [[TMP0]], 0, !nosanitize [[META2]]
// REMOVE-NEXT:    ret i32 [[TMP3]]
//
int test(int x) {
  return x + 123;
}

// CHECK-LABEL: define dso_local noundef i32 @test_runtime(
// CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.allow.runtime.check(metadata [[META3:![0-9]+]])
// CHECK-NEXT:    [[CONV:%.*]] = zext i1 [[TMP0]] to i32
// CHECK-NEXT:    ret i32 [[CONV]]
//
// REMOVE-LABEL: define dso_local noundef i32 @test_runtime(
// REMOVE-SAME: ) local_unnamed_addr #[[ATTR0]] {
// REMOVE-NEXT:  entry:
// REMOVE-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.allow.runtime.check(metadata [[META3:![0-9]+]])
// REMOVE-NEXT:    [[CONV:%.*]] = zext i1 [[TMP0]] to i32
// REMOVE-NEXT:    ret i32 [[CONV]]
//
int test_runtime() {
  return __builtin_allow_runtime_check("mycheck");
}

//.
// CHECK: [[META2]] = !{}
// CHECK: [[META3]] = !{!"mycheck"}
//.
// REMOVE: [[META2]] = !{}
// REMOVE: [[META3]] = !{!"mycheck"}
//.
