// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64-none-linux-gnu -target-feature +zve64d \
// RUN: -target-feature +f -target-feature +d -target-feature +zvfh \
// RUN: -target-feature +zfh -disable-O0-optnone \
// RUN: -mvscale-min=4 -mvscale-max=4 -emit-llvm -o - %s | \
// RUN: opt -S -passes=sroa | FileCheck %s

// REQUIRES: riscv-registered-target

#include <riscv_vector.h>

// ADDITION

// CHECK-LABEL: @add_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[ADD]]
//
vint8m1_t add_i8(vint8m1_t a, vint8m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[ADD]]
//
vint16m1_t add_i16(vint16m1_t a, vint16m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vint32m1_t add_i32(vint32m1_t a, vint32m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[ADD]]
//
vint64m1_t add_i64(vint64m1_t a, vint64m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[ADD]]
//
vuint8m1_t add_u8(vuint8m1_t a, vuint8m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[ADD]]
//
vuint16m1_t add_u16(vuint16m1_t a, vuint16m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vuint32m1_t add_u32(vuint32m1_t a, vuint32m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[ADD]]
//
vuint64m1_t add_u64(vuint64m1_t a, vuint64m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[ADD]]
//
vfloat16m1_t add_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[ADD]]
//
vfloat32m1_t add_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[ADD]]
//
vfloat64m1_t add_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a + b;
}

// CHECK-LABEL: @add_inplace_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[ADD]]
//
vint8m1_t add_inplace_i8(vint8m1_t a, vint8m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[ADD]]
//
vint16m1_t add_inplace_i16(vint16m1_t a, vint16m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vint32m1_t add_inplace_i32(vint32m1_t a, vint32m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[ADD]]
//
vint64m1_t add_inplace_i64(vint64m1_t a, vint64m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[ADD]]
//
vuint8m1_t add_inplace_u8(vuint8m1_t a, vuint8m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[ADD]]
//
vuint16m1_t add_inplace_u16(vuint16m1_t a, vuint16m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vuint32m1_t add_inplace_u32(vuint32m1_t a, vuint32m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[ADD]]
//
vuint64m1_t add_inplace_u64(vuint64m1_t a, vuint64m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[ADD]]
//
vfloat16m1_t add_inplace_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[ADD]]
//
vfloat32m1_t add_inplace_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_inplace_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[ADD]]
//
vfloat64m1_t add_inplace_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a += b;
}

// CHECK-LABEL: @add_scalar_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[ADD]]
//
vint8m1_t add_scalar_i8(vint8m1_t a, int8_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[ADD]]
//
vint16m1_t add_scalar_i16(vint16m1_t a, int16_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vint32m1_t add_scalar_i32(vint32m1_t a, int32_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[ADD]]
//
vint64m1_t add_scalar_i64(vint64m1_t a, int64_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[ADD]]
//
vuint8m1_t add_scalar_u8(vuint8m1_t a, uint8_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[ADD]]
//
vuint16m1_t add_scalar_u16(vuint16m1_t a, uint16_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[ADD]]
//
vuint32m1_t add_scalar_u32(vuint32m1_t a, uint32_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = add <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[ADD]]
//
vuint64m1_t add_scalar_u64(vuint64m1_t a, uint64_t b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x half> poison, half [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x half> [[SPLAT_SPLATINSERT]], <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 4 x half> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[ADD]]
//
vfloat16m1_t add_scalar_f16(vfloat16m1_t a, _Float16 b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x float> poison, float [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x float> [[SPLAT_SPLATINSERT]], <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 2 x float> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[ADD]]
//
vfloat32m1_t add_scalar_f32(vfloat32m1_t a, float b) {
  return a + b;
}

// CHECK-LABEL: @add_scalar_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x double> poison, double [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x double> [[SPLAT_SPLATINSERT]], <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[ADD:%.*]] = fadd <vscale x 1 x double> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[ADD]]
//
vfloat64m1_t add_scalar_f64(vfloat64m1_t a, double b) {
  return a + b;
}

// SUBTRACTION

// CHECK-LABEL: @sub_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SUB]]
//
vint8m1_t sub_i8(vint8m1_t a, vint8m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SUB]]
//
vint16m1_t sub_i16(vint16m1_t a, vint16m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vint32m1_t sub_i32(vint32m1_t a, vint32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SUB]]
//
vint64m1_t sub_i64(vint64m1_t a, vint64m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SUB]]
//
vuint8m1_t sub_u8(vuint8m1_t a, vuint8m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SUB]]
//
vuint16m1_t sub_u16(vuint16m1_t a, vuint16m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vuint32m1_t sub_u32(vuint32m1_t a, vuint32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SUB]]
//
vuint64m1_t sub_u64(vuint64m1_t a, vuint64m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[SUB]]
//
vfloat16m1_t sub_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[SUB]]
//
vfloat32m1_t sub_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[SUB]]
//
vfloat64m1_t sub_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SUB]]
//
vint8m1_t sub_inplace_i8(vint8m1_t a, vint8m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SUB]]
//
vint16m1_t sub_inplace_i16(vint16m1_t a, vint16m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vint32m1_t sub_inplace_i32(vint32m1_t a, vint32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SUB]]
//
vint64m1_t sub_inplace_i64(vint64m1_t a, vint64m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SUB]]
//
vuint8m1_t sub_inplace_u8(vuint8m1_t a, vuint8m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SUB]]
//
vuint16m1_t sub_inplace_u16(vuint16m1_t a, vuint16m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vuint32m1_t sub_inplace_u32(vuint32m1_t a, vuint32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SUB]]
//
vuint64m1_t sub_inplace_u64(vuint64m1_t a, vuint64m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[SUB]]
//
vfloat16m1_t sub_inplace_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[SUB]]
//
vfloat32m1_t sub_inplace_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_inplace_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[SUB]]
//
vfloat64m1_t sub_inplace_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SUB]]
//
vint8m1_t sub_scalar_i8(vint8m1_t a, int8_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SUB]]
//
vint16m1_t sub_scalar_i16(vint16m1_t a, int16_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vint32m1_t sub_scalar_i32(vint32m1_t a, int32_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SUB]]
//
vint64m1_t sub_scalar_i64(vint64m1_t a, int64_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SUB]]
//
vuint8m1_t sub_scalar_u8(vuint8m1_t a, uint8_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SUB]]
//
vuint16m1_t sub_scalar_u16(vuint16m1_t a, uint16_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SUB]]
//
vuint32m1_t sub_scalar_u32(vuint32m1_t a, uint32_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = sub <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SUB]]
//
vuint64m1_t sub_scalar_u64(vuint64m1_t a, uint64_t b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x half> poison, half [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x half> [[SPLAT_SPLATINSERT]], <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 4 x half> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[SUB]]
//
vfloat16m1_t sub_scalar_f16(vfloat16m1_t a, _Float16 b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x float> poison, float [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x float> [[SPLAT_SPLATINSERT]], <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 2 x float> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[SUB]]
//
vfloat32m1_t sub_scalar_f32(vfloat32m1_t a, float b) {
  return a - b;
}

// CHECK-LABEL: @sub_scalar_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x double> poison, double [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x double> [[SPLAT_SPLATINSERT]], <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SUB:%.*]] = fsub <vscale x 1 x double> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[SUB]]
//
vfloat64m1_t sub_scalar_f64(vfloat64m1_t a, double b) {
  return a - b;
}

// MULTIPLICATION

// CHECK-LABEL: @mul_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[MUL]]
//
vint8m1_t mul_i8(vint8m1_t a, vint8m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[MUL]]
//
vint16m1_t mul_i16(vint16m1_t a, vint16m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vint32m1_t mul_i32(vint32m1_t a, vint32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[MUL]]
//
vint64m1_t mul_i64(vint64m1_t a, vint64m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[MUL]]
//
vuint8m1_t mul_u8(vuint8m1_t a, vuint8m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[MUL]]
//
vuint16m1_t mul_u16(vuint16m1_t a, vuint16m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vuint32m1_t mul_u32(vuint32m1_t a, vuint32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[MUL]]
//
vuint64m1_t mul_u64(vuint64m1_t a, vuint64m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[MUL]]
//
vfloat16m1_t mul_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[MUL]]
//
vfloat32m1_t mul_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[MUL]]
//
vfloat64m1_t mul_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[MUL]]
//
vint8m1_t mul_inplace_i8(vint8m1_t a, vint8m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[MUL]]
//
vint16m1_t mul_inplace_i16(vint16m1_t a, vint16m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vint32m1_t mul_inplace_i32(vint32m1_t a, vint32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[MUL]]
//
vint64m1_t mul_inplace_i64(vint64m1_t a, vint64m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[MUL]]
//
vuint8m1_t mul_inplace_u8(vuint8m1_t a, vuint8m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[MUL]]
//
vuint16m1_t mul_inplace_u16(vuint16m1_t a, vuint16m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vuint32m1_t mul_inplace_u32(vuint32m1_t a, vuint32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[MUL]]
//
vuint64m1_t mul_inplace_u64(vuint64m1_t a, vuint64m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[MUL]]
//
vfloat16m1_t mul_inplace_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[MUL]]
//
vfloat32m1_t mul_inplace_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_inplace_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[MUL]]
//
vfloat64m1_t mul_inplace_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[MUL]]
//
vint8m1_t mul_scalar_i8(vint8m1_t a, int8_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[MUL]]
//
vint16m1_t mul_scalar_i16(vint16m1_t a, int16_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vint32m1_t mul_scalar_i32(vint32m1_t a, int32_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[MUL]]
//
vint64m1_t mul_scalar_i64(vint64m1_t a, int64_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[MUL]]
//
vuint8m1_t mul_scalar_u8(vuint8m1_t a, uint8_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[MUL]]
//
vuint16m1_t mul_scalar_u16(vuint16m1_t a, uint16_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[MUL]]
//
vuint32m1_t mul_scalar_u32(vuint32m1_t a, uint32_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = mul <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[MUL]]
//
vuint64m1_t mul_scalar_u64(vuint64m1_t a, uint64_t b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x half> poison, half [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x half> [[SPLAT_SPLATINSERT]], <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 4 x half> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[MUL]]
//
vfloat16m1_t mul_scalar_f16(vfloat16m1_t a, _Float16 b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x float> poison, float [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x float> [[SPLAT_SPLATINSERT]], <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 2 x float> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[MUL]]
//
vfloat32m1_t mul_scalar_f32(vfloat32m1_t a, float b) {
  return a * b;
}

// CHECK-LABEL: @mul_scalar_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x double> poison, double [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x double> [[SPLAT_SPLATINSERT]], <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[MUL:%.*]] = fmul <vscale x 1 x double> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[MUL]]
//
vfloat64m1_t mul_scalar_f64(vfloat64m1_t a, double b) {
  return a * b;
}

// DIVISION

// CHECK-LABEL: @div_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[DIV]]
//
vint8m1_t div_i8(vint8m1_t a, vint8m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[DIV]]
//
vint16m1_t div_i16(vint16m1_t a, vint16m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vint32m1_t div_i32(vint32m1_t a, vint32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vint64m1_t div_i64(vint64m1_t a, vint64m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[DIV]]
//
vuint8m1_t div_u8(vuint8m1_t a, vuint8m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[DIV]]
//
vuint16m1_t div_u16(vuint16m1_t a, vuint16m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vuint32m1_t div_u32(vuint32m1_t a, vuint32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vuint64m1_t div_u64(vuint64m1_t a, vuint64m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[DIV]]
//
vfloat16m1_t div_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[DIV]]
//
vfloat32m1_t div_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[DIV]]
//
vfloat64m1_t div_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[DIV]]
//
vint8m1_t div_inplace_i8(vint8m1_t a, vint8m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[DIV]]
//
vint16m1_t div_inplace_i16(vint16m1_t a, vint16m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vint32m1_t div_inplace_i32(vint32m1_t a, vint32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vint64m1_t div_inplace_i64(vint64m1_t a, vint64m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[DIV]]
//
vuint8m1_t div_inplace_u8(vuint8m1_t a, vuint8m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[DIV]]
//
vuint16m1_t div_inplace_u16(vuint16m1_t a, vuint16m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vuint32m1_t div_inplace_u32(vuint32m1_t a, vuint32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vuint64m1_t div_inplace_u64(vuint64m1_t a, vuint64m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 4 x half> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[DIV]]
//
vfloat16m1_t div_inplace_f16(vfloat16m1_t a, vfloat16m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 2 x float> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[DIV]]
//
vfloat32m1_t div_inplace_f32(vfloat32m1_t a, vfloat32m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_inplace_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 1 x double> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[DIV]]
//
vfloat64m1_t div_inplace_f64(vfloat64m1_t a, vfloat64m1_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[DIV]]
//
vint8m1_t div_scalar_i8(vint8m1_t a, int8_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[DIV]]
//
vint16m1_t div_scalar_i16(vint16m1_t a, int16_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vint32m1_t div_scalar_i32(vint32m1_t a, int32_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vint64m1_t div_scalar_i64(vint64m1_t a, int64_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[DIV]]
//
vuint8m1_t div_scalar_u8(vuint8m1_t a, uint8_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[DIV]]
//
vuint16m1_t div_scalar_u16(vuint16m1_t a, uint16_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[DIV]]
//
vuint32m1_t div_scalar_u32(vuint32m1_t a, uint32_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = sdiv <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[DIV]]
//
vuint64m1_t div_scalar_u64(vuint64m1_t a, uint64_t b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_f16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x half> poison, half [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x half> [[SPLAT_SPLATINSERT]], <vscale x 4 x half> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 4 x half> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x half> [[DIV]]
//
vfloat16m1_t div_scalar_f16(vfloat16m1_t a, _Float16 b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_f32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x float> poison, float [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x float> [[SPLAT_SPLATINSERT]], <vscale x 2 x float> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 2 x float> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x float> [[DIV]]
//
vfloat32m1_t div_scalar_f32(vfloat32m1_t a, float b) {
  return a / b;
}

// CHECK-LABEL: @div_scalar_f64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x double> poison, double [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x double> [[SPLAT_SPLATINSERT]], <vscale x 1 x double> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[DIV:%.*]] = fdiv <vscale x 1 x double> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x double> [[DIV]]
//
vfloat64m1_t div_scalar_f64(vfloat64m1_t a, double b) {
  return a / b;
}

// REMAINDER

// CHECK-LABEL: @rem_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[REM]]
//
vint8m1_t rem_i8(vint8m1_t a, vint8m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[REM]]
//
vint16m1_t rem_i16(vint16m1_t a, vint16m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vint32m1_t rem_i32(vint32m1_t a, vint32m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[REM]]
//
vint64m1_t rem_i64(vint64m1_t a, vint64m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[REM]]
//
vuint8m1_t rem_u8(vuint8m1_t a, vuint8m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[REM]]
//
vuint16m1_t rem_u16(vuint16m1_t a, vuint16m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vuint32m1_t rem_u32(vuint32m1_t a, vuint32m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[REM]]
//
vuint64m1_t rem_u64(vuint64m1_t a, vuint64m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[REM]]
//
vint8m1_t rem_inplace_i8(vint8m1_t a, vint8m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[REM]]
//
vint16m1_t rem_inplace_i16(vint16m1_t a, vint16m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vint32m1_t rem_inplace_i32(vint32m1_t a, vint32m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[REM]]
//
vint64m1_t rem_inplace_i64(vint64m1_t a, vint64m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[REM]]
//
vuint8m1_t rem_inplace_u8(vuint8m1_t a, vuint8m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[REM]]
//
vuint16m1_t rem_inplace_u16(vuint16m1_t a, vuint16m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vuint32m1_t rem_inplace_u32(vuint32m1_t a, vuint32m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_inplace_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[REM]]
//
vuint64m1_t rem_inplace_u64(vuint64m1_t a, vuint64m1_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[REM]]
//
vint8m1_t rem_scalar_i8(vint8m1_t a, int8_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[REM]]
//
vint16m1_t rem_scalar_i16(vint16m1_t a, int16_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vint32m1_t rem_scalar_i32(vint32m1_t a, int32_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[REM]]
//
vint64m1_t rem_scalar_i64(vint64m1_t a, int64_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[REM]]
//
vuint8m1_t rem_scalar_u8(vuint8m1_t a, uint8_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[REM]]
//
vuint16m1_t rem_scalar_u16(vuint16m1_t a, uint16_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[REM]]
//
vuint32m1_t rem_scalar_u32(vuint32m1_t a, uint32_t b) {
  return a % b;
}

// CHECK-LABEL: @rem_scalar_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[REM:%.*]] = srem <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[REM]]
//
vuint64m1_t rem_scalar_u64(vuint64m1_t a, uint64_t b) {
  return a % b;
}
