// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py
// RUN: %clang_cc1 -triple riscv64-none-linux-gnu -target-feature +zve64d \
// RUN: -target-feature +f -target-feature +d -disable-O0-optnone \
// RUN: -mvscale-min=4 -mvscale-max=4 -emit-llvm -o - %s | \
// RUN: opt -S -passes=sroa | FileCheck %s

// REQUIRES: riscv-registered-target

#include <riscv_vector.h>

// CHECK-LABEL: @lshift_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHL]]
//
vint8m1_t lshift_i8(vint8m1_t a, vint8m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_i8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHR]]
//
vint8m1_t rshift_i8(vint8m1_t a, vint8m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHL]]
//
vuint8m1_t lshift_u8(vuint8m1_t a, vuint8m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_u8(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 8 x i8> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHR]]
//
vuint8m1_t rshift_u8(vuint8m1_t a, vuint8m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHL]]
//
vint16m1_t lshift_i16(vint16m1_t a, vint16m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_i16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHR]]
//
vint16m1_t rshift_i16(vint16m1_t a, vint16m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHL]]
//
vuint16m1_t lshift_u16(vuint16m1_t a, vuint16m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_u16(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 4 x i16> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHR]]
//
vuint16m1_t rshift_u16(vuint16m1_t a, vuint16m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHL]]
//
vint32m1_t lshift_i32(vint32m1_t a, vint32m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_i32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHR]]
//
vint32m1_t rshift_i32(vint32m1_t a, vint32m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHL]]
//
vuint32m1_t lshift_u32(vuint32m1_t a, vuint32m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_u32(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 2 x i32> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHR]]
//
vuint32m1_t rshift_u32(vuint32m1_t a, vuint32m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHL]]
//
vint64m1_t lshift_i64(vint64m1_t a, vint64m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_i64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHR]]
//
vint64m1_t rshift_i64(vint64m1_t a, vint64m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHL]]
//
vuint64m1_t lshift_u64(vuint64m1_t a, vuint64m1_t b) {
  return a << b;
}

// CHECK-LABEL: @rshift_u64(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 1 x i64> [[A:%.*]], [[B:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHR]]
//
vuint64m1_t rshift_u64(vuint64m1_t a, vuint64m1_t b) {
  return a >> b;
}

// CHECK-LABEL: @lshift_i8_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHL]]
//
vint8m1_t lshift_i8_rsplat(vint8m1_t a, int8_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_i8_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 8 x i8> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHL]]
//
vint8m1_t lshift_i8_lsplat(vint8m1_t a, int8_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_i8_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHR]]
//
vint8m1_t rshift_i8_rsplat(vint8m1_t a, int8_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_i8_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 8 x i8> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHR]]
//
vint8m1_t rshift_i8_lsplat(vint8m1_t a, int8_t b) {
  return b >> a;
}

// CHECK-LABEL: @lshift_u8_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHL]]
//
vuint8m1_t lshift_u8_rsplat(vuint8m1_t a, uint8_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_u8_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 8 x i8> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHL]]
//
vuint8m1_t lshift_u8_lsplat(vuint8m1_t a, uint8_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_u8_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 8 x i8> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHR]]
//
vuint8m1_t rshift_u8_rsplat(vuint8m1_t a, uint8_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_u8_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 8 x i8> poison, i8 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 8 x i8> [[SPLAT_SPLATINSERT]], <vscale x 8 x i8> poison, <vscale x 8 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 8 x i8> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 8 x i8> [[SHR]]
//
vuint8m1_t rshift_u8_lsplat(vuint8m1_t a, uint8_t b) {
  return b >> a;
}

// CHECK-LABEL: @lshift_i16_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHL]]
//
vint16m1_t lshift_i16_rsplat(vint16m1_t a, int16_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_i16_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 4 x i16> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHL]]
//
vint16m1_t lshift_i16_lsplat(vint16m1_t a, int16_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_i16_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHR]]
//
vint16m1_t rshift_i16_rsplat(vint16m1_t a, int16_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_i16_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 4 x i16> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHR]]
//
vint16m1_t rshift_i16_lsplat(vint16m1_t a, int16_t b) {
  return b >> a;
}

// CHECK-LABEL: @lshift_u16_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHL]]
//
vuint16m1_t lshift_u16_rsplat(vuint16m1_t a, uint16_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_u16_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 4 x i16> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHL]]
//
vuint16m1_t lshift_u16_lsplat(vuint16m1_t a, uint16_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_u16_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 4 x i16> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHR]]
//
vuint16m1_t rshift_u16_rsplat(vuint16m1_t a, uint16_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_u16_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i16> poison, i16 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 4 x i16> [[SPLAT_SPLATINSERT]], <vscale x 4 x i16> poison, <vscale x 4 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 4 x i16> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 4 x i16> [[SHR]]
//
vuint16m1_t rshift_u16_lsplat(vuint16m1_t a, uint16_t b) {
  return b >> a;
}

// CHECK-LABEL: @lshift_i32_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHL]]
//
vint32m1_t lshift_i32_rsplat(vint32m1_t a, int32_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_i32_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 2 x i32> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHL]]
//
vint32m1_t lshift_i32_lsplat(vint32m1_t a, int32_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_i32_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHR]]
//
vint32m1_t rshift_i32_rsplat(vint32m1_t a, int32_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_i32_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 2 x i32> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHR]]
//
vint32m1_t rshift_i32_lsplat(vint32m1_t a, int32_t b) {
  return b >> a;
}

// CHECK-LABEL: @lshift_u32_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHL]]
//
vuint32m1_t lshift_u32_rsplat(vuint32m1_t a, uint32_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_u32_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 2 x i32> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHL]]
//
vuint32m1_t lshift_u32_lsplat(vuint32m1_t a, uint32_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_u32_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 2 x i32> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHR]]
//
vuint32m1_t rshift_u32_rsplat(vuint32m1_t a, uint32_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_u32_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 2 x i32> poison, i32 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 2 x i32> [[SPLAT_SPLATINSERT]], <vscale x 2 x i32> poison, <vscale x 2 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 2 x i32> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 2 x i32> [[SHR]]
//
vuint32m1_t rshift_u32_lsplat(vuint32m1_t a, uint32_t b) {
  return b >> a;
}

// CHECK-LABEL: @lshift_i64_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHL]]
//
vint64m1_t lshift_i64_rsplat(vint64m1_t a, int64_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_i64_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 1 x i64> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHL]]
//
vint64m1_t lshift_i64_lsplat(vint64m1_t a, int64_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_i64_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHR]]
//
vint64m1_t rshift_i64_rsplat(vint64m1_t a, int64_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_i64_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 1 x i64> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHR]]
//
vint64m1_t rshift_i64_lsplat(vint64m1_t a, int64_t b) {
  return b >> a;
}

// CHECK-LABEL: @lshift_u64_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHL]]
//
vuint64m1_t lshift_u64_rsplat(vuint64m1_t a, uint64_t b) {
  return a << b;
}

// CHECK-LABEL: @lshift_u64_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHL:%.*]] = shl <vscale x 1 x i64> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHL]]
//
vuint64m1_t lshift_u64_lsplat(vuint64m1_t a, uint64_t b) {
  return b << a;
}

// CHECK-LABEL: @rshift_u64_rsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 1 x i64> [[A:%.*]], [[SPLAT_SPLAT]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHR]]
//
vuint64m1_t rshift_u64_rsplat(vuint64m1_t a, uint64_t b) {
  return a >> b;
}

// CHECK-LABEL: @rshift_u64_lsplat(
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[SPLAT_SPLATINSERT:%.*]] = insertelement <vscale x 1 x i64> poison, i64 [[B:%.*]], i64 0
// CHECK-NEXT:    [[SPLAT_SPLAT:%.*]] = shufflevector <vscale x 1 x i64> [[SPLAT_SPLATINSERT]], <vscale x 1 x i64> poison, <vscale x 1 x i32> zeroinitializer
// CHECK-NEXT:    [[SHR:%.*]] = ashr <vscale x 1 x i64> [[SPLAT_SPLAT]], [[A:%.*]]
// CHECK-NEXT:    ret <vscale x 1 x i64> [[SHR]]
//
vuint64m1_t rshift_u64_lsplat(vuint64m1_t a, uint64_t b) {
  return b >> a;
}
