// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -triple aarch64_be-apple-darwin -emit-llvm -o - -O1 %s | \
// RUN:     FileCheck -check-prefixes=CHECK %s
//
// Check that TBAA metadata for structs containing bitfields is
// consistent between big and little endian layouts.

struct NamedBitfields {
  int f1 : 8;
  int f2 : 8;
  unsigned f3 : 1;
  unsigned f4 : 15;
  int f5;
  double f6;
};

// CHECK-LABEL: define dso_local void @_Z4copyP14NamedBitfieldsS0_(
// CHECK-SAME: ptr noundef writeonly captures(none) initializes((0, 16)) [[A1:%.*]], ptr noundef readonly captures(none) [[A2:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(16) [[A1]], ptr noundef nonnull align 8 dereferenceable(16) [[A2]], i64 16, i1 false), !tbaa.struct [[TBAA_STRUCT5:![0-9]+]]
// CHECK-NEXT:    ret void
//
void copy(NamedBitfields *a1, NamedBitfields *a2) {
  *a1 = *a2;
}

//.
// CHECK: [[META2:![0-9]+]] = !{!"int", [[META3:![0-9]+]], i64 0}
// CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
// CHECK: [[META4]] = !{!"Simple C++ TBAA"}
// CHECK: [[TBAA_STRUCT5]] = !{i64 0, i64 4, [[META6:![0-9]+]], i64 4, i64 4, [[META7:![0-9]+]], i64 8, i64 8, [[META10:![0-9]+]]}
// CHECK: [[META6]] = !{[[META3]], [[META3]], i64 0}
// CHECK: [[META7]] = !{[[META8:![0-9]+]], [[META2]], i64 4}
// CHECK: [[META8]] = !{!"_ZTS14NamedBitfields", [[META2]], i64 0, [[META2]], i64 1, [[META2]], i64 2, [[META2]], i64 2, [[META2]], i64 4, [[META9:![0-9]+]], i64 8}
// CHECK: [[META9]] = !{!"double", [[META3]], i64 0}
// CHECK: [[META10]] = !{[[META8]], [[META9]], i64 8}
//.
