// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 2
// RUN: %clang_cc1 -triple=x86_64-unknown-linux-gnu -emit-llvm -O2 -o - %s | FileCheck %s

typedef struct F {
  int a : 2;
  int b : 2;
  int c : 28;
} F;

// CHECK-LABEL: define dso_local void @Write
// CHECK-SAME: (ptr noundef [[F:%.*]], i32 [[E_COERCE:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    store volatile i32 [[E_COERCE]], ptr [[F]], align 4, !tbaa.struct [[TBAA_STRUCT2:![0-9]+]]
// CHECK-NEXT:    ret void
//
void Write(F volatile *f, F e) {
  *f = e;
}

// CHECK-LABEL: define dso_local i32 @Read
// CHECK-SAME: (ptr noundef [[F:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[RETVAL_SROA_0_0_COPYLOAD:%.*]] = load volatile i32, ptr [[F]], align 4, !tbaa.struct [[TBAA_STRUCT2]]
// CHECK-NEXT:    ret i32 [[RETVAL_SROA_0_0_COPYLOAD]]
//
F Read(F volatile *f) {
  return *f;
}

// CHECK-LABEL: define dso_local void @Init
// CHECK-SAME: (ptr noundef [[F:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[BF_VALUE:%.*]] = and i32 [[A]], 3
// CHECK-NEXT:    [[BF_VALUE2:%.*]] = shl i32 [[B]], 2
// CHECK-NEXT:    [[BF_SHL:%.*]] = and i32 [[BF_VALUE2]], 12
// CHECK-NEXT:    [[BF_SET4:%.*]] = or i32 [[BF_SHL]], [[BF_VALUE]]
// CHECK-NEXT:    store volatile i32 [[BF_SET4]], ptr [[F]], align 4, !tbaa.struct [[TBAA_STRUCT2]]
// CHECK-NEXT:    ret void
//
void Init(F volatile *f, int a, int b) {
  *f = (F){.a = a, .b = b, .c = 0};
}

// CHECK-LABEL: define dso_local void @Set
// CHECK-SAME: (ptr noundef [[F:%.*]], i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[TMP_SROA_0_0_COPYLOAD:%.*]] = load volatile i32, ptr [[F]], align 4, !tbaa.struct [[TBAA_STRUCT2]]
// CHECK-NEXT:    [[BF_VALUE:%.*]] = and i32 [[A]], 3
// CHECK-NEXT:    [[BF_CLEAR:%.*]] = and i32 [[TMP_SROA_0_0_COPYLOAD]], -16
// CHECK-NEXT:    [[BF_VALUE2:%.*]] = shl i32 [[B]], 2
// CHECK-NEXT:    [[BF_SHL:%.*]] = and i32 [[BF_VALUE2]], 12
// CHECK-NEXT:    [[BF_SET:%.*]] = or i32 [[BF_SHL]], [[BF_VALUE]]
// CHECK-NEXT:    [[BF_SET4:%.*]] = or i32 [[BF_SET]], [[BF_CLEAR]]
// CHECK-NEXT:    store volatile i32 [[BF_SET4]], ptr [[F]], align 4, !tbaa.struct [[TBAA_STRUCT2]]
// CHECK-NEXT:    ret void
//
void Set(F volatile *f, int a, int b) {
  F tmp = *f;
  tmp.a = a;
  tmp.b = b;
  *f = tmp;
}
