// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-windows -fasync-exceptions -fcxx-exceptions -fexceptions -fms-extensions -x c++ -Wno-implicit-function-declaration -emit-llvm %s -o - | FileCheck %s
// Check that the both __try scopes containing a return statement are properly terminated.
[[noreturn]] void Exit();
volatile int *p{nullptr};

// CHECK-LABEL: define dso_local noundef i32 @main(
// CHECK-SAME: i32 noundef [[ARGC:%.*]], ptr noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__C_specific_handler {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[ARGC_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[__EXCEPTION_CODE:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[__EXCEPTION_CODE1:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[CLEANUP_DEST_SLOT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
// CHECK-NEXT:    store i32 [[ARGC]], ptr [[ARGC_ADDR]], align 4
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[CATCH_DISPATCH6:.*]]
// CHECK:       [[INVOKE_CONT]]:
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT2:.*]] unwind label %[[CATCH_DISPATCH:.*]]
// CHECK:       [[INVOKE_CONT2]]:
// CHECK-NEXT:    [[TMP1:%.*]] = load volatile i32, ptr [[ARGC_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP1]], 0
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[IF_END:.*]], label %[[IF_THEN:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    [[TMP2:%.*]] = load volatile ptr, ptr @"?p@@3PECHEC", align 8
// CHECK-NEXT:    store volatile i32 0, ptr [[TMP2]], align 4
// CHECK-NEXT:    br label %[[IF_END]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    [[TMP3:%.*]] = load volatile i32, ptr [[ARGC_ADDR]], align 4
// CHECK-NEXT:    store volatile i32 [[TMP3]], ptr [[RETVAL]], align 4
// CHECK-NEXT:    store volatile i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    invoke void @llvm.seh.try.end()
// CHECK-NEXT:            to label %[[INVOKE_CONT3:.*]] unwind label %[[CATCH_DISPATCH]]
// CHECK:       [[CATCH_DISPATCH]]:
// CHECK-NEXT:    [[TMP4:%.*]] = catchswitch within none [label %[[__EXCEPT:.*]]] unwind label %[[CATCH_DISPATCH6]]
// CHECK:       [[__EXCEPT]]:
// CHECK-NEXT:    [[TMP5:%.*]] = catchpad within [[TMP4]] [ptr null]
// CHECK-NEXT:    catchret from [[TMP5]] to label %[[__EXCEPT4:.*]]
// CHECK:       [[__EXCEPT4]]:
// CHECK-NEXT:    [[TMP6:%.*]] = call i32 @llvm.eh.exceptioncode(token [[TMP5]])
// CHECK-NEXT:    store volatile i32 [[TMP6]], ptr [[__EXCEPTION_CODE1]], align 4
// CHECK-NEXT:    br label %[[__TRY_CONT:.*]]
// CHECK:       [[__TRY_CONT]]:
// CHECK-NEXT:    store i32 0, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP:.*]]
// CHECK:       [[CLEANUP]]:
// CHECK-NEXT:    invoke void @llvm.seh.try.end()
// CHECK-NEXT:            to label %[[INVOKE_CONT5:.*]] unwind label %[[CATCH_DISPATCH6]]
// CHECK:       [[CATCH_DISPATCH6]]:
// CHECK-NEXT:    [[TMP7:%.*]] = catchswitch within none [label %[[__EXCEPT7:.*]]] unwind to caller
// CHECK:       [[__EXCEPT7]]:
// CHECK-NEXT:    [[TMP8:%.*]] = catchpad within [[TMP7]] [ptr null]
// CHECK-NEXT:    catchret from [[TMP8]] to label %[[__EXCEPT8:.*]]
// CHECK:       [[__EXCEPT8]]:
// CHECK-NEXT:    [[TMP9:%.*]] = call i32 @llvm.eh.exceptioncode(token [[TMP8]])
// CHECK-NEXT:    store i32 [[TMP9]], ptr [[__EXCEPTION_CODE]], align 4
// CHECK-NEXT:    br label %[[__TRY_CONT9:.*]]
// CHECK:       [[__TRY_CONT9]]:
// CHECK-NEXT:    call void @"?Exit@@YAXXZ"() #[[ATTR4:[0-9]+]]
// CHECK-NEXT:    unreachable
// CHECK:       [[INVOKE_CONT5]]:
// CHECK-NEXT:    [[CLEANUP_DEST:%.*]] = load i32, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    switch i32 [[CLEANUP_DEST]], label %[[UNREACHABLE:.*]] [
// CHECK-NEXT:      i32 0, label %[[CLEANUP_CONT:.*]]
// CHECK-NEXT:      i32 1, label %[[RETURN:.*]]
// CHECK-NEXT:    ]
// CHECK:       [[CLEANUP_CONT]]:
// CHECK-NEXT:    br label %[[__TRY_CONT9]]
// CHECK:       [[INVOKE_CONT3]]:
// CHECK-NEXT:    br label %[[CLEANUP]]
// CHECK:       [[RETURN]]:
// CHECK-NEXT:    [[TMP10:%.*]] = load i32, ptr [[RETVAL]], align 4
// CHECK-NEXT:    ret i32 [[TMP10]]
// CHECK:       [[UNREACHABLE]]:
// CHECK-NEXT:    unreachable
//
int main(int argc, char**) noexcept
{
  __try {
    __try {
      if (!argc) { *p = 0; }
      return argc;
    } __except(1) {}
  } __except(1) {}

  Exit();
  return 0;
}
