// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -O3 -triple x86_64-windows -fasync-exceptions -fcxx-exceptions -fexceptions -fms-extensions -x c++ -Wno-implicit-function-declaration -emit-llvm %s -o - | FileCheck %s
// Check that the try scope of ExitOnThrow is terminated upon inlining into main.
int AlwaysThrows(int);
[[noreturn]] void Exit();

int ExitOnThrow(int argc) noexcept
{
  try {
    if (!argc) { throw -1; }
    return argc;
  } catch (...) {
  }

  Exit();
  return 0;
}

// CHECK-LABEL: define dso_local noundef i32 @main(
// CHECK-SAME: i32 noundef [[ARGC:%.*]], ptr noundef readnone captures(none) [[TMP0:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] personality ptr @__CxxFrameHandler3 {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[TMP_I:%.*]] = alloca i32, align 4
// CHECK-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[TMP_I]])
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT_I:.*]] unwind label %[[CATCH_DISPATCH_I:.*]]
// CHECK:       [[INVOKE_CONT_I]]:
// CHECK-NEXT:    [[TOBOOL_NOT_I:%.*]] = icmp eq i32 [[ARGC]], 0
// CHECK-NEXT:    br i1 [[TOBOOL_NOT_I]], label %[[IF_THEN_I:.*]], label %[[IF_END_I:.*]]
// CHECK:       [[IF_THEN_I]]:
// CHECK-NEXT:    store i32 -1, ptr [[TMP_I]], align 4, !tbaa [[INT_TBAA7:![0-9]+]]
// CHECK-NEXT:    invoke void @_CxxThrowException(ptr nonnull [[TMP_I]], ptr nonnull @_TI1H) #[[ATTR6:[0-9]+]]
// CHECK-NEXT:            to label %[[UNREACHABLE_I:.*]] unwind label %[[CATCH_DISPATCH_I]]
// CHECK:       [[CATCH_DISPATCH_I]]:
// CHECK-NEXT:    [[TMP1:%.*]] = catchswitch within none [label %[[CATCH_I:.*]]] unwind to caller
// CHECK:       [[CATCH_I]]:
// CHECK-NEXT:    [[TMP2:%.*]] = catchpad within [[TMP1]] [ptr null, i32 0, ptr null]
// CHECK-NEXT:    catchret from [[TMP2]] to label %[[TRY_CONT_I:.*]]
// CHECK:       [[TRY_CONT_I]]:
// CHECK-NEXT:    call void @"?Exit@@YAXXZ"() #[[ATTR7:[0-9]+]]
// CHECK-NEXT:    unreachable
// CHECK:       [[IF_END_I]]:
// CHECK-NEXT:    invoke void @llvm.seh.try.end()
// CHECK-NEXT:            to label %"?ExitOnThrow@@YAHH@Z.exit" unwind label %[[CATCH_DISPATCH_I]]
// CHECK:       [[UNREACHABLE_I]]:
// CHECK-NEXT:    unreachable
// CHECK:       "?ExitOnThrow@@YAHH@Z.exit":
// CHECK-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[TMP_I]])
// CHECK-NEXT:    [[CALL1:%.*]] = tail call noundef i32 @"?AlwaysThrows@@YAHH@Z"(i32 noundef [[ARGC]])
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[CALL1]], [[ARGC]]
// CHECK-NEXT:    ret i32 [[ADD]]
//
int main(int argc, char**)
{
  auto data = ExitOnThrow(argc);
  return data + AlwaysThrows(data);
}
//.
// CHECK: [[INT_TBAA7]] = !{[[META8:![0-9]+]], [[META8]], i64 0}
// CHECK: [[META8]] = !{!"int", [[META9:![0-9]+]], i64 0}
// CHECK: [[META9]] = !{!"omnipotent char", [[META10:![0-9]+]], i64 0}
// CHECK: [[META10]] = !{!"Simple C++ TBAA"}
//.
