// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 6
// RUN: %clang_cc1 -triple x86_64-windows -fasync-exceptions -fcxx-exceptions -fexceptions -fms-extensions -x c++ -Wno-implicit-function-declaration -emit-llvm %s -o - | FileCheck %s
// Check that both try scopes containing a return statement are properly terminated.
void DoSth();
[[noreturn]] void Exit();

// CHECK-LABEL: define dso_local noundef i32 @main(
// CHECK-SAME: i32 noundef [[ARGC:%.*]], ptr noundef [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] personality ptr @__CxxFrameHandler3 {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[DOTADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    [[ARGC_ADDR:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[TMP:%.*]] = alloca i32, align 4
// CHECK-NEXT:    [[CLEANUP_DEST_SLOT:%.*]] = alloca i32, align 4
// CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-NEXT:    store ptr [[TMP0]], ptr [[DOTADDR]], align 8
// CHECK-NEXT:    store i32 [[ARGC]], ptr [[ARGC_ADDR]], align 4
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT:.*]] unwind label %[[CATCH_DISPATCH6:.*]]
// CHECK:       [[INVOKE_CONT]]:
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT1:.*]] unwind label %[[CATCH_DISPATCH:.*]]
// CHECK:       [[INVOKE_CONT1]]:
// CHECK-NEXT:    invoke void @"?DoSth@@YAXXZ"()
// CHECK-NEXT:            to label %[[INVOKE_CONT2:.*]] unwind label %[[CATCH_DISPATCH]]
// CHECK:       [[INVOKE_CONT2]]:
// CHECK-NEXT:    invoke void @llvm.seh.scope.end()
// CHECK-NEXT:            to label %[[INVOKE_CONT3:.*]] unwind label %[[CATCH_DISPATCH]]
// CHECK:       [[CATCH_DISPATCH]]:
// CHECK-NEXT:    [[TMP1:%.*]] = catchswitch within none [label %[[CATCH:.*]]] unwind label %[[CATCH_DISPATCH6]]
// CHECK:       [[CATCH]]:
// CHECK-NEXT:    [[TMP2:%.*]] = catchpad within [[TMP1]] [ptr null, i32 0, ptr null]
// CHECK-NEXT:    invoke void @llvm.seh.scope.end() [ "funclet"(token [[TMP2]]) ]
// CHECK-NEXT:            to label %[[INVOKE_CONT4:.*]] unwind label %[[CATCH_DISPATCH6]]
// CHECK:       [[INVOKE_CONT4]]:
// CHECK-NEXT:    catchret from [[TMP2]] to label %[[CATCHRET_DEST:.*]]
// CHECK:       [[CATCHRET_DEST]]:
// CHECK-NEXT:    br label %[[TRY_CONT:.*]]
// CHECK:       [[TRY_CONT]]:
// CHECK-NEXT:    invoke void @llvm.seh.scope.end()
// CHECK-NEXT:            to label %[[INVOKE_CONT5:.*]] unwind label %[[CATCH_DISPATCH6]]
// CHECK:       [[CATCH_DISPATCH6]]:
// CHECK-NEXT:    [[TMP3:%.*]] = catchswitch within none [label %[[CATCH7:.*]]] unwind to caller
// CHECK:       [[CATCH7]]:
// CHECK-NEXT:    [[TMP4:%.*]] = catchpad within [[TMP3]] [ptr null, i32 0, ptr null]
// CHECK-NEXT:    catchret from [[TMP4]] to label %[[CATCHRET_DEST8:.*]]
// CHECK:       [[CATCHRET_DEST8]]:
// CHECK-NEXT:    br label %[[TRY_CONT9:.*]]
// CHECK:       [[TRY_CONT9]]:
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT10:.*]] unwind label %[[CATCH_DISPATCH19:.*]]
// CHECK:       [[INVOKE_CONT10]]:
// CHECK-NEXT:    invoke void @llvm.seh.try.begin()
// CHECK-NEXT:            to label %[[INVOKE_CONT11:.*]] unwind label %[[CATCH_DISPATCH13:.*]]
// CHECK:       [[INVOKE_CONT11]]:
// CHECK-NEXT:    [[TMP5:%.*]] = load i32, ptr [[ARGC_ADDR]], align 4
// CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[TMP5]], 0
// CHECK-NEXT:    br i1 [[TOBOOL]], label %[[IF_END:.*]], label %[[IF_THEN:.*]]
// CHECK:       [[IF_THEN]]:
// CHECK-NEXT:    store i32 -1, ptr [[TMP]], align 4
// CHECK-NEXT:    invoke void @_CxxThrowException(ptr [[TMP]], ptr @_TI1H) #[[ATTR5:[0-9]+]]
// CHECK-NEXT:            to label %[[UNREACHABLE:.*]] unwind label %[[CATCH_DISPATCH13]]
// CHECK:       [[INVOKE_CONT5]]:
// CHECK-NEXT:    br label %[[TRY_CONT9]]
// CHECK:       [[INVOKE_CONT3]]:
// CHECK-NEXT:    br label %[[TRY_CONT]]
// CHECK:       [[IF_END]]:
// CHECK-NEXT:    [[TMP6:%.*]] = load i32, ptr [[ARGC_ADDR]], align 4
// CHECK-NEXT:    store i32 [[TMP6]], ptr [[RETVAL]], align 4
// CHECK-NEXT:    store i32 1, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    invoke void @llvm.seh.scope.end()
// CHECK-NEXT:            to label %[[INVOKE_CONT12:.*]] unwind label %[[CATCH_DISPATCH13]]
// CHECK:       [[CATCH_DISPATCH13]]:
// CHECK-NEXT:    [[TMP7:%.*]] = catchswitch within none [label %[[CATCH14:.*]]] unwind label %[[CATCH_DISPATCH19]]
// CHECK:       [[CATCH14]]:
// CHECK-NEXT:    [[TMP8:%.*]] = catchpad within [[TMP7]] [ptr null, i32 0, ptr null]
// CHECK-NEXT:    invoke void @llvm.seh.scope.end() [ "funclet"(token [[TMP8]]) ]
// CHECK-NEXT:            to label %[[INVOKE_CONT15:.*]] unwind label %[[CATCH_DISPATCH19]]
// CHECK:       [[INVOKE_CONT15]]:
// CHECK-NEXT:    catchret from [[TMP8]] to label %[[CATCHRET_DEST16:.*]]
// CHECK:       [[CATCHRET_DEST16]]:
// CHECK-NEXT:    br label %[[TRY_CONT17:.*]]
// CHECK:       [[TRY_CONT17]]:
// CHECK-NEXT:    store i32 0, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    br label %[[CLEANUP:.*]]
// CHECK:       [[CLEANUP]]:
// CHECK-NEXT:    invoke void @llvm.seh.scope.end()
// CHECK-NEXT:            to label %[[INVOKE_CONT18:.*]] unwind label %[[CATCH_DISPATCH19]]
// CHECK:       [[CATCH_DISPATCH19]]:
// CHECK-NEXT:    [[TMP9:%.*]] = catchswitch within none [label %[[CATCH20:.*]]] unwind to caller
// CHECK:       [[CATCH20]]:
// CHECK-NEXT:    [[TMP10:%.*]] = catchpad within [[TMP9]] [ptr null, i32 0, ptr null]
// CHECK-NEXT:    catchret from [[TMP10]] to label %[[CATCHRET_DEST21:.*]]
// CHECK:       [[CATCHRET_DEST21]]:
// CHECK-NEXT:    br label %[[TRY_CONT22:.*]]
// CHECK:       [[TRY_CONT22]]:
// CHECK-NEXT:    call void @"?Exit@@YAXXZ"() #[[ATTR5]]
// CHECK-NEXT:    unreachable
// CHECK:       [[INVOKE_CONT18]]:
// CHECK-NEXT:    [[CLEANUP_DEST:%.*]] = load i32, ptr [[CLEANUP_DEST_SLOT]], align 4
// CHECK-NEXT:    switch i32 [[CLEANUP_DEST]], label %[[UNREACHABLE]] [
// CHECK-NEXT:      i32 0, label %[[CLEANUP_CONT:.*]]
// CHECK-NEXT:      i32 1, label %[[RETURN:.*]]
// CHECK-NEXT:    ]
// CHECK:       [[CLEANUP_CONT]]:
// CHECK-NEXT:    br label %[[TRY_CONT22]]
// CHECK:       [[INVOKE_CONT12]]:
// CHECK-NEXT:    br label %[[CLEANUP]]
// CHECK:       [[RETURN]]:
// CHECK-NEXT:    [[TMP11:%.*]] = load i32, ptr [[RETVAL]], align 4
// CHECK-NEXT:    ret i32 [[TMP11]]
// CHECK:       [[UNREACHABLE]]:
// CHECK-NEXT:    unreachable
//
int main(int argc, char**) noexcept
{
  try {
    try {
      DoSth();
    } catch(...) {}
  } catch(...) {}

  try {
    try {
      if (!argc) { throw -1; }
      return argc;
    } catch (...) {}
  } catch (...) {}

  Exit();
  return 0;
}
