; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 2
; RUN: opt -passes=indvars -S < %s | FileCheck %s

target triple = "amdgcn--amdpal"

define void @f(ptr addrspace(7) %arg) {
; CHECK-LABEL: define void @f
; CHECK-SAME: (ptr addrspace(7) [[ARG:%.*]]) {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr addrspace(7) [[ARG]], i32 8
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    br i1 false, label [[BB2:%.*]], label [[BB1]]
; CHECK:       bb2:
; CHECK-NEXT:    br label [[BB3:%.*]]
; CHECK:       bb3:
; CHECK-NEXT:    [[I4:%.*]] = load i32, ptr addrspace(7) [[SCEVGEP]], align 4
; CHECK-NEXT:    br label [[BB3]]
;
bb:
  br label %bb1
bb1:
  %i = getelementptr i32, ptr addrspace(7) %arg, i32 2
  br i1 false, label %bb2, label %bb1
bb2:
  br label %bb3
bb3:
  %i4 = load i32, ptr addrspace(7) %i, align 4
  br label %bb3
}

define void @f2(<2 x ptr addrspace(7)> %arg) {
; CHECK-LABEL: define void @f2
; CHECK-SAME: (<2 x ptr addrspace(7)> [[ARG:%.*]]) {
; CHECK-NEXT:  bb:
; CHECK-NEXT:    br label [[BB1:%.*]]
; CHECK:       bb1:
; CHECK-NEXT:    [[P:%.*]] = extractelement <2 x ptr addrspace(7)> [[ARG]], i32 0
; CHECK-NEXT:    [[I:%.*]] = getelementptr i32, ptr addrspace(7) [[P]], i32 2
; CHECK-NEXT:    br i1 false, label [[BB2:%.*]], label [[BB1]]
; CHECK:       bb2:
; CHECK-NEXT:    [[I_LCSSA:%.*]] = phi ptr addrspace(7) [ [[I]], [[BB1]] ]
; CHECK-NEXT:    br label [[BB3:%.*]]
; CHECK:       bb3:
; CHECK-NEXT:    [[I4:%.*]] = load i32, ptr addrspace(7) [[I_LCSSA]], align 4
; CHECK-NEXT:    br label [[BB3]]
;
bb:
  br label %bb1
bb1:
  %p = extractelement <2 x ptr addrspace(7)> %arg, i32 0
  %i = getelementptr i32, ptr addrspace(7) %p, i32 2
  br i1 false, label %bb2, label %bb1
bb2:
  br label %bb3
bb3:
  %i4 = load i32, ptr addrspace(7) %i, align 4
  br label %bb3
}
