// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --function-signature
// RUN: %clang_cc1 -triple ve-unknown-linux -O2 -emit-llvm -o - %s | FileCheck %s

// CHECK-LABEL: define {{[^@]+}}@test_bitint_17_add_unsigned
// CHECK-SAME: (i17 noundef zeroext [[A:%.*]], i17 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add i17 [[B]], [[A]]
// CHECK-NEXT:    ret i17 [[ADD]]
//
unsigned _BitInt(17) test_bitint_17_add_unsigned(unsigned _BitInt(17) a, unsigned _BitInt(17) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_17_add_signed
// CHECK-SAME: (i17 noundef signext [[A:%.*]], i17 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i17 [[B]], [[A]]
// CHECK-NEXT:    ret i17 [[ADD]]
//
signed _BitInt(17) test_bitint_17_add_signed(signed _BitInt(17) a, signed _BitInt(17) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_17_add_default
// CHECK-SAME: (i17 noundef signext [[A:%.*]], i17 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i17 [[B]], [[A]]
// CHECK-NEXT:    ret i17 [[ADD]]
//
_BitInt(17) test_bitint_17_add_default(_BitInt(17) a, _BitInt(17) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_32_add_unsigned
// CHECK-SAME: (i32 noundef zeroext [[A:%.*]], i32 noundef zeroext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add i32 [[B]], [[A]]
// CHECK-NEXT:    ret i32 [[ADD]]
//
unsigned _BitInt(32) test_bitint_32_add_unsigned(unsigned _BitInt(32) a, unsigned _BitInt(32) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_32_add_signed
// CHECK-SAME: (i32 noundef signext [[A:%.*]], i32 noundef signext [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i32 [[B]], [[A]]
// CHECK-NEXT:    ret i32 [[ADD]]
//
signed _BitInt(32) test_bitint_32_add_signed(signed _BitInt(32) a, signed _BitInt(32) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_65_add_unsigned
// CHECK-SAME: (i65 noundef [[A:%.*]], i65 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add i65 [[B]], [[A]]
// CHECK-NEXT:    ret i65 [[ADD]]
//
unsigned _BitInt(65) test_bitint_65_add_unsigned(unsigned _BitInt(65) a, unsigned _BitInt(65) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_65_add_signed
// CHECK-SAME: (i65 noundef [[A:%.*]], i65 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i65 [[B]], [[A]]
// CHECK-NEXT:    ret i65 [[ADD]]
//
signed _BitInt(65) test_bitint_65_add_signed(signed _BitInt(65) a, signed _BitInt(65) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_77_add_unsigned
// CHECK-SAME: (i77 noundef [[A:%.*]], i77 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add i77 [[B]], [[A]]
// CHECK-NEXT:    ret i77 [[ADD]]
//
unsigned _BitInt(77) test_bitint_77_add_unsigned(unsigned _BitInt(77) a, unsigned _BitInt(77) b) {
    return a + b;
}

// CHECK-LABEL: define {{[^@]+}}@test_bitint_77_add_signed
// CHECK-SAME: (i77 noundef [[A:%.*]], i77 noundef [[B:%.*]]) local_unnamed_addr #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[ADD:%.*]] = add nsw i77 [[B]], [[A]]
// CHECK-NEXT:    ret i77 [[ADD]]
//
signed _BitInt(77) test_bitint_77_add_signed(signed _BitInt(77) a, signed _BitInt(77) b) {
    return a + b;
}
