// -*- C++ -*-
//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

_LIBCPP_MODULE_EXPORT namespace std {
  using std::sig_atomic_t _LIBCPP_USING_IF_EXISTS;

  // [support.signal], signal handlers
  using std::signal _LIBCPP_USING_IF_EXISTS;

  using std::raise _LIBCPP_USING_IF_EXISTS;

} // namespace std
